header_reader2.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <ctype.h>
#include <library/i_error.h>
#include <library/dynamic_symbol.h>
Data Structures
struct hparse_info_st
Defines
#define MLINE_SIZE 4001
Typedefs
typedef hparse_info_st Hparse_Info
Functions
void Hskip_to_endif (Hparse_Info *hinfo, char *source, int line)
int Hget_next_line (Hparse_Info *hinfo, char *ret_buf)
void Hparse_line (char *ptr, char *name, char *arg)
STRING_Symbol_Table * read_header_file (char *file_name, int print_warnings)
Define Documentation
#define MLINE_SIZE 4001
Definition at line 71 of file header_reader2.c.
Referenced by Hget_next_line(), Hskip_to_endif(), and read_header_file().
Typedef Documentation
typedef struct hparse_info_st
 Hparse_Info
Function Documentation
int Hget_next_line (Hparse_Info * hinfo, char * ret_buf)
Definition at line 260 of file header_reader2.c.
References hparse_info_st::comment_level, I_punt(), hparse_info_st::in, hparse_info_st::line, MLINE_SIZE, hparse_info_st::name, and NULL.
Referenced by Hskip_to_endif(), and read_header_file().
void Hparse_line (char * ptr, char * name, char * arg)
Definition at line 234 of file header_reader2.c.
Referenced by read_header_file().
void Hskip_to_endif (Hparse_Info * hinfo, char * source, int line)
Definition at line 207 of file header_reader2.c.
References hparse_info_st::endif_level, Hget_next_line(), I_punt(), and MLINE_SIZE.
Referenced by read_header_file().
STRING_Symbol_Table* read_header_file (char * file_name, int print_warnings)
Definition at line 91 of file header_reader2.c.
References hparse_info_st::comment_level, hparse_info_st::endif_level, Hget_next_line(), Hparse_line(), Hskip_to_endif(), I_punt(), hparse_info_st::in, hparse_info_st::line, MLINE_SIZE, name, hparse_info_st::name, NULL, STRING_add_symbol(), STRING_find_symbol(), STRING_find_symbol_data(), STRING_new_symbol_table(), and hparse_info_st::table.
Referenced by read_header_tables().