lmdes2_customizer.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <library/i_error.h>
#include <library/l_alloc_new.h>
#include <library/dynamic_symbol.h>
#include <library/heap.h>
#include <stdarg.h>
#include <time.h>
#include <sys/time.h>
#include <library/md.h>
Data Structures
struct Pointer_Mapping
struct Resource_Info
struct Pair_Node
struct ENTRY_Contents_Table
struct ENTRY_Contents_Node
Defines
#define SLOT_RESOURCE 0x00000001
#define DEBUG_OPTI 0
#define VERBOSE_OPTI 0
#define VERBOSE_STATS 0
#define MAX_IDENT_LEN (100+1)
Functions
STRING_Symbol_Table * read_header_file (char *file_name, int print_warnings)
void customize_md (MD *md)
int eliminate_redundant_new_entries_only (MD *md, char *section_name)
int CU_redundant_entries (MD_Entry *entry1, MD_Entry *entry2, char *ignore_field)
void print_generating_set (FILE *out, INT_Symbol_Table *generating_set, MD_Entry **unit_array, int committed)
void commit_usage (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource, int user, int time)
void print_table_trees (FILE *out, MD *md)
static void C_punt (MD *md, char *fmt,...)
void print_time_stamp (FILE *out)
void print_usage (char *fmt,...)
void read_command_line_parameters (int argc, char **arg_ptr)
int main (int argc, char **argv)
void read_header_tables (MD *md)
int find_header_value (MD *md, char *name, int *value)
void annotate_header_values (MD *md, char *section_name, char *field_name, char *prefix, int required)
void annotate_hash (MD *md, char *section_name)
void annotate_latency_class (MD *md, char *section_name, char *src_field_name, char *dest_field_name)
void convert_to_bit_representation (MD *md, char *src_section_name, char *src_field_name, char *value_section_name, char *value_field_name, char *dest_field_name)
void find_children (INT_Symbol_Table *child_table, MD_Entry *entry, MD_Field_Decl *field_decl)
void add_all_children_to_list (MD *md, char *section_name, char *field_name)
void convert_to_int_list (MD *md, char *src_section_name, char *src_field_name, char *value_section_name, char *value_field_name, char *dest_field_name)
void convert_to_int_list_all_targets (MD *md, char *src_section_name, char *src_field_name, char *value_field_name, char *dest_field_name)
void check_int_bounds (MD *md, char *section_name, char *field_name, int lower_bound, int upper_bound)
void check_proc_opcs (MD *md)
void check_table_option_count (MD *md)
void check_bidirectional_links (MD *md, char *section_name, char *field_name)
MD_Section * CU_find_section (MD *md, char *section_name)
MD_Field_Decl * CU_find_field_decl (MD_Section *section, char *field_name)
MD_Field * CU_find_field (MD_Entry *entry, MD_Field_Decl *field_decl)
MD_Field * CU_find_field_by_name (MD_Entry *entry, char *field_name)
void CU_get_unique_name (MD *md, MD_Entry *entry, char *base_name, char *new_name)
MD_Entry * CU_dup_entry (MD_Entry *orig_entry)
void CU_rename_entry (MD_Entry *entry, char *new_name)
void CU_add_link_at (MD_Field *field, int at_index, MD_Entry *new_link)
void CU_delete_link_at (MD_Field *field, int at_index)
MD_Entry * CU_dup_alt (MD_Entry *orig_alt)
MD_Entry * CU_dup_res_table (MD_Entry *orig_res_table)
MD_Entry * CU_dup_resource_usage (MD_Entry *orig_ru)
int CU_get_slot (MD_Entry *entry)
int CU_get_min_time (MD_Entry *entry)
int CU_overlapping_resource_usage (MD_Entry *entry1, MD_Entry *entry2)
int CU_make_res_table_orthogonal (MD_Entry *res_table)
void CU_consolidate_res_table_usages (MD_Entry *res_table)
int usage_cycle_compatable (MD_Entry *usage_entry, MD_Entry *option_entry)
int usage_resource_compatable (MD_Entry *usage_entry, MD_Entry *option_entry)
void distribute_usage (MD_Field *table_use_field, int index, MD_Entry *usage_entry)
void CU_distribute_unconditional_usages (MD_Entry *table_entry)
void CU_homogenize_table_options (MD_Entry *table_option)
void CU_homogenize_resource_usages (MD_Entry *ru_entry)
void CU_optimize_resource_usage_times (MD *md)
int CU_get_ru_time (MD_Entry *ru_entry)
int CU_num_table_uses (MD_Entry *option_entry)
void CU_order_use_fields (MD *md, int min_reorder)
void homogenize_reservation_tables (MD *md)
void check_for_unconditional_overlap (MD *md)
int assign_resource_map_locations (MD *md)
int usage_common_to_all_options (MD_Entry *option_entry, MD_Entry *ru_entry)
int option_usage_common_at_time (MD_Entry *option_entry, MD_Entry *usage_entry)
void remove_common_usage (MD_Entry *option_entry, MD_Entry *usage_entry)
void CU_coalesce_unconditional_usages (MD *md)
void optimize_resource_units (MD *md, int max_offset)
void free_link_table (INT_Symbol_Table *link_table)
INT_Symbol_Table * build_link_table (MD *md, MD_Section *target_section)
void free_remap_table (INT_Symbol_Table *remap_table)
INT_Symbol_Table * build_remap_table (MD_Section *section)
void add_remap_entry (INT_Symbol_Table *remap_table, MD_Entry *from_entry, MD_Entry *to_entry)
void free_referenced_table (INT_Symbol_Table *referenced_table)
INT_Symbol_Table * build_referenced_table (INT_Symbol_Table *link_table, int init_size)
int entry_referenced (INT_Symbol_Table *referenced_table, MD_Entry *test_entry)
int remove_unreferenced_entries (MD *md, char *section_name)
unsigned int CU_hash_string (char *string)
ENTRY_Contents_Table * ENTRY_new_contents_table (char *ignore_field, int size)
unsigned int ENTRY_hash_contents (MD_Entry *entry1, char *ignore_field)
void ENTRY_add_contents (ENTRY_Contents_Table *table, MD_Entry *entry)
MD_Entry * ENTRY_find_match (ENTRY_Contents_Table *table, MD_Entry *entry)
void ENTRY_free_nodes (ENTRY_Contents_Node *first_node)
void ENTRY_delete_contents_table (ENTRY_Contents_Table *table)
void CU_replace_references (INT_Symbol_Table *link_table, INT_Symbol_Table *remap_table)
int eliminate_redundant_entries (MD *md, char *section_name)
void remove_original_name (MD *md)
void rename_section_entries (MD *md, char *section_name, char *prefix)
int optimize_alt_lists (MD *md)
int do_classical_optimizations (MD *md)
int CU_count_section_entries (MD_Section *section)
int CU_count_entries (MD *md)
void check_slot_specification (MD *md)
void mark_resource_unit_slots (MD *md)
int CU_num_options (MD_Entry *entry)
int CU_max_usage_time (MD_Entry *entry)
void format_reservation_tables (MD *md)
int CU_parm_exists (MD *md, char *name)
void CU_set_string_parm (MD *md, char *name, char *string_value)
void CU_set_int_parm (MD *md, char *name, int value)
void expand_options (MD_Entry *dest_option, MD_Entry *src_option)
void expand_out_reservation_tables (MD *md)
void calc_forbidden_latencies (INT_Symbol_Table *forbidden_set, MD_Field *use1_field, MD_Field *use2_field)
void add_usage (Resource_Info *resource, int user, int time)
int usage_exists (Resource_Info *resource, int user, int time)
int is_forbidden (INT_Symbol_Table ***forbidden_matrix, int user1, int user2, int latency)
int is_compatable (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource, int new_user, int new_time)
void add_to_generating_set (INT_Symbol_Table ***forbidden_matrix, INT_Symbol_Table *set, int user1, int user2, int latency)
int resource_redundant (Resource_Info *resource1, Resource_Info *resource2)
void delete_resource (Resource_Info *resource)
INT_Symbol_Table * build_generating_set (MD *md, INT_Symbol_Table ***forbidden_matrix, MD_Entry **unit_array, int num_units)
void enumerate_pairs (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource)
int mark_covered (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource, int user, int time)
int is_usage_committed (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource, int user, int time)
int count_num_covered (INT_Symbol_Table ***forbidden_matrix, Resource_Info *resource, int user, int time)
void minimize_generating_set (INT_Symbol_Table *generating_set, INT_Symbol_Table ***forbidden_matrix, int num_units, MD_Entry **unit_array)
void free_generating_set (INT_Symbol_Table *generating_set)
void instantiate_generating_set (INT_Symbol_Table *generating_set, MD_Field **use_array, int num_units, MD_Section *usage_section)
void reduce_resource_units (MD *md)
int count_table_uses (MD *md, MD_Entry *table_entry)
double average_usage_checks (MD *md)
int calc_best_case_succeed (MD_Entry *alt_entry)
int calc_best_case_fail (MD_Entry *alt_entry)
int calc_worst_case_fail (MD_Entry *alt_entry)
int calc_memory_size (MD *md)
void print_static_stats (FILE *out, MD *md)
void print_ru_tree (FILE *out, MD_Entry *ru_entry)
void print_unit_tree (FILE *out, MD_Entry *unit_entry, int option_id)
void print_option_tree (FILE *out, MD_Entry *option_entry)
void print_and_or_tree (FILE *out, MD_Entry *table)
int CU_calc_max_field_size (MD *md, char *section_name, char *field_name)
int CU_calc_int_field_max_value (MD *md, char *section_name, char *field_name)
void CU_set_slot_parameters (MD *md)
void dump_md (char *file_name, MD *md)
Variables
char * program_name = NULL
char * input_file_name = NULL
char * output_file_name = NULL
int using_stdin = 0
char * output_mode = NULL
char * input_mode = NULL
int output_page_width = 80
int verbose = 0
int expand_tables = 0
int tree_opti = 1
int place_slots_first = 0
int static_stats = 0
int print_trees = 0
int resource_minimization = 1
int opti_level = 4
L_Alloc_Pool * ENTRY_Contents_Table_pool = NULL
L_Alloc_Pool * ENTRY_Contents_Node_pool = NULL
STRING_Symbol_Table * header_table_table = NULL
STRING_Symbol_Table * rename_table = NULL
int header_errors = 0
int customization_errors = 0
Define Documentation
#define DEBUG_OPTI 0
Definition at line 122 of file lmdes2_customizer.c.
Referenced by CU_coalesce_unconditional_usages(), optimize_alt_lists(), print_static_stats(), and remove_unreferenced_entries().
#define MAX_IDENT_LEN (100+1)
Definition at line 701 of file lmdes2_customizer.c.
Referenced by annotate_header_values().
#define SLOT_RESOURCE 0x00000001
Definition at line 84 of file lmdes2_customizer.c.
Referenced by add_to_generating_set(), build_generating_set(), and minimize_generating_set().
#define VERBOSE_OPTI 0
Definition at line 127 of file lmdes2_customizer.c.
#define VERBOSE_STATS 0
Definition at line 132 of file lmdes2_customizer.c.
Function Documentation
void add_all_children_to_list (MD * md, char * section_name, char * field_name)
Definition at line 1153 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, entry, find_children(), INT_Symbol_Table::head_symbol, INT_delete_symbol(), INT_delete_symbol_table(), INT_find_symbol(), INT_new_symbol_table(), MD_Field_Decl::kleene_starred_req, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_link, MD_LINK, MD_next_entry(), MD_set_link, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
void add_remap_entry (INT_Symbol_Table * remap_table, MD_Entry * from_entry, MD_Entry * to_entry)
Definition at line 4963 of file lmdes2_customizer.c.
References INT_Symbol::data, Pointer_Mapping::from, I_punt(), INT_add_symbol(), INT_find_symbol(), INT_Symbol::next_symbol, NULL, and Pointer_Mapping::to.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
void add_to_generating_set (INT_Symbol_Table *** forbidden_matrix, INT_Symbol_Table * set, int user1, int user2, int latency)
Definition at line 7189 of file lmdes2_customizer.c.
References add_usage(), C_punt(), INT_Symbol::data, Resource_Info::flags, INT_Symbol_Table::head_symbol, is_compatable(), Resource_Info::name, INT_Symbol::next_symbol, NULL, SLOT_RESOURCE, and usage_exists().
Referenced by build_generating_set().
void add_usage (Resource_Info * resource, int user, int time)
Definition at line 7067 of file lmdes2_customizer.c.
References INT_add_symbol(), INT_find_symbol(), INT_find_symbol_data(), INT_new_symbol_table(), Resource_Info::name, NULL, and Resource_Info::time_table.
Referenced by add_to_generating_set(), and build_generating_set().
void annotate_hash (MD * md, char * section_name)
Definition at line 857 of file lmdes2_customizer.c.
References C_punt(), entry, MD_Field::max_element_index, MD_delete_field_decl(), MD_find_field_decl, MD_find_section, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, and NULL.
Referenced by customize_md().
void annotate_header_values (MD * md, char * section_name, char * field_name, char * prefix, int required)
Definition at line 773 of file lmdes2_customizer.c.
References C_punt(), entry, find_header_value(), header_errors, MAX_IDENT_LEN, MD_delete_field_decl(), MD_find_field_decl, MD_find_section, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_OPTIONAL_FIELD, MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, and NULL.
Referenced by customize_md().
void annotate_latency_class (MD * md, char * section_name, char * src_field_name, char * dest_field_name)
Definition at line 905 of file lmdes2_customizer.c.
References C_punt(), MD_Field::max_element_index, MD_delete_field_decl(), MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_kleene_star_requirement(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, NULL, and MD_Entry::section.
Referenced by customize_md().
int assign_resource_map_locations (MD * md)
Definition at line 4292 of file lmdes2_customizer.c.
References CU_find_section(), MD_delete_field_decl(), MD_find_field_decl, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, and NULL.
Referenced by customize_md().
double average_usage_checks (MD * md)
Definition at line 8705 of file lmdes2_customizer.c.
References count_table_uses(), CU_find_field_by_name(), CU_find_section(), MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Entry::name, MD_Section::name, and MD_Entry::section.
Referenced by customize_md().
INT_Symbol_Table* build_generating_set (MD * md, INT_Symbol_Table *** forbidden_matrix, MD_Entry ** unit_array, int num_units)
Definition at line 7356 of file lmdes2_customizer.c.
References add_to_generating_set(), add_usage(), C_punt(), CU_find_field_decl(), CU_find_section(), INT_Symbol::data, delete_resource(), Resource_Info::flags, INT_Symbol_Table::head_symbol, INT_add_symbol(), INT_delete_symbol(), INT_find_symbol_data(), INT_new_symbol_table(), MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_int, MD_get_link, MD_next_entry(), Resource_Info::name, MD_Entry::name, INT_Symbol::next_symbol, NULL, print_generating_set(), Resource_Info::resource_entry, resource_redundant(), SLOT_RESOURCE, Resource_Info::time_table, and INT_Symbol::value.
Referenced by reduce_resource_units().
INT_Symbol_Table* build_link_table (MD * md, MD_Section * target_section)
Definition at line 4872 of file lmdes2_customizer.c.
References INT_add_symbol(), INT_new_symbol_table(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field_Decl::max_require_index, MD_first_field_decl(), MD_first_section(), MD_LINK, MD_next_field_decl(), MD_next_section(), NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by eliminate_redundant_entries(), eliminate_redundant_new_entries_only(), and remove_unreferenced_entries().
INT_Symbol_Table* build_referenced_table (INT_Symbol_Table * link_table, int init_size)
Definition at line 5022 of file lmdes2_customizer.c.
References INT_Symbol::data, MD_Field::element, INT_Symbol_Table::head_symbol, INT_add_symbol(), INT_find_symbol(), INT_new_symbol_table(), MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_link, MD_LINK, MD_next_entry(), INT_Symbol::next_symbol, NULL, MD_Field_Decl::section, and MD_Element::type.
Referenced by remove_unreferenced_entries().
INT_Symbol_Table* build_remap_table (MD_Section * section)
Definition at line 4947 of file lmdes2_customizer.c.
References MD_Section::entry_table, INT_new_symbol_table(), and MD_Symbol_Table::symbol_count.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
static void C_punt (MD * md, char * fmt, ...) [static]
Definition at line 216 of file lmdes2_customizer.c.
References MD::name, and NULL.
Referenced by add_all_children_to_list(), add_to_generating_set(), annotate_hash(), annotate_header_values(), annotate_latency_class(), build_generating_set(), check_bidirectional_links(), check_int_bounds(), check_proc_opcs(), check_table_option_count(), commit_usage(), convert_to_bit_representation(), convert_to_int_list(), convert_to_int_list_all_targets(), count_num_covered(), count_table_uses(), CU_add_link_at(), CU_calc_int_field_max_value(), CU_consolidate_res_table_usages(), CU_delete_link_at(), CU_distribute_unconditional_usages(), CU_dup_alt(), CU_dup_entry(), CU_dup_res_table(), CU_dup_resource_usage(), CU_find_field(), CU_find_field_decl(), CU_find_section(), CU_get_min_time(), CU_get_slot(), CU_homogenize_table_options(), CU_make_res_table_orthogonal(), CU_max_usage_time(), CU_num_table_uses(), CU_optimize_resource_usage_times(), CU_redundant_entries(), CU_rename_entry(), customize_md(), eliminate_redundant_entries(), eliminate_redundant_new_entries_only(), ENTRY_add_contents(), ENTRY_hash_contents(), enumerate_pairs(), expand_options(), find_header_value(), format_reservation_tables(), is_usage_committed(), main(), mark_covered(), optimize_alt_lists(), optimize_resource_units(), read_header_tables(), reduce_resource_units(), remove_common_usage(), and remove_unreferenced_entries().
int calc_best_case_fail (MD_Entry * alt_entry)
Definition at line 8842 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Entry::name, MD_Section::name, and MD_Entry::section.
Referenced by print_static_stats().
int calc_best_case_succeed (MD_Entry * alt_entry)
Definition at line 8795 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Section::name, and MD_Entry::section.
Referenced by print_static_stats().
void calc_forbidden_latencies (INT_Symbol_Table * forbidden_set, MD_Field * use1_field, MD_Field * use2_field)
Definition at line 6992 of file lmdes2_customizer.c.
References CU_find_field_decl(), CU_find_section(), MD_Field::entry, INT_add_symbol(), INT_find_symbol(), MD_Field::max_element_index, MD_Section::md, MD_find_field, MD_get_int, MD_get_link, MD_Entry::name, NULL, and MD_Entry::section.
Referenced by reduce_resource_units().
int calc_memory_size (MD * md)
Definition at line 8934 of file lmdes2_customizer.c.
References CU_find_field_by_name(), CU_find_section(), expand_tables, MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_next_entry(), and MD_num_entries.
Referenced by print_static_stats().
int calc_worst_case_fail (MD_Entry * alt_entry)
Definition at line 8885 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Section::name, and MD_Entry::section.
Referenced by print_static_stats().
void check_bidirectional_links (MD * md, char * section_name, char * field_name)
Definition at line 1726 of file lmdes2_customizer.c.
References C_punt(), customization_errors, MD_Field_Decl::kleene_starred_req, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_link, MD_LINK, MD_next_entry(), MD_Entry::name, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
void check_for_unconditional_overlap (MD * md)
Definition at line 4213 of file lmdes2_customizer.c.
References CU_find_field_by_name(), CU_find_section(), CU_overlapping_resource_usage(), customization_errors, MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Entry::name, and NULL.
Referenced by customize_md().
void check_int_bounds (MD * md, char * section_name, char * field_name, int lower_bound, int upper_bound)
Definition at line 1523 of file lmdes2_customizer.c.
References C_punt(), customization_errors, entry, MD_Field_Decl::kleene_starred_req, MD_Field_Decl::max_require_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_INT, MD_next_entry(), NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
void check_proc_opcs (MD * md)
Definition at line 1582 of file lmdes2_customizer.c.
References C_punt(), customization_errors, entry, INT_add_symbol(), INT_delete_symbol_table(), INT_find_symbol_data(), INT_new_symbol_table(), MD_Field_Decl::kleene_starred_req, MD_Field_Decl::max_require_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_INT, MD_next_entry(), MD_Entry::name, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
void check_slot_specification (MD * md)
Definition at line 6212 of file lmdes2_customizer.c.
References CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_get_slot(), customization_errors, entry, MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_int, MD_get_link, MD_next_entry(), MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by customize_md().
void check_table_option_count (MD * md)
Definition at line 1684 of file lmdes2_customizer.c.
References C_punt(), customization_errors, entry, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_next_entry(), and NULL.
Referenced by customize_md().
void commit_usage (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource, int user, int time)
Definition at line 7780 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, INT_find_symbol(), INT_find_symbol_data(), mark_covered(), NULL, and Resource_Info::time_table.
Referenced by minimize_generating_set().
void convert_to_bit_representation (MD * md, char * src_section_name, char * src_field_name, char * value_section_name, char * value_field_name, char * dest_field_name)
Definition at line 978 of file lmdes2_customizer.c.
References C_punt(), MD_Field_Decl::kleene_starred_req, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_field_decl(), MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_INT, MD_LINK, MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, MD_Entry::name, MD_Section::name, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
void convert_to_int_list (MD * md, char * src_section_name, char * src_field_name, char * value_section_name, char * value_field_name, char * dest_field_name)
Definition at line 1246 of file lmdes2_customizer.c.
References C_punt(), MD_Field_Decl::kleene_starred_req, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_field_decl(), MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_INT, MD_kleene_star_requirement(), MD_LINK, MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
void convert_to_int_list_all_targets (MD * md, char * src_section_name, char * src_field_name, char * value_field_name, char * dest_field_name)
Definition at line 1366 of file lmdes2_customizer.c.
References C_punt(), customization_errors, MD_Field_Decl::kleene_starred_req, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_field_decl(), MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_INT, MD_kleene_star_requirement(), MD_LINK, MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
int count_num_covered (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource, int user, int time)
Definition at line 7837 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_find_symbol(), Resource_Info::name, INT_Symbol::next_symbol, NULL, Resource_Info::time_table, and INT_Symbol::value.
int count_table_uses (MD * md, MD_Entry * table_entry)
Definition at line 8610 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_decl(), CU_find_section(), MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Section::name, MD_Entry::name, opti_level, and MD_Entry::section.
Referenced by average_usage_checks().
void CU_add_link_at (MD_Field * field, int at_index, MD_Entry * new_link)
Definition at line 2162 of file lmdes2_customizer.c.
References C_punt(), MD_Field::element, MD_Field::entry, MD_Field::max_element_index, MD_Section::md, MD_get_link, MD_LINK, MD_set_link, NULL, MD_Entry::section, and MD_Element::type.
Referenced by CU_dup_alt(), CU_dup_resource_usage(), and expand_options().
int CU_calc_int_field_max_value (MD * md, char * section_name, char * field_name)
Definition at line 9260 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_decl(), CU_find_section(), entry, MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_int, and MD_next_entry().
Referenced by customize_md().
int CU_calc_max_field_size (MD * md, char * section_name, char * field_name)
Definition at line 9224 of file lmdes2_customizer.c.
References CU_find_field_decl(), CU_find_section(), entry, MD_Field::max_element_index, MD_find_field, MD_first_entry(), and MD_next_entry().
Referenced by customize_md().
void CU_coalesce_unconditional_usages (MD * md)
Definition at line 4473 of file lmdes2_customizer.c.
References CU_dup_entry(), CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_get_unique_name(), DEBUG_OPTI, MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_new_entry(), MD_new_field(), MD_next_entry(), MD_set_link, MD_Section::name, MD_Entry::name, NULL, option_usage_common_at_time(), remove_common_usage(), and MD_Entry::section.
Referenced by customize_md().
void CU_consolidate_res_table_usages (MD_Entry * res_table)
Definition at line 2991 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), MD_Field::max_element_index, MD_Section::md, MD_get_link, MD_set_link, MD_Entry::name, MD_Section::name, and MD_Entry::section.
Referenced by homogenize_reservation_tables().
int CU_count_entries (MD * md)
Definition at line 6191 of file lmdes2_customizer.c.
References CU_count_section_entries(), MD_first_section(), MD_next_section(), and NULL.
Referenced by customize_md().
int CU_count_section_entries (MD_Section * section)
Definition at line 6183 of file lmdes2_customizer.c.
References MD_Section::entry_table, and MD_Symbol_Table::symbol_count.
Referenced by CU_count_entries(), customize_md(), and reduce_resource_units().
void CU_delete_link_at (MD_Field * field, int at_index)
Definition at line 2198 of file lmdes2_customizer.c.
References C_punt(), MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Field::max_element_index, MD_Section::md, MD_LINK, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Entry::section, and MD_Element::type.
Referenced by CU_make_res_table_orthogonal(), optimize_alt_lists(), and remove_common_usage().
void CU_distribute_unconditional_usages (MD_Entry * table_entry)
Definition at line 3270 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Section::name, MD_Entry::name, NULL, and MD_Entry::section.
Referenced by homogenize_reservation_tables().
MD_Entry* CU_dup_alt (MD_Entry * orig_alt)
Definition at line 2259 of file lmdes2_customizer.c.
References C_punt(), CU_add_link_at(), CU_dup_entry(), CU_find_field_decl(), CU_find_section(), CU_rename_entry(), MD_Field::max_element_index, MD_Section::md, MD_find_field, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by CU_dup_res_table().
MD_Entry* CU_dup_entry (MD_Entry * orig_entry)
Definition at line 1960 of file lmdes2_customizer.c.
References C_punt(), CU_get_unique_name(), MD_Field::element, MD_Field::max_element_index, MD_DOUBLE, MD_find_field, MD_find_field_decl, MD_first_field_decl(), MD_get_double, MD_get_int, MD_get_link, MD_get_string, MD_INT, MD_LINK, MD_new_entry(), MD_new_field(), MD_next_field_decl(), MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_STRING, MD_Entry::name, NULL, MD_Entry::section, and MD_Element::type.
Referenced by CU_coalesce_unconditional_usages(), CU_dup_alt(), CU_dup_res_table(), CU_dup_resource_usage(), CU_make_res_table_orthogonal(), distribute_usage(), expand_options(), optimize_alt_lists(), optimize_resource_units(), and remove_common_usage().
MD_Entry* CU_dup_res_table (MD_Entry * orig_res_table)
Definition at line 2321 of file lmdes2_customizer.c.
References C_punt(), CU_dup_alt(), CU_dup_entry(), CU_find_field_decl(), CU_find_section(), CU_rename_entry(), MD_Section::md, MD_find_field, MD_first_entry(), MD_get_link, MD_next_entry(), MD_set_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by CU_make_res_table_orthogonal().
MD_Entry* CU_dup_resource_usage (MD_Entry * orig_ru)
Definition at line 2381 of file lmdes2_customizer.c.
References C_punt(), CU_add_link_at(), CU_dup_entry(), CU_find_field_decl(), CU_find_section(), CU_rename_entry(), MD_Field::max_element_index, MD_Section::md, MD_find_field, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by CU_homogenize_resource_usages().
MD_Field* CU_find_field (MD_Entry * entry, MD_Field_Decl * field_decl)
Definition at line 1844 of file lmdes2_customizer.c.
References C_punt(), entry, MD_find_field, MD_Field_Decl::name, and NULL.
Referenced by CU_num_table_uses().
MD_Field* CU_find_field_by_name (MD_Entry * entry, char * field_name)
Definition at line 1859 of file lmdes2_customizer.c.
References CU_find_field_decl(), entry, and MD_find_field.
Referenced by average_usage_checks(), calc_best_case_fail(), calc_best_case_succeed(), calc_memory_size(), calc_worst_case_fail(), check_for_unconditional_overlap(), check_slot_specification(), CU_coalesce_unconditional_usages(), CU_consolidate_res_table_usages(), CU_distribute_unconditional_usages(), CU_get_min_time(), CU_get_ru_time(), CU_get_slot(), CU_homogenize_resource_usages(), CU_homogenize_table_options(), CU_make_res_table_orthogonal(), CU_max_usage_time(), CU_num_options(), CU_order_use_fields(), CU_overlapping_resource_usage(), distribute_usage(), expand_options(), expand_out_reservation_tables(), format_reservation_tables(), optimize_alt_lists(), optimize_resource_units(), option_usage_common_at_time(), print_and_or_tree(), print_option_tree(), print_ru_tree(), print_static_stats(), print_unit_tree(), reduce_resource_units(), remove_common_usage(), usage_common_to_all_options(), usage_cycle_compatable(), and usage_resource_compatable().
MD_Field_Decl* CU_find_field_decl (MD_Section * section, char * field_name)
Definition at line 1830 of file lmdes2_customizer.c.
References C_punt(), MD_Section::md, MD_find_field_decl, MD_Section::name, and NULL.
Referenced by build_generating_set(), calc_forbidden_latencies(), check_slot_specification(), count_table_uses(), CU_calc_int_field_max_value(), CU_calc_max_field_size(), CU_coalesce_unconditional_usages(), CU_dup_alt(), CU_dup_res_table(), CU_dup_resource_usage(), CU_find_field_by_name(), CU_get_slot(), CU_homogenize_table_options(), CU_num_table_uses(), CU_optimize_resource_usage_times(), CU_set_slot_parameters(), CU_set_string_parm(), expand_out_reservation_tables(), format_reservation_tables(), instantiate_generating_set(), optimize_alt_lists(), and optimize_resource_units().
MD_Section* CU_find_section (MD * md, char * section_name)
Definition at line 1819 of file lmdes2_customizer.c.
References C_punt(), MD_find_section, and NULL.
Referenced by assign_resource_map_locations(), average_usage_checks(), build_generating_set(), calc_forbidden_latencies(), calc_memory_size(), check_for_unconditional_overlap(), check_slot_specification(), count_table_uses(), CU_calc_int_field_max_value(), CU_calc_max_field_size(), CU_coalesce_unconditional_usages(), CU_dup_alt(), CU_dup_res_table(), CU_dup_resource_usage(), CU_homogenize_table_options(), CU_num_table_uses(), CU_optimize_resource_usage_times(), CU_order_use_fields(), CU_parm_exists(), CU_set_slot_parameters(), CU_set_string_parm(), customize_md(), eliminate_redundant_entries(), eliminate_redundant_new_entries_only(), expand_out_reservation_tables(), format_reservation_tables(), homogenize_reservation_tables(), mark_resource_unit_slots(), optimize_alt_lists(), optimize_resource_units(), print_static_stats(), print_table_trees(), reduce_resource_units(), remove_unreferenced_entries(), and rename_section_entries().
int CU_get_min_time (MD_Entry * entry)
Definition at line 2560 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), entry, MD_Field::max_element_index, MD_get_int, and MD_get_link.
Referenced by CU_order_use_fields().
int CU_get_ru_time (MD_Entry * ru_entry)
Definition at line 3772 of file lmdes2_customizer.c.
References CU_find_field_by_name(), and MD_get_int.
Referenced by CU_order_use_fields().
int CU_get_slot (MD_Entry * entry)
Definition at line 2446 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), CU_find_field_decl(), entry, MD_Field::max_element_index, MD_find_field, MD_get_int, MD_get_link, NULL, and MD_Entry::section.
Referenced by check_slot_specification(), CU_order_use_fields(), and mark_resource_unit_slots().
void CU_get_unique_name (MD * md, MD_Entry * entry, char * base_name, char * new_name)
Definition at line 1888 of file lmdes2_customizer.c.
References STRING_Symbol::data, entry, I_punt(), MD_find_entry, MD_first_section(), MD_next_section(), NULL, rename_table, STRING_add_symbol(), and STRING_find_symbol().
Referenced by CU_coalesce_unconditional_usages(), CU_dup_entry(), CU_homogenize_table_options(), CU_rename_entry(), expand_out_reservation_tables(), and format_reservation_tables().
unsigned int CU_hash_string (char * string)
Definition at line 5173 of file lmdes2_customizer.c.
Referenced by ENTRY_hash_contents().
void CU_homogenize_resource_usages (MD_Entry * ru_entry)
Definition at line 3509 of file lmdes2_customizer.c.
References CU_dup_resource_usage(), CU_find_field_by_name(), MD_Field::max_element_index, MD_delete_element(), MD_get_int, MD_get_link, MD_set_int, and MD_set_link.
Referenced by homogenize_reservation_tables().
void CU_homogenize_table_options (MD_Entry * table_option)
Definition at line 3442 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_get_unique_name(), MD_Field::max_element_index, MD_Section::md, MD_get_link, MD_new_entry(), MD_new_field(), MD_set_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by homogenize_reservation_tables().
int CU_make_res_table_orthogonal (MD_Entry * res_table)
Definition at line 2764 of file lmdes2_customizer.c.
References C_punt(), CU_delete_link_at(), CU_dup_entry(), CU_dup_res_table(), CU_find_field_by_name(), CU_overlapping_resource_usage(), CU_rename_entry(), MD_Field::max_element_index, MD_Section::md, MD_delete_entry, MD_get_link, MD_print_entry(), MD_set_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by homogenize_reservation_tables().
int CU_max_usage_time (MD_Entry * entry)
Definition at line 6427 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), entry, MD_Field::max_element_index, MD_get_int, MD_get_link, and NULL.
int CU_num_options (MD_Entry * entry)
Definition at line 6411 of file lmdes2_customizer.c.
References CU_find_field_by_name(), entry, and MD_Field::max_element_index.
int CU_num_table_uses (MD_Entry * option_entry)
Definition at line 3785 of file lmdes2_customizer.c.
References C_punt(), CU_find_field(), CU_find_field_decl(), CU_find_section(), MD_Section::md, MD_first_entry(), MD_get_link, MD_max_element_index, MD_next_entry(), MD_Entry::name, NULL, and MD_Entry::section.
Referenced by CU_order_use_fields().
void CU_optimize_resource_usage_times (MD * md)
Definition at line 3612 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_decl(), CU_find_section(), MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_int, MD_get_link, MD_next_entry(), MD_set_int, MD_Entry::name, NULL, and opti_level.
Referenced by homogenize_reservation_tables().
void CU_order_use_fields (MD * md, int min_reorder)
Definition at line 3841 of file lmdes2_customizer.c.
References CU_find_field_by_name(), CU_find_section(), CU_get_min_time(), CU_get_ru_time(), CU_get_slot(), CU_num_table_uses(), MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_next_entry(), MD_set_link, MD_Section::name, MD_Entry::name, NULL, opti_level, and MD_Entry::section.
Referenced by customize_md(), and homogenize_reservation_tables().
int CU_overlapping_resource_usage (MD_Entry * entry1, MD_Entry * entry2)
Definition at line 2639 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Section::name, and MD_Entry::section.
Referenced by check_for_unconditional_overlap(), and CU_make_res_table_orthogonal().
int CU_parm_exists (MD * md, char * name)
Definition at line 6796 of file lmdes2_customizer.c.
References CU_find_section(), MD_find_entry, and NULL.
Referenced by customize_md().
int CU_redundant_entries (MD_Entry * entry1, MD_Entry * entry2, char * ignore_field)
Definition at line 5458 of file lmdes2_customizer.c.
References C_punt(), MD_Element::d, MD_Field::element, MD_Element::i, MD_Element::l, MD_Field::max_element_index, MD_Section::md, MD_DOUBLE, MD_find_field, MD_first_field_decl(), MD_INT, MD_LINK, MD_next_field_decl(), MD_STRING, MD_Field_Decl::name, MD_Section::name, NULL, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by ENTRY_add_contents(), ENTRY_find_match(), and optimize_alt_lists().
void CU_rename_entry (MD_Entry * entry, char * new_name)
Definition at line 2083 of file lmdes2_customizer.c.
References C_punt(), CU_get_unique_name(), entry, MD_Field_Decl::kleene_starred_req, MD_Field_Decl::max_require_index, MD_Section::md, MD_find_field, MD_find_field_decl, MD_get_string, MD_new_field(), MD_new_field_decl(), MD_OPTIONAL_FIELD, MD_print_field_decl(), MD_rename_entry(), MD_require_string(), MD_set_string, MD_STRING, MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Element_Req::type, and MD_Field_Decl::type.
Referenced by CU_dup_alt(), CU_dup_res_table(), CU_dup_resource_usage(), and CU_make_res_table_orthogonal().
void CU_replace_references (INT_Symbol_Table * link_table, INT_Symbol_Table * remap_table)
Definition at line 5561 of file lmdes2_customizer.c.
References INT_Symbol::data, MD_Field::element, INT_Symbol_Table::head_symbol, INT_find_symbol_data(), MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_link, MD_LINK, MD_next_entry(), MD_set_link, MD_Entry::name, INT_Symbol::next_symbol, NULL, MD_Field_Decl::section, Pointer_Mapping::to, and MD_Element::type.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
void CU_set_int_parm (MD * md, char * name, int value)
Definition at line 6838 of file lmdes2_customizer.c.
References CU_set_string_parm().
Referenced by CU_set_slot_parameters(), and customize_md().
void CU_set_slot_parameters (MD * md)
Definition at line 9310 of file lmdes2_customizer.c.
References CU_find_field_decl(), CU_find_section(), CU_set_int_parm(), MD_find_field, MD_first_entry(), MD_get_int, and MD_next_entry().
Referenced by customize_md().
void CU_set_string_parm (MD * md, char * name, char * string_value)
Definition at line 6812 of file lmdes2_customizer.c.
References CU_find_field_decl(), CU_find_section(), MD_delete_entry, MD_find_entry, MD_new_entry(), MD_new_field(), MD_set_string, and NULL.
Referenced by CU_set_int_parm(), and customize_md().
void customize_md (MD * md)
Definition at line 9374 of file lmdes2_customizer.c.
References add_all_children_to_list(), annotate_hash(), annotate_header_values(), annotate_latency_class(), assign_resource_map_locations(), average_usage_checks(), C_punt(), check_bidirectional_links(), check_for_unconditional_overlap(), check_int_bounds(), check_proc_opcs(), check_slot_specification(), check_table_option_count(), convert_to_bit_representation(), convert_to_int_list_all_targets(), CU_calc_int_field_max_value(), CU_calc_max_field_size(), CU_coalesce_unconditional_usages(), CU_count_entries(), CU_count_section_entries(), CU_find_section(), CU_order_use_fields(), CU_parm_exists(), CU_set_int_parm(), CU_set_slot_parameters(), CU_set_string_parm(), customization_errors, do_classical_optimizations(), dump_md(), expand_out_reservation_tables(), expand_tables, format_reservation_tables(), header_errors, homogenize_reservation_tables(), mark_resource_unit_slots(), MD_find_section, opti_level, optimize_resource_units(), print_static_stats(), print_table_trees(), print_time_stamp(), print_trees, read_header_tables(), reduce_resource_units(), remove_original_name(), rename_section_entries(), rename_table, resource_minimization, static_stats, STRING_delete_symbol_table(), STRING_new_symbol_table(), and tree_opti.
Referenced by main().
void delete_resource (Resource_Info * resource)
Definition at line 7324 of file lmdes2_customizer.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_delete_symbol(), INT_delete_symbol_table(), INT_Symbol::next_symbol, NULL, and Resource_Info::time_table.
Referenced by build_generating_set(), and free_generating_set().
void distribute_usage (MD_Field * table_use_field, int index, MD_Entry * usage_entry)
Definition at line 3226 of file lmdes2_customizer.c.
References CU_dup_entry(), CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_set_link, and MD_Entry::name.
int do_classical_optimizations (MD * md)
Definition at line 6106 of file lmdes2_customizer.c.
References eliminate_redundant_entries(), opti_level, optimize_alt_lists(), print_time_stamp(), and remove_unreferenced_entries().
Referenced by customize_md().
void dump_md (char * file_name, MD * md)
Definition at line 9353 of file lmdes2_customizer.c.
References I_punt(), MD_write_md(), and print_time_stamp().
Referenced by customize_md().
int eliminate_redundant_entries (MD * md, char * section_name)
Definition at line 5624 of file lmdes2_customizer.c.
References add_remap_entry(), build_link_table(), build_remap_table(), C_punt(), CU_find_section(), CU_replace_references(), INT_Symbol::data, ENTRY_add_contents(), ENTRY_delete_contents_table(), ENTRY_find_match(), ENTRY_new_contents_table(), MD_Section::entry_table, free_link_table(), free_remap_table(), Pointer_Mapping::from, INT_Symbol_Table::head_symbol, MD_delete_entry, MD_first_entry(), MD_next_entry(), MD_Section::name, INT_Symbol::next_symbol, NULL, and MD_Symbol_Table::symbol_count.
Referenced by do_classical_optimizations().
int eliminate_redundant_new_entries_only (MD * md, char * section_name)
Definition at line 5746 of file lmdes2_customizer.c.
References add_remap_entry(), build_link_table(), build_remap_table(), C_punt(), CU_find_section(), CU_replace_references(), INT_Symbol::data, ENTRY_add_contents(), ENTRY_delete_contents_table(), ENTRY_find_match(), ENTRY_new_contents_table(), MD_Section::entry_table, free_link_table(), free_remap_table(), Pointer_Mapping::from, INT_Symbol_Table::head_symbol, MD_delete_entry, MD_first_entry(), MD_next_entry(), MD_Section::name, INT_Symbol::next_symbol, NULL, and MD_Symbol_Table::symbol_count.
Referenced by homogenize_reservation_tables().
void ENTRY_add_contents (ENTRY_Contents_Table * table, MD_Entry * entry)
Definition at line 5336 of file lmdes2_customizer.c.
References C_punt(), CU_redundant_entries(), INT_Symbol::data, entry, ENTRY_Contents_Node_pool, ENTRY_hash_contents(), ENTRY_Contents_Table::hash_table, ENTRY_Contents_Table::ignore_field, INT_add_symbol(), INT_find_symbol(), L_alloc(), L_create_alloc_pool(), node, and NULL.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
void ENTRY_delete_contents_table (ENTRY_Contents_Table * table)
Definition at line 5438 of file lmdes2_customizer.c.
References ENTRY_Contents_Table_pool, ENTRY_free_nodes(), ENTRY_Contents_Table::hash_table, ENTRY_Contents_Table::ignore_field, INT_delete_symbol_table(), L_free(), and NULL.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
MD_Entry* ENTRY_find_match (ENTRY_Contents_Table * table, MD_Entry * entry)
Definition at line 5391 of file lmdes2_customizer.c.
References CU_redundant_entries(), INT_Symbol::data, entry, ENTRY_hash_contents(), ENTRY_Contents_Table::hash_table, ENTRY_Contents_Table::ignore_field, INT_find_symbol(), node, and NULL.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
void ENTRY_free_nodes (ENTRY_Contents_Node * first_node)
Definition at line 5423 of file lmdes2_customizer.c.
References ENTRY_Contents_Node_pool, L_free(), ENTRY_Contents_Node::next_node, node, and NULL.
Referenced by ENTRY_delete_contents_table().
unsigned int ENTRY_hash_contents (MD_Entry * entry1, char * ignore_field)
Definition at line 5245 of file lmdes2_customizer.c.
References C_punt(), CU_hash_string(), MD_Element::d, MD_Field::element, MD_Element::i, MD_Element::l, MD_Field::max_element_index, MD_Section::md, MD_DOUBLE, MD_find_field, MD_first_field_decl(), MD_INT, MD_LINK, MD_next_field_decl(), MD_STRING, MD_Field_Decl::name, NULL, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by ENTRY_add_contents(), and ENTRY_find_match().
ENTRY_Contents_Table* ENTRY_new_contents_table (char * ignore_field, int size)
Definition at line 5215 of file lmdes2_customizer.c.
References ENTRY_Contents_Table_pool, ENTRY_Contents_Table::hash_table, ENTRY_Contents_Table::ignore_field, INT_new_symbol_table(), L_alloc(), L_create_alloc_pool(), and NULL.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
int entry_referenced (INT_Symbol_Table * referenced_table, MD_Entry * test_entry)
Definition at line 5088 of file lmdes2_customizer.c.
References INT_find_symbol(), and NULL.
Referenced by remove_unreferenced_entries().
void enumerate_pairs (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource)
Definition at line 7558 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_find_symbol(), Resource_Info::name, Pair_Node::next, INT_Symbol::next_symbol, NULL, Pair_Node::resource, Pair_Node::time1, Resource_Info::time_table, and INT_Symbol::value.
Referenced by minimize_generating_set().
void expand_options (MD_Entry * dest_option, MD_Entry * src_option)
Definition at line 6846 of file lmdes2_customizer.c.
References C_punt(), CU_add_link_at(), CU_dup_entry(), CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_set_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by expand_out_reservation_tables().
void expand_out_reservation_tables (MD * md)
Definition at line 6928 of file lmdes2_customizer.c.
References CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_get_unique_name(), expand_options(), MD_Field::max_element_index, MD_delete_element(), MD_first_entry(), MD_get_link, MD_new_entry(), MD_new_field(), MD_next_entry(), MD_set_link, MD_Entry::name, and NULL.
Referenced by customize_md().
void find_children (INT_Symbol_Table * child_table, MD_Entry * entry, MD_Field_Decl * field_decl)
Definition at line 1118 of file lmdes2_customizer.c.
References entry, INT_add_symbol(), INT_find_symbol(), MD_Field::max_element_index, MD_find_field, MD_get_link, and NULL.
Referenced by add_all_children_to_list().
int find_header_value (MD * md, char * name, int * value)
Definition at line 704 of file lmdes2_customizer.c.
References C_punt(), STRING_Symbol::data, STRING_Symbol_Table::head_symbol, header_errors, header_table_table, MD::name, STRING_Symbol::next_symbol, NULL, and STRING_find_symbol_data().
Referenced by annotate_header_values().
void format_reservation_tables (MD * md)
Definition at line 6528 of file lmdes2_customizer.c.
References C_punt(), CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_get_unique_name(), MD_Field::max_element_index, MD_delete_field_decl(), MD_find_field_decl, MD_first_entry(), MD_get_link, MD_new_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_require_multi_target_link(), MD_REQUIRED_FIELD, MD_set_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by customize_md().
void free_generating_set (INT_Symbol_Table * generating_set)
Definition at line 8338 of file lmdes2_customizer.c.
References INT_Symbol::data, delete_resource(), INT_Symbol_Table::head_symbol, INT_delete_symbol(), INT_delete_symbol_table(), and INT_Symbol::next_symbol.
Referenced by reduce_resource_units().
void free_link_table (INT_Symbol_Table * link_table)
Definition at line 4866 of file lmdes2_customizer.c.
References INT_delete_symbol_table(), and NULL.
Referenced by eliminate_redundant_entries(), eliminate_redundant_new_entries_only(), and remove_unreferenced_entries().
void free_referenced_table (INT_Symbol_Table * referenced_table)
Definition at line 5016 of file lmdes2_customizer.c.
References INT_delete_symbol_table(), and NULL.
Referenced by remove_unreferenced_entries().
void free_remap_table (INT_Symbol_Table * remap_table)
Definition at line 4933 of file lmdes2_customizer.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_delete_symbol_table(), INT_Symbol::next_symbol, and NULL.
Referenced by eliminate_redundant_entries(), and eliminate_redundant_new_entries_only().
void homogenize_reservation_tables (MD * md)
Definition at line 4091 of file lmdes2_customizer.c.
References CU_consolidate_res_table_usages(), CU_distribute_unconditional_usages(), CU_find_section(), CU_homogenize_resource_usages(), CU_homogenize_table_options(), CU_make_res_table_orthogonal(), CU_optimize_resource_usage_times(), CU_order_use_fields(), eliminate_redundant_new_entries_only(), MD_first_entry(), MD_next_entry(), NULL, opti_level, and tree_opti.
Referenced by customize_md().
void instantiate_generating_set (INT_Symbol_Table * generating_set, MD_Field ** use_array, int num_units, MD_Section * usage_section)
Definition at line 8365 of file lmdes2_customizer.c.
References CU_find_field_decl(), INT_Symbol::data, INT_Symbol_Table::head_symbol, MD_delete_element(), MD_delete_entry, MD_first_entry(), MD_new_entry(), MD_new_field(), MD_next_entry(), MD_set_int, MD_set_link, Resource_Info::name, INT_Symbol::next_symbol, Resource_Info::resource_entry, Resource_Info::time_table, and INT_Symbol::value.
Referenced by reduce_resource_units().
int is_compatable (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource, int new_user, int new_time)
Definition at line 7147 of file lmdes2_customizer.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, is_forbidden(), INT_Symbol::next_symbol, NULL, Resource_Info::time_table, and INT_Symbol::value.
Referenced by add_to_generating_set().
int is_forbidden (INT_Symbol_Table *** forbidden_matrix, int user1, int user2, int latency)
Definition at line 7116 of file lmdes2_customizer.c.
References INT_find_symbol(), and NULL.
Referenced by is_compatable().
int is_usage_committed (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource, int user, int time)
Definition at line 7811 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, INT_find_symbol(), INT_find_symbol_data(), NULL, and Resource_Info::time_table.
int main (int argc, char ** argv)
Definition at line 510 of file lmdes2_customizer.c.
References C_punt(), customize_md(), input_file_name, MD_check_md(), MD_delete_md(), MD_print_md(), MD_print_md_declarations(), MD_read_md(), MD_write_md(), MD::name, NULL, output_file_name, output_mode, read_command_line_parameters(), using_stdin, and verbose.
int mark_covered (INT_Symbol_Table *** forbidden_matrix, Resource_Info * resource, int user, int time)
Definition at line 7635 of file lmdes2_customizer.c.
References C_punt(), INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_find_symbol(), Resource_Info::name, Pair_Node::next, INT_Symbol::next_symbol, NULL, Resource_Info::time_table, and INT_Symbol::value.
Referenced by commit_usage().
void mark_resource_unit_slots (MD * md)
Definition at line 6369 of file lmdes2_customizer.c.
References CU_find_section(), CU_get_slot(), MD_delete_field_decl(), MD_find_field_decl, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_OPTIONAL_FIELD, MD_require_int(), MD_set_int, and NULL.
Referenced by customize_md().
void minimize_generating_set (INT_Symbol_Table * generating_set, INT_Symbol_Table *** forbidden_matrix, int num_units, MD_Entry ** unit_array)
Definition at line 7955 of file lmdes2_customizer.c.
References commit_usage(), INT_Symbol::data, enumerate_pairs(), Resource_Info::flags, INT_Symbol_Table::head_symbol, INT_find_symbol_data(), Resource_Info::name, Pair_Node::next, INT_Symbol::next_symbol, NULL, Pair_Node::resource, SLOT_RESOURCE, Pair_Node::time1, Resource_Info::time_table, and INT_Symbol::value.
Referenced by reduce_resource_units().
int optimize_alt_lists (MD * md)
Definition at line 5926 of file lmdes2_customizer.c.
References C_punt(), CU_delete_link_at(), CU_dup_entry(), CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), CU_redundant_entries(), DEBUG_OPTI, MD_Field::max_element_index, MD_find_field, MD_first_entry(), MD_get_link, MD_next_entry(), MD_set_link, MD_Entry::name, and NULL.
Referenced by do_classical_optimizations().
void optimize_resource_units (MD * md, int max_offset)
Definition at line 4603 of file lmdes2_customizer.c.
References C_punt(), CU_dup_entry(), CU_find_field_by_name(), CU_find_field_decl(), CU_find_section(), INT_Symbol::data, Heap_Create(), Heap_Dispose(), Heap_ExtractTop(), Heap_Insert(), HEAP_MIN, INT_add_symbol(), INT_delete_symbol_table(), INT_find_symbol(), INT_new_symbol_table(), MD_Element_Req::kleene_starred, MD_Element_Req::link, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_element(), MD_first_entry(), MD_get_int, MD_get_link, MD_kleene_star_requirement(), MD_LINK, MD_next_entry(), MD_print_field_decl(), MD_require_link(), MD_set_link, MD_Entry::name, MD_Field_Decl::name, MD_Section::name, NULL, MD_Field_Decl::require, and MD_Element_Req::type.
Referenced by customize_md().
int option_usage_common_at_time (MD_Entry * option_entry, MD_Entry * usage_entry)
Definition at line 4383 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_int, MD_get_link, and usage_common_to_all_options().
Referenced by CU_coalesce_unconditional_usages().
void print_and_or_tree (FILE * out, MD_Entry * table)
Definition at line 9185 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Section::name, MD_Entry::name, print_option_tree(), print_unit_tree(), and MD_Entry::section.
Referenced by print_table_trees().
void print_generating_set (FILE * out, INT_Symbol_Table * generating_set, MD_Entry ** unit_array, int committed)
Definition at line 8291 of file lmdes2_customizer.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, Resource_Info::name, INT_Symbol::next_symbol, Resource_Info::time_table, and INT_Symbol::value.
Referenced by build_generating_set().
void print_option_tree (FILE * out, MD_Entry * option_entry)
Definition at line 9170 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, and print_unit_tree().
Referenced by print_and_or_tree().
void print_ru_tree (FILE * out, MD_Entry * ru_entry)
Definition at line 9131 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_int, MD_get_link, and MD_Entry::name.
Referenced by print_unit_tree().
void print_static_stats (FILE * out, MD * md)
Definition at line 9030 of file lmdes2_customizer.c.
References calc_best_case_fail(), calc_best_case_succeed(), calc_memory_size(), calc_worst_case_fail(), CU_find_field_by_name(), CU_find_section(), DEBUG_OPTI, MD_Field::max_element_index, MD_first_entry(), MD_get_link, MD_next_entry(), and MD_Entry::name.
Referenced by customize_md().
void print_table_trees (FILE * out, MD * md)
Definition at line 9205 of file lmdes2_customizer.c.
References CU_find_section(), MD_first_entry(), MD_next_entry(), and print_and_or_tree().
Referenced by customize_md(), and reduce_resource_units().
void print_time_stamp (FILE * out)
Definition at line 240 of file lmdes2_customizer.c.
References NULL.
Referenced by customize_md(), do_classical_optimizations(), and dump_md().
void print_unit_tree (FILE * out, MD_Entry * unit_entry, int option_id)
Definition at line 9154 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_Entry::name, and print_ru_tree().
Referenced by print_and_or_tree(), and print_option_tree().
void print_usage (char * fmt, ...)
Definition at line 256 of file lmdes2_customizer.c.
References NULL, and program_name.
Referenced by read_command_line_parameters().
void read_command_line_parameters (int argc, char ** arg_ptr)
Definition at line 308 of file lmdes2_customizer.c.
References bypass_alloc_routines, expand_tables, input_file_name, NULL, opti_level, output_file_name, output_mode, output_page_width, print_trees, print_usage(), program_name, resource_minimization, static_stats, tree_opti, using_stdin, and verbose.
Referenced by main().
STRING_Symbol_Table* read_header_file (char * file_name, int print_warnings)
Definition at line 91 of file header_reader2.c.
References hparse_info_st::comment_level, hparse_info_st::endif_level, Hget_next_line(), Hparse_line(), Hskip_to_endif(), I_punt(), hparse_info_st::in, hparse_info_st::line, MLINE_SIZE, hparse_info_st::name, name, NULL, STRING_add_symbol(), STRING_find_symbol(), STRING_find_symbol_data(), STRING_new_symbol_table(), and hparse_info_st::table.
Referenced by read_header_tables().
void read_header_tables (MD * md)
Definition at line 624 of file lmdes2_customizer.c.
References C_punt(), MD_Field::decl, header_table_table, MD_Field::max_element_index, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_string, MD_Field_Decl::name, NULL, read_header_file(), STRING_add_symbol(), STRING_find_symbol(), STRING_new_symbol_table(), and verbose.
Referenced by customize_md().
void reduce_resource_units (MD * md)
Definition at line 8450 of file lmdes2_customizer.c.
References build_generating_set(), C_punt(), calc_forbidden_latencies(), CU_count_section_entries(), CU_find_field_by_name(), CU_find_section(), free_generating_set(), instantiate_generating_set(), INT_delete_symbol_table(), INT_new_symbol_table(), MD_Field::max_element_index, MD_first_entry(), MD_next_entry(), minimize_generating_set(), name, MD::name, and print_table_trees().
Referenced by customize_md().
void remove_common_usage (MD_Entry * option_entry, MD_Entry * usage_entry)
Definition at line 4424 of file lmdes2_customizer.c.
References C_punt(), CU_delete_link_at(), CU_dup_entry(), CU_find_field_by_name(), MD_Field::max_element_index, MD_get_link, MD_set_link, MD_Entry::name, and NULL.
Referenced by CU_coalesce_unconditional_usages().
void remove_original_name (MD * md)
Definition at line 5878 of file lmdes2_customizer.c.
References MD_delete_field_decl(), MD_find_field_decl, MD_first_section(), MD_next_section(), MD_Field_Decl::name, and NULL.
Referenced by customize_md().
int remove_unreferenced_entries (MD * md, char * section_name)
Definition at line 5101 of file lmdes2_customizer.c.
References build_link_table(), build_referenced_table(), C_punt(), CU_find_section(), DEBUG_OPTI, entry_referenced(), MD_Section::entry_table, free_link_table(), free_referenced_table(), INT_Symbol_Table::head_symbol, MD_delete_entry, MD_first_entry(), MD_next_entry(), MD_Section::name, NULL, and MD_Symbol_Table::symbol_count.
Referenced by do_classical_optimizations().
void rename_section_entries (MD * md, char * section_name, char * prefix)
Definition at line 5904 of file lmdes2_customizer.c.
References CU_find_section(), entry, MD_first_entry(), MD_next_entry(), MD_rename_entry(), and NULL.
Referenced by customize_md().
int resource_redundant (Resource_Info * resource1, Resource_Info * resource2)
Definition at line 7279 of file lmdes2_customizer.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, INT_find_symbol(), INT_find_symbol_data(), INT_Symbol::next_symbol, NULL, Resource_Info::time_table, and INT_Symbol::value.
Referenced by build_generating_set().
int usage_common_to_all_options (MD_Entry * option_entry, MD_Entry * ru_entry)
Definition at line 4345 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, and MD_get_link.
Referenced by option_usage_common_at_time().
int usage_cycle_compatable (MD_Entry * usage_entry, MD_Entry * option_entry)
Definition at line 3142 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, MD_get_int, and MD_get_link.
int usage_exists (Resource_Info * resource, int user, int time)
Definition at line 7093 of file lmdes2_customizer.c.
References INT_find_symbol(), INT_find_symbol_data(), NULL, and Resource_Info::time_table.
Referenced by add_to_generating_set().
int usage_resource_compatable (MD_Entry * usage_entry, MD_Entry * option_entry)
Definition at line 3184 of file lmdes2_customizer.c.
References CU_find_field_by_name(), MD_Field::max_element_index, and MD_get_link.
Variable Documentation
int customization_errors = 0
Definition at line 199 of file lmdes2_customizer.c.
Referenced by check_bidirectional_links(), check_for_unconditional_overlap(), check_int_bounds(), check_proc_opcs(), check_slot_specification(), check_table_option_count(), convert_to_int_list_all_targets(), and customize_md().
L_Alloc_Pool* ENTRY_Contents_Node_pool = NULL
Definition at line 185 of file lmdes2_customizer.c.
Referenced by ENTRY_add_contents(), and ENTRY_free_nodes().
L_Alloc_Pool* ENTRY_Contents_Table_pool = NULL
Definition at line 184 of file lmdes2_customizer.c.
Referenced by ENTRY_delete_contents_table(), and ENTRY_new_contents_table().
int expand_tables = 0
Definition at line 155 of file lmdes2_customizer.c.
Referenced by calc_memory_size(), customize_md(), and read_command_line_parameters().
int header_errors = 0
Definition at line 194 of file lmdes2_customizer.c.
Referenced by annotate_header_values(), customize_md(), and find_header_value().
STRING_Symbol_Table* header_table_table = NULL
Definition at line 188 of file lmdes2_customizer.c.
Referenced by find_header_value(), and read_header_tables().
char* input_file_name = NULL
Definition at line 148 of file lmdes2_customizer.c.
Referenced by main(), and read_command_line_parameters().
char* input_mode = NULL
Definition at line 152 of file lmdes2_customizer.c.
int opti_level = 4
Definition at line 180 of file lmdes2_customizer.c.
Referenced by count_table_uses(), CU_optimize_resource_usage_times(), CU_order_use_fields(), customize_md(), do_classical_optimizations(), homogenize_reservation_tables(), and read_command_line_parameters().
char* output_file_name = NULL
Definition at line 149 of file lmdes2_customizer.c.
Referenced by main(), and read_command_line_parameters().
char* output_mode = NULL
Definition at line 151 of file lmdes2_customizer.c.
Referenced by main(), and read_command_line_parameters().
int output_page_width = 80
Definition at line 153 of file lmdes2_customizer.c.
Referenced by read_command_line_parameters().
int place_slots_first = 0
Definition at line 157 of file lmdes2_customizer.c.
int print_trees = 0
Definition at line 159 of file lmdes2_customizer.c.
Referenced by customize_md(), and read_command_line_parameters().
char* program_name = NULL
Definition at line 145 of file lmdes2_customizer.c.
Referenced by print_usage(), and read_command_line_parameters().
STRING_Symbol_Table* rename_table = NULL
Definition at line 191 of file lmdes2_customizer.c.
Referenced by CU_get_unique_name(), and customize_md().
int resource_minimization = 1
Definition at line 160 of file lmdes2_customizer.c.
Referenced by customize_md(), and read_command_line_parameters().
int static_stats = 0
Definition at line 158 of file lmdes2_customizer.c.
Referenced by customize_md(), and read_command_line_parameters().
int tree_opti = 1
Definition at line 156 of file lmdes2_customizer.c.
Referenced by customize_md(), homogenize_reservation_tables(), and read_command_line_parameters().
int using_stdin = 0
Definition at line 150 of file lmdes2_customizer.c.
Referenced by main(), and read_command_line_parameters().
int verbose = 0
Definition at line 154 of file lmdes2_customizer.c.