attr_mngr.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <library/l_alloc_new.h>
#include <library/i_error.h>
#include <library/attr_mngr.h>
Functions
L_AttrMngr * L_create_AttrMngr (char *fn_name, float weight)
A_Attr_Field * A_new_int_field (int value)
A_Attr_Field * A_new_float_field (double value)
A_Attr_Field * A_new_string_field (char *value)
A_Attr_Field * A_new_label_field (char *value)
void L_insert_fn_attr (L_AttrMngr *func_attr, char *attr_name, long attr_value)
void L_insert_fn_attr_int (L_AttrMngr *func_attr, char *attr_name, long attr_value)
void L_insert_fn_attr_float (L_AttrMngr *func_attr, char *attr_name, float attr_value)
void L_insert_fn_attr_string (L_AttrMngr *func_attr, char *attr_name, char *attr_value)
void L_insert_fn_attr_label (L_AttrMngr *func_attr, char *attr_name, char *attr_value)
void L_insert_fn_attr_list (L_AttrMngr *func_attr, char *attr_name, A_Attr_Field **field, int max_field)
void L_insert_cb_attr (L_AttrMngr *func_attr, int cb_num, char *attr_name, long attr_value)
void L_insert_cb_attr_int (L_AttrMngr *func_attr, int cb_num, char *attr_name, long attr_value)
void L_insert_cb_attr_float (L_AttrMngr *func_attr, int cb_num, char *attr_name, float attr_value)
void L_insert_cb_attr_string (L_AttrMngr *func_attr, int cb_num, char *attr_name, char *attr_value)
void L_insert_cb_attr_label (L_AttrMngr *func_attr, int cb_num, char *attr_name, char *attr_value)
void L_insert_cb_attr_list (L_AttrMngr *func_attr, int cb_num, char *attr_name, A_Attr_Field **field, int max_field)
void L_insert_op_attr (L_AttrMngr *func_attr, int op_num, char *attr_name, long attr_value, int dep)
void L_insert_op_attr_int (L_AttrMngr *func_attr, int op_num, char *attr_name, long attr_value, int dep)
void L_insert_op_attr_float (L_AttrMngr *func_attr, int op_num, char *attr_name, float attr_value, int dep)
void L_insert_op_attr_string (L_AttrMngr *func_attr, int op_num, char *attr_name, char *attr_value, int dep)
void L_insert_op_attr_label (L_AttrMngr *func_attr, int op_num, char *attr_name, char *attr_value, int dep)
void L_insert_op_attr_list (L_AttrMngr *func_attr, int op_num, char *attr_name, A_Attr_Field **field, int max_field, int dep)
void L_write_attr_to_file (FILE *out, L_AttrMngr *func_attr)
void L_free_AttrMngr (L_AttrMngr *func_attr)
void L_free_Attr (A_Attr *Attr)
Variables
L_Alloc_Pool * L_AttrMngr_pool = NULL
L_Alloc_Pool * A_Attr_pool = NULL
Function Documentation
A_Attr_Field* A_new_float_field (double value)
Definition at line 102 of file attr_mngr.c.
References A_FLOAT, A_Attr_Field::f, A_Attr_Field::type, and A_Attr_Field::value.
Referenced by L_insert_cb_attr_float(), L_insert_fn_attr_float(), and L_insert_op_attr_float().
A_Attr_Field* A_new_int_field (int value)
Definition at line 91 of file attr_mngr.c.
References A_INT, A_Attr_Field::i, A_Attr_Field::type, and A_Attr_Field::value.
Referenced by L_insert_cb_attr_int(), L_insert_fn_attr_int(), and L_insert_op_attr_int().
A_Attr_Field* A_new_label_field (char * value)
Definition at line 124 of file attr_mngr.c.
References A_LABEL, A_Attr_Field::l, A_Attr_Field::type, and A_Attr_Field::value.
Referenced by L_insert_cb_attr_label(), L_insert_fn_attr_label(), and L_insert_op_attr_label().
A_Attr_Field* A_new_string_field (char * value)
Definition at line 113 of file attr_mngr.c.
References A_STRING, A_Attr_Field::s, A_Attr_Field::type, and A_Attr_Field::value.
Referenced by L_insert_cb_attr_string(), L_insert_fn_attr_string(), and L_insert_op_attr_string().
L_AttrMngr* L_create_AttrMngr (char * fn_name, float weight)
Definition at line 73 of file attr_mngr.c.
References A_Attr_pool, L_AttrMngr::cb_attr, L_AttrMngr::fn_attr, L_AttrMngr::fn_name, L_alloc(), L_AttrMngr_pool, L_create_alloc_pool(), L_AttrMngr::num_cb_attr, L_AttrMngr::num_fn_attr, L_AttrMngr::num_op_attr, L_AttrMngr::op_attr, and L_AttrMngr::weight.
void L_free_Attr (A_Attr * Attr)
Definition at line 495 of file attr_mngr.c.
References A_Attr_pool, A_Attr::field, L_free(), A_Attr::next_attr, and A_Attr::num_fields.
Referenced by L_free_AttrMngr().
void L_free_AttrMngr (L_AttrMngr * func_attr)
Definition at line 486 of file attr_mngr.c.
References L_AttrMngr::cb_attr, L_AttrMngr::fn_attr, L_AttrMngr_pool, L_free(), L_free_Attr(), and L_AttrMngr::op_attr.
void L_insert_cb_attr (L_AttrMngr * func_attr, int cb_num, char * attr_name, long attr_value)
Definition at line 210 of file attr_mngr.c.
References L_insert_cb_attr_int().
void L_insert_cb_attr_float (L_AttrMngr * func_attr, int cb_num, char * attr_name, float attr_value)
Definition at line 228 of file attr_mngr.c.
References A_new_float_field(), and L_insert_cb_attr_list().
void L_insert_cb_attr_int (L_AttrMngr * func_attr, int cb_num, char * attr_name, long attr_value)
Definition at line 217 of file attr_mngr.c.
References A_new_int_field(), and L_insert_cb_attr_list().
Referenced by L_insert_cb_attr().
void L_insert_cb_attr_label (L_AttrMngr * func_attr, int cb_num, char * attr_name, char * attr_value)
Definition at line 250 of file attr_mngr.c.
References A_new_label_field(), and L_insert_cb_attr_list().
void L_insert_cb_attr_list (L_AttrMngr * func_attr, int cb_num, char * attr_name, A_Attr_Field ** field, int max_field)
Definition at line 261 of file attr_mngr.c.
References A_Attr_pool, L_AttrMngr::cb_attr, A_Attr::field, A_Attr::id_num, L_alloc(), A_Attr::name, A_Attr::next_attr, L_AttrMngr::num_cb_attr, and A_Attr::num_fields.
Referenced by L_insert_cb_attr_float(), L_insert_cb_attr_int(), L_insert_cb_attr_label(), and L_insert_cb_attr_string().
void L_insert_cb_attr_string (L_AttrMngr * func_attr, int cb_num, char * attr_name, char * attr_value)
Definition at line 239 of file attr_mngr.c.
References A_new_string_field(), and L_insert_cb_attr_list().
void L_insert_fn_attr (L_AttrMngr * func_attr, char * attr_name, long attr_value)
Definition at line 135 of file attr_mngr.c.
References L_insert_fn_attr_int().
void L_insert_fn_attr_float (L_AttrMngr * func_attr, char * attr_name, float attr_value)
Definition at line 152 of file attr_mngr.c.
References A_new_float_field(), and L_insert_fn_attr_list().
void L_insert_fn_attr_int (L_AttrMngr * func_attr, char * attr_name, long attr_value)
Definition at line 141 of file attr_mngr.c.
References A_new_int_field(), and L_insert_fn_attr_list().
Referenced by L_insert_fn_attr().
void L_insert_fn_attr_label (L_AttrMngr * func_attr, char * attr_name, char * attr_value)
Definition at line 174 of file attr_mngr.c.
References A_new_label_field(), and L_insert_fn_attr_list().
void L_insert_fn_attr_list (L_AttrMngr * func_attr, char * attr_name, A_Attr_Field ** field, int max_field)
Definition at line 185 of file attr_mngr.c.
References A_Attr_pool, A_Attr::field, L_AttrMngr::fn_attr, L_alloc(), A_Attr::name, A_Attr::next_attr, A_Attr::num_fields, and L_AttrMngr::num_fn_attr.
Referenced by L_insert_fn_attr_float(), L_insert_fn_attr_int(), L_insert_fn_attr_label(), and L_insert_fn_attr_string().
void L_insert_fn_attr_string (L_AttrMngr * func_attr, char * attr_name, char * attr_value)
Definition at line 163 of file attr_mngr.c.
References A_new_string_field(), and L_insert_fn_attr_list().
void L_insert_op_attr (L_AttrMngr * func_attr, int op_num, char * attr_name, long attr_value, int dep)
Definition at line 287 of file attr_mngr.c.
References L_insert_op_attr_int().
void L_insert_op_attr_float (L_AttrMngr * func_attr, int op_num, char * attr_name, float attr_value, int dep)
Definition at line 305 of file attr_mngr.c.
References A_new_float_field(), and L_insert_op_attr_list().
void L_insert_op_attr_int (L_AttrMngr * func_attr, int op_num, char * attr_name, long attr_value, int dep)
Definition at line 294 of file attr_mngr.c.
References A_new_int_field(), and L_insert_op_attr_list().
Referenced by L_insert_op_attr().
void L_insert_op_attr_label (L_AttrMngr * func_attr, int op_num, char * attr_name, char * attr_value, int dep)
Definition at line 327 of file attr_mngr.c.
References A_new_label_field(), and L_insert_op_attr_list().
void L_insert_op_attr_list (L_AttrMngr * func_attr, int op_num, char * attr_name, A_Attr_Field ** field, int max_field, int dep)
Definition at line 338 of file attr_mngr.c.
References A_Attr_pool, A_Attr::dep, A_Attr::field, A_Attr::id_num, L_alloc(), A_Attr::name, A_Attr::next_attr, A_Attr::num_fields, L_AttrMngr::num_op_attr, and L_AttrMngr::op_attr.
Referenced by L_insert_op_attr_float(), L_insert_op_attr_int(), L_insert_op_attr_label(), and L_insert_op_attr_string().
void L_insert_op_attr_string (L_AttrMngr * func_attr, int op_num, char * attr_name, char * attr_value, int dep)
Definition at line 316 of file attr_mngr.c.
References A_new_string_field(), and L_insert_op_attr_list().
void L_write_attr_to_file (FILE * out, L_AttrMngr * func_attr)
Definition at line 365 of file attr_mngr.c.
References A_FLOAT, A_INT, A_LABEL, A_STRING, AM_VERSION, A_Attr_Field::f, A_Attr::field, L_AttrMngr::fn_attr, L_AttrMngr::fn_name, A_Attr_Field::i, I_punt(), A_Attr_Field::l, A_Attr::name, A_Attr::next_attr, L_AttrMngr::num_cb_attr, A_Attr::num_fields, L_AttrMngr::num_fn_attr, L_AttrMngr::num_op_attr, A_Attr_Field::s, A_Attr_Field::type, A_Attr_Field::value, and L_AttrMngr::weight.
Variable Documentation
L_Alloc_Pool* A_Attr_pool = NULL
Definition at line 70 of file attr_mngr.c.
Referenced by L_create_AttrMngr(), L_free_Attr(), L_insert_cb_attr_list(), L_insert_fn_attr_list(), and L_insert_op_attr_list().
L_Alloc_Pool* L_AttrMngr_pool = NULL
Definition at line 69 of file attr_mngr.c.
Referenced by L_create_AttrMngr(), and L_free_AttrMngr().