attr_mngr.h File Reference
#include <config.h>
Data Structures
struct A_Attr_Field
struct A_Attr
struct L_AttrMngr
Defines
#define AM_VERSION 3
#define A_INT 0
#define A_FLOAT 1
#define A_STRING 2
#define A_LABEL 3
Functions
L_AttrMngr * L_create_AttrMngr (char *fn_name, float weight)
void L_insert_fn_attr (L_AttrMngr *func_attr, char *attr_name, long attr_value)
void L_insert_cb_attr (L_AttrMngr *func_attr, int cb_num, char *attr_name, long attr_value)
void L_insert_op_attr (L_AttrMngr *func_attr, int op_num, char *attr_name, long attr_value, int dep)
void L_insert_fn_attr_int (L_AttrMngr *func_attr, char *attr_name, long attr_value)
void L_insert_cb_attr_int (L_AttrMngr *func_attr, int cb_num, char *attr_name, long attr_value)
void L_insert_op_attr_int (L_AttrMngr *func_attr, int op_num, char *attr_name, long attr_value, int dep)
void L_insert_fn_attr_float (L_AttrMngr *func_attr, char *attr_name, float attr_value)
void L_insert_cb_attr_float (L_AttrMngr *func_attr, int cb_num, char *attr_name, float attr_value)
void L_insert_op_attr_float (L_AttrMngr *func_attr, int op_num, char *attr_name, float attr_value, int dep)
void L_insert_fn_attr_string (L_AttrMngr *func_attr, char *attr_name, char *attr_value)
void L_insert_cb_attr_string (L_AttrMngr *func_attr, int cb_num, char *attr_name, char *attr_value)
void L_insert_op_attr_string (L_AttrMngr *func_attr, int op_num, char *attr_name, char *attr_value, int dep)
void L_insert_fn_attr_label (L_AttrMngr *func_attr, char *attr_name, char *attr_value)
void L_insert_cb_attr_label (L_AttrMngr *func_attr, int cb_num, char *attr_name, char *attr_value)
void L_insert_op_attr_label (L_AttrMngr *func_attr, int op_num, char *attr_name, char *attr_value, int dep)
void L_insert_fn_attr_list (L_AttrMngr *func_attr, char *attr_name, A_Attr_Field **field, int max_field)
void L_insert_cb_attr_list (L_AttrMngr *func_attr, int cb_num, char *attr_name, A_Attr_Field **field, int max_field)
void L_insert_op_attr_list (L_AttrMngr *func_attr, int op_num, char *attr_name, A_Attr_Field **field, int max_field, int dep)
void L_write_attr_to_file (FILE *out, L_AttrMngr *func_attr)
void L_free_AttrMngr (L_AttrMngr *func_attr)
void L_free_Attr (A_Attr *Attr)
Define Documentation
#define A_FLOAT 1
Definition at line 68 of file attr_mngr.h.
Referenced by A_new_float_field(), and L_write_attr_to_file().
#define A_INT 0
Definition at line 67 of file attr_mngr.h.
Referenced by A_new_int_field(), and L_write_attr_to_file().
#define A_LABEL 3
Definition at line 70 of file attr_mngr.h.
Referenced by A_new_label_field(), and L_write_attr_to_file().
#define A_STRING 2
Definition at line 69 of file attr_mngr.h.
Referenced by A_new_string_field(), and L_write_attr_to_file().
#define AM_VERSION 3
Definition at line 65 of file attr_mngr.h.
Referenced by L_write_attr_to_file().
Function Documentation
L_AttrMngr* L_create_AttrMngr (char * fn_name, float weight)
Definition at line 73 of file attr_mngr.c.
References A_Attr_pool, L_AttrMngr::cb_attr, L_AttrMngr::fn_attr, L_AttrMngr::fn_name, L_alloc(), L_AttrMngr_pool, L_create_alloc_pool(), L_AttrMngr::num_cb_attr, L_AttrMngr::num_fn_attr, L_AttrMngr::num_op_attr, L_AttrMngr::op_attr, and L_AttrMngr::weight.
void L_free_Attr (A_Attr * Attr)
Definition at line 495 of file attr_mngr.c.
References A_Attr_pool, A_Attr::field, L_free(), A_Attr::next_attr, and A_Attr::num_fields.
Referenced by L_free_AttrMngr().
void L_free_AttrMngr (L_AttrMngr * func_attr)
Definition at line 486 of file attr_mngr.c.
References L_AttrMngr::cb_attr, L_AttrMngr::fn_attr, L_AttrMngr_pool, L_free(), L_free_Attr(), and L_AttrMngr::op_attr.
void L_insert_cb_attr (L_AttrMngr * func_attr, int cb_num, char * attr_name, long attr_value)
Definition at line 210 of file attr_mngr.c.
References L_insert_cb_attr_int().
void L_insert_cb_attr_float (L_AttrMngr * func_attr, int cb_num, char * attr_name, float attr_value)
Definition at line 228 of file attr_mngr.c.
References A_new_float_field(), and L_insert_cb_attr_list().
void L_insert_cb_attr_int (L_AttrMngr * func_attr, int cb_num, char * attr_name, long attr_value)
Definition at line 217 of file attr_mngr.c.
References A_new_int_field(), and L_insert_cb_attr_list().
Referenced by L_insert_cb_attr().
void L_insert_cb_attr_label (L_AttrMngr * func_attr, int cb_num, char * attr_name, char * attr_value)
Definition at line 250 of file attr_mngr.c.
References A_new_label_field(), and L_insert_cb_attr_list().
void L_insert_cb_attr_list (L_AttrMngr * func_attr, int cb_num, char * attr_name, A_Attr_Field ** field, int max_field)
Definition at line 261 of file attr_mngr.c.
References A_Attr_pool, L_AttrMngr::cb_attr, A_Attr::field, A_Attr::id_num, L_alloc(), A_Attr::name, A_Attr::next_attr, L_AttrMngr::num_cb_attr, and A_Attr::num_fields.
Referenced by L_insert_cb_attr_float(), L_insert_cb_attr_int(), L_insert_cb_attr_label(), and L_insert_cb_attr_string().
void L_insert_cb_attr_string (L_AttrMngr * func_attr, int cb_num, char * attr_name, char * attr_value)
Definition at line 239 of file attr_mngr.c.
References A_new_string_field(), and L_insert_cb_attr_list().
void L_insert_fn_attr (L_AttrMngr * func_attr, char * attr_name, long attr_value)
Definition at line 135 of file attr_mngr.c.
References L_insert_fn_attr_int().
void L_insert_fn_attr_float (L_AttrMngr * func_attr, char * attr_name, float attr_value)
Definition at line 152 of file attr_mngr.c.
References A_new_float_field(), and L_insert_fn_attr_list().
void L_insert_fn_attr_int (L_AttrMngr * func_attr, char * attr_name, long attr_value)
Definition at line 141 of file attr_mngr.c.
References A_new_int_field(), and L_insert_fn_attr_list().
Referenced by L_insert_fn_attr().
void L_insert_fn_attr_label (L_AttrMngr * func_attr, char * attr_name, char * attr_value)
Definition at line 174 of file attr_mngr.c.
References A_new_label_field(), and L_insert_fn_attr_list().
void L_insert_fn_attr_list (L_AttrMngr * func_attr, char * attr_name, A_Attr_Field ** field, int max_field)
Definition at line 185 of file attr_mngr.c.
References A_Attr_pool, A_Attr::field, L_AttrMngr::fn_attr, L_alloc(), A_Attr::name, A_Attr::next_attr, A_Attr::num_fields, and L_AttrMngr::num_fn_attr.
Referenced by L_insert_fn_attr_float(), L_insert_fn_attr_int(), L_insert_fn_attr_label(), and L_insert_fn_attr_string().
void L_insert_fn_attr_string (L_AttrMngr * func_attr, char * attr_name, char * attr_value)
Definition at line 163 of file attr_mngr.c.
References A_new_string_field(), and L_insert_fn_attr_list().
void L_insert_op_attr (L_AttrMngr * func_attr, int op_num, char * attr_name, long attr_value, int dep)
Definition at line 287 of file attr_mngr.c.
References L_insert_op_attr_int().
void L_insert_op_attr_float (L_AttrMngr * func_attr, int op_num, char * attr_name, float attr_value, int dep)
Definition at line 305 of file attr_mngr.c.
References A_new_float_field(), and L_insert_op_attr_list().
void L_insert_op_attr_int (L_AttrMngr * func_attr, int op_num, char * attr_name, long attr_value, int dep)
Definition at line 294 of file attr_mngr.c.
References A_new_int_field(), and L_insert_op_attr_list().
Referenced by L_insert_op_attr().
void L_insert_op_attr_label (L_AttrMngr * func_attr, int op_num, char * attr_name, char * attr_value, int dep)
Definition at line 327 of file attr_mngr.c.
References A_new_label_field(), and L_insert_op_attr_list().
void L_insert_op_attr_list (L_AttrMngr * func_attr, int op_num, char * attr_name, A_Attr_Field ** field, int max_field, int dep)
Definition at line 338 of file attr_mngr.c.
References A_Attr_pool, A_Attr::dep, A_Attr::field, A_Attr::id_num, L_alloc(), A_Attr::name, A_Attr::next_attr, A_Attr::num_fields, L_AttrMngr::num_op_attr, and L_AttrMngr::op_attr.
Referenced by L_insert_op_attr_float(), L_insert_op_attr_int(), L_insert_op_attr_label(), and L_insert_op_attr_string().
void L_insert_op_attr_string (L_AttrMngr * func_attr, int op_num, char * attr_name, char * attr_value, int dep)
Definition at line 316 of file attr_mngr.c.
References A_new_string_field(), and L_insert_op_attr_list().
void L_write_attr_to_file (FILE * out, L_AttrMngr * func_attr)
Definition at line 365 of file attr_mngr.c.
References A_FLOAT, A_INT, A_LABEL, A_STRING, AM_VERSION, A_Attr_Field::f, A_Attr::field, L_AttrMngr::fn_attr, L_AttrMngr::fn_name, A_Attr_Field::i, I_punt(), A_Attr_Field::l, A_Attr::name, A_Attr::next_attr, L_AttrMngr::num_cb_attr, A_Attr::num_fields, L_AttrMngr::num_fn_attr, L_AttrMngr::num_op_attr, A_Attr_Field::s, A_Attr_Field::type, A_Attr_Field::value, and L_AttrMngr::weight.