block_sparse_array.c File Reference
#include <config.h>
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include <stdio.h>
#include <library/i_error.h>
#include `block_sparse_array.h`
Functions
static void AllocateData (BlockSparseArray block, int index, int length)
static BlockSparseArray ExtractBlock (BlockSparseArray block, int index, int length)
static void MergeBlocks (BlockSparseArray *array, int index, int length)
static int GetBlock (BlockSparseArray *array, int index)
static void GetOrAddBlock (BlockSparseArray *array, int index, int length)
BlockSparseArray NewBlockSparseArray ()
void FreeBlockSparseArray (BlockSparseArray array)
void BlockSparseArraySet (BlockSparseArray *array, int index, void *data)
void BlockSparseArrayClear (BlockSparseArray *array, int index)
void * BlockSparseArrayGet (BlockSparseArray *array, int index)
int BlockSparseArrayGetFirstIndex (BlockSparseArray *array)
int BlockSparseArrayGetNextIndex (BlockSparseArray *array, int index)
int BlockSparseArrayGetFirstNonZeroIndex (BlockSparseArray *array)
int BlockSparseArrayGetNextNonZeroIndex (BlockSparseArray *array, int index)
void * BlockSparseArrayGetFirstNonZero (BlockSparseArray *array, int *index)
void * BlockSparseArrayGetNextNonZero (BlockSparseArray *array, int *index)
void BlockSparseArraySetOption (BlockSparseArray array, int option)
void BlockSparseArrayClrOption (BlockSparseArray array, int option)
void BlockSparseArrayPrepare (BlockSparseArray *array, int index, int length)
void BlockSparseArrayCompact (BlockSparseArray *array)
void BlockSparseArrayDump (BlockSparseArray array, FILE *out, void(*print_func)(FILE *out, void *data))
Function Documentation
static void AllocateData (BlockSparseArray block, int index, int length) [static]
Definition at line 597 of file block_sparse_array.c.
References BSA_BLOCK_INDEX, BSA_BLOCK_LENGTH, _BlockSparseArray::data, _BlockSparseArray::first_index, I_punt(), _BlockSparseArray::length, and NULL.
Referenced by ExtractBlock(), GetOrAddBlock(), and MergeBlocks().
void BlockSparseArrayClear (BlockSparseArray * array, int index)
Definition at line 156 of file block_sparse_array.c.
References GetOrAddBlock(), I_punt(), and NULL.
void BlockSparseArrayClrOption (BlockSparseArray array, int option)
Definition at line 403 of file block_sparse_array.c.
References _BlockSparseArray::next, _BlockSparseArray::options, and _BlockSparseArray::prev.
Referenced by MergeBlocks().
void BlockSparseArrayCompact (BlockSparseArray * array)
Definition at line 431 of file block_sparse_array.c.
References BLOCK_SIZE, BSA_BLOCK_INDEX, _BlockSparseArray::data, ExtractBlock(), _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
void BlockSparseArrayDump (BlockSparseArray array, FILE * out, void(*)(FILE *out, void *data) print_func)
Definition at line 552 of file block_sparse_array.c.
References _BlockSparseArray::next, and _BlockSparseArray::prev.
void* BlockSparseArrayGet (BlockSparseArray * array, int index)
Definition at line 172 of file block_sparse_array.c.
References GetBlock(), and NULL.
int BlockSparseArrayGetFirstIndex (BlockSparseArray * array)
Definition at line 185 of file block_sparse_array.c.
void* BlockSparseArrayGetFirstNonZero (BlockSparseArray * array, int * index)
Definition at line 311 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
int BlockSparseArrayGetFirstNonZeroIndex (BlockSparseArray * array)
Definition at line 236 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
int BlockSparseArrayGetNextIndex (BlockSparseArray * array, int index)
Definition at line 201 of file block_sparse_array.c.
References GetBlock().
void* BlockSparseArrayGetNextNonZero (BlockSparseArray * array, int * index)
Definition at line 342 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, GetBlock(), _BlockSparseArray::length, _BlockSparseArray::next, and NULL.
int BlockSparseArrayGetNextNonZeroIndex (BlockSparseArray * array, int index)
Definition at line 264 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, GetBlock(), _BlockSparseArray::length, _BlockSparseArray::next, and NULL.
void BlockSparseArrayPrepare (BlockSparseArray * array, int index, int length)
Definition at line 421 of file block_sparse_array.c.
References GetOrAddBlock().
void BlockSparseArraySet (BlockSparseArray * array, int index, void * data)
Definition at line 132 of file block_sparse_array.c.
References BSA_WARN_ON_OVERWRITE, GetOrAddBlock(), I_punt(), I_warn(), and NULL.
void BlockSparseArraySetOption (BlockSparseArray array, int option)
Definition at line 389 of file block_sparse_array.c.
References _BlockSparseArray::next, _BlockSparseArray::options, and _BlockSparseArray::prev.
static BlockSparseArray ExtractBlock (BlockSparseArray block, int index, int length) [static]
Definition at line 617 of file block_sparse_array.c.
References AllocateData(), _BlockSparseArray::data, _BlockSparseArray::first_index, _BlockSparseArray::length, NewBlockSparseArray(), and _BlockSparseArray::options.
Referenced by BlockSparseArrayCompact().
void FreeBlockSparseArray (BlockSparseArray array)
Definition at line 96 of file block_sparse_array.c.
References BSA_CHECK_NULL_ON_FREE, _BlockSparseArray::data, _BlockSparseArray::first_index, FreeBlockSparseArray(), I_warn(), _BlockSparseArray::length, _BlockSparseArray::next, NULL, _BlockSparseArray::options, and _BlockSparseArray::prev.
Referenced by FreeBlockSparseArray(), and MergeBlocks().
static int GetBlock (BlockSparseArray * array, int index) [static]
Definition at line 739 of file block_sparse_array.c.
References _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
Referenced by BlockSparseArrayGet(), BlockSparseArrayGetNextIndex(), BlockSparseArrayGetNextNonZero(), BlockSparseArrayGetNextNonZeroIndex(), and MergeBlocks().
static void GetOrAddBlock (BlockSparseArray * array, int index, int length) [static]
Definition at line 780 of file block_sparse_array.c.
References AllocateData(), BSA_BLOCK_INDEX, BSA_BLOCK_LENGTH, _BlockSparseArray::first_index, I_punt(), _BlockSparseArray::length, MergeBlocks(), NewBlockSparseArray(), _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
Referenced by BlockSparseArrayClear(), BlockSparseArrayPrepare(), and BlockSparseArraySet().
static void MergeBlocks (BlockSparseArray * array, int index, int length) [static]
Definition at line 644 of file block_sparse_array.c.
References AllocateData(), BLOCK_SIZE, BlockSparseArrayClrOption(), BSA_CHECK_NULL_ON_FREE, _BlockSparseArray::data, _BlockSparseArray::first_index, FreeBlockSparseArray(), GetBlock(), _BlockSparseArray::length, NewBlockSparseArray(), _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
Referenced by GetOrAddBlock().
BlockSparseArray NewBlockSparseArray ()
Definition at line 81 of file block_sparse_array.c.
References I_punt(), and NULL.
Referenced by ExtractBlock(), GetOrAddBlock(), and MergeBlocks().