block_sparse_array.h File Reference
#include <config.h>
#include <stdio.h>
Data Structures
struct _BlockSparseArray
Defines
#define BLOCK_SIZE 32
#define BSA_WARN_ON_OVERWRITE 0x0000000000000001
#define BSA_CHECK_NULL_ON_FREE 0x0000000000000002
#define BSA_BLOCK_INDEX(i) (i) - ((i) % BLOCK_SIZE)
#define BSA_BLOCK_LENGTH(i, l)
Typedefs
typedef _BlockSparseArray * BlockSparseArray
Functions
BlockSparseArray NewBlockSparseArray ()
void FreeBlockSparseArray (BlockSparseArray array)
void BlockSparseArraySet (BlockSparseArray *array, int index, void *data)
void BlockSparseArrayClear (BlockSparseArray *array, int index)
void * BlockSparseArrayGet (BlockSparseArray *array, int index)
int BlockSparseArrayGetFirstIndex (BlockSparseArray *array)
int BlockSparseArrayGetNextIndex (BlockSparseArray *array, int index)
int BlockSparseArrayGetFirstNonZeroIndex (BlockSparseArray *array)
int BlockSparseArrayGetNextNonZeroIndex (BlockSparseArray *array, int index)
void * BlockSparseArrayGetFirstNonZero (BlockSparseArray *array, int *index)
void * BlockSparseArrayGetNextNonZero (BlockSparseArray *array, int *index)
void BlockSparseArraySetOption (BlockSparseArray array, int option)
void BlockSparseArrayClrOption (BlockSparseArray array, int option)
void BlockSparseArrayPrepare (BlockSparseArray *array, int index, int length)
void BlockSparseArrayCompact (BlockSparseArray *array)
void BlockSparseArrayDump (BlockSparseArray array, FILE *out, void(*print_func)(FILE *out, void *data))
Define Documentation
#define BLOCK_SIZE 32
Definition at line 78 of file block_sparse_array.h.
Referenced by BlockSparseArrayCompact(), and MergeBlocks().
#define BSA_BLOCK_INDEX(i) (i) - ((i) % BLOCK_SIZE)
Definition at line 94 of file block_sparse_array.h.
Referenced by AllocateData(), BlockSparseArrayCompact(), and GetOrAddBlock().
#define BSA_BLOCK_LENGTH(i, l)
Value:
(BLOCK_SIZE - (((i) + (l) - 1) % BLOCK_SIZE) + \
                                (l) - 1 + ((i) % BLOCK_SIZE))
Definition at line 100 of file block_sparse_array.h.
Referenced by AllocateData(), and GetOrAddBlock().
#define BSA_CHECK_NULL_ON_FREE 0x0000000000000002
Definition at line 86 of file block_sparse_array.h.
Referenced by FreeBlockSparseArray(), and MergeBlocks().
#define BSA_WARN_ON_OVERWRITE 0x0000000000000001
Definition at line 83 of file block_sparse_array.h.
Referenced by BlockSparseArraySet().
Typedef Documentation
typedef struct _BlockSparseArray * BlockSparseArray
Function Documentation
void BlockSparseArrayClear (BlockSparseArray * array, int index)
Definition at line 156 of file block_sparse_array.c.
References GetOrAddBlock(), I_punt(), and NULL.
void BlockSparseArrayClrOption (BlockSparseArray array, int option)
Definition at line 403 of file block_sparse_array.c.
References _BlockSparseArray::next, _BlockSparseArray::options, and _BlockSparseArray::prev.
Referenced by MergeBlocks().
void BlockSparseArrayCompact (BlockSparseArray * array)
Definition at line 431 of file block_sparse_array.c.
References BLOCK_SIZE, BSA_BLOCK_INDEX, _BlockSparseArray::data, ExtractBlock(), _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
void BlockSparseArrayDump (BlockSparseArray array, FILE * out, void(*)(FILE *out, void *data) print_func)
Definition at line 552 of file block_sparse_array.c.
References _BlockSparseArray::next, and _BlockSparseArray::prev.
void* BlockSparseArrayGet (BlockSparseArray * array, int index)
Definition at line 172 of file block_sparse_array.c.
References GetBlock(), and NULL.
int BlockSparseArrayGetFirstIndex (BlockSparseArray * array)
Definition at line 185 of file block_sparse_array.c.
void* BlockSparseArrayGetFirstNonZero (BlockSparseArray * array, int * index)
Definition at line 311 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
int BlockSparseArrayGetFirstNonZeroIndex (BlockSparseArray * array)
Definition at line 236 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, _BlockSparseArray::length, _BlockSparseArray::next, NULL, and _BlockSparseArray::prev.
int BlockSparseArrayGetNextIndex (BlockSparseArray * array, int index)
Definition at line 201 of file block_sparse_array.c.
References GetBlock().
void* BlockSparseArrayGetNextNonZero (BlockSparseArray * array, int * index)
Definition at line 342 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, GetBlock(), _BlockSparseArray::length, _BlockSparseArray::next, and NULL.
int BlockSparseArrayGetNextNonZeroIndex (BlockSparseArray * array, int index)
Definition at line 264 of file block_sparse_array.c.
References _BlockSparseArray::data, _BlockSparseArray::first_index, GetBlock(), _BlockSparseArray::length, _BlockSparseArray::next, and NULL.
void BlockSparseArrayPrepare (BlockSparseArray * array, int index, int length)
Definition at line 421 of file block_sparse_array.c.
References GetOrAddBlock().
void BlockSparseArraySet (BlockSparseArray * array, int index, void * data)
Definition at line 132 of file block_sparse_array.c.
References BSA_WARN_ON_OVERWRITE, GetOrAddBlock(), I_punt(), I_warn(), and NULL.
void BlockSparseArraySetOption (BlockSparseArray array, int option)
Definition at line 389 of file block_sparse_array.c.
References _BlockSparseArray::next, _BlockSparseArray::options, and _BlockSparseArray::prev.
void FreeBlockSparseArray (BlockSparseArray array)
Definition at line 96 of file block_sparse_array.c.
References BSA_CHECK_NULL_ON_FREE, _BlockSparseArray::data, _BlockSparseArray::first_index, FreeBlockSparseArray(), I_warn(), _BlockSparseArray::length, _BlockSparseArray::next, NULL, _BlockSparseArray::options, and _BlockSparseArray::prev.
Referenced by FreeBlockSparseArray(), and MergeBlocks().
BlockSparseArray NewBlockSparseArray ()
Definition at line 81 of file block_sparse_array.c.
References I_punt(), and NULL.
Referenced by ExtractBlock(), GetOrAddBlock(), and MergeBlocks().