c_basic.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <signal.h>
#include <unistd.h>
#include <time.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/c_basic.h>
Data Structures
struct _Str
Defines
#define NUM_BITS 32
#define MAX_FILE 512
#define MAX_NAME_LENGTH 512
#define INIT_FILE {if (!init) init_file();}
Typedefs
typedef _Str * Str
Functions
int C_is_space (int ch)
int C_is_alpha (int ch)
int C_is_lower (int ch)
int C_is_upper (int ch)
int C_is_digit (int ch)
int C_is_alpha_numeric (int ch)
int C_to_lower (int ch)
int C_to_upper (int ch)
int C_is_hex_digit (int ch)
int C_is_oct_digit (int ch)
int C_is_control (int ch)
int C_is_graph (int ch)
int C_log2 (C_Integer n)
int C_is_log2 (C_Integer n)
C_Integer C_pow2 (int n)
C_Integer C_mask (int n)
int C_strlen (C_String str)
C_String C_strcpy (C_String dst, C_String src)
C_String C_strncpy (C_String dst, C_String src, int n)
C_String C_strcat (C_String dst, C_String src)
C_String C_strncat (C_String dst, C_String src, int n)
int C_strcmp (C_String str1, C_String str2)
int C_strncmp (C_String str1, C_String str2, int n)
C_String C_strchr (C_String str, int ch)
C_String C_strrchr (C_String str, int ch)
int C_strspn (C_String str, C_String ct)
int C_strcspn (C_String str, C_String ct)
C_String C_strpbrk (C_String str, C_String ct)
C_String C_strstr (C_String str1, C_String str2)
C_String C_strrstr (C_String str1, C_String str2)
C_String C_strsave (C_String str)
int C_str2char (C_String str)
C_String C_savestr (C_String str)
static Str FindS (Str T, C_String str)
static Str AddS (Str T, C_String str)
static Str FindAndAddS (Str T, C_String str, Str *node)
C_String C_findstr (C_String str)
C_Pointer C_addptr (C_String str, C_Pointer ptr)
C_Pointer C_findptr (C_String str)
static void VisitS (Str T, int(*fn)(C_String name, C_Pointer ptr))
void C_for_all_ptr (int(*fn)(C_String name, C_Pointer ptr))
C_Float C_string_to_float (C_String str)
C_String C_float_to_string (C_Float value, C_String line)
C_Double C_string_to_double (C_String str)
C_String C_double_to_string (C_Double value, C_String line)
C_Integer C_string_to_char (C_String str)
C_String C_char_to_string (int value, C_String line)
C_Integer C_string_to_integer (C_String str)
C_String C_integer_to_string (C_Integer value, C_String line)
C_Integer C_string_to_hex (C_String str)
C_String C_hex_to_string (C_Integer value, C_String line)
C_Integer C_string_to_oct (C_String str)
C_String C_oct_to_string (C_Integer value, C_String line)
void C_abort (void)
void C_exit (int status)
void C_assert (int expression, char *error_mesg)
C_Pointer C_calloc (int num_obj, int size_obj)
C_Pointer C_malloc (int size)
C_Pointer C_calloc2 (int num_obj, int size_obj)
C_Pointer C_malloc2 (int size)
void C_free (C_Pointer ptr)
static void init_file (void)
static int find_file (char *name)
static int new_file (char *name)
static void free_file (int i)
C_File C_open_file (C_String file_name, int mode)
int C_flush_file (C_File file)
int C_close_file (C_File file)
int C_create_tmp_file (C_String name)
int C_remove_file (C_String name)
int C_rename_file (C_String name, C_String new_name)
int C_destroy_directory (C_String dir_name)
static C_String index_file (C_String db_prefix)
static int add_record_index (C_String db_prefix, C_String name)
static int delete_record_index (C_String db_prefix, C_String name)
static int destroy_all_records (C_String db_name)
int C_database_size (C_String db_name)
int C_destroy_database (C_String db_name)
int C_disconnect_database (C_String db_name)
C_File C_read_record (C_String record_name)
C_File C_write_record (C_String record_name)
int C_destroy_record (C_String record_name)
C_String C_file_name (C_File file)
int C_eof (C_File file)
int C_read_char (C_File file, C_Integer *value)
int C_read_word (C_File file, C_String line, int length)
int C_read_integer (C_File file, C_Integer *value)
int C_read_float (C_File file, C_Float *value)
int C_read_double (C_File file, C_Double *value)
int C_read_line (C_File file, C_String line, int length)
int C_read_block (C_File file, C_String line, int length)
int C_write_char (C_File file, C_Integer value)
int C_write_word (C_File file, C_String line)
int C_write_line (C_File file, C_String line)
int C_write_block (C_File file, C_String line, int length)
int C_write_integer (C_File file, C_Integer value)
int C_write_float (C_File file, C_Float value)
int C_write_double (C_File file, C_Double value)
long C_time (void)
char * C_asctime (time_t tm)
static void RemoveS (Str ptr)
void C_RemoveAllString ()
Variables
static unsigned long p2 [32]
static unsigned long m2 [33]
static Str str_root = 0
static int string_count
static int string_length
xx xx xx xx xx xx xx xx xx
struct {
 short defined
 short eof
 short mode
 char * name
 FILE * F
} files [MAX_FILE]
static int init = 0
int errno
static C_String db_prefix = 0
static char db_index [MAX_NAME_LENGTH]
Define Documentation
#define INIT_FILE {if (!init) init_file();}
Definition at line 880 of file c_basic.c.
Referenced by C_close_file(), C_create_tmp_file(), C_eof(), C_file_name(), C_flush_file(), C_open_file(), C_read_block(), C_read_char(), C_read_double(), C_read_float(), C_read_integer(), C_read_line(), C_read_word(), C_write_block(), C_write_char(), C_write_double(), C_write_float(), C_write_integer(), C_write_line(), and C_write_word().
#define MAX_FILE 512
Definition at line 867 of file c_basic.c.
Referenced by C_close_file(), C_eof(), C_file_name(), C_flush_file(), C_read_block(), C_read_char(), C_read_double(), C_read_float(), C_read_integer(), C_read_line(), C_read_word(), C_write_block(), C_write_char(), C_write_double(), C_write_float(), C_write_integer(), C_write_line(), C_write_word(), find_file(), init_file(), and new_file().
#define MAX_NAME_LENGTH 512
Definition at line 868 of file c_basic.c.
Referenced by C_database_size(), C_destroy_record(), C_read_record(), C_write_record(), delete_record_index(), and destroy_all_records().
#define NUM_BITS 32
Definition at line 166 of file c_basic.c.
Referenced by C_is_log2(), C_log2(), C_mask(), and C_pow2().
Typedef Documentation
typedef struct _Str * Str
Function Documentation
static int add_record_index (C_String db_prefix, C_String name) [static]
Definition at line 1077 of file c_basic.c.
References C_assert(), C_BAD_INDEX, C_close_file(), C_OPEN_APPEND_ONLY, C_open_file(), C_SUCCESS, C_write_line(), and index_file().
Referenced by C_write_record().
static Str AddS (Str T, C_String str) [static]
Definition at line 465 of file c_basic.c.
References C_malloc2(), C_savestr(), C_strcmp(), _Str::left, _Str::name, _Str::ptr, and _Str::right.
Referenced by AddS(), C_addptr(), and FindString().
void C_abort (void)
Definition at line 802 of file c_basic.c.
C_Pointer C_addptr (C_String str, C_Pointer ptr)
Definition at line 569 of file c_basic.c.
References AddS(), C_assert(), FindS(), _Str::ptr, and str_root.
char* C_asctime (time_t tm)
Definition at line 1450 of file c_basic.c.
void C_assert (int expression, char * error_mesg)
Definition at line 812 of file c_basic.c.
References C_exit().
Referenced by add_record_index(), C2_init_scope(), C2_kill_scope_above(), C2_reset_attribute(), C2_scope_in(), C2_scope_out(), C_addptr(), C_calloc2(), C_clear(), C_clear_attr(), C_clear_free_all(), C_clear_free_name(), C_delete(), C_delete_tbl(), C_destroy_record(), C_find(), C_find_from_index(), C_find_index(), C_findptr(), C_findstr(), C_forall(), C_full(), C_get_arg(), C_malloc2(), C_open(), C_open_file(), C_read_record(), C_strsave(), C_unique_name(), C_update(), C_write_record(), delete_record_index(), find_symbol(), and new_file().
C_Pointer C_calloc (int num_obj, int size_obj)
Definition at line 828 of file c_basic.c.
Referenced by C_calloc2().
C_Pointer C_calloc2 (int num_obj, int size_obj)
Definition at line 844 of file c_basic.c.
References C_assert(), and C_calloc().
C_String C_char_to_string (int value, C_String line)
Definition at line 716 of file c_basic.c.
References C_ALERT, C_BS, C_CR, C_FF, C_HT, C_is_control(), C_is_graph(), C_NL, C_S_QUOTE, and C_VT.
int C_close_file (C_File file)
Definition at line 996 of file c_basic.c.
References C_FAILURE, C_SUCCESS, defined, F, files, free_file(), INIT_FILE, and MAX_FILE.
Referenced by add_record_index(), C_database_size(), delete_record_index(), destroy_all_records(), S_store_record(), and S_sum_of_column().
int C_create_tmp_file (C_String name)
Definition at line 1008 of file c_basic.c.
References C_open_file(), C_OPEN_WRITE_ONLY, C_strcpy(), and INIT_FILE.
Referenced by delete_record_index().
int C_database_size (C_String db_name)
Definition at line 1139 of file c_basic.c.
References C_BAD_INDEX, C_close_file(), C_eof(), C_open_file(), C_OPEN_READ_ONLY, C_read_line(), index_file(), and MAX_NAME_LENGTH.
int C_destroy_database (C_String db_name)
Definition at line 1160 of file c_basic.c.
References C_destroy_directory(), and destroy_all_records().
int C_destroy_directory (C_String dir_name)
Definition at line 1053 of file c_basic.c.
References C_FAILURE, and C_SUCCESS.
Referenced by C_destroy_database().
int C_destroy_record (C_String record_name)
Definition at line 1192 of file c_basic.c.
References C_assert(), C_remove_file(), delete_record_index(), MAX_NAME_LENGTH, and name.
int C_disconnect_database (C_String db_name)
Definition at line 1167 of file c_basic.c.
References C_SUCCESS.
C_String C_double_to_string (C_Double value, C_String line)
Definition at line 630 of file c_basic.c.
int C_eof (C_File file)
Definition at line 1216 of file c_basic.c.
References defined, files, INIT_FILE, and MAX_FILE.
Referenced by C_database_size(), delete_record_index(), destroy_all_records(), and S_sum_of_column().
void C_exit (int status)
Definition at line 807 of file c_basic.c.
Referenced by C_assert().
C_String C_file_name (C_File file)
Definition at line 1206 of file c_basic.c.
References defined, files, INIT_FILE, and MAX_FILE.
C_Pointer C_findptr (C_String str)
Definition at line 585 of file c_basic.c.
References C_assert(), FindS(), _Str::ptr, and str_root.
C_String C_findstr (C_String str)
Definition at line 557 of file c_basic.c.
References C_assert(), FindAndAddS(), _Str::ptr, and str_root.
Referenced by AddArgument(), and ChangeArgument().
C_String C_float_to_string (C_Float value, C_String line)
Definition at line 621 of file c_basic.c.
int C_flush_file (C_File file)
Definition at line 983 of file c_basic.c.
References C_FAILURE, C_OPEN_READ_ONLY, C_SUCCESS, defined, F, files, INIT_FILE, MAX_FILE, and mode.
void C_for_all_ptr (int(*)(C_String name, C_Pointer ptr) fn)
Definition at line 609 of file c_basic.c.
References str_root, and VisitS().
void C_free (C_Pointer ptr)
Definition at line 859 of file c_basic.c.
C_String C_hex_to_string (C_Integer value, C_String line)
Definition at line 781 of file c_basic.c.
References ITintmaxhexfmt.
C_String C_integer_to_string (C_Integer value, C_String line)
Definition at line 770 of file c_basic.c.
References ITintmaxformat.
int C_is_alpha (int ch)
Definition at line 92 of file c_basic.c.
Referenced by C_is_alpha_numeric().
int C_is_alpha_numeric (int ch)
Definition at line 112 of file c_basic.c.
References C_is_alpha(), and C_is_digit().
Referenced by C_string_to_char().
int C_is_control (int ch)
Definition at line 152 of file c_basic.c.
Referenced by C_char_to_string().
int C_is_digit (int ch)
Definition at line 107 of file c_basic.c.
Referenced by C_is_alpha_numeric().
int C_is_graph (int ch)
Definition at line 159 of file c_basic.c.
Referenced by C_char_to_string().
int C_is_hex_digit (int ch)
Definition at line 141 of file c_basic.c.
int C_is_log2 (C_Integer n)
Definition at line 253 of file c_basic.c.
References NUM_BITS, and p2.
int C_is_lower (int ch)
Definition at line 97 of file c_basic.c.
Referenced by C_to_upper().
int C_is_oct_digit (int ch)
Definition at line 147 of file c_basic.c.
Referenced by C_string_to_char().
int C_is_space (int ch)
Definition at line 86 of file c_basic.c.
References C_CR, C_FF, C_HT, C_NL, and C_VT.
Referenced by C_read_word().
int C_is_upper (int ch)
Definition at line 102 of file c_basic.c.
Referenced by C_to_lower().
int C_log2 (C_Integer n)
Definition at line 242 of file c_basic.c.
References NUM_BITS, and p2.
C_Pointer C_malloc (int size)
Definition at line 834 of file c_basic.c.
Referenced by C_malloc2(), C_strsave(), and new_node().
C_Pointer C_malloc2 (int size)
Definition at line 851 of file c_basic.c.
References C_assert(), and C_malloc().
Referenced by AddS(), C_savestr(), and FindAndAddS().
C_Integer C_mask (int n)
Definition at line 271 of file c_basic.c.
References m2, and NUM_BITS.
C_String C_oct_to_string (C_Integer value, C_String line)
Definition at line 792 of file c_basic.c.
References ITintmaxoctfmt.
C_File C_open_file (C_String file_name, int mode)
Definition at line 952 of file c_basic.c.
References C_assert(), C_BAD_INDEX, C_OPEN_APPEND_ONLY, C_OPEN_READ_ONLY, C_OPEN_WRITE_ONLY, F, files, find_file(), INIT_FILE, new_file(), and NULL.
Referenced by add_record_index(), C_create_tmp_file(), C_database_size(), C_read_record(), C_write_record(), delete_record_index(), destroy_all_records(), S_create_record(), and S_sum_of_column().
C_Integer C_pow2 (int n)
Definition at line 265 of file c_basic.c.
References NUM_BITS, and p2.
int C_read_block (C_File file, C_String line, int length)
Definition at line 1345 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_char (C_File file, C_Integer * value)
Definition at line 1226 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_double (C_File file, C_Double * value)
Definition at line 1304 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_float (C_File file, C_Float * value)
Definition at line 1288 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_integer (C_File file, C_Integer * value)
Definition at line 1276 of file c_basic.c.
References defined, F, files, INIT_FILE, ITintmaxformat, and MAX_FILE.
int C_read_line (C_File file, C_String line, int length)
Definition at line 1320 of file c_basic.c.
References C_NL, defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by C_database_size(), delete_record_index(), destroy_all_records(), and S_sum_of_column().
C_File C_read_record (C_String record_name)
Definition at line 1172 of file c_basic.c.
References C_assert(), C_open_file(), C_OPEN_READ_ONLY, MAX_NAME_LENGTH, and name.
int C_read_word (C_File file, C_String line, int length)
Definition at line 1242 of file c_basic.c.
References C_is_space(), defined, F, files, INIT_FILE, and MAX_FILE.
int C_remove_file (C_String name)
Definition at line 1020 of file c_basic.c.
References C_FAILURE, and C_SUCCESS.
Referenced by C_destroy_record(), delete_record_index(), and destroy_all_records().
void C_RemoveAllString ()
Definition at line 1471 of file c_basic.c.
References RemoveS(), and str_root.
int C_rename_file (C_String name, C_String new_name)
Definition at line 1033 of file c_basic.c.
References C_BAD_INDEX, C_FAILURE, and C_SUCCESS.
Referenced by delete_record_index().
C_String C_savestr (C_String str)
Definition at line 440 of file c_basic.c.
References C_malloc2(), C_strcpy(), and C_strlen().
Referenced by AddS(), C_get_arg(), and FindAndAddS().
int C_str2char (C_String str)
Definition at line 383 of file c_basic.c.
References C_ALERT, C_BS, C_CR, C_FF, C_HT, C_NL, C_NU, and C_VT.
C_String C_strcat (C_String dst, C_String src)
Definition at line 295 of file c_basic.c.
C_String C_strchr (C_String str, int ch)
Definition at line 313 of file c_basic.c.
int C_strcmp (C_String str1, C_String str2)
Definition at line 304 of file c_basic.c.
Referenced by AddS(), find_file(), FindAndAddS(), and FindS().
C_String C_strcpy (C_String dst, C_String src)
Definition at line 287 of file c_basic.c.
Referenced by C_create_tmp_file(), and C_savestr().
int C_strcspn (C_String str, C_String ct)
Definition at line 327 of file c_basic.c.
C_Integer C_string_to_char (C_String str)
Definition at line 635 of file c_basic.c.
References C_ALERT, C_BACKSLASH, C_BS, C_CR, C_FF, C_HT, C_is_alpha_numeric(), C_is_oct_digit(), C_NL, C_QUESTION, C_string_to_hex(), C_string_to_oct(), and C_VT.
C_Double C_string_to_double (C_String str)
Definition at line 626 of file c_basic.c.
References atof().
Referenced by yylex().
C_Float C_string_to_float (C_String str)
Definition at line 617 of file c_basic.c.
References atof().
C_Integer C_string_to_hex (C_String str)
Definition at line 775 of file c_basic.c.
References ITintmaxhexfmt.
Referenced by C_string_to_char(), and yylex().
C_Integer C_string_to_integer (C_String str)
Definition at line 764 of file c_basic.c.
References ITintmaxformat.
Referenced by yylex().
C_Integer C_string_to_oct (C_String str)
Definition at line 786 of file c_basic.c.
References ITintmaxoctfmt.
Referenced by C_string_to_char(), and yylex().
int C_strlen (C_String str)
Definition at line 281 of file c_basic.c.
Referenced by C_savestr(), find_empty_entry(), and find_symbol().
C_String C_strncat (C_String dst, C_String src, int n)
Definition at line 299 of file c_basic.c.
int C_strncmp (C_String str1, C_String str2, int n)
Definition at line 309 of file c_basic.c.
C_String C_strncpy (C_String dst, C_String src, int n)
Definition at line 291 of file c_basic.c.
C_String C_strpbrk (C_String str, C_String ct)
Definition at line 331 of file c_basic.c.
C_String C_strrchr (C_String str, int ch)
Definition at line 317 of file c_basic.c.
C_String C_strrstr (C_String str1, C_String str2)
Definition at line 349 of file c_basic.c.
References C_NIL.
C_String C_strsave (C_String str)
Definition at line 363 of file c_basic.c.
References C_assert(), and C_malloc().
Referenced by C_unique_name(), C_update(), and new_file().
int C_strspn (C_String str, C_String ct)
Definition at line 322 of file c_basic.c.
C_String C_strstr (C_String str1, C_String str2)
Definition at line 335 of file c_basic.c.
References C_NIL.
long C_time (void)
Definition at line 1445 of file c_basic.c.
int C_to_lower (int ch)
Definition at line 117 of file c_basic.c.
References C_is_upper().
int C_to_upper (int ch)
Definition at line 129 of file c_basic.c.
References C_is_lower().
int C_write_block (C_File file, C_String line, int length)
Definition at line 1393 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_char (C_File file, C_Integer value)
Definition at line 1357 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_double (C_File file, C_Double value)
Definition at line 1429 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by S_print_real().
int C_write_float (C_File file, C_Float value)
Definition at line 1417 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_integer (C_File file, C_Integer value)
Definition at line 1405 of file c_basic.c.
References defined, F, files, INIT_FILE, ITintmaxformat, and MAX_FILE.
Referenced by S_print_integer().
int C_write_line (C_File file, C_String line)
Definition at line 1381 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by add_record_index(), and delete_record_index().
C_File C_write_record (C_String record_name)
Definition at line 1181 of file c_basic.c.
References add_record_index(), C_assert(), C_open_file(), C_OPEN_WRITE_ONLY, MAX_NAME_LENGTH, and name.
int C_write_word (C_File file, C_String line)
Definition at line 1369 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by S_print_name(), and S_store_record().
static int delete_record_index (C_String db_prefix, C_String name) [static]
Definition at line 1088 of file c_basic.c.
References C_assert(), C_BAD_INDEX, C_close_file(), C_create_tmp_file(), C_eof(), C_open_file(), C_OPEN_READ_ONLY, C_read_line(), C_remove_file(), C_rename_file(), C_SUCCESS, C_write_line(), index_file(), and MAX_NAME_LENGTH.
Referenced by C_destroy_record().
static int destroy_all_records (C_String db_name) [static]
Definition at line 1114 of file c_basic.c.
References C_BAD_INDEX, C_close_file(), C_eof(), C_FAILURE, C_open_file(), C_OPEN_READ_ONLY, C_read_line(), C_remove_file(), C_SUCCESS, index_file(), MAX_NAME_LENGTH, and name.
Referenced by C_destroy_database().
static int find_file (char * name) [static]
Definition at line 905 of file c_basic.c.
References C_BAD_INDEX, C_strcmp(), defined, files, and MAX_FILE.
Referenced by C_open_file().
static Str FindAndAddS (Str T, C_String str, Str * node) [static]
Definition at line 498 of file c_basic.c.
References C_malloc2(), C_savestr(), C_strcmp(), _Str::left, _Str::name, node, _Str::ptr, _Str::right, string_count, and string_length.
Referenced by C_findstr().
static Str FindS (Str T, C_String str) [static]
Definition at line 448 of file c_basic.c.
References C_strcmp(), _Str::left, _Str::name, and _Str::right.
Referenced by C_addptr(), C_findptr(), FindS(), and FindString().
static void free_file (int i) [static]
Definition at line 935 of file c_basic.c.
References files.
Referenced by C_close_file().
static C_String index_file (C_String db_prefix) [static]
Definition at line 1071 of file c_basic.c.
Referenced by add_record_index(), C_database_size(), delete_record_index(), and destroy_all_records().
static void init_file (void) [static]
Definition at line 883 of file c_basic.c.
References C_OPEN_READ_ONLY, C_OPEN_WRITE_ONLY, C_STDERR, C_STDIN, C_STDOUT, defined, files, and MAX_FILE.
static int new_file (char * name) [static]
Definition at line 917 of file c_basic.c.
References C_assert(), C_strsave(), defined, files, and MAX_FILE.
Referenced by C_open_file().
static void RemoveS (Str ptr) [static]
Definition at line 1457 of file c_basic.c.
References _Str::left, _Str::name, and _Str::right.
Referenced by C_RemoveAllString(), RemoveAllString(), and RemoveS().
static void VisitS (Str T, int(*)(C_String name, C_Pointer ptr) fn) [static]
Definition at line 598 of file c_basic.c.
References _Str::left, _Str::name, _Str::ptr, and _Str::right.
Referenced by C_for_all_ptr().
Variable Documentation
char db_index[MAX_NAME_LENGTH] [static]
Definition at line 1068 of file c_basic.c.
C_String db_prefix = 0 [static]
Definition at line 1067 of file c_basic.c.
short defined
Definition at line 872 of file c_basic.c.
Referenced by add_node(), add_reg(), C_close_file(), C_eof(), C_file_name(), C_flush_file(), C_read_block(), C_read_char(), C_read_double(), C_read_float(), C_read_integer(), C_read_line(), C_read_word(), C_write_block(), C_write_char(), C_write_double(), C_write_float(), C_write_integer(), C_write_line(), C_write_word(), find_df_node(), find_df_reg(), find_file(), init_file(), new_file(), reaching_definition(), and reset_nodes().
short eof
Definition at line 873 of file c_basic.c.
int errno
FILE* F
Definition at line 876 of file c_basic.c.
Referenced by C_close_file(), C_flush_file(), C_open_file(), C_read_block(), C_read_char(), C_read_double(), C_read_float(), C_read_integer(), C_read_line(), C_read_word(), C_write_block(), C_write_char(), C_write_double(), C_write_float(), C_write_integer(), C_write_line(), C_write_word(), I_open_output_file(), ReadGraph(), and WriteGraph().
struct { ... }
 files[MAX_FILE] [static]
Referenced by C_close_file(), C_eof(), C_file_name(), C_flush_file(), C_open_file(), C_read_block(), C_read_char(), C_read_double(), C_read_float(), C_read_integer(), C_read_line(), C_read_word(), C_write_block(), C_write_char(), C_write_double(), C_write_float(), C_write_integer(), C_write_line(), C_write_word(), find_file(), free_file(), init_file(), and new_file().
int init = 0 [static]
Definition at line 881 of file c_basic.c.
unsigned long m2[33] [static]
Definition at line 201 of file c_basic.c.
Referenced by C_mask().
short mode
Definition at line 874 of file c_basic.c.
Referenced by C_flush_file(), find_empty_entry(), and find_symbol().
char* name
Definition at line 875 of file c_basic.c.
Referenced by C_destroy_record(), C_read_record(), C_write_record(), destroy_all_records(), L_add_to_parm_table_list(), and L_read_parm_section_defaults().
unsigned long p2[32] [static]
Definition at line 167 of file c_basic.c.
Referenced by C_is_log2(), C_log2(), and C_pow2().
Str str_root = 0 [static]
Definition at line 437 of file c_basic.c.
Referenced by C_addptr(), C_findptr(), C_findstr(), C_for_all_ptr(), and C_RemoveAllString().
int string_count [static]
Definition at line 494 of file c_basic.c.
Referenced by FindAndAddS().
int string_length [static]
Definition at line 494 of file c_basic.c.
Referenced by FindAndAddS().