c_basic.h File Reference
#include <config.h>
#include <time.h>
#include <library/i_types.h>
Data Structures
union C_Data
struct C_Fstat
Defines
#define C_TYPE_VOID 0
#define C_TYPE_INTEGER 1
#define C_TYPE_FLOAT 2
#define C_TYPE_DOUBLE 3
#define C_TYPE_POINTER 4
#define C_TRUE 1
#define C_FALSE 0
#define C_ALL_ONE 0xFFFFFFFF
#define C_NIL 0
#define C_SUCCESS 1
#define C_FAILURE 0
#define C_BAD_INDEX -1
#define C_INT_MIN -2147483647L
#define C_INT_MAX +2147483647L
#define C_FLOAT_DIG 6
#define C_FLOAT_EPSILON 1E-5
#define C_FLOAT_MAX 1E+37
#define C_FLOAT_MIN 1E-37
#define C_DOUBLE_DIG 9
#define C_DOUBLE_EPSILON 1E-8
#define C_DOUBLE_MAX 1E+37
#define C_DOUBLE_MIN 1E-37
#define C_NU '\0'
#define C_NL '\n'
#define C_HT '\t'
#define C_VT '\v'
#define C_BS '\b'
#define C_CR '\r'
#define C_FF '\f'
#define C_ALERT '\a'
#define C_BACKSLASH '\\'
#define C_QUESTION '\?'
#define C_S_QUOTE '\''
#define C_D_QUOTE '\`'
#define C_STDIN 0
#define C_STDOUT 1
#define C_STDERR 2
#define C_OPEN_READ_ONLY 0
#define C_OPEN_WRITE_ONLY 1
#define C_OPEN_APPEND_ONLY 2
Typedefs
typedef char Boolean
typedef int Integer
typedef float Float
typedef double Double
typedef char String
typedef void * Pointer
typedef long(*) Function (char *,...)
typedef char C_Boolean
typedef ITintmax C_Integer
typedef float C_Float
typedef double C_Double
typedef void * C_Pointer
typedef char * C_String
typedef long(*) C_Function (char *,...)
typedef C_Boolean * Cb
typedef C_Integer * Ci
typedef C_Float * Cf
typedef C_Double * Cd
typedef int C_File
Functions
int C_is_space (int ch)
int C_is_alpha (int ch)
int C_is_lower (int ch)
int C_is_upper (int ch)
int C_is_digit (int ch)
int C_is_alpha_numeric (int ch)
int C_to_lower (int ch)
int C_to_upper (int ch)
int C_is_hex_digit (int ch)
int C_is_oct_digit (int ch)
int C_is_control ()
int C_is_graph ()
int C_log2 (C_Integer n)
int C_is_log2 (C_Integer n)
C_Integer C_pow2 (int n)
C_Integer C_mask (int n)
int C_strlen (C_String str)
C_String C_strcpy (C_String dst, C_String src)
C_String C_strncpy (C_String dst, C_String src, int n)
C_String C_strcat (C_String dst, C_String src)
C_String C_strncat (C_String dst, C_String src, int n)
int C_strcmp (C_String str1, C_String str2)
int C_strncmp (C_String str1, C_String str2, int n)
C_String C_strchr (C_String str, int ch)
C_String C_strrchr (C_String str, int ch)
int C_strspn (C_String str, C_String ct)
int C_strcspn (C_String str, C_String ct)
C_String C_strpbrk (C_String str, C_String ct)
C_String C_strstr (C_String str1, C_String str2)
C_String C_strrstr (C_String str1, C_String str2)
C_String C_strsave (C_String str)
int C_str2char (C_String str)
C_String C_savestr (C_String str)
C_String C_findstr (C_String str)
C_Pointer C_addptr (C_String str, C_Pointer ptr)
C_Pointer C_findptr (C_String str)
void C_for_all_ptr (int(*fn)(C_String name, C_Pointer ptr))
void C_RemoveAllString ()
C_Float C_string_to_float (C_String str)
C_String C_float_to_string (C_Float value, C_String line)
C_Double C_string_to_double (C_String str)
C_String C_double_to_string (C_Double value, C_String line)
C_String C_char_to_string (int value, C_String line)
C_Integer C_string_to_integer (C_String str)
C_String C_integer_to_string (C_Integer value, C_String line)
C_Integer C_string_to_hex (C_String str)
C_String C_hex_to_string (C_Integer value, C_String line)
C_Integer C_string_to_oct (C_String str)
C_String C_oct_to_string (C_Integer value, C_String line)
void C_abort (void)
void C_exit (int status)
void C_assert (int expression, char *error_mesg)
C_Pointer C_calloc (int num_obj, int size_obj)
C_Pointer C_malloc (int size)
C_Pointer C_calloc2 (int num_obj, int size_obj)
C_Pointer C_malloc2 (int size)
void C_free (C_Pointer ptr)
int C_lookup_file (char *fname, C_Fstat *st)
C_File C_open_file (C_String file_name, int mode)
int C_flush_file (C_File file)
int C_close_file (C_File file)
int C_create_tmp_file (C_String name)
int C_remove_file (C_String name)
int C_rename_file (C_String name, C_String new_name)
int C_create_directory (C_String dir_name)
int C_destroy_directory (C_String dir_name)
int C_create_tmp_directory (C_String dir_name)
int C_database_size (C_String db_name)
int C_create_database (C_String db_name)
int C_destroy_database (C_String db_name)
int C_connect_database (C_String db_name)
int C_disconnect_database (C_String db_name)
C_File C_read_record (C_String record_name)
C_File C_write_record (C_String record_name)
int C_destroy_record (C_String record_name)
C_String C_file_name (C_File file)
int C_eof (C_File file)
int C_read_char (C_File file, C_Integer *value)
int C_read_word (C_File file, C_String line, int length)
int C_read_integer (C_File file, C_Integer *value)
int C_read_float (C_File file, C_Float *value)
int C_read_double (C_File file, C_Double *value)
int C_read_line (C_File file, C_String line, int length)
int C_read_block (C_File file, C_String line, int length)
int C_write_char (C_File file, C_Integer value)
int C_write_word (C_File file, C_String line)
int C_write_line (C_File file, C_String line)
int C_write_block (C_File file, C_String line, int length)
int C_write_integer (C_File file, C_Integer value)
int C_write_float (C_File file, C_Float value)
int C_write_double (C_File file, C_Double value)
long C_time (void)
char * C_asctime (time_t tm)
Define Documentation
#define C_ALERT '\a'
Definition at line 144 of file c_basic.h.
Referenced by C_char_to_string(), C_str2char(), and C_string_to_char().
#define C_ALL_ONE 0xFFFFFFFF
Definition at line 113 of file c_basic.h.
#define C_BACKSLASH '\\'
Definition at line 145 of file c_basic.h.
Referenced by C_string_to_char().
#define C_BAD_INDEX -1
Definition at line 119 of file c_basic.h.
Referenced by add_record_index(), C_database_size(), C_open_file(), C_rename_file(), delete_record_index(), destroy_all_records(), and find_file().
#define C_BS '\b'
Definition at line 141 of file c_basic.h.
Referenced by C_char_to_string(), C_str2char(), and C_string_to_char().
#define C_CR '\r'
Definition at line 142 of file c_basic.h.
Referenced by C_char_to_string(), C_is_space(), C_str2char(), and C_string_to_char().
#define C_D_QUOTE '\`'
Definition at line 148 of file c_basic.h.
#define C_DOUBLE_DIG 9
Definition at line 129 of file c_basic.h.
#define C_DOUBLE_EPSILON 1E-8
Definition at line 130 of file c_basic.h.
#define C_DOUBLE_MAX 1E+37
Definition at line 131 of file c_basic.h.
#define C_DOUBLE_MIN 1E-37
Definition at line 132 of file c_basic.h.
#define C_FAILURE 0
Definition at line 118 of file c_basic.h.
Referenced by C_close_file(), C_destroy_directory(), C_flush_file(), C_remove_file(), C_rename_file(), and destroy_all_records().
#define C_FALSE 0
Definition at line 111 of file c_basic.h.
#define C_FF '\f'
Definition at line 143 of file c_basic.h.
Referenced by C_char_to_string(), C_is_space(), C_str2char(), and C_string_to_char().
#define C_FLOAT_DIG 6
Definition at line 124 of file c_basic.h.
#define C_FLOAT_EPSILON 1E-5
Definition at line 125 of file c_basic.h.
#define C_FLOAT_MAX 1E+37
Definition at line 126 of file c_basic.h.
#define C_FLOAT_MIN 1E-37
Definition at line 127 of file c_basic.h.
#define C_HT '\t'
Definition at line 139 of file c_basic.h.
Referenced by C_char_to_string(), C_is_space(), C_str2char(), and C_string_to_char().
#define C_INT_MAX +2147483647L
Definition at line 122 of file c_basic.h.
#define C_INT_MIN -2147483647L
Definition at line 121 of file c_basic.h.
#define C_NIL 0
Definition at line 115 of file c_basic.h.
Referenced by C_strrstr(), and C_strstr().
#define C_NL '\n'
Definition at line 138 of file c_basic.h.
Referenced by C_char_to_string(), C_is_space(), C_read_line(), C_str2char(), and C_string_to_char().
#define C_NU '\0'
Definition at line 137 of file c_basic.h.
Referenced by C_str2char().
#define C_OPEN_APPEND_ONLY 2
Definition at line 271 of file c_basic.h.
Referenced by add_record_index(), C_open_file(), and S_create_record().
#define C_OPEN_READ_ONLY 0
Definition at line 269 of file c_basic.h.
Referenced by C_database_size(), C_flush_file(), C_open_file(), C_read_record(), delete_record_index(), destroy_all_records(), init_file(), and S_sum_of_column().
#define C_OPEN_WRITE_ONLY 1
Definition at line 270 of file c_basic.h.
Referenced by C_create_tmp_file(), C_open_file(), C_write_record(), and init_file().
#define C_QUESTION '\?'
Definition at line 146 of file c_basic.h.
Referenced by C_string_to_char().
#define C_S_QUOTE '\''
Definition at line 147 of file c_basic.h.
Referenced by C_char_to_string().
#define C_STDERR 2
Definition at line 249 of file c_basic.h.
Referenced by init_file().
#define C_STDIN 0
Definition at line 247 of file c_basic.h.
Referenced by init_file().
#define C_STDOUT 1
Definition at line 248 of file c_basic.h.
Referenced by init_file().
#define C_SUCCESS 1
Definition at line 117 of file c_basic.h.
Referenced by add_record_index(), C_close_file(), C_destroy_directory(), C_disconnect_database(), C_flush_file(), C_remove_file(), C_rename_file(), delete_record_index(), and destroy_all_records().
#define C_TRUE 1
Definition at line 110 of file c_basic.h.
#define C_TYPE_DOUBLE 3
Definition at line 97 of file c_basic.h.
#define C_TYPE_FLOAT 2
Definition at line 96 of file c_basic.h.
#define C_TYPE_INTEGER 1
Definition at line 95 of file c_basic.h.
#define C_TYPE_POINTER 4
Definition at line 98 of file c_basic.h.
#define C_TYPE_VOID 0
Definition at line 94 of file c_basic.h.
#define C_VT '\v'
Definition at line 140 of file c_basic.h.
Referenced by C_char_to_string(), C_is_space(), C_str2char(), and C_string_to_char().
Typedef Documentation
typedef char Boolean
Definition at line 74 of file c_basic.h.
typedef char C_Boolean
Definition at line 81 of file c_basic.h.
typedef double C_Double
Definition at line 84 of file c_basic.h.
typedef int C_File
Definition at line 245 of file c_basic.h.
typedef float C_Float
Definition at line 83 of file c_basic.h.
typedef long(*) C_Function(char *,...)
Definition at line 87 of file c_basic.h.
typedef ITintmax C_Integer
Definition at line 82 of file c_basic.h.
typedef void* C_Pointer
Definition at line 85 of file c_basic.h.
typedef char* C_String
Definition at line 86 of file c_basic.h.
typedef C_Boolean* Cb
Definition at line 89 of file c_basic.h.
typedef C_Double* Cd
Definition at line 92 of file c_basic.h.
typedef C_Float* Cf
Definition at line 91 of file c_basic.h.
typedef C_Integer* Ci
Definition at line 90 of file c_basic.h.
typedef double Double
Definition at line 77 of file c_basic.h.
typedef float Float
Definition at line 76 of file c_basic.h.
typedef long(*) Function(char *,...)
Definition at line 80 of file c_basic.h.
typedef int Integer
Definition at line 75 of file c_basic.h.
typedef void* Pointer
Definition at line 79 of file c_basic.h.
typedef char String
Definition at line 78 of file c_basic.h.
Function Documentation
void C_abort (void)
Definition at line 802 of file c_basic.c.
C_Pointer C_addptr (C_String str, C_Pointer ptr)
Definition at line 569 of file c_basic.c.
References AddS(), C_assert(), FindS(), _Str::ptr, and str_root.
char* C_asctime (time_t tm)
Definition at line 1450 of file c_basic.c.
void C_assert (int expression, char * error_mesg)
Definition at line 812 of file c_basic.c.
References C_exit().
Referenced by add_record_index(), C2_init_scope(), C2_kill_scope_above(), C2_reset_attribute(), C2_scope_in(), C2_scope_out(), C_addptr(), C_calloc2(), C_clear(), C_clear_attr(), C_clear_free_all(), C_clear_free_name(), C_delete(), C_delete_tbl(), C_destroy_record(), C_find(), C_find_from_index(), C_find_index(), C_findptr(), C_findstr(), C_forall(), C_full(), C_get_arg(), C_malloc2(), C_open(), C_open_file(), C_read_record(), C_strsave(), C_unique_name(), C_update(), C_write_record(), delete_record_index(), find_symbol(), and new_file().
C_Pointer C_calloc (int num_obj, int size_obj)
Definition at line 828 of file c_basic.c.
Referenced by C_calloc2().
C_Pointer C_calloc2 (int num_obj, int size_obj)
Definition at line 844 of file c_basic.c.
References C_assert(), and C_calloc().
C_String C_char_to_string (int value, C_String line)
Definition at line 716 of file c_basic.c.
References C_ALERT, C_BS, C_CR, C_FF, C_HT, C_is_control(), C_is_graph(), C_NL, C_S_QUOTE, and C_VT.
int C_close_file (C_File file)
Definition at line 996 of file c_basic.c.
References C_FAILURE, C_SUCCESS, defined, F, files, free_file(), INIT_FILE, and MAX_FILE.
Referenced by add_record_index(), C_database_size(), delete_record_index(), destroy_all_records(), S_store_record(), and S_sum_of_column().
int C_connect_database (C_String db_name)
int C_create_database (C_String db_name)
int C_create_directory (C_String dir_name)
int C_create_tmp_directory (C_String dir_name)
int C_create_tmp_file (C_String name)
Definition at line 1008 of file c_basic.c.
References C_open_file(), C_OPEN_WRITE_ONLY, C_strcpy(), and INIT_FILE.
Referenced by delete_record_index().
int C_database_size (C_String db_name)
Definition at line 1139 of file c_basic.c.
References C_BAD_INDEX, C_close_file(), C_eof(), C_open_file(), C_OPEN_READ_ONLY, C_read_line(), index_file(), and MAX_NAME_LENGTH.
int C_destroy_database (C_String db_name)
Definition at line 1160 of file c_basic.c.
References C_destroy_directory(), and destroy_all_records().
int C_destroy_directory (C_String dir_name)
Definition at line 1053 of file c_basic.c.
References C_FAILURE, and C_SUCCESS.
Referenced by C_destroy_database().
int C_destroy_record (C_String record_name)
Definition at line 1192 of file c_basic.c.
References C_assert(), C_remove_file(), delete_record_index(), MAX_NAME_LENGTH, and name.
int C_disconnect_database (C_String db_name)
Definition at line 1167 of file c_basic.c.
References C_SUCCESS.
C_String C_double_to_string (C_Double value, C_String line)
Definition at line 630 of file c_basic.c.
int C_eof (C_File file)
Definition at line 1216 of file c_basic.c.
References defined, files, INIT_FILE, and MAX_FILE.
Referenced by C_database_size(), delete_record_index(), destroy_all_records(), and S_sum_of_column().
void C_exit (int status)
Definition at line 807 of file c_basic.c.
Referenced by C_assert().
C_String C_file_name (C_File file)
Definition at line 1206 of file c_basic.c.
References defined, files, INIT_FILE, and MAX_FILE.
C_Pointer C_findptr (C_String str)
Definition at line 585 of file c_basic.c.
References C_assert(), FindS(), _Str::ptr, and str_root.
C_String C_findstr (C_String str)
Definition at line 557 of file c_basic.c.
References C_assert(), FindAndAddS(), _Str::ptr, and str_root.
Referenced by AddArgument(), and ChangeArgument().
C_String C_float_to_string (C_Float value, C_String line)
Definition at line 621 of file c_basic.c.
int C_flush_file (C_File file)
Definition at line 983 of file c_basic.c.
References C_FAILURE, C_OPEN_READ_ONLY, C_SUCCESS, defined, F, files, INIT_FILE, MAX_FILE, and mode.
void C_for_all_ptr (int(*)(C_String name, C_Pointer ptr) fn)
Definition at line 609 of file c_basic.c.
References str_root, and VisitS().
void C_free (C_Pointer ptr)
Definition at line 859 of file c_basic.c.
C_String C_hex_to_string (C_Integer value, C_String line)
Definition at line 781 of file c_basic.c.
References ITintmaxhexfmt.
C_String C_integer_to_string (C_Integer value, C_String line)
Definition at line 770 of file c_basic.c.
References ITintmaxformat.
int C_is_alpha (int ch)
Definition at line 92 of file c_basic.c.
Referenced by C_is_alpha_numeric().
int C_is_alpha_numeric (int ch)
Definition at line 112 of file c_basic.c.
References C_is_alpha(), and C_is_digit().
Referenced by C_string_to_char().
int C_is_control ()
int C_is_digit (int ch)
Definition at line 107 of file c_basic.c.
Referenced by C_is_alpha_numeric().
int C_is_graph ()
int C_is_hex_digit (int ch)
Definition at line 141 of file c_basic.c.
int C_is_log2 (C_Integer n)
Definition at line 253 of file c_basic.c.
References NUM_BITS, and p2.
int C_is_lower (int ch)
Definition at line 97 of file c_basic.c.
Referenced by C_to_upper().
int C_is_oct_digit (int ch)
Definition at line 147 of file c_basic.c.
Referenced by C_string_to_char().
int C_is_space (int ch)
Definition at line 86 of file c_basic.c.
References C_CR, C_FF, C_HT, C_NL, and C_VT.
Referenced by C_read_word().
int C_is_upper (int ch)
Definition at line 102 of file c_basic.c.
Referenced by C_to_lower().
int C_log2 (C_Integer n)
Definition at line 242 of file c_basic.c.
References NUM_BITS, and p2.
int C_lookup_file (char * fname, C_Fstat * st)
C_Pointer C_malloc (int size)
Definition at line 834 of file c_basic.c.
Referenced by C_malloc2(), C_strsave(), and new_node().
C_Pointer C_malloc2 (int size)
Definition at line 851 of file c_basic.c.
References C_assert(), and C_malloc().
Referenced by AddS(), C_savestr(), and FindAndAddS().
C_Integer C_mask (int n)
Definition at line 271 of file c_basic.c.
References m2, and NUM_BITS.
C_String C_oct_to_string (C_Integer value, C_String line)
Definition at line 792 of file c_basic.c.
References ITintmaxoctfmt.
C_File C_open_file (C_String file_name, int mode)
Definition at line 952 of file c_basic.c.
References C_assert(), C_BAD_INDEX, C_OPEN_APPEND_ONLY, C_OPEN_READ_ONLY, C_OPEN_WRITE_ONLY, F, files, find_file(), INIT_FILE, new_file(), and NULL.
Referenced by add_record_index(), C_create_tmp_file(), C_database_size(), C_read_record(), C_write_record(), delete_record_index(), destroy_all_records(), S_create_record(), and S_sum_of_column().
C_Integer C_pow2 (int n)
Definition at line 265 of file c_basic.c.
References NUM_BITS, and p2.
int C_read_block (C_File file, C_String line, int length)
Definition at line 1345 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_char (C_File file, C_Integer * value)
Definition at line 1226 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_double (C_File file, C_Double * value)
Definition at line 1304 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_float (C_File file, C_Float * value)
Definition at line 1288 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_read_integer (C_File file, C_Integer * value)
Definition at line 1276 of file c_basic.c.
References defined, F, files, INIT_FILE, ITintmaxformat, and MAX_FILE.
int C_read_line (C_File file, C_String line, int length)
Definition at line 1320 of file c_basic.c.
References C_NL, defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by C_database_size(), delete_record_index(), destroy_all_records(), and S_sum_of_column().
C_File C_read_record (C_String record_name)
Definition at line 1172 of file c_basic.c.
References C_assert(), C_open_file(), C_OPEN_READ_ONLY, MAX_NAME_LENGTH, and name.
int C_read_word (C_File file, C_String line, int length)
Definition at line 1242 of file c_basic.c.
References C_is_space(), defined, F, files, INIT_FILE, and MAX_FILE.
int C_remove_file (C_String name)
Definition at line 1020 of file c_basic.c.
References C_FAILURE, and C_SUCCESS.
Referenced by C_destroy_record(), delete_record_index(), and destroy_all_records().
void C_RemoveAllString ()
Definition at line 1471 of file c_basic.c.
References RemoveS(), and str_root.
int C_rename_file (C_String name, C_String new_name)
Definition at line 1033 of file c_basic.c.
References C_BAD_INDEX, C_FAILURE, and C_SUCCESS.
Referenced by delete_record_index().
C_String C_savestr (C_String str)
Definition at line 440 of file c_basic.c.
References C_malloc2(), C_strcpy(), and C_strlen().
Referenced by AddS(), C_get_arg(), and FindAndAddS().
int C_str2char (C_String str)
Definition at line 383 of file c_basic.c.
References C_ALERT, C_BS, C_CR, C_FF, C_HT, C_NL, C_NU, and C_VT.
C_String C_strcat (C_String dst, C_String src)
Definition at line 295 of file c_basic.c.
C_String C_strchr (C_String str, int ch)
Definition at line 313 of file c_basic.c.
int C_strcmp (C_String str1, C_String str2)
Definition at line 304 of file c_basic.c.
Referenced by AddS(), find_file(), FindAndAddS(), and FindS().
C_String C_strcpy (C_String dst, C_String src)
Definition at line 287 of file c_basic.c.
Referenced by C_create_tmp_file(), and C_savestr().
int C_strcspn (C_String str, C_String ct)
Definition at line 327 of file c_basic.c.
C_Double C_string_to_double (C_String str)
Definition at line 626 of file c_basic.c.
References atof().
Referenced by yylex().
C_Float C_string_to_float (C_String str)
Definition at line 617 of file c_basic.c.
References atof().
C_Integer C_string_to_hex (C_String str)
Definition at line 775 of file c_basic.c.
References ITintmaxhexfmt.
Referenced by C_string_to_char(), and yylex().
C_Integer C_string_to_integer (C_String str)
Definition at line 764 of file c_basic.c.
References ITintmaxformat.
Referenced by yylex().
C_Integer C_string_to_oct (C_String str)
Definition at line 786 of file c_basic.c.
References ITintmaxoctfmt.
Referenced by C_string_to_char(), and yylex().
int C_strlen (C_String str)
Definition at line 281 of file c_basic.c.
Referenced by C_savestr(), find_empty_entry(), and find_symbol().
C_String C_strncat (C_String dst, C_String src, int n)
Definition at line 299 of file c_basic.c.
int C_strncmp (C_String str1, C_String str2, int n)
Definition at line 309 of file c_basic.c.
C_String C_strncpy (C_String dst, C_String src, int n)
Definition at line 291 of file c_basic.c.
C_String C_strpbrk (C_String str, C_String ct)
Definition at line 331 of file c_basic.c.
C_String C_strrchr (C_String str, int ch)
Definition at line 317 of file c_basic.c.
C_String C_strrstr (C_String str1, C_String str2)
Definition at line 349 of file c_basic.c.
References C_NIL.
C_String C_strsave (C_String str)
Definition at line 363 of file c_basic.c.
References C_assert(), and C_malloc().
Referenced by C_unique_name(), C_update(), and new_file().
int C_strspn (C_String str, C_String ct)
Definition at line 322 of file c_basic.c.
C_String C_strstr (C_String str1, C_String str2)
Definition at line 335 of file c_basic.c.
References C_NIL.
long C_time (void)
Definition at line 1445 of file c_basic.c.
int C_to_lower (int ch)
Definition at line 117 of file c_basic.c.
References C_is_upper().
int C_to_upper (int ch)
Definition at line 129 of file c_basic.c.
References C_is_lower().
int C_write_block (C_File file, C_String line, int length)
Definition at line 1393 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_char (C_File file, C_Integer value)
Definition at line 1357 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_double (C_File file, C_Double value)
Definition at line 1429 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by S_print_real().
int C_write_float (C_File file, C_Float value)
Definition at line 1417 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
int C_write_integer (C_File file, C_Integer value)
Definition at line 1405 of file c_basic.c.
References defined, F, files, INIT_FILE, ITintmaxformat, and MAX_FILE.
Referenced by S_print_integer().
int C_write_line (C_File file, C_String line)
Definition at line 1381 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by add_record_index(), and delete_record_index().
C_File C_write_record (C_String record_name)
Definition at line 1181 of file c_basic.c.
References add_record_index(), C_assert(), C_open_file(), C_OPEN_WRITE_ONLY, MAX_NAME_LENGTH, and name.
int C_write_word (C_File file, C_String line)
Definition at line 1369 of file c_basic.c.
References defined, F, files, INIT_FILE, and MAX_FILE.
Referenced by S_print_name(), and S_store_record().