c_symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <malloc.h>
#include <string.h>
#include <library/c_symbol.h>
Defines
#define C_INVALID_SYMBOL -1
#define C_DELETED_SYMBOL -2
Functions
static C_Symbol find_symbol (SymTbl tbl, char *name, int type, int new_entry)
static int find_empty_entry (SymTbl tbl, char *name, int type, int new_entry)
int C_open (int max_size, int mode)
void C_delete_tbl (int tbl_id)
void C_clear (int tbl_id)
void C_clear_free_all (int tbl_id)
void C_clear_free_name (int tbl_id)
void C_clear_attr (int tbl_id)
void C_update (int tbl_id, char *name, int type, Integer value, Pointer ptr)
int C_find (int tbl_id, char *name, int type, Integer *value, Pointer *ptr)
int C_full (int tbl_id, char *name, int type)
int C_delete (int tbl_id, char *name, int type)
int C_forall (int tbl_id, C_Function fn)
int C_find_index (int tbl_id, void *ptr)
Pointer C_find_from_index (int tbl_id, int index)
int C_open_name_table (int max_size)
char * C_unique_name (int tbl_id, char *name)
Variables
_SymTbl TBL [C_MAX_SYMBOL_TABLE] = { { 0 } }
static int next_tbl = 0
Define Documentation
#define C_DELETED_SYMBOL -2
Definition at line 82 of file c_symbol.c.
Referenced by C_delete(), find_empty_entry(), and find_symbol().
#define C_INVALID_SYMBOL -1
Definition at line 81 of file c_symbol.c.
Referenced by C_clear(), C_clear_free_all(), C_clear_free_name(), C_delete(), C_delete_tbl(), C_find(), C_unique_name(), C_update(), find_empty_entry(), and find_symbol().
Function Documentation
void C_clear (int tbl_id)
Clear a symbol table.
Definition at line 422 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, _C_Symbol::name, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
Referenced by C2_kill_scope_above(), and C2_scope_in().
void C_clear_attr (int tbl_id)
Clear a symbol table.
Definition at line 502 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_MAX_SYMBOL_TABLE, _C_Symbol::ptr, _SymTbl::size, TBL, and _C_Symbol::value.
Referenced by C2_reset_attribute().
void C_clear_free_all (int tbl_id)
Clear a symbol table and free all fields
Definition at line 448 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, _C_Symbol::name, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
void C_clear_free_name (int tbl_id)
Clear a symbol table and free name fields
Definition at line 476 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, _C_Symbol::name, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
int C_delete (int tbl_id, char * name, int type)
Delete a symbol in the symbol table.
Definition at line 586 of file c_symbol.c.
References C_assert(), C_DELETED_SYMBOL, C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, find_symbol(), TBL, and _C_Symbol::type.
void C_delete_tbl (int tbl_id)
Delete a symbol table, leaving ptr to C_Symbol NULL
Definition at line 390 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, _C_Symbol::name, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
int C_find (int tbl_id, char * name, int type, Integer * value, Pointer * ptr)
Find a symbol in the symbol table.
Definition at line 540 of file c_symbol.c.
References C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, find_symbol(), _C_Symbol::ptr, TBL, _C_Symbol::type, and _C_Symbol::value.
Referenced by C2_find_global_symbol(), C2_find_local_symbol(), and C2_find_symbol().
Pointer C_find_from_index (int tbl_id, int index)
Definition at line 671 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_MAX_SYMBOL_TABLE, _C_Symbol::ptr, _SymTbl::size, and TBL.
int C_find_index (int tbl_id, void * ptr)
Definition at line 646 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_MAX_SYMBOL_TABLE, _C_Symbol::ptr, _SymTbl::size, TBL, and _C_Symbol::type.
int C_forall (int tbl_id, C_Function fn)
Traverse a symbol table.
Definition at line 608 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_MAX_SYMBOL_TABLE, _C_Symbol::name, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
Referenced by C2_forall(), and C2_forall_global().
int C_full (int tbl_id, char * name, int type)
Find a empty slot in the symbol table.
Definition at line 573 of file c_symbol.c.
References C_assert(), C_MAX_SYMBOL_TABLE, find_empty_entry(), and TBL.
int C_open (int max_size, int mode)
Create a new symbol table.
get next table
allocate a table
Definition at line 297 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_MATCH_BY_AND_TYPE, C_MATCH_BY_EXACT_TYPE, C_MAX_SYMBOL_TABLE, next_tbl, NULL, and TBL.
Referenced by C2_init_scope(), and C_open_name_table().
int C_open_name_table (int max_size)
Create a name table
Definition at line 686 of file c_symbol.c.
References C_MATCH_BY_EXACT_TYPE, and C_open().
char* C_unique_name (int tbl_id, char * name)
Definition at line 691 of file c_symbol.c.
References C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, C_strsave(), find_symbol(), _C_Symbol::name, TBL, and _C_Symbol::type.
void C_update (int tbl_id, char * name, int type, Integer value, Pointer ptr)
Add a new symbol in the symbol table.
Definition at line 519 of file c_symbol.c.
References C_assert(), C_INVALID_SYMBOL, C_MAX_SYMBOL_TABLE, C_strsave(), find_symbol(), _C_Symbol::name, _C_Symbol::ptr, TBL, _C_Symbol::type, and _C_Symbol::value.
Referenced by C2_update_global_symbol(), C2_update_local_symbol(), and C2_update_symbol().
static int find_empty_entry (SymTbl tbl, char * name, int type, int new_entry) [static]
Definition at line 211 of file c_symbol.c.
References _SymTbl::array, C_DELETED_SYMBOL, C_INVALID_SYMBOL, C_MATCH_BY_EXACT_TYPE, C_strlen(), _SymTbl::mode, mode, _C_Symbol::name, _SymTbl::size, and _C_Symbol::type.
Referenced by C_full().
static C_Symbol find_symbol (SymTbl tbl, char * name, int type, int new_entry) [static]
Definition at line 109 of file c_symbol.c.
References _SymTbl::array, C_assert(), C_DELETED_SYMBOL, C_INVALID_SYMBOL, C_MATCH_BY_EXACT_TYPE, C_strlen(), _SymTbl::mode, mode, _C_Symbol::name, NULL, _SymTbl::size, TBL, and _C_Symbol::type.
Referenced by C_delete(), C_find(), C_unique_name(), and C_update().
Variable Documentation
int next_tbl = 0 [static]
Definition at line 105 of file c_symbol.c.
_SymTbl TBL[C_MAX_SYMBOL_TABLE] = { { 0 } }
Definition at line 104 of file c_symbol.c.