c_symbol2.c File Reference
#include <config.h>
#include <library/c_symbol2.h>
Functions
int C2_init_scope (int num_scope, int s_global, int s_local)
void C2_kill_scope_above (int n)
void C2_reset_attribute (int n)
int C2_scope_in (void)
int C2_scope_out (void)
int C2_find_symbol (char *name, int type, Integer *value, Pointer *ptr)
int C2_update_symbol (char *name, int type, Integer value, Pointer ptr)
int C2_find_local_symbol (char *name, int type, Integer *value, Pointer *ptr)
int C2_update_local_symbol (char *name, int type, Integer value, Pointer ptr)
int C2_find_global_symbol (char *name, int type, Integer *value, Pointer *ptr)
int C2_update_global_symbol (char *name, int type, Integer value, Pointer ptr)
int C2_forall (C_Function fn)
int C2_forall_global (C_Function fn)
Variables
static int scope [C2_MAX_SCOPE]
static int scope_id [C2_MAX_SCOPE]
static int next_scope_id = 0
static int n_scope = 0
Function Documentation
int C2_find_global_symbol (char * name, int type, Integer * value, Pointer * ptr)
Definition at line 186 of file c_symbol2.c.
References C_find(), scope, and scope_id.
int C2_find_local_symbol (char * name, int type, Integer * value, Pointer * ptr)
Definition at line 165 of file c_symbol2.c.
References C_find(), n_scope, scope, and scope_id.
int C2_find_symbol (char * name, int type, Integer * value, Pointer * ptr)
Definition at line 141 of file c_symbol2.c.
References C_find(), n_scope, scope, and scope_id.
int C2_forall (C_Function fn)
Definition at line 204 of file c_symbol2.c.
References C_forall(), n_scope, and scope.
int C2_forall_global (C_Function fn)
Definition at line 210 of file c_symbol2.c.
References C_forall(), and scope.
int C2_init_scope (int num_scope, int s_global, int s_local)
Definition at line 73 of file c_symbol2.c.
References C2_scope_in(), C_assert(), C_MATCH_BY_AND_TYPE, C_open(), n_scope, next_scope_id, and scope.
void C2_kill_scope_above (int n)
Definition at line 92 of file c_symbol2.c.
References C_assert(), C_clear(), n_scope, and scope.
void C2_reset_attribute (int n)
Definition at line 108 of file c_symbol2.c.
References C_assert(), C_clear_attr(), n_scope, and scope.
int C2_scope_in (void)
Definition at line 120 of file c_symbol2.c.
References C2_MAX_SCOPE, C_assert(), C_clear(), n_scope, next_scope_id, scope, and scope_id.
Referenced by C2_init_scope().
int C2_scope_out (void)
Definition at line 132 of file c_symbol2.c.
References C_assert(), n_scope, and scope_id.
int C2_update_global_symbol (char * name, int type, Integer value, Pointer ptr)
Definition at line 197 of file c_symbol2.c.
References C_update(), scope, and scope_id.
int C2_update_local_symbol (char * name, int type, Integer value, Pointer ptr)
Definition at line 177 of file c_symbol2.c.
References C_update(), n_scope, scope, and scope_id.
int C2_update_symbol (char * name, int type, Integer value, Pointer ptr)
Definition at line 156 of file c_symbol2.c.
References C_update(), n_scope, scope, and scope_id.
Variable Documentation
int n_scope = 0 [static]
Definition at line 70 of file c_symbol2.c.
Referenced by C2_find_local_symbol(), C2_find_symbol(), C2_forall(), C2_init_scope(), C2_kill_scope_above(), C2_reset_attribute(), C2_scope_in(), C2_scope_out(), C2_update_local_symbol(), and C2_update_symbol().
int next_scope_id = 0 [static]
Definition at line 69 of file c_symbol2.c.
Referenced by C2_init_scope(), and C2_scope_in().
int scope[C2_MAX_SCOPE] [static]
Definition at line 67 of file c_symbol2.c.
Referenced by C2_find_global_symbol(), C2_find_local_symbol(), C2_find_symbol(), C2_forall(), C2_forall_global(), C2_init_scope(), C2_kill_scope_above(), C2_reset_attribute(), C2_scope_in(), C2_update_global_symbol(), C2_update_local_symbol(), and C2_update_symbol().
int scope_id[C2_MAX_SCOPE] [static]
Definition at line 68 of file c_symbol2.c.
Referenced by C2_find_global_symbol(), C2_find_local_symbol(), C2_find_symbol(), C2_scope_in(), C2_scope_out(), C2_update_global_symbol(), C2_update_local_symbol(), and C2_update_symbol().