char_array_symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `char_array_symbol.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Functions
CHAR_ARRAY_Symbol_Table * CHAR_ARRAY_new_symbol_table (char *name, int expected_size)
void CHAR_ARRAY_delete_symbol_table (CHAR_ARRAY_Symbol_Table *table, void(*free_routine)(void *))
void CHAR_ARRAY_resize_symbol_table (CHAR_ARRAY_Symbol_Table *table)
static unsigned int CHAR_ARRAY_hash_char_array (char *char_array, int array_length)
CHAR_ARRAY_Symbol * CHAR_ARRAY_add_symbol (CHAR_ARRAY_Symbol_Table *table, char *char_array, int array_length, void *data)
CHAR_ARRAY_Symbol * CHAR_ARRAY_find_symbol (CHAR_ARRAY_Symbol_Table *table, char *char_array, int array_length)
void * CHAR_ARRAY_find_symbol_data (CHAR_ARRAY_Symbol_Table *table, char *char_array, int array_length)
void CHAR_ARRAY_delete_symbol (CHAR_ARRAY_Symbol *symbol, void(*free_routine)(void *))
void CHAR_ARRAY_print_symbol_table_hash (FILE *out, CHAR_ARRAY_Symbol_Table *table)
Variables
L_Alloc_Pool * CHAR_ARRAY_Symbol_Table_pool = NULL
L_Alloc_Pool * CHAR_ARRAY_Symbol_pool = NULL
Function Documentation
CHAR_ARRAY_Symbol* CHAR_ARRAY_add_symbol (CHAR_ARRAY_Symbol_Table * table, char * char_array, int array_length, void * data)
Definition at line 278 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::array_length, CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_hash_char_array(), CHAR_ARRAY_resize_symbol_table(), CHAR_ARRAY_Symbol_pool, CHAR_ARRAY_Symbol::data, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_mask, CHAR_ARRAY_Symbol::hash_val, CHAR_ARRAY_Symbol_Table::head_symbol, I_punt(), L_alloc(), CHAR_ARRAY_Symbol_Table::name, CHAR_ARRAY_Symbol::next_hash, CHAR_ARRAY_Symbol::next_symbol, NULL, CHAR_ARRAY_Symbol::prev_symbol, CHAR_ARRAY_Symbol_Table::resize_size, CHAR_ARRAY_Symbol_Table::symbol_count, CHAR_ARRAY_Symbol::table, and CHAR_ARRAY_Symbol_Table::tail_symbol.
Referenced by new_Func_Name_List().
void CHAR_ARRAY_delete_symbol (CHAR_ARRAY_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 509 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_Symbol_pool, CHAR_ARRAY_Symbol::data, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_mask, CHAR_ARRAY_Symbol::hash_val, CHAR_ARRAY_Symbol_Table::head_symbol, L_free(), CHAR_ARRAY_Symbol::next_hash, CHAR_ARRAY_Symbol::next_symbol, NULL, CHAR_ARRAY_Symbol::prev_hash, CHAR_ARRAY_Symbol::prev_symbol, CHAR_ARRAY_Symbol_Table::symbol_count, CHAR_ARRAY_Symbol::table, and CHAR_ARRAY_Symbol_Table::tail_symbol.
void CHAR_ARRAY_delete_symbol_table (CHAR_ARRAY_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 156 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_Symbol_pool, CHAR_ARRAY_Symbol_Table_pool, CHAR_ARRAY_Symbol::data, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::head_symbol, L_free(), CHAR_ARRAY_Symbol_Table::name, CHAR_ARRAY_Symbol::next_symbol, and NULL.
Referenced by delete_Func_Name_List().
CHAR_ARRAY_Symbol* CHAR_ARRAY_find_symbol (CHAR_ARRAY_Symbol_Table * table, char * char_array, int array_length)
Definition at line 402 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::array_length, CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_hash_char_array(), CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_mask, CHAR_ARRAY_Symbol::hash_val, I_punt(), CHAR_ARRAY_Symbol::next_hash, and NULL.
Referenced by is_in_Func_Name_List(), and new_Func_Name_List().
void* CHAR_ARRAY_find_symbol_data (CHAR_ARRAY_Symbol_Table * table, char * char_array, int array_length)
Definition at line 457 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::array_length, CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_hash_char_array(), CHAR_ARRAY_Symbol::data, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_mask, CHAR_ARRAY_Symbol::hash_val, I_punt(), CHAR_ARRAY_Symbol::next_hash, and NULL.
static unsigned int CHAR_ARRAY_hash_char_array (char * char_array, int array_length) [static]
Definition at line 243 of file char_array_symbol.c.
Referenced by CHAR_ARRAY_add_symbol(), CHAR_ARRAY_find_symbol(), and CHAR_ARRAY_find_symbol_data().
CHAR_ARRAY_Symbol_Table* CHAR_ARRAY_new_symbol_table (char * name, int expected_size)
Definition at line 81 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol_pool, CHAR_ARRAY_Symbol_Table_pool, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_mask, CHAR_ARRAY_Symbol_Table::hash_size, CHAR_ARRAY_Symbol_Table::head_symbol, I_punt(), L_alloc(), L_create_alloc_pool(), CHAR_ARRAY_Symbol_Table::name, NULL, CHAR_ARRAY_Symbol_Table::resize_size, CHAR_ARRAY_Symbol_Table::symbol_count, and CHAR_ARRAY_Symbol_Table::tail_symbol.
Referenced by new_Func_Name_List().
void CHAR_ARRAY_print_symbol_table_hash (FILE * out, CHAR_ARRAY_Symbol_Table * table)
Definition at line 563 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol::array_length, CHAR_ARRAY_Symbol::char_array, CHAR_ARRAY_Symbol_Table::hash, CHAR_ARRAY_Symbol_Table::hash_size, CHAR_ARRAY_Symbol_Table::name, CHAR_ARRAY_Symbol::next_hash, NULL, and CHAR_ARRAY_Symbol_Table::symbol_count.
void CHAR_ARRAY_resize_symbol_table (CHAR_ARRAY_Symbol_Table * table)
Definition at line 186 of file char_array_symbol.c.
References CHAR_ARRAY_Symbol_Table::hash_size, CHAR_ARRAY_Symbol::hash_val, CHAR_ARRAY_Symbol_Table::head_symbol, I_punt(), CHAR_ARRAY_Symbol::next_hash, CHAR_ARRAY_Symbol::next_symbol, NULL, and CHAR_ARRAY_Symbol::prev_hash.
Referenced by CHAR_ARRAY_add_symbol().
Variable Documentation
L_Alloc_Pool* CHAR_ARRAY_Symbol_pool = NULL
Definition at line 68 of file char_array_symbol.c.
Referenced by CHAR_ARRAY_add_symbol(), CHAR_ARRAY_delete_symbol(), CHAR_ARRAY_delete_symbol_table(), and CHAR_ARRAY_new_symbol_table().
L_Alloc_Pool* CHAR_ARRAY_Symbol_Table_pool = NULL
Definition at line 67 of file char_array_symbol.c.
Referenced by CHAR_ARRAY_delete_symbol_table(), and CHAR_ARRAY_new_symbol_table().