dataflow.h File Reference
#include <config.h>
#include <library/set.h>
Data Structures
struct I_Node
struct I_Reg
Defines
#define MAX_NODE_ID (16*1024)
#define MAX_REG_ID (16*1024)
#define REACH_DEFINE 1
#define USE_DEF_CHAIN 2
#define LIVE_VAR 4
#define DOMINATOR 8
#define POST_DOMINATOR 16
Functions
I_Node * find_df_node (int id)
I_Reg * find_df_reg (int reg_id)
void define_df_graph (void)
void add_df_node (int id)
void add_df_node_src_reg (int reg_id)
void add_df_node_dest_reg (int reg_id)
void connect_df_node (int src_id, int dest_id)
void end_df_graph (void)
void analyze_df_graph (int mode)
void print_df_node (FILE *F, struct I_Node *node)
void print_df_graph (FILE *F)
Define Documentation
#define DOMINATOR 8
Definition at line 121 of file dataflow.h.
Referenced by analyze_df_graph().
#define LIVE_VAR 4
Definition at line 120 of file dataflow.h.
Referenced by analyze_df_graph().
#define MAX_NODE_ID (16*1024)
Definition at line 64 of file dataflow.h.
Referenced by reset_nodes().
#define MAX_REG_ID (16*1024)
Definition at line 65 of file dataflow.h.
Referenced by reaching_definition(), and reset_nodes().
#define POST_DOMINATOR 16
Definition at line 122 of file dataflow.h.
Referenced by analyze_df_graph().
#define REACH_DEFINE 1
Definition at line 118 of file dataflow.h.
Referenced by analyze_df_graph().
#define USE_DEF_CHAIN 2
Definition at line 119 of file dataflow.h.
Referenced by analyze_df_graph().
Function Documentation
void add_df_node (int id)
Definition at line 296 of file dataflow.c.
References add_node(), AddNode(), entry, find_df_node(), FindNode(), GOOD_ID, graph, NewNode(), node, nodeExt, nodeId, and punt().
void add_df_node_dest_reg (int reg_id)
Definition at line 337 of file dataflow.c.
References add_reg(), I_Node::dest_reg, I_Reg::e_def, GOOD_REG_ID, graph, I_Node::id, node, punt(), and Set_add().
void add_df_node_src_reg (int reg_id)
Definition at line 322 of file dataflow.c.
References add_reg(), I_Reg::e_use, GOOD_REG_ID, graph, I_Node::id, node, punt(), Set_add(), and I_Node::src_reg.
void analyze_df_graph (int mode)
Definition at line 397 of file dataflow.c.
References dominator(), DOMINATOR, entry, graph, LIVE_VAR, live_variable(), nodes, post_dominator(), POST_DOMINATOR, REACH_DEFINE, reaching_definition(), regs, ud_chain(), and USE_DEF_CHAIN.
void connect_df_node (int src_id, int dest_id)
Definition at line 356 of file dataflow.c.
References AddNode(), ConnectNodes(), FindNode(), graph, NewNode(), nodeId, and punt().
void define_df_graph (void)
Definition at line 270 of file dataflow.c.
References entry, FreeGraph(), graph, NewGraph(), node, punt(), and reset_nodes().
void end_df_graph (void)
Definition at line 379 of file dataflow.c.
References entry, graph, nextNode, nodeExt, _FGraph::nodes, and punt().
struct I_Node* find_df_node (int id)
Definition at line 213 of file dataflow.c.
References defined, GOOD_ID, nodes, nodes_defined, and punt().
Referenced by add_df_node().
struct I_Reg* find_df_reg (int reg_id)
Definition at line 239 of file dataflow.c.
References defined, GOOD_REG_ID, nodes_defined, punt(), and regs.
void print_df_graph (FILE * F)
Definition at line 916 of file dataflow.c.
References graph, I_Node::id, nextNode, node, nodeId, nodes, _FGraph::nodes, and print_df_node().
void print_df_node (FILE * F, struct I_Node * node)
Definition at line 881 of file dataflow.c.
References I_Node::a_in, I_Node::a_out, I_Node::def, I_Node::defined, I_Node::dest_reg, I_Node::dom, I_Node::e_in, I_Node::e_out, I_Node::gen, I_Node::id, I_Node::kill, node, I_Node::post_dom, print_set(), I_Node::src_reg, I_Node::use, I_Node::v_in, and I_Node::v_out.
Referenced by print_df_graph().