execute.h File Reference
#include <config.h>
Data Structures
struct _Argv
Defines
#define MAX_ARGC 100
#define EXIT_NEGATIVE -1
#define CORE_DUMP -2
#define TERM_SIG -3
Typedefs
typedef _Argv * Argv
Functions
int InitArgv (Argv argv)
int AddArgument (Argv argv, char *str)
int ChangeArgument (Argv argv, int N, char *str)
int DebugExecute (int flag)
int Execute (Argv argv)
Variables
int error_code
Define Documentation
#define CORE_DUMP -2
Definition at line 96 of file execute.h.
Referenced by Execute().
#define EXIT_NEGATIVE -1
Definition at line 95 of file execute.h.
Referenced by Execute().
#define MAX_ARGC 100
Definition at line 62 of file execute.h.
Referenced by AddArgument().
#define TERM_SIG -3
Definition at line 97 of file execute.h.
Referenced by Execute().
Typedef Documentation
typedef struct _Argv * Argv
Function Documentation
int AddArgument (Argv argv, char * str)
Definition at line 93 of file execute.c.
References _Argv::argc, _Argv::argv, C_findstr(), and MAX_ARGC.
Referenced by Mkdir(), and Rmdir().
int ChangeArgument (Argv argv, int N, char * str)
Definition at line 115 of file execute.c.
References _Argv::argc, _Argv::argv, and C_findstr().
int DebugExecute (int flag)
Definition at line 135 of file execute.c.
References dryrun, and verbose.
int Execute (Argv argv)
Definition at line 158 of file execute.c.
References _Argv::argc, _Argv::argv, CORE_DUMP, dryrun, error_code, EXIT_NEGATIVE, TERM_SIG, and verbose.
Referenced by Mkdir(), and Rmdir().
int InitArgv (Argv argv)
Definition at line 81 of file execute.c.
References _Argv::argc, and _Argv::argv.
Referenced by Mkdir(), and Rmdir().
Variable Documentation
int error_code
Definition at line 73 of file execute.c.
Referenced by Execute().