execute.c File Reference
#include <config.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/wait.h>
#include <library/execute.h>
#include <library/c_basic.h>
Functions
int InitArgv (Argv argv)
int AddArgument (Argv argv, char *str)
int ChangeArgument (Argv argv, int N, char *str)
int DebugExecute (int flag)
int Execute (Argv argv)
Variables
int error_code = 0
static int dryrun = 0
static int verbose = 0
Function Documentation
int AddArgument (Argv argv, char * str)
Definition at line 93 of file execute.c.
References _Argv::argc, _Argv::argv, C_findstr(), and MAX_ARGC.
Referenced by Mkdir(), and Rmdir().
int ChangeArgument (Argv argv, int N, char * str)
Definition at line 115 of file execute.c.
References _Argv::argc, _Argv::argv, and C_findstr().
int DebugExecute (int flag)
Definition at line 135 of file execute.c.
References dryrun, and verbose.
int Execute (Argv argv)
Definition at line 158 of file execute.c.
References _Argv::argc, _Argv::argv, CORE_DUMP, dryrun, error_code, EXIT_NEGATIVE, TERM_SIG, and verbose.
Referenced by Mkdir(), and Rmdir().
int InitArgv (Argv argv)
Definition at line 81 of file execute.c.
References _Argv::argc, and _Argv::argv.
Referenced by Mkdir(), and Rmdir().
Variable Documentation
int dryrun = 0 [static]
Definition at line 74 of file execute.c.
Referenced by DebugExecute(), and Execute().
int error_code = 0
Definition at line 73 of file execute.c.
Referenced by Execute().
int verbose = 0 [static]
Definition at line 75 of file execute.c.
Referenced by DebugExecute(), and Execute().