file.c File Reference
#include <config.h>
#include <library/execute.h>
#include <library/file.h>
Defines
#define RM `/bin/rm`
#define MKDIR `/bin/mkdir`
Functions
int Rmdir (char *name)
int Mkdir (char *name)
Define Documentation
#define MKDIR `/bin/mkdir`
Definition at line 63 of file file.c.
Referenced by Mkdir().
#define RM `/bin/rm`
Definition at line 62 of file file.c.
Referenced by Rmdir().
Function Documentation
int Mkdir (char * name)
Definition at line 80 of file file.c.
References AddArgument(), Execute(), InitArgv(), and MKDIR.
int Rmdir (char * name)
Definition at line 66 of file file.c.
References AddArgument(), Execute(), InitArgv(), and RM.