file.h File Reference
#include <config.h>
#include <stdio.h>
Functions
int Rmdir (char *name)
int Mkdir (char *name)
Function Documentation
int Mkdir (char * name)
Definition at line 80 of file file.c.
References AddArgument(), Execute(), InitArgv(), and MKDIR.
int Rmdir (char * name)
Definition at line 66 of file file.c.
References AddArgument(), Execute(), InitArgv(), and RM.