func_list.h File Reference
#include <config.h>
#include <library/char_array_symbol.h>
Typedefs
typedef CHAR_ARRAY_Symbol_Table Func_Name_List
Functions
Func_Name_List * new_Func_Name_List (char *name_list)
void * delete_Func_Name_List (Func_Name_List *list)
int search_Func_Name_List (Func_Name_List *list, char *func_name)
int is_in_Func_Name_List (Func_Name_List *list, char *func_name)
Typedef Documentation
typedef CHAR_ARRAY_Symbol_Table Func_Name_List
Definition at line 72 of file func_list.h.
Function Documentation
void* delete_Func_Name_List (Func_Name_List * list)
Definition at line 186 of file func_list.c.
References CHAR_ARRAY_delete_symbol_table(), I_punt(), and NULL.
int is_in_Func_Name_List (Func_Name_List * list, char * func_name)
Definition at line 203 of file func_list.c.
References CHAR_ARRAY_find_symbol(), I_punt(), NULL, and relevant_len().
Func_Name_List* new_Func_Name_List (char * name_list)
Definition at line 138 of file func_list.c.
References CHAR_ARRAY_add_symbol(), CHAR_ARRAY_find_symbol(), CHAR_ARRAY_new_symbol_table(), I_punt(), NULL, and relevant_len().
int search_Func_Name_List (Func_Name_List * list, char * func_name)