func_list.c File Reference
#include <config.h>
#include <stdio.h>
#include <ctype.h>
#include <library/i_error.h>
#include `func_list.h`
Functions
static int relevant_len (char *func_name)
Func_Name_List * new_Func_Name_List (char *name_list)
void * delete_Func_Name_List (Func_Name_List *list)
int is_in_Func_Name_List (Func_Name_List *list, char *func_name)
Function Documentation
void* delete_Func_Name_List (Func_Name_List * list)
Definition at line 186 of file func_list.c.
References CHAR_ARRAY_delete_symbol_table(), I_punt(), and NULL.
int is_in_Func_Name_List (Func_Name_List * list, char * func_name)
Definition at line 203 of file func_list.c.
References CHAR_ARRAY_find_symbol(), I_punt(), NULL, and relevant_len().
Func_Name_List* new_Func_Name_List (char * name_list)
Definition at line 138 of file func_list.c.
References CHAR_ARRAY_add_symbol(), CHAR_ARRAY_find_symbol(), CHAR_ARRAY_new_symbol_table(), I_punt(), NULL, and relevant_len().
static int relevant_len (char * func_name) [static]
Definition at line 83 of file func_list.c.
Referenced by is_in_Func_Name_List(), and new_Func_Name_List().