graph.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/graph.h>
Defines
#define AUTO_REMOVE_MULTIPLE_ARCS
Functions
static void Punt (char *mesg)
Node NewNode (void)
Node FreeNode (Node *node)
Arc NewArc (void)
Arc FreeArc (Arc *arc)
void ConnectNodes (Node src_node, Node dest_node, int relation)
int PrintNodeCount ()
void DisconnectNodes (Node src_node, Node dest_node, int relation)
Arc FindSrcArc (Node src_node, Node dest_node, int type)
Arc FindDestArc (Node src_node, Node dest_node, int type)
static int _Add_2_nd_buf (Node node)
void RemoveNodes (Node *node)
int MarkNodesZero (Node node)
int MarkNodes (Node node, int mask, int mark)
int VisitNodes (Node node, int mark, int(*fn)(Node))
static int MarkStatusBits (Node node)
static int ClearStatusBits (Node node, int(*fn)(Node))
int VisitAllNodes (Node node, int(*fn)(Node))
static int FindNonZero (Node node)
int IsCyclic (Node node)
FGraph NewGraph (void)
FGraph FreeGraph (FGraph *graph)
void AddNode (FGraph graph, Node node)
Node FindNode (FGraph graph, int node_id)
Node DeleteNode (FGraph graph, int node_id)
Variables
static Node d_node_list = 0
static Arc d_arc_list = 0
static int node_count
static Node nd_buf [MAX_GRAPH_SIZE]
static int nd_buf_size = 0
static FGraph d_graph_list = 0
Define Documentation
#define AUTO_REMOVE_MULTIPLE_ARCS
Definition at line 71 of file graph.c.
Function Documentation
static int _Add_2_nd_buf (Node node) [static]
Definition at line 317 of file graph.c.
References MAX_GRAPH_SIZE, nd_buf, nd_buf_size, node, and Punt().
Referenced by MarkNodes(), MarkNodesZero(), RemoveNodes(), and VisitNodes().
void AddNode (FGraph graph, Node node)
Definition at line 602 of file graph.c.
References graph, nextNode, node, and _FGraph::nodes.
Referenced by add_df_node(), connect_df_node(), DecodeArc(), DecodeNode(), DecodeRoot(), and PlaceTraces().
static int ClearStatusBits (Node node, int(*)(Node) fn) [static]
Definition at line 475 of file graph.c.
References destinationArcs, destinationNode, isNil, nextArc, node, nodeStatus, and RESERVED_STATUS_BITS.
Referenced by VisitAllNodes().
void ConnectNodes (Node src_node, Node dest_node, int relation)
Definition at line 169 of file graph.c.
References arcType, destinationArcs, destinationNode, isNil, NewArc(), nextArc, node_count, Punt(), sourceArcs, and sourceNode.
Referenced by connect_df_node(), DecodeArc(), and PlaceTraces().
Node DeleteNode (FGraph graph, int node_id)
Definition at line 633 of file graph.c.
References FindNode(), graph, nextNode, and _FGraph::nodes.
void DisconnectNodes (Node src_node, Node dest_node, int relation)
Definition at line 213 of file graph.c.
References arcType, destinationArcs, destinationNode, FreeArc(), isNil, nextArc, sourceArcs, and sourceNode.
Arc FindDestArc (Node src_node, Node dest_node, int type)
Definition at line 296 of file graph.c.
References arcType, destinationArcs, destinationNode, nextArc, and sourceNode.
Referenced by DecodeArc(), PlaceTraces(), and SelectTraces().
Node FindNode (FGraph graph, int node_id)
Definition at line 623 of file graph.c.
References graph, nextNode, nodeId, and _FGraph::nodes.
Referenced by add_df_node(), connect_df_node(), DecodeArc(), DecodeNode(), DecodeRoot(), DeleteNode(), and PlaceTraces().
static int FindNonZero (Node node) [static]
Definition at line 522 of file graph.c.
References destinationArcs, destinationNode, isNil, nextArc, node, and nodeStatus.
Referenced by IsCyclic().
Arc FindSrcArc (Node src_node, Node dest_node, int type)
Definition at line 278 of file graph.c.
References arcType, destinationNode, nextArc, sourceArcs, and sourceNode.
Referenced by DecodeArc(), PlaceTraces(), and SelectTraces().
Arc FreeArc (Arc * arc)
Definition at line 150 of file graph.c.
References d_arc_list, and nextArc.
Referenced by DisconnectNodes(), and RemoveNodes().
FGraph FreeGraph (FGraph * graph)
Definition at line 581 of file graph.c.
References d_graph_list, graph, nodes, and RemoveNodes().
Referenced by define_df_graph(), and PlaceTraces().
Node FreeNode (Node * node)
Definition at line 111 of file graph.c.
References d_node_list, nextNode, and node.
Referenced by RemoveNodes().
int IsCyclic (Node node)
Definition at line 551 of file graph.c.
References FindNonZero(), MarkNodesZero(), and node.
int MarkNodes (Node node, int mask, int mark)
Definition at line 387 of file graph.c.
References _Add_2_nd_buf(), nd_buf, nd_buf_size, node, nodeStatus, Punt(), RESERVED_STATUS_BITS, and VisitAllNodes().
int MarkNodesZero (Node node)
Definition at line 366 of file graph.c.
References _Add_2_nd_buf(), nd_buf, nd_buf_size, node, nodeStatus, and VisitAllNodes().
Referenced by IsCyclic().
static int MarkStatusBits (Node node) [static]
Definition at line 458 of file graph.c.
References destinationArcs, destinationNode, isNil, nextArc, node, nodeStatus, and RESERVED_STATUS_BITS.
Referenced by VisitAllNodes().
Arc NewArc (void)
Definition at line 125 of file graph.c.
References arcExt, arcType, arcWeight, d_arc_list, destinationNode, isNil, nextArc, Punt(), and sourceNode.
Referenced by ConnectNodes().
FGraph NewGraph (void)
Definition at line 561 of file graph.c.
References d_graph_list, _FGraph::extension, isNil, _FGraph::next, _FGraph::nodes, Punt(), and _FGraph::root.
Referenced by define_df_graph(), PlaceTraces(), and ReadGraph().
Node NewNode (void)
Definition at line 84 of file graph.c.
References d_node_list, destinationArcs, isNil, new_node(), nextNode, nodeExt, nodeId, nodeStatus, nodeType, nodeWeight, Punt(), and sourceArcs.
Referenced by add_df_node(), connect_df_node(), DecodeArc(), DecodeNode(), DecodeRoot(), GetNode(), and PlaceTraces().
int PrintNodeCount ()
Definition at line 202 of file graph.c.
References node_count.
static void Punt (char * mesg) [static]
Definition at line 74 of file graph.c.
void RemoveNodes (Node * node)
Definition at line 328 of file graph.c.
References _Add_2_nd_buf(), destinationArcs, FreeArc(), FreeNode(), isNil, nd_buf, nd_buf_size, nextArc, node, sourceArcs, and VisitAllNodes().
Referenced by FreeGraph().
int VisitAllNodes (Node node, int(*)(Node) fn)
Definition at line 498 of file graph.c.
References ClearStatusBits(), MarkStatusBits(), and node.
Referenced by MarkNodes(), MarkNodesZero(), RemoveNodes(), and VisitNodes().
int VisitNodes (Node node, int mark, int(*)(Node) fn)
Definition at line 419 of file graph.c.
References _Add_2_nd_buf(), nd_buf, nd_buf_size, node, nodeStatus, and VisitAllNodes().
Variable Documentation
Arc d_arc_list = 0 [static]
Definition at line 121 of file graph.c.
Referenced by FreeArc(), and NewArc().
FGraph d_graph_list = 0 [static]
Definition at line 557 of file graph.c.
Referenced by FreeGraph(), and NewGraph().
Node d_node_list = 0 [static]
Definition at line 80 of file graph.c.
Referenced by FreeNode(), and NewNode().
Node nd_buf[MAX_GRAPH_SIZE] [static]
Definition at line 314 of file graph.c.
Referenced by _Add_2_nd_buf(), MarkNodes(), MarkNodesZero(), RemoveNodes(), and VisitNodes().
int nd_buf_size = 0 [static]
Definition at line 315 of file graph.c.
Referenced by _Add_2_nd_buf(), MarkNodes(), MarkNodesZero(), RemoveNodes(), and VisitNodes().
int node_count [static]
Definition at line 166 of file graph.c.
Referenced by ConnectNodes(), and PrintNodeCount().