hash.h File Reference
#include <config.h>
Data Structures
struct _Entry
Defines
#define INVALID_ENTRY -1
Typedefs
typedef _Entry * Entry
Functions
int NewHashTbl (int max_size)
Entry AddEntry (int tbl_id, int key, int type)
Entry FindEntry (int tbl_id, int key, int type)
void ClearHashTbl (int tbl_id)
Define Documentation
#define INVALID_ENTRY -1
Definition at line 68 of file hash.h.
Referenced by AddEntry(), ClearHashTbl(), FindEntry(), Hash(), and NewHashTbl().
Typedef Documentation
typedef struct _Entry * Entry
Function Documentation
Entry AddEntry (int tbl_id, int key, int type)
Add a new entry in the hash table.
Definition at line 167 of file hash.c.
References _Tbl::array, error(), Hash(), INVALID_ENTRY, _Entry::key, next_tbl, _Entry::ptr, TBL, _Entry::type, and _Entry::value.
void ClearHashTbl (int tbl_id)
Completely erase a hash table
Definition at line 208 of file hash.c.
References _Tbl::array, error(), INVALID_ENTRY, _Entry::key, next_tbl, _Entry::ptr, _Tbl::size, TBL, _Entry::type, and _Entry::value.
Entry FindEntry (int tbl_id, int key, int type)
Find an entry in the hash table.
Definition at line 189 of file hash.c.
References _Tbl::array, error(), Hash(), INVALID_ENTRY, next_tbl, TBL, and _Entry::type.
int NewHashTbl (int max_size)
Create a new symbol table.
get next table
Definition at line 138 of file hash.c.
References _Tbl::array, error(), INVALID_ENTRY, _Entry::key, MAX, next_tbl, _Entry::ptr, _Tbl::size, TBL, _Entry::type, and _Entry::value.