hash.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/hash.h>
Data Structures
struct _Tbl
Defines
#define MAX 100
Typedefs
typedef _Tbl * Tbl
Functions
static void error (char *mesg)
static int Hash (Tbl tbl, int key, int type)
int NewHashTbl (int max_size)
Entry AddEntry (int tbl_id, int key, int type)
Entry FindEntry (int tbl_id, int key, int type)
void ClearHashTbl (int tbl_id)
Variables
static _Tbl TBL [MAX]
static int next_tbl = 0
Define Documentation
#define MAX 100
Definition at line 71 of file hash.c.
Referenced by NewHashTbl(), NewSymTbl(), print_set(), Set_subtract_union(), and Set_union().
Typedef Documentation
typedef struct _Tbl * Tbl
Function Documentation
Entry AddEntry (int tbl_id, int key, int type)
Add a new entry in the hash table.
Definition at line 167 of file hash.c.
References _Tbl::array, error(), Hash(), INVALID_ENTRY, _Entry::key, next_tbl, _Entry::ptr, TBL, _Entry::type, and _Entry::value.
void ClearHashTbl (int tbl_id)
Completely erase a hash table
Definition at line 208 of file hash.c.
References _Tbl::array, error(), INVALID_ENTRY, _Entry::key, next_tbl, _Entry::ptr, _Tbl::size, TBL, _Entry::type, and _Entry::value.
static void error (char * mesg) [static]
Definition at line 85 of file hash.c.
Referenced by AddEntry(), AddSym(), ClearFreeSymTbl(), ClearHashTbl(), ClearSymTbl(), FindEntry(), FindSym(), Hash(), NewHashTbl(), and NewSymTbl().
Entry FindEntry (int tbl_id, int key, int type)
Find an entry in the hash table.
Definition at line 189 of file hash.c.
References _Tbl::array, error(), Hash(), INVALID_ENTRY, next_tbl, TBL, and _Entry::type.
static int Hash (Tbl tbl, int key, int type) [static]
Definition at line 96 of file hash.c.
References _Tbl::array, error(), INVALID_ENTRY, and _Tbl::size.
Referenced by AddEntry(), AddSym(), FindEntry(), and FindSym().
int NewHashTbl (int max_size)
Create a new symbol table.
get next table
Definition at line 138 of file hash.c.
References _Tbl::array, error(), INVALID_ENTRY, _Entry::key, MAX, next_tbl, _Entry::ptr, _Tbl::size, TBL, _Entry::type, and _Entry::value.
Variable Documentation
int next_tbl = 0 [static]
Definition at line 81 of file hash.c.
Referenced by AddEntry(), AddSym(), C_open(), ClearFreeSymTbl(), ClearHashTbl(), ClearSymTbl(), FindEntry(), FindSym(), NewHashTbl(), and NewSymTbl().
_Tbl TBL[MAX] [static]
Definition at line 80 of file hash.c.
Referenced by AddEntry(), AddSym(), C_clear(), C_clear_attr(), C_clear_free_all(), C_clear_free_name(), C_delete(), C_delete_tbl(), C_find(), C_find_from_index(), C_find_index(), C_forall(), C_full(), C_open(), C_unique_name(), C_update(), ClearFreeSymTbl(), ClearHashTbl(), ClearSymTbl(), find_symbol(), FindEntry(), FindSym(), NewHashTbl(), and NewSymTbl().