heap.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/l_alloc_new.h>
#include <library/heap.h>
Defines
#define Heap_NodeSwap(a, b)
Functions
static void HeapifyMax (Heap *root)
static void HeapifyMin (Heap *root)
Heap * Heap_Create (int dir)
Heap * Heap_Dispose (Heap *root, void(*element_dispose)(void *))
void Heap_Insert (Heap *root, void *element, double weight)
void * Heap_Top (Heap *root)
double * Heap_TopWeight (Heap *root)
void * Heap_ExtractTop (Heap *root)
Variables
static L_Alloc_Pool * heapNodePool = NULL
Define Documentation
#define Heap_NodeSwap(a, b)
Value:
{  HeapNode node; \
                                   node.weight = (a)->weight; \
                                   node.element = (a)->element; \
                                   (a)->weight = (b)->weight; \
                                   (a)->element = (b)->element; \
                                   (b)->weight = node.weight; \
                                   (b)->element = node.element; \
                                }
Definition at line 87 of file heap.c.
Referenced by Heap_Insert(), HeapifyMax(), and HeapifyMin().
Function Documentation
Heap* Heap_Create (int dir)
Definition at line 163 of file heap.c.
References Heap::dir, Heap::heap, heapNodePool, L_create_alloc_pool(), NULL, and Heap::size.
Heap* Heap_Dispose (Heap * root, void(*)(void *) element_dispose)
Definition at line 184 of file heap.c.
References Heap::heap, heapNodePool, L_free(), h_node::left, node, NULL, and h_node::right.
void* Heap_ExtractTop (Heap * root)
Definition at line 318 of file heap.c.
References Heap::dir, h_node::element, Heap::heap, HEAP_MAX, HeapifyMax(), HeapifyMin(), heapNodePool, L_free(), h_node::left, NULL, h_node::p, h_node::right, Heap::size, and h_node::weight.
void Heap_Insert (Heap * root, void * element, double weight)
Definition at line 228 of file heap.c.
References Heap::dir, h_node::element, Heap::heap, HEAP_MAX, Heap_NodeSwap, heapNodePool, L_alloc(), h_node::left, NULL, h_node::p, h_node::right, Heap::size, and h_node::weight.
void* Heap_Top (Heap * root)
Definition at line 294 of file heap.c.
References h_node::element, Heap::heap, NULL, and Heap::size.
double* Heap_TopWeight (Heap * root)
Definition at line 306 of file heap.c.
References Heap::heap, NULL, Heap::size, and h_node::weight.
static void HeapifyMax (Heap * root) [static]
Definition at line 99 of file heap.c.
References Heap::heap, Heap_NodeSwap, h_node::left, NULL, h_node::right, and h_node::weight.
Referenced by Heap_ExtractTop().
static void HeapifyMin (Heap * root) [static]
Definition at line 129 of file heap.c.
References Heap::heap, Heap_NodeSwap, h_node::left, NULL, h_node::right, and h_node::weight.
Referenced by Heap_ExtractTop().
Variable Documentation
L_Alloc_Pool* heapNodePool = NULL [static]
Definition at line 67 of file heap.c.
Referenced by Heap_Create(), Heap_Dispose(), Heap_ExtractTop(), and Heap_Insert().