i_bdd_interface.h File Reference
#include <config.h>
Functions
List I_BDD_minterms (DdManager *dd, DdNode *node)
unsigned int I_BDD_num_terms (DdManager *dd)
void I_BDD_print_minterm (char *m, int n)
void I_BDD_print_minterms (List mins, int terms)
void I_BDD_new_mutex_domain (DdManager *dd, DdNode *node[], unsigned int size)
Function Documentation
List I_BDD_minterms (DdManager * dd, DdNode * node)
Definition at line 133 of file i_bdd_interface.c.
References I_BDD_minterms_aux(), I_punt(), and NULL.
void I_BDD_new_mutex_domain (DdManager * dd, DdNode * node[], unsigned int size)
Definition at line 204 of file i_bdd_interface.c.
References I_punt().
unsigned int I_BDD_num_terms (DdManager * dd)
Definition at line 76 of file i_bdd_interface.c.
void I_BDD_print_minterm (char * m, int n)
Definition at line 156 of file i_bdd_interface.c.
void I_BDD_print_minterms (List mins, int terms)
Definition at line 168 of file i_bdd_interface.c.
References List_next(), and List_start().