i_bdd_interface.c File Reference
#include <config.h>
#include <stdlib.h>
#include <library/i_error.h>
#include <library/l_alloc_new.h>
#include <library/i_global.h>
#include <library/i_list.h>
#include <bdd/cudd.h>
#include <library/i_bdd_interface.h>
#include <bdd/cuddInt.h>
Functions
unsigned int I_BDD_num_terms (DdManager *dd)
static void I_BDD_minterms_aux (DdManager *dd, DdNode *node, char *list, List *minterm_list)
List I_BDD_minterms (DdManager *dd, DdNode *node)
void I_BDD_print_minterm (char *m, int n)
void I_BDD_print_minterms (List mins, int terms)
void I_BDD_new_mutex_domain (DdManager *dd, DdNode *node[], unsigned int size)
Function Documentation
List I_BDD_minterms (DdManager * dd, DdNode * node)
Definition at line 133 of file i_bdd_interface.c.
References I_BDD_minterms_aux(), I_punt(), and NULL.
static void I_BDD_minterms_aux (DdManager * dd, DdNode * node, char * list, List * minterm_list) [static]
Definition at line 82 of file i_bdd_interface.c.
References I_punt(), and List_insert_last().
Referenced by I_BDD_minterms().
void I_BDD_new_mutex_domain (DdManager * dd, DdNode * node[], unsigned int size)
Definition at line 204 of file i_bdd_interface.c.
References I_punt().
unsigned int I_BDD_num_terms (DdManager * dd)
Definition at line 76 of file i_bdd_interface.c.
void I_BDD_print_minterm (char * m, int n)
Definition at line 156 of file i_bdd_interface.c.
void I_BDD_print_minterms (List mins, int terms)
Definition at line 168 of file i_bdd_interface.c.
References List_next(), and List_start().