i_error.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include `i_error.h`
Functions
void I_punt (char *fmt,...)
void I_warn (char *fmt,...)
Function Documentation
void I_punt (char * fmt, ...)
Definition at line 70 of file i_error.c.
void I_warn (char * fmt, ...)
Definition at line 83 of file i_error.c.
Referenced by BlockSparseArraySet(), FreeBlockSparseArray(), and Graph_bfs_topo_sort().