i_error.h File Reference
#include <config.h>
Functions
void I_punt (char *fmt,...)
void I_warn (char *fmt,...)
Function Documentation
void I_punt (char * fmt, ...)
Definition at line 70 of file i_error.c.
void I_warn (char * fmt, ...)
Definition at line 83 of file i_error.c.
Referenced by BlockSparseArraySet(), FreeBlockSparseArray(), and Graph_bfs_topo_sort().