i_graph.c File Reference
#include <config.h>
#include <stdlib.h>
#include `i_graph.h`
Functions
GraphNode Graph_create_graph_node_given_id (Graph graph, int new_id)
GraphNode Graph_create_graph_node (Graph graph)
static GraphNode Graph_free_graph_node (GraphNode graph_node)
static GraphArc Graph_free_graph_arc (GraphArc graph_arc)
GraphArc Graph_create_graph_arc_given_id (Graph graph, int new_id)
GraphArc Graph_create_graph_arc (Graph graph)
static GraphEquivCD Graph_new_graph_equiv_cd ()
GraphEquivCD Graph_create_graph_equiv_cd (Graph graph)
GraphEquivCD Graph_free_graph_equiv_cd (GraphEquivCD graph_equiv_cd)
Graph Graph_create_graph ()
Graph Graph_free_graph (Graph graph)
GraphNode Graph_node_from_id (Graph graph, int id)
GraphNode Graph_node_from_id_or_null (Graph graph, int id)
GraphArc Graph_arc_from_id (Graph graph, int id)
GraphArc Graph_arc_from_id_or_null (Graph graph, int id)
GraphEquivCD Graph_equiv_cd_from_id (Graph graph, int id)
int Graph_size (Graph graph)
GraphArc Graph_connect_nodes_with_weight (Graph graph, GraphNode src_node, GraphNode dest_node, int wcet_weight)
GraphArc Graph_connect_nodes (Graph graph, GraphNode src_node, GraphNode dest_node)
int Graph_delete_unreachable (Graph graph, void(*node_ptr_del)(void *), void(*arc_ptr_del)(void *))
static void Graph_daVinci_visit (GraphNode node, FILE *daVinci_file, void(*print_ptr_func)(FILE *, GraphNode))
void Graph_daVinci (Graph graph, char *filename, void(*print_ptr_func)(FILE *, GraphNode))
void Graph_daVinci_visit2 (GraphNode node, void(*output_str_fn)(char *), void(*print_node_fn)(GraphNode, char *, int), void(*print_arc_fn)(GraphArc, char *, int), int detail)
void Graph_daVinci2 (Graph graph, void(*output_str_fn)(char *), void(*print_node_fn)(GraphNode, char *, int), void(*print_arc_fn)(GraphArc, char *, int), int detail)
void Graph_daVinci2_multi_root (Graph graph, void(*output_str_fn)(char *), void(*print_node_fn)(GraphNode, char *, int), void(*print_arc_fn)(GraphArc, char *, int), int detail)
void Graph_imm_dominator (Graph graph)
void Graph_dominator (Graph graph)
void Graph_imm_post_dominator (Graph graph)
void Graph_post_dominator (Graph graph)
void Graph_control_dependence (Graph graph)
void Graph_equiv_cd (Graph graph)
static void Graph_count_paths_visit (GraphNode node)
void Graph_count_paths (Graph graph)
void Graph_dfs_topo_visit (Graph graph, GraphNode node)
int Graph_dfs_topo_sort (Graph graph)
static void Graph_bfs_accept_node (Graph g, GraphNode n, List *fl, GraphNode *dn)
int Graph_bfs_topo_sort (Graph g)
int Graph_topological_sort (Graph graph)
void Graph_rev_topological_visit (Graph graph, GraphNode node)
void Graph_rev_topological_sort (Graph graph)
void Graph_preorder_dfs_visit (Graph graph, GraphNode node, int directed)
void Graph_preorder_dfs_sort (Graph graph, int directed)
Variables
L_Alloc_Pool * GraphPool = NULL
L_Alloc_Pool * GraphNodePool = NULL
L_Alloc_Pool * GraphArcPool = NULL
L_Alloc_Pool * GraphEquivCDPool = NULL
Function Documentation
GraphArc Graph_arc_from_id (Graph graph, int id)
Definition at line 278 of file i_graph.c.
References graph, and HashTable_find().
Referenced by Graph_equiv_cd().
GraphArc Graph_arc_from_id_or_null (Graph graph, int id)
Definition at line 282 of file i_graph.c.
References graph, and HashTable_find_or_null().
Referenced by Graph_create_graph_arc_given_id().
static void Graph_bfs_accept_node (Graph g, GraphNode n, List * fl, GraphNode * dn) [static]
Definition at line 1118 of file i_graph.c.
References graph_node::flags, GRAPH_NODE_DEFER, GRAPH_NODE_VISIT_BLACK, GRAPH_NODE_VISIT_GREY, GRAPH_NODE_VISIT_WHITE, GraphArcDest, I_punt(), List_insert_last(), List_next(), List_start(), graph_node::succ, graph_node::tflags, and graph::topo_list.
Referenced by Graph_bfs_topo_sort().
int Graph_bfs_topo_sort (Graph g)
Definition at line 1145 of file i_graph.c.
References graph::flags, graph_node::flags, Graph_bfs_accept_node(), Graph_dfs_topo_sort(), GRAPH_NODE_HEADER, GRAPH_NODE_VISIT_BLACK, GRAPH_NODE_VISIT_WHITE, GraphArcSrc, GRAPHTOPOSORT, I_warn(), List_delete_current(), List_insert_last(), List_next(), List_reset(), List_size(), List_start(), graph::nodes, NULL, graph_node::pred, graph::root, graph_node::tflags, and graph::topo_list.
GraphArc Graph_connect_nodes (Graph graph, GraphNode src_node, GraphNode dest_node)
Definition at line 313 of file i_graph.c.
References graph, Graph_create_graph_arc(), List_insert_last(), graph_arc::pred, graph_node::pred, graph_arc::succ, and graph_node::succ.
GraphArc Graph_connect_nodes_with_weight (Graph graph, GraphNode src_node, GraphNode dest_node, int wcet_weight)
Definition at line 297 of file i_graph.c.
References graph, Graph_create_graph_arc(), List_insert_last(), graph_arc::pred, graph_node::pred, graph_arc::succ, graph_node::succ, and graph_arc::wcet_weight.
void Graph_control_dependence (Graph graph)
Definition at line 934 of file i_graph.c.
References graph_node::contr_dep, I_Node::dom, graph_node::flags, graph, Graph_imm_post_dominator(), Graph_topological_sort(), GraphArcDest, GRAPHCONTROL, GRAPHIMMPOSTDOM, graph_node::id, I_Node::id, graph_arc::id, graph_node::imm_post_dom, List_last(), List_next(), List_start(), node, NULL, graph_node::post_dom, Set_add(), and Set_in().
Referenced by Graph_equiv_cd().
void Graph_count_paths (Graph graph)
Definition at line 1047 of file i_graph.c.
References graph, Graph_count_paths_visit(), Graph_dominator(), GRAPHCOUNTPATH, GRAPHDOM, List_next(), List_size(), List_start(), and node.
static void Graph_count_paths_visit (GraphNode node) [static]
Definition at line 1028 of file i_graph.c.
References I_Node::dom, graph_node::id, graph_node::info, List_next(), List_start(), node, Set_in(), graph_arc::succ, and graph_node::tflags.
Referenced by Graph_count_paths().
Graph Graph_create_graph ()
Definition at line 198 of file i_graph.c.
References graph::arc_id, graph::arcs, graph::dfs_list, graph::equiv_cds, graph::flags, GRAPHMODIFIED, GraphPool, graph::hash_id_arc, graph::hash_id_equiv_cd, graph::hash_id_node, HashTable_create(), L_alloc(), L_create_alloc_pool(), graph::node_id, graph::nodes, NULL, graph::rev_topo_list, graph::root, and graph::topo_list.
GraphArc Graph_create_graph_arc (Graph graph)
Definition at line 150 of file i_graph.c.
References graph, and Graph_create_graph_arc_given_id().
Referenced by Graph_connect_nodes(), and Graph_connect_nodes_with_weight().
GraphArc Graph_create_graph_arc_given_id (Graph graph, int new_id)
Definition at line 126 of file i_graph.c.
References graph_arc::flags, graph, Graph_arc_from_id_or_null(), GraphArcPool, GRAPHMODIFIED, HashTable_insert(), I_punt(), graph_arc::id, graph_arc::info, L_alloc(), L_create_alloc_pool(), List_insert_last(), NULL, graph_arc::pred, graph_arc::ptr, and graph_arc::succ.
Referenced by Graph_create_graph_arc().
GraphEquivCD Graph_create_graph_equiv_cd (Graph graph)
Definition at line 171 of file i_graph.c.
References graph, Graph_new_graph_equiv_cd(), HashTable_insert(), graph_equiv_cd::id, List_insert_last(), and List_size().
Referenced by Graph_equiv_cd().
GraphNode Graph_create_graph_node (Graph graph)
Definition at line 104 of file i_graph.c.
References graph, and Graph_create_graph_node_given_id().
GraphNode Graph_create_graph_node_given_id (Graph graph, int new_id)
Definition at line 72 of file i_graph.c.
References graph_node::contr_dep, graph_node::dom, graph_node::equiv_cd, graph_node::flags, graph, Graph_node_from_id_or_null(), GRAPHMODIFIED, GraphNodePool, HashTable_insert(), I_punt(), graph_node::id, graph_node::imm_dom, graph_node::imm_post_dom, graph_node::info, L_alloc(), L_create_alloc_pool(), List_insert_last(), _FGraph::nodes, NULL, graph_node::post_dom, graph_node::pred, graph_node::ptr, graph_node::succ, and graph_node::tflags.
Referenced by Graph_create_graph_node().
void Graph_daVinci (Graph graph, char * filename, void(*)(FILE *, GraphNode) print_ptr_func)
Definition at line 420 of file i_graph.c.
References graph, Graph_daVinci_visit(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, I_close_output_file(), I_open_output_file(), List_next(), List_start(), node, and NULL.
void Graph_daVinci2 (Graph graph, void(*)(char *) output_str_fn, void(*)(GraphNode, char *, int) print_node_fn, void(*)(GraphArc, char *, int) print_arc_fn, int detail)
Definition at line 660 of file i_graph.c.
References graph, Graph_daVinci_visit2(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, GraphRootNode, List_next(), List_start(), and node.
void Graph_daVinci2_multi_root (Graph graph, void(*)(char *) output_str_fn, void(*)(GraphNode, char *, int) print_node_fn, void(*)(GraphArc, char *, int) print_arc_fn, int detail)
Definition at line 693 of file i_graph.c.
References graph, Graph_daVinci_visit2(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, GraphRootNode, List_first(), List_next(), List_start(), node, NULL, and graph_arc::succ.
static void Graph_daVinci_visit (GraphNode node, FILE * daVinci_file, void(*)(FILE *, GraphNode) print_ptr_func) [static]
Definition at line 376 of file i_graph.c.
References I_Node::dom, GRAPH_NODE_VISIT_BLACK, graph_node::id, List_get_next(), List_next(), List_start(), node, Set_in(), and graph_arc::succ.
Referenced by Graph_daVinci().
void Graph_daVinci_visit2 (GraphNode node, void(*)(char *) output_str_fn, void(*)(GraphNode, char *, int) print_node_fn, void(*)(GraphArc, char *, int) print_arc_fn, int detail)
Definition at line 444 of file i_graph.c.
References DAV_ALL_EDGE_PROPERTIES, DAV_ALL_NODE_PROPERTIES, DAV_BORDER, DAV_COLOR, DAV_EDGECOLOR, DAV_EDGEDIR, DAV_EDGEPATTERN, DAV_FONTFAMILY, DAV_FONTSTYLE, DAV_GO, DAV_HIDDEN, DAV_ID, DAV_OBJECT, DAV_TYPE, EXTRACT_BIT_VAL, GRAPH_NODE_VISIT_BLACK, List_get_next(), List_next(), List_start(), node, and graph_arc::succ.
Referenced by Graph_daVinci2(), and Graph_daVinci2_multi_root().
int Graph_delete_unreachable (Graph graph, void(*)(void *) node_ptr_del, void(*)(void *) arc_ptr_del)
Definition at line 326 of file i_graph.c.
References graph, Graph_free_graph_arc(), Graph_free_graph_node(), Graph_topological_sort(), GraphArcContents, GraphNodeContents, GRAPHTOPOSORT, List_delete_current(), List_next(), List_remove(), List_reset(), List_start(), node, _FGraph::nodes, graph_node::pred, and graph_arc::succ.
int Graph_dfs_topo_sort (Graph graph)
Definition at line 1087 of file i_graph.c.
References graph, Graph_dfs_topo_visit(), GRAPHTOPOSORT, List_next(), List_reset(), List_size(), List_start(), node, _FGraph::nodes, and _FGraph::root.
Referenced by Graph_bfs_topo_sort(), and Graph_topological_sort().
void Graph_dfs_topo_visit (Graph graph, GraphNode node)
Definition at line 1070 of file i_graph.c.
References graph, GraphArcDest, List_insert_first(), List_next(), List_start(), node, and graph_node::tflags.
Referenced by Graph_dfs_topo_sort().
void Graph_dominator (Graph graph)
Definition at line 761 of file i_graph.c.
References I_Node::dom, graph_node::dom, graph, GRAPHDOM, I_Node::id, List_next(), List_size(), List_start(), node, _FGraph::nodes, NULL, graph_arc::pred, Set_add(), Set_dispose(), Set_intersect_acc(), Set_same(), and Set_union().
Referenced by Graph_count_paths(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_imm_dominator(), Graph_preorder_dfs_sort(), and Graph_rev_topological_sort().
void Graph_equiv_cd (Graph graph)
Definition at line 981 of file i_graph.c.
References graph_equiv_cd::arcs, Bool, graph_equiv_cd::contr_dep, FALSE, graph, Graph_arc_from_id(), Graph_control_dependence(), Graph_create_graph_equiv_cd(), GRAPHCONTROL, GRAPHEQUIVCD, List_insert_last(), List_next(), List_start(), node, graph_equiv_cd::nodes, NULL, Set_2array(), Set_same(), Set_size(), Set_union(), and TRUE.
GraphEquivCD Graph_equiv_cd_from_id (Graph graph, int id)
Definition at line 286 of file i_graph.c.
References graph, and HashTable_find().
Graph Graph_free_graph (Graph graph)
Definition at line 226 of file i_graph.c.
References graph, Graph_free_graph_arc(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), GraphArcPool, GraphEquivCDPool, GraphNodePool, GraphPool, HashTable_free(), L_free(), L_print_alloc_info(), List_next(), List_reset(), List_start(), node, _FGraph::nodes, and NULL.
static GraphArc Graph_free_graph_arc (GraphArc graph_arc) [static]
Definition at line 120 of file i_graph.c.
References GraphArcPool, L_free(), and NULL.
Referenced by Graph_delete_unreachable(), and Graph_free_graph().
GraphEquivCD Graph_free_graph_equiv_cd (GraphEquivCD graph_equiv_cd)
Definition at line 183 of file i_graph.c.
References graph_equiv_cd::arcs, graph_equiv_cd::contr_dep, GraphEquivCDPool, L_free(), List_reset(), graph_equiv_cd::nodes, NULL, and Set_dispose().
Referenced by Graph_free_graph().
static GraphNode Graph_free_graph_node (GraphNode graph_node) [static]
Definition at line 108 of file i_graph.c.
References graph_node::contr_dep, graph_node::dom, GraphNodePool, L_free(), List_reset(), NULL, graph_node::post_dom, graph_node::pred, Set_dispose(), and graph_node::succ.
Referenced by Graph_delete_unreachable(), and Graph_free_graph().
void Graph_imm_dominator (Graph graph)
Definition at line 734 of file i_graph.c.
References I_Node::dom, graph_node::flags, graph, Graph_dominator(), GRAPHDOM, GRAPHIMMDOM, graph_node::id, List_next(), List_start(), node, NULL, and Set_in().
void Graph_imm_post_dominator (Graph graph)
Definition at line 841 of file i_graph.c.
References graph_node::flags, graph, Graph_post_dominator(), GRAPHIMMPOSTDOM, GRAPHPOSTDOM, graph_node::id, List_next(), List_prev(), List_start(), node, NULL, I_Node::post_dom, and Set_in().
Referenced by Graph_control_dependence().
static GraphEquivCD Graph_new_graph_equiv_cd () [static]
Definition at line 154 of file i_graph.c.
References graph_equiv_cd::arcs, graph_equiv_cd::contr_dep, GraphEquivCDPool, graph_equiv_cd::id, L_alloc(), L_create_alloc_pool(), graph_equiv_cd::nodes, NULL, and graph_equiv_cd::ptr.
Referenced by Graph_create_graph_equiv_cd().
GraphNode Graph_node_from_id (Graph graph, int id)
Definition at line 270 of file i_graph.c.
References graph, and HashTable_find().
GraphNode Graph_node_from_id_or_null (Graph graph, int id)
Definition at line 274 of file i_graph.c.
References graph, and HashTable_find_or_null().
Referenced by Graph_create_graph_node_given_id().
void Graph_post_dominator (Graph graph)
Definition at line 865 of file i_graph.c.
References graph, GRAPHPOSTDOM, I_Node::id, List_next(), List_size(), List_start(), node, _FGraph::nodes, NULL, I_Node::post_dom, graph_node::post_dom, Set_add(), Set_dispose(), Set_intersect_acc(), Set_same(), Set_union(), and graph_arc::succ.
Referenced by Graph_imm_post_dominator().
void Graph_preorder_dfs_sort (Graph graph, int directed)
Definition at line 1311 of file i_graph.c.
References graph, Graph_dominator(), GRAPH_NODE_VISIT_WHITE, Graph_preorder_dfs_visit(), GRAPHDFSPRESORT, GRAPHDOM, List_next(), List_reset(), List_start(), and node.
void Graph_preorder_dfs_visit (Graph graph, GraphNode node, int directed)
Definition at line 1282 of file i_graph.c.
References graph_arc::flags, graph, GRAPH_ARC_BACKEDGE, GRAPH_NODE_VISIT_BLACK, GRAPH_NODE_VISIT_GREY, GRAPH_NODE_VISIT_WHITE, GraphArcDest, GraphArcSrc, List_insert_last(), List_next(), List_start(), node, and graph_node::tflags.
Referenced by Graph_preorder_dfs_sort().
void Graph_rev_topological_sort (Graph graph)
Definition at line 1244 of file i_graph.c.
References graph, Graph_dominator(), Graph_rev_topological_visit(), GRAPHDOM, GRAPHREVTOPOSORT, I_punt(), List_next(), List_reset(), List_start(), node, and NULL.
void Graph_rev_topological_visit (Graph graph, GraphNode node)
Definition at line 1225 of file i_graph.c.
References graph, GraphArcSrc, List_insert_first(), List_next(), List_start(), node, and graph_node::tflags.
Referenced by Graph_rev_topological_sort().
int Graph_size (Graph graph)
Definition at line 290 of file i_graph.c.
References graph, I_punt(), List_size(), and _FGraph::nodes.
int Graph_topological_sort (Graph graph)
Definition at line 1221 of file i_graph.c.
References graph, and Graph_dfs_topo_sort().
Referenced by Graph_control_dependence(), and Graph_delete_unreachable().
Variable Documentation
L_Alloc_Pool* GraphArcPool = NULL
Definition at line 69 of file i_graph.c.
Referenced by Graph_create_graph_arc_given_id(), Graph_free_graph(), and Graph_free_graph_arc().
L_Alloc_Pool* GraphEquivCDPool = NULL
Definition at line 70 of file i_graph.c.
Referenced by Graph_free_graph(), Graph_free_graph_equiv_cd(), and Graph_new_graph_equiv_cd().
L_Alloc_Pool* GraphNodePool = NULL
Definition at line 68 of file i_graph.c.
Referenced by Graph_create_graph_node_given_id(), Graph_free_graph(), and Graph_free_graph_node().
L_Alloc_Pool* GraphPool = NULL
Definition at line 67 of file i_graph.c.
Referenced by Graph_create_graph(), and Graph_free_graph().