i_graph.h File Reference
#include <config.h>
#include <library/i_global.h>
#include <library/l_alloc_new.h>
#include <library/i_list.h>
#include <library/set.h>
#include <library/i_hash.h>
#include <library/i_error.h>
#include <library/i_io.h>
Data Structures
struct graph_equiv_cd
struct graph_node
struct graph_arc
struct graph
Defines
#define GraphContents(g) (g $\rightarrow$ ptr)
#define GraphRootNode(g) (g $\rightarrow$ root)
#define GraphNodeContents(n) (n $\rightarrow$ ptr)
#define GraphArcContents(a) (a $\rightarrow$ ptr)
#define GraphArcDest(a) (a $\rightarrow$ succ)
#define GraphArcSrc(a) (a $\rightarrow$ pred)
#define GraphTopoList(g) (g $\rightarrow$ topo_list)
#define GraphRevTopoList(g) (g $\rightarrow$ rev_topo_list)
#define GraphEquivCDContents(e) (e $\rightarrow$ ptr)
#define GRAPHMODIFIED 0x00000000
#define GRAPHTOPOSORT 0x00000001
#define GRAPHDOM 0x00000002
#define GRAPHEQUIVCD 0x00000004
#define GRAPHCONTROL 0x00000008
#define GRAPHPOSTDOM 0x00000010
#define GRAPHIMMPOSTDOM 0x00000020
#define GRAPHIMMDOM 0x00000040
#define GRAPHCOUNTPATH 0x00000080
#define GRAPHREVTOPOSORT 0x00000100
#define GRAPHDFSPRESORT 0x00000200
#define GRAPH_ARC_VISITED 0x00000001
#define GRAPH_ARC_BACKEDGE 0x00000002
#define GRAPH_NODE_START 0x00000001
#define GRAPH_NODE_STOP 0x00000002
#define GRAPH_NODE_HEADER 0x00000004
#define GRAPH_NODE_DEFER 0x00000008
#define GRAPH_NODE_VISIT_WHITE 0x00000000
#define GRAPH_NODE_VISIT_GREY 0x00000001
#define GRAPH_NODE_VISIT_BLACK 0x00000002
#define GRAPH_USER_DEF1 0x00400000
#define GRAPH_USER_DEF2 0x00800000
#define GRAPH_USER_DEF3 0x01000000
#define GRAPH_USER_DEF4 0x02000000
#define GRAPH_USER_DEF5 0x04000000
#define GRAPH_USER_DEF6 0x08000000
#define GRAPH_USER_DEF7 0x10000000
#define GRAPH_USER_DEF8 0x20000000
#define GRAPH_USER_DEF9 0x40000000
#define GRAPH_USER_DEF10 0x80000000
#define DAV_ALL_REQUIRED_PROPERTIES 0x00000003
#define DAV_TYPE 0x00000001
#define DAV_ID 0x00000002
#define DAV_ALL_NODE_PROPERTIES 0x00000FF0
#define DAV_OBJECT 0x00000010
#define DAV_FONTFAMILY 0x00000020
#define DAV_FONTSTYLE 0x00000040
#define DAV_COLOR 0x00000080
#define DAV_GO 0x00000100
#define DAV_ICONFILE 0x00000200
#define DAV_HIDDEN 0x00000400
#define DAV_BORDER 0x00000800
#define DAV_ALL_EDGE_PROPERTIES 0x00007000
#define DAV_EDGECOLOR 0x00001000
#define DAV_EDGEPATTERN 0x00002000
#define DAV_EDGEDIR 0x00004000
#define EXTRACT_BIT_VAL(flag, val) (((flag) & (val))==0 ? 0 : 1)
Typedefs
typedef graph_equiv_cd * GraphEquivCD
typedef graph_equiv_cd _GraphEquivCD
typedef graph_node * GraphNode
typedef graph_node _GraphNode
typedef graph_arc * GraphArc
typedef graph_arc _GraphArc
typedef graph * Graph
typedef graph _Graph
Functions
Graph Graph_create_graph ()
Graph Graph_free_graph (Graph graph)
GraphNode Graph_create_graph_node (Graph graph)
GraphNode Graph_create_graph_node_given_id (Graph graph, int new_id)
GraphArc Graph_create_graph_arc (Graph graph)
GraphArc Graph_create_graph_arc_given_id (Graph graph, int new_id)
GraphArc Graph_connect_nodes (Graph graph, GraphNode src_node, GraphNode dest_node)
GraphArc Graph_connect_nodes_with_weight (Graph graph, GraphNode src_node, GraphNode dest_node, int wcet_weight)
GraphNode Graph_node_from_id (Graph graph, int id)
GraphNode Graph_node_from_id_or_null (Graph graph, int id)
GraphArc Graph_arc_from_id (Graph graph, int id)
GraphArc Graph_arc_from_id_or_null (Graph graph, int id)
GraphEquivCD Graph_equiv_cd_from_id (Graph graph, int id)
int Graph_size (Graph graph)
void Graph_daVinci (Graph graph, char *filename, void(*print_ptr_func)(FILE *, GraphNode))
void Graph_daVinci2 (Graph graph, void(*output_str_fn)(char *), void(*print_node_fn)(GraphNode, char *, int), void(*print_arc_fn)(GraphArc, char *, int), int)
void Graph_daVinci2_multi_root (Graph graph, void(*output_str_fn)(char *), void(*print_node_fn)(GraphNode, char *, int), void(*print_arc_fn)(GraphArc, char *, int), int)
void Graph_count_paths (Graph graph)
int Graph_num_paths (Graph graph, GraphNode node)
void Graph_dominator (Graph graph)
void Graph_imm_dominator (Graph graph)
void Graph_post_dominator (Graph graph)
void Graph_imm_post_dominator (Graph graph)
void Graph_control_dependence (Graph graph)
void Graph_equiv_cd (Graph graph)
int Graph_topological_sort (Graph graph)
int Graph_bfs_topo_sort (Graph graph)
int Graph_dfs_topo_sort (Graph graph)
void Graph_rev_topological_sort (Graph graph)
void Graph_preorder_dfs_sort (Graph graph, int directed)
int Graph_delete_unreachable (Graph graph, void(*node_ptr_del)(void *), void(*arc_ptr_del)(void *))
Variables
L_Alloc_Pool * GraphPool
L_Alloc_Pool * GraphNodePool
L_Alloc_Pool * GraphArcPool
L_Alloc_Pool * GraphEquivCDPool
Define Documentation
#define DAV_ALL_EDGE_PROPERTIES 0x00007000
Definition at line 145 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_ALL_NODE_PROPERTIES 0x00000FF0
Definition at line 134 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_ALL_REQUIRED_PROPERTIES 0x00000003
Definition at line 130 of file i_graph.h.
#define DAV_BORDER 0x00000800
Definition at line 142 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_COLOR 0x00000080
Definition at line 138 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_EDGECOLOR 0x00001000
Definition at line 146 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_EDGEDIR 0x00004000
Definition at line 148 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_EDGEPATTERN 0x00002000
Definition at line 147 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_FONTFAMILY 0x00000020
Definition at line 136 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_FONTSTYLE 0x00000040
Definition at line 137 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_GO 0x00000100
Definition at line 139 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_HIDDEN 0x00000400
Definition at line 141 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_ICONFILE 0x00000200
Definition at line 140 of file i_graph.h.
#define DAV_ID 0x00000002
Definition at line 132 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_OBJECT 0x00000010
Definition at line 135 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define DAV_TYPE 0x00000001
Definition at line 131 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define EXTRACT_BIT_VAL(flag, val) (((flag) & (val))==0 ? 0 : 1)
Definition at line 150 of file i_graph.h.
Referenced by Graph_daVinci_visit2().
#define GRAPH_ARC_BACKEDGE 0x00000002
Definition at line 102 of file i_graph.h.
Referenced by Graph_preorder_dfs_visit().
#define GRAPH_ARC_VISITED 0x00000001
Definition at line 101 of file i_graph.h.
#define GRAPH_NODE_DEFER 0x00000008
Definition at line 109 of file i_graph.h.
Referenced by Graph_bfs_accept_node().
#define GRAPH_NODE_HEADER 0x00000004
Definition at line 108 of file i_graph.h.
Referenced by Graph_bfs_topo_sort().
#define GRAPH_NODE_START 0x00000001
Definition at line 106 of file i_graph.h.
#define GRAPH_NODE_STOP 0x00000002
Definition at line 107 of file i_graph.h.
#define GRAPH_NODE_VISIT_BLACK 0x00000002
Definition at line 115 of file i_graph.h.
Referenced by Graph_bfs_accept_node(), Graph_bfs_topo_sort(), Graph_daVinci_visit(), Graph_daVinci_visit2(), and Graph_preorder_dfs_visit().
#define GRAPH_NODE_VISIT_GREY 0x00000001
Definition at line 114 of file i_graph.h.
Referenced by Graph_bfs_accept_node(), and Graph_preorder_dfs_visit().
#define GRAPH_NODE_VISIT_WHITE 0x00000000
Definition at line 113 of file i_graph.h.
Referenced by Graph_bfs_accept_node(), Graph_bfs_topo_sort(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_preorder_dfs_sort(), and Graph_preorder_dfs_visit().
#define GRAPH_USER_DEF1 0x00400000
Definition at line 118 of file i_graph.h.
#define GRAPH_USER_DEF10 0x80000000
Definition at line 127 of file i_graph.h.
#define GRAPH_USER_DEF2 0x00800000
Definition at line 119 of file i_graph.h.
#define GRAPH_USER_DEF3 0x01000000
Definition at line 120 of file i_graph.h.
#define GRAPH_USER_DEF4 0x02000000
Definition at line 121 of file i_graph.h.
#define GRAPH_USER_DEF5 0x04000000
Definition at line 122 of file i_graph.h.
#define GRAPH_USER_DEF6 0x08000000
Definition at line 123 of file i_graph.h.
#define GRAPH_USER_DEF7 0x10000000
Definition at line 124 of file i_graph.h.
#define GRAPH_USER_DEF8 0x20000000
Definition at line 125 of file i_graph.h.
#define GRAPH_USER_DEF9 0x40000000
Definition at line 126 of file i_graph.h.
#define GraphArcContents(a) (a $\rightarrow$ ptr)
Definition at line 79 of file i_graph.h.
Referenced by Graph_delete_unreachable().
#define GraphArcDest(a) (a $\rightarrow$ succ)
Definition at line 80 of file i_graph.h.
Referenced by Graph_bfs_accept_node(), Graph_control_dependence(), Graph_dfs_topo_visit(), and Graph_preorder_dfs_visit().
#define GraphArcSrc(a) (a $\rightarrow$ pred)
Definition at line 81 of file i_graph.h.
Referenced by Graph_bfs_topo_sort(), Graph_preorder_dfs_visit(), and Graph_rev_topological_visit().
#define GraphContents(g) (g $\rightarrow$ ptr)
Definition at line 76 of file i_graph.h.
#define GRAPHCONTROL 0x00000008
Definition at line 93 of file i_graph.h.
Referenced by Graph_control_dependence(), and Graph_equiv_cd().
#define GRAPHCOUNTPATH 0x00000080
Definition at line 97 of file i_graph.h.
Referenced by Graph_count_paths().
#define GRAPHDFSPRESORT 0x00000200
Definition at line 99 of file i_graph.h.
Referenced by Graph_preorder_dfs_sort().
#define GRAPHDOM 0x00000002
Definition at line 91 of file i_graph.h.
Referenced by Graph_count_paths(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_dominator(), Graph_imm_dominator(), Graph_preorder_dfs_sort(), and Graph_rev_topological_sort().
#define GRAPHEQUIVCD 0x00000004
Definition at line 92 of file i_graph.h.
Referenced by Graph_equiv_cd().
#define GraphEquivCDContents(e) (e $\rightarrow$ ptr)
Definition at line 84 of file i_graph.h.
#define GRAPHIMMDOM 0x00000040
Definition at line 96 of file i_graph.h.
Referenced by Graph_imm_dominator().
#define GRAPHIMMPOSTDOM 0x00000020
Definition at line 95 of file i_graph.h.
Referenced by Graph_control_dependence(), and Graph_imm_post_dominator().
#define GRAPHMODIFIED 0x00000000
Definition at line 89 of file i_graph.h.
Referenced by Graph_create_graph(), Graph_create_graph_arc_given_id(), and Graph_create_graph_node_given_id().
#define GraphNodeContents(n) (n $\rightarrow$ ptr)
Definition at line 78 of file i_graph.h.
Referenced by Graph_delete_unreachable().
#define GRAPHPOSTDOM 0x00000010
Definition at line 94 of file i_graph.h.
Referenced by Graph_imm_post_dominator(), and Graph_post_dominator().
#define GraphRevTopoList(g) (g $\rightarrow$ rev_topo_list)
Definition at line 83 of file i_graph.h.
#define GRAPHREVTOPOSORT 0x00000100
Definition at line 98 of file i_graph.h.
Referenced by Graph_rev_topological_sort().
#define GraphRootNode(g) (g $\rightarrow$ root)
Definition at line 77 of file i_graph.h.
Referenced by Graph_daVinci2(), and Graph_daVinci2_multi_root().
#define GraphTopoList(g) (g $\rightarrow$ topo_list)
Definition at line 82 of file i_graph.h.
#define GRAPHTOPOSORT 0x00000001
Definition at line 90 of file i_graph.h.
Referenced by Graph_bfs_topo_sort(), Graph_delete_unreachable(), and Graph_dfs_topo_sort().
Typedef Documentation
typedef struct graph _Graph
typedef struct graph_arc _GraphArc
typedef struct graph_equiv_cd _GraphEquivCD
typedef struct graph_node _GraphNode
typedef struct graph * Graph
typedef struct graph_arc * GraphArc
typedef struct graph_equiv_cd * GraphEquivCD
typedef struct graph_node * GraphNode
Function Documentation
GraphArc Graph_arc_from_id (Graph graph, int id)
Definition at line 278 of file i_graph.c.
References graph, and HashTable_find().
Referenced by Graph_equiv_cd().
GraphArc Graph_arc_from_id_or_null (Graph graph, int id)
Definition at line 282 of file i_graph.c.
References graph, and HashTable_find_or_null().
Referenced by Graph_create_graph_arc_given_id().
int Graph_bfs_topo_sort (Graph graph)
Definition at line 1145 of file i_graph.c.
References graph_node::flags, graph::flags, Graph_bfs_accept_node(), Graph_dfs_topo_sort(), GRAPH_NODE_HEADER, GRAPH_NODE_VISIT_BLACK, GRAPH_NODE_VISIT_WHITE, GraphArcSrc, GRAPHTOPOSORT, I_warn(), List_delete_current(), List_insert_last(), List_next(), List_reset(), List_size(), List_start(), graph::nodes, NULL, graph_node::pred, graph::root, graph_node::tflags, and graph::topo_list.
GraphArc Graph_connect_nodes (Graph graph, GraphNode src_node, GraphNode dest_node)
Definition at line 313 of file i_graph.c.
References graph, Graph_create_graph_arc(), List_insert_last(), graph_node::pred, graph_arc::pred, graph_node::succ, and graph_arc::succ.
GraphArc Graph_connect_nodes_with_weight (Graph graph, GraphNode src_node, GraphNode dest_node, int wcet_weight)
Definition at line 297 of file i_graph.c.
References graph, Graph_create_graph_arc(), List_insert_last(), graph_node::pred, graph_arc::pred, graph_node::succ, graph_arc::succ, and graph_arc::wcet_weight.
void Graph_control_dependence (Graph graph)
Definition at line 934 of file i_graph.c.
References graph_node::contr_dep, I_Node::dom, graph_node::flags, graph, Graph_imm_post_dominator(), Graph_topological_sort(), GraphArcDest, GRAPHCONTROL, GRAPHIMMPOSTDOM, graph_arc::id, I_Node::id, graph_node::id, graph_node::imm_post_dom, List_last(), List_next(), List_start(), node, NULL, graph_node::post_dom, Set_add(), and Set_in().
Referenced by Graph_equiv_cd().
void Graph_count_paths (Graph graph)
Definition at line 1047 of file i_graph.c.
References graph, Graph_count_paths_visit(), Graph_dominator(), GRAPHCOUNTPATH, GRAPHDOM, List_next(), List_size(), List_start(), and node.
Graph Graph_create_graph ()
Definition at line 198 of file i_graph.c.
References graph::arc_id, graph::arcs, graph::dfs_list, graph::equiv_cds, graph::flags, GRAPHMODIFIED, GraphPool, graph::hash_id_arc, graph::hash_id_equiv_cd, graph::hash_id_node, HashTable_create(), L_alloc(), L_create_alloc_pool(), graph::node_id, graph::nodes, NULL, graph::rev_topo_list, graph::root, and graph::topo_list.
GraphArc Graph_create_graph_arc (Graph graph)
Definition at line 150 of file i_graph.c.
References graph, and Graph_create_graph_arc_given_id().
Referenced by Graph_connect_nodes(), and Graph_connect_nodes_with_weight().
GraphArc Graph_create_graph_arc_given_id (Graph graph, int new_id)
Definition at line 126 of file i_graph.c.
References graph_arc::flags, graph, Graph_arc_from_id_or_null(), GraphArcPool, GRAPHMODIFIED, HashTable_insert(), I_punt(), graph_arc::id, graph_arc::info, L_alloc(), L_create_alloc_pool(), List_insert_last(), NULL, graph_arc::pred, graph_arc::ptr, and graph_arc::succ.
Referenced by Graph_create_graph_arc().
GraphNode Graph_create_graph_node (Graph graph)
Definition at line 104 of file i_graph.c.
References graph, and Graph_create_graph_node_given_id().
GraphNode Graph_create_graph_node_given_id (Graph graph, int new_id)
Definition at line 72 of file i_graph.c.
References graph_node::contr_dep, graph_node::dom, graph_node::equiv_cd, graph_node::flags, graph, Graph_node_from_id_or_null(), GRAPHMODIFIED, GraphNodePool, HashTable_insert(), I_punt(), graph_node::id, graph_node::imm_dom, graph_node::imm_post_dom, graph_node::info, L_alloc(), L_create_alloc_pool(), List_insert_last(), _FGraph::nodes, NULL, graph_node::post_dom, graph_node::pred, graph_node::ptr, graph_node::succ, and graph_node::tflags.
Referenced by Graph_create_graph_node().
void Graph_daVinci (Graph graph, char * filename, void(*)(FILE *, GraphNode) print_ptr_func)
Definition at line 420 of file i_graph.c.
References graph, Graph_daVinci_visit(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, I_close_output_file(), I_open_output_file(), List_next(), List_start(), node, and NULL.
void Graph_daVinci2 (Graph graph, void(*)(char *) output_str_fn, void(*)(GraphNode, char *, int) print_node_fn, void(*)(GraphArc, char *, int) print_arc_fn, int)
Definition at line 660 of file i_graph.c.
References graph, Graph_daVinci_visit2(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, GraphRootNode, List_next(), List_start(), and node.
void Graph_daVinci2_multi_root (Graph graph, void(*)(char *) output_str_fn, void(*)(GraphNode, char *, int) print_node_fn, void(*)(GraphArc, char *, int) print_arc_fn, int)
Definition at line 693 of file i_graph.c.
References graph, Graph_daVinci_visit2(), Graph_dominator(), GRAPH_NODE_VISIT_WHITE, GRAPHDOM, GraphRootNode, List_first(), List_next(), List_start(), node, NULL, and graph_arc::succ.
int Graph_delete_unreachable (Graph graph, void(*)(void *) node_ptr_del, void(*)(void *) arc_ptr_del)
Definition at line 326 of file i_graph.c.
References graph, Graph_free_graph_arc(), Graph_free_graph_node(), Graph_topological_sort(), GraphArcContents, GraphNodeContents, GRAPHTOPOSORT, List_delete_current(), List_next(), List_remove(), List_reset(), List_start(), node, _FGraph::nodes, graph_node::pred, and graph_arc::succ.
int Graph_dfs_topo_sort (Graph graph)
Definition at line 1087 of file i_graph.c.
References graph, Graph_dfs_topo_visit(), GRAPHTOPOSORT, List_next(), List_reset(), List_size(), List_start(), node, _FGraph::nodes, and _FGraph::root.
Referenced by Graph_bfs_topo_sort(), and Graph_topological_sort().
void Graph_dominator (Graph graph)
Definition at line 761 of file i_graph.c.
References graph_node::dom, I_Node::dom, graph, GRAPHDOM, I_Node::id, List_next(), List_size(), List_start(), node, _FGraph::nodes, NULL, graph_arc::pred, Set_add(), Set_dispose(), Set_intersect_acc(), Set_same(), and Set_union().
Referenced by Graph_count_paths(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_imm_dominator(), Graph_preorder_dfs_sort(), and Graph_rev_topological_sort().
void Graph_equiv_cd (Graph graph)
Definition at line 981 of file i_graph.c.
References graph_equiv_cd::arcs, Bool, graph_equiv_cd::contr_dep, FALSE, graph, Graph_arc_from_id(), Graph_control_dependence(), Graph_create_graph_equiv_cd(), GRAPHCONTROL, GRAPHEQUIVCD, List_insert_last(), List_next(), List_start(), node, graph_equiv_cd::nodes, NULL, Set_2array(), Set_same(), Set_size(), Set_union(), and TRUE.
GraphEquivCD Graph_equiv_cd_from_id (Graph graph, int id)
Definition at line 286 of file i_graph.c.
References graph, and HashTable_find().
Graph Graph_free_graph (Graph graph)
Definition at line 226 of file i_graph.c.
References graph, Graph_free_graph_arc(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), GraphArcPool, GraphEquivCDPool, GraphNodePool, GraphPool, HashTable_free(), L_free(), L_print_alloc_info(), List_next(), List_reset(), List_start(), node, _FGraph::nodes, and NULL.
void Graph_imm_dominator (Graph graph)
Definition at line 734 of file i_graph.c.
References I_Node::dom, graph_node::flags, graph, Graph_dominator(), GRAPHDOM, GRAPHIMMDOM, graph_node::id, List_next(), List_start(), node, NULL, and Set_in().
void Graph_imm_post_dominator (Graph graph)
Definition at line 841 of file i_graph.c.
References graph_node::flags, graph, Graph_post_dominator(), GRAPHIMMPOSTDOM, GRAPHPOSTDOM, graph_node::id, List_next(), List_prev(), List_start(), node, NULL, I_Node::post_dom, and Set_in().
Referenced by Graph_control_dependence().
GraphNode Graph_node_from_id (Graph graph, int id)
Definition at line 270 of file i_graph.c.
References graph, and HashTable_find().
GraphNode Graph_node_from_id_or_null (Graph graph, int id)
Definition at line 274 of file i_graph.c.
References graph, and HashTable_find_or_null().
Referenced by Graph_create_graph_node_given_id().
int Graph_num_paths (Graph graph, GraphNode node)
void Graph_post_dominator (Graph graph)
Definition at line 865 of file i_graph.c.
References graph, GRAPHPOSTDOM, I_Node::id, List_next(), List_size(), List_start(), node, _FGraph::nodes, NULL, graph_node::post_dom, I_Node::post_dom, Set_add(), Set_dispose(), Set_intersect_acc(), Set_same(), Set_union(), and graph_arc::succ.
Referenced by Graph_imm_post_dominator().
void Graph_preorder_dfs_sort (Graph graph, int directed)
Definition at line 1311 of file i_graph.c.
References graph, Graph_dominator(), GRAPH_NODE_VISIT_WHITE, Graph_preorder_dfs_visit(), GRAPHDFSPRESORT, GRAPHDOM, List_next(), List_reset(), List_start(), and node.
void Graph_rev_topological_sort (Graph graph)
Definition at line 1244 of file i_graph.c.
References graph, Graph_dominator(), Graph_rev_topological_visit(), GRAPHDOM, GRAPHREVTOPOSORT, I_punt(), List_next(), List_reset(), List_start(), node, and NULL.
int Graph_size (Graph graph)
Definition at line 290 of file i_graph.c.
References graph, I_punt(), List_size(), and _FGraph::nodes.
int Graph_topological_sort (Graph graph)
Definition at line 1221 of file i_graph.c.
References graph, and Graph_dfs_topo_sort().
Referenced by Graph_control_dependence(), and Graph_delete_unreachable().
Variable Documentation
L_Alloc_Pool* GraphArcPool
Definition at line 69 of file i_graph.c.
Referenced by Graph_create_graph_arc_given_id(), Graph_free_graph(), and Graph_free_graph_arc().
L_Alloc_Pool* GraphEquivCDPool
Definition at line 70 of file i_graph.c.
Referenced by Graph_free_graph(), Graph_free_graph_equiv_cd(), and Graph_new_graph_equiv_cd().
L_Alloc_Pool* GraphNodePool
Definition at line 68 of file i_graph.c.
Referenced by Graph_create_graph_node_given_id(), Graph_free_graph(), and Graph_free_graph_node().
L_Alloc_Pool* GraphPool
Definition at line 67 of file i_graph.c.
Referenced by Graph_create_graph(), and Graph_free_graph().