i_hash.h File Reference
#include <config.h>
#include <library/l_alloc_new.h>
Data Structures
struct _hash_element
struct _hash_table
Defines
#define HASH_FUNC(value) ((value))
Typedefs
typedef _hash_element * HashElement
typedef _hash_element _HashElement
typedef _hash_table * HashTable
typedef _hash_table _HashTable
Functions
HashTable HashTable_create (int size)
void HashTable_free (HashTable hash_table)
void HashTable_free_func (HashTable hash_table, void(*ptr_free_func)(void *))
void HashTable_reset (HashTable hash_table)
void HashTable_reset_func (HashTable hash_table, void(*ptr_free_func)(void *))
void * HashTable_find (HashTable hash_table, int key)
void * HashTable_find_or_null (HashTable hash_table, int key)
void HashTable_insert (HashTable hash_table, int key, void *ptr)
int HashTable_member (HashTable hash_table, int key)
void HashTable_update (HashTable hash_table, int key, void *ptr)
void HashTable_start (HashTable hash_table)
void * HashTable_next (HashTable hash_table)
int HashTable_key (HashTable hash_table)
void HashTable_remove (HashTable hash_table, int key)
Variables
L_Alloc_Pool * HashTablePool
L_Alloc_Pool * HashElementPool
Define Documentation
#define HASH_FUNC(value) ((value))
Definition at line 69 of file i_hash.h.
Referenced by HashLTable_find(), HashLTable_find_or_null(), HashLTable_insert(), HashLTable_member(), HashLTable_remove(), HashLTable_update(), HashTable_find(), HashTable_find_or_null(), HashTable_insert(), HashTable_member(), HashTable_remove(), and HashTable_update().
Typedef Documentation
typedef struct _hash_element _HashElement
typedef struct _hash_table _HashTable
typedef struct _hash_element * HashElement
typedef struct _hash_table * HashTable
Function Documentation
HashTable HashTable_create (int size)
Definition at line 73 of file i_hash.c.
References HashElementPool, HashTablePool, L_alloc(), L_create_alloc_pool(), _hash_table::mask, NULL, and _hash_table::tbl.
Referenced by Graph_create_graph().
void* HashTable_find (HashTable hash_table, int key)
Definition at line 174 of file i_hash.c.
References HASH_FUNC, I_punt(), _hash_element::key, _hash_table::mask, _hash_element::next, NULL, _hash_element::ptr, and _hash_table::tbl.
Referenced by Graph_arc_from_id(), Graph_equiv_cd_from_id(), and Graph_node_from_id().
void* HashTable_find_or_null (HashTable hash_table, int key)
Definition at line 191 of file i_hash.c.
References HASH_FUNC, _hash_element::key, _hash_table::mask, _hash_element::next, NULL, _hash_element::ptr, and _hash_table::tbl.
Referenced by Graph_arc_from_id_or_null(), and Graph_node_from_id_or_null().
void HashTable_free (HashTable hash_table)
Definition at line 109 of file i_hash.c.
References HashTable_reset(), HashTablePool, L_free(), and _hash_table::tbl.
Referenced by Graph_free_graph().
void HashTable_free_func (HashTable hash_table, void(*)(void *) ptr_free_func)
Definition at line 120 of file i_hash.c.
References HashTable_reset_func(), HashTablePool, L_free(), and _hash_table::tbl.
void HashTable_insert (HashTable hash_table, int key, void * ptr)
Definition at line 223 of file i_hash.c.
References HASH_FUNC, HashElementPool, _hash_element::key, L_alloc(), _hash_table::mask, _hash_element::next, _hash_element::ptr, and _hash_table::tbl.
Referenced by Graph_create_graph_arc_given_id(), Graph_create_graph_equiv_cd(), and Graph_create_graph_node_given_id().
int HashTable_key (HashTable hash_table)
Definition at line 331 of file i_hash.c.
References _hash_table::elem_indx, and _hash_element::key.
int HashTable_member (HashTable hash_table, int key)
Definition at line 207 of file i_hash.c.
References FALSE, HASH_FUNC, _hash_element::key, _hash_table::mask, _hash_element::next, NULL, _hash_table::tbl, and TRUE.
void* HashTable_next (HashTable hash_table)
Definition at line 304 of file i_hash.c.
References _hash_table::elem_indx, _hash_table::key_indx, _hash_element::next, NULL, _hash_element::ptr, and _hash_table::tbl.
void HashTable_remove (HashTable hash_table, int key)
Definition at line 240 of file i_hash.c.
References HASH_FUNC, HashElementPool, I_punt(), _hash_element::key, L_free(), _hash_table::mask, _hash_element::next, NULL, and _hash_table::tbl.
void HashTable_reset (HashTable hash_table)
Definition at line 131 of file i_hash.c.
References HashElementPool, L_free(), _hash_table::mask, _hash_element::next, NULL, and _hash_table::tbl.
Referenced by HashTable_free().
void HashTable_reset_func (HashTable hash_table, void(*)(void *) ptr_free_func)
Definition at line 152 of file i_hash.c.
References HashElementPool, L_free(), _hash_table::mask, _hash_element::next, NULL, and _hash_table::tbl.
Referenced by HashTable_free_func().
void HashTable_start (HashTable hash_table)
Definition at line 296 of file i_hash.c.
References _hash_table::elem_indx, _hash_table::key_indx, and NULL.
void HashTable_update (HashTable hash_table, int key, void * ptr)
Definition at line 270 of file i_hash.c.
References HASH_FUNC, HashElementPool, _hash_element::key, L_alloc(), _hash_table::mask, _hash_element::next, NULL, _hash_element::ptr, and _hash_table::tbl.
Variable Documentation
L_Alloc_Pool* HashElementPool
Definition at line 70 of file i_hash.c.
Referenced by HashTable_create(), HashTable_insert(), HashTable_remove(), HashTable_reset(), HashTable_reset_func(), and HashTable_update().
L_Alloc_Pool* HashTablePool
Definition at line 71 of file i_hash.c.
Referenced by HashTable_create(), HashTable_free(), and HashTable_free_func().