i_hashl.h File Reference
#include <config.h>
#include <library/i_types.h>
#include <library/l_alloc_new.h>
Data Structures
struct _hashl_element
struct _hashl_table
Defines
#define HASH_FUNC(value) ((value))
Typedefs
typedef _hashl_element * HashLElement
typedef _hashl_element _HashLElement
typedef _hashl_table * HashLTable
typedef _hashl_table _HashLTable
Functions
HashLTable HashLTable_create (int size)
void HashLTable_free (HashLTable hash_table)
void HashLTable_free_func (HashLTable hash_table, void(*ptr_free_func)(void *))
void HashLTable_reset (HashLTable hash_table)
void HashLTable_reset_func (HashLTable hash_table, void(*ptr_free_func)(void *))
void * HashLTable_find (HashLTable hash_table, ITintmax key)
void * HashLTable_find_or_null (HashLTable hash_table, ITintmax key)
void HashLTable_insert (HashLTable hash_table, ITintmax key, void *ptr)
int HashLTable_member (HashLTable hash_table, ITintmax key)
void HashLTable_update (HashLTable hash_table, ITintmax key, void *ptr)
void HashLTable_start (HashLTable hash_table)
void * HashLTable_next (HashLTable hash_table)
void HashLTable_remove (HashLTable hash_table, ITintmax key)
ITintmax HashLTable_curr_key (HashLTable hash_table)
Variables
L_Alloc_Pool * HashLTablePool
L_Alloc_Pool * HashLElementPool
Define Documentation
#define HASH_FUNC(value) ((value))
Definition at line 70 of file i_hashl.h.
Typedef Documentation
typedef struct _hashl_element _HashLElement
typedef struct _hashl_table _HashLTable
typedef struct _hashl_element
 * HashLElement
typedef struct _hashl_table
 * HashLTable
Function Documentation
HashLTable HashLTable_create (int size)
Definition at line 74 of file i_hashl.c.
References HashLElementPool, HashLTablePool, L_alloc(), L_create_alloc_pool(), _hashl_table::mask, NULL, and _hashl_table::tbl.
ITintmax HashLTable_curr_key (HashLTable hash_table)
Definition at line 332 of file i_hashl.c.
References _hashl_table::elem_indx, and _hashl_element::key.
void* HashLTable_find (HashLTable hash_table, ITintmax key)
Definition at line 175 of file i_hashl.c.
References HASH_FUNC, I_punt(), _hashl_element::key, _hashl_table::mask, _hashl_element::next, NULL, _hashl_element::ptr, and _hashl_table::tbl.
void* HashLTable_find_or_null (HashLTable hash_table, ITintmax key)
Definition at line 192 of file i_hashl.c.
References HASH_FUNC, _hashl_element::key, _hashl_table::mask, _hashl_element::next, NULL, _hashl_element::ptr, and _hashl_table::tbl.
void HashLTable_free (HashLTable hash_table)
Definition at line 110 of file i_hashl.c.
References HashLTable_reset(), HashLTablePool, L_free(), and _hashl_table::tbl.
void HashLTable_free_func (HashLTable hash_table, void(*)(void *) ptr_free_func)
Definition at line 121 of file i_hashl.c.
References HashLTable_reset_func(), HashLTablePool, L_free(), and _hashl_table::tbl.
void HashLTable_insert (HashLTable hash_table, ITintmax key, void * ptr)
Definition at line 224 of file i_hashl.c.
References HASH_FUNC, HashLElementPool, _hashl_element::key, L_alloc(), _hashl_table::mask, _hashl_element::next, _hashl_element::ptr, and _hashl_table::tbl.
int HashLTable_member (HashLTable hash_table, ITintmax key)
Definition at line 208 of file i_hashl.c.
References FALSE, HASH_FUNC, _hashl_element::key, _hashl_table::mask, _hashl_element::next, NULL, _hashl_table::tbl, and TRUE.
void* HashLTable_next (HashLTable hash_table)
Definition at line 305 of file i_hashl.c.
References _hashl_table::elem_indx, _hashl_table::key_indx, _hashl_element::next, NULL, _hashl_element::ptr, and _hashl_table::tbl.
void HashLTable_remove (HashLTable hash_table, ITintmax key)
Definition at line 241 of file i_hashl.c.
References HASH_FUNC, HashLElementPool, I_punt(), _hashl_element::key, L_free(), _hashl_table::mask, _hashl_element::next, NULL, and _hashl_table::tbl.
void HashLTable_reset (HashLTable hash_table)
Definition at line 132 of file i_hashl.c.
References HashLElementPool, L_free(), _hashl_table::mask, _hashl_element::next, NULL, and _hashl_table::tbl.
Referenced by HashLTable_free().
void HashLTable_reset_func (HashLTable hash_table, void(*)(void *) ptr_free_func)
Definition at line 153 of file i_hashl.c.
References HashLElementPool, L_free(), _hashl_table::mask, _hashl_element::next, NULL, and _hashl_table::tbl.
Referenced by HashLTable_free_func().
void HashLTable_start (HashLTable hash_table)
Definition at line 297 of file i_hashl.c.
References _hashl_table::elem_indx, _hashl_table::key_indx, and NULL.
void HashLTable_update (HashLTable hash_table, ITintmax key, void * ptr)
Definition at line 271 of file i_hashl.c.
References HASH_FUNC, HashLElementPool, _hashl_element::key, L_alloc(), _hashl_table::mask, _hashl_element::next, NULL, _hashl_element::ptr, and _hashl_table::tbl.
Variable Documentation
L_Alloc_Pool* HashLElementPool
Definition at line 71 of file i_hashl.c.
Referenced by HashLTable_create(), HashLTable_insert(), HashLTable_remove(), HashLTable_reset(), HashLTable_reset_func(), and HashLTable_update().
L_Alloc_Pool* HashLTablePool
Definition at line 72 of file i_hashl.c.
Referenced by HashLTable_create(), HashLTable_free(), and HashLTable_free_func().