i_io.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include `i_io.h`
#include <library/i_error.h>
Functions
FILE * I_open_output_file (char *name)
void I_close_output_file (FILE *F)
Function Documentation
void I_close_output_file (FILE * F)
Definition at line 105 of file i_io.c.
References I_punt(), and NULL.
Referenced by Graph_daVinci().
FILE* I_open_output_file (char * name)
Definition at line 73 of file i_io.c.
References F, I_punt(), and NULL.
Referenced by Graph_daVinci().