i_list.h File Reference
#include <config.h>
#include <library/l_alloc_new.h>
Data Structures
struct list_element
struct list
Typedefs
typedef list_element * ListElement
typedef list_element _ListElement
typedef list * List
typedef list _List
Functions
int List_size (List list)
void * List_get_first (List list)
void * List_get_last (List list)
void * List_get_next (List list)
void * List_next (List list)
void * List_prev (List list)
void * List_current (List list)
void * List_first (List list)
void * List_last (List list)
void List_start (List list)
List List_delete_current (List list)
List List_reset (List list)
List List_reset_free_ptrs (List list, void(*free_fn)(void *))
List List_insert_first (List list, void *ptr)
List List_insert_last (List list, void *ptr)
List List_insert_prev (List list, void *ptr)
List List_append (List list, List append_list)
List List_insert_next (List list, void *ptr)
void * List_get_next_l (List list, int level)
void * List_next_l (List list, int level)
void * List_prev_l (List list, int level)
void * List_current_l (List list, int level)
void * List_first_l (List list, int level)
void * List_last_l (List list, int level)
void List_start_l (List list, int level)
List List_delete_current_l (List list, int level)
List List_insert_prev_l (List list, void *ptr, int level)
List List_insert_next_l (List list, void *ptr, int level)
void List_copy_current_ptr (List list, int to_level, int from_level)
int List_max_registered_current (List list)
int List_register_new_ptr (List list)
void List_free_all_ptrs (List list)
List List_remove (List list, void *ptr)
List List_copy (List list)
void List_change_current (List list, void *new_ptr)
void List_change_current_l (List list, void *new_ptr, int level)
int List_member (List list, void *ptr)
Variables
L_Alloc_Pool * ListPool
L_Alloc_Pool * ListElementPool
Typedef Documentation
typedef struct list _List
typedef struct list_element _ListElement
typedef struct list
 * List
typedef struct list_element
 * ListElement
Function Documentation
List List_append (List list, List append_list)
Definition at line 540 of file i_list.c.
References list::first, list::last, List_reset(), list_element::next, list_element::prev, and list::size.
void List_change_current (List list, void * new_ptr)
Definition at line 266 of file i_list.c.
References List_change_current_l().
void List_change_current_l (List list, void * new_ptr, int level)
Definition at line 247 of file i_list.c.
References list::current, I_punt(), list::num_currents, and list_element::ptr.
Referenced by List_change_current().
List List_copy (List list)
Definition at line 794 of file i_list.c.
References List_first(), List_insert_last(), List_next(), and NULL.
void List_copy_current_ptr (List list, int to_level, int from_level)
Definition at line 678 of file i_list.c.
References list::current, I_punt(), and list::num_currents.
void* List_current (List list)
Definition at line 291 of file i_list.c.
References List_current_l().
void* List_current_l (List list, int level)
Definition at line 272 of file i_list.c.
References list::current, I_punt(), NULL, list::num_currents, and list_element::ptr.
Referenced by List_current().
List List_delete_current (List list)
Definition at line 625 of file i_list.c.
References List_delete_current_l().
Referenced by Graph_bfs_topo_sort(), and Graph_delete_unreachable().
List List_delete_current_l (List list, int level)
Definition at line 564 of file i_list.c.
References list::current, I_punt(), list_element::next, NULL, list::num_currents, and list_element::prev.
Referenced by List_delete_current().
void* List_first (List list)
Definition at line 313 of file i_list.c.
References List_first_l().
Referenced by Graph_daVinci2_multi_root(), and List_copy().
void* List_first_l (List list, int level)
Definition at line 297 of file i_list.c.
References list::current, list::first, I_punt(), NULL, list::num_currents, and list_element::ptr.
Referenced by List_first().
void List_free_all_ptrs (List list)
Definition at line 719 of file i_list.c.
References list::current, I_punt(), NULL, and list::num_currents.
void* List_get_first (List list)
Definition at line 125 of file i_list.c.
References list::first, NULL, and list_element::ptr.
void* List_get_last (List list)
Definition at line 134 of file i_list.c.
References list::last, NULL, and list_element::ptr.
void* List_get_next (List list)
Definition at line 165 of file i_list.c.
References List_get_next_l().
Referenced by Graph_daVinci_visit(), and Graph_daVinci_visit2().
void* List_get_next_l (List list, int level)
Definition at line 143 of file i_list.c.
References list::current, list::first, I_punt(), list_element::next, NULL, list::num_currents, and list_element::ptr.
Referenced by List_get_next().
List List_insert_first (List list, void * ptr)
Definition at line 364 of file i_list.c.
References list::first, list::last, List_new_list(), List_new_list_element(), list_element::next, list_element::prev, list_element::ptr, and list::size.
Referenced by Graph_dfs_topo_visit(), and Graph_rev_topological_visit().
List List_insert_last (List list, void * ptr)
Definition at line 390 of file i_list.c.
References list::first, list::last, List_new_list(), List_new_list_element(), list_element::next, list_element::prev, list_element::ptr, and list::size.
Referenced by Graph_bfs_accept_node(), Graph_bfs_topo_sort(), Graph_connect_nodes(), Graph_connect_nodes_with_weight(), Graph_create_graph_arc_given_id(), Graph_create_graph_equiv_cd(), Graph_create_graph_node_given_id(), Graph_equiv_cd(), Graph_preorder_dfs_visit(), I_BDD_minterms_aux(), and List_copy().
List List_insert_next (List list, void * ptr)
Definition at line 535 of file i_list.c.
References List_insert_next_l().
List List_insert_next_l (List list, void * ptr, int level)
Definition at line 478 of file i_list.c.
References list::current, list::first, I_punt(), list::last, List_new_list(), List_new_list_element(), list_element::next, list::num_currents, list_element::prev, list_element::ptr, and list::size.
Referenced by List_insert_next().
List List_insert_prev (List list, void * ptr)
Definition at line 473 of file i_list.c.
References List_insert_prev_l().
List List_insert_prev_l (List list, void * ptr, int level)
Definition at line 416 of file i_list.c.
References list::current, list::first, I_punt(), list::last, List_new_list(), List_new_list_element(), list_element::next, list::num_currents, list_element::prev, list_element::ptr, and list::size.
Referenced by List_insert_prev().
void* List_last (List list)
Definition at line 339 of file i_list.c.
References List_last_l().
Referenced by Graph_control_dependence().
void* List_last_l (List list, int level)
Definition at line 320 of file i_list.c.
References list::current, I_punt(), list::last, NULL, list::num_currents, and list_element::ptr.
Referenced by List_last().
int List_max_registered_current (List list)
Definition at line 690 of file i_list.c.
References list::num_currents.
int List_member (List list, void * ptr)
Definition at line 807 of file i_list.c.
References list::first, list_element::next, and list_element::ptr.
void* List_next (List list)
Definition at line 198 of file i_list.c.
References list::current, list::first, list_element::next, NULL, and list_element::ptr.
Referenced by Graph_bfs_accept_node(), Graph_bfs_topo_sort(), Graph_control_dependence(), Graph_count_paths(), Graph_count_paths_visit(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_daVinci_visit(), Graph_daVinci_visit2(), Graph_delete_unreachable(), Graph_dfs_topo_sort(), Graph_dfs_topo_visit(), Graph_dominator(), Graph_equiv_cd(), Graph_free_graph(), Graph_imm_dominator(), Graph_imm_post_dominator(), Graph_post_dominator(), Graph_preorder_dfs_sort(), Graph_preorder_dfs_visit(), Graph_rev_topological_sort(), Graph_rev_topological_visit(), I_BDD_print_minterms(), and List_copy().
void* List_next_l (List list, int level)
Definition at line 171 of file i_list.c.
References list::current, list::first, I_punt(), list_element::next, NULL, list::num_currents, and list_element::ptr.
void* List_prev (List list)
Definition at line 240 of file i_list.c.
References List_prev_l().
Referenced by Graph_imm_post_dominator().
void* List_prev_l (List list, int level)
Definition at line 215 of file i_list.c.
References list::current, I_punt(), list::last, NULL, list::num_currents, list_element::prev, and list_element::ptr.
Referenced by List_prev().
int List_register_new_ptr (List list)
Definition at line 696 of file i_list.c.
References list::current, I_punt(), NULL, and list::num_currents.
List List_remove (List list, void * ptr)
Definition at line 734 of file i_list.c.
References list::current, list::first, I_punt(), list_element::next, NULL, list::num_currents, list_element::prev, and list_element::ptr.
Referenced by Graph_delete_unreachable().
List List_reset (List list)
Definition at line 631 of file i_list.c.
References list::current, list::first, L_free(), ListElementPool, ListPool, list_element::next, and NULL.
Referenced by Graph_bfs_topo_sort(), Graph_delete_unreachable(), Graph_dfs_topo_sort(), Graph_free_graph(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), Graph_preorder_dfs_sort(), Graph_rev_topological_sort(), and List_append().
List List_reset_free_ptrs (List list, void(*)(void *) free_fn)
Definition at line 654 of file i_list.c.
References list::current, list::first, L_free(), ListElementPool, ListPool, list_element::next, NULL, and list_element::ptr.
int List_size (List list)
Definition at line 116 of file i_list.c.
References list::size.
Referenced by Graph_bfs_topo_sort(), Graph_count_paths(), Graph_create_graph_equiv_cd(), Graph_dfs_topo_sort(), Graph_dominator(), Graph_post_dominator(), and Graph_size().
void List_start (List list)
Definition at line 359 of file i_list.c.
References List_start_l().
Referenced by Graph_bfs_accept_node(), Graph_bfs_topo_sort(), Graph_control_dependence(), Graph_count_paths(), Graph_count_paths_visit(), Graph_daVinci(), Graph_daVinci2(), Graph_daVinci2_multi_root(), Graph_daVinci_visit(), Graph_daVinci_visit2(), Graph_delete_unreachable(), Graph_dfs_topo_sort(), Graph_dfs_topo_visit(), Graph_dominator(), Graph_equiv_cd(), Graph_free_graph(), Graph_imm_dominator(), Graph_imm_post_dominator(), Graph_post_dominator(), Graph_preorder_dfs_sort(), Graph_preorder_dfs_visit(), Graph_rev_topological_sort(), Graph_rev_topological_visit(), and I_BDD_print_minterms().
void List_start_l (List list, int level)
Definition at line 345 of file i_list.c.
References list::current, I_punt(), NULL, and list::num_currents.
Referenced by List_start().
Variable Documentation
L_Alloc_Pool* ListElementPool
Definition at line 71 of file i_list.c.
Referenced by List_new_list_element(), List_reset(), and List_reset_free_ptrs().
L_Alloc_Pool* ListPool
Definition at line 70 of file i_list.c.
Referenced by List_new_list(), List_reset(), and List_reset_free_ptrs().