int_array_symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `int_array_symbol.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Functions
INT_ARRAY_Symbol_Table * INT_ARRAY_new_symbol_table (char *name, int expected_size)
void INT_ARRAY_delete_symbol_table (INT_ARRAY_Symbol_Table *table, void(*free_routine)(void *))
void INT_ARRAY_resize_symbol_table (INT_ARRAY_Symbol_Table *table)
static unsigned int INT_ARRAY_hash_int_array (int *int_array, int array_length)
INT_ARRAY_Symbol * INT_ARRAY_add_symbol (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length, void *data)
INT_ARRAY_Symbol * INT_ARRAY_find_symbol (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length)
void * INT_ARRAY_find_symbol_data (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length)
void INT_ARRAY_delete_symbol (INT_ARRAY_Symbol *symbol, void(*free_routine)(void *))
void INT_ARRAY_print_symbol_table_hash (FILE *out, INT_ARRAY_Symbol_Table *table)
Variables
L_Alloc_Pool * INT_ARRAY_Symbol_Table_pool = NULL
L_Alloc_Pool * INT_ARRAY_Symbol_pool = NULL
Function Documentation
INT_ARRAY_Symbol* INT_ARRAY_add_symbol (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length, void * data)
Definition at line 279 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, INT_ARRAY_Symbol_Table::head_symbol, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_resize_symbol_table(), INT_ARRAY_Symbol_pool, L_alloc(), INT_ARRAY_Symbol_Table::name, INT_ARRAY_Symbol::next_hash, INT_ARRAY_Symbol::next_symbol, NULL, INT_ARRAY_Symbol::prev_symbol, INT_ARRAY_Symbol_Table::resize_size, INT_ARRAY_Symbol_Table::symbol_count, INT_ARRAY_Symbol::table, and INT_ARRAY_Symbol_Table::tail_symbol.
void INT_ARRAY_delete_symbol (INT_ARRAY_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 509 of file int_array_symbol.c.
References INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, INT_ARRAY_Symbol_Table::head_symbol, INT_ARRAY_Symbol::int_array, INT_ARRAY_Symbol_pool, L_free(), INT_ARRAY_Symbol::next_hash, INT_ARRAY_Symbol::next_symbol, NULL, INT_ARRAY_Symbol::prev_hash, INT_ARRAY_Symbol::prev_symbol, INT_ARRAY_Symbol_Table::symbol_count, INT_ARRAY_Symbol::table, and INT_ARRAY_Symbol_Table::tail_symbol.
void INT_ARRAY_delete_symbol_table (INT_ARRAY_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 156 of file int_array_symbol.c.
References INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::head_symbol, INT_ARRAY_Symbol::int_array, INT_ARRAY_Symbol_pool, INT_ARRAY_Symbol_Table_pool, L_free(), INT_ARRAY_Symbol_Table::name, INT_ARRAY_Symbol::next_symbol, and NULL.
INT_ARRAY_Symbol* INT_ARRAY_find_symbol (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length)
Definition at line 402 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_Symbol::next_hash, and NULL.
void* INT_ARRAY_find_symbol_data (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length)
Definition at line 457 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_Symbol::next_hash, and NULL.
static unsigned int INT_ARRAY_hash_int_array (int * int_array, int array_length) [static]
Definition at line 244 of file int_array_symbol.c.
Referenced by INT_ARRAY_add_symbol(), INT_ARRAY_find_symbol(), and INT_ARRAY_find_symbol_data().
INT_ARRAY_Symbol_Table* INT_ARRAY_new_symbol_table (char * name, int expected_size)
Definition at line 81 of file int_array_symbol.c.
References INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol_Table::hash_size, INT_ARRAY_Symbol_Table::head_symbol, I_punt(), INT_ARRAY_Symbol_pool, INT_ARRAY_Symbol_Table_pool, L_alloc(), L_create_alloc_pool(), INT_ARRAY_Symbol_Table::name, NULL, INT_ARRAY_Symbol_Table::resize_size, INT_ARRAY_Symbol_Table::symbol_count, and INT_ARRAY_Symbol_Table::tail_symbol.
void INT_ARRAY_print_symbol_table_hash (FILE * out, INT_ARRAY_Symbol_Table * table)
Definition at line 563 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_size, INT_ARRAY_Symbol::int_array, INT_ARRAY_Symbol_Table::name, INT_ARRAY_Symbol::next_hash, NULL, and INT_ARRAY_Symbol_Table::symbol_count.
void INT_ARRAY_resize_symbol_table (INT_ARRAY_Symbol_Table * table)
Definition at line 186 of file int_array_symbol.c.
References INT_ARRAY_Symbol_Table::hash_size, INT_ARRAY_Symbol::hash_val, INT_ARRAY_Symbol_Table::head_symbol, I_punt(), INT_ARRAY_Symbol::next_hash, INT_ARRAY_Symbol::next_symbol, NULL, and INT_ARRAY_Symbol::prev_hash.
Referenced by INT_ARRAY_add_symbol().
Variable Documentation
L_Alloc_Pool* INT_ARRAY_Symbol_pool = NULL
Definition at line 68 of file int_array_symbol.c.
Referenced by INT_ARRAY_add_symbol(), INT_ARRAY_delete_symbol(), INT_ARRAY_delete_symbol_table(), and INT_ARRAY_new_symbol_table().
L_Alloc_Pool* INT_ARRAY_Symbol_Table_pool = NULL
Definition at line 67 of file int_array_symbol.c.
Referenced by INT_ARRAY_delete_symbol_table(), and INT_ARRAY_new_symbol_table().