int_array_symbol.h File Reference
#include <config.h>
Data Structures
struct INT_ARRAY_Symbol
struct INT_ARRAY_Symbol_Table
Functions
INT_ARRAY_Symbol_Table * INT_ARRAY_new_symbol_table (char *name, int expected_size)
void INT_ARRAY_delete_symbol_table (INT_ARRAY_Symbol_Table *table, void(*free_routine)(void *))
INT_ARRAY_Symbol * INT_ARRAY_add_symbol (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length, void *data)
INT_ARRAY_Symbol * INT_ARRAY_find_symbol (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length)
void * INT_ARRAY_find_symbol_data (INT_ARRAY_Symbol_Table *table, int *int_array, int array_length)
void INT_ARRAY_delete_symbol (INT_ARRAY_Symbol *symbol, void(*free_routine)(void *))
Function Documentation
INT_ARRAY_Symbol* INT_ARRAY_add_symbol (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length, void * data)
Definition at line 279 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, INT_ARRAY_Symbol_Table::head_symbol, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_resize_symbol_table(), INT_ARRAY_Symbol_pool, L_alloc(), INT_ARRAY_Symbol_Table::name, INT_ARRAY_Symbol::next_hash, INT_ARRAY_Symbol::next_symbol, NULL, INT_ARRAY_Symbol::prev_symbol, INT_ARRAY_Symbol_Table::resize_size, INT_ARRAY_Symbol_Table::symbol_count, INT_ARRAY_Symbol::table, and INT_ARRAY_Symbol_Table::tail_symbol.
void INT_ARRAY_delete_symbol (INT_ARRAY_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 509 of file int_array_symbol.c.
References INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, INT_ARRAY_Symbol_Table::head_symbol, INT_ARRAY_Symbol::int_array, INT_ARRAY_Symbol_pool, L_free(), INT_ARRAY_Symbol::next_hash, INT_ARRAY_Symbol::next_symbol, NULL, INT_ARRAY_Symbol::prev_hash, INT_ARRAY_Symbol::prev_symbol, INT_ARRAY_Symbol_Table::symbol_count, INT_ARRAY_Symbol::table, and INT_ARRAY_Symbol_Table::tail_symbol.
void INT_ARRAY_delete_symbol_table (INT_ARRAY_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 156 of file int_array_symbol.c.
References INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::head_symbol, INT_ARRAY_Symbol::int_array, INT_ARRAY_Symbol_pool, INT_ARRAY_Symbol_Table_pool, L_free(), INT_ARRAY_Symbol_Table::name, INT_ARRAY_Symbol::next_symbol, and NULL.
INT_ARRAY_Symbol* INT_ARRAY_find_symbol (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length)
Definition at line 402 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_Symbol::next_hash, and NULL.
void* INT_ARRAY_find_symbol_data (INT_ARRAY_Symbol_Table * table, int * int_array, int array_length)
Definition at line 457 of file int_array_symbol.c.
References INT_ARRAY_Symbol::array_length, INT_ARRAY_Symbol::data, INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol::hash_val, I_punt(), INT_ARRAY_Symbol::int_array, INT_ARRAY_hash_int_array(), INT_ARRAY_Symbol::next_hash, and NULL.
INT_ARRAY_Symbol_Table* INT_ARRAY_new_symbol_table (char * name, int expected_size)
Definition at line 81 of file int_array_symbol.c.
References INT_ARRAY_Symbol_Table::hash, INT_ARRAY_Symbol_Table::hash_mask, INT_ARRAY_Symbol_Table::hash_size, INT_ARRAY_Symbol_Table::head_symbol, I_punt(), INT_ARRAY_Symbol_pool, INT_ARRAY_Symbol_Table_pool, L_alloc(), L_create_alloc_pool(), INT_ARRAY_Symbol_Table::name, NULL, INT_ARRAY_Symbol_Table::resize_size, INT_ARRAY_Symbol_Table::symbol_count, and INT_ARRAY_Symbol_Table::tail_symbol.