int_symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `int_symbol.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Functions
INT_Symbol_Table * INT_new_symbol_table (char *name, int expected_size)
void INT_delete_symbol_table (INT_Symbol_Table *table, void(*free_routine)(void *))
void INT_resize_symbol_table (INT_Symbol_Table *table)
INT_Symbol * INT_add_symbol (INT_Symbol_Table *table, int value, void *data)
INT_Symbol * INT_find_symbol (INT_Symbol_Table *table, int value)
void * INT_find_symbol_data (INT_Symbol_Table *table, int value)
void INT_delete_symbol (INT_Symbol *symbol, void(*free_routine)(void *))
void INT_print_symbol_table_hash (FILE *out, INT_Symbol_Table *table)
Variables
L_Alloc_Pool * INT_Symbol_Table_pool = NULL
L_Alloc_Pool * INT_Symbol_pool = NULL
Function Documentation
INT_Symbol* INT_add_symbol (INT_Symbol_Table * table, int value, void * data)
Definition at line 243 of file int_symbol.c.
References INT_Symbol::data, INT_Symbol_Table::hash, INT_Symbol_Table::hash_mask, INT_Symbol_Table::head_symbol, I_punt(), INT_resize_symbol_table(), INT_Symbol_pool, L_alloc(), INT_Symbol_Table::name, INT_Symbol::next_hash, INT_Symbol::next_symbol, NULL, INT_Symbol::prev_symbol, INT_Symbol_Table::resize_size, INT_Symbol_Table::symbol_count, INT_Symbol::table, INT_Symbol_Table::tail_symbol, and INT_Symbol::value.
void INT_delete_symbol (INT_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 370 of file int_symbol.c.
References INT_Symbol::data, INT_Symbol_Table::hash, INT_Symbol_Table::hash_mask, INT_Symbol_Table::head_symbol, INT_Symbol_pool, L_free(), INT_Symbol::next_hash, INT_Symbol::next_symbol, NULL, INT_Symbol::prev_hash, INT_Symbol::prev_symbol, INT_Symbol_Table::symbol_count, INT_Symbol::table, INT_Symbol_Table::tail_symbol, and INT_Symbol::value.
void INT_delete_symbol_table (INT_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 154 of file int_symbol.c.
References INT_Symbol::data, INT_Symbol_Table::hash, INT_Symbol_Table::head_symbol, INT_Symbol_pool, INT_Symbol_Table_pool, L_free(), INT_Symbol_Table::name, INT_Symbol::next_symbol, and NULL.
INT_Symbol* INT_find_symbol (INT_Symbol_Table * table, int value)
Definition at line 321 of file int_symbol.c.
References INT_Symbol_Table::hash, INT_Symbol_Table::hash_mask, INT_Symbol::next_hash, NULL, and INT_Symbol::value.
void* INT_find_symbol_data (INT_Symbol_Table * table, int value)
Definition at line 347 of file int_symbol.c.
References INT_Symbol::data, INT_Symbol_Table::hash, INT_Symbol_Table::hash_mask, INT_Symbol::next_hash, NULL, and INT_Symbol::value.
INT_Symbol_Table* INT_new_symbol_table (char * name, int expected_size)
Definition at line 82 of file int_symbol.c.
References INT_Symbol_Table::hash, INT_Symbol_Table::hash_mask, INT_Symbol_Table::hash_size, INT_Symbol_Table::head_symbol, I_punt(), INT_Symbol_pool, INT_Symbol_Table_pool, L_alloc(), L_create_alloc_pool(), INT_Symbol_Table::name, NULL, INT_Symbol_Table::resize_size, INT_Symbol_Table::symbol_count, and INT_Symbol_Table::tail_symbol.
void INT_print_symbol_table_hash (FILE * out, INT_Symbol_Table * table)
Definition at line 421 of file int_symbol.c.
References INT_Symbol_Table::hash, INT_Symbol_Table::hash_size, INT_Symbol_Table::name, INT_Symbol::next_hash, NULL, INT_Symbol_Table::symbol_count, and INT_Symbol::value.
void INT_resize_symbol_table (INT_Symbol_Table * table)
Definition at line 183 of file int_symbol.c.
References INT_Symbol_Table::hash_size, INT_Symbol_Table::head_symbol, I_punt(), INT_Symbol::next_hash, INT_Symbol::next_symbol, NULL, INT_Symbol::prev_hash, and INT_Symbol::value.
Referenced by INT_add_symbol().
Variable Documentation
L_Alloc_Pool* INT_Symbol_pool = NULL
Definition at line 68 of file int_symbol.c.
Referenced by INT_add_symbol(), INT_delete_symbol(), INT_delete_symbol_table(), and INT_new_symbol_table().
L_Alloc_Pool* INT_Symbol_Table_pool = NULL
Definition at line 67 of file int_symbol.c.
Referenced by INT_delete_symbol_table(), and INT_new_symbol_table().