io.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include <library/io.h>
Functions
static void Punt (char *mesg)
static void DecodeRoot (LIST Largs, FGraph graph)
static void DecodeNode (LIST Largs, FGraph graph)
static void DecodeArc (LIST Largs, FGraph graph)
FGraph ReadGraph (char *file_name)
void WriteGraph (char *file_name, FGraph graph)
Variables
void *(*) graph_ext_handler (LIST)=0
void *(*) node_ext_handler (LIST)=0
void *(*) arc_ext_handler (LIST)=0
int(*) graph_ext_output (_GraphExtension, FILE *)=0
int(*) node_ext_output (_NodeExtension, FILE *)=0
int(*) arc_ext_output (_ArcExtension, FILE *)=0
Function Documentation
static void DecodeArc (LIST Largs, FGraph graph) [static]
Definition at line 197 of file io.c.
References AddNode(), arc_ext_handler, arcExt, arcWeight, ChildOf, ConnectNodes(), FindDestArc(), FindNode(), FindSrcArc(), graph, IntegerOf, NewNode(), node, nodeId, NodeType, NULL, RealOf, SiblingOf, StringOf, T_ID, T_INT, T_LIST, and T_REAL.
Referenced by ReadGraph().
static void DecodeNode (LIST Largs, FGraph graph) [static]
Definition at line 131 of file io.c.
References AddNode(), ChildOf, FindNode(), graph, IntegerOf, NewNode(), node, node_ext_handler, nodeExt, nodeId, nodeStatus, nodeType, NodeType, nodeWeight, Punt(), RealOf, SiblingOf, StringOf, T_ID, T_INT, T_LIST, and T_REAL.
Referenced by ReadGraph().
static void DecodeRoot (LIST Largs, FGraph graph) [static]
Definition at line 92 of file io.c.
References AddNode(), ChildOf, _FGraph::extension, FindNode(), graph, graph_ext_handler, IntegerOf, NewNode(), nodeId, NodeType, Punt(), _FGraph::root, SiblingOf, StringOf, T_ID, T_INT, and T_LIST.
Referenced by ReadGraph().
static void Punt (char * mesg) [static]
Definition at line 85 of file io.c.
FGraph ReadGraph (char * file_name)
Definition at line 281 of file io.c.
References ChildOf, DecodeArc(), DecodeNode(), DecodeRoot(), DisposeNode(), F, GetNode(), graph, NewGraph(), node, NodeType, Punt(), SiblingOf, StringOf, SwitchFile(), T_EOF, T_ID, and T_LIST.
void WriteGraph (char * file_name, FGraph graph)
Definition at line 336 of file io.c.
References arc_ext_output, arcExt, arcType, arcWeight, destinationArcs, destinationNode, _FGraph::extension, F, graph, graph_ext_output, nextArc, nextNode, node_ext_output, nodeExt, nodeId, _FGraph::nodes, nodeStatus, nodeType, nodeWeight, Punt(), _FGraph::root, and sourceNode.
Referenced by PlaceTraces(), ReportSelectionResult(), and TraceSelection().
Variable Documentation
void*(*) arc_ext_handler(LIST)=0
Definition at line 78 of file io.c.
Referenced by DecodeArc().
int(*) arc_ext_output(_ArcExtension, FILE *)=0
Definition at line 82 of file io.c.
Referenced by WriteGraph().
void*(*) graph_ext_handler(LIST)=0
Definition at line 76 of file io.c.
Referenced by DecodeRoot().
int(*) graph_ext_output(_GraphExtension, FILE *)=0
Definition at line 80 of file io.c.
Referenced by WriteGraph().
void*(*) node_ext_handler(LIST)=0
Definition at line 77 of file io.c.
Referenced by DecodeNode().
int(*) node_ext_output(_NodeExtension, FILE *)=0
Definition at line 81 of file io.c.
Referenced by WriteGraph().