io.h File Reference
#include <config.h>
#include <stdio.h>
#include <library/list.h>
#include <library/graph.h>
Functions
FGraph ReadGraph (char *file_name)
void WriteGraph (char *file_name, FGraph graph)
Variables
void *(*) graph_ext_handler (LIST)
void *(*) node_ext_handler (LIST)
void *(*) arc_ext_handler (LIST)
int(*) graph_ext_output (_GraphExtension, FILE *)
int(*) node_ext_output (_NodeExtension, FILE *)
int(*) arc_ext_output (_ArcExtension, FILE *)
Function Documentation
FGraph ReadGraph (char * file_name)
Definition at line 281 of file io.c.
References ChildOf, DecodeArc(), DecodeNode(), DecodeRoot(), DisposeNode(), F, GetNode(), graph, NewGraph(), node, NodeType, Punt(), SiblingOf, StringOf, SwitchFile(), T_EOF, T_ID, and T_LIST.
void WriteGraph (char * file_name, FGraph graph)
Definition at line 336 of file io.c.
References arc_ext_output, arcExt, arcType, arcWeight, destinationArcs, destinationNode, _FGraph::extension, F, graph, graph_ext_output, nextArc, nextNode, node_ext_output, nodeExt, nodeId, _FGraph::nodes, nodeStatus, nodeType, nodeWeight, Punt(), _FGraph::root, and sourceNode.
Referenced by PlaceTraces(), ReportSelectionResult(), and TraceSelection().
Variable Documentation
void*(*) arc_ext_handler(LIST)
Definition at line 78 of file io.c.
Referenced by DecodeArc().
int(*) arc_ext_output(_ArcExtension, FILE *)
Definition at line 82 of file io.c.
Referenced by WriteGraph().
void*(*) graph_ext_handler(LIST)
Definition at line 76 of file io.c.
Referenced by DecodeRoot().
int(*) graph_ext_output(_GraphExtension, FILE *)
Definition at line 80 of file io.c.
Referenced by WriteGraph().
void*(*) node_ext_handler(LIST)
Definition at line 77 of file io.c.
Referenced by DecodeNode().
int(*) node_ext_output(_NodeExtension, FILE *)
Definition at line 81 of file io.c.
Referenced by WriteGraph().