l_alloc_new.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include `l_alloc_new.h`
#include <library/i_list.h>
Functions
L_Alloc_Pool * L_create_alloc_pool (char *name, int size, int num_in_block)
void L_free_alloc_pool (L_Alloc_Pool *pool)
void * L_alloc (L_Alloc_Pool *pool)
void L_free (L_Alloc_Pool *pool, void *ptr)
long L_print_alloc_info (FILE *F, L_Alloc_Pool *pool, int verbose)
void L_summarize_allocation_info (FILE *fp)
Variables
int bypass_alloc_routines = 0
static L_Alloc_Pool * active_alloc_pools = NULL
Function Documentation
void* L_alloc (L_Alloc_Pool * pool)
Definition at line 229 of file l_alloc_new.c.
References _L_Alloc_Pool::allocated, _L_Alloc_Pool::block_list, _L_Alloc_Pool::block_size, _L_Alloc_Pool::blocks_allocated, _L_Alloc_Pool::bypass_routines, _L_Alloc_Pool::element_size, _L_Alloc_Pool::free, _L_Alloc_Pool::head, _L_Alloc_Pool::name, _L_Alloc_Pool_Header::next, NULL, and _L_Alloc_Pool::num_in_block.
Referenced by _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), CHAR_ARRAY_add_symbol(), CHAR_ARRAY_new_symbol_table(), copy_Mptr(), create_Mbuf(), create_Mfile(), create_Mptr(), Graph_create_graph(), Graph_create_graph_arc_given_id(), Graph_create_graph_node_given_id(), Graph_new_graph_equiv_cd(), HashLTable_create(), HashLTable_insert(), HashLTable_update(), HashTable_create(), HashTable_insert(), HashTable_update(), Heap_Insert(), INT_add_symbol(), INT_ARRAY_add_symbol(), INT_ARRAY_new_symbol_table(), INT_new_symbol_table(), L_create_AttrMngr(), L_create_histogram(), L_insert_cb_attr_list(), L_insert_fn_attr_list(), L_insert_op_attr_list(), List_new_list(), List_new_list_element(), MD_add_symbol(), MD_new_buf(), MD_new_element_req(), MD_new_entry(), MD_new_field(), MD_new_field_decl(), MD_new_md(), MD_new_section(), MD_new_symbol_table(), New_Stack(), New_Stack_Elmt(), NewLint(), NewLptr(), NewSet(), NewVArray(), NewVector(), Push_Bot(), Push_Top(), Set_iterator(), STRING_add_symbol(), and STRING_new_symbol_table().
L_Alloc_Pool* L_create_alloc_pool (char * name, int size, int num_in_block)
Definition at line 79 of file l_alloc_new.c.
References active_alloc_pools, _L_Alloc_Pool::allocated, _L_Alloc_Pool::block_list, _L_Alloc_Pool::block_size, _L_Alloc_Pool::blocks_allocated, bypass_alloc_routines, _L_Alloc_Pool::bypass_routines, _L_Alloc_Pool::element_size, _L_Alloc_Pool::free, _L_Alloc_Pool::head, _L_Alloc_Pool::name, _L_Alloc_Pool::next, NULL, and _L_Alloc_Pool::num_in_block.
Referenced by CHAR_ARRAY_new_symbol_table(), create_Mbuf(), create_Mfile(), create_Mptr(), Graph_create_graph(), Graph_create_graph_arc_given_id(), Graph_create_graph_node_given_id(), Graph_new_graph_equiv_cd(), HashLTable_create(), HashTable_create(), Heap_Create(), Init_NewLint(), Init_NewLptr(), INT_ARRAY_new_symbol_table(), INT_new_symbol_table(), L_create_AttrMngr(), L_create_histogram(), List_new_list(), List_new_list_element(), MD_new_md(), MD_read_md(), New_Stack(), NewSet(), NewVArray(), NewVector(), Set_iterator(), and STRING_new_symbol_table().
void L_free (L_Alloc_Pool * pool, void * ptr)
Definition at line 305 of file l_alloc_new.c.
References _L_Alloc_Pool::allocated, _L_Alloc_Pool::bypass_routines, _L_Alloc_Pool::free, _L_Alloc_Pool::head, _L_Alloc_Pool::name, _L_Alloc_Pool_Header::next, and NULL.
Referenced by _MD_free_entry(), _MD_free_field_decl(), _MD_free_section(), CHAR_ARRAY_delete_symbol(), CHAR_ARRAY_delete_symbol_table(), Clear_Stack(), Delete_Stack(), free_Mbuf(), free_Mfile(), free_Mptr(), Free_Stack(), Free_Stack_Elmt(), FreeSet(), FreeVArray(), FreeVector(), Graph_free_graph(), Graph_free_graph_arc(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), HashLTable_free(), HashLTable_free_func(), HashLTable_remove(), HashLTable_reset(), HashLTable_reset_func(), HashTable_free(), HashTable_free_func(), HashTable_remove(), HashTable_reset(), HashTable_reset_func(), Heap_Dispose(), Heap_ExtractTop(), INT_ARRAY_delete_symbol(), INT_ARRAY_delete_symbol_table(), INT_delete_symbol(), INT_delete_symbol_table(), L_delete_histogram(), L_free_Attr(), L_free_AttrMngr(), List_reset(), List_reset_free_ptrs(), MD_delete_buf(), MD_delete_element(), MD_delete_field(), MD_delete_md(), MD_delete_symbol(), MD_delete_symbol_table(), Pop(), Set_end_iterator(), STRING_delete_symbol(), and STRING_delete_symbol_table().
void L_free_alloc_pool (L_Alloc_Pool * pool)
Definition at line 166 of file l_alloc_new.c.
References active_alloc_pools, _L_Alloc_Pool::allocated, _L_Alloc_Pool::block_list, _L_Alloc_Pool::free, _L_Alloc_Pool::name, _L_Alloc_Pool_Header::next, _L_Alloc_Pool::next, and NULL.
Referenced by MD_delete_md(), and MD_read_md().
long L_print_alloc_info (FILE * F, L_Alloc_Pool * pool, int verbose)
Definition at line 352 of file l_alloc_new.c.
References _L_Alloc_Pool::allocated, _L_Alloc_Pool::block_size, _L_Alloc_Pool::blocks_allocated, _L_Alloc_Pool::bypass_routines, _L_Alloc_Pool::free, and _L_Alloc_Pool::name.
Referenced by Graph_free_graph(), and L_summarize_allocation_info().
void L_summarize_allocation_info (FILE * fp)
Definition at line 381 of file l_alloc_new.c.
References active_alloc_pools, L_print_alloc_info(), and _L_Alloc_Pool::next.
Variable Documentation
L_Alloc_Pool* active_alloc_pools = NULL [static]
Definition at line 76 of file l_alloc_new.c.
Referenced by L_create_alloc_pool(), L_free_alloc_pool(), and L_summarize_allocation_info().
int bypass_alloc_routines = 0
Definition at line 74 of file l_alloc_new.c.
Referenced by L_create_alloc_pool().