l_histogram.c File Reference
#include <config.h>
#include <string.h>
#include <library/l_histogram.h>
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Defines
#define NUM_HIST_PRINT 10
Functions
L_Histogram * L_create_histogram (char *name, int init_size)
void L_delete_histogram (L_Histogram *hist)
void L_realloc_histogram_data (L_Histogram *hist, int entry)
void L_update_histogram (L_Histogram *hist, int entry, double val)
void L_clear_histogram (L_Histogram *hist)
void L_scale_histogram_entries (L_Histogram *hist, double scale)
void L_copy_histogram (L_Histogram *dest, L_Histogram *src)
void L_add_histograms (L_Histogram *dest, L_Histogram *src1, L_Histogram *src2)
static void L_print_histogram_all_entries (FILE *F, L_Histogram *hist)
static void L_print_histogram_grouped_values (FILE *F, L_Histogram *hist)
static void L_print_histogram_grouped_percentages (FILE *F, L_Histogram *hist)
static void L_print_histogram_individual_percentages (FILE *F, L_Histogram *hist, double sum)
static void L_print_histogram_average_value (FILE *F, L_Histogram *hist)
void L_print_histogram (FILE *F, L_Histogram *hist, int mode, double sum)
Variables
L_Alloc_Pool * L_histogram_pool = NULL
static int hist_print [NUM_HIST_PRINT]
Define Documentation
#define NUM_HIST_PRINT 10
Definition at line 342 of file l_histogram.c.
Referenced by L_print_histogram_grouped_values().
Function Documentation
void L_add_histograms (L_Histogram * dest, L_Histogram * src1, L_Histogram * src2)
Definition at line 237 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_clear_histogram (L_Histogram * hist)
Definition at line 185 of file l_histogram.c.
References L_Histogram::data, I_punt(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_copy_histogram (L_Histogram * dest, L_Histogram * src)
Definition at line 217 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
L_Histogram* L_create_histogram (char * name, int init_size)
Definition at line 66 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_alloc(), L_create_alloc_pool(), L_DEFAULT_HISTOGRAM_SIZE, L_histogram_pool, L_MAX_HISTOGRAM_SIZE, L_Histogram::name, NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_delete_histogram (L_Histogram * hist)
Definition at line 106 of file l_histogram.c.
References L_Histogram::data, _L_Alloc_Pool::free, L_free(), L_histogram_pool, L_Histogram::name, and NULL.
void L_print_histogram (FILE * F, L_Histogram * hist, int mode, double sum)
Definition at line 605 of file l_histogram.c.
References I_punt(), L_PRINT_ALL_ENTRIES, L_PRINT_AVERAGE_VALUE, L_PRINT_GROUPED_PERCENTAGES, L_PRINT_GROUPED_VALUES, L_print_histogram_all_entries(), L_print_histogram_average_value(), L_print_histogram_grouped_percentages(), L_print_histogram_grouped_values(), L_print_histogram_individual_percentages(), L_PRINT_INDIVIDUAL_PERCENTAGES, and NULL.
static void L_print_histogram_all_entries (FILE * F, L_Histogram * hist) [static]
Definition at line 284 of file l_histogram.c.
References L_Histogram::data, L_Histogram::name, L_Histogram::over_max_data, and L_Histogram::size.
Referenced by L_print_histogram().
static void L_print_histogram_average_value (FILE * F, L_Histogram * hist) [static]
Definition at line 554 of file l_histogram.c.
References L_Histogram::data, L_MAX_HISTOGRAM_SIZE, L_Histogram::name, L_Histogram::over_max_data, and L_Histogram::size.
Referenced by L_print_histogram().
static void L_print_histogram_grouped_percentages (FILE * F, L_Histogram * hist) [static]
Definition at line 429 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_Histogram::name, and L_Histogram::size.
Referenced by L_print_histogram().
static void L_print_histogram_grouped_values (FILE * F, L_Histogram * hist) [static]
Definition at line 357 of file l_histogram.c.
References L_Histogram::data, hist_print, L_Histogram::name, NUM_HIST_PRINT, L_Histogram::over_max_data, and L_Histogram::size.
Referenced by L_print_histogram().
static void L_print_histogram_individual_percentages (FILE * F, L_Histogram * hist, double sum) [static]
Definition at line 499 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_Histogram::name, and L_Histogram::size.
Referenced by L_print_histogram().
void L_realloc_histogram_data (L_Histogram * hist, int entry)
Definition at line 127 of file l_histogram.c.
References L_Histogram::data, _L_Alloc_Pool::free, I_punt(), L_MAX_HISTOGRAM_SIZE, and L_Histogram::size.
Referenced by L_add_histograms(), L_copy_histogram(), and L_update_histogram().
void L_scale_histogram_entries (L_Histogram * hist, double scale)
Definition at line 201 of file l_histogram.c.
References L_Histogram::data, I_punt(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_update_histogram (L_Histogram * hist, int entry, double val)
Definition at line 164 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_MAX_HISTOGRAM_SIZE, L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
Variable Documentation
int hist_print[NUM_HIST_PRINT] [static]
Initial value:
 {
  0,
  1,
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  256
}
Definition at line 343 of file l_histogram.c.
Referenced by L_print_histogram_grouped_values().
L_Alloc_Pool* L_histogram_pool = NULL
Definition at line 63 of file l_histogram.c.
Referenced by L_create_histogram(), and L_delete_histogram().