l_histogram.h File Reference
#include <config.h>
#include <stdio.h>
#include <malloc.h>
Data Structures
struct L_Histogram
Defines
#define L_DEFAULT_HISTOGRAM_SIZE 1024
#define L_MAX_HISTOGRAM_SIZE L_DEFAULT_HISTOGRAM_SIZE*256
#define L_PRINT_ALL_ENTRIES 1
#define L_PRINT_GROUPED_VALUES 2
#define L_PRINT_GROUPED_PERCENTAGES 3
#define L_PRINT_INDIVIDUAL_PERCENTAGES 4
#define L_PRINT_AVERAGE_VALUE 5
Functions
L_Histogram * L_create_histogram (char *, int)
void L_delete_histogram (L_Histogram *)
void L_realloc_histogram_data (L_Histogram *, int)
void L_update_histogram (L_Histogram *, int, double)
void L_clear_histogram (L_Histogram *)
void L_scale_histogram_entries (L_Histogram *, double)
void L_copy_histogram (L_Histogram *, L_Histogram *)
void L_add_histograms (L_Histogram *, L_Histogram *, L_Histogram *)
void L_print_histogram (FILE *, L_Histogram *, int, double)
Define Documentation
#define L_DEFAULT_HISTOGRAM_SIZE 1024
Definition at line 64 of file l_histogram.h.
Referenced by L_create_histogram().
#define L_MAX_HISTOGRAM_SIZE L_DEFAULT_HISTOGRAM_SIZE*256
Definition at line 65 of file l_histogram.h.
Referenced by L_create_histogram(), L_print_histogram_average_value(), L_realloc_histogram_data(), and L_update_histogram().
#define L_PRINT_ALL_ENTRIES 1
Definition at line 78 of file l_histogram.h.
Referenced by L_print_histogram().
#define L_PRINT_AVERAGE_VALUE 5
Definition at line 82 of file l_histogram.h.
Referenced by L_print_histogram().
#define L_PRINT_GROUPED_PERCENTAGES 3
Definition at line 80 of file l_histogram.h.
Referenced by L_print_histogram().
#define L_PRINT_GROUPED_VALUES 2
Definition at line 79 of file l_histogram.h.
Referenced by L_print_histogram().
#define L_PRINT_INDIVIDUAL_PERCENTAGES 4
Definition at line 81 of file l_histogram.h.
Referenced by L_print_histogram().
Function Documentation
void L_add_histograms (L_Histogram *, L_Histogram *, L_Histogram *)
Definition at line 237 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_clear_histogram (L_Histogram *)
Definition at line 185 of file l_histogram.c.
References L_Histogram::data, I_punt(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_copy_histogram (L_Histogram *, L_Histogram *)
Definition at line 217 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
L_Histogram* L_create_histogram (char *, int)
Definition at line 66 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_alloc(), L_create_alloc_pool(), L_DEFAULT_HISTOGRAM_SIZE, L_histogram_pool, L_MAX_HISTOGRAM_SIZE, L_Histogram::name, NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_delete_histogram (L_Histogram *)
Definition at line 106 of file l_histogram.c.
References L_Histogram::data, _L_Alloc_Pool::free, L_free(), L_histogram_pool, L_Histogram::name, and NULL.
void L_print_histogram (FILE *, L_Histogram *, int, double)
Definition at line 605 of file l_histogram.c.
References I_punt(), L_PRINT_ALL_ENTRIES, L_PRINT_AVERAGE_VALUE, L_PRINT_GROUPED_PERCENTAGES, L_PRINT_GROUPED_VALUES, L_print_histogram_all_entries(), L_print_histogram_average_value(), L_print_histogram_grouped_percentages(), L_print_histogram_grouped_values(), L_print_histogram_individual_percentages(), L_PRINT_INDIVIDUAL_PERCENTAGES, and NULL.
void L_realloc_histogram_data (L_Histogram *, int)
Definition at line 127 of file l_histogram.c.
References L_Histogram::data, _L_Alloc_Pool::free, I_punt(), L_MAX_HISTOGRAM_SIZE, and L_Histogram::size.
Referenced by L_add_histograms(), L_copy_histogram(), and L_update_histogram().
void L_scale_histogram_entries (L_Histogram *, double)
Definition at line 201 of file l_histogram.c.
References L_Histogram::data, I_punt(), NULL, L_Histogram::over_max_data, and L_Histogram::size.
void L_update_histogram (L_Histogram *, int, double)
Definition at line 164 of file l_histogram.c.
References L_Histogram::data, I_punt(), L_MAX_HISTOGRAM_SIZE, L_realloc_histogram_data(), NULL, L_Histogram::over_max_data, and L_Histogram::size.