l_parms.h File Reference
#include <config.h>
#include <stdio.h>
Data Structures
struct parm_table_node
struct parm_table_list
struct parm_warn_node
struct parm_warn_list
struct parm_macro_node
struct parm_macro_list
struct parm_parse_info_st
struct parm_section_info
Defines
#define PARM_LINE_MAX 2048
#define PARM_BUF_MAX 1024
#define PARM_LEVEL_MAX 20
#define PARM_FORCE_PARM 1
#define PARM_COMMAND_LINE 2
#define PARM_ENVIRONMENT 3
#define PARM_INTERNAL 4
#define PARM_TABLE_HASH_SIZE 128
#define NOT_USED 0
#define USED 1
#define PARM_NOT_USED 0
#define NO_PARM_DEF 1
#define MULT_PARM_DEF 2
#define WARNINGS_ON 1
#define WARNINGS_OFF 0
#define READ_PARM_S(ppi, parm) L_read_parm_s(ppi,`parm`,&parm)
#define READ_PARM_I(ppi, parm) L_read_parm_i(ppi,`parm`,&parm)
#define READ_PARM_B(ppi, parm) L_read_parm_b(ppi,`parm`,&parm)
#define PRINT_PARM_S(out, parm) fprintf (out, ` %s = %s;\n`,`parm`,parm)
#define PRINT_PARM_I(out, parm) fprintf (out, ` %s = %i;\n`,`parm`,parm)
#define PRINT_PARM_B(out, parm) fprintf (out, ` %s = %i;\n`,`parm`,parm)
#define PRINT_PARM_B_YES_NO(out, parm)
#define PRINT_PARM_B_ON_OFF(out, parm)
#define PRINT_PARM_F(out, parm) fprintf (out, ` %s = %f;\n`,`parm`,parm)
#define PRINT_PARM_LF(out, parm) fprintf (out, ` %s = %lf;\n`,`parm`,parm)
Typedefs
typedef parm_table_node Parm_Table_Node
typedef parm_table_list Parm_Table_List
typedef parm_warn_node Parm_Warn_Node
typedef parm_warn_list Parm_Warn_List
typedef parm_macro_node Parm_Macro_Node
typedef parm_macro_list Parm_Macro_List
typedef parm_parse_info_st Parm_Parse_Info
typedef parm_section_info Parm_Section_Info
Functions
char * L_get_std_parm_name (char **argv, char **envp, char *env_var_name, char *default_std_parms)
Parm_Macro_List * L_create_external_macro_list (char **argv, char **envp)
Parm_Macro_List * L_create_external_macro_list_new (char **argv, char **envp, int *lastarg)
void L_free_parm_macro_list (Parm_Macro_List *list)
void L_load_parameters (char *parm_file_name, Parm_Macro_List *command_line_macro_list, char *section, void(*read_func)(Parm_Parse_Info *ppi))
void L_load_parameters_aliased (char *parm_file_name, Parm_Macro_List *command_line_macro_list, char *new_section_name, char *old_section_name, void(*read_func)(Parm_Parse_Info *ppi))
void L_read_parm_s (Parm_Parse_Info *ppi_in, char *name, char **ptr)
void L_read_parm_b (Parm_Parse_Info *ppi_in, char *name, int *ptr)
void L_read_parm_i (Parm_Parse_Info *ppi_in, char *name, int *ptr)
void L_read_parm_f (Parm_Parse_Info *ppi_in, char *name, float *ptr)
void L_read_parm_lf (Parm_Parse_Info *ppi_in, char *name, double *ptr)
void L_warn_about_unused_macros (FILE *out, Parm_Macro_List *external_list)
void L_show_parms_warnings (void)
int L_pmatch (char *s1, char *s2)
Variables
int L_punt_on_unknown_parm
int L_warn_old_parm_section_name_used
char * L_parm_dump_file_name
int L_warn_parm_not_used
int L_warn_parm_not_defined
int L_warn_dev_parm_not_defined
int L_warn_parm_defined_twice
int L_dump_parms
char * L_parm_warn_file_name
Define Documentation
#define MULT_PARM_DEF 2
Definition at line 98 of file l_parms.h.
Referenced by L_add_parm_already_defined(), and L_show_parms_warnings().
#define NO_PARM_DEF 1
Definition at line 97 of file l_parms.h.
Referenced by L_add_parm_not_defined(), and L_show_parms_warnings().
#define NOT_USED 0
Definition at line 93 of file l_parms.h.
Referenced by L_add_parm_not_used().
#define PARM_BUF_MAX 1024
Definition at line 84 of file l_parms.h.
Referenced by L_get_next_parm().
#define PARM_COMMAND_LINE 2
Definition at line 88 of file l_parms.h.
Referenced by L_create_external_macro_list_new(), and L_warn_about_unused_macros().
#define PARM_ENVIRONMENT 3
Definition at line 89 of file l_parms.h.
Referenced by L_create_external_macro_list_new().
#define PARM_FORCE_PARM 1
Definition at line 87 of file l_parms.h.
Referenced by L_add_forced_parms(), L_create_external_macro_list_new(), L_warn_about_unused_macros(), and look_for_forced_param().
#define PARM_INTERNAL 4
Definition at line 90 of file l_parms.h.
Referenced by L_get_next_parm().
#define PARM_LEVEL_MAX 20
Definition at line 85 of file l_parms.h.
Referenced by L_read_parm_section_defaults().
#define PARM_LINE_MAX 2048
Definition at line 83 of file l_parms.h.
Referenced by L_get_next_parm(), and L_read_parm_section_defaults().
#define PARM_NOT_USED 0
Definition at line 96 of file l_parms.h.
Referenced by L_add_parm_not_used(), and L_show_parms_warnings().
#define PARM_TABLE_HASH_SIZE 128
Definition at line 92 of file l_parms.h.
Referenced by L_add_parm_not_used(), L_add_to_parm_table_list(), L_create_parm_table_list(), L_free_parm_table_list(), and L_get_parm_table_entry().
#define PRINT_PARM_B(out, parm) fprintf (out, ` %s = %i;\n`,`parm`,parm)
Definition at line 357 of file l_parms.h.
#define PRINT_PARM_B_ON_OFF(out, parm)
Value:
(parm ? fprintf (out, "    %s = on;\n", "parm") : \
     fprintf (out, "    %s = off;\n", "parm"))
Definition at line 361 of file l_parms.h.
#define PRINT_PARM_B_YES_NO(out, parm)
Value:
(parm ? fprintf (out, "    %s = yes;\n", "parm") : \
     fprintf (out, "    %s = no;\n", "parm"))
Definition at line 358 of file l_parms.h.
#define PRINT_PARM_F(out, parm) fprintf (out, ` %s = %f;\n`,`parm`,parm)
Definition at line 364 of file l_parms.h.
#define PRINT_PARM_I(out, parm) fprintf (out, ` %s = %i;\n`,`parm`,parm)
Definition at line 356 of file l_parms.h.
#define PRINT_PARM_LF(out, parm) fprintf (out, ` %s = %lf;\n`,`parm`,parm)
Definition at line 365 of file l_parms.h.
#define PRINT_PARM_S(out, parm) fprintf (out, ` %s = %s;\n`,`parm`,parm)
Definition at line 355 of file l_parms.h.
#define READ_PARM_B(ppi, parm) L_read_parm_b(ppi,`parm`,&parm)
Definition at line 353 of file l_parms.h.
#define READ_PARM_I(ppi, parm) L_read_parm_i(ppi,`parm`,&parm)
Definition at line 352 of file l_parms.h.
#define READ_PARM_S(ppi, parm) L_read_parm_s(ppi,`parm`,&parm)
Definition at line 351 of file l_parms.h.
#define USED 1
Definition at line 94 of file l_parms.h.
Referenced by L_get_parm_table_entry(), and L_show_parms_warnings().
#define WARNINGS_OFF 0
Definition at line 101 of file l_parms.h.
#define WARNINGS_ON 1
Definition at line 100 of file l_parms.h.
Typedef Documentation
typedef struct parm_macro_list
 Parm_Macro_List
typedef struct parm_macro_node
 Parm_Macro_Node
typedef struct parm_parse_info_st
 Parm_Parse_Info
typedef struct parm_section_info
 Parm_Section_Info
typedef struct parm_table_list
 Parm_Table_List
typedef struct parm_table_node
 Parm_Table_Node
typedef struct parm_warn_list
 Parm_Warn_List
typedef struct parm_warn_node
 Parm_Warn_Node
Function Documentation
Parm_Macro_List* L_create_external_macro_list (char ** argv, char ** envp)
Definition at line 494 of file l_parms.c.
References L_create_external_macro_list_new().
Parm_Macro_List* L_create_external_macro_list_new (char ** argv, char ** envp, int * lastarg)
Definition at line 501 of file l_parms.c.
References I_punt(), L_create_parm_macro_list(), L_define_parm_macro(), NULL, PARM_COMMAND_LINE, PARM_ENVIRONMENT, and PARM_FORCE_PARM.
Referenced by L_create_external_macro_list().
void L_free_parm_macro_list (Parm_Macro_List * list)
Definition at line 916 of file l_parms.c.
References parm_macro_list::head, node, and NULL.
Referenced by _L_load_parameters(), and L_read_parm_section_defaults().
char* L_get_std_parm_name (char ** argv, char ** envp, char * env_var_name, char * default_std_parms)
Definition at line 423 of file l_parms.c.
References NULL.
void L_load_parameters (char * parm_file_name, Parm_Macro_List * command_line_macro_list, char * section, void(*)(Parm_Parse_Info *ppi) read_func)
Definition at line 2587 of file l_parms.c.
References _L_load_parameters(), and NULL.
void L_load_parameters_aliased (char * parm_file_name, Parm_Macro_List * command_line_macro_list, char * new_section_name, char * old_section_name, void(*)(Parm_Parse_Info *ppi) read_func)
Definition at line 2599 of file l_parms.c.
References _L_load_parameters().
int L_pmatch (char * s1, char * s2)
void L_read_parm_b (Parm_Parse_Info * ppi_in, char * name, int * ptr)
Definition at line 1600 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_pmatch(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_f (Parm_Parse_Info * ppi_in, char * name, float * ptr)
Definition at line 1705 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_i (Parm_Parse_Info * ppi_in, char * name, int * ptr)
Definition at line 1545 of file l_parms.c.
References parm_parse_info_st::calc_ptr, parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, L_add_parm_not_defined(), L_get_parm_table_entry(), L_parm_calc_complete_expr(), L_warn_dev_parm_not_defined, parm_parse_info_st::line_no, look_for_forced_param(), parm_parse_info_st::name, node, NULL, parm_parse_info_st::parm_list, and parm_parse_info_st::setting.
void L_read_parm_lf (Parm_Parse_Info * ppi_in, char * name, double * ptr)
Definition at line 1759 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_s (Parm_Parse_Info * ppi_in, char * name, char ** ptr)
Definition at line 1660 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, L_add_parm_not_defined(), L_get_parm_table_entry(), L_set_parm_s(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_show_parms_warnings (void)
Definition at line 710 of file l_parms.c.
References current_section_name1, current_section_name2, first_time, parm_warn_list::head, I_punt(), L_dump_parms, L_parm_dump_file_name, L_parm_warn_file_name, L_warn_parm_defined_twice, L_warn_parm_not_defined, L_warn_parm_not_used, MULT_PARM_DEF, parm_table_node::next_input, NO_PARM_DEF, node, NULL, PARM_NOT_USED, start_node_of_input, USED, parm_table_node::used, parm_table_node::user_name, parm_table_node::value, and warn_list.
Referenced by _L_load_parameters().
void L_warn_about_unused_macros (FILE * out, Parm_Macro_List * external_list)
Definition at line 667 of file l_parms.c.
References parm_macro_list::head, I_punt(), node, NULL, PARM_COMMAND_LINE, and PARM_FORCE_PARM.
Variable Documentation
int L_dump_parms
Definition at line 152 of file l_parms.c.
Referenced by L_show_parms_warnings().
char* L_parm_dump_file_name
Definition at line 145 of file l_parms.c.
Referenced by L_show_parms_warnings().
char* L_parm_warn_file_name
Definition at line 146 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_punt_on_unknown_parm
Definition at line 120 of file l_parms.c.
int L_warn_dev_parm_not_defined
Definition at line 150 of file l_parms.c.
Referenced by L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), and L_read_parm_s().
int L_warn_old_parm_section_name_used
Definition at line 147 of file l_parms.c.
Referenced by _L_load_parameters().
int L_warn_parm_defined_twice
Definition at line 151 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_warn_parm_not_defined
Definition at line 149 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_warn_parm_not_used
Definition at line 148 of file l_parms.c.
Referenced by L_show_parms_warnings().