l_parms.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/i_error.h>
#include `l_parms.h`
Defines
#define TNULL 0
#define TPLUS 1
#define TMINUS 2
#define TSTAR 3
#define TSLASH 4
#define TLPARN 5
#define TRPARN 6
#define TNUM 7
Functions
Parm_Table_List * L_create_parm_table_list (void)
void L_free_parm_table_list (Parm_Table_List *list)
Parm_Table_Node * L_get_parm_table_entry (Parm_Table_List *list, char *name)
void L_add_to_parm_table_list (Parm_Table_List *list, Parm_Parse_Info *ppi, char *section_name1, char *section_name2)
int L_pmatch (char *s1, char *s2)
Parm_Macro_List * L_create_parm_macro_list (void)
void I_punt (char *msg,...)
static int L_get_next_parm (Parm_Parse_Info *ppi)
void L_define_parm_macro (Parm_Macro_List *list, char *name, char *value, int from)
void L_read_parm_sections (Parm_Parse_Info *ppi, Parm_Section_Info *psi)
int L_parm_calc_complete_expr (Parm_Parse_Info *ppi)
int L_parm_calc_expr (Parm_Parse_Info *ppi)
int L_parm_calc_factor (Parm_Parse_Info *ppi)
int L_parm_calc_term (Parm_Parse_Info *ppi)
int L_peek_next_token (Parm_Parse_Info *ppi)
int L_get_next_token (Parm_Parse_Info *ppi)
void L_add_parm_already_defined (Parm_Table_Node *old_parm_node, char *new_value, char *new_file_name, int new_parm_line_no, char *section_name1, char *section_name2)
char * L_get_std_parm_name (char **argv, char **envp, char *env_var_name, char *default_std_parms)
Parm_Macro_List * L_create_external_macro_list (char **argv, char **envp)
Parm_Macro_List * L_create_external_macro_list_new (char **argv, char **envp, int *lastarg)
void L_warn_about_unused_macros (FILE *out, Parm_Macro_List *external_list)
void L_show_parms_warnings (void)
void L_free_parm_macro_list (Parm_Macro_List *list)
int look_for_forced_param (char *name, Parm_Macro_List *list)
char * L_add_forced_parms (Parm_Parse_Info *ppi, Parm_Table_List *list)
char * L_get_parm_macro_value (Parm_Parse_Info *ppi, char *name)
void L_expand_parm_macros (Parm_Parse_Info *ppi, char *line, char *buf, int max)
void L_set_parm_s (char **parm, char *new_string)
void L_add_parm_not_used (Parm_Table_List *parm_list, char *section_name1, char *section_name2)
void L_add_parm_not_defined (char *name, char *section_name1, char *section_name2)
void L_read_parm_i (Parm_Parse_Info *ppi_in, char *name, int *ptr)
void L_read_parm_b (Parm_Parse_Info *ppi_in, char *name, int *ptr)
void L_read_parm_s (Parm_Parse_Info *ppi_in, char *name, char **ptr)
void L_read_parm_f (Parm_Parse_Info *ppi_in, char *name, float *ptr)
void L_read_parm_lf (Parm_Parse_Info *ppi_in, char *name, double *ptr)
void L_read_parm_section_defaults (Parm_Parse_Info *ppi, Parm_Section_Info *psi, char *defaults_file_name)
void _L_load_parameters (char *parm_file_name, Parm_Macro_List *command_line_macro_list, char *section_name1, char *section_name2, void(*read_func)(Parm_Parse_Info *ppi))
void L_load_parameters (char *parm_file_name, Parm_Macro_List *command_line_macro_list, char *section, void(*read_func)(Parm_Parse_Info *ppi))
void L_load_parameters_aliased (char *parm_file_name, Parm_Macro_List *command_line_macro_list, char *new_section_name, char *old_section_name, void(*read_func)(Parm_Parse_Info *ppi))
Variables
int L_punt_on_unknown_parm = 0
Parm_Warn_List * warn_list
char * current_section_name1
char * current_section_name2
int section_name1_used = 0
int section_name2_used = 0
Parm_Table_List * parameter_list
Parm_Table_Node * start_node_of_input
static int first_time = 1
char * L_parm_dump_file_name = (char *) `stderr`
char * L_parm_warn_file_name = (char *) `stderr`
int L_warn_old_parm_section_name_used = WARNINGS_OFF
int L_warn_parm_not_used = WARNINGS_ON
int L_warn_parm_not_defined = WARNINGS_ON
int L_warn_dev_parm_not_defined = WARNINGS_OFF
int L_warn_parm_defined_twice = WARNINGS_ON
int L_dump_parms = WARNINGS_OFF
Define Documentation
#define TLPARN 5
Definition at line 1939 of file l_parms.c.
Referenced by L_parm_calc_factor(), and L_peek_next_token().
#define TMINUS 2
Definition at line 1936 of file l_parms.c.
Referenced by L_parm_calc_expr(), L_parm_calc_factor(), and L_peek_next_token().
#define TNULL 0
Definition at line 1934 of file l_parms.c.
Referenced by L_peek_next_token().
#define TNUM 7
Definition at line 1941 of file l_parms.c.
Referenced by L_parm_calc_factor(), and L_peek_next_token().
#define TPLUS 1
Definition at line 1935 of file l_parms.c.
Referenced by L_parm_calc_expr(), and L_peek_next_token().
#define TRPARN 6
Definition at line 1940 of file l_parms.c.
Referenced by L_parm_calc_factor(), and L_peek_next_token().
#define TSLASH 4
Definition at line 1938 of file l_parms.c.
Referenced by L_parm_calc_term(), and L_peek_next_token().
#define TSTAR 3
Definition at line 1937 of file l_parms.c.
Referenced by L_parm_calc_term(), and L_peek_next_token().
Function Documentation
void _L_load_parameters (char * parm_file_name, Parm_Macro_List * command_line_macro_list, char * section_name1, char * section_name2, void(*)(Parm_Parse_Info *ppi) read_func)
Definition at line 2433 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, parm_parse_info_st::file, parm_warn_list::head, I_punt(), parm_parse_info_st::internal_level, parm_parse_info_st::internal_list, L_add_forced_parms(), L_add_parm_not_used(), L_create_parm_macro_list(), L_create_parm_table_list(), L_free_parm_macro_list(), L_free_parm_table_list(), L_read_parm_sections(), L_show_parms_warnings(), L_warn_old_parm_section_name_used, parm_parse_info_st::line_no, parm_parse_info_st::name, parm_section_info::name1, parm_section_info::name2, NULL, parameter_list, parm_parse_info_st::parm_list, parm_section_info::parm_list, parm_section_info::read_func, section_name1_used, section_name2_used, start_node_of_input, and warn_list.
Referenced by L_load_parameters(), and L_load_parameters_aliased().
void I_punt (char * msg, ...)
Definition at line 70 of file i_error.c.
Referenced by _L_load_parameters(), addc_to_Mbuf(), AllocateData(), BlockSparseArrayClear(), BlockSparseArraySet(), CHAR_ARRAY_add_symbol(), CHAR_ARRAY_find_symbol(), CHAR_ARRAY_find_symbol_data(), CHAR_ARRAY_new_symbol_table(), CHAR_ARRAY_resize_symbol_table(), clear_Mbuf(), copy_Mbuf_buf(), delete_Func_Name_List(), GetOrAddBlock(), Graph_bfs_accept_node(), Graph_create_graph_arc_given_id(), Graph_create_graph_node_given_id(), Graph_rev_topological_sort(), Graph_size(), HashLTable_find(), HashLTable_remove(), HashTable_find(), HashTable_remove(), I_BDD_minterms(), I_BDD_minterms_aux(), I_BDD_new_mutex_domain(), I_close_output_file(), I_open_output_file(), INT_add_symbol(), INT_ARRAY_add_symbol(), INT_ARRAY_find_symbol(), INT_ARRAY_find_symbol_data(), INT_ARRAY_new_symbol_table(), INT_ARRAY_resize_symbol_table(), INT_new_symbol_table(), INT_resize_symbol_table(), is_in_Func_Name_List(), L_add_forced_parms(), L_add_histograms(), L_add_parm_already_defined(), L_add_parm_not_defined(), L_add_parm_not_used(), L_add_to_parm_table_list(), L_clear_histogram(), L_copy_histogram(), L_create_external_macro_list_new(), L_create_histogram(), L_create_parm_macro_list(), L_create_parm_table_list(), L_define_parm_macro(), L_expand_parm_macros(), L_get_parm_table_entry(), L_parm_calc_complete_expr(), L_parm_calc_factor(), L_peek_next_token(), L_print_histogram(), L_print_histogram_grouped_percentages(), L_print_histogram_individual_percentages(), L_read_parm_b(), L_read_parm_f(), L_read_parm_lf(), L_read_parm_section_defaults(), L_read_parm_sections(), L_realloc_histogram_data(), L_scale_histogram_entries(), L_set_parm_s(), L_show_parms_warnings(), L_update_histogram(), L_warn_about_unused_macros(), L_write_attr_to_file(), List_change_current_l(), List_copy_current_ptr(), List_current_l(), List_delete_current_l(), List_first_l(), List_free_all_ptrs(), List_get_next_l(), List_insert_next_l(), List_insert_prev_l(), List_last_l(), List_new_list(), List_next_l(), List_prev_l(), List_register_new_ptr(), List_remove(), List_start_l(), look_for_forced_param(), Mbackupc(), new_Func_Name_List(), NewBlockSparseArray(), NewVArray(), Set_reset(), STRING_add_symbol(), STRING_new_symbol_table(), and STRING_resize_symbol_table().
char* L_add_forced_parms (Parm_Parse_Info * ppi, Parm_Table_List * list)
Definition at line 980 of file l_parms.c.
References parm_parse_info_st::command_line_list, parm_macro_list::head, I_punt(), L_get_parm_table_entry(), node, NULL, PARM_FORCE_PARM, and parm_table_node::value.
Referenced by _L_load_parameters().
void L_add_parm_already_defined (Parm_Table_Node * old_parm_node, char * new_value, char * new_file_name, int new_parm_line_no, char * section_name1, char * section_name2)
Definition at line 1335 of file l_parms.c.
References parm_warn_list::head, I_punt(), MULT_PARM_DEF, parm_warn_node::next, node, NULL, parm_table_node::parm_file_name, parm_table_node::parm_line_no, parm_table_node::user_name, parm_table_node::value, and warn_list.
void L_add_parm_not_defined (char * name, char * section_name1, char * section_name2)
Definition at line 1489 of file l_parms.c.
References parm_warn_list::head, I_punt(), parm_warn_node::next, NO_PARM_DEF, node, NULL, and warn_list.
Referenced by L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), and L_read_parm_s().
void L_add_parm_not_used (Parm_Table_List * parm_list, char * section_name1, char * section_name2)
Definition at line 1408 of file l_parms.c.
References parm_table_list::head, parm_warn_list::head, I_punt(), parm_table_node::next, parm_warn_node::next, node, NOT_USED, NULL, parm_table_node::parm_file_name, parm_table_node::parm_line_no, PARM_NOT_USED, PARM_TABLE_HASH_SIZE, parm_table_node::used, parm_table_node::user_name, and warn_list.
Referenced by _L_load_parameters().
void L_add_to_parm_table_list (Parm_Table_List * list, Parm_Parse_Info * ppi, char * section_name1, char * section_name2)
Definition at line 275 of file l_parms.c.
References parm_table_list::head, I_punt(), parm_parse_info_st::name, name, parm_table_node::next, node, NULL, parm_parse_info_st::parm_buf, PARM_TABLE_HASH_SIZE, and parm_parse_info_st::setting.
Referenced by L_read_parm_sections(), and look_for_forced_param().
Parm_Macro_List* L_create_external_macro_list (char ** argv, char ** envp)
Definition at line 494 of file l_parms.c.
References L_create_external_macro_list_new().
Parm_Macro_List* L_create_external_macro_list_new (char ** argv, char ** envp, int * lastarg)
Definition at line 501 of file l_parms.c.
References I_punt(), L_create_parm_macro_list(), L_define_parm_macro(), NULL, PARM_COMMAND_LINE, PARM_ENVIRONMENT, and PARM_FORCE_PARM.
Referenced by L_create_external_macro_list().
Parm_Macro_List * L_create_parm_macro_list (void)
Definition at line 903 of file l_parms.c.
References parm_macro_list::head, I_punt(), and NULL.
Referenced by _L_load_parameters(), L_create_external_macro_list_new(), and L_read_parm_section_defaults().
Parm_Table_List * L_create_parm_table_list (void)
Definition at line 181 of file l_parms.c.
References parm_table_list::head, I_punt(), NULL, and PARM_TABLE_HASH_SIZE.
Referenced by _L_load_parameters().
void L_define_parm_macro (Parm_Macro_List * list, char * name, char * value, int from)
Definition at line 1066 of file l_parms.c.
References parm_macro_list::head, I_punt(), node, and NULL.
Referenced by L_create_external_macro_list_new(), and L_get_next_parm().
void L_expand_parm_macros (Parm_Parse_Info * ppi, char * line, char * buf, int max)
Definition at line 1168 of file l_parms.c.
References I_punt(), L_get_parm_macro_value(), NULL, and parm_parse_info_st::parm_buf.
Referenced by L_get_next_parm().
void L_free_parm_macro_list (Parm_Macro_List * list)
Definition at line 916 of file l_parms.c.
References parm_macro_list::head, node, and NULL.
Referenced by _L_load_parameters(), and L_read_parm_section_defaults().
void L_free_parm_table_list (Parm_Table_List * list)
Definition at line 197 of file l_parms.c.
References parm_table_list::head, node, NULL, and PARM_TABLE_HASH_SIZE.
Referenced by _L_load_parameters().
static int L_get_next_parm (Parm_Parse_Info * ppi) [static]
Definition at line 1816 of file l_parms.c.
References parm_parse_info_st::file, parm_parse_info_st::internal_level, parm_parse_info_st::internal_list, L_define_parm_macro(), L_expand_parm_macros(), parm_parse_info_st::line_buf, parm_parse_info_st::line_no, NULL, parm_parse_info_st::parm_buf, PARM_BUF_MAX, PARM_INTERNAL, PARM_LINE_MAX, and parm_parse_info_st::setting.
Referenced by L_read_parm_sections().
int L_get_next_token (Parm_Parse_Info * ppi)
Definition at line 2060 of file l_parms.c.
References parm_parse_info_st::calc_ptr, and L_peek_next_token().
Referenced by L_parm_calc_expr(), L_parm_calc_factor(), and L_parm_calc_term().
char* L_get_parm_macro_value (Parm_Parse_Info * ppi, char * name)
Definition at line 1020 of file l_parms.c.
References parm_parse_info_st::command_line_list, parm_macro_list::head, parm_parse_info_st::internal_level, parm_parse_info_st::internal_list, node, and NULL.
Referenced by L_expand_parm_macros().
Parm_Table_Node * L_get_parm_table_entry (Parm_Table_List * list, char * name)
Definition at line 222 of file l_parms.c.
References parm_table_list::head, I_punt(), node, NULL, PARM_TABLE_HASH_SIZE, and USED.
Referenced by L_add_forced_parms(), L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), and L_read_parm_s().
char* L_get_std_parm_name (char ** argv, char ** envp, char * env_var_name, char * default_std_parms)
Definition at line 423 of file l_parms.c.
References NULL.
void L_load_parameters (char * parm_file_name, Parm_Macro_List * command_line_macro_list, char * section, void(*)(Parm_Parse_Info *ppi) read_func)
Definition at line 2587 of file l_parms.c.
References _L_load_parameters(), and NULL.
void L_load_parameters_aliased (char * parm_file_name, Parm_Macro_List * command_line_macro_list, char * new_section_name, char * old_section_name, void(*)(Parm_Parse_Info *ppi) read_func)
Definition at line 2599 of file l_parms.c.
References _L_load_parameters().
int L_parm_calc_complete_expr (Parm_Parse_Info * ppi)
Definition at line 1947 of file l_parms.c.
References parm_parse_info_st::calc_ptr, I_punt(), L_parm_calc_expr(), parm_parse_info_st::line_no, and parm_parse_info_st::name.
Referenced by L_read_parm_i().
int L_parm_calc_expr (Parm_Parse_Info * ppi)
Definition at line 1966 of file l_parms.c.
References L_get_next_token(), L_parm_calc_term(), L_peek_next_token(), TMINUS, parm_parse_info_st::token, and TPLUS.
Referenced by L_parm_calc_complete_expr(), and L_parm_calc_factor().
int L_parm_calc_factor (Parm_Parse_Info * ppi)
Definition at line 2018 of file l_parms.c.
References parm_parse_info_st::calc_ptr, I_punt(), L_get_next_token(), L_parm_calc_expr(), parm_parse_info_st::line_no, parm_parse_info_st::name, TLPARN, TMINUS, TNUM, parm_parse_info_st::token, TRPARN, and parm_parse_info_st::value.
Referenced by L_parm_calc_term().
int L_parm_calc_term (Parm_Parse_Info * ppi)
Definition at line 1992 of file l_parms.c.
References L_get_next_token(), L_parm_calc_factor(), L_peek_next_token(), parm_parse_info_st::token, TSLASH, and TSTAR.
Referenced by L_parm_calc_expr().
int L_peek_next_token (Parm_Parse_Info * ppi)
Definition at line 2069 of file l_parms.c.
References parm_parse_info_st::calc_ptr, I_punt(), parm_parse_info_st::line_no, parm_parse_info_st::name, TLPARN, TMINUS, TNULL, TNUM, parm_parse_info_st::token, TPLUS, TRPARN, TSLASH, TSTAR, and parm_parse_info_st::value.
Referenced by L_get_next_token(), L_parm_calc_expr(), and L_parm_calc_term().
int L_pmatch (char * s1, char * s2)
Definition at line 1316 of file l_parms.c.
Referenced by L_read_parm_b(), L_read_parm_section_defaults(), and L_read_parm_sections().
void L_read_parm_b (Parm_Parse_Info * ppi_in, char * name, int * ptr)
Definition at line 1600 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_pmatch(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_f (Parm_Parse_Info * ppi_in, char * name, float * ptr)
Definition at line 1705 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_i (Parm_Parse_Info * ppi_in, char * name, int * ptr)
Definition at line 1545 of file l_parms.c.
References parm_parse_info_st::calc_ptr, parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, L_add_parm_not_defined(), L_get_parm_table_entry(), L_parm_calc_complete_expr(), L_warn_dev_parm_not_defined, parm_parse_info_st::line_no, look_for_forced_param(), parm_parse_info_st::name, node, NULL, parm_parse_info_st::parm_list, and parm_parse_info_st::setting.
void L_read_parm_lf (Parm_Parse_Info * ppi_in, char * name, double * ptr)
Definition at line 1759 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, I_punt(), L_add_parm_not_defined(), L_get_parm_table_entry(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_s (Parm_Parse_Info * ppi_in, char * name, char ** ptr)
Definition at line 1660 of file l_parms.c.
References parm_parse_info_st::command_line_list, current_section_name1, current_section_name2, L_add_parm_not_defined(), L_get_parm_table_entry(), L_set_parm_s(), L_warn_dev_parm_not_defined, look_for_forced_param(), node, NULL, and parm_parse_info_st::parm_list.
void L_read_parm_section_defaults (Parm_Parse_Info * ppi, Parm_Section_Info * psi, char * defaults_file_name)
Definition at line 2122 of file l_parms.c.
References parm_parse_info_st::file, I_punt(), parm_parse_info_st::internal_level, parm_parse_info_st::internal_list, L_create_parm_macro_list(), L_free_parm_macro_list(), L_pmatch(), L_read_parm_sections(), parm_parse_info_st::line_no, parm_parse_info_st::name, name, parm_section_info::name1, parm_section_info::name2, NULL, PARM_LEVEL_MAX, and PARM_LINE_MAX.
Referenced by L_read_parm_sections().
void L_read_parm_sections (Parm_Parse_Info * ppi, Parm_Section_Info * psi)
Definition at line 2206 of file l_parms.c.
References parm_section_info::found, I_punt(), parm_parse_info_st::internal_level, L_add_to_parm_table_list(), L_get_next_parm(), L_pmatch(), L_read_parm_section_defaults(), parm_section_info::name1, parm_section_info::name2, NULL, parm_section_info::parm_list, section_name1_used, and section_name2_used.
Referenced by _L_load_parameters(), and L_read_parm_section_defaults().
void L_set_parm_s (char ** parm, char * new_string)
Definition at line 1292 of file l_parms.c.
References I_punt(), and NULL.
Referenced by L_read_parm_s().
void L_show_parms_warnings (void)
Definition at line 710 of file l_parms.c.
References current_section_name1, current_section_name2, first_time, parm_warn_list::head, I_punt(), L_dump_parms, L_parm_dump_file_name, L_parm_warn_file_name, L_warn_parm_defined_twice, L_warn_parm_not_defined, L_warn_parm_not_used, MULT_PARM_DEF, parm_table_node::next_input, NO_PARM_DEF, node, NULL, PARM_NOT_USED, start_node_of_input, parm_table_node::used, USED, parm_table_node::user_name, parm_table_node::value, and warn_list.
Referenced by _L_load_parameters().
void L_warn_about_unused_macros (FILE * out, Parm_Macro_List * external_list)
Definition at line 667 of file l_parms.c.
References parm_macro_list::head, I_punt(), node, NULL, PARM_COMMAND_LINE, and PARM_FORCE_PARM.
int look_for_forced_param (char * name, Parm_Macro_List * list)
Definition at line 931 of file l_parms.c.
References current_section_name1, current_section_name2, parm_macro_list::head, I_punt(), L_add_to_parm_table_list(), parm_parse_info_st::line_no, parm_parse_info_st::name, node, NULL, parameter_list, parm_parse_info_st::parm_buf, PARM_FORCE_PARM, and parm_parse_info_st::setting.
Referenced by L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), and L_read_parm_s().
Variable Documentation
char* current_section_name1
Definition at line 128 of file l_parms.c.
Referenced by _L_load_parameters(), L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), L_read_parm_s(), L_show_parms_warnings(), and look_for_forced_param().
char* current_section_name2
Definition at line 129 of file l_parms.c.
Referenced by _L_load_parameters(), L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), L_read_parm_s(), L_show_parms_warnings(), and look_for_forced_param().
int first_time = 1 [static]
Definition at line 142 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_dump_parms = WARNINGS_OFF
Definition at line 152 of file l_parms.c.
Referenced by L_show_parms_warnings().
char* L_parm_dump_file_name = (char *) `stderr`
Definition at line 145 of file l_parms.c.
Referenced by L_show_parms_warnings().
char* L_parm_warn_file_name = (char *) `stderr`
Definition at line 146 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_punt_on_unknown_parm = 0
Definition at line 120 of file l_parms.c.
int L_warn_dev_parm_not_defined = WARNINGS_OFF
Definition at line 150 of file l_parms.c.
Referenced by L_read_parm_b(), L_read_parm_f(), L_read_parm_i(), L_read_parm_lf(), and L_read_parm_s().
int L_warn_old_parm_section_name_used = WARNINGS_OFF
Definition at line 147 of file l_parms.c.
Referenced by _L_load_parameters().
int L_warn_parm_defined_twice = WARNINGS_ON
Definition at line 151 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_warn_parm_not_defined = WARNINGS_ON
Definition at line 149 of file l_parms.c.
Referenced by L_show_parms_warnings().
int L_warn_parm_not_used = WARNINGS_ON
Definition at line 148 of file l_parms.c.
Referenced by L_show_parms_warnings().
Parm_Table_List* parameter_list
Definition at line 134 of file l_parms.c.
Referenced by _L_load_parameters(), and look_for_forced_param().
int section_name1_used = 0
Definition at line 131 of file l_parms.c.
Referenced by _L_load_parameters(), and L_read_parm_sections().
int section_name2_used = 0
Definition at line 132 of file l_parms.c.
Referenced by _L_load_parameters(), and L_read_parm_sections().
Parm_Table_Node* start_node_of_input
Definition at line 139 of file l_parms.c.
Referenced by _L_load_parameters(), and L_show_parms_warnings().
Parm_Warn_List* warn_list
Definition at line 127 of file l_parms.c.
Referenced by _L_load_parameters(), L_add_parm_already_defined(), L_add_parm_not_defined(), L_add_parm_not_used(), and L_show_parms_warnings().