line.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <library/line.h>
Defines
#define WHITE_SPACE(ch) ((ch==' ')||(ch=='\t')||(ch==''))
Functions
static void Punt (char *mesg)
int ReadLine (FILE *F, char buf[], int len)
int ReadWord (FILE *F, char buf[], int len)
int ParseLine (char *line, char *buf[], int len)
int ParseLine2 (char *line, char *buf[], int len)
int MatchPrefix (char *line, char *prefix)
int WildcardMatch (char *pattern, char *name)
int RemovePostfix (char src[], char seperator, char buf[], int buf_len)
int RemovePrefix (char src[], char seperator, char buf[], int buf_len)
int GetPrefix (char src[], char seperator, char buf[], int buf_len)
Define Documentation
#define WHITE_SPACE(ch) ((ch==' ')||(ch=='\t')||(ch==''))
Definition at line 71 of file line.c.
Referenced by ParseLine(), ParseLine2(), ReadLine(), and ReadWord().
Function Documentation
int GetPrefix (char src[], char seperator, char buf[], int buf_len)
Definition at line 346 of file line.c.
int MatchPrefix (char * line, char * prefix)
Definition at line 230 of file line.c.
int ParseLine (char * line, char * buf[], int len)
Definition at line 164 of file line.c.
References Punt(), and WHITE_SPACE.
int ParseLine2 (char * line, char * buf[], int len)
Definition at line 196 of file line.c.
References Punt(), and WHITE_SPACE.
static void Punt (char * mesg) [static]
Definition at line 65 of file line.c.
Referenced by _Add_2_nd_buf(), AddExtensionFields(), AppendLint(), AppendLptr(), ConnectNodes(), DecodeNode(), DecodeRoot(), MarkNodes(), NewArc(), NewGraph(), NewLint(), NewLptr(), NewNode(), ParseLine(), ParseLine2(), PlaceTraces(), ReadGraph(), ReadLine(), ReadWord(), ReportSelectionResult(), SelectBySortArc(), SelectTraces(), TraceSelection(), and WriteGraph().
int ReadLine (FILE * F, char buf[], int len)
Definition at line 83 of file line.c.
References Punt(), and WHITE_SPACE.
int ReadWord (FILE * F, char buf[], int len)
Definition at line 126 of file line.c.
References Punt(), and WHITE_SPACE.
int RemovePostfix (char src[], char seperator, char buf[], int buf_len)
Definition at line 294 of file line.c.
int RemovePrefix (char src[], char seperator, char buf[], int buf_len)
Definition at line 322 of file line.c.
int WildcardMatch (char * pattern, char * name)
Definition at line 249 of file line.c.
References WildcardMatch().
Referenced by WildcardMatch().