list.c File Reference
#include <config.h>
#include `FIX_list.h`
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <malloc.h>
#include <string.h>
#include <library/i_types.h>
#include `list.h`
Data Structures
struct yysvf
struct String
struct yywork
Defines
#define U(x) x
#define NLSTATE yyprevious=YYNEWLINE
#define BEGIN yybgin = yysvec + 1 +
#define INITIAL 0
#define YYLERR yysvec
#define YYSTATE (yyestate-yysvec-1)
#define YYOPTIM 1
#define YYLMAX 200
#define output(c) (void)putc(c,yyout)
#define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)
#define unput(c) {yytchar= (c);if(yytchar=='\n')yylineno--;*yysptr++=yytchar;}
#define yymore() (yymorfg=1)
#define ECHO (void)fprintf(yyout, `%s`,yytext)
#define REJECT { nstr = yyreject(); goto yyfussy;}
#define YYLMAX 2500
#define ToState(n) BEGIN(n)
#define DefaultState 0
#define COMMENT 2
#define YYNEWLINE 10
#define MAX_LEVEL 20
#define YYTYPE unsigned char
#define YYU(x) x
#define NLSTATE yyprevious=YYNEWLINE
Functions
static int lexOpen (char *file_name, int inclusion)
static int lexClose (char *file_name)
static int lexIntLit (void)
static int lexRealLit (void)
static int lexStringLit (void)
static int lexCharLit (void)
static int lexIdentifier (void)
static void lexError (char *)
static char * FindString (char *str)
int yywrap (void)
int yylex ()
static void Push (FILE *fpt, char *name)
static FILE * Pop (void)
static char * LastFile (void)
static int lexExist (char *file_name, int inclusion)
int old_lexOpen (char *file_name, int inclusion)
int old_lexClose (char *file_name)
static FILE * SwitchFile (FILE *fpt)
static char * lmalloc (int size)
static char * strsave (char *str)
static String * FindS (String *T, char *str)
static String * AddS (String *T, char *str)
char * old_FindString (char *str)
static LIST NewNode (void)
LIST DisposeNode (LIST node)
void FreeDeadList ()
static void AddChildNode (LIST parent, LIST child)
LIST GetNode (void)
void print_node (LIST node, int indent)
void PrintNode (FILE *F, LIST node)
LIST GetInteger (LIST list, int *val)
LIST GetReal (LIST list, double *val)
LIST GetString (LIST list, char **val)
LIST GetId (LIST list, char **val)
static void RemoveS (String *ptr)
void RemoveAllString ()
yylook ()
yyback (int *p, m)
yyinput ()
yyoutput (int c)
yyunput (int c)
Variables
int yyleng
char yytext []
int yymorfg
char * yysptr
char yysbuf []
int yytchar
FILE * yyin = NULL
FILE * yyout = NULL
int yylineno
yysvf * yyestate
yysvf yysvec []
yysvf * yybgin
int TokenType
char * TokenName
ITintmax TokenInteger
double TokenReal
static int lex_error = 0
static int stack_top = 0
static FILE * stack [MAX_LEVEL]
static char * fname [MAX_LEVEL]
static char * current_file = `??`
static String * stringTree = 0
static LIST dead_list = 0
static int dead_list_length = 0
static FILE * FF = NULL
int yyvstop []
yywork yycrank []
yysvf yysvec []
yywork * yytop = yycrank + 1556
yysvf * yybgin = yysvec + 1
char yymatch []
char yyextra []
int yylineno = 1
yysvf * yylstate [YYLMAX]
yysvf ** yylsp
yysvf ** yyolsp
char * yysptr = yysbuf
int * yyfnd
yysvf * yyestate
int yyprevious = YYNEWLINE
Define Documentation
#define BEGIN yybgin = yysvec + 1 +
Definition at line 73 of file list.c.
#define COMMENT 2
Definition at line 180 of file list.c.
#define DefaultState 0
Definition at line 176 of file list.c.
#define ECHO (void)fprintf(yyout, `%s`,yytext)
Definition at line 110 of file list.c.
#define INITIAL 0
Definition at line 74 of file list.c.
#define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)
Definition at line 107 of file list.c.
#define MAX_LEVEL 20
Definition at line 435 of file list.c.
#define NLSTATE yyprevious=YYNEWLINE
Definition at line 2225 of file list.c.
#define NLSTATE yyprevious=YYNEWLINE
Definition at line 2225 of file list.c.
#define output(c) (void)putc(c,yyout)
Definition at line 79 of file list.c.
#define REJECT { nstr = yyreject(); goto yyfussy;}
Definition at line 111 of file list.c.
#define ToState(n) BEGIN(n)
Definition at line 175 of file list.c.
#define U(x) x
Definition at line 71 of file list.c.
#define unput(c) {yytchar= (c);if(yytchar=='\n')yylineno--;*yysptr++=yytchar;}
Definition at line 108 of file list.c.
#define YYLERR yysvec
Definition at line 75 of file list.c.
#define YYLMAX 2500
Definition at line 154 of file list.c.
#define YYLMAX 200
Definition at line 154 of file list.c.
#define yymore() (yymorfg=1)
Definition at line 109 of file list.c.
#define YYNEWLINE 10
Definition at line 181 of file list.c.
#define YYOPTIM 1
Definition at line 77 of file list.c.
#define YYSTATE (yyestate-yysvec-1)
Definition at line 76 of file list.c.
#define YYTYPE unsigned char
Definition at line 1622 of file list.c.
#define YYU(x) x
Definition at line 2224 of file list.c.
Function Documentation
static void AddChildNode (LIST parent, LIST child) [static]
Definition at line 894 of file list.c.
References ChildOf, LastChildOf, and SiblingOf.
Referenced by GetNode().
static String* AddS (String * T, char * str) [static]
Definition at line 770 of file list.c.
References AddS(), String::left, lmalloc(), String::name, String::right, and strsave().
LIST DisposeNode (LIST node)
Definition at line 856 of file list.c.
References ChildOf, dead_list, DisposeNode(), FreeDeadList(), node, NodeType, SiblingOf, and T_LIST.
Referenced by DisposeNode(), and ReadGraph().
static String* FindS (String * T, char * str) [static]
Definition at line 753 of file list.c.
References FindS(), String::left, String::name, and String::right.
static char * FindString (char * str) [static]
Definition at line 808 of file list.c.
References AddS(), FindS(), String::name, and stringTree.
Referenced by GetNode(), lexExist(), lexOpen(), and old_FindString().
void FreeDeadList (void)
Definition at line 877 of file list.c.
References dead_list, and SiblingOf.
Referenced by DisposeNode().
LIST GetId (LIST list, char ** val)
Definition at line 1108 of file list.c.
References NodeType, SiblingOf, StringOf, and T_ID.
LIST GetInteger (LIST list, int * val)
Definition at line 1078 of file list.c.
References NodeType, ScalarOf, SiblingOf, and T_INT.
LIST GetNode (void)
Definition at line 936 of file list.c.
References AddChildNode(), ChildOf, FindString(), GetNode(), L_CHAR, L_ERROR, L_ID, L_INT, L_REAL, L_STRING, new_node(), NewNode(), NodeType, RealOf, ScalarOf, StringOf, T_CHAR, T_EOF, T_ID, T_INT, T_LIST, T_NULL, T_REAL, T_STRING, TokenInteger, TokenName, TokenReal, and yylex.
Referenced by GetNode(), and ReadGraph().
LIST GetReal (LIST list, double * val)
Definition at line 1088 of file list.c.
References NodeType, RealOf, SiblingOf, and T_REAL.
LIST GetString (LIST list, char ** val)
Definition at line 1098 of file list.c.
References NodeType, SiblingOf, StringOf, and T_STRING.
static char* LastFile (void) [static]
Definition at line 470 of file list.c.
References fname, and stack_top.
Referenced by lexClose().
static int lexCharLit (void) [static]
Definition at line 702 of file list.c.
References L_CHAR, TokenBuffer, TokenName, and TokenType.
Referenced by yylex().
static int lexClose (char * file_name) [static]
Definition at line 599 of file list.c.
References current_file, LastFile(), Pop(), and yyin.
Referenced by old_lexClose().
static void lexError (char *) [static]
Definition at line 443 of file list.c.
References current_file, and lex_error.
Referenced by lexOpen(), Push(), SwitchFile(), and yylex().
static int lexExist (char * file_name, int inclusion) [static]
Definition at line 486 of file list.c.
References current_file, FindString(), and NULL.
static int lexIdentifier (void) [static]
Definition at line 710 of file list.c.
References L_ID, TokenBuffer, TokenName, and TokenType.
Referenced by yylex().
static int lexIntLit (void) [static]
Definition at line 675 of file list.c.
References ITintmaxformat, ITuintmaxformat, L_INT, TokenBuffer, TokenInteger, and TokenType.
Referenced by yylex().
static int lexOpen (char * file_name, int inclusion) [static]
Definition at line 537 of file list.c.
References current_file, FindString(), lexError(), NULL, Push(), yyin, and yyout.
Referenced by old_lexOpen().
static int lexRealLit (void) [static]
Definition at line 686 of file list.c.
References atof(), L_REAL, TokenBuffer, TokenReal, and TokenType.
Referenced by yylex().
static int lexStringLit (void) [static]
Definition at line 694 of file list.c.
References L_STRING, TokenBuffer, TokenName, and TokenType.
Referenced by yylex().
static char* lmalloc (int size) [static]
Definition at line 731 of file list.c.
Referenced by AddS(), NewNode(), and strsave().
static LIST NewNode (void) [static]
Definition at line 830 of file list.c.
References ChildOf, dead_list, LastChildOf, lmalloc(), new_node(), NodeType, SiblingOf, and T_NULL.
char* old_FindString (char * str)
Definition at line 802 of file list.c.
References FindString().
int old_lexClose (char * file_name)
Definition at line 593 of file list.c.
References lexClose().
int old_lexOpen (char * file_name, int inclusion)
Definition at line 531 of file list.c.
References lexOpen().
static FILE* Pop (void) [static]
Definition at line 461 of file list.c.
References stack, and stack_top.
Referenced by lexClose().
void print_node (LIST node, int indent)
Definition at line 1012 of file list.c.
References ChildOf, IntegerOf, ITintmaxformat, node, NodeType, NULL, print_node(), RealOf, ScalarOf, SiblingOf, StringOf, T_CHAR, T_EOF, T_ID, T_INT, T_LIST, T_NULL, T_OPER, T_REAL, and T_STRING.
void PrintNode (FILE * F, LIST node)
Definition at line 1069 of file list.c.
References node, and print_node().
static void Push (FILE * fpt, char * name) [static]
Definition at line 451 of file list.c.
References fname, lexError(), MAX_LEVEL, stack, and stack_top.
Referenced by lexOpen().
void RemoveAllString (void)
Definition at line 1134 of file list.c.
References RemoveS(), and stringTree.
static void RemoveS (String * ptr) [static]
Definition at line 1120 of file list.c.
References String::left, String::name, RemoveS(), and String::right.
static char* strsave (char * str) [static]
Definition at line 744 of file list.c.
References lmalloc().
Referenced by AddS().
static FILE* SwitchFile (FILE * fpt) [static]
Definition at line 609 of file list.c.
References lexError(), NULL, and yyin.
Referenced by ReadGraph().
yyback (int * p, m)
Definition at line 2455 of file list.c.
yyinput ()
Definition at line 2473 of file list.c.
References input.
int yylex (void)
Definition at line 183 of file list.c.
References COMMENT, DefaultState, L_ERROR, lexCharLit(), lexError(), lexIdentifier(), lexIntLit(), lexRealLit(), lexStringLit(), TokenBuffer, TokenChar, TokenType, ToState, yylook, yyout, yyprevious, and yywrap.
yylook ()
Definition at line 2237 of file list.c.
References yywork::advance, input, output, unput, yywork::verify, yyback, yybgin, yycrank, yyestate, yyleng, YYLERR, YYLMAX, yylsp, yylstate, yymorfg, YYNEWLINE, yyolsp, yysvf::yyother, yyout, yysvf::yystoff, yysvec, and YYU.
yyoutput (int c)
Definition at line 2482 of file list.c.
References output.
yyunput (int c)
Definition at line 2492 of file list.c.
References unput.
int yywrap (void)
Variable Documentation
char* current_file = `??` [static]
Definition at line 439 of file list.c.
Referenced by lexClose(), lexError(), lexExist(), and lexOpen().
LIST dead_list = 0 [static]
Definition at line 825 of file list.c.
int dead_list_length = 0 [static]
Definition at line 826 of file list.c.
FILE* FF = NULL [static]
Definition at line 1010 of file list.c.
char* fname[MAX_LEVEL] [static]
Definition at line 438 of file list.c.
int lex_error = 0 [static]
Definition at line 173 of file list.c.
FILE* stack[MAX_LEVEL] [static]
Definition at line 437 of file list.c.
int stack_top = 0 [static]
Definition at line 436 of file list.c.
Referenced by LastFile(), Pop(), pop_file(), Push(), and push_file().
String* stringTree = 0 [static]
Definition at line 728 of file list.c.
Referenced by FindString(), and RemoveAllString().
ITintmax TokenInteger
Definition at line 171 of file list.c.
char* TokenName
Definition at line 170 of file list.c.
double TokenReal
Definition at line 172 of file list.c.
int TokenType
Definition at line 169 of file list.c.
struct yysvf* yybgin = yysvec + 1
Definition at line 2176 of file list.c.
struct yysvf * yybgin
Definition at line 2603 of file c_list.c.
struct yywork
 yycrank[]
struct yysvf* yyestate
Definition at line 111 of file c_list.c.
struct yysvf* yyestate
Definition at line 130 of file list.c.
char yyextra[]
Initial value:
 {
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0
}
Definition at line 2212 of file list.c.
int* yyfnd
Definition at line 2230 of file list.c.
FILE* yyin = NULL
Definition at line 122 of file list.c.
int yyleng
Definition at line 112 of file list.c.
int yylineno = 1
Definition at line 2223 of file list.c.
int yylineno
Definition at line 2650 of file c_list.c.
struct yysvf ** yylsp
Definition at line 2227 of file list.c.
struct yysvf* yylstate[YYLMAX]
Definition at line 2227 of file list.c.
char yymatch[]
Definition at line 2177 of file list.c.
int yymorfg
Definition at line 114 of file list.c.
struct yysvf ** yyolsp
Definition at line 2227 of file list.c.
FILE * yyout = NULL
Definition at line 122 of file list.c.
int yyprevious = YYNEWLINE
Definition at line 2232 of file list.c.
char yysbuf[YYLMAX]
Definition at line 2228 of file list.c.
char* yysptr = yysbuf
Definition at line 2229 of file list.c.
char* yysptr
Definition at line 2656 of file c_list.c.
struct yysvf yysvec[]
Definition at line 2018 of file list.c.
struct yysvf yysvec[]
Definition at line 2425 of file c_list.c.
int yytchar
Definition at line 116 of file list.c.
char yytext[YYLMAX]
Definition at line 2226 of file list.c.
struct yywork* yytop = yycrank + 1556
Definition at line 2175 of file list.c.
int yyvstop[]
Definition at line 1139 of file list.c.