llist.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include `llist.h`
Functions
static void Punt (char *mesg)
void Init_NewLint ()
Lint NewLint (int id)
Lint AppendLint (Lint list1, Lint list2)
Lint CopyLint (Lint list)
Lint FreeLint (Lint list)
Lint FindNth (Lint list, int N)
int InLint (Lint list, int id)
int PrintLint (Lint list)
void Init_NewLptr ()
Lptr NewLptr (void *ptr)
Lptr AppendLptr (Lptr list1, Lptr list2)
Lptr AddToSortedLptr (void *p, Lptr list)
Lint AddToSortedLint (int p, Lint list)
Lptr InSortedLptr (Lptr list, void *p)
Lint InSortedLint (Lint list, int p)
int LintLength (Lint list)
Lptr CopyLptr (Lptr list)
Lptr FreeLptr (Lptr list)
Lptr InLptr (Lptr list, void *ptr)
Lptr NameInLptr (Lptr list, char *ptr)
int LptrLength (Lptr list)
int SameSortedLptr (Lptr list1, Lptr list2)
void CopySortedLptrList (Lptr *base, Lptr list)
void En_FIFO_LptrQ (LptrQ Q, void *element)
void En_FILO_LptrQ (LptrQ Q, void *element)
void * De_LptrQ (LptrQ Q)
void * Peek_LptrQ (LptrQ Q)
Variables
int debug_lptr
int new_lptr_added
static Lint d_lint = 0
L_Alloc_Pool * Lint_Pool
static Lptr d_lptr = 0
L_Alloc_Pool * Lptr_Pool
Function Documentation
Lint AddToSortedLint (int p, Lint list)
Definition at line 346 of file llist.c.
References _Lint::id, Init_NewLint(), Lint_Pool, NewLint(), and _Lint::next.
Lptr AddToSortedLptr (void * p, Lptr list)
Definition at line 259 of file llist.c.
References debug_lptr, Init_NewLptr(), Lptr_Pool, LptrLength(), new_lptr_added, NewLptr(), _Lptr::next, and _Lptr::ptr.
Referenced by CopySortedLptrList().
Lint AppendLint (Lint list1, Lint list2)
Definition at line 113 of file llist.c.
References _Lint::id, _Lint::next, and Punt().
Referenced by FreeLint().
Lptr AppendLptr (Lptr list1, Lptr list2)
Definition at line 229 of file llist.c.
References _Lptr::next, _Lptr::ptr, and Punt().
Referenced by FreeLptr().
Lint CopyLint (Lint list)
Definition at line 142 of file llist.c.
References CopyLint(), _Lint::id, NewLint(), and _Lint::next.
Referenced by CopyLint().
Lptr CopyLptr (Lptr list)
Definition at line 437 of file llist.c.
References CopyLptr(), NewLptr(), _Lptr::next, and _Lptr::ptr.
Referenced by CopyLptr().
void CopySortedLptrList (Lptr * base, Lptr list)
Definition at line 512 of file llist.c.
References AddToSortedLptr(), CopySortedLptrList(), _Lptr::next, and _Lptr::ptr.
Referenced by CopySortedLptrList().
void* De_LptrQ (LptrQ Q)
Definition at line 557 of file llist.c.
References FreeLptr(), _LptrQ::head, _LptrQ::length, _Lptr::next, _Lptr::ptr, and _LptrQ::tail.
void En_FIFO_LptrQ (LptrQ Q, void * element)
Definition at line 521 of file llist.c.
References _LptrQ::head, _LptrQ::length, NewLptr(), _Lptr::next, and _LptrQ::tail.
void En_FILO_LptrQ (LptrQ Q, void * element)
Definition at line 539 of file llist.c.
References _LptrQ::head, _LptrQ::length, NewLptr(), _Lptr::next, and _LptrQ::tail.
Lint FindNth (Lint list, int N)
Definition at line 162 of file llist.c.
References _Lint::next.
Lint FreeLint (Lint list)
Definition at line 151 of file llist.c.
References AppendLint(), and d_lint.
Lptr FreeLptr (Lptr list)
Definition at line 447 of file llist.c.
References AppendLptr(), and d_lptr.
Referenced by De_LptrQ().
void Init_NewLint ()
Definition at line 89 of file llist.c.
References L_create_alloc_pool(), and Lint_Pool.
Referenced by AddToSortedLint().
void Init_NewLptr ()
Definition at line 203 of file llist.c.
References L_create_alloc_pool(), and Lptr_Pool.
Referenced by AddToSortedLptr(), and NewLptr().
int InLint (Lint list, int id)
Definition at line 178 of file llist.c.
References _Lint::id, and _Lint::next.
Lptr InLptr (Lptr list, void * ptr)
Definition at line 460 of file llist.c.
References _Lptr::next, and _Lptr::ptr.
Lint InSortedLint (Lint list, int p)
Definition at line 409 of file llist.c.
References _Lint::id, and _Lint::next.
Lptr InSortedLptr (Lptr list, void * p)
Definition at line 394 of file llist.c.
References _Lptr::next, and _Lptr::ptr.
int LintLength (Lint list)
Definition at line 425 of file llist.c.
References _Lint::next.
int LptrLength (Lptr list)
Definition at line 483 of file llist.c.
References _Lptr::next.
Referenced by AddToSortedLptr().
Lptr NameInLptr (Lptr list, char * ptr)
Definition at line 471 of file llist.c.
References _Lptr::next, and _Lptr::ptr.
Lint NewLint (int id)
Definition at line 94 of file llist.c.
References d_lint, _Lint::id, L_alloc(), Lint_Pool, _Lint::next, and Punt().
Referenced by AddToSortedLint(), and CopyLint().
Lptr NewLptr (void * ptr)
Definition at line 208 of file llist.c.
References d_lptr, Init_NewLptr(), L_alloc(), Lptr_Pool, _Lptr::next, _Lptr::ptr, and Punt().
Referenced by AddToSortedLptr(), CopyLptr(), En_FIFO_LptrQ(), and En_FILO_LptrQ().
void* Peek_LptrQ (LptrQ Q)
Definition at line 579 of file llist.c.
References _LptrQ::head, _LptrQ::length, NULL, and _Lptr::ptr.
int PrintLint (Lint list)
Definition at line 189 of file llist.c.
References _Lint::id, and _Lint::next.
static void Punt (char * mesg) [static]
Definition at line 78 of file llist.c.
int SameSortedLptr (Lptr list1, Lptr list2)
Definition at line 497 of file llist.c.
References _Lptr::next, and _Lptr::ptr.
Variable Documentation
Lint d_lint = 0 [static]
Definition at line 85 of file llist.c.
Referenced by FreeLint(), and NewLint().
Lptr d_lptr = 0 [static]
Definition at line 199 of file llist.c.
Referenced by FreeLptr(), and NewLptr().
int debug_lptr
Definition at line 70 of file llist.c.
Referenced by AddToSortedLptr().
L_Alloc_Pool* Lint_Pool
Definition at line 86 of file llist.c.
Referenced by AddToSortedLint(), Init_NewLint(), and NewLint().
L_Alloc_Pool* Lptr_Pool
Definition at line 200 of file llist.c.
Referenced by AddToSortedLptr(), Init_NewLptr(), and NewLptr().
int new_lptr_added
Definition at line 71 of file llist.c.
Referenced by AddToSortedLptr().