mbuf.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <library/i_error.h>
#include `mbuf.h`
Functions
Mbuf * create_Mbuf ()
void free_Mbuf (Mbuf *mbuf)
void clear_Mbuf (Mbuf *mbuf)
void addc_to_Mbuf (Mbuf *mbuf, char ch)
void adds_to_Mbuf (Mbuf *mbuf, char *str)
void pad_Mbuf_to_len (Mbuf *mbuf, int desired_len, char pad_ch)
void strip_Mbuf (Mbuf *mbuf)
char * get_Mbuf_buf (Mbuf *mbuf)
char * copy_Mbuf_buf (Mbuf *mbuf)
int len_of_Mbuf (Mbuf *mbuf)
int match_Mbuf (Mbuf *mbuf, char *string)
Variables
L_Alloc_Pool * Mbuf_pool = NULL
Function Documentation
void addc_to_Mbuf (Mbuf * mbuf, char ch)
Definition at line 122 of file mbuf.c.
References Mbuf::buf, Mbuf::cur_len, I_punt(), Mbuf::max_len, and NULL.
Referenced by adds_to_Mbuf(), create_Mfile(), and pad_Mbuf_to_len().
void adds_to_Mbuf (Mbuf * mbuf, char * str)
Definition at line 154 of file mbuf.c.
References addc_to_Mbuf().
void clear_Mbuf (Mbuf * mbuf)
Definition at line 106 of file mbuf.c.
References Mbuf::buf, Mbuf::cur_len, I_punt(), Mbuf::max_len, and NULL.
Referenced by create_Mbuf(), and create_Mfile().
char* copy_Mbuf_buf (Mbuf * mbuf)
Definition at line 199 of file mbuf.c.
References Mbuf::buf, Mbuf::cur_len, I_punt(), and NULL.
Referenced by create_Mfile().
Mbuf* create_Mbuf ()
Definition at line 76 of file mbuf.c.
References Mbuf::buf, clear_Mbuf(), L_alloc(), L_create_alloc_pool(), Mbuf_pool, and NULL.
Referenced by create_Mfile().
void free_Mbuf (Mbuf * mbuf)
Definition at line 97 of file mbuf.c.
References Mbuf::buf, L_free(), and Mbuf_pool.
Referenced by create_Mfile().
char* get_Mbuf_buf (Mbuf * mbuf)
Definition at line 192 of file mbuf.c.
References Mbuf::buf.
int len_of_Mbuf (Mbuf * mbuf)
Definition at line 222 of file mbuf.c.
References Mbuf::cur_len.
Referenced by create_Mfile().
int match_Mbuf (Mbuf * mbuf, char * string)
Definition at line 229 of file mbuf.c.
References Mbuf::buf.
void pad_Mbuf_to_len (Mbuf * mbuf, int desired_len, char pad_ch)
Definition at line 166 of file mbuf.c.
References addc_to_Mbuf(), and Mbuf::cur_len.
void strip_Mbuf (Mbuf * mbuf)
Definition at line 174 of file mbuf.c.
References Mbuf::buf, and Mbuf::cur_len.
Variable Documentation
L_Alloc_Pool* Mbuf_pool = NULL
Definition at line 73 of file mbuf.c.
Referenced by create_Mbuf(), and free_Mbuf().