md.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `md.h`
#include <stdarg.h>
#include <ctype.h>
#include <library/l_alloc_new.h>
Data Structures
struct MD_Buf
Defines
#define MD_DEBUG_MACROS
Functions
static void MD_resize_field_arrays (MD_Section *section, int max_index)
static void MD_resize_element_array (MD_Field *field, int max_index)
static int MD_legal_ident (char *ident)
static void MD_punt (MD *md, char *fmt,...)
static void MD_warn (FILE *out, char *fmt,...)
static char * MD_strdup (char *string)
static char * MD_concat_strings (char *string1, char *string2)
static MD_Symbol_Table * MD_new_symbol_table (MD *md, char *name, int expected_size)
void MD_delete_symbol_table (MD_Symbol_Table *table, void(*free_routine)(void *))
static void MD_resize_symbol_table (MD_Symbol_Table *table)
static unsigned int MD_hash_string (char *string)
static MD_Symbol * MD_add_symbol (MD_Symbol_Table *table, char *name, void *data)
static void MD_rename_symbol (MD_Symbol *symbol, char *new_name)
void * _MD_find_symbol_data (MD_Symbol_Table *table, char *name)
void MD_delete_symbol (MD_Symbol *symbol, void(*free_routine)(void *))
MD * MD_new_md (char *name, int num_sections)
void MD_delete_md (MD *md)
int MD_check_md (FILE *out, MD *md)
MD_Buf * MD_new_buf ()
void MD_resize_buf (MD_Buf *buf)
void MD_delete_buf (MD_Buf *buf)
void MD_read_consume_comments (FILE *in)
int MD_read_int (FILE *in)
double MD_read_double (FILE *in, MD_Buf *value_buf)
void MD_read_string (FILE *in, MD_Buf *value_buf)
void MD_read_block (FILE *in, unsigned int block_size, MD_Buf *value_buf)
void MD_read_nl (FILE *in)
void MD_read_sp (FILE *in)
MD * MD_read_md (FILE *in, char *name)
void MD_write_md (FILE *out, MD *md)
void MD_print_md (FILE *out, MD *md, int page_width)
void MD_print_md_declarations (FILE *out, MD *md, int page_width)
void MD_print_md_template (FILE *out, MD *md)
MD_Section * MD_new_section (MD *md, char *name, int num_entries, int num_fields)
int _MD_num_sections (MD *md)
MD_Section * _MD_find_section (MD *md, char *name)
MD_Section * MD_first_section (MD *md)
MD_Section * MD_last_section (MD *md)
MD_Section * MD_next_section (MD_Section *section)
MD_Section * MD_prev_section (MD_Section *section)
void * _MD_set_section_ext (MD_Section *section, void *ext)
void * _MD_get_section_ext (MD_Section *section)
void _MD_free_section (MD_Section *section)
void _MD_delete_section (MD_Section *section)
int _MD_check_section (FILE *out, MD_Section *section, char *caller_name)
void MD_print_section (FILE *out, MD_Section *section, int page_width)
void MD_print_section_template (FILE *out, MD_Section *section)
MD_Entry * MD_new_entry (MD_Section *section, char *name)
void MD_rename_entry (MD_Entry *entry, char *new_name)
int _MD_num_entries (MD_Section *section)
MD_Entry * _MD_find_entry (MD_Section *section, char *name)
MD_Entry * MD_first_entry (MD_Section *section)
MD_Entry * MD_last_entry (MD_Section *section)
MD_Entry * MD_next_entry (MD_Entry *entry)
MD_Entry * MD_prev_entry (MD_Entry *entry)
void * _MD_set_entry_ext (MD_Entry *entry, void *ext)
void * _MD_get_entry_ext (MD_Entry *entry)
void _MD_free_entry (MD_Entry *entry)
void _MD_delete_entry (MD_Entry *entry)
int _MD_check_entry (FILE *out, MD_Entry *entry, char *caller_name)
void MD_print_entry (FILE *out, MD_Entry *entry, int page_width)
void MD_print_entry_template (FILE *out, MD_Entry *entry)
MD_Field_Decl * MD_new_field_decl (MD_Section *section, char *name, MD_FIELD_TYPE field_type)
int _MD_num_field_decls (MD_Section *section)
int _MD_max_field_index (MD_Section *section)
MD_Field_Decl * _MD_find_field_decl (MD_Section *section, char *name)
MD_Field_Decl * MD_first_field_decl (MD_Section *section)
MD_Field_Decl * MD_last_field_decl (MD_Section *section)
MD_Field_Decl * MD_next_field_decl (MD_Field_Decl *field_decl)
MD_Field_Decl * MD_prev_field_decl (MD_Field_Decl *field_decl)
void _MD_free_field_decl (MD_Field_Decl *field_decl)
void MD_delete_field_decl (MD_Field_Decl *field_decl)
void MD_print_field_decl (FILE *out, MD_Field_Decl *field_decl, int page_width)
static MD_Element_Req * MD_new_element_req (MD_Field_Decl *field_decl, int index, char *caller_name)
void MD_require_int (MD_Field_Decl *field_decl, int element_index)
void MD_require_double (MD_Field_Decl *field_decl, int element_index)
void MD_require_string (MD_Field_Decl *field_decl, int element_index)
void MD_require_block (MD_Field_Decl *field_decl, int element_index)
void MD_require_link (MD_Field_Decl *field_decl, int element_index, MD_Section *section)
void MD_require_multi_target_link (MD_Field_Decl *field_decl, int element_index, int section_array_size, MD_Section **section_array)
void MD_kleene_star_requirement (MD_Field_Decl *field_decl, int element_index)
MD_Field * MD_new_field (MD_Entry *entry, MD_Field_Decl *decl, int num_elements)
MD_Field * _MD_find_field (MD_Entry *entry, MD_Field_Decl *field_decl)
void MD_delete_field (MD_Field *field)
int _MD_check_field (FILE *out, MD_Field *field, char *caller_name)
static int MD_check_setting (FILE *out, MD_Field *field, int index, char *caller_name)
int _MD_num_elements (MD_Field *field)
int _MD_max_element_index (MD_Field *field)
void _MD_set_int (MD_Field *field, int index, int value)
void _MD_set_int_type_checking (MD_Field *field, int index, int value)
int _MD_get_int (MD_Field *field, int index)
void _MD_set_double (MD_Field *field, int index, double value)
void _MD_set_double_type_checking (MD_Field *field, int index, double value)
double _MD_get_double (MD_Field *field, int index)
void _MD_set_string (MD_Field *field, int index, char *value)
void _MD_set_string_type_checking (MD_Field *field, int index, char *value)
char * _MD_get_string (MD_Field *field, int index)
void _MD_set_block (MD_Field *field, int index, unsigned int size, void *ptr)
void _MD_set_block_type_checking (MD_Field *field, int index, unsigned int size, void *ptr)
int _MD_get_block_size (MD_Field *field, int index)
void * _MD_get_block_ptr (MD_Field *field, int index)
void _MD_set_link (MD_Field *field, int index, MD_Entry *value)
void _MD_set_link_type_checking (MD_Field *field, int index, MD_Entry *value)
MD_Entry * _MD_get_link (MD_Field *field, int index)
void MD_delete_element (MD_Field *field, int index)
Variables
static L_Alloc_Pool * MD_Buf_pool = NULL
static L_Alloc_Pool * MD_pool = NULL
static L_Alloc_Pool * MD_Symbol_Table_pool = NULL
static L_Alloc_Pool * MD_Symbol_pool = NULL
static L_Alloc_Pool * MD_Section_pool = NULL
static L_Alloc_Pool * MD_Entry_pool = NULL
static L_Alloc_Pool * MD_Field_Decl_pool = NULL
static L_Alloc_Pool * MD_Element_Req_pool = NULL
static L_Alloc_Pool * MD_Field_pool = NULL
static L_Alloc_Pool * MD_Element_pool = NULL
static char * MD_type_name []
Define Documentation
#define MD_DEBUG_MACROS
Definition at line 92 of file md.c.
Function Documentation
int _MD_check_entry (FILE * out, MD_Entry * entry, char * caller_name)
Definition at line 2767 of file md.c.
References _MD_check_field(), entry, MD_Section::field_decl, MD_Section::max_field_index, MD_REQUIRED_FIELD, MD_warn(), MD_Section::name, MD_Field_Decl::name, NULL, and MD_Field_Decl::type.
Referenced by _MD_check_section().
int _MD_check_field (FILE * out, MD_Field * field, char * caller_name)
Definition at line 4414 of file md.c.
References MD_Field::decl, MD_Element_Req::desc, MD_Field::element, entry, MD_Field::entry, MD_Field_Decl::kleene_starred_req, MD_Element::l, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_LINK, MD_type_name, MD_warn(), MD_Section::name, MD_Field_Decl::name, MD_Entry::name, NULL, MD_Field_Decl::require, MD_Entry::section, MD_Element::type, MD_Element_Req::type, and MD_Element::value.
Referenced by _MD_check_entry().
int _MD_check_section (FILE * out, MD_Section * section, char * caller_name)
Definition at line 2412 of file md.c.
References _MD_check_entry(), MD_Symbol::data, entry, MD_Section::entry_table, MD_Symbol_Table::head_symbol, MD_Symbol::next_symbol, and NULL.
Referenced by MD_check_md().
void _MD_delete_entry (MD_Entry * entry)
Definition at line 2745 of file md.c.
References _MD_free_entry(), entry, and MD_delete_symbol().
void _MD_delete_section (MD_Section * section)
Definition at line 2389 of file md.c.
References _MD_free_section(), MD_delete_symbol(), and MD_Section::symbol.
MD_Entry* _MD_find_entry (MD_Section * section, char * name)
Definition at line 2594 of file md.c.
References _MD_find_symbol_data(), and MD_Section::entry_table.
MD_Field* _MD_find_field (MD_Entry * entry, MD_Field_Decl * field_decl)
Definition at line 4331 of file md.c.
References entry, MD_Field_Decl::field_index, MD_punt(), MD_Field_Decl::name, MD_Section::name, and MD_Field_Decl::section.
MD_Field_Decl* _MD_find_field_decl (MD_Section * section, char * name)
Definition at line 3440 of file md.c.
References _MD_find_symbol_data(), and MD_Section::field_decl_table.
MD_Section* _MD_find_section (MD * md, char * name)
Definition at line 2245 of file md.c.
References _MD_find_symbol_data(), and MD::section_table.
void* _MD_find_symbol_data (MD_Symbol_Table * table, char * name)
Definition at line 650 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_hash_string(), MD_Symbol::name, MD_Symbol::next_hash, and NULL.
Referenced by _MD_find_entry(), _MD_find_field_decl(), and _MD_find_section().
void _MD_free_entry (MD_Entry * entry)
Definition at line 2704 of file md.c.
References entry, L_free(), MD_delete_field(), MD_Entry_pool, and NULL.
Referenced by _MD_delete_entry(), and _MD_free_section().
void _MD_free_field_decl (MD_Field_Decl * field_decl)
Definition at line 3529 of file md.c.
References MD_Element_Req::desc, MD_Section::field_decl, MD_Field_Decl::field_index, L_free(), MD_Element_Req::link, MD_Field_Decl::max_require_index, MD_Element_Req_pool, MD_Field_Decl_pool, MD_LINK, MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Field_Decl::section, and MD_Element_Req::type.
Referenced by _MD_free_section(), and MD_delete_field_decl().
void _MD_free_section (MD_Section * section)
Definition at line 2353 of file md.c.
References _MD_free_entry(), _MD_free_field_decl(), MD_Section::entry_table, MD_Section::field_decl, MD_Section::field_decl_table, L_free(), MD_delete_symbol_table(), MD_Section_pool, MD_Section::name, and NULL.
Referenced by _MD_delete_section(), and MD_delete_md().
void* _MD_get_block_ptr (MD_Field * field, int index)
Definition at line 5178 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_BLOCK, MD_punt(), MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Block::ptr, MD_Entry::section, MD_Element::type, and MD_Element::value.
int _MD_get_block_size (MD_Field * field, int index)
Definition at line 5145 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_BLOCK, MD_punt(), MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Entry::section, MD_Block::size, MD_Element::type, and MD_Element::value.
double _MD_get_double (MD_Field * field, int index)
Definition at line 4901 of file md.c.
References MD_Element::d, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_DOUBLE, MD_punt(), MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
void* _MD_get_entry_ext (MD_Entry * entry)
Definition at line 2690 of file md.c.
References entry.
int _MD_get_int (MD_Field * field, int index)
Definition at line 4789 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Element::i, MD_Section::md, MD_INT, MD_punt(), MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
MD_Entry* _MD_get_link (MD_Field * field, int index)
Definition at line 5300 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Element::l, MD_Section::md, MD_LINK, MD_punt(), MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
void* _MD_get_section_ext (MD_Section * section)
Definition at line 2339 of file md.c.
References MD_Section::user_ext.
char* _MD_get_string (MD_Field * field, int index)
Definition at line 5014 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_punt(), MD_STRING, MD_type_name, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
int _MD_max_element_index (MD_Field * field)
Definition at line 4690 of file md.c.
References MD_Field::max_element_index.
int _MD_max_field_index (MD_Section * section)
Definition at line 3427 of file md.c.
References MD_Section::max_field_index.
int _MD_num_elements (MD_Field * field)
Definition at line 4675 of file md.c.
References MD_Field::max_element_index.
int _MD_num_entries (MD_Section * section)
Definition at line 2581 of file md.c.
References MD_Section::entry_table, and MD_Symbol_Table::symbol_count.
int _MD_num_field_decls (MD_Section * section)
Definition at line 3414 of file md.c.
References MD_Section::field_decl_table, and MD_Symbol_Table::symbol_count.
int _MD_num_sections (MD * md)
Definition at line 2232 of file md.c.
References MD::section_table, and MD_Symbol_Table::symbol_count.
void _MD_set_block (MD_Field * field, int index, unsigned int size, void * ptr)
Definition at line 5044 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Block::size, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_block_type_checking().
void _MD_set_block_type_checking (MD_Field * field, int index, unsigned int size, void * ptr)
Definition at line 5124 of file md.c.
References _MD_set_block(), and MD_check_setting().
void _MD_set_double (MD_Field * field, int index, double value)
Definition at line 4818 of file md.c.
References MD_Element::b, MD_Element::d, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_DOUBLE, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_double_type_checking().
void _MD_set_double_type_checking (MD_Field * field, int index, double value)
Definition at line 4881 of file md.c.
References _MD_set_double(), and MD_check_setting().
void* _MD_set_entry_ext (MD_Entry * entry, void * ext)
Definition at line 2675 of file md.c.
References entry.
void _MD_set_int (MD_Field * field, int index, int value)
Definition at line 4705 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, MD_Element::i, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_INT, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_int_type_checking().
void _MD_set_int_type_checking (MD_Field * field, int index, int value)
Definition at line 4769 of file md.c.
References _MD_set_int(), and MD_check_setting().
void _MD_set_link (MD_Field * field, int index, MD_Entry * value)
Definition at line 5208 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, MD_Element::l, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_LINK, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_link_type_checking().
void _MD_set_link_type_checking (MD_Field * field, int index, MD_Entry * value)
Definition at line 5280 of file md.c.
References _MD_set_link(), and MD_check_setting().
void* _MD_set_section_ext (MD_Section * section, void * ext)
Definition at line 2324 of file md.c.
References MD_Section::user_ext.
void _MD_set_string (MD_Field * field, int index, char * value)
Definition at line 4931 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_strdup(), MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_string_type_checking().
void _MD_set_string_type_checking (MD_Field * field, int index, char * value)
Definition at line 4994 of file md.c.
References _MD_set_string(), and MD_check_setting().
static MD_Symbol* MD_add_symbol (MD_Symbol_Table * table, char * name, void * data) [static]
Definition at line 461 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_Symbol_Table::head_symbol, L_alloc(), MD_Symbol_Table::md, MD_hash_string(), MD_punt(), MD_resize_symbol_table(), MD_Symbol_pool, MD_Symbol_Table::name, MD_Symbol::name, MD_Symbol::next_hash, MD_Symbol::next_symbol, NULL, MD_Symbol::prev_symbol, MD_Symbol_Table::resize_size, MD_Symbol_Table::symbol_count, MD_Symbol::symbol_id, MD_Symbol::table, and MD_Symbol_Table::tail_symbol.
Referenced by MD_new_entry(), MD_new_field_decl(), and MD_new_section().
int MD_check_md (FILE * out, MD * md)
Definition at line 888 of file md.c.
References _MD_check_section(), MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_Symbol::next_symbol, NULL, and MD::section_table.
static int MD_check_setting (FILE * out, MD_Field * field, int index, char * caller_name) [static]
Definition at line 4558 of file md.c.
References MD_Field::decl, MD_Element_Req::desc, MD_Field::element, MD_Field::entry, MD_Field_Decl::kleene_starred_req, MD_Element::l, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_LINK, MD_type_name, MD_warn(), MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Field_Decl::require, MD_Entry::section, MD_Element_Req::type, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_block_type_checking(), _MD_set_double_type_checking(), _MD_set_int_type_checking(), _MD_set_link_type_checking(), and _MD_set_string_type_checking().
static char* MD_concat_strings (char * string1, char * string2) [static]
Definition at line 237 of file md.c.
References MD_punt(), and NULL.
Referenced by MD_kleene_star_requirement(), and MD_new_section().
void MD_delete_buf (MD_Buf * buf)
Definition at line 964 of file md.c.
References MD_Buf::buf, L_free(), and MD_Buf_pool.
Referenced by MD_read_md().
void MD_delete_element (MD_Field * field, int index)
Definition at line 5326 of file md.c.
References MD_Element::b, MD_Field::element, L_free(), MD_Field::max_element_index, MD_BLOCK, MD_Element_pool, MD_STRING, NULL, MD_Block::ptr, MD_Element::s, MD_Element::type, and MD_Element::value.
void MD_delete_field (MD_Field * field)
Definition at line 4353 of file md.c.
References MD_Element::b, MD_Field::element, L_free(), MD_Field::max_element_index, MD_BLOCK, MD_Element_pool, MD_STRING, NULL, MD_Block::ptr, MD_Element::s, MD_Element::type, and MD_Element::value.
Referenced by _MD_free_entry(), and MD_delete_field_decl().
void MD_delete_field_decl (MD_Field_Decl * field_decl)
Definition at line 3578 of file md.c.
References _MD_free_field_decl(), MD_Symbol::data, entry, MD_Section::entry_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_delete_field(), MD_delete_symbol(), MD_Symbol::next_symbol, NULL, MD_Field_Decl::section, and MD_Field_Decl::symbol.
void MD_delete_md (MD * md)
Definition at line 826 of file md.c.
References _MD_free_section(), _L_Alloc_Pool::allocated, _L_Alloc_Pool::free, L_free(), L_free_alloc_pool(), MD_delete_symbol_table(), MD_Element_pool, MD_Element_Req_pool, MD_Entry_pool, MD_Field_Decl_pool, MD_Field_pool, MD_pool, MD_Section_pool, MD_Symbol_pool, MD_Symbol_Table_pool, MD::name, NULL, and MD::section_table.
void MD_delete_symbol (MD_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 677 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_Symbol_Table::head_symbol, L_free(), MD_Symbol_pool, MD_Symbol::next_hash, MD_Symbol::next_symbol, NULL, MD_Symbol::prev_hash, MD_Symbol::prev_symbol, MD_Symbol_Table::symbol_count, MD_Symbol::table, and MD_Symbol_Table::tail_symbol.
Referenced by _MD_delete_entry(), _MD_delete_section(), and MD_delete_field_decl().
void MD_delete_symbol_table (MD_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 336 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::head_symbol, L_free(), MD_Symbol_pool, MD_Symbol_Table_pool, MD_Symbol_Table::name, MD_Symbol::next_symbol, and NULL.
Referenced by _MD_free_section(), and MD_delete_md().
MD_Entry* MD_first_entry (MD_Section * section)
Definition at line 2605 of file md.c.
References MD_Symbol::data, MD_Section::entry_table, MD_Symbol_Table::head_symbol, and NULL.
Referenced by MD_print_md_declarations().
MD_Field_Decl* MD_first_field_decl (MD_Section * section)
Definition at line 3452 of file md.c.
References MD_Symbol::data, MD_Section::field_decl_table, MD_Symbol_Table::head_symbol, and NULL.
MD_Section* MD_first_section (MD * md)
Definition at line 2255 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, NULL, and MD::section_table.
Referenced by MD_print_md_declarations().
static unsigned int MD_hash_string (char * string) [static]
Definition at line 422 of file md.c.
Referenced by _MD_find_symbol_data(), MD_add_symbol(), and MD_rename_symbol().
void MD_kleene_star_requirement (MD_Field_Decl * field_decl, int element_index)
Definition at line 4149 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::kleene_starred, MD_Field_Decl::kleene_starred_req, MD_Field_Decl::max_require_index, MD_Section::md, MD_concat_strings(), MD_punt(), MD_Section::name, MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Element_Req::require_index, and MD_Field_Decl::section.
Referenced by MD_read_md().
MD_Entry* MD_last_entry (MD_Section * section)
Definition at line 2622 of file md.c.
References MD_Symbol::data, MD_Section::entry_table, NULL, and MD_Symbol_Table::tail_symbol.
MD_Field_Decl* MD_last_field_decl (MD_Section * section)
Definition at line 3469 of file md.c.
References MD_Symbol::data, MD_Section::field_decl_table, NULL, and MD_Symbol_Table::tail_symbol.
MD_Section* MD_last_section (MD * md)
Definition at line 2271 of file md.c.
References MD_Symbol::data, NULL, MD::section_table, and MD_Symbol_Table::tail_symbol.
static int MD_legal_ident (char * ident) [static]
Definition at line 2824 of file md.c.
Referenced by MD_print_entry(), MD_print_entry_template(), and MD_print_md_declarations().
MD_Buf* MD_new_buf ()
Definition at line 915 of file md.c.
References MD_Buf::buf, MD_Buf::buf_size, L_alloc(), MD_Buf_pool, MD_punt(), and NULL.
Referenced by MD_read_md().
static MD_Element_Req* MD_new_element_req (MD_Field_Decl * field_decl, int index, char * caller_name) [static]
Definition at line 3739 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::field_decl, MD_Element_Req::kleene_starred, MD_Field_Decl::kleene_starred_req, L_alloc(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field_Decl::max_require_index, MD_Section::md, MD_Element_Req_pool, MD_punt(), MD_Field_Decl::name, MD_Section::name, NULL, MD_Field_Decl::require, MD_Field_Decl::require_array_size, MD_Element_Req::require_index, and MD_Field_Decl::section.
Referenced by MD_require_block(), MD_require_double(), MD_require_int(), MD_require_link(), MD_require_multi_target_link(), and MD_require_string().
MD_Entry* MD_new_entry (MD_Section * section, char * name)
Definition at line 2499 of file md.c.
References entry, MD_Section::entry_table, MD_Section::field_array_size, L_alloc(), MD_Section::md, MD_add_symbol(), MD_Entry_pool, MD_punt(), MD_strdup(), and NULL.
Referenced by MD_read_md().
MD_Field* MD_new_field (MD_Entry * entry, MD_Field_Decl * decl, int num_elements)
Definition at line 4220 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Field::entry, entry, MD_Field_Decl::field_index, L_alloc(), MD_Field::max_element_index, MD_Field_pool, MD_punt(), MD_resize_element_array(), MD_Field_Decl::name, and NULL.
Referenced by MD_read_md().
MD_Field_Decl* MD_new_field_decl (MD_Section * section, char * name, MD_FIELD_TYPE field_type)
Definition at line 3240 of file md.c.
References MD_Section::field_array_size, MD_Section::field_decl, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Field_Decl::kleene_starred_req, L_alloc(), MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_add_symbol(), MD_Field_Decl_pool, MD_resize_field_arrays(), MD_strdup(), MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Field_Decl::require_array_size, MD_Field_Decl::section, MD_Field_Decl::symbol, and MD_Field_Decl::type.
Referenced by MD_read_md().
MD* MD_new_md (char * name, int num_sections)
Definition at line 772 of file md.c.
References L_alloc(), L_create_alloc_pool(), MD_Element_pool, MD_Element_Req_pool, MD_Entry_pool, MD_Field_Decl_pool, MD_Field_pool, MD_new_symbol_table(), MD_pool, MD_punt(), MD_Section_pool, MD_strdup(), MD_Symbol_pool, MD_Symbol_Table_pool, MD::name, NULL, and MD::section_table.
Referenced by MD_read_md().
MD_Section* MD_new_section (MD * md, char * name, int num_entries, int num_fields)
Definition at line 2166 of file md.c.
References MD_Section::entry_table, MD_Section::field_array_size, MD_Section::field_decl, MD_Section::field_decl_table, L_alloc(), MD_Section::max_field_index, MD_Section::md, MD_add_symbol(), MD_concat_strings(), MD_new_symbol_table(), MD_resize_field_arrays(), MD_Section_pool, MD_strdup(), MD_Section::name, NULL, MD::section_table, MD_Section::symbol, and MD_Section::user_ext.
Referenced by MD_read_md().
static MD_Symbol_Table* MD_new_symbol_table (MD * md, char * name, int expected_size) [static]
Definition at line 265 of file md.c.
References MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol_Table::hash_size, MD_Symbol_Table::head_symbol, L_alloc(), MD_Symbol_Table::md, MD_punt(), MD_strdup(), MD_Symbol_Table_pool, MD_Symbol_Table::name, NULL, MD_Symbol_Table::resize_size, MD_Symbol_Table::symbol_count, and MD_Symbol_Table::tail_symbol.
Referenced by MD_new_md(), and MD_new_section().
MD_Entry* MD_next_entry (MD_Entry * entry)
Definition at line 2639 of file md.c.
References MD_Symbol::data, entry, and NULL.
Referenced by MD_print_md_declarations().
MD_Field_Decl* MD_next_field_decl (MD_Field_Decl * field_decl)
Definition at line 3486 of file md.c.
References MD_Symbol::data, MD_Symbol::next_symbol, NULL, and MD_Field_Decl::symbol.
MD_Section* MD_next_section (MD_Section * section)
Definition at line 2288 of file md.c.
References MD_Symbol::data, MD_Symbol::next_symbol, NULL, and MD_Section::symbol.
Referenced by MD_print_md_declarations().
MD_Entry* MD_prev_entry (MD_Entry * entry)
Definition at line 2656 of file md.c.
References MD_Symbol::data, entry, and NULL.
MD_Field_Decl* MD_prev_field_decl (MD_Field_Decl * field_decl)
Definition at line 3503 of file md.c.
References MD_Symbol::data, NULL, MD_Symbol::prev_symbol, and MD_Field_Decl::symbol.
MD_Section* MD_prev_section (MD_Section * section)
Definition at line 2305 of file md.c.
References MD_Symbol::data, NULL, MD_Symbol::prev_symbol, and MD_Section::symbol.
void MD_print_entry (FILE * out, MD_Entry * entry, int page_width)
Definition at line 2848 of file md.c.
References MD_Element::b, MD_Element::d, MD_Symbol::data, MD_Field::element, entry, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_Element::i, MD_Element::l, MD_Field::max_element_index, MD_BLOCK, MD_DOUBLE, MD_INT, MD_legal_ident(), MD_LINK, MD_punt(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Symbol::next_symbol, NULL, MD_Block::ptr, MD_Element::s, MD_Block::size, MD_Element::type, and MD_Element::value.
Referenced by MD_print_section().
void MD_print_entry_template (FILE * out, MD_Entry * entry)
Definition at line 3190 of file md.c.
References entry, and MD_legal_ident().
Referenced by MD_print_section_template().
void MD_print_field_decl (FILE * out, MD_Field_Decl * field_decl, int page_width)
Definition at line 3620 of file md.c.
References MD_Element_Req::desc, MD_Field_Decl::max_require_index, MD_Section::md, MD_OPTIONAL_FIELD, MD_punt(), MD_REQUIRED_FIELD, MD_Field_Decl::name, MD_Field_Decl::require, MD_Field_Decl::section, and MD_Field_Decl::type.
Referenced by MD_print_section().
void MD_print_md (FILE * out, MD * md, int page_width)
Definition at line 1985 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_print_section(), MD::name, MD_Symbol::next_symbol, NULL, and MD::section_table.
void MD_print_md_declarations (FILE * out, MD * md, int page_width)
Definition at line 2024 of file md.c.
References entry, MD_first_entry(), MD_first_section(), MD_legal_ident(), MD_next_entry(), MD_next_section(), MD::name, MD_Section::name, MD_Entry::name, and NULL.
void MD_print_md_template (FILE * out, MD * md)
Definition at line 2127 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_print_section_template(), MD::name, MD_Symbol::next_symbol, NULL, and MD::section_table.
void MD_print_section (FILE * out, MD_Section * section, int page_width)
Definition at line 2439 of file md.c.
References MD_Symbol::data, entry, MD_Section::entry_table, MD_Section::field_decl_table, MD_Symbol_Table::head_symbol, MD_print_entry(), MD_print_field_decl(), MD_Section::name, MD_Symbol::next_symbol, and NULL.
Referenced by MD_print_md().
void MD_print_section_template (FILE * out, MD_Section * section)
Definition at line 2474 of file md.c.
References MD_Symbol::data, entry, MD_Section::entry_table, MD_Symbol_Table::head_symbol, MD_print_entry_template(), MD_Section::name, MD_Symbol::next_symbol, and NULL.
Referenced by MD_print_md_template().
static void MD_punt (MD * md, char * fmt, ...) [static]
Definition at line 151 of file md.c.
References MD::name, and NULL.
Referenced by _MD_find_field(), _MD_get_block_ptr(), _MD_get_block_size(), _MD_get_double(), _MD_get_int(), _MD_get_link(), _MD_get_string(), _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), MD_add_symbol(), MD_concat_strings(), MD_kleene_star_requirement(), MD_new_buf(), MD_new_element_req(), MD_new_entry(), MD_new_field(), MD_new_md(), MD_new_symbol_table(), MD_print_entry(), MD_print_field_decl(), MD_read_block(), MD_read_double(), MD_read_int(), MD_read_md(), MD_read_nl(), MD_read_sp(), MD_read_string(), MD_rename_symbol(), MD_require_link(), MD_require_multi_target_link(), MD_resize_buf(), MD_resize_element_array(), MD_resize_field_arrays(), MD_resize_symbol_table(), MD_strdup(), and MD_write_md().
void MD_read_block (FILE * in, unsigned int block_size, MD_Buf * value_buf)
Definition at line 1193 of file md.c.
References MD_Buf::buf, MD_Buf::buf_size, MD_punt(), MD_resize_buf(), and NULL.
Referenced by MD_read_md().
void MD_read_consume_comments (FILE * in)
Definition at line 974 of file md.c.
Referenced by MD_read_md().
double MD_read_double (FILE * in, MD_Buf * value_buf)
Definition at line 1080 of file md.c.
References MD_Buf::buf, MD_Buf::buf_size, MD_punt(), MD_resize_buf(), and NULL.
Referenced by MD_read_md().
int MD_read_int (FILE * in)
Definition at line 1006 of file md.c.
References MD_punt(), and NULL.
Referenced by MD_read_md().
MD* MD_read_md (FILE * in, char * name)
Definition at line 1251 of file md.c.
References MD_Buf::buf, entry, L_create_alloc_pool(), L_free_alloc_pool(), MD_Buf_pool, MD_delete_buf(), MD_kleene_star_requirement(), MD_new_buf(), MD_new_entry(), MD_new_field(), MD_new_field_decl(), MD_new_md(), MD_new_section(), MD_OPTIONAL_FIELD, MD_punt(), MD_read_block(), MD_read_consume_comments(), MD_read_double(), MD_read_int(), MD_read_nl(), MD_read_sp(), MD_read_string(), MD_require_block(), MD_require_double(), MD_require_int(), MD_require_multi_target_link(), MD_require_string(), MD_REQUIRED_FIELD, MD_set_block, MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_Section::name, and NULL.
void MD_read_nl (FILE * in)
Definition at line 1220 of file md.c.
References MD_punt(), and NULL.
Referenced by MD_read_md().
void MD_read_sp (FILE * in)
Definition at line 1235 of file md.c.
References MD_punt(), and NULL.
Referenced by MD_read_md().
void MD_read_string (FILE * in, MD_Buf * value_buf)
Definition at line 1146 of file md.c.
References MD_Buf::buf, MD_Buf::buf_size, MD_punt(), MD_resize_buf(), and NULL.
Referenced by MD_read_md().
void MD_rename_entry (MD_Entry * entry, char * new_name)
Definition at line 2556 of file md.c.
References entry, MD_rename_symbol(), and MD_strdup().
static void MD_rename_symbol (MD_Symbol * symbol, char * new_name) [static]
Definition at line 550 of file md.c.
References MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_Symbol_Table::md, MD_hash_string(), MD_punt(), MD_Symbol_Table::name, MD_Symbol::name, MD_Symbol::next_hash, NULL, MD_Symbol::prev_hash, and MD_Symbol::table.
Referenced by MD_rename_entry().
void MD_require_block (MD_Field_Decl * field_decl, int element_index)
Definition at line 3937 of file md.c.
References MD_Element_Req::desc, MD_BLOCK, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_double (MD_Field_Decl * field_decl, int element_index)
Definition at line 3883 of file md.c.
References MD_Element_Req::desc, MD_DOUBLE, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_int (MD_Field_Decl * field_decl, int element_index)
Definition at line 3856 of file md.c.
References MD_Element_Req::desc, MD_INT, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_link (MD_Field_Decl * field_decl, int element_index, MD_Section * section)
Definition at line 3966 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Section::md, MD_LINK, MD_new_element_req(), MD_punt(), MD_Section::name, NULL, MD_Field_Decl::section, and MD_Element_Req::type.
void MD_require_multi_target_link (MD_Field_Decl * field_decl, int element_index, int section_array_size, MD_Section ** section_array)
Definition at line 4037 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Section::md, MD_LINK, MD_new_element_req(), MD_punt(), MD_Section::name, NULL, MD_Field_Decl::section, and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_string (MD_Field_Decl * field_decl, int element_index)
Definition at line 3910 of file md.c.
References MD_Element_Req::desc, MD_new_element_req(), MD_strdup(), MD_STRING, and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_resize_buf (MD_Buf * buf)
Definition at line 936 of file md.c.
References MD_Buf::buf, MD_Buf::buf_size, MD_punt(), and NULL.
Referenced by MD_read_block(), MD_read_double(), and MD_read_string().
static void MD_resize_element_array (MD_Field * field, int max_index) [static]
Definition at line 4274 of file md.c.
References MD_Field::element, MD_Field::element_array_size, MD_Field::entry, MD_Field::max_element_index, MD_Section::md, MD_punt(), NULL, and MD_Entry::section.
Referenced by _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), and MD_new_field().
static void MD_resize_field_arrays (MD_Section * section, int max_index) [static]
Definition at line 3303 of file md.c.
References MD_Symbol::data, entry, MD_Section::entry_table, MD_Section::field_array_size, MD_Section::field_decl, MD_Symbol_Table::head_symbol, MD_Section::max_field_index, MD_Section::md, MD_punt(), MD_Symbol::next_symbol, and NULL.
Referenced by MD_new_field_decl(), and MD_new_section().
static void MD_resize_symbol_table (MD_Symbol_Table * table) [static]
Definition at line 365 of file md.c.
References MD_Symbol_Table::hash_size, MD_Symbol::hash_val, MD_Symbol_Table::head_symbol, MD_Symbol_Table::md, MD_punt(), MD_Symbol::next_hash, MD_Symbol::next_symbol, NULL, and MD_Symbol::prev_hash.
Referenced by MD_add_symbol().
static char* MD_strdup (char * string) [static]
Definition at line 204 of file md.c.
References MD_punt(), and NULL.
Referenced by _MD_set_string(), MD_new_entry(), MD_new_field_decl(), MD_new_md(), MD_new_section(), MD_new_symbol_table(), MD_rename_entry(), MD_require_block(), MD_require_double(), MD_require_int(), and MD_require_string().
static void MD_warn (FILE * out, char * fmt, ...) [static]
Definition at line 179 of file md.c.
Referenced by _MD_check_entry(), _MD_check_field(), and MD_check_setting().
void MD_write_md (FILE * out, MD * md)
Definition at line 1624 of file md.c.
References MD_Element::b, MD_Element::d, MD_Symbol::data, MD_Field::element, entry, MD_Section::entry_table, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_Element::i, MD_Field_Decl::kleene_starred_req, MD_Element::l, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_BLOCK, MD_DOUBLE, MD_INT, MD_LINK, MD_OPTIONAL_FIELD, MD_punt(), MD_REQUIRED_FIELD, MD_STRING, MD_Section::name, MD_Field_Decl::name, MD_Symbol::next_symbol, NULL, MD_Block::ptr, MD_Field_Decl::require, MD_Element::s, MD::section_table, MD_Block::size, MD_Entry::symbol, MD_Symbol_Table::symbol_count, MD_Symbol::symbol_id, MD_Field_Decl::type, MD_Element_Req::type, MD_Element::type, and MD_Element::value.
Variable Documentation
L_Alloc_Pool* MD_Buf_pool = NULL [static]
Definition at line 116 of file md.c.
Referenced by MD_delete_buf(), MD_new_buf(), and MD_read_md().
L_Alloc_Pool* MD_Element_pool = NULL [static]
Definition at line 127 of file md.c.
Referenced by _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), MD_delete_element(), MD_delete_field(), MD_delete_md(), and MD_new_md().
L_Alloc_Pool* MD_Element_Req_pool = NULL [static]
Definition at line 125 of file md.c.
Referenced by _MD_free_field_decl(), MD_delete_md(), MD_new_element_req(), and MD_new_md().
L_Alloc_Pool* MD_Entry_pool = NULL [static]
Definition at line 123 of file md.c.
Referenced by _MD_free_entry(), MD_delete_md(), MD_new_entry(), and MD_new_md().
L_Alloc_Pool* MD_Field_Decl_pool = NULL [static]
Definition at line 124 of file md.c.
Referenced by _MD_free_field_decl(), MD_delete_md(), MD_new_field_decl(), and MD_new_md().
L_Alloc_Pool* MD_Field_pool = NULL [static]
Definition at line 126 of file md.c.
Referenced by MD_delete_md(), MD_new_field(), and MD_new_md().
L_Alloc_Pool* MD_pool = NULL [static]
Definition at line 119 of file md.c.
Referenced by MD_delete_md(), and MD_new_md().
L_Alloc_Pool* MD_Section_pool = NULL [static]
Definition at line 122 of file md.c.
Referenced by _MD_free_section(), MD_delete_md(), MD_new_md(), and MD_new_section().
L_Alloc_Pool* MD_Symbol_pool = NULL [static]
Definition at line 121 of file md.c.
Referenced by MD_add_symbol(), MD_delete_md(), MD_delete_symbol(), MD_delete_symbol_table(), and MD_new_md().
L_Alloc_Pool* MD_Symbol_Table_pool = NULL [static]
Definition at line 120 of file md.c.
Referenced by MD_delete_md(), MD_delete_symbol_table(), MD_new_md(), and MD_new_symbol_table().
char* MD_type_name[] [static]
Initial value:
 { "(UNDEFINED)", "INT", "DOUBLE", "STRING",
  "LINK", "BLOCK", "(UNDEFINED)"
}
Definition at line 130 of file md.c.
Referenced by _MD_check_field(), _MD_get_block_ptr(), _MD_get_block_size(), _MD_get_double(), _MD_get_int(), _MD_get_link(), _MD_get_string(), and MD_check_setting().