md.h File Reference
#include <stdio.h>
Data Structures
struct MD_Symbol
struct MD_Symbol_Table
struct MD
struct MD_Section
struct MD_Element_Req
struct MD_Field_Decl
struct MD_Entry
struct MD_Block
struct MD_Element
struct MD_Field
Defines
#define MD_INT 1
#define MD_DOUBLE 2
#define MD_STRING 3
#define MD_LINK 4
#define MD_BLOCK 5
#define MD_OPTIONAL_ELEMENTS -1
#define MD_num_sections(md) ((md) $\rightarrow$ section_table $\rightarrow$ symbol_count)
#define MD_find_section(md, name) ((MD_Section *)_MD_find_symbol_data((md) $\rightarrow$ section_table, name))
#define MD_delete_section(section)
#define MD_num_entries(section) ((section) $\rightarrow$ entry_table $\rightarrow$ symbol_count)
#define MD_find_entry(section, name) ((MD_Entry *)_MD_find_symbol_data((section) $\rightarrow$ entry_table, name))
#define MD_delete_entry(entry)
#define MD_num_field_decls(section) ((section) $\rightarrow$ field_decl_table $\rightarrow$ symbol_count)
#define MD_max_field_index(section) ((section) $\rightarrow$ max_field_index)
#define MD_find_field_decl(section, name)
#define MD_find_field(entry, field_decl) ((entry) $\rightarrow$ field[(field_decl) $\rightarrow$ field_index])
#define MD_num_elements(field) ((field) $\rightarrow$ max_element_index + 1)
#define MD_max_element_index(field) ((field) $\rightarrow$ max_element_index)
#define MD_set_int(field, index, value) _MD_set_int(field, index, value)
#define MD_get_int(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.i)
#define MD_set_double(field, index, value) _MD_set_double(field, index, value)
#define MD_get_double(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.d)
#define MD_set_string(field, index, value) _MD_set_string(field, index, value)
#define MD_get_string(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.s)
#define MD_set_block(field, index, size, ptr) _MD_set_block(field, index, size, ptr)
#define MD_get_block_size(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.b.size)
#define MD_get_block_ptr(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.b.ptr)
#define MD_set_link(field, index, value) _MD_set_link(field, index, value)
#define MD_get_link(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.l)
#define MD_set_section_ext(section, ext) ((section) $\rightarrow$ user_ext = (void *)(ext))
#define MD_get_section_ext(section) ((section) $\rightarrow$ user_ext)
#define MD_set_entry_ext(entry, ext) ((entry) $\rightarrow$ user_ext = (void *)(ext))
#define MD_get_entry_ext(entry) ((entry) $\rightarrow$ user_ext)
#define MD_check_section(out, section) _MD_check_section(out, section, `MD_check_section`)
#define MD_check_entry(out, entry) _MD_check_entry(out, entry, `MD_check_entry`)
#define MD_check_field(out, field) _MD_check_field(out, field, `MD_check_field`)
Enumerations
enum MD_FIELD_TYPE { MD_REQUIRED_FIELD = 1,
MD_OPTIONAL_FIELD = 2
 }
Functions
MD * MD_new_md (char *name, int num_sections)
int MD_check_md (FILE *out, MD *md)
void MD_delete_md (MD *md)
MD_Section * MD_new_section (MD *md, char *name, int num_entries, int num_fields)
MD_Section * MD_first_section (MD *md)
MD_Section * MD_last_section (MD *md)
MD_Section * MD_next_section (MD_Section *section)
MD_Section * MD_prev_section (MD_Section *section)
MD_Field_Decl * MD_new_field_decl (MD_Section *section, char *name, MD_FIELD_TYPE field_type)
MD_Field_Decl * MD_first_field_decl (MD_Section *section)
MD_Field_Decl * MD_last_field_decl (MD_Section *section)
MD_Field_Decl * MD_next_field_decl (MD_Field_Decl *field_decl)
MD_Field_Decl * MD_prev_field_decl (MD_Field_Decl *field_decl)
void MD_require_int (MD_Field_Decl *field_decl, int element_index)
void MD_require_double (MD_Field_Decl *field_decl, int element_index)
void MD_require_string (MD_Field_Decl *field_decl, int element_index)
void MD_require_block (MD_Field_Decl *field_decl, int element_index)
void MD_require_link (MD_Field_Decl *field_decl, int element_index, MD_Section *section)
void MD_require_multi_target_link (MD_Field_Decl *field_decl, int element_index, int section_array_size, MD_Section **section_array)
void MD_kleene_star_requirement (MD_Field_Decl *field_decl, int element_index)
MD_Entry * MD_new_entry (MD_Section *section, char *name)
void MD_rename_entry (MD_Entry *entry, char *new_name)
MD_Entry * MD_first_entry (MD_Section *section)
MD_Entry * MD_last_entry (MD_Section *section)
MD_Entry * MD_next_entry (MD_Entry *entry)
MD_Entry * MD_prev_entry (MD_Entry *entry)
MD_Field * MD_new_field (MD_Entry *entry, MD_Field_Decl *decl, int num_elements)
void MD_delete_field (MD_Field *field)
void MD_delete_field_decl (MD_Field_Decl *field_decl)
void MD_delete_element (MD_Field *field, int index)
MD * MD_read_md (FILE *in, char *name)
void MD_write_md (FILE *out, MD *md)
void MD_print_md (FILE *out, MD *md, int page_width)
void MD_print_md_declarations (FILE *out, MD *md, int page_width)
void MD_print_md_template (FILE *out, MD *md)
void MD_print_section (FILE *out, MD_Section *section, int page_width)
void MD_print_section_template (FILE *out, MD_Section *section)
void MD_print_field_decl (FILE *out, MD_Field_Decl *field_decl, int page_width)
void MD_print_entry (FILE *out, MD_Entry *entry, int page_width)
void MD_print_entry_template (FILE *out, MD_Entry *entry)
void MD_delete_symbol (MD_Symbol *symbol, void(*free_routine)(void *))
void * _MD_find_symbol_data (MD_Symbol_Table *table, char *name)
int _MD_num_sections (MD *md)
MD_Section * _MD_find_section (MD *md, char *name)
void * _MD_set_section_ext (MD_Section *section, void *ext)
void * _MD_get_section_ext (MD_Section *section)
void _MD_free_section (MD_Section *section)
void _MD_delete_section (MD_Section *section)
int _MD_check_section (FILE *out, MD_Section *section, char *caller_name)
int _MD_num_entries (MD_Section *section)
MD_Entry * _MD_find_entry (MD_Section *section, char *name)
void * _MD_set_entry_ext (MD_Entry *entry, void *ext)
void * _MD_get_entry_ext (MD_Entry *entry)
void _MD_free_entry (MD_Entry *entry)
void _MD_delete_entry (MD_Entry *entry)
int _MD_check_entry (FILE *out, MD_Entry *entry, char *caller_name)
MD_Field_Decl * _MD_find_field_decl (MD_Section *section, char *name)
void _MD_free_field_decl (MD_Field_Decl *field_decl)
int _MD_num_field_decls (MD_Section *section)
int _MD_max_field_index (MD_Section *section)
MD_Field * _MD_find_field (MD_Entry *entry, MD_Field_Decl *field_decl)
int _MD_check_field (FILE *out, MD_Field *field, char *caller_name)
int _MD_num_elements (MD_Field *field)
int _MD_max_element_index (MD_Field *field)
void _MD_set_int (MD_Field *field, int index, int value)
void _MD_set_int_type_checking (MD_Field *field, int index, int value)
int _MD_get_int (MD_Field *field, int index)
void _MD_set_double (MD_Field *field, int index, double value)
void _MD_set_double_type_checking (MD_Field *field, int index, double value)
double _MD_get_double (MD_Field *field, int index)
void _MD_set_string (MD_Field *field, int index, char *value)
void _MD_set_string_type_checking (MD_Field *field, int index, char *value)
char * _MD_get_string (MD_Field *field, int index)
void _MD_set_block (MD_Field *field, int index, unsigned int size, void *ptr)
void _MD_set_block_type_checking (MD_Field *field, int index, unsigned int size, void *ptr)
int _MD_get_block_size (MD_Field *field, int index)
void * _MD_get_block_ptr (MD_Field *field, int index)
void _MD_set_link (MD_Field *field, int index, MD_Entry *value)
void _MD_set_link_type_checking (MD_Field *field, int index, MD_Entry *value)
MD_Entry * _MD_get_link (MD_Field *field, int index)
Define Documentation
#define MD_BLOCK 5
Definition at line 109 of file md.h.
Referenced by _MD_get_block_ptr(), _MD_get_block_size(), _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), MD_delete_element(), MD_delete_field(), MD_print_entry(), MD_require_block(), and MD_write_md().
#define MD_check_entry(out, entry) _MD_check_entry(out, entry, `MD_check_entry`)
Definition at line 458 of file md.h.
#define MD_check_field(out, field) _MD_check_field(out, field, `MD_check_field`)
Definition at line 460 of file md.h.
#define MD_check_section(out, section) _MD_check_section(out, section, `MD_check_section`)
Definition at line 456 of file md.h.
#define MD_delete_entry(entry)
Value:
(MD_delete_symbol(((MD_Entry *)(entry))->symbol, \
                              (void (*)(void *))_MD_free_entry))
Definition at line 360 of file md.h.
#define MD_delete_section(section)
Value:
(MD_delete_symbol(((MD_Section *)(section))->symbol, \
                              (void (*)(void *))_MD_free_section))
Definition at line 351 of file md.h.
#define MD_DOUBLE 2
Definition at line 106 of file md.h.
Referenced by _MD_get_double(), _MD_set_double(), MD_print_entry(), MD_require_double(), and MD_write_md().
#define MD_find_entry(section, name) ((MD_Entry *)_MD_find_symbol_data((section) $\rightarrow$ entry_table, name))
Definition at line 357 of file md.h.
#define MD_find_field(entry, field_decl) ((entry) $\rightarrow$ field[(field_decl) $\rightarrow$ field_index])
Definition at line 373 of file md.h.
#define MD_find_field_decl(section, name)
Value:
((MD_Field_Decl *)_MD_find_symbol_data((section)->field_decl_table, \
                                                 name))
Definition at line 369 of file md.h.
#define MD_find_section(md, name) ((MD_Section *)_MD_find_symbol_data((md) $\rightarrow$ section_table, name))
Definition at line 347 of file md.h.
#define MD_get_block_ptr(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.b.ptr)
Definition at line 392 of file md.h.
#define MD_get_block_size(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.b.size)
Definition at line 390 of file md.h.
#define MD_get_double(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.d)
Definition at line 383 of file md.h.
#define MD_get_entry_ext(entry) ((entry) $\rightarrow$ user_ext)
Definition at line 402 of file md.h.
#define MD_get_int(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.i)
Definition at line 380 of file md.h.
#define MD_get_link(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.l)
Definition at line 396 of file md.h.
#define MD_get_section_ext(section) ((section) $\rightarrow$ user_ext)
Definition at line 399 of file md.h.
#define MD_get_string(field, index) ((field) $\rightarrow$ element[index] $\rightarrow$ value.s)
Definition at line 386 of file md.h.
#define MD_INT 1
Definition at line 105 of file md.h.
Referenced by _MD_get_int(), _MD_set_int(), MD_print_entry(), MD_require_int(), and MD_write_md().
#define MD_LINK 4
Definition at line 108 of file md.h.
Referenced by _MD_check_field(), _MD_free_field_decl(), _MD_get_link(), _MD_set_link(), MD_check_setting(), MD_print_entry(), MD_require_link(), MD_require_multi_target_link(), and MD_write_md().
#define MD_max_element_index(field) ((field) $\rightarrow$ max_element_index)
Definition at line 377 of file md.h.
#define MD_max_field_index(section) ((section) $\rightarrow$ max_field_index)
Definition at line 367 of file md.h.
#define MD_num_elements(field) ((field) $\rightarrow$ max_element_index + 1)
Definition at line 376 of file md.h.
#define MD_num_entries(section) ((section) $\rightarrow$ entry_table $\rightarrow$ symbol_count)
Definition at line 355 of file md.h.
#define MD_num_field_decls(section) ((section) $\rightarrow$ field_decl_table $\rightarrow$ symbol_count)
Definition at line 364 of file md.h.
#define MD_num_sections(md) ((md) $\rightarrow$ section_table $\rightarrow$ symbol_count)
Definition at line 346 of file md.h.
#define MD_OPTIONAL_ELEMENTS -1
Definition at line 119 of file md.h.
#define MD_set_block(field, index, size, ptr) _MD_set_block(field, index, size, ptr)
Definition at line 388 of file md.h.
Referenced by MD_read_md().
#define MD_set_double(field, index, value) _MD_set_double(field, index, value)
Definition at line 382 of file md.h.
Referenced by MD_read_md().
#define MD_set_entry_ext(entry, ext) ((entry) $\rightarrow$ user_ext = (void *)(ext))
Definition at line 401 of file md.h.
#define MD_set_int(field, index, value) _MD_set_int(field, index, value)
Definition at line 379 of file md.h.
Referenced by MD_read_md().
#define MD_set_link(field, index, value) _MD_set_link(field, index, value)
Definition at line 395 of file md.h.
Referenced by MD_read_md().
#define MD_set_section_ext(section, ext) ((section) $\rightarrow$ user_ext = (void *)(ext))
Definition at line 398 of file md.h.
#define MD_set_string(field, index, value) _MD_set_string(field, index, value)
Definition at line 385 of file md.h.
Referenced by MD_read_md().
#define MD_STRING 3
Definition at line 107 of file md.h.
Referenced by _MD_get_string(), _MD_set_block(), _MD_set_double(), _MD_set_int(), _MD_set_link(), _MD_set_string(), MD_delete_element(), MD_delete_field(), MD_print_entry(), MD_require_string(), and MD_write_md().
Enumeration Type Documentation
enum MD_FIELD_TYPE
Enumerator:
MD_REQUIRED_FIELD
MD_OPTIONAL_FIELD
Definition at line 112 of file md.h.
Function Documentation
int _MD_check_entry (FILE * out, MD_Entry * entry, char * caller_name)
Definition at line 2767 of file md.c.
References _MD_check_field(), entry, MD_Section::field_decl, MD_Section::max_field_index, MD_REQUIRED_FIELD, MD_warn(), MD_Field_Decl::name, MD_Section::name, NULL, and MD_Field_Decl::type.
Referenced by _MD_check_section().
int _MD_check_field (FILE * out, MD_Field * field, char * caller_name)
Definition at line 4414 of file md.c.
References MD_Field::decl, MD_Element_Req::desc, MD_Field::element, MD_Field::entry, entry, MD_Field_Decl::kleene_starred_req, MD_Element::l, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_LINK, MD_type_name, MD_warn(), MD_Entry::name, MD_Field_Decl::name, MD_Section::name, NULL, MD_Field_Decl::require, MD_Entry::section, MD_Element_Req::type, MD_Element::type, and MD_Element::value.
Referenced by _MD_check_entry().
int _MD_check_section (FILE * out, MD_Section * section, char * caller_name)
Definition at line 2412 of file md.c.
References _MD_check_entry(), MD_Symbol::data, entry, MD_Section::entry_table, MD_Symbol_Table::head_symbol, MD_Symbol::next_symbol, and NULL.
Referenced by MD_check_md().
void _MD_delete_entry (MD_Entry * entry)
Definition at line 2745 of file md.c.
References _MD_free_entry(), entry, and MD_delete_symbol().
void _MD_delete_section (MD_Section * section)
Definition at line 2389 of file md.c.
References _MD_free_section(), MD_delete_symbol(), and MD_Section::symbol.
MD_Entry* _MD_find_entry (MD_Section * section, char * name)
Definition at line 2594 of file md.c.
References _MD_find_symbol_data(), and MD_Section::entry_table.
MD_Field* _MD_find_field (MD_Entry * entry, MD_Field_Decl * field_decl)
Definition at line 4331 of file md.c.
References entry, MD_Field_Decl::field_index, MD_punt(), MD_Section::name, MD_Field_Decl::name, and MD_Field_Decl::section.
MD_Field_Decl* _MD_find_field_decl (MD_Section * section, char * name)
Definition at line 3440 of file md.c.
References _MD_find_symbol_data(), and MD_Section::field_decl_table.
MD_Section* _MD_find_section (MD * md, char * name)
Definition at line 2245 of file md.c.
References _MD_find_symbol_data(), and MD::section_table.
void* _MD_find_symbol_data (MD_Symbol_Table * table, char * name)
Definition at line 650 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_hash_string(), MD_Symbol::name, MD_Symbol::next_hash, and NULL.
Referenced by _MD_find_entry(), _MD_find_field_decl(), and _MD_find_section().
void _MD_free_entry (MD_Entry * entry)
Definition at line 2704 of file md.c.
References entry, L_free(), MD_delete_field(), MD_Entry_pool, and NULL.
Referenced by _MD_delete_entry(), and _MD_free_section().
void _MD_free_field_decl (MD_Field_Decl * field_decl)
Definition at line 3529 of file md.c.
References MD_Element_Req::desc, MD_Section::field_decl, MD_Field_Decl::field_index, L_free(), MD_Element_Req::link, MD_Field_Decl::max_require_index, MD_Element_Req_pool, MD_Field_Decl_pool, MD_LINK, MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Field_Decl::section, and MD_Element_Req::type.
Referenced by _MD_free_section(), and MD_delete_field_decl().
void _MD_free_section (MD_Section * section)
Definition at line 2353 of file md.c.
References _MD_free_entry(), _MD_free_field_decl(), MD_Section::entry_table, MD_Section::field_decl, MD_Section::field_decl_table, L_free(), MD_delete_symbol_table(), MD_Section_pool, MD_Section::name, and NULL.
Referenced by _MD_delete_section(), and MD_delete_md().
void* _MD_get_block_ptr (MD_Field * field, int index)
Definition at line 5178 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_BLOCK, MD_punt(), MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Block::ptr, MD_Entry::section, MD_Element::type, and MD_Element::value.
int _MD_get_block_size (MD_Field * field, int index)
Definition at line 5145 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_BLOCK, MD_punt(), MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Entry::section, MD_Block::size, MD_Element::type, and MD_Element::value.
double _MD_get_double (MD_Field * field, int index)
Definition at line 4901 of file md.c.
References MD_Element::d, MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_DOUBLE, MD_punt(), MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
void* _MD_get_entry_ext (MD_Entry * entry)
Definition at line 2690 of file md.c.
References entry.
int _MD_get_int (MD_Field * field, int index)
Definition at line 4789 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Element::i, MD_Section::md, MD_INT, MD_punt(), MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
MD_Entry* _MD_get_link (MD_Field * field, int index)
Definition at line 5300 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Element::l, MD_Section::md, MD_LINK, MD_punt(), MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Entry::section, MD_Element::type, and MD_Element::value.
void* _MD_get_section_ext (MD_Section * section)
Definition at line 2339 of file md.c.
References MD_Section::user_ext.
char* _MD_get_string (MD_Field * field, int index)
Definition at line 5014 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::entry, MD_Section::md, MD_punt(), MD_STRING, MD_type_name, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
int _MD_max_element_index (MD_Field * field)
Definition at line 4690 of file md.c.
References MD_Field::max_element_index.
int _MD_max_field_index (MD_Section * section)
Definition at line 3427 of file md.c.
References MD_Section::max_field_index.
int _MD_num_elements (MD_Field * field)
Definition at line 4675 of file md.c.
References MD_Field::max_element_index.
int _MD_num_entries (MD_Section * section)
Definition at line 2581 of file md.c.
References MD_Section::entry_table, and MD_Symbol_Table::symbol_count.
int _MD_num_field_decls (MD_Section * section)
Definition at line 3414 of file md.c.
References MD_Section::field_decl_table, and MD_Symbol_Table::symbol_count.
int _MD_num_sections (MD * md)
Definition at line 2232 of file md.c.
References MD::section_table, and MD_Symbol_Table::symbol_count.
void _MD_set_block (MD_Field * field, int index, unsigned int size, void * ptr)
Definition at line 5044 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Block::size, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_block_type_checking().
void _MD_set_block_type_checking (MD_Field * field, int index, unsigned int size, void * ptr)
Definition at line 5124 of file md.c.
References _MD_set_block(), and MD_check_setting().
void _MD_set_double (MD_Field * field, int index, double value)
Definition at line 4818 of file md.c.
References MD_Element::b, MD_Element::d, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_DOUBLE, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_double_type_checking().
void _MD_set_double_type_checking (MD_Field * field, int index, double value)
Definition at line 4881 of file md.c.
References _MD_set_double(), and MD_check_setting().
void* _MD_set_entry_ext (MD_Entry * entry, void * ext)
Definition at line 2675 of file md.c.
References entry.
void _MD_set_int (MD_Field * field, int index, int value)
Definition at line 4705 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, MD_Element::i, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_INT, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_int_type_checking().
void _MD_set_int_type_checking (MD_Field * field, int index, int value)
Definition at line 4769 of file md.c.
References _MD_set_int(), and MD_check_setting().
void _MD_set_link (MD_Field * field, int index, MD_Entry * value)
Definition at line 5208 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, MD_Element::l, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_LINK, MD_punt(), MD_resize_element_array(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_link_type_checking().
void _MD_set_link_type_checking (MD_Field * field, int index, MD_Entry * value)
Definition at line 5280 of file md.c.
References _MD_set_link(), and MD_check_setting().
void* _MD_set_section_ext (MD_Section * section, void * ext)
Definition at line 2324 of file md.c.
References MD_Section::user_ext.
void _MD_set_string (MD_Field * field, int index, char * value)
Definition at line 4931 of file md.c.
References MD_Element::b, MD_Field::decl, MD_Field::element, MD_Field::element_array_size, MD_Element::element_index, MD_Field::entry, MD_Element::field, L_alloc(), MD_Field::max_element_index, MD_Section::md, MD_BLOCK, MD_Element_pool, MD_punt(), MD_resize_element_array(), MD_strdup(), MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Block::ptr, MD_Element::s, MD_Entry::section, MD_Element::type, and MD_Element::value.
Referenced by _MD_set_string_type_checking().
void _MD_set_string_type_checking (MD_Field * field, int index, char * value)
Definition at line 4994 of file md.c.
References _MD_set_string(), and MD_check_setting().
int MD_check_md (FILE * out, MD * md)
Definition at line 888 of file md.c.
References _MD_check_section(), MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_Symbol::next_symbol, NULL, and MD::section_table.
void MD_delete_element (MD_Field * field, int index)
Definition at line 5326 of file md.c.
References MD_Element::b, MD_Field::element, L_free(), MD_Field::max_element_index, MD_BLOCK, MD_Element_pool, MD_STRING, NULL, MD_Block::ptr, MD_Element::s, MD_Element::type, and MD_Element::value.
void MD_delete_field (MD_Field * field)
Definition at line 4353 of file md.c.
References MD_Element::b, MD_Field::element, L_free(), MD_Field::max_element_index, MD_BLOCK, MD_Element_pool, MD_STRING, NULL, MD_Block::ptr, MD_Element::s, MD_Element::type, and MD_Element::value.
Referenced by _MD_free_entry(), and MD_delete_field_decl().
void MD_delete_field_decl (MD_Field_Decl * field_decl)
Definition at line 3578 of file md.c.
References _MD_free_field_decl(), MD_Symbol::data, entry, MD_Section::entry_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_delete_field(), MD_delete_symbol(), MD_Symbol::next_symbol, NULL, MD_Field_Decl::section, and MD_Field_Decl::symbol.
void MD_delete_md (MD * md)
Definition at line 826 of file md.c.
References _MD_free_section(), _L_Alloc_Pool::allocated, _L_Alloc_Pool::free, L_free(), L_free_alloc_pool(), MD_delete_symbol_table(), MD_Element_pool, MD_Element_Req_pool, MD_Entry_pool, MD_Field_Decl_pool, MD_Field_pool, MD_pool, MD_Section_pool, MD_Symbol_pool, MD_Symbol_Table_pool, MD::name, NULL, and MD::section_table.
void MD_delete_symbol (MD_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 677 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::hash, MD_Symbol_Table::hash_mask, MD_Symbol::hash_val, MD_Symbol_Table::head_symbol, L_free(), MD_Symbol_pool, MD_Symbol::next_hash, MD_Symbol::next_symbol, NULL, MD_Symbol::prev_hash, MD_Symbol::prev_symbol, MD_Symbol_Table::symbol_count, MD_Symbol::table, and MD_Symbol_Table::tail_symbol.
Referenced by _MD_delete_entry(), _MD_delete_section(), and MD_delete_field_decl().
MD_Entry* MD_first_entry (MD_Section * section)
Definition at line 2605 of file md.c.
References MD_Symbol::data, MD_Section::entry_table, MD_Symbol_Table::head_symbol, and NULL.
Referenced by MD_print_md_declarations().
MD_Field_Decl* MD_first_field_decl (MD_Section * section)
Definition at line 3452 of file md.c.
References MD_Symbol::data, MD_Section::field_decl_table, MD_Symbol_Table::head_symbol, and NULL.
MD_Section* MD_first_section (MD * md)
Definition at line 2255 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, NULL, and MD::section_table.
Referenced by MD_print_md_declarations().
void MD_kleene_star_requirement (MD_Field_Decl * field_decl, int element_index)
Definition at line 4149 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::kleene_starred, MD_Field_Decl::kleene_starred_req, MD_Field_Decl::max_require_index, MD_Section::md, MD_concat_strings(), MD_punt(), MD_Field_Decl::name, MD_Section::name, NULL, MD_Field_Decl::require, MD_Element_Req::require_index, and MD_Field_Decl::section.
Referenced by MD_read_md().
MD_Entry* MD_last_entry (MD_Section * section)
Definition at line 2622 of file md.c.
References MD_Symbol::data, MD_Section::entry_table, NULL, and MD_Symbol_Table::tail_symbol.
MD_Field_Decl* MD_last_field_decl (MD_Section * section)
Definition at line 3469 of file md.c.
References MD_Symbol::data, MD_Section::field_decl_table, NULL, and MD_Symbol_Table::tail_symbol.
MD_Section* MD_last_section (MD * md)
Definition at line 2271 of file md.c.
References MD_Symbol::data, NULL, MD::section_table, and MD_Symbol_Table::tail_symbol.
MD_Entry* MD_new_entry (MD_Section * section, char * name)
Definition at line 2499 of file md.c.
References entry, MD_Section::entry_table, MD_Section::field_array_size, L_alloc(), MD_Section::md, MD_add_symbol(), MD_Entry_pool, MD_punt(), MD_strdup(), and NULL.
Referenced by MD_read_md().
MD_Field* MD_new_field (MD_Entry * entry, MD_Field_Decl * decl, int num_elements)
Definition at line 4220 of file md.c.
References MD_Field::decl, MD_Field::element, MD_Field::element_array_size, entry, MD_Field::entry, MD_Field_Decl::field_index, L_alloc(), MD_Field::max_element_index, MD_Field_pool, MD_punt(), MD_resize_element_array(), MD_Field_Decl::name, and NULL.
Referenced by MD_read_md().
MD_Field_Decl* MD_new_field_decl (MD_Section * section, char * name, MD_FIELD_TYPE field_type)
Definition at line 3240 of file md.c.
References MD_Section::field_array_size, MD_Section::field_decl, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Field_Decl::kleene_starred_req, L_alloc(), MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_add_symbol(), MD_Field_Decl_pool, MD_resize_field_arrays(), MD_strdup(), MD_Field_Decl::name, NULL, MD_Field_Decl::require, MD_Field_Decl::require_array_size, MD_Field_Decl::section, MD_Field_Decl::symbol, and MD_Field_Decl::type.
Referenced by MD_read_md().
MD* MD_new_md (char * name, int num_sections)
Definition at line 772 of file md.c.
References L_alloc(), L_create_alloc_pool(), MD_Element_pool, MD_Element_Req_pool, MD_Entry_pool, MD_Field_Decl_pool, MD_Field_pool, MD_new_symbol_table(), MD_pool, MD_punt(), MD_Section_pool, MD_strdup(), MD_Symbol_pool, MD_Symbol_Table_pool, MD::name, NULL, and MD::section_table.
Referenced by MD_read_md().
MD_Section* MD_new_section (MD * md, char * name, int num_entries, int num_fields)
Definition at line 2166 of file md.c.
References MD_Section::entry_table, MD_Section::field_array_size, MD_Section::field_decl, MD_Section::field_decl_table, L_alloc(), MD_Section::max_field_index, MD_Section::md, MD_add_symbol(), MD_concat_strings(), MD_new_symbol_table(), MD_resize_field_arrays(), MD_Section_pool, MD_strdup(), MD_Section::name, NULL, MD::section_table, MD_Section::symbol, and MD_Section::user_ext.
Referenced by MD_read_md().
MD_Entry* MD_next_entry (MD_Entry * entry)
Definition at line 2639 of file md.c.
References MD_Symbol::data, entry, and NULL.
Referenced by MD_print_md_declarations().
MD_Field_Decl* MD_next_field_decl (MD_Field_Decl * field_decl)
Definition at line 3486 of file md.c.
References MD_Symbol::data, MD_Symbol::next_symbol, NULL, and MD_Field_Decl::symbol.
MD_Section* MD_next_section (MD_Section * section)
Definition at line 2288 of file md.c.
References MD_Symbol::data, MD_Symbol::next_symbol, NULL, and MD_Section::symbol.
Referenced by MD_print_md_declarations().
MD_Entry* MD_prev_entry (MD_Entry * entry)
Definition at line 2656 of file md.c.
References MD_Symbol::data, entry, and NULL.
MD_Field_Decl* MD_prev_field_decl (MD_Field_Decl * field_decl)
Definition at line 3503 of file md.c.
References MD_Symbol::data, NULL, MD_Symbol::prev_symbol, and MD_Field_Decl::symbol.
MD_Section* MD_prev_section (MD_Section * section)
Definition at line 2305 of file md.c.
References MD_Symbol::data, NULL, MD_Symbol::prev_symbol, and MD_Section::symbol.
void MD_print_entry (FILE * out, MD_Entry * entry, int page_width)
Definition at line 2848 of file md.c.
References MD_Element::b, MD_Element::d, MD_Symbol::data, MD_Field::element, entry, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_Element::i, MD_Element::l, MD_Field::max_element_index, MD_BLOCK, MD_DOUBLE, MD_INT, MD_legal_ident(), MD_LINK, MD_punt(), MD_STRING, MD_Entry::name, MD_Field_Decl::name, MD_Symbol::next_symbol, NULL, MD_Block::ptr, MD_Element::s, MD_Block::size, MD_Element::type, and MD_Element::value.
Referenced by MD_print_section().
void MD_print_entry_template (FILE * out, MD_Entry * entry)
Definition at line 3190 of file md.c.
References entry, and MD_legal_ident().
Referenced by MD_print_section_template().
void MD_print_field_decl (FILE * out, MD_Field_Decl * field_decl, int page_width)
Definition at line 3620 of file md.c.
References MD_Element_Req::desc, MD_Field_Decl::max_require_index, MD_Section::md, MD_OPTIONAL_FIELD, MD_punt(), MD_REQUIRED_FIELD, MD_Field_Decl::name, MD_Field_Decl::require, MD_Field_Decl::section, and MD_Field_Decl::type.
Referenced by MD_print_section().
void MD_print_md (FILE * out, MD * md, int page_width)
Definition at line 1985 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_print_section(), MD::name, MD_Symbol::next_symbol, NULL, and MD::section_table.
void MD_print_md_declarations (FILE * out, MD * md, int page_width)
Definition at line 2024 of file md.c.
References entry, MD_first_entry(), MD_first_section(), MD_legal_ident(), MD_next_entry(), MD_next_section(), MD_Entry::name, MD_Section::name, MD::name, and NULL.
void MD_print_md_template (FILE * out, MD * md)
Definition at line 2127 of file md.c.
References MD_Symbol::data, MD_Symbol_Table::head_symbol, MD_print_section_template(), MD::name, MD_Symbol::next_symbol, NULL, and MD::section_table.
void MD_print_section (FILE * out, MD_Section * section, int page_width)
Definition at line 2439 of file md.c.
References MD_Symbol::data, entry, MD_Section::entry_table, MD_Section::field_decl_table, MD_Symbol_Table::head_symbol, MD_print_entry(), MD_print_field_decl(), MD_Section::name, MD_Symbol::next_symbol, and NULL.
Referenced by MD_print_md().
void MD_print_section_template (FILE * out, MD_Section * section)
Definition at line 2474 of file md.c.
References MD_Symbol::data, entry, MD_Section::entry_table, MD_Symbol_Table::head_symbol, MD_print_entry_template(), MD_Section::name, MD_Symbol::next_symbol, and NULL.
Referenced by MD_print_md_template().
MD* MD_read_md (FILE * in, char * name)
Definition at line 1251 of file md.c.
References MD_Buf::buf, entry, L_create_alloc_pool(), L_free_alloc_pool(), MD_Buf_pool, MD_delete_buf(), MD_kleene_star_requirement(), MD_new_buf(), MD_new_entry(), MD_new_field(), MD_new_field_decl(), MD_new_md(), MD_new_section(), MD_OPTIONAL_FIELD, MD_punt(), MD_read_block(), MD_read_consume_comments(), MD_read_double(), MD_read_int(), MD_read_nl(), MD_read_sp(), MD_read_string(), MD_require_block(), MD_require_double(), MD_require_int(), MD_require_multi_target_link(), MD_require_string(), MD_REQUIRED_FIELD, MD_set_block, MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_Section::name, and NULL.
void MD_rename_entry (MD_Entry * entry, char * new_name)
Definition at line 2556 of file md.c.
References entry, MD_rename_symbol(), and MD_strdup().
void MD_require_block (MD_Field_Decl * field_decl, int element_index)
Definition at line 3937 of file md.c.
References MD_Element_Req::desc, MD_BLOCK, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_double (MD_Field_Decl * field_decl, int element_index)
Definition at line 3883 of file md.c.
References MD_Element_Req::desc, MD_DOUBLE, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_int (MD_Field_Decl * field_decl, int element_index)
Definition at line 3856 of file md.c.
References MD_Element_Req::desc, MD_INT, MD_new_element_req(), MD_strdup(), and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_link (MD_Field_Decl * field_decl, int element_index, MD_Section * section)
Definition at line 3966 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Section::md, MD_LINK, MD_new_element_req(), MD_punt(), MD_Section::name, NULL, MD_Field_Decl::section, and MD_Element_Req::type.
void MD_require_multi_target_link (MD_Field_Decl * field_decl, int element_index, int section_array_size, MD_Section ** section_array)
Definition at line 4037 of file md.c.
References MD_Element_Req::desc, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Section::md, MD_LINK, MD_new_element_req(), MD_punt(), MD_Section::name, NULL, MD_Field_Decl::section, and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_require_string (MD_Field_Decl * field_decl, int element_index)
Definition at line 3910 of file md.c.
References MD_Element_Req::desc, MD_new_element_req(), MD_strdup(), MD_STRING, and MD_Element_Req::type.
Referenced by MD_read_md().
void MD_write_md (FILE * out, MD * md)
Definition at line 1624 of file md.c.
References MD_Element::b, MD_Element::d, MD_Symbol::data, MD_Field::element, entry, MD_Section::entry_table, MD_Section::field_decl_table, MD_Field_Decl::field_index, MD_Symbol_Table::head_symbol, MD_Element::i, MD_Field_Decl::kleene_starred_req, MD_Element::l, MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_BLOCK, MD_DOUBLE, MD_INT, MD_LINK, MD_OPTIONAL_FIELD, MD_punt(), MD_REQUIRED_FIELD, MD_STRING, MD_Field_Decl::name, MD_Section::name, MD_Symbol::next_symbol, NULL, MD_Block::ptr, MD_Field_Decl::require, MD_Element::s, MD::section_table, MD_Block::size, MD_Entry::symbol, MD_Symbol_Table::symbol_count, MD_Symbol::symbol_id, MD_Element::type, MD_Element_Req::type, MD_Field_Decl::type, and MD_Element::value.