merge_sort.h File Reference
#include <config.h>
Data Structures
struct Element
Defines
#define RECORD_SIZE (4096*2)
Functions
void merge_sort (struct Element *list, struct Element *output, int len)
Define Documentation
#define RECORD_SIZE (4096*2)
Definition at line 69 of file merge_sort.h.
Referenced by merge().
Function Documentation
void merge_sort (struct Element * list, struct Element * output, int len)
Definition at line 113 of file merge_sort.c.
References Element::index, merge(), merge_sort(), output, Element::ptr, and Element::weight.
Referenced by merge_sort().