merge_sort.c File Reference
#include <config.h>
#include <library/merge_sort.h>
Functions
static void merge (struct Element *left, int size_left, struct Element *right, int size_right)
void merge_sort (struct Element *list, struct Element *output, int len)
Function Documentation
static void merge (struct Element * left, int size_left, struct Element * right, int size_right) [static]
Definition at line 63 of file merge_sort.c.
References Element::index, Element::ptr, RECORD_SIZE, and Element::weight.
Referenced by merge_sort().
void merge_sort (struct Element * list, struct Element * output, int len)
Definition at line 113 of file merge_sort.c.
References Element::index, merge(), merge_sort(), output, Element::ptr, and Element::weight.
Referenced by merge_sort().