mfile.h File Reference
#include <config.h>
#include <library/l_alloc_new.h>
#include <stdarg.h>
#include `mbuf.h`
Data Structures
struct Mline
struct Mfile
struct Mptr
Defines
#define MAXARGS 100
Functions
Mfile * create_Mfile (FILE *in, char *input_file_name, char *desc)
void free_Mfile (Mfile *mfile)
Mptr * create_Mptr (Mfile *mfile)
Mptr * copy_Mptr (Mptr *orig_mptr)
void move_Mptr (Mptr *old_mptr, Mptr *new_mptr)
void free_Mptr (Mptr *mptr)
int Mptr_pos (Mptr *mptr)
int Mgetc (Mptr *mptr)
int Mpeekc (Mptr *mptr)
void Mbackupc (Mptr *mptr)
void print_buf_with_arrow (FILE *out, char *buf, int pos)
void Merror (Mptr *mptr, char *fmt,...)
Variables
L_Alloc_Pool * Mfile_pool
L_Alloc_Pool * Mline_pool
L_Alloc_Pool * Mptr_pool
Define Documentation
#define MAXARGS 100
Definition at line 69 of file mfile.h.
Function Documentation
Mptr* copy_Mptr (Mptr * orig_mptr)
Definition at line 330 of file mfile.c.
References L_alloc(), Mptr::mfile, Mptr::mline, Mptr_pool, and Mptr::pos.
Mfile* create_Mfile (FILE * in, char * input_file_name, char * desc)
Definition at line 203 of file mfile.c.
References addc_to_Mbuf(), Mline::buf, clear_Mbuf(), copy_Mbuf_buf(), create_Mbuf(), Mfile::desc, free_Mbuf(), Mfile::head, L_alloc(), L_create_alloc_pool(), Mline::len, len_of_Mbuf(), Mfile::line_count, Mline::line_no, Mline::mfile, Mfile_pool, Mline_pool, Mfile::name, Mline::next, NULL, Mline::prev, and Mfile::tail.
Mptr* create_Mptr (Mfile * mfile)
Definition at line 310 of file mfile.c.
References Mfile::head, L_alloc(), L_create_alloc_pool(), Mptr::mfile, Mptr::mline, Mptr_pool, NULL, and Mptr::pos.
void free_Mfile (Mfile * mfile)
Definition at line 287 of file mfile.c.
References Mline::buf, Mfile::desc, Mfile::head, L_free(), Mfile_pool, Mline_pool, Mfile::name, Mline::next, and NULL.
void free_Mptr (Mptr * mptr)
Definition at line 355 of file mfile.c.
References L_free(), and Mptr_pool.
void Mbackupc (Mptr * mptr)
Definition at line 410 of file mfile.c.
References I_punt(), Mline::len, Mptr::mfile, Mptr::mline, NULL, Mptr::pos, Mline::prev, and Mfile::tail.
void Merror (Mptr * mptr, char * fmt, ...)
Definition at line 153 of file mfile.c.
References Mline::buf, Mfile::desc, Mline::line_no, Mptr::mfile, Mptr::mline, Mfile::name, NULL, Mptr::pos, and print_buf_with_arrow().
int Mgetc (Mptr * mptr)
Definition at line 363 of file mfile.c.
References Mline::buf, Mline::len, Mptr::mline, Mline::next, NULL, and Mptr::pos.
void move_Mptr (Mptr * old_mptr, Mptr * new_mptr)
Definition at line 346 of file mfile.c.
References Mptr::mfile, Mptr::mline, and Mptr::pos.
int Mpeekc (Mptr * mptr)
Definition at line 394 of file mfile.c.
References Mline::buf, Mptr::mline, NULL, and Mptr::pos.
int Mptr_pos (Mptr * mptr)
Definition at line 387 of file mfile.c.
References Mptr::pos.
void print_buf_with_arrow (FILE * out, char * buf, int pos)
Definition at line 78 of file mfile.c.
Referenced by Merror().
Variable Documentation
L_Alloc_Pool* Mfile_pool
Definition at line 72 of file mfile.c.
Referenced by create_Mfile(), and free_Mfile().
L_Alloc_Pool* Mline_pool
Definition at line 73 of file mfile.c.
Referenced by create_Mfile(), and free_Mfile().
L_Alloc_Pool* Mptr_pool
Definition at line 74 of file mfile.c.
Referenced by copy_Mptr(), create_Mptr(), and free_Mptr().