s_recorder.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <library/c_basic.h>
#include <library/s_recorder.h>
Defines
#define DEBUG
Functions
double atof (const char *)
int S_create_record (char *name)
void S_store_record (void)
void S_print_integer (C_Integer value)
void S_print_real (C_Double value)
void S_print_name (C_String str)
int S_sum_of_column (char *name, int N, double *sum)
Variables
static C_File file = 1
Define Documentation
#define DEBUG
Definition at line 70 of file s_recorder.c.
Function Documentation
double atof (const char *)
Referenced by C_string_to_double(), C_string_to_float(), lexRealLit(), and S_sum_of_column().
int S_create_record (char * name)
Definition at line 77 of file s_recorder.c.
References C_OPEN_APPEND_ONLY, C_open_file(), and file.
void S_print_integer (C_Integer value)
Definition at line 93 of file s_recorder.c.
References C_write_integer(), and file.
void S_print_name (C_String str)
Definition at line 105 of file s_recorder.c.
References C_write_word(), and file.
void S_print_real (C_Double value)
Definition at line 99 of file s_recorder.c.
References C_write_double(), and file.
void S_store_record (void)
Definition at line 86 of file s_recorder.c.
References C_close_file(), C_write_word(), and file.
int S_sum_of_column (char * name, int N, double * sum)
Definition at line 121 of file s_recorder.c.
References atof(), C_close_file(), C_eof(), C_open_file(), C_OPEN_READ_ONLY, and C_read_line().
Variable Documentation
C_File file = 1 [static]
Definition at line 74 of file s_recorder.c.
Referenced by S_create_record(), S_print_integer(), S_print_name(), S_print_real(), and S_store_record().