set.h File Reference
#include <config.h>
#include <stdio.h>
#include <library/i_types.h>
Data Structures
struct _Set
struct _SetIterator
Defines
#define Set_VECTOR_LENGTH (8*32)
#define Set_VARRAY_SIZE 8
#define Set_VECTOR_SIZE 8
#define Set_INDEX(x) (x & 0x0FF)
#define Set_BASE(x) (x >> 8)
#define Set_CONSTRUCT_BASE(x) (x << 8)
#define Set_WORD_SELECT(x) (x >> 5)
#define Set_BIT_SELECT(x) (x & 0x01F)
#define Set_INVALID ((Set)-1)
Typedefs
typedef ITuint32 _32bit
typedef _32bit * Set_Vector
typedef _Set * Set
typedef _SetIterator SetIterator
Functions
int Set_in (Set, int)
int Set_size (Set)
int Set_same (Set, Set)
int Set_empty (Set)
int Set_subtract_empty (Set, Set)
int Set_intersect_empty (Set, Set)
Set Set_add (Set, int)
Set Set_delete (Set, int)
Set Set_copy (Set)
Set Set_union (Set, Set)
Set Set_intersect (Set, Set)
Set Set_subtract (Set, Set)
Set Set_subtract_union (Set, Set, Set)
Set Set_union_acc (Set, Set)
Set Set_union_acc_ch (Set set1, Set set2, int *change)
Set Set_intersect_acc (Set, Set)
Set Set_subtract_acc (Set, Set)
Set Set_subtract_union_acc (Set, Set, Set)
Set Set_dispose (Set)
Set Set_compress (Set)
Set Set_new (void)
void Set_print (FILE *, char *, Set)
int Set_2array (Set, int *)
SetIterator * Set_iterator (Set set, int finis)
int Set_exhausted (SetIterator *si)
int Set_next (SetIterator *si)
void Set_reset (SetIterator *si, Set set)
SetIterator * Set_end_iterator (SetIterator *si)
void Set_memory_usage (long *pused, long *presv, long *pmax)
Define Documentation
#define Set_BASE(x) (x >> 8)
Definition at line 99 of file set.h.
Referenced by Set_add(), Set_delete(), and Set_in().
#define Set_BIT_SELECT(x) (x & 0x01F)
Definition at line 102 of file set.h.
Referenced by ClearBit(), ReadBit(), and SetBit().
#define Set_CONSTRUCT_BASE(x) (x << 8)
Definition at line 100 of file set.h.
Referenced by Set_2array(), Set_next(), and Set_print().
#define Set_INDEX(x) (x & 0x0FF)
Definition at line 98 of file set.h.
Referenced by ClearBit(), ReadBit(), and SetBit().
#define Set_INVALID ((Set)-1)
Definition at line 104 of file set.h.
#define Set_VARRAY_SIZE 8
Definition at line 96 of file set.h.
Referenced by FreeVArray(), NewSet(), NewVArray(), Set_subtract_union(), and Set_union().
#define Set_VECTOR_LENGTH (8*32)
Definition at line 95 of file set.h.
#define Set_VECTOR_SIZE 8
Definition at line 97 of file set.h.
Referenced by NewVector(), Set_2array(), Set_empty(), Set_next(), and Set_print().
#define Set_WORD_SELECT(x) (x >> 5)
Definition at line 101 of file set.h.
Referenced by ClearBit(), ReadBit(), and SetBit().
Typedef Documentation
typedef ITuint32 _32bit
Definition at line 71 of file set.h.
typedef struct _Set * Set
typedef _32bit* Set_Vector
Definition at line 73 of file set.h.
typedef struct _SetIterator
 SetIterator
Function Documentation
int Set_2array (Set, int *)
Definition at line 1621 of file set.c.
References _Set::max_base, NULL, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Graph_equiv_cd().
Set Set_add (Set, int)
Definition at line 452 of file set.c.
References ABS, EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_BASE, Set_print(), SetBit(), SIGN, and _Set::varray.
Referenced by add_df_node_dest_reg(), add_df_node_src_reg(), AddExtensionFields(), dominator(), FreeSet(), Graph_control_dependence(), Graph_dominator(), Graph_post_dominator(), post_dominator(), reaching_definition(), and ud_chain().
Set Set_compress (Set)
Definition at line 1504 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), and _Set::varray.
Set Set_copy (Set)
Definition at line 520 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, and _Set::varray.
Set Set_delete (Set, int)
Definition at line 487 of file set.c.
References ABS, ClearBit(), _Set::max_base, Set_BASE, Set_print(), and SIGN.
Set Set_dispose (Set)
Definition at line 1496 of file set.c.
References FreeSet(), and NULL.
Referenced by AddExtensionFields(), dominator(), FreeExtensionFields(), Graph_dominator(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), Graph_post_dominator(), live_variable(), post_dominator(), reaching_definition(), reset_nodes(), Set_intersect_acc(), and ud_chain().
int Set_empty (Set)
Definition at line 425 of file set.c.
References _Set::max_base, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_same(), and Set_subtract_empty().
SetIterator* Set_end_iterator (SetIterator * si)
Definition at line 1904 of file set.c.
References L_free(), NULL, and SET_SetIterator_pool.
int Set_exhausted (SetIterator * si)
Definition at line 1820 of file set.c.
References _SetIterator::current_varray, and _SetIterator::set.
int Set_in (Set, int)
Definition at line 336 of file set.c.
References ABS, _Set::max_base, ReadBit(), Set_BASE, SIGN, and _Set::varray.
Referenced by FreeSet(), Graph_control_dependence(), Graph_count_paths_visit(), Graph_daVinci_visit(), Graph_imm_dominator(), Graph_imm_post_dominator(), print_set(), reaching_definition(), and SelectTraces().
Set Set_intersect (Set, Set)
Definition at line 901 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.
Referenced by AddExtensionFields(), dominator(), post_dominator(), and ud_chain().
Set Set_intersect_acc (Set, Set)
Definition at line 974 of file set.c.
References FreeVector(), _Set::max_base, NULL, Set_dispose(), Set_print(), and _Set::varray.
Referenced by Graph_dominator(), and Graph_post_dominator().
int Set_intersect_empty (Set, Set)
Definition at line 1050 of file set.c.
References _Set::max_base, and _Set::varray.
SetIterator* Set_iterator (Set set, int finis)
Definition at line 1796 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, _SetIterator::finis, L_alloc(), L_create_alloc_pool(), NULL, _SetIterator::set, Set_next(), and SET_SetIterator_pool.
void Set_memory_usage (long * pused, long * presv, long * pmax)
Definition at line 1911 of file set.c.
References _L_Alloc_Pool::allocated, _L_Alloc_Pool::free, mallocated, maxmallocated, SET_Set_pool, SET_VArray_pool, and SET_Vector_pool.
Referenced by Set_print_memory_usage().
Set Set_new (void)
Definition at line 248 of file set.c.
References NewSet().
int Set_next (SetIterator * si)
Definition at line 1829 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, _SetIterator::finis, _Set::max_base, _SetIterator::nxt, _SetIterator::set, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_iterator(), and Set_reset().
void Set_print (FILE *, char *, Set)
Definition at line 1560 of file set.c.
References _Set::max_base, NULL, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_add(), Set_delete(), Set_intersect(), Set_intersect_acc(), Set_same(), Set_subtract(), Set_subtract_acc(), Set_union(), Set_union_acc(), and Set_union_acc_ch().
void Set_reset (SetIterator * si, Set set)
Definition at line 1890 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, I_punt(), _SetIterator::set, and Set_next().
int Set_same (Set, Set)
Definition at line 1677 of file set.c.
References Set_empty(), and Set_print().
Referenced by AddExtensionFields(), dominator(), Graph_dominator(), Graph_equiv_cd(), Graph_post_dominator(), and post_dominator().
int Set_size (Set)
Definition at line 359 of file set.c.
References _Set::max_base, and _Set::varray.
Referenced by Graph_equiv_cd(), live_variable(), reaching_definition(), and ud_chain().
Set Set_subtract (Set, Set)
Definition at line 1095 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), Set_union(), and _Set::varray.
Referenced by live_variable(), reaching_definition(), Set_subtract_union(), and ud_chain().
Set Set_subtract_acc (Set, Set)
Definition at line 1180 of file set.c.
References _Set::max_base, NULL, Set_print(), and _Set::varray.
Referenced by Set_subtract_union_acc().
int Set_subtract_empty (Set, Set)
Definition at line 1242 of file set.c.
References _Set::max_base, NULL, Set_empty(), and _Set::varray.
Set Set_subtract_union (Set, Set, Set)
Definition at line 1300 of file set.c.
References EnlargeVArray(), MAX, _Set::max_base, NewSet(), NewVector(), Set_subtract(), Set_union(), Set_VARRAY_SIZE, and _Set::varray.
Set Set_subtract_union_acc (Set, Set, Set)
Definition at line 1410 of file set.c.
References EnlargeVArray(), _Set::max_base, NewVector(), Set_subtract_acc(), Set_union(), Set_union_acc(), and _Set::varray.
Set Set_union (Set, Set)
Definition at line 575 of file set.c.
References EnlargeVArray(), MAX, _Set::max_base, NewSet(), NewVector(), Set_print(), Set_VARRAY_SIZE, and _Set::varray.
Referenced by AddExtensionFields(), dominator(), Graph_dominator(), Graph_equiv_cd(), Graph_post_dominator(), live_variable(), post_dominator(), reaching_definition(), Set_subtract(), Set_subtract_union(), Set_subtract_union_acc(), and ud_chain().
Set Set_union_acc (Set, Set)
Definition at line 701 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.
Referenced by Set_subtract_union_acc().
Set Set_union_acc_ch (Set set1, Set set2, int * change)
Definition at line 801 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.