set.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include <library/set.h>
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Defines
#define ABS(x) (x<0 ? -x:x)
#define MAX(x, y) ((x>y)?x:y)
#define SIGN(x) ((x>=0)?0:1)
Functions
static Set_Vector * NewVArray (int size)
static void FreeVArray (int size, Set_Vector *varray)
static void EnlargeVArray (int size, int *base, Set_Vector **varray)
static Set_Vector NewVector (void)
static void FreeVector (Set_Vector vector)
static Set NewSet (void)
Set Set_new (void)
static void FreeSet (Set set)
static int ReadBit (Set_Vector vector, int element)
static int SetBit (Set_Vector vector, int element)
static int ClearBit (Set_Vector vector, int element)
int Set_in (Set set, int element)
int Set_size (Set set)
int Set_empty (Set set)
Set Set_add (Set set, int element)
Set Set_delete (Set set, int element)
Set Set_copy (Set set1)
Set Set_union (Set set1, Set set2)
Set Set_union_acc (Set set1, Set set2)
Set Set_union_acc_ch (Set set1, Set set2, int *change)
Set Set_intersect (Set set1, Set set2)
Set Set_intersect_acc (Set set1, Set set2)
int Set_intersect_empty (Set set1, Set set2)
Set Set_subtract (Set set1, Set set2)
Set Set_subtract_acc (Set set1, Set set2)
int Set_subtract_empty (Set set1, Set set2)
Set Set_subtract_union (Set set1, Set set2, Set set3)
Set Set_subtract_union_acc (Set set1, Set set2, Set set3)
Set Set_dispose (Set set)
Set Set_compress (Set set)
void Set_print (FILE *F, char *name, Set set)
int Set_2array (Set set, int *buf)
int Set_same (Set set1, Set set2)
SetIterator * Set_iterator (Set set, int finis)
int Set_exhausted (SetIterator *si)
int Set_next (SetIterator *si)
void Set_reset (SetIterator *si, Set set)
SetIterator * Set_end_iterator (SetIterator *si)
void Set_memory_usage (long *pused, long *presv, long *pmax)
void Set_print_memory_usage (FILE *fp)
Variables
int total = 0
int n_varray = 0
int n_vector = 0
int n_set = 0
static long mallocated = 0
static long maxmallocated = 0
Set OUT = NULL
int SetId = 0
L_Alloc_Pool * SET_VArray_pool = NULL
L_Alloc_Pool * SET_Vector_pool = NULL
L_Alloc_Pool * SET_Set_pool = NULL
L_Alloc_Pool * SET_SetIterator_pool = NULL
Define Documentation
#define ABS(x) (x<0 ? -x:x)
Definition at line 90 of file set.c.
Referenced by ClearBit(), ReadBit(), Set_add(), Set_delete(), Set_in(), and SetBit().
#define MAX(x, y) ((x>y)?x:y)
Definition at line 91 of file set.c.
#define SIGN(x) ((x>=0)?0:1)
Definition at line 92 of file set.c.
Referenced by Set_add(), Set_delete(), and Set_in().
Function Documentation
static int ClearBit (Set_Vector vector, int element) [static]
Definition at line 321 of file set.c.
References ABS, Set_BIT_SELECT, Set_INDEX, and Set_WORD_SELECT.
Referenced by Set_delete().
static void EnlargeVArray (int size, int * base, Set_Vector ** varray) [static]
Definition at line 177 of file set.c.
References FreeVArray(), and NewVArray().
Referenced by Set_add(), Set_compress(), Set_copy(), Set_intersect(), Set_subtract(), Set_subtract_union(), Set_subtract_union_acc(), Set_union(), Set_union_acc(), and Set_union_acc_ch().
static void FreeSet (Set set) [static]
Definition at line 254 of file set.c.
References FreeVArray(), FreeVector(), _Set::id, L_free(), _Set::max_base, NULL, OUT, Set_add(), Set_in(), SET_Set_pool, and _Set::varray.
Referenced by Set_dispose().
static void FreeVArray (int size, Set_Vector * varray) [static]
Definition at line 159 of file set.c.
References L_free(), mallocated, NULL, SET_VArray_pool, and Set_VARRAY_SIZE.
Referenced by EnlargeVArray(), and FreeSet().
static void FreeVector (Set_Vector vector) [static]
Definition at line 220 of file set.c.
References L_free(), NULL, and SET_Vector_pool.
Referenced by FreeSet(), and Set_intersect_acc().
static Set NewSet (void) [static]
Definition at line 229 of file set.c.
References _Set::dummy, _Set::id, L_alloc(), L_create_alloc_pool(), _Set::max_base, NewVArray(), NULL, SET_Set_pool, Set_VARRAY_SIZE, SetId, and _Set::varray.
Referenced by Set_add(), Set_compress(), Set_copy(), Set_intersect(), Set_new(), Set_subtract(), Set_subtract_union(), Set_union(), Set_union_acc(), and Set_union_acc_ch().
static Set_Vector* NewVArray (int size) [static]
Definition at line 129 of file set.c.
References I_punt(), L_alloc(), L_create_alloc_pool(), mallocated, maxmallocated, NULL, SET_VArray_pool, and Set_VARRAY_SIZE.
Referenced by EnlargeVArray(), and NewSet().
static Set_Vector NewVector (void) [static]
Definition at line 196 of file set.c.
References L_alloc(), L_create_alloc_pool(), NULL, SET_Vector_pool, and Set_VECTOR_SIZE.
Referenced by Set_add(), Set_compress(), Set_copy(), Set_intersect(), Set_subtract(), Set_subtract_union(), Set_subtract_union_acc(), Set_union(), Set_union_acc(), and Set_union_acc_ch().
static int ReadBit (Set_Vector vector, int element) [static]
Definition at line 292 of file set.c.
References ABS, Set_BIT_SELECT, Set_INDEX, and Set_WORD_SELECT.
Referenced by Set_in().
int Set_2array (Set set, int * buf)
Definition at line 1621 of file set.c.
References _Set::max_base, NULL, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Graph_equiv_cd().
Set Set_add (Set set, int element)
Definition at line 452 of file set.c.
References ABS, EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_BASE, Set_print(), SetBit(), SIGN, and _Set::varray.
Referenced by add_df_node_dest_reg(), add_df_node_src_reg(), AddExtensionFields(), dominator(), FreeSet(), Graph_control_dependence(), Graph_dominator(), Graph_post_dominator(), post_dominator(), reaching_definition(), and ud_chain().
Set Set_compress (Set set)
Definition at line 1504 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), and _Set::varray.
Set Set_copy (Set set1)
Definition at line 520 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, and _Set::varray.
Set Set_delete (Set set, int element)
Definition at line 487 of file set.c.
References ABS, ClearBit(), _Set::max_base, Set_BASE, Set_print(), and SIGN.
Set Set_dispose (Set set)
Definition at line 1496 of file set.c.
References FreeSet(), and NULL.
Referenced by AddExtensionFields(), dominator(), FreeExtensionFields(), Graph_dominator(), Graph_free_graph_equiv_cd(), Graph_free_graph_node(), Graph_post_dominator(), live_variable(), post_dominator(), reaching_definition(), reset_nodes(), Set_intersect_acc(), and ud_chain().
int Set_empty (Set set)
Definition at line 425 of file set.c.
References _Set::max_base, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_same(), and Set_subtract_empty().
SetIterator* Set_end_iterator (SetIterator * si)
Definition at line 1904 of file set.c.
References L_free(), NULL, and SET_SetIterator_pool.
int Set_exhausted (SetIterator * si)
Definition at line 1820 of file set.c.
References _SetIterator::current_varray, and _SetIterator::set.
int Set_in (Set set, int element)
Definition at line 336 of file set.c.
References ABS, _Set::max_base, ReadBit(), Set_BASE, SIGN, and _Set::varray.
Referenced by FreeSet(), Graph_control_dependence(), Graph_count_paths_visit(), Graph_daVinci_visit(), Graph_imm_dominator(), Graph_imm_post_dominator(), print_set(), reaching_definition(), and SelectTraces().
Set Set_intersect (Set set1, Set set2)
Definition at line 901 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.
Referenced by AddExtensionFields(), dominator(), post_dominator(), and ud_chain().
Set Set_intersect_acc (Set set1, Set set2)
Definition at line 974 of file set.c.
References FreeVector(), _Set::max_base, NULL, Set_dispose(), Set_print(), and _Set::varray.
Referenced by Graph_dominator(), and Graph_post_dominator().
int Set_intersect_empty (Set set1, Set set2)
Definition at line 1050 of file set.c.
References _Set::max_base, and _Set::varray.
SetIterator* Set_iterator (Set set, int finis)
Definition at line 1796 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, _SetIterator::finis, L_alloc(), L_create_alloc_pool(), NULL, _SetIterator::set, Set_next(), and SET_SetIterator_pool.
void Set_memory_usage (long * pused, long * presv, long * pmax)
Definition at line 1911 of file set.c.
References _L_Alloc_Pool::allocated, _L_Alloc_Pool::free, mallocated, maxmallocated, SET_Set_pool, SET_VArray_pool, and SET_Vector_pool.
Referenced by Set_print_memory_usage().
Set Set_new (void)
Definition at line 248 of file set.c.
References NewSet().
int Set_next (SetIterator * si)
Definition at line 1829 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, _SetIterator::finis, _Set::max_base, _SetIterator::nxt, _SetIterator::set, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_iterator(), and Set_reset().
void Set_print (FILE * F, char * name, Set set)
Definition at line 1560 of file set.c.
References _Set::max_base, NULL, Set_CONSTRUCT_BASE, Set_VECTOR_SIZE, and _Set::varray.
Referenced by Set_add(), Set_delete(), Set_intersect(), Set_intersect_acc(), Set_same(), Set_subtract(), Set_subtract_acc(), Set_union(), Set_union_acc(), and Set_union_acc_ch().
void Set_print_memory_usage (FILE * fp)
Definition at line 1952 of file set.c.
References Set_memory_usage().
void Set_reset (SetIterator * si, Set set)
Definition at line 1890 of file set.c.
References _SetIterator::current_base, _SetIterator::current_bit, _SetIterator::current_varray, I_punt(), _SetIterator::set, and Set_next().
int Set_same (Set set1, Set set2)
Definition at line 1677 of file set.c.
References Set_empty(), and Set_print().
Referenced by AddExtensionFields(), dominator(), Graph_dominator(), Graph_equiv_cd(), Graph_post_dominator(), and post_dominator().
int Set_size (Set set)
Definition at line 359 of file set.c.
References _Set::max_base, and _Set::varray.
Referenced by Graph_equiv_cd(), live_variable(), reaching_definition(), and ud_chain().
Set Set_subtract (Set set1, Set set2)
Definition at line 1095 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), Set_union(), and _Set::varray.
Referenced by live_variable(), reaching_definition(), Set_subtract_union(), and ud_chain().
Set Set_subtract_acc (Set set1, Set set2)
Definition at line 1180 of file set.c.
References _Set::max_base, NULL, Set_print(), and _Set::varray.
Referenced by Set_subtract_union_acc().
int Set_subtract_empty (Set set1, Set set2)
Definition at line 1242 of file set.c.
References _Set::max_base, NULL, Set_empty(), and _Set::varray.
Set Set_subtract_union (Set set1, Set set2, Set set3)
Definition at line 1300 of file set.c.
References EnlargeVArray(), MAX, _Set::max_base, NewSet(), NewVector(), Set_subtract(), Set_union(), Set_VARRAY_SIZE, and _Set::varray.
Set Set_subtract_union_acc (Set set1, Set set2, Set set3)
Definition at line 1410 of file set.c.
References EnlargeVArray(), _Set::max_base, NewVector(), Set_subtract_acc(), Set_union(), Set_union_acc(), and _Set::varray.
Set Set_union (Set set1, Set set2)
Definition at line 575 of file set.c.
References EnlargeVArray(), MAX, _Set::max_base, NewSet(), NewVector(), Set_print(), Set_VARRAY_SIZE, and _Set::varray.
Referenced by AddExtensionFields(), dominator(), Graph_dominator(), Graph_equiv_cd(), Graph_post_dominator(), live_variable(), post_dominator(), reaching_definition(), Set_subtract(), Set_subtract_union(), Set_subtract_union_acc(), and ud_chain().
Set Set_union_acc (Set set1, Set set2)
Definition at line 701 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.
Referenced by Set_subtract_union_acc().
Set Set_union_acc_ch (Set set1, Set set2, int * change)
Definition at line 801 of file set.c.
References EnlargeVArray(), _Set::max_base, NewSet(), NewVector(), NULL, Set_print(), and _Set::varray.
static int SetBit (Set_Vector vector, int element) [static]
Definition at line 307 of file set.c.
References ABS, Set_BIT_SELECT, Set_INDEX, and Set_WORD_SELECT.
Referenced by Set_add().
Variable Documentation
long mallocated = 0 [static]
Definition at line 114 of file set.c.
Referenced by FreeVArray(), NewVArray(), and Set_memory_usage().
long maxmallocated = 0 [static]
Definition at line 115 of file set.c.
Referenced by NewVArray(), and Set_memory_usage().
int n_set = 0
Definition at line 112 of file set.c.
int n_varray = 0
Definition at line 110 of file set.c.
int n_vector = 0
Definition at line 111 of file set.c.
Set OUT = NULL
Definition at line 117 of file set.c.
Referenced by FreeSet().
L_Alloc_Pool* SET_Set_pool = NULL
Definition at line 123 of file set.c.
Referenced by FreeSet(), NewSet(), and Set_memory_usage().
L_Alloc_Pool* SET_SetIterator_pool = NULL
Definition at line 125 of file set.c.
Referenced by Set_end_iterator(), and Set_iterator().
L_Alloc_Pool* SET_VArray_pool = NULL
Definition at line 121 of file set.c.
Referenced by FreeVArray(), NewVArray(), and Set_memory_usage().
L_Alloc_Pool* SET_Vector_pool = NULL
Definition at line 122 of file set.c.
Referenced by FreeVector(), NewVector(), and Set_memory_usage().
int SetId = 0
Definition at line 119 of file set.c.
Referenced by NewSet().
int total = 0
Definition at line 109 of file set.c.