stack.c File Reference
#include <config.h>
#include <stdio.h>
#include <library/l_alloc_new.h>
#include <library/stack.h>
Functions
Stack * New_Stack (void)
StackElmt * New_Stack_Elmt (void)
void Free_Stack_Elmt (StackElmt *ptr)
Stack * Free_Stack (Stack *stack)
void Clear_Stack (Stack *stack)
void Push_Top (Stack *stack, void *ptr)
void Push_Bot (Stack *stack, void *ptr)
void * Pop (Stack *stack)
void * Stack_Top (Stack *stack)
void * Stack_Elmt_Data (StackElmt *elmt)
StackElmt * Stack_Find (Stack *stack, void *ptr)
StackElmt * Stack_Ptr_Reset (Stack *stack)
void Stack_Ptr_Set (Stack *stack, StackElmt *ptr)
StackElmt * Stack_Find_Next (Stack *stack)
int Stack_Is_Bottom (Stack *stack)
void Delete_Stack (Stack *stack, StackElmt *ptr)
void Stack_Print (Stack *stack)
Variables
static L_Alloc_Pool * stackPool = NULL
static L_Alloc_Pool * stackElmtPool = NULL
Function Documentation
void Clear_Stack (Stack * stack)
Definition at line 122 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack, and stackElmtPool.
void Delete_Stack (Stack * stack, StackElmt * ptr)
Definition at line 272 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack_elmt::prev, stack, and stackElmtPool.
Stack* Free_Stack (Stack * stack)
Definition at line 106 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack, stackElmtPool, and stackPool.
void Free_Stack_Elmt (StackElmt * ptr)
Definition at line 100 of file stack.c.
References L_free(), and stackElmtPool.
Stack* New_Stack (void)
Definition at line 73 of file stack.c.
References L_alloc(), L_create_alloc_pool(), NULL, stack, stackElmtPool, and stackPool.
StackElmt* New_Stack_Elmt (void)
Definition at line 94 of file stack.c.
References L_alloc(), and stackElmtPool.
void* Pop (Stack * stack)
Definition at line 186 of file stack.c.
References L_free(), NULL, stack_elmt::ptr, stack, and stackElmtPool.
void Push_Bot (Stack * stack, void * ptr)
Definition at line 164 of file stack.c.
References L_alloc(), stack_elmt::next, NULL, stack_elmt::prev, stack_elmt::ptr, stack, and stackElmtPool.
void Push_Top (Stack * stack, void * ptr)
Definition at line 142 of file stack.c.
References L_alloc(), stack_elmt::next, NULL, stack_elmt::prev, stack_elmt::ptr, stack, and stackElmtPool.
void* Stack_Elmt_Data (StackElmt * elmt)
Definition at line 216 of file stack.c.
References NULL, and stack_elmt::ptr.
StackElmt* Stack_Find (Stack * stack, void * ptr)
Definition at line 225 of file stack.c.
References NULL, stack_elmt::ptr, and stack.
StackElmt* Stack_Find_Next (Stack * stack)
Definition at line 253 of file stack.c.
References NULL, and stack.
int Stack_Is_Bottom (Stack * stack)
Definition at line 266 of file stack.c.
References NULL, and stack.
void Stack_Print (Stack * stack)
Definition at line 303 of file stack.c.
References stack_elmt::next, NULL, stack_elmt::ptr, and stack.
StackElmt* Stack_Ptr_Reset (Stack * stack)
Definition at line 239 of file stack.c.
References stack.
void Stack_Ptr_Set (Stack * stack, StackElmt * ptr)
Definition at line 246 of file stack.c.
References stack.
void* Stack_Top (Stack * stack)
Definition at line 207 of file stack.c.
References NULL, and stack.
Variable Documentation
L_Alloc_Pool* stackElmtPool = NULL [static]
Definition at line 70 of file stack.c.
Referenced by Clear_Stack(), Delete_Stack(), Free_Stack(), Free_Stack_Elmt(), New_Stack(), New_Stack_Elmt(), Pop(), Push_Bot(), and Push_Top().
L_Alloc_Pool* stackPool = NULL [static]
Definition at line 69 of file stack.c.
Referenced by Free_Stack(), and New_Stack().