stack.h File Reference
#include <config.h>
Data Structures
struct stack_elmt
struct stack_hdr
Defines
#define _Stack_Ptr_Reset(stack, t)
#define _Stack_Find_Next(stack, n)
#define _Stack_Top(stack) ((stack $\rightarrow$ top) ? stack $\rightarrow$ top $\rightarrow$ ptr : (void *)-1)
#define _Stack_Elmt_Data(elmt) ((elmt) ? elmt $\rightarrow$ ptr : (void *)-1)
Typedefs
typedef stack_elmt StackElmt
typedef stack_hdr Stack
Functions
Stack * New_Stack (void)
StackElmt * New_Stack_Elmt (void)
void Free_Stack_Elmt (StackElmt *ptr)
Stack * Free_Stack (Stack *stack)
void Clear_Stack (Stack *stack)
void Push_Top (Stack *stack, void *ptr)
void Push_Bot (Stack *stack, void *ptr)
void * Pop (Stack *stack)
void * Stack_Top (Stack *stack)
StackElmt * Stack_Find (Stack *stack, void *ptr)
StackElmt * Stack_Ptr_Reset (Stack *stack)
void Stack_Ptr_Set (Stack *stack, StackElmt *ptr)
StackElmt * Stack_Find_Next (Stack *stack)
void Delete_Stack (Stack *stack, StackElmt *ptr)
void * Stack_Elmt_Data (StackElmt *elmt)
void Stack_Print (Stack *stack)
Define Documentation
#define _Stack_Elmt_Data(elmt) ((elmt) ? elmt $\rightarrow$ ptr : (void *)-1)
Definition at line 98 of file stack.h.
#define _Stack_Find_Next(stack, n)
Value:
{ Stack *tmp;   \
                                          if ( tmp != NULL )  { \
                                              tmp = stack->ptr->next; \
                                              stack->ptr = tmp;  \
                                          } \
                                          n = tmp; \
                                        }
Definition at line 89 of file stack.h.
#define _Stack_Ptr_Reset(stack, t)
Value:
{ \
                                          stack->ptr = stack->top; \
                                          t = stack->ptr; \
                                        }
Definition at line 84 of file stack.h.
#define _Stack_Top(stack) ((stack $\rightarrow$ top) ? stack $\rightarrow$ top $\rightarrow$ ptr : (void *)-1)
Definition at line 97 of file stack.h.
Typedef Documentation
typedef struct stack_hdr
 Stack
typedef struct stack_elmt
 StackElmt
Function Documentation
void Clear_Stack (Stack * stack)
Definition at line 122 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack, and stackElmtPool.
void Delete_Stack (Stack * stack, StackElmt * ptr)
Definition at line 272 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack_elmt::prev, stack, and stackElmtPool.
Stack* Free_Stack (Stack * stack)
Definition at line 106 of file stack.c.
References L_free(), stack_elmt::next, NULL, stack, stackElmtPool, and stackPool.
void Free_Stack_Elmt (StackElmt * ptr)
Definition at line 100 of file stack.c.
References L_free(), and stackElmtPool.
Stack* New_Stack (void)
Definition at line 73 of file stack.c.
References L_alloc(), L_create_alloc_pool(), NULL, stack, stackElmtPool, and stackPool.
StackElmt* New_Stack_Elmt (void)
Definition at line 94 of file stack.c.
References L_alloc(), and stackElmtPool.
void* Pop (Stack * stack)
Definition at line 186 of file stack.c.
References L_free(), NULL, stack_elmt::ptr, stack, and stackElmtPool.
void Push_Bot (Stack * stack, void * ptr)
Definition at line 164 of file stack.c.
References L_alloc(), stack_elmt::next, NULL, stack_elmt::prev, stack_elmt::ptr, stack, and stackElmtPool.
void Push_Top (Stack * stack, void * ptr)
Definition at line 142 of file stack.c.
References L_alloc(), stack_elmt::next, NULL, stack_elmt::prev, stack_elmt::ptr, stack, and stackElmtPool.
void* Stack_Elmt_Data (StackElmt * elmt)
Definition at line 216 of file stack.c.
References NULL, and stack_elmt::ptr.
StackElmt* Stack_Find (Stack * stack, void * ptr)
Definition at line 225 of file stack.c.
References NULL, stack_elmt::ptr, and stack.
StackElmt* Stack_Find_Next (Stack * stack)
Definition at line 253 of file stack.c.
References NULL, and stack.
void Stack_Print (Stack * stack)
Definition at line 303 of file stack.c.
References stack_elmt::next, NULL, stack_elmt::ptr, and stack.
StackElmt* Stack_Ptr_Reset (Stack * stack)
Definition at line 239 of file stack.c.
References stack.
void Stack_Ptr_Set (Stack * stack, StackElmt * ptr)
Definition at line 246 of file stack.c.
References stack.
void* Stack_Top (Stack * stack)
Definition at line 207 of file stack.c.
References NULL, and stack.