string_symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `string_symbol.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Functions
STRING_Symbol_Table * STRING_new_symbol_table (char *name, int expected_size)
void STRING_delete_symbol_table (STRING_Symbol_Table *table, void(*free_routine)(void *))
void STRING_resize_symbol_table (STRING_Symbol_Table *table)
static unsigned int STRING_hash_string (char *string)
STRING_Symbol * STRING_add_symbol (STRING_Symbol_Table *table, char *name, void *data)
STRING_Symbol * STRING_find_symbol (STRING_Symbol_Table *table, char *name)
void * STRING_find_symbol_data (STRING_Symbol_Table *table, char *name)
void STRING_delete_symbol (STRING_Symbol *symbol, void(*free_routine)(void *))
void STRING_print_symbol_table_hash (FILE *out, STRING_Symbol_Table *table)
STRING_Symbol * STRING_first_symbol (STRING_Symbol_Table *table)
Variables
L_Alloc_Pool * STRING_Symbol_Table_pool = NULL
L_Alloc_Pool * STRING_Symbol_pool = NULL
Function Documentation
STRING_Symbol* STRING_add_symbol (STRING_Symbol_Table * table, char * name, void * data)
Definition at line 280 of file string_symbol.c.
References STRING_Symbol::data, STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_mask, STRING_Symbol::hash_val, STRING_Symbol_Table::head_symbol, I_punt(), L_alloc(), STRING_Symbol::name, STRING_Symbol_Table::name, STRING_Symbol::next_hash, STRING_Symbol::next_symbol, NULL, STRING_Symbol::prev_symbol, STRING_Symbol_Table::resize_size, STRING_hash_string(), STRING_resize_symbol_table(), STRING_Symbol_pool, STRING_Symbol_Table::symbol_count, STRING_Symbol::table, and STRING_Symbol_Table::tail_symbol.
void STRING_delete_symbol (STRING_Symbol * symbol, void(*)(void *) free_routine)
Definition at line 427 of file string_symbol.c.
References STRING_Symbol::data, STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_mask, STRING_Symbol::hash_val, STRING_Symbol_Table::head_symbol, L_free(), STRING_Symbol::name, STRING_Symbol::next_hash, STRING_Symbol::next_symbol, NULL, STRING_Symbol::prev_hash, STRING_Symbol::prev_symbol, STRING_Symbol_pool, STRING_Symbol_Table::symbol_count, STRING_Symbol::table, and STRING_Symbol_Table::tail_symbol.
void STRING_delete_symbol_table (STRING_Symbol_Table * table, void(*)(void *) free_routine)
Definition at line 153 of file string_symbol.c.
References STRING_Symbol::data, STRING_Symbol_Table::hash, STRING_Symbol_Table::head_symbol, L_free(), STRING_Symbol::name, STRING_Symbol_Table::name, STRING_Symbol::next_symbol, NULL, STRING_Symbol_pool, and STRING_Symbol_Table_pool.
STRING_Symbol* STRING_find_symbol (STRING_Symbol_Table * table, char * name)
Definition at line 368 of file string_symbol.c.
References STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_mask, STRING_Symbol::hash_val, STRING_Symbol::name, STRING_Symbol::next_hash, NULL, and STRING_hash_string().
void* STRING_find_symbol_data (STRING_Symbol_Table * table, char * name)
Definition at line 399 of file string_symbol.c.
References STRING_Symbol::data, STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_mask, STRING_Symbol::hash_val, STRING_Symbol::name, STRING_Symbol::next_hash, NULL, and STRING_hash_string().
STRING_Symbol* STRING_first_symbol (STRING_Symbol_Table * table)
Definition at line 513 of file string_symbol.c.
References STRING_Symbol_Table::head_symbol.
static unsigned int STRING_hash_string (char * string) [static]
Definition at line 240 of file string_symbol.c.
Referenced by STRING_add_symbol(), STRING_find_symbol(), and STRING_find_symbol_data().
STRING_Symbol_Table* STRING_new_symbol_table (char * name, int expected_size)
Definition at line 80 of file string_symbol.c.
References STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_mask, STRING_Symbol_Table::hash_size, STRING_Symbol_Table::head_symbol, I_punt(), L_alloc(), L_create_alloc_pool(), STRING_Symbol_Table::name, NULL, STRING_Symbol_Table::resize_size, STRING_Symbol_pool, STRING_Symbol_Table_pool, STRING_Symbol_Table::symbol_count, and STRING_Symbol_Table::tail_symbol.
void STRING_print_symbol_table_hash (FILE * out, STRING_Symbol_Table * table)
Definition at line 480 of file string_symbol.c.
References STRING_Symbol_Table::hash, STRING_Symbol_Table::hash_size, STRING_Symbol_Table::name, STRING_Symbol::name, STRING_Symbol::next_hash, NULL, and STRING_Symbol_Table::symbol_count.
void STRING_resize_symbol_table (STRING_Symbol_Table * table)
Definition at line 183 of file string_symbol.c.
References STRING_Symbol_Table::hash_size, STRING_Symbol::hash_val, STRING_Symbol_Table::head_symbol, I_punt(), STRING_Symbol::next_hash, STRING_Symbol::next_symbol, NULL, and STRING_Symbol::prev_hash.
Referenced by STRING_add_symbol().
Variable Documentation
L_Alloc_Pool* STRING_Symbol_pool = NULL
Definition at line 68 of file string_symbol.c.
Referenced by STRING_add_symbol(), STRING_delete_symbol(), STRING_delete_symbol_table(), and STRING_new_symbol_table().
L_Alloc_Pool* STRING_Symbol_Table_pool = NULL
Definition at line 67 of file string_symbol.c.
Referenced by STRING_delete_symbol_table(), and STRING_new_symbol_table().