symbol.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <library/symbol.h>
Data Structures
struct _SymTbl
Defines
#define MAX 100
Typedefs
typedef _SymTbl * SymTbl
Functions
static void error (char *mesg)
char * StrSave (char *str)
static int Hash (SymTbl tbl, char *name, int type)
int NewSymTbl (int max_size)
void ClearSymTbl (int tbl_id)
void ClearFreeSymTbl (int tbl_id, void(*free_xxx)(void *))
Symbol AddSym (int tbl_id, char *name, int type)
Symbol FindSym (int tbl_id, char *name, int type)
Variables
static _SymTbl TBL [MAX]
static int next_tbl = 0
Define Documentation
#define MAX 100
Definition at line 98 of file symbol.c.
Typedef Documentation
typedef struct _SymTbl * SymTbl
Function Documentation
Symbol AddSym (int tbl_id, char * name, int type)
Add a new symbol in the symbol table.
Definition at line 227 of file symbol.c.
References _SymTbl::array, error(), Hash(), INVALID_SYMBOL, _Symbol::name, next_tbl, _Symbol::ptr, StrSave(), TBL, _Symbol::type, and _Symbol::value.
void ClearFreeSymTbl (int tbl_id, void(*)(void *) free_xxx)
Definition at line 208 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
void ClearSymTbl (int tbl_id)
Clear a symbol table.
Definition at line 192 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
static void error (char * mesg) [static]
Definition at line 74 of file symbol.c.
Symbol FindSym (int tbl_id, char * name, int type)
Find a symbol in the symbol table.
Definition at line 247 of file symbol.c.
References _SymTbl::array, error(), Hash(), INVALID_SYMBOL, next_tbl, TBL, and _Symbol::type.
static int Hash (SymTbl tbl, char * name, int type) [static]
Definition at line 115 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, and _SymTbl::size.
int NewSymTbl (int max_size)
Create a new symbol table.
get next table
Definition at line 162 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, MAX, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
char* StrSave (char * str)
Definition at line 82 of file symbol.c.
Referenced by AddSym().
Variable Documentation
int next_tbl = 0 [static]
Definition at line 108 of file symbol.c.
_SymTbl TBL[MAX] [static]
Definition at line 107 of file symbol.c.