symbol.h File Reference
#include <config.h>
Data Structures
struct _Symbol
Defines
#define INVALID_SYMBOL -1
Typedefs
typedef _Symbol * Symbol
Functions
char * StrSave (char *str)
int NewSymTbl (int max_size)
Symbol AddSym (int tbl_id, char *name, int type)
Symbol FindSym (int tbl_id, char *name, int type)
void ClearSymTbl (int tbl_id)
void ClearFreeSymTbl (int tbl_id, void(*free_xxx)(void *))
Define Documentation
#define INVALID_SYMBOL -1
Definition at line 68 of file symbol.h.
Referenced by AddSym(), ClearFreeSymTbl(), ClearSymTbl(), FindSym(), Hash(), and NewSymTbl().
Typedef Documentation
typedef struct _Symbol * Symbol
Function Documentation
Symbol AddSym (int tbl_id, char * name, int type)
Add a new symbol in the symbol table.
Definition at line 227 of file symbol.c.
References _SymTbl::array, error(), Hash(), INVALID_SYMBOL, _Symbol::name, next_tbl, _Symbol::ptr, StrSave(), TBL, _Symbol::type, and _Symbol::value.
void ClearFreeSymTbl (int tbl_id, void(*)(void *) free_xxx)
Definition at line 208 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
void ClearSymTbl (int tbl_id)
Clear a symbol table.
Definition at line 192 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
Symbol FindSym (int tbl_id, char * name, int type)
Find a symbol in the symbol table.
Definition at line 247 of file symbol.c.
References _SymTbl::array, error(), Hash(), INVALID_SYMBOL, next_tbl, TBL, and _Symbol::type.
int NewSymTbl (int max_size)
Create a new symbol table.
get next table
Definition at line 162 of file symbol.c.
References _SymTbl::array, error(), INVALID_SYMBOL, MAX, _C_Symbol::name, next_tbl, _C_Symbol::ptr, _SymTbl::size, TBL, _C_Symbol::type, and _C_Symbol::value.
char* StrSave (char * str)
Definition at line 82 of file symbol.c.
Referenced by AddSym().