trace.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <library/trace.h>
#include <library/select_sort.h>
#include <library/set.h>
Data Structures
struct Ext
Defines
#define SCALE 5
#define FAVOR_FORWARD 2
#define SECOND_LEVEL_SELECT
#define MAX_SIZE (MAX_GRAPH_SIZE*2)
Functions
static void Punt (char *mesg)
static void FreeExtensionFields (void)
static void AddExtensionFields (FGraph graph)
static double successor_node_weight (Node src, Node dest)
static double predecessor_node_weight (Node src, Node dest)
static double successor_arc_weight (Arc arc)
static double predecessor_arc_weight (Arc arc)
static Arc best_successor_1 (Node node)
static Arc best_predecessor_1 (Node node)
static Arc best_successor_2 (Node node)
static Arc best_predecessor_2 (Node node)
static Arc best_successor_3 (Node node)
static Arc best_predecessor_3 (Node node)
static void SelectTraces (FGraph graph)
void SelectBySortArc (FGraph graph)
static void PlaceTraces (FGraph graph)
void TraceSelection (FGraph graph, int method, double min_prob)
void ReportSelectionResult (FGraph graph, double *matrix)
Variables
static struct Ext others [MAX_GRAPH_SIZE]
static int n_others = 0
static Arc(*) best_successor_of (Node)
static Arc(*) best_predecessor_of (Node)
static double min_prob_requirement = 0.0
Define Documentation
#define FAVOR_FORWARD 2
Definition at line 72 of file trace.c.
Referenced by successor_arc_weight(), and successor_node_weight().
#define MAX_SIZE (MAX_GRAPH_SIZE*2)
Referenced by SelectBySortArc().
#define SCALE 5
Definition at line 71 of file trace.c.
Referenced by predecessor_arc_weight(), predecessor_node_weight(), successor_arc_weight(), and successor_node_weight().
#define SECOND_LEVEL_SELECT
Definition at line 87 of file trace.c.
Function Documentation
static void AddExtensionFields (FGraph graph) [static]
Definition at line 121 of file trace.c.
References Ext::dominator, FreeExtensionFields(), graph, _Node::id, Ext::level, n_others, _Arc::next, nextArc, nextNode, nodeExt, _FGraph::nodes, Ext::order, others, Punt(), _FGraph::root, Set_add(), Set_dispose(), Set_intersect(), Set_same(), Set_union(), sourceArcs, and sourceNode.
Referenced by SelectTraces().
static Arc best_predecessor_1 (Node node) [static]
Definition at line 384 of file trace.c.
References new_node(), nextArc, node, nodeStatus, nodeWeight, predecessor_node_weight(), sourceArcs, sourceNode, and VISITED.
Referenced by TraceSelection().
static Arc best_predecessor_2 (Node node) [static]
Definition at line 468 of file trace.c.
References arcWeight, nextArc, node, nodeStatus, predecessor_arc_weight(), sourceArcs, sourceNode, and VISITED.
Referenced by PlaceTraces(), and TraceSelection().
static Arc best_predecessor_3 (Node node) [static]
Definition at line 555 of file trace.c.
References arcWeight, min_prob_requirement, nextArc, node, nodeStatus, nodeWeight, predecessor_arc_weight(), sourceArcs, sourceNode, and VISITED.
Referenced by TraceSelection().
static Arc best_successor_1 (Node node) [static]
Definition at line 341 of file trace.c.
References destinationArcs, destinationNode, new_node(), nextArc, node, nodeStatus, nodeWeight, successor_node_weight(), and VISITED.
Referenced by TraceSelection().
static Arc best_successor_2 (Node node) [static]
Definition at line 430 of file trace.c.
References arcWeight, destinationArcs, destinationNode, nextArc, node, nodeStatus, successor_arc_weight(), and VISITED.
Referenced by PlaceTraces(), and TraceSelection().
static Arc best_successor_3 (Node node) [static]
Definition at line 510 of file trace.c.
References arcWeight, destinationArcs, destinationNode, min_prob_requirement, nextArc, node, nodeStatus, nodeWeight, successor_arc_weight(), and VISITED.
Referenced by TraceSelection().
static void FreeExtensionFields (void) [static]
Definition at line 110 of file trace.c.
References Ext::dominator, dominator(), n_others, others, and Set_dispose().
Referenced by AddExtensionFields().
static void PlaceTraces (FGraph graph) [static]
Definition at line 1213 of file trace.c.
References AddNode(), arcType, arcWeight, best_predecessor_2(), best_predecessor_of, best_successor_2(), best_successor_of, ConnectNodes(), destinationArcs, destinationNode, FindDestArc(), FindNode(), FindSrcArc(), FreeGraph(), graph, MAX_GRAPH_SIZE, NewGraph(), NewNode(), nextArc, nextNode, node, nodeId, _FGraph::nodes, nodeStatus, nodeType, nodeWeight, Punt(), _FGraph::root, SelectTraces(), sourceArcs, TRACE_HEAD, TRACE_TAIL, VISITED, and WriteGraph().
Referenced by TraceSelection().
static double predecessor_arc_weight (Arc arc) [static]
Definition at line 312 of file trace.c.
References arcWeight, destinationNode, Ext::level, nodeExt, SCALE, and sourceNode.
Referenced by best_predecessor_2(), and best_predecessor_3().
static double predecessor_node_weight (Node src, Node dest) [static]
Definition at line 269 of file trace.c.
References Ext::level, nodeExt, nodeWeight, and SCALE.
Referenced by best_predecessor_1().
static void Punt (char * mesg) [static]
Definition at line 91 of file trace.c.
void ReportSelectionResult (FGraph graph, double * matrix)
Definition at line 1545 of file trace.c.
References arcType, arcWeight, destinationArcs, destinationNode, graph, L_LOOP, L_TRACE, LOOP_HEAD, N_ARCS, N_LEAF, N_LOOP, N_NODES, N_ROOT, N_TRACE, nextArc, nextNode, node, _FGraph::nodes, nodeStatus, nodeType, nodeWeight, Punt(), sourceArcs, sourceNode, TRACE_HEAD, TRACE_TAIL, VISITED, W_A, W_ARCS, W_B, W_BACK_EDGE, W_C, W_D, W_E, W_NODES, W_SEQUENTIAL, and WriteGraph().
void SelectBySortArc (FGraph graph)
Definition at line 1015 of file trace.c.
References arcType, arcWeight, destinationArcs, destinationNode, graph, LOOP_HEAD, MAX_GRAPH_SIZE, MAX_SIZE, max_sort(), nextArc, nextNode, _FGraph::nodes, nodeStatus, nodeType, NOT_VISITED, ST_Entry::ptr, Punt(), _FGraph::root, sourceArcs, sourceNode, TRACE_HEAD, TRACE_TAIL, and VISITED.
Referenced by TraceSelection().
static void SelectTraces (FGraph graph) [static]
Definition at line 600 of file trace.c.
References AddExtensionFields(), arcType, best_predecessor_of, best_successor_of, destinationArcs, destinationNode, Ext::dominator, FindDestArc(), FindSrcArc(), graph, ST_Entry::index, LOOP_HEAD, MAX_GRAPH_SIZE, max_sort(), nextArc, nextNode, nodeExt, _FGraph::nodes, nodeStatus, nodeType, nodeWeight, NOT_VISITED, Ext::order, ST_Entry::ptr, Punt(), _FGraph::root, Set_in(), sourceArcs, sourceNode, successor_node_weight(), TRACE_HEAD, TRACE_TAIL, VISITED, and ST_Entry::weight.
Referenced by PlaceTraces(), and TraceSelection().
static double successor_arc_weight (Arc arc) [static]
Definition at line 288 of file trace.c.
References arcWeight, destinationNode, FAVOR_FORWARD, Ext::level, nodeExt, SCALE, and sourceNode.
Referenced by best_successor_2(), and best_successor_3().
static double successor_node_weight (Node src, Node dest) [static]
Definition at line 245 of file trace.c.
References FAVOR_FORWARD, Ext::level, nodeExt, nodeWeight, and SCALE.
Referenced by best_successor_1(), and SelectTraces().
void TraceSelection (FGraph graph, int method, double min_prob)
Definition at line 1492 of file trace.c.
References best_predecessor_1(), best_predecessor_2(), best_predecessor_3(), best_predecessor_of, best_successor_1(), best_successor_2(), best_successor_3(), best_successor_of, graph, min_prob_requirement, PlaceTraces(), Punt(), SELECT_BY_ARC_WEIGHT, SELECT_BY_MAX_ARC, SELECT_BY_MIN_PROB, SELECT_BY_NODE_WEIGHT, SelectBySortArc(), SelectTraces(), and WriteGraph().
Variable Documentation
Arc(*) best_predecessor_of(Node) [static]
Definition at line 335 of file trace.c.
Referenced by PlaceTraces(), SelectTraces(), and TraceSelection().
Arc(*) best_successor_of(Node) [static]
Definition at line 334 of file trace.c.
Referenced by PlaceTraces(), SelectTraces(), and TraceSelection().
double min_prob_requirement = 0.0 [static]
Definition at line 336 of file trace.c.
Referenced by best_predecessor_3(), best_successor_3(), and TraceSelection().
int n_others = 0 [static]
Definition at line 107 of file trace.c.
Referenced by AddExtensionFields(), and FreeExtensionFields().
struct Ext
 others[MAX_GRAPH_SIZE] [static]
Referenced by AddExtensionFields(), and FreeExtensionFields().