md_preprocessor.c File Reference
#include <config.h>
#include `md_preprocessor.h`
Functions
void print_usage (char *fmt,...)
void read_command_line_parameters (int argc, char **arg_ptr)
void L_punt (char *fmt,...)
void Perror (Pptr *pptr, char *fmt,...)
void Pputc (Pptr *pptr, int ch)
int main (int argc, char **argv, char **envp)
Pptr * process_body (Pptr *pptr)
Pptr * skip_body (Pptr *pptr)
Pptr * process_def_directive (Pptr *pptr)
Pptr * process_undef_directive (Pptr *pptr)
Value_List * get_for_value_list (Pptr *pptr, Pptr *placemark)
Pptr * process_for_directive (Pptr *pptr, Pptr *placemark)
Pptr * process_if_directive (Pptr *pptr, Pptr *placemark)
Pptr * process_include_directive (Pptr *pptr, Pptr *placemark)
Pptr * process_directive (Pptr *pptr)
char * Pget_alnum_string (Pptr *pptr)
char * Pget_identifier (Pptr *pptr)
char * Pget_stripped_line (Pptr *pptr)
char * Pget_quoted_string (Pptr *pptr, int strip_quotes)
char * Pget_for_string (Pptr *pptr)
char * Pget_bounded_string (Pptr *pptr)
void Pskip_whitespace (Pptr *pptr)
void Pskip_whitespace_no_nl (Pptr *pptr)
Pptr * create_Pptr (Mfile *mfile)
Pptr * copy_Pptr (Pptr *orig_pptr)
void move_Pptr (Pptr *old_pptr, Pptr *new_pptr)
void free_Pptr (Pptr *pptr)
void Pexpand_directive (Pptr *source_pptr)
int Pexpand_text (Pptr *pptr)
int Pgetc (Pptr *pptr)
int Ppeekc (Pptr *pptr)
int Pcalc_C_int_expr (Pptr *pptr, int current_precedence)
int Pcalc_C_int_factor (Pptr *pptr)
double Pcalc_C_float_expr (Pptr *pptr, int current_precedence)
double Pcalc_C_float_factor (Pptr *pptr)
Pdef * create_Pdef (char *name, char *val, int allow_implicit_replacement, int level)
void free_Pdef (void *def_v)
void add_Pdef (char *name, char *val, int allow_implicit_replacement, int level)
void delete_Pdef (char *name)
char * Plookup (char *name, int implicit_replacement)
Variables
FILE * out
Mfile * current_file
Psymbol_Table * Pdef_table = NULL
Psymbol_Table * Mfile_table = NULL
int allow_text_replacement = 1
int disable_implicit_text_replacement = 0
Mbuf * temp_mbuf = NULL
Mbuf * pptr_mbuf = NULL
Pptr * temp_placemark = NULL
Mptr * expand_placemark = NULL
L_Alloc_Pool * Pptr_pool = NULL
L_Alloc_Pool * Pdef_pool = NULL
L_Alloc_Pool * String_Node_pool = NULL
L_Alloc_Pool * Value_List_pool = NULL
char * program_name = NULL
char * input_file_name = NULL
char * output_file_name = NULL
int using_stdin = 0
int print_line_directives = 1
int print_alloc_usage = 0
Function Documentation
void add_Pdef (char * name, char * val, int allow_implicit_replacement, int level)
Definition at line 3492 of file md_preprocessor.c.
References add_Psymbol(), Pdef::allow_implicit_replacement, create_Pdef(), Psymbol::data, find_Psymbol(), Pdef::level, NULL, Pdef_table, and Pdef::val.
Referenced by main(), process_def_directive(), and read_command_line_parameters().
Pptr* copy_Pptr (Pptr * orig_pptr)
Definition at line 2149 of file md_preprocessor.c.
References adds_to_Mbuf(), copy_Mptr(), create_Mbuf(), Pptr::expanded, Pptr::expanded_pos, get_Mbuf_buf(), L_alloc(), Pptr::mptr, Pptr_pool, Pptr::quoted, and Pptr::scanned.
Referenced by Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), and process_directive().
Pdef* create_Pdef (char * name, char * val, int allow_implicit_replacement, int level)
Definition at line 3470 of file md_preprocessor.c.
References Pdef::allow_implicit_replacement, L_alloc(), Pdef::level, Pdef::name, Pdef_pool, and Pdef::val.
Referenced by add_Pdef().
Pptr* create_Pptr (Mfile * mfile)
Definition at line 2133 of file md_preprocessor.c.
References create_Mbuf(), create_Mptr(), Pptr::expanded, Pptr::expanded_pos, L_alloc(), Pptr::mptr, Pptr_pool, Pptr::quoted, and Pptr::scanned.
Referenced by main(), and process_include_directive().
void delete_Pdef (char * name)
Definition at line 3521 of file md_preprocessor.c.
References delete_Psymbol(), find_Psymbol(), free_Pdef(), NULL, and Pdef_table.
Referenced by process_undef_directive().
void free_Pdef (void * def_v)
Definition at line 3482 of file md_preprocessor.c.
References L_free(), Pdef::name, Pdef_pool, and Pdef::val.
Referenced by delete_Pdef(), and main().
void free_Pptr (Pptr * pptr)
Definition at line 2189 of file md_preprocessor.c.
References Pptr::expanded, free_Mbuf(), free_Mptr(), L_free(), Pptr::mptr, and Pptr_pool.
Referenced by main(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), process_directive(), and process_include_directive().
Value_List* get_for_value_list (Pptr * pptr, Pptr * placemark)
Definition at line 1091 of file md_preprocessor.c.
References Value_List::allow_implicit_replacement, disable_implicit_text_replacement, Value_List::first_value, L_alloc(), Value_List::last_value, move_Pptr(), Value_List::name, String_Node::next, NULL, Perror(), Pget_for_string(), Pget_identifier(), Pgetc(), Ppeekc(), Pskip_whitespace(), String_Node::string, String_Node_pool, Value_List::value_count, and Value_List_pool.
Referenced by process_for_directive().
void L_punt (char * fmt, ...)
Definition at line 353 of file md_preprocessor.c.
Referenced by main(), move_Pptr(), Pget_bounded_string(), and process_directive().
int main (int argc, char ** argv, char ** envp)
Definition at line 586 of file md_preprocessor.c.
References add_Pdef(), add_Psymbol(), create_Mbuf(), create_Mfile(), create_Mptr(), create_Pptr(), create_Psymbol_Table(), current_file, expand_placemark, free_Mbuf(), free_Mfile(), free_Mptr(), free_Pdef(), free_Pptr(), free_Psymbol_Table(), input_file_name, L_create_alloc_pool(), L_free_alloc_pool(), L_print_alloc_info(), L_punt(), Mbuf_pool, Mfile_pool, Mfile_table, Mline_pool, Mptr_pool, name, NULL, out, output_file_name, Pdef_pool, Pdef_table, Pgetc(), Ppeekc(), pptr_mbuf, Pptr_pool, Pputc(), print_alloc_usage, process_body(), Psymbol_pool, Psymbol_Table_pool, read_command_line_parameters(), String_Node_pool, temp_mbuf, temp_placemark, using_stdin, and Value_List_pool.
void move_Pptr (Pptr * old_pptr, Pptr * new_pptr)
Definition at line 2171 of file md_preprocessor.c.
References adds_to_Mbuf(), clear_Mbuf(), Pptr::expanded, Pptr::expanded_pos, get_Mbuf_buf(), L_punt(), move_Mptr(), Pptr::mptr, Pptr::quoted, and Pptr::scanned.
Referenced by get_for_value_list(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pget_bounded_string(), Pget_for_string(), Pget_quoted_string(), process_def_directive(), process_for_directive(), and process_if_directive().
double Pcalc_C_float_expr (Pptr * pptr, int current_precedence)
Definition at line 3102 of file md_preprocessor.c.
References copy_Pptr(), free_Pptr(), move_Pptr(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Perror(), Pgetc(), Ppeekc(), and Pskip_whitespace().
Referenced by Pcalc_C_float_expr(), Pcalc_C_float_factor(), and Pexpand_directive().
double Pcalc_C_float_factor (Pptr * pptr)
Definition at line 3272 of file md_preprocessor.c.
References addc_to_Mbuf(), copy_Pptr(), create_Mbuf(), free_Mbuf(), free_Pptr(), get_Mbuf_buf(), move_Pptr(), Pcalc_C_float_expr(), Perror(), Pgetc(), Ppeekc(), and Pskip_whitespace().
Referenced by Pcalc_C_float_expr().
int Pcalc_C_int_expr (Pptr * pptr, int current_precedence)
Definition at line 2777 of file md_preprocessor.c.
References copy_Pptr(), free_Pptr(), move_Pptr(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Perror(), Pgetc(), Ppeekc(), and Pskip_whitespace().
Referenced by Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), and process_if_directive().
int Pcalc_C_int_factor (Pptr * pptr)
Definition at line 2950 of file md_preprocessor.c.
References copy_Pptr(), free_Pptr(), move_Pptr(), Pcalc_C_int_expr(), Perror(), Pgetc(), Ppeekc(), and Pskip_whitespace().
Referenced by Pcalc_C_int_expr(), and Pexpand_directive().
void Perror (Pptr * pptr, char * fmt, ...)
Definition at line 373 of file md_preprocessor.c.
References Mline::buf, Mbuf::buf, Mbuf::cur_len, Pptr::expanded, Mline::line_no, Mbackupc(), Mptr::mfile, Mptr::mline, Pptr::mptr, Mfile::name, NULL, and Mptr::pos.
Referenced by get_for_value_list(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), Pget_bounded_string(), Pget_for_string(), Pget_identifier(), Pget_quoted_string(), process_def_directive(), process_directive(), process_for_directive(), process_if_directive(), and process_include_directive().
void Pexpand_directive (Pptr * source_pptr)
Definition at line 2203 of file md_preprocessor.c.
References addc_to_Mbuf(), adds_to_Mbuf(), allow_text_replacement, copy_Pptr(), create_Mbuf(), disable_implicit_text_replacement, Pptr::expanded, Pptr::expanded_pos, free_Mbuf(), free_Pptr(), get_Mbuf_buf(), Merror(), Mgetc(), move_Mptr(), Mpeekc(), Pptr::mptr, NULL, Pcalc_C_float_expr(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Perror(), Pgetc(), Plookup(), Ppeekc(), Pskip_whitespace(), and Pptr::scanned.
Referenced by Pexpand_text().
int Pexpand_text (Pptr * pptr)
Definition at line 2542 of file md_preprocessor.c.
References addc_to_Mbuf(), adds_to_Mbuf(), allow_text_replacement, clear_Mbuf(), Mbuf::cur_len, disable_implicit_text_replacement, expand_placemark, Pptr::expanded, Pptr::expanded_pos, get_Mbuf_buf(), Merror(), Mgetc(), move_Mptr(), Mpeekc(), Pptr::mptr, Mptr_pos(), NULL, Pexpand_directive(), Plookup(), pptr_mbuf, Pptr::quoted, and Pptr::scanned.
Referenced by Pgetc(), and Ppeekc().
char* Pget_alnum_string (Pptr * pptr)
Definition at line 1758 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), Pgetc(), Ppeekc(), and temp_mbuf.
Referenced by process_directive(), and process_if_directive().
char* Pget_bounded_string (Pptr * pptr)
Definition at line 2034 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), L_punt(), move_Pptr(), Perror(), Pgetc(), Ppeekc(), Pskip_whitespace_no_nl(), temp_mbuf, and temp_placemark.
Referenced by Pget_for_string(), and process_def_directive().
char* Pget_for_string (Pptr * pptr)
Definition at line 1936 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), move_Pptr(), Perror(), Pget_bounded_string(), Pget_quoted_string(), Pgetc(), Ppeekc(), Pskip_whitespace_no_nl(), temp_mbuf, and temp_placemark.
Referenced by get_for_value_list().
char* Pget_identifier (Pptr * pptr)
Definition at line 1784 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), Perror(), Pgetc(), Ppeekc(), and temp_mbuf.
Referenced by get_for_value_list(), process_def_directive(), and process_undef_directive().
char* Pget_quoted_string (Pptr * pptr, int strip_quotes)
Definition at line 1852 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), move_Pptr(), Perror(), Pgetc(), Ppeekc(), Pskip_whitespace_no_nl(), temp_mbuf, and temp_placemark.
Referenced by Pget_for_string(), and process_include_directive().
char* Pget_stripped_line (Pptr * pptr)
Definition at line 1821 of file md_preprocessor.c.
References addc_to_Mbuf(), clear_Mbuf(), copy_Mbuf_buf(), Pgetc(), Ppeekc(), Pskip_whitespace_no_nl(), strip_Mbuf(), and temp_mbuf.
Referenced by process_def_directive().
int Pgetc (Pptr * pptr)
Definition at line 2732 of file md_preprocessor.c.
References get_Mbuf_buf(), and Pexpand_text().
Referenced by get_for_value_list(), main(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), Pget_alnum_string(), Pget_bounded_string(), Pget_for_string(), Pget_identifier(), Pget_quoted_string(), Pget_stripped_line(), process_body(), process_def_directive(), process_directive(), process_for_directive(), process_if_directive(), process_include_directive(), Pskip_whitespace(), Pskip_whitespace_no_nl(), and skip_body().
char* Plookup (char * name, int implicit_replacement)
Definition at line 3535 of file md_preprocessor.c.
References Pdef::allow_implicit_replacement, Psymbol::data, find_Psymbol(), NULL, Pdef_table, and Pdef::val.
Referenced by Pexpand_directive(), and Pexpand_text().
int Ppeekc (Pptr * pptr)
Definition at line 2755 of file md_preprocessor.c.
References get_Mbuf_buf(), and Pexpand_text().
Referenced by get_for_value_list(), main(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), Pget_alnum_string(), Pget_bounded_string(), Pget_for_string(), Pget_identifier(), Pget_quoted_string(), Pget_stripped_line(), process_body(), process_def_directive(), process_for_directive(), process_if_directive(), process_include_directive(), Pskip_whitespace(), Pskip_whitespace_no_nl(), and skip_body().
void Pputc (Pptr * pptr, int ch)
Definition at line 503 of file md_preprocessor.c.
References Mline::line_no, Mptr::mfile, Mptr::mline, Pptr::mptr, Mfile::name, NULL, out, and print_line_directives.
Referenced by main(), process_body(), and process_include_directive().
void print_usage (char * fmt, ...)
Definition at line 154 of file md_preprocessor.c.
References NULL, and program_name.
Referenced by read_command_line_parameters().
Pptr* process_body (Pptr * pptr)
Definition at line 763 of file md_preprocessor.c.
References Pgetc(), Ppeekc(), Pputc(), and process_directive().
Referenced by main(), process_if_directive(), and process_include_directive().
Pptr* process_def_directive (Pptr * pptr)
Definition at line 944 of file md_preprocessor.c.
References add_Pdef(), disable_implicit_text_replacement, move_Pptr(), name, Perror(), Pget_bounded_string(), Pget_identifier(), Pget_stripped_line(), Pgetc(), Ppeekc(), Pskip_whitespace_no_nl(), and temp_placemark.
Referenced by process_directive().
Pptr* process_directive (Pptr * pptr)
Definition at line 1648 of file md_preprocessor.c.
References copy_Pptr(), free_Pptr(), L_punt(), Perror(), Pget_alnum_string(), Pgetc(), process_def_directive(), process_for_directive(), process_if_directive(), process_include_directive(), and process_undef_directive().
Referenced by process_body().
Pptr* process_for_directive (Pptr * pptr, Pptr * placemark)
Definition at line 1205 of file md_preprocessor.c.
References get_for_value_list(), move_Pptr(), Value_List::name, Value_List::next_list, NULL, Perror(), Pgetc(), Ppeekc(), Pskip_whitespace(), and Value_List::value_count.
Referenced by process_directive().
Pptr* process_if_directive (Pptr * pptr, Pptr * placemark)
Definition at line 1393 of file md_preprocessor.c.
References move_Pptr(), Pcalc_C_int_expr(), Perror(), Pget_alnum_string(), Pgetc(), Ppeekc(), process_body(), Pskip_whitespace(), and skip_body().
Referenced by process_directive().
Pptr* process_include_directive (Pptr * pptr, Pptr * placemark)
Definition at line 1560 of file md_preprocessor.c.
References add_Psymbol(), create_Mfile(), create_Pptr(), Psymbol::data, find_Psymbol(), free_Pptr(), Mfile_table, Pptr::mptr, Mfile::name, NULL, Perror(), Pget_quoted_string(), Pgetc(), Mptr::pos, Ppeekc(), Pputc(), process_body(), and Pskip_whitespace_no_nl().
Referenced by process_directive().
Pptr* process_undef_directive (Pptr * pptr)
Definition at line 1062 of file md_preprocessor.c.
References delete_Pdef(), disable_implicit_text_replacement, name, Pget_identifier(), and Pskip_whitespace_no_nl().
Referenced by process_directive().
void Pskip_whitespace (Pptr * pptr)
Definition at line 2105 of file md_preprocessor.c.
References Pgetc(), and Ppeekc().
Referenced by get_for_value_list(), Pcalc_C_float_expr(), Pcalc_C_float_factor(), Pcalc_C_int_expr(), Pcalc_C_int_factor(), Pexpand_directive(), process_for_directive(), and process_if_directive().
void Pskip_whitespace_no_nl (Pptr * pptr)
Definition at line 2118 of file md_preprocessor.c.
References Pgetc(), and Ppeekc().
Referenced by Pget_bounded_string(), Pget_for_string(), Pget_quoted_string(), Pget_stripped_line(), process_def_directive(), process_include_directive(), and process_undef_directive().
void read_command_line_parameters (int argc, char ** arg_ptr)
Definition at line 193 of file md_preprocessor.c.
References add_Pdef(), bypass_alloc_routines, input_file_name, name, NULL, output_file_name, print_alloc_usage, print_line_directives, print_usage(), program_name, and using_stdin.
Referenced by main().
Pptr* skip_body (Pptr * pptr)
Definition at line 858 of file md_preprocessor.c.
References allow_text_replacement, Pgetc(), and Ppeekc().
Referenced by process_if_directive().
Variable Documentation
int allow_text_replacement = 1
Definition at line 116 of file md_preprocessor.c.
Referenced by Pexpand_directive(), Pexpand_text(), and skip_body().
Mfile* current_file
Definition at line 107 of file md_preprocessor.c.
int disable_implicit_text_replacement = 0
Definition at line 127 of file md_preprocessor.c.
Referenced by get_for_value_list(), Pexpand_directive(), Pexpand_text(), process_def_directive(), and process_undef_directive().
Mptr* expand_placemark = NULL
Definition at line 135 of file md_preprocessor.c.
Referenced by main(), and Pexpand_text().
char* input_file_name = NULL
Definition at line 146 of file md_preprocessor.c.
Referenced by main(), and read_command_line_parameters().
Psymbol_Table* Mfile_table = NULL
Definition at line 111 of file md_preprocessor.c.
Referenced by main(), and process_include_directive().
FILE* out
Definition at line 104 of file md_preprocessor.c.
Referenced by main(), and Pputc().
char* output_file_name = NULL
Definition at line 147 of file md_preprocessor.c.
Referenced by main(), and read_command_line_parameters().
L_Alloc_Pool* Pdef_pool = NULL
Definition at line 139 of file md_preprocessor.c.
Referenced by create_Pdef(), free_Pdef(), and main().
Psymbol_Table* Pdef_table = NULL
Definition at line 110 of file md_preprocessor.c.
Referenced by add_Pdef(), delete_Pdef(), main(), and Plookup().
Mbuf* pptr_mbuf = NULL
Definition at line 131 of file md_preprocessor.c.
Referenced by main(), and Pexpand_text().
L_Alloc_Pool* Pptr_pool = NULL
Definition at line 138 of file md_preprocessor.c.
Referenced by copy_Pptr(), create_Pptr(), free_Pptr(), and main().
int print_alloc_usage = 0
Definition at line 150 of file md_preprocessor.c.
Referenced by main(), and read_command_line_parameters().
int print_line_directives = 1
Definition at line 149 of file md_preprocessor.c.
Referenced by Pputc(), and read_command_line_parameters().
char* program_name = NULL
Definition at line 143 of file md_preprocessor.c.
Referenced by print_usage(), and read_command_line_parameters().
L_Alloc_Pool* String_Node_pool = NULL
Definition at line 140 of file md_preprocessor.c.
Referenced by get_for_value_list(), and main().
Mbuf* temp_mbuf = NULL
Definition at line 130 of file md_preprocessor.c.
Referenced by main(), Pget_alnum_string(), Pget_bounded_string(), Pget_for_string(), Pget_identifier(), Pget_quoted_string(), and Pget_stripped_line().
Pptr* temp_placemark = NULL
Definition at line 134 of file md_preprocessor.c.
Referenced by main(), Pget_bounded_string(), Pget_for_string(), Pget_quoted_string(), and process_def_directive().
int using_stdin = 0
Definition at line 148 of file md_preprocessor.c.
Referenced by main(), and read_command_line_parameters().
L_Alloc_Pool* Value_List_pool = NULL
Definition at line 141 of file md_preprocessor.c.
Referenced by get_for_value_list(), and main().