psymbol.h File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <library/l_alloc_new.h>
Data Structures
struct Psymbol
struct Psymbol_Table
Defines
#define PSYMBOL_HASH_SIZE 32
Functions
Psymbol_Table * create_Psymbol_Table (char *name)
void free_Psymbol_Table (Psymbol_Table *table, void(*free_routine)(void *))
int hash_Psymbol_name (char *name)
void add_Psymbol (Psymbol_Table *table, char *name, void *data)
Psymbol * find_Psymbol (Psymbol_Table *table, char *name)
void delete_Psymbol (Psymbol *symbol, void(*free_routine)(void *))
void print_Psymbol_hash_table (FILE *out, Psymbol_Table *table)
Variables
L_Alloc_Pool * Psymbol_Table_pool
L_Alloc_Pool * Psymbol_pool
Define Documentation
#define PSYMBOL_HASH_SIZE 32
Definition at line 70 of file psymbol.h.
Referenced by create_Psymbol_Table(), hash_Psymbol_name(), and print_Psymbol_hash_table().
Function Documentation
void add_Psymbol (Psymbol_Table * table, char * name, void * data)
Definition at line 147 of file psymbol.c.
References Psymbol_Table::count, Psymbol::data, Psymbol_Table::hash, hash_Psymbol_name(), Psymbol_Table::head, L_alloc(), L_create_alloc_pool(), Psymbol::name, Psymbol::next_hash, Psymbol::next_symbol, NULL, Psymbol::prev_hash, Psymbol::prev_symbol, Psymbol_pool, Psymbol::table, and Psymbol_Table::tail.
Referenced by add_Pdef(), main(), and process_include_directive().
Psymbol_Table* create_Psymbol_Table (char * name)
Definition at line 72 of file psymbol.c.
References Psymbol_Table::count, Psymbol_Table::hash, Psymbol_Table::head, L_alloc(), L_create_alloc_pool(), Psymbol_Table::name, NULL, PSYMBOL_HASH_SIZE, Psymbol_Table_pool, and Psymbol_Table::tail.
Referenced by main().
void delete_Psymbol (Psymbol * symbol, void(*)(void *) free_routine)
Definition at line 212 of file psymbol.c.
References Psymbol_Table::count, Psymbol::data, Psymbol_Table::hash, hash_Psymbol_name(), Psymbol_Table::head, L_free(), Psymbol::name, Psymbol::next_hash, Psymbol::next_symbol, NULL, Psymbol::prev_hash, Psymbol::prev_symbol, Psymbol_pool, Psymbol::table, and Psymbol_Table::tail.
Referenced by delete_Pdef().
Psymbol* find_Psymbol (Psymbol_Table * table, char * name)
Definition at line 191 of file psymbol.c.
References Psymbol_Table::hash, hash_Psymbol_name(), Psymbol::name, Psymbol::next_hash, and NULL.
Referenced by add_Pdef(), delete_Pdef(), Plookup(), and process_include_directive().
void free_Psymbol_Table (Psymbol_Table * table, void(*)(void *) free_routine)
Definition at line 97 of file psymbol.c.
References Psymbol::data, Psymbol_Table::head, L_free(), Psymbol_Table::name, Psymbol::name, Psymbol::next_symbol, NULL, Psymbol_pool, and Psymbol_Table_pool.
Referenced by main().
int hash_Psymbol_name (char * name)
Definition at line 125 of file psymbol.c.
References PSYMBOL_HASH_SIZE.
Referenced by add_Psymbol(), delete_Psymbol(), and find_Psymbol().
void print_Psymbol_hash_table (FILE * out, Psymbol_Table * table)
Definition at line 257 of file psymbol.c.
References Psymbol_Table::count, Psymbol_Table::hash, Psymbol::name, Psymbol_Table::name, Psymbol::next_hash, NULL, and PSYMBOL_HASH_SIZE.
Variable Documentation
L_Alloc_Pool* Psymbol_pool
Definition at line 68 of file psymbol.c.
Referenced by add_Psymbol(), delete_Psymbol(), free_Psymbol_Table(), and main().
L_Alloc_Pool* Psymbol_Table_pool
Definition at line 67 of file psymbol.c.
Referenced by create_Psymbol_Table(), free_Psymbol_Table(), and main().