m_arm.h File Reference
#include <machine/m_spec.h>
Defines
#define INT_2EXP13 0x2000
#define INT_2EXP10 0x400
#define INT_2EXP4 0x10
#define MAX_INT_NAME 22
#define FIELD_5(a) ((((a) >= -INT_2EXP4)&&((a) < INT_2EXP4))?1:0)
#define FIELD_11(a) ((((a) >= -INT_2EXP10)&&((a) < INT_2EXP10))?1:0)
#define FIELD_14(a) ((((a) >= -INT_2EXP13)&&((a) < INT_2EXP13))?1:0)
Enumerations
enum { M_ARM_1_01 = 1
 }
enum {
ARM_MAC_LEAF = 100,
ARM_MAC_ALLOC,
ARM_MAC_CALLEE_I,
ARM_MAC_TRUE_SP,
ARM_MAC_RETADDR,
ARM_MAC_FZERO,
ARM_MAC_FONE,
ARM_MAC_LAST
 }
Functions
int M_arm_type_size (int mtype)
int M_arm_type_align (int mtype)
void M_arm_void (M_Type type)
void M_arm_bit_long (M_Type type, int n)
void M_arm_bit_int (M_Type type, int n)
void M_arm_bit_short (M_Type type, int n)
void M_arm_bit_char (M_Type type, int n)
void M_arm_char (M_Type type, int unsign)
void M_arm_short (M_Type type, int unsign)
void M_arm_int (M_Type type, int unsign)
void M_arm_long (M_Type type, int unsign)
void M_arm_float (M_Type type, int unsign)
void M_arm_double (M_Type type, int unsign)
void M_arm_pointer (M_Type type)
int M_arm_eval_type (M_Type type, M_Type ntype)
int M_arm_eval_type2 (M_Type type, M_Type ntype)
int M_arm_call_type (M_Type type, M_Type ntype)
int M_arm_call_type2 (M_Type type, M_Type ntype)
void M_arm_array_layout (M_Type type, int *offset)
int M_arm_array_align (M_Type type)
int M_arm_array_size (M_Type type, int dim)
void M_arm_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_arm_union_align (int n, _M_Type *type)
int M_arm_union_size (int n, _M_Type *type)
void M_arm_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_arm_struct_align (int n, _M_Type *type)
int M_arm_struct_size (int n, _M_Type *type, int struct_align)
int M_arm_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose, int needs_st)
int M_arm_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_arm_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_arm_no_short_int (void)
int M_arm_layout_order (void)
void M_arm_cb_label_name (char *fn, int cb, char *line, int len)
int M_arm_is_cb_label (char *label, char *fn, int *cb)
void M_arm_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_arm_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_arm_structure_pointer (int purpose)
int M_arm_return_register (int type, int purpose)
char * M_arm_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_arm_fn_name_from_label (char *label)
void M_set_model_arm (char *model_name)
int M_arm_fragile_macro (int macro_value)
Set M_arm_fragile_macro_set ()
int M_arm_dataflow_macro (int id)
int M_arm_subroutine_call (int opc)
void M_define_macros_arm (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_arm (int id)
void M_define_opcode_name_arm (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_arm (int id)
int M_oper_supported_in_arch_arm (int opc)
int M_num_oper_required_for_arm (L_Oper *oper, char *name)
int M_is_stack_operand_arm (L_Operand *operand)
int M_is_unsafe_macro_arm (L_Operand *operand)
int M_operand_type_arm (L_Operand *operand)
int M_conflicting_operands_arm (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_arm (int ctype)
Define Documentation
#define FIELD_11(a) ((((a) >= -INT_2EXP10)&&((a) < INT_2EXP10))?1:0)
Definition at line 181 of file m_arm.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define FIELD_14(a) ((((a) >= -INT_2EXP13)&&((a) < INT_2EXP13))?1:0)
Definition at line 182 of file m_arm.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define FIELD_5(a) ((((a) >= -INT_2EXP4)&&((a) < INT_2EXP4))?1:0)
Definition at line 180 of file m_arm.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define INT_2EXP10 0x400
Definition at line 175 of file m_arm.h.
#define INT_2EXP13 0x2000
Definition at line 174 of file m_arm.h.
#define INT_2EXP4 0x10
Definition at line 176 of file m_arm.h.
#define MAX_INT_NAME 22
Definition at line 178 of file m_arm.h.
Referenced by M_conflicting_operands_hppa().
Enumeration Type Documentation
anonymous enum
Enumerator:
M_ARM_1_01
Definition at line 156 of file m_arm.h.
anonymous enum
Enumerator:
ARM_MAC_LEAF
ARM_MAC_ALLOC
ARM_MAC_CALLEE_I
ARM_MAC_TRUE_SP
ARM_MAC_RETADDR
ARM_MAC_FZERO
ARM_MAC_FONE
ARM_MAC_LAST
Definition at line 161 of file m_arm.h.
Function Documentation
int M_arm_array_align (M_Type type)
Definition at line 438 of file ml_arm.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_arm_array_layout (M_Type type, int * offset)
Definition at line 433 of file ml_arm.c.
Referenced by M_array_layout().
int M_arm_array_size (M_Type type, int dim)
Definition at line 443 of file ml_arm.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_arm_bit_char (M_Type type, int n)
Definition at line 241 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_arm_bit_int (M_Type type, int n)
Definition at line 221 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_arm_bit_long (M_Type type, int n)
Definition at line 211 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_arm_bit_short (M_Type type, int n)
Definition at line 231 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_arm_call_type (M_Type type, M_Type ntype)
Definition at line 358 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_arm_call_type2 (M_Type type, M_Type ntype)
Definition at line 394 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_pointer(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_arm_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1191 of file ml_arm.c.
Referenced by M_cb_label_name().
void M_arm_char (M_Type type, int unsign)
Definition at line 239 of file mi_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_CHAR, M_ARM_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char().
int M_arm_dataflow_macro (int id)
void M_arm_double (M_Type type, int unsign)
Definition at line 260 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_DOUBLE, M_ARM_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_arm_eval_type (M_Type type, M_Type ntype)
Definition at line 279 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_arm_eval_type2 (M_Type type, M_Type ntype)
Definition at line 314 of file ml_arm.c.
References M_arm_llong(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_arm_float (M_Type type, int unsign)
Definition at line 251 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_FLOAT, M_ARM_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_arm_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1259 of file ml_arm.c.
Referenced by M_fn_label_name().
char* M_arm_fn_name_from_label (char * label)
Definition at line 1271 of file ml_arm.c.
Referenced by M_fn_name_from_label().
int M_arm_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 923 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_align_offset(), M_ARM_DBL_BASE, M_ARM_FLT_BASE, M_ARM_INT_BASE, M_ARM_MAX_FNVAR_REG, M_ARM_SIZE_DOUBLE, M_ARM_SIZE_FLOAT, M_ARM_SIZE_INT, M_ARM_SIZE_LLONG, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_arm_fragile_macro (int macro_value)
Definition at line 1280 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_fragile_macro().
Set M_arm_fragile_macro_set ()
void M_arm_int (M_Type type, int unsign)
Definition at line 257 of file mi_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_INT, M_ARM_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int().
int M_arm_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1196 of file ml_arm.c.
Referenced by M_is_cb_label().
int M_arm_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1207 of file ml_arm.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_arm_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1201 of file ml_arm.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_arm_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose, int needs_st)
Definition at line 692 of file ml_arm.c.
References _struct_M_Type::align, List_next(), List_start(), M_ARM_align_offset(), M_ARM_DBL_BASE, M_ARM_FLT_BASE, M_ARM_INT_BASE, M_ARM_MAX_FNVAR_REG, M_ARM_SIZE_DOUBLE, M_ARM_SIZE_FLOAT, M_ARM_SIZE_INT, M_ARM_SIZE_LLONG, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_arm_layout_order (void)
Definition at line 284 of file mi_arm.c.
References M_BIG_ENDIAN.
Referenced by M_layout_order().
void M_arm_long (M_Type type, int unsign)
Definition at line 266 of file mi_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_LONG, M_ARM_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long().
int M_arm_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1147 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_MAX, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_arm_no_short_int (void)
Definition at line 1187 of file ml_arm.c.
References M_ARM_SIZE_INT, and M_ARM_SIZE_SHORT.
Referenced by M_no_short_int().
void M_arm_pointer (M_Type type)
Definition at line 269 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_POINTER, M_ARM_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_arm_return_register (int type, int purpose)
Definition at line 1244 of file ml_arm.c.
References M_ARM_RET_F, M_ARM_RET_I32, M_ARM_RET_I64, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, and M_TYPE_LONG.
Referenced by M_return_register().
void M_arm_short (M_Type type, int unsign)
Definition at line 248 of file mi_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_SHORT, M_ARM_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short().
int M_arm_struct_align (int n, _M_Type * type)
Definition at line 603 of file ml_arm.c.
References M_ARM_ALIGN_CHAR.
Referenced by M_struct_align().
void M_arm_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 516 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_SIZE_CHAR, M_ARM_SIZE_INT, M_ARM_SIZE_LONG, M_ARM_SIZE_SHORT, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_arm_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 619 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_CHAR, M_ARM_ALIGN_LONG, M_ARM_ALIGN_SHORT, M_ARM_SIZE_INT, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_arm_structure_pointer (int purpose)
Definition at line 1239 of file ml_arm.c.
References M_ARM_RET_ST.
Referenced by M_structure_pointer().
int M_arm_subroutine_call (int opc)
Definition at line 1303 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_subroutine_call().
int M_arm_type_align (int mtype)
Definition at line 204 of file mi_arm.c.
References M_ARM_ALIGN_BIT, M_ARM_ALIGN_BLOCK, M_ARM_ALIGN_CHAR, M_ARM_ALIGN_DOUBLE, M_ARM_ALIGN_FLOAT, M_ARM_ALIGN_INT, M_ARM_ALIGN_LLONG, M_ARM_ALIGN_LONG, M_ARM_ALIGN_POINTER, M_ARM_ALIGN_SHORT, M_ARM_ALIGN_STRUCT, M_ARM_ALIGN_UNION, M_ARM_ALIGN_VOID, M_ARM_SIZE_BIT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_arm_type_size (int mtype)
Definition at line 180 of file mi_arm.c.
References M_ARM_SIZE_BIT, M_ARM_SIZE_BLOCK, M_ARM_SIZE_CHAR, M_ARM_SIZE_DOUBLE, M_ARM_SIZE_FLOAT, M_ARM_SIZE_INT, M_ARM_SIZE_LLONG, M_ARM_SIZE_LONG, M_ARM_SIZE_POINTER, M_ARM_SIZE_SHORT, M_ARM_SIZE_STRUCT, M_ARM_SIZE_UNION, M_ARM_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_arm_union_align (int n, _M_Type * type)
Definition at line 466 of file ml_arm.c.
References M_ARM_ALIGN_CHAR.
Referenced by M_union_align().
void M_arm_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 457 of file ml_arm.c.
Referenced by M_union_layout().
int M_arm_union_size (int n, _M_Type * type)
Definition at line 484 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_arm_void (M_Type type)
Definition at line 202 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_VOID, M_ARM_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
int M_conflicting_operands_arm (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1626 of file ml_arm.c.
References ARM_MAC_TRUE_SP, and M_assert().
Referenced by M_dep_conflicting_operands().
void M_define_macros_arm (STRING_Symbol_Table * sym_tbl)
Definition at line 1319 of file ml_arm.c.
References ARM_MAC_ALLOC, ARM_MAC_CALLEE_I, ARM_MAC_FONE, ARM_MAC_FZERO, ARM_MAC_LEAF, ARM_MAC_RETADDR, ARM_MAC_TRUE_SP, and M_add_symbol.
Referenced by M_define_macros().
void M_define_opcode_name_arm (STRING_Symbol_Table * sym_tbl)
Definition at line 1349 of file ml_arm.c.
Referenced by M_define_opcode_name().
char* M_get_macro_name_arm (int id)
Definition at line 1333 of file ml_arm.c.
References ARM_MAC_ALLOC, ARM_MAC_CALLEE_I, ARM_MAC_FONE, ARM_MAC_FZERO, ARM_MAC_LEAF, ARM_MAC_RETADDR, and ARM_MAC_TRUE_SP.
Referenced by M_get_macro_name().
char* M_get_opcode_name_arm (int id)
Definition at line 1353 of file ml_arm.c.
Referenced by M_get_opcode_name().
int M_is_stack_operand_arm (L_Operand * operand)
Definition at line 1549 of file ml_arm.c.
References ARM_MAC_TRUE_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_arm (L_Operand * operand)
Definition at line 1566 of file ml_arm.c.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_arm (L_Oper * oper, char * name)
Definition at line 1405 of file ml_arm.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_arm (int ctype)
Definition at line 1686 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_num_registers().
int M_oper_supported_in_arch_arm (int opc)
Definition at line 1365 of file ml_arm.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_arm (L_Operand * operand)
Definition at line 1592 of file ml_arm.c.
References FIELD_11, FIELD_14, FIELD_5, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit11, MDES_OPERAND_Lit14, MDES_OPERAND_Lit21, MDES_OPERAND_Lit5, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_arm (char * model_name)
Definition at line 288 of file mi_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_set_machine().