m_bx86.h File Reference
#include <config.h>
#include <machine/m_spec.h>
Data Structures
struct Lbx86_Ext_Fields
Defines
#define MDES_OPERAND_flag 100
#define MDES_OPERAND_istk 101
#define MDES_OPERAND_fstk 102
#define MDES_OPERAND_FLAG 103
#define MDES_OPERAND_ISTK 104
#define MDES_OPERAND_FSTK 105
#define MDES_OPERAND_CON 106
#define MDES_OPERAND_SOME 107
#define MDES_OPERAND_ANY 108
#define MDES_OPERAND_REG_STK 109
#define LBX86_EXT(oper) ((Lbx86_Ext_Fields *)(oper $\rightarrow$ ext))
#define LBX86_SEG_OVR(oper) (LBX86_EXT(oper) $\rightarrow$ seg_ovr_popval & 0xF)
#define LBX86_POPVAL(oper) ((LBX86_EXT(oper) $\rightarrow$ seg_ovr_popval >> 4) & 0xF)
#define LBX86_ENCODE_SEG_OVR_POPVAL(seg_ovr, popval)
#define LBX86_EXTRACT_GENOPC(popc) ((int)(((unsigned)(popc)) >> 4))
#define LBX86_GENOPC(oper) (LBX86_EXTRACT_GENOPC(oper $\rightarrow$ proc_opc))
#define LBX86_EXTRACT_VARIANT(popc) ((int)(((unsigned)(popc)) & 0xF))
#define LBX86_VARIANT(oper) (LBX86_EXTRACT_VARIANT(oper $\rightarrow$ proc_opc))
#define LBX86_ENCODE_POPC(genopc, variant) ((int)((genopc << 4) | variant))
#define LBX86_ADDR_BASE 3
#define LBX86_ADDR_INDEX 4
#define LBX86_ADDR_SCALE 5
#define LBX86_ADDR_DISP 6
Enumerations
enum {
M_B_486 = 0,
M_B_PENTIUM,
M_B_PPRO,
M_B_PENTIUM_MMX,
M_B_PENTIUM_II,
M_B_K5,
M_B_K6,
M_B_K6_MMX,
M_B_K6_PLUS
 }
enum {
LBX86_MAC_CALLEE_I = 100,
LBX86_MAC_CALLEE_F,
LBX86_MAC_OSZAPC_FLAGS,
LBX86_MAC_C_FLAGS,
LBX86_MAC_OSZAP_FLAGS,
LBX86_MAC_D_FLAGS,
LBX86_MAC_OC_FLAGS,
LBX86_MAC_SZAPC_FLAGS,
LBX86_MAC_OSZPC_FLAGS,
LBX86_MAC_Z_FLAGS,
LBX86_MAC_ZC_FLAGS,
LBX86_MAC_OSZ_FLAGS,
LBX86_MAC_OS_FLAGS,
LBX86_MAC_O_FLAGS,
LBX86_MAC_S_FLAGS,
LBX86_MAC_A_FLAGS,
LBX86_MAC_P_FLAGS,
LBX86_MAC_ALL_GP_REG32,
LBX86_MAC_ALL_GP_REG16,
LBX86_MAC_EAX,
LBX86_MAC_AX,
LBX86_MAC_AH,
LBX86_MAC_AL,
LBX86_MAC_EAXH,
LBX86_MAC_EBX,
LBX86_MAC_BX,
LBX86_MAC_BH,
LBX86_MAC_BL,
LBX86_MAC_EBXH,
LBX86_MAC_ECX,
LBX86_MAC_CX,
LBX86_MAC_CH,
LBX86_MAC_CL,
LBX86_MAC_ECXH,
LBX86_MAC_EDX,
LBX86_MAC_DX,
LBX86_MAC_DH,
LBX86_MAC_DL,
LBX86_MAC_EDXH,
LBX86_MAC_ESI,
LBX86_MAC_SI,
LBX86_MAC_ESIH,
LBX86_MAC_EDI,
LBX86_MAC_DI,
LBX86_MAC_EDIH,
LBX86_MAC_EBP,
LBX86_MAC_BP,
LBX86_MAC_EBPH,
LBX86_MAC_ESP,
LBX86_MAC_SP,
LBX86_MAC_ESPH,
LBX86_MAC_CS,
LBX86_MAC_SS,
LBX86_MAC_DS,
LBX86_MAC_ES,
LBX86_MAC_FS,
LBX86_MAC_GS,
LBX86_MAC_ALL_FST,
LBX86_MAC_ST0,
LBX86_MAC_ST1,
LBX86_MAC_ST2,
LBX86_MAC_ST3,
LBX86_MAC_ST4,
LBX86_MAC_ST5,
LBX86_MAC_ST6,
LBX86_MAC_ST7,
LBX86_MAC_ALL_MM,
LBX86_MAC_MM0,
LBX86_MAC_MM1,
LBX86_MAC_MM2,
LBX86_MAC_MM3,
LBX86_MAC_MM4,
LBX86_MAC_MM5,
LBX86_MAC_MM6,
LBX86_MAC_MM7,
LBX86_MAC_ADDR,
LBX86_MAC_FPSW,
LBX86_MAC_FPCW
 }
Functions
void M_define_macros_bx86 (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_bx86 (int id)
int M_bx86_fragile_macro (int macro_value)
int M_bx86_subroutine_call (int opc)
void M_define_opcode_name_bx86 (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_bx86 (int id)
int M_bx86_type_size (int mtype)
int M_bx86_type_align (int mtype)
void M_bx86_void (M_Type type)
void M_bx86_bit_long (M_Type type, int n)
void M_bx86_bit_int (M_Type type, int n)
void M_bx86_bit_short (M_Type type, int n)
void M_bx86_bit_char (M_Type type, int n)
void M_bx86_char (M_Type type, int unsign)
void M_bx86_short (M_Type type, int unsign)
void M_bx86_int (M_Type type, int unsign)
void M_bx86_long (M_Type type, int unsign)
void M_bx86_float (M_Type type, int unsign)
void M_bx86_double (M_Type type, int unsign)
void M_bx86_pointer (M_Type type)
int M_bx86_eval_type (M_Type type, M_Type ntype)
int M_bx86_eval_type2 (M_Type type, M_Type ntype)
int M_bx86_call_type (M_Type type, M_Type ntype)
int M_bx86_call_type2 (M_Type type, M_Type ntype)
void M_bx86_array_layout (M_Type type, int *offset)
int M_bx86_array_align (M_Type type)
int M_bx86_array_size (M_Type type, int dim)
void M_bx86_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_bx86_union_align (int n, _M_Type *type)
int M_bx86_union_size (int n, _M_Type *type)
void M_bx86_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_bx86_struct_align (int n, _M_Type *type)
int M_bx86_struct_size (int n, _M_Type *type, int struct_align)
int M_bx86_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_bx86_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_bx86_no_short_int (void)
int M_bx86_layout_order (void)
void M_bx86_cb_label_name (char *fn, int cb, char *line, int len)
int M_bx86_is_cb_label (char *label, char *fn, int *cb)
void M_bx86_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_bx86_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_bx86_structure_pointer (int purpose)
int M_bx86_return_register (int type, int purpose)
char * M_bx86_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_bx86_fn_name_from_label (char *label)
void M_set_model_bx86 (char *model_name)
int M_oper_supported_in_arch_bx86 (int opc)
int M_num_oper_required_for_bx86 (L_Oper *oper, char *name)
int M_is_stack_operand_bx86 (L_Operand *operand)
int M_is_unsafe_macro_bx86 (L_Operand *operand)
int M_operand_type_bx86 (L_Operand *operand)
int M_conflicting_operands_bx86 (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
void M_get_memory_operands_bx86 (int *first, int *number, int proc_opc)
int M_memory_access_size_bx86 (L_Oper *op)
int M_get_data_type_bx86 (L_Oper *op)
int M_num_registers_bx86 (int ctype)
int M_is_implicit_memory_op_bx86 (L_Oper *oper)
Define Documentation
#define LBX86_ADDR_BASE 3
Definition at line 220 of file m_bx86.h.
#define LBX86_ADDR_DISP 6
Definition at line 223 of file m_bx86.h.
#define LBX86_ADDR_INDEX 4
Definition at line 221 of file m_bx86.h.
#define LBX86_ADDR_SCALE 5
Definition at line 222 of file m_bx86.h.
#define LBX86_ENCODE_POPC(genopc, variant) ((int)((genopc << 4) | variant))
Definition at line 218 of file m_bx86.h.
#define LBX86_ENCODE_SEG_OVR_POPVAL(seg_ovr, popval)
Value:
((char)((popval << 4) | \
                                                             (seg_ovr & 0xF)))
Definition at line 210 of file m_bx86.h.
#define LBX86_EXT(oper) ((Lbx86_Ext_Fields *)(oper $\rightarrow$ ext))
Definition at line 206 of file m_bx86.h.
Referenced by M_memory_access_size_bx86().
#define LBX86_EXTRACT_GENOPC(popc) ((int)(((unsigned)(popc)) >> 4))
Definition at line 213 of file m_bx86.h.
#define LBX86_EXTRACT_VARIANT(popc) ((int)(((unsigned)(popc)) & 0xF))
Definition at line 215 of file m_bx86.h.
#define LBX86_GENOPC(oper) (LBX86_EXTRACT_GENOPC(oper $\rightarrow$ proc_opc))
Definition at line 214 of file m_bx86.h.
#define LBX86_POPVAL(oper) ((LBX86_EXT(oper) $\rightarrow$ seg_ovr_popval >> 4) & 0xF)
Definition at line 209 of file m_bx86.h.
#define LBX86_SEG_OVR(oper) (LBX86_EXT(oper) $\rightarrow$ seg_ovr_popval & 0xF)
Definition at line 208 of file m_bx86.h.
#define LBX86_VARIANT(oper) (LBX86_EXTRACT_VARIANT(oper $\rightarrow$ proc_opc))
Definition at line 216 of file m_bx86.h.
#define MDES_OPERAND_ANY 108
Definition at line 193 of file m_bx86.h.
#define MDES_OPERAND_CON 106
Definition at line 191 of file m_bx86.h.
#define MDES_OPERAND_FLAG 103
Definition at line 188 of file m_bx86.h.
#define MDES_OPERAND_flag 100
Definition at line 184 of file m_bx86.h.
Referenced by M_operand_type_x86().
#define MDES_OPERAND_FSTK 105
Definition at line 190 of file m_bx86.h.
#define MDES_OPERAND_fstk 102
Definition at line 186 of file m_bx86.h.
Referenced by M_operand_type_x86().
#define MDES_OPERAND_ISTK 104
Definition at line 189 of file m_bx86.h.
#define MDES_OPERAND_istk 101
Definition at line 185 of file m_bx86.h.
Referenced by M_operand_type_x86().
#define MDES_OPERAND_REG_STK 109
Definition at line 194 of file m_bx86.h.
#define MDES_OPERAND_SOME 107
Definition at line 192 of file m_bx86.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
M_B_486
M_B_PENTIUM
M_B_PPRO
M_B_PENTIUM_MMX
M_B_PENTIUM_II
M_B_K5
M_B_K6
M_B_K6_MMX
M_B_K6_PLUS
Definition at line 84 of file m_bx86.h.
anonymous enum
Enumerator:
LBX86_MAC_CALLEE_I
LBX86_MAC_CALLEE_F
LBX86_MAC_OSZAPC_FLAGS
LBX86_MAC_C_FLAGS
LBX86_MAC_OSZAP_FLAGS
LBX86_MAC_D_FLAGS
LBX86_MAC_OC_FLAGS
LBX86_MAC_SZAPC_FLAGS
LBX86_MAC_OSZPC_FLAGS
LBX86_MAC_Z_FLAGS
LBX86_MAC_ZC_FLAGS
LBX86_MAC_OSZ_FLAGS
LBX86_MAC_OS_FLAGS
LBX86_MAC_O_FLAGS
LBX86_MAC_S_FLAGS
LBX86_MAC_A_FLAGS
LBX86_MAC_P_FLAGS
LBX86_MAC_ALL_GP_REG32
LBX86_MAC_ALL_GP_REG16
LBX86_MAC_EAX
LBX86_MAC_AX
LBX86_MAC_AH
LBX86_MAC_AL
LBX86_MAC_EAXH
LBX86_MAC_EBX
LBX86_MAC_BX
LBX86_MAC_BH
LBX86_MAC_BL
LBX86_MAC_EBXH
LBX86_MAC_ECX
LBX86_MAC_CX
LBX86_MAC_CH
LBX86_MAC_CL
LBX86_MAC_ECXH
LBX86_MAC_EDX
LBX86_MAC_DX
LBX86_MAC_DH
LBX86_MAC_DL
LBX86_MAC_EDXH
LBX86_MAC_ESI
LBX86_MAC_SI
LBX86_MAC_ESIH
LBX86_MAC_EDI
LBX86_MAC_DI
LBX86_MAC_EDIH
LBX86_MAC_EBP
LBX86_MAC_BP
LBX86_MAC_EBPH
LBX86_MAC_ESP
LBX86_MAC_SP
LBX86_MAC_ESPH
LBX86_MAC_CS
LBX86_MAC_SS
LBX86_MAC_DS
LBX86_MAC_ES
LBX86_MAC_FS
LBX86_MAC_GS
LBX86_MAC_ALL_FST
LBX86_MAC_ST0
LBX86_MAC_ST1
LBX86_MAC_ST2
LBX86_MAC_ST3
LBX86_MAC_ST4
LBX86_MAC_ST5
LBX86_MAC_ST6
LBX86_MAC_ST7
LBX86_MAC_ALL_MM
LBX86_MAC_MM0
LBX86_MAC_MM1
LBX86_MAC_MM2
LBX86_MAC_MM3
LBX86_MAC_MM4
LBX86_MAC_MM5
LBX86_MAC_MM6
LBX86_MAC_MM7
LBX86_MAC_ADDR
LBX86_MAC_FPSW
LBX86_MAC_FPCW
Definition at line 97 of file m_bx86.h.
Function Documentation
int M_bx86_array_align (M_Type type)
Definition at line 397 of file ml_bx86.c.
References _struct_M_Type::align, and I_punt().
void M_bx86_array_layout (M_Type type, int * offset)
Definition at line 390 of file ml_bx86.c.
References I_punt().
int M_bx86_array_size (M_Type type, int dim)
Definition at line 404 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), and _struct_M_Type::size.
void M_bx86_bit_char (M_Type type, int n)
Definition at line 184 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_bx86_bit_int (M_Type type, int n)
Definition at line 158 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_bx86_bit_long (M_Type type, int n)
Definition at line 145 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_bx86_bit_short (M_Type type, int n)
Definition at line 171 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_bx86_call_type (M_Type type, M_Type ntype)
Definition at line 309 of file ml_bx86.c.
References I_punt(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_bx86_call_type2 (M_Type type, M_Type ntype)
Definition at line 345 of file ml_bx86.c.
References I_punt(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bx86_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1017 of file ml_bx86.c.
Referenced by M_cb_label_name().
void M_bx86_char (M_Type type, int unsign)
Definition at line 182 of file mi_bx86.c.
References _struct_M_Type::align, M_BX86_ALIGN_CHAR, M_BX86_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char().
void M_bx86_double (M_Type type, int unsign)
Definition at line 208 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_DOUBLE, M_BX86_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_bx86_eval_type (M_Type type, M_Type ntype)
Definition at line 231 of file ml_bx86.c.
References I_punt(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_bx86_eval_type2 (M_Type type, M_Type ntype)
Definition at line 266 of file ml_bx86.c.
References I_punt(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_bx86_float (M_Type type, int unsign)
Definition at line 197 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_FLOAT, M_BX86_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_bx86_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1091 of file ml_bx86.c.
Referenced by M_fn_label_name().
char* M_bx86_fn_name_from_label (char * label)
Definition at line 1106 of file ml_bx86.c.
Referenced by M_fn_name_from_label().
int M_bx86_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 721 of file ml_bx86.c.
References _struct_M_Type::align, have_reversed, I_punt(), M_assert(), M_BX86_ALIGN_INT, M_BX86_ALIGN_MAX, M_BX86_FLT_BASE, M_BX86_INT_BASE, M_BX86_MAX_FNVAR_REG, M_BX86_SIZE_INT, M_BX86_SMALL_STRUCT_MAX, M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
int M_bx86_fragile_macro (int macro_value)
Definition at line 1118 of file ml_bx86.c.
References M_assert(), M_B_486, M_B_K5, M_B_K6, M_B_K6_MMX, M_B_K6_PLUS, M_B_PENTIUM, M_B_PENTIUM_II, M_B_PENTIUM_MMX, M_B_PPRO, and M_model.
Referenced by M_fragile_macro().
void M_bx86_int (M_Type type, int unsign)
Definition at line 202 of file mi_bx86.c.
References _struct_M_Type::align, M_BX86_ALIGN_INT, M_BX86_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int().
int M_bx86_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1023 of file ml_bx86.c.
Referenced by M_is_cb_label().
int M_bx86_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1036 of file ml_bx86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_bx86_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1029 of file ml_bx86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_bx86_layout_order (void)
Definition at line 222 of file mi_bx86.c.
References M_LITTLE_ENDIAN.
Referenced by M_layout_order().
void M_bx86_long (M_Type type, int unsign)
Definition at line 212 of file mi_bx86.c.
References _struct_M_Type::align, M_BX86_ALIGN_LONG, M_BX86_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long().
int M_bx86_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 968 of file ml_bx86.c.
References _struct_M_Type::align, M_assert(), M_BX86_ALIGN_MAX, M_BX86_VAR_PTR, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
int M_bx86_no_short_int (void)
Definition at line 1011 of file ml_bx86.c.
References M_BX86_SIZE_INT, and M_BX86_SIZE_SHORT.
void M_bx86_pointer (M_Type type)
Definition at line 219 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_POINTER, M_BX86_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_bx86_return_register (int type, int purpose)
Definition at line 1070 of file ml_bx86.c.
References M_BX86_RET_F, M_BX86_RET_I32, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
void M_bx86_short (M_Type type, int unsign)
Definition at line 192 of file mi_bx86.c.
References _struct_M_Type::align, M_BX86_ALIGN_SHORT, M_BX86_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short().
int M_bx86_struct_align (int n, _M_Type * type)
Definition at line 638 of file ml_bx86.c.
References I_punt(), and M_BX86_ALIGN_CHAR.
void M_bx86_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 499 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_SIZE_CHAR, M_BX86_SIZE_INT, M_BX86_SIZE_LONG, M_BX86_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
int M_bx86_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 659 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_CHAR, M_BX86_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
int M_bx86_structure_pointer (int purpose)
Definition at line 1064 of file ml_bx86.c.
References M_BX86_RET_ST.
int M_bx86_subroutine_call (int opc)
Definition at line 1154 of file ml_bx86.c.
References M_assert(), M_B_486, M_B_K5, M_B_K6, M_B_K6_MMX, M_B_K6_PLUS, M_B_PENTIUM, M_B_PENTIUM_II, M_B_PENTIUM_MMX, M_B_PPRO, and M_model.
int M_bx86_type_align (int mtype)
Definition at line 146 of file mi_bx86.c.
References M_BX86_ALIGN_BIT, M_BX86_ALIGN_BLOCK, M_BX86_ALIGN_CHAR, M_BX86_ALIGN_DOUBLE, M_BX86_ALIGN_FLOAT, M_BX86_ALIGN_INT, M_BX86_ALIGN_LONG, M_BX86_ALIGN_POINTER, M_BX86_ALIGN_SHORT, M_BX86_ALIGN_STRUCT, M_BX86_ALIGN_UNION, M_BX86_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
int M_bx86_type_size (int mtype)
Definition at line 110 of file mi_bx86.c.
References M_BX86_SIZE_BIT, M_BX86_SIZE_BLOCK, M_BX86_SIZE_CHAR, M_BX86_SIZE_DOUBLE, M_BX86_SIZE_FLOAT, M_BX86_SIZE_INT, M_BX86_SIZE_LONG, M_BX86_SIZE_POINTER, M_BX86_SIZE_SHORT, M_BX86_SIZE_STRUCT, M_BX86_SIZE_UNION, M_BX86_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
int M_bx86_union_align (int n, _M_Type * type)
Definition at line 432 of file ml_bx86.c.
References I_punt(), and M_BX86_ALIGN_CHAR.
void M_bx86_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 420 of file ml_bx86.c.
References I_punt().
int M_bx86_union_size (int n, _M_Type * type)
Definition at line 453 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_CHAR, and _struct_M_Type::size.
void M_bx86_void (M_Type type)
Definition at line 134 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_VOID, M_BX86_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
int M_conflicting_operands_bx86 (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1719 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CX, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, LBX86_MAC_ZC_FLAGS, M_assert(), MSPEC_a_flags, MSPEC_ah, MSPEC_al, MSPEC_all_fst, MSPEC_all_mm, MSPEC_ax, MSPEC_bh, MSPEC_bl, MSPEC_bp, MSPEC_bx, MSPEC_c_flags, MSPEC_ch, MSPEC_cl, MSPEC_cx, MSPEC_dh, MSPEC_di, MSPEC_dl, MSPEC_dx, MSPEC_eax, MSPEC_eaxh, MSPEC_ebp, MSPEC_ebph, MSPEC_ebx, MSPEC_ebxh, MSPEC_ecx, MSPEC_ecxh, MSPEC_edi, MSPEC_edih, MSPEC_edx, MSPEC_edxh, MSPEC_esi, MSPEC_esih, MSPEC_esp, MSPEC_esph, MSPEC_gp_reg16, MSPEC_gp_reg32, MSPEC_mm0, MSPEC_mm1, MSPEC_mm2, MSPEC_mm3, MSPEC_mm4, MSPEC_mm5, MSPEC_mm6, MSPEC_mm7, MSPEC_o_flags, MSPEC_oc_flags, MSPEC_os_flags, MSPEC_osz_flags, MSPEC_oszap_flags, MSPEC_oszapc_flags, MSPEC_oszpc_flags, MSPEC_p_flags, MSPEC_s_flags, MSPEC_si, MSPEC_sp, MSPEC_st0, MSPEC_st1, MSPEC_st2, MSPEC_st3, MSPEC_st4, MSPEC_st5, MSPEC_st6, MSPEC_st7, MSPEC_szapc_flags, MSPEC_z_flags, and MSPEC_zc_flags.
Referenced by M_dep_conflicting_operands().
void M_define_macros_bx86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1178 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CALLEE_F, LBX86_MAC_CALLEE_I, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CS, LBX86_MAC_CX, LBX86_MAC_D_FLAGS, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DS, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ES, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_FPCW, LBX86_MAC_FPSW, LBX86_MAC_FS, LBX86_MAC_GS, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_SS, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, LBX86_MAC_ZC_FLAGS, and M_add_symbol.
Referenced by M_define_macros().
void M_define_opcode_name_bx86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1431 of file ml_bx86.c.
Referenced by M_define_opcode_name().
int M_get_data_type_bx86 (L_Oper * op)
Definition at line 2396 of file ml_bx86.c.
References I_punt(), and M_assert().
Referenced by M_get_data_type().
char* M_get_macro_name_bx86 (int id)
Definition at line 1263 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CALLEE_F, LBX86_MAC_CALLEE_I, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CS, LBX86_MAC_CX, LBX86_MAC_D_FLAGS, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DS, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ES, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_FPCW, LBX86_MAC_FPSW, LBX86_MAC_FS, LBX86_MAC_GS, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_SS, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, and LBX86_MAC_ZC_FLAGS.
Referenced by M_get_macro_name().
void M_get_memory_operands_bx86 (int * first, int * number, int proc_opc)
Definition at line 2379 of file ml_bx86.c.
Referenced by M_get_memory_operands().
char* M_get_opcode_name_bx86 (int id)
Definition at line 1437 of file ml_bx86.c.
Referenced by M_get_opcode_name().
int M_is_implicit_memory_op_bx86 (L_Oper * oper)
Definition at line 2496 of file ml_bx86.c.
References I_punt().
Referenced by M_is_implicit_memory_op().
int M_is_stack_operand_bx86 (L_Operand * operand)
Definition at line 1619 of file ml_bx86.c.
References LBX86_MAC_ESP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_bx86 (L_Operand * operand)
Definition at line 1631 of file ml_bx86.c.
Referenced by M_is_unsafe_macro().
int M_memory_access_size_bx86 (L_Oper * op)
Definition at line 2388 of file ml_bx86.c.
References LBX86_EXT.
Referenced by M_memory_access_size().
int M_num_oper_required_for_bx86 (L_Oper * oper, char * name)
Definition at line 1489 of file ml_bx86.c.
References indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_bx86 (int ctype)
Definition at line 2479 of file ml_bx86.c.
References I_punt().
Referenced by M_num_registers().
int M_oper_supported_in_arch_bx86 (int opc)
Definition at line 1453 of file ml_bx86.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_bx86 (L_Operand * operand)
Definition at line 1644 of file ml_bx86.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_bx86 (char * model_name)
Definition at line 245 of file mi_bx86.c.
References M_assert(), M_B_486, M_B_K5, M_B_K6, M_B_K6_MMX, M_B_K6_PLUS, M_B_PENTIUM, M_B_PENTIUM_II, M_B_PENTIUM_MMX, M_B_PPRO, and M_model.
Referenced by M_set_machine().