m_impact.h File Reference
#include <config.h>
#include <machine/m_spec.h>
Defines
#define ADDR_ALIGN(addr, align) (((addr)+(align-1)) & ~(align-1))
Enumerations
enum {
M_IM_LCODE = 1000,
M_IM_VER_1,
M_IM_HP_LCODE,
M_IM_HP_MCODE,
M_IM_SPARC_LCODE,
M_IM_SPARC_MCODE
 }
Functions
int M_impact_type_size (int mtype)
int M_impact_type_align (int mtype)
void M_impact_void (M_Type type)
void M_impact_bit_long (M_Type type, int n)
void M_impact_bit_int (M_Type type, int n)
void M_impact_bit_short (M_Type type, int n)
void M_impact_bit_char (M_Type type, int n)
void M_impact_char (M_Type type, int unsign)
void M_impact_short (M_Type type, int unsign)
void M_impact_int (M_Type type, int unsign)
void M_impact_long (M_Type type, int unsign)
void M_impact_float (M_Type type, int unsign)
void M_impact_double (M_Type type, int unsign)
void M_impact_pointer (M_Type type)
int M_impact_eval_type (M_Type type, M_Type ntype)
int M_impact_eval_type2 (M_Type type, M_Type ntype)
int M_impact_call_type (M_Type type, M_Type ntype)
int M_impact_call_type2 (M_Type type, M_Type ntype)
void M_impact_array_layout (M_Type type, int *offset)
int M_impact_array_align (M_Type type)
int M_impact_array_size (M_Type type, int dim)
void M_impact_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_impact_union_align (int n, _M_Type *type)
int M_impact_union_size (int n, _M_Type *type)
void M_impact_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_impact_struct_align (int n, _M_Type *type)
int M_impact_struct_size (int n, _M_Type *type, int struct_align)
int M_impact_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_impact_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **base_macro, int *su_sreg, int *su_ereg, int *pcount, int need_ST, int purpose)
int M_impact_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_impact_no_short_int (void)
int M_impact_layout_order (void)
void M_impact_cb_label_name (char *fn, int cb, char *line, int len)
int M_impact_is_cb_label (char *label, char *fn, int *cb)
void M_impact_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_impact_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_impact_structure_pointer (int purpose)
int M_impact_return_register (int type, int purpose)
char * M_impact_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_impact_fn_name_from_label (char *label)
void M_set_model_impact (char *model_name)
int M_impact_fragile_macro (int macro_value)
Set M_impact_fragile_macro_set ()
int M_impact_dataflow_macro (int id)
int M_impact_subroutine_call (int opc)
int M_oper_supported_in_arch_impact (int opc)
int M_num_oper_required_for_impact (L_Oper *oper, char *name)
int M_is_stack_operand_impact (L_Operand *operand)
int M_is_unsafe_macro_impact (L_Operand *operand)
int M_operand_type_impact (L_Operand *operand)
int M_conflicting_operands_impact (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
void M_define_macros_impact (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_impact (int id)
int M_num_registers_impact (int ctype)
Variables
int M_impact_model
Define Documentation
#define ADDR_ALIGN(addr, align) (((addr)+(align-1)) & ~(align-1))
Definition at line 113 of file m_impact.h.
Referenced by M_tahoe_fnvar_to_lvar(), and M_tahoe_lvar_layout().
Enumeration Type Documentation
anonymous enum
Enumerator:
M_IM_LCODE
M_IM_VER_1
M_IM_HP_LCODE
M_IM_HP_MCODE
M_IM_SPARC_LCODE
M_IM_SPARC_MCODE
Definition at line 87 of file m_impact.h.
Function Documentation
int M_conflicting_operands_impact (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 3889 of file ml_impact.c.
References M_assert(), M_conflicting_operands_impact_hp_lcode(), M_conflicting_operands_impact_lcode(), M_conflicting_operands_impact_sparc_lcode(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, and M_impact_model.
Referenced by M_dep_conflicting_operands().
void M_define_macros_impact (STRING_Symbol_Table * sym_tbl)
Definition at line 3928 of file ml_impact.c.
References M_assert(), M_define_macros_hppa(), M_define_macros_sparc(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, and M_impact_model.
Referenced by M_define_macros().
char* M_get_macro_name_impact (int id)
Definition at line 3955 of file ml_impact.c.
References M_assert(), M_get_macro_name_hppa(), M_get_macro_name_sparc(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and NULL.
Referenced by M_get_macro_name().
int M_impact_array_align (M_Type type)
Definition at line 858 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_array_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_array_align().
Referenced by M_array_align().
void M_impact_array_layout (M_Type type, int * offset)
Definition at line 831 of file ml_impact.c.
References M_assert(), M_hppa_array_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_array_layout().
Referenced by M_array_layout().
int M_impact_array_size (M_Type type, int dim)
Definition at line 886 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_array_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_sparc_array_size(), and _struct_M_Type::size.
Referenced by M_array_size().
void M_impact_bit_char (M_Type type, int n)
Definition at line 333 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_char(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_char(), M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_impact_bit_int (M_Type type, int n)
Definition at line 255 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_int(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_int(), M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_impact_bit_long (M_Type type, int n)
Definition at line 216 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_long(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_long(), M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_impact_bit_short (M_Type type, int n)
Definition at line 294 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_short(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_short(), M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_impact_call_type (M_Type type, M_Type ntype)
Definition at line 651 of file ml_impact.c.
References M_assert(), M_hppa_call_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_double(), M_impact_float(), M_impact_int(), M_impact_model, M_impact_void(), M_sparc_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_impact_call_type2 (M_Type type, M_Type ntype)
Definition at line 733 of file ml_impact.c.
References M_assert(), M_hppa_call_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_char(), M_impact_double(), M_impact_float(), M_impact_int(), M_impact_long(), M_impact_model, M_impact_pointer(), M_impact_short(), M_impact_void(), M_sparc_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_impact_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 2309 of file ml_impact.c.
References M_assert(), M_hppa_cb_label_name(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_cb_label_name().
Referenced by M_cb_label_name().
void M_impact_char (M_Type type, int unsign)
Definition at line 329 of file mi_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_char(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_CHAR, M_IMPACT_LCODE_ALIGN_CHAR, M_IMPACT_LCODE_SIZE_CHAR, M_impact_model, M_IMPACT_SIZE_CHAR, M_sparc_char(), M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char(), M_impact_call_type2(), and M_impact_eval_type2().
int M_impact_dataflow_macro (int id)
Definition at line 2837 of file ml_impact.c.
References M_assert(), M_hppa_dataflow_macro(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_dataflow_macro().
Referenced by M_dataflow_macro().
void M_impact_double (M_Type type, int unsign)
Definition at line 407 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_double(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_DOUBLE, M_IMPACT_LCODE_ALIGN_DOUBLE, M_IMPACT_LCODE_SIZE_DOUBLE, M_impact_model, M_IMPACT_SIZE_DOUBLE, M_sparc_double(), M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), and M_impact_eval_type2().
int M_impact_eval_type (M_Type type, M_Type ntype)
Definition at line 477 of file ml_impact.c.
References M_assert(), M_hppa_eval_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_double(), M_impact_float(), M_impact_int(), M_impact_model, M_impact_void(), M_sparc_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_impact_eval_type2 (M_Type type, M_Type ntype)
Definition at line 557 of file ml_impact.c.
References M_assert(), M_hppa_eval_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_char(), M_impact_double(), M_impact_float(), M_impact_int(), M_impact_long(), M_impact_model, M_impact_pointer(), M_impact_short(), M_impact_void(), M_sparc_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_impact_float (M_Type type, int unsign)
Definition at line 372 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_float(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_FLOAT, M_IMPACT_LCODE_ALIGN_FLOAT, M_IMPACT_LCODE_SIZE_FLOAT, M_impact_model, M_IMPACT_SIZE_FLOAT, M_sparc_float(), M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), and M_impact_eval_type2().
char* M_impact_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 2546 of file ml_impact.c.
References M_IM_LCODE, and M_impact_model.
Referenced by M_fn_label_name().
char* M_impact_fn_name_from_label (char * label)
Definition at line 2568 of file ml_impact.c.
References M_IM_LCODE, and M_impact_model.
Referenced by M_fn_name_from_label().
int M_impact_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** base_macro, int * su_sreg, int * su_ereg, int * pcount, int need_ST, int purpose)
Definition at line 1777 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_hppa_fnvar_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_ARG_F, M_IMPACT_ARG_F2, M_IMPACT_ARG_I, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_ALIGN_MAX, M_IMPACT_LCODE_FLT_BASE, M_IMPACT_LCODE_INT_BASE, M_IMPACT_LCODE_MAX_FNVAR_REG, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SMALL_STRUCT_MAX, M_IMPACT_MAX_FNVAR_REG, M_impact_model, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_sparc_fnvar_layout(), M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_impact_fragile_macro (int macro_value)
Definition at line 2584 of file ml_impact.c.
References M_assert(), M_hppa_fragile_macro(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_fragile_macro().
Referenced by M_fragile_macro().
Set M_impact_fragile_macro_set ()
Definition at line 2635 of file ml_impact.c.
References M_assert(), M_hppa_fragile_macro_set(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_sparc_fragile_macro_set(), Set_add(), and Set_impact_fragile_macro.
Referenced by M_fragile_macro_set().
void M_impact_int (M_Type type, int unsign)
Definition at line 399 of file mi_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_int(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_SIZE_INT, M_impact_model, M_IMPACT_SIZE_INT, M_sparc_int(), M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), and M_int().
int M_impact_is_cb_label (char * label, char * fn, int * cb)
Definition at line 2336 of file ml_impact.c.
References M_assert(), M_hppa_is_cb_label(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_is_cb_label().
Referenced by M_is_cb_label().
int M_impact_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 2391 of file ml_impact.c.
References M_assert(), M_hppa_is_jumptbl_label(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_JUMPTBL_BASE_NAME, and M_sparc_is_jumptbl_label().
Referenced by M_is_jumptbl_label().
void M_impact_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 2364 of file ml_impact.c.
References M_assert(), M_hppa_jumptbl_label_name(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_JUMPTBL_BASE_NAME, and M_sparc_jumptbl_label_name().
Referenced by M_jumptbl_label_name().
int M_impact_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 1447 of file ml_impact.c.
References _struct_M_Type::align, List_next(), List_start(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_hppa_layout_fnvar(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_ARG_F, M_IMPACT_ARG_F2, M_IMPACT_ARG_I, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_ALIGN_MAX, M_IMPACT_LCODE_FLT_BASE, M_IMPACT_LCODE_INT_BASE, M_IMPACT_LCODE_MAX_FNVAR_REG, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SMALL_STRUCT_MAX, M_IMPACT_MAX_FNVAR_REG, M_impact_model, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_sparc_layout_fnvar(), M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_impact_layout_order (void)
Definition at line 469 of file mi_impact.c.
References M_assert(), M_BIG_ENDIAN, M_hppa_layout_order(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_LITTLE_ENDIAN, M_read_database_i(), and M_sparc_layout_order().
Referenced by M_layout_order().
void M_impact_long (M_Type type, int unsign)
Definition at line 434 of file mi_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_long(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_LONG, M_IMPACT_LCODE_ALIGN_LONG, M_IMPACT_LCODE_SIZE_LONG, M_impact_model, M_IMPACT_SIZE_LONG, M_sparc_long(), M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type2(), M_impact_eval_type2(), and M_long().
int M_impact_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 2174 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_lvar_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_LCODE_ALIGN_MAX, M_impact_model, M_sparc_lvar_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_impact_no_short_int (void)
Definition at line 2281 of file ml_impact.c.
References M_assert(), M_hppa_no_short_int(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SIZE_SHORT, M_impact_model, M_IMPACT_SIZE_INT, M_IMPACT_SIZE_SHORT, and M_sparc_no_short_int().
Referenced by M_no_short_int().
void M_impact_pointer (M_Type type)
Definition at line 442 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_pointer(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_POINTER, M_IMPACT_LCODE_ALIGN_POINTER, M_IMPACT_LCODE_SIZE_POINTER, M_impact_model, M_IMPACT_SIZE_POINTER, M_sparc_pointer(), M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type2(), M_impact_eval_type2(), and M_pointer().
int M_impact_return_register (int type, int purpose)
Definition at line 2497 of file ml_impact.c.
References M_assert(), M_hppa_return_register(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_RET_F, M_IMPACT_LCODE_RET_I32, M_impact_model, M_IMPACT_R0_F, M_IMPACT_R0_F2, M_IMPACT_R0_I, M_sparc_return_register(), M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
Referenced by M_return_register().
void M_impact_short (M_Type type, int unsign)
Definition at line 364 of file mi_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_short(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_SHORT, M_IMPACT_LCODE_ALIGN_SHORT, M_IMPACT_LCODE_SIZE_SHORT, M_impact_model, M_IMPACT_SIZE_SHORT, M_sparc_short(), M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type2(), M_impact_eval_type2(), and M_short().
int M_impact_struct_align (int n, _M_Type * type)
Definition at line 1255 of file ml_impact.c.
References M_assert(), M_hppa_struct_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, and M_sparc_struct_align().
Referenced by M_struct_align().
void M_impact_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 1089 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_struct_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_SIZE_CHAR, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SIZE_LONG, M_IMPACT_LCODE_SIZE_SHORT, M_impact_model, M_IMPACT_SIZE_CHAR, M_IMPACT_SIZE_INT, M_IMPACT_SIZE_LONG, M_sparc_struct_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_impact_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 1309 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_struct_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_IMPACT_LCODE_ALIGN_LONG, M_IMPACT_LCODE_ALIGN_SHORT, M_IMPACT_LCODE_SIZE_INT, M_impact_model, M_IMPACT_SIZE_INT, M_sparc_struct_size(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_impact_structure_pointer (int purpose)
Definition at line 2469 of file ml_impact.c.
References M_assert(), M_hppa_structure_pointer(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_RET_ST, M_impact_model, M_IMPACT_ST, and M_sparc_structure_pointer().
Referenced by M_structure_pointer().
int M_impact_subroutine_call (int opc)
Definition at line 2874 of file ml_impact.c.
References M_assert(), M_hppa_subroutine_call(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_subroutine_call().
Referenced by M_subroutine_call().
int M_impact_type_align (int mtype)
Definition at line 236 of file mi_impact.c.
References M_assert(), M_hppa_type_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_ALIGN_BLOCK, M_IMPACT_ALIGN_CHAR, M_IMPACT_ALIGN_DOUBLE, M_IMPACT_ALIGN_FLOAT, M_IMPACT_ALIGN_INT, M_IMPACT_ALIGN_LONG, M_IMPACT_ALIGN_POINTER, M_IMPACT_ALIGN_SHORT, M_IMPACT_ALIGN_STRUCT, M_IMPACT_ALIGN_UNION, M_IMPACT_ALIGN_VOID, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BLOCK, M_IMPACT_LCODE_ALIGN_CHAR, M_IMPACT_LCODE_ALIGN_DOUBLE, M_IMPACT_LCODE_ALIGN_FLOAT, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_ALIGN_LONG, M_IMPACT_LCODE_ALIGN_POINTER, M_IMPACT_LCODE_ALIGN_SHORT, M_IMPACT_LCODE_ALIGN_STRUCT, M_IMPACT_LCODE_ALIGN_UNION, M_IMPACT_LCODE_ALIGN_VOID, M_impact_model, M_sparc_type_align(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_impact_type_size (int mtype)
Definition at line 148 of file mi_impact.c.
References M_assert(), M_hppa_type_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_SIZE_BIT, M_IMPACT_LCODE_SIZE_BLOCK, M_IMPACT_LCODE_SIZE_CHAR, M_IMPACT_LCODE_SIZE_DOUBLE, M_IMPACT_LCODE_SIZE_FLOAT, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SIZE_LONG, M_IMPACT_LCODE_SIZE_POINTER, M_IMPACT_LCODE_SIZE_SHORT, M_IMPACT_LCODE_SIZE_STRUCT, M_IMPACT_LCODE_SIZE_UNION, M_IMPACT_LCODE_SIZE_VOID, M_impact_model, M_IMPACT_SIZE_BIT, M_IMPACT_SIZE_BLOCK, M_IMPACT_SIZE_CHAR, M_IMPACT_SIZE_DOUBLE, M_IMPACT_SIZE_FLOAT, M_IMPACT_SIZE_INT, M_IMPACT_SIZE_LONG, M_IMPACT_SIZE_POINTER, M_IMPACT_SIZE_SHORT, M_IMPACT_SIZE_STRUCT, M_IMPACT_SIZE_UNION, M_IMPACT_SIZE_VOID, M_sparc_type_size(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_impact_union_align (int n, _M_Type * type)
Definition at line 963 of file ml_impact.c.
References M_assert(), M_hppa_union_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, and M_sparc_union_align().
Referenced by M_union_align().
void M_impact_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 926 of file ml_impact.c.
References M_assert(), M_hppa_union_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_union_layout().
Referenced by M_union_layout().
int M_impact_union_size (int n, _M_Type * type)
Definition at line 1017 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_union_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, M_sparc_union_size(), and _struct_M_Type::size.
Referenced by M_union_size().
void M_impact_void (M_Type type)
Definition at line 181 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_void(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_VOID, M_IMPACT_LCODE_ALIGN_VOID, M_IMPACT_LCODE_SIZE_VOID, M_impact_model, M_IMPACT_SIZE_VOID, M_sparc_void(), M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), and M_void().
int M_is_stack_operand_impact (L_Operand * operand)
Definition at line 3126 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_is_stack_operand_hppa(), and M_is_stack_operand_sparc().
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_impact (L_Operand * operand)
Definition at line 3171 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_is_unsafe_macro_hppa(), and M_is_unsafe_macro_sparc().
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_impact (L_Oper * oper, char * name)
Definition at line 2947 of file ml_impact.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_num_oper_required_for_hppa(), M_num_oper_required_for_sparc(), non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_impact (int ctype)
Definition at line 3984 of file ml_impact.c.
Referenced by M_num_registers().
int M_oper_supported_in_arch_impact (int opc)
Definition at line 2913 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_oper_supported_in_arch_hppa(), and M_oper_supported_in_arch_sparc().
Referenced by M_oper_supported_in_arch().
int M_operand_type_impact (L_Operand * operand)
Definition at line 3309 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), and M_operand_type_impact_sparc_lcode().
Referenced by M_mdes_operand_type().
void M_set_model_impact (char * model_name)
Definition at line 507 of file mi_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_model, M_set_model_hppa(), M_set_model_sparc(), and M_use_layout_database.
Referenced by M_set_machine().
Variable Documentation
int M_impact_model
Definition at line 84 of file mi_impact.c.
Referenced by M_conflicting_operands_impact(), M_define_macros_impact(), M_get_macro_name_impact(), M_impact_array_align(), M_impact_array_layout(), M_impact_array_size(), M_impact_bit_char(), M_impact_bit_int(), M_impact_bit_long(), M_impact_bit_short(), M_impact_call_type(), M_impact_call_type2(), M_impact_cb_label_name(), M_impact_char(), M_impact_dataflow_macro(), M_impact_double(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_float(), M_impact_fn_label_name(), M_impact_fn_name_from_label(), M_impact_fnvar_layout(), M_impact_fragile_macro(), M_impact_fragile_macro_set(), M_impact_int(), M_impact_is_cb_label(), M_impact_is_jumptbl_label(), M_impact_jumptbl_label_name(), M_impact_layout_fnvar(), M_impact_layout_order(), M_impact_long(), M_impact_lvar_layout(), M_impact_no_short_int(), M_impact_pointer(), M_impact_return_register(), M_impact_short(), M_impact_struct_align(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_structure_pointer(), M_impact_subroutine_call(), M_impact_type_align(), M_impact_type_size(), M_impact_union_align(), M_impact_union_layout(), M_impact_union_size(), M_impact_void(), M_is_stack_operand_impact(), M_is_unsafe_macro_impact(), M_num_oper_required_for_impact(), M_oper_supported_in_arch_impact(), M_operand_type_impact(), and M_set_model_impact().