m_sh.h File Reference
#include <config.h>
#include <machine/m_spec.h>
Defines
#define MDES_OPERAND_sh_icc 100
#define MDES_OPERAND_sh_fcc 101
#define LSHop_SETJMP_JSR 1000
#define LSHop_LDD_INT 1001
#define LSHop_STD_INT 1002
#define LSHop_CRA 1003
#define LSHop_SAVE 1004
#define LSHop_RESTORE 1005
#define LSHop_NEG 1006
#define LSHop_MOVT 1007
#define LSHop_MOVA 1008
#define LSHop_TST 1009
#define LSHop_CMPPL 1010
#define LSHop_CMPPZ 1011
#define LSHop_STSL 1012
#define LSHop_LDSL 1013
Enumerations
enum { M_SH_1,
M_SH_2
 }
enum {
L_SH_MAC_LEAF = 100,
L_SH_MAC_ALLOC,
L_SH_MAC_CALLEE,
L_SH_MAC_CALLER,
L_SH_MAC_SR,
L_SH_MAC_PR
 }
Functions
int M_sh_type_size (int mtype)
int M_sh_type_align (int mtype)
void M_sh_void (M_Type type)
void M_sh_bit_long (M_Type type, int n)
void M_sh_bit_int (M_Type type, int n)
void M_sh_bit_short (M_Type type, int n)
void M_sh_bit_char (M_Type type, int n)
void M_sh_char (M_Type type, int unsign)
void M_sh_short (M_Type type, int unsign)
void M_sh_int (M_Type type, int unsign)
void M_sh_long (M_Type type, int unsign)
void M_sh_float (M_Type type, int unsign)
void M_sh_double (M_Type type, int unsign)
void M_sh_pointer (M_Type type)
int M_sh_eval_type (M_Type type, M_Type ntype)
int M_sh_eval_type2 (M_Type type, M_Type ntype)
int M_sh_call_type (M_Type type, M_Type ntype)
int M_sh_call_type2 (M_Type type, M_Type ntype)
void M_sh_array_layout (M_Type type, int *offset)
int M_sh_array_align (M_Type type)
int M_sh_array_size (M_Type type, int dim)
void M_sh_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_sh_union_align (int n, _M_Type *type)
int M_sh_union_size (int n, _M_Type *type)
void M_sh_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_sh_struct_align (int n, _M_Type *type)
int M_sh_struct_size (int n, _M_Type *type, int struct_align)
int M_sh_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_sh_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_sh_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_sh_no_short_int (void)
int M_sh_layout_order (void)
void M_sh_cb_label_name (char *fn, int cb, char *line, int len)
int M_sh_is_cb_label (char *label, char *fn, int *cb)
void M_sh_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_sh_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_sh_structure_pointer (int purpose)
int M_sh_return_register (int type, int purpose)
char * M_sh_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_sh_fn_name_from_label (char *label)
void M_set_model_sh (char *model_name)
void M_define_macros_sh (STRING_Symbol_Table *sym_tbl)
int M_sh_fragile_macro (int macro_value)
Set M_sh_fragile_macro_set ()
int M_sh_dataflow_macro (int id)
int M_sh_subroutine_call (int opc)
char * M_get_macro_name_sh (int id)
int M_oper_supported_in_arch_sh (int opc)
int M_is_stack_operand_sh (L_Operand *operand)
int M_is_unsafe_macro_sh (L_Operand *operand)
int M_num_oper_required_for_sh (L_Oper *oper, char *name)
int M_operand_type_sh (L_Operand *operand)
int M_conflicting_operands_sh (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_sh (int ctype)
Define Documentation
#define LSHop_CMPPL 1010
Definition at line 136 of file m_sh.h.
#define LSHop_CMPPZ 1011
Definition at line 139 of file m_sh.h.
#define LSHop_CRA 1003
Definition at line 122 of file m_sh.h.
#define LSHop_LDD_INT 1001
Definition at line 120 of file m_sh.h.
#define LSHop_LDSL 1013
Definition at line 145 of file m_sh.h.
#define LSHop_MOVA 1008
Definition at line 130 of file m_sh.h.
#define LSHop_MOVT 1007
Definition at line 127 of file m_sh.h.
#define LSHop_NEG 1006
Definition at line 125 of file m_sh.h.
#define LSHop_RESTORE 1005
Definition at line 124 of file m_sh.h.
#define LSHop_SAVE 1004
Definition at line 123 of file m_sh.h.
#define LSHop_SETJMP_JSR 1000
Definition at line 119 of file m_sh.h.
#define LSHop_STD_INT 1002
Definition at line 121 of file m_sh.h.
#define LSHop_STSL 1012
Definition at line 142 of file m_sh.h.
#define LSHop_TST 1009
Definition at line 133 of file m_sh.h.
#define MDES_OPERAND_sh_fcc 101
Definition at line 115 of file m_sh.h.
#define MDES_OPERAND_sh_icc 100
Definition at line 114 of file m_sh.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
L_SH_MAC_LEAF
L_SH_MAC_ALLOC
L_SH_MAC_CALLEE
L_SH_MAC_CALLER
L_SH_MAC_SR
L_SH_MAC_PR
Definition at line 102 of file m_sh.h.
anonymous enum
Enumerator:
M_SH_1
M_SH_2
Definition at line 93 of file m_sh.h.
Function Documentation
int M_conflicting_operands_sh (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1225 of file ml_sh.c.
References I_punt(), and M_assert().
Referenced by M_dep_conflicting_operands().
void M_define_macros_sh (STRING_Symbol_Table * sym_tbl)
Definition at line 980 of file ml_sh.c.
References L_SH_MAC_ALLOC, L_SH_MAC_CALLEE, L_SH_MAC_CALLER, L_SH_MAC_LEAF, L_SH_MAC_PR, L_SH_MAC_SR, and M_add_symbol.
Referenced by M_define_macros().
char* M_get_macro_name_sh (int id)
Definition at line 1065 of file ml_sh.c.
References L_SH_MAC_ALLOC, L_SH_MAC_CALLEE, L_SH_MAC_CALLER, L_SH_MAC_LEAF, L_SH_MAC_PR, and L_SH_MAC_SR.
Referenced by M_get_macro_name().
int M_is_stack_operand_sh (L_Operand * operand)
Definition at line 1124 of file ml_sh.c.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_sh (L_Operand * operand)
Definition at line 1137 of file ml_sh.c.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_sh (L_Oper * oper, char * name)
Definition at line 1153 of file ml_sh.c.
Referenced by M_num_oper_required_for().
int M_num_registers_sh (int ctype)
Definition at line 1370 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_num_registers().
int M_oper_supported_in_arch_sh (int opc)
Definition at line 1095 of file ml_sh.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_sh (L_Operand * operand)
Definition at line 1197 of file ml_sh.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_sh (char * model_name)
Definition at line 234 of file mi_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_set_machine().
int M_sh_array_align (M_Type type)
Definition at line 388 of file ml_sh.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_sh_array_layout (M_Type type, int * offset)
Definition at line 382 of file ml_sh.c.
Referenced by M_array_layout().
int M_sh_array_size (M_Type type, int dim)
Definition at line 394 of file ml_sh.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_sh_bit_char (M_Type type, int n)
Definition at line 181 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_sh_bit_int (M_Type type, int n)
Definition at line 157 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_sh_bit_long (M_Type type, int n)
Definition at line 145 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_sh_bit_short (M_Type type, int n)
Definition at line 169 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_sh_call_type (M_Type type, M_Type ntype)
Definition at line 302 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_sh_call_type2 (M_Type type, M_Type ntype)
Definition at line 339 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_sh_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 876 of file ml_sh.c.
Referenced by M_cb_label_name().
void M_sh_char (M_Type type, int unsign)
Definition at line 185 of file mi_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_CHAR, M_SH_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char().
int M_sh_dataflow_macro (int id)
Definition at line 1034 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_dataflow_macro().
void M_sh_double (M_Type type, int unsign)
Definition at line 203 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_DOUBLE, M_SH_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_sh_eval_type (M_Type type, M_Type ntype)
Definition at line 225 of file ml_sh.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_sh_eval_type2 (M_Type type, M_Type ntype)
Definition at line 259 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_sh_float (M_Type type, int unsign)
Definition at line 193 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_FLOAT, M_SH_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_sh_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 953 of file ml_sh.c.
char* M_sh_fn_name_from_label (char * label)
Definition at line 966 of file ml_sh.c.
int M_sh_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 686 of file ml_sh.c.
References M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_SH_ALIGN_MAX, M_SH_IN_BASE, M_SH_MAX_FNVAR_REG, M_SH_OUT_BASE, M_SH_SIZE_INT, M_SH_SIZE_POINTER, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_fnvar_layout(), and M_sh_layout_fnvar().
int M_sh_fragile_macro (int macro_value)
Definition at line 991 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_fragile_macro().
Set M_sh_fragile_macro_set ()
Definition at line 1018 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, M_SH_2, and NULL.
Referenced by M_fragile_macro_set().
void M_sh_int (M_Type type, int unsign)
Definition at line 205 of file mi_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_INT, M_SH_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int().
int M_sh_is_cb_label (char * label, char * fn, int * cb)
Definition at line 882 of file ml_sh.c.
Referenced by M_is_cb_label().
int M_sh_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 895 of file ml_sh.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_sh_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 888 of file ml_sh.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_sh_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 629 of file ml_sh.c.
References List_next(), List_size(), List_start(), M_sh_fnvar_layout(), mode, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_sh_layout_order (void)
Definition at line 226 of file mi_sh.c.
References M_BIG_ENDIAN.
Referenced by M_layout_order().
void M_sh_long (M_Type type, int unsign)
Definition at line 215 of file mi_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_LONG, M_SH_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long().
int M_sh_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 829 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_sh_no_short_int (void)
Definition at line 870 of file ml_sh.c.
References M_SH_SIZE_INT, and M_SH_SIZE_SHORT.
Referenced by M_no_short_int().
void M_sh_pointer (M_Type type)
Definition at line 213 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_POINTER, M_SH_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_sh_return_register (int type, int purpose)
Definition at line 929 of file ml_sh.c.
References M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_SH_RET_F, M_SH_RET_IN, M_SH_RET_OUT, M_TYPE_DOUBLE, and M_TYPE_FLOAT.
Referenced by M_return_register().
void M_sh_short (M_Type type, int unsign)
Definition at line 195 of file mi_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_SHORT, M_SH_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short().
int M_sh_struct_align (int n, _M_Type * type)
Definition at line 547 of file ml_sh.c.
References M_SH_ALIGN_CHAR.
Referenced by M_struct_align().
void M_sh_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 466 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_CHAR, M_SH_ALIGN_INT, M_SH_SIZE_CHAR, M_SH_SIZE_INT, M_SH_SIZE_LONG, M_SH_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::nbits.
Referenced by M_struct_layout().
int M_sh_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 566 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_CHAR, M_SH_ALIGN_INT, M_SH_SIZE_INT, M_TYPE_BIT_CHAR, and M_TYPE_BIT_LONG.
Referenced by M_struct_size().
int M_sh_structure_pointer (int purpose)
Definition at line 923 of file ml_sh.c.
References M_SH_ST.
Referenced by M_structure_pointer().
int M_sh_subroutine_call (int opc)
Definition at line 1049 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_subroutine_call().
int M_sh_type_align (int mtype)
Definition at line 149 of file mi_sh.c.
References M_SH_ALIGN_BIT, M_SH_ALIGN_BLOCK, M_SH_ALIGN_CHAR, M_SH_ALIGN_DOUBLE, M_SH_ALIGN_FLOAT, M_SH_ALIGN_INT, M_SH_ALIGN_LONG, M_SH_ALIGN_POINTER, M_SH_ALIGN_SHORT, M_SH_ALIGN_STRUCT, M_SH_ALIGN_UNION, M_SH_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_sh_type_size (int mtype)
Definition at line 114 of file mi_sh.c.
References M_SH_SIZE_BIT, M_SH_SIZE_BLOCK, M_SH_SIZE_CHAR, M_SH_SIZE_DOUBLE, M_SH_SIZE_FLOAT, M_SH_SIZE_INT, M_SH_SIZE_LONG, M_SH_SIZE_POINTER, M_SH_SIZE_SHORT, M_SH_SIZE_STRUCT, M_SH_SIZE_UNION, M_SH_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_sh_union_align (int n, _M_Type * type)
Definition at line 418 of file ml_sh.c.
References M_SH_ALIGN_CHAR.
Referenced by M_union_align().
void M_sh_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 407 of file ml_sh.c.
Referenced by M_union_layout().
int M_sh_union_size (int n, _M_Type * type)
Definition at line 437 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_sh_void (M_Type type)
Definition at line 135 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_VOID, M_SH_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().