m_sparc.h File Reference
#include <config.h>
#include <machine/m_spec.h>
Defines
#define MDES_OPERAND_sparc_icc 100
#define MDES_OPERAND_sparc_fcc 101
#define LSPARCop_SETJMP_JSR 1000
#define LSPARCop_LDD_INT 1001
#define LSPARCop_STD_INT 1002
#define LSPARCop_CRA 1003
#define LSPARCop_SAVE 1004
#define LSPARCop_RESTORE 1005
Enumerations
enum { M_SPARC_ELC = 0,
M_SPARC_VIKING,
M_SPARC_ILP8
 }
enum {
L_SPARC_MAC_ZERO = 200,
L_SPARC_MAC_ICC,
L_SPARC_MAC_ICC0,
L_SPARC_MAC_ICC1,
L_SPARC_MAC_ICC2,
L_SPARC_MAC_ICC3,
L_SPARC_MAC_ICC4,
L_SPARC_MAC_ICC5,
L_SPARC_MAC_ICC6,
L_SPARC_MAC_ICC7,
L_SPARC_MAC_ICC8,
L_SPARC_MAC_ICC9,
L_SPARC_MAC_ICC10,
L_SPARC_MAC_ICC11,
L_SPARC_MAC_ICC12,
L_SPARC_MAC_ICC13,
L_SPARC_MAC_ICC14,
L_SPARC_MAC_ICC15,
L_SPARC_MAC_LEAF,
L_SPARC_MAC_CALLEE,
L_SPARC_MAC_CALLER,
L_SPARC_MAC_ALLOC,
L_SPARC_MAC_PRED_BASE,
L_SPARC_MAC_G1,
L_SPARC_MAC_FCC,
L_SPARC_MAC_FCC0,
L_SPARC_MAC_FCC1,
L_SPARC_MAC_FCC2,
L_SPARC_MAC_FCC3,
L_SPARC_MAC_FCC4,
L_SPARC_MAC_FCC5,
L_SPARC_MAC_FCC6,
L_SPARC_MAC_FCC7,
L_SPARC_MAC_FCC8,
L_SPARC_MAC_FCC9,
L_SPARC_MAC_FCC10,
L_SPARC_MAC_FCC11,
L_SPARC_MAC_FCC12,
L_SPARC_MAC_FCC13,
L_SPARC_MAC_FCC14,
L_SPARC_MAC_FCC15,
L_SPARC_MAC_RETADDR,
L_SPARC_MAC_NONLEAF_RETADDR,
L_SPARC_MAC_CARRY_SET,
L_SPARC_MAC_CARRY_CLEAR,
L_SPARC_MAC_NEG_SET,
L_SPARC_MAC_NEG_CLEAR,
L_SPARC_MAC_OVERFLOW_SET,
L_SPARC_MAC_OVERFLOW_CLEAR,
L_SPARC_MAC_FSR,
L_SPARC_MAC_Y
 }
Functions
int M_sparc_type_size (int mtype)
int M_sparc_type_align (int mtype)
void M_sparc_void (M_Type type)
void M_sparc_bit_long (M_Type type, int n)
void M_sparc_bit_int (M_Type type, int n)
void M_sparc_bit_short (M_Type type, int n)
void M_sparc_bit_char (M_Type type, int n)
void M_sparc_char (M_Type type, int unsign)
void M_sparc_short (M_Type type, int unsign)
void M_sparc_int (M_Type type, int unsign)
void M_sparc_long (M_Type type, int unsign)
void M_sparc_float (M_Type type, int unsign)
void M_sparc_double (M_Type type, int unsign)
void M_sparc_pointer (M_Type type)
int M_sparc_eval_type (M_Type type, M_Type ntype)
int M_sparc_eval_type2 (M_Type type, M_Type ntype)
int M_sparc_call_type (M_Type type, M_Type ntype)
int M_sparc_call_type2 (M_Type type, M_Type ntype)
void M_sparc_array_layout (M_Type type, int *offset)
int M_sparc_array_align (M_Type type)
int M_sparc_array_size (M_Type type, int dim)
void M_sparc_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_sparc_union_align (int n, _M_Type *type)
int M_sparc_union_size (int n, _M_Type *type)
void M_sparc_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_sparc_struct_align (int n, _M_Type *type)
int M_sparc_struct_size (int n, _M_Type *type, int struct_align)
int M_sparc_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_sparc_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_sparc_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_sparc_no_short_int (void)
int M_sparc_layout_order (void)
void M_sparc_cb_label_name (char *fn, int cb, char *line, int len)
int M_sparc_is_cb_label (char *label, char *fn, int *cb)
void M_sparc_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_sparc_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_sparc_structure_pointer (int purpose)
int M_sparc_return_register (int type, int purpose)
char * M_sparc_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_sparc_fn_name_from_label (char *label)
void M_set_model_sparc (char *model_name)
void M_define_macros_sparc (STRING_Symbol_Table *sym_tbl)
int M_sparc_fragile_macro (int macro_value)
Set M_sparc_fragile_macro_set ()
int M_sparc_dataflow_macro (int id)
int M_sparc_subroutine_call (int opc)
char * M_get_macro_name_sparc (int id)
int M_oper_supported_in_arch_sparc (int opc)
int M_is_stack_operand_sparc (L_Operand *operand)
int M_is_unsafe_macro_sparc (L_Operand *operand)
int M_num_oper_required_for_sparc (L_Oper *oper, char *name)
int M_operand_type_sparc (L_Operand *operand)
int M_conflicting_operands_sparc (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_sparc (int ctype)
Define Documentation
#define LSPARCop_CRA 1003
Definition at line 218 of file m_sparc.h.
#define LSPARCop_LDD_INT 1001
Definition at line 216 of file m_sparc.h.
#define LSPARCop_RESTORE 1005
Definition at line 220 of file m_sparc.h.
#define LSPARCop_SAVE 1004
Definition at line 219 of file m_sparc.h.
#define LSPARCop_SETJMP_JSR 1000
Definition at line 215 of file m_sparc.h.
#define LSPARCop_STD_INT 1002
Definition at line 217 of file m_sparc.h.
#define MDES_OPERAND_sparc_fcc 101
Definition at line 211 of file m_sparc.h.
Referenced by M_operand_type_impact_sparc_lcode(), and M_operand_type_sparc().
#define MDES_OPERAND_sparc_icc 100
Definition at line 210 of file m_sparc.h.
Referenced by M_operand_type_impact_sparc_lcode(), and M_operand_type_sparc().
Enumeration Type Documentation
anonymous enum
Enumerator:
M_SPARC_ELC
M_SPARC_VIKING
M_SPARC_ILP8
Definition at line 90 of file m_sparc.h.
anonymous enum
Enumerator:
L_SPARC_MAC_ZERO
L_SPARC_MAC_ICC
L_SPARC_MAC_ICC0
L_SPARC_MAC_ICC1
L_SPARC_MAC_ICC2
L_SPARC_MAC_ICC3
L_SPARC_MAC_ICC4
L_SPARC_MAC_ICC5
L_SPARC_MAC_ICC6
L_SPARC_MAC_ICC7
L_SPARC_MAC_ICC8
L_SPARC_MAC_ICC9
L_SPARC_MAC_ICC10
L_SPARC_MAC_ICC11
L_SPARC_MAC_ICC12
L_SPARC_MAC_ICC13
L_SPARC_MAC_ICC14
L_SPARC_MAC_ICC15
L_SPARC_MAC_LEAF
L_SPARC_MAC_CALLEE
L_SPARC_MAC_CALLER
L_SPARC_MAC_ALLOC
L_SPARC_MAC_PRED_BASE
L_SPARC_MAC_G1
L_SPARC_MAC_FCC
L_SPARC_MAC_FCC0
L_SPARC_MAC_FCC1
L_SPARC_MAC_FCC2
L_SPARC_MAC_FCC3
L_SPARC_MAC_FCC4
L_SPARC_MAC_FCC5
L_SPARC_MAC_FCC6
L_SPARC_MAC_FCC7
L_SPARC_MAC_FCC8
L_SPARC_MAC_FCC9
L_SPARC_MAC_FCC10
L_SPARC_MAC_FCC11
L_SPARC_MAC_FCC12
L_SPARC_MAC_FCC13
L_SPARC_MAC_FCC14
L_SPARC_MAC_FCC15
L_SPARC_MAC_RETADDR
L_SPARC_MAC_NONLEAF_RETADDR
L_SPARC_MAC_CARRY_SET
L_SPARC_MAC_CARRY_CLEAR
L_SPARC_MAC_NEG_SET
L_SPARC_MAC_NEG_CLEAR
L_SPARC_MAC_OVERFLOW_SET
L_SPARC_MAC_OVERFLOW_CLEAR
L_SPARC_MAC_FSR
L_SPARC_MAC_Y
Definition at line 101 of file m_sparc.h.
Function Documentation
int M_conflicting_operands_sparc (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1496 of file ml_sparc.c.
References I_punt(), and M_assert().
Referenced by M_dep_conflicting_operands().
void M_define_macros_sparc (STRING_Symbol_Table * sym_tbl)
Definition at line 1059 of file ml_sparc.c.
References L_SPARC_MAC_ALLOC, L_SPARC_MAC_CALLEE, L_SPARC_MAC_CALLER, L_SPARC_MAC_CARRY_CLEAR, L_SPARC_MAC_CARRY_SET, L_SPARC_MAC_FCC, L_SPARC_MAC_FCC0, L_SPARC_MAC_FCC1, L_SPARC_MAC_FCC10, L_SPARC_MAC_FCC11, L_SPARC_MAC_FCC12, L_SPARC_MAC_FCC13, L_SPARC_MAC_FCC14, L_SPARC_MAC_FCC15, L_SPARC_MAC_FCC2, L_SPARC_MAC_FCC3, L_SPARC_MAC_FCC4, L_SPARC_MAC_FCC5, L_SPARC_MAC_FCC6, L_SPARC_MAC_FCC7, L_SPARC_MAC_FCC8, L_SPARC_MAC_FCC9, L_SPARC_MAC_FSR, L_SPARC_MAC_G1, L_SPARC_MAC_ICC, L_SPARC_MAC_ICC0, L_SPARC_MAC_ICC1, L_SPARC_MAC_ICC10, L_SPARC_MAC_ICC11, L_SPARC_MAC_ICC12, L_SPARC_MAC_ICC13, L_SPARC_MAC_ICC14, L_SPARC_MAC_ICC15, L_SPARC_MAC_ICC2, L_SPARC_MAC_ICC3, L_SPARC_MAC_ICC4, L_SPARC_MAC_ICC5, L_SPARC_MAC_ICC6, L_SPARC_MAC_ICC7, L_SPARC_MAC_ICC8, L_SPARC_MAC_ICC9, L_SPARC_MAC_LEAF, L_SPARC_MAC_NEG_CLEAR, L_SPARC_MAC_NEG_SET, L_SPARC_MAC_NONLEAF_RETADDR, L_SPARC_MAC_OVERFLOW_CLEAR, L_SPARC_MAC_OVERFLOW_SET, L_SPARC_MAC_PRED_BASE, L_SPARC_MAC_RETADDR, L_SPARC_MAC_Y, L_SPARC_MAC_ZERO, and M_add_symbol.
Referenced by M_define_macros(), and M_define_macros_impact().
char* M_get_macro_name_sparc (int id)
Definition at line 1196 of file ml_sparc.c.
References L_SPARC_MAC_ALLOC, L_SPARC_MAC_CALLEE, L_SPARC_MAC_CALLER, L_SPARC_MAC_CARRY_CLEAR, L_SPARC_MAC_CARRY_SET, L_SPARC_MAC_FCC, L_SPARC_MAC_FCC0, L_SPARC_MAC_FCC1, L_SPARC_MAC_FCC10, L_SPARC_MAC_FCC11, L_SPARC_MAC_FCC12, L_SPARC_MAC_FCC13, L_SPARC_MAC_FCC14, L_SPARC_MAC_FCC15, L_SPARC_MAC_FCC2, L_SPARC_MAC_FCC3, L_SPARC_MAC_FCC4, L_SPARC_MAC_FCC5, L_SPARC_MAC_FCC6, L_SPARC_MAC_FCC7, L_SPARC_MAC_FCC8, L_SPARC_MAC_FCC9, L_SPARC_MAC_FSR, L_SPARC_MAC_G1, L_SPARC_MAC_ICC, L_SPARC_MAC_ICC0, L_SPARC_MAC_ICC1, L_SPARC_MAC_ICC10, L_SPARC_MAC_ICC11, L_SPARC_MAC_ICC12, L_SPARC_MAC_ICC13, L_SPARC_MAC_ICC14, L_SPARC_MAC_ICC15, L_SPARC_MAC_ICC2, L_SPARC_MAC_ICC3, L_SPARC_MAC_ICC4, L_SPARC_MAC_ICC5, L_SPARC_MAC_ICC6, L_SPARC_MAC_ICC7, L_SPARC_MAC_ICC8, L_SPARC_MAC_ICC9, L_SPARC_MAC_LEAF, L_SPARC_MAC_NEG_CLEAR, L_SPARC_MAC_NEG_SET, L_SPARC_MAC_NONLEAF_RETADDR, L_SPARC_MAC_OVERFLOW_CLEAR, L_SPARC_MAC_OVERFLOW_SET, L_SPARC_MAC_PRED_BASE, L_SPARC_MAC_RETADDR, L_SPARC_MAC_Y, and L_SPARC_MAC_ZERO.
Referenced by M_get_macro_name(), and M_get_macro_name_impact().
int M_is_stack_operand_sparc (L_Operand * operand)
Definition at line 1347 of file ml_sparc.c.
Referenced by M_is_stack_operand(), and M_is_stack_operand_impact().
int M_is_unsafe_macro_sparc (L_Operand * operand)
Definition at line 1361 of file ml_sparc.c.
References L_SPARC_MAC_FCC, L_SPARC_MAC_FCC15, L_SPARC_MAC_ICC, and L_SPARC_MAC_ICC15.
Referenced by M_is_unsafe_macro(), and M_is_unsafe_macro_impact().
int M_num_oper_required_for_sparc (L_Oper * oper, char * name)
Definition at line 1410 of file ml_sparc.c.
Referenced by M_num_oper_required_for(), and M_num_oper_required_for_impact().
int M_num_registers_sparc (int ctype)
Definition at line 1639 of file ml_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, and M_SPARC_VIKING.
Referenced by M_num_registers().
int M_oper_supported_in_arch_sparc (int opc)
Definition at line 1318 of file ml_sparc.c.
Referenced by M_oper_supported_in_arch(), and M_oper_supported_in_arch_impact().
int M_operand_type_sparc (L_Operand * operand)
Definition at line 1454 of file ml_sparc.c.
References L_SPARC_MAC_FCC, L_SPARC_MAC_FCC15, L_SPARC_MAC_ICC, L_SPARC_MAC_ICC15, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, MDES_OPERAND_sparc_fcc, MDES_OPERAND_sparc_icc, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_sparc (char * model_name)
Definition at line 230 of file mi_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, M_SPARC_ILP8, and M_SPARC_VIKING.
Referenced by M_set_machine(), and M_set_model_impact().
int M_sparc_array_align (M_Type type)
Definition at line 398 of file ml_sparc.c.
References _struct_M_Type::align.
Referenced by M_array_align(), and M_impact_array_align().
void M_sparc_array_layout (M_Type type, int * offset)
Definition at line 392 of file ml_sparc.c.
Referenced by M_array_layout(), and M_impact_array_layout().
int M_sparc_array_size (M_Type type, int dim)
Definition at line 404 of file ml_sparc.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size(), and M_impact_array_size().
void M_sparc_bit_char (M_Type type, int n)
Definition at line 177 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_BIT, M_SPARC_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char(), and M_impact_bit_char().
void M_sparc_bit_int (M_Type type, int n)
Definition at line 153 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_BIT, M_SPARC_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int(), and M_impact_bit_int().
void M_sparc_bit_long (M_Type type, int n)
Definition at line 141 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_BIT, M_SPARC_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long(), and M_impact_bit_long().
void M_sparc_bit_short (M_Type type, int n)
Definition at line 165 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_BIT, M_SPARC_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short(), and M_impact_bit_short().
int M_sparc_call_type (M_Type type, M_Type ntype)
Definition at line 297 of file ml_sparc.c.
References M_char(), M_double(), M_int(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type(), M_impact_call_type(), and M_impact_call_type2().
int M_sparc_call_type2 (M_Type type, M_Type ntype)
Definition at line 342 of file ml_sparc.c.
References M_char(), M_double(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_sparc_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 955 of file ml_sparc.c.
Referenced by M_cb_label_name(), and M_impact_cb_label_name().
void M_sparc_char (M_Type type, int unsign)
Definition at line 183 of file mi_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_CHAR, M_SPARC_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char(), and M_impact_char().
int M_sparc_dataflow_macro (int id)
Definition at line 1164 of file ml_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, and M_SPARC_VIKING.
Referenced by M_dataflow_macro(), and M_impact_dataflow_macro().
void M_sparc_double (M_Type type, int unsign)
Definition at line 199 of file ml_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_DOUBLE, M_SPARC_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), and M_impact_double().
int M_sparc_eval_type (M_Type type, M_Type ntype)
Definition at line 221 of file ml_sparc.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type(), M_impact_eval_type(), and M_impact_eval_type2().
int M_sparc_eval_type2 (M_Type type, M_Type ntype)
Definition at line 255 of file ml_sparc.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_sparc_float (M_Type type, int unsign)
Definition at line 189 of file ml_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_FLOAT, M_SPARC_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), and M_impact_float().
char* M_sparc_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1032 of file ml_sparc.c.
Referenced by M_fn_label_name().
char* M_sparc_fn_name_from_label (char * label)
Definition at line 1045 of file ml_sparc.c.
Referenced by M_fn_name_from_label().
int M_sparc_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 730 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_SPARC_ALIGN_MAX, M_SPARC_ALIGN_POINTER, M_SPARC_IN_BASE, M_SPARC_MAX_FNVAR_REG, M_SPARC_OUT_BASE, M_SPARC_PARAM_FP_OFFSET, M_SPARC_SIZE_INT, M_SPARC_SIZE_POINTER, M_SPARC_SMALL_STRUCT_MAX, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_INT, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout(), M_impact_fnvar_layout(), and M_sparc_layout_fnvar().
int M_sparc_fragile_macro (int macro_value)
Definition at line 1121 of file ml_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, and M_SPARC_VIKING.
Referenced by M_fragile_macro(), and M_impact_fragile_macro().
Set M_sparc_fragile_macro_set ()
Definition at line 1148 of file ml_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, M_SPARC_VIKING, and NULL.
Referenced by M_fragile_macro_set(), and M_impact_fragile_macro_set().
void M_sparc_int (M_Type type, int unsign)
Definition at line 203 of file mi_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_INT, M_SPARC_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_int(), and M_int().
int M_sparc_is_cb_label (char * label, char * fn, int * cb)
Definition at line 961 of file ml_sparc.c.
Referenced by M_impact_is_cb_label(), and M_is_cb_label().
int M_sparc_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 974 of file ml_sparc.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_impact_is_jumptbl_label(), and M_is_jumptbl_label().
void M_sparc_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 967 of file ml_sparc.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_impact_jumptbl_label_name(), and M_jumptbl_label_name().
int M_sparc_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 678 of file ml_sparc.c.
References List_next(), List_size(), List_start(), M_sparc_fnvar_layout(), mode, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_impact_layout_fnvar(), and M_layout_fnvar().
int M_sparc_layout_order (void)
Definition at line 224 of file mi_sparc.c.
References M_BIG_ENDIAN.
Referenced by M_impact_layout_order(), and M_layout_order().
void M_sparc_long (M_Type type, int unsign)
Definition at line 213 of file mi_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_LONG, M_SPARC_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_long(), and M_long().
int M_sparc_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 907 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_impact_lvar_layout(), and M_lvar_layout().
int M_sparc_no_short_int (void)
Definition at line 949 of file ml_sparc.c.
References M_SPARC_SIZE_INT, and M_SPARC_SIZE_SHORT.
Referenced by M_impact_no_short_int(), and M_no_short_int().
void M_sparc_pointer (M_Type type)
Definition at line 209 of file ml_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_POINTER, M_SPARC_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_pointer(), and M_pointer().
int M_sparc_return_register (int type, int purpose)
Definition at line 1008 of file ml_sparc.c.
References M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_SPARC_RET_F, M_SPARC_RET_IN, M_SPARC_RET_OUT, M_TYPE_DOUBLE, and M_TYPE_FLOAT.
Referenced by M_impact_return_register(), and M_return_register().
void M_sparc_short (M_Type type, int unsign)
Definition at line 193 of file mi_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_SHORT, M_SPARC_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_short(), and M_short().
int M_sparc_struct_align (int n, _M_Type * type)
Definition at line 599 of file ml_sparc.c.
References M_SPARC_ALIGN_CHAR.
Referenced by M_impact_struct_align(), and M_struct_align().
void M_sparc_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 476 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_CHAR, M_SPARC_ALIGN_INT, M_SPARC_SIZE_CHAR, M_SPARC_SIZE_INT, M_SPARC_SIZE_LONG, M_SPARC_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_impact_struct_layout(), and M_struct_layout().
int M_sparc_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 618 of file ml_sparc.c.
References _struct_M_Type::align, M_assert(), M_SPARC_ALIGN_CHAR, M_SPARC_ALIGN_LONG, M_SPARC_ALIGN_SHORT, M_SPARC_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_impact_struct_size(), and M_struct_size().
int M_sparc_structure_pointer (int purpose)
Definition at line 1002 of file ml_sparc.c.
References M_SPARC_ST.
Referenced by M_impact_structure_pointer(), and M_structure_pointer().
int M_sparc_subroutine_call (int opc)
Definition at line 1180 of file ml_sparc.c.
References M_assert(), M_model, M_SPARC_ELC, and M_SPARC_VIKING.
Referenced by M_impact_subroutine_call(), and M_subroutine_call().
int M_sparc_type_align (int mtype)
Definition at line 143 of file mi_sparc.c.
References M_SPARC_ALIGN_BIT, M_SPARC_ALIGN_BLOCK, M_SPARC_ALIGN_CHAR, M_SPARC_ALIGN_DOUBLE, M_SPARC_ALIGN_FLOAT, M_SPARC_ALIGN_INT, M_SPARC_ALIGN_LONG, M_SPARC_ALIGN_POINTER, M_SPARC_ALIGN_SHORT, M_SPARC_ALIGN_STRUCT, M_SPARC_ALIGN_UNION, M_SPARC_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_impact_type_align(), and M_type_align().
int M_sparc_type_size (int mtype)
Definition at line 108 of file mi_sparc.c.
References M_SPARC_SIZE_BIT, M_SPARC_SIZE_BLOCK, M_SPARC_SIZE_CHAR, M_SPARC_SIZE_DOUBLE, M_SPARC_SIZE_FLOAT, M_SPARC_SIZE_INT, M_SPARC_SIZE_LONG, M_SPARC_SIZE_POINTER, M_SPARC_SIZE_SHORT, M_SPARC_SIZE_STRUCT, M_SPARC_SIZE_UNION, M_SPARC_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_impact_type_size(), and M_type_size().
int M_sparc_union_align (int n, _M_Type * type)
Definition at line 428 of file ml_sparc.c.
References M_SPARC_ALIGN_CHAR.
Referenced by M_impact_union_align(), and M_union_align().
void M_sparc_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 417 of file ml_sparc.c.
Referenced by M_impact_union_layout(), and M_union_layout().
int M_sparc_union_size (int n, _M_Type * type)
Definition at line 447 of file ml_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_impact_union_size(), and M_union_size().
void M_sparc_void (M_Type type)
Definition at line 131 of file ml_sparc.c.
References _struct_M_Type::align, M_SPARC_ALIGN_VOID, M_SPARC_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_void(), and M_void().