m_spec.h File Reference
#include <config.h>
#include <stdio.h>
#include <library/dynamic_symbol.h>
#include <Lcode/l_code.h>
#include <library/l_parms.h>
#include <library/i_list.h>
Data Structures
struct _struct_M_Type
struct _struct_M_Param
Defines
#define M_IMPACT 0
#define M_SPARC 1
#define M_HPPA 5
#define M_X86 6
#define M_PLAYDOH 7
#define M_TI 8
#define M_SH 9
#define M_BX86 10
#define M_TAHOE 11
#define M_STARCORE 12
#define M_WIMS 13
#define M_ARM 14
#define M_JUMPTBL_BASE_NAME `_hash_`
#define MDES_OPERAND_NULL 0
#define MDES_OPERAND_i 1
#define MDES_OPERAND_f 2
#define MDES_OPERAND_f2 3
#define MDES_OPERAND_p 4
#define MDES_OPERAND_Label 5
#define MDES_OPERAND_REG 6
#define MDES_OPERAND_btr 7
#define MDES_OPERAND_cntl 8
#define MDES_OPERAND_Lit 9
#define MDES_OPERAND_Lit1 10
#define MDES_OPERAND_Lit2 11
#define MDES_OPERAND_Lit3 12
#define MDES_OPERAND_Lit4 13
#define MDES_OPERAND_Lit5 14
#define MDES_OPERAND_Lit6 15
#define MDES_OPERAND_Lit7 16
#define MDES_OPERAND_Lit8 17
#define MDES_OPERAND_Lit9 18
#define MDES_OPERAND_Lit10 19
#define MDES_OPERAND_Lit11 20
#define MDES_OPERAND_Lit12 21
#define MDES_OPERAND_Lit13 22
#define MDES_OPERAND_Lit14 23
#define MDES_OPERAND_Lit15 24
#define MDES_OPERAND_Lit16 25
#define MDES_OPERAND_Lit17 26
#define MDES_OPERAND_Lit18 27
#define MDES_OPERAND_Lit19 28
#define MDES_OPERAND_Lit20 29
#define MDES_OPERAND_Lit21 30
#define MDES_OPERAND_Lit22 31
#define MDES_OPERAND_Lit23 32
#define MDES_OPERAND_Lit24 33
#define MDES_OPERAND_Lit25 34
#define MDES_OPERAND_Lit26 35
#define MDES_OPERAND_Lit27 36
#define MDES_OPERAND_Lit28 37
#define MDES_OPERAND_Lit29 38
#define MDES_OPERAND_Lit30 39
#define MDES_OPERAND_Lit31 40
#define MDES_OPERAND_Lit32 41
#define MDES_OPERAND_Lit64 42
#define MDES_OPERAND_addr 43
#define M_add_symbol(table, name, id)
#define M_SIZE_LLONG 64
#define M_ALIGN_LLONG 64
#define M_SIZE_INT 32
#define M_ALIGN_INT 32
#define M_SIZE_CHAR 8
#define M_TYPE_VOID 0
#define M_TYPE_CHAR 1
#define M_TYPE_SHORT 2
#define M_TYPE_INT 3
#define M_TYPE_LONG 4
#define M_TYPE_LLONG 5
#define M_TYPE_FLOAT 6
#define M_TYPE_DOUBLE 7
#define M_TYPE_POINTER 8
#define M_TYPE_UNION 9
#define M_TYPE_STRUCT 10
#define M_TYPE_BLOCK 11
#define M_TYPE_BIT_CHAR 12
#define M_TYPE_BIT_SHORT 13
#define M_TYPE_BIT_INT 14
#define M_TYPE_BIT_LONG 15
#define M_TYPE_BIT_LLONG 16
#define M_TYFL_HFA_SGL 1
#define M_TYFL_HFA_DBL 2
#define M_TYFL_HFA 3
#define M_THRU_REGISTER 0
#define M_THRU_MEMORY 1
#define M_INDIRECT_THRU_REGISTER 2
#define M_INDIRECT_THRU_MEMORY 3
#define M_DONT_CARE_FNVAR 0
#define M_GET_FNVAR 1
#define M_PUT_FNVAR 2
#define M_RET_FNVAR 3
#define M_LITTLE_ENDIAN 0
#define M_BIG_ENDIAN 1
Typedefs
typedef _struct_M_Type _M_Type
typedef _struct_M_Type * M_Type
typedef int(*) IFPTR1 (L_Operand *operand)
typedef int(*) IFPTR2 (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
typedef _struct_M_Param _M_Param
typedef _struct_M_Param * M_Param
Functions
void M_read_parm (Parm_Parse_Info *ppi)
char * M_layout_database_desc ()
int M_read_database_i (char *section_name, char *entry_name, char *field_name)
char * M_read_database_s (char *section_name, char *entry_name, char *field_name)
int M_database_info_present (char *section_name, char *entry_name, char *field_name)
void M_assert (int cc, char *mesg)
void M_set_machine (char *arch, char *model, char *swarch)
char * M_get_macro_name (int id)
void M_define_macros (STRING_Symbol_Table *sym_tbl)
int M_subroutine_call (int opc)
int M_fragile_macro (int macro_value)
Set M_fragile_macro_set ()
int M_dataflow_macro (int id)
int M_zero_macro (L_Operand *opd)
void M_define_opcode_name (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name (int id)
void M_set_swarch_tahoe (char *model_name)
int M_cannot_predicate (L_Oper *oper)
int M_extra_pred_define_opcode (int proc_opc)
int M_extra_pred_define_type1 (L_Oper *)
int M_extra_pred_define_type2 (L_Oper *)
int M_native_int_register_ctype (void)
int M_native_int_register_mtype (void)
void M_void (M_Type type)
void M_bit_llong (M_Type type, int n, int unsign)
void M_bit_long (M_Type type, int n, int unsign)
void M_bit_int (M_Type type, int n, int unsign)
void M_bit_short (M_Type type, int n, int unsign)
void M_bit_char (M_Type type, int n, int unsign)
void M_char (M_Type type, int unsign)
void M_short (M_Type type, int unsign)
void M_int (M_Type type, int unsign)
void M_long (M_Type type, int unsign)
void M_llong (M_Type type, int unsign)
void M_float (M_Type type, int unsign)
void M_double (M_Type type, int unsign)
void M_pointer (M_Type type)
void M_union (M_Type type, int align, int size)
void M_struct (M_Type type, int align, int size)
void M_block (M_Type type, int align, int size)
int M_eval_type (M_Type type, M_Type ntype)
int M_eval_type2 (M_Type type, M_Type ntype)
int M_call_type (M_Type type, M_Type ntype)
int M_call_type2 (M_Type type, M_Type ntype)
int M_type_size (int mtype)
int M_type_align (int mtype)
int M_return_value_thru_stack ()
int M_return_value_offset ()
void M_array_layout (M_Type type, int *offset)
int M_array_align (M_Type type)
int M_array_size (M_Type type, int dim)
void M_union_layout (int n, _M_Type *type, int *offset, int *bit_offset, char *union_name, char *field_name[])
int M_union_align (int n, _M_Type *type, char *union_name)
int M_union_size (int n, _M_Type *type, char *union_name)
void M_struct_layout (int n, _M_Type *type, int *base, int *bit_offset, char *struct_name, char *field_name[])
int M_struct_align (int n, _M_Type *type, char *struct_name)
int M_struct_size (int n, _M_Type *type, int struct_align, char *struct_name)
int M_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose, int need_ST)
int M_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **base_macro, int *su_sreg, int *su_ereg, int *pcount, int need_ST, int purpose)
int M_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_no_short_int (void)
int M_supports_long_long (void)
int M_pointer_size (void)
int M_compatible_type (M_Type type1, M_Type type2)
int M_layout_order (void)
void M_cb_label_name (char *fn, int cb, char *line, int len)
int M_is_cb_label (char *label, char *fn, int *cb)
void M_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_is_jumptbl_label (char *label, char *fn, int *tbl_id)
char * M_fn_name_from_label (char *label)
char * M_fn_label_name (char *label, int(*is_func)(char *is_func_label))
int M_structure_pointer (int purpose)
int M_return_register (int type, int purpose)
L_Operand * M_return_epilogue_cntr_register ()
L_Operand * M_return_loop_cntr_register ()
int M_oper_supported_in_arch (int opc)
int M_num_oper_required_for (L_Oper *oper, char *name)
int M_is_stack_operand (L_Operand *operand)
int M_is_unsafe_macro (L_Operand *operand)
void M_get_memory_operands (int *, int *, int)
int M_num_registers (int)
int M_memory_access_size (L_Oper *op)
int M_get_data_type (L_Oper *op)
int M_scaled_addressing_avail (void)
int M_is_implicit_memory_op (L_Oper *oper)
int M_coalescing_oper (L_Oper *)
IFPTR1 M_mdes_operand_type (void)
IFPTR2 M_dep_conflicting_operands (void)
int M_opc_from_proc_opc (int proc_opc)
int M_layout_retvar (M_Param param, int purpose)
Variables
int M_arch
int M_model
int M_swarch
int Mspec_num_int_caller_reg
int Mspec_num_int_callee_reg
int Mspec_num_flt_caller_reg
int Mspec_num_flt_callee_reg
int Mspec_num_dbl_caller_reg
int Mspec_num_dbl_callee_reg
int Mspec_num_prd_caller_reg
int Mspec_num_prd_callee_reg
int M_use_layout_database
char * M_layout_database_name
Define Documentation
#define M_add_symbol(table, name, id)
Value:
STRING_add_symbol((table),(name), \
                                        (void *)(id))
Definition at line 154 of file m_spec.h.
Referenced by M_define_macros_arm(), M_define_macros_bx86(), M_define_macros_hppa(), M_define_macros_playdoh(), M_define_macros_sh(), M_define_macros_sparc(), M_define_macros_starcore(), M_define_macros_tahoe(), M_define_macros_ti(), M_define_macros_wims(), M_define_macros_x86(), M_define_opcode_name_hppa(), M_define_opcode_name_playdoh(), M_define_opcode_name_ti(), and M_define_opcode_name_x86().
#define M_ALIGN_INT 32
Definition at line 222 of file m_spec.h.
#define M_ALIGN_LLONG 64
Definition at line 220 of file m_spec.h.
#define M_ARM 14
Definition at line 98 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cannot_predicate(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_supports_long_long(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_BIG_ENDIAN 1
Definition at line 376 of file m_spec.h.
Referenced by M_arm_layout_order(), M_hppa_layout_order(), M_impact_layout_order(), M_playdoh_layout_order(), M_sh_layout_order(), M_sparc_layout_order(), M_starcore_struct_layout(), M_starcore_struct_size(), M_tahoe_layout_order(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_ti_layout_order(), and M_wims_layout_order().
#define M_BX86 10
Definition at line 94 of file m_spec.h.
Referenced by M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_cb_label_name(), M_char(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_order(), M_llong(), M_long(), M_mdes_operand_type(), M_memory_access_size(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_scaled_addressing_avail(), M_set_machine(), M_short(), and M_void().
#define M_DONT_CARE_FNVAR 0
Definition at line 335 of file m_spec.h.
Referenced by M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_bx86_fnvar_layout(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sh_return_register(), M_sparc_fnvar_layout(), M_sparc_return_register(), M_starcore_fnvar_layout(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define M_GET_FNVAR 1
Definition at line 336 of file m_spec.h.
Referenced by M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_bx86_fnvar_layout(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sh_return_register(), M_sparc_fnvar_layout(), M_sparc_return_register(), M_starcore_fnvar_layout(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define M_HPPA 5
Definition at line 89 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_IMPACT 0
Definition at line 83 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cannot_predicate(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_INDIRECT_THRU_MEMORY 3
Definition at line 333 of file m_spec.h.
Referenced by M_arm_layout_retvar(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sparc_fnvar_layout(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_wims_layout_retvar().
#define M_INDIRECT_THRU_REGISTER 2
Definition at line 332 of file m_spec.h.
Referenced by M_bx86_fnvar_layout(), M_default_layout_retvar(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sparc_fnvar_layout(), M_tahoe_layout_retvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define M_JUMPTBL_BASE_NAME `_hash_`
Definition at line 103 of file m_spec.h.
Referenced by M_arm_is_jumptbl_label(), M_arm_jumptbl_label_name(), M_bx86_is_jumptbl_label(), M_bx86_jumptbl_label_name(), M_hppa_is_jumptbl_label(), M_hppa_jumptbl_label_name(), M_impact_is_jumptbl_label(), M_impact_jumptbl_label_name(), M_playdoh_is_jumptbl_label(), M_playdoh_jumptbl_label_name(), M_sh_is_jumptbl_label(), M_sh_jumptbl_label_name(), M_sparc_is_jumptbl_label(), M_sparc_jumptbl_label_name(), M_starcore_is_jumptbl_label(), M_starcore_jumptbl_label_name(), M_tahoe_is_jumptbl_label(), M_tahoe_jumptbl_label_name(), M_ti_is_jumptbl_label(), M_ti_jumptbl_label_name(), M_wims_is_jumptbl_label(), M_wims_jumptbl_label_name(), M_x86_is_jumptbl_label(), and M_x86_jumptbl_label_name().
#define M_LITTLE_ENDIAN 0
Definition at line 375 of file m_spec.h.
Referenced by M_bx86_layout_order(), M_impact_layout_order(), M_playdoh_layout_order(), M_starcore_layout_order(), M_starcore_struct_layout(), M_starcore_struct_size(), M_tahoe_layout_order(), M_tahoe_struct_layout(), M_tahoe_struct_size(), and M_x86_layout_order().
#define M_PLAYDOH 7
Definition at line 91 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cannot_predicate(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_supports_long_long(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_PUT_FNVAR 2
Definition at line 337 of file m_spec.h.
Referenced by M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_bx86_fnvar_layout(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sh_return_register(), M_sparc_fnvar_layout(), M_sparc_return_register(), M_starcore_fnvar_layout(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define M_RET_FNVAR 3
Definition at line 338 of file m_spec.h.
Referenced by M_tahoe_layout_fnvar().
#define M_SH 9
Definition at line 93 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_SIZE_CHAR 8
Definition at line 223 of file m_spec.h.
Referenced by M_memory_access_size_x86().
#define M_SIZE_INT 32
Definition at line 221 of file m_spec.h.
#define M_SIZE_LLONG 64
Definition at line 219 of file m_spec.h.
#define M_SPARC 1
Definition at line 84 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_STARCORE 12
Definition at line 96 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_coalescing_oper(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_TAHOE 11
Definition at line 95 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cannot_predicate(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_pointer_size(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_supports_long_long(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), M_void(), and M_zero_macro().
#define M_THRU_MEMORY 1
Definition at line 331 of file m_spec.h.
Referenced by M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_layout_retvar(), M_bx86_fnvar_layout(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sparc_fnvar_layout(), M_starcore_fnvar_layout(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_layout_retvar(), and M_x86_fnvar_layout().
#define M_THRU_REGISTER 0
Definition at line 330 of file m_spec.h.
Referenced by M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_bx86_fnvar_layout(), M_default_layout_retvar(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sh_fnvar_layout(), M_sparc_fnvar_layout(), M_starcore_fnvar_layout(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define M_TI 8
Definition at line 92 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_TYFL_HFA 3
Definition at line 250 of file m_spec.h.
Referenced by M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), and M_tahoe_layout_retvar().
#define M_TYFL_HFA_DBL 2
Definition at line 249 of file m_spec.h.
#define M_TYFL_HFA_SGL 1
Definition at line 248 of file m_spec.h.
#define M_TYPE_BIT_CHAR 12
Definition at line 242 of file m_spec.h.
Referenced by M_arm_bit_char(), M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_lvar_layout(), M_arm_struct_layout(), M_arm_struct_size(), M_arm_type_align(), M_arm_type_size(), M_bit_char(), M_bx86_bit_char(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_lvar_layout(), M_bx86_struct_layout(), M_bx86_struct_size(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_bit_char(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_lvar_layout(), M_hppa_struct_layout(), M_hppa_struct_size(), M_hppa_type_align(), M_hppa_type_size(), M_impact_bit_char(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_lvar_layout(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_type_align(), M_impact_type_size(), M_playdoh_bit_char(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_lvar_layout(), M_playdoh_struct_layout(), M_playdoh_struct_size(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_bit_char(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_lvar_layout(), M_sh_struct_layout(), M_sh_struct_size(), M_sh_type_align(), M_sh_type_size(), M_sparc_bit_char(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_lvar_layout(), M_sparc_struct_layout(), M_sparc_struct_size(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_bit_char(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_lvar_layout(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_type_align(), M_starcore_type_size(), M_struct_layout(), M_tahoe_bit_char(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_lvar_layout(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_bit_char(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_lvar_layout(), M_ti_struct_layout(), M_ti_struct_size(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_bit_char(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_lvar_layout(), M_wims_struct_layout(), M_wims_struct_size(), M_wims_type_align(), M_wims_type_size(), M_x86_bit_char(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_lvar_layout(), M_x86_struct_layout(), M_x86_struct_size(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_BIT_INT 14
Definition at line 244 of file m_spec.h.
Referenced by M_arm_bit_int(), M_bit_int(), M_bx86_bit_int(), M_hppa_bit_int(), M_impact_bit_int(), M_playdoh_bit_int(), M_playdoh_type_size(), M_sh_bit_int(), M_sparc_bit_int(), M_starcore_bit_int(), M_starcore_lvar_layout(), M_struct_layout(), M_tahoe_bit_int(), M_tahoe_lvar_layout(), M_ti_bit_int(), M_wims_bit_int(), and M_x86_bit_int().
#define M_TYPE_BIT_LLONG 16
Definition at line 246 of file m_spec.h.
Referenced by M_arm_bit_llong(), M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type2(), M_arm_type_align(), M_arm_type_size(), M_bit_llong(), M_call_type2(), M_eval_type2(), M_playdoh_bit_llong(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type2(), M_playdoh_type_size(), M_tahoe_bit_llong(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type2(), M_tahoe_type_size(), M_wims_bit_llong(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_type_align(), and M_wims_type_size().
#define M_TYPE_BIT_LONG 15
Definition at line 245 of file m_spec.h.
Referenced by M_arm_bit_long(), M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_lvar_layout(), M_arm_struct_layout(), M_arm_struct_size(), M_arm_type_align(), M_arm_type_size(), M_bit_long(), M_bx86_bit_long(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_lvar_layout(), M_bx86_struct_layout(), M_bx86_struct_size(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_bit_long(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_lvar_layout(), M_hppa_struct_layout(), M_hppa_struct_size(), M_hppa_type_align(), M_hppa_type_size(), M_impact_bit_long(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_lvar_layout(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_type_align(), M_impact_type_size(), M_playdoh_bit_long(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_lvar_layout(), M_playdoh_struct_layout(), M_playdoh_struct_size(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_bit_long(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_lvar_layout(), M_sh_struct_layout(), M_sh_struct_size(), M_sh_type_align(), M_sh_type_size(), M_sparc_bit_long(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_lvar_layout(), M_sparc_struct_layout(), M_sparc_struct_size(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_bit_long(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_lvar_layout(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_type_align(), M_starcore_type_size(), M_struct_layout(), M_tahoe_bit_long(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_lvar_layout(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_bit_long(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_lvar_layout(), M_ti_struct_layout(), M_ti_struct_size(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_bit_long(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_lvar_layout(), M_wims_struct_layout(), M_wims_struct_size(), M_wims_type_align(), M_wims_type_size(), M_x86_bit_long(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_lvar_layout(), M_x86_struct_layout(), M_x86_struct_size(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_BIT_SHORT 13
Definition at line 243 of file m_spec.h.
Referenced by M_arm_bit_short(), M_arm_struct_layout(), M_arm_struct_size(), M_arm_type_align(), M_arm_type_size(), M_bit_short(), M_bx86_bit_short(), M_bx86_struct_layout(), M_bx86_struct_size(), M_call_type2(), M_eval_type2(), M_hppa_bit_short(), M_hppa_struct_layout(), M_hppa_struct_size(), M_hppa_type_align(), M_hppa_type_size(), M_impact_bit_short(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_type_align(), M_playdoh_bit_short(), M_playdoh_struct_layout(), M_playdoh_struct_size(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_bit_short(), M_sh_struct_layout(), M_sparc_bit_short(), M_sparc_struct_layout(), M_sparc_struct_size(), M_starcore_bit_short(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_type_align(), M_starcore_type_size(), M_struct_layout(), M_tahoe_bit_short(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_bit_short(), M_ti_struct_layout(), M_type_align(), M_type_size(), M_wims_bit_short(), M_wims_struct_layout(), M_wims_struct_size(), M_wims_type_align(), M_wims_type_size(), M_x86_bit_short(), M_x86_struct_layout(), and M_x86_struct_size().
#define M_TYPE_BLOCK 11
Definition at line 241 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_type_align(), M_arm_type_size(), M_block(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_type_align(), M_impact_type_size(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_CHAR 1
Definition at line 231 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_char(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_char(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_char(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_char(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_char(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_type_align(), M_impact_type_size(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_char(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_char(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_char(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_char(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_char(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_char(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_char(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_char(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_DOUBLE 7
Definition at line 237 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_double(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_return_register(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_double(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_return_register(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_double(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_double(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_return_register(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_double(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_return_register(), M_impact_type_align(), M_impact_type_size(), M_memory_access_size_x86(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_double(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_return_register(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_double(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_return_register(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_double(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_return_register(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_double(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_double(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_return_register(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_double(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_return_register(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_double(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_return_register(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_double(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_return_register(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_FLOAT 6
Definition at line 236 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_float(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_return_register(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_float(), M_bx86_fnvar_layout(), M_bx86_return_register(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_float(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_float(), M_hppa_fnvar_layout(), M_hppa_return_register(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_float(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_return_register(), M_impact_type_align(), M_impact_type_size(), M_memory_access_size_x86(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_float(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_return_register(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_float(), M_sh_fnvar_layout(), M_sh_return_register(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_float(), M_sparc_return_register(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_float(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_float(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_return_register(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_float(), M_ti_fnvar_layout(), M_ti_return_register(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_float(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_return_register(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_float(), M_x86_fnvar_layout(), M_x86_return_register(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_INT 3
Definition at line 233 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_int(), M_arm_layout_fnvar(), M_arm_return_register(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_int(), M_bx86_return_register(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_int(), M_hppa_return_register(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_int(), M_impact_layout_fnvar(), M_impact_return_register(), M_impact_type_align(), M_impact_type_size(), M_int(), M_memory_access_size_x86(), M_native_int_register_mtype(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_int(), M_playdoh_layout_fnvar(), M_playdoh_return_register(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_int(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_int(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_int(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_int(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_return_register(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_int(), M_ti_return_register(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_int(), M_wims_layout_fnvar(), M_wims_return_register(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_int(), M_x86_return_register(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_LLONG 5
Definition at line 235 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_llong(), M_arm_return_register(), M_arm_type_align(), M_arm_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_llong(), M_native_int_register_mtype(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_llong(), M_playdoh_return_register(), M_playdoh_type_align(), M_playdoh_type_size(), M_starcore_fnvar_to_lvar(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_llong(), M_tahoe_return_register(), M_tahoe_type_align(), M_tahoe_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_llong(), M_wims_return_register(), M_wims_type_align(), and M_wims_type_size().
#define M_TYPE_LONG 4
Definition at line 234 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_long(), M_arm_return_register(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_long(), M_bx86_return_register(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_long(), M_hppa_return_register(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_long(), M_impact_return_register(), M_impact_type_align(), M_impact_type_size(), M_long(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_long(), M_playdoh_return_register(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_long(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_long(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_long(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_long(), M_tahoe_return_register(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_long(), M_ti_return_register(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_long(), M_wims_return_register(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_long(), M_x86_return_register(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_POINTER 8
Definition at line 238 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_pointer(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_pointer(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_pointer(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_pointer(), M_impact_type_align(), M_impact_type_size(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_pointer(), M_playdoh_type_align(), M_playdoh_type_size(), M_pointer(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_pointer(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_pointer(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_pointer(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_pointer(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_pointer(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_pointer(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_pointer(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_SHORT 2
Definition at line 232 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_short(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_short(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_short(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_short(), M_impact_type_align(), M_impact_type_size(), M_memory_access_size_x86(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_short(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_short(), M_sh_type_align(), M_sh_type_size(), M_short(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_short(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_short(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_short(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_short(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_short(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_short(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_STRUCT 10
Definition at line 240 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_layout_retvar(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_default_layout_retvar(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_type_align(), M_impact_type_size(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_lvar_layout(), M_starcore_return_register(), M_starcore_type_align(), M_starcore_type_size(), M_struct(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_lvar_layout(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_layout_retvar(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_UNION 9
Definition at line 239 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_fnvar_layout(), M_arm_layout_fnvar(), M_arm_layout_retvar(), M_arm_type_align(), M_arm_type_size(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_fnvar_layout(), M_bx86_type_align(), M_bx86_type_size(), M_call_type(), M_call_type2(), M_default_layout_retvar(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_fnvar_layout(), M_hppa_type_align(), M_hppa_type_size(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_impact_type_align(), M_impact_type_size(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_playdoh_type_align(), M_playdoh_type_size(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_fnvar_layout(), M_sh_type_align(), M_sh_type_size(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_fnvar_layout(), M_sparc_type_align(), M_sparc_type_size(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_fnvar_layout(), M_starcore_lvar_layout(), M_starcore_type_align(), M_starcore_type_size(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_lvar_layout(), M_tahoe_type_align(), M_tahoe_type_size(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_fnvar_layout(), M_ti_type_align(), M_ti_type_size(), M_type_align(), M_type_size(), M_union(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), M_wims_layout_retvar(), M_wims_type_align(), M_wims_type_size(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_fnvar_layout(), M_x86_type_align(), and M_x86_type_size().
#define M_TYPE_VOID 0
Definition at line 230 of file m_spec.h.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_arm_type_align(), M_arm_type_size(), M_arm_void(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_bx86_type_align(), M_bx86_type_size(), M_bx86_void(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_hppa_type_align(), M_hppa_type_size(), M_hppa_void(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_type_align(), M_impact_type_size(), M_impact_void(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_type_align(), M_playdoh_type_size(), M_playdoh_void(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sh_type_align(), M_sh_type_size(), M_sh_void(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_sparc_type_align(), M_sparc_type_size(), M_sparc_void(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_type_align(), M_starcore_type_size(), M_starcore_void(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), M_tahoe_type_align(), M_tahoe_type_size(), M_tahoe_void(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_ti_type_align(), M_ti_type_size(), M_ti_void(), M_type_align(), M_type_size(), M_void(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_wims_type_align(), M_wims_type_size(), M_wims_void(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), M_x86_eval_type2(), M_x86_type_align(), M_x86_type_size(), and M_x86_void().
#define M_WIMS 13
Definition at line 97 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_supports_long_long(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define M_X86 6
Definition at line 90 of file m_spec.h.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
#define MDES_OPERAND_addr 43
Definition at line 152 of file m_spec.h.
Referenced by M_operand_type_starcore().
#define MDES_OPERAND_btr 7
Definition at line 116 of file m_spec.h.
Referenced by M_operand_type_tahoe().
#define MDES_OPERAND_cntl 8
Definition at line 117 of file m_spec.h.
Referenced by M_operand_type_starcore().
#define MDES_OPERAND_f 2
Definition at line 111 of file m_spec.h.
Referenced by M_operand_type_starcore(), and M_operand_type_tahoe().
#define MDES_OPERAND_f2 3
Definition at line 112 of file m_spec.h.
#define MDES_OPERAND_i 1
Definition at line 110 of file m_spec.h.
Referenced by M_operand_type_starcore(), and M_operand_type_tahoe().
#define MDES_OPERAND_Label 5
Definition at line 114 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_ti(), M_operand_type_wims(), and M_operand_type_x86().
#define MDES_OPERAND_Lit 9
Definition at line 118 of file m_spec.h.
Referenced by M_operand_type_bx86(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), and M_operand_type_x86().
#define MDES_OPERAND_Lit1 10
Definition at line 119 of file m_spec.h.
#define MDES_OPERAND_Lit10 19
Definition at line 128 of file m_spec.h.
#define MDES_OPERAND_Lit11 20
Definition at line 129 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define MDES_OPERAND_Lit12 21
Definition at line 130 of file m_spec.h.
#define MDES_OPERAND_Lit13 22
Definition at line 131 of file m_spec.h.
#define MDES_OPERAND_Lit14 23
Definition at line 132 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define MDES_OPERAND_Lit15 24
Definition at line 133 of file m_spec.h.
#define MDES_OPERAND_Lit16 25
Definition at line 134 of file m_spec.h.
Referenced by M_operand_type_ti().
#define MDES_OPERAND_Lit17 26
Definition at line 135 of file m_spec.h.
#define MDES_OPERAND_Lit18 27
Definition at line 136 of file m_spec.h.
#define MDES_OPERAND_Lit19 28
Definition at line 137 of file m_spec.h.
#define MDES_OPERAND_Lit2 11
Definition at line 120 of file m_spec.h.
#define MDES_OPERAND_Lit20 29
Definition at line 138 of file m_spec.h.
#define MDES_OPERAND_Lit21 30
Definition at line 139 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define MDES_OPERAND_Lit22 31
Definition at line 140 of file m_spec.h.
#define MDES_OPERAND_Lit23 32
Definition at line 141 of file m_spec.h.
#define MDES_OPERAND_Lit24 33
Definition at line 142 of file m_spec.h.
Referenced by M_operand_type_ti().
#define MDES_OPERAND_Lit25 34
Definition at line 143 of file m_spec.h.
#define MDES_OPERAND_Lit26 35
Definition at line 144 of file m_spec.h.
#define MDES_OPERAND_Lit27 36
Definition at line 145 of file m_spec.h.
#define MDES_OPERAND_Lit28 37
Definition at line 146 of file m_spec.h.
#define MDES_OPERAND_Lit29 38
Definition at line 147 of file m_spec.h.
#define MDES_OPERAND_Lit3 12
Definition at line 121 of file m_spec.h.
#define MDES_OPERAND_Lit30 39
Definition at line 148 of file m_spec.h.
#define MDES_OPERAND_Lit31 40
Definition at line 149 of file m_spec.h.
#define MDES_OPERAND_Lit32 41
Definition at line 150 of file m_spec.h.
#define MDES_OPERAND_Lit4 13
Definition at line 122 of file m_spec.h.
#define MDES_OPERAND_Lit5 14
Definition at line 123 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), and M_operand_type_wims().
#define MDES_OPERAND_Lit6 15
Definition at line 124 of file m_spec.h.
#define MDES_OPERAND_Lit64 42
Definition at line 151 of file m_spec.h.
#define MDES_OPERAND_Lit7 16
Definition at line 125 of file m_spec.h.
#define MDES_OPERAND_Lit8 17
Definition at line 126 of file m_spec.h.
#define MDES_OPERAND_Lit9 18
Definition at line 127 of file m_spec.h.
#define MDES_OPERAND_NULL 0
Definition at line 109 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), M_operand_type_ti(), M_operand_type_wims(), and M_operand_type_x86().
#define MDES_OPERAND_p 4
Definition at line 113 of file m_spec.h.
Referenced by M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_playdoh(), M_operand_type_starcore(), and M_operand_type_tahoe().
#define MDES_OPERAND_REG 6
Definition at line 115 of file m_spec.h.
Referenced by M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_ti(), M_operand_type_wims(), and M_operand_type_x86().
Typedef Documentation
typedef struct _struct_M_Param _M_Param
typedef struct _struct_M_Type
 _M_Type
typedef int(*) IFPTR1(L_Operand *operand)
Definition at line 425 of file m_spec.h.
typedef int(*) IFPTR2(L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
Definition at line 426 of file m_spec.h.
typedef struct _struct_M_Param * M_Param
typedef struct _struct_M_Type * M_Type
Function Documentation
int M_array_align (M_Type type)
Definition at line 1083 of file ml_spec.c.
References _struct_M_Type::align, M_arch, M_ARM, M_arm_array_align(), M_assert(), M_HPPA, M_hppa_array_align(), M_IMPACT, M_impact_array_align(), M_PLAYDOH, M_playdoh_array_align(), M_SH, M_sh_array_align(), M_SPARC, M_sparc_array_align(), M_STARCORE, M_starcore_array_align(), M_TAHOE, M_tahoe_array_align(), M_TI, M_ti_array_align(), M_use_layout_database, M_WIMS, M_wims_array_align(), M_X86, and M_x86_array_align().
void M_array_layout (M_Type type, int * offset)
Definition at line 1032 of file ml_spec.c.
References M_arch, M_ARM, M_arm_array_layout(), M_assert(), M_HPPA, M_hppa_array_layout(), M_IMPACT, M_impact_array_layout(), M_PLAYDOH, M_playdoh_array_layout(), M_SH, M_sh_array_layout(), M_SPARC, M_sparc_array_layout(), M_STARCORE, M_starcore_array_layout(), M_TAHOE, M_tahoe_array_layout(), M_TI, M_ti_array_layout(), M_use_layout_database, M_WIMS, M_wims_array_layout(), M_X86, and M_x86_array_layout().
int M_array_size (M_Type type, int dim)
Definition at line 1125 of file ml_spec.c.
References _struct_M_Type::align, M_arch, M_ARM, M_arm_array_size(), M_assert(), M_HPPA, M_hppa_array_size(), M_IMPACT, M_impact_array_size(), M_PLAYDOH, M_playdoh_array_size(), M_SH, M_sh_array_size(), M_SPARC, M_sparc_array_size(), M_STARCORE, M_starcore_array_size(), M_TAHOE, M_tahoe_array_size(), M_TI, M_ti_array_size(), M_use_layout_database, M_WIMS, M_wims_array_size(), M_X86, M_x86_array_size(), and _struct_M_Type::size.
void M_assert (int cc, char * mesg)
Definition at line 128 of file mi_spec.c.
References I_punt().
Referenced by M_arm_bit_char(), M_arm_bit_int(), M_arm_bit_llong(), M_arm_bit_long(), M_arm_bit_short(), M_arm_fnvar_layout(), M_arm_fragile_macro(), M_arm_layout_fnvar(), M_arm_lvar_layout(), M_arm_struct_layout(), M_arm_struct_size(), M_arm_subroutine_call(), M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_block(), M_bx86_bit_char(), M_bx86_bit_int(), M_bx86_bit_long(), M_bx86_bit_short(), M_bx86_fnvar_layout(), M_bx86_fragile_macro(), M_bx86_lvar_layout(), M_bx86_struct_layout(), M_bx86_struct_size(), M_bx86_subroutine_call(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_conflicting_operands_arm(), M_conflicting_operands_bx86(), M_conflicting_operands_hppa(), M_conflicting_operands_impact(), M_conflicting_operands_impact_hp_lcode(), M_conflicting_operands_impact_lcode(), M_conflicting_operands_impact_sparc_lcode(), M_conflicting_operands_playdoh(), M_conflicting_operands_sh(), M_conflicting_operands_sparc(), M_conflicting_operands_starcore(), M_conflicting_operands_tahoe(), M_conflicting_operands_ti(), M_conflicting_operands_wims(), M_dataflow_macro(), M_define_macros(), M_define_macros_impact(), M_define_macros_playdoh(), M_define_macros_starcore(), M_define_macros_tahoe(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_data_type_bx86(), M_get_data_type_x86(), M_get_macro_name(), M_get_macro_name_impact(), M_get_macro_name_playdoh(), M_get_macro_name_starcore(), M_get_macro_name_tahoe(), M_get_opcode_name(), M_hppa_bit_char(), M_hppa_bit_int(), M_hppa_bit_long(), M_hppa_bit_short(), M_hppa_dataflow_macro(), M_hppa_fnvar_layout(), M_hppa_fragile_macro(), M_hppa_fragile_macro_set(), M_hppa_lvar_layout(), M_hppa_struct_layout(), M_hppa_struct_size(), M_hppa_subroutine_call(), M_impact_array_align(), M_impact_array_layout(), M_impact_array_size(), M_impact_bit_char(), M_impact_bit_int(), M_impact_bit_long(), M_impact_bit_short(), M_impact_call_type(), M_impact_call_type2(), M_impact_cb_label_name(), M_impact_char(), M_impact_dataflow_macro(), M_impact_double(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_float(), M_impact_fnvar_layout(), M_impact_fragile_macro(), M_impact_fragile_macro_set(), M_impact_int(), M_impact_is_cb_label(), M_impact_is_jumptbl_label(), M_impact_jumptbl_label_name(), M_impact_layout_fnvar(), M_impact_layout_order(), M_impact_long(), M_impact_lvar_layout(), M_impact_no_short_int(), M_impact_pointer(), M_impact_return_register(), M_impact_short(), M_impact_struct_align(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_structure_pointer(), M_impact_subroutine_call(), M_impact_type_align(), M_impact_type_size(), M_impact_union_align(), M_impact_union_layout(), M_impact_union_size(), M_impact_void(), M_int(), M_is_cb_label(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_stack_operand_impact(), M_is_stack_operand_playdoh(), M_is_stack_operand_starcore(), M_is_stack_operand_tahoe(), M_is_unsafe_macro(), M_is_unsafe_macro_impact(), M_is_unsafe_macro_playdoh(), M_is_unsafe_macro_starcore(), M_is_unsafe_macro_tahoe(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_memory_access_size_x86(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_starcore(), M_num_oper_required_for_tahoe(), M_num_registers(), M_num_registers_arm(), M_num_registers_hppa(), M_num_registers_sh(), M_num_registers_sparc(), M_num_registers_ti(), M_num_registers_wims(), M_opc_from_proc_opc(), M_opc_from_proc_opc_playdoh(), M_opc_from_proc_opc_starcore(), M_opc_from_proc_opc_tahoe(), M_oper_supported_in_arch(), M_oper_supported_in_arch_impact(), M_oper_supported_in_arch_playdoh(), M_oper_supported_in_arch_starcore(), M_oper_supported_in_arch_tahoe(), M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact(), M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), M_operand_type_ti(), M_operand_type_wims(), M_operand_type_x86(), M_playdoh_array_align(), M_playdoh_array_layout(), M_playdoh_array_size(), M_playdoh_bit_char(), M_playdoh_bit_int(), M_playdoh_bit_llong(), M_playdoh_bit_long(), M_playdoh_bit_short(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_cb_label_name(), M_playdoh_char(), M_playdoh_dataflow_macro(), M_playdoh_double(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_float(), M_playdoh_fn_label_name(), M_playdoh_fn_name_from_label(), M_playdoh_fnvar_layout(), M_playdoh_fragile_macro(), M_playdoh_fragile_macro_set(), M_playdoh_int(), M_playdoh_is_cb_label(), M_playdoh_is_jumptbl_label(), M_playdoh_jumptbl_label_name(), M_playdoh_layout_fnvar(), M_playdoh_layout_order(), M_playdoh_long(), M_playdoh_lvar_layout(), M_playdoh_no_short_int(), M_playdoh_pointer(), M_playdoh_return_register(), M_playdoh_short(), M_playdoh_struct_align(), M_playdoh_struct_layout(), M_playdoh_struct_size(), M_playdoh_structure_pointer(), M_playdoh_subroutine_call(), M_playdoh_type_align(), M_playdoh_type_size(), M_playdoh_union_align(), M_playdoh_union_layout(), M_playdoh_union_size(), M_playdoh_void(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_set_machine(), M_set_model_arm(), M_set_model_bx86(), M_set_model_hppa(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_sh(), M_set_model_sparc(), M_set_model_starcore(), M_set_model_tahoe(), M_set_model_ti(), M_set_model_wims(), M_set_model_x86(), M_set_swarch_tahoe(), M_sh_bit_char(), M_sh_bit_int(), M_sh_bit_long(), M_sh_bit_short(), M_sh_dataflow_macro(), M_sh_fnvar_layout(), M_sh_fragile_macro(), M_sh_fragile_macro_set(), M_sh_lvar_layout(), M_sh_struct_layout(), M_sh_struct_size(), M_sh_subroutine_call(), M_short(), M_sparc_bit_char(), M_sparc_bit_int(), M_sparc_bit_long(), M_sparc_bit_short(), M_sparc_dataflow_macro(), M_sparc_fnvar_layout(), M_sparc_fragile_macro(), M_sparc_fragile_macro_set(), M_sparc_lvar_layout(), M_sparc_struct_layout(), M_sparc_struct_size(), M_sparc_subroutine_call(), M_starcore_array_align(), M_starcore_array_layout(), M_starcore_array_size(), M_starcore_bit_char(), M_starcore_bit_int(), M_starcore_bit_long(), M_starcore_bit_short(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_cb_label_name(), M_starcore_char(), M_starcore_dataflow_macro(), M_starcore_double(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_float(), M_starcore_fn_label_name(), M_starcore_fn_name_from_label(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_fragile_macro(), M_starcore_int(), M_starcore_is_cb_label(), M_starcore_is_jumptbl_label(), M_starcore_jumptbl_label_name(), M_starcore_layout_order(), M_starcore_long(), M_starcore_lvar_layout(), M_starcore_no_short_int(), M_starcore_pointer(), M_starcore_return_register(), M_starcore_short(), M_starcore_struct_align(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_structure_pointer(), M_starcore_subroutine_call(), M_starcore_type_align(), M_starcore_type_size(), M_starcore_union_align(), M_starcore_union_layout(), M_starcore_union_size(), M_starcore_void(), M_struct(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_tahoe_bit_char(), M_tahoe_bit_int(), M_tahoe_bit_llong(), M_tahoe_bit_long(), M_tahoe_bit_short(), M_tahoe_dataflow_macro(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_fragile_macro(), M_tahoe_layout_fnvar(), M_tahoe_layout_order(), M_tahoe_layout_retvar(), M_tahoe_lvar_layout(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_tahoe_subroutine_call(), M_ti_bit_int(), M_ti_bit_long(), M_ti_bit_short(), M_ti_fnvar_layout(), M_ti_fragile_macro(), M_ti_lvar_layout(), M_ti_struct_layout(), M_ti_struct_size(), M_ti_subroutine_call(), M_type_align(), M_type_size(), M_union(), M_union_align(), M_union_layout(), M_union_size(), M_void(), M_wims_bit_char(), M_wims_bit_int(), M_wims_bit_llong(), M_wims_bit_long(), M_wims_bit_short(), M_wims_double(), M_wims_float(), M_wims_fnvar_layout(), M_wims_fragile_macro(), M_wims_layout_fnvar(), M_wims_lvar_layout(), M_wims_return_register(), M_wims_struct_layout(), M_wims_struct_size(), M_wims_subroutine_call(), M_x86_bit_char(), M_x86_bit_int(), M_x86_bit_long(), M_x86_bit_short(), M_x86_fnvar_layout(), M_x86_fragile_macro(), M_x86_lvar_layout(), M_x86_struct_layout(), M_x86_struct_size(), and M_x86_subroutine_call().
void M_bit_char (M_Type type, int n, int unsign)
Definition at line 401 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_char(), M_assert(), M_BX86, M_bx86_bit_char(), M_HPPA, M_hppa_bit_char(), M_IMPACT, M_impact_bit_char(), M_PLAYDOH, M_playdoh_bit_char(), M_read_database_i(), M_SH, M_sh_bit_char(), M_SPARC, M_sparc_bit_char(), M_STARCORE, M_starcore_bit_char(), M_TAHOE, M_tahoe_bit_char(), M_TI, M_ti_bit_char(), M_TYPE_BIT_CHAR, M_use_layout_database, M_WIMS, M_wims_bit_char(), M_X86, M_x86_bit_char(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_int (M_Type type, int n, int unsign)
Definition at line 263 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_int(), M_assert(), M_BX86, M_bx86_bit_int(), M_HPPA, M_hppa_bit_int(), M_IMPACT, M_impact_bit_int(), M_PLAYDOH, M_playdoh_bit_int(), M_read_database_i(), M_SH, M_sh_bit_int(), M_SPARC, M_sparc_bit_int(), M_STARCORE, M_starcore_bit_int(), M_TAHOE, M_tahoe_bit_int(), M_TI, M_ti_bit_int(), M_TYPE_BIT_INT, M_use_layout_database, M_WIMS, M_wims_bit_int(), M_X86, M_x86_bit_int(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_llong (M_Type type, int n, int unsign)
Definition at line 157 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_assert(), M_read_database_i(), M_TAHOE, M_tahoe_bit_llong(), M_TYPE_BIT_LLONG, M_use_layout_database, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_long (M_Type type, int n, int unsign)
Definition at line 194 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_long(), M_assert(), M_BX86, M_bx86_bit_long(), M_HPPA, M_hppa_bit_long(), M_IMPACT, M_impact_bit_long(), M_PLAYDOH, M_playdoh_bit_long(), M_read_database_i(), M_SH, M_sh_bit_long(), M_SPARC, M_sparc_bit_long(), M_STARCORE, M_starcore_bit_long(), M_TAHOE, M_tahoe_bit_long(), M_TI, M_ti_bit_long(), M_TYPE_BIT_LONG, M_use_layout_database, M_WIMS, M_wims_bit_long(), M_X86, M_x86_bit_long(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_short (M_Type type, int n, int unsign)
Definition at line 332 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_short(), M_assert(), M_BX86, M_bx86_bit_short(), M_HPPA, M_hppa_bit_short(), M_IMPACT, M_impact_bit_short(), M_PLAYDOH, M_playdoh_bit_short(), M_read_database_i(), M_SH, M_sh_bit_short(), M_SPARC, M_sparc_bit_short(), M_STARCORE, M_starcore_bit_short(), M_TAHOE, M_tahoe_bit_short(), M_TI, M_ti_bit_short(), M_TYPE_BIT_SHORT, M_use_layout_database, M_WIMS, M_wims_bit_short(), M_X86, M_x86_bit_short(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_block (M_Type type, int align, int size)
Definition at line 683 of file ml_spec.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BLOCK, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_call_type (M_Type type, M_Type ntype)
Definition at line 867 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_call_type(), M_assert(), M_double(), M_float(), M_HPPA, M_hppa_call_type(), M_IMPACT, M_impact_call_type(), M_int(), M_llong(), M_native_int_register_mtype(), M_PLAYDOH, M_playdoh_call_type(), M_SH, M_sh_call_type(), M_SPARC, M_sparc_call_type(), M_STARCORE, M_starcore_call_type(), M_TAHOE, M_tahoe_call_type(), M_TI, M_ti_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_call_type(), M_X86, M_x86_call_type(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_call_type2 (M_Type type, M_Type ntype)
Definition at line 949 of file ml_spec.c.
References M_arch, M_ARM, M_arm_call_type2(), M_assert(), M_char(), M_double(), M_float(), M_HPPA, M_hppa_call_type2(), M_IMPACT, M_impact_call_type2(), M_int(), M_llong(), M_long(), M_PLAYDOH, M_playdoh_call_type2(), M_pointer(), M_SH, M_sh_call_type2(), M_short(), M_SPARC, M_sparc_call_type2(), M_STARCORE, M_starcore_call_type2(), M_TAHOE, M_tahoe_call_type2(), M_TI, M_ti_call_type2(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_call_type2(), M_X86, M_x86_call_type2(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_cannot_predicate (L_Oper * oper)
Definition at line 3203 of file ml_spec.c.
References M_arch, M_ARM, M_cannot_predicate_tahoe(), M_IMPACT, M_PLAYDOH, and M_TAHOE.
void M_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1927 of file ml_spec.c.
References M_arch, M_ARM, M_arm_cb_label_name(), M_assert(), M_BX86, M_bx86_cb_label_name(), M_HPPA, M_hppa_cb_label_name(), M_IMPACT, M_impact_cb_label_name(), M_PLAYDOH, M_playdoh_cb_label_name(), M_SH, M_sh_cb_label_name(), M_SPARC, M_sparc_cb_label_name(), M_STARCORE, M_starcore_cb_label_name(), M_TAHOE, M_tahoe_cb_label_name(), M_TI, M_ti_cb_label_name(), M_WIMS, M_wims_cb_label_name(), M_X86, and M_x86_cb_label_name().
void M_char (M_Type type, int unsign)
Definition at line 221 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_char(), M_assert(), M_BX86, M_bx86_char(), M_HPPA, M_hppa_char(), M_IMPACT, M_impact_char(), M_PLAYDOH, M_playdoh_char(), M_read_database_i(), M_SH, M_sh_char(), M_SPARC, M_sparc_char(), M_STARCORE, M_starcore_char(), M_TAHOE, M_tahoe_char(), M_TI, M_ti_char(), M_TYPE_CHAR, M_use_layout_database, M_WIMS, M_wims_char(), M_X86, M_x86_char(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_coalescing_oper (L_Oper *)
Definition at line 3223 of file ml_spec.c.
References M_arch, M_STARCORE, and M_starcore_coalescing_oper().
int M_compatible_type (M_Type type1, M_Type type2)
Definition at line 1915 of file ml_spec.c.
References M_eval_type(), and _struct_M_Type::type.
int M_database_info_present (char * section_name, char * entry_name, char * field_name)
Definition at line 917 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_read_md(), and NULL.
int M_dataflow_macro (int id)
Definition at line 2502 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_hppa_dataflow_macro(), M_IMPACT, M_impact_dataflow_macro(), M_PLAYDOH, M_SH, M_sh_dataflow_macro(), M_SPARC, M_sparc_dataflow_macro(), M_STARCORE, M_starcore_dataflow_macro(), M_TAHOE, M_tahoe_dataflow_macro(), M_TI, M_WIMS, and M_X86.
void M_define_macros (STRING_Symbol_Table * sym_tbl)
Definition at line 2587 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_define_macros_arm(), M_define_macros_bx86(), M_define_macros_hppa(), M_define_macros_impact(), M_define_macros_playdoh(), M_define_macros_sh(), M_define_macros_sparc(), M_define_macros_starcore(), M_define_macros_tahoe(), M_define_macros_ti(), M_define_macros_wims(), M_define_macros_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_define_opcode_name (STRING_Symbol_Table * sym_tbl)
Definition at line 2669 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_define_opcode_name_arm(), M_define_opcode_name_bx86(), M_define_opcode_name_hppa(), M_define_opcode_name_playdoh(), M_define_opcode_name_starcore(), M_define_opcode_name_ti(), M_define_opcode_name_wims(), M_define_opcode_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
IFPTR2 M_dep_conflicting_operands (void)
Definition at line 2952 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_conflicting_operands_arm(), M_conflicting_operands_bx86(), M_conflicting_operands_hppa(), M_conflicting_operands_impact(), M_conflicting_operands_playdoh(), M_conflicting_operands_sh(), M_conflicting_operands_sparc(), M_conflicting_operands_starcore(), M_conflicting_operands_tahoe(), M_conflicting_operands_ti(), M_conflicting_operands_wims(), M_conflicting_operands_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
void M_double (M_Type type, int unsign)
Definition at line 529 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_double(), M_assert(), M_BX86, M_bx86_double(), M_HPPA, M_hppa_double(), M_IMPACT, M_impact_double(), M_PLAYDOH, M_playdoh_double(), M_read_database_i(), M_SH, M_sh_double(), M_SPARC, M_sparc_double(), M_STARCORE, M_starcore_double(), M_TAHOE, M_tahoe_double(), M_TI, M_ti_double(), M_TYPE_DOUBLE, M_use_layout_database, M_WIMS, M_wims_double(), M_X86, M_x86_double(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
int M_eval_type (M_Type type, M_Type ntype)
Definition at line 699 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_eval_type(), M_assert(), M_BX86, M_bx86_eval_type(), M_double(), M_float(), M_HPPA, M_hppa_eval_type(), M_IMPACT, M_impact_eval_type(), M_int(), M_llong(), M_native_int_register_mtype(), M_PLAYDOH, M_playdoh_eval_type(), M_SH, M_sh_eval_type(), M_SPARC, M_sparc_eval_type(), M_STARCORE, M_starcore_eval_type(), M_TAHOE, M_tahoe_eval_type(), M_TI, M_ti_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_eval_type(), M_X86, M_x86_eval_type(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_compatible_type().
int M_eval_type2 (M_Type type, M_Type ntype)
Definition at line 783 of file ml_spec.c.
References M_arch, M_ARM, M_arm_eval_type2(), M_assert(), M_BX86, M_bx86_eval_type2(), M_char(), M_double(), M_float(), M_HPPA, M_hppa_eval_type2(), M_IMPACT, M_impact_eval_type2(), M_int(), M_llong(), M_long(), M_PLAYDOH, M_playdoh_eval_type2(), M_pointer(), M_SH, M_sh_eval_type2(), M_short(), M_SPARC, M_sparc_eval_type2(), M_STARCORE, M_starcore_eval_type2(), M_TAHOE, M_tahoe_eval_type2(), M_TI, M_ti_eval_type2(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_eval_type2(), M_X86, M_x86_eval_type2(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_extra_pred_define_opcode (int proc_opc)
Definition at line 2411 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_STARCORE, M_starcore_extra_pred_define_opcode(), M_TAHOE, and M_tahoe_extra_pred_define_opcode().
int M_extra_pred_define_type1 (L_Oper *)
Definition at line 2433 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_TAHOE, and M_tahoe_extra_pred_define_type1().
int M_extra_pred_define_type2 (L_Oper *)
Definition at line 2452 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_TAHOE, and M_tahoe_extra_pred_define_type2().
void M_float (M_Type type, int unsign)
Definition at line 469 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_float(), M_assert(), M_BX86, M_bx86_float(), M_HPPA, M_hppa_float(), M_IMPACT, M_impact_float(), M_PLAYDOH, M_playdoh_float(), M_read_database_i(), M_SH, M_sh_float(), M_SPARC, M_sparc_float(), M_STARCORE, M_starcore_float(), M_TAHOE, M_tahoe_float(), M_TI, M_ti_float(), M_TYPE_FLOAT, M_use_layout_database, M_WIMS, M_wims_float(), M_X86, M_x86_float(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
char* M_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 2089 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fn_label_name(), M_assert(), M_BX86, M_bx86_fn_label_name(), M_HPPA, M_hppa_fn_label_name(), M_IMPACT, M_impact_fn_label_name(), M_PLAYDOH, M_playdoh_fn_label_name(), M_SH, M_SPARC, M_sparc_fn_label_name(), M_STARCORE, M_starcore_fn_label_name(), M_TAHOE, M_tahoe_fn_label_name(), M_TI, M_WIMS, M_wims_fn_label_name(), M_X86, and M_x86_fn_label_name().
char* M_fn_name_from_label (char * label)
Definition at line 2124 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fn_name_from_label(), M_assert(), M_BX86, M_bx86_fn_name_from_label(), M_HPPA, M_hppa_fn_name_from_label(), M_IMPACT, M_impact_fn_name_from_label(), M_PLAYDOH, M_playdoh_fn_name_from_label(), M_SH, M_SPARC, M_sparc_fn_name_from_label(), M_STARCORE, M_starcore_fn_name_from_label(), M_TAHOE, M_tahoe_fn_name_from_label(), M_TI, M_WIMS, M_X86, and M_x86_fn_name_from_label().
int M_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** base_macro, int * su_sreg, int * su_ereg, int * pcount, int need_ST, int purpose)
Definition at line 1712 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fnvar_layout(), M_assert(), M_HPPA, M_hppa_fnvar_layout(), M_IMPACT, M_impact_fnvar_layout(), M_PLAYDOH, M_playdoh_fnvar_layout(), M_SH, M_sh_fnvar_layout(), M_SPARC, M_sparc_fnvar_layout(), M_STARCORE, M_starcore_fnvar_layout(), M_TAHOE, M_tahoe_fnvar_layout(), M_TI, M_ti_fnvar_layout(), M_WIMS, M_wims_fnvar_layout(), M_X86, and M_x86_fnvar_layout().
int M_fragile_macro (int macro_value)
Definition at line 2361 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fragile_macro(), M_assert(), M_BX86, M_bx86_fragile_macro(), M_HPPA, M_hppa_fragile_macro(), M_IMPACT, M_impact_fragile_macro(), M_PLAYDOH, M_playdoh_fragile_macro(), M_SH, M_sh_fragile_macro(), M_SPARC, M_sparc_fragile_macro(), M_STARCORE, M_starcore_fragile_macro(), M_TAHOE, M_tahoe_fragile_macro(), M_TI, M_ti_fragile_macro(), M_WIMS, M_wims_fragile_macro(), M_X86, and M_x86_fragile_macro().
Set M_fragile_macro_set ()
Definition at line 2471 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_hppa_fragile_macro_set(), M_IMPACT, M_impact_fragile_macro_set(), M_PLAYDOH, M_playdoh_fragile_macro_set(), M_SH, M_sh_fragile_macro_set(), M_SPARC, M_sparc_fragile_macro_set(), M_STARCORE, M_starcore_fragile_macro_set(), M_TAHOE, M_tahoe_fragile_macro_set(), M_TI, M_WIMS, M_X86, and NULL.
int M_get_data_type (L_Oper * op)
Definition at line 3095 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_data_type_bx86(), M_get_data_type_starcore(), M_get_data_type_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
char* M_get_macro_name (int id)
Definition at line 2634 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_macro_name_arm(), M_get_macro_name_bx86(), M_get_macro_name_hppa(), M_get_macro_name_impact(), M_get_macro_name_playdoh(), M_get_macro_name_sh(), M_get_macro_name_sparc(), M_get_macro_name_starcore(), M_get_macro_name_tahoe(), M_get_macro_name_ti(), M_get_macro_name_wims(), M_get_macro_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_get_memory_operands (int *, int *, int)
Definition at line 2995 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_get_memory_operands_bx86(), M_get_memory_operands_starcore(), M_get_memory_operands_tahoe(), M_get_memory_operands_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
char* M_get_opcode_name (int id)
Definition at line 2722 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_opcode_name_arm(), M_get_opcode_name_bx86(), M_get_opcode_name_hppa(), M_get_opcode_name_playdoh(), M_get_opcode_name_starcore(), M_get_opcode_name_ti(), M_get_opcode_name_wims(), M_get_opcode_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_int (M_Type type, int unsign)
Definition at line 341 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_int(), M_assert(), M_BX86, M_bx86_int(), M_HPPA, M_hppa_int(), M_IMPACT, M_impact_int(), M_PLAYDOH, M_playdoh_int(), M_read_database_i(), M_SH, M_sh_int(), M_SPARC, M_sparc_int(), M_STARCORE, M_starcore_int(), M_TAHOE, M_tahoe_int(), M_TI, M_ti_int(), M_TYPE_INT, M_use_layout_database, M_WIMS, M_wims_int(), M_X86, M_x86_int(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
int M_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1973 of file ml_spec.c.
References M_arch, M_ARM, M_arm_is_cb_label(), M_assert(), M_BX86, M_bx86_is_cb_label(), M_HPPA, M_hppa_is_cb_label(), M_IMPACT, M_impact_is_cb_label(), M_PLAYDOH, M_playdoh_is_cb_label(), M_SH, M_sh_is_cb_label(), M_SPARC, M_sparc_is_cb_label(), M_STARCORE, M_starcore_is_cb_label(), M_TAHOE, M_tahoe_is_cb_label(), M_TI, M_ti_is_cb_label(), M_WIMS, M_wims_is_cb_label(), M_X86, and M_x86_is_cb_label().
int M_is_implicit_memory_op (L_Oper * oper)
Definition at line 3147 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_HPPA, M_IMPACT, M_is_implicit_memory_op_bx86(), M_is_implicit_memory_op_starcore(), M_is_implicit_memory_op_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 2054 of file ml_spec.c.
References M_arch, M_ARM, M_arm_is_jumptbl_label(), M_assert(), M_BX86, M_bx86_is_jumptbl_label(), M_HPPA, M_hppa_is_jumptbl_label(), M_IMPACT, M_impact_is_jumptbl_label(), M_PLAYDOH, M_playdoh_is_jumptbl_label(), M_SH, M_sh_is_jumptbl_label(), M_SPARC, M_sparc_is_jumptbl_label(), M_STARCORE, M_starcore_is_jumptbl_label(), M_TAHOE, M_tahoe_is_jumptbl_label(), M_TI, M_ti_is_jumptbl_label(), M_WIMS, M_wims_is_jumptbl_label(), M_X86, and M_x86_is_jumptbl_label().
int M_is_stack_operand (L_Operand * operand)
Definition at line 2841 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_is_stack_operand_arm(), M_is_stack_operand_bx86(), M_is_stack_operand_hppa(), M_is_stack_operand_impact(), M_is_stack_operand_playdoh(), M_is_stack_operand_sh(), M_is_stack_operand_sparc(), M_is_stack_operand_starcore(), M_is_stack_operand_tahoe(), M_is_stack_operand_ti(), M_is_stack_operand_wims(), M_is_stack_operand_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_is_unsafe_macro (L_Operand * operand)
Definition at line 2879 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_is_unsafe_macro_arm(), M_is_unsafe_macro_bx86(), M_is_unsafe_macro_hppa(), M_is_unsafe_macro_impact(), M_is_unsafe_macro_playdoh(), M_is_unsafe_macro_sh(), M_is_unsafe_macro_sparc(), M_is_unsafe_macro_starcore(), M_is_unsafe_macro_tahoe(), M_is_unsafe_macro_ti(), M_is_unsafe_macro_wims(), M_is_unsafe_macro_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
void M_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 2008 of file ml_spec.c.
References M_arch, M_ARM, M_arm_jumptbl_label_name(), M_assert(), M_BX86, M_bx86_jumptbl_label_name(), M_HPPA, M_hppa_jumptbl_label_name(), M_IMPACT, M_impact_jumptbl_label_name(), M_PLAYDOH, M_playdoh_jumptbl_label_name(), M_SH, M_sh_jumptbl_label_name(), M_SPARC, M_sparc_jumptbl_label_name(), M_STARCORE, M_starcore_jumptbl_label_name(), M_TAHOE, M_tahoe_jumptbl_label_name(), M_TI, M_ti_jumptbl_label_name(), M_WIMS, M_wims_jumptbl_label_name(), M_X86, and M_x86_jumptbl_label_name().
char* M_layout_database_desc ()
Definition at line 695 of file mi_spec.c.
References entry, M_layout_database, MD_find_section, MD_first_entry(), and NULL.
Referenced by M_read_database_i(), M_read_database_s(), and M_struct_layout().
int M_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose, int need_ST)
Definition at line 1631 of file ml_spec.c.
References M_arch, M_ARM, M_arm_layout_fnvar(), M_assert(), M_HPPA, M_hppa_layout_fnvar(), M_IMPACT, M_impact_layout_fnvar(), M_PLAYDOH, M_playdoh_layout_fnvar(), M_SH, M_sh_layout_fnvar(), M_SPARC, M_sparc_layout_fnvar(), M_STARCORE, M_starcore_layout_fnvar(), M_TAHOE, M_tahoe_layout_fnvar(), M_TI, M_ti_layout_fnvar(), M_WIMS, M_wims_layout_fnvar(), M_X86, and M_x86_layout_fnvar().
int M_layout_order (void)
Definition at line 656 of file mi_spec.c.
References M_arch, M_ARM, M_arm_layout_order(), M_assert(), M_BX86, M_bx86_layout_order(), M_HPPA, M_hppa_layout_order(), M_IMPACT, M_impact_layout_order(), M_PLAYDOH, M_playdoh_layout_order(), M_SH, M_sh_layout_order(), M_SPARC, M_sparc_layout_order(), M_STARCORE, M_starcore_layout_order(), M_TAHOE, M_tahoe_layout_order(), M_TI, M_ti_layout_order(), M_WIMS, M_wims_layout_order(), M_X86, and M_x86_layout_order().
int M_layout_retvar (M_Param param, int purpose)
Definition at line 1678 of file ml_spec.c.
References M_arch, M_ARM, M_arm_layout_retvar(), M_assert(), M_default_layout_retvar(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_tahoe_layout_retvar(), M_TI, M_WIMS, M_wims_layout_retvar(), and M_X86.
void M_llong (M_Type type, int unsign)
Definition at line 461 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_llong(), M_assert(), M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_playdoh_llong(), M_read_database_i(), M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_tahoe_llong(), M_TI, M_TYPE_LLONG, M_use_layout_database, M_WIMS, M_wims_llong(), M_X86, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type(), M_call_type2(), M_eval_type(), and M_eval_type2().
void M_long (M_Type type, int unsign)
Definition at line 401 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_long(), M_assert(), M_BX86, M_bx86_long(), M_HPPA, M_hppa_long(), M_IMPACT, M_impact_long(), M_PLAYDOH, M_playdoh_long(), M_read_database_i(), M_SH, M_sh_long(), M_SPARC, M_sparc_long(), M_STARCORE, M_starcore_long(), M_TAHOE, M_tahoe_long(), M_TI, M_ti_long(), M_TYPE_LONG, M_use_layout_database, M_WIMS, M_wims_long(), M_X86, M_x86_long(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1789 of file ml_spec.c.
References M_arch, M_ARM, M_arm_lvar_layout(), M_assert(), M_HPPA, M_hppa_lvar_layout(), M_IMPACT, M_impact_lvar_layout(), M_PLAYDOH, M_playdoh_lvar_layout(), M_SH, M_sh_lvar_layout(), M_SPARC, M_sparc_lvar_layout(), M_STARCORE, M_starcore_lvar_layout(), M_TAHOE, M_tahoe_lvar_layout(), M_TI, M_ti_lvar_layout(), M_WIMS, M_wims_lvar_layout(), M_X86, and M_x86_lvar_layout().
IFPTR1 M_mdes_operand_type (void)
Definition at line 2917 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), M_operand_type_ti(), M_operand_type_wims(), M_operand_type_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_memory_access_size (L_Oper * op)
Definition at line 3065 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_memory_access_size_bx86(), M_memory_access_size_starcore(), M_memory_access_size_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_native_int_register_ctype (void)
Definition at line 1822 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_native_int_register_mtype (void)
Definition at line 1847 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_TYPE_INT, M_TYPE_LLONG, M_WIMS, and M_X86.
Referenced by M_call_type(), and M_eval_type().
int M_no_short_int (void)
Definition at line 1872 of file ml_spec.c.
References M_arch, M_ARM, M_arm_no_short_int(), M_assert(), M_HPPA, M_hppa_no_short_int(), M_IMPACT, M_impact_no_short_int(), M_PLAYDOH, M_playdoh_no_short_int(), M_read_database_i(), M_SH, M_sh_no_short_int(), M_SPARC, M_sparc_no_short_int(), M_STARCORE, M_starcore_no_short_int(), M_TAHOE, M_tahoe_no_short_int(), M_TI, M_ti_no_short_int(), M_use_layout_database, M_WIMS, M_wims_no_short_int(), M_X86, and M_x86_no_short_int().
int M_num_oper_required_for (L_Oper * oper, char * name)
Definition at line 2806 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_sh(), M_num_oper_required_for_sparc(), M_num_oper_required_for_starcore(), M_num_oper_required_for_tahoe(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), M_num_oper_required_for_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_num_registers (int)
Definition at line 3029 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_num_registers_arm(), M_num_registers_bx86(), M_num_registers_hppa(), M_num_registers_impact(), M_num_registers_playdoh(), M_num_registers_sh(), M_num_registers_sparc(), M_num_registers_starcore(), M_num_registers_tahoe(), M_num_registers_ti(), M_num_registers_wims(), M_num_registers_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_opc_from_proc_opc (int proc_opc)
Definition at line 3173 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_opc_from_proc_opc_playdoh(), M_opc_from_proc_opc_starcore(), M_opc_from_proc_opc_tahoe(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_oper_supported_in_arch (int opc)
Definition at line 2765 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_oper_supported_in_arch_arm(), M_oper_supported_in_arch_bx86(), M_oper_supported_in_arch_hppa(), M_oper_supported_in_arch_impact(), M_oper_supported_in_arch_playdoh(), M_oper_supported_in_arch_sh(), M_oper_supported_in_arch_sparc(), M_oper_supported_in_arch_starcore(), M_oper_supported_in_arch_tahoe(), M_oper_supported_in_arch_ti(), M_oper_supported_in_arch_wims(), M_oper_supported_in_arch_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_pointer (M_Type type)
Definition at line 589 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_pointer(), M_assert(), M_BX86, M_bx86_pointer(), M_HPPA, M_hppa_pointer(), M_IMPACT, M_impact_pointer(), M_PLAYDOH, M_playdoh_pointer(), M_read_database_i(), M_SH, M_sh_pointer(), M_SPARC, M_sparc_pointer(), M_STARCORE, M_starcore_pointer(), M_TAHOE, M_tahoe_pointer(), M_TI, M_ti_pointer(), M_TYPE_POINTER, M_use_layout_database, M_WIMS, M_wims_pointer(), M_X86, M_x86_pointer(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type2(), M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_call_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_pointer_size (void)
Definition at line 1004 of file mi_spec.c.
References M_arch, and M_TAHOE.
int M_read_database_i (char * section_name, char * entry_name, char * field_name)
Definition at line 723 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_desc(), M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_int, MD_read_md(), and NULL.
Referenced by M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_char(), M_double(), M_float(), M_impact_layout_order(), M_int(), M_llong(), M_long(), M_no_short_int(), M_playdoh_layout_order(), M_pointer(), M_short(), M_starcore_fnvar_layout(), M_struct_align(), M_struct_layout(), M_struct_size(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), and M_union_size().
char* M_read_database_s (char * section_name, char * entry_name, char * field_name)
Definition at line 820 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_desc(), M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_string, MD_read_md(), and NULL.
void M_read_parm (Parm_Parse_Info * ppi)
Definition at line 100 of file mi_spec.c.
References L_read_parm_i(), L_read_parm_s(), M_layout_database_name, Mspec_num_dbl_callee_reg, Mspec_num_dbl_caller_reg, Mspec_num_flt_callee_reg, Mspec_num_flt_caller_reg, Mspec_num_int_callee_reg, Mspec_num_int_caller_reg, Mspec_num_prd_callee_reg, and Mspec_num_prd_caller_reg.
L_Operand* M_return_epilogue_cntr_register ()
Definition at line 2306 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_starcore_epilogue_cntr_register(), M_TAHOE, M_tahoe_epilogue_cntr_register(), M_TI, M_WIMS, M_X86, and NULL.
L_Operand* M_return_loop_cntr_register ()
Definition at line 2334 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_starcore_loop_cntr_register(), M_TAHOE, M_tahoe_loop_cntr_register(), M_TI, M_WIMS, M_X86, and NULL.
int M_return_register (int type, int purpose)
Definition at line 2273 of file ml_spec.c.
References M_arch, M_ARM, M_arm_return_register(), M_assert(), M_HPPA, M_hppa_return_register(), M_IMPACT, M_impact_return_register(), M_PLAYDOH, M_playdoh_return_register(), M_SH, M_sh_return_register(), M_SPARC, M_sparc_return_register(), M_STARCORE, M_starcore_return_register(), M_TAHOE, M_tahoe_return_register(), M_TI, M_ti_return_register(), M_WIMS, M_wims_return_register(), M_X86, and M_x86_return_register().
int M_return_value_offset ()
Definition at line 2225 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_return_value_thru_stack ()
Definition at line 2192 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_scaled_addressing_avail (void)
Definition at line 3124 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_set_machine (char * arch, char * model, char * swarch)
Definition at line 137 of file mi_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_set_model_arm(), M_set_model_bx86(), M_set_model_hppa(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_sh(), M_set_model_sparc(), M_set_model_starcore(), M_set_model_tahoe(), M_set_model_ti(), M_set_model_wims(), M_set_model_x86(), M_set_swarch_tahoe(), M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_set_swarch_tahoe (char * model_name)
Definition at line 1168 of file mi_tahoe.c.
References M_assert(), M_IPF_HPUX_ILP32, M_IPF_HPUX_LP64, M_IPF_LIN_LP64, M_IPF_WIN_P64, M_swarch, M_tahoe_align_long, M_tahoe_align_pointer, M_tahoe_size_long, and M_tahoe_size_pointer.
Referenced by M_set_machine().
void M_short (M_Type type, int unsign)
Definition at line 281 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_short(), M_assert(), M_BX86, M_bx86_short(), M_HPPA, M_hppa_short(), M_IMPACT, M_impact_short(), M_PLAYDOH, M_playdoh_short(), M_read_database_i(), M_SH, M_sh_short(), M_SPARC, M_sparc_short(), M_STARCORE, M_starcore_short(), M_TAHOE, M_tahoe_short(), M_TI, M_ti_short(), M_TYPE_SHORT, M_use_layout_database, M_WIMS, M_wims_short(), M_X86, M_x86_short(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
void M_struct (M_Type type, int align, int size)
Definition at line 666 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_assert(), M_TYPE_STRUCT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_struct_align (int n, _M_Type * type, char * struct_name)
Definition at line 1546 of file ml_spec.c.
References M_arch, M_ARM, M_arm_struct_align(), M_assert(), M_HPPA, M_hppa_struct_align(), M_IMPACT, M_impact_struct_align(), M_PLAYDOH, M_playdoh_struct_align(), M_read_database_i(), M_SH, M_sh_struct_align(), M_SPARC, M_sparc_struct_align(), M_STARCORE, M_starcore_struct_align(), M_TAHOE, M_tahoe_struct_align(), M_TI, M_ti_struct_align(), M_use_layout_database, M_WIMS, M_wims_struct_align(), M_X86, and M_x86_struct_align().
void M_struct_layout (int n, _M_Type * type, int * base, int * bit_offset, char * struct_name, char * field_name[])
Definition at line 1320 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_struct_layout(), M_assert(), M_HPPA, M_hppa_struct_layout(), M_IMPACT, M_impact_struct_layout(), M_layout_database_desc(), M_layout_database_name, M_PLAYDOH, M_playdoh_struct_layout(), M_read_database_i(), M_SH, M_sh_struct_layout(), M_SPARC, M_sparc_struct_layout(), M_STARCORE, M_starcore_struct_layout(), M_TAHOE, M_tahoe_struct_layout(), M_TI, M_ti_struct_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_INT, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_use_layout_database, M_WIMS, M_wims_struct_layout(), M_X86, M_x86_struct_layout(), and _struct_M_Type::type.
int M_struct_size (int n, _M_Type * type, int struct_align, char * struct_name)
Definition at line 1589 of file ml_spec.c.
References M_arch, M_ARM, M_arm_struct_size(), M_assert(), M_HPPA, M_hppa_struct_size(), M_IMPACT, M_impact_struct_size(), M_PLAYDOH, M_playdoh_struct_size(), M_read_database_i(), M_SH, M_sh_struct_size(), M_SPARC, M_sparc_struct_size(), M_STARCORE, M_starcore_struct_size(), M_TAHOE, M_tahoe_struct_size(), M_TI, M_ti_struct_size(), M_use_layout_database, M_WIMS, M_wims_struct_size(), M_X86, and M_x86_struct_size().
int M_structure_pointer (int purpose)
Definition at line 2159 of file ml_spec.c.
References M_arch, M_ARM, M_arm_structure_pointer(), M_assert(), M_HPPA, M_hppa_structure_pointer(), M_IMPACT, M_impact_structure_pointer(), M_PLAYDOH, M_playdoh_structure_pointer(), M_SH, M_sh_structure_pointer(), M_SPARC, M_sparc_structure_pointer(), M_STARCORE, M_starcore_structure_pointer(), M_TAHOE, M_tahoe_structure_pointer(), M_TI, M_ti_structure_pointer(), M_WIMS, M_wims_structure_pointer(), M_X86, and M_x86_structure_pointer().
int M_subroutine_call (int opc)
Definition at line 2554 of file ml_spec.c.
References M_arch, M_ARM, M_arm_subroutine_call(), M_assert(), M_HPPA, M_hppa_subroutine_call(), M_IMPACT, M_impact_subroutine_call(), M_PLAYDOH, M_playdoh_subroutine_call(), M_SH, M_sh_subroutine_call(), M_SPARC, M_sparc_subroutine_call(), M_STARCORE, M_starcore_subroutine_call(), M_TAHOE, M_tahoe_subroutine_call(), M_TI, M_ti_subroutine_call(), M_WIMS, M_wims_subroutine_call(), M_X86, and M_x86_subroutine_call().
int M_supports_long_long (void)
Definition at line 989 of file mi_spec.c.
References M_arch, M_ARM, M_PLAYDOH, M_TAHOE, and M_WIMS.
int M_type_align (int mtype)
Definition at line 581 of file mi_spec.c.
References M_arch, M_ARM, M_arm_type_align(), M_assert(), M_HPPA, M_hppa_type_align(), M_IMPACT, M_impact_type_align(), M_PLAYDOH, M_playdoh_type_align(), M_read_database_i(), M_SH, M_sh_type_align(), M_SPARC, M_sparc_type_align(), M_STARCORE, M_starcore_type_align(), M_TAHOE, M_tahoe_type_align(), M_TI, M_ti_type_align(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_type_align(), M_X86, and M_x86_type_align().
int M_type_size (int mtype)
Definition at line 506 of file mi_spec.c.
References M_arch, M_ARM, M_arm_type_size(), M_assert(), M_HPPA, M_hppa_type_size(), M_IMPACT, M_impact_type_size(), M_PLAYDOH, M_playdoh_type_size(), M_read_database_i(), M_SH, M_sh_type_size(), M_SPARC, M_sparc_type_size(), M_STARCORE, M_starcore_type_size(), M_TAHOE, M_tahoe_type_size(), M_TI, M_ti_type_size(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_type_size(), M_X86, and M_x86_type_size().
Referenced by M_memory_access_size_x86().
void M_union (M_Type type, int align, int size)
Definition at line 649 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_assert(), M_TYPE_UNION, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_union_align (int n, _M_Type * type, char * union_name)
Definition at line 1234 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_align(), M_assert(), M_HPPA, M_hppa_union_align(), M_IMPACT, M_impact_union_align(), M_PLAYDOH, M_playdoh_union_align(), M_read_database_i(), M_SH, M_sh_union_align(), M_SPARC, M_sparc_union_align(), M_STARCORE, M_starcore_union_align(), M_TAHOE, M_tahoe_union_align(), M_TI, M_ti_union_align(), M_use_layout_database, M_WIMS, M_wims_union_align(), M_X86, and M_x86_union_align().
void M_union_layout (int n, _M_Type * type, int * offset, int * bit_offset, char * union_name, char * field_name[])
Definition at line 1175 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_layout(), M_assert(), M_HPPA, M_hppa_union_layout(), M_IMPACT, M_impact_union_layout(), M_PLAYDOH, M_playdoh_union_layout(), M_read_database_i(), M_SH, M_sh_union_layout(), M_SPARC, M_sparc_union_layout(), M_STARCORE, M_starcore_union_layout(), M_TAHOE, M_tahoe_union_layout(), M_TI, M_ti_union_layout(), M_use_layout_database, M_WIMS, M_wims_union_layout(), M_X86, and M_x86_union_layout().
int M_union_size (int n, _M_Type * type, char * union_name)
Definition at line 1277 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_size(), M_assert(), M_HPPA, M_hppa_union_size(), M_IMPACT, M_impact_union_size(), M_PLAYDOH, M_playdoh_union_size(), M_read_database_i(), M_SH, M_sh_union_size(), M_SPARC, M_sparc_union_size(), M_STARCORE, M_starcore_union_size(), M_TAHOE, M_tahoe_union_size(), M_TI, M_ti_union_size(), M_use_layout_database, M_WIMS, M_wims_union_size(), M_X86, and M_x86_union_size().
void M_void (M_Type type)
Definition at line 94 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_void(), M_assert(), M_BX86, M_bx86_void(), M_HPPA, M_hppa_void(), M_IMPACT, M_impact_void(), M_PLAYDOH, M_playdoh_void(), M_SH, M_sh_void(), M_SPARC, M_sparc_void(), M_STARCORE, M_starcore_void(), M_TAHOE, M_tahoe_void(), M_TI, M_ti_void(), M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_void(), M_X86, M_x86_void(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
int M_zero_macro (L_Operand * opd)
Definition at line 2531 of file ml_spec.c.
References M_arch, M_TAHOE, and TAHOE_MAC_ZERO.
Variable Documentation
int M_arch
Definition at line 86 of file mi_spec.c.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_cannot_predicate(), M_cb_label_name(), M_char(), M_coalescing_oper(), M_dataflow_macro(), M_define_macros(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_macro_name(), M_get_memory_operands(), M_get_opcode_name(), M_int(), M_is_cb_label(), M_is_implicit_memory_op(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_unsafe_macro(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_registers(), M_opc_from_proc_opc(), M_oper_supported_in_arch(), M_pointer(), M_pointer_size(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_scaled_addressing_avail(), M_set_machine(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_supports_long_long(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), M_void(), and M_zero_macro().
char* M_layout_database_name
Definition at line 122 of file mi_spec.c.
Referenced by M_database_info_present(), M_read_database_i(), M_read_database_s(), M_read_parm(), and M_struct_layout().
int M_model
Definition at line 87 of file mi_spec.c.
Referenced by M_arm_fragile_macro(), M_arm_subroutine_call(), M_bx86_fragile_macro(), M_bx86_subroutine_call(), M_define_macros_tahoe(), M_get_macro_name_tahoe(), M_hppa_dataflow_macro(), M_hppa_fragile_macro(), M_hppa_fragile_macro_set(), M_hppa_subroutine_call(), M_is_stack_operand_tahoe(), M_is_unsafe_macro_tahoe(), M_num_oper_required_for_tahoe(), M_num_registers_arm(), M_num_registers_hppa(), M_num_registers_sh(), M_num_registers_sparc(), M_num_registers_ti(), M_num_registers_wims(), M_oper_supported_in_arch_hppa(), M_oper_supported_in_arch_tahoe(), M_set_model_arm(), M_set_model_bx86(), M_set_model_hppa(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_sh(), M_set_model_sparc(), M_set_model_starcore(), M_set_model_tahoe(), M_set_model_ti(), M_set_model_wims(), M_set_model_x86(), M_sh_dataflow_macro(), M_sh_fragile_macro(), M_sh_fragile_macro_set(), M_sh_subroutine_call(), M_sparc_dataflow_macro(), M_sparc_fragile_macro(), M_sparc_fragile_macro_set(), M_sparc_subroutine_call(), M_tahoe_dataflow_macro(), M_tahoe_fragile_macro(), M_tahoe_subroutine_call(), M_ti_fragile_macro(), M_ti_subroutine_call(), M_wims_fragile_macro(), M_wims_subroutine_call(), M_x86_fragile_macro(), and M_x86_subroutine_call().
int M_swarch
Definition at line 88 of file mi_spec.c.
Referenced by M_set_swarch_tahoe(), and M_tahoe_layout_order().
int M_use_layout_database
Definition at line 121 of file mi_spec.c.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_char(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_int(), M_llong(), M_long(), M_no_short_int(), M_pointer(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_starcore(), M_set_model_tahoe(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
int Mspec_num_dbl_callee_reg
Definition at line 95 of file mi_spec.c.
Referenced by M_read_parm().
int Mspec_num_dbl_caller_reg
Definition at line 94 of file mi_spec.c.
Referenced by M_read_parm().
int Mspec_num_flt_callee_reg
Definition at line 93 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_flt_caller_reg
Definition at line 92 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_int_callee_reg
Definition at line 91 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_int_caller_reg
Definition at line 90 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_prd_callee_reg
Definition at line 97 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_prd_caller_reg
Definition at line 96 of file mi_spec.c.
Referenced by M_read_parm().