m_tahoe.h File Reference
#include <config.h>
#include `m_spec.h`
Defines
#define SCRATCH_SPACE_SIZE 16
#define TAHOE_NUM_INT_REG (128)
#define TAHOE_NUM_INT_STATIC_REG (32)
#define TAHOE_NUM_INT_STACKED_REG
#define TAHOE_NUM_PRED_REG (64)
#define TAHOE_NUM_FLOAT_REG (128)
#define TAHOE_NUM_BRANCH_REG (8)
#define TAHOE_MIN_INT_REGISTER_ID (0)
#define TAHOE_MAX_INT_REGISTER_ID (TAHOE_NUM_INT_REG-1)
#define TAHOE_MIN_INT_STATIC_REGISTER_ID (0)
#define TAHOE_MAX_INT_STATIC_REGISTER_ID (TAHOE_NUM_INT_STATIC_REG-1)
#define TAHOE_MIN_INT_STACKED_REGISTER_ID (32)
#define TAHOE_MAX_INT_STACKED_REGISTER_ID (TAHOE_MAX_INT_REGISTER_ID)
#define TAHOE_MAX_PRED_REGISTER_NUMBER (TAHOE_NUM_PRED_REG-1)
#define TAHOE_MAX_FLOAT_REGISTER_NUMBER (TAHOE_NUM_FLOAT_REG-1)
#define TAHOE_MAX_BRANCH_REGISTER_NUMBER (TAHOE_NUM_BRANCH_REG-1)
#define TAHOE_NUM_SPECIAL_INT_REG (2)
#define TAHOE_NUM_SPECIAL_PRED_REG (0)
#define TAHOE_NUM_SPECIAL_FLOAT_REG (0)
#define TAHOE_NUM_SPECIAL_BRANCH_REG (0)
#define TAHOE_INT_REG_BASE (0)
#define TAHOE_INT_STACK_REG_BASE
#define TAHOE_INT_SPILL_REG_BASE
#define TAHOE_FLOAT_REG_BASE (TAHOE_INT_REG_BASE + TAHOE_NUM_INT_REG)
#define TAHOE_PRED_REG_BASE (TAHOE_FLOAT_REG_BASE + TAHOE_NUM_FLOAT_REG)
#define TAHOE_BRANCH_REG_BASE (TAHOE_PRED_REG_BASE + TAHOE_NUM_PRED_REG)
#define ADDR_ALIGN(addr, align) (((addr)+(align-1)) & ~(align-1))
#define M_IPF_MODEL_OK(model)
#define M_IPF_SWARCH_OK(model)
#define TAHOE_APPLICATION_MACRO(macro)
#define TAHOE_M_APPLICATION_MACRO(macro)
#define TAHOE_I_APPLICATION_MACRO(macro)
#define M_TAHOE_MAX_FNVAR_INT_REG 8
#define M_TAHOE_MAX_FNVAR_FLT_REG 8
#define M_TAHOE_MAX_RET_REG 4
#define M_TAHOE_SMALL_STRUCT_MAX 64
#define M_TAHOE_IN_INT_BASE 0
#define M_TAHOE_OUT_INT_BASE 8
#define M_TAHOE_RET_INT_BASE 16
#define M_TAHOE_FLT_BASE 20
#define M_TAHOE_RET_FLT_BASE 20
#define TAHOEop_VERSION 1
#define TAHOEop_START 1000
#define TAHOEop_INVALID 1000
#define TAHOEop_NOP_B 1001
#define TAHOEop_NOP_F 1002
#define TAHOEop_NOP_I 1003
#define TAHOEop_NOP_M 1004
#define TAHOEop_NOP_X 1005
#define TAHOEop_BREAK_B 1006
#define TAHOEop_BREAK_F 1007
#define TAHOEop_BREAK_I 1008
#define TAHOEop_BREAK_M 1009
#define TAHOEop_BREAK_X 1010
#define TAHOEop_ADD 1011
#define TAHOEop_ADDL 1012
#define TAHOEop_ADDS 1013
#define TAHOEop_SHLADD 1014
#define TAHOEop_SUB 1015
#define TAHOEop_AND 1016
#define TAHOEop_ANDCM 1017
#define TAHOEop_OR 1018
#define TAHOEop_XOR 1019
#define TAHOEop_DEP 1020
#define TAHOEop_DEP_Z 1021
#define TAHOEop_EXTR 1022
#define TAHOEop_EXTR_U 1023
#define TAHOEop_SHRP 1024
#define TAHOEop_SXT1 1025
#define TAHOEop_SXT2 1026
#define TAHOEop_SXT4 1027
#define TAHOEop_ZXT1 1028
#define TAHOEop_ZXT2 1029
#define TAHOEop_ZXT4 1030
#define TAHOEop_CZX1_L 1031
#define TAHOEop_CZX1_R 1032
#define TAHOEop_CZX2_L 1033
#define TAHOEop_CZX2_R 1034
#define TAHOEop_LD1 1035
#define TAHOEop_LD1_ACQ 1036
#define TAHOEop_LD1_BIAS 1037
#define TAHOEop_LD2 1038
#define TAHOEop_LD2_ACQ 1039
#define TAHOEop_LD2_BIAS 1040
#define TAHOEop_LD4 1041
#define TAHOEop_LD4_ACQ 1042
#define TAHOEop_LD4_BIAS 1043
#define TAHOEop_LD8 1044
#define TAHOEop_LD8_ACQ 1045
#define TAHOEop_LD8_BIAS 1046
#define TAHOEop_LD8_FILL 1047
#define TAHOEop_LFETCH 1048
#define TAHOEop_LFETCH_FAULT 1049
#define TAHOEop_LDF_FILL 1050
#define TAHOEop_LDF8 1051
#define TAHOEop_LDF8_A 1052
#define TAHOEop_LDFD 1053
#define TAHOEop_LDFD_A 1054
#define TAHOEop_LDFE 1055
#define TAHOEop_LDFE_A 1056
#define TAHOEop_LDFS 1057
#define TAHOEop_LDFS_A 1058
#define TAHOEop_LDFP8 1059
#define TAHOEop_LDFPD 1060
#define TAHOEop_LDFPS 1061
#define TAHOEop_LD1_C 1062
#define TAHOEop_LD2_C 1063
#define TAHOEop_LD4_C 1064
#define TAHOEop_LD8_C 1065
#define TAHOEop_LDF8_C 1066
#define TAHOEop_LDFD_C 1067
#define TAHOEop_LDFE_C 1068
#define TAHOEop_LDFP8_C 1069
#define TAHOEop_LDFPD_C 1070
#define TAHOEop_LDFPS_C 1071
#define TAHOEop_LDFS_C 1072
#define TAHOEop_CHK_A 1073
#define TAHOEop_CHK_S_I 1074
#define TAHOEop_CHK_S_F 1075
#define TAHOEop_CHK_S_M 1076
#define TAHOEop_XMA_H 1077
#define TAHOEop_XMA_HU 1078
#define TAHOEop_XMA_L 1079
#define TAHOEop_FMA_D 1080
#define TAHOEop_FMA_S 1081
#define TAHOEop_FMA 1082
#define TAHOEop_FMS_D 1083
#define TAHOEop_FMS_S 1084
#define TAHOEop_FMS 1085
#define TAHOEop_FNMA_D 1086
#define TAHOEop_FNMA_S 1087
#define TAHOEop_FNMA 1088
#define TAHOEop_FAMAX 1089
#define TAHOEop_FAMIN 1090
#define TAHOEop_FAND 1091
#define TAHOEop_FANDCM 1092
#define TAHOEop_FMAX 1093
#define TAHOEop_FMERGE_NS 1094
#define TAHOEop_FMERGE_S 1095
#define TAHOEop_FMERGE_SE 1096
#define TAHOEop_FMIN 1097
#define TAHOEop_FMIX_L 1098
#define TAHOEop_FMIX_LR 1099
#define TAHOEop_FMIX_R 1100
#define TAHOEop_FOR 1101
#define TAHOEop_FPACK 1102
#define TAHOEop_FRCPA 1103
#define TAHOEop_FRSQRTA 1104
#define TAHOEop_FSELECT 1105
#define TAHOEop_FSWAP 1106
#define TAHOEop_FSWAP_NL 1107
#define TAHOEop_FSWAP_NR 1108
#define TAHOEop_FSXT_L 1109
#define TAHOEop_FSXT_R 1110
#define TAHOEop_FXOR 1111
#define TAHOEop_FCHKF 1112
#define TAHOEop_FCLRF 1113
#define TAHOEop_FSETC 1114
#define TAHOEop_MOV_TOAR_I 1115
#define TAHOEop_MOV_FRAR_I 1116
#define TAHOEop_MOV_TOAR_M 1117
#define TAHOEop_MOV_FRAR_M 1118
#define TAHOEop_MOV_FRCR 1119
#define TAHOEop_MOV_TOCR 1120
#define TAHOEop_MOV_FRIP 1121
#define TAHOEop_MOV_FRPR 1122
#define TAHOEop_MOV_TOPR 1123
#define TAHOEop_MOV_TOPR_ROT 1124
#define TAHOEop_SETF_D 1125
#define TAHOEop_SETF_EXP 1126
#define TAHOEop_SETF_S 1127
#define TAHOEop_SETF_SIG 1128
#define TAHOEop_GETF_D 1129
#define TAHOEop_GETF_EXP 1130
#define TAHOEop_GETF_S 1131
#define TAHOEop_GETF_SIG 1132
#define TAHOEop_MOV_FRBR 1133
#define TAHOEop_MOV_TOBR 1134
#define TAHOEop_MOV_TOSYST 1135
#define TAHOEop_MOV_FRSYST 1136
#define TAHOEop_MOVL 1137
#define TAHOEop_CMP 1138
#define TAHOEop_TBIT 1139
#define TAHOEop_TNAT 1140
#define TAHOEop_BR_CALL 1141
#define TAHOEop_BR_COND 1142
#define TAHOEop_BR_IA 1143
#define TAHOEop_BR_RET 1144
#define TAHOEop_BRL_CALL 1145
#define TAHOEop_BRL_COND 1146
#define TAHOEop_BRP 1147
#define TAHOEop_BRP_RET 1148
#define TAHOEop_BR_CEXIT 1149
#define TAHOEop_BR_CLOOP 1150
#define TAHOEop_BR_CTOP 1151
#define TAHOEop_BR_WEXIT 1152
#define TAHOEop_BR_WTOP 1153
#define TAHOEop_PADD1 1154
#define TAHOEop_PADD1_SSS 1155
#define TAHOEop_PADD1_UUS 1156
#define TAHOEop_PADD1_UUU 1157
#define TAHOEop_PADD2 1158
#define TAHOEop_PADD2_SSS 1159
#define TAHOEop_PADD2_UUS 1160
#define TAHOEop_PADD2_UUU 1161
#define TAHOEop_PADD4 1162
#define TAHOEop_PAVG1 1163
#define TAHOEop_PAVG1_RAZ 1164
#define TAHOEop_PAVG2 1165
#define TAHOEop_PAVG2_RAZ 1166
#define TAHOEop_PAVGSUB1 1167
#define TAHOEop_PAVGSUB2 1168
#define TAHOEop_PCMP1_EQ 1169
#define TAHOEop_PCMP1_GT 1170
#define TAHOEop_PCMP2_EQ 1171
#define TAHOEop_PCMP2_GT 1172
#define TAHOEop_PCMP_EQ 1173
#define TAHOEop_PCMP_GT 1174
#define TAHOEop_PSHLADD2 1175
#define TAHOEop_PSHRADD2 1176
#define TAHOEop_PSUB1 1177
#define TAHOEop_PSUB1_SSS 1178
#define TAHOEop_PSUB1_UUS 1179
#define TAHOEop_PSUB1_UUU 1180
#define TAHOEop_PSUB2 1181
#define TAHOEop_PSUB2_SSS 1182
#define TAHOEop_PSUB2_UUS 1183
#define TAHOEop_PSUB2_UUU 1184
#define TAHOEop_PSUB4 1185
#define TAHOEop_PMAX1_U 1186
#define TAHOEop_PMAX2 1187
#define TAHOEop_PMIN1_U 1188
#define TAHOEop_PMIN2 1189
#define TAHOEop_PSAD1 1190
#define TAHOEop_PMPY2_L 1191
#define TAHOEop_PMPY2_R 1192
#define TAHOEop_PMPYSHR2 1193
#define TAHOEop_PMPYSHR2_U 1194
#define TAHOEop_POPCNT 1195
#define TAHOEop_MIX1_L 1196
#define TAHOEop_MIX1_R 1197
#define TAHOEop_MIX2_L 1198
#define TAHOEop_MIX2_R 1199
#define TAHOEop_MIX4_L 1200
#define TAHOEop_MIX4_R 1201
#define TAHOEop_MUX1 1202
#define TAHOEop_MUX2 1203
#define TAHOEop_PACK2_SSS 1204
#define TAHOEop_PACK2_USS 1205
#define TAHOEop_PACK4_SSS 1206
#define TAHOEop_PSHL2 1207
#define TAHOEop_PSHL4 1208
#define TAHOEop_PSHR2 1209
#define TAHOEop_PSHR2_U 1210
#define TAHOEop_PSHR4 1211
#define TAHOEop_PSHR4_U 1212
#define TAHOEop_SHL 1213
#define TAHOEop_SHR 1214
#define TAHOEop_SHR_U 1215
#define TAHOEop_UNPACK1_H 1216
#define TAHOEop_UNPACK1_L 1217
#define TAHOEop_UNPACK2_H 1218
#define TAHOEop_UNPACK2_L 1219
#define TAHOEop_UNPACK4_H 1220
#define TAHOEop_UNPACK4_L 1221
#define TAHOEop_ADDP4 1222
#define TAHOEop_SHLADDP4 1223
#define TAHOEop_CLRRRB 1224
#define TAHOEop_CLRRRB_PR 1225
#define TAHOEop_COVER 1226
#define TAHOEop_FLUSHRS 1227
#define TAHOEop_LOADRS 1228
#define TAHOEop_CMPXCHG1_ACQ 1229
#define TAHOEop_CMPXCHG1_REL 1230
#define TAHOEop_CMPXCHG2_ACQ 1231
#define TAHOEop_CMPXCHG2_REL 1232
#define TAHOEop_CMPXCHG4_ACQ 1233
#define TAHOEop_CMPXCHG4_REL 1234
#define TAHOEop_CMPXCHG8_ACQ 1235
#define TAHOEop_CMPXCHG8_REL 1236
#define TAHOEop_FETCHADD4_ACQ 1237
#define TAHOEop_FETCHADD4_REL 1238
#define TAHOEop_FETCHADD8_ACQ 1239
#define TAHOEop_FETCHADD8_REL 1240
#define TAHOEop_XCHG1 1241
#define TAHOEop_XCHG2 1242
#define TAHOEop_XCHG4 1243
#define TAHOEop_XCHG8 1244
#define TAHOEop_FCLASS 1245
#define TAHOEop_FCMP 1246
#define TAHOEop_FCVT_FX 1247
#define TAHOEop_FCVT_FXU 1248
#define TAHOEop_FCVT_XF 1249
#define TAHOEop_FPCVT_FX 1250
#define TAHOEop_FPCVT_FX_TRUNC 1251
#define TAHOEop_FPCVT_FXU 1252
#define TAHOEop_FPCVT_FXU_TRUNC 1253
#define TAHOEop_FPMA 1254
#define TAHOEop_FPMS 1255
#define TAHOEop_FPNMA 1256
#define TAHOEop_FPMERGE 1257
#define TAHOEop_FPAMAX 1258
#define TAHOEop_FPAMIN 1259
#define TAHOEop_FPCMP 1260
#define TAHOEop_FPMAX 1261
#define TAHOEop_FPMERGE_NS 1262
#define TAHOEop_FPMERGE_S 1263
#define TAHOEop_FPMIN 1264
#define TAHOEop_FPRCPA 1265
#define TAHOEop_FPRSQRTA 1266
#define TAHOEop_ST1 1267
#define TAHOEop_ST1_REL 1268
#define TAHOEop_ST2 1269
#define TAHOEop_ST2_REL 1270
#define TAHOEop_ST4 1271
#define TAHOEop_ST4_REL 1272
#define TAHOEop_ST8 1273
#define TAHOEop_ST8_REL 1274
#define TAHOEop_ST8_SPILL 1275
#define TAHOEop_STF_SPILL 1276
#define TAHOEop_STF8 1277
#define TAHOEop_STFD 1278
#define TAHOEop_STFE 1279
#define TAHOEop_STFS 1280
#define TAHOEop_EPC 1281
#define TAHOEop_BSW_0 1282
#define TAHOEop_BSW_1 1283
#define TAHOEop_RFI 1284
#define TAHOEop_INVALA 1285
#define TAHOEop_INVALA_E 1286
#define TAHOEop_INVALA_E_F 1287
#define TAHOEop_CC 1288
#define TAHOEop_FWB 1289
#define TAHOEop_HALT 1290
#define TAHOEop_HALT_MF 1291
#define TAHOEop_MF 1292
#define TAHOEop_MF_A 1293
#define TAHOEop_SRLZ_D 1294
#define TAHOEop_SRLZ_I 1295
#define TAHOEop_SYNC_I 1296
#define TAHOEop_ALLOC 1297
#define TAHOEop_FC 1298
#define TAHOEop_ITC_D 1299
#define TAHOEop_ITC_I 1300
#define TAHOEop_ITR_D 1301
#define TAHOEop_ITR_I 1302
#define TAHOEop_PROBE_R 1303
#define TAHOEop_PROBE_R_FAULT 1304
#define TAHOEop_PROBE_RW_FAULT 1305
#define TAHOEop_PROBE_W 1306
#define TAHOEop_PROBE_W_FAULT 1307
#define TAHOEop_PTC_E 1308
#define TAHOEop_PTC_G 1309
#define TAHOEop_PTC_GA 1310
#define TAHOEop_PTC_L 1311
#define TAHOEop_PTR_D 1312
#define TAHOEop_PTR_I 1313
#define TAHOEop_RSM 1314
#define TAHOEop_RUM 1315
#define TAHOEop_SSM 1316
#define TAHOEop_SUM 1317
#define TAHOEop_TAK 1318
#define TAHOEop_THASH 1319
#define TAHOEop_TPA 1320
#define TAHOEop_TTAG 1321
#define TAHOEop_MOVI 1322
#define TAHOEop_MOV_GR 1323
#define TAHOEop_NON_INSTR 1324
#define TAHOEop_FABS 1325
#define TAHOEop_FADD_D 1326
#define TAHOEop_FADD_S 1327
#define TAHOEop_FADD 1328
#define TAHOEop_CHK_S 1329
#define TAHOEop_MOV_FR 1330
#define TAHOEop_FSUB_D 1331
#define TAHOEop_FSUB_S 1332
#define TAHOEop_FSUB 1333
Enumerations
enum {
M_IPF_ITANIUM = 0,
M_IPF_MCKINLEY,
M_IPF_MADISON,
M_IPF_DEERFIELD,
M_IPF_MENDOCITO,
M_IPF_CHIVANO
 }
enum { M_IPF_LIN_LP64 = 0,
M_IPF_WIN_P64,
M_IPF_HPUX_LP64,
M_IPF_HPUX_ILP32
 }
enum {
TAHOE_MAC_ZERO = (L_MAC_LAST + 1),
TAHOE_MAC_GP,
TAHOE_MAC_AP,
TAHOE_MAC_RETADDR,
TAHOE_MAC_PRED_TRUE,
TAHOE_MAC_FZERO,
TAHOE_MAC_FONE,
TAHOE_PRED_SAVE_REG,
TAHOE_PRED_BLK_REG,
TAHOE_PRED_ROT_BLK_REG,
TAHOE_GP_SAVE_REG,
TAHOE_MAC_TMPREG1,
TAHOE_MAC_TMPREG2,
TAHOE_MAC_LEAF,
TAHOE_MAC_SYNC_SIZE,
TAHOE_MAC_MEM_ALLOC,
TAHOE_MAC_TEMPLATE,
TAHOE_MAC_LABEL,
TAHOE_MAC_PSP,
TAHOE_MAC_PSPILL,
TAHOE_MAC_KR0,
TAHOE_MAC_KR1,
TAHOE_MAC_KR2,
TAHOE_MAC_KR3,
TAHOE_MAC_RSC,
TAHOE_MAC_BSP,
TAHOE_MAC_RNAT,
TAHOE_MAC_CCV,
TAHOE_MAC_UNAT,
TAHOE_MAC_FPSR,
TAHOE_MAC_ITC,
TAHOE_MAC_AR_PFS,
TAHOE_MAC_LC,
TAHOE_MAC_EC
 }
Functions
int M_tahoe_type_size (int mtype)
int M_tahoe_type_align (int mtype)
void M_tahoe_void (M_Type type)
void M_tahoe_bit_llong (M_Type type, int n)
void M_tahoe_bit_long (M_Type type, int n)
void M_tahoe_bit_int (M_Type type, int n)
void M_tahoe_bit_short (M_Type type, int n)
void M_tahoe_bit_char (M_Type type, int n)
void M_tahoe_char (M_Type type, int unsign)
void M_tahoe_short (M_Type type, int unsign)
void M_tahoe_int (M_Type type, int unsign)
void M_tahoe_long (M_Type type, int unsign)
void M_tahoe_llong (M_Type type, int unsign)
void M_tahoe_float (M_Type type, int unsign)
void M_tahoe_double (M_Type type, int unsign)
void M_tahoe_pointer (M_Type type)
int M_tahoe_eval_type (M_Type type, M_Type ntype)
int M_tahoe_eval_type2 (M_Type type, M_Type ntype)
int M_tahoe_call_type (M_Type type, M_Type ntype)
int M_tahoe_call_type2 (M_Type type, M_Type ntype)
void M_tahoe_array_layout (M_Type type, int *offset)
int M_tahoe_array_align (M_Type type)
int M_tahoe_array_size (M_Type type, int dim)
void M_tahoe_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_tahoe_union_align (int n, _M_Type *type)
int M_tahoe_union_size (int n, _M_Type *type)
void M_tahoe_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_tahoe_struct_align (int n, _M_Type *type)
int M_tahoe_struct_size (int n, _M_Type *type, int struct_align)
int M_tahoe_layout_fnvar (List param_list, char **macro, int *pcount, int purpose)
int M_tahoe_layout_retvar (M_Param param, int purpose)
int M_tahoe_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_tahoe_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_tahoe_fnvar_to_lvar (_M_Type type, long int *offset, char **base_macro, int local_space)
int M_tahoe_no_short_int (void)
int M_tahoe_layout_order (void)
void M_tahoe_cb_label_name (char *fn, int cb, char *line, int len)
int M_tahoe_is_cb_label (char *label, char *fn, int *cb)
void M_tahoe_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_tahoe_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_tahoe_structure_pointer (int purpose)
int M_tahoe_return_register (int type, int purpose)
L_Operand * M_tahoe_epilogue_cntr_register ()
L_Operand * M_tahoe_loop_cntr_register ()
char * M_tahoe_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_tahoe_fn_name_from_label (char *label)
void M_set_model_tahoe (char *model_name)
int M_tahoe_fragile_macro (int macro_value)
Set M_tahoe_fragile_macro_set (void)
int M_tahoe_extra_pred_define_opcode (int proc_opc)
int M_tahoe_extra_pred_define_type1 (L_Oper *)
int M_tahoe_extra_pred_define_type2 (L_Oper *)
int M_tahoe_subroutine_call (int opc)
int M_tahoe_dataflow_macro (int id)
void M_define_macros_tahoe (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_tahoe (int id)
int M_oper_supported_in_arch_tahoe (int opc)
int M_num_oper_required_for_tahoe (L_Oper *oper, char *name)
int M_num_registers_tahoe (int ctype)
int M_is_stack_operand_tahoe (L_Operand *operand)
int M_is_unsafe_macro_tahoe (L_Operand *operand)
int M_operand_type_tahoe (L_Operand *operand)
int M_conflicting_operands_tahoe (L_Operand *operand, L_Operand *conflict_array[], int len, int prepass)
int M_opc_from_proc_opc_tahoe (int proc_opc)
int M_cannot_predicate_tahoe (L_Oper *oper)
void M_get_memory_operands_tahoe (int *first, int *number, int proc_opc)
Define Documentation
#define ADDR_ALIGN(addr, align) (((addr)+(align-1)) & ~(align-1))
Definition at line 122 of file m_tahoe.h.
#define M_IPF_MODEL_OK(model)
Value:
(((model) == M_IPF_ITANIUM) ||  \
                                 ((model) == M_IPF_MCKINLEY) || \
                                 ((model) == M_IPF_MADISON) ||  \
                                 ((model) == M_IPF_DEERFIELD) || \
                                 ((model) == M_IPF_MENDOCITO) || \
                                 ((model) == M_IPF_CHIVANO))
Definition at line 138 of file m_tahoe.h.
Referenced by M_define_macros_tahoe(), M_get_macro_name_tahoe(), M_is_stack_operand_tahoe(), M_is_unsafe_macro_tahoe(), M_num_oper_required_for_tahoe(), M_oper_supported_in_arch_tahoe(), M_tahoe_dataflow_macro(), M_tahoe_fragile_macro(), and M_tahoe_subroutine_call().
#define M_IPF_SWARCH_OK(model)
Value:
(((model) == M_IPF_LIN_LP64) ||  \
                                  ((model) == M_IPF_WIN_P64) ||   \
                                  ((model) == M_IPF_HPUX_LP64) || \
                                  ((model) == M_IPF_HPUX_ILP32))
Definition at line 157 of file m_tahoe.h.
#define M_TAHOE_FLT_BASE 20
Definition at line 274 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define M_TAHOE_IN_INT_BASE 0
Definition at line 269 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define M_TAHOE_MAX_FNVAR_FLT_REG 8
Definition at line 259 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define M_TAHOE_MAX_FNVAR_INT_REG 8
Definition at line 256 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define M_TAHOE_MAX_RET_REG 4
Definition at line 262 of file m_tahoe.h.
#define M_TAHOE_OUT_INT_BASE 8
Definition at line 270 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define M_TAHOE_RET_FLT_BASE 20
Definition at line 276 of file m_tahoe.h.
Referenced by M_tahoe_return_register().
#define M_TAHOE_RET_INT_BASE 16
Definition at line 272 of file m_tahoe.h.
Referenced by M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_return_register(), and M_tahoe_structure_pointer().
#define M_TAHOE_SMALL_STRUCT_MAX 64
Definition at line 265 of file m_tahoe.h.
#define SCRATCH_SPACE_SIZE 16
Definition at line 83 of file m_tahoe.h.
Referenced by M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
#define TAHOE_APPLICATION_MACRO(macro)
Value:
((TAHOE_I_APPLICATION_MACRO(macro)|| \
                                           TAHOE_M_APPLICATION_MACRO(macro)))
Definition at line 223 of file m_tahoe.h.
#define TAHOE_BRANCH_REG_BASE (TAHOE_PRED_REG_BASE + TAHOE_NUM_PRED_REG)
Definition at line 118 of file m_tahoe.h.
#define TAHOE_FLOAT_REG_BASE (TAHOE_INT_REG_BASE + TAHOE_NUM_INT_REG)
Definition at line 116 of file m_tahoe.h.
#define TAHOE_I_APPLICATION_MACRO(macro)
Value:
((macro->value.mac >= TAHOE_MAC_AR_PFS) && \
                                    (macro->value.mac <= TAHOE_MAC_EC))
Definition at line 230 of file m_tahoe.h.
#define TAHOE_INT_REG_BASE (0)
Definition at line 111 of file m_tahoe.h.
#define TAHOE_INT_SPILL_REG_BASE
Value:
(TAHOE_INT_REG_BASE + TAHOE_NUM_INT_REG - \
                                  TAHOE_NUM_SPILL_INT_REG)
Definition at line 114 of file m_tahoe.h.
#define TAHOE_INT_STACK_REG_BASE
Value:
(TAHOE_INT_REG_BASE + \
                                  TAHOE_NUM_INT_STATIC_REG)
Definition at line 112 of file m_tahoe.h.
#define TAHOE_M_APPLICATION_MACRO(macro)
Value:
((macro->value.mac >= TAHOE_MAC_KR0) \
                                          &&                                  \
                                          (macro->value.mac <= TAHOE_MAC_ITC))
Definition at line 226 of file m_tahoe.h.
#define TAHOE_MAX_BRANCH_REGISTER_NUMBER (TAHOE_NUM_BRANCH_REG-1)
Definition at line 101 of file m_tahoe.h.
#define TAHOE_MAX_FLOAT_REGISTER_NUMBER (TAHOE_NUM_FLOAT_REG-1)
Definition at line 100 of file m_tahoe.h.
#define TAHOE_MAX_INT_REGISTER_ID (TAHOE_NUM_INT_REG-1)
Definition at line 94 of file m_tahoe.h.
#define TAHOE_MAX_INT_STACKED_REGISTER_ID (TAHOE_MAX_INT_REGISTER_ID)
Definition at line 98 of file m_tahoe.h.
#define TAHOE_MAX_INT_STATIC_REGISTER_ID (TAHOE_NUM_INT_STATIC_REG-1)
Definition at line 96 of file m_tahoe.h.
#define TAHOE_MAX_PRED_REGISTER_NUMBER (TAHOE_NUM_PRED_REG-1)
Definition at line 99 of file m_tahoe.h.
#define TAHOE_MIN_INT_REGISTER_ID (0)
Definition at line 93 of file m_tahoe.h.
#define TAHOE_MIN_INT_STACKED_REGISTER_ID (32)
Definition at line 97 of file m_tahoe.h.
#define TAHOE_MIN_INT_STATIC_REGISTER_ID (0)
Definition at line 95 of file m_tahoe.h.
#define TAHOE_NUM_BRANCH_REG (8)
Definition at line 91 of file m_tahoe.h.
#define TAHOE_NUM_FLOAT_REG (128)
Definition at line 90 of file m_tahoe.h.
#define TAHOE_NUM_INT_REG (128)
Definition at line 85 of file m_tahoe.h.
#define TAHOE_NUM_INT_STACKED_REG
Value:
(TAHOE_NUM_INT_REG - \
                                            TAHOE_NUM_INT_STATIC_REG)
Definition at line 87 of file m_tahoe.h.
#define TAHOE_NUM_INT_STATIC_REG (32)
Definition at line 86 of file m_tahoe.h.
#define TAHOE_NUM_PRED_REG (64)
Definition at line 89 of file m_tahoe.h.
#define TAHOE_NUM_SPECIAL_BRANCH_REG (0)
Definition at line 109 of file m_tahoe.h.
#define TAHOE_NUM_SPECIAL_FLOAT_REG (0)
Definition at line 108 of file m_tahoe.h.
#define TAHOE_NUM_SPECIAL_INT_REG (2)
Definition at line 103 of file m_tahoe.h.
#define TAHOE_NUM_SPECIAL_PRED_REG (0)
Definition at line 107 of file m_tahoe.h.
#define TAHOE_PRED_REG_BASE (TAHOE_FLOAT_REG_BASE + TAHOE_NUM_FLOAT_REG)
Definition at line 117 of file m_tahoe.h.
Referenced by M_conflicting_operands_tahoe().
#define TAHOEop_ADD 1011
Definition at line 304 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ADDL 1012
Definition at line 305 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ADDP4 1222
Definition at line 553 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ADDS 1013
Definition at line 306 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ALLOC 1297
Definition at line 636 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_AND 1016
Definition at line 309 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ANDCM 1017
Definition at line 310 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_CALL 1141
Definition at line 453 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_CEXIT 1149
Definition at line 461 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_CLOOP 1150
Definition at line 462 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_COND 1142
Definition at line 454 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_CTOP 1151
Definition at line 463 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_IA 1143
Definition at line 455 of file m_tahoe.h.
#define TAHOEop_BR_RET 1144
Definition at line 456 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_WEXIT 1152
Definition at line 464 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BR_WTOP 1153
Definition at line 465 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BREAK_B 1006
Definition at line 298 of file m_tahoe.h.
#define TAHOEop_BREAK_F 1007
Definition at line 299 of file m_tahoe.h.
#define TAHOEop_BREAK_I 1008
Definition at line 300 of file m_tahoe.h.
#define TAHOEop_BREAK_M 1009
Definition at line 301 of file m_tahoe.h.
#define TAHOEop_BREAK_X 1010
Definition at line 302 of file m_tahoe.h.
#define TAHOEop_BRL_CALL 1145
Definition at line 457 of file m_tahoe.h.
#define TAHOEop_BRL_COND 1146
Definition at line 458 of file m_tahoe.h.
#define TAHOEop_BRP 1147
Definition at line 459 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_BRP_RET 1148
Definition at line 460 of file m_tahoe.h.
#define TAHOEop_BSW_0 1282
Definition at line 621 of file m_tahoe.h.
#define TAHOEop_BSW_1 1283
Definition at line 622 of file m_tahoe.h.
#define TAHOEop_CC 1288
Definition at line 627 of file m_tahoe.h.
#define TAHOEop_CHK_A 1073
Definition at line 375 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_CHK_S 1329
Definition at line 670 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_CHK_S_F 1075
Definition at line 377 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_CHK_S_I 1074
Definition at line 376 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_CHK_S_M 1076
Definition at line 378 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_CLRRRB 1224
Definition at line 556 of file m_tahoe.h.
#define TAHOEop_CLRRRB_PR 1225
Definition at line 557 of file m_tahoe.h.
#define TAHOEop_CMP 1138
Definition at line 449 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe(), and M_tahoe_extra_pred_define_type1().
#define TAHOEop_CMPXCHG1_ACQ 1229
Definition at line 563 of file m_tahoe.h.
#define TAHOEop_CMPXCHG1_REL 1230
Definition at line 564 of file m_tahoe.h.
#define TAHOEop_CMPXCHG2_ACQ 1231
Definition at line 565 of file m_tahoe.h.
#define TAHOEop_CMPXCHG2_REL 1232
Definition at line 566 of file m_tahoe.h.
#define TAHOEop_CMPXCHG4_ACQ 1233
Definition at line 567 of file m_tahoe.h.
#define TAHOEop_CMPXCHG4_REL 1234
Definition at line 568 of file m_tahoe.h.
#define TAHOEop_CMPXCHG8_ACQ 1235
Definition at line 569 of file m_tahoe.h.
#define TAHOEop_CMPXCHG8_REL 1236
Definition at line 570 of file m_tahoe.h.
#define TAHOEop_COVER 1226
Definition at line 559 of file m_tahoe.h.
#define TAHOEop_CZX1_L 1031
Definition at line 327 of file m_tahoe.h.
#define TAHOEop_CZX1_R 1032
Definition at line 328 of file m_tahoe.h.
#define TAHOEop_CZX2_L 1033
Definition at line 329 of file m_tahoe.h.
#define TAHOEop_CZX2_R 1034
Definition at line 330 of file m_tahoe.h.
#define TAHOEop_DEP 1020
Definition at line 314 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_DEP_Z 1021
Definition at line 315 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_EPC 1281
Definition at line 620 of file m_tahoe.h.
#define TAHOEop_EXTR 1022
Definition at line 316 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_EXTR_U 1023
Definition at line 317 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FABS 1325
Definition at line 666 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FADD 1328
Definition at line 669 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FADD_D 1326
Definition at line 667 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FADD_S 1327
Definition at line 668 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FAMAX 1089
Definition at line 396 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FAMIN 1090
Definition at line 397 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FAND 1091
Definition at line 398 of file m_tahoe.h.
#define TAHOEop_FANDCM 1092
Definition at line 399 of file m_tahoe.h.
#define TAHOEop_FC 1298
Definition at line 637 of file m_tahoe.h.
#define TAHOEop_FCHKF 1112
Definition at line 419 of file m_tahoe.h.
#define TAHOEop_FCLASS 1245
Definition at line 582 of file m_tahoe.h.
#define TAHOEop_FCLRF 1113
Definition at line 420 of file m_tahoe.h.
#define TAHOEop_FCMP 1246
Definition at line 583 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FCVT_FX 1247
Definition at line 584 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FCVT_FXU 1248
Definition at line 585 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FCVT_XF 1249
Definition at line 586 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FETCHADD4_ACQ 1237
Definition at line 572 of file m_tahoe.h.
#define TAHOEop_FETCHADD4_REL 1238
Definition at line 573 of file m_tahoe.h.
#define TAHOEop_FETCHADD8_ACQ 1239
Definition at line 574 of file m_tahoe.h.
#define TAHOEop_FETCHADD8_REL 1240
Definition at line 575 of file m_tahoe.h.
#define TAHOEop_FLUSHRS 1227
Definition at line 560 of file m_tahoe.h.
#define TAHOEop_FMA 1082
Definition at line 386 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMA_D 1080
Definition at line 384 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMA_S 1081
Definition at line 385 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMAX 1093
Definition at line 400 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMERGE_NS 1094
Definition at line 401 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMERGE_S 1095
Definition at line 402 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMERGE_SE 1096
Definition at line 403 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMIN 1097
Definition at line 404 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMIX_L 1098
Definition at line 405 of file m_tahoe.h.
#define TAHOEop_FMIX_LR 1099
Definition at line 406 of file m_tahoe.h.
#define TAHOEop_FMIX_R 1100
Definition at line 407 of file m_tahoe.h.
#define TAHOEop_FMS 1085
Definition at line 390 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMS_D 1083
Definition at line 388 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FMS_S 1084
Definition at line 389 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FNMA 1088
Definition at line 394 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FNMA_D 1086
Definition at line 392 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FNMA_S 1087
Definition at line 393 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FOR 1101
Definition at line 408 of file m_tahoe.h.
#define TAHOEop_FPACK 1102
Definition at line 409 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPAMAX 1258
Definition at line 595 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPAMIN 1259
Definition at line 596 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPCMP 1260
Definition at line 597 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPCVT_FX 1250
Definition at line 587 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPCVT_FX_TRUNC 1251
Definition at line 588 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPCVT_FXU 1252
Definition at line 589 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPCVT_FXU_TRUNC 1253
Definition at line 590 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMA 1254
Definition at line 591 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMAX 1261
Definition at line 598 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMERGE 1257
Definition at line 594 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMERGE_NS 1262
Definition at line 599 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMERGE_S 1263
Definition at line 600 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMIN 1264
Definition at line 601 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPMS 1255
Definition at line 592 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPNMA 1256
Definition at line 593 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPRCPA 1265
Definition at line 602 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FPRSQRTA 1266
Definition at line 603 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FRCPA 1103
Definition at line 410 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe(), M_tahoe_extra_pred_define_opcode(), and M_tahoe_extra_pred_define_type2().
#define TAHOEop_FRSQRTA 1104
Definition at line 411 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe(), M_tahoe_extra_pred_define_opcode(), and M_tahoe_extra_pred_define_type2().
#define TAHOEop_FSELECT 1105
Definition at line 412 of file m_tahoe.h.
#define TAHOEop_FSETC 1114
Definition at line 421 of file m_tahoe.h.
#define TAHOEop_FSUB 1333
Definition at line 674 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FSUB_D 1331
Definition at line 672 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FSUB_S 1332
Definition at line 673 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_FSWAP 1106
Definition at line 413 of file m_tahoe.h.
#define TAHOEop_FSWAP_NL 1107
Definition at line 414 of file m_tahoe.h.
#define TAHOEop_FSWAP_NR 1108
Definition at line 415 of file m_tahoe.h.
#define TAHOEop_FSXT_L 1109
Definition at line 416 of file m_tahoe.h.
#define TAHOEop_FSXT_R 1110
Definition at line 417 of file m_tahoe.h.
#define TAHOEop_FWB 1289
Definition at line 628 of file m_tahoe.h.
#define TAHOEop_FXOR 1111
Definition at line 418 of file m_tahoe.h.
#define TAHOEop_GETF_D 1129
Definition at line 438 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_GETF_EXP 1130
Definition at line 439 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_GETF_S 1131
Definition at line 440 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_GETF_SIG 1132
Definition at line 441 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_HALT 1290
Definition at line 629 of file m_tahoe.h.
#define TAHOEop_HALT_MF 1291
Definition at line 630 of file m_tahoe.h.
#define TAHOEop_INVALA 1285
Definition at line 624 of file m_tahoe.h.
#define TAHOEop_INVALA_E 1286
Definition at line 625 of file m_tahoe.h.
#define TAHOEop_INVALA_E_F 1287
Definition at line 626 of file m_tahoe.h.
#define TAHOEop_INVALID 1000
Definition at line 290 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ITC_D 1299
Definition at line 638 of file m_tahoe.h.
#define TAHOEop_ITC_I 1300
Definition at line 639 of file m_tahoe.h.
#define TAHOEop_ITR_D 1301
Definition at line 640 of file m_tahoe.h.
#define TAHOEop_ITR_I 1302
Definition at line 641 of file m_tahoe.h.
#define TAHOEop_LD1 1035
Definition at line 332 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD1_ACQ 1036
Definition at line 333 of file m_tahoe.h.
#define TAHOEop_LD1_BIAS 1037
Definition at line 334 of file m_tahoe.h.
#define TAHOEop_LD1_C 1062
Definition at line 363 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD2 1038
Definition at line 335 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD2_ACQ 1039
Definition at line 336 of file m_tahoe.h.
#define TAHOEop_LD2_BIAS 1040
Definition at line 337 of file m_tahoe.h.
#define TAHOEop_LD2_C 1063
Definition at line 364 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD4 1041
Definition at line 338 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD4_ACQ 1042
Definition at line 339 of file m_tahoe.h.
#define TAHOEop_LD4_BIAS 1043
Definition at line 340 of file m_tahoe.h.
#define TAHOEop_LD4_C 1064
Definition at line 365 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD8 1044
Definition at line 341 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD8_ACQ 1045
Definition at line 342 of file m_tahoe.h.
#define TAHOEop_LD8_BIAS 1046
Definition at line 343 of file m_tahoe.h.
#define TAHOEop_LD8_C 1065
Definition at line 366 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LD8_FILL 1047
Definition at line 344 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LDF8 1051
Definition at line 351 of file m_tahoe.h.
#define TAHOEop_LDF8_A 1052
Definition at line 352 of file m_tahoe.h.
#define TAHOEop_LDF8_C 1066
Definition at line 367 of file m_tahoe.h.
#define TAHOEop_LDF_FILL 1050
Definition at line 349 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LDFD 1053
Definition at line 353 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LDFD_A 1054
Definition at line 354 of file m_tahoe.h.
#define TAHOEop_LDFD_C 1067
Definition at line 368 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LDFE 1055
Definition at line 355 of file m_tahoe.h.
#define TAHOEop_LDFE_A 1056
Definition at line 356 of file m_tahoe.h.
#define TAHOEop_LDFE_C 1068
Definition at line 369 of file m_tahoe.h.
#define TAHOEop_LDFP8 1059
Definition at line 359 of file m_tahoe.h.
#define TAHOEop_LDFP8_C 1069
Definition at line 370 of file m_tahoe.h.
#define TAHOEop_LDFPD 1060
Definition at line 360 of file m_tahoe.h.
#define TAHOEop_LDFPD_C 1070
Definition at line 371 of file m_tahoe.h.
#define TAHOEop_LDFPS 1061
Definition at line 361 of file m_tahoe.h.
#define TAHOEop_LDFPS_C 1071
Definition at line 372 of file m_tahoe.h.
#define TAHOEop_LDFS 1057
Definition at line 357 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LDFS_A 1058
Definition at line 358 of file m_tahoe.h.
#define TAHOEop_LDFS_C 1072
Definition at line 373 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LFETCH 1048
Definition at line 346 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_LFETCH_FAULT 1049
Definition at line 347 of file m_tahoe.h.
#define TAHOEop_LOADRS 1228
Definition at line 561 of file m_tahoe.h.
#define TAHOEop_MF 1292
Definition at line 631 of file m_tahoe.h.
#define TAHOEop_MF_A 1293
Definition at line 632 of file m_tahoe.h.
#define TAHOEop_MIX1_L 1196
Definition at line 521 of file m_tahoe.h.
#define TAHOEop_MIX1_R 1197
Definition at line 522 of file m_tahoe.h.
#define TAHOEop_MIX2_L 1198
Definition at line 523 of file m_tahoe.h.
#define TAHOEop_MIX2_R 1199
Definition at line 524 of file m_tahoe.h.
#define TAHOEop_MIX4_L 1200
Definition at line 525 of file m_tahoe.h.
#define TAHOEop_MIX4_R 1201
Definition at line 526 of file m_tahoe.h.
#define TAHOEop_MOV_FR 1330
Definition at line 671 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_FRAR_I 1116
Definition at line 424 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_FRAR_M 1118
Definition at line 426 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_FRBR 1133
Definition at line 443 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_FRCR 1119
Definition at line 427 of file m_tahoe.h.
#define TAHOEop_MOV_FRIP 1121
Definition at line 429 of file m_tahoe.h.
#define TAHOEop_MOV_FRPR 1122
Definition at line 430 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_FRSYST 1136
Definition at line 446 of file m_tahoe.h.
#define TAHOEop_MOV_GR 1323
Definition at line 664 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_TOAR_I 1115
Definition at line 423 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_TOAR_M 1117
Definition at line 425 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_TOBR 1134
Definition at line 444 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_TOCR 1120
Definition at line 428 of file m_tahoe.h.
#define TAHOEop_MOV_TOPR 1123
Definition at line 431 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOV_TOPR_ROT 1124
Definition at line 432 of file m_tahoe.h.
#define TAHOEop_MOV_TOSYST 1135
Definition at line 445 of file m_tahoe.h.
#define TAHOEop_MOVI 1322
Definition at line 663 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MOVL 1137
Definition at line 447 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MUX1 1202
Definition at line 528 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_MUX2 1203
Definition at line 529 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_NON_INSTR 1324
Definition at line 665 of file m_tahoe.h.
#define TAHOEop_NOP_B 1001
Definition at line 292 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_NOP_F 1002
Definition at line 293 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_NOP_I 1003
Definition at line 294 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_NOP_M 1004
Definition at line 295 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_NOP_X 1005
Definition at line 296 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_OR 1018
Definition at line 311 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PACK2_SSS 1204
Definition at line 531 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PACK2_USS 1205
Definition at line 532 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PACK4_SSS 1206
Definition at line 533 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD1 1154
Definition at line 467 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD1_SSS 1155
Definition at line 468 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD1_UUS 1156
Definition at line 469 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD1_UUU 1157
Definition at line 470 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD2 1158
Definition at line 471 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD2_SSS 1159
Definition at line 472 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD2_UUS 1160
Definition at line 473 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD2_UUU 1161
Definition at line 474 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PADD4 1162
Definition at line 475 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVG1 1163
Definition at line 477 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVG1_RAZ 1164
Definition at line 478 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVG2 1165
Definition at line 479 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVG2_RAZ 1166
Definition at line 480 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVGSUB1 1167
Definition at line 482 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PAVGSUB2 1168
Definition at line 483 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP1_EQ 1169
Definition at line 485 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP1_GT 1170
Definition at line 486 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP2_EQ 1171
Definition at line 487 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP2_GT 1172
Definition at line 488 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP_EQ 1173
Definition at line 489 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PCMP_GT 1174
Definition at line 490 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMAX1_U 1186
Definition at line 505 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMAX2 1187
Definition at line 506 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMIN1_U 1188
Definition at line 508 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMIN2 1189
Definition at line 509 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMPY2_L 1191
Definition at line 513 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMPY2_R 1192
Definition at line 514 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMPYSHR2 1193
Definition at line 516 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PMPYSHR2_U 1194
Definition at line 517 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_POPCNT 1195
Definition at line 519 of file m_tahoe.h.
#define TAHOEop_PROBE_R 1303
Definition at line 642 of file m_tahoe.h.
#define TAHOEop_PROBE_R_FAULT 1304
Definition at line 643 of file m_tahoe.h.
#define TAHOEop_PROBE_RW_FAULT 1305
Definition at line 644 of file m_tahoe.h.
#define TAHOEop_PROBE_W 1306
Definition at line 645 of file m_tahoe.h.
#define TAHOEop_PROBE_W_FAULT 1307
Definition at line 646 of file m_tahoe.h.
#define TAHOEop_PSAD1 1190
Definition at line 511 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHL2 1207
Definition at line 535 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHL4 1208
Definition at line 536 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHLADD2 1175
Definition at line 492 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHR2 1209
Definition at line 537 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHR2_U 1210
Definition at line 538 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHR4 1211
Definition at line 539 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHR4_U 1212
Definition at line 540 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSHRADD2 1176
Definition at line 493 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB1 1177
Definition at line 495 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB1_SSS 1178
Definition at line 496 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB1_UUS 1179
Definition at line 497 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB1_UUU 1180
Definition at line 498 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB2 1181
Definition at line 499 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB2_SSS 1182
Definition at line 500 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB2_UUS 1183
Definition at line 501 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB2_UUU 1184
Definition at line 502 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PSUB4 1185
Definition at line 503 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_PTC_E 1308
Definition at line 647 of file m_tahoe.h.
#define TAHOEop_PTC_G 1309
Definition at line 648 of file m_tahoe.h.
#define TAHOEop_PTC_GA 1310
Definition at line 649 of file m_tahoe.h.
#define TAHOEop_PTC_L 1311
Definition at line 650 of file m_tahoe.h.
#define TAHOEop_PTR_D 1312
Definition at line 651 of file m_tahoe.h.
#define TAHOEop_PTR_I 1313
Definition at line 652 of file m_tahoe.h.
#define TAHOEop_RFI 1284
Definition at line 623 of file m_tahoe.h.
#define TAHOEop_RSM 1314
Definition at line 653 of file m_tahoe.h.
#define TAHOEop_RUM 1315
Definition at line 654 of file m_tahoe.h.
#define TAHOEop_SETF_D 1125
Definition at line 434 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SETF_EXP 1126
Definition at line 435 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SETF_S 1127
Definition at line 436 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SETF_SIG 1128
Definition at line 437 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHL 1213
Definition at line 542 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHLADD 1014
Definition at line 307 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHLADDP4 1223
Definition at line 554 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHR 1214
Definition at line 543 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHR_U 1215
Definition at line 544 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SHRP 1024
Definition at line 318 of file m_tahoe.h.
#define TAHOEop_SRLZ_D 1294
Definition at line 633 of file m_tahoe.h.
#define TAHOEop_SRLZ_I 1295
Definition at line 634 of file m_tahoe.h.
#define TAHOEop_SSM 1316
Definition at line 655 of file m_tahoe.h.
#define TAHOEop_ST1 1267
Definition at line 605 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ST1_REL 1268
Definition at line 606 of file m_tahoe.h.
#define TAHOEop_ST2 1269
Definition at line 607 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ST2_REL 1270
Definition at line 608 of file m_tahoe.h.
#define TAHOEop_ST4 1271
Definition at line 609 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ST4_REL 1272
Definition at line 610 of file m_tahoe.h.
#define TAHOEop_ST8 1273
Definition at line 611 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ST8_REL 1274
Definition at line 612 of file m_tahoe.h.
#define TAHOEop_ST8_SPILL 1275
Definition at line 613 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_START 1000
Definition at line 286 of file m_tahoe.h.
#define TAHOEop_STF8 1277
Definition at line 615 of file m_tahoe.h.
#define TAHOEop_STF_SPILL 1276
Definition at line 614 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_STFD 1278
Definition at line 616 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_STFE 1279
Definition at line 617 of file m_tahoe.h.
#define TAHOEop_STFS 1280
Definition at line 618 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SUB 1015
Definition at line 308 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SUM 1317
Definition at line 656 of file m_tahoe.h.
#define TAHOEop_SXT1 1025
Definition at line 320 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SXT2 1026
Definition at line 321 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SXT4 1027
Definition at line 322 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_SYNC_I 1296
Definition at line 635 of file m_tahoe.h.
#define TAHOEop_TAK 1318
Definition at line 657 of file m_tahoe.h.
#define TAHOEop_TBIT 1139
Definition at line 450 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe(), M_tahoe_extra_pred_define_opcode(), and M_tahoe_extra_pred_define_type1().
#define TAHOEop_THASH 1319
Definition at line 658 of file m_tahoe.h.
#define TAHOEop_TNAT 1140
Definition at line 451 of file m_tahoe.h.
#define TAHOEop_TPA 1320
Definition at line 659 of file m_tahoe.h.
#define TAHOEop_TTAG 1321
Definition at line 660 of file m_tahoe.h.
#define TAHOEop_UNPACK1_H 1216
Definition at line 546 of file m_tahoe.h.
#define TAHOEop_UNPACK1_L 1217
Definition at line 547 of file m_tahoe.h.
#define TAHOEop_UNPACK2_H 1218
Definition at line 548 of file m_tahoe.h.
#define TAHOEop_UNPACK2_L 1219
Definition at line 549 of file m_tahoe.h.
#define TAHOEop_UNPACK4_H 1220
Definition at line 550 of file m_tahoe.h.
#define TAHOEop_UNPACK4_L 1221
Definition at line 551 of file m_tahoe.h.
#define TAHOEop_VERSION 1
Definition at line 283 of file m_tahoe.h.
#define TAHOEop_XCHG1 1241
Definition at line 577 of file m_tahoe.h.
#define TAHOEop_XCHG2 1242
Definition at line 578 of file m_tahoe.h.
#define TAHOEop_XCHG4 1243
Definition at line 579 of file m_tahoe.h.
#define TAHOEop_XCHG8 1244
Definition at line 580 of file m_tahoe.h.
#define TAHOEop_XMA_H 1077
Definition at line 380 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_XMA_HU 1078
Definition at line 381 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_XMA_L 1079
Definition at line 382 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_XOR 1019
Definition at line 312 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ZXT1 1028
Definition at line 323 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ZXT2 1029
Definition at line 324 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
#define TAHOEop_ZXT4 1030
Definition at line 325 of file m_tahoe.h.
Referenced by M_opc_from_proc_opc_tahoe().
Enumeration Type Documentation
anonymous enum
Enumerator:
M_IPF_ITANIUM
M_IPF_MCKINLEY
M_IPF_MADISON
M_IPF_DEERFIELD
M_IPF_MENDOCITO
M_IPF_CHIVANO
Definition at line 129 of file m_tahoe.h.
anonymous enum
Enumerator:
M_IPF_LIN_LP64
M_IPF_WIN_P64
M_IPF_HPUX_LP64
M_IPF_HPUX_ILP32
Definition at line 150 of file m_tahoe.h.
anonymous enum
Enumerator:
TAHOE_MAC_ZERO
TAHOE_MAC_GP
TAHOE_MAC_AP
TAHOE_MAC_RETADDR
TAHOE_MAC_PRED_TRUE
TAHOE_MAC_FZERO
TAHOE_MAC_FONE
TAHOE_PRED_SAVE_REG
TAHOE_PRED_BLK_REG
TAHOE_PRED_ROT_BLK_REG
TAHOE_GP_SAVE_REG
TAHOE_MAC_TMPREG1
TAHOE_MAC_TMPREG2
TAHOE_MAC_LEAF
TAHOE_MAC_SYNC_SIZE
TAHOE_MAC_MEM_ALLOC
TAHOE_MAC_TEMPLATE
TAHOE_MAC_LABEL
TAHOE_MAC_PSP
TAHOE_MAC_PSPILL
TAHOE_MAC_KR0
TAHOE_MAC_KR1
TAHOE_MAC_KR2
TAHOE_MAC_KR3
TAHOE_MAC_RSC
TAHOE_MAC_BSP
TAHOE_MAC_RNAT
TAHOE_MAC_CCV
TAHOE_MAC_UNAT
TAHOE_MAC_FPSR
TAHOE_MAC_ITC
TAHOE_MAC_AR_PFS
TAHOE_MAC_LC
TAHOE_MAC_EC
Definition at line 167 of file m_tahoe.h.
Function Documentation
int M_cannot_predicate_tahoe (L_Oper * oper)
Definition at line 1404 of file ml_tahoe.c.
Referenced by M_cannot_predicate().
int M_conflicting_operands_tahoe (L_Operand * operand, L_Operand * conflict_array[], int len, int prepass)
Definition at line 870 of file ml_tahoe.c.
References M_assert(), TAHOE_MAC_FONE, TAHOE_MAC_FZERO, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_REG_BASE.
Referenced by M_dep_conflicting_operands().
void M_define_macros_tahoe (STRING_Symbol_Table * sym_tbl)
Definition at line 334 of file ml_tahoe.c.
References M_add_symbol, M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_GP_SAVE_REG, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FONE, TAHOE_MAC_FPSR, TAHOE_MAC_FZERO, TAHOE_MAC_GP, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LABEL, TAHOE_MAC_LC, TAHOE_MAC_LEAF, TAHOE_MAC_MEM_ALLOC, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_PSP, TAHOE_MAC_PSPILL, TAHOE_MAC_RETADDR, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_SYNC_SIZE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_TMPREG1, TAHOE_MAC_TMPREG2, TAHOE_MAC_UNAT, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_SAVE_REG.
Referenced by M_define_macros().
char* M_get_macro_name_tahoe (int id)
Definition at line 389 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_GP_SAVE_REG, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FONE, TAHOE_MAC_FPSR, TAHOE_MAC_FZERO, TAHOE_MAC_GP, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LABEL, TAHOE_MAC_LC, TAHOE_MAC_LEAF, TAHOE_MAC_MEM_ALLOC, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_PSP, TAHOE_MAC_PSPILL, TAHOE_MAC_RETADDR, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_SYNC_SIZE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_TMPREG1, TAHOE_MAC_TMPREG2, TAHOE_MAC_UNAT, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_SAVE_REG.
Referenced by M_get_macro_name().
void M_get_memory_operands_tahoe (int * first, int * number, int proc_opc)
Definition at line 1420 of file ml_tahoe.c.
Referenced by M_get_memory_operands().
int M_is_stack_operand_tahoe (L_Operand * operand)
Definition at line 752 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_PSP, and TAHOE_MAC_PSPILL.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_tahoe (L_Operand * operand)
Definition at line 778 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FPSR, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LC, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_UNAT, and TAHOE_PRED_BLK_REG.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_tahoe (L_Oper * oper, char * name)
Definition at line 531 of file ml_tahoe.c.
References label_base, M_assert(), M_IPF_MODEL_OK, M_model, and zero_offset.
Referenced by M_num_oper_required_for().
int M_num_registers_tahoe (int ctype)
Definition at line 726 of file ml_tahoe.c.
Referenced by M_num_registers().
int M_opc_from_proc_opc_tahoe (int proc_opc)
Definition at line 997 of file ml_tahoe.c.
References I_warn(), M_assert(), TAHOEop_ADD, TAHOEop_ADDL, TAHOEop_ADDP4, TAHOEop_ADDS, TAHOEop_ALLOC, TAHOEop_AND, TAHOEop_ANDCM, TAHOEop_BR_CALL, TAHOEop_BR_CEXIT, TAHOEop_BR_CLOOP, TAHOEop_BR_COND, TAHOEop_BR_CTOP, TAHOEop_BR_RET, TAHOEop_BR_WEXIT, TAHOEop_BR_WTOP, TAHOEop_BRP, TAHOEop_CHK_A, TAHOEop_CHK_S, TAHOEop_CHK_S_F, TAHOEop_CHK_S_I, TAHOEop_CHK_S_M, TAHOEop_CMP, TAHOEop_DEP, TAHOEop_DEP_Z, TAHOEop_EXTR, TAHOEop_EXTR_U, TAHOEop_FABS, TAHOEop_FADD, TAHOEop_FADD_D, TAHOEop_FADD_S, TAHOEop_FAMAX, TAHOEop_FAMIN, TAHOEop_FCMP, TAHOEop_FCVT_FX, TAHOEop_FCVT_FXU, TAHOEop_FCVT_XF, TAHOEop_FMA, TAHOEop_FMA_D, TAHOEop_FMA_S, TAHOEop_FMAX, TAHOEop_FMERGE_NS, TAHOEop_FMERGE_S, TAHOEop_FMERGE_SE, TAHOEop_FMIN, TAHOEop_FMS, TAHOEop_FMS_D, TAHOEop_FMS_S, TAHOEop_FNMA, TAHOEop_FNMA_D, TAHOEop_FNMA_S, TAHOEop_FPACK, TAHOEop_FPAMAX, TAHOEop_FPAMIN, TAHOEop_FPCMP, TAHOEop_FPCVT_FX, TAHOEop_FPCVT_FX_TRUNC, TAHOEop_FPCVT_FXU, TAHOEop_FPCVT_FXU_TRUNC, TAHOEop_FPMA, TAHOEop_FPMAX, TAHOEop_FPMERGE, TAHOEop_FPMERGE_NS, TAHOEop_FPMERGE_S, TAHOEop_FPMIN, TAHOEop_FPMS, TAHOEop_FPNMA, TAHOEop_FPRCPA, TAHOEop_FPRSQRTA, TAHOEop_FRCPA, TAHOEop_FRSQRTA, TAHOEop_FSUB, TAHOEop_FSUB_D, TAHOEop_FSUB_S, TAHOEop_GETF_D, TAHOEop_GETF_EXP, TAHOEop_GETF_S, TAHOEop_GETF_SIG, TAHOEop_INVALID, TAHOEop_LD1, TAHOEop_LD1_C, TAHOEop_LD2, TAHOEop_LD2_C, TAHOEop_LD4, TAHOEop_LD4_C, TAHOEop_LD8, TAHOEop_LD8_C, TAHOEop_LD8_FILL, TAHOEop_LDF_FILL, TAHOEop_LDFD, TAHOEop_LDFD_C, TAHOEop_LDFS, TAHOEop_LDFS_C, TAHOEop_LFETCH, TAHOEop_MOV_FR, TAHOEop_MOV_FRAR_I, TAHOEop_MOV_FRAR_M, TAHOEop_MOV_FRBR, TAHOEop_MOV_FRPR, TAHOEop_MOV_GR, TAHOEop_MOV_TOAR_I, TAHOEop_MOV_TOAR_M, TAHOEop_MOV_TOBR, TAHOEop_MOV_TOPR, TAHOEop_MOVI, TAHOEop_MOVL, TAHOEop_MUX1, TAHOEop_MUX2, TAHOEop_NOP_B, TAHOEop_NOP_F, TAHOEop_NOP_I, TAHOEop_NOP_M, TAHOEop_NOP_X, TAHOEop_OR, TAHOEop_PACK2_SSS, TAHOEop_PACK2_USS, TAHOEop_PACK4_SSS, TAHOEop_PADD1, TAHOEop_PADD1_SSS, TAHOEop_PADD1_UUS, TAHOEop_PADD1_UUU, TAHOEop_PADD2, TAHOEop_PADD2_SSS, TAHOEop_PADD2_UUS, TAHOEop_PADD2_UUU, TAHOEop_PADD4, TAHOEop_PAVG1, TAHOEop_PAVG1_RAZ, TAHOEop_PAVG2, TAHOEop_PAVG2_RAZ, TAHOEop_PAVGSUB1, TAHOEop_PAVGSUB2, TAHOEop_PCMP1_EQ, TAHOEop_PCMP1_GT, TAHOEop_PCMP2_EQ, TAHOEop_PCMP2_GT, TAHOEop_PCMP_EQ, TAHOEop_PCMP_GT, TAHOEop_PMAX1_U, TAHOEop_PMAX2, TAHOEop_PMIN1_U, TAHOEop_PMIN2, TAHOEop_PMPY2_L, TAHOEop_PMPY2_R, TAHOEop_PMPYSHR2, TAHOEop_PMPYSHR2_U, TAHOEop_PSAD1, TAHOEop_PSHL2, TAHOEop_PSHL4, TAHOEop_PSHLADD2, TAHOEop_PSHR2, TAHOEop_PSHR2_U, TAHOEop_PSHR4, TAHOEop_PSHR4_U, TAHOEop_PSHRADD2, TAHOEop_PSUB1, TAHOEop_PSUB1_SSS, TAHOEop_PSUB1_UUS, TAHOEop_PSUB1_UUU, TAHOEop_PSUB2, TAHOEop_PSUB2_SSS, TAHOEop_PSUB2_UUS, TAHOEop_PSUB2_UUU, TAHOEop_PSUB4, TAHOEop_SETF_D, TAHOEop_SETF_EXP, TAHOEop_SETF_S, TAHOEop_SETF_SIG, TAHOEop_SHL, TAHOEop_SHLADD, TAHOEop_SHLADDP4, TAHOEop_SHR, TAHOEop_SHR_U, TAHOEop_ST1, TAHOEop_ST2, TAHOEop_ST4, TAHOEop_ST8, TAHOEop_ST8_SPILL, TAHOEop_STF_SPILL, TAHOEop_STFD, TAHOEop_STFS, TAHOEop_SUB, TAHOEop_SXT1, TAHOEop_SXT2, TAHOEop_SXT4, TAHOEop_TBIT, TAHOEop_XMA_H, TAHOEop_XMA_HU, TAHOEop_XMA_L, TAHOEop_XOR, TAHOEop_ZXT1, TAHOEop_ZXT2, and TAHOEop_ZXT4.
Referenced by M_opc_from_proc_opc().
int M_oper_supported_in_arch_tahoe (int opc)
Definition at line 480 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, and M_model.
Referenced by M_oper_supported_in_arch().
int M_operand_type_tahoe (L_Operand * operand)
Definition at line 822 of file ml_tahoe.c.
References M_assert(), MDES_OPERAND_btr, MDES_OPERAND_f, MDES_OPERAND_i, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_p, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_tahoe (char * model_name)
Definition at line 1130 of file mi_tahoe.c.
References M_assert(), M_IPF_CHIVANO, M_IPF_DEERFIELD, M_IPF_ITANIUM, M_IPF_MADISON, M_IPF_MCKINLEY, M_IPF_MENDOCITO, M_model, and M_use_layout_database.
Referenced by M_set_machine().
int M_tahoe_array_align (M_Type type)
Definition at line 554 of file mi_tahoe.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_tahoe_array_layout (M_Type type, int * offset)
Definition at line 546 of file mi_tahoe.c.
Referenced by M_array_layout().
int M_tahoe_array_size (M_Type type, int dim)
Definition at line 561 of file mi_tahoe.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_tahoe_bit_char (M_Type type, int n)
Definition at line 249 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_tahoe_bit_int (M_Type type, int n)
Definition at line 224 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_tahoe_bit_llong (M_Type type, int n)
Definition at line 200 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_LLONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_llong().
void M_tahoe_bit_long (M_Type type, int n)
Definition at line 212 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_tahoe_bit_short (M_Type type, int n)
Definition at line 236 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_tahoe_call_type (M_Type type, M_Type ntype)
Definition at line 464 of file mi_tahoe.c.
References M_tahoe_double(), M_tahoe_llong(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_tahoe_call_type2 (M_Type type, M_Type ntype)
Definition at line 498 of file mi_tahoe.c.
References M_tahoe_char(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_tahoe_long(), M_tahoe_pointer(), M_tahoe_short(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_tahoe_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1015 of file mi_tahoe.c.
Referenced by M_cb_label_name().
void M_tahoe_char (M_Type type, int unsign)
Definition at line 261 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_CHAR, M_TAHOE_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_dataflow_macro (int id)
Definition at line 304 of file ml_tahoe.c.
References FALSE, M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_FONE, TAHOE_MAC_FZERO, TAHOE_MAC_LABEL, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_ZERO, and TRUE.
Referenced by M_dataflow_macro().
void M_tahoe_double (M_Type type, int unsign)
Definition at line 321 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_DOUBLE, M_TAHOE_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
L_Operand* M_tahoe_epilogue_cntr_register ()
Definition at line 1373 of file ml_tahoe.c.
References TAHOE_MAC_EC.
Referenced by M_return_epilogue_cntr_register().
int M_tahoe_eval_type (M_Type type, M_Type ntype)
Definition at line 343 of file mi_tahoe.c.
References I_punt(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_POINTER, M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_tahoe_eval_type2 (M_Type type, M_Type ntype)
Definition at line 419 of file mi_tahoe.c.
References M_tahoe_char(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_tahoe_long(), M_tahoe_pointer(), M_tahoe_short(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
int M_tahoe_extra_pred_define_opcode (int proc_opc)
Definition at line 213 of file ml_tahoe.c.
References TAHOEop_FRCPA, TAHOEop_FRSQRTA, and TAHOEop_TBIT.
Referenced by M_extra_pred_define_opcode().
int M_tahoe_extra_pred_define_type1 (L_Oper *)
Definition at line 236 of file ml_tahoe.c.
References TAHOEop_CMP, and TAHOEop_TBIT.
Referenced by M_extra_pred_define_type1().
int M_tahoe_extra_pred_define_type2 (L_Oper *)
Definition at line 265 of file ml_tahoe.c.
References TAHOEop_FRCPA, and TAHOEop_FRSQRTA.
Referenced by M_extra_pred_define_type2().
void M_tahoe_float (M_Type type, int unsign)
Definition at line 311 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_FLOAT, M_TAHOE_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
char* M_tahoe_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1103 of file mi_tahoe.c.
Referenced by M_fn_label_name().
char* M_tahoe_fn_name_from_label (char * label)
Definition at line 1119 of file mi_tahoe.c.
Referenced by M_fn_name_from_label().
int M_tahoe_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 1464 of file mi_tahoe.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_warn(), M_align_offset(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_TAHOE_FLT_BASE, M_TAHOE_IN_INT_BASE, M_TAHOE_MAX_FNVAR_FLT_REG, M_TAHOE_MAX_FNVAR_INT_REG, M_TAHOE_OUT_INT_BASE, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_LLONG, M_THRU_MEMORY, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, SCRATCH_SPACE_SIZE, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_fnvar_layout().
int M_tahoe_fnvar_to_lvar (_M_Type type, long int * offset, char ** base_macro, int local_space)
Definition at line 1748 of file mi_tahoe.c.
References ADDR_ALIGN, _struct_M_Type::align, M_assert(), M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, _struct_M_Type::size, and _struct_M_Type::type.
int M_tahoe_fragile_macro (int macro_value)
Definition at line 82 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_AP, TAHOE_MAC_EC, TAHOE_MAC_LC, TAHOE_MAC_TMPREG1, and TAHOE_MAC_TMPREG2.
Referenced by M_fragile_macro().
Set M_tahoe_fragile_macro_set (void)
Definition at line 145 of file ml_tahoe.c.
References Set_add(), Set_tahoe_fragile_macro, TAHOE_MAC_AP, TAHOE_MAC_EC, TAHOE_MAC_LC, TAHOE_MAC_TMPREG1, and TAHOE_MAC_TMPREG2.
Referenced by M_fragile_macro_set().
void M_tahoe_int (M_Type type, int unsign)
Definition at line 281 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_INT, M_TAHOE_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
int M_tahoe_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1023 of file mi_tahoe.c.
Referenced by M_is_cb_label().
int M_tahoe_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1040 of file mi_tahoe.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_tahoe_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1031 of file mi_tahoe.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_tahoe_layout_fnvar (List param_list, char ** macro, int * pcount, int purpose)
Definition at line 1243 of file mi_tahoe.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_warn(), List_next(), List_start(), M_align_offset(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_RET_FNVAR, M_TAHOE_FLT_BASE, M_TAHOE_IN_INT_BASE, M_TAHOE_MAX_FNVAR_FLT_REG, M_TAHOE_MAX_FNVAR_INT_REG, M_TAHOE_OUT_INT_BASE, M_TAHOE_RET_INT_BASE, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_LLONG, M_THRU_MEMORY, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, SCRATCH_SPACE_SIZE, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_tahoe_layout_order (void)
Definition at line 643 of file mi_tahoe.c.
References M_assert(), M_BIG_ENDIAN, M_IPF_HPUX_ILP32, M_IPF_HPUX_LP64, M_IPF_LIN_LP64, M_IPF_WIN_P64, M_LITTLE_ENDIAN, and M_swarch.
Referenced by M_layout_order(), M_tahoe_struct_layout(), and M_tahoe_struct_size().
int M_tahoe_layout_retvar (M_Param param, int purpose)
Definition at line 1675 of file mi_tahoe.c.
References _struct_M_Type::flags, I_warn(), M_assert(), M_INDIRECT_THRU_REGISTER, M_TAHOE_RET_INT_BASE, M_tahoe_return_register(), M_TAHOE_SIZE_LLONG, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_retvar().
void M_tahoe_llong (M_Type type, int unsign)
Definition at line 291 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_LLONG, M_TAHOE_SIZE_LLONG, M_TYPE_LLONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_llong(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
void M_tahoe_long (M_Type type, int unsign)
Definition at line 301 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_LONG, M_TAHOE_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
L_Operand* M_tahoe_loop_cntr_register ()
Definition at line 1381 of file ml_tahoe.c.
References I_punt(), and NULL.
Referenced by M_return_loop_cntr_register().
int M_tahoe_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1807 of file mi_tahoe.c.
References ADDR_ALIGN, _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_INT, M_TYPE_BIT_LONG, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_tahoe_no_short_int (void)
Definition at line 1007 of file mi_tahoe.c.
References M_TAHOE_SIZE_INT, and M_TAHOE_SIZE_SHORT.
Referenced by M_no_short_int().
void M_tahoe_pointer (M_Type type)
Definition at line 331 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_POINTER, M_TAHOE_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_return_register (int type, int purpose)
Definition at line 1081 of file mi_tahoe.c.
References M_TAHOE_RET_FLT_BASE, M_TAHOE_RET_INT_BASE, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, and M_TYPE_LONG.
Referenced by M_return_register(), and M_tahoe_layout_retvar().
void M_tahoe_short (M_Type type, int unsign)
Definition at line 271 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_SHORT, M_TAHOE_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_struct_align (int n, _M_Type * type)
Definition at line 893 of file mi_tahoe.c.
References M_TAHOE_ALIGN_CHAR.
Referenced by M_struct_align().
void M_tahoe_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 678 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_BIG_ENDIAN, M_LITTLE_ENDIAN, M_tahoe_layout_order(), M_TAHOE_SIZE_CHAR, M_TAHOE_SIZE_INT, M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_tahoe_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 913 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_BIG_ENDIAN, M_LITTLE_ENDIAN, M_TAHOE_ALIGN_CHAR, M_TAHOE_ALIGN_LONG, M_TAHOE_ALIGN_SHORT, M_tahoe_layout_order(), M_TAHOE_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_tahoe_structure_pointer (int purpose)
Definition at line 1073 of file mi_tahoe.c.
References M_TAHOE_RET_INT_BASE.
Referenced by M_structure_pointer().
int M_tahoe_subroutine_call (int opc)
Definition at line 284 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, and M_model.
Referenced by M_subroutine_call().
int M_tahoe_type_align (int mtype)
Definition at line 148 of file mi_tahoe.c.
References M_TAHOE_ALIGN_BIT, M_TAHOE_ALIGN_CHAR, M_TAHOE_ALIGN_DOUBLE, M_TAHOE_ALIGN_FLOAT, M_TAHOE_ALIGN_INT, M_TAHOE_ALIGN_LLONG, M_TAHOE_ALIGN_LONG, M_TAHOE_ALIGN_POINTER, M_TAHOE_ALIGN_SHORT, M_TAHOE_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_tahoe_type_size (int mtype)
Definition at line 111 of file mi_tahoe.c.
References M_TAHOE_SIZE_BIT, M_TAHOE_SIZE_CHAR, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_FLOAT, M_TAHOE_SIZE_INT, M_TAHOE_SIZE_LLONG, M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_POINTER, M_TAHOE_SIZE_SHORT, M_TAHOE_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_tahoe_union_align (int n, _M_Type * type)
Definition at line 589 of file mi_tahoe.c.
References M_TAHOE_ALIGN_CHAR.
Referenced by M_union_align().
void M_tahoe_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 576 of file mi_tahoe.c.
Referenced by M_union_layout().
int M_tahoe_union_size (int n, _M_Type * type)
Definition at line 610 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_tahoe_void (M_Type type)
Definition at line 190 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_VOID, M_TAHOE_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), and M_void().