m_ti.h File Reference
#include <config.h>
#include <machine/m_spec.h>
Defines
#define INT_2EXP15 0x8000
#define INT_2EXP23 0x800000
#define FIELD_16(a) ((((a) >= -INT_2EXP15)&&((a) < INT_2EXP15))?1:0)
#define FIELD_24(a) ((((a) >= -INT_2EXP23)&&((a) < INT_2EXP23))?1:0)
#define LTIop_ALU_DIRECT 1000
#define LTIop_ALU_INDIRECT 1001
#define LTIop_ALU_REG_INDIRECT 1050
#define LTIop_ALU_INDIRECT_REG 1051
#define LTIop_ALU_INDIRECT_INDIRECT 1052
#define LTIop_ALU_REG_DIRECT 1053
#define LTIop_BS 1150
#define LTIop_BD 1151
#define LTIop_BR 1152
#define LTIop_BRD 1153
#define LTIop_CALL 1154
#define LTIop_RETS 1155
#define LTIop_REPEAT_BLOCK 1156
#define LTIop_REPEAT_INSTRUCTION 1157
#define LTIop_POP 1158
#define LTIop_POPF 1159
#define LTIop_PUSH 1160
#define LTIop_PUSHF 1161
#define LTIop_SUBRI 1162
#define LTIop_SUBRF 1163
#define LTIop_CALLU 1164
#define LTIop_BU 1165
#define LTIop_BUD 1166
#define LTIop_DB 1167
#define LTIop_DBD 1168
#define LTIop_PAR_STORE 1301
#define LTIop_PAR_LOAD 1302
#define LTIop_PAR_ONE_OPERAND 1303
#define LTIop_PAR_TWO_OPERAND 1304
#define TIopcode_ALU_DIRECT `LTIop_ALU_DIRECT`
#define TIopcode_ALU_INDIRECT `LTIop_ALU_INDIRECT`
#define TIopcode_ALU_REG_INDIRECT `LTIop_ALU_REG_INDIRECT`
#define TIopcode_ALU_INDIRECT_REG `LTIop_ALU_INDIRECT_REG`
#define TIopcode_ALU_INDIRECT_INDIRECT `LTIop_ALU_INDIRECT_INDIRECT`
#define TIopcode_ALU_REG_DIRECT `LTIop_ALU_REG_DIRECT`
#define TIopcode_BS `LTIop_BS`
#define TIopcode_BD `LTIop_BD`
#define TIopcode_BR `LTIop_BR`
#define TIopcode_BRD `LTIop_BRD`
#define TIopcode_CALL `LTIop_CALL`
#define TIopcode_RETS `LTIop_RETS`
#define TIopcode_REPEAT_BLOCK `LTIop_REPEAT_BLOCK`
#define TIopcode_REPEAT_INSTRUCTION `LTIop_REPEAT_INSTRUCTION`
#define TIopcode_POP `LTIop_POP`
#define TIopcode_POPF `LTIop_POPF`
#define TIopcode_PUSH `LTIop_PUSH`
#define TIopcode_PUSHF `LTIop_PUSHF`
#define TIopcode_SUBRI `LTIop_SUBRI`
#define TIopcode_SUBRF `LTIop_SUBRF`
#define TIopcode_CALLU `LTIop_CALLU`
#define TIopcode_BU `LTIop_BU`
#define TIopcode_BUD `LTIop_BUD`
#define TIopcode_DB `LTIop_DB`
#define TIopcode_DBD `LTIop_DBD`
#define TIopcode_PAR_STORE `LTIop_PAR_STF`
#define TIopcode_PAR_LOAD `LTIop_PAR_STI`
#define TIopcode_PAR_ONE_OPERAND `LTIop_PAR_ADDF_SUBF`
#define TIopcode_PAR_TWO_OPERAND `LTIop_PAR_ADDI_SUBI`
Enumerations
enum { M_TI_1 = 1
 }
enum {
TI_MAC_LEAF = 100,
TI_MAC_ALLOC,
TI_MAC_CALLEE_I,
TI_MAC_CALLEE_F,
TI_MAC_TRUE_SP,
TI_MAC_COMPUTATION_REG0,
TI_MAC_COMPUTATION_REG1,
TI_MAC_COMPUTATION_REG2,
TI_MAC_COMPUTATION_REG3,
TI_MAC_COMPUTATION_REG4,
TI_MAC_COMPUTATION_REG5,
TI_MAC_COMPUTATION_REG6,
TI_MAC_COMPUTATION_REG7,
TI_MAC_AUXILIARY_REG0,
TI_MAC_AUXILIARY_REG1,
TI_MAC_AUXILIARY_REG2,
TI_MAC_AUXILIARY_REG3,
TI_MAC_AUXILIARY_REG4,
TI_MAC_AUXILIARY_REG5,
TI_MAC_AUXILIARY_REG6,
TI_MAC_AUXILIARY_REG7,
TI_MAC_ST,
TI_MAC_BK,
TI_MAC_INDEX_REG0,
TI_MAC_INDEX_REG1,
TI_MAC_FP,
TI_MAC_DP,
TI_MAC_RS,
TI_MAC_RE,
TI_MAC_RC
 }
Functions
int M_ti_type_size (int mtype)
int M_ti_type_align (int mtype)
void M_ti_void (M_Type type)
void M_ti_bit_long (M_Type type, int n)
void M_ti_bit_int (M_Type type, int n)
void M_ti_bit_short (M_Type type, int n)
void M_ti_bit_char (M_Type type, int n)
void M_ti_char (M_Type type, int unsign)
void M_ti_short (M_Type type, int unsign)
void M_ti_int (M_Type type, int unsign)
void M_ti_long (M_Type type, int unsign)
void M_ti_float (M_Type type, int unsign)
void M_ti_double (M_Type type, int unsign)
void M_ti_pointer (M_Type type)
int M_ti_eval_type (M_Type type, M_Type ntype)
int M_ti_eval_type2 (M_Type type, M_Type ntype)
int M_ti_call_type (M_Type type, M_Type ntype)
int M_ti_call_type2 (M_Type type, M_Type ntype)
void M_ti_array_layout (M_Type type, int *offset)
int M_ti_array_align (M_Type type)
int M_ti_array_size (M_Type type, int dim)
void M_ti_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_ti_union_align (int n, _M_Type *type)
int M_ti_union_size (int n, _M_Type *type)
void M_ti_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_ti_struct_align (int n, _M_Type *type)
int M_ti_struct_size (int n, _M_Type *type, int struct_align)
int M_ti_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_ti_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_ti_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_ti_no_short_int (void)
int M_ti_layout_order (void)
void M_ti_cb_label_name (char *fn, int cb, char *line, int len)
int M_ti_is_cb_label (char *label, char *fn, int *cb)
void M_ti_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_ti_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_ti_structure_pointer (int purpose)
int M_ti_return_register (int type, int purpose)
char * M_ti_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_ti_fn_name_from_label (char *label)
void M_set_model_ti (char *model_name)
int M_ti_fragile_macro (int macro_value)
int M_ti_subroutine_call (int opc)
void M_define_macros_ti (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_ti (int id)
void M_define_opcode_name_ti (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_ti (int id)
int M_oper_supported_in_arch_ti (int opc)
int M_num_oper_required_for_ti (L_Oper *oper, char *name)
int M_is_stack_operand_ti (L_Operand *operand)
int M_is_unsafe_macro_ti (L_Operand *operand)
int M_operand_type_ti (L_Operand *operand)
int M_conflicting_operands_ti (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_ti (int ctype)
Define Documentation
#define FIELD_16(a) ((((a) >= -INT_2EXP15)&&((a) < INT_2EXP15))?1:0)
Definition at line 90 of file m_ti.h.
Referenced by M_operand_type_ti().
#define FIELD_24(a) ((((a) >= -INT_2EXP23)&&((a) < INT_2EXP23))?1:0)
Definition at line 91 of file m_ti.h.
#define INT_2EXP15 0x8000
Definition at line 87 of file m_ti.h.
#define INT_2EXP23 0x800000
Definition at line 88 of file m_ti.h.
#define LTIop_ALU_DIRECT 1000
Definition at line 142 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_ALU_INDIRECT 1001
Definition at line 143 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_ALU_INDIRECT_INDIRECT 1052
Definition at line 148 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_ALU_INDIRECT_REG 1051
Definition at line 147 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_ALU_REG_DIRECT 1053
Definition at line 149 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_ALU_REG_INDIRECT 1050
Definition at line 146 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BD 1151
Definition at line 153 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BR 1152
Definition at line 154 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BRD 1153
Definition at line 155 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BS 1150
Definition at line 152 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BU 1165
Definition at line 167 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_BUD 1166
Definition at line 168 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_CALL 1154
Definition at line 156 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_CALLU 1164
Definition at line 166 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_DB 1167
Definition at line 169 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_DBD 1168
Definition at line 170 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PAR_LOAD 1302
Definition at line 174 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PAR_ONE_OPERAND 1303
Definition at line 175 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PAR_STORE 1301
Definition at line 173 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PAR_TWO_OPERAND 1304
Definition at line 176 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_POP 1158
Definition at line 160 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_POPF 1159
Definition at line 161 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PUSH 1160
Definition at line 162 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_PUSHF 1161
Definition at line 163 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_REPEAT_BLOCK 1156
Definition at line 158 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_REPEAT_INSTRUCTION 1157
Definition at line 159 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_RETS 1155
Definition at line 157 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_SUBRF 1163
Definition at line 165 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define LTIop_SUBRI 1162
Definition at line 164 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_DIRECT `LTIop_ALU_DIRECT`
Definition at line 179 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_INDIRECT `LTIop_ALU_INDIRECT`
Definition at line 180 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_INDIRECT_INDIRECT `LTIop_ALU_INDIRECT_INDIRECT`
Definition at line 184 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_INDIRECT_REG `LTIop_ALU_INDIRECT_REG`
Definition at line 183 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_REG_DIRECT `LTIop_ALU_REG_DIRECT`
Definition at line 185 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_ALU_REG_INDIRECT `LTIop_ALU_REG_INDIRECT`
Definition at line 182 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BD `LTIop_BD`
Definition at line 188 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BR `LTIop_BR`
Definition at line 189 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BRD `LTIop_BRD`
Definition at line 190 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BS `LTIop_BS`
Definition at line 187 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BU `LTIop_BU`
Definition at line 202 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_BUD `LTIop_BUD`
Definition at line 203 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_CALL `LTIop_CALL`
Definition at line 191 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_CALLU `LTIop_CALLU`
Definition at line 201 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_DB `LTIop_DB`
Definition at line 204 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_DBD `LTIop_DBD`
Definition at line 205 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PAR_LOAD `LTIop_PAR_STI`
Definition at line 208 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PAR_ONE_OPERAND `LTIop_PAR_ADDF_SUBF`
Definition at line 209 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PAR_STORE `LTIop_PAR_STF`
Definition at line 207 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PAR_TWO_OPERAND `LTIop_PAR_ADDI_SUBI`
Definition at line 210 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_POP `LTIop_POP`
Definition at line 195 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_POPF `LTIop_POPF`
Definition at line 196 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PUSH `LTIop_PUSH`
Definition at line 197 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_PUSHF `LTIop_PUSHF`
Definition at line 198 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_REPEAT_BLOCK `LTIop_REPEAT_BLOCK`
Definition at line 193 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_REPEAT_INSTRUCTION `LTIop_REPEAT_INSTRUCTION`
Definition at line 194 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_RETS `LTIop_RETS`
Definition at line 192 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_SUBRF `LTIop_SUBRF`
Definition at line 200 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
#define TIopcode_SUBRI `LTIop_SUBRI`
Definition at line 199 of file m_ti.h.
Referenced by M_define_opcode_name_ti(), and M_get_opcode_name_ti().
Enumeration Type Documentation
anonymous enum
Enumerator:
M_TI_1
Definition at line 96 of file m_ti.h.
anonymous enum
Enumerator:
TI_MAC_LEAF
TI_MAC_ALLOC
TI_MAC_CALLEE_I
TI_MAC_CALLEE_F
TI_MAC_TRUE_SP
TI_MAC_COMPUTATION_REG0
TI_MAC_COMPUTATION_REG1
TI_MAC_COMPUTATION_REG2
TI_MAC_COMPUTATION_REG3
TI_MAC_COMPUTATION_REG4
TI_MAC_COMPUTATION_REG5
TI_MAC_COMPUTATION_REG6
TI_MAC_COMPUTATION_REG7
TI_MAC_AUXILIARY_REG0
TI_MAC_AUXILIARY_REG1
TI_MAC_AUXILIARY_REG2
TI_MAC_AUXILIARY_REG3
TI_MAC_AUXILIARY_REG4
TI_MAC_AUXILIARY_REG5
TI_MAC_AUXILIARY_REG6
TI_MAC_AUXILIARY_REG7
TI_MAC_ST
TI_MAC_BK
TI_MAC_INDEX_REG0
TI_MAC_INDEX_REG1
TI_MAC_FP
TI_MAC_DP
TI_MAC_RS
TI_MAC_RE
TI_MAC_RC
Definition at line 101 of file m_ti.h.
Function Documentation
int M_conflicting_operands_ti (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1560 of file ml_ti.c.
References M_assert(), TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, and TI_MAC_TRUE_SP.
Referenced by M_dep_conflicting_operands().
void M_define_macros_ti (STRING_Symbol_Table * sym_tbl)
Definition at line 1106 of file ml_ti.c.
References M_add_symbol, TI_MAC_ALLOC, TI_MAC_AUXILIARY_REG7, TI_MAC_BK, TI_MAC_CALLEE_F, TI_MAC_CALLEE_I, TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, TI_MAC_DP, TI_MAC_INDEX_REG0, TI_MAC_INDEX_REG1, TI_MAC_LEAF, TI_MAC_RC, TI_MAC_RE, TI_MAC_RS, TI_MAC_ST, and TI_MAC_TRUE_SP.
Referenced by M_define_macros().
void M_define_opcode_name_ti (STRING_Symbol_Table * sym_tbl)
Definition at line 1192 of file ml_ti.c.
References LTIop_ALU_DIRECT, LTIop_ALU_INDIRECT, LTIop_ALU_INDIRECT_INDIRECT, LTIop_ALU_INDIRECT_REG, LTIop_ALU_REG_DIRECT, LTIop_ALU_REG_INDIRECT, LTIop_BD, LTIop_BR, LTIop_BRD, LTIop_BS, LTIop_BU, LTIop_BUD, LTIop_CALL, LTIop_CALLU, LTIop_DB, LTIop_DBD, LTIop_PAR_LOAD, LTIop_PAR_ONE_OPERAND, LTIop_PAR_STORE, LTIop_PAR_TWO_OPERAND, LTIop_POP, LTIop_POPF, LTIop_PUSH, LTIop_PUSHF, LTIop_REPEAT_BLOCK, LTIop_REPEAT_INSTRUCTION, LTIop_RETS, LTIop_SUBRF, LTIop_SUBRI, M_add_symbol, TIopcode_ALU_DIRECT, TIopcode_ALU_INDIRECT, TIopcode_ALU_INDIRECT_INDIRECT, TIopcode_ALU_INDIRECT_REG, TIopcode_ALU_REG_DIRECT, TIopcode_ALU_REG_INDIRECT, TIopcode_BD, TIopcode_BR, TIopcode_BRD, TIopcode_BS, TIopcode_BU, TIopcode_BUD, TIopcode_CALL, TIopcode_CALLU, TIopcode_DB, TIopcode_DBD, TIopcode_PAR_LOAD, TIopcode_PAR_ONE_OPERAND, TIopcode_PAR_STORE, TIopcode_PAR_TWO_OPERAND, TIopcode_POP, TIopcode_POPF, TIopcode_PUSH, TIopcode_PUSHF, TIopcode_REPEAT_BLOCK, TIopcode_REPEAT_INSTRUCTION, TIopcode_RETS, TIopcode_SUBRF, and TIopcode_SUBRI.
Referenced by M_define_opcode_name().
char* M_get_macro_name_ti (int id)
Definition at line 1141 of file ml_ti.c.
References TI_MAC_ALLOC, TI_MAC_AUXILIARY_REG7, TI_MAC_BK, TI_MAC_CALLEE_F, TI_MAC_CALLEE_I, TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, TI_MAC_DP, TI_MAC_INDEX_REG0, TI_MAC_INDEX_REG1, TI_MAC_LEAF, TI_MAC_RC, TI_MAC_RE, TI_MAC_RS, TI_MAC_ST, and TI_MAC_TRUE_SP.
Referenced by M_get_macro_name().
char* M_get_opcode_name_ti (int id)
Definition at line 1232 of file ml_ti.c.
References LTIop_ALU_DIRECT, LTIop_ALU_INDIRECT, LTIop_ALU_INDIRECT_INDIRECT, LTIop_ALU_INDIRECT_REG, LTIop_ALU_REG_DIRECT, LTIop_ALU_REG_INDIRECT, LTIop_BD, LTIop_BR, LTIop_BRD, LTIop_BS, LTIop_BU, LTIop_BUD, LTIop_CALL, LTIop_CALLU, LTIop_DB, LTIop_DBD, LTIop_PAR_LOAD, LTIop_PAR_ONE_OPERAND, LTIop_PAR_STORE, LTIop_PAR_TWO_OPERAND, LTIop_POP, LTIop_POPF, LTIop_PUSH, LTIop_PUSHF, LTIop_REPEAT_BLOCK, LTIop_REPEAT_INSTRUCTION, LTIop_RETS, LTIop_SUBRF, LTIop_SUBRI, TIopcode_ALU_DIRECT, TIopcode_ALU_INDIRECT, TIopcode_ALU_INDIRECT_INDIRECT, TIopcode_ALU_INDIRECT_REG, TIopcode_ALU_REG_DIRECT, TIopcode_ALU_REG_INDIRECT, TIopcode_BD, TIopcode_BR, TIopcode_BRD, TIopcode_BS, TIopcode_BU, TIopcode_BUD, TIopcode_CALL, TIopcode_CALLU, TIopcode_DB, TIopcode_DBD, TIopcode_PAR_LOAD, TIopcode_PAR_ONE_OPERAND, TIopcode_PAR_STORE, TIopcode_PAR_TWO_OPERAND, TIopcode_POP, TIopcode_POPF, TIopcode_PUSH, TIopcode_PUSHF, TIopcode_REPEAT_BLOCK, TIopcode_REPEAT_INSTRUCTION, TIopcode_RETS, TIopcode_SUBRF, and TIopcode_SUBRI.
Referenced by M_get_opcode_name().
int M_is_stack_operand_ti (L_Operand * operand)
Definition at line 1487 of file ml_ti.c.
References TI_MAC_TRUE_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_ti (L_Operand * operand)
Definition at line 1503 of file ml_ti.c.
References TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, and TI_MAC_ST.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_ti (L_Oper * oper, char * name)
Definition at line 1347 of file ml_ti.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_ti (int ctype)
Definition at line 1632 of file ml_ti.c.
References M_assert(), M_model, and M_TI_1.
Referenced by M_num_registers().
int M_oper_supported_in_arch_ti (int opc)
Definition at line 1310 of file ml_ti.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_ti (L_Operand * operand)
Definition at line 1528 of file ml_ti.c.
References FIELD_16, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit16, MDES_OPERAND_Lit24, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
void M_set_model_ti (char * model_name)
Definition at line 227 of file mi_ti.c.
References M_assert(), M_model, M_TI_1, and use_standard_function_call_model.
Referenced by M_set_machine().
int M_ti_array_align (M_Type type)
Definition at line 411 of file ml_ti.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_ti_array_layout (M_Type type, int * offset)
Definition at line 405 of file ml_ti.c.
Referenced by M_array_layout().
int M_ti_array_size (M_Type type, int dim)
Definition at line 417 of file ml_ti.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_ti_bit_char (M_Type type, int n)
Definition at line 190 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_ti_bit_int (M_Type type, int n)
Definition at line 166 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_ti_bit_long (M_Type type, int n)
Definition at line 154 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_ti_bit_short (M_Type type, int n)
Definition at line 178 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_ti_call_type (M_Type type, M_Type ntype)
Definition at line 312 of file ml_ti.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_ti_call_type2 (M_Type type, M_Type ntype)
Definition at line 354 of file ml_ti.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_ti_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 961 of file ml_ti.c.
Referenced by M_cb_label_name().
void M_ti_char (M_Type type, int unsign)
Definition at line 179 of file mi_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_CHAR, M_TI_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char().
void M_ti_double (M_Type type, int unsign)
Definition at line 215 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_DOUBLE, M_TI_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_ti_eval_type (M_Type type, M_Type ntype)
Definition at line 236 of file ml_ti.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_ti_eval_type2 (M_Type type, M_Type ntype)
Definition at line 270 of file ml_ti.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_ti_float (M_Type type, int unsign)
Definition at line 205 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_FLOAT, M_TI_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_ti_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1035 of file ml_ti.c.
char* M_ti_fn_name_from_label (char * label)
Definition at line 1049 of file ml_ti.c.
int M_ti_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 663 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TI_ALIGN_INT, M_TI_ALIGN_MAX, M_TI_FLT_BASE, M_TI_INT_BASE, M_TI_MAX_FNVAR_REG, M_TI_NUM_INT_PARM_REGS, M_TI_SIZE_INT, M_TI_SMALL_STRUCT_MAX, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, _struct_M_Type::size, and use_standard_function_call_model.
Referenced by M_fnvar_layout(), and M_ti_layout_fnvar().
int M_ti_fragile_macro (int macro_value)
Definition at line 1059 of file ml_ti.c.
References M_assert(), M_model, M_TI_1, and TI_MAC_ST.
Referenced by M_fragile_macro().
void M_ti_int (M_Type type, int unsign)
Definition at line 199 of file mi_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_INT, M_TI_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int().
int M_ti_is_cb_label (char * label, char * fn, int * cb)
Definition at line 967 of file ml_ti.c.
Referenced by M_is_cb_label().
int M_ti_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 980 of file ml_ti.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_ti_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 973 of file ml_ti.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_ti_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 610 of file ml_ti.c.
References List_next(), List_size(), List_start(), M_ti_fnvar_layout(), mode, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_ti_layout_order (void)
Definition at line 220 of file mi_ti.c.
References M_BIG_ENDIAN.
Referenced by M_layout_order().
void M_ti_long (M_Type type, int unsign)
Definition at line 209 of file mi_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_LONG, M_TI_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long().
int M_ti_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 913 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_ti_no_short_int (void)
Definition at line 955 of file ml_ti.c.
References M_TI_SIZE_INT, and M_TI_SIZE_SHORT.
Referenced by M_no_short_int().
void M_ti_pointer (M_Type type)
Definition at line 225 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_POINTER, M_TI_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_ti_return_register (int type, int purpose)
Definition at line 1014 of file ml_ti.c.
References M_TI_RET_F, M_TI_RET_I32, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
Referenced by M_return_register().
void M_ti_short (M_Type type, int unsign)
Definition at line 189 of file mi_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_SHORT, M_TI_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short().
int M_ti_struct_align (int n, _M_Type * type)
Definition at line 546 of file ml_ti.c.
References M_TI_ALIGN_CHAR.
Referenced by M_struct_align().
void M_ti_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 497 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_layout().
int M_ti_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 565 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_CHAR, M_TI_SIZE_INT, M_TYPE_BIT_CHAR, and M_TYPE_BIT_LONG.
Referenced by M_struct_size().
int M_ti_structure_pointer (int purpose)
Definition at line 1008 of file ml_ti.c.
References M_TI_RET_ST.
Referenced by M_structure_pointer().
int M_ti_subroutine_call (int opc)
Definition at line 1087 of file ml_ti.c.
References M_assert(), M_model, and M_TI_1.
Referenced by M_subroutine_call().
int M_ti_type_align (int mtype)
Definition at line 143 of file mi_ti.c.
References M_TI_ALIGN_BIT, M_TI_ALIGN_BLOCK, M_TI_ALIGN_CHAR, M_TI_ALIGN_DOUBLE, M_TI_ALIGN_FLOAT, M_TI_ALIGN_INT, M_TI_ALIGN_LONG, M_TI_ALIGN_POINTER, M_TI_ALIGN_SHORT, M_TI_ALIGN_STRUCT, M_TI_ALIGN_UNION, M_TI_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_ti_type_size (int mtype)
Definition at line 107 of file mi_ti.c.
References M_TI_SIZE_BIT, M_TI_SIZE_BLOCK, M_TI_SIZE_CHAR, M_TI_SIZE_DOUBLE, M_TI_SIZE_FLOAT, M_TI_SIZE_INT, M_TI_SIZE_LONG, M_TI_SIZE_POINTER, M_TI_SIZE_SHORT, M_TI_SIZE_STRUCT, M_TI_SIZE_UNION, M_TI_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_ti_union_align (int n, _M_Type * type)
Definition at line 443 of file ml_ti.c.
References M_TI_ALIGN_CHAR.
Referenced by M_union_align().
void M_ti_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 432 of file ml_ti.c.
Referenced by M_union_layout().
int M_ti_union_size (int n, _M_Type * type)
Definition at line 463 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_ti_void (M_Type type)
Definition at line 144 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_VOID, M_TI_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().