mi_spec.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <machine/m_spec.h>
#include <machine/m_hppa.h>
#include <machine/m_impact.h>
#include <machine/m_hpl_pd.h>
#include <machine/m_sparc.h>
#include <machine/m_x86.h>
#include <machine/m_ti.h>
#include <machine/m_sh.h>
#include <machine/m_bx86.h>
#include <machine/m_tahoe.h>
#include <machine/m_starcore.h>
#include <machine/m_arm.h>
#include <machine/m_wims.h>
#include <library/md.h>
Defines
#define MD_DEBUG_MACROS
Functions
void M_read_parm (Parm_Parse_Info *ppi)
void M_assert (int cc, char *mesg)
void M_set_machine (char *arch, char *model, char *swarch)
void M_char (M_Type type, int unsign)
void M_short (M_Type type, int unsign)
void M_int (M_Type type, int unsign)
void M_long (M_Type type, int unsign)
void M_llong (M_Type type, int unsign)
int M_type_size (int mtype)
int M_type_align (int mtype)
int M_layout_order (void)
char * M_layout_database_desc ()
int M_read_database_i (char *section_name, char *entry_name, char *field_name)
char * M_read_database_s (char *section_name, char *entry_name, char *field_name)
int M_database_info_present (char *section_name, char *entry_name, char *field_name)
int M_supports_long_long (void)
int M_pointer_size (void)
Variables
int M_arch = 0
int M_model = 0
int M_swarch = 0
int Mspec_num_int_caller_reg = 0
int Mspec_num_int_callee_reg = 0
int Mspec_num_flt_caller_reg = 0
int Mspec_num_flt_callee_reg = 0
int Mspec_num_dbl_caller_reg = 0
int Mspec_num_dbl_callee_reg = 0
int Mspec_num_prd_caller_reg = 0
int Mspec_num_prd_callee_reg = 0
int M_use_layout_database = 0
char * M_layout_database_name = `./host_layout_info.md`
static MD * M_layout_database = NULL
Define Documentation
#define MD_DEBUG_MACROS
Definition at line 80 of file mi_spec.c.
Function Documentation
void M_assert (int cc, char * mesg)
Definition at line 128 of file mi_spec.c.
References I_punt().
Referenced by M_arm_bit_char(), M_arm_bit_int(), M_arm_bit_llong(), M_arm_bit_long(), M_arm_bit_short(), M_arm_fnvar_layout(), M_arm_fragile_macro(), M_arm_layout_fnvar(), M_arm_lvar_layout(), M_arm_struct_layout(), M_arm_struct_size(), M_arm_subroutine_call(), M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_block(), M_bx86_bit_char(), M_bx86_bit_int(), M_bx86_bit_long(), M_bx86_bit_short(), M_bx86_fnvar_layout(), M_bx86_fragile_macro(), M_bx86_lvar_layout(), M_bx86_struct_layout(), M_bx86_struct_size(), M_bx86_subroutine_call(), M_call_type(), M_call_type2(), M_cb_label_name(), M_char(), M_conflicting_operands_arm(), M_conflicting_operands_bx86(), M_conflicting_operands_hppa(), M_conflicting_operands_impact(), M_conflicting_operands_impact_hp_lcode(), M_conflicting_operands_impact_lcode(), M_conflicting_operands_impact_sparc_lcode(), M_conflicting_operands_playdoh(), M_conflicting_operands_sh(), M_conflicting_operands_sparc(), M_conflicting_operands_starcore(), M_conflicting_operands_tahoe(), M_conflicting_operands_ti(), M_conflicting_operands_wims(), M_dataflow_macro(), M_define_macros(), M_define_macros_impact(), M_define_macros_playdoh(), M_define_macros_starcore(), M_define_macros_tahoe(), M_define_opcode_name(), M_dep_conflicting_operands(), M_double(), M_eval_type(), M_eval_type2(), M_extra_pred_define_opcode(), M_extra_pred_define_type1(), M_extra_pred_define_type2(), M_float(), M_fn_label_name(), M_fn_name_from_label(), M_fnvar_layout(), M_fragile_macro(), M_fragile_macro_set(), M_get_data_type(), M_get_data_type_bx86(), M_get_data_type_x86(), M_get_macro_name(), M_get_macro_name_impact(), M_get_macro_name_playdoh(), M_get_macro_name_starcore(), M_get_macro_name_tahoe(), M_get_opcode_name(), M_hppa_bit_char(), M_hppa_bit_int(), M_hppa_bit_long(), M_hppa_bit_short(), M_hppa_dataflow_macro(), M_hppa_fnvar_layout(), M_hppa_fragile_macro(), M_hppa_fragile_macro_set(), M_hppa_lvar_layout(), M_hppa_struct_layout(), M_hppa_struct_size(), M_hppa_subroutine_call(), M_impact_array_align(), M_impact_array_layout(), M_impact_array_size(), M_impact_bit_char(), M_impact_bit_int(), M_impact_bit_long(), M_impact_bit_short(), M_impact_call_type(), M_impact_call_type2(), M_impact_cb_label_name(), M_impact_char(), M_impact_dataflow_macro(), M_impact_double(), M_impact_eval_type(), M_impact_eval_type2(), M_impact_float(), M_impact_fnvar_layout(), M_impact_fragile_macro(), M_impact_fragile_macro_set(), M_impact_int(), M_impact_is_cb_label(), M_impact_is_jumptbl_label(), M_impact_jumptbl_label_name(), M_impact_layout_fnvar(), M_impact_layout_order(), M_impact_long(), M_impact_lvar_layout(), M_impact_no_short_int(), M_impact_pointer(), M_impact_return_register(), M_impact_short(), M_impact_struct_align(), M_impact_struct_layout(), M_impact_struct_size(), M_impact_structure_pointer(), M_impact_subroutine_call(), M_impact_type_align(), M_impact_type_size(), M_impact_union_align(), M_impact_union_layout(), M_impact_union_size(), M_impact_void(), M_int(), M_is_cb_label(), M_is_jumptbl_label(), M_is_stack_operand(), M_is_stack_operand_impact(), M_is_stack_operand_playdoh(), M_is_stack_operand_starcore(), M_is_stack_operand_tahoe(), M_is_unsafe_macro(), M_is_unsafe_macro_impact(), M_is_unsafe_macro_playdoh(), M_is_unsafe_macro_starcore(), M_is_unsafe_macro_tahoe(), M_jumptbl_label_name(), M_layout_fnvar(), M_layout_order(), M_layout_retvar(), M_llong(), M_long(), M_lvar_layout(), M_mdes_operand_type(), M_memory_access_size(), M_memory_access_size_x86(), M_native_int_register_ctype(), M_native_int_register_mtype(), M_no_short_int(), M_num_oper_required_for(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_starcore(), M_num_oper_required_for_tahoe(), M_num_registers(), M_num_registers_arm(), M_num_registers_hppa(), M_num_registers_sh(), M_num_registers_sparc(), M_num_registers_ti(), M_num_registers_wims(), M_opc_from_proc_opc(), M_opc_from_proc_opc_playdoh(), M_opc_from_proc_opc_starcore(), M_opc_from_proc_opc_tahoe(), M_oper_supported_in_arch(), M_oper_supported_in_arch_impact(), M_oper_supported_in_arch_playdoh(), M_oper_supported_in_arch_starcore(), M_oper_supported_in_arch_tahoe(), M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact(), M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), M_operand_type_impact_sparc_lcode(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), M_operand_type_ti(), M_operand_type_wims(), M_operand_type_x86(), M_playdoh_array_align(), M_playdoh_array_layout(), M_playdoh_array_size(), M_playdoh_bit_char(), M_playdoh_bit_int(), M_playdoh_bit_llong(), M_playdoh_bit_long(), M_playdoh_bit_short(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_cb_label_name(), M_playdoh_char(), M_playdoh_dataflow_macro(), M_playdoh_double(), M_playdoh_eval_type(), M_playdoh_eval_type2(), M_playdoh_float(), M_playdoh_fn_label_name(), M_playdoh_fn_name_from_label(), M_playdoh_fnvar_layout(), M_playdoh_fragile_macro(), M_playdoh_fragile_macro_set(), M_playdoh_int(), M_playdoh_is_cb_label(), M_playdoh_is_jumptbl_label(), M_playdoh_jumptbl_label_name(), M_playdoh_layout_fnvar(), M_playdoh_layout_order(), M_playdoh_long(), M_playdoh_lvar_layout(), M_playdoh_no_short_int(), M_playdoh_pointer(), M_playdoh_return_register(), M_playdoh_short(), M_playdoh_struct_align(), M_playdoh_struct_layout(), M_playdoh_struct_size(), M_playdoh_structure_pointer(), M_playdoh_subroutine_call(), M_playdoh_type_align(), M_playdoh_type_size(), M_playdoh_union_align(), M_playdoh_union_layout(), M_playdoh_union_size(), M_playdoh_void(), M_pointer(), M_return_epilogue_cntr_register(), M_return_loop_cntr_register(), M_return_register(), M_return_value_offset(), M_return_value_thru_stack(), M_set_machine(), M_set_model_arm(), M_set_model_bx86(), M_set_model_hppa(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_sh(), M_set_model_sparc(), M_set_model_starcore(), M_set_model_tahoe(), M_set_model_ti(), M_set_model_wims(), M_set_model_x86(), M_set_swarch_tahoe(), M_sh_bit_char(), M_sh_bit_int(), M_sh_bit_long(), M_sh_bit_short(), M_sh_dataflow_macro(), M_sh_fnvar_layout(), M_sh_fragile_macro(), M_sh_fragile_macro_set(), M_sh_lvar_layout(), M_sh_struct_layout(), M_sh_struct_size(), M_sh_subroutine_call(), M_short(), M_sparc_bit_char(), M_sparc_bit_int(), M_sparc_bit_long(), M_sparc_bit_short(), M_sparc_dataflow_macro(), M_sparc_fnvar_layout(), M_sparc_fragile_macro(), M_sparc_fragile_macro_set(), M_sparc_lvar_layout(), M_sparc_struct_layout(), M_sparc_struct_size(), M_sparc_subroutine_call(), M_starcore_array_align(), M_starcore_array_layout(), M_starcore_array_size(), M_starcore_bit_char(), M_starcore_bit_int(), M_starcore_bit_long(), M_starcore_bit_short(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_cb_label_name(), M_starcore_char(), M_starcore_dataflow_macro(), M_starcore_double(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_float(), M_starcore_fn_label_name(), M_starcore_fn_name_from_label(), M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_starcore_fragile_macro(), M_starcore_int(), M_starcore_is_cb_label(), M_starcore_is_jumptbl_label(), M_starcore_jumptbl_label_name(), M_starcore_layout_order(), M_starcore_long(), M_starcore_lvar_layout(), M_starcore_no_short_int(), M_starcore_pointer(), M_starcore_return_register(), M_starcore_short(), M_starcore_struct_align(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_structure_pointer(), M_starcore_subroutine_call(), M_starcore_type_align(), M_starcore_type_size(), M_starcore_union_align(), M_starcore_union_layout(), M_starcore_union_size(), M_starcore_void(), M_struct(), M_struct_align(), M_struct_layout(), M_struct_size(), M_structure_pointer(), M_subroutine_call(), M_tahoe_bit_char(), M_tahoe_bit_int(), M_tahoe_bit_llong(), M_tahoe_bit_long(), M_tahoe_bit_short(), M_tahoe_dataflow_macro(), M_tahoe_fnvar_layout(), M_tahoe_fnvar_to_lvar(), M_tahoe_fragile_macro(), M_tahoe_layout_fnvar(), M_tahoe_layout_order(), M_tahoe_layout_retvar(), M_tahoe_lvar_layout(), M_tahoe_struct_layout(), M_tahoe_struct_size(), M_tahoe_subroutine_call(), M_ti_bit_int(), M_ti_bit_long(), M_ti_bit_short(), M_ti_fnvar_layout(), M_ti_fragile_macro(), M_ti_lvar_layout(), M_ti_struct_layout(), M_ti_struct_size(), M_ti_subroutine_call(), M_type_align(), M_type_size(), M_union(), M_union_align(), M_union_layout(), M_union_size(), M_void(), M_wims_bit_char(), M_wims_bit_int(), M_wims_bit_llong(), M_wims_bit_long(), M_wims_bit_short(), M_wims_double(), M_wims_float(), M_wims_fnvar_layout(), M_wims_fragile_macro(), M_wims_layout_fnvar(), M_wims_lvar_layout(), M_wims_return_register(), M_wims_struct_layout(), M_wims_struct_size(), M_wims_subroutine_call(), M_x86_bit_char(), M_x86_bit_int(), M_x86_bit_long(), M_x86_bit_short(), M_x86_fnvar_layout(), M_x86_fragile_macro(), M_x86_lvar_layout(), M_x86_struct_layout(), M_x86_struct_size(), and M_x86_subroutine_call().
void M_char (M_Type type, int unsign)
Definition at line 221 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_char(), M_assert(), M_BX86, M_bx86_char(), M_HPPA, M_hppa_char(), M_IMPACT, M_impact_char(), M_PLAYDOH, M_playdoh_char(), M_read_database_i(), M_SH, M_sh_char(), M_SPARC, M_sparc_char(), M_STARCORE, M_starcore_char(), M_TAHOE, M_tahoe_char(), M_TI, M_ti_char(), M_TYPE_CHAR, M_use_layout_database, M_WIMS, M_wims_char(), M_X86, M_x86_char(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_database_info_present (char * section_name, char * entry_name, char * field_name)
Definition at line 917 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_read_md(), and NULL.
void M_int (M_Type type, int unsign)
Definition at line 341 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_int(), M_assert(), M_BX86, M_bx86_int(), M_HPPA, M_hppa_int(), M_IMPACT, M_impact_int(), M_PLAYDOH, M_playdoh_int(), M_read_database_i(), M_SH, M_sh_int(), M_SPARC, M_sparc_int(), M_STARCORE, M_starcore_int(), M_TAHOE, M_tahoe_int(), M_TI, M_ti_int(), M_TYPE_INT, M_use_layout_database, M_WIMS, M_wims_int(), M_X86, M_x86_int(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
char* M_layout_database_desc ()
Definition at line 695 of file mi_spec.c.
References entry, M_layout_database, MD_find_section, MD_first_entry(), and NULL.
Referenced by M_read_database_i(), M_read_database_s(), and M_struct_layout().
int M_layout_order (void)
Definition at line 656 of file mi_spec.c.
References M_arch, M_ARM, M_arm_layout_order(), M_assert(), M_BX86, M_bx86_layout_order(), M_HPPA, M_hppa_layout_order(), M_IMPACT, M_impact_layout_order(), M_PLAYDOH, M_playdoh_layout_order(), M_SH, M_sh_layout_order(), M_SPARC, M_sparc_layout_order(), M_STARCORE, M_starcore_layout_order(), M_TAHOE, M_tahoe_layout_order(), M_TI, M_ti_layout_order(), M_WIMS, M_wims_layout_order(), M_X86, and M_x86_layout_order().
void M_llong (M_Type type, int unsign)
Definition at line 461 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_llong(), M_assert(), M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_playdoh_llong(), M_read_database_i(), M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_tahoe_llong(), M_TI, M_TYPE_LLONG, M_use_layout_database, M_WIMS, M_wims_llong(), M_X86, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type(), M_call_type2(), M_eval_type(), and M_eval_type2().
void M_long (M_Type type, int unsign)
Definition at line 401 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_long(), M_assert(), M_BX86, M_bx86_long(), M_HPPA, M_hppa_long(), M_IMPACT, M_impact_long(), M_PLAYDOH, M_playdoh_long(), M_read_database_i(), M_SH, M_sh_long(), M_SPARC, M_sparc_long(), M_STARCORE, M_starcore_long(), M_TAHOE, M_tahoe_long(), M_TI, M_ti_long(), M_TYPE_LONG, M_use_layout_database, M_WIMS, M_wims_long(), M_X86, M_x86_long(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_pointer_size (void)
Definition at line 1004 of file mi_spec.c.
References M_arch, and M_TAHOE.
int M_read_database_i (char * section_name, char * entry_name, char * field_name)
Definition at line 723 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_desc(), M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_int, MD_read_md(), and NULL.
Referenced by M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_char(), M_double(), M_float(), M_impact_layout_order(), M_int(), M_llong(), M_long(), M_no_short_int(), M_playdoh_layout_order(), M_pointer(), M_short(), M_starcore_fnvar_layout(), M_struct_align(), M_struct_layout(), M_struct_size(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), and M_union_size().
char* M_read_database_s (char * section_name, char * entry_name, char * field_name)
Definition at line 820 of file mi_spec.c.
References entry, I_punt(), M_layout_database, M_layout_database_desc(), M_layout_database_name, MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_string, MD_read_md(), and NULL.
void M_read_parm (Parm_Parse_Info * ppi)
Definition at line 100 of file mi_spec.c.
References L_read_parm_i(), L_read_parm_s(), M_layout_database_name, Mspec_num_dbl_callee_reg, Mspec_num_dbl_caller_reg, Mspec_num_flt_callee_reg, Mspec_num_flt_caller_reg, Mspec_num_int_callee_reg, Mspec_num_int_caller_reg, Mspec_num_prd_callee_reg, and Mspec_num_prd_caller_reg.
void M_set_machine (char * arch, char * model, char * swarch)
Definition at line 137 of file mi_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_set_model_arm(), M_set_model_bx86(), M_set_model_hppa(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_sh(), M_set_model_sparc(), M_set_model_starcore(), M_set_model_tahoe(), M_set_model_ti(), M_set_model_wims(), M_set_model_x86(), M_set_swarch_tahoe(), M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_short (M_Type type, int unsign)
Definition at line 281 of file mi_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_short(), M_assert(), M_BX86, M_bx86_short(), M_HPPA, M_hppa_short(), M_IMPACT, M_impact_short(), M_PLAYDOH, M_playdoh_short(), M_read_database_i(), M_SH, M_sh_short(), M_SPARC, M_sparc_short(), M_STARCORE, M_starcore_short(), M_TAHOE, M_tahoe_short(), M_TI, M_ti_short(), M_TYPE_SHORT, M_use_layout_database, M_WIMS, M_wims_short(), M_X86, M_x86_short(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
int M_supports_long_long (void)
Definition at line 989 of file mi_spec.c.
References M_arch, M_ARM, M_PLAYDOH, M_TAHOE, and M_WIMS.
int M_type_align (int mtype)
Definition at line 581 of file mi_spec.c.
References M_arch, M_ARM, M_arm_type_align(), M_assert(), M_HPPA, M_hppa_type_align(), M_IMPACT, M_impact_type_align(), M_PLAYDOH, M_playdoh_type_align(), M_read_database_i(), M_SH, M_sh_type_align(), M_SPARC, M_sparc_type_align(), M_STARCORE, M_starcore_type_align(), M_TAHOE, M_tahoe_type_align(), M_TI, M_ti_type_align(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_type_align(), M_X86, and M_x86_type_align().
int M_type_size (int mtype)
Definition at line 506 of file mi_spec.c.
References M_arch, M_ARM, M_arm_type_size(), M_assert(), M_HPPA, M_hppa_type_size(), M_IMPACT, M_impact_type_size(), M_PLAYDOH, M_playdoh_type_size(), M_read_database_i(), M_SH, M_sh_type_size(), M_SPARC, M_sparc_type_size(), M_STARCORE, M_starcore_type_size(), M_TAHOE, M_tahoe_type_size(), M_TI, M_ti_type_size(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_type_size(), M_X86, and M_x86_type_size().
Referenced by M_memory_access_size_x86().
Variable Documentation
int M_arch = 0
Definition at line 86 of file mi_spec.c.
MD* M_layout_database = NULL [static]
Definition at line 125 of file mi_spec.c.
Referenced by M_database_info_present(), M_layout_database_desc(), M_read_database_i(), and M_read_database_s().
char* M_layout_database_name = `./host_layout_info.md`
Definition at line 122 of file mi_spec.c.
Referenced by M_database_info_present(), M_read_database_i(), M_read_database_s(), M_read_parm(), and M_struct_layout().
int M_model = 0
Definition at line 87 of file mi_spec.c.
int M_swarch = 0
Definition at line 88 of file mi_spec.c.
Referenced by M_set_swarch_tahoe(), and M_tahoe_layout_order().
int M_use_layout_database = 0
Definition at line 121 of file mi_spec.c.
Referenced by M_array_align(), M_array_layout(), M_array_size(), M_bit_char(), M_bit_int(), M_bit_llong(), M_bit_long(), M_bit_short(), M_call_type(), M_call_type2(), M_char(), M_double(), M_eval_type(), M_eval_type2(), M_float(), M_int(), M_llong(), M_long(), M_no_short_int(), M_pointer(), M_set_model_impact(), M_set_model_playdoh(), M_set_model_starcore(), M_set_model_tahoe(), M_short(), M_struct_align(), M_struct_layout(), M_struct_size(), M_type_align(), M_type_size(), M_union_align(), M_union_layout(), M_union_size(), and M_void().
int Mspec_num_dbl_callee_reg = 0
Definition at line 95 of file mi_spec.c.
Referenced by M_read_parm().
int Mspec_num_dbl_caller_reg = 0
Definition at line 94 of file mi_spec.c.
Referenced by M_read_parm().
int Mspec_num_flt_callee_reg = 0
Definition at line 93 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_flt_caller_reg = 0
Definition at line 92 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_int_callee_reg = 0
Definition at line 91 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_int_caller_reg = 0
Definition at line 90 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_prd_callee_reg = 0
Definition at line 97 of file mi_spec.c.
Referenced by M_conflicting_operands_impact_lcode(), M_conflicting_operands_playdoh(), and M_read_parm().
int Mspec_num_prd_caller_reg = 0
Definition at line 96 of file mi_spec.c.
Referenced by M_read_parm().