mi_tahoe.c File Reference
#include <config.h>
#include `m_spec.h`
#include `m_tahoe.h`
#include <library/i_error.h>
#include <library/i_list.h>
Defines
#define M_TAHOE_SIZE_VOID 0
#define M_TAHOE_SIZE_BIT 1
#define M_TAHOE_SIZE_CHAR 8
#define M_TAHOE_SIZE_SHORT 16
#define M_TAHOE_SIZE_INT 32
#define M_TAHOE_SIZE_LONG M_tahoe_size_long
#define M_TAHOE_SIZE_POINTER M_tahoe_size_pointer
#define M_TAHOE_SIZE_LLONG 64
#define M_TAHOE_SIZE_FLOAT 32
#define M_TAHOE_SIZE_DOUBLE 64
#define M_TAHOE_SIZE_MAX 64
#define M_TAHOE_ALIGN_VOID -1
#define M_TAHOE_ALIGN_BIT 1
#define M_TAHOE_ALIGN_CHAR 8
#define M_TAHOE_ALIGN_SHORT 16
#define M_TAHOE_ALIGN_INT 32
#define M_TAHOE_ALIGN_LONG M_tahoe_align_long
#define M_TAHOE_ALIGN_POINTER M_tahoe_align_pointer
#define M_TAHOE_ALIGN_LLONG 64
#define M_TAHOE_ALIGN_FLOAT 32
#define M_TAHOE_ALIGN_DOUBLE 64
#define M_TAHOE_ALIGN_MAX 64
Functions
int M_tahoe_type_size (int mtype)
int M_tahoe_type_align (int mtype)
void M_tahoe_void (M_Type type)
void M_tahoe_bit_llong (M_Type type, int n)
void M_tahoe_bit_long (M_Type type, int n)
void M_tahoe_bit_int (M_Type type, int n)
void M_tahoe_bit_short (M_Type type, int n)
void M_tahoe_bit_char (M_Type type, int n)
void M_tahoe_char (M_Type type, int unsign)
void M_tahoe_short (M_Type type, int unsign)
void M_tahoe_int (M_Type type, int unsign)
void M_tahoe_llong (M_Type type, int unsign)
void M_tahoe_long (M_Type type, int unsign)
void M_tahoe_float (M_Type type, int unsign)
void M_tahoe_double (M_Type type, int unsign)
void M_tahoe_pointer (M_Type type)
int M_tahoe_eval_type (M_Type type, M_Type ntype)
int M_tahoe_eval_type2 (M_Type type, M_Type ntype)
int M_tahoe_call_type (M_Type type, M_Type ntype)
int M_tahoe_call_type2 (M_Type type, M_Type ntype)
void M_tahoe_array_layout (M_Type type, int *offset)
int M_tahoe_array_align (M_Type type)
int M_tahoe_array_size (M_Type type, int dim)
void M_tahoe_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_tahoe_union_align (int n, _M_Type *type)
int M_tahoe_union_size (int n, _M_Type *type)
int M_tahoe_layout_order (void)
void M_tahoe_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_tahoe_struct_align (int n, _M_Type *type)
int M_tahoe_struct_size (int n, _M_Type *type, int struct_align)
int M_tahoe_no_short_int (void)
void M_tahoe_cb_label_name (char *fn, int cb, char *line, int len)
int M_tahoe_is_cb_label (char *label, char *fn, int *cb)
void M_tahoe_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_tahoe_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_tahoe_structure_pointer (int purpose)
int M_tahoe_return_register (int type, int purpose)
char * M_tahoe_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_tahoe_fn_name_from_label (char *label)
void M_set_model_tahoe (char *model_name)
void M_set_swarch_tahoe (char *model_name)
static int M_align_offset (int offset, int align_bit)
int M_tahoe_layout_fnvar (List param_list, char **macro, int *pcount, int purpose)
int M_tahoe_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_tahoe_layout_retvar (M_Param param, int purpose)
int M_tahoe_fnvar_to_lvar (_M_Type type, long int *offset, char **base_macro, int local_space)
int M_tahoe_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
Variables
int M_tahoe_size_long = 64
int M_tahoe_size_pointer = 64
int M_tahoe_align_long = 64
int M_tahoe_align_pointer = 64
Define Documentation
#define M_TAHOE_ALIGN_BIT 1
Definition at line 98 of file mi_tahoe.c.
Referenced by M_tahoe_bit_char(), M_tahoe_bit_int(), M_tahoe_bit_llong(), M_tahoe_bit_long(), M_tahoe_bit_short(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_CHAR 8
Definition at line 99 of file mi_tahoe.c.
Referenced by M_tahoe_char(), M_tahoe_struct_align(), M_tahoe_struct_size(), M_tahoe_type_align(), M_tahoe_union_align(), and M_tahoe_union_size().
#define M_TAHOE_ALIGN_DOUBLE 64
Definition at line 106 of file mi_tahoe.c.
Referenced by M_tahoe_double(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_FLOAT 32
Definition at line 105 of file mi_tahoe.c.
Referenced by M_tahoe_float(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_INT 32
Definition at line 101 of file mi_tahoe.c.
Referenced by M_tahoe_int(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_LLONG 64
Definition at line 104 of file mi_tahoe.c.
Referenced by M_tahoe_llong(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_LONG M_tahoe_align_long
Definition at line 102 of file mi_tahoe.c.
Referenced by M_tahoe_long(), M_tahoe_struct_size(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_MAX 64
Definition at line 107 of file mi_tahoe.c.
#define M_TAHOE_ALIGN_POINTER M_tahoe_align_pointer
Definition at line 103 of file mi_tahoe.c.
Referenced by M_tahoe_pointer(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_SHORT 16
Definition at line 100 of file mi_tahoe.c.
Referenced by M_tahoe_short(), M_tahoe_struct_size(), and M_tahoe_type_align().
#define M_TAHOE_ALIGN_VOID -1
Definition at line 97 of file mi_tahoe.c.
Referenced by M_tahoe_type_align(), and M_tahoe_void().
#define M_TAHOE_SIZE_BIT 1
Definition at line 86 of file mi_tahoe.c.
Referenced by M_tahoe_bit_char(), M_tahoe_bit_int(), M_tahoe_bit_llong(), M_tahoe_bit_long(), M_tahoe_bit_short(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_CHAR 8
Definition at line 87 of file mi_tahoe.c.
Referenced by M_tahoe_char(), M_tahoe_struct_layout(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_DOUBLE 64
Definition at line 94 of file mi_tahoe.c.
Referenced by M_tahoe_double(), M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_FLOAT 32
Definition at line 93 of file mi_tahoe.c.
Referenced by M_tahoe_float(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_INT 32
Definition at line 89 of file mi_tahoe.c.
Referenced by M_tahoe_int(), M_tahoe_no_short_int(), M_tahoe_struct_layout(), M_tahoe_struct_size(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_LLONG 64
Definition at line 92 of file mi_tahoe.c.
Referenced by M_tahoe_fnvar_layout(), M_tahoe_layout_fnvar(), M_tahoe_layout_retvar(), M_tahoe_llong(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_LONG M_tahoe_size_long
Definition at line 90 of file mi_tahoe.c.
Referenced by M_tahoe_eval_type(), M_tahoe_long(), M_tahoe_struct_layout(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_MAX 64
Definition at line 95 of file mi_tahoe.c.
#define M_TAHOE_SIZE_POINTER M_tahoe_size_pointer
Definition at line 91 of file mi_tahoe.c.
Referenced by M_tahoe_eval_type(), M_tahoe_pointer(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_SHORT 16
Definition at line 88 of file mi_tahoe.c.
Referenced by M_tahoe_no_short_int(), M_tahoe_short(), M_tahoe_struct_layout(), and M_tahoe_type_size().
#define M_TAHOE_SIZE_VOID 0
Definition at line 85 of file mi_tahoe.c.
Referenced by M_tahoe_type_size(), and M_tahoe_void().
Function Documentation
static int M_align_offset (int offset, int align_bit) [static]
Definition at line 1215 of file mi_tahoe.c.
References I_punt().
void M_set_model_tahoe (char * model_name)
Definition at line 1130 of file mi_tahoe.c.
References M_assert(), M_IPF_CHIVANO, M_IPF_DEERFIELD, M_IPF_ITANIUM, M_IPF_MADISON, M_IPF_MCKINLEY, M_IPF_MENDOCITO, M_model, and M_use_layout_database.
Referenced by M_set_machine().
void M_set_swarch_tahoe (char * model_name)
Definition at line 1168 of file mi_tahoe.c.
References M_assert(), M_IPF_HPUX_ILP32, M_IPF_HPUX_LP64, M_IPF_LIN_LP64, M_IPF_WIN_P64, M_swarch, M_tahoe_align_long, M_tahoe_align_pointer, M_tahoe_size_long, and M_tahoe_size_pointer.
Referenced by M_set_machine().
int M_tahoe_array_align (M_Type type)
Definition at line 554 of file mi_tahoe.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_tahoe_array_layout (M_Type type, int * offset)
Definition at line 546 of file mi_tahoe.c.
Referenced by M_array_layout().
int M_tahoe_array_size (M_Type type, int dim)
Definition at line 561 of file mi_tahoe.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_tahoe_bit_char (M_Type type, int n)
Definition at line 249 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_tahoe_bit_int (M_Type type, int n)
Definition at line 224 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_tahoe_bit_llong (M_Type type, int n)
Definition at line 200 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_LLONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_llong().
void M_tahoe_bit_long (M_Type type, int n)
Definition at line 212 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_tahoe_bit_short (M_Type type, int n)
Definition at line 236 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_TAHOE_ALIGN_BIT, M_TAHOE_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_tahoe_call_type (M_Type type, M_Type ntype)
Definition at line 464 of file mi_tahoe.c.
References M_tahoe_double(), M_tahoe_llong(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_tahoe_call_type2 (M_Type type, M_Type ntype)
Definition at line 498 of file mi_tahoe.c.
References M_tahoe_char(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_tahoe_long(), M_tahoe_pointer(), M_tahoe_short(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_tahoe_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1015 of file mi_tahoe.c.
Referenced by M_cb_label_name().
void M_tahoe_char (M_Type type, int unsign)
Definition at line 261 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_CHAR, M_TAHOE_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
void M_tahoe_double (M_Type type, int unsign)
Definition at line 321 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_DOUBLE, M_TAHOE_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
int M_tahoe_eval_type (M_Type type, M_Type ntype)
Definition at line 343 of file mi_tahoe.c.
References I_punt(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_POINTER, M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_tahoe_eval_type2 (M_Type type, M_Type ntype)
Definition at line 419 of file mi_tahoe.c.
References M_tahoe_char(), M_tahoe_double(), M_tahoe_float(), M_tahoe_int(), M_tahoe_llong(), M_tahoe_long(), M_tahoe_pointer(), M_tahoe_short(), M_tahoe_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_tahoe_float (M_Type type, int unsign)
Definition at line 311 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_FLOAT, M_TAHOE_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
char* M_tahoe_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1103 of file mi_tahoe.c.
Referenced by M_fn_label_name().
char* M_tahoe_fn_name_from_label (char * label)
Definition at line 1119 of file mi_tahoe.c.
Referenced by M_fn_name_from_label().
int M_tahoe_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 1464 of file mi_tahoe.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_warn(), M_align_offset(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_TAHOE_FLT_BASE, M_TAHOE_IN_INT_BASE, M_TAHOE_MAX_FNVAR_FLT_REG, M_TAHOE_MAX_FNVAR_INT_REG, M_TAHOE_OUT_INT_BASE, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_LLONG, M_THRU_MEMORY, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, SCRATCH_SPACE_SIZE, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_fnvar_layout().
int M_tahoe_fnvar_to_lvar (_M_Type type, long int * offset, char ** base_macro, int local_space)
Definition at line 1748 of file mi_tahoe.c.
References ADDR_ALIGN, _struct_M_Type::align, M_assert(), M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, _struct_M_Type::size, and _struct_M_Type::type.
void M_tahoe_int (M_Type type, int unsign)
Definition at line 281 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_INT, M_TAHOE_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
int M_tahoe_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1023 of file mi_tahoe.c.
Referenced by M_is_cb_label().
int M_tahoe_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1040 of file mi_tahoe.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_tahoe_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1031 of file mi_tahoe.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_tahoe_layout_fnvar (List param_list, char ** macro, int * pcount, int purpose)
Definition at line 1243 of file mi_tahoe.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_warn(), List_next(), List_start(), M_align_offset(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_RET_FNVAR, M_TAHOE_FLT_BASE, M_TAHOE_IN_INT_BASE, M_TAHOE_MAX_FNVAR_FLT_REG, M_TAHOE_MAX_FNVAR_INT_REG, M_TAHOE_OUT_INT_BASE, M_TAHOE_RET_INT_BASE, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_LLONG, M_THRU_MEMORY, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, SCRATCH_SPACE_SIZE, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_tahoe_layout_order (void)
Definition at line 643 of file mi_tahoe.c.
References M_assert(), M_BIG_ENDIAN, M_IPF_HPUX_ILP32, M_IPF_HPUX_LP64, M_IPF_LIN_LP64, M_IPF_WIN_P64, M_LITTLE_ENDIAN, and M_swarch.
Referenced by M_layout_order(), M_tahoe_struct_layout(), and M_tahoe_struct_size().
int M_tahoe_layout_retvar (M_Param param, int purpose)
Definition at line 1675 of file mi_tahoe.c.
References _struct_M_Type::flags, I_warn(), M_assert(), M_INDIRECT_THRU_REGISTER, M_TAHOE_RET_INT_BASE, M_tahoe_return_register(), M_TAHOE_SIZE_LLONG, M_THRU_REGISTER, M_TYFL_HFA, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_retvar().
void M_tahoe_llong (M_Type type, int unsign)
Definition at line 291 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_LLONG, M_TAHOE_SIZE_LLONG, M_TYPE_LLONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_llong(), M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), and M_tahoe_eval_type2().
void M_tahoe_long (M_Type type, int unsign)
Definition at line 301 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_LONG, M_TAHOE_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1807 of file mi_tahoe.c.
References ADDR_ALIGN, _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_INT, M_TYPE_BIT_LONG, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_tahoe_no_short_int (void)
Definition at line 1007 of file mi_tahoe.c.
References M_TAHOE_SIZE_INT, and M_TAHOE_SIZE_SHORT.
Referenced by M_no_short_int().
void M_tahoe_pointer (M_Type type)
Definition at line 331 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_POINTER, M_TAHOE_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_return_register (int type, int purpose)
Definition at line 1081 of file mi_tahoe.c.
References M_TAHOE_RET_FLT_BASE, M_TAHOE_RET_INT_BASE, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, and M_TYPE_LONG.
Referenced by M_return_register(), and M_tahoe_layout_retvar().
void M_tahoe_short (M_Type type, int unsign)
Definition at line 271 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_SHORT, M_TAHOE_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short(), M_tahoe_call_type2(), and M_tahoe_eval_type2().
int M_tahoe_struct_align (int n, _M_Type * type)
Definition at line 893 of file mi_tahoe.c.
References M_TAHOE_ALIGN_CHAR.
Referenced by M_struct_align().
void M_tahoe_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 678 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_BIG_ENDIAN, M_LITTLE_ENDIAN, M_tahoe_layout_order(), M_TAHOE_SIZE_CHAR, M_TAHOE_SIZE_INT, M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_tahoe_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 913 of file mi_tahoe.c.
References _struct_M_Type::align, M_assert(), M_BIG_ENDIAN, M_LITTLE_ENDIAN, M_TAHOE_ALIGN_CHAR, M_TAHOE_ALIGN_LONG, M_TAHOE_ALIGN_SHORT, M_tahoe_layout_order(), M_TAHOE_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_tahoe_structure_pointer (int purpose)
Definition at line 1073 of file mi_tahoe.c.
References M_TAHOE_RET_INT_BASE.
Referenced by M_structure_pointer().
int M_tahoe_type_align (int mtype)
Definition at line 148 of file mi_tahoe.c.
References M_TAHOE_ALIGN_BIT, M_TAHOE_ALIGN_CHAR, M_TAHOE_ALIGN_DOUBLE, M_TAHOE_ALIGN_FLOAT, M_TAHOE_ALIGN_INT, M_TAHOE_ALIGN_LLONG, M_TAHOE_ALIGN_LONG, M_TAHOE_ALIGN_POINTER, M_TAHOE_ALIGN_SHORT, M_TAHOE_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_tahoe_type_size (int mtype)
Definition at line 111 of file mi_tahoe.c.
References M_TAHOE_SIZE_BIT, M_TAHOE_SIZE_CHAR, M_TAHOE_SIZE_DOUBLE, M_TAHOE_SIZE_FLOAT, M_TAHOE_SIZE_INT, M_TAHOE_SIZE_LLONG, M_TAHOE_SIZE_LONG, M_TAHOE_SIZE_POINTER, M_TAHOE_SIZE_SHORT, M_TAHOE_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_tahoe_union_align (int n, _M_Type * type)
Definition at line 589 of file mi_tahoe.c.
References M_TAHOE_ALIGN_CHAR.
Referenced by M_union_align().
void M_tahoe_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 576 of file mi_tahoe.c.
Referenced by M_union_layout().
int M_tahoe_union_size (int n, _M_Type * type)
Definition at line 610 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_tahoe_void (M_Type type)
Definition at line 190 of file mi_tahoe.c.
References _struct_M_Type::align, M_TAHOE_ALIGN_VOID, M_TAHOE_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_tahoe_call_type(), M_tahoe_call_type2(), M_tahoe_eval_type(), M_tahoe_eval_type2(), and M_void().
Variable Documentation
int M_tahoe_align_long = 64
Definition at line 82 of file mi_tahoe.c.
Referenced by M_set_swarch_tahoe().
int M_tahoe_align_pointer = 64
Definition at line 83 of file mi_tahoe.c.
Referenced by M_set_swarch_tahoe().
int M_tahoe_size_long = 64
Definition at line 80 of file mi_tahoe.c.
Referenced by M_set_swarch_tahoe().
int M_tahoe_size_pointer = 64
Definition at line 81 of file mi_tahoe.c.
Referenced by M_set_swarch_tahoe().