mi_starcore.c File Reference
#include <config.h>
#include `m_spec.h`
#include `m_starcore.h`
#include <library/i_error.h>
Functions
int M_starcore_type_size (int mtype)
int M_starcore_type_align (int mtype)
void M_starcore_void (M_Type type)
void M_starcore_bit_long (M_Type type, int n)
void M_starcore_bit_int (M_Type type, int n)
void M_starcore_bit_short (M_Type type, int n)
void M_starcore_bit_char (M_Type type, int n)
void M_starcore_char (M_Type type, int unsign)
void M_starcore_short (M_Type type, int unsign)
void M_starcore_int (M_Type type, int unsign)
void M_starcore_long (M_Type type, int unsign)
void M_starcore_float (M_Type type, int unsign)
void M_starcore_double (M_Type type, int unsign)
void M_starcore_pointer (M_Type type)
int M_starcore_eval_type (M_Type type, M_Type ntype)
int M_starcore_eval_type2 (M_Type type, M_Type ntype)
int M_starcore_call_type (M_Type type, M_Type ntype)
int M_starcore_call_type2 (M_Type type, M_Type ntype)
void M_starcore_array_layout (M_Type type, int *offset)
int M_starcore_array_align (M_Type type)
int M_starcore_array_size (M_Type type, int dim)
void M_starcore_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_starcore_union_align (int n, _M_Type *type)
int M_starcore_union_size (int n, _M_Type *type)
int M_starcore_layout_order (void)
void M_starcore_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_starcore_struct_align (int n, _M_Type *type)
int M_starcore_struct_size (int n, _M_Type *type, int struct_align)
static int M_is_vararg_func (char *str)
static int M_align_offset (int offset, int align_bit)
int M_starcore_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_starcore_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_starcore_fnvar_to_lvar (_M_Type type, long int *offset, char **base_macro, int local_space)
int M_starcore_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_starcore_no_short_int (void)
void M_starcore_cb_label_name (char *fn, int cb, char *line, int len)
int M_starcore_is_cb_label (char *label, char *fn, int *cb)
void M_starcore_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_starcore_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_starcore_structure_pointer (int purpose)
int M_starcore_return_register (int type, int purpose)
char * M_starcore_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_starcore_fn_name_from_label (char *label)
void M_set_model_starcore (char *model_name)
Variables
int M_EM_SC_model = -1
int stack_only = 0
char * starcore_fn_name = NULL
Function Documentation
static int M_align_offset (int offset, int align_bit) [static]
Definition at line 1166 of file mi_starcore.c.
References I_punt().
Referenced by M_starcore_fnvar_layout(), M_starcore_fnvar_to_lvar(), M_tahoe_fnvar_layout(), and M_tahoe_layout_fnvar().
static int M_is_vararg_func (char * str) [static]
Definition at line 1135 of file mi_starcore.c.
References INT_MAX.
Referenced by M_starcore_fnvar_layout().
void M_set_model_starcore (char * model_name)
Definition at line 1654 of file mi_starcore.c.
References M_assert(), M_EM_SC140, M_EM_SC_model, M_model, and M_use_layout_database.
Referenced by M_set_machine().
int M_starcore_array_align (M_Type type)
Definition at line 613 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_array_align().
void M_starcore_array_layout (M_Type type, int * offset)
Definition at line 598 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_array_layout().
int M_starcore_array_size (M_Type type, int dim)
Definition at line 629 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and _struct_M_Type::size.
Referenced by M_array_size().
void M_starcore_bit_char (M_Type type, int n)
Definition at line 257 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_BIT, M_STARCORE_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_starcore_bit_int (M_Type type, int n)
Definition at line 216 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_BIT, M_STARCORE_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_starcore_bit_long (M_Type type, int n)
Definition at line 196 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_BIT, M_STARCORE_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_starcore_bit_short (M_Type type, int n)
Definition at line 236 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_BIT, M_STARCORE_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_starcore_call_type (M_Type type, M_Type ntype)
Definition at line 502 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_starcore_double(), M_starcore_int(), M_starcore_pointer(), M_starcore_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_starcore_call_type2 (M_Type type, M_Type ntype)
Definition at line 545 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_starcore_char(), M_starcore_double(), M_starcore_float(), M_starcore_int(), M_starcore_long(), M_starcore_pointer(), M_starcore_short(), M_starcore_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_starcore_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1474 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_cb_label_name().
void M_starcore_char (M_Type type, int unsign)
Definition at line 277 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_CHAR, M_STARCORE_SIZE_CHAR, M_TYPE_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_char(), M_starcore_call_type2(), and M_starcore_eval_type2().
void M_starcore_double (M_Type type, int unsign)
Definition at line 367 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_DOUBLE, M_STARCORE_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), and M_starcore_eval_type2().
int M_starcore_eval_type (M_Type type, M_Type ntype)
Definition at line 405 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_starcore_double(), M_starcore_float(), M_starcore_int(), M_starcore_pointer(), M_starcore_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_starcore_eval_type2 (M_Type type, M_Type ntype)
Definition at line 452 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_starcore_char(), M_starcore_double(), M_starcore_float(), M_starcore_int(), M_starcore_long(), M_starcore_pointer(), M_starcore_short(), M_starcore_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_starcore_float (M_Type type, int unsign)
Definition at line 349 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_FLOAT, M_STARCORE_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_starcore_call_type2(), M_starcore_eval_type(), and M_starcore_eval_type2().
char* M_starcore_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1611 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_fn_label_name().
char* M_starcore_fn_name_from_label (char * label)
Definition at line 1634 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_fn_name_from_label().
int M_starcore_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 1235 of file mi_starcore.c.
References _struct_M_Type::align, M_align_offset(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_is_vararg_func(), M_PUT_FNVAR, M_read_database_i(), M_STARCORE_ALIGN_MAX, M_STARCORE_IN_ADDR_BASE, M_STARCORE_IN_INT_BASE, M_STARCORE_MAX_FNVAR_ADDR_REG, M_STARCORE_MAX_FNVAR_INT_REG, M_STARCORE_OUT_ADDR_BASE, M_STARCORE_OUT_INT_BASE, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Type::size, and starcore_fn_name.
Referenced by M_fnvar_layout(), and M_starcore_layout_fnvar().
int M_starcore_fnvar_to_lvar (_M_Type type, long int * offset, char ** base_macro, int local_space)
Definition at line 1367 of file mi_starcore.c.
References _struct_M_Type::align, M_align_offset(), M_assert(), M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, _struct_M_Type::size, and _struct_M_Type::type.
void M_starcore_int (M_Type type, int unsign)
Definition at line 313 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_INT, M_STARCORE_SIZE_INT, M_TYPE_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_int(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), and M_starcore_eval_type2().
int M_starcore_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1489 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_is_cb_label().
int M_starcore_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1522 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_starcore_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1506 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_starcore_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 1183 of file mi_starcore.c.
References List_next(), List_size(), List_start(), M_starcore_fnvar_layout(), _struct_M_Param::mode, mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_starcore_layout_order (void)
Definition at line 744 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_LITTLE_ENDIAN.
Referenced by M_layout_order(), M_starcore_struct_layout(), and M_starcore_struct_size().
void M_starcore_long (M_Type type, int unsign)
Definition at line 331 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_LONG, M_STARCORE_SIZE_LONG, M_TYPE_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_long(), M_starcore_call_type2(), and M_starcore_eval_type2().
int M_starcore_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1404 of file mi_starcore.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_INT, M_TYPE_BIT_LONG, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_starcore_no_short_int (void)
Definition at line 1458 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_SIZE_INT, and M_STARCORE_SIZE_SHORT.
Referenced by M_no_short_int().
void M_starcore_pointer (M_Type type)
Definition at line 385 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_POINTER, M_STARCORE_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), and M_starcore_eval_type2().
int M_starcore_return_register (int type, int purpose)
Definition at line 1581 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_LCODE_RET_ADDR, M_STARCORE_LCODE_RET_INT, M_STARCORE_LCODE_RET_ST, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, and M_TYPE_STRUCT.
Referenced by M_return_register().
void M_starcore_short (M_Type type, int unsign)
Definition at line 295 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_SHORT, M_STARCORE_SIZE_SHORT, M_TYPE_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_short(), M_starcore_call_type2(), and M_starcore_eval_type2().
int M_starcore_struct_align (int n, _M_Type * type)
Definition at line 1000 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_STARCORE_ALIGN_CHAR.
Referenced by M_struct_align().
void M_starcore_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 774 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_BIG_ENDIAN, M_EM_SC_model, M_LITTLE_ENDIAN, M_starcore_layout_order(), M_STARCORE_SIZE_CHAR, M_STARCORE_SIZE_INT, M_STARCORE_SIZE_LONG, M_STARCORE_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_starcore_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 1029 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_BIG_ENDIAN, M_EM_SC_model, M_LITTLE_ENDIAN, M_STARCORE_ALIGN_CHAR, M_STARCORE_ALIGN_LONG, M_STARCORE_ALIGN_SHORT, M_starcore_layout_order(), M_STARCORE_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_starcore_structure_pointer (int purpose)
Definition at line 1564 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_STARCORE_LCODE_RET_ST.
Referenced by M_structure_pointer().
int M_starcore_type_align (int mtype)
Definition at line 126 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_BIT, M_STARCORE_ALIGN_BLOCK, M_STARCORE_ALIGN_CHAR, M_STARCORE_ALIGN_DOUBLE, M_STARCORE_ALIGN_FLOAT, M_STARCORE_ALIGN_INT, M_STARCORE_ALIGN_LONG, M_STARCORE_ALIGN_POINTER, M_STARCORE_ALIGN_SHORT, M_STARCORE_ALIGN_STRUCT, M_STARCORE_ALIGN_UNION, M_STARCORE_ALIGN_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_align().
int M_starcore_type_size (int mtype)
Definition at line 79 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_SIZE_BIT, M_STARCORE_SIZE_BLOCK, M_STARCORE_SIZE_CHAR, M_STARCORE_SIZE_DOUBLE, M_STARCORE_SIZE_FLOAT, M_STARCORE_SIZE_INT, M_STARCORE_SIZE_LONG, M_STARCORE_SIZE_POINTER, M_STARCORE_SIZE_SHORT, M_STARCORE_SIZE_STRUCT, M_STARCORE_SIZE_UNION, M_STARCORE_SIZE_VOID, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and M_TYPE_VOID.
Referenced by M_type_size().
int M_starcore_union_align (int n, _M_Type * type)
Definition at line 673 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and M_STARCORE_ALIGN_CHAR.
Referenced by M_union_align().
void M_starcore_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 654 of file mi_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_union_layout().
int M_starcore_union_size (int n, _M_Type * type)
Definition at line 702 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_starcore_void (M_Type type)
Definition at line 178 of file mi_starcore.c.
References _struct_M_Type::align, EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, M_STARCORE_ALIGN_VOID, M_STARCORE_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_starcore_call_type(), M_starcore_call_type2(), M_starcore_eval_type(), M_starcore_eval_type2(), and M_void().
Variable Documentation
int M_EM_SC_model = -1
Definition at line 72 of file mi_starcore.c.
Referenced by M_define_macros_starcore(), M_get_macro_name_starcore(), M_is_stack_operand_starcore(), M_is_unsafe_macro_starcore(), M_num_oper_required_for_starcore(), M_oper_supported_in_arch_starcore(), M_set_model_starcore(), M_starcore_array_align(), M_starcore_array_layout(), M_starcore_array_size(), M_starcore_bit_char(), M_starcore_bit_int(), M_starcore_bit_long(), M_starcore_bit_short(), M_starcore_call_type(), M_starcore_call_type2(), M_starcore_cb_label_name(), M_starcore_char(), M_starcore_dataflow_macro(), M_starcore_double(), M_starcore_eval_type(), M_starcore_eval_type2(), M_starcore_float(), M_starcore_fn_label_name(), M_starcore_fn_name_from_label(), M_starcore_fragile_macro(), M_starcore_int(), M_starcore_is_cb_label(), M_starcore_is_jumptbl_label(), M_starcore_jumptbl_label_name(), M_starcore_layout_order(), M_starcore_long(), M_starcore_no_short_int(), M_starcore_pointer(), M_starcore_return_register(), M_starcore_short(), M_starcore_struct_align(), M_starcore_struct_layout(), M_starcore_struct_size(), M_starcore_structure_pointer(), M_starcore_subroutine_call(), M_starcore_type_align(), M_starcore_type_size(), M_starcore_union_align(), M_starcore_union_layout(), M_starcore_union_size(), and M_starcore_void().
int stack_only = 0
Definition at line 73 of file mi_starcore.c.
char* starcore_fn_name = NULL
Definition at line 74 of file mi_starcore.c.
Referenced by M_starcore_fnvar_layout().