ml_sh.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `m_spec.h`
#include `m_sh.h`
Defines
#define M_SH_SIZE_VOID 0
#define M_SH_SIZE_BIT 1
#define M_SH_SIZE_CHAR 8
#define M_SH_SIZE_SHORT 16
#define M_SH_SIZE_INT 32
#define M_SH_SIZE_LONG 32
#define M_SH_SIZE_FLOAT 32
#define M_SH_SIZE_DOUBLE 64
#define M_SH_SIZE_POINTER 32
#define M_SH_SIZE_UNION -1
#define M_SH_SIZE_STRUCT -1
#define M_SH_SIZE_BLOCK -1
#define M_SH_SIZE_MAX 64
#define M_SH_ALIGN_VOID -1
#define M_SH_ALIGN_BIT 1
#define M_SH_ALIGN_CHAR 8
#define M_SH_ALIGN_SHORT 16
#define M_SH_ALIGN_INT 32
#define M_SH_ALIGN_LONG 32
#define M_SH_ALIGN_FLOAT 32
#define M_SH_ALIGN_DOUBLE 64
#define M_SH_ALIGN_POINTER 32
#define M_SH_ALIGN_UNION -1
#define M_SH_ALIGN_STRUCT -1
#define M_SH_ALIGN_BLOCK -1
#define M_SH_ALIGN_MAX 64
#define M_SH_SMALL_STRUCT_MAX 128
#define M_SH_MAX_FNVAR_REG 4
#define M_SH_PARAM_FP_OFFSET 0
#define M_SH_IN_BASE 4
#define M_SH_FLT_BASE 4
#define M_SH_OUT_BASE 4
#define M_SH_RET_IN 0
#define M_SH_RET_OUT 0
#define M_SH_RET_F 0
#define M_SH_ST 0
Functions
void M_sh_void (M_Type type)
void M_sh_bit_long (M_Type type, int n)
void M_sh_bit_int (M_Type type, int n)
void M_sh_bit_short (M_Type type, int n)
void M_sh_bit_char (M_Type type, int n)
void M_sh_float (M_Type type, int unsign)
void M_sh_double (M_Type type, int unsign)
void M_sh_pointer (M_Type type)
int M_sh_eval_type (M_Type type, M_Type ntype)
int M_sh_eval_type2 (M_Type type, M_Type ntype)
int M_sh_call_type (M_Type type, M_Type ntype)
int M_sh_call_type2 (M_Type type, M_Type ntype)
void M_sh_array_layout (M_Type type, int *offset)
int M_sh_array_align (M_Type type)
int M_sh_array_size (M_Type type, int dim)
void M_sh_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_sh_union_align (int n, _M_Type *type)
int M_sh_union_size (int n, _M_Type *type)
void M_sh_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_sh_struct_align (int n, _M_Type *type)
int M_sh_struct_size (int n, _M_Type *type, int struct_align)
int M_sh_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_sh_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_sh_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_sh_no_short_int (void)
void M_sh_cb_label_name (char *fn, int cb, char *line, int len)
int M_sh_is_cb_label (char *label, char *fn, int *cb)
void M_sh_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_sh_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_sh_structure_pointer (int purpose)
int M_sh_return_register (int type, int purpose)
char * M_sh_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_sh_fn_name_from_label (char *label)
void M_define_macros_sh (STRING_Symbol_Table *sym_tbl)
int M_sh_fragile_macro (int macro_value)
Set M_sh_fragile_macro_set ()
int M_sh_dataflow_macro (int id)
int M_sh_subroutine_call (int opc)
char * M_get_macro_name_sh (int id)
int M_oper_supported_in_arch_sh (int opc)
int M_is_stack_operand_sh (L_Operand *operand)
int M_is_unsafe_macro_sh (L_Operand *operand)
int M_num_oper_required_for_sh (L_Oper *oper, char *name)
int M_operand_type_sh (L_Operand *operand)
int M_conflicting_operands_sh (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_sh (int ctype)
Define Documentation
#define M_SH_ALIGN_BIT 1
Definition at line 100 of file ml_sh.c.
#define M_SH_ALIGN_BLOCK -1
Definition at line 110 of file ml_sh.c.
#define M_SH_ALIGN_CHAR 8
Definition at line 101 of file ml_sh.c.
#define M_SH_ALIGN_DOUBLE 64
Definition at line 106 of file ml_sh.c.
#define M_SH_ALIGN_FLOAT 32
Definition at line 105 of file ml_sh.c.
#define M_SH_ALIGN_INT 32
Definition at line 103 of file ml_sh.c.
#define M_SH_ALIGN_LONG 32
Definition at line 104 of file ml_sh.c.
#define M_SH_ALIGN_MAX 64
Definition at line 111 of file ml_sh.c.
#define M_SH_ALIGN_POINTER 32
Definition at line 107 of file ml_sh.c.
#define M_SH_ALIGN_SHORT 16
Definition at line 102 of file ml_sh.c.
#define M_SH_ALIGN_STRUCT -1
Definition at line 109 of file ml_sh.c.
#define M_SH_ALIGN_UNION -1
Definition at line 108 of file ml_sh.c.
#define M_SH_ALIGN_VOID -1
Definition at line 99 of file ml_sh.c.
#define M_SH_FLT_BASE 4
Definition at line 124 of file ml_sh.c.
#define M_SH_IN_BASE 4
Definition at line 123 of file ml_sh.c.
Referenced by M_sh_fnvar_layout().
#define M_SH_MAX_FNVAR_REG 4
Definition at line 117 of file ml_sh.c.
Referenced by M_sh_fnvar_layout().
#define M_SH_OUT_BASE 4
Definition at line 125 of file ml_sh.c.
Referenced by M_sh_fnvar_layout().
#define M_SH_PARAM_FP_OFFSET 0
Definition at line 120 of file ml_sh.c.
#define M_SH_RET_F 0
Definition at line 129 of file ml_sh.c.
Referenced by M_sh_return_register().
#define M_SH_RET_IN 0
Definition at line 127 of file ml_sh.c.
Referenced by M_sh_return_register().
#define M_SH_RET_OUT 0
Definition at line 128 of file ml_sh.c.
Referenced by M_sh_return_register().
#define M_SH_SIZE_BIT 1
Definition at line 86 of file ml_sh.c.
#define M_SH_SIZE_BLOCK -1
Definition at line 96 of file ml_sh.c.
#define M_SH_SIZE_CHAR 8
Definition at line 87 of file ml_sh.c.
#define M_SH_SIZE_DOUBLE 64
Definition at line 92 of file ml_sh.c.
#define M_SH_SIZE_FLOAT 32
Definition at line 91 of file ml_sh.c.
#define M_SH_SIZE_INT 32
Definition at line 89 of file ml_sh.c.
#define M_SH_SIZE_LONG 32
Definition at line 90 of file ml_sh.c.
#define M_SH_SIZE_MAX 64
Definition at line 97 of file ml_sh.c.
#define M_SH_SIZE_POINTER 32
Definition at line 93 of file ml_sh.c.
#define M_SH_SIZE_SHORT 16
Definition at line 88 of file ml_sh.c.
#define M_SH_SIZE_STRUCT -1
Definition at line 95 of file ml_sh.c.
#define M_SH_SIZE_UNION -1
Definition at line 94 of file ml_sh.c.
#define M_SH_SIZE_VOID 0
Definition at line 85 of file ml_sh.c.
#define M_SH_SMALL_STRUCT_MAX 128
Definition at line 112 of file ml_sh.c.
#define M_SH_ST 0
Definition at line 131 of file ml_sh.c.
Referenced by M_sh_structure_pointer().
Function Documentation
int M_conflicting_operands_sh (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1225 of file ml_sh.c.
References I_punt(), and M_assert().
Referenced by M_dep_conflicting_operands().
void M_define_macros_sh (STRING_Symbol_Table * sym_tbl)
Definition at line 980 of file ml_sh.c.
References L_SH_MAC_ALLOC, L_SH_MAC_CALLEE, L_SH_MAC_CALLER, L_SH_MAC_LEAF, L_SH_MAC_PR, L_SH_MAC_SR, and M_add_symbol.
Referenced by M_define_macros().
char* M_get_macro_name_sh (int id)
Definition at line 1065 of file ml_sh.c.
References L_SH_MAC_ALLOC, L_SH_MAC_CALLEE, L_SH_MAC_CALLER, L_SH_MAC_LEAF, L_SH_MAC_PR, and L_SH_MAC_SR.
Referenced by M_get_macro_name().
int M_is_stack_operand_sh (L_Operand * operand)
Definition at line 1124 of file ml_sh.c.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_sh (L_Operand * operand)
Definition at line 1137 of file ml_sh.c.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_sh (L_Oper * oper, char * name)
Definition at line 1153 of file ml_sh.c.
Referenced by M_num_oper_required_for().
int M_num_registers_sh (int ctype)
Definition at line 1370 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_num_registers().
int M_oper_supported_in_arch_sh (int opc)
Definition at line 1095 of file ml_sh.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_sh (L_Operand * operand)
Definition at line 1197 of file ml_sh.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
int M_sh_array_align (M_Type type)
Definition at line 388 of file ml_sh.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_sh_array_layout (M_Type type, int * offset)
Definition at line 382 of file ml_sh.c.
Referenced by M_array_layout().
int M_sh_array_size (M_Type type, int dim)
Definition at line 394 of file ml_sh.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_sh_bit_char (M_Type type, int n)
Definition at line 181 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_sh_bit_int (M_Type type, int n)
Definition at line 157 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_sh_bit_long (M_Type type, int n)
Definition at line 145 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_sh_bit_short (M_Type type, int n)
Definition at line 169 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_BIT, M_SH_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_sh_call_type (M_Type type, M_Type ntype)
Definition at line 302 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_sh_call_type2 (M_Type type, M_Type ntype)
Definition at line 339 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_sh_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 876 of file ml_sh.c.
Referenced by M_cb_label_name().
int M_sh_dataflow_macro (int id)
Definition at line 1034 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_dataflow_macro().
void M_sh_double (M_Type type, int unsign)
Definition at line 203 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_DOUBLE, M_SH_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_sh_eval_type (M_Type type, M_Type ntype)
Definition at line 225 of file ml_sh.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_sh_eval_type2 (M_Type type, M_Type ntype)
Definition at line 259 of file ml_sh.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_sh_float (M_Type type, int unsign)
Definition at line 193 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_FLOAT, M_SH_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_sh_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 953 of file ml_sh.c.
char* M_sh_fn_name_from_label (char * label)
Definition at line 966 of file ml_sh.c.
int M_sh_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 686 of file ml_sh.c.
References M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_SH_ALIGN_MAX, M_SH_IN_BASE, M_SH_MAX_FNVAR_REG, M_SH_OUT_BASE, M_SH_SIZE_INT, M_SH_SIZE_POINTER, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_fnvar_layout(), and M_sh_layout_fnvar().
int M_sh_fragile_macro (int macro_value)
Definition at line 991 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_fragile_macro().
Set M_sh_fragile_macro_set ()
Definition at line 1018 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, M_SH_2, and NULL.
Referenced by M_fragile_macro_set().
int M_sh_is_cb_label (char * label, char * fn, int * cb)
Definition at line 882 of file ml_sh.c.
Referenced by M_is_cb_label().
int M_sh_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 895 of file ml_sh.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_sh_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 888 of file ml_sh.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_sh_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 629 of file ml_sh.c.
References List_next(), List_size(), List_start(), M_sh_fnvar_layout(), _struct_M_Param::mode, mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_sh_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 829 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_sh_no_short_int (void)
Definition at line 870 of file ml_sh.c.
References M_SH_SIZE_INT, and M_SH_SIZE_SHORT.
Referenced by M_no_short_int().
void M_sh_pointer (M_Type type)
Definition at line 213 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_POINTER, M_SH_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_sh_return_register (int type, int purpose)
Definition at line 929 of file ml_sh.c.
References M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_SH_RET_F, M_SH_RET_IN, M_SH_RET_OUT, M_TYPE_DOUBLE, and M_TYPE_FLOAT.
Referenced by M_return_register().
int M_sh_struct_align (int n, _M_Type * type)
Definition at line 547 of file ml_sh.c.
References M_SH_ALIGN_CHAR.
Referenced by M_struct_align().
void M_sh_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 466 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_CHAR, M_SH_ALIGN_INT, M_SH_SIZE_CHAR, M_SH_SIZE_INT, M_SH_SIZE_LONG, M_SH_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::nbits.
Referenced by M_struct_layout().
int M_sh_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 566 of file ml_sh.c.
References _struct_M_Type::align, M_assert(), M_SH_ALIGN_CHAR, M_SH_ALIGN_INT, M_SH_SIZE_INT, M_TYPE_BIT_CHAR, and M_TYPE_BIT_LONG.
Referenced by M_struct_size().
int M_sh_structure_pointer (int purpose)
Definition at line 923 of file ml_sh.c.
References M_SH_ST.
Referenced by M_structure_pointer().
int M_sh_subroutine_call (int opc)
Definition at line 1049 of file ml_sh.c.
References M_assert(), M_model, M_SH_1, and M_SH_2.
Referenced by M_subroutine_call().
int M_sh_union_align (int n, _M_Type * type)
Definition at line 418 of file ml_sh.c.
References M_SH_ALIGN_CHAR.
Referenced by M_union_align().
void M_sh_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 407 of file ml_sh.c.
Referenced by M_union_layout().
int M_sh_union_size (int n, _M_Type * type)
Definition at line 437 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_sh_void (M_Type type)
Definition at line 135 of file ml_sh.c.
References _struct_M_Type::align, M_SH_ALIGN_VOID, M_SH_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().