ml_wims.c File Reference
#include <stdio.h>
#include <Lcode/l_main.h>
#include `m_wims.h`
Defines
#define M_WIMS_SIZE_VOID 0
#define M_WIMS_SIZE_BIT 1
#define M_WIMS_SIZE_CHAR 8
#define M_WIMS_SIZE_SHORT 16
#define M_WIMS_SIZE_INT 16
#define M_WIMS_SIZE_LONG 16
#define M_WIMS_SIZE_LLONG 32
#define M_WIMS_SIZE_FLOAT -1
#define M_WIMS_SIZE_DOUBLE -1
#define M_WIMS_SIZE_POINTER ((M_model == M_WIMS_16) ? 16 : 32)
#define M_WIMS_SIZE_UNION -1
#define M_WIMS_SIZE_STRUCT -1
#define M_WIMS_SIZE_BLOCK -1
#define M_WIMS_SIZE_MAX ((M_model == M_WIMS_16) ? 16 : 32)
#define M_WIMS_ALIGN_VOID -1
#define M_WIMS_ALIGN_BIT 1
#define M_WIMS_ALIGN_CHAR 8
#define M_WIMS_ALIGN_SHORT 16
#define M_WIMS_ALIGN_INT 16
#define M_WIMS_ALIGN_LONG 16
#define M_WIMS_ALIGN_LLONG 32
#define M_WIMS_ALIGN_FLOAT -1
#define M_WIMS_ALIGN_DOUBLE -1
#define M_WIMS_ALIGN_POINTER ((M_model == M_WIMS_16) ? 16 : 32)
#define M_WIMS_ALIGN_UNION -1
#define M_WIMS_ALIGN_STRUCT -1
#define M_WIMS_ALIGN_BLOCK -1
#define M_WIMS_ALIGN_MAX ((M_model == M_WIMS_16) ? 16 : 32)
#define M_WIMS_MAX_FNVAR_REG 0
#define M_WIMS_SMALL_STRUCT_MAX 32
#define MIN_PARAM_SIZE (32 * 0)
#define M_WIMS_INT_BASE 0
#define M_WIMS_FLT_BASE 0
#define M_WIMS_RET_F 15
#define M_WIMS_RET_I32 15
#define M_WIMS_RET_I64 15
#define M_WIMS_RET_ST 15
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_wims_void (M_Type type)
void M_wims_bit_long (M_Type type, int n)
void M_wims_bit_llong (M_Type type, int n)
void M_wims_bit_int (M_Type type, int n)
void M_wims_bit_short (M_Type type, int n)
void M_wims_bit_char (M_Type type, int n)
void M_wims_float (M_Type type, int unsign)
void M_wims_double (M_Type type, int unsign)
void M_wims_pointer (M_Type type)
int M_wims_eval_type (M_Type type, M_Type ntype)
int M_wims_eval_type2 (M_Type type, M_Type ntype)
int M_wims_call_type (M_Type type, M_Type ntype)
int M_wims_call_type2 (M_Type type, M_Type ntype)
void M_wims_array_layout (M_Type type, int *offset)
int M_wims_array_align (M_Type type)
int M_wims_array_size (M_Type type, int dim)
void M_wims_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_wims_union_align (int n, _M_Type *type)
int M_wims_union_size (int n, _M_Type *type)
void M_wims_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_wims_struct_align (int n, _M_Type *type)
int M_wims_struct_size (int n, _M_Type *type, int struct_align)
int M_wims_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_wims_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_wims_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_wims_no_short_int (void)
void M_wims_cb_label_name (char *fn, int cb, char *line, int len)
int M_wims_is_cb_label (char *label, char *fn, int *cb)
void M_wims_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_wims_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_wims_structure_pointer (int purpose)
int M_wims_return_register (int type, int purpose)
char * M_wims_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_wims_fn_name_from_label (char *label)
int M_wims_fragile_macro (int macro_value)
int M_wims_subroutine_call (int opc)
void M_define_macros_wims (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_wims (int id)
void M_define_opcode_name_wims (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_wims (int id)
int M_oper_supported_in_arch_wims (int opc)
int M_num_oper_required_for_wims (L_Oper *oper, char *name)
int M_is_stack_operand_wims (L_Operand *operand)
int M_is_unsafe_macro_wims (L_Operand *operand)
int M_operand_type_wims (L_Operand *operand)
int M_conflicting_operands_wims (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_wims (int ctype)
int M_wims_layout_retvar (M_Param param, int purpose)
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define long_neg_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_WIMS_ALIGN_BIT 1
Definition at line 165 of file ml_wims.c.
#define M_WIMS_ALIGN_BLOCK -1
Definition at line 176 of file ml_wims.c.
#define M_WIMS_ALIGN_CHAR 8
Definition at line 166 of file ml_wims.c.
#define M_WIMS_ALIGN_DOUBLE -1
Definition at line 172 of file ml_wims.c.
#define M_WIMS_ALIGN_FLOAT -1
Definition at line 171 of file ml_wims.c.
#define M_WIMS_ALIGN_INT 16
Definition at line 168 of file ml_wims.c.
#define M_WIMS_ALIGN_LLONG 32
Definition at line 170 of file ml_wims.c.
#define M_WIMS_ALIGN_LONG 16
Definition at line 169 of file ml_wims.c.
#define M_WIMS_ALIGN_MAX ((M_model == M_WIMS_16) ? 16 : 32)
Definition at line 177 of file ml_wims.c.
#define M_WIMS_ALIGN_POINTER ((M_model == M_WIMS_16) ? 16 : 32)
Definition at line 173 of file ml_wims.c.
#define M_WIMS_ALIGN_SHORT 16
Definition at line 167 of file ml_wims.c.
#define M_WIMS_ALIGN_STRUCT -1
Definition at line 175 of file ml_wims.c.
#define M_WIMS_ALIGN_UNION -1
Definition at line 174 of file ml_wims.c.
#define M_WIMS_ALIGN_VOID -1
Definition at line 164 of file ml_wims.c.
#define M_WIMS_FLT_BASE 0
Definition at line 186 of file ml_wims.c.
Referenced by M_wims_fnvar_layout(), and M_wims_layout_fnvar().
#define M_WIMS_INT_BASE 0
Definition at line 185 of file ml_wims.c.
Referenced by M_wims_fnvar_layout(), and M_wims_layout_fnvar().
#define M_WIMS_MAX_FNVAR_REG 0
Definition at line 180 of file ml_wims.c.
Referenced by M_wims_fnvar_layout(), and M_wims_layout_fnvar().
#define M_WIMS_RET_F 15
Definition at line 189 of file ml_wims.c.
#define M_WIMS_RET_I32 15
Definition at line 190 of file ml_wims.c.
Referenced by M_wims_return_register().
#define M_WIMS_RET_I64 15
Definition at line 191 of file ml_wims.c.
#define M_WIMS_RET_ST 15
Definition at line 192 of file ml_wims.c.
Referenced by M_wims_structure_pointer().
#define M_WIMS_SIZE_BIT 1
Definition at line 150 of file ml_wims.c.
#define M_WIMS_SIZE_BLOCK -1
Definition at line 161 of file ml_wims.c.
#define M_WIMS_SIZE_CHAR 8
Definition at line 151 of file ml_wims.c.
#define M_WIMS_SIZE_DOUBLE -1
Definition at line 157 of file ml_wims.c.
#define M_WIMS_SIZE_FLOAT -1
Definition at line 156 of file ml_wims.c.
#define M_WIMS_SIZE_INT 16
Definition at line 153 of file ml_wims.c.
#define M_WIMS_SIZE_LLONG 32
Definition at line 155 of file ml_wims.c.
#define M_WIMS_SIZE_LONG 16
Definition at line 154 of file ml_wims.c.
#define M_WIMS_SIZE_MAX ((M_model == M_WIMS_16) ? 16 : 32)
Definition at line 162 of file ml_wims.c.
#define M_WIMS_SIZE_POINTER ((M_model == M_WIMS_16) ? 16 : 32)
Definition at line 158 of file ml_wims.c.
#define M_WIMS_SIZE_SHORT 16
Definition at line 152 of file ml_wims.c.
#define M_WIMS_SIZE_STRUCT -1
Definition at line 160 of file ml_wims.c.
#define M_WIMS_SIZE_UNION -1
Definition at line 159 of file ml_wims.c.
#define M_WIMS_SIZE_VOID 0
Definition at line 149 of file ml_wims.c.
#define M_WIMS_SMALL_STRUCT_MAX 32
Definition at line 181 of file ml_wims.c.
Referenced by M_wims_fnvar_layout(), and M_wims_layout_fnvar().
#define MIN_PARAM_SIZE (32 * 0)
Definition at line 182 of file ml_wims.c.
#define non_zero_offset(a)
Value:
((!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                   ((a->src[1]->ctype&0x30)==0x00)))||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_conflicting_operands_wims (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1658 of file ml_wims.c.
References M_assert(), and WIMS_MAC_TRUE_SP.
Referenced by M_dep_conflicting_operands().
void M_define_macros_wims (STRING_Symbol_Table * sym_tbl)
Definition at line 1349 of file ml_wims.c.
References M_add_symbol, WIMS_MAC_ALLOC, WIMS_MAC_CALLEE_I, WIMS_MAC_LEAF, WIMS_MAC_RETADDR, and WIMS_MAC_TRUE_SP.
Referenced by M_define_macros().
void M_define_opcode_name_wims (STRING_Symbol_Table * sym_tbl)
Definition at line 1376 of file ml_wims.c.
Referenced by M_define_opcode_name().
char* M_get_macro_name_wims (int id)
Definition at line 1362 of file ml_wims.c.
References WIMS_MAC_ALLOC, WIMS_MAC_CALLEE_I, WIMS_MAC_LEAF, WIMS_MAC_RETADDR, and WIMS_MAC_TRUE_SP.
Referenced by M_get_macro_name().
char* M_get_opcode_name_wims (int id)
Definition at line 1380 of file ml_wims.c.
Referenced by M_get_opcode_name().
int M_is_stack_operand_wims (L_Operand * operand)
Definition at line 1588 of file ml_wims.c.
References WIMS_MAC_TRUE_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_wims (L_Operand * operand)
Definition at line 1605 of file ml_wims.c.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_wims (L_Oper * oper, char * name)
Definition at line 1432 of file ml_wims.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_wims (int ctype)
Definition at line 1718 of file ml_wims.c.
References M_assert(), M_model, M_WIMS_16, and M_WIMS_24.
Referenced by M_num_registers().
int M_oper_supported_in_arch_wims (int opc)
Definition at line 1392 of file ml_wims.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_wims (L_Operand * operand)
Definition at line 1624 of file ml_wims.c.
References FIELD_11, FIELD_14, FIELD_5, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit11, MDES_OPERAND_Lit14, MDES_OPERAND_Lit21, MDES_OPERAND_Lit5, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
int M_wims_array_align (M_Type type)
Definition at line 522 of file ml_wims.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_wims_array_layout (M_Type type, int * offset)
Definition at line 517 of file ml_wims.c.
Referenced by M_array_layout().
int M_wims_array_size (M_Type type, int dim)
Definition at line 527 of file ml_wims.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_wims_bit_char (M_Type type, int n)
Definition at line 249 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_WIMS_ALIGN_BIT, M_WIMS_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_wims_bit_int (M_Type type, int n)
Definition at line 229 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_INT, M_WIMS_ALIGN_BIT, M_WIMS_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_wims_bit_llong (M_Type type, int n)
Definition at line 219 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_LLONG, M_WIMS_ALIGN_BIT, M_WIMS_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_wims_bit_long (M_Type type, int n)
Definition at line 209 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_LONG, M_WIMS_ALIGN_BIT, M_WIMS_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_wims_bit_short (M_Type type, int n)
Definition at line 239 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_SHORT, M_WIMS_ALIGN_BIT, M_WIMS_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_wims_call_type (M_Type type, M_Type ntype)
Definition at line 369 of file ml_wims.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), M_wims_llong(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_wims_call_type2 (M_Type type, M_Type ntype)
Definition at line 416 of file ml_wims.c.
References M_double(), M_float(), M_int(), M_pointer(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), M_wims_llong(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_wims_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1218 of file ml_wims.c.
Referenced by M_cb_label_name().
void M_wims_double (M_Type type, int unsign)
Definition at line 269 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_DOUBLE, M_WIMS_ALIGN_DOUBLE, M_WIMS_SIZE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_wims_eval_type (M_Type type, M_Type ntype)
Definition at line 289 of file ml_wims.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), M_wims_llong(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_wims_eval_type2 (M_Type type, M_Type ntype)
Definition at line 325 of file ml_wims.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), M_wims_llong(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_wims_float (M_Type type, int unsign)
Definition at line 259 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_FLOAT, M_WIMS_ALIGN_FLOAT, M_WIMS_SIZE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_wims_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1286 of file ml_wims.c.
Referenced by M_fn_label_name().
char* M_wims_fn_name_from_label (char * label)
Definition at line 1298 of file ml_wims.c.
int M_wims_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 971 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_WIMS_ALIGN_INT, M_WIMS_ALIGN_MAX, M_WIMS_ALIGN_POINTER, M_WIMS_FLT_BASE, M_WIMS_INT_BASE, M_WIMS_MAX_FNVAR_REG, M_WIMS_SIZE_INT, M_WIMS_SIZE_POINTER, M_WIMS_SMALL_STRUCT_MAX, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_wims_fragile_macro (int macro_value)
Definition at line 1307 of file ml_wims.c.
References M_assert(), M_model, M_WIMS_16, and M_WIMS_24.
Referenced by M_fragile_macro().
int M_wims_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1223 of file ml_wims.c.
Referenced by M_is_cb_label().
int M_wims_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1234 of file ml_wims.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_wims_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1228 of file ml_wims.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_wims_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 758 of file ml_wims.c.
References _struct_M_Type::align, List_next(), List_start(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_WIMS_ALIGN_INT, M_WIMS_ALIGN_MAX, M_WIMS_ALIGN_POINTER, M_WIMS_FLT_BASE, M_WIMS_INT_BASE, M_WIMS_MAX_FNVAR_REG, M_WIMS_SIZE_INT, M_WIMS_SIZE_POINTER, M_WIMS_SMALL_STRUCT_MAX, MIN_PARAM_SIZE, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_wims_layout_retvar (M_Param param, int purpose)
Definition at line 1741 of file ml_wims.c.
References M_INDIRECT_THRU_MEMORY, M_THRU_MEMORY, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, and _struct_M_Type::type.
Referenced by M_layout_retvar().
int M_wims_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1174 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_WIMS_ALIGN_MAX, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_wims_no_short_int (void)
Definition at line 1214 of file ml_wims.c.
References M_WIMS_SIZE_INT, and M_WIMS_SIZE_SHORT.
Referenced by M_no_short_int().
void M_wims_pointer (M_Type type)
Definition at line 279 of file ml_wims.c.
References _struct_M_Type::align, M_TYPE_POINTER, M_WIMS_ALIGN_POINTER, M_WIMS_SIZE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_wims_return_register (int type, int purpose)
Definition at line 1271 of file ml_wims.c.
References M_assert(), M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, and M_WIMS_RET_I32.
Referenced by M_return_register().
int M_wims_struct_align (int n, _M_Type * type)
Definition at line 687 of file ml_wims.c.
References M_WIMS_ALIGN_CHAR.
Referenced by M_struct_align().
void M_wims_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 600 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_WIMS_SIZE_CHAR, M_WIMS_SIZE_INT, M_WIMS_SIZE_LONG, M_WIMS_SIZE_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_wims_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 703 of file ml_wims.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_WIMS_ALIGN_CHAR, M_WIMS_ALIGN_LONG, M_WIMS_ALIGN_SHORT, and M_WIMS_SIZE_INT.
Referenced by M_struct_size().
int M_wims_structure_pointer (int purpose)
Definition at line 1266 of file ml_wims.c.
References M_WIMS_RET_ST.
Referenced by M_structure_pointer().
int M_wims_subroutine_call (int opc)
Definition at line 1331 of file ml_wims.c.
References M_assert(), M_model, M_WIMS_16, and M_WIMS_24.
Referenced by M_subroutine_call().
int M_wims_union_align (int n, _M_Type * type)
Definition at line 550 of file ml_wims.c.
References M_WIMS_ALIGN_CHAR.
Referenced by M_union_align().
void M_wims_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 541 of file ml_wims.c.
Referenced by M_union_layout().
int M_wims_union_size (int n, _M_Type * type)
Definition at line 568 of file ml_wims.c.
References _struct_M_Type::align, M_WIMS_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_wims_void (M_Type type)
Definition at line 200 of file ml_wims.c.
References _struct_M_Type::align, M_TYPE_VOID, M_WIMS_ALIGN_VOID, M_WIMS_SIZE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().