ml_hpl_pd.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <machine/m_spec.h>
#include <machine/m_hpl_pd.h>
#include <machine/m_hppa.h>
#include <machine/m_sparc.h>
Defines
#define JWS_NEW_STACK_MODEL
#define M_PLAYDOH_SIZE_VOID 0
#define M_PLAYDOH_SIZE_BIT 1
#define M_PLAYDOH_SIZE_CHAR 8
#define M_PLAYDOH_SIZE_SHORT 16
#define M_PLAYDOH_SIZE_INT 32
#define M_PLAYDOH_SIZE_LONG 32
#define M_PLAYDOH_SIZE_FLOAT 32
#define M_PLAYDOH_SIZE_DOUBLE 64
#define M_PLAYDOH_SIZE_POINTER 32
#define M_PLAYDOH_SIZE_UNION -1
#define M_PLAYDOH_SIZE_STRUCT -1
#define M_PLAYDOH_SIZE_BLOCK -1
#define M_PLAYDOH_SIZE_MAX 64
#define M_PLAYDOH_ALIGN_VOID -1
#define M_PLAYDOH_ALIGN_BIT 1
#define M_PLAYDOH_ALIGN_CHAR 8
#define M_PLAYDOH_ALIGN_SHORT 16
#define M_PLAYDOH_ALIGN_INT 32
#define M_PLAYDOH_ALIGN_LONG 32
#define M_PLAYDOH_ALIGN_FLOAT 32
#define M_PLAYDOH_ALIGN_DOUBLE 32
#define M_PLAYDOH_ALIGN_POINTER 32
#define M_PLAYDOH_ALIGN_UNION -1
#define M_PLAYDOH_ALIGN_STRUCT -1
#define M_PLAYDOH_ALIGN_BLOCK -1
#define M_PLAYDOH_ALIGN_MAX 64
#define M_PLAYDOH_MAX_FNVAR_REG 4
#define M_PLAYDOH_SMALL_STRUCT_MAX 64
#define MIN_PARAM_SIZE (M_PLAYDOH_MAX_FNVAR_REG * M_PLAYDOH_SIZE_INT)
#define M_PLAYDOH_INT_BASE 0
#define M_PLAYDOH_FLT_BASE 4
#define M_PLAYDOH_RET_I32 15
#define M_PLAYDOH_RET_I64 15
#define M_PLAYDOH_RET_ST 15
#define M_PLAYDOH_RET_F 4
#define zero_offset(a)
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_playdoh_void (M_Type type)
void M_playdoh_bit_long (M_Type type, int n)
void M_playdoh_bit_int (M_Type type, int n)
void M_playdoh_bit_short (M_Type type, int n)
void M_playdoh_bit_char (M_Type type, int n)
void M_playdoh_float (M_Type type, int unsign)
void M_playdoh_double (M_Type type, int unsign)
void M_playdoh_pointer (M_Type type)
int M_playdoh_eval_type (M_Type type, M_Type ntype)
int M_playdoh_eval_type2 (M_Type type, M_Type ntype)
int M_playdoh_call_type (M_Type type, M_Type ntype)
int M_playdoh_call_type2 (M_Type type, M_Type ntype)
void M_playdoh_array_layout (M_Type type, int *offset)
int M_playdoh_array_align (M_Type type)
int M_playdoh_array_size (M_Type type, int dim)
void M_playdoh_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_playdoh_union_align (int n, _M_Type *type)
int M_playdoh_union_size (int n, _M_Type *type)
void M_playdoh_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_playdoh_struct_align (int n, _M_Type *type)
int M_playdoh_struct_size (int n, _M_Type *type, int struct_align)
int M_playdoh_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_playdoh_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **base_macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_playdoh_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_playdoh_no_short_int (void)
void M_playdoh_cb_label_name (char *fn, int cb, char *line, int len)
int M_playdoh_is_cb_label (char *label, char *fn, int *cb)
void M_playdoh_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_playdoh_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_playdoh_structure_pointer (int purpose)
int M_playdoh_return_register (int type, int purpose)
char * M_playdoh_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_playdoh_fn_name_from_label (char *label)
int M_playdoh_fragile_macro (int macro_value)
Set M_playdoh_fragile_macro_set ()
int M_playdoh_dataflow_macro (int id)
int M_playdoh_subroutine_call (int opc)
void M_define_macros_playdoh (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_playdoh (int id)
void M_define_opcode_name_playdoh (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_playdoh (int id)
int M_oper_supported_in_arch_playdoh (int opc)
int M_num_oper_required_for_playdoh (L_Oper *oper, char *name)
int M_num_registers_playdoh (int ctype)
int M_is_stack_operand_playdoh (L_Operand *operand)
int M_is_unsafe_macro_playdoh (L_Operand *operand)
int M_operand_type_playdoh (L_Operand *operand)
int M_conflicting_operands_playdoh (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_opc_from_proc_opc_playdoh (int proc_opc)
int M_base_displ_load_opcode (int proc_opc)
int M_sign_extend_load_opcode (int proc_opc)
int M_base_displ_store_opcode (int proc_opc)
Variables
int M_playdoh_model
Set Set_playdoh_fragile_macro = NULL
int M_playdoh_dbl_offset = 0
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define JWS_NEW_STACK_MODEL
Definition at line 74 of file ml_hpl_pd.c.
#define long_neg_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_PLAYDOH_ALIGN_BIT 1
Definition at line 119 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_BLOCK -1
Definition at line 129 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_CHAR 8
Definition at line 120 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_DOUBLE 32
Definition at line 125 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_FLOAT 32
Definition at line 124 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_INT 32
Definition at line 122 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_LONG 32
Definition at line 123 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_MAX 64
Definition at line 130 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_POINTER 32
Definition at line 126 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_SHORT 16
Definition at line 121 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_STRUCT -1
Definition at line 128 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_UNION -1
Definition at line 127 of file ml_hpl_pd.c.
#define M_PLAYDOH_ALIGN_VOID -1
Definition at line 118 of file ml_hpl_pd.c.
#define M_PLAYDOH_FLT_BASE 4
Definition at line 139 of file ml_hpl_pd.c.
Referenced by M_playdoh_fnvar_layout(), and M_playdoh_layout_fnvar().
#define M_PLAYDOH_INT_BASE 0
Definition at line 138 of file ml_hpl_pd.c.
Referenced by M_playdoh_fnvar_layout(), and M_playdoh_layout_fnvar().
#define M_PLAYDOH_MAX_FNVAR_REG 4
Definition at line 133 of file ml_hpl_pd.c.
Referenced by M_playdoh_fnvar_layout(), and M_playdoh_layout_fnvar().
#define M_PLAYDOH_RET_F 4
Definition at line 144 of file ml_hpl_pd.c.
Referenced by M_playdoh_return_register().
#define M_PLAYDOH_RET_I32 15
Definition at line 141 of file ml_hpl_pd.c.
Referenced by M_playdoh_return_register().
#define M_PLAYDOH_RET_I64 15
Definition at line 142 of file ml_hpl_pd.c.
Referenced by M_playdoh_return_register().
#define M_PLAYDOH_RET_ST 15
Definition at line 143 of file ml_hpl_pd.c.
Referenced by M_playdoh_structure_pointer().
#define M_PLAYDOH_SIZE_BIT 1
Definition at line 105 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_BLOCK -1
Definition at line 115 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_CHAR 8
Definition at line 106 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_DOUBLE 64
Definition at line 111 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_FLOAT 32
Definition at line 110 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_INT 32
Definition at line 108 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_LONG 32
Definition at line 109 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_MAX 64
Definition at line 116 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_POINTER 32
Definition at line 112 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_SHORT 16
Definition at line 107 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_STRUCT -1
Definition at line 114 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_UNION -1
Definition at line 113 of file ml_hpl_pd.c.
#define M_PLAYDOH_SIZE_VOID 0
Definition at line 104 of file ml_hpl_pd.c.
#define M_PLAYDOH_SMALL_STRUCT_MAX 64
Definition at line 134 of file ml_hpl_pd.c.
Referenced by M_playdoh_fnvar_layout(), and M_playdoh_layout_fnvar().
#define MIN_PARAM_SIZE (M_PLAYDOH_MAX_FNVAR_REG * M_PLAYDOH_SIZE_INT)
Definition at line 135 of file ml_hpl_pd.c.
#define non_zero_offset(a)
Value:
((!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                   ((a->src[1]->ctype&0x30)==0x00)))||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
#define zero_offset(a)
Value:
((a->src[1]->type==L_OPERAND_IMMED) &&\
                                 ((a->src[1]->ctype&0x30)==0x00)&&\
                                 (a->src[1]->value.i == 0))
Referenced by M_num_oper_required_for_starcore(), and M_num_oper_required_for_tahoe().
Function Documentation
int M_base_displ_load_opcode (int proc_opc)
Definition at line 5816 of file ml_hpl_pd.c.
References PLAYDOHop_FLG_D_C1_C1, PLAYDOHop_FLG_D_C1_C2, PLAYDOHop_FLG_D_C1_C3, PLAYDOHop_FLG_D_C1_V1, PLAYDOHop_FLG_D_C2_C1, PLAYDOHop_FLG_D_C2_C2, PLAYDOHop_FLG_D_C2_C3, PLAYDOHop_FLG_D_C2_V1, PLAYDOHop_FLG_D_C3_C1, PLAYDOHop_FLG_D_C3_C2, PLAYDOHop_FLG_D_C3_C3, PLAYDOHop_FLG_D_C3_V1, PLAYDOHop_FLG_D_V1_C1, PLAYDOHop_FLG_D_V1_C2, PLAYDOHop_FLG_D_V1_C3, PLAYDOHop_FLG_D_V1_V1, PLAYDOHop_FLG_S_C1_C1, PLAYDOHop_FLG_S_C1_C2, PLAYDOHop_FLG_S_C1_C3, PLAYDOHop_FLG_S_C1_V1, PLAYDOHop_FLG_S_C2_C1, PLAYDOHop_FLG_S_C2_C2, PLAYDOHop_FLG_S_C2_C3, PLAYDOHop_FLG_S_C2_V1, PLAYDOHop_FLG_S_C3_C1, PLAYDOHop_FLG_S_C3_C2, PLAYDOHop_FLG_S_C3_C3, PLAYDOHop_FLG_S_C3_V1, PLAYDOHop_FLG_S_V1_C1, PLAYDOHop_FLG_S_V1_C2, PLAYDOHop_FLG_S_V1_C3, PLAYDOHop_FLG_S_V1_V1, PLAYDOHop_FLM_D_C1_C1, PLAYDOHop_FLM_D_C1_C2, PLAYDOHop_FLM_D_C1_C3, PLAYDOHop_FLM_D_C1_V1, PLAYDOHop_FLM_D_C2_C1, PLAYDOHop_FLM_D_C2_C2, PLAYDOHop_FLM_D_C2_C3, PLAYDOHop_FLM_D_C2_V1, PLAYDOHop_FLM_D_C3_C1, PLAYDOHop_FLM_D_C3_C2, PLAYDOHop_FLM_D_C3_C3, PLAYDOHop_FLM_D_C3_V1, PLAYDOHop_FLM_D_V1_C1, PLAYDOHop_FLM_D_V1_C2, PLAYDOHop_FLM_D_V1_C3, PLAYDOHop_FLM_D_V1_V1, PLAYDOHop_FLM_S_C1_C1, PLAYDOHop_FLM_S_C1_C2, PLAYDOHop_FLM_S_C1_C3, PLAYDOHop_FLM_S_C1_V1, PLAYDOHop_FLM_S_C2_C1, PLAYDOHop_FLM_S_C2_C2, PLAYDOHop_FLM_S_C2_C3, PLAYDOHop_FLM_S_C2_V1, PLAYDOHop_FLM_S_C3_C1, PLAYDOHop_FLM_S_C3_C2, PLAYDOHop_FLM_S_C3_C3, PLAYDOHop_FLM_S_C3_V1, PLAYDOHop_FLM_S_V1_C1, PLAYDOHop_FLM_S_V1_C2, PLAYDOHop_FLM_S_V1_C3, PLAYDOHop_FLM_S_V1_V1, PLAYDOHop_LG_B_C1_C1, PLAYDOHop_LG_B_C1_C2, PLAYDOHop_LG_B_C1_C3, PLAYDOHop_LG_B_C1_V1, PLAYDOHop_LG_B_C2_C1, PLAYDOHop_LG_B_C2_C2, PLAYDOHop_LG_B_C2_C3, PLAYDOHop_LG_B_C2_V1, PLAYDOHop_LG_B_C3_C1, PLAYDOHop_LG_B_C3_C2, PLAYDOHop_LG_B_C3_C3, PLAYDOHop_LG_B_C3_V1, PLAYDOHop_LG_B_V1_C1, PLAYDOHop_LG_B_V1_C2, PLAYDOHop_LG_B_V1_C3, PLAYDOHop_LG_B_V1_V1, PLAYDOHop_LG_H_C1_C1, PLAYDOHop_LG_H_C1_C2, PLAYDOHop_LG_H_C1_C3, PLAYDOHop_LG_H_C1_V1, PLAYDOHop_LG_H_C2_C1, PLAYDOHop_LG_H_C2_C2, PLAYDOHop_LG_H_C2_C3, PLAYDOHop_LG_H_C2_V1, PLAYDOHop_LG_H_C3_C1, PLAYDOHop_LG_H_C3_C2, PLAYDOHop_LG_H_C3_C3, PLAYDOHop_LG_H_C3_V1, PLAYDOHop_LG_H_V1_C1, PLAYDOHop_LG_H_V1_C2, PLAYDOHop_LG_H_V1_C3, PLAYDOHop_LG_H_V1_V1, PLAYDOHop_LG_Q_C1_C1, PLAYDOHop_LG_Q_C1_C2, PLAYDOHop_LG_Q_C1_C3, PLAYDOHop_LG_Q_C1_V1, PLAYDOHop_LG_Q_C2_C1, PLAYDOHop_LG_Q_C2_C2, PLAYDOHop_LG_Q_C2_C3, PLAYDOHop_LG_Q_C2_V1, PLAYDOHop_LG_Q_C3_C1, PLAYDOHop_LG_Q_C3_C2, PLAYDOHop_LG_Q_C3_C3, PLAYDOHop_LG_Q_C3_V1, PLAYDOHop_LG_Q_V1_C1, PLAYDOHop_LG_Q_V1_C2, PLAYDOHop_LG_Q_V1_C3, PLAYDOHop_LG_Q_V1_V1, PLAYDOHop_LG_W_C1_C1, PLAYDOHop_LG_W_C1_C2, PLAYDOHop_LG_W_C1_C3, PLAYDOHop_LG_W_C1_V1, PLAYDOHop_LG_W_C2_C1, PLAYDOHop_LG_W_C2_C2, PLAYDOHop_LG_W_C2_C3, PLAYDOHop_LG_W_C2_V1, PLAYDOHop_LG_W_C3_C1, PLAYDOHop_LG_W_C3_C2, PLAYDOHop_LG_W_C3_C3, PLAYDOHop_LG_W_C3_V1, PLAYDOHop_LG_W_V1_C1, PLAYDOHop_LG_W_V1_C2, PLAYDOHop_LG_W_V1_C3, PLAYDOHop_LG_W_V1_V1, PLAYDOHop_LGX_B_C1_C1, PLAYDOHop_LGX_B_C1_C2, PLAYDOHop_LGX_B_C1_C3, PLAYDOHop_LGX_B_C1_V1, PLAYDOHop_LGX_B_C2_C1, PLAYDOHop_LGX_B_C2_C2, PLAYDOHop_LGX_B_C2_C3, PLAYDOHop_LGX_B_C2_V1, PLAYDOHop_LGX_B_C3_C1, PLAYDOHop_LGX_B_C3_C2, PLAYDOHop_LGX_B_C3_C3, PLAYDOHop_LGX_B_C3_V1, PLAYDOHop_LGX_B_V1_C1, PLAYDOHop_LGX_B_V1_C2, PLAYDOHop_LGX_B_V1_C3, PLAYDOHop_LGX_B_V1_V1, PLAYDOHop_LGX_H_C1_C1, PLAYDOHop_LGX_H_C1_C2, PLAYDOHop_LGX_H_C1_C3, PLAYDOHop_LGX_H_C1_V1, PLAYDOHop_LGX_H_C2_C1, PLAYDOHop_LGX_H_C2_C2, PLAYDOHop_LGX_H_C2_C3, PLAYDOHop_LGX_H_C2_V1, PLAYDOHop_LGX_H_C3_C1, PLAYDOHop_LGX_H_C3_C2, PLAYDOHop_LGX_H_C3_C3, PLAYDOHop_LGX_H_C3_V1, PLAYDOHop_LGX_H_V1_C1, PLAYDOHop_LGX_H_V1_C2, PLAYDOHop_LGX_H_V1_C3, PLAYDOHop_LGX_H_V1_V1, PLAYDOHop_LM_B_C1_C1, PLAYDOHop_LM_B_C1_C2, PLAYDOHop_LM_B_C1_C3, PLAYDOHop_LM_B_C1_V1, PLAYDOHop_LM_B_C2_C1, PLAYDOHop_LM_B_C2_C2, PLAYDOHop_LM_B_C2_C3, PLAYDOHop_LM_B_C2_V1, PLAYDOHop_LM_B_C3_C1, PLAYDOHop_LM_B_C3_C2, PLAYDOHop_LM_B_C3_C3, PLAYDOHop_LM_B_C3_V1, PLAYDOHop_LM_B_V1_C1, PLAYDOHop_LM_B_V1_C2, PLAYDOHop_LM_B_V1_C3, PLAYDOHop_LM_B_V1_V1, PLAYDOHop_LM_H_C1_C1, PLAYDOHop_LM_H_C1_C2, PLAYDOHop_LM_H_C1_C3, PLAYDOHop_LM_H_C1_V1, PLAYDOHop_LM_H_C2_C1, PLAYDOHop_LM_H_C2_C2, PLAYDOHop_LM_H_C2_C3, PLAYDOHop_LM_H_C2_V1, PLAYDOHop_LM_H_C3_C1, PLAYDOHop_LM_H_C3_C2, PLAYDOHop_LM_H_C3_C3, PLAYDOHop_LM_H_C3_V1, PLAYDOHop_LM_H_V1_C1, PLAYDOHop_LM_H_V1_C2, PLAYDOHop_LM_H_V1_C3, PLAYDOHop_LM_H_V1_V1, PLAYDOHop_LM_Q_C1_C1, PLAYDOHop_LM_Q_C1_C2, PLAYDOHop_LM_Q_C1_C3, PLAYDOHop_LM_Q_C1_V1, PLAYDOHop_LM_Q_C2_C1, PLAYDOHop_LM_Q_C2_C2, PLAYDOHop_LM_Q_C2_C3, PLAYDOHop_LM_Q_C2_V1, PLAYDOHop_LM_Q_C3_C1, PLAYDOHop_LM_Q_C3_C2, PLAYDOHop_LM_Q_C3_C3, PLAYDOHop_LM_Q_C3_V1, PLAYDOHop_LM_Q_V1_C1, PLAYDOHop_LM_Q_V1_C2, PLAYDOHop_LM_Q_V1_C3, PLAYDOHop_LM_Q_V1_V1, PLAYDOHop_LM_W_C1_C1, PLAYDOHop_LM_W_C1_C2, PLAYDOHop_LM_W_C1_C3, PLAYDOHop_LM_W_C1_V1, PLAYDOHop_LM_W_C2_C1, PLAYDOHop_LM_W_C2_C2, PLAYDOHop_LM_W_C2_C3, PLAYDOHop_LM_W_C2_V1, PLAYDOHop_LM_W_C3_C1, PLAYDOHop_LM_W_C3_C2, PLAYDOHop_LM_W_C3_C3, PLAYDOHop_LM_W_C3_V1, PLAYDOHop_LM_W_V1_C1, PLAYDOHop_LM_W_V1_C2, PLAYDOHop_LM_W_V1_C3, PLAYDOHop_LM_W_V1_V1, PLAYDOHop_LMX_B_C1_C1, PLAYDOHop_LMX_B_C1_C2, PLAYDOHop_LMX_B_C1_C3, PLAYDOHop_LMX_B_C1_V1, PLAYDOHop_LMX_B_C2_C1, PLAYDOHop_LMX_B_C2_C2, PLAYDOHop_LMX_B_C2_C3, PLAYDOHop_LMX_B_C2_V1, PLAYDOHop_LMX_B_C3_C1, PLAYDOHop_LMX_B_C3_C2, PLAYDOHop_LMX_B_C3_C3, PLAYDOHop_LMX_B_C3_V1, PLAYDOHop_LMX_B_V1_C1, PLAYDOHop_LMX_B_V1_C2, PLAYDOHop_LMX_B_V1_C3, PLAYDOHop_LMX_B_V1_V1, PLAYDOHop_LMX_H_C1_C1, PLAYDOHop_LMX_H_C1_C2, PLAYDOHop_LMX_H_C1_C3, PLAYDOHop_LMX_H_C1_V1, PLAYDOHop_LMX_H_C2_C1, PLAYDOHop_LMX_H_C2_C2, PLAYDOHop_LMX_H_C2_C3, PLAYDOHop_LMX_H_C2_V1, PLAYDOHop_LMX_H_C3_C1, PLAYDOHop_LMX_H_C3_C2, PLAYDOHop_LMX_H_C3_C3, PLAYDOHop_LMX_H_C3_V1, PLAYDOHop_LMX_H_V1_C1, PLAYDOHop_LMX_H_V1_C2, PLAYDOHop_LMX_H_V1_C3, and PLAYDOHop_LMX_H_V1_V1.
int M_base_displ_store_opcode (int proc_opc)
Definition at line 6290 of file ml_hpl_pd.c.
References PLAYDOHop_FSG_D_C1, PLAYDOHop_FSG_D_C2, PLAYDOHop_FSG_D_C3, PLAYDOHop_FSG_D_V1, PLAYDOHop_FSG_S_C1, PLAYDOHop_FSG_S_C2, PLAYDOHop_FSG_S_C3, PLAYDOHop_FSG_S_V1, PLAYDOHop_FSM_D_C1, PLAYDOHop_FSM_D_C2, PLAYDOHop_FSM_D_C3, PLAYDOHop_FSM_D_V1, PLAYDOHop_FSM_S_C1, PLAYDOHop_FSM_S_C2, PLAYDOHop_FSM_S_C3, PLAYDOHop_FSM_S_V1, PLAYDOHop_SG_B_C1, PLAYDOHop_SG_B_C2, PLAYDOHop_SG_B_C3, PLAYDOHop_SG_B_V1, PLAYDOHop_SG_H_C1, PLAYDOHop_SG_H_C2, PLAYDOHop_SG_H_C3, PLAYDOHop_SG_H_V1, PLAYDOHop_SG_Q_C1, PLAYDOHop_SG_Q_C2, PLAYDOHop_SG_Q_C3, PLAYDOHop_SG_Q_V1, PLAYDOHop_SG_W_C1, PLAYDOHop_SG_W_C2, PLAYDOHop_SG_W_C3, PLAYDOHop_SG_W_V1, PLAYDOHop_SM_B_C1, PLAYDOHop_SM_B_C2, PLAYDOHop_SM_B_C3, PLAYDOHop_SM_B_V1, PLAYDOHop_SM_H_C1, PLAYDOHop_SM_H_C2, PLAYDOHop_SM_H_C3, PLAYDOHop_SM_H_V1, PLAYDOHop_SM_Q_C1, PLAYDOHop_SM_Q_C2, PLAYDOHop_SM_Q_C3, PLAYDOHop_SM_Q_V1, PLAYDOHop_SM_W_C1, PLAYDOHop_SM_W_C2, PLAYDOHop_SM_W_C3, and PLAYDOHop_SM_W_V1.
int M_conflicting_operands_playdoh (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 3980 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_V1, Mspec_num_flt_callee_reg, Mspec_num_flt_caller_reg, Mspec_num_int_callee_reg, Mspec_num_int_caller_reg, and Mspec_num_prd_callee_reg.
Referenced by M_dep_conflicting_operands().
void M_define_macros_playdoh (STRING_Symbol_Table * sym_tbl)
Definition at line 1811 of file ml_hpl_pd.c.
References M_add_symbol, M_assert(), M_playdoh_model, M_PLAYDOH_V1, PLAYDOH_MAC_ESC, PLAYDOH_MAC_FONE, PLAYDOH_MAC_FZERO, PLAYDOH_MAC_LC, PLAYDOH_MAC_PRED_ALL_ROT, PLAYDOH_MAC_PRED_ALL_STATIC, PLAYDOH_MAC_PRED_FALSE, PLAYDOH_MAC_PRED_TRUE, PLAYDOH_MAC_PV_0, PLAYDOH_MAC_PV_1, PLAYDOH_MAC_PV_2, PLAYDOH_MAC_PV_3, PLAYDOH_MAC_PV_4, PLAYDOH_MAC_PV_5, PLAYDOH_MAC_PV_6, PLAYDOH_MAC_PV_7, PLAYDOH_MAC_RETADDR, PLAYDOH_MAC_RRB, PLAYDOH_MAC_TEMPREG, PLAYDOH_MAC_TRUE_SP, and PLAYDOH_MAC_ZERO.
Referenced by M_define_macros().
void M_define_opcode_name_playdoh (STRING_Symbol_Table * sym_tbl)
Definition at line 1904 of file ml_hpl_pd.c.
References M_add_symbol, PLAYDOHop_BRCF, PLAYDOHop_BRCT, PLAYDOHop_BRDVF, PLAYDOHop_BRDVI, PLAYDOHop_BRESTORE, PLAYDOHop_BRF_B_B_B, PLAYDOHop_BRF_B_B_F, PLAYDOHop_BRF_B_F_B, PLAYDOHop_BRF_B_F_F, PLAYDOHop_BRF_F_B_B, PLAYDOHop_BRF_F_B_F, PLAYDOHop_BRF_F_F_B, PLAYDOHop_BRF_F_F_F, PLAYDOHop_BRL, PLAYDOHop_BRLC, PLAYDOHop_BRU, PLAYDOHop_BRW_B_B_B, PLAYDOHop_BRW_B_B_F, PLAYDOHop_BRW_B_F_B, PLAYDOHop_BRW_B_F_F, PLAYDOHop_BRW_F_B_B, PLAYDOHop_BRW_F_B_F, PLAYDOHop_BRW_F_F_B, PLAYDOHop_BRW_F_F_F, PLAYDOHop_BSAVE, PLAYDOHop_CMPR_EV, PLAYDOHop_CMPR_FALSE, PLAYDOHop_CMPR_NSV, PLAYDOHop_CMPR_OD, PLAYDOHop_CMPR_SV, PLAYDOHop_CMPR_TRUE, PLAYDOHop_EXTRSB, PLAYDOHop_EXTRSH, PLAYDOHop_FCMPR_D_FALSE, PLAYDOHop_FCMPR_D_TRUE, PLAYDOHop_FCMPR_S_FALSE, PLAYDOHop_FCMPR_S_TRUE, PLAYDOHop_FL_D_C1_C1, PLAYDOHop_FL_D_C1_C2, PLAYDOHop_FL_D_C1_C3, PLAYDOHop_FL_D_C1_V1, PLAYDOHop_FL_D_C2_C1, PLAYDOHop_FL_D_C2_C2, PLAYDOHop_FL_D_C2_C3, PLAYDOHop_FL_D_C2_V1, PLAYDOHop_FL_D_C3_C1, PLAYDOHop_FL_D_C3_C2, PLAYDOHop_FL_D_C3_C3, PLAYDOHop_FL_D_C3_V1, PLAYDOHop_FL_D_V1_C1, PLAYDOHop_FL_D_V1_C2, PLAYDOHop_FL_D_V1_C3, PLAYDOHop_FL_D_V1_V1, PLAYDOHop_FL_S_C1_C1, PLAYDOHop_FL_S_C1_C2, PLAYDOHop_FL_S_C1_C3, PLAYDOHop_FL_S_C1_V1, PLAYDOHop_FL_S_C2_C1, PLAYDOHop_FL_S_C2_C2, PLAYDOHop_FL_S_C2_C3, PLAYDOHop_FL_S_C2_V1, PLAYDOHop_FL_S_C3_C1, PLAYDOHop_FL_S_C3_C2, PLAYDOHop_FL_S_C3_C3, PLAYDOHop_FL_S_C3_V1, PLAYDOHop_FL_S_V1_C1, PLAYDOHop_FL_S_V1_C2, PLAYDOHop_FL_S_V1_C3, PLAYDOHop_FL_S_V1_V1, PLAYDOHop_FLDS_D_C1_C1, PLAYDOHop_FLDS_D_C1_C2, PLAYDOHop_FLDS_D_C1_C3, PLAYDOHop_FLDS_D_C1_V1, PLAYDOHop_FLDS_D_C2_C1, PLAYDOHop_FLDS_D_C2_C2, PLAYDOHop_FLDS_D_C2_C3, PLAYDOHop_FLDS_D_C2_V1, PLAYDOHop_FLDS_D_C3_C1, PLAYDOHop_FLDS_D_C3_C2, PLAYDOHop_FLDS_D_C3_C3, PLAYDOHop_FLDS_D_C3_V1, PLAYDOHop_FLDS_D_V1_C1, PLAYDOHop_FLDS_D_V1_C2, PLAYDOHop_FLDS_D_V1_C3, PLAYDOHop_FLDS_D_V1_V1, PLAYDOHop_FLDS_S_C1_C1, PLAYDOHop_FLDS_S_C1_C2, PLAYDOHop_FLDS_S_C1_C3, PLAYDOHop_FLDS_S_C1_V1, PLAYDOHop_FLDS_S_C2_C1, PLAYDOHop_FLDS_S_C2_C2, PLAYDOHop_FLDS_S_C2_C3, PLAYDOHop_FLDS_S_C2_V1, PLAYDOHop_FLDS_S_C3_C1, PLAYDOHop_FLDS_S_C3_C2, PLAYDOHop_FLDS_S_C3_C3, PLAYDOHop_FLDS_S_C3_V1, PLAYDOHop_FLDS_S_V1_C1, PLAYDOHop_FLDS_S_V1_C2, PLAYDOHop_FLDS_S_V1_C3, PLAYDOHop_FLDS_S_V1_V1, PLAYDOHop_FLDSI_D_C1_C1, PLAYDOHop_FLDSI_D_C1_C2, PLAYDOHop_FLDSI_D_C1_C3, PLAYDOHop_FLDSI_D_C1_V1, PLAYDOHop_FLDSI_D_C2_C1, PLAYDOHop_FLDSI_D_C2_C2, PLAYDOHop_FLDSI_D_C2_C3, PLAYDOHop_FLDSI_D_C2_V1, PLAYDOHop_FLDSI_D_C3_C1, PLAYDOHop_FLDSI_D_C3_C2, PLAYDOHop_FLDSI_D_C3_C3, PLAYDOHop_FLDSI_D_C3_V1, PLAYDOHop_FLDSI_D_V1_C1, PLAYDOHop_FLDSI_D_V1_C2, PLAYDOHop_FLDSI_D_V1_C3, PLAYDOHop_FLDSI_D_V1_V1, PLAYDOHop_FLDSI_S_C1_C1, PLAYDOHop_FLDSI_S_C1_C2, PLAYDOHop_FLDSI_S_C1_C3, PLAYDOHop_FLDSI_S_C1_V1, PLAYDOHop_FLDSI_S_C2_C1, PLAYDOHop_FLDSI_S_C2_C2, PLAYDOHop_FLDSI_S_C2_C3, PLAYDOHop_FLDSI_S_C2_V1, PLAYDOHop_FLDSI_S_C3_C1, PLAYDOHop_FLDSI_S_C3_C2, PLAYDOHop_FLDSI_S_C3_C3, PLAYDOHop_FLDSI_S_C3_V1, PLAYDOHop_FLDSI_S_V1_C1, PLAYDOHop_FLDSI_S_V1_C2, PLAYDOHop_FLDSI_S_V1_C3, PLAYDOHop_FLDSI_S_V1_V1, PLAYDOHop_FLDV_D, PLAYDOHop_FLDV_S, PLAYDOHop_FLI_D_C1_C1, PLAYDOHop_FLI_D_C1_C2, PLAYDOHop_FLI_D_C1_C3, PLAYDOHop_FLI_D_C1_V1, PLAYDOHop_FLI_D_C2_C1, PLAYDOHop_FLI_D_C2_C2, PLAYDOHop_FLI_D_C2_C3, PLAYDOHop_FLI_D_C2_V1, PLAYDOHop_FLI_D_C3_C1, PLAYDOHop_FLI_D_C3_C2, PLAYDOHop_FLI_D_C3_C3, PLAYDOHop_FLI_D_C3_V1, PLAYDOHop_FLI_D_V1_C1, PLAYDOHop_FLI_D_V1_C2, PLAYDOHop_FLI_D_V1_C3, PLAYDOHop_FLI_D_V1_V1, PLAYDOHop_FLI_S_C1_C1, PLAYDOHop_FLI_S_C1_C2, PLAYDOHop_FLI_S_C1_C3, PLAYDOHop_FLI_S_C1_V1, PLAYDOHop_FLI_S_C2_C1, PLAYDOHop_FLI_S_C2_C2, PLAYDOHop_FLI_S_C2_C3, PLAYDOHop_FLI_S_C2_V1, PLAYDOHop_FLI_S_C3_C1, PLAYDOHop_FLI_S_C3_C2, PLAYDOHop_FLI_S_C3_C3, PLAYDOHop_FLI_S_C3_V1, PLAYDOHop_FLI_S_V1_C1, PLAYDOHop_FLI_S_V1_C2, PLAYDOHop_FLI_S_V1_C3, PLAYDOHop_FLI_S_V1_V1, PLAYDOHop_FMPYADDN_D, PLAYDOHop_FMPYADDN_S, PLAYDOHop_FRESTORE_D, PLAYDOHop_FRESTORE_S, PLAYDOHop_FS_D_C1, PLAYDOHop_FS_D_C2, PLAYDOHop_FS_D_C3, PLAYDOHop_FS_D_V1, PLAYDOHop_FS_S_C1, PLAYDOHop_FS_S_C2, PLAYDOHop_FS_S_C3, PLAYDOHop_FS_S_V1, PLAYDOHop_FSAVE_D, PLAYDOHop_FSAVE_S, PLAYDOHop_FSI_D_C1, PLAYDOHop_FSI_D_C2, PLAYDOHop_FSI_D_C3, PLAYDOHop_FSI_D_V1, PLAYDOHop_FSI_S_C1, PLAYDOHop_FSI_S_C2, PLAYDOHop_FSI_S_C3, PLAYDOHop_FSI_S_V1, PLAYDOHop_L_B_C1_C1, PLAYDOHop_L_B_C1_C2, PLAYDOHop_L_B_C1_C3, PLAYDOHop_L_B_C1_V1, PLAYDOHop_L_B_C2_C1, PLAYDOHop_L_B_C2_C2, PLAYDOHop_L_B_C2_C3, PLAYDOHop_L_B_C2_V1, PLAYDOHop_L_B_C3_C1, PLAYDOHop_L_B_C3_C2, PLAYDOHop_L_B_C3_C3, PLAYDOHop_L_B_C3_V1, PLAYDOHop_L_B_V1_C1, PLAYDOHop_L_B_V1_C2, PLAYDOHop_L_B_V1_C3, PLAYDOHop_L_B_V1_V1, PLAYDOHop_L_H_C1_C1, PLAYDOHop_L_H_C1_C2, PLAYDOHop_L_H_C1_C3, PLAYDOHop_L_H_C1_V1, PLAYDOHop_L_H_C2_C1, PLAYDOHop_L_H_C2_C2, PLAYDOHop_L_H_C2_C3, PLAYDOHop_L_H_C2_V1, PLAYDOHop_L_H_C3_C1, PLAYDOHop_L_H_C3_C2, PLAYDOHop_L_H_C3_C3, PLAYDOHop_L_H_C3_V1, PLAYDOHop_L_H_V1_C1, PLAYDOHop_L_H_V1_C2, PLAYDOHop_L_H_V1_C3, PLAYDOHop_L_H_V1_V1, PLAYDOHop_L_Q_C1_C1, PLAYDOHop_L_Q_C1_C2, PLAYDOHop_L_Q_C1_C3, PLAYDOHop_L_Q_C1_V1, PLAYDOHop_L_Q_C2_C1, PLAYDOHop_L_Q_C2_C2, PLAYDOHop_L_Q_C2_C3, PLAYDOHop_L_Q_C2_V1, PLAYDOHop_L_Q_C3_C1, PLAYDOHop_L_Q_C3_C2, PLAYDOHop_L_Q_C3_C3, PLAYDOHop_L_Q_C3_V1, PLAYDOHop_L_Q_V1_C1, PLAYDOHop_L_Q_V1_C2, PLAYDOHop_L_Q_V1_C3, PLAYDOHop_L_Q_V1_V1, PLAYDOHop_L_W_C1_C1, PLAYDOHop_L_W_C1_C2, PLAYDOHop_L_W_C1_C3, PLAYDOHop_L_W_C1_V1, PLAYDOHop_L_W_C2_C1, PLAYDOHop_L_W_C2_C2, PLAYDOHop_L_W_C2_C3, PLAYDOHop_L_W_C2_V1, PLAYDOHop_L_W_C3_C1, PLAYDOHop_L_W_C3_C2, PLAYDOHop_L_W_C3_C3, PLAYDOHop_L_W_C3_V1, PLAYDOHop_L_W_V1_C1, PLAYDOHop_L_W_V1_C2, PLAYDOHop_L_W_V1_C3, PLAYDOHop_L_W_V1_V1, PLAYDOHop_LDCM, PLAYDOHop_LDS_B_C1_C1, PLAYDOHop_LDS_B_C1_C2, PLAYDOHop_LDS_B_C1_C3, PLAYDOHop_LDS_B_C1_V1, PLAYDOHop_LDS_B_C2_C1, PLAYDOHop_LDS_B_C2_C2, PLAYDOHop_LDS_B_C2_C3, PLAYDOHop_LDS_B_C2_V1, PLAYDOHop_LDS_B_C3_C1, PLAYDOHop_LDS_B_C3_C2, PLAYDOHop_LDS_B_C3_C3, PLAYDOHop_LDS_B_C3_V1, PLAYDOHop_LDS_B_V1_C1, PLAYDOHop_LDS_B_V1_C2, PLAYDOHop_LDS_B_V1_C3, PLAYDOHop_LDS_B_V1_V1, PLAYDOHop_LDS_H_C1_C1, PLAYDOHop_LDS_H_C1_C2, PLAYDOHop_LDS_H_C1_C3, PLAYDOHop_LDS_H_C1_V1, PLAYDOHop_LDS_H_C2_C1, PLAYDOHop_LDS_H_C2_C2, PLAYDOHop_LDS_H_C2_C3, PLAYDOHop_LDS_H_C2_V1, PLAYDOHop_LDS_H_C3_C1, PLAYDOHop_LDS_H_C3_C2, PLAYDOHop_LDS_H_C3_C3, PLAYDOHop_LDS_H_C3_V1, PLAYDOHop_LDS_H_V1_C1, PLAYDOHop_LDS_H_V1_C2, PLAYDOHop_LDS_H_V1_C3, PLAYDOHop_LDS_H_V1_V1, PLAYDOHop_LDS_Q_C1_C1, PLAYDOHop_LDS_Q_C1_C2, PLAYDOHop_LDS_Q_C1_C3, PLAYDOHop_LDS_Q_C1_V1, PLAYDOHop_LDS_Q_C2_C1, PLAYDOHop_LDS_Q_C2_C2, PLAYDOHop_LDS_Q_C2_C3, PLAYDOHop_LDS_Q_C2_V1, PLAYDOHop_LDS_Q_C3_C1, PLAYDOHop_LDS_Q_C3_C2, PLAYDOHop_LDS_Q_C3_C3, PLAYDOHop_LDS_Q_C3_V1, PLAYDOHop_LDS_Q_V1_C1, PLAYDOHop_LDS_Q_V1_C2, PLAYDOHop_LDS_Q_V1_C3, PLAYDOHop_LDS_Q_V1_V1, PLAYDOHop_LDS_W_C1_C1, PLAYDOHop_LDS_W_C1_C2, PLAYDOHop_LDS_W_C1_C3, PLAYDOHop_LDS_W_C1_V1, PLAYDOHop_LDS_W_C2_C1, PLAYDOHop_LDS_W_C2_C2, PLAYDOHop_LDS_W_C2_C3, PLAYDOHop_LDS_W_C2_V1, PLAYDOHop_LDS_W_C3_C1, PLAYDOHop_LDS_W_C3_C2, PLAYDOHop_LDS_W_C3_C3, PLAYDOHop_LDS_W_C3_V1, PLAYDOHop_LDS_W_V1_C1, PLAYDOHop_LDS_W_V1_C2, PLAYDOHop_LDS_W_V1_C3, PLAYDOHop_LDS_W_V1_V1, PLAYDOHop_LDSI_B_C1_C1, PLAYDOHop_LDSI_B_C1_C2, PLAYDOHop_LDSI_B_C1_C3, PLAYDOHop_LDSI_B_C1_V1, PLAYDOHop_LDSI_B_C2_C1, PLAYDOHop_LDSI_B_C2_C2, PLAYDOHop_LDSI_B_C2_C3, PLAYDOHop_LDSI_B_C2_V1, PLAYDOHop_LDSI_B_C3_C1, PLAYDOHop_LDSI_B_C3_C2, PLAYDOHop_LDSI_B_C3_C3, PLAYDOHop_LDSI_B_C3_V1, PLAYDOHop_LDSI_B_V1_C1, PLAYDOHop_LDSI_B_V1_C2, PLAYDOHop_LDSI_B_V1_C3, PLAYDOHop_LDSI_B_V1_V1, PLAYDOHop_LDSI_H_C1_C1, PLAYDOHop_LDSI_H_C1_C2, PLAYDOHop_LDSI_H_C1_C3, PLAYDOHop_LDSI_H_C1_V1, PLAYDOHop_LDSI_H_C2_C1, PLAYDOHop_LDSI_H_C2_C2, PLAYDOHop_LDSI_H_C2_C3, PLAYDOHop_LDSI_H_C2_V1, PLAYDOHop_LDSI_H_C3_C1, PLAYDOHop_LDSI_H_C3_C2, PLAYDOHop_LDSI_H_C3_C3, PLAYDOHop_LDSI_H_C3_V1, PLAYDOHop_LDSI_H_V1_C1, PLAYDOHop_LDSI_H_V1_C2, PLAYDOHop_LDSI_H_V1_C3, PLAYDOHop_LDSI_H_V1_V1, PLAYDOHop_LDSI_Q_C1_C1, PLAYDOHop_LDSI_Q_C1_C2, PLAYDOHop_LDSI_Q_C1_C3, PLAYDOHop_LDSI_Q_C1_V1, PLAYDOHop_LDSI_Q_C2_C1, PLAYDOHop_LDSI_Q_C2_C2, PLAYDOHop_LDSI_Q_C2_C3, PLAYDOHop_LDSI_Q_C2_V1, PLAYDOHop_LDSI_Q_C3_C1, PLAYDOHop_LDSI_Q_C3_C2, PLAYDOHop_LDSI_Q_C3_C3, PLAYDOHop_LDSI_Q_C3_V1, PLAYDOHop_LDSI_Q_V1_C1, PLAYDOHop_LDSI_Q_V1_C2, PLAYDOHop_LDSI_Q_V1_C3, PLAYDOHop_LDSI_Q_V1_V1, PLAYDOHop_LDSI_W_C1_C1, PLAYDOHop_LDSI_W_C1_C2, PLAYDOHop_LDSI_W_C1_C3, PLAYDOHop_LDSI_W_C1_V1, PLAYDOHop_LDSI_W_C2_C1, PLAYDOHop_LDSI_W_C2_C2, PLAYDOHop_LDSI_W_C2_C3, PLAYDOHop_LDSI_W_C2_V1, PLAYDOHop_LDSI_W_C3_C1, PLAYDOHop_LDSI_W_C3_C2, PLAYDOHop_LDSI_W_C3_C3, PLAYDOHop_LDSI_W_C3_V1, PLAYDOHop_LDSI_W_V1_C1, PLAYDOHop_LDSI_W_V1_C2, PLAYDOHop_LDSI_W_V1_C3, PLAYDOHop_LDSI_W_V1_V1, PLAYDOHop_LDV_B, PLAYDOHop_LDV_H, PLAYDOHop_LDV_Q, PLAYDOHop_LDV_W, PLAYDOHop_LI_B_C1_C1, PLAYDOHop_LI_B_C1_C2, PLAYDOHop_LI_B_C1_C3, PLAYDOHop_LI_B_C1_V1, PLAYDOHop_LI_B_C2_C1, PLAYDOHop_LI_B_C2_C2, PLAYDOHop_LI_B_C2_C3, PLAYDOHop_LI_B_C2_V1, PLAYDOHop_LI_B_C3_C1, PLAYDOHop_LI_B_C3_C2, PLAYDOHop_LI_B_C3_C3, PLAYDOHop_LI_B_C3_V1, PLAYDOHop_LI_B_V1_C1, PLAYDOHop_LI_B_V1_C2, PLAYDOHop_LI_B_V1_C3, PLAYDOHop_LI_B_V1_V1, PLAYDOHop_LI_H_C1_C1, PLAYDOHop_LI_H_C1_C2, PLAYDOHop_LI_H_C1_C3, PLAYDOHop_LI_H_C1_V1, PLAYDOHop_LI_H_C2_C1, PLAYDOHop_LI_H_C2_C2, PLAYDOHop_LI_H_C2_C3, PLAYDOHop_LI_H_C2_V1, PLAYDOHop_LI_H_C3_C1, PLAYDOHop_LI_H_C3_C2, PLAYDOHop_LI_H_C3_C3, PLAYDOHop_LI_H_C3_V1, PLAYDOHop_LI_H_V1_C1, PLAYDOHop_LI_H_V1_C2, PLAYDOHop_LI_H_V1_C3, PLAYDOHop_LI_H_V1_V1, PLAYDOHop_LI_Q_C1_C1, PLAYDOHop_LI_Q_C1_C2, PLAYDOHop_LI_Q_C1_C3, PLAYDOHop_LI_Q_C1_V1, PLAYDOHop_LI_Q_C2_C1, PLAYDOHop_LI_Q_C2_C2, PLAYDOHop_LI_Q_C2_C3, PLAYDOHop_LI_Q_C2_V1, PLAYDOHop_LI_Q_C3_C1, PLAYDOHop_LI_Q_C3_C2, PLAYDOHop_LI_Q_C3_C3, PLAYDOHop_LI_Q_C3_V1, PLAYDOHop_LI_Q_V1_C1, PLAYDOHop_LI_Q_V1_C2, PLAYDOHop_LI_Q_V1_C3, PLAYDOHop_LI_Q_V1_V1, PLAYDOHop_LI_W_C1_C1, PLAYDOHop_LI_W_C1_C2, PLAYDOHop_LI_W_C1_C3, PLAYDOHop_LI_W_C1_V1, PLAYDOHop_LI_W_C2_C1, PLAYDOHop_LI_W_C2_C2, PLAYDOHop_LI_W_C2_C3, PLAYDOHop_LI_W_C2_V1, PLAYDOHop_LI_W_C3_C1, PLAYDOHop_LI_W_C3_C2, PLAYDOHop_LI_W_C3_C3, PLAYDOHop_LI_W_C3_V1, PLAYDOHop_LI_W_V1_C1, PLAYDOHop_LI_W_V1_C2, PLAYDOHop_LI_W_V1_C3, PLAYDOHop_LI_W_V1_V1, PLAYDOHop_M_NO_OP, PLAYDOHop_MOVEBB, PLAYDOHop_MOVECG, PLAYDOHop_MOVEFG_L, PLAYDOHop_MOVEFG_U, PLAYDOHop_MOVEGBP, PLAYDOHop_MOVEGC, PLAYDOHop_MOVEGCM, PLAYDOHop_MOVEGF_L, PLAYDOHop_MOVEGF_U, PLAYDOHop_MOVEGG, PLAYDOHop_MOVELB, PLAYDOHop_MOVELBS, PLAYDOHop_MOVELBX, PLAYDOHop_MOVELF, PLAYDOHop_MOVELFS, PLAYDOHop_MOVELG, PLAYDOHop_MOVELGS, PLAYDOHop_MOVELGX, PLAYDOHop_MOVEPG, PLAYDOHop_PBRA, PLAYDOHop_PBRAL, PLAYDOHop_PBRALBS, PLAYDOHop_PBRR, PLAYDOHop_PBRRL, PLAYDOHop_PBRRLBS, PLAYDOHop_RESTORE, PLAYDOHop_S_B_C1, PLAYDOHop_S_B_C2, PLAYDOHop_S_B_C3, PLAYDOHop_S_B_V1, PLAYDOHop_S_H_C1, PLAYDOHop_S_H_C2, PLAYDOHop_S_H_C3, PLAYDOHop_S_H_V1, PLAYDOHop_S_Q_C1, PLAYDOHop_S_Q_C2, PLAYDOHop_S_Q_C3, PLAYDOHop_S_Q_V1, PLAYDOHop_S_W_C1, PLAYDOHop_S_W_C2, PLAYDOHop_S_W_C3, PLAYDOHop_S_W_V1, PLAYDOHop_SAVE, PLAYDOHop_SH1ADDL, PLAYDOHop_SH2ADDL, PLAYDOHop_SH3ADDL, PLAYDOHop_SI_B_C1, PLAYDOHop_SI_B_C2, PLAYDOHop_SI_B_C3, PLAYDOHop_SI_B_V1, PLAYDOHop_SI_H_C1, PLAYDOHop_SI_H_C2, PLAYDOHop_SI_H_C3, PLAYDOHop_SI_H_V1, PLAYDOHop_SI_Q_C1, PLAYDOHop_SI_Q_C2, PLAYDOHop_SI_Q_C3, PLAYDOHop_SI_Q_V1, PLAYDOHop_SI_W_C1, PLAYDOHop_SI_W_C2, PLAYDOHop_SI_W_C3, PLAYDOHop_SI_W_V1, PLAYDOHop_VEXTRSB, PLAYDOHop_VEXTRSH, PLAYDOHop_VFL_D_C1_C1, PLAYDOHop_VFL_S_C1_C1, PLAYDOHop_VFLE_D_C1_C1, PLAYDOHop_VFLE_S_C1_C1, PLAYDOHop_VFS_D_C1, PLAYDOHop_VFS_S_C1, PLAYDOHop_VFSE_D_C1, PLAYDOHop_VFSE_S_C1, PLAYDOHop_VL_B_C1_C1, PLAYDOHop_VL_H_C1_C1, PLAYDOHop_VL_W_C1_C1, PLAYDOHop_VLE_B_C1_C1, PLAYDOHop_VLE_H_C1_C1, PLAYDOHop_VLE_W_C1_C1, PLAYDOHop_VS_B_C1, PLAYDOHop_VS_H_C1, PLAYDOHop_VS_W_C1, PLAYDOHop_VSE_B_C1, PLAYDOHop_VSE_H_C1, PLAYDOHop_VSE_W_C1, PLAYDOHopcode_BRCF, PLAYDOHopcode_BRCT, PLAYDOHopcode_BRDVF, PLAYDOHopcode_BRDVI, PLAYDOHopcode_BRESTORE, PLAYDOHopcode_BRF_B_B_B, PLAYDOHopcode_BRF_B_B_F, PLAYDOHopcode_BRF_B_F_B, PLAYDOHopcode_BRF_B_F_F, PLAYDOHopcode_BRF_F_B_B, PLAYDOHopcode_BRF_F_B_F, PLAYDOHopcode_BRF_F_F_B, PLAYDOHopcode_BRF_F_F_F, PLAYDOHopcode_BRL, PLAYDOHopcode_BRLC, PLAYDOHopcode_BRU, PLAYDOHopcode_BRW_B_B_B, PLAYDOHopcode_BRW_B_B_F, PLAYDOHopcode_BRW_B_F_B, PLAYDOHopcode_BRW_B_F_F, PLAYDOHopcode_BRW_F_B_B, PLAYDOHopcode_BRW_F_B_F, PLAYDOHopcode_BRW_F_F_B, PLAYDOHopcode_BRW_F_F_F, PLAYDOHopcode_BSAVE, PLAYDOHopcode_CMPR_EV, PLAYDOHopcode_CMPR_FALSE, PLAYDOHopcode_CMPR_NSV, PLAYDOHopcode_CMPR_OD, PLAYDOHopcode_CMPR_SV, PLAYDOHopcode_CMPR_TRUE, PLAYDOHopcode_EXTRSB, PLAYDOHopcode_EXTRSH, PLAYDOHopcode_FCMPR_D_FALSE, PLAYDOHopcode_FCMPR_D_TRUE, PLAYDOHopcode_FCMPR_S_FALSE, PLAYDOHopcode_FCMPR_S_TRUE, PLAYDOHopcode_FL_D_C1_C1, PLAYDOHopcode_FL_D_C1_C2, PLAYDOHopcode_FL_D_C1_C3, PLAYDOHopcode_FL_D_C1_V1, PLAYDOHopcode_FL_D_C2_C1, PLAYDOHopcode_FL_D_C2_C2, PLAYDOHopcode_FL_D_C2_C3, PLAYDOHopcode_FL_D_C2_V1, PLAYDOHopcode_FL_D_C3_C1, PLAYDOHopcode_FL_D_C3_C2, PLAYDOHopcode_FL_D_C3_C3, PLAYDOHopcode_FL_D_C3_V1, PLAYDOHopcode_FL_D_V1_C1, PLAYDOHopcode_FL_D_V1_C2, PLAYDOHopcode_FL_D_V1_C3, PLAYDOHopcode_FL_D_V1_V1, PLAYDOHopcode_FL_S_C1_C1, PLAYDOHopcode_FL_S_C1_C2, PLAYDOHopcode_FL_S_C1_C3, PLAYDOHopcode_FL_S_C1_V1, PLAYDOHopcode_FL_S_C2_C1, PLAYDOHopcode_FL_S_C2_C2, PLAYDOHopcode_FL_S_C2_C3, PLAYDOHopcode_FL_S_C2_V1, PLAYDOHopcode_FL_S_C3_C1, PLAYDOHopcode_FL_S_C3_C2, PLAYDOHopcode_FL_S_C3_C3, PLAYDOHopcode_FL_S_C3_V1, PLAYDOHopcode_FL_S_V1_C1, PLAYDOHopcode_FL_S_V1_C2, PLAYDOHopcode_FL_S_V1_C3, PLAYDOHopcode_FL_S_V1_V1, PLAYDOHopcode_FLDS_D_C1_C1, PLAYDOHopcode_FLDS_D_C1_C2, PLAYDOHopcode_FLDS_D_C1_C3, PLAYDOHopcode_FLDS_D_C1_V1, PLAYDOHopcode_FLDS_D_C2_C1, PLAYDOHopcode_FLDS_D_C2_C2, PLAYDOHopcode_FLDS_D_C2_C3, PLAYDOHopcode_FLDS_D_C2_V1, PLAYDOHopcode_FLDS_D_C3_C1, PLAYDOHopcode_FLDS_D_C3_C2, PLAYDOHopcode_FLDS_D_C3_C3, PLAYDOHopcode_FLDS_D_C3_V1, PLAYDOHopcode_FLDS_D_V1_C1, PLAYDOHopcode_FLDS_D_V1_C2, PLAYDOHopcode_FLDS_D_V1_C3, PLAYDOHopcode_FLDS_D_V1_V1, PLAYDOHopcode_FLDS_S_C1_C1, PLAYDOHopcode_FLDS_S_C1_C2, PLAYDOHopcode_FLDS_S_C1_C3, PLAYDOHopcode_FLDS_S_C1_V1, PLAYDOHopcode_FLDS_S_C2_C1, PLAYDOHopcode_FLDS_S_C2_C2, PLAYDOHopcode_FLDS_S_C2_C3, PLAYDOHopcode_FLDS_S_C2_V1, PLAYDOHopcode_FLDS_S_C3_C1, PLAYDOHopcode_FLDS_S_C3_C2, PLAYDOHopcode_FLDS_S_C3_C3, PLAYDOHopcode_FLDS_S_C3_V1, PLAYDOHopcode_FLDS_S_V1_C1, PLAYDOHopcode_FLDS_S_V1_C2, PLAYDOHopcode_FLDS_S_V1_C3, PLAYDOHopcode_FLDS_S_V1_V1, PLAYDOHopcode_FLDSI_D_C1_C1, PLAYDOHopcode_FLDSI_D_C1_C2, PLAYDOHopcode_FLDSI_D_C1_C3, PLAYDOHopcode_FLDSI_D_C1_V1, PLAYDOHopcode_FLDSI_D_C2_C1, PLAYDOHopcode_FLDSI_D_C2_C2, PLAYDOHopcode_FLDSI_D_C2_C3, PLAYDOHopcode_FLDSI_D_C2_V1, PLAYDOHopcode_FLDSI_D_C3_C1, PLAYDOHopcode_FLDSI_D_C3_C2, PLAYDOHopcode_FLDSI_D_C3_C3, PLAYDOHopcode_FLDSI_D_C3_V1, PLAYDOHopcode_FLDSI_D_V1_C1, PLAYDOHopcode_FLDSI_D_V1_C2, PLAYDOHopcode_FLDSI_D_V1_C3, PLAYDOHopcode_FLDSI_D_V1_V1, PLAYDOHopcode_FLDSI_S_C1_C1, PLAYDOHopcode_FLDSI_S_C1_C2, PLAYDOHopcode_FLDSI_S_C1_C3, PLAYDOHopcode_FLDSI_S_C1_V1, PLAYDOHopcode_FLDSI_S_C2_C1, PLAYDOHopcode_FLDSI_S_C2_C2, PLAYDOHopcode_FLDSI_S_C2_C3, PLAYDOHopcode_FLDSI_S_C2_V1, PLAYDOHopcode_FLDSI_S_C3_C1, PLAYDOHopcode_FLDSI_S_C3_C2, PLAYDOHopcode_FLDSI_S_C3_C3, PLAYDOHopcode_FLDSI_S_C3_V1, PLAYDOHopcode_FLDSI_S_V1_C1, PLAYDOHopcode_FLDSI_S_V1_C2, PLAYDOHopcode_FLDSI_S_V1_C3, PLAYDOHopcode_FLDSI_S_V1_V1, PLAYDOHopcode_FLDV_D, PLAYDOHopcode_FLDV_S, PLAYDOHopcode_FLI_D_C1_C1, PLAYDOHopcode_FLI_D_C1_C2, PLAYDOHopcode_FLI_D_C1_C3, PLAYDOHopcode_FLI_D_C1_V1, PLAYDOHopcode_FLI_D_C2_C1, PLAYDOHopcode_FLI_D_C2_C2, PLAYDOHopcode_FLI_D_C2_C3, PLAYDOHopcode_FLI_D_C2_V1, PLAYDOHopcode_FLI_D_C3_C1, PLAYDOHopcode_FLI_D_C3_C2, PLAYDOHopcode_FLI_D_C3_C3, PLAYDOHopcode_FLI_D_C3_V1, PLAYDOHopcode_FLI_D_V1_C1, PLAYDOHopcode_FLI_D_V1_C2, PLAYDOHopcode_FLI_D_V1_C3, PLAYDOHopcode_FLI_D_V1_V1, PLAYDOHopcode_FLI_S_C1_C1, PLAYDOHopcode_FLI_S_C1_C2, PLAYDOHopcode_FLI_S_C1_C3, PLAYDOHopcode_FLI_S_C1_V1, PLAYDOHopcode_FLI_S_C2_C1, PLAYDOHopcode_FLI_S_C2_C2, PLAYDOHopcode_FLI_S_C2_C3, PLAYDOHopcode_FLI_S_C2_V1, PLAYDOHopcode_FLI_S_C3_C1, PLAYDOHopcode_FLI_S_C3_C2, PLAYDOHopcode_FLI_S_C3_C3, PLAYDOHopcode_FLI_S_C3_V1, PLAYDOHopcode_FLI_S_V1_C1, PLAYDOHopcode_FLI_S_V1_C2, PLAYDOHopcode_FLI_S_V1_C3, PLAYDOHopcode_FLI_S_V1_V1, PLAYDOHopcode_FMPYADDN_D, PLAYDOHopcode_FMPYADDN_S, PLAYDOHopcode_FRESTORE_D, PLAYDOHopcode_FRESTORE_S, PLAYDOHopcode_FS_D_C1, PLAYDOHopcode_FS_D_C2, PLAYDOHopcode_FS_D_C3, PLAYDOHopcode_FS_D_V1, PLAYDOHopcode_FS_S_C1, PLAYDOHopcode_FS_S_C2, PLAYDOHopcode_FS_S_C3, PLAYDOHopcode_FS_S_V1, PLAYDOHopcode_FSAVE_D, PLAYDOHopcode_FSAVE_S, PLAYDOHopcode_FSI_D_C1, PLAYDOHopcode_FSI_D_C2, PLAYDOHopcode_FSI_D_C3, PLAYDOHopcode_FSI_D_V1, PLAYDOHopcode_FSI_S_C1, PLAYDOHopcode_FSI_S_C2, PLAYDOHopcode_FSI_S_C3, PLAYDOHopcode_FSI_S_V1, PLAYDOHopcode_L_B_C1_C1, PLAYDOHopcode_L_B_C1_C2, PLAYDOHopcode_L_B_C1_C3, PLAYDOHopcode_L_B_C1_V1, PLAYDOHopcode_L_B_C2_C1, PLAYDOHopcode_L_B_C2_C2, PLAYDOHopcode_L_B_C2_C3, PLAYDOHopcode_L_B_C2_V1, PLAYDOHopcode_L_B_C3_C1, PLAYDOHopcode_L_B_C3_C2, PLAYDOHopcode_L_B_C3_C3, PLAYDOHopcode_L_B_C3_V1, PLAYDOHopcode_L_B_V1_C1, PLAYDOHopcode_L_B_V1_C2, PLAYDOHopcode_L_B_V1_C3, PLAYDOHopcode_L_B_V1_V1, PLAYDOHopcode_L_H_C1_C1, PLAYDOHopcode_L_H_C1_C2, PLAYDOHopcode_L_H_C1_C3, PLAYDOHopcode_L_H_C1_V1, PLAYDOHopcode_L_H_C2_C1, PLAYDOHopcode_L_H_C2_C2, PLAYDOHopcode_L_H_C2_C3, PLAYDOHopcode_L_H_C2_V1, PLAYDOHopcode_L_H_C3_C1, PLAYDOHopcode_L_H_C3_C2, PLAYDOHopcode_L_H_C3_C3, PLAYDOHopcode_L_H_C3_V1, PLAYDOHopcode_L_H_V1_C1, PLAYDOHopcode_L_H_V1_C2, PLAYDOHopcode_L_H_V1_C3, PLAYDOHopcode_L_H_V1_V1, PLAYDOHopcode_L_Q_C1_C1, PLAYDOHopcode_L_Q_C1_C2, PLAYDOHopcode_L_Q_C1_C3, PLAYDOHopcode_L_Q_C1_V1, PLAYDOHopcode_L_Q_C2_C1, PLAYDOHopcode_L_Q_C2_C2, PLAYDOHopcode_L_Q_C2_C3, PLAYDOHopcode_L_Q_C2_V1, PLAYDOHopcode_L_Q_C3_C1, PLAYDOHopcode_L_Q_C3_C2, PLAYDOHopcode_L_Q_C3_C3, PLAYDOHopcode_L_Q_C3_V1, PLAYDOHopcode_L_Q_V1_C1, PLAYDOHopcode_L_Q_V1_C2, PLAYDOHopcode_L_Q_V1_C3, PLAYDOHopcode_L_Q_V1_V1, PLAYDOHopcode_L_W_C1_C1, PLAYDOHopcode_L_W_C1_C2, PLAYDOHopcode_L_W_C1_C3, PLAYDOHopcode_L_W_C1_V1, PLAYDOHopcode_L_W_C2_C1, PLAYDOHopcode_L_W_C2_C2, PLAYDOHopcode_L_W_C2_C3, PLAYDOHopcode_L_W_C2_V1, PLAYDOHopcode_L_W_C3_C1, PLAYDOHopcode_L_W_C3_C2, PLAYDOHopcode_L_W_C3_C3, PLAYDOHopcode_L_W_C3_V1, PLAYDOHopcode_L_W_V1_C1, PLAYDOHopcode_L_W_V1_C2, PLAYDOHopcode_L_W_V1_C3, PLAYDOHopcode_L_W_V1_V1, PLAYDOHopcode_LDCM, PLAYDOHopcode_LDS_B_C1_C1, PLAYDOHopcode_LDS_B_C1_C2, PLAYDOHopcode_LDS_B_C1_C3, PLAYDOHopcode_LDS_B_C1_V1, PLAYDOHopcode_LDS_B_C2_C1, PLAYDOHopcode_LDS_B_C2_C2, PLAYDOHopcode_LDS_B_C2_C3, PLAYDOHopcode_LDS_B_C2_V1, PLAYDOHopcode_LDS_B_C3_C1, PLAYDOHopcode_LDS_B_C3_C2, PLAYDOHopcode_LDS_B_C3_C3, PLAYDOHopcode_LDS_B_C3_V1, PLAYDOHopcode_LDS_B_V1_C1, PLAYDOHopcode_LDS_B_V1_C2, PLAYDOHopcode_LDS_B_V1_C3, PLAYDOHopcode_LDS_B_V1_V1, PLAYDOHopcode_LDS_H_C1_C1, PLAYDOHopcode_LDS_H_C1_C2, PLAYDOHopcode_LDS_H_C1_C3, PLAYDOHopcode_LDS_H_C1_V1, PLAYDOHopcode_LDS_H_C2_C1, PLAYDOHopcode_LDS_H_C2_C2, PLAYDOHopcode_LDS_H_C2_C3, PLAYDOHopcode_LDS_H_C2_V1, PLAYDOHopcode_LDS_H_C3_C1, PLAYDOHopcode_LDS_H_C3_C2, PLAYDOHopcode_LDS_H_C3_C3, PLAYDOHopcode_LDS_H_C3_V1, PLAYDOHopcode_LDS_H_V1_C1, PLAYDOHopcode_LDS_H_V1_C2, PLAYDOHopcode_LDS_H_V1_C3, PLAYDOHopcode_LDS_H_V1_V1, PLAYDOHopcode_LDS_Q_C1_C1, PLAYDOHopcode_LDS_Q_C1_C2, PLAYDOHopcode_LDS_Q_C1_C3, PLAYDOHopcode_LDS_Q_C1_V1, PLAYDOHopcode_LDS_Q_C2_C1, PLAYDOHopcode_LDS_Q_C2_C2, PLAYDOHopcode_LDS_Q_C2_C3, PLAYDOHopcode_LDS_Q_C2_V1, PLAYDOHopcode_LDS_Q_C3_C1, PLAYDOHopcode_LDS_Q_C3_C2, PLAYDOHopcode_LDS_Q_C3_C3, PLAYDOHopcode_LDS_Q_C3_V1, PLAYDOHopcode_LDS_Q_V1_C1, PLAYDOHopcode_LDS_Q_V1_C2, PLAYDOHopcode_LDS_Q_V1_C3, PLAYDOHopcode_LDS_Q_V1_V1, PLAYDOHopcode_LDS_W_C1_C1, PLAYDOHopcode_LDS_W_C1_C2, PLAYDOHopcode_LDS_W_C1_C3, PLAYDOHopcode_LDS_W_C1_V1, PLAYDOHopcode_LDS_W_C2_C1, PLAYDOHopcode_LDS_W_C2_C2, PLAYDOHopcode_LDS_W_C2_C3, PLAYDOHopcode_LDS_W_C2_V1, PLAYDOHopcode_LDS_W_C3_C1, PLAYDOHopcode_LDS_W_C3_C2, PLAYDOHopcode_LDS_W_C3_C3, PLAYDOHopcode_LDS_W_C3_V1, PLAYDOHopcode_LDS_W_V1_C1, PLAYDOHopcode_LDS_W_V1_C2, PLAYDOHopcode_LDS_W_V1_C3, PLAYDOHopcode_LDS_W_V1_V1, PLAYDOHopcode_LDSI_B_C1_C1, PLAYDOHopcode_LDSI_B_C1_C2, PLAYDOHopcode_LDSI_B_C1_C3, PLAYDOHopcode_LDSI_B_C1_V1, PLAYDOHopcode_LDSI_B_C2_C1, PLAYDOHopcode_LDSI_B_C2_C2, PLAYDOHopcode_LDSI_B_C2_C3, PLAYDOHopcode_LDSI_B_C2_V1, PLAYDOHopcode_LDSI_B_C3_C1, PLAYDOHopcode_LDSI_B_C3_C2, PLAYDOHopcode_LDSI_B_C3_C3, PLAYDOHopcode_LDSI_B_C3_V1, PLAYDOHopcode_LDSI_B_V1_C1, PLAYDOHopcode_LDSI_B_V1_C2, PLAYDOHopcode_LDSI_B_V1_C3, PLAYDOHopcode_LDSI_B_V1_V1, PLAYDOHopcode_LDSI_H_C1_C1, PLAYDOHopcode_LDSI_H_C1_C2, PLAYDOHopcode_LDSI_H_C1_C3, PLAYDOHopcode_LDSI_H_C1_V1, PLAYDOHopcode_LDSI_H_C2_C1, PLAYDOHopcode_LDSI_H_C2_C2, PLAYDOHopcode_LDSI_H_C2_C3, PLAYDOHopcode_LDSI_H_C2_V1, PLAYDOHopcode_LDSI_H_C3_C1, PLAYDOHopcode_LDSI_H_C3_C2, PLAYDOHopcode_LDSI_H_C3_C3, PLAYDOHopcode_LDSI_H_C3_V1, PLAYDOHopcode_LDSI_H_V1_C1, PLAYDOHopcode_LDSI_H_V1_C2, PLAYDOHopcode_LDSI_H_V1_C3, PLAYDOHopcode_LDSI_H_V1_V1, PLAYDOHopcode_LDSI_Q_C1_C1, PLAYDOHopcode_LDSI_Q_C1_C2, PLAYDOHopcode_LDSI_Q_C1_C3, PLAYDOHopcode_LDSI_Q_C1_V1, PLAYDOHopcode_LDSI_Q_C2_C1, PLAYDOHopcode_LDSI_Q_C2_C2, PLAYDOHopcode_LDSI_Q_C2_C3, PLAYDOHopcode_LDSI_Q_C2_V1, PLAYDOHopcode_LDSI_Q_C3_C1, PLAYDOHopcode_LDSI_Q_C3_C2, PLAYDOHopcode_LDSI_Q_C3_C3, PLAYDOHopcode_LDSI_Q_C3_V1, PLAYDOHopcode_LDSI_Q_V1_C1, PLAYDOHopcode_LDSI_Q_V1_C2, PLAYDOHopcode_LDSI_Q_V1_C3, PLAYDOHopcode_LDSI_Q_V1_V1, PLAYDOHopcode_LDSI_W_C1_C1, PLAYDOHopcode_LDSI_W_C1_C2, PLAYDOHopcode_LDSI_W_C1_C3, PLAYDOHopcode_LDSI_W_C1_V1, PLAYDOHopcode_LDSI_W_C2_C1, PLAYDOHopcode_LDSI_W_C2_C2, PLAYDOHopcode_LDSI_W_C2_C3, PLAYDOHopcode_LDSI_W_C2_V1, PLAYDOHopcode_LDSI_W_C3_C1, PLAYDOHopcode_LDSI_W_C3_C2, PLAYDOHopcode_LDSI_W_C3_C3, PLAYDOHopcode_LDSI_W_C3_V1, PLAYDOHopcode_LDSI_W_V1_C1, PLAYDOHopcode_LDSI_W_V1_C2, PLAYDOHopcode_LDSI_W_V1_C3, PLAYDOHopcode_LDSI_W_V1_V1, PLAYDOHopcode_LDV_B, PLAYDOHopcode_LDV_H, PLAYDOHopcode_LDV_Q, PLAYDOHopcode_LDV_W, PLAYDOHopcode_LI_B_C1_C1, PLAYDOHopcode_LI_B_C1_C2, PLAYDOHopcode_LI_B_C1_C3, PLAYDOHopcode_LI_B_C1_V1, PLAYDOHopcode_LI_B_C2_C1, PLAYDOHopcode_LI_B_C2_C2, PLAYDOHopcode_LI_B_C2_C3, PLAYDOHopcode_LI_B_C2_V1, PLAYDOHopcode_LI_B_C3_C1, PLAYDOHopcode_LI_B_C3_C2, PLAYDOHopcode_LI_B_C3_C3, PLAYDOHopcode_LI_B_C3_V1, PLAYDOHopcode_LI_B_V1_C1, PLAYDOHopcode_LI_B_V1_C2, PLAYDOHopcode_LI_B_V1_C3, PLAYDOHopcode_LI_B_V1_V1, PLAYDOHopcode_LI_H_C1_C1, PLAYDOHopcode_LI_H_C1_C2, PLAYDOHopcode_LI_H_C1_C3, PLAYDOHopcode_LI_H_C1_V1, PLAYDOHopcode_LI_H_C2_C1, PLAYDOHopcode_LI_H_C2_C2, PLAYDOHopcode_LI_H_C2_C3, PLAYDOHopcode_LI_H_C2_V1, PLAYDOHopcode_LI_H_C3_C1, PLAYDOHopcode_LI_H_C3_C2, PLAYDOHopcode_LI_H_C3_C3, PLAYDOHopcode_LI_H_C3_V1, PLAYDOHopcode_LI_H_V1_C1, PLAYDOHopcode_LI_H_V1_C2, PLAYDOHopcode_LI_H_V1_C3, PLAYDOHopcode_LI_H_V1_V1, PLAYDOHopcode_LI_Q_C1_C1, PLAYDOHopcode_LI_Q_C1_C2, PLAYDOHopcode_LI_Q_C1_C3, PLAYDOHopcode_LI_Q_C1_V1, PLAYDOHopcode_LI_Q_C2_C1, PLAYDOHopcode_LI_Q_C2_C2, PLAYDOHopcode_LI_Q_C2_C3, PLAYDOHopcode_LI_Q_C2_V1, PLAYDOHopcode_LI_Q_C3_C1, PLAYDOHopcode_LI_Q_C3_C2, PLAYDOHopcode_LI_Q_C3_C3, PLAYDOHopcode_LI_Q_C3_V1, PLAYDOHopcode_LI_Q_V1_C1, PLAYDOHopcode_LI_Q_V1_C2, PLAYDOHopcode_LI_Q_V1_C3, PLAYDOHopcode_LI_Q_V1_V1, PLAYDOHopcode_LI_W_C1_C1, PLAYDOHopcode_LI_W_C1_C2, PLAYDOHopcode_LI_W_C1_C3, PLAYDOHopcode_LI_W_C1_V1, PLAYDOHopcode_LI_W_C2_C1, PLAYDOHopcode_LI_W_C2_C2, PLAYDOHopcode_LI_W_C2_C3, PLAYDOHopcode_LI_W_C2_V1, PLAYDOHopcode_LI_W_C3_C1, PLAYDOHopcode_LI_W_C3_C2, PLAYDOHopcode_LI_W_C3_C3, PLAYDOHopcode_LI_W_C3_V1, PLAYDOHopcode_LI_W_V1_C1, PLAYDOHopcode_LI_W_V1_C2, PLAYDOHopcode_LI_W_V1_C3, PLAYDOHopcode_LI_W_V1_V1, PLAYDOHopcode_M_NO_OP, PLAYDOHopcode_MOVEBB, PLAYDOHopcode_MOVECG, PLAYDOHopcode_MOVEFG_L, PLAYDOHopcode_MOVEFG_U, PLAYDOHopcode_MOVEGBP, PLAYDOHopcode_MOVEGC, PLAYDOHopcode_MOVEGCM, PLAYDOHopcode_MOVEGF_L, PLAYDOHopcode_MOVEGF_U, PLAYDOHopcode_MOVEGG, PLAYDOHopcode_MOVELB, PLAYDOHopcode_MOVELBS, PLAYDOHopcode_MOVELBX, PLAYDOHopcode_MOVELF, PLAYDOHopcode_MOVELFS, PLAYDOHopcode_MOVELG, PLAYDOHopcode_MOVELGS, PLAYDOHopcode_MOVELGX, PLAYDOHopcode_MOVEPG, PLAYDOHopcode_PBRA, PLAYDOHopcode_PBRAL, PLAYDOHopcode_PBRALBS, PLAYDOHopcode_PBRR, PLAYDOHopcode_PBRRL, PLAYDOHopcode_PBRRLBS, PLAYDOHopcode_RESTORE, PLAYDOHopcode_S_B_C1, PLAYDOHopcode_S_B_C2, PLAYDOHopcode_S_B_C3, PLAYDOHopcode_S_B_V1, PLAYDOHopcode_S_H_C1, PLAYDOHopcode_S_H_C2, PLAYDOHopcode_S_H_C3, PLAYDOHopcode_S_H_V1, PLAYDOHopcode_S_Q_C1, PLAYDOHopcode_S_Q_C2, PLAYDOHopcode_S_Q_C3, PLAYDOHopcode_S_Q_V1, PLAYDOHopcode_S_W_C1, PLAYDOHopcode_S_W_C2, PLAYDOHopcode_S_W_C3, PLAYDOHopcode_S_W_V1, PLAYDOHopcode_SAVE, PLAYDOHopcode_SH1ADDL, PLAYDOHopcode_SH2ADDL, PLAYDOHopcode_SH3ADDL, PLAYDOHopcode_SI_B_C1, PLAYDOHopcode_SI_B_C2, PLAYDOHopcode_SI_B_C3, PLAYDOHopcode_SI_B_V1, PLAYDOHopcode_SI_H_C1, PLAYDOHopcode_SI_H_C2, PLAYDOHopcode_SI_H_C3, PLAYDOHopcode_SI_H_V1, PLAYDOHopcode_SI_Q_C1, PLAYDOHopcode_SI_Q_C2, PLAYDOHopcode_SI_Q_C3, PLAYDOHopcode_SI_Q_V1, PLAYDOHopcode_SI_W_C1, PLAYDOHopcode_SI_W_C2, PLAYDOHopcode_SI_W_C3, PLAYDOHopcode_SI_W_V1, PLAYDOHopcode_VEXTRSB, PLAYDOHopcode_VEXTRSH, PLAYDOHopcode_VFL_D_C1_C1, PLAYDOHopcode_VFL_S_C1_C1, PLAYDOHopcode_VFLE_D_C1_C1, PLAYDOHopcode_VFLE_S_C1_C1, PLAYDOHopcode_VFS_D_C1, PLAYDOHopcode_VFS_S_C1, PLAYDOHopcode_VFSE_D_C1, PLAYDOHopcode_VFSE_S_C1, PLAYDOHopcode_VL_B_C1_C1, PLAYDOHopcode_VL_H_C1_C1, PLAYDOHopcode_VL_W_C1_C1, PLAYDOHopcode_VLE_B_C1_C1, PLAYDOHopcode_VLE_H_C1_C1, PLAYDOHopcode_VLE_W_C1_C1, PLAYDOHopcode_VS_B_C1, PLAYDOHopcode_VS_H_C1, PLAYDOHopcode_VS_W_C1, PLAYDOHopcode_VSE_B_C1, PLAYDOHopcode_VSE_H_C1, and PLAYDOHopcode_VSE_W_C1.
Referenced by M_define_opcode_name().
char* M_get_macro_name_playdoh (int id)
Definition at line 1844 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_V1, PLAYDOH_MAC_ESC, PLAYDOH_MAC_FONE, PLAYDOH_MAC_FZERO, PLAYDOH_MAC_LC, PLAYDOH_MAC_PRED_ALL_ROT, PLAYDOH_MAC_PRED_ALL_STATIC, PLAYDOH_MAC_PRED_FALSE, PLAYDOH_MAC_PRED_TRUE, PLAYDOH_MAC_PV_0, PLAYDOH_MAC_PV_1, PLAYDOH_MAC_PV_2, PLAYDOH_MAC_PV_3, PLAYDOH_MAC_PV_4, PLAYDOH_MAC_PV_5, PLAYDOH_MAC_PV_6, PLAYDOH_MAC_PV_7, PLAYDOH_MAC_RETADDR, PLAYDOH_MAC_RRB, PLAYDOH_MAC_TEMPREG, PLAYDOH_MAC_TRUE_SP, and PLAYDOH_MAC_ZERO.
Referenced by M_get_macro_name().
char* M_get_opcode_name_playdoh (int id)
Definition at line 2537 of file ml_hpl_pd.c.
References PLAYDOHop_BRCF, PLAYDOHop_BRCT, PLAYDOHop_BRDVF, PLAYDOHop_BRDVI, PLAYDOHop_BRESTORE, PLAYDOHop_BRF_B_B_F, PLAYDOHop_BRF_B_F_F, PLAYDOHop_BRF_F_B_B, PLAYDOHop_BRF_F_F_B, PLAYDOHop_BRF_F_F_F, PLAYDOHop_BRL, PLAYDOHop_BRLC, PLAYDOHop_BRU, PLAYDOHop_BRW_B_B_F, PLAYDOHop_BRW_B_F_F, PLAYDOHop_BRW_F_B_B, PLAYDOHop_BRW_F_F_B, PLAYDOHop_BRW_F_F_F, PLAYDOHop_BSAVE, PLAYDOHop_CMPR_EV, PLAYDOHop_CMPR_FALSE, PLAYDOHop_CMPR_OD, PLAYDOHop_CMPR_TRUE, PLAYDOHop_EXTRSB, PLAYDOHop_EXTRSH, PLAYDOHop_FCMPR_D_FALSE, PLAYDOHop_FCMPR_D_TRUE, PLAYDOHop_FCMPR_S_FALSE, PLAYDOHop_FCMPR_S_TRUE, PLAYDOHop_FL_D_C1_C1, PLAYDOHop_FL_D_C1_C2, PLAYDOHop_FL_D_C1_C3, PLAYDOHop_FL_D_C1_V1, PLAYDOHop_FL_D_C2_C1, PLAYDOHop_FL_D_C2_C2, PLAYDOHop_FL_D_C2_C3, PLAYDOHop_FL_D_C2_V1, PLAYDOHop_FL_D_C3_C1, PLAYDOHop_FL_D_C3_C2, PLAYDOHop_FL_D_C3_C3, PLAYDOHop_FL_D_C3_V1, PLAYDOHop_FL_D_V1_C1, PLAYDOHop_FL_D_V1_C2, PLAYDOHop_FL_D_V1_C3, PLAYDOHop_FL_D_V1_V1, PLAYDOHop_FL_S_C1_C1, PLAYDOHop_FL_S_C1_C2, PLAYDOHop_FL_S_C1_C3, PLAYDOHop_FL_S_C1_V1, PLAYDOHop_FL_S_C2_C1, PLAYDOHop_FL_S_C2_C2, PLAYDOHop_FL_S_C2_C3, PLAYDOHop_FL_S_C2_V1, PLAYDOHop_FL_S_C3_C1, PLAYDOHop_FL_S_C3_C2, PLAYDOHop_FL_S_C3_C3, PLAYDOHop_FL_S_C3_V1, PLAYDOHop_FL_S_V1_C1, PLAYDOHop_FL_S_V1_C2, PLAYDOHop_FL_S_V1_C3, PLAYDOHop_FL_S_V1_V1, PLAYDOHop_FLDS_D_C1_C1, PLAYDOHop_FLDS_D_C1_C2, PLAYDOHop_FLDS_D_C1_C3, PLAYDOHop_FLDS_D_C1_V1, PLAYDOHop_FLDS_D_C2_C1, PLAYDOHop_FLDS_D_C2_C2, PLAYDOHop_FLDS_D_C2_C3, PLAYDOHop_FLDS_D_C2_V1, PLAYDOHop_FLDS_D_C3_C1, PLAYDOHop_FLDS_D_C3_C2, PLAYDOHop_FLDS_D_C3_C3, PLAYDOHop_FLDS_D_C3_V1, PLAYDOHop_FLDS_D_V1_C1, PLAYDOHop_FLDS_D_V1_C2, PLAYDOHop_FLDS_D_V1_C3, PLAYDOHop_FLDS_D_V1_V1, PLAYDOHop_FLDS_S_C1_C1, PLAYDOHop_FLDS_S_C1_C2, PLAYDOHop_FLDS_S_C1_C3, PLAYDOHop_FLDS_S_C1_V1, PLAYDOHop_FLDS_S_C2_C1, PLAYDOHop_FLDS_S_C2_C2, PLAYDOHop_FLDS_S_C2_C3, PLAYDOHop_FLDS_S_C2_V1, PLAYDOHop_FLDS_S_C3_C1, PLAYDOHop_FLDS_S_C3_C2, PLAYDOHop_FLDS_S_C3_C3, PLAYDOHop_FLDS_S_C3_V1, PLAYDOHop_FLDS_S_V1_C1, PLAYDOHop_FLDS_S_V1_C2, PLAYDOHop_FLDS_S_V1_C3, PLAYDOHop_FLDS_S_V1_V1, PLAYDOHop_FLDSI_D_C1_C1, PLAYDOHop_FLDSI_D_C1_C2, PLAYDOHop_FLDSI_D_C1_C3, PLAYDOHop_FLDSI_D_C1_V1, PLAYDOHop_FLDSI_D_C2_C1, PLAYDOHop_FLDSI_D_C2_C2, PLAYDOHop_FLDSI_D_C2_C3, PLAYDOHop_FLDSI_D_C2_V1, PLAYDOHop_FLDSI_D_C3_C1, PLAYDOHop_FLDSI_D_C3_C2, PLAYDOHop_FLDSI_D_C3_C3, PLAYDOHop_FLDSI_D_C3_V1, PLAYDOHop_FLDSI_D_V1_C1, PLAYDOHop_FLDSI_D_V1_C2, PLAYDOHop_FLDSI_D_V1_C3, PLAYDOHop_FLDSI_D_V1_V1, PLAYDOHop_FLDSI_S_C1_C1, PLAYDOHop_FLDSI_S_C1_C2, PLAYDOHop_FLDSI_S_C1_C3, PLAYDOHop_FLDSI_S_C1_V1, PLAYDOHop_FLDSI_S_C2_C1, PLAYDOHop_FLDSI_S_C2_C2, PLAYDOHop_FLDSI_S_C2_C3, PLAYDOHop_FLDSI_S_C2_V1, PLAYDOHop_FLDSI_S_C3_C1, PLAYDOHop_FLDSI_S_C3_C2, PLAYDOHop_FLDSI_S_C3_C3, PLAYDOHop_FLDSI_S_C3_V1, PLAYDOHop_FLDSI_S_V1_C1, PLAYDOHop_FLDSI_S_V1_C2, PLAYDOHop_FLDSI_S_V1_C3, PLAYDOHop_FLDSI_S_V1_V1, PLAYDOHop_FLDV_D, PLAYDOHop_FLDV_S, PLAYDOHop_FLI_D_C1_C1, PLAYDOHop_FLI_D_C1_C2, PLAYDOHop_FLI_D_C1_C3, PLAYDOHop_FLI_D_C1_V1, PLAYDOHop_FLI_D_C2_C1, PLAYDOHop_FLI_D_C2_C2, PLAYDOHop_FLI_D_C2_C3, PLAYDOHop_FLI_D_C2_V1, PLAYDOHop_FLI_D_C3_C1, PLAYDOHop_FLI_D_C3_C2, PLAYDOHop_FLI_D_C3_C3, PLAYDOHop_FLI_D_C3_V1, PLAYDOHop_FLI_D_V1_C1, PLAYDOHop_FLI_D_V1_C2, PLAYDOHop_FLI_D_V1_C3, PLAYDOHop_FLI_D_V1_V1, PLAYDOHop_FLI_S_C1_C1, PLAYDOHop_FLI_S_C1_C2, PLAYDOHop_FLI_S_C1_C3, PLAYDOHop_FLI_S_C1_V1, PLAYDOHop_FLI_S_C2_C1, PLAYDOHop_FLI_S_C2_C2, PLAYDOHop_FLI_S_C2_C3, PLAYDOHop_FLI_S_C2_V1, PLAYDOHop_FLI_S_C3_C1, PLAYDOHop_FLI_S_C3_C2, PLAYDOHop_FLI_S_C3_C3, PLAYDOHop_FLI_S_C3_V1, PLAYDOHop_FLI_S_V1_C1, PLAYDOHop_FLI_S_V1_C2, PLAYDOHop_FLI_S_V1_C3, PLAYDOHop_FLI_S_V1_V1, PLAYDOHop_FMPYADDN_D, PLAYDOHop_FMPYADDN_S, PLAYDOHop_FRESTORE_D, PLAYDOHop_FRESTORE_S, PLAYDOHop_FS_D_C1, PLAYDOHop_FS_D_C2, PLAYDOHop_FS_D_C3, PLAYDOHop_FS_D_V1, PLAYDOHop_FS_S_C1, PLAYDOHop_FS_S_C2, PLAYDOHop_FS_S_C3, PLAYDOHop_FS_S_V1, PLAYDOHop_FSAVE_D, PLAYDOHop_FSAVE_S, PLAYDOHop_FSI_D_C1, PLAYDOHop_FSI_D_C2, PLAYDOHop_FSI_D_C3, PLAYDOHop_FSI_D_V1, PLAYDOHop_FSI_S_C1, PLAYDOHop_FSI_S_C2, PLAYDOHop_FSI_S_C3, PLAYDOHop_FSI_S_V1, PLAYDOHop_L_B_C1_C1, PLAYDOHop_L_B_C1_C2, PLAYDOHop_L_B_C1_C3, PLAYDOHop_L_B_C1_V1, PLAYDOHop_L_B_C2_C1, PLAYDOHop_L_B_C2_C2, PLAYDOHop_L_B_C2_C3, PLAYDOHop_L_B_C2_V1, PLAYDOHop_L_B_C3_C1, PLAYDOHop_L_B_C3_C2, PLAYDOHop_L_B_C3_C3, PLAYDOHop_L_B_C3_V1, PLAYDOHop_L_B_V1_C1, PLAYDOHop_L_B_V1_C2, PLAYDOHop_L_B_V1_C3, PLAYDOHop_L_B_V1_V1, PLAYDOHop_L_H_C1_C1, PLAYDOHop_L_H_C1_C2, PLAYDOHop_L_H_C1_C3, PLAYDOHop_L_H_C1_V1, PLAYDOHop_L_H_C2_C1, PLAYDOHop_L_H_C2_C2, PLAYDOHop_L_H_C2_C3, PLAYDOHop_L_H_C2_V1, PLAYDOHop_L_H_C3_C1, PLAYDOHop_L_H_C3_C2, PLAYDOHop_L_H_C3_C3, PLAYDOHop_L_H_C3_V1, PLAYDOHop_L_H_V1_C1, PLAYDOHop_L_H_V1_C2, PLAYDOHop_L_H_V1_C3, PLAYDOHop_L_H_V1_V1, PLAYDOHop_L_Q_C1_C1, PLAYDOHop_L_Q_C1_C2, PLAYDOHop_L_Q_C1_C3, PLAYDOHop_L_Q_C1_V1, PLAYDOHop_L_Q_C2_C1, PLAYDOHop_L_Q_C2_C2, PLAYDOHop_L_Q_C2_C3, PLAYDOHop_L_Q_C2_V1, PLAYDOHop_L_Q_C3_C1, PLAYDOHop_L_Q_C3_C2, PLAYDOHop_L_Q_C3_C3, PLAYDOHop_L_Q_C3_V1, PLAYDOHop_L_Q_V1_C1, PLAYDOHop_L_Q_V1_C2, PLAYDOHop_L_Q_V1_C3, PLAYDOHop_L_Q_V1_V1, PLAYDOHop_L_W_C1_C1, PLAYDOHop_L_W_C1_C2, PLAYDOHop_L_W_C1_C3, PLAYDOHop_L_W_C1_V1, PLAYDOHop_L_W_C2_C1, PLAYDOHop_L_W_C2_C2, PLAYDOHop_L_W_C2_C3, PLAYDOHop_L_W_C2_V1, PLAYDOHop_L_W_C3_C1, PLAYDOHop_L_W_C3_C2, PLAYDOHop_L_W_C3_C3, PLAYDOHop_L_W_C3_V1, PLAYDOHop_L_W_V1_C1, PLAYDOHop_L_W_V1_C2, PLAYDOHop_L_W_V1_C3, PLAYDOHop_L_W_V1_V1, PLAYDOHop_LDCM, PLAYDOHop_LDS_B_C1_C1, PLAYDOHop_LDS_B_C1_C2, PLAYDOHop_LDS_B_C1_C3, PLAYDOHop_LDS_B_C1_V1, PLAYDOHop_LDS_B_C2_C1, PLAYDOHop_LDS_B_C2_C2, PLAYDOHop_LDS_B_C2_C3, PLAYDOHop_LDS_B_C2_V1, PLAYDOHop_LDS_B_C3_C1, PLAYDOHop_LDS_B_C3_C2, PLAYDOHop_LDS_B_C3_C3, PLAYDOHop_LDS_B_C3_V1, PLAYDOHop_LDS_B_V1_C1, PLAYDOHop_LDS_B_V1_C2, PLAYDOHop_LDS_B_V1_C3, PLAYDOHop_LDS_B_V1_V1, PLAYDOHop_LDS_H_C1_C1, PLAYDOHop_LDS_H_C1_C2, PLAYDOHop_LDS_H_C1_C3, PLAYDOHop_LDS_H_C1_V1, PLAYDOHop_LDS_H_C2_C1, PLAYDOHop_LDS_H_C2_C2, PLAYDOHop_LDS_H_C2_C3, PLAYDOHop_LDS_H_C2_V1, PLAYDOHop_LDS_H_C3_C1, PLAYDOHop_LDS_H_C3_C2, PLAYDOHop_LDS_H_C3_C3, PLAYDOHop_LDS_H_C3_V1, PLAYDOHop_LDS_H_V1_C1, PLAYDOHop_LDS_H_V1_C2, PLAYDOHop_LDS_H_V1_C3, PLAYDOHop_LDS_H_V1_V1, PLAYDOHop_LDS_Q_C1_C1, PLAYDOHop_LDS_Q_C1_C2, PLAYDOHop_LDS_Q_C1_C3, PLAYDOHop_LDS_Q_C1_V1, PLAYDOHop_LDS_Q_C2_C1, PLAYDOHop_LDS_Q_C2_C2, PLAYDOHop_LDS_Q_C2_C3, PLAYDOHop_LDS_Q_C2_V1, PLAYDOHop_LDS_Q_C3_C1, PLAYDOHop_LDS_Q_C3_C2, PLAYDOHop_LDS_Q_C3_C3, PLAYDOHop_LDS_Q_C3_V1, PLAYDOHop_LDS_Q_V1_C1, PLAYDOHop_LDS_Q_V1_C2, PLAYDOHop_LDS_Q_V1_C3, PLAYDOHop_LDS_Q_V1_V1, PLAYDOHop_LDS_W_C1_C1, PLAYDOHop_LDS_W_C1_C2, PLAYDOHop_LDS_W_C1_C3, PLAYDOHop_LDS_W_C1_V1, PLAYDOHop_LDS_W_C2_C1, PLAYDOHop_LDS_W_C2_C2, PLAYDOHop_LDS_W_C2_C3, PLAYDOHop_LDS_W_C2_V1, PLAYDOHop_LDS_W_C3_C1, PLAYDOHop_LDS_W_C3_C2, PLAYDOHop_LDS_W_C3_C3, PLAYDOHop_LDS_W_C3_V1, PLAYDOHop_LDS_W_V1_C1, PLAYDOHop_LDS_W_V1_C2, PLAYDOHop_LDS_W_V1_C3, PLAYDOHop_LDS_W_V1_V1, PLAYDOHop_LDSI_B_C1_C1, PLAYDOHop_LDSI_B_C1_C2, PLAYDOHop_LDSI_B_C1_C3, PLAYDOHop_LDSI_B_C1_V1, PLAYDOHop_LDSI_B_C2_C1, PLAYDOHop_LDSI_B_C2_C2, PLAYDOHop_LDSI_B_C2_C3, PLAYDOHop_LDSI_B_C2_V1, PLAYDOHop_LDSI_B_C3_C1, PLAYDOHop_LDSI_B_C3_C2, PLAYDOHop_LDSI_B_C3_C3, PLAYDOHop_LDSI_B_C3_V1, PLAYDOHop_LDSI_B_V1_C1, PLAYDOHop_LDSI_B_V1_C2, PLAYDOHop_LDSI_B_V1_C3, PLAYDOHop_LDSI_B_V1_V1, PLAYDOHop_LDSI_H_C1_C1, PLAYDOHop_LDSI_H_C1_C2, PLAYDOHop_LDSI_H_C1_C3, PLAYDOHop_LDSI_H_C1_V1, PLAYDOHop_LDSI_H_C2_C1, PLAYDOHop_LDSI_H_C2_C2, PLAYDOHop_LDSI_H_C2_C3, PLAYDOHop_LDSI_H_C2_V1, PLAYDOHop_LDSI_H_C3_C1, PLAYDOHop_LDSI_H_C3_C2, PLAYDOHop_LDSI_H_C3_C3, PLAYDOHop_LDSI_H_C3_V1, PLAYDOHop_LDSI_H_V1_C1, PLAYDOHop_LDSI_H_V1_C2, PLAYDOHop_LDSI_H_V1_C3, PLAYDOHop_LDSI_H_V1_V1, PLAYDOHop_LDSI_Q_C1_C1, PLAYDOHop_LDSI_Q_C1_C2, PLAYDOHop_LDSI_Q_C1_C3, PLAYDOHop_LDSI_Q_C1_V1, PLAYDOHop_LDSI_Q_C2_C1, PLAYDOHop_LDSI_Q_C2_C2, PLAYDOHop_LDSI_Q_C2_C3, PLAYDOHop_LDSI_Q_C2_V1, PLAYDOHop_LDSI_Q_C3_C1, PLAYDOHop_LDSI_Q_C3_C2, PLAYDOHop_LDSI_Q_C3_C3, PLAYDOHop_LDSI_Q_C3_V1, PLAYDOHop_LDSI_Q_V1_C1, PLAYDOHop_LDSI_Q_V1_C2, PLAYDOHop_LDSI_Q_V1_C3, PLAYDOHop_LDSI_Q_V1_V1, PLAYDOHop_LDSI_W_C1_C1, PLAYDOHop_LDSI_W_C1_C2, PLAYDOHop_LDSI_W_C1_C3, PLAYDOHop_LDSI_W_C1_V1, PLAYDOHop_LDSI_W_C2_C1, PLAYDOHop_LDSI_W_C2_C2, PLAYDOHop_LDSI_W_C2_C3, PLAYDOHop_LDSI_W_C2_V1, PLAYDOHop_LDSI_W_C3_C1, PLAYDOHop_LDSI_W_C3_C2, PLAYDOHop_LDSI_W_C3_C3, PLAYDOHop_LDSI_W_C3_V1, PLAYDOHop_LDSI_W_V1_C1, PLAYDOHop_LDSI_W_V1_C2, PLAYDOHop_LDSI_W_V1_C3, PLAYDOHop_LDSI_W_V1_V1, PLAYDOHop_LDV_B, PLAYDOHop_LDV_H, PLAYDOHop_LDV_Q, PLAYDOHop_LDV_W, PLAYDOHop_LI_B_C1_C1, PLAYDOHop_LI_B_C1_C2, PLAYDOHop_LI_B_C1_C3, PLAYDOHop_LI_B_C1_V1, PLAYDOHop_LI_B_C2_C1, PLAYDOHop_LI_B_C2_C2, PLAYDOHop_LI_B_C2_C3, PLAYDOHop_LI_B_C2_V1, PLAYDOHop_LI_B_C3_C1, PLAYDOHop_LI_B_C3_C2, PLAYDOHop_LI_B_C3_C3, PLAYDOHop_LI_B_C3_V1, PLAYDOHop_LI_B_V1_C1, PLAYDOHop_LI_B_V1_C2, PLAYDOHop_LI_B_V1_C3, PLAYDOHop_LI_B_V1_V1, PLAYDOHop_LI_H_C1_C1, PLAYDOHop_LI_H_C1_C2, PLAYDOHop_LI_H_C1_C3, PLAYDOHop_LI_H_C1_V1, PLAYDOHop_LI_H_C2_C1, PLAYDOHop_LI_H_C2_C2, PLAYDOHop_LI_H_C2_C3, PLAYDOHop_LI_H_C2_V1, PLAYDOHop_LI_H_C3_C1, PLAYDOHop_LI_H_C3_C2, PLAYDOHop_LI_H_C3_C3, PLAYDOHop_LI_H_C3_V1, PLAYDOHop_LI_H_V1_C1, PLAYDOHop_LI_H_V1_C2, PLAYDOHop_LI_H_V1_C3, PLAYDOHop_LI_H_V1_V1, PLAYDOHop_LI_Q_C1_C1, PLAYDOHop_LI_Q_C1_C2, PLAYDOHop_LI_Q_C1_C3, PLAYDOHop_LI_Q_C1_V1, PLAYDOHop_LI_Q_C2_C1, PLAYDOHop_LI_Q_C2_C2, PLAYDOHop_LI_Q_C2_C3, PLAYDOHop_LI_Q_C2_V1, PLAYDOHop_LI_Q_C3_C1, PLAYDOHop_LI_Q_C3_C2, PLAYDOHop_LI_Q_C3_C3, PLAYDOHop_LI_Q_C3_V1, PLAYDOHop_LI_Q_V1_C1, PLAYDOHop_LI_Q_V1_C2, PLAYDOHop_LI_Q_V1_C3, PLAYDOHop_LI_Q_V1_V1, PLAYDOHop_LI_W_C1_C1, PLAYDOHop_LI_W_C1_C2, PLAYDOHop_LI_W_C1_C3, PLAYDOHop_LI_W_C1_V1, PLAYDOHop_LI_W_C2_C1, PLAYDOHop_LI_W_C2_C2, PLAYDOHop_LI_W_C2_C3, PLAYDOHop_LI_W_C2_V1, PLAYDOHop_LI_W_C3_C1, PLAYDOHop_LI_W_C3_C2, PLAYDOHop_LI_W_C3_C3, PLAYDOHop_LI_W_C3_V1, PLAYDOHop_LI_W_V1_C1, PLAYDOHop_LI_W_V1_C2, PLAYDOHop_LI_W_V1_C3, PLAYDOHop_LI_W_V1_V1, PLAYDOHop_M_NO_OP, PLAYDOHop_MOVEBB, PLAYDOHop_MOVECG, PLAYDOHop_MOVEFG_L, PLAYDOHop_MOVEFG_U, PLAYDOHop_MOVEGBP, PLAYDOHop_MOVEGC, PLAYDOHop_MOVEGCM, PLAYDOHop_MOVEGF_L, PLAYDOHop_MOVEGF_U, PLAYDOHop_MOVEGG, PLAYDOHop_MOVELB, PLAYDOHop_MOVELBS, PLAYDOHop_MOVELBX, PLAYDOHop_MOVELF, PLAYDOHop_MOVELFS, PLAYDOHop_MOVELG, PLAYDOHop_MOVELGS, PLAYDOHop_MOVELGX, PLAYDOHop_MOVEPG, PLAYDOHop_PBRA, PLAYDOHop_PBRAL, PLAYDOHop_PBRALBS, PLAYDOHop_PBRR, PLAYDOHop_PBRRL, PLAYDOHop_PBRRLBS, PLAYDOHop_RESTORE, PLAYDOHop_S_B_C1, PLAYDOHop_S_B_C2, PLAYDOHop_S_B_C3, PLAYDOHop_S_B_V1, PLAYDOHop_S_H_C1, PLAYDOHop_S_H_C2, PLAYDOHop_S_H_C3, PLAYDOHop_S_H_V1, PLAYDOHop_S_Q_C1, PLAYDOHop_S_Q_C2, PLAYDOHop_S_Q_C3, PLAYDOHop_S_Q_V1, PLAYDOHop_S_W_C1, PLAYDOHop_S_W_C2, PLAYDOHop_S_W_C3, PLAYDOHop_S_W_V1, PLAYDOHop_SAVE, PLAYDOHop_SH1ADDL, PLAYDOHop_SH2ADDL, PLAYDOHop_SH3ADDL, PLAYDOHop_SI_B_C1, PLAYDOHop_SI_B_C2, PLAYDOHop_SI_B_C3, PLAYDOHop_SI_B_V1, PLAYDOHop_SI_H_C1, PLAYDOHop_SI_H_C2, PLAYDOHop_SI_H_C3, PLAYDOHop_SI_H_V1, PLAYDOHop_SI_Q_C1, PLAYDOHop_SI_Q_C2, PLAYDOHop_SI_Q_C3, PLAYDOHop_SI_Q_V1, PLAYDOHop_SI_W_C1, PLAYDOHop_SI_W_C2, PLAYDOHop_SI_W_C3, PLAYDOHop_SI_W_V1, PLAYDOHop_VEXTRSB, PLAYDOHop_VEXTRSH, PLAYDOHop_VFL_D_C1_C1, PLAYDOHop_VFL_S_C1_C1, PLAYDOHop_VFLE_D_C1_C1, PLAYDOHop_VFLE_S_C1_C1, PLAYDOHop_VFS_D_C1, PLAYDOHop_VFS_S_C1, PLAYDOHop_VFSE_D_C1, PLAYDOHop_VFSE_S_C1, PLAYDOHop_VL_B_C1_C1, PLAYDOHop_VL_H_C1_C1, PLAYDOHop_VL_W_C1_C1, PLAYDOHop_VLE_B_C1_C1, PLAYDOHop_VLE_H_C1_C1, PLAYDOHop_VLE_W_C1_C1, PLAYDOHop_VS_B_C1, PLAYDOHop_VS_H_C1, PLAYDOHop_VS_W_C1, PLAYDOHop_VSE_B_C1, PLAYDOHop_VSE_H_C1, PLAYDOHop_VSE_W_C1, PLAYDOHopcode_BRCF, PLAYDOHopcode_BRCT, PLAYDOHopcode_BRDVF, PLAYDOHopcode_BRDVI, PLAYDOHopcode_BRESTORE, PLAYDOHopcode_BRF_B_B_F, PLAYDOHopcode_BRF_B_F_F, PLAYDOHopcode_BRF_F_B_B, PLAYDOHopcode_BRF_F_F_B, PLAYDOHopcode_BRF_F_F_F, PLAYDOHopcode_BRL, PLAYDOHopcode_BRLC, PLAYDOHopcode_BRU, PLAYDOHopcode_BRW_B_B_F, PLAYDOHopcode_BRW_B_F_F, PLAYDOHopcode_BRW_F_B_B, PLAYDOHopcode_BRW_F_F_B, PLAYDOHopcode_BRW_F_F_F, PLAYDOHopcode_BSAVE, PLAYDOHopcode_CMPR_EV, PLAYDOHopcode_CMPR_FALSE, PLAYDOHopcode_CMPR_OD, PLAYDOHopcode_CMPR_TRUE, PLAYDOHopcode_EXTRSB, PLAYDOHopcode_EXTRSH, PLAYDOHopcode_FCMPR_D_FALSE, PLAYDOHopcode_FCMPR_D_TRUE, PLAYDOHopcode_FCMPR_S_FALSE, PLAYDOHopcode_FCMPR_S_TRUE, PLAYDOHopcode_FL_D_C1_C1, PLAYDOHopcode_FL_D_C1_C2, PLAYDOHopcode_FL_D_C1_C3, PLAYDOHopcode_FL_D_C1_V1, PLAYDOHopcode_FL_D_C2_C1, PLAYDOHopcode_FL_D_C2_C2, PLAYDOHopcode_FL_D_C2_C3, PLAYDOHopcode_FL_D_C2_V1, PLAYDOHopcode_FL_D_C3_C1, PLAYDOHopcode_FL_D_C3_C2, PLAYDOHopcode_FL_D_C3_C3, PLAYDOHopcode_FL_D_C3_V1, PLAYDOHopcode_FL_D_V1_C1, PLAYDOHopcode_FL_D_V1_C2, PLAYDOHopcode_FL_D_V1_C3, PLAYDOHopcode_FL_D_V1_V1, PLAYDOHopcode_FL_S_C1_C1, PLAYDOHopcode_FL_S_C1_C2, PLAYDOHopcode_FL_S_C1_C3, PLAYDOHopcode_FL_S_C1_V1, PLAYDOHopcode_FL_S_C2_C1, PLAYDOHopcode_FL_S_C2_C2, PLAYDOHopcode_FL_S_C2_C3, PLAYDOHopcode_FL_S_C2_V1, PLAYDOHopcode_FL_S_C3_C1, PLAYDOHopcode_FL_S_C3_C2, PLAYDOHopcode_FL_S_C3_C3, PLAYDOHopcode_FL_S_C3_V1, PLAYDOHopcode_FL_S_V1_C1, PLAYDOHopcode_FL_S_V1_C2, PLAYDOHopcode_FL_S_V1_C3, PLAYDOHopcode_FL_S_V1_V1, PLAYDOHopcode_FLDS_D_C1_C1, PLAYDOHopcode_FLDS_D_C1_C2, PLAYDOHopcode_FLDS_D_C1_C3, PLAYDOHopcode_FLDS_D_C1_V1, PLAYDOHopcode_FLDS_D_C2_C1, PLAYDOHopcode_FLDS_D_C2_C2, PLAYDOHopcode_FLDS_D_C2_C3, PLAYDOHopcode_FLDS_D_C2_V1, PLAYDOHopcode_FLDS_D_C3_C1, PLAYDOHopcode_FLDS_D_C3_C2, PLAYDOHopcode_FLDS_D_C3_C3, PLAYDOHopcode_FLDS_D_C3_V1, PLAYDOHopcode_FLDS_D_V1_C1, PLAYDOHopcode_FLDS_D_V1_C2, PLAYDOHopcode_FLDS_D_V1_C3, PLAYDOHopcode_FLDS_D_V1_V1, PLAYDOHopcode_FLDS_S_C1_C1, PLAYDOHopcode_FLDS_S_C1_C2, PLAYDOHopcode_FLDS_S_C1_C3, PLAYDOHopcode_FLDS_S_C1_V1, PLAYDOHopcode_FLDS_S_C2_C1, PLAYDOHopcode_FLDS_S_C2_C2, PLAYDOHopcode_FLDS_S_C2_C3, PLAYDOHopcode_FLDS_S_C2_V1, PLAYDOHopcode_FLDS_S_C3_C1, PLAYDOHopcode_FLDS_S_C3_C2, PLAYDOHopcode_FLDS_S_C3_C3, PLAYDOHopcode_FLDS_S_C3_V1, PLAYDOHopcode_FLDS_S_V1_C1, PLAYDOHopcode_FLDS_S_V1_C2, PLAYDOHopcode_FLDS_S_V1_C3, PLAYDOHopcode_FLDS_S_V1_V1, PLAYDOHopcode_FLDSI_D_C1_C1, PLAYDOHopcode_FLDSI_D_C1_C2, PLAYDOHopcode_FLDSI_D_C1_C3, PLAYDOHopcode_FLDSI_D_C1_V1, PLAYDOHopcode_FLDSI_D_C2_C1, PLAYDOHopcode_FLDSI_D_C2_C2, PLAYDOHopcode_FLDSI_D_C2_C3, PLAYDOHopcode_FLDSI_D_C2_V1, PLAYDOHopcode_FLDSI_D_C3_C1, PLAYDOHopcode_FLDSI_D_C3_C2, PLAYDOHopcode_FLDSI_D_C3_C3, PLAYDOHopcode_FLDSI_D_C3_V1, PLAYDOHopcode_FLDSI_D_V1_C1, PLAYDOHopcode_FLDSI_D_V1_C2, PLAYDOHopcode_FLDSI_D_V1_C3, PLAYDOHopcode_FLDSI_D_V1_V1, PLAYDOHopcode_FLDSI_S_C1_C1, PLAYDOHopcode_FLDSI_S_C1_C2, PLAYDOHopcode_FLDSI_S_C1_C3, PLAYDOHopcode_FLDSI_S_C1_V1, PLAYDOHopcode_FLDSI_S_C2_C1, PLAYDOHopcode_FLDSI_S_C2_C2, PLAYDOHopcode_FLDSI_S_C2_C3, PLAYDOHopcode_FLDSI_S_C2_V1, PLAYDOHopcode_FLDSI_S_C3_C1, PLAYDOHopcode_FLDSI_S_C3_C2, PLAYDOHopcode_FLDSI_S_C3_C3, PLAYDOHopcode_FLDSI_S_C3_V1, PLAYDOHopcode_FLDSI_S_V1_C1, PLAYDOHopcode_FLDSI_S_V1_C2, PLAYDOHopcode_FLDSI_S_V1_C3, PLAYDOHopcode_FLDSI_S_V1_V1, PLAYDOHopcode_FLDV_D, PLAYDOHopcode_FLDV_S, PLAYDOHopcode_FLI_D_C1_C1, PLAYDOHopcode_FLI_D_C1_C2, PLAYDOHopcode_FLI_D_C1_C3, PLAYDOHopcode_FLI_D_C1_V1, PLAYDOHopcode_FLI_D_C2_C1, PLAYDOHopcode_FLI_D_C2_C2, PLAYDOHopcode_FLI_D_C2_C3, PLAYDOHopcode_FLI_D_C2_V1, PLAYDOHopcode_FLI_D_C3_C1, PLAYDOHopcode_FLI_D_C3_C2, PLAYDOHopcode_FLI_D_C3_C3, PLAYDOHopcode_FLI_D_C3_V1, PLAYDOHopcode_FLI_D_V1_C1, PLAYDOHopcode_FLI_D_V1_C2, PLAYDOHopcode_FLI_D_V1_C3, PLAYDOHopcode_FLI_D_V1_V1, PLAYDOHopcode_FLI_S_C1_C1, PLAYDOHopcode_FLI_S_C1_C2, PLAYDOHopcode_FLI_S_C1_C3, PLAYDOHopcode_FLI_S_C1_V1, PLAYDOHopcode_FLI_S_C2_C1, PLAYDOHopcode_FLI_S_C2_C2, PLAYDOHopcode_FLI_S_C2_C3, PLAYDOHopcode_FLI_S_C2_V1, PLAYDOHopcode_FLI_S_C3_C1, PLAYDOHopcode_FLI_S_C3_C2, PLAYDOHopcode_FLI_S_C3_C3, PLAYDOHopcode_FLI_S_C3_V1, PLAYDOHopcode_FLI_S_V1_C1, PLAYDOHopcode_FLI_S_V1_C2, PLAYDOHopcode_FLI_S_V1_C3, PLAYDOHopcode_FLI_S_V1_V1, PLAYDOHopcode_FMPYADDN_D, PLAYDOHopcode_FMPYADDN_S, PLAYDOHopcode_FRESTORE_D, PLAYDOHopcode_FRESTORE_S, PLAYDOHopcode_FS_D_C1, PLAYDOHopcode_FS_D_C2, PLAYDOHopcode_FS_D_C3, PLAYDOHopcode_FS_D_V1, PLAYDOHopcode_FS_S_C1, PLAYDOHopcode_FS_S_C2, PLAYDOHopcode_FS_S_C3, PLAYDOHopcode_FS_S_V1, PLAYDOHopcode_FSAVE_D, PLAYDOHopcode_FSAVE_S, PLAYDOHopcode_FSI_D_C1, PLAYDOHopcode_FSI_D_C2, PLAYDOHopcode_FSI_D_C3, PLAYDOHopcode_FSI_D_V1, PLAYDOHopcode_FSI_S_C1, PLAYDOHopcode_FSI_S_C2, PLAYDOHopcode_FSI_S_C3, PLAYDOHopcode_FSI_S_V1, PLAYDOHopcode_L_B_C1_C1, PLAYDOHopcode_L_B_C1_C2, PLAYDOHopcode_L_B_C1_C3, PLAYDOHopcode_L_B_C1_V1, PLAYDOHopcode_L_B_C2_C1, PLAYDOHopcode_L_B_C2_C2, PLAYDOHopcode_L_B_C2_C3, PLAYDOHopcode_L_B_C2_V1, PLAYDOHopcode_L_B_C3_C1, PLAYDOHopcode_L_B_C3_C2, PLAYDOHopcode_L_B_C3_C3, PLAYDOHopcode_L_B_C3_V1, PLAYDOHopcode_L_B_V1_C1, PLAYDOHopcode_L_B_V1_C2, PLAYDOHopcode_L_B_V1_C3, PLAYDOHopcode_L_B_V1_V1, PLAYDOHopcode_L_H_C1_C1, PLAYDOHopcode_L_H_C1_C2, PLAYDOHopcode_L_H_C1_C3, PLAYDOHopcode_L_H_C1_V1, PLAYDOHopcode_L_H_C2_C1, PLAYDOHopcode_L_H_C2_C2, PLAYDOHopcode_L_H_C2_C3, PLAYDOHopcode_L_H_C2_V1, PLAYDOHopcode_L_H_C3_C1, PLAYDOHopcode_L_H_C3_C2, PLAYDOHopcode_L_H_C3_C3, PLAYDOHopcode_L_H_C3_V1, PLAYDOHopcode_L_H_V1_C1, PLAYDOHopcode_L_H_V1_C2, PLAYDOHopcode_L_H_V1_C3, PLAYDOHopcode_L_H_V1_V1, PLAYDOHopcode_L_Q_C1_C1, PLAYDOHopcode_L_Q_C1_C2, PLAYDOHopcode_L_Q_C1_C3, PLAYDOHopcode_L_Q_C1_V1, PLAYDOHopcode_L_Q_C2_C1, PLAYDOHopcode_L_Q_C2_C2, PLAYDOHopcode_L_Q_C2_C3, PLAYDOHopcode_L_Q_C2_V1, PLAYDOHopcode_L_Q_C3_C1, PLAYDOHopcode_L_Q_C3_C2, PLAYDOHopcode_L_Q_C3_C3, PLAYDOHopcode_L_Q_C3_V1, PLAYDOHopcode_L_Q_V1_C1, PLAYDOHopcode_L_Q_V1_C2, PLAYDOHopcode_L_Q_V1_C3, PLAYDOHopcode_L_Q_V1_V1, PLAYDOHopcode_L_W_C1_C1, PLAYDOHopcode_L_W_C1_C2, PLAYDOHopcode_L_W_C1_C3, PLAYDOHopcode_L_W_C1_V1, PLAYDOHopcode_L_W_C2_C1, PLAYDOHopcode_L_W_C2_C2, PLAYDOHopcode_L_W_C2_C3, PLAYDOHopcode_L_W_C2_V1, PLAYDOHopcode_L_W_C3_C1, PLAYDOHopcode_L_W_C3_C2, PLAYDOHopcode_L_W_C3_C3, PLAYDOHopcode_L_W_C3_V1, PLAYDOHopcode_L_W_V1_C1, PLAYDOHopcode_L_W_V1_C2, PLAYDOHopcode_L_W_V1_C3, PLAYDOHopcode_L_W_V1_V1, PLAYDOHopcode_LDCM, PLAYDOHopcode_LDS_B_C1_C1, PLAYDOHopcode_LDS_B_C1_C2, PLAYDOHopcode_LDS_B_C1_C3, PLAYDOHopcode_LDS_B_C1_V1, PLAYDOHopcode_LDS_B_C2_C1, PLAYDOHopcode_LDS_B_C2_C2, PLAYDOHopcode_LDS_B_C2_C3, PLAYDOHopcode_LDS_B_C2_V1, PLAYDOHopcode_LDS_B_C3_C1, PLAYDOHopcode_LDS_B_C3_C2, PLAYDOHopcode_LDS_B_C3_C3, PLAYDOHopcode_LDS_B_C3_V1, PLAYDOHopcode_LDS_B_V1_C1, PLAYDOHopcode_LDS_B_V1_C2, PLAYDOHopcode_LDS_B_V1_C3, PLAYDOHopcode_LDS_B_V1_V1, PLAYDOHopcode_LDS_H_C1_C1, PLAYDOHopcode_LDS_H_C1_C2, PLAYDOHopcode_LDS_H_C1_C3, PLAYDOHopcode_LDS_H_C1_V1, PLAYDOHopcode_LDS_H_C2_C1, PLAYDOHopcode_LDS_H_C2_C2, PLAYDOHopcode_LDS_H_C2_C3, PLAYDOHopcode_LDS_H_C2_V1, PLAYDOHopcode_LDS_H_C3_C1, PLAYDOHopcode_LDS_H_C3_C2, PLAYDOHopcode_LDS_H_C3_C3, PLAYDOHopcode_LDS_H_C3_V1, PLAYDOHopcode_LDS_H_V1_C1, PLAYDOHopcode_LDS_H_V1_C2, PLAYDOHopcode_LDS_H_V1_C3, PLAYDOHopcode_LDS_H_V1_V1, PLAYDOHopcode_LDS_Q_C1_C1, PLAYDOHopcode_LDS_Q_C1_C2, PLAYDOHopcode_LDS_Q_C1_C3, PLAYDOHopcode_LDS_Q_C1_V1, PLAYDOHopcode_LDS_Q_C2_C1, PLAYDOHopcode_LDS_Q_C2_C2, PLAYDOHopcode_LDS_Q_C2_C3, PLAYDOHopcode_LDS_Q_C2_V1, PLAYDOHopcode_LDS_Q_C3_C1, PLAYDOHopcode_LDS_Q_C3_C2, PLAYDOHopcode_LDS_Q_C3_C3, PLAYDOHopcode_LDS_Q_C3_V1, PLAYDOHopcode_LDS_Q_V1_C1, PLAYDOHopcode_LDS_Q_V1_C2, PLAYDOHopcode_LDS_Q_V1_C3, PLAYDOHopcode_LDS_Q_V1_V1, PLAYDOHopcode_LDS_W_C1_C1, PLAYDOHopcode_LDS_W_C1_C2, PLAYDOHopcode_LDS_W_C1_C3, PLAYDOHopcode_LDS_W_C1_V1, PLAYDOHopcode_LDS_W_C2_C1, PLAYDOHopcode_LDS_W_C2_C2, PLAYDOHopcode_LDS_W_C2_C3, PLAYDOHopcode_LDS_W_C2_V1, PLAYDOHopcode_LDS_W_C3_C1, PLAYDOHopcode_LDS_W_C3_C2, PLAYDOHopcode_LDS_W_C3_C3, PLAYDOHopcode_LDS_W_C3_V1, PLAYDOHopcode_LDS_W_V1_C1, PLAYDOHopcode_LDS_W_V1_C2, PLAYDOHopcode_LDS_W_V1_C3, PLAYDOHopcode_LDS_W_V1_V1, PLAYDOHopcode_LDSI_B_C1_C1, PLAYDOHopcode_LDSI_B_C1_C2, PLAYDOHopcode_LDSI_B_C1_C3, PLAYDOHopcode_LDSI_B_C1_V1, PLAYDOHopcode_LDSI_B_C2_C1, PLAYDOHopcode_LDSI_B_C2_C2, PLAYDOHopcode_LDSI_B_C2_C3, PLAYDOHopcode_LDSI_B_C2_V1, PLAYDOHopcode_LDSI_B_C3_C1, PLAYDOHopcode_LDSI_B_C3_C2, PLAYDOHopcode_LDSI_B_C3_C3, PLAYDOHopcode_LDSI_B_C3_V1, PLAYDOHopcode_LDSI_B_V1_C1, PLAYDOHopcode_LDSI_B_V1_C2, PLAYDOHopcode_LDSI_B_V1_C3, PLAYDOHopcode_LDSI_B_V1_V1, PLAYDOHopcode_LDSI_H_C1_C1, PLAYDOHopcode_LDSI_H_C1_C2, PLAYDOHopcode_LDSI_H_C1_C3, PLAYDOHopcode_LDSI_H_C1_V1, PLAYDOHopcode_LDSI_H_C2_C1, PLAYDOHopcode_LDSI_H_C2_C2, PLAYDOHopcode_LDSI_H_C2_C3, PLAYDOHopcode_LDSI_H_C2_V1, PLAYDOHopcode_LDSI_H_C3_C1, PLAYDOHopcode_LDSI_H_C3_C2, PLAYDOHopcode_LDSI_H_C3_C3, PLAYDOHopcode_LDSI_H_C3_V1, PLAYDOHopcode_LDSI_H_V1_C1, PLAYDOHopcode_LDSI_H_V1_C2, PLAYDOHopcode_LDSI_H_V1_C3, PLAYDOHopcode_LDSI_H_V1_V1, PLAYDOHopcode_LDSI_Q_C1_C1, PLAYDOHopcode_LDSI_Q_C1_C2, PLAYDOHopcode_LDSI_Q_C1_C3, PLAYDOHopcode_LDSI_Q_C1_V1, PLAYDOHopcode_LDSI_Q_C2_C1, PLAYDOHopcode_LDSI_Q_C2_C2, PLAYDOHopcode_LDSI_Q_C2_C3, PLAYDOHopcode_LDSI_Q_C2_V1, PLAYDOHopcode_LDSI_Q_C3_C1, PLAYDOHopcode_LDSI_Q_C3_C2, PLAYDOHopcode_LDSI_Q_C3_C3, PLAYDOHopcode_LDSI_Q_C3_V1, PLAYDOHopcode_LDSI_Q_V1_C1, PLAYDOHopcode_LDSI_Q_V1_C2, PLAYDOHopcode_LDSI_Q_V1_C3, PLAYDOHopcode_LDSI_Q_V1_V1, PLAYDOHopcode_LDSI_W_C1_C1, PLAYDOHopcode_LDSI_W_C1_C2, PLAYDOHopcode_LDSI_W_C1_C3, PLAYDOHopcode_LDSI_W_C1_V1, PLAYDOHopcode_LDSI_W_C2_C1, PLAYDOHopcode_LDSI_W_C2_C2, PLAYDOHopcode_LDSI_W_C2_C3, PLAYDOHopcode_LDSI_W_C2_V1, PLAYDOHopcode_LDSI_W_C3_C1, PLAYDOHopcode_LDSI_W_C3_C2, PLAYDOHopcode_LDSI_W_C3_C3, PLAYDOHopcode_LDSI_W_C3_V1, PLAYDOHopcode_LDSI_W_V1_C1, PLAYDOHopcode_LDSI_W_V1_C2, PLAYDOHopcode_LDSI_W_V1_C3, PLAYDOHopcode_LDSI_W_V1_V1, PLAYDOHopcode_LDV_B, PLAYDOHopcode_LDV_H, PLAYDOHopcode_LDV_Q, PLAYDOHopcode_LDV_W, PLAYDOHopcode_LI_B_C1_C1, PLAYDOHopcode_LI_B_C1_C2, PLAYDOHopcode_LI_B_C1_C3, PLAYDOHopcode_LI_B_C1_V1, PLAYDOHopcode_LI_B_C2_C1, PLAYDOHopcode_LI_B_C2_C2, PLAYDOHopcode_LI_B_C2_C3, PLAYDOHopcode_LI_B_C2_V1, PLAYDOHopcode_LI_B_C3_C1, PLAYDOHopcode_LI_B_C3_C2, PLAYDOHopcode_LI_B_C3_C3, PLAYDOHopcode_LI_B_C3_V1, PLAYDOHopcode_LI_B_V1_C1, PLAYDOHopcode_LI_B_V1_C2, PLAYDOHopcode_LI_B_V1_C3, PLAYDOHopcode_LI_B_V1_V1, PLAYDOHopcode_LI_H_C1_C1, PLAYDOHopcode_LI_H_C1_C2, PLAYDOHopcode_LI_H_C1_C3, PLAYDOHopcode_LI_H_C1_V1, PLAYDOHopcode_LI_H_C2_C1, PLAYDOHopcode_LI_H_C2_C2, PLAYDOHopcode_LI_H_C2_C3, PLAYDOHopcode_LI_H_C2_V1, PLAYDOHopcode_LI_H_C3_C1, PLAYDOHopcode_LI_H_C3_C2, PLAYDOHopcode_LI_H_C3_C3, PLAYDOHopcode_LI_H_C3_V1, PLAYDOHopcode_LI_H_V1_C1, PLAYDOHopcode_LI_H_V1_C2, PLAYDOHopcode_LI_H_V1_C3, PLAYDOHopcode_LI_H_V1_V1, PLAYDOHopcode_LI_Q_C1_C1, PLAYDOHopcode_LI_Q_C1_C2, PLAYDOHopcode_LI_Q_C1_C3, PLAYDOHopcode_LI_Q_C1_V1, PLAYDOHopcode_LI_Q_C2_C1, PLAYDOHopcode_LI_Q_C2_C2, PLAYDOHopcode_LI_Q_C2_C3, PLAYDOHopcode_LI_Q_C2_V1, PLAYDOHopcode_LI_Q_C3_C1, PLAYDOHopcode_LI_Q_C3_C2, PLAYDOHopcode_LI_Q_C3_C3, PLAYDOHopcode_LI_Q_C3_V1, PLAYDOHopcode_LI_Q_V1_C1, PLAYDOHopcode_LI_Q_V1_C2, PLAYDOHopcode_LI_Q_V1_C3, PLAYDOHopcode_LI_Q_V1_V1, PLAYDOHopcode_LI_W_C1_C1, PLAYDOHopcode_LI_W_C1_C2, PLAYDOHopcode_LI_W_C1_C3, PLAYDOHopcode_LI_W_C1_V1, PLAYDOHopcode_LI_W_C2_C1, PLAYDOHopcode_LI_W_C2_C2, PLAYDOHopcode_LI_W_C2_C3, PLAYDOHopcode_LI_W_C2_V1, PLAYDOHopcode_LI_W_C3_C1, PLAYDOHopcode_LI_W_C3_C2, PLAYDOHopcode_LI_W_C3_C3, PLAYDOHopcode_LI_W_C3_V1, PLAYDOHopcode_LI_W_V1_C1, PLAYDOHopcode_LI_W_V1_C2, PLAYDOHopcode_LI_W_V1_C3, PLAYDOHopcode_LI_W_V1_V1, PLAYDOHopcode_M_NO_OP, PLAYDOHopcode_MOVEBB, PLAYDOHopcode_MOVECG, PLAYDOHopcode_MOVEFG_L, PLAYDOHopcode_MOVEFG_U, PLAYDOHopcode_MOVEGBP, PLAYDOHopcode_MOVEGC, PLAYDOHopcode_MOVEGCM, PLAYDOHopcode_MOVEGF_L, PLAYDOHopcode_MOVEGF_U, PLAYDOHopcode_MOVEGG, PLAYDOHopcode_MOVELB, PLAYDOHopcode_MOVELBS, PLAYDOHopcode_MOVELBX, PLAYDOHopcode_MOVELF, PLAYDOHopcode_MOVELFS, PLAYDOHopcode_MOVELG, PLAYDOHopcode_MOVELGS, PLAYDOHopcode_MOVELGX, PLAYDOHopcode_MOVEPG, PLAYDOHopcode_PBRA, PLAYDOHopcode_PBRAL, PLAYDOHopcode_PBRALBS, PLAYDOHopcode_PBRR, PLAYDOHopcode_PBRRL, PLAYDOHopcode_PBRRLBS, PLAYDOHopcode_RESTORE, PLAYDOHopcode_S_B_C1, PLAYDOHopcode_S_B_C2, PLAYDOHopcode_S_B_C3, PLAYDOHopcode_S_B_V1, PLAYDOHopcode_S_H_C1, PLAYDOHopcode_S_H_C2, PLAYDOHopcode_S_H_C3, PLAYDOHopcode_S_H_V1, PLAYDOHopcode_S_Q_C1, PLAYDOHopcode_S_Q_C2, PLAYDOHopcode_S_Q_C3, PLAYDOHopcode_S_Q_V1, PLAYDOHopcode_S_W_C1, PLAYDOHopcode_S_W_C2, PLAYDOHopcode_S_W_C3, PLAYDOHopcode_S_W_V1, PLAYDOHopcode_SAVE, PLAYDOHopcode_SH1ADDL, PLAYDOHopcode_SH2ADDL, PLAYDOHopcode_SH3ADDL, PLAYDOHopcode_SI_B_C1, PLAYDOHopcode_SI_B_C2, PLAYDOHopcode_SI_B_C3, PLAYDOHopcode_SI_B_V1, PLAYDOHopcode_SI_H_C1, PLAYDOHopcode_SI_H_C2, PLAYDOHopcode_SI_H_C3, PLAYDOHopcode_SI_H_V1, PLAYDOHopcode_SI_Q_C1, PLAYDOHopcode_SI_Q_C2, PLAYDOHopcode_SI_Q_C3, PLAYDOHopcode_SI_Q_V1, PLAYDOHopcode_SI_W_C1, PLAYDOHopcode_SI_W_C2, PLAYDOHopcode_SI_W_C3, PLAYDOHopcode_SI_W_V1, PLAYDOHopcode_VEXTRSB, PLAYDOHopcode_VEXTRSH, PLAYDOHopcode_VFL_D_C1_C1, PLAYDOHopcode_VFL_S_C1_C1, PLAYDOHopcode_VFLE_D_C1_C1, PLAYDOHopcode_VFLE_S_C1_C1, PLAYDOHopcode_VFS_D_C1, PLAYDOHopcode_VFS_S_C1, PLAYDOHopcode_VFSE_D_C1, PLAYDOHopcode_VFSE_S_C1, PLAYDOHopcode_VL_B_C1_C1, PLAYDOHopcode_VL_H_C1_C1, PLAYDOHopcode_VL_W_C1_C1, PLAYDOHopcode_VLE_B_C1_C1, PLAYDOHopcode_VLE_H_C1_C1, PLAYDOHopcode_VLE_W_C1_C1, PLAYDOHopcode_VS_B_C1, PLAYDOHopcode_VS_H_C1, PLAYDOHopcode_VS_W_C1, PLAYDOHopcode_VSE_B_C1, PLAYDOHopcode_VSE_H_C1, and PLAYDOHopcode_VSE_W_C1.
Referenced by M_get_opcode_name().
int M_is_stack_operand_playdoh (L_Operand * operand)
Definition at line 3864 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_playdoh (L_Operand * operand)
Definition at line 3889 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_playdoh (L_Oper * oper, char * name)
Definition at line 3694 of file ml_hpl_pd.c.
References has_label_operand, indexed_memory_op, long_pos_int_inc, M_assert(), M_playdoh_model, M_PLAYDOH_V1, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_playdoh (int ctype)
Definition at line 3846 of file ml_hpl_pd.c.
Referenced by M_num_registers().
int M_opc_from_proc_opc_playdoh (int proc_opc)
Definition at line 4176 of file ml_hpl_pd.c.
References M_assert(), PLAYDOHop_BRCF, PLAYDOHop_BRCT, PLAYDOHop_BRDVF, PLAYDOHop_BRDVI, PLAYDOHop_BRESTORE, PLAYDOHop_BRF_B_B_F, PLAYDOHop_BRF_B_F_F, PLAYDOHop_BRF_F_B_B, PLAYDOHop_BRF_F_F_B, PLAYDOHop_BRF_F_F_F, PLAYDOHop_BRL, PLAYDOHop_BRLC, PLAYDOHop_BRU, PLAYDOHop_BRW_B_B_F, PLAYDOHop_BRW_B_F_F, PLAYDOHop_BRW_F_B_B, PLAYDOHop_BRW_F_F_B, PLAYDOHop_BRW_F_F_F, PLAYDOHop_BSAVE, PLAYDOHop_CMPR_EV, PLAYDOHop_CMPR_FALSE, PLAYDOHop_CMPR_OD, PLAYDOHop_CMPR_TRUE, PLAYDOHop_EXTRSB, PLAYDOHop_EXTRSH, PLAYDOHop_FCMPR_D_FALSE, PLAYDOHop_FCMPR_D_TRUE, PLAYDOHop_FCMPR_S_FALSE, PLAYDOHop_FCMPR_S_TRUE, PLAYDOHop_FL_D_C1_C1, PLAYDOHop_FL_D_C1_C2, PLAYDOHop_FL_D_C1_C3, PLAYDOHop_FL_D_C1_V1, PLAYDOHop_FL_D_C2_C1, PLAYDOHop_FL_D_C2_C2, PLAYDOHop_FL_D_C2_C3, PLAYDOHop_FL_D_C2_V1, PLAYDOHop_FL_D_C3_C1, PLAYDOHop_FL_D_C3_C2, PLAYDOHop_FL_D_C3_C3, PLAYDOHop_FL_D_C3_V1, PLAYDOHop_FL_D_V1_C1, PLAYDOHop_FL_D_V1_C2, PLAYDOHop_FL_D_V1_C3, PLAYDOHop_FL_D_V1_V1, PLAYDOHop_FL_S_C1_C1, PLAYDOHop_FL_S_C1_C2, PLAYDOHop_FL_S_C1_C3, PLAYDOHop_FL_S_C1_V1, PLAYDOHop_FL_S_C2_C1, PLAYDOHop_FL_S_C2_C2, PLAYDOHop_FL_S_C2_C3, PLAYDOHop_FL_S_C2_V1, PLAYDOHop_FL_S_C3_C1, PLAYDOHop_FL_S_C3_C2, PLAYDOHop_FL_S_C3_C3, PLAYDOHop_FL_S_C3_V1, PLAYDOHop_FL_S_V1_C1, PLAYDOHop_FL_S_V1_C2, PLAYDOHop_FL_S_V1_C3, PLAYDOHop_FL_S_V1_V1, PLAYDOHop_FLDS_D_C1_C1, PLAYDOHop_FLDS_D_C1_C2, PLAYDOHop_FLDS_D_C1_C3, PLAYDOHop_FLDS_D_C1_V1, PLAYDOHop_FLDS_D_C2_C1, PLAYDOHop_FLDS_D_C2_C2, PLAYDOHop_FLDS_D_C2_C3, PLAYDOHop_FLDS_D_C2_V1, PLAYDOHop_FLDS_D_C3_C1, PLAYDOHop_FLDS_D_C3_C2, PLAYDOHop_FLDS_D_C3_C3, PLAYDOHop_FLDS_D_C3_V1, PLAYDOHop_FLDS_D_V1_C1, PLAYDOHop_FLDS_D_V1_C2, PLAYDOHop_FLDS_D_V1_C3, PLAYDOHop_FLDS_D_V1_V1, PLAYDOHop_FLDS_S_C1_C1, PLAYDOHop_FLDS_S_C1_C2, PLAYDOHop_FLDS_S_C1_C3, PLAYDOHop_FLDS_S_C1_V1, PLAYDOHop_FLDS_S_C2_C1, PLAYDOHop_FLDS_S_C2_C2, PLAYDOHop_FLDS_S_C2_C3, PLAYDOHop_FLDS_S_C2_V1, PLAYDOHop_FLDS_S_C3_C1, PLAYDOHop_FLDS_S_C3_C2, PLAYDOHop_FLDS_S_C3_C3, PLAYDOHop_FLDS_S_C3_V1, PLAYDOHop_FLDS_S_V1_C1, PLAYDOHop_FLDS_S_V1_C2, PLAYDOHop_FLDS_S_V1_C3, PLAYDOHop_FLDS_S_V1_V1, PLAYDOHop_FLDSI_D_C1_C1, PLAYDOHop_FLDSI_D_C1_C2, PLAYDOHop_FLDSI_D_C1_C3, PLAYDOHop_FLDSI_D_C1_V1, PLAYDOHop_FLDSI_D_C2_C1, PLAYDOHop_FLDSI_D_C2_C2, PLAYDOHop_FLDSI_D_C2_C3, PLAYDOHop_FLDSI_D_C2_V1, PLAYDOHop_FLDSI_D_C3_C1, PLAYDOHop_FLDSI_D_C3_C2, PLAYDOHop_FLDSI_D_C3_C3, PLAYDOHop_FLDSI_D_C3_V1, PLAYDOHop_FLDSI_D_V1_C1, PLAYDOHop_FLDSI_D_V1_C2, PLAYDOHop_FLDSI_D_V1_C3, PLAYDOHop_FLDSI_D_V1_V1, PLAYDOHop_FLDSI_S_C1_C1, PLAYDOHop_FLDSI_S_C1_C2, PLAYDOHop_FLDSI_S_C1_C3, PLAYDOHop_FLDSI_S_C1_V1, PLAYDOHop_FLDSI_S_C2_C1, PLAYDOHop_FLDSI_S_C2_C2, PLAYDOHop_FLDSI_S_C2_C3, PLAYDOHop_FLDSI_S_C2_V1, PLAYDOHop_FLDSI_S_C3_C1, PLAYDOHop_FLDSI_S_C3_C2, PLAYDOHop_FLDSI_S_C3_C3, PLAYDOHop_FLDSI_S_C3_V1, PLAYDOHop_FLDSI_S_V1_C1, PLAYDOHop_FLDSI_S_V1_C2, PLAYDOHop_FLDSI_S_V1_C3, PLAYDOHop_FLDSI_S_V1_V1, PLAYDOHop_FLDV_D, PLAYDOHop_FLDV_S, PLAYDOHop_FLI_D_C1_C1, PLAYDOHop_FLI_D_C1_C2, PLAYDOHop_FLI_D_C1_C3, PLAYDOHop_FLI_D_C1_V1, PLAYDOHop_FLI_D_C2_C1, PLAYDOHop_FLI_D_C2_C2, PLAYDOHop_FLI_D_C2_C3, PLAYDOHop_FLI_D_C2_V1, PLAYDOHop_FLI_D_C3_C1, PLAYDOHop_FLI_D_C3_C2, PLAYDOHop_FLI_D_C3_C3, PLAYDOHop_FLI_D_C3_V1, PLAYDOHop_FLI_D_V1_C1, PLAYDOHop_FLI_D_V1_C2, PLAYDOHop_FLI_D_V1_C3, PLAYDOHop_FLI_D_V1_V1, PLAYDOHop_FLI_S_C1_C1, PLAYDOHop_FLI_S_C1_C2, PLAYDOHop_FLI_S_C1_C3, PLAYDOHop_FLI_S_C1_V1, PLAYDOHop_FLI_S_C2_C1, PLAYDOHop_FLI_S_C2_C2, PLAYDOHop_FLI_S_C2_C3, PLAYDOHop_FLI_S_C2_V1, PLAYDOHop_FLI_S_C3_C1, PLAYDOHop_FLI_S_C3_C2, PLAYDOHop_FLI_S_C3_C3, PLAYDOHop_FLI_S_C3_V1, PLAYDOHop_FLI_S_V1_C1, PLAYDOHop_FLI_S_V1_C2, PLAYDOHop_FLI_S_V1_C3, PLAYDOHop_FLI_S_V1_V1, PLAYDOHop_FMPYADDN_D, PLAYDOHop_FMPYADDN_S, PLAYDOHop_FRESTORE_D, PLAYDOHop_FRESTORE_S, PLAYDOHop_FS_D_C1, PLAYDOHop_FS_D_C2, PLAYDOHop_FS_D_C3, PLAYDOHop_FS_D_V1, PLAYDOHop_FS_S_C1, PLAYDOHop_FS_S_C2, PLAYDOHop_FS_S_C3, PLAYDOHop_FS_S_V1, PLAYDOHop_FSAVE_D, PLAYDOHop_FSAVE_S, PLAYDOHop_FSI_D_C1, PLAYDOHop_FSI_D_C2, PLAYDOHop_FSI_D_C3, PLAYDOHop_FSI_D_V1, PLAYDOHop_FSI_S_C1, PLAYDOHop_FSI_S_C2, PLAYDOHop_FSI_S_C3, PLAYDOHop_FSI_S_V1, PLAYDOHop_L_B_C1_C1, PLAYDOHop_L_B_C1_C2, PLAYDOHop_L_B_C1_C3, PLAYDOHop_L_B_C1_V1, PLAYDOHop_L_B_C2_C1, PLAYDOHop_L_B_C2_C2, PLAYDOHop_L_B_C2_C3, PLAYDOHop_L_B_C2_V1, PLAYDOHop_L_B_C3_C1, PLAYDOHop_L_B_C3_C2, PLAYDOHop_L_B_C3_C3, PLAYDOHop_L_B_C3_V1, PLAYDOHop_L_B_V1_C1, PLAYDOHop_L_B_V1_C2, PLAYDOHop_L_B_V1_C3, PLAYDOHop_L_B_V1_V1, PLAYDOHop_L_H_C1_C1, PLAYDOHop_L_H_C1_C2, PLAYDOHop_L_H_C1_C3, PLAYDOHop_L_H_C1_V1, PLAYDOHop_L_H_C2_C1, PLAYDOHop_L_H_C2_C2, PLAYDOHop_L_H_C2_C3, PLAYDOHop_L_H_C2_V1, PLAYDOHop_L_H_C3_C1, PLAYDOHop_L_H_C3_C2, PLAYDOHop_L_H_C3_C3, PLAYDOHop_L_H_C3_V1, PLAYDOHop_L_H_V1_C1, PLAYDOHop_L_H_V1_C2, PLAYDOHop_L_H_V1_C3, PLAYDOHop_L_H_V1_V1, PLAYDOHop_L_Q_C1_C1, PLAYDOHop_L_Q_C1_C2, PLAYDOHop_L_Q_C1_C3, PLAYDOHop_L_Q_C1_V1, PLAYDOHop_L_Q_C2_C1, PLAYDOHop_L_Q_C2_C2, PLAYDOHop_L_Q_C2_C3, PLAYDOHop_L_Q_C2_V1, PLAYDOHop_L_Q_C3_C1, PLAYDOHop_L_Q_C3_C2, PLAYDOHop_L_Q_C3_C3, PLAYDOHop_L_Q_C3_V1, PLAYDOHop_L_Q_V1_C1, PLAYDOHop_L_Q_V1_C2, PLAYDOHop_L_Q_V1_C3, PLAYDOHop_L_Q_V1_V1, PLAYDOHop_L_W_C1_C1, PLAYDOHop_L_W_C1_C2, PLAYDOHop_L_W_C1_C3, PLAYDOHop_L_W_C1_V1, PLAYDOHop_L_W_C2_C1, PLAYDOHop_L_W_C2_C2, PLAYDOHop_L_W_C2_C3, PLAYDOHop_L_W_C2_V1, PLAYDOHop_L_W_C3_C1, PLAYDOHop_L_W_C3_C2, PLAYDOHop_L_W_C3_C3, PLAYDOHop_L_W_C3_V1, PLAYDOHop_L_W_V1_C1, PLAYDOHop_L_W_V1_C2, PLAYDOHop_L_W_V1_C3, PLAYDOHop_L_W_V1_V1, PLAYDOHop_LDCM, PLAYDOHop_LDS_B_C1_C1, PLAYDOHop_LDS_B_C1_C2, PLAYDOHop_LDS_B_C1_C3, PLAYDOHop_LDS_B_C1_V1, PLAYDOHop_LDS_B_C2_C1, PLAYDOHop_LDS_B_C2_C2, PLAYDOHop_LDS_B_C2_C3, PLAYDOHop_LDS_B_C2_V1, PLAYDOHop_LDS_B_C3_C1, PLAYDOHop_LDS_B_C3_C2, PLAYDOHop_LDS_B_C3_C3, PLAYDOHop_LDS_B_C3_V1, PLAYDOHop_LDS_B_V1_C1, PLAYDOHop_LDS_B_V1_C2, PLAYDOHop_LDS_B_V1_C3, PLAYDOHop_LDS_B_V1_V1, PLAYDOHop_LDS_H_C1_C1, PLAYDOHop_LDS_H_C1_C2, PLAYDOHop_LDS_H_C1_C3, PLAYDOHop_LDS_H_C1_V1, PLAYDOHop_LDS_H_C2_C1, PLAYDOHop_LDS_H_C2_C2, PLAYDOHop_LDS_H_C2_C3, PLAYDOHop_LDS_H_C2_V1, PLAYDOHop_LDS_H_C3_C1, PLAYDOHop_LDS_H_C3_C2, PLAYDOHop_LDS_H_C3_C3, PLAYDOHop_LDS_H_C3_V1, PLAYDOHop_LDS_H_V1_C1, PLAYDOHop_LDS_H_V1_C2, PLAYDOHop_LDS_H_V1_C3, PLAYDOHop_LDS_H_V1_V1, PLAYDOHop_LDS_Q_C1_C1, PLAYDOHop_LDS_Q_C1_C2, PLAYDOHop_LDS_Q_C1_C3, PLAYDOHop_LDS_Q_C1_V1, PLAYDOHop_LDS_Q_C2_C1, PLAYDOHop_LDS_Q_C2_C2, PLAYDOHop_LDS_Q_C2_C3, PLAYDOHop_LDS_Q_C2_V1, PLAYDOHop_LDS_Q_C3_C1, PLAYDOHop_LDS_Q_C3_C2, PLAYDOHop_LDS_Q_C3_C3, PLAYDOHop_LDS_Q_C3_V1, PLAYDOHop_LDS_Q_V1_C1, PLAYDOHop_LDS_Q_V1_C2, PLAYDOHop_LDS_Q_V1_C3, PLAYDOHop_LDS_Q_V1_V1, PLAYDOHop_LDS_W_C1_C1, PLAYDOHop_LDS_W_C1_C2, PLAYDOHop_LDS_W_C1_C3, PLAYDOHop_LDS_W_C1_V1, PLAYDOHop_LDS_W_C2_C1, PLAYDOHop_LDS_W_C2_C2, PLAYDOHop_LDS_W_C2_C3, PLAYDOHop_LDS_W_C2_V1, PLAYDOHop_LDS_W_C3_C1, PLAYDOHop_LDS_W_C3_C2, PLAYDOHop_LDS_W_C3_C3, PLAYDOHop_LDS_W_C3_V1, PLAYDOHop_LDS_W_V1_C1, PLAYDOHop_LDS_W_V1_C2, PLAYDOHop_LDS_W_V1_C3, PLAYDOHop_LDS_W_V1_V1, PLAYDOHop_LDSI_B_C1_C1, PLAYDOHop_LDSI_B_C1_C2, PLAYDOHop_LDSI_B_C1_C3, PLAYDOHop_LDSI_B_C1_V1, PLAYDOHop_LDSI_B_C2_C1, PLAYDOHop_LDSI_B_C2_C2, PLAYDOHop_LDSI_B_C2_C3, PLAYDOHop_LDSI_B_C2_V1, PLAYDOHop_LDSI_B_C3_C1, PLAYDOHop_LDSI_B_C3_C2, PLAYDOHop_LDSI_B_C3_C3, PLAYDOHop_LDSI_B_C3_V1, PLAYDOHop_LDSI_B_V1_C1, PLAYDOHop_LDSI_B_V1_C2, PLAYDOHop_LDSI_B_V1_C3, PLAYDOHop_LDSI_B_V1_V1, PLAYDOHop_LDSI_H_C1_C1, PLAYDOHop_LDSI_H_C1_C2, PLAYDOHop_LDSI_H_C1_C3, PLAYDOHop_LDSI_H_C1_V1, PLAYDOHop_LDSI_H_C2_C1, PLAYDOHop_LDSI_H_C2_C2, PLAYDOHop_LDSI_H_C2_C3, PLAYDOHop_LDSI_H_C2_V1, PLAYDOHop_LDSI_H_C3_C1, PLAYDOHop_LDSI_H_C3_C2, PLAYDOHop_LDSI_H_C3_C3, PLAYDOHop_LDSI_H_C3_V1, PLAYDOHop_LDSI_H_V1_C1, PLAYDOHop_LDSI_H_V1_C2, PLAYDOHop_LDSI_H_V1_C3, PLAYDOHop_LDSI_H_V1_V1, PLAYDOHop_LDSI_Q_C1_C1, PLAYDOHop_LDSI_Q_C1_C2, PLAYDOHop_LDSI_Q_C1_C3, PLAYDOHop_LDSI_Q_C1_V1, PLAYDOHop_LDSI_Q_C2_C1, PLAYDOHop_LDSI_Q_C2_C2, PLAYDOHop_LDSI_Q_C2_C3, PLAYDOHop_LDSI_Q_C2_V1, PLAYDOHop_LDSI_Q_C3_C1, PLAYDOHop_LDSI_Q_C3_C2, PLAYDOHop_LDSI_Q_C3_C3, PLAYDOHop_LDSI_Q_C3_V1, PLAYDOHop_LDSI_Q_V1_C1, PLAYDOHop_LDSI_Q_V1_C2, PLAYDOHop_LDSI_Q_V1_C3, PLAYDOHop_LDSI_Q_V1_V1, PLAYDOHop_LDSI_W_C1_C1, PLAYDOHop_LDSI_W_C1_C2, PLAYDOHop_LDSI_W_C1_C3, PLAYDOHop_LDSI_W_C1_V1, PLAYDOHop_LDSI_W_C2_C1, PLAYDOHop_LDSI_W_C2_C2, PLAYDOHop_LDSI_W_C2_C3, PLAYDOHop_LDSI_W_C2_V1, PLAYDOHop_LDSI_W_C3_C1, PLAYDOHop_LDSI_W_C3_C2, PLAYDOHop_LDSI_W_C3_C3, PLAYDOHop_LDSI_W_C3_V1, PLAYDOHop_LDSI_W_V1_C1, PLAYDOHop_LDSI_W_V1_C2, PLAYDOHop_LDSI_W_V1_C3, PLAYDOHop_LDSI_W_V1_V1, PLAYDOHop_LDV_B, PLAYDOHop_LDV_H, PLAYDOHop_LDV_Q, PLAYDOHop_LDV_W, PLAYDOHop_LG_B_C1_C1, PLAYDOHop_LG_B_C1_C2, PLAYDOHop_LG_B_C1_C3, PLAYDOHop_LG_B_C1_V1, PLAYDOHop_LG_B_C2_C1, PLAYDOHop_LG_B_C2_C2, PLAYDOHop_LG_B_C2_C3, PLAYDOHop_LG_B_C2_V1, PLAYDOHop_LG_B_C3_C1, PLAYDOHop_LG_B_C3_C2, PLAYDOHop_LG_B_C3_C3, PLAYDOHop_LG_B_C3_V1, PLAYDOHop_LG_B_V1_C1, PLAYDOHop_LG_B_V1_C2, PLAYDOHop_LG_B_V1_C3, PLAYDOHop_LG_B_V1_V1, PLAYDOHop_LG_H_C1_C1, PLAYDOHop_LG_H_C1_C2, PLAYDOHop_LG_H_C1_C3, PLAYDOHop_LG_H_C1_V1, PLAYDOHop_LG_H_C2_C1, PLAYDOHop_LG_H_C2_C2, PLAYDOHop_LG_H_C2_C3, PLAYDOHop_LG_H_C2_V1, PLAYDOHop_LG_H_C3_C1, PLAYDOHop_LG_H_C3_C2, PLAYDOHop_LG_H_C3_C3, PLAYDOHop_LG_H_C3_V1, PLAYDOHop_LG_H_V1_C1, PLAYDOHop_LG_H_V1_C2, PLAYDOHop_LG_H_V1_C3, PLAYDOHop_LG_H_V1_V1, PLAYDOHop_LG_Q_C1_C1, PLAYDOHop_LG_Q_C1_C2, PLAYDOHop_LG_Q_C1_C3, PLAYDOHop_LG_Q_C1_V1, PLAYDOHop_LG_Q_C2_C1, PLAYDOHop_LG_Q_C2_C2, PLAYDOHop_LG_Q_C2_C3, PLAYDOHop_LG_Q_C2_V1, PLAYDOHop_LG_Q_C3_C1, PLAYDOHop_LG_Q_C3_C2, PLAYDOHop_LG_Q_C3_C3, PLAYDOHop_LG_Q_C3_V1, PLAYDOHop_LG_Q_V1_C1, PLAYDOHop_LG_Q_V1_C2, PLAYDOHop_LG_Q_V1_C3, PLAYDOHop_LG_Q_V1_V1, PLAYDOHop_LG_W_C1_C1, PLAYDOHop_LG_W_C1_C2, PLAYDOHop_LG_W_C1_C3, PLAYDOHop_LG_W_C1_V1, PLAYDOHop_LG_W_C2_C1, PLAYDOHop_LG_W_C2_C2, PLAYDOHop_LG_W_C2_C3, PLAYDOHop_LG_W_C2_V1, PLAYDOHop_LG_W_C3_C1, PLAYDOHop_LG_W_C3_C2, PLAYDOHop_LG_W_C3_C3, PLAYDOHop_LG_W_C3_V1, PLAYDOHop_LG_W_V1_C1, PLAYDOHop_LG_W_V1_C2, PLAYDOHop_LG_W_V1_C3, PLAYDOHop_LG_W_V1_V1, PLAYDOHop_LGX_B_C1_C1, PLAYDOHop_LGX_B_C1_C2, PLAYDOHop_LGX_B_C1_C3, PLAYDOHop_LGX_B_C1_V1, PLAYDOHop_LGX_B_C2_C1, PLAYDOHop_LGX_B_C2_C2, PLAYDOHop_LGX_B_C2_C3, PLAYDOHop_LGX_B_C2_V1, PLAYDOHop_LGX_B_C3_C1, PLAYDOHop_LGX_B_C3_C2, PLAYDOHop_LGX_B_C3_C3, PLAYDOHop_LGX_B_C3_V1, PLAYDOHop_LGX_B_V1_C1, PLAYDOHop_LGX_B_V1_C2, PLAYDOHop_LGX_B_V1_C3, PLAYDOHop_LGX_B_V1_V1, PLAYDOHop_LGX_H_C1_C1, PLAYDOHop_LGX_H_C1_C2, PLAYDOHop_LGX_H_C1_C3, PLAYDOHop_LGX_H_C1_V1, PLAYDOHop_LGX_H_C2_C1, PLAYDOHop_LGX_H_C2_C2, PLAYDOHop_LGX_H_C2_C3, PLAYDOHop_LGX_H_C2_V1, PLAYDOHop_LGX_H_C3_C1, PLAYDOHop_LGX_H_C3_C2, PLAYDOHop_LGX_H_C3_C3, PLAYDOHop_LGX_H_C3_V1, PLAYDOHop_LGX_H_V1_C1, PLAYDOHop_LGX_H_V1_C2, PLAYDOHop_LGX_H_V1_C3, PLAYDOHop_LGX_H_V1_V1, PLAYDOHop_LI_B_C1_C1, PLAYDOHop_LI_B_C1_C2, PLAYDOHop_LI_B_C1_C3, PLAYDOHop_LI_B_C1_V1, PLAYDOHop_LI_B_C2_C1, PLAYDOHop_LI_B_C2_C2, PLAYDOHop_LI_B_C2_C3, PLAYDOHop_LI_B_C2_V1, PLAYDOHop_LI_B_C3_C1, PLAYDOHop_LI_B_C3_C2, PLAYDOHop_LI_B_C3_C3, PLAYDOHop_LI_B_C3_V1, PLAYDOHop_LI_B_V1_C1, PLAYDOHop_LI_B_V1_C2, PLAYDOHop_LI_B_V1_C3, PLAYDOHop_LI_B_V1_V1, PLAYDOHop_LI_H_C1_C1, PLAYDOHop_LI_H_C1_C2, PLAYDOHop_LI_H_C1_C3, PLAYDOHop_LI_H_C1_V1, PLAYDOHop_LI_H_C2_C1, PLAYDOHop_LI_H_C2_C2, PLAYDOHop_LI_H_C2_C3, PLAYDOHop_LI_H_C2_V1, PLAYDOHop_LI_H_C3_C1, PLAYDOHop_LI_H_C3_C2, PLAYDOHop_LI_H_C3_C3, PLAYDOHop_LI_H_C3_V1, PLAYDOHop_LI_H_V1_C1, PLAYDOHop_LI_H_V1_C2, PLAYDOHop_LI_H_V1_C3, PLAYDOHop_LI_H_V1_V1, PLAYDOHop_LI_Q_C1_C1, PLAYDOHop_LI_Q_C1_C2, PLAYDOHop_LI_Q_C1_C3, PLAYDOHop_LI_Q_C1_V1, PLAYDOHop_LI_Q_C2_C1, PLAYDOHop_LI_Q_C2_C2, PLAYDOHop_LI_Q_C2_C3, PLAYDOHop_LI_Q_C2_V1, PLAYDOHop_LI_Q_C3_C1, PLAYDOHop_LI_Q_C3_C2, PLAYDOHop_LI_Q_C3_C3, PLAYDOHop_LI_Q_C3_V1, PLAYDOHop_LI_Q_V1_C1, PLAYDOHop_LI_Q_V1_C2, PLAYDOHop_LI_Q_V1_C3, PLAYDOHop_LI_Q_V1_V1, PLAYDOHop_LI_W_C1_C1, PLAYDOHop_LI_W_C1_C2, PLAYDOHop_LI_W_C1_C3, PLAYDOHop_LI_W_C1_V1, PLAYDOHop_LI_W_C2_C1, PLAYDOHop_LI_W_C2_C2, PLAYDOHop_LI_W_C2_C3, PLAYDOHop_LI_W_C2_V1, PLAYDOHop_LI_W_C3_C1, PLAYDOHop_LI_W_C3_C2, PLAYDOHop_LI_W_C3_C3, PLAYDOHop_LI_W_C3_V1, PLAYDOHop_LI_W_V1_C1, PLAYDOHop_LI_W_V1_C2, PLAYDOHop_LI_W_V1_C3, PLAYDOHop_LI_W_V1_V1, PLAYDOHop_LM_B_C1_C1, PLAYDOHop_LM_B_C1_C2, PLAYDOHop_LM_B_C1_C3, PLAYDOHop_LM_B_C1_V1, PLAYDOHop_LM_B_C2_C1, PLAYDOHop_LM_B_C2_C2, PLAYDOHop_LM_B_C2_C3, PLAYDOHop_LM_B_C2_V1, PLAYDOHop_LM_B_C3_C1, PLAYDOHop_LM_B_C3_C2, PLAYDOHop_LM_B_C3_C3, PLAYDOHop_LM_B_C3_V1, PLAYDOHop_LM_B_V1_C1, PLAYDOHop_LM_B_V1_C2, PLAYDOHop_LM_B_V1_C3, PLAYDOHop_LM_B_V1_V1, PLAYDOHop_LM_H_C1_C1, PLAYDOHop_LM_H_C1_C2, PLAYDOHop_LM_H_C1_C3, PLAYDOHop_LM_H_C1_V1, PLAYDOHop_LM_H_C2_C1, PLAYDOHop_LM_H_C2_C2, PLAYDOHop_LM_H_C2_C3, PLAYDOHop_LM_H_C2_V1, PLAYDOHop_LM_H_C3_C1, PLAYDOHop_LM_H_C3_C2, PLAYDOHop_LM_H_C3_C3, PLAYDOHop_LM_H_C3_V1, PLAYDOHop_LM_H_V1_C1, PLAYDOHop_LM_H_V1_C2, PLAYDOHop_LM_H_V1_C3, PLAYDOHop_LM_H_V1_V1, PLAYDOHop_LM_Q_C1_C1, PLAYDOHop_LM_Q_C1_C2, PLAYDOHop_LM_Q_C1_C3, PLAYDOHop_LM_Q_C1_V1, PLAYDOHop_LM_Q_C2_C1, PLAYDOHop_LM_Q_C2_C2, PLAYDOHop_LM_Q_C2_C3, PLAYDOHop_LM_Q_C2_V1, PLAYDOHop_LM_Q_C3_C1, PLAYDOHop_LM_Q_C3_C2, PLAYDOHop_LM_Q_C3_C3, PLAYDOHop_LM_Q_C3_V1, PLAYDOHop_LM_Q_V1_C1, PLAYDOHop_LM_Q_V1_C2, PLAYDOHop_LM_Q_V1_C3, PLAYDOHop_LM_Q_V1_V1, PLAYDOHop_LM_W_C1_C1, PLAYDOHop_LM_W_C1_C2, PLAYDOHop_LM_W_C1_C3, PLAYDOHop_LM_W_C1_V1, PLAYDOHop_LM_W_C2_C1, PLAYDOHop_LM_W_C2_C2, PLAYDOHop_LM_W_C2_C3, PLAYDOHop_LM_W_C2_V1, PLAYDOHop_LM_W_C3_C1, PLAYDOHop_LM_W_C3_C2, PLAYDOHop_LM_W_C3_C3, PLAYDOHop_LM_W_C3_V1, PLAYDOHop_LM_W_V1_C1, PLAYDOHop_LM_W_V1_C2, PLAYDOHop_LM_W_V1_C3, PLAYDOHop_LM_W_V1_V1, PLAYDOHop_LMX_B_C1_C1, PLAYDOHop_LMX_B_C1_C2, PLAYDOHop_LMX_B_C1_C3, PLAYDOHop_LMX_B_C1_V1, PLAYDOHop_LMX_B_C2_C1, PLAYDOHop_LMX_B_C2_C2, PLAYDOHop_LMX_B_C2_C3, PLAYDOHop_LMX_B_C2_V1, PLAYDOHop_LMX_B_C3_C1, PLAYDOHop_LMX_B_C3_C2, PLAYDOHop_LMX_B_C3_C3, PLAYDOHop_LMX_B_C3_V1, PLAYDOHop_LMX_B_V1_C1, PLAYDOHop_LMX_B_V1_C2, PLAYDOHop_LMX_B_V1_C3, PLAYDOHop_LMX_B_V1_V1, PLAYDOHop_LMX_H_C1_C1, PLAYDOHop_LMX_H_C1_C2, PLAYDOHop_LMX_H_C1_C3, PLAYDOHop_LMX_H_C1_V1, PLAYDOHop_LMX_H_C2_C1, PLAYDOHop_LMX_H_C2_C2, PLAYDOHop_LMX_H_C2_C3, PLAYDOHop_LMX_H_C2_V1, PLAYDOHop_LMX_H_C3_C1, PLAYDOHop_LMX_H_C3_C2, PLAYDOHop_LMX_H_C3_C3, PLAYDOHop_LMX_H_C3_V1, PLAYDOHop_LMX_H_V1_C1, PLAYDOHop_LMX_H_V1_C2, PLAYDOHop_LMX_H_V1_C3, PLAYDOHop_LMX_H_V1_V1, PLAYDOHop_LX_B_C1_C1, PLAYDOHop_LX_B_C1_C2, PLAYDOHop_LX_B_C1_C3, PLAYDOHop_LX_B_C1_V1, PLAYDOHop_LX_B_C2_C1, PLAYDOHop_LX_B_C2_C2, PLAYDOHop_LX_B_C2_C3, PLAYDOHop_LX_B_C2_V1, PLAYDOHop_LX_B_C3_C1, PLAYDOHop_LX_B_C3_C2, PLAYDOHop_LX_B_C3_C3, PLAYDOHop_LX_B_C3_V1, PLAYDOHop_LX_B_V1_C1, PLAYDOHop_LX_B_V1_C2, PLAYDOHop_LX_B_V1_C3, PLAYDOHop_LX_B_V1_V1, PLAYDOHop_LX_H_C1_C1, PLAYDOHop_LX_H_C1_C2, PLAYDOHop_LX_H_C1_C3, PLAYDOHop_LX_H_C1_V1, PLAYDOHop_LX_H_C2_C1, PLAYDOHop_LX_H_C2_C2, PLAYDOHop_LX_H_C2_C3, PLAYDOHop_LX_H_C2_V1, PLAYDOHop_LX_H_C3_C1, PLAYDOHop_LX_H_C3_C2, PLAYDOHop_LX_H_C3_C3, PLAYDOHop_LX_H_C3_V1, PLAYDOHop_LX_H_V1_C1, PLAYDOHop_LX_H_V1_C2, PLAYDOHop_LX_H_V1_C3, PLAYDOHop_LX_H_V1_V1, PLAYDOHop_M_NO_OP, PLAYDOHop_MOVEBB, PLAYDOHop_MOVECG, PLAYDOHop_MOVEFG_L, PLAYDOHop_MOVEFG_U, PLAYDOHop_MOVEGBP, PLAYDOHop_MOVEGC, PLAYDOHop_MOVEGCM, PLAYDOHop_MOVEGF_L, PLAYDOHop_MOVEGF_U, PLAYDOHop_MOVEGG, PLAYDOHop_MOVELB, PLAYDOHop_MOVELBS, PLAYDOHop_MOVELBX, PLAYDOHop_MOVELF, PLAYDOHop_MOVELFS, PLAYDOHop_MOVELG, PLAYDOHop_MOVELGS, PLAYDOHop_MOVELGX, PLAYDOHop_MOVEPG, PLAYDOHop_PBRA, PLAYDOHop_PBRAL, PLAYDOHop_PBRALBS, PLAYDOHop_PBRR, PLAYDOHop_PBRRL, PLAYDOHop_PBRRLBS, PLAYDOHop_RESTORE, PLAYDOHop_S_B_C1, PLAYDOHop_S_B_C2, PLAYDOHop_S_B_C3, PLAYDOHop_S_B_V1, PLAYDOHop_S_H_C1, PLAYDOHop_S_H_C2, PLAYDOHop_S_H_C3, PLAYDOHop_S_H_V1, PLAYDOHop_S_Q_C1, PLAYDOHop_S_Q_C2, PLAYDOHop_S_Q_C3, PLAYDOHop_S_Q_V1, PLAYDOHop_S_W_C1, PLAYDOHop_S_W_C2, PLAYDOHop_S_W_C3, PLAYDOHop_S_W_V1, PLAYDOHop_SAVE, PLAYDOHop_SG_B_C1, PLAYDOHop_SG_B_C2, PLAYDOHop_SG_B_C3, PLAYDOHop_SG_B_V1, PLAYDOHop_SG_H_C1, PLAYDOHop_SG_H_C2, PLAYDOHop_SG_H_C3, PLAYDOHop_SG_H_V1, PLAYDOHop_SG_Q_C1, PLAYDOHop_SG_Q_C2, PLAYDOHop_SG_Q_C3, PLAYDOHop_SG_Q_V1, PLAYDOHop_SG_W_C1, PLAYDOHop_SG_W_C2, PLAYDOHop_SG_W_C3, PLAYDOHop_SG_W_V1, PLAYDOHop_SH1ADDL, PLAYDOHop_SH2ADDL, PLAYDOHop_SH3ADDL, PLAYDOHop_SI_B_C1, PLAYDOHop_SI_B_C2, PLAYDOHop_SI_B_C3, PLAYDOHop_SI_B_V1, PLAYDOHop_SI_H_C1, PLAYDOHop_SI_H_C2, PLAYDOHop_SI_H_C3, PLAYDOHop_SI_H_V1, PLAYDOHop_SI_Q_C1, PLAYDOHop_SI_Q_C2, PLAYDOHop_SI_Q_C3, PLAYDOHop_SI_Q_V1, PLAYDOHop_SI_W_C1, PLAYDOHop_SI_W_C2, PLAYDOHop_SI_W_C3, PLAYDOHop_SI_W_V1, PLAYDOHop_SM_B_C1, PLAYDOHop_SM_B_C2, PLAYDOHop_SM_B_C3, PLAYDOHop_SM_B_V1, PLAYDOHop_SM_H_C1, PLAYDOHop_SM_H_C2, PLAYDOHop_SM_H_C3, PLAYDOHop_SM_H_V1, PLAYDOHop_SM_Q_C1, PLAYDOHop_SM_Q_C2, PLAYDOHop_SM_Q_C3, PLAYDOHop_SM_Q_V1, PLAYDOHop_SM_W_C1, PLAYDOHop_SM_W_C2, PLAYDOHop_SM_W_C3, PLAYDOHop_SM_W_V1, PLAYDOHop_VEXTRSB, PLAYDOHop_VEXTRSH, PLAYDOHop_VFL_D_C1_C1, PLAYDOHop_VFL_S_C1_C1, PLAYDOHop_VFLE_D_C1_C1, PLAYDOHop_VFLE_S_C1_C1, PLAYDOHop_VFS_D_C1, PLAYDOHop_VFS_S_C1, PLAYDOHop_VFSE_D_C1, PLAYDOHop_VFSE_S_C1, PLAYDOHop_VL_B_C1_C1, PLAYDOHop_VL_H_C1_C1, PLAYDOHop_VL_W_C1_C1, PLAYDOHop_VLE_B_C1_C1, PLAYDOHop_VLE_H_C1_C1, PLAYDOHop_VLE_W_C1_C1, PLAYDOHop_VS_B_C1, PLAYDOHop_VS_H_C1, PLAYDOHop_VS_W_C1, PLAYDOHop_VSE_B_C1, PLAYDOHop_VSE_H_C1, and PLAYDOHop_VSE_W_C1.
Referenced by M_opc_from_proc_opc().
int M_oper_supported_in_arch_playdoh (int opc)
Definition at line 3642 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_oper_supported_in_arch().
int M_operand_type_playdoh (L_Operand * operand)
Definition at line 3903 of file ml_hpl_pd.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_p, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
int M_playdoh_array_align (M_Type type)
Definition at line 512 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_array_align().
void M_playdoh_array_layout (M_Type type, int * offset)
Definition at line 499 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_array_layout().
int M_playdoh_array_size (M_Type type, int dim)
Definition at line 526 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_playdoh_model, M_PLAYDOH_V1, and _struct_M_Type::size.
Referenced by M_array_size().
void M_playdoh_bit_char (M_Type type, int n)
Definition at line 226 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_BIT, M_playdoh_model, M_PLAYDOH_SIZE_BIT, M_PLAYDOH_V1, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_playdoh_bit_int (M_Type type, int n)
Definition at line 188 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_BIT, M_playdoh_model, M_PLAYDOH_SIZE_BIT, M_PLAYDOH_V1, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_playdoh_bit_long (M_Type type, int n)
Definition at line 169 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_BIT, M_playdoh_model, M_PLAYDOH_SIZE_BIT, M_PLAYDOH_V1, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_playdoh_bit_short (M_Type type, int n)
Definition at line 207 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_BIT, M_playdoh_model, M_PLAYDOH_SIZE_BIT, M_PLAYDOH_V1, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_playdoh_call_type (M_Type type, M_Type ntype)
Definition at line 396 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_double(), M_playdoh_float(), M_playdoh_int(), M_playdoh_llong(), M_playdoh_model, M_PLAYDOH_V1, M_playdoh_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_playdoh_call_type2 (M_Type type, M_Type ntype)
Definition at line 443 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_char(), M_playdoh_double(), M_playdoh_float(), M_playdoh_int(), M_playdoh_llong(), M_playdoh_long(), M_playdoh_model, M_playdoh_pointer(), M_playdoh_short(), M_PLAYDOH_V1, M_playdoh_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_playdoh_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1436 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_cb_label_name().
int M_playdoh_dataflow_macro (int id)
Definition at line 1778 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
void M_playdoh_double (M_Type type, int unsign)
Definition at line 262 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_DOUBLE, M_playdoh_model, M_PLAYDOH_SIZE_DOUBLE, M_PLAYDOH_V1, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), and M_playdoh_eval_type2().
int M_playdoh_eval_type (M_Type type, M_Type ntype)
Definition at line 297 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_double(), M_playdoh_float(), M_playdoh_int(), M_playdoh_llong(), M_playdoh_model, M_PLAYDOH_V1, M_playdoh_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_playdoh_eval_type2 (M_Type type, M_Type ntype)
Definition at line 342 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_char(), M_playdoh_double(), M_playdoh_float(), M_playdoh_int(), M_playdoh_llong(), M_playdoh_long(), M_playdoh_model, M_playdoh_pointer(), M_playdoh_short(), M_PLAYDOH_V1, M_playdoh_void(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_playdoh_float (M_Type type, int unsign)
Definition at line 245 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_FLOAT, M_playdoh_model, M_PLAYDOH_SIZE_FLOAT, M_PLAYDOH_V1, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), and M_playdoh_eval_type2().
char* M_playdoh_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1559 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_fn_label_name().
char* M_playdoh_fn_name_from_label (char * label)
Definition at line 1581 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_fn_name_from_label().
int M_playdoh_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** base_macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 1062 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PLAYDOH_ALIGN_INT, M_PLAYDOH_ALIGN_MAX, M_PLAYDOH_FLT_BASE, M_PLAYDOH_INT_BASE, M_PLAYDOH_MAX_FNVAR_REG, M_playdoh_model, M_PLAYDOH_SIZE_INT, M_PLAYDOH_SMALL_STRUCT_MAX, M_PLAYDOH_V1, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_playdoh_fragile_macro (int macro_value)
Definition at line 1599 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_fragile_macro().
Set M_playdoh_fragile_macro_set (void)
Definition at line 1627 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_V1, Set_add(), and Set_playdoh_fragile_macro.
Referenced by M_fragile_macro_set().
int M_playdoh_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1449 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_is_cb_label().
int M_playdoh_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1476 of file ml_hpl_pd.c.
References M_assert(), M_JUMPTBL_BASE_NAME, M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_is_jumptbl_label().
void M_playdoh_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1463 of file ml_hpl_pd.c.
References M_assert(), M_JUMPTBL_BASE_NAME, M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_jumptbl_label_name().
int M_playdoh_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 826 of file ml_hpl_pd.c.
References _struct_M_Type::align, List_next(), List_start(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PLAYDOH_ALIGN_INT, M_PLAYDOH_ALIGN_MAX, M_PLAYDOH_FLT_BASE, M_PLAYDOH_INT_BASE, M_PLAYDOH_MAX_FNVAR_REG, M_PLAYDOH_SIZE_INT, M_PLAYDOH_SMALL_STRUCT_MAX, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_playdoh_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1371 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_MAX, M_playdoh_model, M_PLAYDOH_V1, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_playdoh_no_short_int (void)
Definition at line 1422 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_SIZE_INT, M_PLAYDOH_SIZE_SHORT, and M_PLAYDOH_V1.
Referenced by M_no_short_int().
void M_playdoh_pointer (M_Type type)
Definition at line 279 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_POINTER, M_playdoh_model, M_PLAYDOH_SIZE_POINTER, M_PLAYDOH_V1, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_playdoh_call_type2(), M_playdoh_eval_type2(), and M_pointer().
int M_playdoh_return_register (int type, int purpose)
Definition at line 1531 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_RET_F, M_PLAYDOH_RET_I32, M_PLAYDOH_RET_I64, M_PLAYDOH_V1, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, and M_TYPE_LONG.
Referenced by M_return_register().
int M_playdoh_struct_align (int n, _M_Type * type)
Definition at line 731 of file ml_hpl_pd.c.
References M_assert(), M_PLAYDOH_ALIGN_CHAR, M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_struct_align().
void M_playdoh_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 636 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_playdoh_model, M_PLAYDOH_SIZE_CHAR, M_PLAYDOH_SIZE_INT, M_PLAYDOH_SIZE_LONG, M_PLAYDOH_SIZE_SHORT, M_PLAYDOH_V1, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_playdoh_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 758 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_CHAR, M_PLAYDOH_ALIGN_LONG, M_PLAYDOH_ALIGN_SHORT, M_playdoh_model, M_PLAYDOH_SIZE_INT, M_PLAYDOH_V1, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_playdoh_structure_pointer (int purpose)
Definition at line 1517 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, M_PLAYDOH_RET_ST, and M_PLAYDOH_V1.
Referenced by M_structure_pointer().
int M_playdoh_subroutine_call (int opc)
Definition at line 1794 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_subroutine_call().
int M_playdoh_union_align (int n, _M_Type * type)
Definition at line 568 of file ml_hpl_pd.c.
References M_assert(), M_PLAYDOH_ALIGN_CHAR, M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_union_align().
void M_playdoh_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 550 of file ml_hpl_pd.c.
References M_assert(), M_playdoh_model, and M_PLAYDOH_V1.
Referenced by M_union_layout().
int M_playdoh_union_size (int n, _M_Type * type)
Definition at line 596 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_CHAR, M_playdoh_model, M_PLAYDOH_V1, and _struct_M_Type::size.
Referenced by M_union_size().
void M_playdoh_void (M_Type type)
Definition at line 152 of file ml_hpl_pd.c.
References _struct_M_Type::align, M_assert(), M_PLAYDOH_ALIGN_VOID, M_playdoh_model, M_PLAYDOH_SIZE_VOID, M_PLAYDOH_V1, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_playdoh_call_type(), M_playdoh_call_type2(), M_playdoh_eval_type(), M_playdoh_eval_type2(), and M_void().
int M_sign_extend_load_opcode (int proc_opc)
Definition at line 6081 of file ml_hpl_pd.c.
References PLAYDOHop_LGX_B_C1_C1, PLAYDOHop_LGX_B_C1_C2, PLAYDOHop_LGX_B_C1_C3, PLAYDOHop_LGX_B_C1_V1, PLAYDOHop_LGX_B_C2_C1, PLAYDOHop_LGX_B_C2_C2, PLAYDOHop_LGX_B_C2_C3, PLAYDOHop_LGX_B_C2_V1, PLAYDOHop_LGX_B_C3_C1, PLAYDOHop_LGX_B_C3_C2, PLAYDOHop_LGX_B_C3_C3, PLAYDOHop_LGX_B_C3_V1, PLAYDOHop_LGX_B_V1_C1, PLAYDOHop_LGX_B_V1_C2, PLAYDOHop_LGX_B_V1_C3, PLAYDOHop_LGX_B_V1_V1, PLAYDOHop_LGX_H_C1_C1, PLAYDOHop_LGX_H_C1_C2, PLAYDOHop_LGX_H_C1_C3, PLAYDOHop_LGX_H_C1_V1, PLAYDOHop_LGX_H_C2_C1, PLAYDOHop_LGX_H_C2_C2, PLAYDOHop_LGX_H_C2_C3, PLAYDOHop_LGX_H_C2_V1, PLAYDOHop_LGX_H_C3_C1, PLAYDOHop_LGX_H_C3_C2, PLAYDOHop_LGX_H_C3_C3, PLAYDOHop_LGX_H_C3_V1, PLAYDOHop_LGX_H_V1_C1, PLAYDOHop_LGX_H_V1_C2, PLAYDOHop_LGX_H_V1_C3, PLAYDOHop_LGX_H_V1_V1, PLAYDOHop_LGX_Q_C1_C1, PLAYDOHop_LGX_Q_C1_C2, PLAYDOHop_LGX_Q_C1_C3, PLAYDOHop_LGX_Q_C1_V1, PLAYDOHop_LGX_Q_C2_C1, PLAYDOHop_LGX_Q_C2_C2, PLAYDOHop_LGX_Q_C2_C3, PLAYDOHop_LGX_Q_C2_V1, PLAYDOHop_LGX_Q_C3_C1, PLAYDOHop_LGX_Q_C3_C2, PLAYDOHop_LGX_Q_C3_C3, PLAYDOHop_LGX_Q_C3_V1, PLAYDOHop_LGX_Q_V1_C1, PLAYDOHop_LGX_Q_V1_C2, PLAYDOHop_LGX_Q_V1_C3, PLAYDOHop_LGX_Q_V1_V1, PLAYDOHop_LGX_W_C1_C1, PLAYDOHop_LGX_W_C1_C2, PLAYDOHop_LGX_W_C1_C3, PLAYDOHop_LGX_W_C1_V1, PLAYDOHop_LGX_W_C2_C1, PLAYDOHop_LGX_W_C2_C2, PLAYDOHop_LGX_W_C2_C3, PLAYDOHop_LGX_W_C2_V1, PLAYDOHop_LGX_W_C3_C1, PLAYDOHop_LGX_W_C3_C2, PLAYDOHop_LGX_W_C3_C3, PLAYDOHop_LGX_W_C3_V1, PLAYDOHop_LGX_W_V1_C1, PLAYDOHop_LGX_W_V1_C2, PLAYDOHop_LGX_W_V1_C3, PLAYDOHop_LGX_W_V1_V1, PLAYDOHop_LMX_B_C1_C1, PLAYDOHop_LMX_B_C1_C2, PLAYDOHop_LMX_B_C1_C3, PLAYDOHop_LMX_B_C1_V1, PLAYDOHop_LMX_B_C2_C1, PLAYDOHop_LMX_B_C2_C2, PLAYDOHop_LMX_B_C2_C3, PLAYDOHop_LMX_B_C2_V1, PLAYDOHop_LMX_B_C3_C1, PLAYDOHop_LMX_B_C3_C2, PLAYDOHop_LMX_B_C3_C3, PLAYDOHop_LMX_B_C3_V1, PLAYDOHop_LMX_B_V1_C1, PLAYDOHop_LMX_B_V1_C2, PLAYDOHop_LMX_B_V1_C3, PLAYDOHop_LMX_B_V1_V1, PLAYDOHop_LMX_H_C1_C1, PLAYDOHop_LMX_H_C1_C2, PLAYDOHop_LMX_H_C1_C3, PLAYDOHop_LMX_H_C1_V1, PLAYDOHop_LMX_H_C2_C1, PLAYDOHop_LMX_H_C2_C2, PLAYDOHop_LMX_H_C2_C3, PLAYDOHop_LMX_H_C2_V1, PLAYDOHop_LMX_H_C3_C1, PLAYDOHop_LMX_H_C3_C2, PLAYDOHop_LMX_H_C3_C3, PLAYDOHop_LMX_H_C3_V1, PLAYDOHop_LMX_H_V1_C1, PLAYDOHop_LMX_H_V1_C2, PLAYDOHop_LMX_H_V1_C3, PLAYDOHop_LMX_H_V1_V1, PLAYDOHop_LMX_Q_C1_C1, PLAYDOHop_LMX_Q_C1_C2, PLAYDOHop_LMX_Q_C1_C3, PLAYDOHop_LMX_Q_C1_V1, PLAYDOHop_LMX_Q_C2_C1, PLAYDOHop_LMX_Q_C2_C2, PLAYDOHop_LMX_Q_C2_C3, PLAYDOHop_LMX_Q_C2_V1, PLAYDOHop_LMX_Q_C3_C1, PLAYDOHop_LMX_Q_C3_C2, PLAYDOHop_LMX_Q_C3_C3, PLAYDOHop_LMX_Q_C3_V1, PLAYDOHop_LMX_Q_V1_C1, PLAYDOHop_LMX_Q_V1_C2, PLAYDOHop_LMX_Q_V1_C3, PLAYDOHop_LMX_Q_V1_V1, PLAYDOHop_LMX_W_C1_C1, PLAYDOHop_LMX_W_C1_C2, PLAYDOHop_LMX_W_C1_C3, PLAYDOHop_LMX_W_C1_V1, PLAYDOHop_LMX_W_C2_C1, PLAYDOHop_LMX_W_C2_C2, PLAYDOHop_LMX_W_C2_C3, PLAYDOHop_LMX_W_C2_V1, PLAYDOHop_LMX_W_C3_C1, PLAYDOHop_LMX_W_C3_C2, PLAYDOHop_LMX_W_C3_C3, PLAYDOHop_LMX_W_C3_V1, PLAYDOHop_LMX_W_V1_C1, PLAYDOHop_LMX_W_V1_C2, PLAYDOHop_LMX_W_V1_C3, PLAYDOHop_LMX_W_V1_V1, PLAYDOHop_LX_B_C1_C1, PLAYDOHop_LX_B_C1_C2, PLAYDOHop_LX_B_C1_C3, PLAYDOHop_LX_B_C1_V1, PLAYDOHop_LX_B_C2_C1, PLAYDOHop_LX_B_C2_C2, PLAYDOHop_LX_B_C2_C3, PLAYDOHop_LX_B_C2_V1, PLAYDOHop_LX_B_C3_C1, PLAYDOHop_LX_B_C3_C2, PLAYDOHop_LX_B_C3_C3, PLAYDOHop_LX_B_C3_V1, PLAYDOHop_LX_B_V1_C1, PLAYDOHop_LX_B_V1_C2, PLAYDOHop_LX_B_V1_C3, PLAYDOHop_LX_B_V1_V1, PLAYDOHop_LX_H_C1_C1, PLAYDOHop_LX_H_C1_C2, PLAYDOHop_LX_H_C1_C3, PLAYDOHop_LX_H_C1_V1, PLAYDOHop_LX_H_C2_C1, PLAYDOHop_LX_H_C2_C2, PLAYDOHop_LX_H_C2_C3, PLAYDOHop_LX_H_C2_V1, PLAYDOHop_LX_H_C3_C1, PLAYDOHop_LX_H_C3_C2, PLAYDOHop_LX_H_C3_C3, PLAYDOHop_LX_H_C3_V1, PLAYDOHop_LX_H_V1_C1, PLAYDOHop_LX_H_V1_C2, PLAYDOHop_LX_H_V1_C3, PLAYDOHop_LX_H_V1_V1, PLAYDOHop_LX_Q_C1_C1, PLAYDOHop_LX_Q_C1_C2, PLAYDOHop_LX_Q_C1_C3, PLAYDOHop_LX_Q_C1_V1, PLAYDOHop_LX_Q_C2_C1, PLAYDOHop_LX_Q_C2_C2, PLAYDOHop_LX_Q_C2_C3, PLAYDOHop_LX_Q_C2_V1, PLAYDOHop_LX_Q_C3_C1, PLAYDOHop_LX_Q_C3_C2, PLAYDOHop_LX_Q_C3_C3, PLAYDOHop_LX_Q_C3_V1, PLAYDOHop_LX_Q_V1_C1, PLAYDOHop_LX_Q_V1_C2, PLAYDOHop_LX_Q_V1_C3, PLAYDOHop_LX_Q_V1_V1, PLAYDOHop_LX_W_C1_C1, PLAYDOHop_LX_W_C1_C2, PLAYDOHop_LX_W_C1_C3, PLAYDOHop_LX_W_C1_V1, PLAYDOHop_LX_W_C2_C1, PLAYDOHop_LX_W_C2_C2, PLAYDOHop_LX_W_C2_C3, PLAYDOHop_LX_W_C2_V1, PLAYDOHop_LX_W_C3_C1, PLAYDOHop_LX_W_C3_C2, PLAYDOHop_LX_W_C3_C3, PLAYDOHop_LX_W_C3_V1, PLAYDOHop_LX_W_V1_C1, PLAYDOHop_LX_W_V1_C2, PLAYDOHop_LX_W_V1_C3, and PLAYDOHop_LX_W_V1_V1.
Variable Documentation
int M_playdoh_dbl_offset = 0
Definition at line 3938 of file ml_hpl_pd.c.
int M_playdoh_model
Definition at line 98 of file mi_hpl_pd.c.
Set Set_playdoh_fragile_macro = NULL
Definition at line 101 of file ml_hpl_pd.c.
Referenced by M_playdoh_fragile_macro_set().