ml_ti.c File Reference
#include <config.h>
#include <stdio.h>
#include <Lcode/l_main.h>
#include `m_ti.h`
Defines
#define M_TI_SIZE_VOID 0
#define M_TI_SIZE_BIT 1
#define M_TI_SIZE_CHAR 32
#define M_TI_SIZE_SHORT 32
#define M_TI_SIZE_INT 32
#define M_TI_SIZE_LONG 32
#define M_TI_SIZE_FLOAT 32
#define M_TI_SIZE_DOUBLE 32
#define M_TI_SIZE_POINTER 32
#define M_TI_SIZE_UNION -1
#define M_TI_SIZE_STRUCT -1
#define M_TI_SIZE_BLOCK -1
#define M_TI_SIZE_MAX 64
#define M_TI_ALIGN_VOID -1
#define M_TI_ALIGN_BIT 1
#define M_TI_ALIGN_CHAR 32
#define M_TI_ALIGN_SHORT 32
#define M_TI_ALIGN_INT 32
#define M_TI_ALIGN_LONG 32
#define M_TI_ALIGN_FLOAT 32
#define M_TI_ALIGN_DOUBLE 32
#define M_TI_ALIGN_POINTER 32
#define M_TI_ALIGN_UNION -1
#define M_TI_ALIGN_STRUCT -1
#define M_TI_ALIGN_BLOCK -1
#define M_TI_ALIGN_MAX 64
#define M_TI_MAX_FNVAR_REG 6
#define M_TI_SMALL_STRUCT_MAX 64
#define MIN_PARAM_SIZE (16 * 8)
#define M_TI_NUM_FLT_PARM_REGS 2
#define M_TI_NUM_INT_PARM_REGS 4
#define M_TI_INT_BASE 0
#define M_TI_FLT_BASE 4
#define M_TI_RET_F 6
#define M_TI_RET_I32 6
#define M_TI_RET_I64 6
#define M_TI_RET_ST 6
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_ti_void (M_Type type)
void M_ti_bit_long (M_Type type, int n)
void M_ti_bit_int (M_Type type, int n)
void M_ti_bit_short (M_Type type, int n)
void M_ti_bit_char (M_Type type, int n)
void M_ti_float (M_Type type, int unsign)
void M_ti_double (M_Type type, int unsign)
void M_ti_pointer (M_Type type)
int M_ti_eval_type (M_Type type, M_Type ntype)
int M_ti_eval_type2 (M_Type type, M_Type ntype)
int M_ti_call_type (M_Type type, M_Type ntype)
int M_ti_call_type2 (M_Type type, M_Type ntype)
void M_ti_array_layout (M_Type type, int *offset)
int M_ti_array_align (M_Type type)
int M_ti_array_size (M_Type type, int dim)
void M_ti_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_ti_union_align (int n, _M_Type *type)
int M_ti_union_size (int n, _M_Type *type)
void M_ti_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_ti_struct_align (int n, _M_Type *type)
int M_ti_struct_size (int n, _M_Type *type, int struct_align)
int M_ti_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_ti_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_ti_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_ti_no_short_int (void)
void M_ti_cb_label_name (char *fn, int cb, char *line, int len)
int M_ti_is_cb_label (char *label, char *fn, int *cb)
void M_ti_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_ti_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_ti_structure_pointer (int purpose)
int M_ti_return_register (int type, int purpose)
char * M_ti_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_ti_fn_name_from_label (char *label)
int M_ti_fragile_macro (int macro_value)
int M_ti_subroutine_call (int opc)
void M_define_macros_ti (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_ti (int id)
void M_define_opcode_name_ti (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_ti (int id)
int M_oper_supported_in_arch_ti (int opc)
int M_num_oper_required_for_ti (L_Oper *oper, char *name)
int M_is_stack_operand_ti (L_Operand *operand)
int M_is_unsafe_macro_ti (L_Operand *operand)
int M_operand_type_ti (L_Operand *operand)
int M_conflicting_operands_ti (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_ti (int ctype)
Variables
int use_standard_function_call_model
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define long_neg_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_TI_ALIGN_BIT 1
Definition at line 93 of file ml_ti.c.
#define M_TI_ALIGN_BLOCK -1
Definition at line 103 of file ml_ti.c.
#define M_TI_ALIGN_CHAR 32
Definition at line 94 of file ml_ti.c.
#define M_TI_ALIGN_DOUBLE 32
Definition at line 99 of file ml_ti.c.
#define M_TI_ALIGN_FLOAT 32
Definition at line 98 of file ml_ti.c.
#define M_TI_ALIGN_INT 32
Definition at line 96 of file ml_ti.c.
#define M_TI_ALIGN_LONG 32
Definition at line 97 of file ml_ti.c.
#define M_TI_ALIGN_MAX 64
Definition at line 104 of file ml_ti.c.
#define M_TI_ALIGN_POINTER 32
Definition at line 100 of file ml_ti.c.
#define M_TI_ALIGN_SHORT 32
Definition at line 95 of file ml_ti.c.
#define M_TI_ALIGN_STRUCT -1
Definition at line 102 of file ml_ti.c.
#define M_TI_ALIGN_UNION -1
Definition at line 101 of file ml_ti.c.
#define M_TI_ALIGN_VOID -1
Definition at line 92 of file ml_ti.c.
#define M_TI_FLT_BASE 4
Definition at line 128 of file ml_ti.c.
Referenced by M_ti_fnvar_layout().
#define M_TI_INT_BASE 0
Definition at line 117 of file ml_ti.c.
Referenced by M_ti_fnvar_layout().
#define M_TI_MAX_FNVAR_REG 6
Definition at line 110 of file ml_ti.c.
Referenced by M_ti_fnvar_layout().
#define M_TI_NUM_FLT_PARM_REGS 2
Definition at line 114 of file ml_ti.c.
#define M_TI_NUM_INT_PARM_REGS 4
Definition at line 115 of file ml_ti.c.
Referenced by M_ti_fnvar_layout().
#define M_TI_RET_F 6
Definition at line 132 of file ml_ti.c.
Referenced by M_ti_return_register().
#define M_TI_RET_I32 6
Definition at line 133 of file ml_ti.c.
Referenced by M_ti_return_register().
#define M_TI_RET_I64 6
Definition at line 134 of file ml_ti.c.
#define M_TI_RET_ST 6
Definition at line 135 of file ml_ti.c.
Referenced by M_ti_structure_pointer().
#define M_TI_SIZE_BIT 1
Definition at line 79 of file ml_ti.c.
#define M_TI_SIZE_BLOCK -1
Definition at line 89 of file ml_ti.c.
#define M_TI_SIZE_CHAR 32
Definition at line 80 of file ml_ti.c.
#define M_TI_SIZE_DOUBLE 32
Definition at line 85 of file ml_ti.c.
#define M_TI_SIZE_FLOAT 32
Definition at line 84 of file ml_ti.c.
#define M_TI_SIZE_INT 32
Definition at line 82 of file ml_ti.c.
#define M_TI_SIZE_LONG 32
Definition at line 83 of file ml_ti.c.
#define M_TI_SIZE_MAX 64
Definition at line 90 of file ml_ti.c.
#define M_TI_SIZE_POINTER 32
Definition at line 86 of file ml_ti.c.
#define M_TI_SIZE_SHORT 32
Definition at line 81 of file ml_ti.c.
#define M_TI_SIZE_STRUCT -1
Definition at line 88 of file ml_ti.c.
#define M_TI_SIZE_UNION -1
Definition at line 87 of file ml_ti.c.
#define M_TI_SIZE_VOID 0
Definition at line 78 of file ml_ti.c.
#define M_TI_SMALL_STRUCT_MAX 64
Definition at line 111 of file ml_ti.c.
Referenced by M_ti_fnvar_layout().
#define MIN_PARAM_SIZE (16 * 8)
Definition at line 112 of file ml_ti.c.
#define non_zero_offset(a)
Value:
(!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) ||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_conflicting_operands_ti (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1560 of file ml_ti.c.
References M_assert(), TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, and TI_MAC_TRUE_SP.
Referenced by M_dep_conflicting_operands().
void M_define_macros_ti (STRING_Symbol_Table * sym_tbl)
Definition at line 1106 of file ml_ti.c.
References M_add_symbol, TI_MAC_ALLOC, TI_MAC_AUXILIARY_REG7, TI_MAC_BK, TI_MAC_CALLEE_F, TI_MAC_CALLEE_I, TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, TI_MAC_DP, TI_MAC_INDEX_REG0, TI_MAC_INDEX_REG1, TI_MAC_LEAF, TI_MAC_RC, TI_MAC_RE, TI_MAC_RS, TI_MAC_ST, and TI_MAC_TRUE_SP.
Referenced by M_define_macros().
void M_define_opcode_name_ti (STRING_Symbol_Table * sym_tbl)
Definition at line 1192 of file ml_ti.c.
References LTIop_ALU_DIRECT, LTIop_ALU_INDIRECT, LTIop_ALU_INDIRECT_INDIRECT, LTIop_ALU_INDIRECT_REG, LTIop_ALU_REG_DIRECT, LTIop_ALU_REG_INDIRECT, LTIop_BD, LTIop_BR, LTIop_BRD, LTIop_BS, LTIop_BU, LTIop_BUD, LTIop_CALL, LTIop_CALLU, LTIop_DB, LTIop_DBD, LTIop_PAR_LOAD, LTIop_PAR_ONE_OPERAND, LTIop_PAR_STORE, LTIop_PAR_TWO_OPERAND, LTIop_POP, LTIop_POPF, LTIop_PUSH, LTIop_PUSHF, LTIop_REPEAT_BLOCK, LTIop_REPEAT_INSTRUCTION, LTIop_RETS, LTIop_SUBRF, LTIop_SUBRI, M_add_symbol, TIopcode_ALU_DIRECT, TIopcode_ALU_INDIRECT, TIopcode_ALU_INDIRECT_INDIRECT, TIopcode_ALU_INDIRECT_REG, TIopcode_ALU_REG_DIRECT, TIopcode_ALU_REG_INDIRECT, TIopcode_BD, TIopcode_BR, TIopcode_BRD, TIopcode_BS, TIopcode_BU, TIopcode_BUD, TIopcode_CALL, TIopcode_CALLU, TIopcode_DB, TIopcode_DBD, TIopcode_PAR_LOAD, TIopcode_PAR_ONE_OPERAND, TIopcode_PAR_STORE, TIopcode_PAR_TWO_OPERAND, TIopcode_POP, TIopcode_POPF, TIopcode_PUSH, TIopcode_PUSHF, TIopcode_REPEAT_BLOCK, TIopcode_REPEAT_INSTRUCTION, TIopcode_RETS, TIopcode_SUBRF, and TIopcode_SUBRI.
Referenced by M_define_opcode_name().
char* M_get_macro_name_ti (int id)
Definition at line 1141 of file ml_ti.c.
References TI_MAC_ALLOC, TI_MAC_AUXILIARY_REG7, TI_MAC_BK, TI_MAC_CALLEE_F, TI_MAC_CALLEE_I, TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, TI_MAC_COMPUTATION_REG2, TI_MAC_COMPUTATION_REG3, TI_MAC_DP, TI_MAC_INDEX_REG0, TI_MAC_INDEX_REG1, TI_MAC_LEAF, TI_MAC_RC, TI_MAC_RE, TI_MAC_RS, TI_MAC_ST, and TI_MAC_TRUE_SP.
Referenced by M_get_macro_name().
char* M_get_opcode_name_ti (int id)
Definition at line 1232 of file ml_ti.c.
References LTIop_ALU_DIRECT, LTIop_ALU_INDIRECT, LTIop_ALU_INDIRECT_INDIRECT, LTIop_ALU_INDIRECT_REG, LTIop_ALU_REG_DIRECT, LTIop_ALU_REG_INDIRECT, LTIop_BD, LTIop_BR, LTIop_BRD, LTIop_BS, LTIop_BU, LTIop_BUD, LTIop_CALL, LTIop_CALLU, LTIop_DB, LTIop_DBD, LTIop_PAR_LOAD, LTIop_PAR_ONE_OPERAND, LTIop_PAR_STORE, LTIop_PAR_TWO_OPERAND, LTIop_POP, LTIop_POPF, LTIop_PUSH, LTIop_PUSHF, LTIop_REPEAT_BLOCK, LTIop_REPEAT_INSTRUCTION, LTIop_RETS, LTIop_SUBRF, LTIop_SUBRI, TIopcode_ALU_DIRECT, TIopcode_ALU_INDIRECT, TIopcode_ALU_INDIRECT_INDIRECT, TIopcode_ALU_INDIRECT_REG, TIopcode_ALU_REG_DIRECT, TIopcode_ALU_REG_INDIRECT, TIopcode_BD, TIopcode_BR, TIopcode_BRD, TIopcode_BS, TIopcode_BU, TIopcode_BUD, TIopcode_CALL, TIopcode_CALLU, TIopcode_DB, TIopcode_DBD, TIopcode_PAR_LOAD, TIopcode_PAR_ONE_OPERAND, TIopcode_PAR_STORE, TIopcode_PAR_TWO_OPERAND, TIopcode_POP, TIopcode_POPF, TIopcode_PUSH, TIopcode_PUSHF, TIopcode_REPEAT_BLOCK, TIopcode_REPEAT_INSTRUCTION, TIopcode_RETS, TIopcode_SUBRF, and TIopcode_SUBRI.
Referenced by M_get_opcode_name().
int M_is_stack_operand_ti (L_Operand * operand)
Definition at line 1487 of file ml_ti.c.
References TI_MAC_TRUE_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_ti (L_Operand * operand)
Definition at line 1503 of file ml_ti.c.
References TI_MAC_COMPUTATION_REG0, TI_MAC_COMPUTATION_REG1, and TI_MAC_ST.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_ti (L_Oper * oper, char * name)
Definition at line 1347 of file ml_ti.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_ti (int ctype)
Definition at line 1632 of file ml_ti.c.
References M_assert(), M_model, and M_TI_1.
Referenced by M_num_registers().
int M_oper_supported_in_arch_ti (int opc)
Definition at line 1310 of file ml_ti.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_ti (L_Operand * operand)
Definition at line 1528 of file ml_ti.c.
References FIELD_16, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit16, MDES_OPERAND_Lit24, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
int M_ti_array_align (M_Type type)
Definition at line 411 of file ml_ti.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_ti_array_layout (M_Type type, int * offset)
Definition at line 405 of file ml_ti.c.
Referenced by M_array_layout().
int M_ti_array_size (M_Type type, int dim)
Definition at line 417 of file ml_ti.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_ti_bit_char (M_Type type, int n)
Definition at line 190 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_ti_bit_int (M_Type type, int n)
Definition at line 166 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_ti_bit_long (M_Type type, int n)
Definition at line 154 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_ti_bit_short (M_Type type, int n)
Definition at line 178 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_BIT, M_TI_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_ti_call_type (M_Type type, M_Type ntype)
Definition at line 312 of file ml_ti.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_ti_call_type2 (M_Type type, M_Type ntype)
Definition at line 354 of file ml_ti.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_ti_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 961 of file ml_ti.c.
Referenced by M_cb_label_name().
void M_ti_double (M_Type type, int unsign)
Definition at line 215 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_DOUBLE, M_TI_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_ti_eval_type (M_Type type, M_Type ntype)
Definition at line 236 of file ml_ti.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_ti_eval_type2 (M_Type type, M_Type ntype)
Definition at line 270 of file ml_ti.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_ti_float (M_Type type, int unsign)
Definition at line 205 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_FLOAT, M_TI_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_ti_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1035 of file ml_ti.c.
char* M_ti_fn_name_from_label (char * label)
Definition at line 1049 of file ml_ti.c.
int M_ti_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 663 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TI_ALIGN_INT, M_TI_ALIGN_MAX, M_TI_FLT_BASE, M_TI_INT_BASE, M_TI_MAX_FNVAR_REG, M_TI_NUM_INT_PARM_REGS, M_TI_SIZE_INT, M_TI_SMALL_STRUCT_MAX, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, _struct_M_Type::size, and use_standard_function_call_model.
Referenced by M_fnvar_layout(), and M_ti_layout_fnvar().
int M_ti_fragile_macro (int macro_value)
Definition at line 1059 of file ml_ti.c.
References M_assert(), M_model, M_TI_1, and TI_MAC_ST.
Referenced by M_fragile_macro().
int M_ti_is_cb_label (char * label, char * fn, int * cb)
Definition at line 967 of file ml_ti.c.
Referenced by M_is_cb_label().
int M_ti_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 980 of file ml_ti.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_ti_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 973 of file ml_ti.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_ti_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 610 of file ml_ti.c.
References List_next(), List_size(), List_start(), M_ti_fnvar_layout(), _struct_M_Param::mode, mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_ti_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 913 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_ti_no_short_int (void)
Definition at line 955 of file ml_ti.c.
References M_TI_SIZE_INT, and M_TI_SIZE_SHORT.
Referenced by M_no_short_int().
void M_ti_pointer (M_Type type)
Definition at line 225 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_POINTER, M_TI_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_ti_return_register (int type, int purpose)
Definition at line 1014 of file ml_ti.c.
References M_TI_RET_F, M_TI_RET_I32, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
Referenced by M_return_register().
int M_ti_struct_align (int n, _M_Type * type)
Definition at line 546 of file ml_ti.c.
References M_TI_ALIGN_CHAR.
Referenced by M_struct_align().
void M_ti_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 497 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_layout().
int M_ti_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 565 of file ml_ti.c.
References _struct_M_Type::align, M_assert(), M_TI_ALIGN_CHAR, M_TI_SIZE_INT, M_TYPE_BIT_CHAR, and M_TYPE_BIT_LONG.
Referenced by M_struct_size().
int M_ti_structure_pointer (int purpose)
Definition at line 1008 of file ml_ti.c.
References M_TI_RET_ST.
Referenced by M_structure_pointer().
int M_ti_subroutine_call (int opc)
Definition at line 1087 of file ml_ti.c.
References M_assert(), M_model, and M_TI_1.
Referenced by M_subroutine_call().
int M_ti_union_align (int n, _M_Type * type)
Definition at line 443 of file ml_ti.c.
References M_TI_ALIGN_CHAR.
Referenced by M_union_align().
void M_ti_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 432 of file ml_ti.c.
Referenced by M_union_layout().
int M_ti_union_size (int n, _M_Type * type)
Definition at line 463 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_ti_void (M_Type type)
Definition at line 144 of file ml_ti.c.
References _struct_M_Type::align, M_TI_ALIGN_VOID, M_TI_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
Variable Documentation
int use_standard_function_call_model
Definition at line 75 of file mi_ti.c.
Referenced by M_set_model_ti(), and M_ti_fnvar_layout().