ml_spec.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <machine/m_spec.h>
#include <machine/m_hppa.h>
#include <machine/m_impact.h>
#include <machine/m_hpl_pd.h>
#include <machine/m_sparc.h>
#include <machine/m_x86.h>
#include <machine/m_ti.h>
#include <machine/m_sh.h>
#include <machine/m_bx86.h>
#include <machine/m_tahoe.h>
#include <machine/m_starcore.h>
#include <machine/m_arm.h>
#include <machine/m_wims.h>
Defines
#define TEST_SIZE
Functions
void M_void (M_Type type)
void M_bit_llong (M_Type type, int n, int unsign)
void M_bit_long (M_Type type, int n, int unsign)
void M_bit_int (M_Type type, int n, int unsign)
void M_bit_short (M_Type type, int n, int unsign)
void M_bit_char (M_Type type, int n, int unsign)
void M_float (M_Type type, int unsign)
void M_double (M_Type type, int unsign)
void M_pointer (M_Type type)
void M_union (M_Type type, int align, int size)
void M_struct (M_Type type, int align, int size)
void M_block (M_Type type, int align, int size)
int M_eval_type (M_Type type, M_Type ntype)
int M_eval_type2 (M_Type type, M_Type ntype)
int M_call_type (M_Type type, M_Type ntype)
int M_call_type2 (M_Type type, M_Type ntype)
void M_array_layout (M_Type type, int *offset)
int M_array_align (M_Type type)
int M_array_size (M_Type type, int dim)
void M_union_layout (int n, _M_Type *type, int *offset, int *bit_offset, char *union_name, char *field_name[])
int M_union_align (int n, _M_Type *type, char *union_name)
int M_union_size (int n, _M_Type *type, char *union_name)
void M_struct_layout (int n, _M_Type *type, int *base, int *bit_offset, char *struct_name, char *field_name[])
int M_struct_align (int n, _M_Type *type, char *struct_name)
int M_struct_size (int n, _M_Type *type, int struct_align, char *struct_name)
int M_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose, int needs_ST)
int M_default_layout_retvar (M_Param param, int purpose)
int M_layout_retvar (M_Param param, int purpose)
int M_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **base_macro, int *su_sreg, int *su_ereg, int *pcount, int need_ST, int purpose)
int M_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_native_int_register_ctype (void)
int M_native_int_register_mtype (void)
int M_no_short_int (void)
int M_compatible_type (M_Type type1, M_Type type2)
void M_cb_label_name (char *fn, int cb, char *line, int len)
int M_is_cb_label (char *label, char *fn, int *cb)
void M_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_is_jumptbl_label (char *label, char *fn, int *tbl_id)
char * M_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_fn_name_from_label (char *label)
int M_structure_pointer (int purpose)
int M_return_value_thru_stack ()
int M_return_value_offset ()
int M_return_register (int type, int purpose)
L_Operand * M_return_epilogue_cntr_register ()
L_Operand * M_return_loop_cntr_register ()
int M_fragile_macro (int macro_value)
int M_extra_pred_define_opcode (int proc_opc)
int M_extra_pred_define_type1 (L_Oper *oper)
int M_extra_pred_define_type2 (L_Oper *oper)
Set M_fragile_macro_set ()
int M_dataflow_macro (int id)
int M_zero_macro (L_Operand *opd)
int M_subroutine_call (int opc)
void M_define_macros (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name (int id)
void M_define_opcode_name (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name (int id)
int M_oper_supported_in_arch (int opc)
int M_num_oper_required_for (L_Oper *oper, char *name)
int M_is_stack_operand (L_Operand *operand)
int M_is_unsafe_macro (L_Operand *operand)
IFPTR1 M_mdes_operand_type (void)
IFPTR2 M_dep_conflicting_operands (void)
void M_get_memory_operands (int *first, int *number, int proc_opc)
int M_num_registers (int ctype)
int M_memory_access_size (L_Oper *op)
int M_get_data_type (L_Oper *op)
int M_scaled_addressing_avail (void)
int M_is_implicit_memory_op (L_Oper *oper)
int M_opc_from_proc_opc (int proc_opc)
int M_cannot_predicate (L_Oper *oper)
int M_coalescing_oper (L_Oper *oper)
static int M_align_offset (int offset, int align_bit)
Variables
int M_arch
int M_model
Define Documentation
#define TEST_SIZE
Definition at line 81 of file ml_spec.c.
Function Documentation
static int M_align_offset (int offset, int align_bit) [static]
Definition at line 3240 of file ml_spec.c.
References I_punt().
int M_array_align (M_Type type)
Definition at line 1083 of file ml_spec.c.
References _struct_M_Type::align, M_arch, M_ARM, M_arm_array_align(), M_assert(), M_HPPA, M_hppa_array_align(), M_IMPACT, M_impact_array_align(), M_PLAYDOH, M_playdoh_array_align(), M_SH, M_sh_array_align(), M_SPARC, M_sparc_array_align(), M_STARCORE, M_starcore_array_align(), M_TAHOE, M_tahoe_array_align(), M_TI, M_ti_array_align(), M_use_layout_database, M_WIMS, M_wims_array_align(), M_X86, and M_x86_array_align().
void M_array_layout (M_Type type, int * offset)
Definition at line 1032 of file ml_spec.c.
References M_arch, M_ARM, M_arm_array_layout(), M_assert(), M_HPPA, M_hppa_array_layout(), M_IMPACT, M_impact_array_layout(), M_PLAYDOH, M_playdoh_array_layout(), M_SH, M_sh_array_layout(), M_SPARC, M_sparc_array_layout(), M_STARCORE, M_starcore_array_layout(), M_TAHOE, M_tahoe_array_layout(), M_TI, M_ti_array_layout(), M_use_layout_database, M_WIMS, M_wims_array_layout(), M_X86, and M_x86_array_layout().
int M_array_size (M_Type type, int dim)
Definition at line 1125 of file ml_spec.c.
References _struct_M_Type::align, M_arch, M_ARM, M_arm_array_size(), M_assert(), M_HPPA, M_hppa_array_size(), M_IMPACT, M_impact_array_size(), M_PLAYDOH, M_playdoh_array_size(), M_SH, M_sh_array_size(), M_SPARC, M_sparc_array_size(), M_STARCORE, M_starcore_array_size(), M_TAHOE, M_tahoe_array_size(), M_TI, M_ti_array_size(), M_use_layout_database, M_WIMS, M_wims_array_size(), M_X86, M_x86_array_size(), and _struct_M_Type::size.
void M_bit_char (M_Type type, int n, int unsign)
Definition at line 401 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_char(), M_assert(), M_BX86, M_bx86_bit_char(), M_HPPA, M_hppa_bit_char(), M_IMPACT, M_impact_bit_char(), M_PLAYDOH, M_playdoh_bit_char(), M_read_database_i(), M_SH, M_sh_bit_char(), M_SPARC, M_sparc_bit_char(), M_STARCORE, M_starcore_bit_char(), M_TAHOE, M_tahoe_bit_char(), M_TI, M_ti_bit_char(), M_TYPE_BIT_CHAR, M_use_layout_database, M_WIMS, M_wims_bit_char(), M_X86, M_x86_bit_char(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_int (M_Type type, int n, int unsign)
Definition at line 263 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_int(), M_assert(), M_BX86, M_bx86_bit_int(), M_HPPA, M_hppa_bit_int(), M_IMPACT, M_impact_bit_int(), M_PLAYDOH, M_playdoh_bit_int(), M_read_database_i(), M_SH, M_sh_bit_int(), M_SPARC, M_sparc_bit_int(), M_STARCORE, M_starcore_bit_int(), M_TAHOE, M_tahoe_bit_int(), M_TI, M_ti_bit_int(), M_TYPE_BIT_INT, M_use_layout_database, M_WIMS, M_wims_bit_int(), M_X86, M_x86_bit_int(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_llong (M_Type type, int n, int unsign)
Definition at line 157 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_assert(), M_read_database_i(), M_TAHOE, M_tahoe_bit_llong(), M_TYPE_BIT_LLONG, M_use_layout_database, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_long (M_Type type, int n, int unsign)
Definition at line 194 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_long(), M_assert(), M_BX86, M_bx86_bit_long(), M_HPPA, M_hppa_bit_long(), M_IMPACT, M_impact_bit_long(), M_PLAYDOH, M_playdoh_bit_long(), M_read_database_i(), M_SH, M_sh_bit_long(), M_SPARC, M_sparc_bit_long(), M_STARCORE, M_starcore_bit_long(), M_TAHOE, M_tahoe_bit_long(), M_TI, M_ti_bit_long(), M_TYPE_BIT_LONG, M_use_layout_database, M_WIMS, M_wims_bit_long(), M_X86, M_x86_bit_long(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bit_short (M_Type type, int n, int unsign)
Definition at line 332 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, I_punt(), M_arch, M_ARM, M_arm_bit_short(), M_assert(), M_BX86, M_bx86_bit_short(), M_HPPA, M_hppa_bit_short(), M_IMPACT, M_impact_bit_short(), M_PLAYDOH, M_playdoh_bit_short(), M_read_database_i(), M_SH, M_sh_bit_short(), M_SPARC, M_sparc_bit_short(), M_STARCORE, M_starcore_bit_short(), M_TAHOE, M_tahoe_bit_short(), M_TI, M_ti_bit_short(), M_TYPE_BIT_SHORT, M_use_layout_database, M_WIMS, M_wims_bit_short(), M_X86, M_x86_bit_short(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
void M_block (M_Type type, int align, int size)
Definition at line 683 of file ml_spec.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BLOCK, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_call_type (M_Type type, M_Type ntype)
Definition at line 867 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_call_type(), M_assert(), M_double(), M_float(), M_HPPA, M_hppa_call_type(), M_IMPACT, M_impact_call_type(), M_int(), M_llong(), M_native_int_register_mtype(), M_PLAYDOH, M_playdoh_call_type(), M_SH, M_sh_call_type(), M_SPARC, M_sparc_call_type(), M_STARCORE, M_starcore_call_type(), M_TAHOE, M_tahoe_call_type(), M_TI, M_ti_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_call_type(), M_X86, M_x86_call_type(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_call_type2 (M_Type type, M_Type ntype)
Definition at line 949 of file ml_spec.c.
References M_arch, M_ARM, M_arm_call_type2(), M_assert(), M_char(), M_double(), M_float(), M_HPPA, M_hppa_call_type2(), M_IMPACT, M_impact_call_type2(), M_int(), M_llong(), M_long(), M_PLAYDOH, M_playdoh_call_type2(), M_pointer(), M_SH, M_sh_call_type2(), M_short(), M_SPARC, M_sparc_call_type2(), M_STARCORE, M_starcore_call_type2(), M_TAHOE, M_tahoe_call_type2(), M_TI, M_ti_call_type2(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_call_type2(), M_X86, M_x86_call_type2(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_cannot_predicate (L_Oper * oper)
Definition at line 3203 of file ml_spec.c.
References M_arch, M_ARM, M_cannot_predicate_tahoe(), M_IMPACT, M_PLAYDOH, and M_TAHOE.
void M_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1927 of file ml_spec.c.
References M_arch, M_ARM, M_arm_cb_label_name(), M_assert(), M_BX86, M_bx86_cb_label_name(), M_HPPA, M_hppa_cb_label_name(), M_IMPACT, M_impact_cb_label_name(), M_PLAYDOH, M_playdoh_cb_label_name(), M_SH, M_sh_cb_label_name(), M_SPARC, M_sparc_cb_label_name(), M_STARCORE, M_starcore_cb_label_name(), M_TAHOE, M_tahoe_cb_label_name(), M_TI, M_ti_cb_label_name(), M_WIMS, M_wims_cb_label_name(), M_X86, and M_x86_cb_label_name().
int M_coalescing_oper (L_Oper * oper)
Definition at line 3223 of file ml_spec.c.
References M_arch, M_STARCORE, and M_starcore_coalescing_oper().
int M_compatible_type (M_Type type1, M_Type type2)
Definition at line 1915 of file ml_spec.c.
References M_eval_type(), and _struct_M_Type::type.
int M_dataflow_macro (int id)
Definition at line 2502 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_hppa_dataflow_macro(), M_IMPACT, M_impact_dataflow_macro(), M_PLAYDOH, M_SH, M_sh_dataflow_macro(), M_SPARC, M_sparc_dataflow_macro(), M_STARCORE, M_starcore_dataflow_macro(), M_TAHOE, M_tahoe_dataflow_macro(), M_TI, M_WIMS, and M_X86.
int M_default_layout_retvar (M_Param param, int purpose)
Definition at line 1667 of file ml_spec.c.
References M_INDIRECT_THRU_REGISTER, M_THRU_REGISTER, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, and _struct_M_Type::type.
Referenced by M_layout_retvar().
void M_define_macros (STRING_Symbol_Table * sym_tbl)
Definition at line 2587 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_define_macros_arm(), M_define_macros_bx86(), M_define_macros_hppa(), M_define_macros_impact(), M_define_macros_playdoh(), M_define_macros_sh(), M_define_macros_sparc(), M_define_macros_starcore(), M_define_macros_tahoe(), M_define_macros_ti(), M_define_macros_wims(), M_define_macros_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_define_opcode_name (STRING_Symbol_Table * sym_tbl)
Definition at line 2669 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_define_opcode_name_arm(), M_define_opcode_name_bx86(), M_define_opcode_name_hppa(), M_define_opcode_name_playdoh(), M_define_opcode_name_starcore(), M_define_opcode_name_ti(), M_define_opcode_name_wims(), M_define_opcode_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
IFPTR2 M_dep_conflicting_operands (void)
Definition at line 2952 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_conflicting_operands_arm(), M_conflicting_operands_bx86(), M_conflicting_operands_hppa(), M_conflicting_operands_impact(), M_conflicting_operands_playdoh(), M_conflicting_operands_sh(), M_conflicting_operands_sparc(), M_conflicting_operands_starcore(), M_conflicting_operands_tahoe(), M_conflicting_operands_ti(), M_conflicting_operands_wims(), M_conflicting_operands_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
void M_double (M_Type type, int unsign)
Definition at line 529 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_double(), M_assert(), M_BX86, M_bx86_double(), M_HPPA, M_hppa_double(), M_IMPACT, M_impact_double(), M_PLAYDOH, M_playdoh_double(), M_read_database_i(), M_SH, M_sh_double(), M_SPARC, M_sparc_double(), M_STARCORE, M_starcore_double(), M_TAHOE, M_tahoe_double(), M_TI, M_ti_double(), M_TYPE_DOUBLE, M_use_layout_database, M_WIMS, M_wims_double(), M_X86, M_x86_double(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
int M_eval_type (M_Type type, M_Type ntype)
Definition at line 699 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_eval_type(), M_assert(), M_BX86, M_bx86_eval_type(), M_double(), M_float(), M_HPPA, M_hppa_eval_type(), M_IMPACT, M_impact_eval_type(), M_int(), M_llong(), M_native_int_register_mtype(), M_PLAYDOH, M_playdoh_eval_type(), M_SH, M_sh_eval_type(), M_SPARC, M_sparc_eval_type(), M_STARCORE, M_starcore_eval_type(), M_TAHOE, M_tahoe_eval_type(), M_TI, M_ti_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_eval_type(), M_X86, M_x86_eval_type(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_compatible_type().
int M_eval_type2 (M_Type type, M_Type ntype)
Definition at line 783 of file ml_spec.c.
References M_arch, M_ARM, M_arm_eval_type2(), M_assert(), M_BX86, M_bx86_eval_type2(), M_char(), M_double(), M_float(), M_HPPA, M_hppa_eval_type2(), M_IMPACT, M_impact_eval_type2(), M_int(), M_llong(), M_long(), M_PLAYDOH, M_playdoh_eval_type2(), M_pointer(), M_SH, M_sh_eval_type2(), M_short(), M_SPARC, M_sparc_eval_type2(), M_STARCORE, M_starcore_eval_type2(), M_TAHOE, M_tahoe_eval_type2(), M_TI, M_ti_eval_type2(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_use_layout_database, M_void(), M_WIMS, M_wims_eval_type2(), M_X86, M_x86_eval_type2(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_extra_pred_define_opcode (int proc_opc)
Definition at line 2411 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_STARCORE, M_starcore_extra_pred_define_opcode(), M_TAHOE, and M_tahoe_extra_pred_define_opcode().
int M_extra_pred_define_type1 (L_Oper * oper)
Definition at line 2433 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_TAHOE, and M_tahoe_extra_pred_define_type1().
int M_extra_pred_define_type2 (L_Oper * oper)
Definition at line 2452 of file ml_spec.c.
References M_arch, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_TAHOE, and M_tahoe_extra_pred_define_type2().
void M_float (M_Type type, int unsign)
Definition at line 469 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_float(), M_assert(), M_BX86, M_bx86_float(), M_HPPA, M_hppa_float(), M_IMPACT, M_impact_float(), M_PLAYDOH, M_playdoh_float(), M_read_database_i(), M_SH, M_sh_float(), M_SPARC, M_sparc_float(), M_STARCORE, M_starcore_float(), M_TAHOE, M_tahoe_float(), M_TI, M_ti_float(), M_TYPE_FLOAT, M_use_layout_database, M_WIMS, M_wims_float(), M_X86, M_x86_float(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
char* M_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 2089 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fn_label_name(), M_assert(), M_BX86, M_bx86_fn_label_name(), M_HPPA, M_hppa_fn_label_name(), M_IMPACT, M_impact_fn_label_name(), M_PLAYDOH, M_playdoh_fn_label_name(), M_SH, M_SPARC, M_sparc_fn_label_name(), M_STARCORE, M_starcore_fn_label_name(), M_TAHOE, M_tahoe_fn_label_name(), M_TI, M_WIMS, M_wims_fn_label_name(), M_X86, and M_x86_fn_label_name().
char* M_fn_name_from_label (char * label)
Definition at line 2124 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fn_name_from_label(), M_assert(), M_BX86, M_bx86_fn_name_from_label(), M_HPPA, M_hppa_fn_name_from_label(), M_IMPACT, M_impact_fn_name_from_label(), M_PLAYDOH, M_playdoh_fn_name_from_label(), M_SH, M_SPARC, M_sparc_fn_name_from_label(), M_STARCORE, M_starcore_fn_name_from_label(), M_TAHOE, M_tahoe_fn_name_from_label(), M_TI, M_WIMS, M_X86, and M_x86_fn_name_from_label().
int M_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** base_macro, int * su_sreg, int * su_ereg, int * pcount, int need_ST, int purpose)
Definition at line 1712 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fnvar_layout(), M_assert(), M_HPPA, M_hppa_fnvar_layout(), M_IMPACT, M_impact_fnvar_layout(), M_PLAYDOH, M_playdoh_fnvar_layout(), M_SH, M_sh_fnvar_layout(), M_SPARC, M_sparc_fnvar_layout(), M_STARCORE, M_starcore_fnvar_layout(), M_TAHOE, M_tahoe_fnvar_layout(), M_TI, M_ti_fnvar_layout(), M_WIMS, M_wims_fnvar_layout(), M_X86, and M_x86_fnvar_layout().
int M_fragile_macro (int macro_value)
Definition at line 2361 of file ml_spec.c.
References M_arch, M_ARM, M_arm_fragile_macro(), M_assert(), M_BX86, M_bx86_fragile_macro(), M_HPPA, M_hppa_fragile_macro(), M_IMPACT, M_impact_fragile_macro(), M_PLAYDOH, M_playdoh_fragile_macro(), M_SH, M_sh_fragile_macro(), M_SPARC, M_sparc_fragile_macro(), M_STARCORE, M_starcore_fragile_macro(), M_TAHOE, M_tahoe_fragile_macro(), M_TI, M_ti_fragile_macro(), M_WIMS, M_wims_fragile_macro(), M_X86, and M_x86_fragile_macro().
Set M_fragile_macro_set ()
Definition at line 2471 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_hppa_fragile_macro_set(), M_IMPACT, M_impact_fragile_macro_set(), M_PLAYDOH, M_playdoh_fragile_macro_set(), M_SH, M_sh_fragile_macro_set(), M_SPARC, M_sparc_fragile_macro_set(), M_STARCORE, M_starcore_fragile_macro_set(), M_TAHOE, M_tahoe_fragile_macro_set(), M_TI, M_WIMS, M_X86, and NULL.
int M_get_data_type (L_Oper * op)
Definition at line 3095 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_data_type_bx86(), M_get_data_type_starcore(), M_get_data_type_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
char* M_get_macro_name (int id)
Definition at line 2634 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_macro_name_arm(), M_get_macro_name_bx86(), M_get_macro_name_hppa(), M_get_macro_name_impact(), M_get_macro_name_playdoh(), M_get_macro_name_sh(), M_get_macro_name_sparc(), M_get_macro_name_starcore(), M_get_macro_name_tahoe(), M_get_macro_name_ti(), M_get_macro_name_wims(), M_get_macro_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_get_memory_operands (int * first, int * number, int proc_opc)
Definition at line 2995 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_get_memory_operands_bx86(), M_get_memory_operands_starcore(), M_get_memory_operands_tahoe(), M_get_memory_operands_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
char* M_get_opcode_name (int id)
Definition at line 2722 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_get_opcode_name_arm(), M_get_opcode_name_bx86(), M_get_opcode_name_hppa(), M_get_opcode_name_playdoh(), M_get_opcode_name_starcore(), M_get_opcode_name_ti(), M_get_opcode_name_wims(), M_get_opcode_name_x86(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1973 of file ml_spec.c.
References M_arch, M_ARM, M_arm_is_cb_label(), M_assert(), M_BX86, M_bx86_is_cb_label(), M_HPPA, M_hppa_is_cb_label(), M_IMPACT, M_impact_is_cb_label(), M_PLAYDOH, M_playdoh_is_cb_label(), M_SH, M_sh_is_cb_label(), M_SPARC, M_sparc_is_cb_label(), M_STARCORE, M_starcore_is_cb_label(), M_TAHOE, M_tahoe_is_cb_label(), M_TI, M_ti_is_cb_label(), M_WIMS, M_wims_is_cb_label(), M_X86, and M_x86_is_cb_label().
int M_is_implicit_memory_op (L_Oper * oper)
Definition at line 3147 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_HPPA, M_IMPACT, M_is_implicit_memory_op_bx86(), M_is_implicit_memory_op_starcore(), M_is_implicit_memory_op_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 2054 of file ml_spec.c.
References M_arch, M_ARM, M_arm_is_jumptbl_label(), M_assert(), M_BX86, M_bx86_is_jumptbl_label(), M_HPPA, M_hppa_is_jumptbl_label(), M_IMPACT, M_impact_is_jumptbl_label(), M_PLAYDOH, M_playdoh_is_jumptbl_label(), M_SH, M_sh_is_jumptbl_label(), M_SPARC, M_sparc_is_jumptbl_label(), M_STARCORE, M_starcore_is_jumptbl_label(), M_TAHOE, M_tahoe_is_jumptbl_label(), M_TI, M_ti_is_jumptbl_label(), M_WIMS, M_wims_is_jumptbl_label(), M_X86, and M_x86_is_jumptbl_label().
int M_is_stack_operand (L_Operand * operand)
Definition at line 2841 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_is_stack_operand_arm(), M_is_stack_operand_bx86(), M_is_stack_operand_hppa(), M_is_stack_operand_impact(), M_is_stack_operand_playdoh(), M_is_stack_operand_sh(), M_is_stack_operand_sparc(), M_is_stack_operand_starcore(), M_is_stack_operand_tahoe(), M_is_stack_operand_ti(), M_is_stack_operand_wims(), M_is_stack_operand_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_is_unsafe_macro (L_Operand * operand)
Definition at line 2879 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_is_unsafe_macro_arm(), M_is_unsafe_macro_bx86(), M_is_unsafe_macro_hppa(), M_is_unsafe_macro_impact(), M_is_unsafe_macro_playdoh(), M_is_unsafe_macro_sh(), M_is_unsafe_macro_sparc(), M_is_unsafe_macro_starcore(), M_is_unsafe_macro_tahoe(), M_is_unsafe_macro_ti(), M_is_unsafe_macro_wims(), M_is_unsafe_macro_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
void M_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 2008 of file ml_spec.c.
References M_arch, M_ARM, M_arm_jumptbl_label_name(), M_assert(), M_BX86, M_bx86_jumptbl_label_name(), M_HPPA, M_hppa_jumptbl_label_name(), M_IMPACT, M_impact_jumptbl_label_name(), M_PLAYDOH, M_playdoh_jumptbl_label_name(), M_SH, M_sh_jumptbl_label_name(), M_SPARC, M_sparc_jumptbl_label_name(), M_STARCORE, M_starcore_jumptbl_label_name(), M_TAHOE, M_tahoe_jumptbl_label_name(), M_TI, M_ti_jumptbl_label_name(), M_WIMS, M_wims_jumptbl_label_name(), M_X86, and M_x86_jumptbl_label_name().
int M_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose, int needs_ST)
Definition at line 1631 of file ml_spec.c.
References M_arch, M_ARM, M_arm_layout_fnvar(), M_assert(), M_HPPA, M_hppa_layout_fnvar(), M_IMPACT, M_impact_layout_fnvar(), M_PLAYDOH, M_playdoh_layout_fnvar(), M_SH, M_sh_layout_fnvar(), M_SPARC, M_sparc_layout_fnvar(), M_STARCORE, M_starcore_layout_fnvar(), M_TAHOE, M_tahoe_layout_fnvar(), M_TI, M_ti_layout_fnvar(), M_WIMS, M_wims_layout_fnvar(), M_X86, and M_x86_layout_fnvar().
int M_layout_retvar (M_Param param, int purpose)
Definition at line 1678 of file ml_spec.c.
References M_arch, M_ARM, M_arm_layout_retvar(), M_assert(), M_default_layout_retvar(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_tahoe_layout_retvar(), M_TI, M_WIMS, M_wims_layout_retvar(), and M_X86.
int M_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1789 of file ml_spec.c.
References M_arch, M_ARM, M_arm_lvar_layout(), M_assert(), M_HPPA, M_hppa_lvar_layout(), M_IMPACT, M_impact_lvar_layout(), M_PLAYDOH, M_playdoh_lvar_layout(), M_SH, M_sh_lvar_layout(), M_SPARC, M_sparc_lvar_layout(), M_STARCORE, M_starcore_lvar_layout(), M_TAHOE, M_tahoe_lvar_layout(), M_TI, M_ti_lvar_layout(), M_WIMS, M_wims_lvar_layout(), M_X86, and M_x86_lvar_layout().
IFPTR1 M_mdes_operand_type (void)
Definition at line 2917 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_operand_type_arm(), M_operand_type_bx86(), M_operand_type_hppa(), M_operand_type_impact(), M_operand_type_playdoh(), M_operand_type_sh(), M_operand_type_sparc(), M_operand_type_starcore(), M_operand_type_tahoe(), M_operand_type_ti(), M_operand_type_wims(), M_operand_type_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_memory_access_size (L_Oper * op)
Definition at line 3065 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_memory_access_size_bx86(), M_memory_access_size_starcore(), M_memory_access_size_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, M_X86, and NULL.
int M_native_int_register_ctype (void)
Definition at line 1822 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_native_int_register_mtype (void)
Definition at line 1847 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_TYPE_INT, M_TYPE_LLONG, M_WIMS, and M_X86.
Referenced by M_call_type(), and M_eval_type().
int M_no_short_int (void)
Definition at line 1872 of file ml_spec.c.
References M_arch, M_ARM, M_arm_no_short_int(), M_assert(), M_HPPA, M_hppa_no_short_int(), M_IMPACT, M_impact_no_short_int(), M_PLAYDOH, M_playdoh_no_short_int(), M_read_database_i(), M_SH, M_sh_no_short_int(), M_SPARC, M_sparc_no_short_int(), M_STARCORE, M_starcore_no_short_int(), M_TAHOE, M_tahoe_no_short_int(), M_TI, M_ti_no_short_int(), M_use_layout_database, M_WIMS, M_wims_no_short_int(), M_X86, and M_x86_no_short_int().
int M_num_oper_required_for (L_Oper * oper, char * name)
Definition at line 2806 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_sh(), M_num_oper_required_for_sparc(), M_num_oper_required_for_starcore(), M_num_oper_required_for_tahoe(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), M_num_oper_required_for_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_num_registers (int ctype)
Definition at line 3029 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_num_registers_arm(), M_num_registers_bx86(), M_num_registers_hppa(), M_num_registers_impact(), M_num_registers_playdoh(), M_num_registers_sh(), M_num_registers_sparc(), M_num_registers_starcore(), M_num_registers_tahoe(), M_num_registers_ti(), M_num_registers_wims(), M_num_registers_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_opc_from_proc_opc (int proc_opc)
Definition at line 3173 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_opc_from_proc_opc_playdoh(), M_opc_from_proc_opc_starcore(), M_opc_from_proc_opc_tahoe(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_oper_supported_in_arch (int opc)
Definition at line 2765 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_BX86, M_HPPA, M_IMPACT, M_oper_supported_in_arch_arm(), M_oper_supported_in_arch_bx86(), M_oper_supported_in_arch_hppa(), M_oper_supported_in_arch_impact(), M_oper_supported_in_arch_playdoh(), M_oper_supported_in_arch_sh(), M_oper_supported_in_arch_sparc(), M_oper_supported_in_arch_starcore(), M_oper_supported_in_arch_tahoe(), M_oper_supported_in_arch_ti(), M_oper_supported_in_arch_wims(), M_oper_supported_in_arch_x86(), M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_pointer (M_Type type)
Definition at line 589 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_pointer(), M_assert(), M_BX86, M_bx86_pointer(), M_HPPA, M_hppa_pointer(), M_IMPACT, M_impact_pointer(), M_PLAYDOH, M_playdoh_pointer(), M_read_database_i(), M_SH, M_sh_pointer(), M_SPARC, M_sparc_pointer(), M_STARCORE, M_starcore_pointer(), M_TAHOE, M_tahoe_pointer(), M_TI, M_ti_pointer(), M_TYPE_POINTER, M_use_layout_database, M_WIMS, M_wims_pointer(), M_X86, M_x86_pointer(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type2(), M_arm_eval_type2(), M_bx86_call_type2(), M_bx86_eval_type2(), M_call_type2(), M_eval_type2(), M_hppa_call_type2(), M_hppa_eval_type2(), M_sh_call_type2(), M_sh_eval_type2(), M_sparc_call_type2(), M_sparc_eval_type2(), M_ti_call_type2(), M_ti_eval_type2(), M_wims_call_type2(), M_wims_eval_type2(), M_x86_call_type2(), and M_x86_eval_type2().
L_Operand* M_return_epilogue_cntr_register ()
Definition at line 2306 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_starcore_epilogue_cntr_register(), M_TAHOE, M_tahoe_epilogue_cntr_register(), M_TI, M_WIMS, M_X86, and NULL.
L_Operand* M_return_loop_cntr_register ()
Definition at line 2334 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_starcore_loop_cntr_register(), M_TAHOE, M_tahoe_loop_cntr_register(), M_TI, M_WIMS, M_X86, and NULL.
int M_return_register (int type, int purpose)
Definition at line 2273 of file ml_spec.c.
References M_arch, M_ARM, M_arm_return_register(), M_assert(), M_HPPA, M_hppa_return_register(), M_IMPACT, M_impact_return_register(), M_PLAYDOH, M_playdoh_return_register(), M_SH, M_sh_return_register(), M_SPARC, M_sparc_return_register(), M_STARCORE, M_starcore_return_register(), M_TAHOE, M_tahoe_return_register(), M_TI, M_ti_return_register(), M_WIMS, M_wims_return_register(), M_X86, and M_x86_return_register().
int M_return_value_offset ()
Definition at line 2225 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_return_value_thru_stack ()
Definition at line 2192 of file ml_spec.c.
References M_arch, M_ARM, M_assert(), M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
int M_scaled_addressing_avail (void)
Definition at line 3124 of file ml_spec.c.
References M_arch, M_ARM, M_BX86, M_HPPA, M_IMPACT, M_PLAYDOH, M_SH, M_SPARC, M_STARCORE, M_TAHOE, M_TI, M_WIMS, and M_X86.
void M_struct (M_Type type, int align, int size)
Definition at line 666 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_assert(), M_TYPE_STRUCT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_struct_align (int n, _M_Type * type, char * struct_name)
Definition at line 1546 of file ml_spec.c.
References M_arch, M_ARM, M_arm_struct_align(), M_assert(), M_HPPA, M_hppa_struct_align(), M_IMPACT, M_impact_struct_align(), M_PLAYDOH, M_playdoh_struct_align(), M_read_database_i(), M_SH, M_sh_struct_align(), M_SPARC, M_sparc_struct_align(), M_STARCORE, M_starcore_struct_align(), M_TAHOE, M_tahoe_struct_align(), M_TI, M_ti_struct_align(), M_use_layout_database, M_WIMS, M_wims_struct_align(), M_X86, and M_x86_struct_align().
void M_struct_layout (int n, _M_Type * type, int * base, int * bit_offset, char * struct_name, char * field_name[])
Definition at line 1320 of file ml_spec.c.
References I_punt(), M_arch, M_ARM, M_arm_struct_layout(), M_assert(), M_HPPA, M_hppa_struct_layout(), M_IMPACT, M_impact_struct_layout(), M_layout_database_desc(), M_layout_database_name, M_PLAYDOH, M_playdoh_struct_layout(), M_read_database_i(), M_SH, M_sh_struct_layout(), M_SPARC, M_sparc_struct_layout(), M_STARCORE, M_starcore_struct_layout(), M_TAHOE, M_tahoe_struct_layout(), M_TI, M_ti_struct_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_INT, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_use_layout_database, M_WIMS, M_wims_struct_layout(), M_X86, M_x86_struct_layout(), and _struct_M_Type::type.
int M_struct_size (int n, _M_Type * type, int struct_align, char * struct_name)
Definition at line 1589 of file ml_spec.c.
References M_arch, M_ARM, M_arm_struct_size(), M_assert(), M_HPPA, M_hppa_struct_size(), M_IMPACT, M_impact_struct_size(), M_PLAYDOH, M_playdoh_struct_size(), M_read_database_i(), M_SH, M_sh_struct_size(), M_SPARC, M_sparc_struct_size(), M_STARCORE, M_starcore_struct_size(), M_TAHOE, M_tahoe_struct_size(), M_TI, M_ti_struct_size(), M_use_layout_database, M_WIMS, M_wims_struct_size(), M_X86, and M_x86_struct_size().
int M_structure_pointer (int purpose)
Definition at line 2159 of file ml_spec.c.
References M_arch, M_ARM, M_arm_structure_pointer(), M_assert(), M_HPPA, M_hppa_structure_pointer(), M_IMPACT, M_impact_structure_pointer(), M_PLAYDOH, M_playdoh_structure_pointer(), M_SH, M_sh_structure_pointer(), M_SPARC, M_sparc_structure_pointer(), M_STARCORE, M_starcore_structure_pointer(), M_TAHOE, M_tahoe_structure_pointer(), M_TI, M_ti_structure_pointer(), M_WIMS, M_wims_structure_pointer(), M_X86, and M_x86_structure_pointer().
int M_subroutine_call (int opc)
Definition at line 2554 of file ml_spec.c.
References M_arch, M_ARM, M_arm_subroutine_call(), M_assert(), M_HPPA, M_hppa_subroutine_call(), M_IMPACT, M_impact_subroutine_call(), M_PLAYDOH, M_playdoh_subroutine_call(), M_SH, M_sh_subroutine_call(), M_SPARC, M_sparc_subroutine_call(), M_STARCORE, M_starcore_subroutine_call(), M_TAHOE, M_tahoe_subroutine_call(), M_TI, M_ti_subroutine_call(), M_WIMS, M_wims_subroutine_call(), M_X86, and M_x86_subroutine_call().
void M_union (M_Type type, int align, int size)
Definition at line 649 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_assert(), M_TYPE_UNION, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
int M_union_align (int n, _M_Type * type, char * union_name)
Definition at line 1234 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_align(), M_assert(), M_HPPA, M_hppa_union_align(), M_IMPACT, M_impact_union_align(), M_PLAYDOH, M_playdoh_union_align(), M_read_database_i(), M_SH, M_sh_union_align(), M_SPARC, M_sparc_union_align(), M_STARCORE, M_starcore_union_align(), M_TAHOE, M_tahoe_union_align(), M_TI, M_ti_union_align(), M_use_layout_database, M_WIMS, M_wims_union_align(), M_X86, and M_x86_union_align().
void M_union_layout (int n, _M_Type * type, int * offset, int * bit_offset, char * union_name, char * field_name[])
Definition at line 1175 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_layout(), M_assert(), M_HPPA, M_hppa_union_layout(), M_IMPACT, M_impact_union_layout(), M_PLAYDOH, M_playdoh_union_layout(), M_read_database_i(), M_SH, M_sh_union_layout(), M_SPARC, M_sparc_union_layout(), M_STARCORE, M_starcore_union_layout(), M_TAHOE, M_tahoe_union_layout(), M_TI, M_ti_union_layout(), M_use_layout_database, M_WIMS, M_wims_union_layout(), M_X86, and M_x86_union_layout().
int M_union_size (int n, _M_Type * type, char * union_name)
Definition at line 1277 of file ml_spec.c.
References M_arch, M_ARM, M_arm_union_size(), M_assert(), M_HPPA, M_hppa_union_size(), M_IMPACT, M_impact_union_size(), M_PLAYDOH, M_playdoh_union_size(), M_read_database_i(), M_SH, M_sh_union_size(), M_SPARC, M_sparc_union_size(), M_STARCORE, M_starcore_union_size(), M_TAHOE, M_tahoe_union_size(), M_TI, M_ti_union_size(), M_use_layout_database, M_WIMS, M_wims_union_size(), M_X86, and M_x86_union_size().
void M_void (M_Type type)
Definition at line 94 of file ml_spec.c.
References _struct_M_Type::align, _struct_M_Type::flags, M_arch, M_ARM, M_arm_void(), M_assert(), M_BX86, M_bx86_void(), M_HPPA, M_hppa_void(), M_IMPACT, M_impact_void(), M_PLAYDOH, M_playdoh_void(), M_SH, M_sh_void(), M_SPARC, M_sparc_void(), M_STARCORE, M_starcore_void(), M_TAHOE, M_tahoe_void(), M_TI, M_ti_void(), M_TYPE_VOID, M_use_layout_database, M_WIMS, M_wims_void(), M_X86, M_x86_void(), _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_arm_call_type(), M_arm_call_type2(), M_arm_eval_type(), M_arm_eval_type2(), M_bx86_call_type(), M_bx86_call_type2(), M_bx86_eval_type(), M_bx86_eval_type2(), M_call_type(), M_call_type2(), M_eval_type(), M_eval_type2(), M_hppa_call_type(), M_hppa_call_type2(), M_hppa_eval_type(), M_hppa_eval_type2(), M_sh_call_type(), M_sh_call_type2(), M_sh_eval_type(), M_sh_eval_type2(), M_sparc_call_type(), M_sparc_call_type2(), M_sparc_eval_type(), M_sparc_eval_type2(), M_ti_call_type(), M_ti_call_type2(), M_ti_eval_type(), M_ti_eval_type2(), M_wims_call_type(), M_wims_call_type2(), M_wims_eval_type(), M_wims_eval_type2(), M_x86_call_type(), M_x86_call_type2(), M_x86_eval_type(), and M_x86_eval_type2().
int M_zero_macro (L_Operand * opd)
Definition at line 2531 of file ml_spec.c.
References M_arch, M_TAHOE, and TAHOE_MAC_ZERO.
Variable Documentation
int M_arch
Definition at line 86 of file mi_spec.c.
int M_model
Definition at line 87 of file mi_spec.c.