ml_tahoe.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <Lcode/ltahoe_completers.h>
#include `m_spec.h`
#include `m_tahoe.h`
Defines
#define zero_offset(a)
#define label_base(a) (L_is_label((a) $\rightarrow$ src[0]))
Functions
int M_tahoe_fragile_macro (int macro_value)
Set M_tahoe_fragile_macro_set (void)
int M_tahoe_extra_pred_define_opcode (int proc_opc)
int M_tahoe_extra_pred_define_type1 (L_Oper *oper)
int M_tahoe_extra_pred_define_type2 (L_Oper *oper)
int M_tahoe_subroutine_call (int opc)
int M_tahoe_dataflow_macro (int id)
void M_define_macros_tahoe (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_tahoe (int id)
int M_oper_supported_in_arch_tahoe (int opc)
int M_num_oper_required_for_tahoe (L_Oper *oper, char *name)
int M_num_registers_tahoe (int ctype)
int M_is_stack_operand_tahoe (L_Operand *operand)
int M_is_unsafe_macro_tahoe (L_Operand *operand)
int M_operand_type_tahoe (L_Operand *operand)
int M_conflicting_operands_tahoe (L_Operand *operand, L_Operand *conflict_array[], int len, int prepass)
int M_opc_from_proc_opc_tahoe (int proc_opc)
L_Operand * M_tahoe_epilogue_cntr_register ()
L_Operand * M_tahoe_loop_cntr_register ()
int M_cannot_predicate_tahoe (L_Oper *oper)
void M_get_memory_operands_tahoe (int *first, int *number, int proc_opc)
Variables
Set Set_tahoe_fragile_macro = NULL
Define Documentation
#define label_base(a) (L_is_label((a) $\rightarrow$ src[0]))
Definition at line 528 of file ml_tahoe.c.
#define zero_offset(a)
Value:
((L_is_int_constant((a)->src[1])) && \
                          ((a)->src[1]->value.i == 0))
Definition at line 526 of file ml_tahoe.c.
Function Documentation
int M_cannot_predicate_tahoe (L_Oper * oper)
Definition at line 1404 of file ml_tahoe.c.
Referenced by M_cannot_predicate().
int M_conflicting_operands_tahoe (L_Operand * operand, L_Operand * conflict_array[], int len, int prepass)
Definition at line 870 of file ml_tahoe.c.
References M_assert(), TAHOE_MAC_FONE, TAHOE_MAC_FZERO, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_REG_BASE.
Referenced by M_dep_conflicting_operands().
void M_define_macros_tahoe (STRING_Symbol_Table * sym_tbl)
Definition at line 334 of file ml_tahoe.c.
References M_add_symbol, M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_GP_SAVE_REG, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FONE, TAHOE_MAC_FPSR, TAHOE_MAC_FZERO, TAHOE_MAC_GP, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LABEL, TAHOE_MAC_LC, TAHOE_MAC_LEAF, TAHOE_MAC_MEM_ALLOC, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_PSP, TAHOE_MAC_PSPILL, TAHOE_MAC_RETADDR, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_SYNC_SIZE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_TMPREG1, TAHOE_MAC_TMPREG2, TAHOE_MAC_UNAT, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_SAVE_REG.
Referenced by M_define_macros().
char* M_get_macro_name_tahoe (int id)
Definition at line 389 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_GP_SAVE_REG, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FONE, TAHOE_MAC_FPSR, TAHOE_MAC_FZERO, TAHOE_MAC_GP, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LABEL, TAHOE_MAC_LC, TAHOE_MAC_LEAF, TAHOE_MAC_MEM_ALLOC, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_PSP, TAHOE_MAC_PSPILL, TAHOE_MAC_RETADDR, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_SYNC_SIZE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_TMPREG1, TAHOE_MAC_TMPREG2, TAHOE_MAC_UNAT, TAHOE_MAC_ZERO, TAHOE_PRED_BLK_REG, and TAHOE_PRED_SAVE_REG.
Referenced by M_get_macro_name().
void M_get_memory_operands_tahoe (int * first, int * number, int proc_opc)
Definition at line 1420 of file ml_tahoe.c.
Referenced by M_get_memory_operands().
int M_is_stack_operand_tahoe (L_Operand * operand)
Definition at line 752 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_PSP, and TAHOE_MAC_PSPILL.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_tahoe (L_Operand * operand)
Definition at line 778 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_AP, TAHOE_MAC_AR_PFS, TAHOE_MAC_BSP, TAHOE_MAC_CCV, TAHOE_MAC_EC, TAHOE_MAC_FPSR, TAHOE_MAC_ITC, TAHOE_MAC_KR0, TAHOE_MAC_KR1, TAHOE_MAC_KR2, TAHOE_MAC_KR3, TAHOE_MAC_LC, TAHOE_MAC_RNAT, TAHOE_MAC_RSC, TAHOE_MAC_UNAT, and TAHOE_PRED_BLK_REG.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_tahoe (L_Oper * oper, char * name)
Definition at line 531 of file ml_tahoe.c.
References label_base, M_assert(), M_IPF_MODEL_OK, M_model, and zero_offset.
Referenced by M_num_oper_required_for().
int M_num_registers_tahoe (int ctype)
Definition at line 726 of file ml_tahoe.c.
Referenced by M_num_registers().
int M_opc_from_proc_opc_tahoe (int proc_opc)
Definition at line 997 of file ml_tahoe.c.
References I_warn(), M_assert(), TAHOEop_ADD, TAHOEop_ADDL, TAHOEop_ADDP4, TAHOEop_ADDS, TAHOEop_ALLOC, TAHOEop_AND, TAHOEop_ANDCM, TAHOEop_BR_CALL, TAHOEop_BR_CEXIT, TAHOEop_BR_CLOOP, TAHOEop_BR_COND, TAHOEop_BR_CTOP, TAHOEop_BR_RET, TAHOEop_BR_WEXIT, TAHOEop_BR_WTOP, TAHOEop_BRP, TAHOEop_CHK_A, TAHOEop_CHK_S, TAHOEop_CHK_S_F, TAHOEop_CHK_S_I, TAHOEop_CHK_S_M, TAHOEop_CMP, TAHOEop_DEP, TAHOEop_DEP_Z, TAHOEop_EXTR, TAHOEop_EXTR_U, TAHOEop_FABS, TAHOEop_FADD, TAHOEop_FADD_D, TAHOEop_FADD_S, TAHOEop_FAMAX, TAHOEop_FAMIN, TAHOEop_FCMP, TAHOEop_FCVT_FX, TAHOEop_FCVT_FXU, TAHOEop_FCVT_XF, TAHOEop_FMA, TAHOEop_FMA_D, TAHOEop_FMA_S, TAHOEop_FMAX, TAHOEop_FMERGE_NS, TAHOEop_FMERGE_S, TAHOEop_FMERGE_SE, TAHOEop_FMIN, TAHOEop_FMS, TAHOEop_FMS_D, TAHOEop_FMS_S, TAHOEop_FNMA, TAHOEop_FNMA_D, TAHOEop_FNMA_S, TAHOEop_FPACK, TAHOEop_FPAMAX, TAHOEop_FPAMIN, TAHOEop_FPCMP, TAHOEop_FPCVT_FX, TAHOEop_FPCVT_FX_TRUNC, TAHOEop_FPCVT_FXU, TAHOEop_FPCVT_FXU_TRUNC, TAHOEop_FPMA, TAHOEop_FPMAX, TAHOEop_FPMERGE, TAHOEop_FPMERGE_NS, TAHOEop_FPMERGE_S, TAHOEop_FPMIN, TAHOEop_FPMS, TAHOEop_FPNMA, TAHOEop_FPRCPA, TAHOEop_FPRSQRTA, TAHOEop_FRCPA, TAHOEop_FRSQRTA, TAHOEop_FSUB, TAHOEop_FSUB_D, TAHOEop_FSUB_S, TAHOEop_GETF_D, TAHOEop_GETF_EXP, TAHOEop_GETF_S, TAHOEop_GETF_SIG, TAHOEop_INVALID, TAHOEop_LD1, TAHOEop_LD1_C, TAHOEop_LD2, TAHOEop_LD2_C, TAHOEop_LD4, TAHOEop_LD4_C, TAHOEop_LD8, TAHOEop_LD8_C, TAHOEop_LD8_FILL, TAHOEop_LDF_FILL, TAHOEop_LDFD, TAHOEop_LDFD_C, TAHOEop_LDFS, TAHOEop_LDFS_C, TAHOEop_LFETCH, TAHOEop_MOV_FR, TAHOEop_MOV_FRAR_I, TAHOEop_MOV_FRAR_M, TAHOEop_MOV_FRBR, TAHOEop_MOV_FRPR, TAHOEop_MOV_GR, TAHOEop_MOV_TOAR_I, TAHOEop_MOV_TOAR_M, TAHOEop_MOV_TOBR, TAHOEop_MOV_TOPR, TAHOEop_MOVI, TAHOEop_MOVL, TAHOEop_MUX1, TAHOEop_MUX2, TAHOEop_NOP_B, TAHOEop_NOP_F, TAHOEop_NOP_I, TAHOEop_NOP_M, TAHOEop_NOP_X, TAHOEop_OR, TAHOEop_PACK2_SSS, TAHOEop_PACK2_USS, TAHOEop_PACK4_SSS, TAHOEop_PADD1, TAHOEop_PADD1_SSS, TAHOEop_PADD1_UUS, TAHOEop_PADD1_UUU, TAHOEop_PADD2, TAHOEop_PADD2_SSS, TAHOEop_PADD2_UUS, TAHOEop_PADD2_UUU, TAHOEop_PADD4, TAHOEop_PAVG1, TAHOEop_PAVG1_RAZ, TAHOEop_PAVG2, TAHOEop_PAVG2_RAZ, TAHOEop_PAVGSUB1, TAHOEop_PAVGSUB2, TAHOEop_PCMP1_EQ, TAHOEop_PCMP1_GT, TAHOEop_PCMP2_EQ, TAHOEop_PCMP2_GT, TAHOEop_PCMP_EQ, TAHOEop_PCMP_GT, TAHOEop_PMAX1_U, TAHOEop_PMAX2, TAHOEop_PMIN1_U, TAHOEop_PMIN2, TAHOEop_PMPY2_L, TAHOEop_PMPY2_R, TAHOEop_PMPYSHR2, TAHOEop_PMPYSHR2_U, TAHOEop_PSAD1, TAHOEop_PSHL2, TAHOEop_PSHL4, TAHOEop_PSHLADD2, TAHOEop_PSHR2, TAHOEop_PSHR2_U, TAHOEop_PSHR4, TAHOEop_PSHR4_U, TAHOEop_PSHRADD2, TAHOEop_PSUB1, TAHOEop_PSUB1_SSS, TAHOEop_PSUB1_UUS, TAHOEop_PSUB1_UUU, TAHOEop_PSUB2, TAHOEop_PSUB2_SSS, TAHOEop_PSUB2_UUS, TAHOEop_PSUB2_UUU, TAHOEop_PSUB4, TAHOEop_SETF_D, TAHOEop_SETF_EXP, TAHOEop_SETF_S, TAHOEop_SETF_SIG, TAHOEop_SHL, TAHOEop_SHLADD, TAHOEop_SHLADDP4, TAHOEop_SHR, TAHOEop_SHR_U, TAHOEop_ST1, TAHOEop_ST2, TAHOEop_ST4, TAHOEop_ST8, TAHOEop_ST8_SPILL, TAHOEop_STF_SPILL, TAHOEop_STFD, TAHOEop_STFS, TAHOEop_SUB, TAHOEop_SXT1, TAHOEop_SXT2, TAHOEop_SXT4, TAHOEop_TBIT, TAHOEop_XMA_H, TAHOEop_XMA_HU, TAHOEop_XMA_L, TAHOEop_XOR, TAHOEop_ZXT1, TAHOEop_ZXT2, and TAHOEop_ZXT4.
Referenced by M_opc_from_proc_opc().
int M_oper_supported_in_arch_tahoe (int opc)
Definition at line 480 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, and M_model.
Referenced by M_oper_supported_in_arch().
int M_operand_type_tahoe (L_Operand * operand)
Definition at line 822 of file ml_tahoe.c.
References M_assert(), MDES_OPERAND_btr, MDES_OPERAND_f, MDES_OPERAND_i, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_p, and NULL.
Referenced by M_mdes_operand_type().
int M_tahoe_dataflow_macro (int id)
Definition at line 304 of file ml_tahoe.c.
References FALSE, M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_FONE, TAHOE_MAC_FZERO, TAHOE_MAC_LABEL, TAHOE_MAC_PRED_TRUE, TAHOE_MAC_TEMPLATE, TAHOE_MAC_ZERO, and TRUE.
Referenced by M_dataflow_macro().
L_Operand* M_tahoe_epilogue_cntr_register ()
Definition at line 1373 of file ml_tahoe.c.
References TAHOE_MAC_EC.
Referenced by M_return_epilogue_cntr_register().
int M_tahoe_extra_pred_define_opcode (int proc_opc)
Definition at line 213 of file ml_tahoe.c.
References TAHOEop_FRCPA, TAHOEop_FRSQRTA, and TAHOEop_TBIT.
Referenced by M_extra_pred_define_opcode().
int M_tahoe_extra_pred_define_type1 (L_Oper * oper)
Definition at line 236 of file ml_tahoe.c.
References TAHOEop_CMP, and TAHOEop_TBIT.
Referenced by M_extra_pred_define_type1().
int M_tahoe_extra_pred_define_type2 (L_Oper * oper)
Definition at line 265 of file ml_tahoe.c.
References TAHOEop_FRCPA, and TAHOEop_FRSQRTA.
Referenced by M_extra_pred_define_type2().
int M_tahoe_fragile_macro (int macro_value)
Definition at line 82 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, M_model, TAHOE_MAC_AP, TAHOE_MAC_EC, TAHOE_MAC_LC, TAHOE_MAC_TMPREG1, and TAHOE_MAC_TMPREG2.
Referenced by M_fragile_macro().
Set M_tahoe_fragile_macro_set (void)
Definition at line 145 of file ml_tahoe.c.
References Set_add(), Set_tahoe_fragile_macro, TAHOE_MAC_AP, TAHOE_MAC_EC, TAHOE_MAC_LC, TAHOE_MAC_TMPREG1, and TAHOE_MAC_TMPREG2.
Referenced by M_fragile_macro_set().
L_Operand* M_tahoe_loop_cntr_register ()
Definition at line 1381 of file ml_tahoe.c.
References I_punt(), and NULL.
Referenced by M_return_loop_cntr_register().
int M_tahoe_subroutine_call (int opc)
Definition at line 284 of file ml_tahoe.c.
References M_assert(), M_IPF_MODEL_OK, and M_model.
Referenced by M_subroutine_call().
Variable Documentation
Set Set_tahoe_fragile_macro = NULL
Definition at line 72 of file ml_tahoe.c.
Referenced by M_tahoe_fragile_macro_set().