ml_arm.c File Reference
#include <stdio.h>
#include <Lcode/l_main.h>
#include `m_arm.h`
Defines
#define M_ARM_SIZE_VOID 0
#define M_ARM_SIZE_BIT 1
#define M_ARM_SIZE_CHAR 8
#define M_ARM_SIZE_SHORT 16
#define M_ARM_SIZE_INT 32
#define M_ARM_SIZE_LONG 32
#define M_ARM_SIZE_LLONG 64
#define M_ARM_SIZE_FLOAT 32
#define M_ARM_SIZE_DOUBLE 64
#define M_ARM_SIZE_POINTER 32
#define M_ARM_SIZE_UNION -1
#define M_ARM_SIZE_STRUCT -1
#define M_ARM_SIZE_BLOCK -1
#define M_ARM_SIZE_MAX 64
#define M_ARM_ALIGN_VOID -1
#define M_ARM_ALIGN_BIT 1
#define M_ARM_ALIGN_CHAR 8
#define M_ARM_ALIGN_SHORT 16
#define M_ARM_ALIGN_INT 32
#define M_ARM_ALIGN_LONG 32
#define M_ARM_ALIGN_LLONG 64
#define M_ARM_ALIGN_FLOAT 32
#define M_ARM_ALIGN_DOUBLE 64
#define M_ARM_ALIGN_POINTER 32
#define M_ARM_ALIGN_UNION -1
#define M_ARM_ALIGN_STRUCT -1
#define M_ARM_ALIGN_BLOCK -1
#define M_ARM_ALIGN_MAX 64
#define M_ARM_MAX_FNVAR_REG 4
#define M_ARM_SMALL_STRUCT_MAX 32
#define MIN_PARAM_SIZE (M_ARM_MAX_FNVAR_REG * M_ARM_SIZE_INT)
#define M_ARM_INT_BASE 0
#define M_ARM_FLT_BASE 5
#define M_ARM_DBL_BASE 9
#define M_ARM_RET_F 15
#define M_ARM_RET_I32 15
#define M_ARM_RET_I64 15
#define M_ARM_RET_ST 15
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_arm_void (M_Type type)
void M_arm_bit_long (M_Type type, int n)
void M_arm_bit_int (M_Type type, int n)
void M_arm_bit_short (M_Type type, int n)
void M_arm_bit_char (M_Type type, int n)
void M_arm_float (M_Type type, int unsign)
void M_arm_double (M_Type type, int unsign)
void M_arm_pointer (M_Type type)
int M_arm_eval_type (M_Type type, M_Type ntype)
int M_arm_eval_type2 (M_Type type, M_Type ntype)
int M_arm_call_type (M_Type type, M_Type ntype)
int M_arm_call_type2 (M_Type type, M_Type ntype)
void M_arm_array_layout (M_Type type, int *offset)
int M_arm_array_align (M_Type type)
int M_arm_array_size (M_Type type, int dim)
void M_arm_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_arm_union_align (int n, _M_Type *type)
int M_arm_union_size (int n, _M_Type *type)
void M_arm_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_arm_struct_align (int n, _M_Type *type)
int M_arm_struct_size (int n, _M_Type *type, int struct_align)
static int M_ARM_align_offset (int offset, int align_bit)
int M_arm_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose, int needs_st)
int M_arm_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int needs_st, int purpose)
int M_arm_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_arm_no_short_int (void)
void M_arm_cb_label_name (char *fn, int cb, char *line, int len)
int M_arm_is_cb_label (char *label, char *fn, int *cb)
void M_arm_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_arm_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_arm_structure_pointer (int purpose)
int M_arm_return_register (int type, int purpose)
char * M_arm_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_arm_fn_name_from_label (char *label)
int M_arm_fragile_macro (int macro_value)
int M_arm_subroutine_call (int opc)
void M_define_macros_arm (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_arm (int id)
void M_define_opcode_name_arm (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_arm (int id)
int M_oper_supported_in_arch_arm (int opc)
int M_num_oper_required_for_arm (L_Oper *oper, char *name)
int M_is_stack_operand_arm (L_Operand *operand)
int M_is_unsafe_macro_arm (L_Operand *operand)
int M_operand_type_arm (L_Operand *operand)
int M_conflicting_operands_arm (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_arm (int ctype)
int M_arm_layout_retvar (M_Param param, int purpose)
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), and M_num_oper_required_for_wims().
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
#define long_neg_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
#define long_pos_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
#define M_ARM_ALIGN_BIT 1
Definition at line 166 of file ml_arm.c.
#define M_ARM_ALIGN_BLOCK -1
Definition at line 177 of file ml_arm.c.
#define M_ARM_ALIGN_CHAR 8
Definition at line 167 of file ml_arm.c.
#define M_ARM_ALIGN_DOUBLE 64
Definition at line 173 of file ml_arm.c.
#define M_ARM_ALIGN_FLOAT 32
Definition at line 172 of file ml_arm.c.
#define M_ARM_ALIGN_INT 32
Definition at line 169 of file ml_arm.c.
#define M_ARM_ALIGN_LLONG 64
Definition at line 171 of file ml_arm.c.
#define M_ARM_ALIGN_LONG 32
Definition at line 170 of file ml_arm.c.
#define M_ARM_ALIGN_MAX 64
Definition at line 178 of file ml_arm.c.
#define M_ARM_ALIGN_POINTER 32
Definition at line 174 of file ml_arm.c.
#define M_ARM_ALIGN_SHORT 16
Definition at line 168 of file ml_arm.c.
#define M_ARM_ALIGN_STRUCT -1
Definition at line 176 of file ml_arm.c.
#define M_ARM_ALIGN_UNION -1
Definition at line 175 of file ml_arm.c.
#define M_ARM_ALIGN_VOID -1
Definition at line 165 of file ml_arm.c.
#define M_ARM_DBL_BASE 9
Definition at line 188 of file ml_arm.c.
Referenced by M_arm_fnvar_layout(), and M_arm_layout_fnvar().
#define M_ARM_FLT_BASE 5
Definition at line 187 of file ml_arm.c.
Referenced by M_arm_fnvar_layout(), and M_arm_layout_fnvar().
#define M_ARM_INT_BASE 0
Definition at line 186 of file ml_arm.c.
Referenced by M_arm_fnvar_layout(), and M_arm_layout_fnvar().
#define M_ARM_MAX_FNVAR_REG 4
Definition at line 181 of file ml_arm.c.
Referenced by M_arm_fnvar_layout(), and M_arm_layout_fnvar().
#define M_ARM_RET_F 15
Definition at line 190 of file ml_arm.c.
Referenced by M_arm_return_register().
#define M_ARM_RET_I32 15
Definition at line 192 of file ml_arm.c.
Referenced by M_arm_return_register().
#define M_ARM_RET_I64 15
Definition at line 193 of file ml_arm.c.
Referenced by M_arm_return_register().
#define M_ARM_RET_ST 15
Definition at line 194 of file ml_arm.c.
Referenced by M_arm_structure_pointer().
#define M_ARM_SIZE_BIT 1
Definition at line 151 of file ml_arm.c.
#define M_ARM_SIZE_BLOCK -1
Definition at line 162 of file ml_arm.c.
#define M_ARM_SIZE_CHAR 8
Definition at line 152 of file ml_arm.c.
#define M_ARM_SIZE_DOUBLE 64
Definition at line 158 of file ml_arm.c.
#define M_ARM_SIZE_FLOAT 32
Definition at line 157 of file ml_arm.c.
#define M_ARM_SIZE_INT 32
Definition at line 154 of file ml_arm.c.
#define M_ARM_SIZE_LLONG 64
Definition at line 156 of file ml_arm.c.
#define M_ARM_SIZE_LONG 32
Definition at line 155 of file ml_arm.c.
#define M_ARM_SIZE_MAX 64
Definition at line 163 of file ml_arm.c.
#define M_ARM_SIZE_POINTER 32
Definition at line 159 of file ml_arm.c.
#define M_ARM_SIZE_SHORT 16
Definition at line 153 of file ml_arm.c.
#define M_ARM_SIZE_STRUCT -1
Definition at line 161 of file ml_arm.c.
#define M_ARM_SIZE_UNION -1
Definition at line 160 of file ml_arm.c.
#define M_ARM_SIZE_VOID 0
Definition at line 150 of file ml_arm.c.
#define M_ARM_SMALL_STRUCT_MAX 32
Definition at line 182 of file ml_arm.c.
#define MIN_PARAM_SIZE (M_ARM_MAX_FNVAR_REG * M_ARM_SIZE_INT)
Definition at line 183 of file ml_arm.c.
Referenced by M_bx86_fnvar_layout(), M_hppa_fnvar_layout(), M_impact_fnvar_layout(), M_impact_layout_fnvar(), M_playdoh_fnvar_layout(), M_playdoh_layout_fnvar(), M_sparc_fnvar_layout(), M_ti_fnvar_layout(), M_wims_fnvar_layout(), M_wims_layout_fnvar(), and M_x86_fnvar_layout().
#define non_zero_offset(a)
Value:
((!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                   ((a->src[1]->ctype&0x30)==0x00)))||\
                                 (a->src[1]->value.i != 0))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
#define short_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Referenced by M_num_oper_required_for_arm(), M_num_oper_required_for_bx86(), M_num_oper_required_for_hppa(), M_num_oper_required_for_impact(), M_num_oper_required_for_playdoh(), M_num_oper_required_for_ti(), M_num_oper_required_for_wims(), and M_num_oper_required_for_x86().
Function Documentation
static int M_ARM_align_offset (int offset, int align_bit) [static]
Definition at line 675 of file ml_arm.c.
References I_punt().
Referenced by M_arm_fnvar_layout(), and M_arm_layout_fnvar().
int M_arm_array_align (M_Type type)
Definition at line 438 of file ml_arm.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_arm_array_layout (M_Type type, int * offset)
Definition at line 433 of file ml_arm.c.
Referenced by M_array_layout().
int M_arm_array_size (M_Type type, int dim)
Definition at line 443 of file ml_arm.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_arm_bit_char (M_Type type, int n)
Definition at line 241 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_arm_bit_int (M_Type type, int n)
Definition at line 221 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_arm_bit_long (M_Type type, int n)
Definition at line 211 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_arm_bit_short (M_Type type, int n)
Definition at line 231 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_BIT, M_ARM_SIZE_BIT, M_assert(), M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_arm_call_type (M_Type type, M_Type ntype)
Definition at line 358 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_arm_call_type2 (M_Type type, M_Type ntype)
Definition at line 394 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_pointer(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_arm_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1191 of file ml_arm.c.
Referenced by M_cb_label_name().
void M_arm_double (M_Type type, int unsign)
Definition at line 260 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_DOUBLE, M_ARM_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_arm_eval_type (M_Type type, M_Type ntype)
Definition at line 279 of file ml_arm.c.
References M_arm_llong(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_arm_eval_type2 (M_Type type, M_Type ntype)
Definition at line 314 of file ml_arm.c.
References M_arm_llong(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LLONG, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_arm_float (M_Type type, int unsign)
Definition at line 251 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_FLOAT, M_ARM_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_arm_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1259 of file ml_arm.c.
Referenced by M_fn_label_name().
char* M_arm_fn_name_from_label (char * label)
Definition at line 1271 of file ml_arm.c.
Referenced by M_fn_name_from_label().
int M_arm_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int needs_st, int purpose)
Definition at line 923 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_align_offset(), M_ARM_DBL_BASE, M_ARM_FLT_BASE, M_ARM_INT_BASE, M_ARM_MAX_FNVAR_REG, M_ARM_SIZE_DOUBLE, M_ARM_SIZE_FLOAT, M_ARM_SIZE_INT, M_ARM_SIZE_LLONG, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_arm_fragile_macro (int macro_value)
Definition at line 1280 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_fragile_macro().
int M_arm_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1196 of file ml_arm.c.
Referenced by M_is_cb_label().
int M_arm_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1207 of file ml_arm.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_arm_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1201 of file ml_arm.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_arm_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose, int needs_st)
Definition at line 692 of file ml_arm.c.
References _struct_M_Type::align, List_next(), List_start(), M_ARM_align_offset(), M_ARM_DBL_BASE, M_ARM_FLT_BASE, M_ARM_INT_BASE, M_ARM_MAX_FNVAR_REG, M_ARM_SIZE_DOUBLE, M_ARM_SIZE_FLOAT, M_ARM_SIZE_INT, M_ARM_SIZE_LLONG, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, _struct_M_Param::su_ereg, _struct_M_Param::su_sreg, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_arm_layout_retvar (M_Param param, int purpose)
Definition at line 1710 of file ml_arm.c.
References M_INDIRECT_THRU_MEMORY, M_THRU_MEMORY, M_TYPE_STRUCT, M_TYPE_UNION, _struct_M_Param::mode, _struct_M_Param::mtype, and _struct_M_Type::type.
Referenced by M_layout_retvar().
int M_arm_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 1147 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_MAX, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_arm_no_short_int (void)
Definition at line 1187 of file ml_arm.c.
References M_ARM_SIZE_INT, and M_ARM_SIZE_SHORT.
Referenced by M_no_short_int().
void M_arm_pointer (M_Type type)
Definition at line 269 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_POINTER, M_ARM_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_arm_return_register (int type, int purpose)
Definition at line 1244 of file ml_arm.c.
References M_ARM_RET_F, M_ARM_RET_I32, M_ARM_RET_I64, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LLONG, and M_TYPE_LONG.
Referenced by M_return_register().
int M_arm_struct_align (int n, _M_Type * type)
Definition at line 603 of file ml_arm.c.
References M_ARM_ALIGN_CHAR.
Referenced by M_struct_align().
void M_arm_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 516 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_SIZE_CHAR, M_ARM_SIZE_INT, M_ARM_SIZE_LONG, M_ARM_SIZE_SHORT, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_arm_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 619 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_CHAR, M_ARM_ALIGN_LONG, M_ARM_ALIGN_SHORT, M_ARM_SIZE_INT, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_arm_structure_pointer (int purpose)
Definition at line 1239 of file ml_arm.c.
References M_ARM_RET_ST.
Referenced by M_structure_pointer().
int M_arm_subroutine_call (int opc)
Definition at line 1303 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_subroutine_call().
int M_arm_union_align (int n, _M_Type * type)
Definition at line 466 of file ml_arm.c.
References M_ARM_ALIGN_CHAR.
Referenced by M_union_align().
void M_arm_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 457 of file ml_arm.c.
Referenced by M_union_layout().
int M_arm_union_size (int n, _M_Type * type)
Definition at line 484 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_arm_void (M_Type type)
Definition at line 202 of file ml_arm.c.
References _struct_M_Type::align, M_ARM_ALIGN_VOID, M_ARM_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
int M_conflicting_operands_arm (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1626 of file ml_arm.c.
References ARM_MAC_TRUE_SP, and M_assert().
Referenced by M_dep_conflicting_operands().
void M_define_macros_arm (STRING_Symbol_Table * sym_tbl)
Definition at line 1319 of file ml_arm.c.
References ARM_MAC_ALLOC, ARM_MAC_CALLEE_I, ARM_MAC_FONE, ARM_MAC_FZERO, ARM_MAC_LEAF, ARM_MAC_RETADDR, ARM_MAC_TRUE_SP, and M_add_symbol.
Referenced by M_define_macros().
void M_define_opcode_name_arm (STRING_Symbol_Table * sym_tbl)
Definition at line 1349 of file ml_arm.c.
Referenced by M_define_opcode_name().
char* M_get_macro_name_arm (int id)
Definition at line 1333 of file ml_arm.c.
References ARM_MAC_ALLOC, ARM_MAC_CALLEE_I, ARM_MAC_FONE, ARM_MAC_FZERO, ARM_MAC_LEAF, ARM_MAC_RETADDR, and ARM_MAC_TRUE_SP.
Referenced by M_get_macro_name().
char* M_get_opcode_name_arm (int id)
Definition at line 1353 of file ml_arm.c.
Referenced by M_get_opcode_name().
int M_is_stack_operand_arm (L_Operand * operand)
Definition at line 1549 of file ml_arm.c.
References ARM_MAC_TRUE_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_arm (L_Operand * operand)
Definition at line 1566 of file ml_arm.c.
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_arm (L_Oper * oper, char * name)
Definition at line 1405 of file ml_arm.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_arm (int ctype)
Definition at line 1686 of file ml_arm.c.
References M_ARM_1_01, M_assert(), and M_model.
Referenced by M_num_registers().
int M_oper_supported_in_arch_arm (int opc)
Definition at line 1365 of file ml_arm.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_arm (L_Operand * operand)
Definition at line 1592 of file ml_arm.c.
References FIELD_11, FIELD_14, FIELD_5, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit11, MDES_OPERAND_Lit14, MDES_OPERAND_Lit21, MDES_OPERAND_Lit5, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().