ml_bx86.c File Reference
#include <config.h>
#include <library/i_error.h>
#include <Lcode/l_main.h>
#include `m_spec.h`
#include `m_bx86.h`
Defines
#define M_BX86_SIZE_VOID 0
#define M_BX86_SIZE_BIT 1
#define M_BX86_SIZE_CHAR 8
#define M_BX86_SIZE_SHORT 16
#define M_BX86_SIZE_INT 32
#define M_BX86_SIZE_LONG 32
#define M_BX86_SIZE_FLOAT 32
#define M_BX86_SIZE_DOUBLE 64
#define M_BX86_SIZE_POINTER 32
#define M_BX86_SIZE_UNION -1
#define M_BX86_SIZE_STRUCT -1
#define M_BX86_SIZE_BLOCK -1
#define M_BX86_SIZE_MAX 64
#define M_BX86_ALIGN_VOID -1
#define M_BX86_ALIGN_BIT 1
#define M_BX86_ALIGN_CHAR 8
#define M_BX86_ALIGN_SHORT 16
#define M_BX86_ALIGN_INT 32
#define M_BX86_ALIGN_LONG 32
#define M_BX86_ALIGN_FLOAT 32
#define M_BX86_ALIGN_DOUBLE 32
#define M_BX86_ALIGN_POINTER 32
#define M_BX86_ALIGN_UNION -1
#define M_BX86_ALIGN_STRUCT -1
#define M_BX86_ALIGN_BLOCK -1
#define M_BX86_ALIGN_MAX 64
#define M_BX86_MAX_FNVAR_REG 0
#define M_BX86_SMALL_STRUCT_MAX 04
#define MIN_PARAM_SIZE (16 * 0)
#define M_BX86_INT_BASE 0
#define M_BX86_FLT_BASE 4
#define M_BX86_RET_I32 0
#define M_BX86_RET_I64 0
#define M_BX86_RET_ST 0
#define M_BX86_RET_F 1
#define M_BX86_RET_F2 1
#define M_BX86_VAR_PTR `$LV`
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define MSPEC_oszapc_flags LBX86_MAC_OSZAPC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_c_flags LBX86_MAC_C_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_oszap_flags LBX86_MAC_OSZAP_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_oc_flags LBX86_MAC_OC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_szapc_flags LBX86_MAC_SZAPC_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
#define MSPEC_oszpc_flags LBX86_MAC_OSZPC_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
#define MSPEC_z_flags LBX86_MAC_Z_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_zc_flags LBX86_MAC_ZC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_osz_flags LBX86_MAC_OSZ_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
#define MSPEC_os_flags LBX86_MAC_OS_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_d_flags LBX86_MAC_D_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_o_flags LBX86_MAC_O_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_s_flags LBX86_MAC_S_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_a_flags LBX86_MAC_A_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_p_flags LBX86_MAC_P_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_gp_reg32 LBX86_MAC_ALL_GP_REG32,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_gp_reg16 LBX86_MAC_ALL_GP_REG16,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_eax LBX86_MAC_EAX,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_ebx LBX86_MAC_EBX,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_ecx LBX86_MAC_ECX,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_edx LBX86_MAC_EDX,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_esi LBX86_MAC_ESI,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_edi LBX86_MAC_EDI,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_ebp LBX86_MAC_EBP,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_esp LBX86_MAC_ESP,L_CTYPE_INT,L_PTYPE_NULL
#define MSPEC_ax LBX86_MAC_AX,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_bx LBX86_MAC_BX,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_cx LBX86_MAC_CX,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_dx LBX86_MAC_DX,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_si LBX86_MAC_SI,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_di LBX86_MAC_DI,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_bp LBX86_MAC_BP,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_sp LBX86_MAC_SP,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_eaxh LBX86_MAC_EAXH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_ebxh LBX86_MAC_EBXH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_ecxh LBX86_MAC_ECXH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_edxh LBX86_MAC_EDXH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_esih LBX86_MAC_ESIH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_edih LBX86_MAC_EDIH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_ebph LBX86_MAC_EBPH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_esph LBX86_MAC_ESPH,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_al LBX86_MAC_AL,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_bl LBX86_MAC_BL,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_cl LBX86_MAC_CL,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_dl LBX86_MAC_DL,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_ah LBX86_MAC_AH,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_bh LBX86_MAC_BH,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_ch LBX86_MAC_CH,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_dh LBX86_MAC_DH,L_CTYPE_CHAR,L_PTYPE_NULL
#define MSPEC_cs LBX86_MAC_CS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_ds LBX86_MAC_DS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_es LBX86_MAC_ES,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_fs LBX86_MAC_FS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_gs LBX86_MAC_GS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_ss LBX86_MAC_SS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_all_fst LBX86_MAC_ALL_FST,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st0 LBX86_MAC_ST0,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st1 LBX86_MAC_ST1,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st2 LBX86_MAC_ST2,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st3 LBX86_MAC_ST3,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st4 LBX86_MAC_ST4,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st5 LBX86_MAC_ST5,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st6 LBX86_MAC_ST6,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_st7 LBX86_MAC_ST7,L_CTYPE_FLOAT,L_PTYPE_NULL
#define MSPEC_all_mm LBX86_MAC_ALL_MM,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm0 LBX86_MAC_MM0,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm1 LBX86_MAC_MM1,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm2 LBX86_MAC_MM2,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm3 LBX86_MAC_MM3,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm4 LBX86_MAC_MM4,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm5 LBX86_MAC_MM5,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm6 LBX86_MAC_MM6,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_mm7 LBX86_MAC_MM7,L_CTYPE_LONG,L_PTYPE_NULL
#define MSPEC_addr LBX86_MAC_ADDR,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_fpsw LBX86_MAC_FPSW,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_fpcw LBX86_MAC_FPCW,L_CTYPE_VOID,L_PTYPE_NULL
Functions
void M_bx86_void (M_Type type)
void M_bx86_bit_long (M_Type type, int n)
void M_bx86_bit_int (M_Type type, int n)
void M_bx86_bit_short (M_Type type, int n)
void M_bx86_bit_char (M_Type type, int n)
void M_bx86_float (M_Type type, int unsign)
void M_bx86_double (M_Type type, int unsign)
void M_bx86_pointer (M_Type type)
int M_bx86_eval_type (M_Type type, M_Type ntype)
int M_bx86_eval_type2 (M_Type type, M_Type ntype)
int M_bx86_call_type (M_Type type, M_Type ntype)
int M_bx86_call_type2 (M_Type type, M_Type ntype)
void M_bx86_array_layout (M_Type type, int *offset)
int M_bx86_array_align (M_Type type)
int M_bx86_array_size (M_Type type, int dim)
void M_bx86_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_bx86_union_align (int n, _M_Type *type)
int M_bx86_union_size (int n, _M_Type *type)
void M_bx86_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_bx86_struct_align (int n, _M_Type *type)
int M_bx86_struct_size (int n, _M_Type *type, int struct_align)
int M_bx86_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_bx86_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_bx86_no_short_int (void)
void M_bx86_cb_label_name (char *fn, int cb, char *line, int len)
int M_bx86_is_cb_label (char *label, char *fn, int *cb)
void M_bx86_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_bx86_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_bx86_structure_pointer (int purpose)
int M_bx86_return_register (int type, int purpose)
char * M_bx86_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_bx86_fn_name_from_label (char *label)
int M_bx86_fragile_macro (int macro_value)
int M_bx86_subroutine_call (int opc)
void M_define_macros_bx86 (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_bx86 (int id)
void M_define_opcode_name_bx86 (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_bx86 (int id)
int M_oper_supported_in_arch_bx86 (int opc)
int M_num_oper_required_for_bx86 (L_Oper *oper, char *name)
int M_is_stack_operand_bx86 (L_Operand *operand)
int M_is_unsafe_macro_bx86 (L_Operand *operand)
int M_operand_type_bx86 (L_Operand *operand)
int M_conflicting_operands_bx86 (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
void M_get_memory_operands_bx86 (int *first, int *number, int proc_opc)
int M_memory_access_size_bx86 (L_Oper *op)
int M_get_data_type_bx86 (L_Oper *op)
int M_num_registers_bx86 (int ctype)
int M_is_implicit_memory_op_bx86 (L_Oper *oper)
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define long_neg_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_BX86_ALIGN_BIT 1
Definition at line 96 of file ml_bx86.c.
#define M_BX86_ALIGN_BLOCK -1
Definition at line 106 of file ml_bx86.c.
#define M_BX86_ALIGN_CHAR 8
Definition at line 97 of file ml_bx86.c.
#define M_BX86_ALIGN_DOUBLE 32
Definition at line 102 of file ml_bx86.c.
#define M_BX86_ALIGN_FLOAT 32
Definition at line 101 of file ml_bx86.c.
#define M_BX86_ALIGN_INT 32
Definition at line 99 of file ml_bx86.c.
#define M_BX86_ALIGN_LONG 32
Definition at line 100 of file ml_bx86.c.
#define M_BX86_ALIGN_MAX 64
Definition at line 107 of file ml_bx86.c.
#define M_BX86_ALIGN_POINTER 32
Definition at line 103 of file ml_bx86.c.
#define M_BX86_ALIGN_SHORT 16
Definition at line 98 of file ml_bx86.c.
#define M_BX86_ALIGN_STRUCT -1
Definition at line 105 of file ml_bx86.c.
#define M_BX86_ALIGN_UNION -1
Definition at line 104 of file ml_bx86.c.
#define M_BX86_ALIGN_VOID -1
Definition at line 95 of file ml_bx86.c.
#define M_BX86_FLT_BASE 4
Definition at line 119 of file ml_bx86.c.
Referenced by M_bx86_fnvar_layout().
#define M_BX86_INT_BASE 0
Definition at line 118 of file ml_bx86.c.
Referenced by M_bx86_fnvar_layout().
#define M_BX86_MAX_FNVAR_REG 0
Definition at line 113 of file ml_bx86.c.
Referenced by M_bx86_fnvar_layout().
#define M_BX86_RET_F 1
Definition at line 124 of file ml_bx86.c.
Referenced by M_bx86_return_register().
#define M_BX86_RET_F2 1
Definition at line 125 of file ml_bx86.c.
#define M_BX86_RET_I32 0
Definition at line 121 of file ml_bx86.c.
Referenced by M_bx86_return_register().
#define M_BX86_RET_I64 0
Definition at line 122 of file ml_bx86.c.
#define M_BX86_RET_ST 0
Definition at line 123 of file ml_bx86.c.
Referenced by M_bx86_structure_pointer().
#define M_BX86_SIZE_BIT 1
Definition at line 82 of file ml_bx86.c.
#define M_BX86_SIZE_BLOCK -1
Definition at line 92 of file ml_bx86.c.
#define M_BX86_SIZE_CHAR 8
Definition at line 83 of file ml_bx86.c.
#define M_BX86_SIZE_DOUBLE 64
Definition at line 88 of file ml_bx86.c.
#define M_BX86_SIZE_FLOAT 32
Definition at line 87 of file ml_bx86.c.
#define M_BX86_SIZE_INT 32
Definition at line 85 of file ml_bx86.c.
#define M_BX86_SIZE_LONG 32
Definition at line 86 of file ml_bx86.c.
#define M_BX86_SIZE_MAX 64
Definition at line 93 of file ml_bx86.c.
#define M_BX86_SIZE_POINTER 32
Definition at line 89 of file ml_bx86.c.
#define M_BX86_SIZE_SHORT 16
Definition at line 84 of file ml_bx86.c.
#define M_BX86_SIZE_STRUCT -1
Definition at line 91 of file ml_bx86.c.
#define M_BX86_SIZE_UNION -1
Definition at line 90 of file ml_bx86.c.
#define M_BX86_SIZE_VOID 0
Definition at line 81 of file ml_bx86.c.
#define M_BX86_SMALL_STRUCT_MAX 04
Definition at line 114 of file ml_bx86.c.
Referenced by M_bx86_fnvar_layout().
#define M_BX86_VAR_PTR `$LV`
Definition at line 126 of file ml_bx86.c.
Referenced by M_bx86_lvar_layout().
#define MIN_PARAM_SIZE (16 * 0)
Definition at line 115 of file ml_bx86.c.
#define MSPEC_a_flags LBX86_MAC_A_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_addr LBX86_MAC_ADDR,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_ah LBX86_MAC_AH,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_al LBX86_MAC_AL,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_all_fst LBX86_MAC_ALL_FST,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_all_mm LBX86_MAC_ALL_MM,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ax LBX86_MAC_AX,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_bh LBX86_MAC_BH,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_bl LBX86_MAC_BL,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_bp LBX86_MAC_BP,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_bx LBX86_MAC_BX,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_c_flags LBX86_MAC_C_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ch LBX86_MAC_CH,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_cl LBX86_MAC_CL,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_cs LBX86_MAC_CS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_cx LBX86_MAC_CX,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_d_flags LBX86_MAC_D_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_dh LBX86_MAC_DH,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_di LBX86_MAC_DI,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_dl LBX86_MAC_DL,L_CTYPE_CHAR,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ds LBX86_MAC_DS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_dx LBX86_MAC_DX,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_eax LBX86_MAC_EAX,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_eaxh LBX86_MAC_EAXH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ebp LBX86_MAC_EBP,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ebph LBX86_MAC_EBPH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ebx LBX86_MAC_EBX,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ebxh LBX86_MAC_EBXH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ecx LBX86_MAC_ECX,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ecxh LBX86_MAC_ECXH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_edi LBX86_MAC_EDI,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_edih LBX86_MAC_EDIH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_edx LBX86_MAC_EDX,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_edxh LBX86_MAC_EDXH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_es LBX86_MAC_ES,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_esi LBX86_MAC_ESI,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_esih LBX86_MAC_ESIH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_esp LBX86_MAC_ESP,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_esph LBX86_MAC_ESPH,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_fpcw LBX86_MAC_FPCW,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_fpsw LBX86_MAC_FPSW,L_CTYPE_VOID,L_PTYPE_NULL
#define MSPEC_fs LBX86_MAC_FS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_gp_reg16 LBX86_MAC_ALL_GP_REG16,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_gp_reg32 LBX86_MAC_ALL_GP_REG32,L_CTYPE_INT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_gs LBX86_MAC_GS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_mm0 LBX86_MAC_MM0,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm1 LBX86_MAC_MM1,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm2 LBX86_MAC_MM2,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm3 LBX86_MAC_MM3,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm4 LBX86_MAC_MM4,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm5 LBX86_MAC_MM5,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm6 LBX86_MAC_MM6,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_mm7 LBX86_MAC_MM7,L_CTYPE_LONG,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_o_flags LBX86_MAC_O_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_oc_flags LBX86_MAC_OC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_os_flags LBX86_MAC_OS_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_osz_flags LBX86_MAC_OSZ_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_oszap_flags LBX86_MAC_OSZAP_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_oszapc_flags LBX86_MAC_OSZAPC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_oszpc_flags LBX86_MAC_OSZPC_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_p_flags LBX86_MAC_P_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_s_flags LBX86_MAC_S_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_si LBX86_MAC_SI,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_sp LBX86_MAC_SP,L_CTYPE_SHORT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_ss LBX86_MAC_SS,L_CTYPE_SHORT,L_PTYPE_NULL
#define MSPEC_st0 LBX86_MAC_ST0,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st1 LBX86_MAC_ST1,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st2 LBX86_MAC_ST2,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st3 LBX86_MAC_ST3,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st4 LBX86_MAC_ST4,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st5 LBX86_MAC_ST5,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st6 LBX86_MAC_ST6,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_st7 LBX86_MAC_ST7,L_CTYPE_FLOAT,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_szapc_flags LBX86_MAC_SZAPC_FLAGS,L_CTYPE_VOID, L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_z_flags LBX86_MAC_Z_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define MSPEC_zc_flags LBX86_MAC_ZC_FLAGS,L_CTYPE_VOID,L_PTYPE_NULL
Referenced by M_conflicting_operands_bx86().
#define non_zero_offset(a)
Value:
(!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) ||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_bx86_array_align (M_Type type)
Definition at line 397 of file ml_bx86.c.
References _struct_M_Type::align, and I_punt().
void M_bx86_array_layout (M_Type type, int * offset)
Definition at line 390 of file ml_bx86.c.
References I_punt().
int M_bx86_array_size (M_Type type, int dim)
Definition at line 404 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), and _struct_M_Type::size.
void M_bx86_bit_char (M_Type type, int n)
Definition at line 184 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_bx86_bit_int (M_Type type, int n)
Definition at line 158 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_bx86_bit_long (M_Type type, int n)
Definition at line 145 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_bx86_bit_short (M_Type type, int n)
Definition at line 171 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_BIT, M_BX86_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_bx86_call_type (M_Type type, M_Type ntype)
Definition at line 309 of file ml_bx86.c.
References I_punt(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
int M_bx86_call_type2 (M_Type type, M_Type ntype)
Definition at line 345 of file ml_bx86.c.
References I_punt(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
void M_bx86_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1017 of file ml_bx86.c.
Referenced by M_cb_label_name().
void M_bx86_double (M_Type type, int unsign)
Definition at line 208 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_DOUBLE, M_BX86_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_bx86_eval_type (M_Type type, M_Type ntype)
Definition at line 231 of file ml_bx86.c.
References I_punt(), M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_bx86_eval_type2 (M_Type type, M_Type ntype)
Definition at line 266 of file ml_bx86.c.
References I_punt(), M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_bx86_float (M_Type type, int unsign)
Definition at line 197 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_FLOAT, M_BX86_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_bx86_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1091 of file ml_bx86.c.
Referenced by M_fn_label_name().
char* M_bx86_fn_name_from_label (char * label)
Definition at line 1106 of file ml_bx86.c.
Referenced by M_fn_name_from_label().
int M_bx86_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 721 of file ml_bx86.c.
References _struct_M_Type::align, have_reversed, I_punt(), M_assert(), M_BX86_ALIGN_INT, M_BX86_ALIGN_MAX, M_BX86_FLT_BASE, M_BX86_INT_BASE, M_BX86_MAX_FNVAR_REG, M_BX86_SIZE_INT, M_BX86_SMALL_STRUCT_MAX, M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
int M_bx86_fragile_macro (int macro_value)
Definition at line 1118 of file ml_bx86.c.
References M_assert(), M_B_486, M_B_K5, M_B_K6, M_B_K6_MMX, M_B_K6_PLUS, M_B_PENTIUM, M_B_PENTIUM_II, M_B_PENTIUM_MMX, M_B_PPRO, and M_model.
Referenced by M_fragile_macro().
int M_bx86_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1023 of file ml_bx86.c.
Referenced by M_is_cb_label().
int M_bx86_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1036 of file ml_bx86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_bx86_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1029 of file ml_bx86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_bx86_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 968 of file ml_bx86.c.
References _struct_M_Type::align, M_assert(), M_BX86_ALIGN_MAX, M_BX86_VAR_PTR, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
int M_bx86_no_short_int (void)
Definition at line 1011 of file ml_bx86.c.
References M_BX86_SIZE_INT, and M_BX86_SIZE_SHORT.
void M_bx86_pointer (M_Type type)
Definition at line 219 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_POINTER, M_BX86_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_bx86_return_register (int type, int purpose)
Definition at line 1070 of file ml_bx86.c.
References M_BX86_RET_F, M_BX86_RET_I32, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
int M_bx86_struct_align (int n, _M_Type * type)
Definition at line 638 of file ml_bx86.c.
References I_punt(), and M_BX86_ALIGN_CHAR.
void M_bx86_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 499 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_SIZE_CHAR, M_BX86_SIZE_INT, M_BX86_SIZE_LONG, M_BX86_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
int M_bx86_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 659 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_BX86_ALIGN_CHAR, M_BX86_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
int M_bx86_structure_pointer (int purpose)
Definition at line 1064 of file ml_bx86.c.
References M_BX86_RET_ST.
int M_bx86_subroutine_call (int opc)
Definition at line 1154 of file ml_bx86.c.
References M_assert(), M_B_486, M_B_K5, M_B_K6, M_B_K6_MMX, M_B_K6_PLUS, M_B_PENTIUM, M_B_PENTIUM_II, M_B_PENTIUM_MMX, M_B_PPRO, and M_model.
int M_bx86_union_align (int n, _M_Type * type)
Definition at line 432 of file ml_bx86.c.
References I_punt(), and M_BX86_ALIGN_CHAR.
void M_bx86_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 420 of file ml_bx86.c.
References I_punt().
int M_bx86_union_size (int n, _M_Type * type)
Definition at line 453 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_CHAR, and _struct_M_Type::size.
void M_bx86_void (M_Type type)
Definition at line 134 of file ml_bx86.c.
References _struct_M_Type::align, I_punt(), M_BX86_ALIGN_VOID, M_BX86_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
int M_conflicting_operands_bx86 (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1719 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CX, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, LBX86_MAC_ZC_FLAGS, M_assert(), MSPEC_a_flags, MSPEC_ah, MSPEC_al, MSPEC_all_fst, MSPEC_all_mm, MSPEC_ax, MSPEC_bh, MSPEC_bl, MSPEC_bp, MSPEC_bx, MSPEC_c_flags, MSPEC_ch, MSPEC_cl, MSPEC_cx, MSPEC_dh, MSPEC_di, MSPEC_dl, MSPEC_dx, MSPEC_eax, MSPEC_eaxh, MSPEC_ebp, MSPEC_ebph, MSPEC_ebx, MSPEC_ebxh, MSPEC_ecx, MSPEC_ecxh, MSPEC_edi, MSPEC_edih, MSPEC_edx, MSPEC_edxh, MSPEC_esi, MSPEC_esih, MSPEC_esp, MSPEC_esph, MSPEC_gp_reg16, MSPEC_gp_reg32, MSPEC_mm0, MSPEC_mm1, MSPEC_mm2, MSPEC_mm3, MSPEC_mm4, MSPEC_mm5, MSPEC_mm6, MSPEC_mm7, MSPEC_o_flags, MSPEC_oc_flags, MSPEC_os_flags, MSPEC_osz_flags, MSPEC_oszap_flags, MSPEC_oszapc_flags, MSPEC_oszpc_flags, MSPEC_p_flags, MSPEC_s_flags, MSPEC_si, MSPEC_sp, MSPEC_st0, MSPEC_st1, MSPEC_st2, MSPEC_st3, MSPEC_st4, MSPEC_st5, MSPEC_st6, MSPEC_st7, MSPEC_szapc_flags, MSPEC_z_flags, and MSPEC_zc_flags.
Referenced by M_dep_conflicting_operands().
void M_define_macros_bx86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1178 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CALLEE_F, LBX86_MAC_CALLEE_I, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CS, LBX86_MAC_CX, LBX86_MAC_D_FLAGS, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DS, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ES, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_FPCW, LBX86_MAC_FPSW, LBX86_MAC_FS, LBX86_MAC_GS, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_SS, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, LBX86_MAC_ZC_FLAGS, and M_add_symbol.
Referenced by M_define_macros().
void M_define_opcode_name_bx86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1431 of file ml_bx86.c.
Referenced by M_define_opcode_name().
int M_get_data_type_bx86 (L_Oper * op)
Definition at line 2396 of file ml_bx86.c.
References I_punt(), and M_assert().
Referenced by M_get_data_type().
char* M_get_macro_name_bx86 (int id)
Definition at line 1263 of file ml_bx86.c.
References LBX86_MAC_A_FLAGS, LBX86_MAC_ADDR, LBX86_MAC_AH, LBX86_MAC_AL, LBX86_MAC_ALL_FST, LBX86_MAC_ALL_GP_REG16, LBX86_MAC_ALL_GP_REG32, LBX86_MAC_ALL_MM, LBX86_MAC_AX, LBX86_MAC_BH, LBX86_MAC_BL, LBX86_MAC_BP, LBX86_MAC_BX, LBX86_MAC_C_FLAGS, LBX86_MAC_CALLEE_F, LBX86_MAC_CALLEE_I, LBX86_MAC_CH, LBX86_MAC_CL, LBX86_MAC_CS, LBX86_MAC_CX, LBX86_MAC_D_FLAGS, LBX86_MAC_DH, LBX86_MAC_DI, LBX86_MAC_DL, LBX86_MAC_DS, LBX86_MAC_DX, LBX86_MAC_EAX, LBX86_MAC_EAXH, LBX86_MAC_EBP, LBX86_MAC_EBPH, LBX86_MAC_EBX, LBX86_MAC_EBXH, LBX86_MAC_ECX, LBX86_MAC_ECXH, LBX86_MAC_EDI, LBX86_MAC_EDIH, LBX86_MAC_EDX, LBX86_MAC_EDXH, LBX86_MAC_ES, LBX86_MAC_ESI, LBX86_MAC_ESIH, LBX86_MAC_ESP, LBX86_MAC_ESPH, LBX86_MAC_FPCW, LBX86_MAC_FPSW, LBX86_MAC_FS, LBX86_MAC_GS, LBX86_MAC_MM0, LBX86_MAC_MM1, LBX86_MAC_MM2, LBX86_MAC_MM3, LBX86_MAC_MM4, LBX86_MAC_MM5, LBX86_MAC_MM6, LBX86_MAC_MM7, LBX86_MAC_O_FLAGS, LBX86_MAC_OC_FLAGS, LBX86_MAC_OS_FLAGS, LBX86_MAC_OSZ_FLAGS, LBX86_MAC_OSZAP_FLAGS, LBX86_MAC_OSZAPC_FLAGS, LBX86_MAC_OSZPC_FLAGS, LBX86_MAC_P_FLAGS, LBX86_MAC_S_FLAGS, LBX86_MAC_SI, LBX86_MAC_SP, LBX86_MAC_SS, LBX86_MAC_ST0, LBX86_MAC_ST1, LBX86_MAC_ST2, LBX86_MAC_ST3, LBX86_MAC_ST4, LBX86_MAC_ST5, LBX86_MAC_ST6, LBX86_MAC_ST7, LBX86_MAC_SZAPC_FLAGS, LBX86_MAC_Z_FLAGS, and LBX86_MAC_ZC_FLAGS.
Referenced by M_get_macro_name().
void M_get_memory_operands_bx86 (int * first, int * number, int proc_opc)
Definition at line 2379 of file ml_bx86.c.
Referenced by M_get_memory_operands().
char* M_get_opcode_name_bx86 (int id)
Definition at line 1437 of file ml_bx86.c.
Referenced by M_get_opcode_name().
int M_is_implicit_memory_op_bx86 (L_Oper * oper)
Definition at line 2496 of file ml_bx86.c.
References I_punt().
Referenced by M_is_implicit_memory_op().
int M_is_stack_operand_bx86 (L_Operand * operand)
Definition at line 1619 of file ml_bx86.c.
References LBX86_MAC_ESP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_bx86 (L_Operand * operand)
Definition at line 1631 of file ml_bx86.c.
Referenced by M_is_unsafe_macro().
int M_memory_access_size_bx86 (L_Oper * op)
Definition at line 2388 of file ml_bx86.c.
References LBX86_EXT.
Referenced by M_memory_access_size().
int M_num_oper_required_for_bx86 (L_Oper * oper, char * name)
Definition at line 1489 of file ml_bx86.c.
References indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_bx86 (int ctype)
Definition at line 2479 of file ml_bx86.c.
References I_punt().
Referenced by M_num_registers().
int M_oper_supported_in_arch_bx86 (int opc)
Definition at line 1453 of file ml_bx86.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_bx86 (L_Operand * operand)
Definition at line 1644 of file ml_bx86.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().