ml_starcore.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `m_spec.h`
#include `m_starcore.h`
Defines
#define zero_offset(a)
#define label_base(a) (L_is_label((a) $\rightarrow$ src[0]))
Functions
int M_starcore_fragile_macro (int macro_value)
Set M_starcore_fragile_macro_set (void)
int M_starcore_extra_pred_define_opcode (int proc_opc)
int M_starcore_extra_pred_define_type1 (L_Oper *oper)
int M_starcore_extra_pred_define_type2 (L_Oper *oper)
int M_starcore_subroutine_call (int opc)
int M_starcore_dataflow_macro (int id)
void M_define_macros_starcore (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_starcore (int id)
int M_oper_supported_in_arch_starcore (int opc)
int M_num_oper_required_for_starcore (L_Oper *oper, char *name)
int M_num_registers_starcore (int ctype)
int M_is_stack_operand_starcore (L_Operand *operand)
int M_is_unsafe_macro_starcore (L_Operand *operand)
int M_operand_type_starcore (L_Operand *operand)
int M_conflicting_operands_starcore (L_Operand *operand, L_Operand *conflict_array[], int len, int prepass)
int M_opc_from_proc_opc_starcore (int proc_opc)
L_Operand * M_starcore_epilogue_cntr_register ()
L_Operand * M_starcore_loop_cntr_register ()
void M_get_memory_operands_starcore (int *first, int *number, int proc_opc)
void M_define_opcode_name_starcore (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_starcore (int id)
int M_memory_access_size_starcore (L_Oper *op)
int M_get_data_type_starcore (L_Oper *op)
int M_is_implicit_memory_op_starcore (L_Oper *oper)
int M_starcore_coalescing_oper (L_Oper *oper)
void M_starcore_negate_compare (L_Oper *oper)
Variables
Set Set_starcore_fragile_macro = NULL
Define Documentation
#define label_base(a) (L_is_label((a) $\rightarrow$ src[0]))
Definition at line 619 of file ml_starcore.c.
Referenced by M_num_oper_required_for_starcore(), and M_num_oper_required_for_tahoe().
#define zero_offset(a)
Value:
((L_is_int_constant((a)->src[1])) && \
                          ((a)->src[1]->value.i == 0))
Definition at line 617 of file ml_starcore.c.
Function Documentation
int M_conflicting_operands_starcore (L_Operand * operand, L_Operand * conflict_array[], int len, int prepass)
Definition at line 860 of file ml_starcore.c.
References M_assert(), and STARCORE_MAC_SP.
Referenced by M_dep_conflicting_operands().
void M_define_macros_starcore (STRING_Symbol_Table * sym_tbl)
Definition at line 387 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_add_symbol, M_assert(), M_EM_SC_model, STARCORE_MAC_LABEL, STARCORE_MAC_LEAF, STARCORE_MAC_MEM_ALLOC, STARCORE_MAC_SP, STARCORE_MAC_SR, STARCORE_MAC_SYNC_SIZE, STARCORE_MAC_T_BIT, STARCORE_MAC_T_BIT_INV, STARCORE_MAC_TEMP, and STARCORE_MAC_TEMPLATE.
Referenced by M_define_macros().
void M_define_opcode_name_starcore (STRING_Symbol_Table * sym_tbl)
Definition at line 1203 of file ml_starcore.c.
Referenced by M_define_opcode_name().
int M_get_data_type_starcore (L_Oper * op)
Definition at line 1220 of file ml_starcore.c.
Referenced by M_get_data_type().
char* M_get_macro_name_starcore (int id)
Definition at line 414 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, STARCORE_MAC_LABEL, STARCORE_MAC_LEAF, STARCORE_MAC_MEM_ALLOC, STARCORE_MAC_SP, STARCORE_MAC_SR, STARCORE_MAC_SYNC_SIZE, STARCORE_MAC_T_BIT, STARCORE_MAC_T_BIT_INV, STARCORE_MAC_TEMP, and STARCORE_MAC_TEMPLATE.
Referenced by M_get_macro_name().
void M_get_memory_operands_starcore (int * first, int * number, int proc_opc)
Definition at line 1196 of file ml_starcore.c.
Referenced by M_get_memory_operands().
char* M_get_opcode_name_starcore (int id)
Definition at line 1208 of file ml_starcore.c.
References NULL.
Referenced by M_get_opcode_name().
int M_is_implicit_memory_op_starcore (L_Oper * oper)
Definition at line 1226 of file ml_starcore.c.
Referenced by M_is_implicit_memory_op().
int M_is_stack_operand_starcore (L_Operand * operand)
Definition at line 761 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, and STARCORE_MAC_SP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_starcore (L_Operand * operand)
Definition at line 786 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_is_unsafe_macro().
int M_memory_access_size_starcore (L_Oper * op)
Definition at line 1214 of file ml_starcore.c.
Referenced by M_memory_access_size().
int M_num_oper_required_for_starcore (L_Oper * oper, char * name)
Definition at line 622 of file ml_starcore.c.
References EM_SC_MODEL_OK, label_base, M_assert(), M_EM_SC_model, and zero_offset.
Referenced by M_num_oper_required_for().
int M_num_registers_starcore (int ctype)
Definition at line 747 of file ml_starcore.c.
Referenced by M_num_registers().
int M_opc_from_proc_opc_starcore (int proc_opc)
Definition at line 926 of file ml_starcore.c.
References M_assert(), STARCOREop_ABS, STARCOREop_ADC, STARCOREop_ADD, STARCOREop_ADD2, STARCOREop_ADDA_1, STARCOREop_ADDA_2, STARCOREop_ADDL1A, STARCOREop_ADDL2A, STARCOREop_ADDNC_W, STARCOREop_ADR, STARCOREop_AND_1, STARCOREop_AND_2, STARCOREop_ASL, STARCOREop_ASL2A, STARCOREop_ASLA, STARCOREop_ASLL, STARCOREop_ASLW, STARCOREop_ASR, STARCOREop_ASRA, STARCOREop_ASRR, STARCOREop_ASRW, STARCOREop_BF_1, STARCOREop_BF_2, STARCOREop_BFD_1, STARCOREop_BFD_2, STARCOREop_BRA_1, STARCOREop_BRA_2, STARCOREop_BRAD_1, STARCOREop_BRAD_2, STARCOREop_BSR_1, STARCOREop_BSR_2, STARCOREop_BSRD_1, STARCOREop_BSRD_2, STARCOREop_BT_1, STARCOREop_BT_2, STARCOREop_BTD_1, STARCOREop_BTD_2, STARCOREop_CMPEQ, STARCOREop_CMPEQA, STARCOREop_CMPGT, STARCOREop_CMPGTA, STARCOREop_CMPHI, STARCOREop_CMPHIA, STARCOREop_EOR_1, STARCOREop_EOR_2, STARCOREop_EXTRACT, STARCOREop_EXTRACTU, STARCOREop_IADD, STARCOREop_IMAC, STARCOREop_IMACLHUU, STARCOREop_IMACUS, STARCOREop_IMPY, STARCOREop_IMPY_W, STARCOREop_IMPYHLUU, STARCOREop_IMPYSU, STARCOREop_IMPYUU, STARCOREop_INSERT, STARCOREop_JF_1, STARCOREop_JF_3, STARCOREop_JFD_1, STARCOREop_JFD_3, STARCOREop_JMP_1, STARCOREop_JMP_3, STARCOREop_JMPD_1, STARCOREop_JMPD_3, STARCOREop_JSR_1, STARCOREop_JSR_3, STARCOREop_JSRD_1, STARCOREop_JSRD_3, STARCOREop_JT_1, STARCOREop_JT_3, STARCOREop_JTD_1, STARCOREop_JTD_3, STARCOREop_LSLL, STARCOREop_LSR, STARCOREop_LSRA, STARCOREop_LSRR, STARCOREop_LSRW, STARCOREop_MAC_1, STARCOREop_MAC_2, STARCOREop_MACR, STARCOREop_MACSU, STARCOREop_MACUS, STARCOREop_MACUU, STARCOREop_MAX, STARCOREop_MAX2, STARCOREop_MAX2VIT, STARCOREop_MAXM, STARCOREop_MIN, STARCOREop_MOVE_2F_LD, STARCOREop_MOVE_2L_LD, STARCOREop_MOVE_2L_ST, STARCOREop_MOVE_2W_LD, STARCOREop_MOVE_2W_ST, STARCOREop_MOVE_4F_LD, STARCOREop_MOVE_4W_LD, STARCOREop_MOVE_4W_ST, STARCOREop_MOVE_B_LD_1, STARCOREop_MOVE_B_LD_2, STARCOREop_MOVE_B_ST_1, STARCOREop_MOVE_B_ST_2, STARCOREop_MOVE_B_ST_3, STARCOREop_MOVE_F_LD_1, STARCOREop_MOVE_F_LD_2, STARCOREop_MOVE_F_LD_3, STARCOREop_MOVE_F_MV_2, STARCOREop_MOVE_F_ST_1, STARCOREop_MOVE_L_LD_1, STARCOREop_MOVE_L_LD_2, STARCOREop_MOVE_L_LD_3, STARCOREop_MOVE_L_MV_1, STARCOREop_MOVE_L_MV_3, STARCOREop_MOVE_L_ST_1, STARCOREop_MOVE_L_ST_2, STARCOREop_MOVE_L_ST_3, STARCOREop_MOVE_W_LD_1, STARCOREop_MOVE_W_LD_2, STARCOREop_MOVE_W_LD_3, STARCOREop_MOVE_W_MV_1, STARCOREop_MOVE_W_MV_2, STARCOREop_MOVE_W_ST_1, STARCOREop_MOVE_W_ST_2, STARCOREop_MOVE_W_ST_3, STARCOREop_MOVEF, STARCOREop_MOVES_2F_ST, STARCOREop_MOVES_4F_ST, STARCOREop_MOVES_F_ST_1, STARCOREop_MOVES_F_ST_2, STARCOREop_MOVES_F_ST_3, STARCOREop_MOVES_L_ST, STARCOREop_MOVET, STARCOREop_MOVEU_B_LD_1, STARCOREop_MOVEU_B_LD_2, STARCOREop_MOVEU_B_LD_3, STARCOREop_MOVEU_L_MV, STARCOREop_MOVEU_W_LD_1, STARCOREop_MOVEU_W_LD_2, STARCOREop_MOVEU_W_LD_3, STARCOREop_MOVEU_W_MV, STARCOREop_MPY, STARCOREop_MPYR, STARCOREop_MPYSU, STARCOREop_MPYUS, STARCOREop_MPYUU, STARCOREop_NOP, STARCOREop_OR_1, STARCOREop_OR_2, STARCOREop_RTS, STARCOREop_RTSD, STARCOREop_RTSTK, STARCOREop_RTSTKD, STARCOREop_SAT_F, STARCOREop_SAT_L, STARCOREop_SBC, STARCOREop_SBR, STARCOREop_SUB, STARCOREop_SUB2, STARCOREop_SUBA, STARCOREop_SUBNC_W, STARCOREop_SXT_B, STARCOREop_SXT_L, STARCOREop_SXT_W, STARCOREop_SXTA_B, STARCOREop_SXTA_W, STARCOREop_TFR, STARCOREop_TFRA, STARCOREop_TFRF, STARCOREop_TFRT, STARCOREop_TSTEQ, STARCOREop_TSTEQA_L, STARCOREop_TSTEQA_W, STARCOREop_TSTGE, STARCOREop_TSTGEA, STARCOREop_TSTGT, STARCOREop_TSTGTA, STARCOREop_ZXT_B, STARCOREop_ZXT_L, STARCOREop_ZXT_W, STARCOREop_ZXTA_B, and STARCOREop_ZXTA_W.
Referenced by M_opc_from_proc_opc().
int M_oper_supported_in_arch_starcore (int opc)
Definition at line 459 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_oper_supported_in_arch().
int M_operand_type_starcore (L_Operand * operand)
Definition at line 811 of file ml_starcore.c.
References M_assert(), MDES_OPERAND_addr, MDES_OPERAND_cntl, MDES_OPERAND_f, MDES_OPERAND_i, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_p, and NULL.
Referenced by M_mdes_operand_type().
int M_starcore_coalescing_oper (L_Oper * oper)
Definition at line 1235 of file ml_starcore.c.
Referenced by M_coalescing_oper().
int M_starcore_dataflow_macro (int id)
Definition at line 361 of file ml_starcore.c.
References EM_SC_MODEL_OK, FALSE, M_assert(), M_EM_SC_model, STARCORE_MAC_LABEL, STARCORE_MAC_TEMPLATE, and TRUE.
Referenced by M_dataflow_macro().
L_Operand* M_starcore_epilogue_cntr_register ()
Definition at line 1178 of file ml_starcore.c.
References NULL.
Referenced by M_return_epilogue_cntr_register().
int M_starcore_extra_pred_define_opcode (int proc_opc)
Definition at line 216 of file ml_starcore.c.
References STARCOREop_BMTSTC, STARCOREop_BMTSTC_W_2, STARCOREop_BMTSTC_W_3, STARCOREop_BMTSTS, STARCOREop_BMTSTS_W_2, STARCOREop_BMTSTS_W_3, STARCOREop_CMPEQ, STARCOREop_CMPEQA, STARCOREop_CMPGT, STARCOREop_CMPGTA, STARCOREop_CMPHI, STARCOREop_CMPHIA, STARCOREop_DECEQ, STARCOREop_DECEQA, STARCOREop_DECGE, STARCOREop_DECGEA, STARCOREop_TSTEQ, STARCOREop_TSTEQA_L, STARCOREop_TSTEQA_W, STARCOREop_TSTGE, STARCOREop_TSTGEA, STARCOREop_TSTGT, and STARCOREop_TSTGTA.
Referenced by M_extra_pred_define_opcode().
int M_starcore_extra_pred_define_type1 (L_Oper * oper)
Definition at line 255 of file ml_starcore.c.
References STARCOREop_BMTSTC, STARCOREop_BMTSTC_W_2, STARCOREop_BMTSTC_W_3, STARCOREop_BMTSTS, STARCOREop_BMTSTS_W_2, STARCOREop_BMTSTS_W_3, STARCOREop_CMPEQ, STARCOREop_CMPEQA, STARCOREop_CMPGT, STARCOREop_CMPGTA, STARCOREop_CMPHI, STARCOREop_CMPHIA, STARCOREop_TSTEQ, STARCOREop_TSTEQA_L, STARCOREop_TSTEQA_W, STARCOREop_TSTGE, STARCOREop_TSTGEA, STARCOREop_TSTGT, and STARCOREop_TSTGTA.
int M_starcore_extra_pred_define_type2 (L_Oper * oper)
Definition at line 292 of file ml_starcore.c.
References STARCOREop_DECEQ, STARCOREop_DECEQA, STARCOREop_DECGE, and STARCOREop_DECGEA.
int M_starcore_fragile_macro (int macro_value)
Definition at line 80 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), M_EM_SC_model, STARCORE_MAC_SR, STARCORE_MAC_T_BIT, and STARCORE_MAC_T_BIT_INV.
Referenced by M_fragile_macro().
Set M_starcore_fragile_macro_set (void)
Definition at line 148 of file ml_starcore.c.
References Set_add(), Set_starcore_fragile_macro, STARCORE_MAC_SR, STARCORE_MAC_T_BIT, and STARCORE_MAC_T_BIT_INV.
Referenced by M_fragile_macro_set().
L_Operand* M_starcore_loop_cntr_register ()
Definition at line 1186 of file ml_starcore.c.
References I_punt(), and NULL.
Referenced by M_return_loop_cntr_register().
void M_starcore_negate_compare (L_Oper * oper)
Definition at line 1280 of file ml_starcore.c.
References STARCORE_MAC_T_BIT, STARCORE_MAC_T_BIT_INV, STARCOREop_JF_3, and STARCOREop_JT_3.
int M_starcore_subroutine_call (int opc)
Definition at line 313 of file ml_starcore.c.
References EM_SC_MODEL_OK, M_assert(), and M_EM_SC_model.
Referenced by M_subroutine_call().
Variable Documentation
Set Set_starcore_fragile_macro = NULL
Definition at line 70 of file ml_starcore.c.
Referenced by M_starcore_fragile_macro_set().