ml_x86.c File Reference
#include <config.h>
#include <library/i_error.h>
#include <Lcode/l_main.h>
#include `m_spec.h`
#include `m_x86.h`
Defines
#define M_X86_SIZE_VOID 0
#define M_X86_SIZE_BIT 1
#define M_X86_SIZE_CHAR 8
#define M_X86_SIZE_SHORT 16
#define M_X86_SIZE_INT 32
#define M_X86_SIZE_LONG 32
#define M_X86_SIZE_FLOAT 32
#define M_X86_SIZE_DOUBLE 64
#define M_X86_SIZE_POINTER 32
#define M_X86_SIZE_UNION -1
#define M_X86_SIZE_STRUCT -1
#define M_X86_SIZE_BLOCK -1
#define M_X86_SIZE_MAX 64
#define M_X86_ALIGN_VOID -1
#define M_X86_ALIGN_BIT 1
#define M_X86_ALIGN_CHAR 8
#define M_X86_ALIGN_SHORT 16
#define M_X86_ALIGN_INT 32
#define M_X86_ALIGN_LONG 32
#define M_X86_ALIGN_FLOAT 32
#define M_X86_ALIGN_DOUBLE 32
#define M_X86_ALIGN_POINTER 32
#define M_X86_ALIGN_UNION -1
#define M_X86_ALIGN_STRUCT -1
#define M_X86_ALIGN_BLOCK -1
#define M_X86_ALIGN_MAX 64
#define M_X86_MAX_FNVAR_REG 0
#define M_X86_SMALL_STRUCT_MAX 04
#define MIN_PARAM_SIZE (16 * 0)
#define M_X86_INT_BASE 0
#define M_X86_FLT_BASE 4
#define M_X86_RET_I32 0
#define M_X86_RET_I64 0
#define M_X86_RET_ST 0
#define M_X86_RET_F 1
#define M_X86_RET_F2 1
#define M_X86_VAR_PTR `$LV`
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_x86_void (M_Type type)
void M_x86_bit_long (M_Type type, int n)
void M_x86_bit_int (M_Type type, int n)
void M_x86_bit_short (M_Type type, int n)
void M_x86_bit_char (M_Type type, int n)
void M_x86_float (M_Type type, int unsign)
void M_x86_double (M_Type type, int unsign)
void M_x86_pointer (M_Type type)
int M_x86_eval_type (M_Type type, M_Type ntype)
int M_x86_eval_type2 (M_Type type, M_Type ntype)
int M_x86_call_type (M_Type type, M_Type ntype)
int M_x86_call_type2 (M_Type type, M_Type ntype)
void M_x86_array_layout (M_Type type, int *offset)
int M_x86_array_align (M_Type type)
int M_x86_array_size (M_Type type, int dim)
void M_x86_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_x86_union_align (int n, _M_Type *type)
int M_x86_union_size (int n, _M_Type *type)
void M_x86_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_x86_struct_align (int n, _M_Type *type)
int M_x86_struct_size (int n, _M_Type *type, int struct_align)
int M_x86_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_x86_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_x86_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_x86_no_short_int (void)
void M_x86_cb_label_name (char *fn, int cb, char *line, int len)
int M_x86_is_cb_label (char *label, char *fn, int *cb)
void M_x86_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_x86_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_x86_structure_pointer (int purpose)
int M_x86_return_register (int type, int purpose)
char * M_x86_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_x86_fn_name_from_label (char *label)
int M_x86_fragile_macro (int macro_value)
int M_x86_subroutine_call (int opc)
void M_define_macros_x86 (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_x86 (int id)
void M_define_opcode_name_x86 (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_x86 (int id)
int M_oper_supported_in_arch_x86 (int opc)
int M_num_oper_required_for_x86 (L_Oper *oper, char *name)
int M_is_stack_operand_x86 (L_Operand *operand)
int M_is_unsafe_macro_x86 (L_Operand *operand)
int M_operand_type_x86 (L_Operand *operand)
int M_conflicting_operands_x86 (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
void M_get_memory_operands_x86 (int *first, int *number, int proc_opc)
int M_memory_access_size_x86 (L_Oper *op)
int M_get_data_type_x86 (L_Oper *op)
int M_num_registers_x86 (int ctype)
int M_is_implicit_memory_op_x86 (L_Oper *oper)
Variables
static int have_reversed = 0
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define long_neg_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_X86_ALIGN_BIT 1
Definition at line 94 of file ml_x86.c.
#define M_X86_ALIGN_BLOCK -1
Definition at line 104 of file ml_x86.c.
#define M_X86_ALIGN_CHAR 8
Definition at line 95 of file ml_x86.c.
#define M_X86_ALIGN_DOUBLE 32
Definition at line 100 of file ml_x86.c.
#define M_X86_ALIGN_FLOAT 32
Definition at line 99 of file ml_x86.c.
#define M_X86_ALIGN_INT 32
Definition at line 97 of file ml_x86.c.
#define M_X86_ALIGN_LONG 32
Definition at line 98 of file ml_x86.c.
#define M_X86_ALIGN_MAX 64
Definition at line 105 of file ml_x86.c.
#define M_X86_ALIGN_POINTER 32
Definition at line 101 of file ml_x86.c.
#define M_X86_ALIGN_SHORT 16
Definition at line 96 of file ml_x86.c.
#define M_X86_ALIGN_STRUCT -1
Definition at line 103 of file ml_x86.c.
#define M_X86_ALIGN_UNION -1
Definition at line 102 of file ml_x86.c.
#define M_X86_ALIGN_VOID -1
Definition at line 93 of file ml_x86.c.
#define M_X86_FLT_BASE 4
Definition at line 115 of file ml_x86.c.
Referenced by M_x86_fnvar_layout().
#define M_X86_INT_BASE 0
Definition at line 114 of file ml_x86.c.
Referenced by M_x86_fnvar_layout().
#define M_X86_MAX_FNVAR_REG 0
Definition at line 109 of file ml_x86.c.
Referenced by M_x86_fnvar_layout().
#define M_X86_RET_F 1
Definition at line 120 of file ml_x86.c.
Referenced by M_x86_return_register().
#define M_X86_RET_F2 1
Definition at line 121 of file ml_x86.c.
#define M_X86_RET_I32 0
Definition at line 117 of file ml_x86.c.
Referenced by M_x86_return_register().
#define M_X86_RET_I64 0
Definition at line 118 of file ml_x86.c.
#define M_X86_RET_ST 0
Definition at line 119 of file ml_x86.c.
Referenced by M_x86_structure_pointer().
#define M_X86_SIZE_BIT 1
Definition at line 80 of file ml_x86.c.
#define M_X86_SIZE_BLOCK -1
Definition at line 90 of file ml_x86.c.
#define M_X86_SIZE_CHAR 8
Definition at line 81 of file ml_x86.c.
#define M_X86_SIZE_DOUBLE 64
Definition at line 86 of file ml_x86.c.
#define M_X86_SIZE_FLOAT 32
Definition at line 85 of file ml_x86.c.
#define M_X86_SIZE_INT 32
Definition at line 83 of file ml_x86.c.
#define M_X86_SIZE_LONG 32
Definition at line 84 of file ml_x86.c.
#define M_X86_SIZE_MAX 64
Definition at line 91 of file ml_x86.c.
#define M_X86_SIZE_POINTER 32
Definition at line 87 of file ml_x86.c.
#define M_X86_SIZE_SHORT 16
Definition at line 82 of file ml_x86.c.
#define M_X86_SIZE_STRUCT -1
Definition at line 89 of file ml_x86.c.
#define M_X86_SIZE_UNION -1
Definition at line 88 of file ml_x86.c.
#define M_X86_SIZE_VOID 0
Definition at line 79 of file ml_x86.c.
#define M_X86_SMALL_STRUCT_MAX 04
Definition at line 110 of file ml_x86.c.
Referenced by M_x86_fnvar_layout().
#define M_X86_VAR_PTR `$LV`
Definition at line 122 of file ml_x86.c.
Referenced by M_x86_lvar_layout().
#define MIN_PARAM_SIZE (16 * 0)
Definition at line 111 of file ml_x86.c.
#define non_zero_offset(a)
Value:
(!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) ||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
(((a->src[1]->type==L_OPERAND_IMMED)&&\
                                  ((a->src[1]->ctype&0x30)==0x00)) &&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_conflicting_operands_x86 (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 1756 of file ml_x86.c.
Referenced by M_dep_conflicting_operands().
void M_define_macros_x86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1193 of file ml_x86.c.
References LX86_MAC_ALLOC, LX86_MAC_CALLEE_F, LX86_MAC_CALLEE_I, LX86_MAC_EAX, LX86_MAC_EBP, LX86_MAC_EBX, LX86_MAC_ECX, LX86_MAC_EDI, LX86_MAC_EDX, LX86_MAC_ESI, LX86_MAC_ESP, LX86_MAC_FLAGS, LX86_MAC_FPSTACK, LX86_MAC_FZERO, LX86_MAC_LEAF, LX86_MAC_ST0, LX86_MAC_ST1, LX86_MAC_ST2, LX86_MAC_ST3, LX86_MAC_ST4, LX86_MAC_ST5, LX86_MAC_ST6, LX86_MAC_ST7, LX86_MAC_STACK, and M_add_symbol.
Referenced by M_define_macros().
void M_define_opcode_name_x86 (STRING_Symbol_Table * sym_tbl)
Definition at line 1283 of file ml_x86.c.
References LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CDQ, LX86op_CISC_BRANCH, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DEC, LX86op_DIV_F, LX86op_DIV_F2, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F, LX86op_DIVR_F2, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_FLD1, LX86op_FLD_ST, LX86op_FLDCW, LX86op_FLDZ, LX86op_FLOAT_LOAD, LX86op_FLOAT_STORE, LX86op_FP2INT_BRANCH, LX86op_FPOP_I, LX86op_FPUSH_I, LX86op_FSTCW, LX86op_FSTP, LX86op_FSTSW, LX86op_FXCH, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_INC, LX86op_INT_LOAD, LX86op_INT_STORE, LX86op_INT_SUB_WITH_BORROW, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LEA, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MOVS, LX86op_MOVXL, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_NEGATE, LX86op_POP, LX86op_PUSH, LX86op_SAHF, LX86op_SUB_F, LX86op_SUB_F2, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F, LX86op_SUBR_F2, LX86op_SUBR_F2MEM, LX86op_SUBR_FMEM, LX86op_TEST, LX86op_TRACE_JSR, M_add_symbol, X86opcode_ADD_F2MEM, X86opcode_ADD_FMEM, X86opcode_CDQ, X86opcode_CISC_BRANCH, X86opcode_CISC_TO_MEM, X86opcode_CISC_TO_MEM_DEC, X86opcode_CISC_TO_MEM_INC, X86opcode_CISC_TO_MEM_NEGATE, X86opcode_CISC_TO_REG, X86opcode_CISC_TO_REG_CMP, X86opcode_CISC_TO_REG_TEST, X86opcode_DEC, X86opcode_DIV_F, X86opcode_DIV_F2, X86opcode_DIV_F2MEM, X86opcode_DIV_FMEM, X86opcode_DIVR_F, X86opcode_DIVR_F2, X86opcode_DIVR_F2MEM, X86opcode_DIVR_FMEM, X86opcode_EQ_F2MEM, X86opcode_EQ_FMEM, X86opcode_FLD1, X86opcode_FLD_ST, X86opcode_FLDCW, X86opcode_FLDZ, X86opcode_FLOAT_LOAD, X86opcode_FLOAT_STORE, X86opcode_FP2INT_BRANCH, X86opcode_FPOP_I, X86opcode_FPUSH_I, X86opcode_FSTCW, X86opcode_FSTP, X86opcode_FSTSW, X86opcode_FXCH, X86opcode_GE_F2MEM, X86opcode_GE_FMEM, X86opcode_GT_F2MEM, X86opcode_GT_FMEM, X86opcode_INC, X86opcode_INT_LOAD, X86opcode_INT_STORE, X86opcode_INT_SUB_WITH_BORROW, X86opcode_LE_F2MEM, X86opcode_LE_FMEM, X86opcode_LEA, X86opcode_LT_F2MEM, X86opcode_LT_FMEM, X86opcode_MOVS, X86opcode_MOVXL, X86opcode_MUL_F2MEM, X86opcode_MUL_FMEM, X86opcode_NE_F2MEM, X86opcode_NE_FMEM, X86opcode_NEGATE, X86opcode_POP, X86opcode_PUSH, X86opcode_SAHF, X86opcode_SUB_F, X86opcode_SUB_F2, X86opcode_SUB_F2MEM, X86opcode_SUB_FMEM, X86opcode_SUBR_F, X86opcode_SUBR_F2, X86opcode_SUBR_F2MEM, X86opcode_SUBR_FMEM, X86opcode_TEST, and X86opcode_TRACE_JSR.
Referenced by M_define_opcode_name().
int M_get_data_type_x86 (L_Oper * op)
Definition at line 1970 of file ml_x86.c.
References I_punt(), LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CISC_BRANCH, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_FLDCW, LX86op_FLOAT_LOAD, LX86op_FLOAT_STORE, LX86op_FPOP_I, LX86op_FPUSH_I, LX86op_FSTCW, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_INT_LOAD, LX86op_INT_STORE, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MOVXL, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_PUSH, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F2MEM, LX86op_SUBR_FMEM, and M_assert().
Referenced by M_get_data_type().
char* M_get_macro_name_x86 (int id)
Definition at line 1225 of file ml_x86.c.
References LX86_MAC_ALLOC, LX86_MAC_CALLEE_F, LX86_MAC_CALLEE_I, LX86_MAC_EAX, LX86_MAC_EBP, LX86_MAC_EBX, LX86_MAC_ECX, LX86_MAC_EDI, LX86_MAC_EDX, LX86_MAC_ESI, LX86_MAC_ESP, LX86_MAC_FLAGS, LX86_MAC_FPSTACK, LX86_MAC_LEAF, LX86_MAC_ST0, LX86_MAC_ST1, LX86_MAC_ST2, LX86_MAC_ST3, LX86_MAC_ST4, LX86_MAC_ST5, LX86_MAC_ST6, LX86_MAC_ST7, and LX86_MAC_STACK.
Referenced by M_get_macro_name().
void M_get_memory_operands_x86 (int * first, int * number, int proc_opc)
Definition at line 1796 of file ml_x86.c.
References LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CISC_BRANCH, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_FLDCW, LX86op_FLOAT_LOAD, LX86op_FLOAT_STORE, LX86op_FPOP_I, LX86op_FPUSH_I, LX86op_FSTCW, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_INT_LOAD, LX86op_INT_STORE, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MOVXL, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_POP, LX86op_PUSH, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F2MEM, and LX86op_SUBR_FMEM.
Referenced by M_get_memory_operands().
char* M_get_opcode_name_x86 (int id)
Definition at line 1358 of file ml_x86.c.
References LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CDQ, LX86op_CISC_BRANCH, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DEC, LX86op_DIV_F, LX86op_DIV_F2, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F, LX86op_DIVR_F2, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_FLD1, LX86op_FLD_ST, LX86op_FLDCW, LX86op_FLDZ, LX86op_FLOAT_LOAD, LX86op_FLOAT_STORE, LX86op_FP2INT_BRANCH, LX86op_FPOP_I, LX86op_FPUSH_I, LX86op_FSTCW, LX86op_FSTP, LX86op_FSTSW, LX86op_FXCH, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_INC, LX86op_INT_LOAD, LX86op_INT_STORE, LX86op_INT_SUB_WITH_BORROW, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LEA, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MOVS, LX86op_MOVXL, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_NEGATE, LX86op_POP, LX86op_PUSH, LX86op_SAHF, LX86op_SUB_F, LX86op_SUB_F2, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F, LX86op_SUBR_F2, LX86op_SUBR_F2MEM, LX86op_SUBR_FMEM, LX86op_TEST, LX86op_TRACE_JSR, X86opcode_ADD_F2MEM, X86opcode_ADD_FMEM, X86opcode_CDQ, X86opcode_CISC_BRANCH, X86opcode_CISC_TO_MEM, X86opcode_CISC_TO_MEM_DEC, X86opcode_CISC_TO_MEM_INC, X86opcode_CISC_TO_MEM_NEGATE, X86opcode_CISC_TO_REG, X86opcode_CISC_TO_REG_CMP, X86opcode_CISC_TO_REG_TEST, X86opcode_DEC, X86opcode_DIV_F, X86opcode_DIV_F2, X86opcode_DIV_F2MEM, X86opcode_DIV_FMEM, X86opcode_DIVR_F, X86opcode_DIVR_F2, X86opcode_DIVR_F2MEM, X86opcode_DIVR_FMEM, X86opcode_EQ_F2MEM, X86opcode_EQ_FMEM, X86opcode_FLD1, X86opcode_FLD_ST, X86opcode_FLDCW, X86opcode_FLDZ, X86opcode_FLOAT_LOAD, X86opcode_FLOAT_STORE, X86opcode_FP2INT_BRANCH, X86opcode_FPOP_I, X86opcode_FPUSH_I, X86opcode_FSTCW, X86opcode_FSTP, X86opcode_FSTSW, X86opcode_FXCH, X86opcode_GE_F2MEM, X86opcode_GE_FMEM, X86opcode_GT_F2MEM, X86opcode_GT_FMEM, X86opcode_INC, X86opcode_INT_LOAD, X86opcode_INT_STORE, X86opcode_INT_SUB_WITH_BORROW, X86opcode_LE_F2MEM, X86opcode_LE_FMEM, X86opcode_LEA, X86opcode_LT_F2MEM, X86opcode_LT_FMEM, X86opcode_MOVS, X86opcode_MOVXL, X86opcode_MUL_F2MEM, X86opcode_MUL_FMEM, X86opcode_NE_F2MEM, X86opcode_NE_FMEM, X86opcode_NEGATE, X86opcode_POP, X86opcode_PUSH, X86opcode_SAHF, X86opcode_SUB_F, X86opcode_SUB_F2, X86opcode_SUB_F2MEM, X86opcode_SUB_FMEM, X86opcode_SUBR_F, X86opcode_SUBR_F2, X86opcode_SUBR_F2MEM, X86opcode_SUBR_FMEM, X86opcode_TEST, and X86opcode_TRACE_JSR.
Referenced by M_get_opcode_name().
int M_is_implicit_memory_op_x86 (L_Oper * oper)
Definition at line 2061 of file ml_x86.c.
References LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_POP, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F2MEM, and LX86op_SUBR_FMEM.
Referenced by M_is_implicit_memory_op().
int M_is_stack_operand_x86 (L_Operand * operand)
Definition at line 1678 of file ml_x86.c.
References LX86_MAC_ESP.
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_x86 (L_Operand * operand)
Definition at line 1690 of file ml_x86.c.
Referenced by M_is_unsafe_macro().
int M_memory_access_size_x86 (L_Oper * op)
Definition at line 1877 of file ml_x86.c.
References I_punt(), LX86op_ADD_F2MEM, LX86op_ADD_FMEM, LX86op_CISC_BRANCH, LX86op_CISC_TO_MEM, LX86op_CISC_TO_MEM_DEC, LX86op_CISC_TO_MEM_INC, LX86op_CISC_TO_MEM_NEGATE, LX86op_CISC_TO_REG, LX86op_CISC_TO_REG_CMP, LX86op_CISC_TO_REG_TEST, LX86op_DIV_F2MEM, LX86op_DIV_FMEM, LX86op_DIVR_F2MEM, LX86op_DIVR_FMEM, LX86op_EQ_F2MEM, LX86op_EQ_FMEM, LX86op_FLDCW, LX86op_FLOAT_LOAD, LX86op_FLOAT_STORE, LX86op_FPOP_I, LX86op_FPUSH_I, LX86op_FSTCW, LX86op_GE_F2MEM, LX86op_GE_FMEM, LX86op_GT_F2MEM, LX86op_GT_FMEM, LX86op_INT_LOAD, LX86op_INT_STORE, LX86op_LE_F2MEM, LX86op_LE_FMEM, LX86op_LT_F2MEM, LX86op_LT_FMEM, LX86op_MOVXL, LX86op_MUL_F2MEM, LX86op_MUL_FMEM, LX86op_NE_F2MEM, LX86op_NE_FMEM, LX86op_PUSH, LX86op_SUB_F2MEM, LX86op_SUB_FMEM, LX86op_SUBR_F2MEM, LX86op_SUBR_FMEM, M_assert(), M_SIZE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_SHORT, and M_type_size().
Referenced by M_memory_access_size().
int M_num_oper_required_for_x86 (L_Oper * oper, char * name)
Definition at line 1548 of file ml_x86.c.
References indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_x86 (int ctype)
Definition at line 2046 of file ml_x86.c.
Referenced by M_num_registers().
int M_oper_supported_in_arch_x86 (int opc)
Definition at line 1511 of file ml_x86.c.
Referenced by M_oper_supported_in_arch().
int M_operand_type_x86 (L_Operand * operand)
Definition at line 1703 of file ml_x86.c.
References LX86_MAC_FLAGS, LX86_MAC_FPSTACK, LX86_MAC_STACK, M_assert(), MDES_OPERAND_flag, MDES_OPERAND_fstk, MDES_OPERAND_istk, MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
int M_x86_array_align (M_Type type)
Definition at line 380 of file ml_x86.c.
References _struct_M_Type::align.
Referenced by M_array_align().
void M_x86_array_layout (M_Type type, int * offset)
Definition at line 374 of file ml_x86.c.
Referenced by M_array_layout().
int M_x86_array_size (M_Type type, int dim)
Definition at line 386 of file ml_x86.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size().
void M_x86_bit_char (M_Type type, int n)
Definition at line 176 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_X86_ALIGN_BIT, M_X86_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_x86_bit_int (M_Type type, int n)
Definition at line 152 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_INT, M_X86_ALIGN_BIT, M_X86_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_x86_bit_long (M_Type type, int n)
Definition at line 140 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_LONG, M_X86_ALIGN_BIT, M_X86_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_x86_bit_short (M_Type type, int n)
Definition at line 164 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_SHORT, M_X86_ALIGN_BIT, M_X86_SIZE_BIT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_x86_call_type (M_Type type, M_Type ntype)
Definition at line 295 of file ml_x86.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_x86_call_type2 (M_Type type, M_Type ntype)
Definition at line 330 of file ml_x86.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_x86_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1043 of file ml_x86.c.
Referenced by M_cb_label_name().
void M_x86_double (M_Type type, int unsign)
Definition at line 198 of file ml_x86.c.
References _struct_M_Type::align, M_TYPE_DOUBLE, M_X86_ALIGN_DOUBLE, M_X86_SIZE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double().
int M_x86_eval_type (M_Type type, M_Type ntype)
Definition at line 219 of file ml_x86.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_x86_eval_type2 (M_Type type, M_Type ntype)
Definition at line 253 of file ml_x86.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_x86_float (M_Type type, int unsign)
Definition at line 188 of file ml_x86.c.
References _struct_M_Type::align, M_TYPE_FLOAT, M_X86_ALIGN_FLOAT, M_X86_SIZE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float().
char* M_x86_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1117 of file ml_x86.c.
Referenced by M_fn_label_name().
char* M_x86_fn_name_from_label (char * label)
Definition at line 1132 of file ml_x86.c.
Referenced by M_fn_name_from_label().
int M_x86_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 756 of file ml_x86.c.
References _struct_M_Type::align, have_reversed, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_X86_ALIGN_INT, M_X86_ALIGN_MAX, M_X86_FLT_BASE, M_X86_INT_BASE, M_X86_MAX_FNVAR_REG, M_X86_SIZE_INT, M_X86_SMALL_STRUCT_MAX, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout(), and M_x86_layout_fnvar().
int M_x86_fragile_macro (int macro_value)
Definition at line 1144 of file ml_x86.c.
References M_386, M_486, M_assert(), M_KRYPTON, M_model, and M_PENTIUM.
Referenced by M_fragile_macro().
int M_x86_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1049 of file ml_x86.c.
Referenced by M_is_cb_label().
int M_x86_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1062 of file ml_x86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_is_jumptbl_label().
void M_x86_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1055 of file ml_x86.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_jumptbl_label_name().
int M_x86_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 698 of file ml_x86.c.
References List_next(), List_size(), List_start(), M_x86_fnvar_layout(), _struct_M_Param::mode, mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_layout_fnvar().
int M_x86_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 995 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_X86_ALIGN_MAX, M_X86_VAR_PTR, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_x86_no_short_int (void)
Definition at line 1037 of file ml_x86.c.
References M_X86_SIZE_INT, and M_X86_SIZE_SHORT.
Referenced by M_no_short_int().
void M_x86_pointer (M_Type type)
Definition at line 208 of file ml_x86.c.
References _struct_M_Type::align, M_TYPE_POINTER, M_X86_ALIGN_POINTER, M_X86_SIZE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_pointer().
int M_x86_return_register (int type, int purpose)
Definition at line 1096 of file ml_x86.c.
References M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_X86_RET_F, and M_X86_RET_I32.
Referenced by M_return_register().
int M_x86_struct_align (int n, _M_Type * type)
Definition at line 614 of file ml_x86.c.
References M_X86_ALIGN_CHAR.
Referenced by M_struct_align().
void M_x86_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 477 of file ml_x86.c.
References _struct_M_Type::align, I_punt(), M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_X86_SIZE_CHAR, M_X86_SIZE_INT, M_X86_SIZE_LONG, M_X86_SIZE_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_x86_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 634 of file ml_x86.c.
References _struct_M_Type::align, M_assert(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, M_X86_ALIGN_CHAR, and M_X86_SIZE_INT.
Referenced by M_struct_size().
int M_x86_structure_pointer (int purpose)
Definition at line 1090 of file ml_x86.c.
References M_X86_RET_ST.
Referenced by M_structure_pointer().
int M_x86_subroutine_call (int opc)
Definition at line 1174 of file ml_x86.c.
References M_386, M_486, M_assert(), M_KRYPTON, M_model, and M_PENTIUM.
Referenced by M_subroutine_call().
int M_x86_union_align (int n, _M_Type * type)
Definition at line 412 of file ml_x86.c.
References M_X86_ALIGN_CHAR.
Referenced by M_union_align().
void M_x86_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 401 of file ml_x86.c.
Referenced by M_union_layout().
int M_x86_union_size (int n, _M_Type * type)
Definition at line 432 of file ml_x86.c.
References _struct_M_Type::align, M_X86_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_union_size().
void M_x86_void (M_Type type)
Definition at line 130 of file ml_x86.c.
References _struct_M_Type::align, M_TYPE_VOID, M_X86_ALIGN_VOID, M_X86_SIZE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_void().
Variable Documentation
int have_reversed = 0 [static]
Definition at line 752 of file ml_x86.c.
Referenced by M_bx86_fnvar_layout(), and M_x86_fnvar_layout().