ml_impact.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <machine/m_spec.h>
#include <machine/m_impact.h>
#include <machine/m_hppa.h>
#include <machine/m_sparc.h>
#include <library/i_list.h>
Defines
#define JWS_NEW_STACK_MODEL
#define M_IMPACT_LCODE_SIZE_VOID 0
#define M_IMPACT_LCODE_SIZE_BIT 1
#define M_IMPACT_LCODE_SIZE_CHAR 8
#define M_IMPACT_LCODE_SIZE_SHORT 16
#define M_IMPACT_LCODE_SIZE_INT 32
#define M_IMPACT_LCODE_SIZE_LONG 32
#define M_IMPACT_LCODE_SIZE_FLOAT 32
#define M_IMPACT_LCODE_SIZE_DOUBLE 64
#define M_IMPACT_LCODE_SIZE_POINTER 32
#define M_IMPACT_LCODE_SIZE_UNION -1
#define M_IMPACT_LCODE_SIZE_STRUCT -1
#define M_IMPACT_LCODE_SIZE_BLOCK -1
#define M_IMPACT_LCODE_SIZE_MAX 64
#define M_IMPACT_LCODE_ALIGN_VOID -1
#define M_IMPACT_LCODE_ALIGN_BIT 1
#define M_IMPACT_LCODE_ALIGN_CHAR 8
#define M_IMPACT_LCODE_ALIGN_SHORT 16
#define M_IMPACT_LCODE_ALIGN_INT 32
#define M_IMPACT_LCODE_ALIGN_LONG 32
#define M_IMPACT_LCODE_ALIGN_FLOAT 32
#define M_IMPACT_LCODE_ALIGN_DOUBLE 64
#define M_IMPACT_LCODE_ALIGN_POINTER 32
#define M_IMPACT_LCODE_ALIGN_UNION -1
#define M_IMPACT_LCODE_ALIGN_STRUCT -1
#define M_IMPACT_LCODE_ALIGN_BLOCK -1
#define M_IMPACT_LCODE_ALIGN_MAX 64
#define M_IMPACT_SIZE_VOID 0
#define M_IMPACT_SIZE_BIT 1
#define M_IMPACT_SIZE_CHAR 8
#define M_IMPACT_SIZE_SHORT 16
#define M_IMPACT_SIZE_INT 32
#define M_IMPACT_SIZE_LONG 32
#define M_IMPACT_SIZE_FLOAT 32
#define M_IMPACT_SIZE_DOUBLE 64
#define M_IMPACT_SIZE_POINTER 32
#define M_IMPACT_SIZE_UNION -1
#define M_IMPACT_SIZE_STRUCT -1
#define M_IMPACT_SIZE_BLOCK -1
#define M_IMPACT_SIZE_MAX 64
#define M_IMPACT_ALIGN_VOID -1
#define M_IMPACT_ALIGN_BIT 1
#define M_IMPACT_ALIGN_CHAR 8
#define M_IMPACT_ALIGN_SHORT 16
#define M_IMPACT_ALIGN_INT 32
#define M_IMPACT_ALIGN_LONG 32
#define M_IMPACT_ALIGN_FLOAT 32
#define M_IMPACT_ALIGN_DOUBLE 64
#define M_IMPACT_ALIGN_POINTER 32
#define M_IMPACT_ALIGN_UNION -1
#define M_IMPACT_ALIGN_STRUCT -1
#define M_IMPACT_ALIGN_BLOCK -1
#define M_IMPACT_ALIGN_MAX 64
#define M_IMPACT_MAX_FNVAR_REG 4
#define MIN_PARAM_SIZE (M_IMPACT_MAX_FNVAR_REG * M_IMPACT_SIZE_INT)
#define M_IMPACT_R0_I 0
#define M_IMPACT_R0_F 1
#define M_IMPACT_R0_F2 2
#define M_IMPACT_ST 0
#define M_IMPACT_ARG_I 4
#define M_IMPACT_ARG_F (M_IMPACT_ARG_I + M_IMPACT_MAX_FNVAR_REG)
#define M_IMPACT_ARG_F2 (M_IMPACT_ARG_F + M_IMPACT_MAX_FNVAR_REG)
#define M_IMPACT_LCODE_MAX_FNVAR_REG 4
#define M_IMPACT_LCODE_SMALL_STRUCT_MAX 64
#define M_IMPACT_LCODE_MIN_PARAM_SIZE (16 * 8)
#define M_IMPACT_LCODE_INT_BASE 0
#define M_IMPACT_LCODE_FLT_BASE 4
#define M_IMPACT_LCODE_RET_I32 15
#define M_IMPACT_LCODE_RET_I64 15
#define M_IMPACT_LCODE_RET_ST 15
#define M_IMPACT_LCODE_RET_F 4
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_impact_void (M_Type type)
void M_impact_bit_long (M_Type type, int n)
void M_impact_bit_int (M_Type type, int n)
void M_impact_bit_short (M_Type type, int n)
void M_impact_bit_char (M_Type type, int n)
void M_impact_float (M_Type type, int unsign)
void M_impact_double (M_Type type, int unsign)
void M_impact_pointer (M_Type type)
int M_impact_eval_type (M_Type type, M_Type ntype)
int M_impact_eval_type2 (M_Type type, M_Type ntype)
int M_impact_call_type (M_Type type, M_Type ntype)
int M_impact_call_type2 (M_Type type, M_Type ntype)
void M_impact_array_layout (M_Type type, int *offset)
int M_impact_array_align (M_Type type)
int M_impact_array_size (M_Type type, int dim)
void M_impact_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_impact_union_align (int n, _M_Type *type)
int M_impact_union_size (int n, _M_Type *type)
void M_impact_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_impact_struct_align (int n, _M_Type *type)
int M_impact_struct_size (int n, _M_Type *type, int struct_align)
int M_impact_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_impact_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **base_macro, int *su_sreg, int *su_ereg, int *pcount, int need_ST, int purpose)
int M_impact_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_impact_no_short_int (void)
void M_impact_cb_label_name (char *fn, int cb, char *line, int len)
int M_impact_is_cb_label (char *label, char *fn, int *cb)
void M_impact_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_impact_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_impact_structure_pointer (int purpose)
int M_impact_return_register (int type, int purpose)
char * M_impact_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_impact_fn_name_from_label (char *label)
int M_impact_fragile_macro (int macro_value)
Set M_impact_fragile_macro_set ()
int M_impact_dataflow_macro (int id)
int M_impact_subroutine_call (int opc)
int M_oper_supported_in_arch_impact (int opc)
int M_num_oper_required_for_impact (L_Oper *oper, char *name)
int M_is_stack_operand_impact (L_Operand *operand)
int M_is_unsafe_macro_impact (L_Operand *operand)
static int M_operand_type_impact_lcode (L_Operand *operand)
static int M_operand_type_impact_hp_lcode (L_Operand *operand)
static int M_operand_type_impact_sparc_lcode (L_Operand *operand)
int M_operand_type_impact (L_Operand *operand)
static int M_conflicting_operands_impact_lcode (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
static int M_conflicting_operands_impact_hp_lcode (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
static int M_conflicting_operands_impact_sparc_lcode (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_conflicting_operands_impact (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
void M_define_macros_impact (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_impact (int id)
int M_num_registers_impact (int ctype)
Variables
int M_impact_model
Set Set_impact_fragile_macro = NULL
int M_Limpact_dbl_offset = 0
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define JWS_NEW_STACK_MODEL
Definition at line 76 of file ml_impact.c.
#define long_neg_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_IMPACT_ALIGN_BIT 1
Definition at line 131 of file ml_impact.c.
#define M_IMPACT_ALIGN_BLOCK -1
Definition at line 141 of file ml_impact.c.
#define M_IMPACT_ALIGN_CHAR 8
Definition at line 132 of file ml_impact.c.
#define M_IMPACT_ALIGN_DOUBLE 64
Definition at line 137 of file ml_impact.c.
#define M_IMPACT_ALIGN_FLOAT 32
Definition at line 136 of file ml_impact.c.
#define M_IMPACT_ALIGN_INT 32
Definition at line 134 of file ml_impact.c.
#define M_IMPACT_ALIGN_LONG 32
Definition at line 135 of file ml_impact.c.
#define M_IMPACT_ALIGN_MAX 64
Definition at line 142 of file ml_impact.c.
#define M_IMPACT_ALIGN_POINTER 32
Definition at line 138 of file ml_impact.c.
#define M_IMPACT_ALIGN_SHORT 16
Definition at line 133 of file ml_impact.c.
#define M_IMPACT_ALIGN_STRUCT -1
Definition at line 140 of file ml_impact.c.
#define M_IMPACT_ALIGN_UNION -1
Definition at line 139 of file ml_impact.c.
#define M_IMPACT_ALIGN_VOID -1
Definition at line 130 of file ml_impact.c.
#define M_IMPACT_ARG_F (M_IMPACT_ARG_I + M_IMPACT_MAX_FNVAR_REG)
Definition at line 157 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_ARG_F2 (M_IMPACT_ARG_F + M_IMPACT_MAX_FNVAR_REG)
Definition at line 158 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_ARG_I 4
Definition at line 156 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_LCODE_ALIGN_BIT 1
Definition at line 102 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_BLOCK -1
Definition at line 112 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_CHAR 8
Definition at line 103 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_DOUBLE 64
Definition at line 108 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_FLOAT 32
Definition at line 107 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_INT 32
Definition at line 105 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_LONG 32
Definition at line 106 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_MAX 64
Definition at line 113 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_POINTER 32
Definition at line 109 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_SHORT 16
Definition at line 104 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_STRUCT -1
Definition at line 111 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_UNION -1
Definition at line 110 of file ml_impact.c.
#define M_IMPACT_LCODE_ALIGN_VOID -1
Definition at line 101 of file ml_impact.c.
#define M_IMPACT_LCODE_FLT_BASE 4
Definition at line 169 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_LCODE_INT_BASE 0
Definition at line 168 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_LCODE_MAX_FNVAR_REG 4
Definition at line 163 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_LCODE_MIN_PARAM_SIZE (16 * 8)
Definition at line 165 of file ml_impact.c.
#define M_IMPACT_LCODE_RET_F 4
Definition at line 174 of file ml_impact.c.
Referenced by M_impact_return_register().
#define M_IMPACT_LCODE_RET_I32 15
Definition at line 171 of file ml_impact.c.
Referenced by M_impact_return_register().
#define M_IMPACT_LCODE_RET_I64 15
Definition at line 172 of file ml_impact.c.
#define M_IMPACT_LCODE_RET_ST 15
Definition at line 173 of file ml_impact.c.
Referenced by M_impact_structure_pointer().
#define M_IMPACT_LCODE_SIZE_BIT 1
Definition at line 88 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_BLOCK -1
Definition at line 98 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_CHAR 8
Definition at line 89 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_DOUBLE 64
Definition at line 94 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_FLOAT 32
Definition at line 93 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_INT 32
Definition at line 91 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_LONG 32
Definition at line 92 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_MAX 64
Definition at line 99 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_POINTER 32
Definition at line 95 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_SHORT 16
Definition at line 90 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_STRUCT -1
Definition at line 97 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_UNION -1
Definition at line 96 of file ml_impact.c.
#define M_IMPACT_LCODE_SIZE_VOID 0
Definition at line 87 of file ml_impact.c.
#define M_IMPACT_LCODE_SMALL_STRUCT_MAX 64
Definition at line 164 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_MAX_FNVAR_REG 4
Definition at line 149 of file ml_impact.c.
Referenced by M_impact_fnvar_layout(), and M_impact_layout_fnvar().
#define M_IMPACT_R0_F 1
Definition at line 153 of file ml_impact.c.
Referenced by M_impact_return_register().
#define M_IMPACT_R0_F2 2
Definition at line 154 of file ml_impact.c.
Referenced by M_impact_return_register().
#define M_IMPACT_R0_I 0
Definition at line 152 of file ml_impact.c.
Referenced by M_impact_return_register().
#define M_IMPACT_SIZE_BIT 1
Definition at line 117 of file ml_impact.c.
#define M_IMPACT_SIZE_BLOCK -1
Definition at line 127 of file ml_impact.c.
#define M_IMPACT_SIZE_CHAR 8
Definition at line 118 of file ml_impact.c.
#define M_IMPACT_SIZE_DOUBLE 64
Definition at line 123 of file ml_impact.c.
#define M_IMPACT_SIZE_FLOAT 32
Definition at line 122 of file ml_impact.c.
#define M_IMPACT_SIZE_INT 32
Definition at line 120 of file ml_impact.c.
#define M_IMPACT_SIZE_LONG 32
Definition at line 121 of file ml_impact.c.
#define M_IMPACT_SIZE_MAX 64
Definition at line 128 of file ml_impact.c.
#define M_IMPACT_SIZE_POINTER 32
Definition at line 124 of file ml_impact.c.
#define M_IMPACT_SIZE_SHORT 16
Definition at line 119 of file ml_impact.c.
#define M_IMPACT_SIZE_STRUCT -1
Definition at line 126 of file ml_impact.c.
#define M_IMPACT_SIZE_UNION -1
Definition at line 125 of file ml_impact.c.
#define M_IMPACT_SIZE_VOID 0
Definition at line 116 of file ml_impact.c.
#define M_IMPACT_ST 0
Definition at line 155 of file ml_impact.c.
Referenced by M_impact_structure_pointer().
#define MIN_PARAM_SIZE (M_IMPACT_MAX_FNVAR_REG * M_IMPACT_SIZE_INT)
Definition at line 150 of file ml_impact.c.
#define non_zero_offset(a)
Value:
((!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                   ((a->src[1]->ctype&0x30)==0x00)))||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_conflicting_operands_impact (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 3889 of file ml_impact.c.
References M_assert(), M_conflicting_operands_impact_hp_lcode(), M_conflicting_operands_impact_lcode(), M_conflicting_operands_impact_sparc_lcode(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, and M_impact_model.
Referenced by M_dep_conflicting_operands().
static int M_conflicting_operands_impact_hp_lcode (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass) [static]
Definition at line 3569 of file ml_impact.c.
References HPPA_MAC_TRUE_SP, and M_assert().
Referenced by M_conflicting_operands_impact().
static int M_conflicting_operands_impact_lcode (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass) [static]
Definition at line 3384 of file ml_impact.c.
References M_assert(), Mspec_num_flt_callee_reg, Mspec_num_flt_caller_reg, Mspec_num_int_callee_reg, Mspec_num_int_caller_reg, and Mspec_num_prd_callee_reg.
Referenced by M_conflicting_operands_impact().
static int M_conflicting_operands_impact_sparc_lcode (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass) [static]
Definition at line 3746 of file ml_impact.c.
References M_assert().
Referenced by M_conflicting_operands_impact().
void M_define_macros_impact (STRING_Symbol_Table * sym_tbl)
Definition at line 3928 of file ml_impact.c.
References M_assert(), M_define_macros_hppa(), M_define_macros_sparc(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, and M_impact_model.
Referenced by M_define_macros().
char* M_get_macro_name_impact (int id)
Definition at line 3955 of file ml_impact.c.
References M_assert(), M_get_macro_name_hppa(), M_get_macro_name_sparc(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and NULL.
Referenced by M_get_macro_name().
int M_impact_array_align (M_Type type)
Definition at line 858 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_array_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_array_align().
Referenced by M_array_align().
void M_impact_array_layout (M_Type type, int * offset)
Definition at line 831 of file ml_impact.c.
References M_assert(), M_hppa_array_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_array_layout().
Referenced by M_array_layout().
int M_impact_array_size (M_Type type, int dim)
Definition at line 886 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_array_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_sparc_array_size(), and _struct_M_Type::size.
Referenced by M_array_size().
void M_impact_bit_char (M_Type type, int n)
Definition at line 333 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_char(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_char(), M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char().
void M_impact_bit_int (M_Type type, int n)
Definition at line 255 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_int(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_int(), M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int().
void M_impact_bit_long (M_Type type, int n)
Definition at line 216 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_long(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_long(), M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long().
void M_impact_bit_short (M_Type type, int n)
Definition at line 294 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_bit_short(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_BIT, M_IMPACT_LCODE_ALIGN_BIT, M_IMPACT_LCODE_SIZE_BIT, M_impact_model, M_IMPACT_SIZE_BIT, M_sparc_bit_short(), M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short().
int M_impact_call_type (M_Type type, M_Type ntype)
Definition at line 651 of file ml_impact.c.
References M_assert(), M_hppa_call_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_double(), M_impact_float(), M_impact_int(), M_impact_model, M_impact_void(), M_sparc_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type().
int M_impact_call_type2 (M_Type type, M_Type ntype)
Definition at line 733 of file ml_impact.c.
References M_assert(), M_hppa_call_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_char(), M_impact_double(), M_impact_float(), M_impact_int(), M_impact_long(), M_impact_model, M_impact_pointer(), M_impact_short(), M_impact_void(), M_sparc_call_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_impact_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 2309 of file ml_impact.c.
References M_assert(), M_hppa_cb_label_name(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_cb_label_name().
Referenced by M_cb_label_name().
int M_impact_dataflow_macro (int id)
Definition at line 2837 of file ml_impact.c.
References M_assert(), M_hppa_dataflow_macro(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_dataflow_macro().
Referenced by M_dataflow_macro().
void M_impact_double (M_Type type, int unsign)
Definition at line 407 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_double(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_DOUBLE, M_IMPACT_LCODE_ALIGN_DOUBLE, M_IMPACT_LCODE_SIZE_DOUBLE, M_impact_model, M_IMPACT_SIZE_DOUBLE, M_sparc_double(), M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), and M_impact_eval_type2().
int M_impact_eval_type (M_Type type, M_Type ntype)
Definition at line 477 of file ml_impact.c.
References M_assert(), M_hppa_eval_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_double(), M_impact_float(), M_impact_int(), M_impact_model, M_impact_void(), M_sparc_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type().
int M_impact_eval_type2 (M_Type type, M_Type ntype)
Definition at line 557 of file ml_impact.c.
References M_assert(), M_hppa_eval_type(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_char(), M_impact_double(), M_impact_float(), M_impact_int(), M_impact_long(), M_impact_model, M_impact_pointer(), M_impact_short(), M_impact_void(), M_sparc_eval_type(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_impact_float (M_Type type, int unsign)
Definition at line 372 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_float(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_FLOAT, M_IMPACT_LCODE_ALIGN_FLOAT, M_IMPACT_LCODE_SIZE_FLOAT, M_impact_model, M_IMPACT_SIZE_FLOAT, M_sparc_float(), M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), and M_impact_eval_type2().
char* M_impact_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 2546 of file ml_impact.c.
References M_IM_LCODE, and M_impact_model.
Referenced by M_fn_label_name().
char* M_impact_fn_name_from_label (char * label)
Definition at line 2568 of file ml_impact.c.
References M_IM_LCODE, and M_impact_model.
Referenced by M_fn_name_from_label().
int M_impact_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** base_macro, int * su_sreg, int * su_ereg, int * pcount, int need_ST, int purpose)
Definition at line 1777 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_hppa_fnvar_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_ARG_F, M_IMPACT_ARG_F2, M_IMPACT_ARG_I, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_ALIGN_MAX, M_IMPACT_LCODE_FLT_BASE, M_IMPACT_LCODE_INT_BASE, M_IMPACT_LCODE_MAX_FNVAR_REG, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SMALL_STRUCT_MAX, M_IMPACT_MAX_FNVAR_REG, M_impact_model, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_sparc_fnvar_layout(), M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout().
int M_impact_fragile_macro (int macro_value)
Definition at line 2584 of file ml_impact.c.
References M_assert(), M_hppa_fragile_macro(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_fragile_macro().
Referenced by M_fragile_macro().
Set M_impact_fragile_macro_set ()
Definition at line 2635 of file ml_impact.c.
References M_assert(), M_hppa_fragile_macro_set(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_sparc_fragile_macro_set(), Set_add(), and Set_impact_fragile_macro.
Referenced by M_fragile_macro_set().
int M_impact_is_cb_label (char * label, char * fn, int * cb)
Definition at line 2336 of file ml_impact.c.
References M_assert(), M_hppa_is_cb_label(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_is_cb_label().
Referenced by M_is_cb_label().
int M_impact_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 2391 of file ml_impact.c.
References M_assert(), M_hppa_is_jumptbl_label(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_JUMPTBL_BASE_NAME, and M_sparc_is_jumptbl_label().
Referenced by M_is_jumptbl_label().
void M_impact_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 2364 of file ml_impact.c.
References M_assert(), M_hppa_jumptbl_label_name(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_JUMPTBL_BASE_NAME, and M_sparc_jumptbl_label_name().
Referenced by M_jumptbl_label_name().
int M_impact_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 1447 of file ml_impact.c.
References _struct_M_Type::align, List_next(), List_start(), M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_hppa_layout_fnvar(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_ARG_F, M_IMPACT_ARG_F2, M_IMPACT_ARG_I, M_IMPACT_LCODE_ALIGN_INT, M_IMPACT_LCODE_ALIGN_MAX, M_IMPACT_LCODE_FLT_BASE, M_IMPACT_LCODE_INT_BASE, M_IMPACT_LCODE_MAX_FNVAR_REG, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SMALL_STRUCT_MAX, M_IMPACT_MAX_FNVAR_REG, M_impact_model, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_sparc_layout_fnvar(), M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, _struct_M_Param::mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Type::size, and _struct_M_Type::type.
Referenced by M_layout_fnvar().
int M_impact_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 2174 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_lvar_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_MAX, M_IMPACT_LCODE_ALIGN_MAX, M_impact_model, M_sparc_lvar_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_lvar_layout().
int M_impact_no_short_int (void)
Definition at line 2281 of file ml_impact.c.
References M_assert(), M_hppa_no_short_int(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SIZE_SHORT, M_impact_model, M_IMPACT_SIZE_INT, M_IMPACT_SIZE_SHORT, and M_sparc_no_short_int().
Referenced by M_no_short_int().
void M_impact_pointer (M_Type type)
Definition at line 442 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_pointer(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_POINTER, M_IMPACT_LCODE_ALIGN_POINTER, M_IMPACT_LCODE_SIZE_POINTER, M_impact_model, M_IMPACT_SIZE_POINTER, M_sparc_pointer(), M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type2(), M_impact_eval_type2(), and M_pointer().
int M_impact_return_register (int type, int purpose)
Definition at line 2497 of file ml_impact.c.
References M_assert(), M_hppa_return_register(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_RET_F, M_IMPACT_LCODE_RET_I32, M_impact_model, M_IMPACT_R0_F, M_IMPACT_R0_F2, M_IMPACT_R0_I, M_sparc_return_register(), M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
Referenced by M_return_register().
int M_impact_struct_align (int n, _M_Type * type)
Definition at line 1255 of file ml_impact.c.
References M_assert(), M_hppa_struct_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, and M_sparc_struct_align().
Referenced by M_struct_align().
void M_impact_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 1089 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_struct_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_SIZE_CHAR, M_IMPACT_LCODE_SIZE_INT, M_IMPACT_LCODE_SIZE_LONG, M_IMPACT_LCODE_SIZE_SHORT, M_impact_model, M_IMPACT_SIZE_CHAR, M_IMPACT_SIZE_INT, M_IMPACT_SIZE_LONG, M_sparc_struct_layout(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_struct_layout().
int M_impact_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 1309 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_struct_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_IMPACT_LCODE_ALIGN_LONG, M_IMPACT_LCODE_ALIGN_SHORT, M_IMPACT_LCODE_SIZE_INT, M_impact_model, M_IMPACT_SIZE_INT, M_sparc_struct_size(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_struct_size().
int M_impact_structure_pointer (int purpose)
Definition at line 2469 of file ml_impact.c.
References M_assert(), M_hppa_structure_pointer(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_LCODE_RET_ST, M_impact_model, M_IMPACT_ST, and M_sparc_structure_pointer().
Referenced by M_structure_pointer().
int M_impact_subroutine_call (int opc)
Definition at line 2874 of file ml_impact.c.
References M_assert(), M_hppa_subroutine_call(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_subroutine_call().
Referenced by M_subroutine_call().
int M_impact_union_align (int n, _M_Type * type)
Definition at line 963 of file ml_impact.c.
References M_assert(), M_hppa_union_align(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, and M_sparc_union_align().
Referenced by M_union_align().
void M_impact_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 926 of file ml_impact.c.
References M_assert(), M_hppa_union_layout(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, and M_sparc_union_layout().
Referenced by M_union_layout().
int M_impact_union_size (int n, _M_Type * type)
Definition at line 1017 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_union_size(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_INT, M_IMPACT_LCODE_ALIGN_CHAR, M_impact_model, M_sparc_union_size(), and _struct_M_Type::size.
Referenced by M_union_size().
void M_impact_void (M_Type type)
Definition at line 181 of file ml_impact.c.
References _struct_M_Type::align, M_assert(), M_hppa_void(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_IMPACT_ALIGN_VOID, M_IMPACT_LCODE_ALIGN_VOID, M_IMPACT_LCODE_SIZE_VOID, M_impact_model, M_IMPACT_SIZE_VOID, M_sparc_void(), M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_call_type(), M_impact_call_type2(), M_impact_eval_type(), M_impact_eval_type2(), and M_void().
int M_is_stack_operand_impact (L_Operand * operand)
Definition at line 3126 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_is_stack_operand_hppa(), and M_is_stack_operand_sparc().
Referenced by M_is_stack_operand().
int M_is_unsafe_macro_impact (L_Operand * operand)
Definition at line 3171 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_is_unsafe_macro_hppa(), and M_is_unsafe_macro_sparc().
Referenced by M_is_unsafe_macro().
int M_num_oper_required_for_impact (L_Oper * oper, char * name)
Definition at line 2947 of file ml_impact.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_num_oper_required_for_hppa(), M_num_oper_required_for_sparc(), non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for().
int M_num_registers_impact (int ctype)
Definition at line 3984 of file ml_impact.c.
Referenced by M_num_registers().
int M_oper_supported_in_arch_impact (int opc)
Definition at line 2913 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_oper_supported_in_arch_hppa(), and M_oper_supported_in_arch_sparc().
Referenced by M_oper_supported_in_arch().
int M_operand_type_impact (L_Operand * operand)
Definition at line 3309 of file ml_impact.c.
References M_assert(), M_IM_HP_LCODE, M_IM_HP_MCODE, M_IM_LCODE, M_IM_SPARC_LCODE, M_IM_SPARC_MCODE, M_IM_VER_1, M_impact_model, M_operand_type_impact_hp_lcode(), M_operand_type_impact_lcode(), and M_operand_type_impact_sparc_lcode().
Referenced by M_mdes_operand_type().
static int M_operand_type_impact_hp_lcode (L_Operand * operand) [static]
Definition at line 3231 of file ml_impact.c.
References FIELD_11, FIELD_14, FIELD_5, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit11, MDES_OPERAND_Lit14, MDES_OPERAND_Lit21, MDES_OPERAND_Lit5, MDES_OPERAND_NULL, MDES_OPERAND_p, MDES_OPERAND_REG, and NULL.
Referenced by M_operand_type_impact().
static int M_operand_type_impact_lcode (L_Operand * operand) [static]
Definition at line 3199 of file ml_impact.c.
References M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_p, MDES_OPERAND_REG, and NULL.
Referenced by M_operand_type_impact().
static int M_operand_type_impact_sparc_lcode (L_Operand * operand) [static]
Definition at line 3270 of file ml_impact.c.
References L_SPARC_MAC_FCC, L_SPARC_MAC_FCC15, L_SPARC_MAC_ICC, L_SPARC_MAC_ICC15, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit, MDES_OPERAND_NULL, MDES_OPERAND_REG, MDES_OPERAND_sparc_fcc, MDES_OPERAND_sparc_icc, and NULL.
Referenced by M_operand_type_impact().
Variable Documentation
int M_impact_model
Definition at line 84 of file mi_impact.c.
int M_Limpact_dbl_offset = 0
Definition at line 3341 of file ml_impact.c.
Set Set_impact_fragile_macro = NULL
Definition at line 147 of file ml_impact.c.
Referenced by M_impact_fragile_macro_set().