ml_hppa.c File Reference
#include <config.h>
#include <stdio.h>
#include <Lcode/l_main.h>
#include `m_hppa.h`
Defines
#define M_HPPA_SIZE_VOID 0
#define M_HPPA_SIZE_BIT 1
#define M_HPPA_SIZE_CHAR 8
#define M_HPPA_SIZE_SHORT 16
#define M_HPPA_SIZE_INT 32
#define M_HPPA_SIZE_LONG 32
#define M_HPPA_SIZE_FLOAT 32
#define M_HPPA_SIZE_DOUBLE 64
#define M_HPPA_SIZE_POINTER 32
#define M_HPPA_SIZE_UNION -1
#define M_HPPA_SIZE_STRUCT -1
#define M_HPPA_SIZE_BLOCK -1
#define M_HPPA_SIZE_MAX 64
#define M_HPPA_ALIGN_VOID -1
#define M_HPPA_ALIGN_BIT 1
#define M_HPPA_ALIGN_CHAR 8
#define M_HPPA_ALIGN_SHORT 16
#define M_HPPA_ALIGN_INT 32
#define M_HPPA_ALIGN_LONG 32
#define M_HPPA_ALIGN_FLOAT 32
#define M_HPPA_ALIGN_DOUBLE 64
#define M_HPPA_ALIGN_POINTER 32
#define M_HPPA_ALIGN_UNION -1
#define M_HPPA_ALIGN_STRUCT -1
#define M_HPPA_ALIGN_BLOCK -1
#define M_HPPA_ALIGN_MAX 64
#define M_HPPA_MAX_FNVAR_REG 4
#define M_HPPA_SMALL_STRUCT_MAX 64
#define MIN_PARAM_SIZE (16 * 8)
#define M_HPPA_INT_BASE 0
#define M_HPPA_FLT_BASE 4
#define M_HPPA_RET_I32 15
#define M_HPPA_RET_I64 15
#define M_HPPA_RET_ST 15
#define M_HPPA_RET_F 4
#define has_label_operand(a)
#define indexed_memory_op(a)
#define non_zero_offset(a)
#define short_int_inc(a, b)
#define long_pos_int_inc(a, b)
#define long_neg_int_inc(a, b)
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
Functions
void M_hppa_void (M_Type type)
void M_hppa_bit_long (M_Type type, int n)
void M_hppa_bit_int (M_Type type, int n)
void M_hppa_bit_short (M_Type type, int n)
void M_hppa_bit_char (M_Type type, int n)
void M_hppa_float (M_Type type, int unsign)
void M_hppa_double (M_Type type, int unsign)
void M_hppa_pointer (M_Type type)
int M_hppa_eval_type (M_Type type, M_Type ntype)
int M_hppa_eval_type2 (M_Type type, M_Type ntype)
int M_hppa_call_type (M_Type type, M_Type ntype)
int M_hppa_call_type2 (M_Type type, M_Type ntype)
void M_hppa_array_layout (M_Type type, int *offset)
int M_hppa_array_align (M_Type type)
int M_hppa_array_size (M_Type type, int dim)
void M_hppa_union_layout (int n, _M_Type *type, int *offset, int *bit_offset)
int M_hppa_union_align (int n, _M_Type *type)
int M_hppa_union_size (int n, _M_Type *type)
void M_hppa_struct_layout (int n, _M_Type *type, int *base, int *bit_offset)
int M_hppa_struct_align (int n, _M_Type *type)
int M_hppa_struct_size (int n, _M_Type *type, int struct_align)
int M_hppa_layout_fnvar (List param_list, char **base_macro, int *pcount, int purpose)
int M_hppa_fnvar_layout (int n, _M_Type *type, long int *offset, int *mode, int *reg, int *paddr, char **macro, int *su_sreg, int *su_ereg, int *pcount, int is_st, int purpose)
int M_hppa_lvar_layout (int n, _M_Type *type, long int *offset, char **base_macro)
int M_hppa_no_short_int (void)
void M_hppa_cb_label_name (char *fn, int cb, char *line, int len)
int M_hppa_is_cb_label (char *label, char *fn, int *cb)
void M_hppa_jumptbl_label_name (char *fn, int tbl_id, char *line, int len)
int M_hppa_is_jumptbl_label (char *label, char *fn, int *tbl_id)
int M_hppa_structure_pointer (int purpose)
int M_hppa_return_register (int type, int purpose)
char * M_hppa_fn_label_name (char *label, int(*is_func)(char *is_func_label))
char * M_hppa_fn_name_from_label (char *label)
int M_hppa_fragile_macro (int macro_value)
Set M_hppa_fragile_macro_set ()
int M_hppa_dataflow_macro (int id)
int M_hppa_subroutine_call (int opc)
void M_define_macros_hppa (STRING_Symbol_Table *sym_tbl)
char * M_get_macro_name_hppa (int id)
void M_define_opcode_name_hppa (STRING_Symbol_Table *sym_tbl)
char * M_get_opcode_name_hppa (int id)
int M_oper_supported_in_arch_hppa (int opc)
int M_num_oper_required_for_hppa (L_Oper *oper, char *name)
int M_is_stack_operand_hppa (L_Operand *operand)
int M_is_unsafe_macro_hppa (L_Operand *operand)
int M_operand_type_hppa (L_Operand *operand)
int M_conflicting_operands_hppa (L_Operand *operand, L_Operand **conflict_array, int len, int prepass)
int M_num_registers_hppa (int ctype)
Variables
Set Set_hppa_fragile_macro = NULL
Define Documentation
#define has_label_operand(a)
Value:
((a->src[0]->type == L_OPERAND_LABEL)||\
                                 (a->src[1]->type == L_OPERAND_LABEL))
#define indexed_memory_op(a)
Value:
((a->src[0]->type == L_OPERAND_REGISTER)&&\
                                 (a->src[1]->type == L_OPERAND_REGISTER))
#define long_neg_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x2000) && \
                                 (a->src[b]->value.i < 0))
#define long_pos_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i > 0) && \
                                 (a->src[b]->value.i < 0x2000))
#define M_HPPA_ALIGN_BIT 1
Definition at line 93 of file ml_hppa.c.
#define M_HPPA_ALIGN_BLOCK -1
Definition at line 103 of file ml_hppa.c.
#define M_HPPA_ALIGN_CHAR 8
Definition at line 94 of file ml_hppa.c.
#define M_HPPA_ALIGN_DOUBLE 64
Definition at line 99 of file ml_hppa.c.
#define M_HPPA_ALIGN_FLOAT 32
Definition at line 98 of file ml_hppa.c.
#define M_HPPA_ALIGN_INT 32
Definition at line 96 of file ml_hppa.c.
#define M_HPPA_ALIGN_LONG 32
Definition at line 97 of file ml_hppa.c.
#define M_HPPA_ALIGN_MAX 64
Definition at line 104 of file ml_hppa.c.
#define M_HPPA_ALIGN_POINTER 32
Definition at line 100 of file ml_hppa.c.
#define M_HPPA_ALIGN_SHORT 16
Definition at line 95 of file ml_hppa.c.
#define M_HPPA_ALIGN_STRUCT -1
Definition at line 102 of file ml_hppa.c.
#define M_HPPA_ALIGN_UNION -1
Definition at line 101 of file ml_hppa.c.
#define M_HPPA_ALIGN_VOID -1
Definition at line 92 of file ml_hppa.c.
#define M_HPPA_FLT_BASE 4
Definition at line 115 of file ml_hppa.c.
Referenced by M_hppa_fnvar_layout().
#define M_HPPA_INT_BASE 0
Definition at line 114 of file ml_hppa.c.
Referenced by M_hppa_fnvar_layout().
#define M_HPPA_MAX_FNVAR_REG 4
Definition at line 109 of file ml_hppa.c.
Referenced by M_hppa_fnvar_layout().
#define M_HPPA_RET_F 4
Definition at line 120 of file ml_hppa.c.
Referenced by M_hppa_return_register().
#define M_HPPA_RET_I32 15
Definition at line 117 of file ml_hppa.c.
Referenced by M_hppa_return_register().
#define M_HPPA_RET_I64 15
Definition at line 118 of file ml_hppa.c.
#define M_HPPA_RET_ST 15
Definition at line 119 of file ml_hppa.c.
Referenced by M_hppa_structure_pointer().
#define M_HPPA_SIZE_BIT 1
Definition at line 79 of file ml_hppa.c.
#define M_HPPA_SIZE_BLOCK -1
Definition at line 89 of file ml_hppa.c.
#define M_HPPA_SIZE_CHAR 8
Definition at line 80 of file ml_hppa.c.
#define M_HPPA_SIZE_DOUBLE 64
Definition at line 85 of file ml_hppa.c.
#define M_HPPA_SIZE_FLOAT 32
Definition at line 84 of file ml_hppa.c.
#define M_HPPA_SIZE_INT 32
Definition at line 82 of file ml_hppa.c.
#define M_HPPA_SIZE_LONG 32
Definition at line 83 of file ml_hppa.c.
#define M_HPPA_SIZE_MAX 64
Definition at line 90 of file ml_hppa.c.
#define M_HPPA_SIZE_POINTER 32
Definition at line 86 of file ml_hppa.c.
#define M_HPPA_SIZE_SHORT 16
Definition at line 81 of file ml_hppa.c.
#define M_HPPA_SIZE_STRUCT -1
Definition at line 88 of file ml_hppa.c.
#define M_HPPA_SIZE_UNION -1
Definition at line 87 of file ml_hppa.c.
#define M_HPPA_SIZE_VOID 0
Definition at line 78 of file ml_hppa.c.
#define M_HPPA_SMALL_STRUCT_MAX 64
Definition at line 110 of file ml_hppa.c.
Referenced by M_hppa_fnvar_layout().
#define MIN_PARAM_SIZE (16 * 8)
Definition at line 111 of file ml_hppa.c.
#define non_zero_offset(a)
Value:
((!((a->src[1]->type==L_OPERAND_IMMED)&&\
                                   ((a->src[1]->ctype&0x30)==0x00)))||\
                                 (a->src[1]->value.i != 0))
#define register_inc(a, b) (a $\rightarrow$ src[b] $\rightarrow$ type == L_OPERAND_REGISTER)
#define short_int_inc(a, b)
Value:
((a->src[b]->type==L_OPERAND_IMMED)&&\
                                 ((a->src[b]->ctype&0x30)==0x00)&&\
                                 (a->src[b]->value.i >= -0x10) &&\
                                 (a->src[b]->value.i < 0x10))
Function Documentation
int M_conflicting_operands_hppa (L_Operand * operand, L_Operand ** conflict_array, int len, int prepass)
Definition at line 2387 of file ml_hppa.c.
References HPPA_MAC_TRUE_SP, M_assert(), and MAX_INT_NAME.
Referenced by M_dep_conflicting_operands().
void M_define_macros_hppa (STRING_Symbol_Table * sym_tbl)
Definition at line 1443 of file ml_hppa.c.
References HPPA_MAC_ALLOC, HPPA_MAC_CALLEE_F, HPPA_MAC_CALLEE_I, HPPA_MAC_DP, HPPA_MAC_DYNCALL, HPPA_MAC_FLOAT_CBIT, HPPA_MAC_FZERO, HPPA_MAC_LEAF, HPPA_MAC_MILLI_RET_VALUE, HPPA_MAC_MILLI_RETADDR, HPPA_MAC_PLAYDOH_BRTARGET, HPPA_MAC_PLAYDOH_BRTMP, HPPA_MAC_PLAYDOH_DEST0, HPPA_MAC_PLAYDOH_DEST1, HPPA_MAC_PLAYDOH_ESC, HPPA_MAC_PLAYDOH_FDEST0, HPPA_MAC_PLAYDOH_FONE, HPPA_MAC_PLAYDOH_FSRC0, HPPA_MAC_PLAYDOH_FSRC1, HPPA_MAC_PLAYDOH_FSRC2, HPPA_MAC_PLAYDOH_GPM, HPPA_MAC_PLAYDOH_GPR, HPPA_MAC_PLAYDOH_LC, HPPA_MAC_PLAYDOH_PDST0, HPPA_MAC_PLAYDOH_PDST1, HPPA_MAC_PLAYDOH_PRED0, HPPA_MAC_PLAYDOH_PRED1, HPPA_MAC_PLAYDOH_PRED_ALL_ROT, HPPA_MAC_PLAYDOH_PRED_ALL_STATIC, HPPA_MAC_PLAYDOH_PRED_FALSE, HPPA_MAC_PLAYDOH_PRED_TRUE, HPPA_MAC_PLAYDOH_PSRC0, HPPA_MAC_PLAYDOH_PV_0, HPPA_MAC_PLAYDOH_PV_1, HPPA_MAC_PLAYDOH_PV_2, HPPA_MAC_PLAYDOH_PV_3, HPPA_MAC_PLAYDOH_PV_4, HPPA_MAC_PLAYDOH_PV_5, HPPA_MAC_PLAYDOH_PV_6, HPPA_MAC_PLAYDOH_PV_7, HPPA_MAC_PLAYDOH_RRB, HPPA_MAC_PLAYDOH_SRC0, HPPA_MAC_PLAYDOH_SRC1, HPPA_MAC_PLAYDOH_SRC2, HPPA_MAC_PLAYDOH_SRC3, HPPA_MAC_RETADDR, HPPA_MAC_SAR, HPPA_MAC_SR3, HPPA_MAC_SR5, HPPA_MAC_SWAP_PTR, HPPA_MAC_TEMPREG, HPPA_MAC_TRUE_SP, HPPA_MAC_ZERO, and M_add_symbol.
Referenced by M_define_macros(), and M_define_macros_impact().
void M_define_opcode_name_hppa (STRING_Symbol_Table * sym_tbl)
Definition at line 1624 of file ml_hppa.c.
References LHPPAop_ADDIB_LT_BWD, LHPPAop_ADDIB_LT_FWD, LHPPAop_ADDIL, LHPPAop_BB_0_BWD, LHPPAop_BB_0_FWD, LHPPAop_BB_1_BWD, LHPPAop_BB_1_FWD, LHPPAop_COMB_EQ_BWD, LHPPAop_COMB_EQ_FWD, LHPPAop_COMB_GE_BWD, LHPPAop_COMB_GE_FWD, LHPPAop_COMB_GE_U_BWD, LHPPAop_COMB_GE_U_FWD, LHPPAop_COMB_GT_BWD, LHPPAop_COMB_GT_FWD, LHPPAop_COMB_GT_U_BWD, LHPPAop_COMB_GT_U_FWD, LHPPAop_COMB_LE_BWD, LHPPAop_COMB_LE_FWD, LHPPAop_COMB_LE_U_BWD, LHPPAop_COMB_LE_U_FWD, LHPPAop_COMB_LT_BWD, LHPPAop_COMB_LT_FWD, LHPPAop_COMB_LT_U_BWD, LHPPAop_COMB_LT_U_FWD, LHPPAop_COMB_NE_BWD, LHPPAop_COMB_NE_FWD, LHPPAop_COMIB_EQ_BWD, LHPPAop_COMIB_EQ_FWD, LHPPAop_COMIB_GE_BWD, LHPPAop_COMIB_GE_FWD, LHPPAop_COMIB_GE_U_BWD, LHPPAop_COMIB_GE_U_FWD, LHPPAop_COMIB_GT_BWD, LHPPAop_COMIB_GT_FWD, LHPPAop_COMIB_GT_U_BWD, LHPPAop_COMIB_GT_U_FWD, LHPPAop_COMIB_LE_BWD, LHPPAop_COMIB_LE_FWD, LHPPAop_COMIB_LE_U_BWD, LHPPAop_COMIB_LE_U_FWD, LHPPAop_COMIB_LT_BWD, LHPPAop_COMIB_LT_FWD, LHPPAop_COMIB_LT_U_BWD, LHPPAop_COMIB_LT_U_FWD, LHPPAop_COMIB_NE_BWD, LHPPAop_COMIB_NE_FWD, LHPPAop_DEPI, LHPPAop_EXTRU, LHPPAop_FMPYADD, LHPPAop_FMPYSUB, LHPPAop_JSR_DYNCALL, LHPPAop_LD_C2_SC1, LHPPAop_LD_C2_SC2, LHPPAop_LD_C2_SC3, LHPPAop_LD_C2_SV1, LHPPAop_LD_C_SC1, LHPPAop_LD_C_SC2, LHPPAop_LD_C_SC3, LHPPAop_LD_C_SV1, LHPPAop_LD_F2_SC1, LHPPAop_LD_F2_SC2, LHPPAop_LD_F2_SC3, LHPPAop_LD_F2_SV1, LHPPAop_LD_F_SC1, LHPPAop_LD_F_SC2, LHPPAop_LD_F_SC3, LHPPAop_LD_F_SV1, LHPPAop_LD_I_SC1, LHPPAop_LD_I_SC2, LHPPAop_LD_I_SC3, LHPPAop_LD_I_SV1, LHPPAop_LD_POST_C2_SC1, LHPPAop_LD_POST_C2_SC2, LHPPAop_LD_POST_C2_SC3, LHPPAop_LD_POST_C2_SV1, LHPPAop_LD_POST_C_SC1, LHPPAop_LD_POST_C_SC2, LHPPAop_LD_POST_C_SC3, LHPPAop_LD_POST_C_SV1, LHPPAop_LD_POST_F2_SC1, LHPPAop_LD_POST_F2_SC2, LHPPAop_LD_POST_F2_SC3, LHPPAop_LD_POST_F2_SV1, LHPPAop_LD_POST_F_SC1, LHPPAop_LD_POST_F_SC2, LHPPAop_LD_POST_F_SC3, LHPPAop_LD_POST_F_SV1, LHPPAop_LD_POST_I_SC1, LHPPAop_LD_POST_I_SC2, LHPPAop_LD_POST_I_SC3, LHPPAop_LD_POST_I_SV1, LHPPAop_LD_POST_UC2_SC1, LHPPAop_LD_POST_UC2_SC2, LHPPAop_LD_POST_UC2_SC3, LHPPAop_LD_POST_UC2_SV1, LHPPAop_LD_POST_UC_SC1, LHPPAop_LD_POST_UC_SC2, LHPPAop_LD_POST_UC_SC3, LHPPAop_LD_POST_UC_SV1, LHPPAop_LD_PRE_C2_SC1, LHPPAop_LD_PRE_C2_SC2, LHPPAop_LD_PRE_C2_SC3, LHPPAop_LD_PRE_C2_SV1, LHPPAop_LD_PRE_C_SC1, LHPPAop_LD_PRE_C_SC2, LHPPAop_LD_PRE_C_SC3, LHPPAop_LD_PRE_C_SV1, LHPPAop_LD_PRE_F2_SC1, LHPPAop_LD_PRE_F2_SC2, LHPPAop_LD_PRE_F2_SC3, LHPPAop_LD_PRE_F2_SV1, LHPPAop_LD_PRE_F_SC1, LHPPAop_LD_PRE_F_SC2, LHPPAop_LD_PRE_F_SC3, LHPPAop_LD_PRE_F_SV1, LHPPAop_LD_PRE_I_SC1, LHPPAop_LD_PRE_I_SC2, LHPPAop_LD_PRE_I_SC3, LHPPAop_LD_PRE_I_SV1, LHPPAop_LD_PRE_UC2_SC1, LHPPAop_LD_PRE_UC2_SC2, LHPPAop_LD_PRE_UC2_SC3, LHPPAop_LD_PRE_UC2_SV1, LHPPAop_LD_PRE_UC_SC1, LHPPAop_LD_PRE_UC_SC2, LHPPAop_LD_PRE_UC_SC3, LHPPAop_LD_PRE_UC_SV1, LHPPAop_LD_UC2_SC1, LHPPAop_LD_UC2_SC2, LHPPAop_LD_UC2_SC3, LHPPAop_LD_UC2_SV1, LHPPAop_LD_UC_SC1, LHPPAop_LD_UC_SC2, LHPPAop_LD_UC_SC3, LHPPAop_LD_UC_SV1, LHPPAop_LDIL, LHPPAop_LDO, LHPPAop_MTSP, LHPPAop_PRED_MOV, LHPPAop_VEXTRS, LHPPAop_VSHD, LHPPAop_ZVDEP, LHPPAop_ZVDEPI, M_add_symbol, PAopcode_ADDIB_LT_BWD, PAopcode_ADDIB_LT_FWD, PAopcode_ADDIL, PAopcode_BB_0_BWD, PAopcode_BB_0_FWD, PAopcode_BB_1_BWD, PAopcode_BB_1_FWD, PAopcode_COMB_EQ_BWD, PAopcode_COMB_EQ_FWD, PAopcode_COMB_GE_BWD, PAopcode_COMB_GE_FWD, PAopcode_COMB_GE_U_BWD, PAopcode_COMB_GE_U_FWD, PAopcode_COMB_GT_BWD, PAopcode_COMB_GT_FWD, PAopcode_COMB_GT_U_BWD, PAopcode_COMB_GT_U_FWD, PAopcode_COMB_LE_BWD, PAopcode_COMB_LE_FWD, PAopcode_COMB_LE_U_BWD, PAopcode_COMB_LE_U_FWD, PAopcode_COMB_LT_BWD, PAopcode_COMB_LT_FWD, PAopcode_COMB_LT_U_BWD, PAopcode_COMB_LT_U_FWD, PAopcode_COMB_NE_BWD, PAopcode_COMB_NE_FWD, PAopcode_COMIB_EQ_BWD, PAopcode_COMIB_EQ_FWD, PAopcode_COMIB_GE_BWD, PAopcode_COMIB_GE_FWD, PAopcode_COMIB_GE_U_BWD, PAopcode_COMIB_GE_U_FWD, PAopcode_COMIB_GT_BWD, PAopcode_COMIB_GT_FWD, PAopcode_COMIB_GT_U_BWD, PAopcode_COMIB_GT_U_FWD, PAopcode_COMIB_LE_BWD, PAopcode_COMIB_LE_FWD, PAopcode_COMIB_LE_U_BWD, PAopcode_COMIB_LE_U_FWD, PAopcode_COMIB_LT_BWD, PAopcode_COMIB_LT_FWD, PAopcode_COMIB_LT_U_BWD, PAopcode_COMIB_LT_U_FWD, PAopcode_COMIB_NE_BWD, PAopcode_COMIB_NE_FWD, PAopcode_DEPI, PAopcode_EXTRU, PAopcode_FMPYADD, PAopcode_FMPYSUB, PAopcode_JSR_DYNCALL, PAopcode_LD_C2_SC1, PAopcode_LD_C2_SC2, PAopcode_LD_C2_SC3, PAopcode_LD_C2_SV1, PAopcode_LD_C_SC1, PAopcode_LD_C_SC2, PAopcode_LD_C_SC3, PAopcode_LD_C_SV1, PAopcode_LD_F2_SC1, PAopcode_LD_F2_SC2, PAopcode_LD_F2_SC3, PAopcode_LD_F2_SV1, PAopcode_LD_F_SC1, PAopcode_LD_F_SC2, PAopcode_LD_F_SC3, PAopcode_LD_F_SV1, PAopcode_LD_I_SC1, PAopcode_LD_I_SC2, PAopcode_LD_I_SC3, PAopcode_LD_I_SV1, PAopcode_LD_POST_C2_SC1, PAopcode_LD_POST_C2_SC2, PAopcode_LD_POST_C2_SC3, PAopcode_LD_POST_C2_SV1, PAopcode_LD_POST_C_SC1, PAopcode_LD_POST_C_SC2, PAopcode_LD_POST_C_SC3, PAopcode_LD_POST_C_SV1, PAopcode_LD_POST_F2_SC1, PAopcode_LD_POST_F2_SC2, PAopcode_LD_POST_F2_SC3, PAopcode_LD_POST_F2_SV1, PAopcode_LD_POST_F_SC1, PAopcode_LD_POST_F_SC2, PAopcode_LD_POST_F_SC3, PAopcode_LD_POST_F_SV1, PAopcode_LD_POST_I_SC1, PAopcode_LD_POST_I_SC2, PAopcode_LD_POST_I_SC3, PAopcode_LD_POST_I_SV1, PAopcode_LD_POST_UC2_SC1, PAopcode_LD_POST_UC2_SC2, PAopcode_LD_POST_UC2_SC3, PAopcode_LD_POST_UC2_SV1, PAopcode_LD_POST_UC_SC1, PAopcode_LD_POST_UC_SC2, PAopcode_LD_POST_UC_SC3, PAopcode_LD_POST_UC_SV1, PAopcode_LD_PRE_C2_SC1, PAopcode_LD_PRE_C2_SC2, PAopcode_LD_PRE_C2_SC3, PAopcode_LD_PRE_C2_SV1, PAopcode_LD_PRE_C_SC1, PAopcode_LD_PRE_C_SC2, PAopcode_LD_PRE_C_SC3, PAopcode_LD_PRE_C_SV1, PAopcode_LD_PRE_F2_SC1, PAopcode_LD_PRE_F2_SC2, PAopcode_LD_PRE_F2_SC3, PAopcode_LD_PRE_F2_SV1, PAopcode_LD_PRE_F_SC1, PAopcode_LD_PRE_F_SC2, PAopcode_LD_PRE_F_SC3, PAopcode_LD_PRE_F_SV1, PAopcode_LD_PRE_I_SC1, PAopcode_LD_PRE_I_SC2, PAopcode_LD_PRE_I_SC3, PAopcode_LD_PRE_I_SV1, PAopcode_LD_PRE_UC2_SC1, PAopcode_LD_PRE_UC2_SC2, PAopcode_LD_PRE_UC2_SC3, PAopcode_LD_PRE_UC2_SV1, PAopcode_LD_PRE_UC_SC1, PAopcode_LD_PRE_UC_SC2, PAopcode_LD_PRE_UC_SC3, PAopcode_LD_PRE_UC_SV1, PAopcode_LD_UC2_SC1, PAopcode_LD_UC2_SC2, PAopcode_LD_UC2_SC3, PAopcode_LD_UC2_SV1, PAopcode_LD_UC_SC1, PAopcode_LD_UC_SC2, PAopcode_LD_UC_SC3, PAopcode_LD_UC_SV1, PAopcode_LDIL, PAopcode_LDO, PAopcode_MTSP, PAopcode_PRED_MOV, PAopcode_VEXTRS, PAopcode_VSHD, PAopcode_ZVDEP, and PAopcode_ZVDEPI.
Referenced by M_define_opcode_name().
char* M_get_macro_name_hppa (int id)
Definition at line 1505 of file ml_hppa.c.
References HPPA_MAC_ALLOC, HPPA_MAC_CALLEE_F, HPPA_MAC_CALLEE_I, HPPA_MAC_DP, HPPA_MAC_DYNCALL, HPPA_MAC_FLOAT_CBIT, HPPA_MAC_FZERO, HPPA_MAC_LEAF, HPPA_MAC_MILLI_RET_VALUE, HPPA_MAC_MILLI_RETADDR, HPPA_MAC_PLAYDOH_BRTARGET, HPPA_MAC_PLAYDOH_BRTMP, HPPA_MAC_PLAYDOH_DEST0, HPPA_MAC_PLAYDOH_DEST1, HPPA_MAC_PLAYDOH_ESC, HPPA_MAC_PLAYDOH_FDEST0, HPPA_MAC_PLAYDOH_FONE, HPPA_MAC_PLAYDOH_FSRC0, HPPA_MAC_PLAYDOH_FSRC1, HPPA_MAC_PLAYDOH_FSRC2, HPPA_MAC_PLAYDOH_GPM, HPPA_MAC_PLAYDOH_GPR, HPPA_MAC_PLAYDOH_LC, HPPA_MAC_PLAYDOH_PDST0, HPPA_MAC_PLAYDOH_PDST1, HPPA_MAC_PLAYDOH_PRED0, HPPA_MAC_PLAYDOH_PRED1, HPPA_MAC_PLAYDOH_PRED_ALL_ROT, HPPA_MAC_PLAYDOH_PRED_ALL_STATIC, HPPA_MAC_PLAYDOH_PRED_FALSE, HPPA_MAC_PLAYDOH_PRED_TRUE, HPPA_MAC_PLAYDOH_PSRC0, HPPA_MAC_PLAYDOH_PV_0, HPPA_MAC_PLAYDOH_PV_1, HPPA_MAC_PLAYDOH_PV_2, HPPA_MAC_PLAYDOH_PV_3, HPPA_MAC_PLAYDOH_PV_4, HPPA_MAC_PLAYDOH_PV_5, HPPA_MAC_PLAYDOH_PV_6, HPPA_MAC_PLAYDOH_PV_7, HPPA_MAC_PLAYDOH_RRB, HPPA_MAC_PLAYDOH_SRC0, HPPA_MAC_PLAYDOH_SRC1, HPPA_MAC_PLAYDOH_SRC2, HPPA_MAC_PLAYDOH_SRC3, HPPA_MAC_RETADDR, HPPA_MAC_SAR, HPPA_MAC_SR3, HPPA_MAC_SR5, HPPA_MAC_SWAP_PTR, HPPA_MAC_TEMPREG, HPPA_MAC_TRUE_SP, and HPPA_MAC_ZERO.
Referenced by M_get_macro_name(), and M_get_macro_name_impact().
char* M_get_opcode_name_hppa (int id)
Definition at line 1796 of file ml_hppa.c.
References LHPPAop_ADDIB_LT_BWD, LHPPAop_ADDIB_LT_FWD, LHPPAop_ADDIL, LHPPAop_BB_0_BWD, LHPPAop_BB_0_FWD, LHPPAop_BB_1_BWD, LHPPAop_BB_1_FWD, LHPPAop_COMB_EQ_BWD, LHPPAop_COMB_EQ_FWD, LHPPAop_COMB_GE_BWD, LHPPAop_COMB_GE_FWD, LHPPAop_COMB_GE_U_BWD, LHPPAop_COMB_GE_U_FWD, LHPPAop_COMB_GT_BWD, LHPPAop_COMB_GT_FWD, LHPPAop_COMB_GT_U_BWD, LHPPAop_COMB_GT_U_FWD, LHPPAop_COMB_LE_BWD, LHPPAop_COMB_LE_FWD, LHPPAop_COMB_LE_U_BWD, LHPPAop_COMB_LE_U_FWD, LHPPAop_COMB_LT_BWD, LHPPAop_COMB_LT_FWD, LHPPAop_COMB_LT_U_BWD, LHPPAop_COMB_LT_U_FWD, LHPPAop_COMB_NE_BWD, LHPPAop_COMB_NE_FWD, LHPPAop_COMIB_EQ_BWD, LHPPAop_COMIB_EQ_FWD, LHPPAop_COMIB_GE_BWD, LHPPAop_COMIB_GE_FWD, LHPPAop_COMIB_GE_U_BWD, LHPPAop_COMIB_GE_U_FWD, LHPPAop_COMIB_GT_BWD, LHPPAop_COMIB_GT_FWD, LHPPAop_COMIB_GT_U_BWD, LHPPAop_COMIB_GT_U_FWD, LHPPAop_COMIB_LE_BWD, LHPPAop_COMIB_LE_FWD, LHPPAop_COMIB_LE_U_BWD, LHPPAop_COMIB_LE_U_FWD, LHPPAop_COMIB_LT_BWD, LHPPAop_COMIB_LT_FWD, LHPPAop_COMIB_LT_U_BWD, LHPPAop_COMIB_LT_U_FWD, LHPPAop_COMIB_NE_BWD, LHPPAop_COMIB_NE_FWD, LHPPAop_DEPI, LHPPAop_EXTRU, LHPPAop_FMPYADD, LHPPAop_FMPYSUB, LHPPAop_JSR_DYNCALL, LHPPAop_LD_C2_SC1, LHPPAop_LD_C2_SC2, LHPPAop_LD_C2_SC3, LHPPAop_LD_C2_SV1, LHPPAop_LD_C_SC1, LHPPAop_LD_C_SC2, LHPPAop_LD_C_SC3, LHPPAop_LD_C_SV1, LHPPAop_LD_F2_SC1, LHPPAop_LD_F2_SC2, LHPPAop_LD_F2_SC3, LHPPAop_LD_F2_SV1, LHPPAop_LD_F_SC1, LHPPAop_LD_F_SC2, LHPPAop_LD_F_SC3, LHPPAop_LD_F_SV1, LHPPAop_LD_I_SC1, LHPPAop_LD_I_SC2, LHPPAop_LD_I_SC3, LHPPAop_LD_I_SV1, LHPPAop_LD_POST_C2_SC1, LHPPAop_LD_POST_C2_SC2, LHPPAop_LD_POST_C2_SC3, LHPPAop_LD_POST_C2_SV1, LHPPAop_LD_POST_C_SC1, LHPPAop_LD_POST_C_SC2, LHPPAop_LD_POST_C_SC3, LHPPAop_LD_POST_C_SV1, LHPPAop_LD_POST_F2_SC1, LHPPAop_LD_POST_F2_SC2, LHPPAop_LD_POST_F2_SC3, LHPPAop_LD_POST_F2_SV1, LHPPAop_LD_POST_F_SC1, LHPPAop_LD_POST_F_SC2, LHPPAop_LD_POST_F_SC3, LHPPAop_LD_POST_F_SV1, LHPPAop_LD_POST_I_SC1, LHPPAop_LD_POST_I_SC2, LHPPAop_LD_POST_I_SC3, LHPPAop_LD_POST_I_SV1, LHPPAop_LD_POST_UC2_SC1, LHPPAop_LD_POST_UC2_SC2, LHPPAop_LD_POST_UC2_SC3, LHPPAop_LD_POST_UC2_SV1, LHPPAop_LD_POST_UC_SC1, LHPPAop_LD_POST_UC_SC2, LHPPAop_LD_POST_UC_SC3, LHPPAop_LD_POST_UC_SV1, LHPPAop_LD_PRE_C2_SC1, LHPPAop_LD_PRE_C2_SC2, LHPPAop_LD_PRE_C2_SC3, LHPPAop_LD_PRE_C2_SV1, LHPPAop_LD_PRE_C_SC1, LHPPAop_LD_PRE_C_SC2, LHPPAop_LD_PRE_C_SC3, LHPPAop_LD_PRE_C_SV1, LHPPAop_LD_PRE_F2_SC1, LHPPAop_LD_PRE_F2_SC2, LHPPAop_LD_PRE_F2_SC3, LHPPAop_LD_PRE_F2_SV1, LHPPAop_LD_PRE_F_SC1, LHPPAop_LD_PRE_F_SC2, LHPPAop_LD_PRE_F_SC3, LHPPAop_LD_PRE_F_SV1, LHPPAop_LD_PRE_I_SC1, LHPPAop_LD_PRE_I_SC2, LHPPAop_LD_PRE_I_SC3, LHPPAop_LD_PRE_I_SV1, LHPPAop_LD_PRE_UC2_SC1, LHPPAop_LD_PRE_UC2_SC2, LHPPAop_LD_PRE_UC2_SC3, LHPPAop_LD_PRE_UC2_SV1, LHPPAop_LD_PRE_UC_SC1, LHPPAop_LD_PRE_UC_SC2, LHPPAop_LD_PRE_UC_SC3, LHPPAop_LD_PRE_UC_SV1, LHPPAop_LD_UC2_SC1, LHPPAop_LD_UC2_SC2, LHPPAop_LD_UC2_SC3, LHPPAop_LD_UC2_SV1, LHPPAop_LD_UC_SC1, LHPPAop_LD_UC_SC2, LHPPAop_LD_UC_SC3, LHPPAop_LD_UC_SV1, LHPPAop_LDIL, LHPPAop_LDO, LHPPAop_MTSP, LHPPAop_PRED_MOV, LHPPAop_VEXTRS, LHPPAop_VSHD, LHPPAop_ZVDEP, LHPPAop_ZVDEPI, PAopcode_ADDIB_LT_BWD, PAopcode_ADDIB_LT_FWD, PAopcode_ADDIL, PAopcode_BB_0_BWD, PAopcode_BB_0_FWD, PAopcode_BB_1_BWD, PAopcode_BB_1_FWD, PAopcode_COMB_EQ_BWD, PAopcode_COMB_EQ_FWD, PAopcode_COMB_GE_BWD, PAopcode_COMB_GE_FWD, PAopcode_COMB_GE_U_BWD, PAopcode_COMB_GE_U_FWD, PAopcode_COMB_GT_BWD, PAopcode_COMB_GT_FWD, PAopcode_COMB_GT_U_BWD, PAopcode_COMB_GT_U_FWD, PAopcode_COMB_LE_BWD, PAopcode_COMB_LE_FWD, PAopcode_COMB_LE_U_BWD, PAopcode_COMB_LE_U_FWD, PAopcode_COMB_LT_BWD, PAopcode_COMB_LT_FWD, PAopcode_COMB_LT_U_BWD, PAopcode_COMB_LT_U_FWD, PAopcode_COMB_NE_BWD, PAopcode_COMB_NE_FWD, PAopcode_COMIB_EQ_BWD, PAopcode_COMIB_EQ_FWD, PAopcode_COMIB_GE_BWD, PAopcode_COMIB_GE_FWD, PAopcode_COMIB_GE_U_BWD, PAopcode_COMIB_GE_U_FWD, PAopcode_COMIB_GT_BWD, PAopcode_COMIB_GT_FWD, PAopcode_COMIB_GT_U_BWD, PAopcode_COMIB_GT_U_FWD, PAopcode_COMIB_LE_BWD, PAopcode_COMIB_LE_FWD, PAopcode_COMIB_LE_U_BWD, PAopcode_COMIB_LE_U_FWD, PAopcode_COMIB_LT_BWD, PAopcode_COMIB_LT_FWD, PAopcode_COMIB_LT_U_BWD, PAopcode_COMIB_LT_U_FWD, PAopcode_COMIB_NE_BWD, PAopcode_COMIB_NE_FWD, PAopcode_DEPI, PAopcode_EXTRU, PAopcode_FMPYADD, PAopcode_FMPYSUB, PAopcode_JSR_DYNCALL, PAopcode_LD_C2_SC1, PAopcode_LD_C2_SC2, PAopcode_LD_C2_SC3, PAopcode_LD_C2_SV1, PAopcode_LD_C_SC1, PAopcode_LD_C_SC2, PAopcode_LD_C_SC3, PAopcode_LD_C_SV1, PAopcode_LD_F2_SC1, PAopcode_LD_F2_SC2, PAopcode_LD_F2_SC3, PAopcode_LD_F2_SV1, PAopcode_LD_F_SC1, PAopcode_LD_F_SC2, PAopcode_LD_F_SC3, PAopcode_LD_F_SV1, PAopcode_LD_I_SC1, PAopcode_LD_I_SC2, PAopcode_LD_I_SC3, PAopcode_LD_I_SV1, PAopcode_LD_POST_C2_SC1, PAopcode_LD_POST_C2_SC2, PAopcode_LD_POST_C2_SC3, PAopcode_LD_POST_C2_SV1, PAopcode_LD_POST_C_SC1, PAopcode_LD_POST_C_SC2, PAopcode_LD_POST_C_SC3, PAopcode_LD_POST_C_SV1, PAopcode_LD_POST_F2_SC1, PAopcode_LD_POST_F2_SC2, PAopcode_LD_POST_F2_SC3, PAopcode_LD_POST_F2_SV1, PAopcode_LD_POST_F_SC1, PAopcode_LD_POST_F_SC2, PAopcode_LD_POST_F_SC3, PAopcode_LD_POST_F_SV1, PAopcode_LD_POST_I_SC1, PAopcode_LD_POST_I_SC2, PAopcode_LD_POST_I_SC3, PAopcode_LD_POST_I_SV1, PAopcode_LD_POST_UC2_SC1, PAopcode_LD_POST_UC2_SC2, PAopcode_LD_POST_UC2_SC3, PAopcode_LD_POST_UC2_SV1, PAopcode_LD_POST_UC_SC1, PAopcode_LD_POST_UC_SC2, PAopcode_LD_POST_UC_SC3, PAopcode_LD_POST_UC_SV1, PAopcode_LD_PRE_C2_SC1, PAopcode_LD_PRE_C2_SC2, PAopcode_LD_PRE_C2_SC3, PAopcode_LD_PRE_C2_SV1, PAopcode_LD_PRE_C_SC1, PAopcode_LD_PRE_C_SC2, PAopcode_LD_PRE_C_SC3, PAopcode_LD_PRE_C_SV1, PAopcode_LD_PRE_F2_SC1, PAopcode_LD_PRE_F2_SC2, PAopcode_LD_PRE_F2_SC3, PAopcode_LD_PRE_F2_SV1, PAopcode_LD_PRE_F_SC1, PAopcode_LD_PRE_F_SC2, PAopcode_LD_PRE_F_SC3, PAopcode_LD_PRE_F_SV1, PAopcode_LD_PRE_I_SC1, PAopcode_LD_PRE_I_SC2, PAopcode_LD_PRE_I_SC3, PAopcode_LD_PRE_I_SV1, PAopcode_LD_PRE_UC2_SC1, PAopcode_LD_PRE_UC2_SC2, PAopcode_LD_PRE_UC2_SC3, PAopcode_LD_PRE_UC2_SV1, PAopcode_LD_PRE_UC_SC1, PAopcode_LD_PRE_UC_SC2, PAopcode_LD_PRE_UC_SC3, PAopcode_LD_PRE_UC_SV1, PAopcode_LD_UC2_SC1, PAopcode_LD_UC2_SC2, PAopcode_LD_UC2_SC3, PAopcode_LD_UC2_SV1, PAopcode_LD_UC_SC1, PAopcode_LD_UC_SC2, PAopcode_LD_UC_SC3, PAopcode_LD_UC_SV1, PAopcode_LDIL, PAopcode_LDO, PAopcode_MTSP, PAopcode_PRED_MOV, PAopcode_VEXTRS, PAopcode_VSHD, PAopcode_ZVDEP, and PAopcode_ZVDEPI.
Referenced by M_get_opcode_name().
int M_hppa_array_align (M_Type type)
Definition at line 398 of file ml_hppa.c.
References _struct_M_Type::align.
Referenced by M_array_align(), and M_impact_array_align().
void M_hppa_array_layout (M_Type type, int * offset)
Definition at line 392 of file ml_hppa.c.
Referenced by M_array_layout(), and M_impact_array_layout().
int M_hppa_array_size (M_Type type, int dim)
Definition at line 404 of file ml_hppa.c.
References _struct_M_Type::align, and _struct_M_Type::size.
Referenced by M_array_size(), and M_impact_array_size().
void M_hppa_bit_char (M_Type type, int n)
Definition at line 175 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_BIT, M_HPPA_SIZE_BIT, M_TYPE_BIT_CHAR, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_char(), and M_impact_bit_char().
void M_hppa_bit_int (M_Type type, int n)
Definition at line 151 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_BIT, M_HPPA_SIZE_BIT, M_TYPE_BIT_INT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_int(), and M_impact_bit_int().
void M_hppa_bit_long (M_Type type, int n)
Definition at line 139 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_BIT, M_HPPA_SIZE_BIT, M_TYPE_BIT_LONG, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_long(), and M_impact_bit_long().
void M_hppa_bit_short (M_Type type, int n)
Definition at line 163 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_BIT, M_HPPA_SIZE_BIT, M_TYPE_BIT_SHORT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_bit_short(), and M_impact_bit_short().
int M_hppa_call_type (M_Type type, M_Type ntype)
Definition at line 294 of file ml_hppa.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type(), M_impact_call_type(), and M_impact_call_type2().
int M_hppa_call_type2 (M_Type type, M_Type ntype)
Definition at line 339 of file ml_hppa.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_call_type2().
void M_hppa_cb_label_name (char * fn, int cb, char * line, int len)
Definition at line 1040 of file ml_hppa.c.
Referenced by M_cb_label_name(), and M_impact_cb_label_name().
int M_hppa_dataflow_macro (int id)
Definition at line 1387 of file ml_hppa.c.
References HPPA_MAC_LAST, HPPA_MAC_PLAYDOH_GPR, M_assert(), M_HP_PA_1_0, M_HP_PA_1_1, M_HP_PA_7100, M_HP_PA_X, M_HP_PLAYDOH_LCODE, M_HP_PLAYDOH_MCODE, and M_model.
Referenced by M_dataflow_macro(), and M_impact_dataflow_macro().
void M_hppa_double (M_Type type, int unsign)
Definition at line 197 of file ml_hppa.c.
References _struct_M_Type::align, M_HPPA_ALIGN_DOUBLE, M_HPPA_SIZE_DOUBLE, M_TYPE_DOUBLE, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_double(), and M_impact_double().
int M_hppa_eval_type (M_Type type, M_Type ntype)
Definition at line 218 of file ml_hppa.c.
References M_double(), M_float(), M_int(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type(), M_impact_eval_type(), and M_impact_eval_type2().
int M_hppa_eval_type2 (M_Type type, M_Type ntype)
Definition at line 252 of file ml_hppa.c.
References M_char(), M_double(), M_float(), M_int(), M_long(), M_pointer(), M_short(), M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BLOCK, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, M_TYPE_VOID, M_void(), _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_eval_type2().
void M_hppa_float (M_Type type, int unsign)
Definition at line 187 of file ml_hppa.c.
References _struct_M_Type::align, M_HPPA_ALIGN_FLOAT, M_HPPA_SIZE_FLOAT, M_TYPE_FLOAT, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_float(), and M_impact_float().
char* M_hppa_fn_label_name (char * label, int(*)(char *is_func_label) is_func)
Definition at line 1119 of file ml_hppa.c.
Referenced by M_fn_label_name().
char* M_hppa_fn_name_from_label (char * label)
Definition at line 1133 of file ml_hppa.c.
Referenced by M_fn_name_from_label().
int M_hppa_fnvar_layout (int n, _M_Type * type, long int * offset, int * mode, int * reg, int * paddr, char ** macro, int * su_sreg, int * su_ereg, int * pcount, int is_st, int purpose)
Definition at line 719 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_DONT_CARE_FNVAR, M_GET_FNVAR, M_HPPA_ALIGN_INT, M_HPPA_ALIGN_MAX, M_HPPA_FLT_BASE, M_HPPA_INT_BASE, M_HPPA_MAX_FNVAR_REG, M_HPPA_SIZE_INT, M_HPPA_SMALL_STRUCT_MAX, M_INDIRECT_THRU_MEMORY, M_INDIRECT_THRU_REGISTER, M_PUT_FNVAR, M_THRU_MEMORY, M_THRU_REGISTER, M_TYPE_CHAR, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, M_TYPE_LONG, M_TYPE_POINTER, M_TYPE_SHORT, M_TYPE_STRUCT, M_TYPE_UNION, MIN_PARAM_SIZE, and _struct_M_Type::size.
Referenced by M_fnvar_layout(), M_hppa_layout_fnvar(), and M_impact_fnvar_layout().
int M_hppa_fragile_macro (int macro_value)
Definition at line 1143 of file ml_hppa.c.
References HPPA_MAC_DP, HPPA_MAC_FZERO, HPPA_MAC_ZERO, M_assert(), M_HP_PA_1_0, M_HP_PA_1_1, M_HP_PA_7100, M_HP_PA_X, M_HP_PLAYDOH_LCODE, M_HP_PLAYDOH_MCODE, and M_model.
Referenced by M_fragile_macro(), and M_impact_fragile_macro().
Set M_hppa_fragile_macro_set ()
Definition at line 1177 of file ml_hppa.c.
References HPPA_MAC_ALLOC, HPPA_MAC_CALLEE_F, HPPA_MAC_CALLEE_I, HPPA_MAC_CONV_LOC, HPPA_MAC_CONV_OFF, HPPA_MAC_DYNCALL, HPPA_MAC_FLOAT_CBIT, HPPA_MAC_LEAF, HPPA_MAC_MILLI_RET_VALUE, HPPA_MAC_MILLI_RETADDR, HPPA_MAC_RETADDR, HPPA_MAC_SAR, HPPA_MAC_SR3, HPPA_MAC_SR5, HPPA_MAC_SWAP_PTR, HPPA_MAC_TEMPREG, HPPA_MAC_TRUE_SP, M_assert(), M_HP_PA_1_0, M_HP_PA_1_1, M_HP_PA_7100, M_HP_PA_X, M_HP_PLAYDOH_LCODE, M_HP_PLAYDOH_MCODE, M_model, Set_add(), and Set_hppa_fragile_macro.
Referenced by M_fragile_macro_set(), and M_impact_fragile_macro_set().
int M_hppa_is_cb_label (char * label, char * fn, int * cb)
Definition at line 1046 of file ml_hppa.c.
Referenced by M_impact_is_cb_label(), and M_is_cb_label().
int M_hppa_is_jumptbl_label (char * label, char * fn, int * tbl_id)
Definition at line 1059 of file ml_hppa.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_impact_is_jumptbl_label(), and M_is_jumptbl_label().
void M_hppa_jumptbl_label_name (char * fn, int tbl_id, char * line, int len)
Definition at line 1052 of file ml_hppa.c.
References M_JUMPTBL_BASE_NAME.
Referenced by M_impact_jumptbl_label_name(), and M_jumptbl_label_name().
int M_hppa_layout_fnvar (List param_list, char ** base_macro, int * pcount, int purpose)
Definition at line 667 of file ml_hppa.c.
References List_next(), List_size(), List_start(), M_hppa_fnvar_layout(), _struct_M_Param::mode, mode, _struct_M_Param::mtype, _struct_M_Param::offset, _struct_M_Param::paddr, _struct_M_Param::reg, _struct_M_Param::su_ereg, and _struct_M_Param::su_sreg.
Referenced by M_impact_layout_fnvar(), and M_layout_fnvar().
int M_hppa_lvar_layout (int n, _M_Type * type, long int * offset, char ** base_macro)
Definition at line 990 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_MAX, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and _struct_M_Type::size.
Referenced by M_impact_lvar_layout(), and M_lvar_layout().
int M_hppa_no_short_int (void)
Definition at line 1034 of file ml_hppa.c.
References M_HPPA_SIZE_INT, and M_HPPA_SIZE_SHORT.
Referenced by M_impact_no_short_int(), and M_no_short_int().
void M_hppa_pointer (M_Type type)
Definition at line 207 of file ml_hppa.c.
References _struct_M_Type::align, M_HPPA_ALIGN_POINTER, M_HPPA_SIZE_POINTER, M_TYPE_POINTER, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_pointer(), and M_pointer().
int M_hppa_return_register (int type, int purpose)
Definition at line 1098 of file ml_hppa.c.
References M_HPPA_RET_F, M_HPPA_RET_I32, M_TYPE_DOUBLE, M_TYPE_FLOAT, M_TYPE_INT, and M_TYPE_LONG.
Referenced by M_impact_return_register(), and M_return_register().
int M_hppa_struct_align (int n, _M_Type * type)
Definition at line 588 of file ml_hppa.c.
References M_HPPA_ALIGN_CHAR.
Referenced by M_impact_struct_align(), and M_struct_align().
void M_hppa_struct_layout (int n, _M_Type * type, int * base, int * bit_offset)
Definition at line 484 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_SIZE_CHAR, M_HPPA_SIZE_INT, M_HPPA_SIZE_LONG, M_HPPA_SIZE_SHORT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, M_TYPE_BIT_SHORT, and _struct_M_Type::type.
Referenced by M_impact_struct_layout(), and M_struct_layout().
int M_hppa_struct_size (int n, _M_Type * type, int struct_align)
Definition at line 607 of file ml_hppa.c.
References _struct_M_Type::align, M_assert(), M_HPPA_ALIGN_CHAR, M_HPPA_ALIGN_LONG, M_HPPA_ALIGN_SHORT, M_HPPA_SIZE_INT, M_TYPE_BIT_CHAR, M_TYPE_BIT_LONG, and M_TYPE_BIT_SHORT.
Referenced by M_impact_struct_size(), and M_struct_size().
int M_hppa_structure_pointer (int purpose)
Definition at line 1092 of file ml_hppa.c.
References M_HPPA_RET_ST.
Referenced by M_impact_structure_pointer(), and M_structure_pointer().
int M_hppa_subroutine_call (int opc)
Definition at line 1409 of file ml_hppa.c.
References M_assert(), M_HP_PA_1_0, M_HP_PA_1_1, M_HP_PA_7100, M_HP_PA_X, M_HP_PLAYDOH_LCODE, M_HP_PLAYDOH_MCODE, and M_model.
Referenced by M_impact_subroutine_call(), and M_subroutine_call().
int M_hppa_union_align (int n, _M_Type * type)
Definition at line 430 of file ml_hppa.c.
References M_HPPA_ALIGN_CHAR.
Referenced by M_impact_union_align(), and M_union_align().
void M_hppa_union_layout (int n, _M_Type * type, int * offset, int * bit_offset)
Definition at line 419 of file ml_hppa.c.
Referenced by M_impact_union_layout(), and M_union_layout().
int M_hppa_union_size (int n, _M_Type * type)
Definition at line 450 of file ml_hppa.c.
References _struct_M_Type::align, M_HPPA_ALIGN_CHAR, and _struct_M_Type::size.
Referenced by M_impact_union_size(), and M_union_size().
void M_hppa_void (M_Type type)
Definition at line 129 of file ml_hppa.c.
References _struct_M_Type::align, M_HPPA_ALIGN_VOID, M_HPPA_SIZE_VOID, M_TYPE_VOID, _struct_M_Type::nbits, _struct_M_Type::size, _struct_M_Type::type, and _struct_M_Type::unsign.
Referenced by M_impact_void(), and M_void().
int M_is_stack_operand_hppa (L_Operand * operand)
Definition at line 2315 of file ml_hppa.c.
References HPPA_MAC_TRUE_SP.
Referenced by M_is_stack_operand(), and M_is_stack_operand_impact().
int M_is_unsafe_macro_hppa (L_Operand * operand)
Definition at line 2332 of file ml_hppa.c.
References HPPA_MAC_FLOAT_CBIT, HPPA_MAC_FZERO, HPPA_MAC_SAR, HPPA_MAC_SR3, and HPPA_MAC_SR5.
Referenced by M_is_unsafe_macro(), and M_is_unsafe_macro_impact().
int M_num_oper_required_for_hppa (L_Oper * oper, char * name)
Definition at line 2163 of file ml_hppa.c.
References has_label_operand, indexed_memory_op, long_neg_int_inc, long_pos_int_inc, non_zero_offset, register_inc, and short_int_inc.
Referenced by M_num_oper_required_for(), and M_num_oper_required_for_impact().
int M_num_registers_hppa (int ctype)
Definition at line 2492 of file ml_hppa.c.
References M_assert(), M_HP_PA_1_0, M_HP_PA_1_1, M_HP_PA_7100, M_HP_PA_X, and M_model.
Referenced by M_num_registers().
int M_oper_supported_in_arch_hppa (int opc)
Definition at line 2122 of file ml_hppa.c.
References M_HP_PA_X, and M_model.
Referenced by M_oper_supported_in_arch(), and M_oper_supported_in_arch_impact().
int M_operand_type_hppa (L_Operand * operand)
Definition at line 2351 of file ml_hppa.c.
References FIELD_11, FIELD_14, FIELD_5, M_assert(), MDES_OPERAND_Label, MDES_OPERAND_Lit11, MDES_OPERAND_Lit14, MDES_OPERAND_Lit21, MDES_OPERAND_Lit5, MDES_OPERAND_NULL, MDES_OPERAND_REG, and NULL.
Referenced by M_mdes_operand_type().
Variable Documentation
Set Set_hppa_fragile_macro = NULL
Definition at line 106 of file ml_hppa.c.
Referenced by M_hppa_fragile_macro_set().