mia_compare.c File Reference
#include <config.h>
#include `mia_internal.h`
Defines
#define VERBOSE
Functions
static L_Oper * find_add_for_compare (L_Oper *compare, int operand_num)
static int Switch_add_compare_order_if_needed (L_Cb *cb, L_Oper *add, L_Oper *compare, int compare_operand_num)
static void Change_lte_to_lt (L_Oper *compare)
static void Change_gte_to_gt (L_Oper *compare)
int Mopti_loop_compare_height_reduction (L_Func *fn)
int Mopti_compare_height_reduction (L_Func *fn, L_Cb *cb, L_Loop *loop, int loop_n_cb, int *loop_cb)
Define Documentation
#define VERBOSE
Definition at line 66 of file mia_compare.c.
Function Documentation
static void Change_gte_to_gt (L_Oper * compare) [static]
Definition at line 674 of file mia_compare.c.
References TC_CMP_OP_GE, TC_CMP_OP_GEU, TC_CMP_OP_GT, TC_CMP_OP_GTU, TC_GET_CMP_OP, and TC_SET_CMP_OP.
Referenced by Mopti_compare_height_reduction().
static void Change_lte_to_lt (L_Oper * compare) [static]
Definition at line 641 of file mia_compare.c.
References TC_CMP_OP_LE, TC_CMP_OP_LEU, TC_CMP_OP_LT, TC_CMP_OP_LTU, TC_GET_CMP_OP, and TC_SET_CMP_OP.
Referenced by Mopti_compare_height_reduction().
static L_Oper * find_add_for_compare (L_Oper * compare, int operand_num) [static]
Definition at line 529 of file mia_compare.c.
References TAHOEop_ADDS.
Referenced by Mopti_compare_height_reduction().
int Mopti_compare_height_reduction (L_Func * fn, L_Cb * cb, L_Loop * loop, int loop_n_cb, int * loop_cb)
Definition at line 181 of file mia_compare.c.
References Change_gte_to_gt(), Change_lte_to_lt(), find_add_for_compare(), LT_is_R0_operand, SIMM_8, Switch_add_compare_order_if_needed(), and TAHOEop_ADDS.
Referenced by Mopti_loop_compare_height_reduction(), and Mopti_perform_optimizations_tahoe().
int Mopti_loop_compare_height_reduction (L_Func * fn)
Definition at line 94 of file mia_compare.c.
References Mopti_compare_height_reduction().
Referenced by Mopti_perform_optimizations_tahoe().
static int Switch_add_compare_order_if_needed (L_Cb * cb, L_Oper * add, L_Oper * compare, int compare_operand_num) [static]
Definition at line 587 of file mia_compare.c.
Referenced by Mopti_compare_height_reduction().