mia_epi_merge.c File Reference
#include <config.h>
#include `mia_internal.h`
Defines
#define MERGE_PREDICATED_RET_BR 1
#define EPILOGUE_MERGE_THRESHOLD 2.0
#define EPILOGUE_MERGE_MIN_OPERS 2
Functions
int O_is_caller_save_predicate (L_Operand *pred)
static L_Cb * Find_epilogue_cb (L_Func *fn, int *size_of_cb)
static int Count_opers_in_merge_space (L_Cb *cb, L_Oper *branch_oper)
static void Rev_copy_prop_return_value (L_Func *fn, Set modified_cbs)
void Mopti_epilogue_merge (L_Func *fn)
void Mopti_epilogue_cleanup (L_Func *fn)
Define Documentation
#define EPILOGUE_MERGE_MIN_OPERS 2
Definition at line 73 of file mia_epi_merge.c.
Referenced by Mopti_epilogue_merge().
#define EPILOGUE_MERGE_THRESHOLD 2.0
Definition at line 72 of file mia_epi_merge.c.
Referenced by Mopti_epilogue_merge().
#define MERGE_PREDICATED_RET_BR 1
Definition at line 68 of file mia_epi_merge.c.
Function Documentation
static int Count_opers_in_merge_space (L_Cb * cb, L_Oper * branch_oper) [static]
Definition at line 122 of file mia_epi_merge.c.
References LT_is_call_br, LT_is_cmp_op, and LT_is_cond_br.
Referenced by Mopti_epilogue_merge().
static L_Cb* Find_epilogue_cb (L_Func * fn, int * size_of_cb) [static]
Definition at line 76 of file mia_epi_merge.c.
References LT_is_non_instr.
Referenced by Mopti_epilogue_merge().
void Mopti_epilogue_cleanup (L_Func * fn)
Definition at line 447 of file mia_epi_merge.c.
void Mopti_epilogue_merge (L_Func * fn)
Definition at line 228 of file mia_epi_merge.c.
References Count_opers_in_merge_space(), EPILOGUE_MERGE_MIN_OPERS, EPILOGUE_MERGE_THRESHOLD, Find_epilogue_cb(), LT_is_non_instr, O_is_caller_save_predicate(), Rev_copy_prop_return_value(), and TAHOE_PRED_BLK_REG.
int O_is_caller_save_predicate (L_Operand * pred)
static void Rev_copy_prop_return_value (L_Func * fn, Set modified_cbs) [static]
Definition at line 156 of file mia_epi_merge.c.
Referenced by Mopti_epilogue_merge().