mia_opti.c File Reference
#include <config.h>
#include `mia_internal.h`
#include <Lcode/l_disjvreg.h>
Defines
#define Mopti_imax_num_iterations (4)
#define Mopti_omax_num_iterations (4)
#define MAX_NUM_GLOB_ITERATION 10
#define MAX_RD 16
#define TEST_GLOB_COPY_PROP
Functions
static void Mopti_init ()
static void Mopti_deinit ()
static int M_global_code_optimization (L_Func *fn)
static int M_global_common_subexpression (L_Cb *cbA, L_Cb *cbB, int move_flags)
static int M_global_copy_propagation (L_Cb *cbA, L_Cb *cbB)
static int M_local_add_regrouping (L_Cb *cb)
static int Mopti_global_dead_code_optimization (L_Func *fn)
static int M_local_redmov_removal (L_Cb *cb)
static int M_local_cmp_copy_propagation (L_Cb *cb)
static int M_local_cmp_rev_copy_propagation (L_Cb *cb)
static int M_global_cmp_copy_propagation (L_Cb *cbA, L_Cb *cbB)
int M_local_constant_folding (L_Cb *cb)
int M_local_copy_propagation (L_Cb *cb, int use_dem)
int M_local_rev_copy_propagation (L_Cb *cb, int use_dem)
int M_local_constant_propagation (L_Cb *cb)
void L_read_parm_mopti (Parm_Parse_Info *ppi)
void Mopti_perform_optimizations_tahoe (L_Func *fn)
void Mopti_phase2_optimizations (L_Func *fn)
static int Mopti_redundant_ext_rev_set (L_Func *fn, L_Oper *oper, Set rd_set)
int Mopti_global_sxt_elimination (L_Func *fn)
void Mopti_debug (char *fmt,...)
Variables
static int Mopti_init_performed = 0
int Mopti_print_stats = 0
static int Mopti_do_local_opti = 1
static int Mopti_do_local_common_subs = 1
static int Mopti_do_local_copy_prop = 1
static int Mopti_do_local_rev_copy_prop = 1
static int Mopti_do_local_const_prop = 1
static int Mopti_do_local_const_fold = 1
static int Mopti_do_local_add_regrouping = 0
static int Mopti_do_dead_code = 1
static int Mopti_do_global_opti = 1
static int Mopti_do_global_common_subs = 1
static int Mopti_do_global_copy_prop = 1
static int Mopti_do_coalescing = 1
int Mopti_do_compare_height_reduction = 0
int Mopti_constant_preloading = 0
int Mopti_shift_add_merge = 0
int Mopti_do_epilogue_merge = 0
int Mopti2_redundant_memory_ops = 0
int Mopti_debug_messages = 0
Define Documentation
#define MAX_NUM_GLOB_ITERATION 10
Definition at line 1306 of file mia_opti.c.
Referenced by Mopti_global_dead_code_optimization().
#define MAX_RD 16
Definition at line 1356 of file mia_opti.c.
Referenced by Mopti_global_sxt_elimination().
#define Mopti_imax_num_iterations (4)
Definition at line 91 of file mia_opti.c.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
#define Mopti_omax_num_iterations (4)
Definition at line 92 of file mia_opti.c.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
#define TEST_GLOB_COPY_PROP
Referenced by M_global_copy_propagation().
Function Documentation
void L_read_parm_mopti (Parm_Parse_Info * ppi)
Definition at line 149 of file mia_opti.c.
References Mopti2_redundant_memory_ops, Mopti_constant_preloading, Mopti_debug_messages, Mopti_do_coalescing, Mopti_do_compare_height_reduction, Mopti_do_dead_code, Mopti_do_epilogue_merge, Mopti_do_global_common_subs, Mopti_do_global_copy_prop, Mopti_do_local_add_regrouping, Mopti_do_local_common_subs, Mopti_do_local_const_fold, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_opti, Mopti_do_local_rev_copy_prop, Mopti_print_stats, and Mopti_shift_add_merge.
static int M_global_cmp_copy_propagation (L_Cb * cbA, L_Cb * cbB) [static]
Definition at line 1569 of file mia_opti.c.
References L_global_no_defs_between(), L_global_same_def_reachs(), and TAHOE_MAC_ZERO.
static int M_global_code_optimization (L_Func * fn) [static]
Definition at line 522 of file mia_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, M_global_common_subexpression(), M_global_copy_propagation(), Mopti_do_global_common_subs, Mopti_do_global_copy_prop, and Mopti_print_stats.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
static int M_global_common_subexpression (L_Cb * cbA, L_Cb * cbB, int move_flags) [static]
Definition at line 965 of file mia_opti.c.
References L_all_dest_operand_global_no_defs_between(), L_all_src_operand_global_same_def_reachs(), L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_compatible_opcodes(), L_convert_to_move(), L_global_no_danger(), L_move_from_ctype(), Lopti_inter_region_global_common_sub_elim_wgt, MOD, and TAHOEop_MOV_GR.
Referenced by M_global_code_optimization().
static int M_global_copy_propagation (L_Cb * cbA, L_Cb * cbB) [static]
Definition at line 1168 of file mia_opti.c.
References L_global_no_danger(), L_global_no_danger_to_boundary(), L_global_no_defs_between(), L_global_same_def_reachs(), Lopti_inter_region_global_copy_prop_wgt, TAHOEop_MOVL, and TEST_GLOB_COPY_PROP.
Referenced by M_global_code_optimization().
static int M_local_add_regrouping (L_Cb * cb) [static]
Definition at line 581 of file mia_opti.c.
References L_no_other_use_in_cb_after().
Referenced by Mopti_perform_optimizations_tahoe().
static int M_local_cmp_copy_propagation (L_Cb * cb) [static]
Definition at line 1624 of file mia_opti.c.
References TAHOE_MAC_ZERO.
static int M_local_cmp_rev_copy_propagation (L_Cb * cb) [static]
Definition at line 1680 of file mia_opti.c.
References L_can_change_all_later_uses_with(), L_not_live_at_cb_end(), and TAHOE_MAC_ZERO.
int M_local_constant_folding (L_Cb * cb)
Definition at line 1919 of file mia_opti.c.
References SIMM_14, and TAHOEop_ADDS.
Referenced by Mopti_phase2_optimizations().
int M_local_constant_propagation (L_Cb * cb)
Definition at line 2352 of file mia_opti.c.
References ERR, and M_num_oper_required_for().
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int M_local_copy_propagation (L_Cb * cb, int use_dem)
Definition at line 2000 of file mia_opti.c.
References L_extension_compatible_ctype(), L_redundant_extension_fwd(), and M_subroutine_call().
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
static int M_local_redmov_removal (L_Cb * cb) [static]
Definition at line 1138 of file mia_opti.c.
References TAHOEop_MOVL.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int M_local_rev_copy_propagation (L_Cb * cb, int use_dem)
Definition at line 2130 of file mia_opti.c.
References L_can_change_all_later_uses_with(), L_can_change_all_uses_between(), L_not_live_at_cb_end(), L_redundant_extension_rev(), and L_single_use_of().
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
void Mopti_debug (char * fmt, ...)
Definition at line 2428 of file mia_opti.c.
static void Mopti_deinit () [static]
Definition at line 195 of file mia_opti.c.
References L_alloc_danger_ext, MOD, and Mopti_init_performed.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
static int Mopti_global_dead_code_optimization (L_Func * fn) [static]
Definition at line 1309 of file mia_opti.c.
References L_global_dead_code_removal(), Lopti_cnt_global_dead_code_rem, Lopti_cnt_global_opti, Lopti_debug_global_opti, Lopti_do_global_dead_code_rem, Lopti_do_global_opti, and MAX_NUM_GLOB_ITERATION.
int Mopti_global_sxt_elimination (L_Func * fn)
Definition at line 1384 of file mia_opti.c.
References LT_is_R0_operand, MAX_RD, Mopti_redundant_ext_rev_set(), TAHOEop_LD1, TAHOEop_LD2, TAHOEop_LD4, TAHOEop_SXT1, TAHOEop_SXT2, and TAHOEop_SXT4.
Referenced by Mopti_perform_optimizations_tahoe().
static void Mopti_init () [static]
Definition at line 184 of file mia_opti.c.
References L_alloc_danger_ext, MOD, and Mopti_init_performed.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
void Mopti_perform_optimizations_tahoe (L_Func * fn)
Definition at line 204 of file mia_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_compute_danger_info(), L_delete_all_danger_ext(), L_local_common_subexpression(), L_local_dead_code_removal(), L_rename_coalesce_disjoint_virtual_registers(), M_global_code_optimization(), M_local_add_regrouping(), M_local_constant_propagation(), M_local_copy_propagation(), M_local_redmov_removal(), M_local_rev_copy_propagation(), MOD, Mopti_compare_height_reduction(), Mopti_deinit(), Mopti_do_coalescing, Mopti_do_compare_height_reduction, Mopti_do_global_opti, Mopti_do_local_add_regrouping, Mopti_do_local_common_subs, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_opti, Mopti_do_local_rev_copy_prop, Mopti_global_sxt_elimination(), Mopti_imax_num_iterations, Mopti_init(), Mopti_init_performed, Mopti_loop_compare_height_reduction(), Mopti_omax_num_iterations, and Mopti_print_stats.
void Mopti_phase2_optimizations (L_Func * fn)
Definition at line 395 of file mia_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_compute_danger_info(), L_delete_all_danger_ext(), L_local_common_subexpression(), M_global_code_optimization(), M_local_constant_folding(), M_local_constant_propagation(), M_local_copy_propagation(), M_local_redmov_removal(), M_local_rev_copy_propagation(), MOD, Mopti_debug_messages, Mopti_deinit(), Mopti_do_global_opti, Mopti_do_local_common_subs, Mopti_do_local_const_fold, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_rev_copy_prop, Mopti_imax_num_iterations, Mopti_init(), Mopti_init_performed, Mopti_omax_num_iterations, and Mopti_print_stats.
static int Mopti_redundant_ext_rev_set (L_Func * fn, L_Oper * oper, Set rd_set) [static]
Definition at line 1360 of file mia_opti.c.
References L_redundant_extension_rev().
Referenced by Mopti_global_sxt_elimination().
Variable Documentation
int Mopti2_redundant_memory_ops = 0
Definition at line 145 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_constant_preloading = 0
Definition at line 141 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_debug_messages = 0
Definition at line 146 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_phase2_optimizations().
int Mopti_do_coalescing = 1 [static]
Definition at line 138 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations_tahoe().
int Mopti_do_compare_height_reduction = 0
Definition at line 140 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations_tahoe().
int Mopti_do_dead_code = 1 [static]
Definition at line 131 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_do_epilogue_merge = 0
Definition at line 143 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_do_global_common_subs = 1 [static]
Definition at line 135 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and M_global_code_optimization().
int Mopti_do_global_copy_prop = 1 [static]
Definition at line 136 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and M_global_code_optimization().
int Mopti_do_global_opti = 1 [static]
Definition at line 133 of file mia_opti.c.
Referenced by Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_do_local_add_regrouping = 0 [static]
Definition at line 130 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations_tahoe().
int Mopti_do_local_common_subs = 1 [static]
Definition at line 125 of file mia_opti.c.
Referenced by L_read_parm_mopti(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_do_local_const_fold = 1 [static]
Definition at line 129 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_phase2_optimizations().
int Mopti_do_local_const_prop = 1 [static]
Definition at line 128 of file mia_opti.c.
Referenced by L_read_parm_mopti(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_do_local_copy_prop = 1 [static]
Definition at line 126 of file mia_opti.c.
Referenced by L_read_parm_mopti(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_do_local_opti = 1 [static]
Definition at line 123 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations_tahoe().
int Mopti_do_local_rev_copy_prop = 1 [static]
Definition at line 127 of file mia_opti.c.
Referenced by L_read_parm_mopti(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_init_performed = 0 [static]
Definition at line 116 of file mia_opti.c.
Referenced by Mopti_deinit(), Mopti_init(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_print_stats = 0
Definition at line 121 of file mia_opti.c.
Referenced by L_read_parm_mopti(), M_global_code_optimization(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_shift_add_merge = 0
Definition at line 142 of file mia_opti.c.
Referenced by L_read_parm_mopti().