mia_opti.h File Reference
#include <config.h>
Functions
void L_read_parm_mopti (Parm_Parse_Info *ppi)
void Mopti_perform_optimizations_tahoe (L_Func *fn)
void Mopti_phase2_optimizations (L_Func *fn)
int L_no_other_use_in_cb_after (L_Cb *cb, L_Operand *operand, L_Oper *after_oper, L_Oper *except_oper)
int L_no_other_def_use_in_cb (L_Cb *cb, L_Operand *operand, L_Oper *except1, L_Oper *except2, L_Oper *except3)
void Mopti_convert_ldf_to_ldi (L_Func *fn)
int Mopti_global_sxt_elimination (L_Func *fn)
void Mopti_epilogue_merge (L_Func *fn)
void Mopti_epilogue_cleanup (L_Func *fn)
int Mopti_branch_target_expansion (L_Func *fn)
void Mia_post_increment_conversion (L_Func *fn, int ld, int st)
void Mia_softpipe_post_increment_conversion (L_Func *fn, int ld, int st)
void Mopti_tahoe_reductions (L_Func *fn)
void Mopti_shladd (L_Func *fn)
int M_local_shladdp4 (L_Cb *cb, int *reaching_df_done)
int M_local_constant_folding (L_Cb *cb)
void Mopti_constant_generation (L_Func *fn)
Variables
int Mopti_constant_preloading
int Mopti_shift_add_merge
int Mopti_do_epilogue_merge
int Mopti_print_stats
int Mopti_do_predicate_opti
int Mopti_do_opp_cond_combining
int Mopti_do_and_cmp_promotion
int Mopti_do_DeMorgan_combining
int Mopti_do_redundant_compare_removal
int Mopti_do_remove_decidable_compares
int Mopti_do_pred_init_combining
int Mopti_do_dead_pred_def_removal
int Mopti_do_pred_copy_removal
int Mopti_do_sp_removal
int Mopti2_redundant_memory_ops
int Mopti_debug_messages
Function Documentation
int L_no_other_def_use_in_cb (L_Cb * cb, L_Operand * operand, L_Oper * except1, L_Oper * except2, L_Oper * except3)
Referenced by Mia_cb_post_increment().
int L_no_other_use_in_cb_after (L_Cb * cb, L_Operand * operand, L_Oper * after_oper, L_Oper * except_oper)
Referenced by M_local_add_regrouping().
void L_read_parm_mopti (Parm_Parse_Info * ppi)
Definition at line 149 of file mia_opti.c.
References Mopti2_redundant_memory_ops, Mopti_constant_preloading, Mopti_debug_messages, Mopti_do_coalescing, Mopti_do_compare_height_reduction, Mopti_do_dead_code, Mopti_do_epilogue_merge, Mopti_do_global_common_subs, Mopti_do_global_copy_prop, Mopti_do_local_add_regrouping, Mopti_do_local_common_subs, Mopti_do_local_const_fold, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_opti, Mopti_do_local_rev_copy_prop, Mopti_print_stats, and Mopti_shift_add_merge.
int M_local_constant_folding (L_Cb * cb)
int M_local_shladdp4 (L_Cb * cb, int * reaching_df_done)
void Mia_post_increment_conversion (L_Func * fn, int ld, int st)
Definition at line 90 of file mia_post_inc.c.
References Mia_cb_post_increment().
void Mia_softpipe_post_increment_conversion (L_Func * fn, int ld, int st)
Definition at line 117 of file mia_post_inc.c.
References Mia_cb_post_increment().
int Mopti_branch_target_expansion (L_Func * fn)
Definition at line 75 of file mia_jump_opti.c.
References L_expand_flow(), LOPTI_EXPAND_ALLOW_FALLTHRU, and LOPTI_EXPAND_ALLOW_UNCOND.
void Mopti_constant_generation (L_Func * fn)
Definition at line 412 of file mia_lp_prel.c.
References Lconst_max_loop_size_for_preload, Lconst_max_loop_size_with_nested_loops, Lconst_min_preload_weight, MAX_LOOP_NESTING, MIN_LOOP_ITER_FOR_PRELOAD, and preload_loop().
void Mopti_convert_ldf_to_ldi (L_Func * fn)
void Mopti_epilogue_cleanup (L_Func * fn)
Definition at line 447 of file mia_epi_merge.c.
void Mopti_epilogue_merge (L_Func * fn)
Definition at line 228 of file mia_epi_merge.c.
References Count_opers_in_merge_space(), EPILOGUE_MERGE_MIN_OPERS, EPILOGUE_MERGE_THRESHOLD, Find_epilogue_cb(), LT_is_non_instr, O_is_caller_save_predicate(), Rev_copy_prop_return_value(), and TAHOE_PRED_BLK_REG.
int Mopti_global_sxt_elimination (L_Func * fn)
Definition at line 1384 of file mia_opti.c.
References LT_is_R0_operand, MAX_RD, Mopti_redundant_ext_rev_set(), TAHOEop_LD1, TAHOEop_LD2, TAHOEop_LD4, TAHOEop_SXT1, TAHOEop_SXT2, and TAHOEop_SXT4.
Referenced by Mopti_perform_optimizations_tahoe().
void Mopti_perform_optimizations_tahoe (L_Func * fn)
Definition at line 204 of file mia_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_compute_danger_info(), L_delete_all_danger_ext(), L_local_common_subexpression(), L_local_dead_code_removal(), L_rename_coalesce_disjoint_virtual_registers(), M_global_code_optimization(), M_local_add_regrouping(), M_local_constant_propagation(), M_local_copy_propagation(), M_local_redmov_removal(), M_local_rev_copy_propagation(), MOD, Mopti_compare_height_reduction(), Mopti_deinit(), Mopti_do_coalescing, Mopti_do_compare_height_reduction, Mopti_do_global_opti, Mopti_do_local_add_regrouping, Mopti_do_local_common_subs, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_opti, Mopti_do_local_rev_copy_prop, Mopti_global_sxt_elimination(), Mopti_imax_num_iterations, Mopti_init(), Mopti_init_performed, Mopti_loop_compare_height_reduction(), Mopti_omax_num_iterations, and Mopti_print_stats.
void Mopti_phase2_optimizations (L_Func * fn)
Definition at line 395 of file mia_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_compute_danger_info(), L_delete_all_danger_ext(), L_local_common_subexpression(), M_global_code_optimization(), M_local_constant_folding(), M_local_constant_propagation(), M_local_copy_propagation(), M_local_redmov_removal(), M_local_rev_copy_propagation(), MOD, Mopti_debug_messages, Mopti_deinit(), Mopti_do_global_opti, Mopti_do_local_common_subs, Mopti_do_local_const_fold, Mopti_do_local_const_prop, Mopti_do_local_copy_prop, Mopti_do_local_rev_copy_prop, Mopti_imax_num_iterations, Mopti_init(), Mopti_init_performed, Mopti_omax_num_iterations, and Mopti_print_stats.
void Mopti_shladd (L_Func * fn)
Definition at line 206 of file mia_shladd.c.
References L_alloc_danger_ext, L_compute_danger_info(), L_delete_all_danger_ext(), M_global_shift_add_merge(), M_local_shift_add_merge(), and MOD.
void Mopti_tahoe_reductions (L_Func * fn)
Variable Documentation
int Mopti2_redundant_memory_ops
Definition at line 145 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_constant_preloading
Definition at line 141 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_debug_messages
Definition at line 146 of file mia_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_phase2_optimizations().
int Mopti_do_and_cmp_promotion
int Mopti_do_dead_pred_def_removal
int Mopti_do_DeMorgan_combining
int Mopti_do_epilogue_merge
Definition at line 143 of file mia_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_do_opp_cond_combining
int Mopti_do_pred_copy_removal
int Mopti_do_pred_init_combining
int Mopti_do_predicate_opti
int Mopti_do_redundant_compare_removal
int Mopti_do_remove_decidable_compares
int Mopti_do_sp_removal
int Mopti_print_stats
Definition at line 121 of file mia_opti.c.
Referenced by L_read_parm_mopti(), M_global_code_optimization(), Mopti_perform_optimizations_tahoe(), and Mopti_phase2_optimizations().
int Mopti_shift_add_merge
Definition at line 142 of file mia_opti.c.
Referenced by L_read_parm_mopti().