mia_shladd.c File Reference
#include <config.h>
#include `mia_internal.h`
Functions
static int M_local_shift_add_merge (L_Cb *cb)
static int M_global_shift_add_merge (L_Cb *cbA, L_Cb *cbB)
static int M_does_operand_contain_label_addr (L_Oper *oper, L_Operand *operand, int *reaching_df_done)
void Mopti_shladd (L_Func *fn)
Function Documentation
static int M_does_operand_contain_label_addr (L_Oper * oper, L_Operand * operand, int * reaching_df_done) [static]
Definition at line 75 of file mia_shladd.c.
References TAHOEop_MOVL.
static int M_global_shift_add_merge (L_Cb * cbA, L_Cb * cbB) [static]
Definition at line 313 of file mia_shladd.c.
References L_global_no_danger(), L_global_no_defs_between(), L_global_same_def_reachs(), LT_is_R0_operand, TAHOEop_ADD, and TAHOEop_SHLADD.
Referenced by Mopti_shladd().
static int M_local_shift_add_merge (L_Cb * cb) [static]
Definition at line 242 of file mia_shladd.c.
References LT_is_R0_operand, TAHOEop_ADD, and TAHOEop_SHLADD.
Referenced by Mopti_shladd().
void Mopti_shladd (L_Func * fn)
Definition at line 206 of file mia_shladd.c.
References L_alloc_danger_ext, L_compute_danger_info(), L_delete_all_danger_ext(), M_global_shift_add_merge(), M_local_shift_add_merge(), and MOD.