mia_internal.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <Lcode/l_opti.h>
#include <Lcode/ltahoe_op_query.h>
#include <Lcode/ltahoe_completers.h>
#include <machine/m_tahoe.h>
#include `mia_opti.h`
#include <Lcode/l_opti_predicates.h>
Defines
#define MOD if (Mopti_debug_messages) Mopti_debug
#define Ltahoe_new_int_reg()
#define Ltahoe_new_pred_reg(ptype)
#define Ltahoe_copy_or_new(cop, opd)
#define Ltahoe_true_pred(ptype)
#define Ltahoe_IMAC(mac)
#define Ltahoe_PMAC(mac)
#define Ltahoe_FMAC(mac)
#define Ltahoe_DMAC(mac)
#define Ltahoe_BMAC(mac)
Functions
void Mopti_debug (char *fmt,...)
int Mopti_loop_compare_height_reduction (L_Func *fn)
int Mopti_compare_height_reduction (L_Func *fn, L_Cb *cb, L_Loop *loop, int loop_n_cb, int *loop_cb)
Define Documentation
#define Ltahoe_BMAC(mac)
Value:
L_new_macro_operand (TAHOE_MAC_ ## mac, \
                                              L_CTYPE_BTR, 0)
Definition at line 107 of file mia_internal.h.
#define Ltahoe_copy_or_new(cop, opd)
Value:
(cop) = ((opd) == NULL) ? \
                                            Ltahoe_new_int_reg() : \
                                            L_copy_operand ((opd))
Definition at line 89 of file mia_internal.h.
#define Ltahoe_DMAC(mac)
Value:
L_new_macro_operand (TAHOE_MAC_ ## mac, \
                                              L_CTYPE_DOUBLE, 0)
Definition at line 105 of file mia_internal.h.
#define Ltahoe_FMAC(mac)
Value:
L_new_macro_operand (TAHOE_MAC_ ## mac, \
                                              L_CTYPE_DOUBLE, 0)
Definition at line 103 of file mia_internal.h.
#define Ltahoe_IMAC(mac)
Value:
L_new_macro_operand (TAHOE_MAC_ ## mac, \
                                              L_CTYPE_LLONG, 0)
Definition at line 99 of file mia_internal.h.
#define Ltahoe_new_int_reg()
Value:
L_new_register_operand (++(L_fn->max_reg_id), \
                                               L_CTYPE_LLONG, 0)
Definition at line 82 of file mia_internal.h.
#define Ltahoe_new_pred_reg(ptype)
Value:
L_new_register_operand (++(L_fn-> \
                                               max_reg_id), \
                                               L_CTYPE_PREDICATE, (ptype))
Definition at line 85 of file mia_internal.h.
#define Ltahoe_PMAC(mac)
Value:
L_new_macro_operand (TAHOE_MAC_ ## mac, \
                                              L_CTYPE_PREDICATE, 0)
Definition at line 101 of file mia_internal.h.
#define Ltahoe_true_pred(ptype)
Value:
L_new_macro_operand (TAHOE_MAC_PRED_TRUE, \
                                                     L_CTYPE_PREDICATE, \
                                                     (ptype))
Definition at line 93 of file mia_internal.h.
#define MOD if (Mopti_debug_messages) Mopti_debug
Definition at line 73 of file mia_internal.h.
Referenced by M_global_common_subexpression(), Mopti_deinit(), Mopti_init(), Mopti_perform_optimizations_tahoe(), Mopti_phase2_optimizations(), and Mopti_shladd().
Function Documentation
int Mopti_compare_height_reduction (L_Func * fn, L_Cb * cb, L_Loop * loop, int loop_n_cb, int * loop_cb)
Definition at line 181 of file mia_compare.c.
References Change_gte_to_gt(), Change_lte_to_lt(), find_add_for_compare(), LT_is_R0_operand, SIMM_8, Switch_add_compare_order_if_needed(), and TAHOEop_ADDS.
Referenced by Mopti_loop_compare_height_reduction(), and Mopti_perform_optimizations_tahoe().
void Mopti_debug (char * fmt, ...)
Definition at line 2428 of file mia_opti.c.
int Mopti_loop_compare_height_reduction (L_Func * fn)
Definition at line 94 of file mia_compare.c.
References Mopti_compare_height_reduction().
Referenced by Mopti_perform_optimizations_tahoe().