mia_post_inc.c File Reference
#include <config.h>
#include `mia_internal.h`
#include <Lcode/l_softpipe.h>
Functions
static void Mia_cb_post_increment (L_Cb *cb, int conservative, int ld, int st)
void Mia_post_increment_conversion (L_Func *fn, int ld, int st)
void Mia_softpipe_post_increment_conversion (L_Func *fn, int ld, int st)
static void Convert_mem_op_to_post_inc (L_Oper *mem_oper, L_Operand *inc_operand)
static int L_live_out_inhibits_scheduling (L_Cb *cb, L_Operand *operand, L_Oper *add)
Function Documentation
static void Convert_mem_op_to_post_inc (L_Oper * mem_oper, L_Operand * inc_operand) [static]
Definition at line 144 of file mia_post_inc.c.
References TAHOEop_LD1, TAHOEop_LD2, TAHOEop_LD4, TAHOEop_LD8, TAHOEop_LD8_FILL, TAHOEop_LDF_FILL, TAHOEop_LDFD, TAHOEop_LDFS, TAHOEop_ST1, TAHOEop_ST2, TAHOEop_ST4, TAHOEop_ST8, TAHOEop_ST8_SPILL, TAHOEop_STF_SPILL, TAHOEop_STFD, and TAHOEop_STFS.
Referenced by Mia_cb_post_increment().
static int L_live_out_inhibits_scheduling (L_Cb * cb, L_Operand * operand, L_Oper * add) [static]
Definition at line 318 of file mia_post_inc.c.
Referenced by Mia_cb_post_increment().
static void Mia_cb_post_increment (L_Cb * cb, int conservative, int ld, int st) [static]
Definition at line 386 of file mia_post_inc.c.
References Convert_mem_op_to_post_inc(), L_live_out_inhibits_scheduling(), L_no_other_def_use_in_cb(), and SIMM_9.
Referenced by Mia_post_increment_conversion(), and Mia_softpipe_post_increment_conversion().
void Mia_post_increment_conversion (L_Func * fn, int ld, int st)
Definition at line 90 of file mia_post_inc.c.
References Mia_cb_post_increment().
void Mia_softpipe_post_increment_conversion (L_Func * fn, int ld, int st)
Definition at line 117 of file mia_post_inc.c.
References Mia_cb_post_increment().