lmdes_build.c File Reference
#include <config.h>
#include <ctype.h>
#include <machine/hmdes.h>
Functions
void print_usage ()
int main (int argc, char **argv, char **envp)
Variables
char * program_name
Function Documentation
int main (int argc, char ** argv, char ** envp)
Definition at line 81 of file lmdes_build.c.
References create_hmdes(), H_punt(), NULL, print_usage(), program_name, and write_lmdes().
void print_usage ()
Definition at line 71 of file lmdes_build.c.
References program_name.
Referenced by main().
Variable Documentation
char* program_name
Definition at line 68 of file lmdes_build.c.
Referenced by main(), and print_usage().