/* ./src/Lcode/codegen/Ltahoe/ltahoe_table.h generated by ./src/Lcode/codegen/Ltahoe/table.pl on Thu Aug 28 13:54:51 2014
 * Do not edit this file manually.  Edit ./src/Lcode/codegen/Ltahoe/ltahoe_table.src, then run
 * ./src/Lcode/codegen/Ltahoe/table.pl -h ./include/machine/m_tahoe.h -i ./src/Lcode/codegen/Ltahoe/ltahoe_table.src -o ./src/Lcode/codegen/Ltahoe/ltahoe_table
 * to generate this file. */

/*****************************************************************************\
 *
 *		      Illinois Open Source License
 *                     University of Illinois/NCSA
 *                         Open Source License
 *
 * Copyright (c) 2002, The University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Developed by:             
 *
 *		IMPACT Research Group
 *
 *		University of Illinois at Urbana-Champaign
 *
 *              http://www.crhc.uiuc.edu/IMPACT
 *              http://www.gelato.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal with the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimers.
 *
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimers in
 * the documentation and/or other materials provided with the
 * distribution.
 *
 * Neither the names of the IMPACT Research Group, the University of
 * Illinois, nor the names of its contributors may be used to endorse
 * or promote products derived from this Software without specific
 * prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
 * WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
 * OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 *
\*****************************************************************************/

#ifndef _LTAHOE_TABLE
#define _LTAHOE_TABLE

#include <config.h>
#include <Lcode/l_code.h>
#include <machine/m_tahoe.h>
#include <ltahoe_completers.h>
#include <phase1_bitopt.h>
#include <phase3_oper.h>

#define table_num_opcodes 334
#define table_offset 1000

#define LTAHOE_TABLE_ENTRY(t, o)   (t)[(o)-table_offset]

typedef struct _opcode_handler
{
	char opc_str[30];	/* Default: "" */
	int (*completer_sanity_check)(L_Oper *);	/* Default: NULL */
	void (*print_completers)(L_Oper *);	/* Default: NULL */
	void (*print_opcode)(L_Oper *);	/* Default: NULL */
	void (*ComputeKnownBitsFlow)(L_Func *, L_Cb *, L_Oper *);	/* Default: NULL */
	void (*ProcessOperUsingTD)(L_Func *, L_Cb *, L_Oper *);	/* Default: NULL */
	void (*ComputeBitsUsedLocal)(L_Func *, L_Cb *, L_Oper *);	/* Default: NULL */
} opcode_handler;

extern opcode_handler Ltahoe_table[table_num_opcodes];

#endif
