l_main.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <unistd.h>
Functions
int main (int argc, char **argv, char **envp)
Function Documentation
int main (int argc, char ** argv, char ** envp)
Definition at line 121 of file l_main.c.
References C_get_arg(), C_MAX_ARG, C_Arg::count, L_create_external_macro_list(), L_get_std_parm_name(), L_load_parameters_aliased(), L_warn_about_unused_macros(), M_define_macros(), M_define_opcode_name(), M_set_machine(), NULL, C_Arg::option, and strcmp().