r_regalloc.c File Reference
#include <config.h>
#include `r_regalloc.h`
#include `region.h`
#include <machine/m_hppa.h>
#include <Lcode/l_opti.h>
#include <Lcode/l_disjvreg.h>
#include <library/i_list.h>
Defines
#define ON_OFF(parm) ((parm)?`on`:`off`)
#define R_MATCHING_MACRO(l_opd, r_mac)
Functions
static void R_read_parm_regalloc (Parm_Parse_Info *ppi)
void R_print_parm_configuration (void)
static R_Reg * R_new_reg (int vreg_id, int type, double weight, int def, int rclass)
R_Reg * R_add_register (int vreg_id, int type, double weight, int def)
int R_find_free_vreg (void)
int R_spill_loc (int type)
R_Reg * R_add_macro_register (int vreg_id, int mac, int type, int rclass)
void R_determine_available_macros (void)
Set R_process_illegal_register_attr (L_Attr *attr)
int R_issue_time (L_Oper *oper)
Set R_build_rotating_reg_set (L_Func *fn)
void R_get_rot_regs (L_Func *fn, int *int_base, int *int_num, int *flt_base, int *flt_num, int *dbl_base, int *dbl_num, int *pred_base, int *pred_num)
void R_process_cb (L_Cb *cb)
void R_process_cb_for_spilling (L_Func *fn, L_Cb *cb)
R_Reg * R_reset_vreg_list (R_Reg *vregList)
void R_register_saving_convention_selection (L_Func *fn, L_Region *region)
void R_determine_reserved_registers (Set *reserved_resource, Set *constrained_resource, int *constrained_array, R_Reg *vreg)
int R_conv_type_to_Ltype (int type)
int R_conv_rclass_to_Lclass (int rclass)
int R_Ltype_to_Rtype (int type)
static void R_prune_interference_graph (void)
static int R_allocate_unconstrained_virtual_registers (void)
void R_allocate_virtual_registers (L_Func *fn)
static void R_spill_all_virtual_registers (L_Func *fn, L_Region *region)
static void R_regalloc_memory_init (L_Func *fn)
static void R_regalloc_memory_cleanup (void)
int R_register_allocation (L_Func *fn, Parm_Macro_List *command_line_macro_list)
int R_register_allocation_sep (L_Func *fn, Parm_Macro_List *command_line_macro_list, int *int_swap_space_size, int *fp_swap_space_size, int *pred_swap_space_size)
Variables
int R_Init = 1
int R_Register_Allocation = 1
int R_Spill_Everything = 0
int R_Macro_Allocation = 1
int R_Utilize_Profile_Info = 1
int R_Prevent_MCB_Preload_Spills = 0
int R_Same_Cycle_Anti_Deps_Interference = 1
int R_Prune_Interference_Graph = 0
int R_Region_Based_Allocation = 0
int R_Round_Robin_Allocation = 0
int R_Invariant_Vreg_Priorities = 0
int R_Schedule_Invariant_Alloc = 0
int R_Print_Parm_Configuration = 0
int R_Print_Bank_Configuration = 0
int R_Print_Macroregisters = 0
int R_Print_Live_Ranges = 0
int R_Print_Interference_Graph = 0
int R_Print_Class_Selection = 0
int R_Print_Coloring_Stats = 0
int R_Print_Allocation = 0
int R_Print_Allocation_Stats = 0
int R_Print_Dead_Code_Results = 0
int R_Print_Virtual_Register_Function = 0
int R_Allow_Dead_Code_Elimination = 1
int R_Minimize_Spill_Fill = 0
L_Alloc_Pool * R_alloc_virtual_register = NULL
L_Alloc_Pool * R_alloc_interference_arc = NULL
Set R_pa_set = 0
double ld_wgt
double st_wgt
double mv_wgt
int ld_cnt
int st_cnt
int mv_cnt
R_Physical_Bank * R_bank = 0
int ** R_map
int R_global_overlap [R_MAX_BANK]
int R_max_overlap_size [R_MAX_BANK]
int R_n_vreg = 0
R_Reg * R_vreg = NULL
HashTable R_vregHashTbl
HashTable R_regionAllocMap
HashTable flowHashTbl
int * R_buf = NULL
int * R_buf2 = NULL
void ** R_pbuf = NULL
void ** R_pbuf2 = NULL
int R_n_oper
Set R_oper_set = NULL
List R_jsr_list = NULL
Set R_extend_set = NULL
L_Oper * R_rts = NULL
int pred_spill_stack
int int_spill_stack
int fp_spill_stack
int * R_register_contents
R_Macro * R_avail_macro
R_Macro * R_jsr_def_macro
int R_n_avail_macro
int R_n_jsr_def_macro
double caller_callee_threshold = 0.0
double total_instruction_weight = 0.0
double total_spill_weight = 0.0
double total_region_spill_weight = 0.0
double total_caller_weight = 0.0
L_Region * R_Region
Define Documentation
#define ON_OFF(parm) ((parm)?`on`:`off`)
Definition at line 312 of file r_regalloc.c.
Referenced by R_print_parm_configuration().
#define R_MATCHING_MACRO(l_opd, r_mac)
Value:
(((l_opd)->value.mac == (r_mac).id) && \
    (R_Ltype_to_Rtype (L_return_old_ctype ((l_opd))) == (r_mac).type))
Definition at line 1023 of file r_regalloc.c.
Referenced by R_process_cb().
Function Documentation
R_Reg* R_add_macro_register (int vreg_id, int mac, int type, int rclass)
Definition at line 576 of file r_regalloc.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_pa_set, R_Physical_Bank::reg_size, Set_add(), and VREG.
Referenced by R_determine_available_macros().
R_Reg* R_add_register (int vreg_id, int type, double weight, int def)
Definition at line 406 of file r_regalloc.c.
References BANK_NAME(), R_Reg::def_weight, R_Reg::index, M_HP_PLAYDOH_MCODE, M_model, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_Ltype_to_Rtype(), R_new_reg(), R_POINTER, R_PREDICATE, R_PREFER_SPILL, R_Reg::ref_weight, R_Reg::type, and VREG.
Referenced by R_cbsplit_spilled_live_range(), R_determine_region_flybys(), R_isplit_spilled_live_range(), R_process_cb(), and R_process_cb_for_spilling().
static int R_allocate_unconstrained_virtual_registers (void) [static]
Definition at line 2855 of file r_regalloc.c.
References R_Reg::base_index, NULL, Pop(), R_bank, R_determine_reserved_registers(), R_find_free_register(), R_n_vreg, R_Reg::rclass, Set_dispose(), Set_union(), R_Reg::size, and R_Reg::type.
Referenced by R_allocate_virtual_registers().
void R_allocate_virtual_registers (L_Func * fn)
Definition at line 2914 of file r_regalloc.c.
References R_Reg::base_index, R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::flags, Free_Stack(), Heap_Create(), Heap_Dispose(), Heap_ExtractTop(), Heap_Insert(), HEAP_MAX, Heap_Top(), R_Reg::index, New_Stack(), R_Reg::nextReg, NULL, Pop(), R_Reg::priority, Push_Top(), R_allocate_unconstrained_virtual_registers(), R_bank, R_CALLEE, R_CALLER, R_determine_reserved_registers(), R_find_free_register(), R_find_rotating_register(), R_handle_unallocatable_vreg(), R_n_vreg, R_Print_Coloring_Stats, R_Prune_Interference_Graph, R_prune_interference_graph(), R_REGION_CONSTRAINED, R_reset_register_stacks(), R_SPILLED, R_UNCONSTRAINED, R_vreg, R_Reg::rclass, R_Reg::rotating, Set_dispose(), Set_print(), Set_union(), R_Reg::size, and R_Reg::type.
Referenced by R_register_allocation_sep().
Set R_build_rotating_reg_set (L_Func * fn)
Definition at line 883 of file r_regalloc.c.
References NULL, R_get_rot_regs(), and Set_add().
Referenced by R_register_allocation_sep().
int R_conv_rclass_to_Lclass (int rclass)
Definition at line 2018 of file r_regalloc.c.
References R_CALLEE, R_CALLER, and R_MACRO_CALLER.
Referenced by R_add_load(), R_add_store(), R_insert_jsr_spill_fill_code(), R_insert_spill_fill_code(), and R_spill_all_virtual_registers().
int R_conv_type_to_Ltype (int type)
Definition at line 1994 of file r_regalloc.c.
References M_native_int_register_ctype(), R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, R_PREDICATE, and R_QUAD.
Referenced by R_add_load(), R_add_store(), R_cbsplit_spilled_live_range(), R_insert_jsr_spill_fill_code(), and R_isplit_spilled_live_range().
void R_determine_available_macros (void)
Definition at line 647 of file r_regalloc.c.
References R_Physical_Bank::defined, R_Macro::id, R_Physical_Bank::num_reg, R_add_macro_register(), R_avail_macro, R_bank, R_find_free_vreg(), R_jsr_def_macro, R_Macro_Allocation, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_n_avail_macro, R_n_jsr_def_macro, R_NUM_TYPES, R_TYPE_INC, R_Physical_Bank::reg_size, _Arc::type, R_Macro::type, and R_Macro::vreg_id.
Referenced by R_register_allocation_sep().
void R_determine_reserved_registers (Set * reserved_resource, Set * constrained_resource, int * constrained_array, R_Reg * vreg)
Definition at line 1931 of file r_regalloc.c.
References R_Reg::index, R_Reg::interfere, R_Arc::lr, R_Arc::next, NULL, R_buf, R_Region, R_REGION_CONSTRAINED, Set_add(), and VREG.
Referenced by R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), and R_isplit_spilled_live_range().
int R_find_free_vreg (void)
Definition at line 480 of file r_regalloc.c.
Referenced by R_cbsplit_spilled_live_range(), R_determine_available_macros(), and R_isplit_spilled_live_range().
void R_get_rot_regs (L_Func * fn, int * int_base, int * int_num, int * flt_base, int * flt_num, int * dbl_base, int * dbl_num, int * pred_base, int * pred_num)
Definition at line 923 of file r_regalloc.c.
References M_arch, M_native_int_register_ctype(), M_TAHOE, NULL, and R_get_rot_reg_max_alloc().
Referenced by R_build_rotating_reg_set(), R_find_free_register_in_bank(), and R_virtual_to_machine_conversion().
int R_issue_time (L_Oper * oper)
Definition at line 858 of file r_regalloc.c.
References NULL.
Referenced by R_process_cb().
int R_Ltype_to_Rtype (int type)
Definition at line 2035 of file r_regalloc.c.
References R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, and R_PREDICATE.
Referenced by R_add_register(), R_get_rot_reg_alloc_multiple(), R_get_rot_reg_max_alloc(), R_number_of_registers(), R_process_illegal_register_attr(), R_register_overlap(), R_size_of_register(), and R_unmap_physical_registers().
static R_Reg* R_new_reg (int vreg_id, int type, double weight, int def, int rclass) [static]
Definition at line 352 of file r_regalloc.c.
References R_Reg::base_index, R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::constraints, R_Reg::def_instr, R_Reg::def_weight, R_Reg::flags, HashTable_insert(), R_Reg::illegal_reg, R_Reg::index, R_Reg::instr_weight, R_Reg::interfere, R_Reg::intf_vreg, L_alloc(), R_Reg::live_range, R_Reg::nextReg, R_Reg::nth_rot_reg, NULL, R_Reg::priority, R_Reg::pvreg, R_alloc_virtual_register, R_CURRENT_VREG, R_n_vreg, R_vreg, R_vregHashTbl, R_Reg::rclass, R_Reg::ref_cbs, R_Reg::ref_instr, R_Reg::ref_weight, R_Reg::rotating, R_Reg::size, R_Reg::spill_loc, and R_Reg::type.
Referenced by R_add_register().
void R_print_parm_configuration (void)
Definition at line 315 of file r_regalloc.c.
References ON_OFF, R_Macro_Allocation, R_Print_Allocation, R_Print_Bank_Configuration, R_Print_Class_Selection, R_Print_Coloring_Stats, R_Print_Live_Ranges, R_Print_Parm_Configuration, R_Prune_Interference_Graph, R_Region_Based_Allocation, R_Spill_Everything, and R_Utilize_Profile_Info.
Referenced by R_register_allocation_sep().
void R_process_cb (L_Cb * cb)
Definition at line 1028 of file r_regalloc.c.
References R_Reg::def_instr, FALSE, R_Reg::flags, _Set::id, R_Reg::intf_vreg, List_insert_last(), R_Reg::live_range, M_arch, M_HP_PLAYDOH_MCODE, M_HPPA, M_model, M_X86, NULL, op_flag_set(), R_add_register(), R_avail_macro, R_buf, R_CURRENT_VREG, R_extend_set, R_issue_time(), R_jsr_list, R_MATCHING_MACRO, R_MCB_PRELOAD, R_oper_set, R_PA_HACK, R_Prevent_MCB_Preload_Spills, R_process_illegal_register_attr(), R_Region_Based_Allocation, R_rts, R_Same_Cycle_Anti_Deps_Interference, R_Schedule_Invariant_Alloc, R_Reg::ref_cbs, R_Reg::ref_instr, Set_2array(), Set_add(), Set_dispose(), Set_union_acc(), TRUE, and VREG.
Referenced by R_register_allocation_sep().
void R_process_cb_for_spilling (L_Func * fn, L_Cb * cb)
Definition at line 1425 of file r_regalloc.c.
References NULL, and R_add_register().
Referenced by R_register_allocation_sep().
Set R_process_illegal_register_attr (L_Attr * attr)
Definition at line 738 of file r_regalloc.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, NULL, R_Physical_Bank::num_reg, R_bank, R_CALLEE, R_CALLER, R_Ltype_to_Rtype(), R_map, R_Physical_Bank::reg_size, Set_add(), and VREG.
Referenced by R_process_cb().
static void R_prune_interference_graph (void) [static]
Definition at line 2769 of file r_regalloc.c.
References R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::flags, R_Reg::illegal_reg, R_Reg::interfere, R_Arc::lr, R_Arc::next, R_Reg::nextReg, NULL, R_Physical_Bank::num_reg, Pop(), Push_Top(), R_bank, R_CALLEE, R_CALLER, R_global_overlap, R_MACRO_CALLER, R_max_overlap_size, R_PA_HACK, R_UNCONSTRAINED, R_vreg, R_Reg::rclass, R_Physical_Bank::reg_size, Set_size(), and R_Reg::type.
Referenced by R_allocate_virtual_registers().
static void R_read_parm_regalloc (Parm_Parse_Info * ppi) [static]
Definition at line 259 of file r_regalloc.c.
References L_read_parm_b(), M_arch, M_X86, R_Allow_Dead_Code_Elimination, R_Invariant_Vreg_Priorities, R_Macro_Allocation, R_Minimize_Spill_Fill, R_Prevent_MCB_Preload_Spills, R_Print_Allocation, R_Print_Allocation_Stats, R_Print_Bank_Configuration, R_Print_Class_Selection, R_Print_Coloring_Stats, R_Print_Dead_Code_Results, R_Print_Interference_Graph, R_Print_Live_Ranges, R_Print_Macroregisters, R_Print_Parm_Configuration, R_Print_Virtual_Register_Function, R_Prune_Interference_Graph, R_Region_Based_Allocation, R_Register_Allocation, R_Round_Robin_Allocation, R_Same_Cycle_Anti_Deps_Interference, R_Schedule_Invariant_Alloc, R_Spill_Everything, and R_Utilize_Profile_Info.
Referenced by R_register_allocation_sep().
static void R_regalloc_memory_cleanup (void) [static]
Definition at line 3589 of file r_regalloc.c.
References R_Reg::def_instr, R_Reg::interfere, R_Reg::intf_vreg, L_free(), R_Reg::live_range, R_Arc::next, R_Reg::nextReg, NULL, R_alloc_interference_arc, R_alloc_virtual_register, R_vreg, R_Reg::ref_cbs, R_Reg::ref_instr, and Set_dispose().
Referenced by R_register_allocation_sep().
static void R_regalloc_memory_init (L_Func * fn) [static]
Definition at line 3541 of file r_regalloc.c.
References flowHashTbl, fp_spill_stack, HashTable_create(), int_spill_stack, L_create_alloc_pool(), NULL, pred_spill_stack, R_alloc_interference_arc, R_alloc_virtual_register, R_buf, R_buf2, R_MAX, R_n_oper, R_oper_set, R_pbuf, R_pbuf2, R_regionAllocMap, and R_vregHashTbl.
Referenced by R_register_allocation_sep().
int R_register_allocation (L_Func * fn, Parm_Macro_List * command_line_macro_list)
Definition at line 3666 of file r_regalloc.c.
References R_register_allocation_sep().
int R_register_allocation_sep (L_Func * fn, Parm_Macro_List * command_line_macro_list, int * int_swap_space_size, int * fp_swap_space_size, int * pred_swap_space_size)
Definition at line 3676 of file r_regalloc.c.
References fp_spill_stack, int_spill_stack, L_load_parameters_aliased(), M_arch, M_HPPA, NULL, pred_spill_stack, R_allocate_virtual_registers(), R_analyze_bank_overlap(), R_assemble_region(), R_bank, R_build_rotating_reg_set(), R_CALLER, R_compute_dataflow_info(), R_compute_live_ranges(), R_construct_interference_graph(), R_determine_allocation_constraints(), R_determine_available_macros(), R_determine_region_flybys(), R_DOUBLE, R_Init, R_init_pa_set(), R_init_spill_stack(), R_insert_jsr_spill_fill_code(), R_insert_reconciliation_code(), R_insert_spill_fill_code(), R_INT, R_Print_Allocation_Stats, R_Print_Bank_Configuration, R_print_bank_configuration(), R_Print_Parm_Configuration, R_print_parm_configuration(), R_Print_Virtual_Register_Function, R_process_cb(), R_process_cb_for_spilling(), R_read_parm_regalloc(), R_reconcile_allocated_region(), R_regalloc_memory_cleanup(), R_regalloc_memory_init(), R_regalloc_version(), R_Region, R_Region_Based_Allocation, R_register_saving_convention_selection(), R_sort_vreg_list(), R_spill_all_virtual_registers(), R_Spill_Everything, R_unmap_physical_registers(), R_update_alloc_state(), R_update_region_spill_stack(), R_Utilize_Profile_Info, R_virtual_to_machine_conversion(), Set_dispose(), Set_size(), total, total_caller_weight, total_instruction_weight, total_region_spill_weight, total_spill_weight, and R_Physical_Bank::used_reg.
Referenced by R_register_allocation().
void R_register_saving_convention_selection (L_Func * fn, L_Region * region)
Definition at line 1536 of file r_regalloc.c.
References R_Reg::flags, _Set::id, List_next(), List_size(), List_start(), R_Reg::live_range, R_Reg::nextReg, NULL, R_BTR, R_callee_cost(), R_caller_cost(), R_CONTAINS_JSR, R_jsr_list, R_NUM_TYPES, R_PREALLOCATED_MACRO, R_Print_Class_Selection, R_Region_Based_Allocation, R_spill_load_cost(), R_spill_store_cost(), R_vreg, Set_in(), and R_Reg::type.
Referenced by R_register_allocation_sep().
R_Reg* R_reset_vreg_list (R_Reg * vregList)
Definition at line 1469 of file r_regalloc.c.
References R_Reg::base_index, R_Reg::def_instr, R_Reg::flags, R_Reg::live_range, _Arc::next, R_Reg::nextReg, NULL, R_PREALLOCATED_MACRO, R_PREFER_SPILL, R_Reg::rclass, R_Reg::ref_cbs, R_Reg::ref_instr, Set_dispose(), and R_Reg::size.
static void R_spill_all_virtual_registers (L_Func * fn, L_Region * region) [static]
Definition at line 3129 of file r_regalloc.c.
References R_Physical_Bank::base_index, R_Reg::base_index, R_Physical_Bank::defined, R_Reg::index, NULL, O_fill_reg(), O_spill_reg(), R_Reg::phys_reg, R_bank, R_CALLER, R_conv_rclass_to_Lclass(), R_find_free_register(), R_insert_spill_code_after(), R_insert_spill_code_before(), R_map, R_SPILL_CODE, R_spill_loc(), R_Reg::rclass, Set_add(), Set_in(), Set_union(), R_Reg::size, R_Reg::spill_loc, R_Reg::type, R_Physical_Bank::used_reg, and VREG.
Referenced by R_register_allocation_sep().
int R_spill_loc (int type)
Definition at line 501 of file r_regalloc.c.
References fp_spill_stack, int_spill_stack, M_arch, M_TAHOE, pred_spill_stack, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, and R_PREDICATE.
Referenced by R_handle_unallocatable_vreg(), R_insert_jsr_spill_fill_code(), and R_spill_all_virtual_registers().
Variable Documentation
double caller_callee_threshold = 0.0
Definition at line 229 of file r_regalloc.c.
HashTable flowHashTbl
Definition at line 201 of file r_regalloc.c.
Referenced by R_init_flow_hash_tbl(), and R_regalloc_memory_init().
int fp_spill_stack
Definition at line 219 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), R_regalloc_memory_init(), R_register_allocation_sep(), R_spill_loc(), and R_update_region_spill_stack().
int int_spill_stack
Definition at line 218 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), R_regalloc_memory_init(), R_register_allocation_sep(), R_spill_loc(), and R_update_region_spill_stack().
int ld_cnt
Definition at line 188 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code().
double ld_wgt
Definition at line 187 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code().
int mv_cnt
Definition at line 188 of file r_regalloc.c.
double mv_wgt
Definition at line 187 of file r_regalloc.c.
int pred_spill_stack
Definition at line 217 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), R_regalloc_memory_init(), R_register_allocation_sep(), and R_spill_loc().
L_Alloc_Pool* R_alloc_interference_arc = NULL
Definition at line 182 of file r_regalloc.c.
Referenced by R_handle_unallocatable_vreg(), R_isplit_spilled_live_range(), R_regalloc_memory_cleanup(), and R_regalloc_memory_init().
L_Alloc_Pool* R_alloc_virtual_register = NULL
Definition at line 181 of file r_regalloc.c.
Referenced by R_new_reg(), R_regalloc_memory_cleanup(), and R_regalloc_memory_init().
int R_Allow_Dead_Code_Elimination = 1
Definition at line 153 of file r_regalloc.c.
Referenced by R_read_parm_regalloc().
R_Macro* R_avail_macro
Definition at line 223 of file r_regalloc.c.
Referenced by R_determine_available_macros(), and R_process_cb().
R_Physical_Bank* R_bank = 0
Definition at line 190 of file r_regalloc.c.
Referenced by R_add_macro_register(), R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), R_analyze_bank_overlap(), R_define_physical_bank_with_rot(), R_determine_available_macros(), R_find_base_from_phys_reg(), R_find_free_register(), R_find_free_register_in_bank(), R_find_rotating_register(), R_get_rot_reg_alloc_multiple(), R_get_rot_reg_max_alloc(), R_in_physical_register(), R_insert_jsr_spill_fill_code(), R_max_bank_offset(), R_number_of_registers(), R_print_bank_configuration(), R_process_illegal_register_attr(), R_prune_interference_graph(), R_put_in_physical_register(), R_register_allocation_sep(), R_register_overlap(), R_reset_register_stacks(), R_same_register(), R_size_of_register(), R_smallest_overlapping_bank(), R_spill_all_virtual_registers(), and R_virtual_to_machine_conversion().
int* R_buf = NULL
Definition at line 203 of file r_regalloc.c.
Referenced by R_cbsplit_spilled_live_range(), R_determine_allocation_constraints(), R_determine_region_flybys(), R_determine_reserved_registers(), R_isplit_spilled_live_range(), R_process_cb(), R_reconcile_allocated_region(), R_regalloc_memory_init(), R_unmap_physical_registers(), and R_update_alloc_state().
int* R_buf2 = NULL
Definition at line 204 of file r_regalloc.c.
Referenced by R_regalloc_memory_init().
Set R_extend_set = NULL
Definition at line 214 of file r_regalloc.c.
Referenced by R_process_cb().
int R_global_overlap[R_MAX_BANK]
Definition at line 192 of file r_regalloc.c.
Referenced by R_analyze_bank_overlap(), and R_prune_interference_graph().
int R_Init = 1
Definition at line 124 of file r_regalloc.c.
Referenced by R_register_allocation_sep().
int R_Invariant_Vreg_Priorities = 0
Definition at line 136 of file r_regalloc.c.
Referenced by R_cbsplit_spilled_live_range(), R_handle_unallocatable_vreg(), R_isplit_spilled_live_range(), and R_read_parm_regalloc().
R_Macro* R_jsr_def_macro
Definition at line 224 of file r_regalloc.c.
Referenced by R_determine_available_macros().
List R_jsr_list = NULL
Definition at line 212 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), R_process_cb(), and R_register_saving_convention_selection().
int R_Macro_Allocation = 1
Definition at line 127 of file r_regalloc.c.
Referenced by R_determine_available_macros(), R_find_free_register(), R_number_of_registers(), R_print_parm_configuration(), and R_read_parm_regalloc().
int** R_map
Definition at line 191 of file r_regalloc.c.
Referenced by R_add_macro_register(), R_define_physical_bank_with_rot(), R_determine_available_macros(), R_find_base_from_phys_reg(), R_print_bank_configuration(), R_process_illegal_register_attr(), R_spill_all_virtual_registers(), and R_virtual_to_machine_conversion().
int R_max_overlap_size[R_MAX_BANK]
Definition at line 193 of file r_regalloc.c.
Referenced by R_analyze_bank_overlap(), and R_prune_interference_graph().
int R_Minimize_Spill_Fill = 0
Definition at line 176 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), and R_read_parm_regalloc().
int R_n_avail_macro
Definition at line 226 of file r_regalloc.c.
Referenced by R_determine_available_macros().
int R_n_jsr_def_macro
Definition at line 227 of file r_regalloc.c.
Referenced by R_determine_available_macros().
int R_n_oper
Definition at line 209 of file r_regalloc.c.
Referenced by R_regalloc_memory_init(), and R_register_spill_is_required().
int R_n_vreg = 0
Definition at line 195 of file r_regalloc.c.
Referenced by R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), and R_new_reg().
Set R_oper_set = NULL
Definition at line 211 of file r_regalloc.c.
Referenced by R_process_cb(), and R_regalloc_memory_init().
Set R_pa_set = 0
Definition at line 185 of file r_regalloc.c.
Referenced by R_add_macro_register().
void** R_pbuf = NULL
Definition at line 206 of file r_regalloc.c.
Referenced by R_cbsplit_spilled_live_range(), and R_regalloc_memory_init().
void** R_pbuf2 = NULL
Definition at line 207 of file r_regalloc.c.
Referenced by R_regalloc_memory_init().
int R_Prevent_MCB_Preload_Spills = 0
Definition at line 129 of file r_regalloc.c.
Referenced by R_handle_unallocatable_vreg(), R_process_cb(), and R_read_parm_regalloc().
int R_Print_Allocation = 0
Definition at line 147 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_virtual_to_machine_conversion().
int R_Print_Allocation_Stats = 0
Definition at line 148 of file r_regalloc.c.
Referenced by R_read_parm_regalloc(), and R_register_allocation_sep().
int R_Print_Bank_Configuration = 0
Definition at line 140 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_register_allocation_sep().
int R_Print_Class_Selection = 0
Definition at line 145 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_register_saving_convention_selection().
int R_Print_Coloring_Stats = 0
Definition at line 146 of file r_regalloc.c.
Referenced by R_allocate_virtual_registers(), R_print_parm_configuration(), and R_read_parm_regalloc().
int R_Print_Dead_Code_Results = 0
Definition at line 150 of file r_regalloc.c.
Referenced by R_read_parm_regalloc().
int R_Print_Interference_Graph = 0
Definition at line 144 of file r_regalloc.c.
Referenced by R_read_parm_regalloc().
int R_Print_Live_Ranges = 0
Definition at line 143 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), and R_read_parm_regalloc().
int R_Print_Macroregisters = 0
Definition at line 142 of file r_regalloc.c.
Referenced by R_read_parm_regalloc().
int R_Print_Parm_Configuration = 0
Definition at line 139 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_register_allocation_sep().
int R_Print_Virtual_Register_Function = 0
Definition at line 152 of file r_regalloc.c.
Referenced by R_read_parm_regalloc(), and R_register_allocation_sep().
int R_Prune_Interference_Graph = 0
Definition at line 132 of file r_regalloc.c.
Referenced by R_allocate_virtual_registers(), R_print_parm_configuration(), and R_read_parm_regalloc().
L_Region* R_Region
Definition at line 236 of file r_regalloc.c.
Referenced by R_determine_region_flybys(), R_determine_reserved_registers(), R_find_free_register(), R_handle_unallocatable_vreg(), and R_register_allocation_sep().
int R_Region_Based_Allocation = 0
Definition at line 133 of file r_regalloc.c.
Referenced by R_assemble_region(), R_init_spill_stack(), R_print_parm_configuration(), R_process_cb(), R_read_parm_regalloc(), R_register_allocation_sep(), R_register_saving_convention_selection(), and R_update_region_spill_stack().
HashTable R_regionAllocMap
Definition at line 199 of file r_regalloc.c.
Referenced by R_regalloc_memory_init().
int R_Register_Allocation = 1
Definition at line 125 of file r_regalloc.c.
Referenced by R_read_parm_regalloc(), and R_register_spill_is_required().
int* R_register_contents
Definition at line 221 of file r_regalloc.c.
Referenced by R_in_physical_register(), R_insert_spill_fill_code(), and R_put_in_physical_register().
int R_Round_Robin_Allocation = 0
Definition at line 134 of file r_regalloc.c.
Referenced by R_find_free_register_in_bank(), and R_read_parm_regalloc().
L_Oper* R_rts = NULL
Definition at line 215 of file r_regalloc.c.
Referenced by R_process_cb().
int R_Same_Cycle_Anti_Deps_Interference = 1
Definition at line 130 of file r_regalloc.c.
Referenced by R_process_cb(), and R_read_parm_regalloc().
int R_Schedule_Invariant_Alloc = 0
Definition at line 137 of file r_regalloc.c.
Referenced by R_process_cb(), and R_read_parm_regalloc().
int R_Spill_Everything = 0
Definition at line 126 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_register_allocation_sep().
int R_Utilize_Profile_Info = 1
Definition at line 128 of file r_regalloc.c.
Referenced by R_print_parm_configuration(), R_read_parm_regalloc(), and R_register_allocation_sep().
R_Reg* R_vreg = NULL
Definition at line 196 of file r_regalloc.c.
Referenced by R_allocate_virtual_registers(), R_insert_jsr_spill_fill_code(), R_new_reg(), R_prune_interference_graph(), R_regalloc_memory_cleanup(), R_register_saving_convention_selection(), R_update_alloc_state(), and R_virtual_to_machine_conversion().
HashTable R_vregHashTbl
Definition at line 198 of file r_regalloc.c.
Referenced by R_new_reg(), and R_regalloc_memory_init().
int st_cnt
Definition at line 188 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code().
double st_wgt
Definition at line 187 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code().
double total_caller_weight = 0.0
Definition at line 234 of file r_regalloc.c.
Referenced by R_insert_jsr_spill_fill_code(), and R_register_allocation_sep().
double total_instruction_weight = 0.0
Definition at line 231 of file r_regalloc.c.
Referenced by R_register_allocation_sep().
double total_region_spill_weight = 0.0
Definition at line 233 of file r_regalloc.c.
Referenced by R_insert_reconciliation_code(), and R_register_allocation_sep().
double total_spill_weight = 0.0
Definition at line 232 of file r_regalloc.c.
Referenced by R_register_allocation_sep().