r_regbank.c File Reference
#include <config.h>
#include `r_regalloc.h`
Functions
int Lsched_loads_per_cycle (void)
void R_define_physical_bank_with_rot (int rclass, int type, int num_reg, int reg_size, int overlap, int *reg_array, Set *used, int num_rot_reg, int first_rot_reg, int num_rot_reg_alloc)
static void R_invalid_bank_overlap (R_Physical_Bank *bank, int type)
void R_define_physical_bank (int rclass, int type, int num_reg, int reg_size, int overlap, int *reg_array, Set *used)
void R_analyze_bank_overlap (void)
void R_reset_register_stacks (void)
int R_find_free_register_in_bank (R_Physical_Bank *reg_bank, Set reserved_resource, R_Reg *vreg)
int R_find_free_register (R_Reg *vreg, Set reserved_resource, int final)
int R_find_rotating_register (R_Reg *vreg, Set reserved_resource, int final)
int R_smallest_overlapping_bank (int type, int rclass)
void R_print_bank_configuration (void)
void R_virtual_to_machine_conversion (void)
int R_get_rot_reg_alloc_multiple (int ctype)
int R_get_rot_reg_max_alloc (int ctype)
Function Documentation
int Lsched_loads_per_cycle (void)
void R_analyze_bank_overlap (void)
Definition at line 239 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, Clear_Stack(), R_Physical_Bank::defined, NULL, R_Physical_Bank::overlap, R_Physical_Bank::overlap_cnt, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_global_overlap, R_INT, R_invalid_bank_overlap(), R_MAX, R_MAX_BANK, R_max_overlap_size, R_NUM_TYPES, R_OVERLAP_INT, R_OVERLAP_PREDICATE, R_POINTER, R_PREDICATE, R_QUAD, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, stack, and R_Physical_Bank::type.
Referenced by R_register_allocation_sep().
void R_define_physical_bank (int rclass, int type, int num_reg, int reg_size, int overlap, int * reg_array, Set * used)
Definition at line 219 of file r_regbank.c.
References R_define_physical_bank_with_rot().
void R_define_physical_bank_with_rot (int rclass, int type, int num_reg, int reg_size, int overlap, int * reg_array, Set * used, int num_rot_reg, int first_rot_reg, int num_rot_reg_alloc)
Definition at line 95 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, CALLOC, R_Physical_Bank::defined, R_Physical_Bank::mask, R_Physical_Bank::max, NULL, R_Physical_Bank::num_reg, R_Physical_Bank::num_rot_reg, R_Physical_Bank::num_rot_reg_alloc, R_Physical_Bank::overlap, R_bank, R_BTR, R_CALLEE, R_CALLER, R_DOUBLE, R_FLOAT, R_INT, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_MAX_BANK, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_POINTER, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_POINTER, R_PREDICATE, R_QUAD, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, R_Physical_Bank::rot_reg_ofs, R_Physical_Bank::type, and R_Physical_Bank::used_reg.
Referenced by R_define_physical_bank().
int R_find_free_register (R_Reg * vreg, Set reserved_resource, int final)
Definition at line 889 of file r_regbank.c.
References BANK_NAME(), R_Reg::callee_benefit, R_Reg::caller_benefit, R_Physical_Bank::defined, R_Reg::flags, R_Reg::index, NULL, R_bank, R_CALLEE, R_CALLER, R_find_free_register_in_bank(), R_Macro_Allocation, R_MACRO_CALLEE, R_MACRO_CALLER, R_PREFER_SPILL, R_Region, R_REGION_CONSTRAINED, R_Reg::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, Set_in(), and R_Reg::type.
Referenced by R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), R_isplit_spilled_live_range(), and R_spill_all_virtual_registers().
int R_find_free_register_in_bank (R_Physical_Bank * reg_bank, Set reserved_resource, R_Reg * vreg)
Definition at line 482 of file r_regbank.c.
References R_Physical_Bank::alloc_init, R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, BANK_NAME(), R_Physical_Bank::base_index, CLASS_NAME(), Delete_Stack(), init, M_arch, M_X86, R_Physical_Bank::mask, R_Reg::nth_rot_reg, NULL, R_Physical_Bank::num_rot_reg, R_Physical_Bank::overlap_cnt, Pop(), Push_Bot(), R_bank, R_FLOAT, R_get_rot_regs(), R_NUM_TYPES, R_Round_Robin_Allocation, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, R_Physical_Bank::rot_reg_ofs, R_Reg::rotating, Set_in(), Stack_Elmt_Data(), Stack_Find(), Stack_Find_Next(), Stack_Print(), Stack_Ptr_Reset(), Stack_Top(), R_Physical_Bank::type, and R_Reg::type.
Referenced by R_find_free_register(), and R_find_rotating_register().
int R_find_rotating_register (R_Reg * vreg, Set reserved_resource, int final)
Definition at line 1010 of file r_regbank.c.
References BANK_NAME(), R_Reg::callee_benefit, R_Reg::caller_benefit, R_Physical_Bank::defined, R_Reg::index, O_locate_rot_reg_bank(), R_bank, R_CALLEE, R_CALLER, R_find_free_register_in_bank(), R_Reg::rclass, and R_Reg::type.
Referenced by R_allocate_virtual_registers().
int R_get_rot_reg_alloc_multiple (int ctype)
Definition at line 1304 of file r_regbank.c.
References R_Physical_Bank::num_rot_reg, R_Physical_Bank::num_rot_reg_alloc, R_bank, R_CALLEE, R_CALLER, and R_Ltype_to_Rtype().
int R_get_rot_reg_max_alloc (int ctype)
Definition at line 1323 of file r_regbank.c.
References R_Physical_Bank::num_rot_reg, R_bank, R_CALLEE, R_CALLER, and R_Ltype_to_Rtype().
Referenced by R_get_rot_regs().
static void R_invalid_bank_overlap (R_Physical_Bank * bank, int type) [static]
Definition at line 207 of file r_regbank.c.
References BANK_NAME(), CLASS_NAME(), R_Physical_Bank::rclass, and R_Physical_Bank::type.
Referenced by R_analyze_bank_overlap().
void R_print_bank_configuration (void)
Definition at line 1101 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, BANK_NAME(), R_Physical_Bank::base_index, CLASS_NAME(), R_Physical_Bank::defined, NULL, R_Physical_Bank::num_reg, R_Physical_Bank::num_rot_reg, R_Physical_Bank::overlap, R_Physical_Bank::overlap_cnt, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_MAX_BANK, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_POINTER, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_POINTER, R_PREDICATE, R_QUAD, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, Stack_Print(), and R_Physical_Bank::type.
Referenced by R_register_allocation_sep().
void R_reset_register_stacks (void)
Definition at line 434 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, Clear_Stack(), R_Physical_Bank::defined, R_Physical_Bank::num_reg, Push_Bot(), R_bank, R_MAX_BANK, R_Physical_Bank::reg_size, and stack.
Referenced by R_allocate_virtual_registers().
int R_smallest_overlapping_bank (int type, int rclass)
Definition at line 1072 of file r_regbank.c.
References R_Physical_Bank::overlap, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_PREDICATE, and R_QUAD.
void R_virtual_to_machine_conversion (void)
Definition at line 1200 of file r_regbank.c.
References BANK_NAME(), R_Reg::base_index, R_Physical_Bank::base_index, CLASS_NAME(), R_Physical_Bank::defined, R_Reg::flags, R_Reg::index, R_Reg::nextReg, NULL, R_Reg::phys_reg, R_Reg::pvreg, R_bank, R_get_rot_regs(), R_map, R_PREALLOCATED_FLYBY, R_Print_Allocation, R_REGION_CONSTRAINED, R_SPILLED, R_vreg, R_Reg::rclass, R_Reg::rotating, Set_add(), R_Reg::spill_loc, R_Reg::type, and R_Physical_Bank::used_reg.
Referenced by R_register_allocation_sep().