r_regproto.h File Reference
#include <config.h>
#include `r_regalloc.h`
Functions
char * BANK_NAME (int type)
char * CLASS_NAME (int rclass)
R_Reg * R_add_macro_register (int vreg_id, int mac, int type, int rclass)
R_Reg * R_add_register (int vreg_id, int type, double weight, int def)
void R_allocate_virtual_registers (L_Func *fn)
void R_compute_dataflow_info (L_Func *fn)
void R_compute_live_ranges (L_Func *fn, L_Region *region)
void R_construct_interference_graph (L_Func *fn, L_Region *region)
int R_conv_rclass_to_Lclass (int rclass)
int R_conv_type_to_Ltype (int type)
void R_determine_available_macros (void)
void R_determine_reserved_registers (Set *reserved_resource, Set *constrained_resource, int *constrained_array, R_Reg *vreg)
int R_find_free_vreg (void)
R_Arc * R_find_interference (R_Reg *vreg1, R_Reg *vreg2)
Set R_find_reserved_resource (Set reserved_resource, int neighbor[], int num_neighbor)
int R_init_pa_set (void)
int R_Ltype_to_Rtype (int type)
void R_print_interference_graph (void)
void R_print_parm_configuration (void)
void R_process_cb (L_Cb *cb)
void R_process_cb_for_spilling (L_Func *fn, L_Cb *cb)
Set R_process_illegal_register_attr (L_Attr *attr)
int R_register_allocation_sep (L_Func *fn, Parm_Macro_List *command_line_macro_list, int *int_swap_space_size, int *fp_swap_space_size, int *pred_swap_space_size)
int R_register_allocation (L_Func *fn, Parm_Macro_List *command_line_macro_list)
void R_register_saving_convention_selection (L_Func *fn, L_Region *region)
void R_remove_interference (R_Reg *vreg1, R_Reg *vreg2)
R_Reg * R_reset_vreg_list (R_Reg *vregList)
void R_sort_vreg_list (void)
int R_spill_loc (int type)
void R_analyze_bank_overlap (void)
void R_define_physical_bank_with_rot (int rclass, int type, int num_reg, int reg_size, int overlap, int *reg_array, Set *used, int num_rot_reg, int first_reg_rot, int num_rot_reg_alloc)
void R_define_physical_bank (int rclass, int type, int num_reg, int reg_size, int overlap, int *reg_array, Set *used)
int R_find_free_register (R_Reg *vreg, Set reserved_resource, int final)
int R_find_free_register_in_bank (R_Physical_Bank *reg_bank, Set reserved_resource, R_Reg *vreg)
Set R_build_rotating_reg_set (L_Func *)
void R_get_rot_regs (L_Func *, int *, int *, int *, int *, int *, int *, int *, int *)
int R_get_rot_reg_alloc_multiple (int)
int R_get_rot_reg_max_alloc (int)
void R_print_bank_configuration (void)
void R_reset_register_stacks (void)
int R_smallest_overlapping_bank (int type, int rclass)
void R_virtual_to_machine_conversion (void)
void R_add_load (L_Region *region, L_Cb *fromCb, L_Cb *toCb, R_Reg *vreg, L_Region_Regmap *regmap)
void R_add_store (L_Region *region, L_Cb *fromCb, L_Cb *toCb, R_Reg *vreg, L_Region_Regmap *regmap)
L_Region * R_assemble_region (L_Func *fn)
void R_disassemble_region (L_Func *fn)
void R_determine_allocation_constraints (L_Region *region)
double R_determine_reconcile_cost (L_Region *region, R_Reg *vreg, double *store_cost, double *load_cost)
void R_determine_region_flybys (L_Region *region)
int R_find_base_from_phys_reg (int phys_reg, int type, int rclass)
void R_init_flow_hash_tbl (L_Func *fn)
int R_init_spill_stack (L_Region *region, int *fp_spill_stack, int *int_spill_stack, int *pred_spill_stack)
void R_insert_reconciliation_code (L_Func *fn, L_Region *region)
void R_reconcile_allocated_region (L_Region *region)
void R_unmap_physical_registers (L_Region *region)
void R_update_alloc_state (L_Region *region)
void R_update_region_spill_stack (L_Region *region)
int R_number_of_registers (int type, int caller_save, int macro)
int R_register_overlap (int type1, int type2)
int R_size_of_register (int type)
void R_handle_unallocatable_vreg (L_Func *fn, R_Reg *vreg, Stack *vreg_stack)
int R_insert_jsr_spill_fill_code (L_Func *fn, int *int_jsr_swap_space, int *fp_jsr_swap_space, int *pred_jsr_swap_space)
int R_insert_spill_code_after (L_Cb *cb, L_Oper *oper, L_Oper *spill)
int R_insert_spill_code_before (L_Cb *cb, L_Oper *oper, L_Oper *spill)
void R_insert_spill_fill_code (L_Region *region)
void R_regalloc_version (void)
void R_disassemble_regions (L_Func *fn)
void R_print_live_ranges (FILE *)
int R_find_rotating_register (R_Reg *, Set, int)
Function Documentation
char* BANK_NAME (int type)
char* CLASS_NAME (int rclass)
void R_add_load (L_Region * region, L_Cb * fromCb, L_Cb * toCb, R_Reg * vreg, L_Region_Regmap * regmap)
Definition at line 723 of file r_region_ext.c.
References R_Reg::base_index, _reconcile_block::branch, findRCB(), _reconcile_block::flow, _reconcile_block::fromCb, R_Reg::index, _reconcile_block::load_loc, _reconcile_block::loads, _reconcile_block::location, newRCB(), _reconcile_block::nextRCB, NULL, O_fill_reg(), R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_SPILL_CODE, rcbList, R_Reg::rclass, Set_add(), Set_in(), R_Reg::spill_loc, _reconcile_block::toCb, and R_Reg::type.
Referenced by R_reconcile_allocated_region().
R_Reg* R_add_macro_register (int vreg_id, int mac, int type, int rclass)
Definition at line 576 of file r_regalloc.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_pa_set, R_Physical_Bank::reg_size, Set_add(), and VREG.
Referenced by R_determine_available_macros().
R_Reg* R_add_register (int vreg_id, int type, double weight, int def)
Definition at line 406 of file r_regalloc.c.
References BANK_NAME(), R_Reg::def_weight, R_Reg::index, M_HP_PLAYDOH_MCODE, M_model, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_Ltype_to_Rtype(), R_new_reg(), R_POINTER, R_PREDICATE, R_PREFER_SPILL, R_Reg::ref_weight, R_Reg::type, and VREG.
Referenced by R_cbsplit_spilled_live_range(), R_determine_region_flybys(), R_isplit_spilled_live_range(), R_process_cb(), and R_process_cb_for_spilling().
void R_add_store (L_Region * region, L_Cb * fromCb, L_Cb * toCb, R_Reg * vreg, L_Region_Regmap * regmap)
Definition at line 651 of file r_region_ext.c.
References R_Reg::base_index, _reconcile_block::branch, findRCB(), _reconcile_block::flow, _reconcile_block::fromCb, R_Reg::index, _reconcile_block::location, newRCB(), _reconcile_block::nextRCB, NULL, O_spill_reg(), R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_SPILL_CODE, rcbList, R_Reg::rclass, Set_add(), Set_in(), R_Reg::spill_loc, _reconcile_block::store_loc, _reconcile_block::stores, _reconcile_block::toCb, and R_Reg::type.
Referenced by R_reconcile_allocated_region().
void R_allocate_virtual_registers (L_Func * fn)
Definition at line 2914 of file r_regalloc.c.
References R_Reg::base_index, R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::flags, Free_Stack(), Heap_Create(), Heap_Dispose(), Heap_ExtractTop(), Heap_Insert(), HEAP_MAX, Heap_Top(), R_Reg::index, New_Stack(), R_Reg::nextReg, NULL, Pop(), R_Reg::priority, Push_Top(), R_allocate_unconstrained_virtual_registers(), R_bank, R_CALLEE, R_CALLER, R_determine_reserved_registers(), R_find_free_register(), R_find_rotating_register(), R_handle_unallocatable_vreg(), R_n_vreg, R_Print_Coloring_Stats, R_prune_interference_graph(), R_Prune_Interference_Graph, R_REGION_CONSTRAINED, R_reset_register_stacks(), R_SPILLED, R_UNCONSTRAINED, R_vreg, R_Reg::rclass, R_Reg::rotating, Set_dispose(), Set_print(), Set_union(), R_Reg::size, and R_Reg::type.
Referenced by R_register_allocation_sep().
void R_analyze_bank_overlap (void)
Definition at line 239 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, Clear_Stack(), R_Physical_Bank::defined, NULL, R_Physical_Bank::overlap, R_Physical_Bank::overlap_cnt, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_global_overlap, R_INT, R_invalid_bank_overlap(), R_MAX, R_MAX_BANK, R_max_overlap_size, R_NUM_TYPES, R_OVERLAP_INT, R_OVERLAP_PREDICATE, R_POINTER, R_PREDICATE, R_QUAD, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, stack, and R_Physical_Bank::type.
Referenced by R_register_allocation_sep().
L_Region* R_assemble_region (L_Func * fn)
Definition at line 1390 of file r_region_ext.c.
References NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
Set R_build_rotating_reg_set (L_Func *)
Definition at line 883 of file r_regalloc.c.
References NULL, R_get_rot_regs(), and Set_add().
Referenced by R_register_allocation_sep().
void R_compute_dataflow_info (L_Func * fn)
Referenced by R_register_allocation_sep().
void R_compute_live_ranges (L_Func * fn, L_Region * region)
Referenced by R_register_allocation_sep().
void R_construct_interference_graph (L_Func * fn, L_Region * region)
Referenced by R_register_allocation_sep().
int R_conv_rclass_to_Lclass (int rclass)
Definition at line 2018 of file r_regalloc.c.
References R_CALLEE, R_CALLER, and R_MACRO_CALLER.
Referenced by R_add_load(), R_add_store(), R_insert_jsr_spill_fill_code(), R_insert_spill_fill_code(), and R_spill_all_virtual_registers().
int R_conv_type_to_Ltype (int type)
Definition at line 1994 of file r_regalloc.c.
References M_native_int_register_ctype(), R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, R_PREDICATE, and R_QUAD.
Referenced by R_add_load(), R_add_store(), R_cbsplit_spilled_live_range(), R_insert_jsr_spill_fill_code(), and R_isplit_spilled_live_range().
void R_define_physical_bank (int rclass, int type, int num_reg, int reg_size, int overlap, int * reg_array, Set * used)
Definition at line 219 of file r_regbank.c.
References R_define_physical_bank_with_rot().
void R_define_physical_bank_with_rot (int rclass, int type, int num_reg, int reg_size, int overlap, int * reg_array, Set * used, int num_rot_reg, int first_reg_rot, int num_rot_reg_alloc)
Definition at line 95 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, CALLOC, R_Physical_Bank::defined, R_Physical_Bank::mask, R_Physical_Bank::max, NULL, R_Physical_Bank::num_reg, R_Physical_Bank::num_rot_reg, R_Physical_Bank::num_rot_reg_alloc, R_Physical_Bank::overlap, R_bank, R_BTR, R_CALLEE, R_CALLER, R_DOUBLE, R_FLOAT, R_INT, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_MAX_BANK, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_POINTER, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_POINTER, R_PREDICATE, R_QUAD, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, R_Physical_Bank::rot_reg_ofs, R_Physical_Bank::type, and R_Physical_Bank::used_reg.
Referenced by R_define_physical_bank().
void R_determine_allocation_constraints (L_Region * region)
Definition at line 278 of file r_region_ext.c.
References R_Reg::constraints, R_Reg::flags, R_Reg::index, NULL, R_buf, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_REGION_CONSTRAINED, Set_2array(), Set_add(), Set_dispose(), Set_print(), Set_union_acc(), and VREG.
Referenced by R_register_allocation_sep().
void R_determine_available_macros (void)
Definition at line 647 of file r_regalloc.c.
References R_Physical_Bank::defined, R_Macro::id, R_Physical_Bank::num_reg, R_add_macro_register(), R_avail_macro, R_bank, R_find_free_vreg(), R_jsr_def_macro, R_Macro_Allocation, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_n_avail_macro, R_n_jsr_def_macro, R_NUM_TYPES, R_TYPE_INC, R_Physical_Bank::reg_size, R_Macro::type, _Arc::type, and R_Macro::vreg_id.
Referenced by R_register_allocation_sep().
double R_determine_reconcile_cost (L_Region * region, R_Reg * vreg, double * store_cost, double * load_cost)
Definition at line 455 of file r_region_ext.c.
References R_Reg::flags, _reconcile_block::flow, R_Reg::index, NULL, R_LIVE_OUTSIDE_REGION, and Set_in().
void R_determine_region_flybys (L_Region * region)
Definition at line 102 of file r_region_ext.c.
References R_Reg::flags, NULL, R_add_register(), R_buf, R_PREALLOCATED_FLYBY, R_Region, Set_2array(), R_Reg::spill_loc, and VREG.
Referenced by R_register_allocation_sep().
void R_determine_reserved_registers (Set * reserved_resource, Set * constrained_resource, int * constrained_array, R_Reg * vreg)
Definition at line 1931 of file r_regalloc.c.
References R_Reg::index, R_Reg::interfere, R_Arc::lr, R_Arc::next, NULL, R_buf, R_Region, R_REGION_CONSTRAINED, Set_add(), and VREG.
Referenced by R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), and R_isplit_spilled_live_range().
void R_disassemble_region (L_Func * fn)
void R_disassemble_regions (L_Func * fn)
Definition at line 1433 of file r_region_ext.c.
int R_find_base_from_phys_reg (int phys_reg, int type, int rclass)
Definition at line 144 of file r_region_ext.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_map, and R_Physical_Bank::reg_size.
Referenced by R_unmap_physical_registers().
int R_find_free_register (R_Reg * vreg, Set reserved_resource, int final)
Definition at line 889 of file r_regbank.c.
References BANK_NAME(), R_Reg::callee_benefit, R_Reg::caller_benefit, R_Physical_Bank::defined, R_Reg::flags, R_Reg::index, NULL, R_bank, R_CALLEE, R_CALLER, R_find_free_register_in_bank(), R_Macro_Allocation, R_MACRO_CALLEE, R_MACRO_CALLER, R_PREFER_SPILL, R_Region, R_REGION_CONSTRAINED, R_Reg::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, Set_in(), and R_Reg::type.
Referenced by R_allocate_unconstrained_virtual_registers(), R_allocate_virtual_registers(), R_isplit_spilled_live_range(), and R_spill_all_virtual_registers().
int R_find_free_register_in_bank (R_Physical_Bank * reg_bank, Set reserved_resource, R_Reg * vreg)
Definition at line 482 of file r_regbank.c.
References R_Physical_Bank::alloc_init, R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, BANK_NAME(), R_Physical_Bank::base_index, CLASS_NAME(), Delete_Stack(), init, M_arch, M_X86, R_Physical_Bank::mask, R_Reg::nth_rot_reg, NULL, R_Physical_Bank::num_rot_reg, R_Physical_Bank::overlap_cnt, Pop(), Push_Bot(), R_bank, R_FLOAT, R_get_rot_regs(), R_NUM_TYPES, R_Round_Robin_Allocation, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, R_Physical_Bank::res_inc, R_Physical_Bank::rot_reg_ofs, R_Reg::rotating, Set_in(), Stack_Elmt_Data(), Stack_Find(), Stack_Find_Next(), Stack_Print(), Stack_Ptr_Reset(), Stack_Top(), R_Reg::type, and R_Physical_Bank::type.
Referenced by R_find_free_register(), and R_find_rotating_register().
int R_find_free_vreg (void)
Definition at line 480 of file r_regalloc.c.
Referenced by R_cbsplit_spilled_live_range(), R_determine_available_macros(), and R_isplit_spilled_live_range().
R_Arc* R_find_interference (R_Reg * vreg1, R_Reg * vreg2)
Set R_find_reserved_resource (Set reserved_resource, int neighbor[], int num_neighbor)
int R_find_rotating_register (R_Reg *, Set, int)
Definition at line 1010 of file r_regbank.c.
References BANK_NAME(), R_Reg::callee_benefit, R_Reg::caller_benefit, R_Physical_Bank::defined, R_Reg::index, O_locate_rot_reg_bank(), R_bank, R_CALLEE, R_CALLER, R_find_free_register_in_bank(), R_Reg::rclass, and R_Reg::type.
Referenced by R_allocate_virtual_registers().
int R_get_rot_reg_alloc_multiple (int)
Definition at line 1304 of file r_regbank.c.
References R_Physical_Bank::num_rot_reg, R_Physical_Bank::num_rot_reg_alloc, R_bank, R_CALLEE, R_CALLER, and R_Ltype_to_Rtype().
int R_get_rot_reg_max_alloc (int)
Definition at line 1323 of file r_regbank.c.
References R_Physical_Bank::num_rot_reg, R_bank, R_CALLEE, R_CALLER, and R_Ltype_to_Rtype().
Referenced by R_get_rot_regs().
void R_get_rot_regs (L_Func *, int *, int *, int *, int *, int *, int *, int *, int *)
Definition at line 923 of file r_regalloc.c.
References M_arch, M_native_int_register_ctype(), M_TAHOE, NULL, and R_get_rot_reg_max_alloc().
Referenced by R_build_rotating_reg_set(), R_find_free_register_in_bank(), and R_virtual_to_machine_conversion().
void R_handle_unallocatable_vreg (L_Func * fn, R_Reg * vreg, Stack * vreg_stack)
Definition at line 406 of file r_regspill.c.
References R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::flags, R_Reg::index, R_Reg::interfere, L_free(), R_Reg::live_range, R_Arc::lr, R_Arc::next, NULL, R_Reg::priority, R_alloc_interference_arc, R_CALLER, R_CB_SPLIT, R_cbsplit_spilled_live_range(), R_INSTR_SPLIT, R_Invariant_Vreg_Priorities, R_isplit_spilled_live_range(), R_MCB_PRELOAD, R_Prevent_MCB_Preload_Spills, R_Region, R_remove_interference(), R_spill_loc(), R_SPILLED, R_Reg::rclass, R_Reg::ref_instr, Set_dispose(), Set_intersect_empty(), Set_size(), R_Reg::spill_loc, and R_Reg::type.
Referenced by R_allocate_virtual_registers().
void R_init_flow_hash_tbl (L_Func * fn)
Definition at line 81 of file r_region_ext.c.
References _reconcile_block::flow, flowHashTbl, HashTable_insert(), and NULL.
int R_init_pa_set (void)
Referenced by R_register_allocation_sep().
int R_init_spill_stack (L_Region * region, int * fp_spill_stack, int * int_spill_stack, int * pred_spill_stack)
Definition at line 1320 of file r_region_ext.c.
References NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
int R_insert_jsr_spill_fill_code (L_Func * fn, int * int_jsr_swap_space, int * fp_jsr_swap_space, int * pred_jsr_swap_space)
Definition at line 1077 of file r_regspill.c.
References CALLOC, R_Reg::flags, fp_spill_stack, _Set::id, R_Reg::index, int_spill_stack, ld_cnt, ld_wgt, List_next(), List_size(), List_start(), R_Reg::live_range, M_arch, M_TAHOE, MALLOC, R_Reg::nextReg, NULL, O_fill_reg(), O_pred_restore_operation(), O_pred_save_operation(), O_spill_reg(), R_Reg::phys_reg, pred_spill_stack, R_bank, R_BTR, R_CALLEE, R_CALLER, R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_DOUBLE, R_FLOAT, R_insert_spill_code_after(), R_insert_spill_code_before(), R_INT, R_jsr_defines_vreg(), R_jsr_list, R_JSR_SAVE_CODE, R_last_jsr_in_cb(), R_MACRO_CALLER, R_Minimize_Spill_Fill, R_POINTER, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_PREDICATE, R_QUAD, R_spill_loc(), R_SPILLED, R_used_between_jsrs(), R_vreg, R_Reg::rclass, Set_2array(), Set_add(), Set_copy(), Set_delete(), Set_dispose(), Set_in(), Set_size(), Set_subtract(), R_Reg::spill_loc, st_cnt, st_wgt, TAHOE_INT_REG_BASE, TAHOE_PRED_REG_BASE, total_caller_weight, R_Reg::type, R_Physical_Bank::used_reg, and VREG.
Referenced by R_register_allocation_sep().
void R_insert_reconciliation_code (L_Func * fn, L_Region * region)
Definition at line 794 of file r_region_ext.c.
References _reconcile_block::flow, freeRCB(), _reconcile_block::fromCb, _reconcile_block::loads, M_arch, M_HPPA, _reconcile_block::nextRCB, NULL, O_jump_oper(), rcbList, _reconcile_block::stores, _reconcile_block::toCb, and total_region_spill_weight.
Referenced by R_register_allocation_sep().
int R_insert_spill_code_after (L_Cb * cb, L_Oper * oper, L_Oper * spill)
Definition at line 557 of file r_regspill.c.
Referenced by R_insert_jsr_spill_fill_code(), and R_spill_all_virtual_registers().
int R_insert_spill_code_before (L_Cb * cb, L_Oper * oper, L_Oper * spill)
Definition at line 540 of file r_regspill.c.
References NULL.
Referenced by R_insert_jsr_spill_fill_code(), R_insert_spill_fill_code(), and R_spill_all_virtual_registers().
void R_insert_spill_fill_code (L_Region * region)
Definition at line 721 of file r_regspill.c.
References NULL, O_fill_reg(), R_conv_rclass_to_Lclass(), R_in_physical_register(), R_insert_spill_code_before(), R_max_bank_offset(), R_register_contents, R_SPILL_CODE, R_SPILLED, and VREG.
Referenced by R_register_allocation_sep().
int R_Ltype_to_Rtype (int type)
Definition at line 2035 of file r_regalloc.c.
References R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, and R_PREDICATE.
Referenced by R_add_register(), R_get_rot_reg_alloc_multiple(), R_get_rot_reg_max_alloc(), R_number_of_registers(), R_process_illegal_register_attr(), R_register_overlap(), R_size_of_register(), and R_unmap_physical_registers().
int R_number_of_registers (int type, int caller_save, int macro)
Definition at line 72 of file r_regquery.c.
References R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_CALLEE, R_CALLER, R_Ltype_to_Rtype(), R_Macro_Allocation, R_MACRO_CALLEE, and R_MACRO_CALLER.
void R_print_bank_configuration (void)
Definition at line 1101 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, BANK_NAME(), R_Physical_Bank::base_index, CLASS_NAME(), R_Physical_Bank::defined, NULL, R_Physical_Bank::num_reg, R_Physical_Bank::num_rot_reg, R_Physical_Bank::overlap, R_Physical_Bank::overlap_cnt, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_MACRO_CALLEE, R_MACRO_CALLER, R_map, R_MAX_BANK, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_POINTER, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_POINTER, R_PREDICATE, R_QUAD, R_TYPE_INC, R_Physical_Bank::rclass, R_Physical_Bank::reg_size, Stack_Print(), and R_Physical_Bank::type.
Referenced by R_register_allocation_sep().
void R_print_interference_graph (void)
void R_print_live_ranges (FILE *)
void R_print_parm_configuration (void)
Definition at line 315 of file r_regalloc.c.
References ON_OFF, R_Macro_Allocation, R_Print_Allocation, R_Print_Bank_Configuration, R_Print_Class_Selection, R_Print_Coloring_Stats, R_Print_Live_Ranges, R_Print_Parm_Configuration, R_Prune_Interference_Graph, R_Region_Based_Allocation, R_Spill_Everything, and R_Utilize_Profile_Info.
Referenced by R_register_allocation_sep().
void R_process_cb (L_Cb * cb)
Definition at line 1028 of file r_regalloc.c.
References R_Reg::def_instr, FALSE, R_Reg::flags, _Set::id, R_Reg::intf_vreg, List_insert_last(), R_Reg::live_range, M_arch, M_HP_PLAYDOH_MCODE, M_HPPA, M_model, M_X86, NULL, op_flag_set(), R_add_register(), R_avail_macro, R_buf, R_CURRENT_VREG, R_extend_set, R_issue_time(), R_jsr_list, R_MATCHING_MACRO, R_MCB_PRELOAD, R_oper_set, R_PA_HACK, R_Prevent_MCB_Preload_Spills, R_process_illegal_register_attr(), R_Region_Based_Allocation, R_rts, R_Same_Cycle_Anti_Deps_Interference, R_Schedule_Invariant_Alloc, R_Reg::ref_cbs, R_Reg::ref_instr, Set_2array(), Set_add(), Set_dispose(), Set_union_acc(), TRUE, and VREG.
Referenced by R_register_allocation_sep().
void R_process_cb_for_spilling (L_Func * fn, L_Cb * cb)
Definition at line 1425 of file r_regalloc.c.
References NULL, and R_add_register().
Referenced by R_register_allocation_sep().
Set R_process_illegal_register_attr (L_Attr * attr)
Definition at line 738 of file r_regalloc.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, NULL, R_Physical_Bank::num_reg, R_bank, R_CALLEE, R_CALLER, R_Ltype_to_Rtype(), R_map, R_Physical_Bank::reg_size, Set_add(), and VREG.
Referenced by R_process_cb().
void R_reconcile_allocated_region (L_Region * region)
Definition at line 934 of file r_region_ext.c.
References R_Reg::base_index, R_Reg::flags, R_Reg::index, NULL, R_add_load(), R_add_store(), R_buf, R_PREALLOCATED_MACRO, R_SPILLED, rcbList, Set_2array(), and VREG.
Referenced by R_register_allocation_sep().
void R_regalloc_version (void)
Definition at line 72 of file r_version.c.
Referenced by R_register_allocation_sep().
int R_register_allocation (L_Func * fn, Parm_Macro_List * command_line_macro_list)
Definition at line 3666 of file r_regalloc.c.
References R_register_allocation_sep().
int R_register_allocation_sep (L_Func * fn, Parm_Macro_List * command_line_macro_list, int * int_swap_space_size, int * fp_swap_space_size, int * pred_swap_space_size)
Definition at line 3676 of file r_regalloc.c.
References fp_spill_stack, int_spill_stack, L_load_parameters_aliased(), M_arch, M_HPPA, NULL, pred_spill_stack, R_allocate_virtual_registers(), R_analyze_bank_overlap(), R_assemble_region(), R_bank, R_build_rotating_reg_set(), R_CALLER, R_compute_dataflow_info(), R_compute_live_ranges(), R_construct_interference_graph(), R_determine_allocation_constraints(), R_determine_available_macros(), R_determine_region_flybys(), R_DOUBLE, R_Init, R_init_pa_set(), R_init_spill_stack(), R_insert_jsr_spill_fill_code(), R_insert_reconciliation_code(), R_insert_spill_fill_code(), R_INT, R_Print_Allocation_Stats, R_print_bank_configuration(), R_Print_Bank_Configuration, R_print_parm_configuration(), R_Print_Parm_Configuration, R_Print_Virtual_Register_Function, R_process_cb(), R_process_cb_for_spilling(), R_read_parm_regalloc(), R_reconcile_allocated_region(), R_regalloc_memory_cleanup(), R_regalloc_memory_init(), R_regalloc_version(), R_Region, R_Region_Based_Allocation, R_register_saving_convention_selection(), R_sort_vreg_list(), R_spill_all_virtual_registers(), R_Spill_Everything, R_unmap_physical_registers(), R_update_alloc_state(), R_update_region_spill_stack(), R_Utilize_Profile_Info, R_virtual_to_machine_conversion(), Set_dispose(), Set_size(), total, total_caller_weight, total_instruction_weight, total_region_spill_weight, total_spill_weight, and R_Physical_Bank::used_reg.
Referenced by R_register_allocation().
int R_register_overlap (int type1, int type2)
Definition at line 124 of file r_regquery.c.
References R_Physical_Bank::defined, R_Physical_Bank::overlap, R_bank, R_CALLER, and R_Ltype_to_Rtype().
void R_register_saving_convention_selection (L_Func * fn, L_Region * region)
Definition at line 1536 of file r_regalloc.c.
References R_Reg::flags, _Set::id, List_next(), List_size(), List_start(), R_Reg::live_range, R_Reg::nextReg, NULL, R_BTR, R_callee_cost(), R_caller_cost(), R_CONTAINS_JSR, R_jsr_list, R_NUM_TYPES, R_PREALLOCATED_MACRO, R_Print_Class_Selection, R_Region_Based_Allocation, R_spill_load_cost(), R_spill_store_cost(), R_vreg, Set_in(), and R_Reg::type.
Referenced by R_register_allocation_sep().
void R_remove_interference (R_Reg * vreg1, R_Reg * vreg2)
Referenced by R_cbsplit_spilled_live_range(), R_handle_unallocatable_vreg(), and R_isplit_spilled_live_range().
void R_reset_register_stacks (void)
Definition at line 434 of file r_regbank.c.
References R_Physical_Bank::alloc_reg, R_Physical_Bank::avail_reg, R_Physical_Bank::base_index, Clear_Stack(), R_Physical_Bank::defined, R_Physical_Bank::num_reg, Push_Bot(), R_bank, R_MAX_BANK, R_Physical_Bank::reg_size, and stack.
Referenced by R_allocate_virtual_registers().
R_Reg* R_reset_vreg_list (R_Reg * vregList)
Definition at line 1469 of file r_regalloc.c.
References R_Reg::base_index, R_Reg::def_instr, R_Reg::flags, R_Reg::live_range, _Arc::next, R_Reg::nextReg, NULL, R_PREALLOCATED_MACRO, R_PREFER_SPILL, R_Reg::rclass, R_Reg::ref_cbs, R_Reg::ref_instr, Set_dispose(), and R_Reg::size.
int R_size_of_register (int type)
Definition at line 113 of file r_regquery.c.
References R_Physical_Bank::defined, R_bank, R_Ltype_to_Rtype(), and R_Physical_Bank::reg_size.
int R_smallest_overlapping_bank (int type, int rclass)
Definition at line 1072 of file r_regbank.c.
References R_Physical_Bank::overlap, R_bank, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_OVERLAP_BTR, R_OVERLAP_DOUBLE, R_OVERLAP_FLOAT, R_OVERLAP_INT, R_OVERLAP_PREDICATE, R_OVERLAP_QUAD, R_PREDICATE, and R_QUAD.
void R_sort_vreg_list (void)
Referenced by R_register_allocation_sep().
int R_spill_loc (int type)
Definition at line 501 of file r_regalloc.c.
References fp_spill_stack, int_spill_stack, M_arch, M_TAHOE, pred_spill_stack, R_BTR, R_DOUBLE, R_FLOAT, R_INT, R_POINTER, and R_PREDICATE.
Referenced by R_handle_unallocatable_vreg(), R_insert_jsr_spill_fill_code(), and R_spill_all_virtual_registers().
void R_unmap_physical_registers (L_Region * region)
Definition at line 174 of file r_region_ext.c.
References INT_Symbol::data, INT_Symbol::next_symbol, NULL, R_buf, R_CALLEE, R_CALLER, R_find_base_from_phys_reg(), R_Ltype_to_Rtype(), R_MACRO_CALLEE, R_MACRO_CALLER, Set_2array(), Set_add(), and Set_dispose().
Referenced by R_register_allocation_sep().
void R_update_alloc_state (L_Region * region)
Definition at line 1178 of file r_region_ext.c.
References R_Reg::flags, R_Reg::nextReg, NULL, R_buf, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_SPILLED, and R_vreg.
Referenced by R_register_allocation_sep().
void R_update_region_spill_stack (L_Region * region)
Definition at line 1369 of file r_region_ext.c.
References fp_spill_stack, int_spill_stack, NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
void R_virtual_to_machine_conversion (void)
Definition at line 1200 of file r_regbank.c.
References BANK_NAME(), R_Physical_Bank::base_index, R_Reg::base_index, CLASS_NAME(), R_Physical_Bank::defined, R_Reg::flags, R_Reg::index, R_Reg::nextReg, NULL, R_Reg::phys_reg, R_Reg::pvreg, R_bank, R_get_rot_regs(), R_map, R_PREALLOCATED_FLYBY, R_Print_Allocation, R_REGION_CONSTRAINED, R_SPILLED, R_vreg, R_Reg::rclass, R_Reg::rotating, Set_add(), R_Reg::spill_loc, R_Reg::type, and R_Physical_Bank::used_reg.
Referenced by R_register_allocation_sep().