r_regspill.c File Reference
#include <config.h>
#include `r_regalloc.h`
#include <machine/m_tahoe.h>
Functions
static void R_renumber_oper_vreg (L_Oper *oper, int fvreg_id, int tvreg_id)
static void R_cbsplit_spilled_live_range (L_Func *fn, R_Reg *vreg, Stack *vreg_stack)
static void R_isplit_spilled_live_range (L_Func *fn, R_Reg *vreg, Stack *vreg_stack)
void R_handle_unallocatable_vreg (L_Func *fn, R_Reg *vreg, Stack *vreg_stack)
int R_insert_spill_code_before (L_Cb *cb, L_Oper *oper, L_Oper *spill)
int R_insert_spill_code_after (L_Cb *cb, L_Oper *oper, L_Oper *spill)
static int R_in_physical_register (int vreg_id, int base, int vreg_type, int vreg_class)
static void R_put_in_physical_register (int vreg_id, int base, int vreg_type, int vreg_class)
static int R_same_register (R_Reg *vreg1, R_Reg *vreg2)
static int R_register_spill_is_required (L_Cb *cb, L_Oper *oper, R_Reg *vreg)
static int R_max_bank_offset (void)
void R_insert_spill_fill_code (L_Region *region)
int R_jsr_defines_vreg (L_Oper *jsr, int vreg_id)
static L_Oper * O_pred_save_operation (L_Operand *pred, L_Operand *dest)
static L_Oper * O_pred_restore_operation (L_Operand *pred, L_Operand *src, ITintmax mask)
static int R_last_jsr_in_cb (L_Oper *jsr)
Determines if a jsr is the last one in a CB.
static int R_used_between_jsrs (int vreg_id, L_Oper *jsr1, L_Oper *jsr2)
Determines if a register is used between two jsrs.
int R_insert_jsr_spill_fill_code (L_Func *fn, int *int_jsr_swap_space, int *fp_jsr_swap_space, int *pred_jsr_swap_space)
Variables
int R_Prevent_MCB_Preload_Spills
Function Documentation
static L_Oper* O_pred_restore_operation (L_Operand * pred, L_Operand * src, ITintmax mask) [static]
Definition at line 975 of file r_regspill.c.
References TAHOE_PRED_BLK_REG, and TAHOEop_MOV_TOPR.
Referenced by R_insert_jsr_spill_fill_code().
static L_Oper* O_pred_save_operation (L_Operand * pred, L_Operand * dest) [static]
Definition at line 961 of file r_regspill.c.
References TAHOE_PRED_BLK_REG, and TAHOEop_MOV_FRPR.
Referenced by R_insert_jsr_spill_fill_code().
static void R_cbsplit_spilled_live_range (L_Func * fn, R_Reg * vreg, Stack * vreg_stack) [static]
Definition at line 121 of file r_regspill.c.
References R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::constraints, R_Reg::flags, _Set::id, R_Reg::illegal_reg, R_Reg::index, R_Reg::interfere, R_Reg::live_range, R_Arc::lr, R_Arc::next, NULL, R_Reg::priority, Push_Top(), R_Reg::pvreg, R_add_interference_arc(), R_add_register(), R_buf, R_CALLER, R_CB_SPLIT, R_conv_type_to_Ltype(), R_find_free_vreg(), R_Invariant_Vreg_Priorities, R_pbuf, R_remove_interference(), R_renumber_oper_vreg(), R_SPILLED, R_Reg::rclass, R_Reg::ref_instr, Set_2array(), Set_add(), Set_copy(), Set_dispose(), Set_intersect_empty(), R_Reg::spill_loc, R_Reg::type, and VREG.
Referenced by R_handle_unallocatable_vreg().
void R_handle_unallocatable_vreg (L_Func * fn, R_Reg * vreg, Stack * vreg_stack)
Definition at line 406 of file r_regspill.c.
References R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::flags, R_Reg::index, R_Reg::interfere, L_free(), R_Reg::live_range, R_Arc::lr, R_Arc::next, NULL, R_Reg::priority, R_alloc_interference_arc, R_CALLER, R_CB_SPLIT, R_cbsplit_spilled_live_range(), R_INSTR_SPLIT, R_Invariant_Vreg_Priorities, R_isplit_spilled_live_range(), R_MCB_PRELOAD, R_Prevent_MCB_Preload_Spills, R_Region, R_remove_interference(), R_spill_loc(), R_SPILLED, R_Reg::rclass, R_Reg::ref_instr, Set_dispose(), Set_intersect_empty(), Set_size(), R_Reg::spill_loc, and R_Reg::type.
Referenced by R_allocate_virtual_registers().
static int R_in_physical_register (int vreg_id, int base, int vreg_type, int vreg_class) [static]
Definition at line 574 of file r_regspill.c.
References R_bank, R_register_contents, and R_Physical_Bank::reg_size.
Referenced by R_insert_spill_fill_code().
int R_insert_jsr_spill_fill_code (L_Func * fn, int * int_jsr_swap_space, int * fp_jsr_swap_space, int * pred_jsr_swap_space)
Definition at line 1077 of file r_regspill.c.
References CALLOC, R_Reg::flags, fp_spill_stack, _Set::id, R_Reg::index, int_spill_stack, ld_cnt, ld_wgt, List_next(), List_size(), List_start(), R_Reg::live_range, M_arch, M_TAHOE, MALLOC, R_Reg::nextReg, NULL, O_fill_reg(), O_pred_restore_operation(), O_pred_save_operation(), O_spill_reg(), R_Reg::phys_reg, pred_spill_stack, R_bank, R_BTR, R_CALLEE, R_CALLER, R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_DOUBLE, R_FLOAT, R_insert_spill_code_after(), R_insert_spill_code_before(), R_INT, R_jsr_defines_vreg(), R_jsr_list, R_JSR_SAVE_CODE, R_last_jsr_in_cb(), R_MACRO_CALLER, R_Minimize_Spill_Fill, R_POINTER, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_PREDICATE, R_QUAD, R_spill_loc(), R_SPILLED, R_used_between_jsrs(), R_vreg, R_Reg::rclass, Set_2array(), Set_add(), Set_copy(), Set_delete(), Set_dispose(), Set_in(), Set_size(), Set_subtract(), R_Reg::spill_loc, st_cnt, st_wgt, TAHOE_INT_REG_BASE, TAHOE_PRED_REG_BASE, total_caller_weight, R_Reg::type, R_Physical_Bank::used_reg, and VREG.
Referenced by R_register_allocation_sep().
int R_insert_spill_code_after (L_Cb * cb, L_Oper * oper, L_Oper * spill)
Definition at line 557 of file r_regspill.c.
Referenced by R_insert_jsr_spill_fill_code(), and R_spill_all_virtual_registers().
int R_insert_spill_code_before (L_Cb * cb, L_Oper * oper, L_Oper * spill)
Definition at line 540 of file r_regspill.c.
References NULL.
Referenced by R_insert_jsr_spill_fill_code(), R_insert_spill_fill_code(), and R_spill_all_virtual_registers().
void R_insert_spill_fill_code (L_Region * region)
Definition at line 721 of file r_regspill.c.
References NULL, O_fill_reg(), R_conv_rclass_to_Lclass(), R_in_physical_register(), R_insert_spill_code_before(), R_max_bank_offset(), R_register_contents, R_SPILL_CODE, R_SPILLED, and VREG.
Referenced by R_register_allocation_sep().
static void R_isplit_spilled_live_range (L_Func * fn, R_Reg * vreg, Stack * vreg_stack) [static]
Definition at line 267 of file r_regspill.c.
References R_Reg::callee_benefit, R_Reg::caller_benefit, R_Reg::constraints, R_Reg::flags, _Set::id, R_Reg::illegal_reg, R_Reg::index, R_Reg::interfere, L_free(), R_Reg::live_range, R_Arc::lr, R_Arc::next, NULL, R_Reg::priority, R_Reg::pvreg, R_add_interference_arc(), R_add_register(), R_alloc_interference_arc, R_buf, R_CALLER, R_conv_type_to_Ltype(), R_determine_reserved_registers(), R_find_free_register(), R_find_free_vreg(), R_INSTR_SPLIT, R_Invariant_Vreg_Priorities, R_remove_interference(), R_renumber_oper_vreg(), R_SPILLED, R_Reg::rclass, R_Reg::ref_instr, Set_2array(), Set_add(), Set_copy(), Set_delete(), Set_dispose(), Set_in(), Set_intersect_empty(), Set_print(), Set_size(), Set_subtract(), R_Reg::spill_loc, and R_Reg::type.
Referenced by R_handle_unallocatable_vreg().
int R_jsr_defines_vreg (L_Oper * jsr, int vreg_id)
Definition at line 940 of file r_regspill.c.
References NULL.
Referenced by R_insert_jsr_spill_fill_code().
static int R_last_jsr_in_cb (L_Oper * jsr) [static]
Determines if a jsr is the last one in a CB.
Parameters:
jsr the jsr oper to inspect
Returns: If jsr is the last jsr in its CB, returns 1. Otherwise, returns 0.
Definition at line 1000 of file r_regspill.c.
Referenced by R_insert_jsr_spill_fill_code().
static int R_max_bank_offset (void) [static]
Definition at line 688 of file r_regspill.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_MAX_BANK, and R_Physical_Bank::reg_size.
Referenced by R_insert_spill_fill_code().
static void R_put_in_physical_register (int vreg_id, int base, int vreg_type, int vreg_class) [static]
Definition at line 587 of file r_regspill.c.
References R_bank, R_register_contents, and R_Physical_Bank::reg_size.
static int R_register_spill_is_required (L_Cb * cb, L_Oper * oper, R_Reg * vreg) [static]
Definition at line 617 of file r_regspill.c.
References R_Reg::flags, R_Reg::index, R_Reg::pvreg, R_CB_SPLIT, R_INSTR_SPLIT, R_n_oper, R_Register_Allocation, R_same_register(), and VREG.
static void R_renumber_oper_vreg (L_Oper * oper, int fvreg_id, int tvreg_id) [static]
Definition at line 72 of file r_regspill.c.
Referenced by R_cbsplit_spilled_live_range(), and R_isplit_spilled_live_range().
static int R_same_register (R_Reg * vreg1, R_Reg * vreg2) [static]
Definition at line 598 of file r_regspill.c.
References R_Reg::base_index, R_bank, R_Reg::rclass, and R_Reg::type.
Referenced by R_register_spill_is_required().
static int R_used_between_jsrs (int vreg_id, L_Oper * jsr1, L_Oper * jsr2) [static]
Determines if a register is used between two jsrs.
Parameters:
vreg_id the register's id (L_Operand->value.r, R_Reg->phys_reg)
jsr1 the first jsr
jsr2 the second jsr
Returns: If any opers between jsr1 and jsr2 use register vreg_id, returns 1. Otherwise, returns 0.
This function is used to try to conservatively spill and fill registers between jsrs. If a register is not used between two jsrs, there's no reason to fill it after the first and spill it before the second. This is particularly important in C++, where almost every operation is a jsr (See bug 323).
Added 11/29/04 REK
Definition at line 1033 of file r_regspill.c.
References NULL.
Referenced by R_insert_jsr_spill_fill_code().
Variable Documentation
int R_Prevent_MCB_Preload_Spills
Definition at line 129 of file r_regalloc.c.
Referenced by R_handle_unallocatable_vreg(), R_process_cb(), and R_read_parm_regalloc().