r_region_ext.c File Reference
#include <config.h>
#include `r_regalloc.h`
Functions
L_Oper * O_jump_oper (int opc, L_Cb *target_cb)
void R_init_flow_hash_tbl (L_Func *fn)
void R_determine_region_flybys (L_Region *region)
int R_find_base_from_phys_reg (int phys_reg, int type, int rclass)
void R_unmap_physical_registers (L_Region *region)
void R_determine_allocation_constraints (L_Region *region)
double R_determine_reconcile_cost (L_Region *region, R_Reg *vreg, double *store_cost, double *load_cost)
static RCB * newRCB ()
static void freeRCB (RCB *rcb)
static RCB * findRCB (L_Cb *fromCb, L_Cb *toCb)
void R_add_store (L_Region *region, L_Cb *fromCb, L_Cb *toCb, R_Reg *vreg, L_Region_Regmap *regmap)
void R_add_load (L_Region *region, L_Cb *fromCb, L_Cb *toCb, R_Reg *vreg, L_Region_Regmap *regmap)
void R_insert_reconciliation_code (L_Func *fn, L_Region *region)
void R_reconcile_allocated_region (L_Region *region)
void R_update_alloc_state (L_Region *region)
int R_init_spill_stack (L_Region *region, int *int_spill_stack, int *fp_spill_stack, int *pred_spill_stack)
void R_update_region_spill_stack (L_Region *region)
L_Region * R_assemble_region (L_Func *fn)
void R_disassemble_regions (L_Func *fn)
Variables
RCB * rcbList = NULL
Function Documentation
static RCB* findRCB (L_Cb * fromCb, L_Cb * toCb) [static]
Definition at line 636 of file r_region_ext.c.
References _reconcile_block::fromCb, _reconcile_block::nextRCB, NULL, rcbList, and _reconcile_block::toCb.
Referenced by R_add_load(), and R_add_store().
static void freeRCB (RCB * rcb) [static]
Definition at line 627 of file r_region_ext.c.
References _reconcile_block::load_loc, Set_dispose(), and _reconcile_block::store_loc.
Referenced by R_insert_reconciliation_code().
static RCB* newRCB () [static]
Definition at line 608 of file r_region_ext.c.
References _reconcile_block::branch, _reconcile_block::flow, _reconcile_block::fromCb, _reconcile_block::load_loc, _reconcile_block::loads, _reconcile_block::location, _reconcile_block::nextRCB, NULL, _reconcile_block::store_loc, _reconcile_block::stores, and _reconcile_block::toCb.
Referenced by R_add_load(), and R_add_store().
L_Oper* O_jump_oper (int opc, L_Cb * target_cb)
Definition at line 93 of file r_stub.c.
void R_add_load (L_Region * region, L_Cb * fromCb, L_Cb * toCb, R_Reg * vreg, L_Region_Regmap * regmap)
Definition at line 723 of file r_region_ext.c.
References R_Reg::base_index, _reconcile_block::branch, findRCB(), _reconcile_block::flow, _reconcile_block::fromCb, R_Reg::index, _reconcile_block::load_loc, _reconcile_block::loads, _reconcile_block::location, newRCB(), _reconcile_block::nextRCB, NULL, O_fill_reg(), R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_SPILL_CODE, rcbList, R_Reg::rclass, Set_add(), Set_in(), R_Reg::spill_loc, _reconcile_block::toCb, and R_Reg::type.
Referenced by R_reconcile_allocated_region().
void R_add_store (L_Region * region, L_Cb * fromCb, L_Cb * toCb, R_Reg * vreg, L_Region_Regmap * regmap)
Definition at line 651 of file r_region_ext.c.
References R_Reg::base_index, _reconcile_block::branch, findRCB(), _reconcile_block::flow, _reconcile_block::fromCb, R_Reg::index, _reconcile_block::location, newRCB(), _reconcile_block::nextRCB, NULL, O_spill_reg(), R_conv_rclass_to_Lclass(), R_conv_type_to_Ltype(), R_SPILL_CODE, rcbList, R_Reg::rclass, Set_add(), Set_in(), R_Reg::spill_loc, _reconcile_block::store_loc, _reconcile_block::stores, _reconcile_block::toCb, and R_Reg::type.
Referenced by R_reconcile_allocated_region().
L_Region* R_assemble_region (L_Func * fn)
Definition at line 1390 of file r_region_ext.c.
References NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
void R_determine_allocation_constraints (L_Region * region)
Definition at line 278 of file r_region_ext.c.
References R_Reg::constraints, R_Reg::flags, R_Reg::index, NULL, R_buf, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_REGION_CONSTRAINED, Set_2array(), Set_add(), Set_dispose(), Set_print(), Set_union_acc(), and VREG.
Referenced by R_register_allocation_sep().
double R_determine_reconcile_cost (L_Region * region, R_Reg * vreg, double * store_cost, double * load_cost)
Definition at line 455 of file r_region_ext.c.
References R_Reg::flags, _reconcile_block::flow, R_Reg::index, NULL, R_LIVE_OUTSIDE_REGION, and Set_in().
void R_determine_region_flybys (L_Region * region)
Definition at line 102 of file r_region_ext.c.
References R_Reg::flags, NULL, R_add_register(), R_buf, R_PREALLOCATED_FLYBY, R_Region, Set_2array(), R_Reg::spill_loc, and VREG.
Referenced by R_register_allocation_sep().
void R_disassemble_regions (L_Func * fn)
Definition at line 1433 of file r_region_ext.c.
References NULL.
int R_find_base_from_phys_reg (int phys_reg, int type, int rclass)
Definition at line 144 of file r_region_ext.c.
References R_Physical_Bank::base_index, R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_map, and R_Physical_Bank::reg_size.
Referenced by R_unmap_physical_registers().
void R_init_flow_hash_tbl (L_Func * fn)
Definition at line 81 of file r_region_ext.c.
References _reconcile_block::flow, flowHashTbl, HashTable_insert(), and NULL.
int R_init_spill_stack (L_Region * region, int * int_spill_stack, int * fp_spill_stack, int * pred_spill_stack)
Definition at line 1320 of file r_region_ext.c.
References NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
void R_insert_reconciliation_code (L_Func * fn, L_Region * region)
Definition at line 794 of file r_region_ext.c.
References _reconcile_block::flow, freeRCB(), _reconcile_block::fromCb, _reconcile_block::loads, M_arch, M_HPPA, _reconcile_block::nextRCB, NULL, O_jump_oper(), rcbList, _reconcile_block::stores, _reconcile_block::toCb, and total_region_spill_weight.
Referenced by R_register_allocation_sep().
void R_reconcile_allocated_region (L_Region * region)
Definition at line 934 of file r_region_ext.c.
References R_Reg::base_index, R_Reg::flags, R_Reg::index, NULL, R_add_load(), R_add_store(), R_buf, R_PREALLOCATED_MACRO, R_SPILLED, rcbList, Set_2array(), and VREG.
Referenced by R_register_allocation_sep().
void R_unmap_physical_registers (L_Region * region)
Definition at line 174 of file r_region_ext.c.
References INT_Symbol::data, INT_Symbol::next_symbol, NULL, R_buf, R_CALLEE, R_CALLER, R_find_base_from_phys_reg(), R_Ltype_to_Rtype(), R_MACRO_CALLEE, R_MACRO_CALLER, Set_2array(), Set_add(), and Set_dispose().
Referenced by R_register_allocation_sep().
void R_update_alloc_state (L_Region * region)
Definition at line 1178 of file r_region_ext.c.
References R_Reg::flags, R_Reg::nextReg, NULL, R_buf, R_PREALLOCATED_FLYBY, R_PREALLOCATED_MACRO, R_SPILLED, and R_vreg.
Referenced by R_register_allocation_sep().
void R_update_region_spill_stack (L_Region * region)
Definition at line 1369 of file r_region_ext.c.
References fp_spill_stack, int_spill_stack, NULL, and R_Region_Based_Allocation.
Referenced by R_register_allocation_sep().
Variable Documentation
RCB* rcbList = NULL
Definition at line 605 of file r_region_ext.c.
Referenced by findRCB(), R_add_load(), R_add_store(), R_insert_reconciliation_code(), and R_reconcile_allocated_region().