r_regquery.c File Reference
#include <config.h>
#include `r_regalloc.h`
Functions
int R_number_of_registers (int type, int caller_save, int macro)
int R_size_of_register (int type)
int R_register_overlap (int type1, int type2)
Function Documentation
int R_number_of_registers (int type, int caller_save, int macro)
Definition at line 72 of file r_regquery.c.
References R_Physical_Bank::defined, R_Physical_Bank::num_reg, R_bank, R_CALLEE, R_CALLER, R_Ltype_to_Rtype(), R_Macro_Allocation, R_MACRO_CALLEE, and R_MACRO_CALLER.
int R_register_overlap (int type1, int type2)
Definition at line 124 of file r_regquery.c.
References R_Physical_Bank::defined, R_Physical_Bank::overlap, R_bank, R_CALLER, and R_Ltype_to_Rtype().
int R_size_of_register (int type)
Definition at line 113 of file r_regquery.c.
References R_Physical_Bank::defined, R_bank, R_Ltype_to_Rtype(), and R_Physical_Bank::reg_size.