r_stub.c File Reference
#include <config.h>
#include <Lcode/l_code.h>
Functions
double R_callee_cost (int lcode_ctype, int leaf, int callee_allocated)
double R_caller_cost (int lcode_ctype, int leaf)
double R_spill_load_cost (int lcode_ctype)
double R_spill_store_cost (int lcode_ctype)
void O_jump_oper (int opc, L_Cb *dst)
L_Oper * O_spill_reg (int reg, int type, L_Operand *operand, int spill_offset, L_Operand **pred, int type_flag)
L_Oper * O_fill_reg (int reg, int type, L_Operand *operand, int fill_offset, L_Operand **pred, int type_flag)
R_Physical_Bank * O_locate_rot_reg_bank (L_Func *fn, struct R_Reg *vreg)
Function Documentation
L_Oper* O_fill_reg (int reg, int type, L_Operand * operand, int fill_offset, L_Operand ** pred, int type_flag)
Definition at line 108 of file r_stub.c.
References NULL.
Referenced by R_add_load(), R_insert_jsr_spill_fill_code(), R_insert_spill_fill_code(), and R_spill_all_virtual_registers().
void O_jump_oper (int opc, L_Cb * dst)
Definition at line 93 of file r_stub.c.
struct R_Physical_Bank* O_locate_rot_reg_bank (L_Func * fn, struct R_Reg * vreg)
Definition at line 122 of file r_stub.c.
References NULL.
Referenced by R_find_rotating_register().
L_Oper* O_spill_reg (int reg, int type, L_Operand * operand, int spill_offset, L_Operand ** pred, int type_flag)
Definition at line 98 of file r_stub.c.
References NULL.
Referenced by R_add_store(), R_insert_jsr_spill_fill_code(), and R_spill_all_virtual_registers().
double R_callee_cost (int lcode_ctype, int leaf, int callee_allocated)
Definition at line 69 of file r_stub.c.
Referenced by R_register_saving_convention_selection().
double R_caller_cost (int lcode_ctype, int leaf)
Definition at line 75 of file r_stub.c.
Referenced by R_register_saving_convention_selection().
double R_spill_load_cost (int lcode_ctype)
Definition at line 81 of file r_stub.c.
Referenced by R_register_saving_convention_selection().
double R_spill_store_cost (int lcode_ctype)
Definition at line 87 of file r_stub.c.
Referenced by R_register_saving_convention_selection().