region.c File Reference
#include <config.h>
#include <library/heap.h>
#include <library/stack.h>
#include `global_cfg.h`
#include `region.h`
Functions
void initRegion (void)
Region * newRegion (void)
void freeRegion (Region *region)
int inRegion (Region *region, Node *node)
void AddMember (Region *region, Node *node)
void addRegionMemberCb (Region *region, L_Cb *cb)
void printRegionCbs (Region *region)
Variables
L_Alloc_Pool * Region_pool = NULL
L_Alloc_Pool * RegionMember_pool = NULL
L_Alloc_Pool * RegionAlloc_pool = NULL
HashTable regionNodeHashTbl
Function Documentation
void AddMember (Region * region, Node * node)
Definition at line 135 of file region.c.
References _NodeCb, _NodeId, _RegionMemberNode, HashTable_insert(), L_alloc(), region::memberList, region::members, region_member::nextMember, node, NULL, RegionMember_pool, regionNodeHashTbl, and Set_add().
void addRegionMemberCb (Region * region, L_Cb * cb)
Definition at line 156 of file region.c.
References region_member::cb, HashTable_insert(), _Set::id, L_alloc(), region_member::member, region::memberList, region::members, region_member::nextMember, NULL, RegionMember_pool, regionNodeHashTbl, and Set_add().
void freeRegion (Region * region)
Definition at line 113 of file region.c.
References L_free(), region::memberList, region::members, region_member::nextMember, NULL, Region_pool, RegionMember_pool, and Set_dispose().
void initRegion (void)
Definition at line 75 of file region.c.
References HashTable_create(), L_create_alloc_pool(), NULL, Region_pool, RegionAlloc_pool, RegionMember_pool, and regionNodeHashTbl.
int inRegion (Region * region, Node * node)
Definition at line 129 of file region.c.
References _NodeCb, region::members, node, and Set_in().
Region* newRegion (void)
Definition at line 91 of file region.c.
References region::allocList, region::enterList, region::exitList, region::flags, HashTable_create(), region::id, L_alloc(), region::memberList, region::members, region::nextRegion, NULL, region::rclass, Region_pool, region::regionAllocHashTbl, region::seed, and region::weight.
void printRegionCbs (Region * region)
Definition at line 177 of file region.c.
References _RegionMemberCb, region::id, region::memberList, region_member::nextMember, NULL, and region::weight.
Variable Documentation
L_Alloc_Pool* Region_pool = NULL
Definition at line 69 of file region.c.
Referenced by freeRegion(), initRegion(), and newRegion().
L_Alloc_Pool* RegionAlloc_pool = NULL
Definition at line 71 of file region.c.
Referenced by initRegion().
L_Alloc_Pool* RegionMember_pool = NULL
Definition at line 70 of file region.c.
Referenced by AddMember(), addRegionMemberCb(), freeRegion(), and initRegion().
HashTable regionNodeHashTbl
Definition at line 72 of file region.c.
Referenced by AddMember(), addRegionMemberCb(), and initRegion().