region.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `global_cfg.h`
Data Structures
struct region_member
struct region_alloc
struct region
Defines
#define _RegionMemberNode(a) (a) $\rightarrow$ member.node
#define _RegionMemberCb(a) (a) $\rightarrow$ member.cb
#define REGION_ALLOCATED_FIRST 0x01
#define REGION_SPILLED_FIRST 0x02
#define _RegionAllocVregId(a) (a) $\rightarrow$ vregId
#define _RegionAllocBaseIndex(a) (a) $\rightarrow$ baseIndex
#define _RegionAllocPhysReg(a) (a) $\rightarrow$ physReg
#define _RegionAllocClass(a) (a) $\rightarrow$ rclass
#define _RegionAllocFlags(a) (a) $\rightarrow$ flags
#define _RegionAllocSpillLocation(a) (a) $\rightarrow$ spillLocation
#define _RegionAllocNext(a) (a) $\rightarrow$ nextAlloc
#define REGION_ALLOCATED 0x1
#define _RegionFlags(a) (a) $\rightarrow$ flags
#define inRegionCb(region, cb) (Set_in((region) $\rightarrow$ members,(cb) $\rightarrow$ id))
Typedefs
typedef region_member RegionMember
typedef region_alloc RegionAlloc
typedef region Region
Enumerations
enum {
ACYCLIC,
CYCLIC,
INSTRS_FUNCTION,
BLOCKS_FUNCTION,
INSTRS_REGION,
BLOCKS_REGION,
SINGLE_BLOCK,
SINGLE_PATH,
MULTIPLE_PATH,
SINGLE_BLOCK_LOOP,
SINGLE_PATH_LOOP,
MULTIPLE_PATH_LOOP,
MULTIPLE_ENTRY,
UNCLASSIFIED,
ZERO_WEIGHT,
FUNCTION_COUNT,
REGION_CLASSES
 }
enum {
SINGLE_BLOCK_NO_EPI,
SINGLE_PATH_NO_EPI,
MULTIPLE_PATH_NO_EPI,
SINGLE_PATH_EPI,
MULTIPLE_PATH_EPI,
NON_PROLOGUE,
PROLOGUE_REGION_CLASSES
 }
Functions
Region * newRegion (void)
void freeRegion (Region *region)
int inRegion (Region *region, Node *node)
void AddMember (Region *region, Node *node)
L_Loop * loopFromHeader (Func *func, Node *node)
L_Loop * loopFromBackEdge (Func *func, Node *node)
Node * bestSuccessor (Node *node, Node *seed, Set limit)
Node * bestPredecessor (Node *node, Node *seed)
Region * regionFormation (Func *funcList)
double RegionWeight (Region *region)
void regionSelection (Func *funcList)
int isRegionEntry (Region *region, Node *node)
L_Loop * regionLoop (Region *region)
int regionSuperblock (Region *region, L_Loop *loop)
int regionTrace (Region *region, L_Loop *loop)
int regionHyperblock (Region *region, L_Loop *loop)
int regionHyperblockTrace (Region *region, L_Loop *loop)
int regionMultipleEntry (Region *region, L_Loop *loop)
int classifyRegion (Region *region)
void PrintRegion (Region *region)
void initRegionStatistics (void)
void printRegionStatistics (void)
int breakup (char *buf, char **fields)
void readRegionStatistics (void)
void writeRegionStatistics (void)
void calcRegionStats (Region *regions)
void R_disassemble_regions (L_Func *fn)
Variables
L_Alloc_Pool * Region_pool
L_Alloc_Pool * RegionMember_pool
L_Alloc_Pool * RegionAlloc_pool
HashTable regionNodeHashTbl
char * RegionClass []
char * PrologueRegionClass []
int RegionStatistics []
FILE * RegionStatFile
Set loopBackEdges
Set loopHeaders
char * regionInputFormat
char * regionCFGFormat
int regionOutputCFG
int regionSelectRegions
int regionSelectDebug
int printRegions
int printRegionJSR
int printStatistics
int writeRegions
Define Documentation
#define _RegionAllocBaseIndex(a) (a) $\rightarrow$ baseIndex
Definition at line 96 of file region.h.
#define _RegionAllocClass(a) (a) $\rightarrow$ rclass
Definition at line 98 of file region.h.
#define _RegionAllocFlags(a) (a) $\rightarrow$ flags
Definition at line 99 of file region.h.
#define _RegionAllocNext(a) (a) $\rightarrow$ nextAlloc
Definition at line 101 of file region.h.
#define _RegionAllocPhysReg(a) (a) $\rightarrow$ physReg
Definition at line 97 of file region.h.
#define _RegionAllocSpillLocation(a) (a) $\rightarrow$ spillLocation
Definition at line 100 of file region.h.
#define _RegionAllocVregId(a) (a) $\rightarrow$ vregId
Definition at line 95 of file region.h.
#define _RegionFlags(a) (a) $\rightarrow$ flags
Definition at line 127 of file region.h.
#define _RegionMemberCb(a) (a) $\rightarrow$ member.cb
Definition at line 78 of file region.h.
Referenced by printRegionCbs().
#define _RegionMemberNode(a) (a) $\rightarrow$ member.node
Definition at line 77 of file region.h.
Referenced by AddMember().
#define inRegionCb(region, cb) (Set_in((region) $\rightarrow$ members,(cb) $\rightarrow$ id))
Definition at line 129 of file region.h.
#define REGION_ALLOCATED 0x1
Definition at line 125 of file region.h.
#define REGION_ALLOCATED_FIRST 0x01
Definition at line 92 of file region.h.
#define REGION_SPILLED_FIRST 0x02
Definition at line 93 of file region.h.
Typedef Documentation
typedef struct region
 Region
typedef struct region_alloc
 RegionAlloc
typedef struct region_member
 RegionMember
Enumeration Type Documentation
anonymous enum
Enumerator:
ACYCLIC
CYCLIC
INSTRS_FUNCTION
BLOCKS_FUNCTION
INSTRS_REGION
BLOCKS_REGION
SINGLE_BLOCK
SINGLE_PATH
MULTIPLE_PATH
SINGLE_BLOCK_LOOP
SINGLE_PATH_LOOP
MULTIPLE_PATH_LOOP
MULTIPLE_ENTRY
UNCLASSIFIED
ZERO_WEIGHT
FUNCTION_COUNT
REGION_CLASSES
Definition at line 158 of file region.h.
anonymous enum
Enumerator:
SINGLE_BLOCK_NO_EPI
SINGLE_PATH_NO_EPI
MULTIPLE_PATH_NO_EPI
SINGLE_PATH_EPI
MULTIPLE_PATH_EPI
NON_PROLOGUE
PROLOGUE_REGION_CLASSES
Definition at line 182 of file region.h.
Function Documentation
void AddMember (Region * region, Node * node)
Definition at line 135 of file region.c.
References _NodeCb, _NodeId, _RegionMemberNode, HashTable_insert(), L_alloc(), region::memberList, region::members, region_member::nextMember, node, NULL, RegionMember_pool, regionNodeHashTbl, and Set_add().
Node* bestPredecessor (Node * node, Node * seed)
Node* bestSuccessor (Node * node, Node * seed, Set limit)
int breakup (char * buf, char ** fields)
void calcRegionStats (Region * regions)
int classifyRegion (Region * region)
void freeRegion (Region * region)
Definition at line 113 of file region.c.
References L_free(), region::memberList, region::members, region_member::nextMember, NULL, Region_pool, RegionMember_pool, and Set_dispose().
void initRegionStatistics (void)
int inRegion (Region * region, Node * node)
Definition at line 129 of file region.c.
References _NodeCb, region::members, node, and Set_in().
int isRegionEntry (Region * region, Node * node)
L_Loop* loopFromBackEdge (Func * func, Node * node)
L_Loop* loopFromHeader (Func * func, Node * node)
Region* newRegion (void)
Definition at line 91 of file region.c.
References region::allocList, region::enterList, region::exitList, region::flags, HashTable_create(), region::id, L_alloc(), region::memberList, region::members, region::nextRegion, NULL, region::rclass, Region_pool, region::regionAllocHashTbl, region::seed, and region::weight.
void PrintRegion (Region * region)
void printRegionStatistics (void)
void R_disassemble_regions (L_Func * fn)
Definition at line 1433 of file r_region_ext.c.
References NULL.
void readRegionStatistics (void)
Region* regionFormation (Func * funcList)
int regionHyperblock (Region * region, L_Loop * loop)
int regionHyperblockTrace (Region * region, L_Loop * loop)
L_Loop* regionLoop (Region * region)
int regionMultipleEntry (Region * region, L_Loop * loop)
void regionSelection (Func * funcList)
int regionSuperblock (Region * region, L_Loop * loop)
int regionTrace (Region * region, L_Loop * loop)
double RegionWeight (Region * region)
void writeRegionStatistics (void)
Variable Documentation
Set loopBackEdges
Set loopHeaders
int printRegionJSR
int printRegions
int printStatistics
char* PrologueRegionClass[]
L_Alloc_Pool* Region_pool
Definition at line 69 of file region.c.
Referenced by freeRegion(), initRegion(), and newRegion().
L_Alloc_Pool* RegionAlloc_pool
Definition at line 71 of file region.c.
Referenced by initRegion().
char* regionCFGFormat
char* RegionClass[]
char* regionInputFormat
L_Alloc_Pool* RegionMember_pool
Definition at line 70 of file region.c.
Referenced by AddMember(), addRegionMemberCb(), freeRegion(), and initRegion().
HashTable regionNodeHashTbl
Definition at line 72 of file region.c.
Referenced by AddMember(), addRegionMemberCb(), and initRegion().
int regionOutputCFG
int regionSelectDebug
int regionSelectRegions
FILE* RegionStatFile
int RegionStatistics[]
int writeRegions