convert_hmdes.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <library/md.h>
#include <machine/hmdes.h>
Functions
void L_punt (char *fmt,...)
void print_usage ()
MD_Entry * add_entry (MD *md, char *section_name, char *entry_name)
MD_Entry * find_entry_if_exists (MD *md, char *section_name, char *entry_name)
MD_Entry * find_entry (MD *md, char *section_name, char *entry_name)
void add_value_to_field (MD_Entry *entry, char *field_name, int index, int type, void *value)
void create_empty_field (MD_Entry *entry, char *field_name)
void append_value_to_field (MD_Entry *entry, char *field_name, int type, void *value)
void convert_Parameters (MD *md, Hmdes *hmdes)
int in_set (Hmdes_IO_Set *set, char *name)
int compatable_sets (Hmdes_IO_Set *src_set, Hmdes_IO_Set *target_set)
void convert_format (MD *md, Hmdes *hmdes)
MD_Entry * add_op_lat (MD *md, char *prefix, int latency)
void convert_latency (MD *md, Hmdes *hmdes)
void convert_res_tables (MD *md, Hmdes *hmdes)
void convert_operations (MD *md, Hmdes *hmdes)
void convert_hmdes (MD *md, Hmdes *hmdes)
int main (int argc, char **argv, char **envp)
Variables
Header_File header_table []
int num_header_files
char * program_name
Function Documentation
MD_Entry* add_entry (MD * md, char * section_name, char * entry_name)
Definition at line 101 of file convert_hmdes.c.
References entry, L_punt(), MD_find_entry, MD_find_section, MD_new_entry(), and NULL.
Referenced by add_op_lat(), convert_format(), convert_latency(), convert_operations(), convert_Parameters(), and convert_res_tables().
MD_Entry* add_op_lat (MD * md, char * prefix, int latency)
Definition at line 445 of file convert_hmdes.c.
References add_entry(), append_value_to_field(), entry, find_entry_if_exists(), MD_INT, and NULL.
Referenced by convert_latency().
void add_value_to_field (MD_Entry * entry, char * field_name, int index, int type, void * value)
Definition at line 162 of file convert_hmdes.c.
References entry, L_punt(), MD_DOUBLE, MD_find_field, MD_find_field_decl, MD_INT, MD_LINK, MD_new_field(), MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_STRING, and NULL.
Referenced by convert_operations().
void append_value_to_field (MD_Entry * entry, char * field_name, int type, void * value)
Definition at line 231 of file convert_hmdes.c.
References entry, L_punt(), MD_Field::max_element_index, MD_DOUBLE, MD_find_field, MD_find_field_decl, MD_INT, MD_LINK, MD_new_field(), MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_STRING, and NULL.
Referenced by add_op_lat(), convert_format(), convert_latency(), convert_operations(), convert_Parameters(), and convert_res_tables().
int compatable_sets (Hmdes_IO_Set * src_set, Hmdes_IO_Set * target_set)
Definition at line 329 of file convert_hmdes.c.
References hmdes_io_set_st::head, in_set(), hmdes_reg_file_st::name, hmdes_io_set_st::name, hmdes_io_node_st::next, NULL, and hmdes_io_node_st::reg_file.
Referenced by convert_format().
void convert_format (MD * md, Hmdes * hmdes)
Definition at line 352 of file convert_hmdes.c.
References add_entry(), append_value_to_field(), compatable_sets(), hmdes_io_item_st::dest, find_entry(), hmdes_io_set_st::head, msymbol_table_st::head, hmdes_st::IO_items, hmdes_st::IO_sets, hmdes_st::max_dest_operands, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, MD_LINK, hmdes_io_item_st::name, hmdes_reg_file_st::name, hmdes_io_set_st::name, hmdes_io_node_st::next, msymbol_st::next_linear, NULL, hmdes_io_item_st::pred, msymbol_st::ptr, hmdes_io_node_st::reg_file, and hmdes_io_item_st::src.
Referenced by convert_hmdes().
void convert_hmdes (MD * md, Hmdes * hmdes)
Definition at line 832 of file convert_hmdes.c.
References convert_format(), convert_latency(), convert_operations(), convert_Parameters(), and convert_res_tables().
Referenced by main().
void convert_latency (MD * md, Hmdes * hmdes)
Definition at line 469 of file convert_hmdes.c.
References add_entry(), add_op_lat(), append_value_to_field(), hmdes_latency_st::dest, msymbol_table_st::head, L_punt(), hmdes_st::latencies, hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, MD_LINK, hmdes_latency_st::name, msymbol_st::next_linear, NULL, hmdes_latency_st::pred, msymbol_st::ptr, hmdes_latency_st::src, hmdes_latency_st::sync_dest, and hmdes_latency_st::sync_src.
Referenced by convert_hmdes().
void convert_operations (MD * md, Hmdes * hmdes)
Definition at line 739 of file convert_hmdes.c.
References add_entry(), add_value_to_field(), append_value_to_field(), hmdes_operation_node_st::class, find_entry(), hmdes_flag_list_st::head, hmdes_operation_class_st::head, hmdes_operation_st::head, msymbol_table_st::head, hmdes_class_node_st::io_item, hmdes_class_node_st::latency, MD_LINK, hmdes_operation_node_st::mdes_flags, hmdes_flag_st::name, hmdes_res_list_st::name, hmdes_latency_st::name, hmdes_io_item_st::name, hmdes_operation_st::name, hmdes_flag_st::next, hmdes_class_node_st::next, hmdes_operation_node_st::next, msymbol_st::next_linear, NULL, hmdes_operation_st::op_flags, hmdes_st::operations, msymbol_st::ptr, and hmdes_class_node_st::res_list.
Referenced by convert_hmdes().
void convert_Parameters (MD * md, Hmdes * hmdes)
Definition at line 282 of file convert_hmdes.c.
References add_entry(), append_value_to_field(), header_table, L_punt(), MD_STRING, MDES_SUPERSCALAR, MDES_VLIW, name, num_header_files, and hmdes_st::processor_model.
Referenced by convert_hmdes().
void convert_res_tables (MD * md, Hmdes * hmdes)
Definition at line 555 of file convert_hmdes.c.
References add_entry(), append_value_to_field(), create_empty_field(), hmdes_res_node_st::end_usage, find_entry(), find_entry_if_exists(), hmdes_res_node_st::head, hmdes_res_list_st::head, hmdes_resource_st::head, msymbol_table_st::head, MD_INT, MD_LINK, hmdes_res_list_st::name, hmdes_resource_st::name, hmdes_res_option_st::next, hmdes_res_node_st::next, hmdes_res_sub_st::next, msymbol_st::next_linear, NULL, hmdes_res_node_st::num_options, msymbol_st::ptr, hmdes_st::res_lists, hmdes_res_option_st::resource, hmdes_st::resources, hmdes_res_list_st::slot_options, hmdes_res_node_st::start_usage, hmdes_res_option_st::subscript, and hmdes_res_sub_st::subscript.
Referenced by convert_hmdes().
void create_empty_field (MD_Entry * entry, char * field_name)
Definition at line 208 of file convert_hmdes.c.
References entry, L_punt(), MD_find_field, MD_find_field_decl, MD_new_field(), and NULL.
Referenced by convert_res_tables().
MD_Entry* find_entry (MD * md, char * section_name, char * entry_name)
Definition at line 141 of file convert_hmdes.c.
References entry, L_punt(), MD_find_entry, MD_find_section, and NULL.
Referenced by convert_format(), convert_operations(), and convert_res_tables().
MD_Entry* find_entry_if_exists (MD * md, char * section_name, char * entry_name)
Definition at line 123 of file convert_hmdes.c.
References L_punt(), MD_find_entry, MD_find_section, and NULL.
Referenced by add_op_lat(), and convert_res_tables().
int in_set (Hmdes_IO_Set * set, char * name)
Definition at line 308 of file convert_hmdes.c.
References hmdes_io_set_st::head, node, and NULL.
Referenced by compatable_sets().
void L_punt (char * fmt, ...)
Definition at line 73 of file convert_hmdes.c.
Referenced by add_entry(), add_value_to_field(), append_value_to_field(), convert_latency(), convert_Parameters(), create_empty_field(), find_entry(), find_entry_if_exists(), and main().
int main (int argc, char ** argv, char ** envp)
Definition at line 847 of file convert_hmdes.c.
References convert_hmdes(), create_hmdes(), H_punt(), L_punt(), MD_check_md(), MD_print_md(), MD_print_md_declarations(), MD_read_md(), NULL, print_usage(), and program_name.
void print_usage ()
Definition at line 88 of file convert_hmdes.c.
References program_name.
Referenced by main().
Variable Documentation
Header_File header_table[]
Referenced by convert_Parameters().
int num_header_files
Referenced by convert_Parameters().
char* program_name
Definition at line 70 of file convert_hmdes.c.
Referenced by main(), and print_usage().