l_dependence.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `l_dependence.h`
#include `l_schedule.h`
Defines
#define DEP_MEM_OPERAND 0
#define DEP_CNT_OPERAND 1
#define DEP_SYNC_OPERAND 2
#define DEP_VLIW_OPERAND 3
Functions
static void L_read_parm_ldep (Parm_Parse_Info *ppi)
void Ldep_init (Parm_Macro_List *command_line_macro_list)
void Ldep_change_ctl_dep_level_same_iter (L_Oper *load_oper)
int Ldep_invariant_oper (L_Cb *cb, L_Oper *load_oper)
static int Ldep_uncond_def (L_Operand *def_operand)
static int Ldep_defs_may_reorder (Dep_Operand *dep_dest1, L_Operand *dest2)
void Ldep_mark_safe_invariant (L_Func *fn)
int L_safe_operands (L_Operand *reg_src, L_Operand *reg_dest, L_Operand *immed_src, L_Operand *immed_dest)
int L_safe_load (L_Oper *load_oper, L_Oper *br_oper, L_Cb *cb)
void Ldep_mark_safe (L_Func *fn)
int L_is_always_safe (L_Oper *oper)
int L_is_ctl_dep_safe (L_Oper *oper, L_Oper *br, L_Cb *cb)
int L_safe_divide (L_Oper *oper, L_Oper *br, L_Cb *cb)
int L_safe_rem (L_Oper *oper, L_Oper *br, L_Cb *cb)
int L_is_complex_safe (L_Oper *oper, L_Oper *br, L_Cb *cb)
static void L_init_dep_hash_table ()
static void L_reset_dep_hash_table ()
static Dep_Operand * L_find_dep_operand (L_Operand *operand)
static Dep_Operand * L_find_another_dep_operand (Dep_Operand *dep)
static void L_insert_dep_operand (int index, L_Operand *operand, L_Oper *oper)
static void L_remove_dep_operand (Dep_Operand *dep_operand)
static void L_add_input_dep (int type, int dist, int from_index, int to_index, L_Oper *from_oper, L_Oper *to_oper, int omega)
static void L_add_output_dep (int type, int dist, int from_index, int to_index, L_Oper *from_oper, L_Oper *to_oper, int omega)
void L_add_dep (int type, int dist, int from_index, int to_index, L_Oper *from_oper, L_Oper *to_oper, int omega)
L_Dep * L_find_dep (L_Dep *dep, L_Oper *from_oper, L_Oper *to_oper, int type)
L_Dep * L_remove_dep (L_Dep *dep, int *count, int type, L_Oper *from_oper, L_Oper *to_oper)
void L_remove_dep_pair (int type, L_Oper *from_oper, L_Oper *to_oper)
static int L_same_register_operand (L_Operand *op1, L_Operand *op2)
static int L_jsr_independent_oper (L_Oper *jsr, L_Oper *oper)
static int L_safe_to_move_below_branch (L_Cb *cb, L_Oper *oper, L_Oper *branch)
static int L_safe_to_move_below_branch_hb (L_Cb *cb, L_Oper *oper, L_Oper *branch)
static int L_safe_to_move_above_branch (L_Cb *cb, L_Oper *oper, L_Oper *branch)
static int L_safe_to_move_above_branch_hb (L_Cb *cb, L_Oper *oper, L_Oper *branch)
static void L_compute_register_dependence (L_Cb *cb, int prepass)
static void L_compute_cross_iter_register_dependence (L_Cb *cb, int prepass)
static void L_compute_memory_dependence (L_Cb *cb)
static void L_compute_cross_iter_memory_dependence (L_Cb *cb)
static void L_compute_control_dependence (L_Cb *cb, int prepass)
static void L_compute_synchronization_dependence (L_Cb *cb)
static void L_compute_hb_register_dependence (L_Cb *cb, int prepass)
static void L_compute_hb_memory_dependence (L_Cb *cb)
static void L_compute_hb_control_dependence (L_Cb *cb, int prepass)
static void L_compute_hb_synchronization_dependence (L_Cb *cb)
static void L_compute_hb_blk_dependence (L_Cb *cb)
static void L_resolve_dependence (L_Cb *cb)
static void L_allow_concurrent_issue (L_Cb *cb)
void L_compute_mem_copy_dependences (L_Cb *cb)
void L_compute_dependence_level (L_Cb *cb)
void L_delete_dependence_info (Dep_Info *dep_info)
void L_delete_dependence_graph (L_Cb *cb)
void L_print_dependences (FILE *F, L_Dep *dep)
void L_print_dependence_graph (FILE *F, L_Cb *cb)
Dep_Info * L_new_dep_info ()
void L_insert_program_order_dependence (L_Cb *cb)
void L_build_dependence_graph (L_Cb *cb, int prepass, int mode)
Variables
int Ldep_option = 0
int Ldep_resolve_dependences = 0
int Ldep_resolve_all_memory_dep = 0
int Ldep_resolve_all_control_dep = 0
int Ldep_resolve_all_anti_output_dep = 0
int Ldep_add_copy_check_dependences = 0
int Ldep_add_copy_back_dependences = 0
int Ldep_allow_concurrent_issue = 0
int Ldep_remove_jsr_dependences = 0
int Ldep_add_pred_hardware_arcs = 1
int Ldep_allow_upward_code_perc = 0
int Ldep_branch_perc_limit = -1
int Ldep_except_branch_perc_limit = -1
int Ldep_ignore_live_out = 0
int Ldep_allow_speculative_stores = 0
int Ldep_allow_downward_code_perc = 0
int Ldep_print_dependence_graph = 0
int Ldep_remove_always_safe = 0
int Ldep_remove_ctl_dep_safe = 0
int Ldep_remove_complex_safe = 0
int Ldep_use_iter = 1
int Ldep_hb_keep_branch_order = 0
int Ldep_program_order = 0
int Ldep_check_profiled_memory_dependences = 1
int Ldep_allow_lat_dangles_into_jsrs = 1
int Ldep_debug_memory_disambiguation = 0
int Ldep_debug_concurrent_issue = 0
int Ldep_debug_upward_code_perc = 0
int Ldep_debug_downward_code_perc = 0
int(*) L_conflicting_operands ()
L_Alloc_Pool * L_alloc_dep = NULL
L_Alloc_Pool * L_alloc_dep_info = NULL
L_Alloc_Pool * L_alloc_dep_operand = NULL
static Set loop_set
static int Ldep_mode = LDEP_MODE_ACYCLIC
static Dep_Operand * Dep_Hash_Table [DEP_HASH_TABLE_SIZE]
Define Documentation
#define DEP_CNT_OPERAND 1
Definition at line 121 of file l_dependence.c.
Referenced by L_add_check_to_check_dep(), L_compute_control_dependence(), L_compute_hb_control_dependence(), L_mcb_insert_check(), and wbs_insert_check().
#define DEP_MEM_OPERAND 0
Definition at line 120 of file l_dependence.c.
Referenced by L_compute_cross_iter_memory_dependence(), L_compute_hb_memory_dependence(), L_compute_memory_dependence(), and L_insert_program_order_dependence().
#define DEP_SYNC_OPERAND 2
Definition at line 122 of file l_dependence.c.
Referenced by L_compute_hb_synchronization_dependence(), L_compute_mem_copy_dependences(), L_compute_register_dependence(), and L_compute_synchronization_dependence().
#define DEP_VLIW_OPERAND 3
Definition at line 123 of file l_dependence.c.
Referenced by L_allow_concurrent_issue().
Function Documentation
void L_add_dep (int type, int dist, int from_index, int to_index, L_Oper * from_oper, L_Oper * to_oper, int omega)
Definition at line 807 of file l_dependence.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, L_add_input_dep(), L_add_output_dep(), L_Dep::next_dep, NULL, L_Dep::omega, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by L_add_check_to_check_dep(), L_mcb_insert_check(), and wbs_insert_check().
static void L_add_input_dep (int type, int dist, int from_index, int to_index, L_Oper * from_oper, L_Oper * to_oper, int omega) [static]
Definition at line 768 of file l_dependence.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, L_alloc(), L_alloc_dep, L_Dep::next_dep, L_Dep::omega, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by L_add_dep(), L_compute_control_dependence(), L_compute_cross_iter_memory_dependence(), L_compute_cross_iter_register_dependence(), L_compute_hb_blk_dependence(), L_compute_hb_control_dependence(), L_compute_hb_memory_dependence(), L_compute_hb_register_dependence(), L_compute_hb_synchronization_dependence(), L_compute_mem_copy_dependences(), L_compute_memory_dependence(), L_compute_register_dependence(), L_compute_synchronization_dependence(), and L_insert_program_order_dependence().
static void L_add_output_dep (int type, int dist, int from_index, int to_index, L_Oper * from_oper, L_Oper * to_oper, int omega) [static]
Definition at line 788 of file l_dependence.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, L_alloc(), L_alloc_dep, L_Dep::next_dep, L_Dep::omega, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by L_add_dep(), L_compute_control_dependence(), L_compute_cross_iter_memory_dependence(), L_compute_cross_iter_register_dependence(), L_compute_hb_blk_dependence(), L_compute_hb_control_dependence(), L_compute_hb_memory_dependence(), L_compute_hb_register_dependence(), L_compute_hb_synchronization_dependence(), L_compute_mem_copy_dependences(), L_compute_memory_dependence(), L_compute_register_dependence(), L_compute_synchronization_dependence(), and L_insert_program_order_dependence().
static void L_allow_concurrent_issue (L_Cb * cb) [static]
Definition at line 4084 of file l_dependence.c.
References DEP_INFO, DEP_VLIW_OPERAND, L_Dep::distance, L_Dep::from_index, Dep_Info::input_dep, L_DEP_REG_FLOW, L_DEP_VLIW, L_find_dep(), Ldep_debug_concurrent_issue, NULL, Dep_Info::output_dep, L_Dep::to_index, and L_Dep::type.
Referenced by L_build_dependence_graph().
void L_build_dependence_graph (L_Cb * cb, int prepass, int mode)
Definition at line 4530 of file l_dependence.c.
References DEP_INFO, L_allow_concurrent_issue(), L_compute_control_dependence(), L_compute_cross_iter_memory_dependence(), L_compute_cross_iter_register_dependence(), L_compute_dependence_level(), L_compute_hb_blk_dependence(), L_compute_hb_control_dependence(), L_compute_hb_memory_dependence(), L_compute_hb_register_dependence(), L_compute_hb_synchronization_dependence(), L_compute_mem_copy_dependences(), L_compute_memory_dependence(), L_compute_register_dependence(), L_compute_synchronization_dependence(), L_delete_dependence_info(), L_insert_program_order_dependence(), L_new_dep_info(), L_print_dependence_graph(), L_resolve_dependence(), Ldep_allow_concurrent_issue, Ldep_mode, LDEP_MODE_CYCLIC, Ldep_print_dependence_graph, Ldep_program_order, Ldep_resolve_dependences, and NULL.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
static void L_compute_control_dependence (L_Cb * cb, int prepass) [static]
Definition at line 2237 of file l_dependence.c.
References DEP_CNT_OPERAND, DEP_INFO, L_add_input_dep(), L_add_output_dep(), L_DEP_CNT, L_jsr_independent_oper(), L_safe_to_move_below_branch(), Ldep_allow_downward_code_perc, Ldep_remove_jsr_dependences, Lsched_processor_model, Dep_Info::next, NULL, and Dep_Info::oper.
Referenced by L_build_dependence_graph().
static void L_compute_cross_iter_memory_dependence (L_Cb * cb) [static]
Definition at line 2082 of file l_dependence.c.
References DEP_INFO, DEP_MEM_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_MEM_OUTPUT, Ldep_check_profiled_memory_dependences, Ldep_debug_memory_disambiguation, Dep_Info::level, Dep_Info::next, NULL, and Dep_Info::oper.
Referenced by L_build_dependence_graph().
static void L_compute_cross_iter_register_dependence (L_Cb * cb, int prepass) [static]
Definition at line 1683 of file l_dependence.c.
References DEP_INFO, Dep_Operand::index, L_add_input_dep(), L_add_output_dep(), L_conflicting_operands, L_DEP_REG_FLOW, L_DEP_REG_OUTPUT, L_find_dep_operand(), L_init_dep_hash_table(), L_insert_dep_operand(), L_remove_dep_operand(), L_same_register_operand(), NULL, and Dep_Operand::oper.
Referenced by L_build_dependence_graph().
void L_compute_dependence_level (L_Cb * cb)
Definition at line 4359 of file l_dependence.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_oper, Dep_Info::input_dep, Dep_Info::level, L_Dep::next_dep, NULL, and L_Dep::omega.
Referenced by L_build_dependence_graph().
static void L_compute_hb_blk_dependence (L_Cb * cb) [static]
Definition at line 3879 of file l_dependence.c.
References DEP_INFO, L_add_input_dep(), L_add_output_dep(), L_DEP_REG_FLOW, L_DEP_REG_OUTPUT, Ldep_uncond_def(), and NULL.
Referenced by L_build_dependence_graph().
static void L_compute_hb_control_dependence (L_Cb * cb, int prepass) [static]
Definition at line 3467 of file l_dependence.c.
References DEP_CNT_OPERAND, DEP_INFO, L_add_input_dep(), L_add_output_dep(), L_DEP_CNT, L_jsr_independent_oper(), L_safe_to_move_below_branch_hb(), Ldep_allow_downward_code_perc, Ldep_remove_jsr_dependences, Dep_Info::next, NULL, and Dep_Info::oper.
Referenced by L_build_dependence_graph().
static void L_compute_hb_memory_dependence (L_Cb * cb) [static]
Definition at line 3354 of file l_dependence.c.
References DEP_INFO, DEP_MEM_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_MEM_OUTPUT, Ldep_check_profiled_memory_dependences, Ldep_debug_memory_disambiguation, Dep_Info::next, NULL, and Dep_Info::oper.
Referenced by L_build_dependence_graph().
static void L_compute_hb_register_dependence (L_Cb * cb, int prepass) [static]
Definition at line 2670 of file l_dependence.c.
References DEP_INFO, L_add_input_dep(), L_add_output_dep(), L_conflicting_operands, L_DEP_REG_FLOW, L_find_another_dep_operand(), L_find_dep_operand(), L_init_dep_hash_table(), and NULL.
Referenced by L_build_dependence_graph().
static void L_compute_hb_synchronization_dependence (L_Cb * cb) [static]
Definition at line 3814 of file l_dependence.c.
References DEP_INFO, DEP_SYNC_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_SYNC, and NULL.
Referenced by L_build_dependence_graph().
void L_compute_mem_copy_dependences (L_Cb * cb)
Definition at line 4227 of file l_dependence.c.
References DEP_SYNC_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_SYNC, Ldep_add_copy_back_dependences, Ldep_add_copy_check_dependences, and NULL.
Referenced by L_build_dependence_graph().
static void L_compute_memory_dependence (L_Cb * cb) [static]
Definition at line 1980 of file l_dependence.c.
References DEP_INFO, DEP_MEM_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_MEM_OUTPUT, Ldep_check_profiled_memory_dependences, Ldep_debug_memory_disambiguation, Dep_Info::next, NULL, and Dep_Info::oper.
Referenced by L_build_dependence_graph().
static void L_compute_register_dependence (L_Cb * cb, int prepass) [static]
Definition at line 1211 of file l_dependence.c.
References DEP_INFO, DEP_SYNC_OPERAND, Dep_Operand::index, L_add_input_dep(), L_add_output_dep(), L_conflicting_operands, L_DEP_REG_FLOW, L_DEP_REG_OUTPUT, L_find_dep_operand(), L_init_dep_hash_table(), Ldep_allow_lat_dangles_into_jsrs, NULL, and Dep_Operand::oper.
Referenced by L_build_dependence_graph().
static void L_compute_synchronization_dependence (L_Cb * cb) [static]
Definition at line 2599 of file l_dependence.c.
References DEP_INFO, DEP_SYNC_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_SYNC, and NULL.
Referenced by L_build_dependence_graph().
void L_delete_dependence_graph (L_Cb * cb)
Definition at line 4406 of file l_dependence.c.
References DEP_INFO, L_delete_dependence_info(), and NULL.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
void L_delete_dependence_info (Dep_Info * dep_info)
Definition at line 4389 of file l_dependence.c.
References Dep_Info::input_dep, L_alloc_dep, L_alloc_dep_info, L_free(), L_Dep::next_dep, NULL, and Dep_Info::output_dep.
Referenced by L_build_dependence_graph(), L_delete_dependence_graph(), L_mcb_delete_check(), and wbs_delete_check().
static Dep_Operand* L_find_another_dep_operand (Dep_Operand * dep) [static]
Definition at line 694 of file l_dependence.c.
References Dep_Operand::ctype, Dep_Operand::next, NULL, Dep_Operand::type, and Dep_Operand::value.
Referenced by L_compute_hb_register_dependence().
L_Dep* L_find_dep (L_Dep * dep, L_Oper * from_oper, L_Oper * to_oper, int type)
Definition at line 830 of file l_dependence.c.
References L_Dep::from_oper, L_Dep::next_dep, NULL, L_Dep::to_oper, and L_Dep::type.
Referenced by L_allow_concurrent_issue(), and wbs_insert_check().
static Dep_Operand* L_find_dep_operand (L_Operand * operand) [static]
Definition at line 671 of file l_dependence.c.
References Dep_Operand::ctype, DEP_HASH_MASK, Dep_Hash_Table, Dep_Operand::next, NULL, Dep_Operand::type, and Dep_Operand::value.
Referenced by L_compute_cross_iter_register_dependence(), L_compute_hb_register_dependence(), and L_compute_register_dependence().
static void L_init_dep_hash_table () [static]
Definition at line 649 of file l_dependence.c.
References Dep_Hash_Table, DEP_HASH_TABLE_SIZE, and NULL.
Referenced by L_compute_cross_iter_register_dependence(), L_compute_hb_register_dependence(), and L_compute_register_dependence().
static void L_insert_dep_operand (int index, L_Operand * operand, L_Oper * oper) [static]
Definition at line 708 of file l_dependence.c.
References Dep_Operand::ctype, DEP_HASH_MASK, Dep_Hash_Table, Dep_Operand::index, L_alloc(), L_alloc_dep_operand, Ldep_uncond_def(), Dep_Operand::next, NULL, Dep_Operand::oper, Dep_Operand::prev, Dep_Operand::ptype, Dep_Operand::type, Dep_Operand::uncond_def, and Dep_Operand::value.
Referenced by L_compute_cross_iter_register_dependence().
void L_insert_program_order_dependence (L_Cb * cb)
Definition at line 4496 of file l_dependence.c.
References DEP_INFO, DEP_MEM_OPERAND, L_add_input_dep(), L_add_output_dep(), L_DEP_REG_FLOW, and NULL.
Referenced by L_build_dependence_graph().
int L_is_always_safe (L_Oper * oper)
Definition at line 523 of file l_dependence.c.
References Ldep_remove_always_safe.
Referenced by L_safe_to_move_above_branch_hb().
int L_is_complex_safe (L_Oper * oper, L_Oper * br, L_Cb * cb)
Definition at line 618 of file l_dependence.c.
References L_safe_divide(), L_safe_load(), L_safe_rem(), and Ldep_remove_complex_safe.
int L_is_ctl_dep_safe (L_Oper * oper, L_Oper * br, L_Cb * cb)
Definition at line 541 of file l_dependence.c.
References Ldep_remove_ctl_dep_safe, and Ldep_use_iter.
static int L_jsr_independent_oper (L_Oper * jsr, L_Oper * oper) [static]
Definition at line 942 of file l_dependence.c.
References NULL.
Referenced by L_compute_control_dependence(), and L_compute_hb_control_dependence().
Dep_Info* L_new_dep_info ()
Definition at line 4481 of file l_dependence.c.
References DEP_NON_EXCEPTING, Dep_Info::input_dep, L_alloc(), L_alloc_dep_info, Dep_Info::level, Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, Dep_Info::output_dep, and Dep_Info::spec_cond.
Referenced by L_build_dependence_graph(), L_mcb_insert_check(), and wbs_insert_check().
void L_print_dependence_graph (FILE * F, L_Cb * cb)
Definition at line 4457 of file l_dependence.c.
References DEP_INFO, L_print_dependences(), and NULL.
Referenced by L_build_dependence_graph().
void L_print_dependences (FILE * F, L_Dep * dep)
Definition at line 4423 of file l_dependence.c.
References L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, L_DEP_CNT, L_DEP_MEM_ANTI, L_DEP_MEM_FLOW, L_DEP_MEM_OUTPUT, L_DEP_REG_ANTI, L_DEP_REG_FLOW, L_DEP_REG_OUTPUT, L_DEP_SYNC, L_Dep::next_dep, NULL, L_Dep::omega, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by L_print_dependence_graph().
static void L_read_parm_ldep (Parm_Parse_Info * ppi) [static]
Definition at line 138 of file l_dependence.c.
References L_read_parm_b(), L_read_parm_i(), Ldep_add_copy_back_dependences, Ldep_add_copy_check_dependences, Ldep_add_pred_hardware_arcs, Ldep_allow_concurrent_issue, Ldep_allow_downward_code_perc, Ldep_allow_lat_dangles_into_jsrs, Ldep_allow_speculative_stores, Ldep_allow_upward_code_perc, Ldep_branch_perc_limit, Ldep_check_profiled_memory_dependences, Ldep_debug_concurrent_issue, Ldep_debug_downward_code_perc, Ldep_debug_memory_disambiguation, Ldep_debug_upward_code_perc, Ldep_except_branch_perc_limit, Ldep_hb_keep_branch_order, Ldep_ignore_live_out, Ldep_print_dependence_graph, Ldep_program_order, Ldep_remove_always_safe, Ldep_remove_complex_safe, Ldep_remove_ctl_dep_safe, Ldep_remove_jsr_dependences, Ldep_resolve_all_anti_output_dep, Ldep_resolve_all_control_dep, Ldep_resolve_all_memory_dep, Ldep_resolve_dependences, and Ldep_use_iter.
Referenced by Ldep_init().
L_Dep* L_remove_dep (L_Dep * dep, int * count, int type, L_Oper * from_oper, L_Oper * to_oper)
Definition at line 843 of file l_dependence.c.
References L_Dep::from_oper, L_alloc_dep, L_free(), L_Dep::next_dep, NULL, L_Dep::to_oper, and L_Dep::type.
Referenced by L_mcb_delete_check(), L_mcb_insert_check_and_rem_dependences(), L_remove_dep_pair(), L_resolve_dependence(), Lsched_schedule_with_delay_op(), and wbs_delete_check().
static void L_remove_dep_operand (Dep_Operand * dep_operand) [static]
Definition at line 740 of file l_dependence.c.
References DEP_HASH_MASK, Dep_Hash_Table, L_alloc_dep_operand, L_free(), Dep_Operand::next, NULL, Dep_Operand::prev, and Dep_Operand::value.
Referenced by L_compute_cross_iter_register_dependence().
void L_remove_dep_pair (int type, L_Oper * from_oper, L_Oper * to_oper)
Definition at line 892 of file l_dependence.c.
References DEP_INFO, Dep_Info::input_dep, L_remove_dep(), Dep_Info::n_input_dep, Dep_Info::n_output_dep, and Dep_Info::output_dep.
static void L_reset_dep_hash_table () [static]
Definition at line 656 of file l_dependence.c.
References Dep_Hash_Table, DEP_HASH_TABLE_SIZE, L_alloc_dep_operand, L_free(), Dep_Operand::next, and NULL.
static void L_resolve_dependence (L_Cb * cb) [static]
Definition at line 3990 of file l_dependence.c.
References DEP_INFO, Dep_Info::input_dep, L_DEP_CNT, L_DEP_IGNORE_ALL_MEMORY_DEP, L_DEP_IGNORE_CNT_DEP, L_DEP_IGNORE_MEM_ANTI_DEP, L_DEP_IGNORE_MEM_FLOW_DEP, L_DEP_IGNORE_MEM_OUTPUT_DEP, L_DEP_IGNORE_REG_ANTI_DEP, L_DEP_IGNORE_REG_FLOW_DEP, L_DEP_IGNORE_REG_OUTPUT_DEP, L_DEP_MEM_ANTI, L_DEP_MEM_FLOW, L_DEP_MEM_OUTPUT, L_DEP_REG_ANTI, L_DEP_REG_FLOW, L_DEP_REG_OUTPUT, L_remove_dep(), Ldep_option, Ldep_resolve_all_anti_output_dep, Ldep_resolve_all_control_dep, Ldep_resolve_all_memory_dep, Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, and Dep_Info::output_dep.
Referenced by L_build_dependence_graph().
int L_safe_divide (L_Oper * oper, L_Oper * br, L_Cb * cb)
Definition at line 599 of file l_dependence.c.
Referenced by L_is_complex_safe().
int L_safe_load (L_Oper * load_oper, L_Oper * br_oper, L_Cb * cb)
Definition at line 455 of file l_dependence.c.
References L_safe_operands().
Referenced by L_is_complex_safe().
int L_safe_operands (L_Operand * reg_src, L_Operand * reg_dest, L_Operand * immed_src, L_Operand * immed_dest)
Definition at line 437 of file l_dependence.c.
Referenced by L_safe_load().
int L_safe_rem (L_Oper * oper, L_Oper * br, L_Cb * cb)
Definition at line 608 of file l_dependence.c.
Referenced by L_is_complex_safe().
static int L_safe_to_move_above_branch (L_Cb * cb, L_Oper * oper, L_Oper * branch) [static]
Definition at line 1078 of file l_dependence.c.
References DEP_CANT_SPECULATE, DEP_NON_EXCEPTING, DEP_SAFE_STORE, Ldep_allow_speculative_stores, Ldep_ignore_live_out, Ldep_mode, and LDEP_MODE_ACYCLIC.
static int L_safe_to_move_above_branch_hb (L_Cb * cb, L_Oper * oper, L_Oper * branch) [static]
Definition at line 1139 of file l_dependence.c.
References L_is_always_safe(), Ldep_allow_speculative_stores, Ldep_ignore_live_out, Ldep_uncond_def(), and NULL.
static int L_safe_to_move_below_branch (L_Cb * cb, L_Oper * oper, L_Oper * branch) [static]
Definition at line 1000 of file l_dependence.c.
References Ldep_ignore_live_out, Ldep_mode, and LDEP_MODE_ACYCLIC.
Referenced by L_compute_control_dependence().
static int L_safe_to_move_below_branch_hb (L_Cb * cb, L_Oper * oper, L_Oper * branch) [static]
Definition at line 1030 of file l_dependence.c.
References Ldep_ignore_live_out, Ldep_mode, LDEP_MODE_ACYCLIC, and Ldep_uncond_def().
Referenced by L_compute_hb_control_dependence().
static int L_same_register_operand (L_Operand * op1, L_Operand * op2) [static]
Definition at line 918 of file l_dependence.c.
Referenced by L_compute_cross_iter_register_dependence().
void Ldep_change_ctl_dep_level_same_iter (L_Oper * load_oper)
Definition at line 233 of file l_dependence.c.
References NULL.
static int Ldep_defs_may_reorder (Dep_Operand * dep_dest1, L_Operand * dest2) [static]
Definition at line 330 of file l_dependence.c.
References Dep_Operand::ctype, and Dep_Operand::ptype.
void Ldep_init (Parm_Macro_List * command_line_macro_list)
Definition at line 209 of file l_dependence.c.
References L_alloc_dep, L_alloc_dep_info, L_alloc_dep_operand, L_conflicting_operands, L_create_alloc_pool(), L_load_parameters_aliased(), L_read_parm_ldep(), and M_dep_conflicting_operands().
Referenced by Lsched_init().
int Ldep_invariant_oper (L_Cb * cb, L_Oper * load_oper)
Definition at line 282 of file l_dependence.c.
References NULL.
Referenced by Ldep_mark_safe_invariant().
void Ldep_mark_safe (L_Func * fn)
Definition at line 514 of file l_dependence.c.
References Ldep_mark_safe_invariant().
Referenced by Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
void Ldep_mark_safe_invariant (L_Func * fn)
Definition at line 356 of file l_dependence.c.
References Ldep_invariant_oper(), Ldep_remove_always_safe, Ldep_remove_complex_safe, Ldep_remove_ctl_dep_safe, loop_set, NULL, and Set_union_acc().
Referenced by Ldep_mark_safe().
static int Ldep_uncond_def (L_Operand * def_operand) [static]
Definition at line 311 of file l_dependence.c.
References NULL.
Referenced by L_compute_hb_blk_dependence(), L_insert_dep_operand(), L_safe_to_move_above_branch_hb(), and L_safe_to_move_below_branch_hb().
Variable Documentation
Dep_Operand* Dep_Hash_Table[DEP_HASH_TABLE_SIZE] [static]
Definition at line 647 of file l_dependence.c.
Referenced by L_find_dep_operand(), L_init_dep_hash_table(), L_insert_dep_operand(), L_remove_dep_operand(), and L_reset_dep_hash_table().
L_Alloc_Pool* L_alloc_dep = NULL
Definition at line 125 of file l_dependence.c.
Referenced by L_add_input_dep(), L_add_output_dep(), L_delete_dependence_info(), L_remove_dep(), and Ldep_init().
L_Alloc_Pool* L_alloc_dep_info = NULL
Definition at line 126 of file l_dependence.c.
Referenced by L_delete_dependence_info(), L_new_dep_info(), and Ldep_init().
L_Alloc_Pool* L_alloc_dep_operand = NULL
Definition at line 127 of file l_dependence.c.
Referenced by L_insert_dep_operand(), L_remove_dep_operand(), L_reset_dep_hash_table(), and Ldep_init().
int(*) L_conflicting_operands()
Definition at line 118 of file l_dependence.c.
Referenced by L_compute_cross_iter_register_dependence(), L_compute_hb_register_dependence(), L_compute_register_dependence(), and Ldep_init().
int Ldep_add_copy_back_dependences = 0
Definition at line 86 of file l_dependence.c.
Referenced by L_compute_mem_copy_dependences(), and L_read_parm_ldep().
int Ldep_add_copy_check_dependences = 0
Definition at line 85 of file l_dependence.c.
Referenced by L_compute_mem_copy_dependences(), and L_read_parm_ldep().
int Ldep_add_pred_hardware_arcs = 1
Definition at line 91 of file l_dependence.c.
Referenced by L_read_parm_ldep().
int Ldep_allow_concurrent_issue = 0
Definition at line 88 of file l_dependence.c.
Referenced by L_build_dependence_graph(), and L_read_parm_ldep().
int Ldep_allow_downward_code_perc = 0
Definition at line 99 of file l_dependence.c.
Referenced by L_compute_control_dependence(), L_compute_hb_control_dependence(), L_read_parm_ldep(), Lsched_init(), and Lsched_postpass_code_scheduling().
int Ldep_allow_lat_dangles_into_jsrs = 1
Definition at line 112 of file l_dependence.c.
Referenced by L_compute_register_dependence(), and L_read_parm_ldep().
int Ldep_allow_speculative_stores = 0
Definition at line 97 of file l_dependence.c.
Referenced by L_read_parm_ldep(), L_safe_to_move_above_branch(), and L_safe_to_move_above_branch_hb().
int Ldep_allow_upward_code_perc = 0
Definition at line 93 of file l_dependence.c.
Referenced by L_read_parm_ldep(), Lsched_init(), and Lsched_postpass_code_scheduling().
int Ldep_branch_perc_limit = -1
Definition at line 94 of file l_dependence.c.
Referenced by L_read_parm_ldep().
int Ldep_check_profiled_memory_dependences = 1
Definition at line 110 of file l_dependence.c.
Referenced by L_compute_cross_iter_memory_dependence(), L_compute_hb_memory_dependence(), L_compute_memory_dependence(), and L_read_parm_ldep().
int Ldep_debug_concurrent_issue = 0
Definition at line 115 of file l_dependence.c.
Referenced by L_allow_concurrent_issue(), and L_read_parm_ldep().
int Ldep_debug_downward_code_perc = 0
Definition at line 117 of file l_dependence.c.
Referenced by L_read_parm_ldep().
int Ldep_debug_memory_disambiguation = 0
Definition at line 114 of file l_dependence.c.
Referenced by L_compute_cross_iter_memory_dependence(), L_compute_hb_memory_dependence(), L_compute_memory_dependence(), and L_read_parm_ldep().
int Ldep_debug_upward_code_perc = 0
Definition at line 116 of file l_dependence.c.
Referenced by L_read_parm_ldep().
int Ldep_except_branch_perc_limit = -1
Definition at line 95 of file l_dependence.c.
Referenced by L_read_parm_ldep(), and wbs_insert_check().
int Ldep_hb_keep_branch_order = 0
Definition at line 107 of file l_dependence.c.
Referenced by L_read_parm_ldep().
int Ldep_ignore_live_out = 0
Definition at line 96 of file l_dependence.c.
Referenced by L_read_parm_ldep(), L_safe_to_move_above_branch(), L_safe_to_move_above_branch_hb(), L_safe_to_move_below_branch(), and L_safe_to_move_below_branch_hb().
int Ldep_mode = LDEP_MODE_ACYCLIC [static]
Definition at line 131 of file l_dependence.c.
Referenced by L_build_dependence_graph(), L_safe_to_move_above_branch(), L_safe_to_move_below_branch(), and L_safe_to_move_below_branch_hb().
int Ldep_option = 0
Definition at line 80 of file l_dependence.c.
Referenced by L_resolve_dependence().
int Ldep_print_dependence_graph = 0
Definition at line 101 of file l_dependence.c.
Referenced by L_build_dependence_graph(), and L_read_parm_ldep().
int Ldep_program_order = 0
Definition at line 108 of file l_dependence.c.
Referenced by L_build_dependence_graph(), and L_read_parm_ldep().
int Ldep_remove_always_safe = 0
Definition at line 102 of file l_dependence.c.
Referenced by L_is_always_safe(), L_read_parm_ldep(), and Ldep_mark_safe_invariant().
int Ldep_remove_complex_safe = 0
Definition at line 104 of file l_dependence.c.
Referenced by L_is_complex_safe(), L_read_parm_ldep(), and Ldep_mark_safe_invariant().
int Ldep_remove_ctl_dep_safe = 0
Definition at line 103 of file l_dependence.c.
Referenced by L_is_ctl_dep_safe(), L_read_parm_ldep(), and Ldep_mark_safe_invariant().
int Ldep_remove_jsr_dependences = 0
Definition at line 90 of file l_dependence.c.
Referenced by L_compute_control_dependence(), L_compute_hb_control_dependence(), and L_read_parm_ldep().
int Ldep_resolve_all_anti_output_dep = 0
Definition at line 84 of file l_dependence.c.
Referenced by L_read_parm_ldep(), and L_resolve_dependence().
int Ldep_resolve_all_control_dep = 0
Definition at line 83 of file l_dependence.c.
Referenced by L_read_parm_ldep(), and L_resolve_dependence().
int Ldep_resolve_all_memory_dep = 0
Definition at line 82 of file l_dependence.c.
Referenced by L_read_parm_ldep(), and L_resolve_dependence().
int Ldep_resolve_dependences = 0
Definition at line 81 of file l_dependence.c.
Referenced by L_build_dependence_graph(), and L_read_parm_ldep().
int Ldep_use_iter = 1
Definition at line 105 of file l_dependence.c.
Referenced by L_is_ctl_dep_safe(), and L_read_parm_ldep().
Set loop_set [static]
Definition at line 129 of file l_dependence.c.
Referenced by Ldep_mark_safe_invariant().