l_delay_slots.c File Reference
#include <config.h>
#include `l_schedule.h`
Functions
static L_Cb * L_alter_branch_destination (L_Func *fn, L_Cb *cb, L_Cb *dest_cb, L_Oper *br, L_Oper *filler)
static int L_valid_branch_filler (L_Oper *br, L_Oper *filler)
void Lsched_fill_from_target (L_Func *fn)
void Lsched_fill_nonsquashing_slots (L_Func *fn)
void Lsched_fill_nonsquashing_branches (L_Func *fn)
void Lsched_fill_squashing_branches (L_Func *fn)
void Lsched_fill_unfilled_branches (L_Func *fn)
int Lsched_handle_spilled_branch (L_Cb *cb, Sched_Info *sinfo)
int Lsched_update_ctl_delay_sinfo (Squeue *queue, Sched_Info *sinfo)
void Lsched_check_for_fill_candidates (Squeue *queue)
void Lsched_schedule_with_delay_op (L_Cb *cb, Sched_Info *sinfo, int current_time, int current_block, int issue_slot, int spec)
Function Documentation
static L_Cb* L_alter_branch_destination (L_Func * fn, L_Cb * cb, L_Cb* dest_cb, L_Oper * br, L_Oper* filler) [static]
Definition at line 83 of file l_delay_slots.c.
References NULL.
Referenced by Lsched_fill_from_target(), and Lsched_fill_squashing_branches().
static int L_valid_branch_filler (L_Oper * br, L_Oper* filler) [static]
Definition at line 154 of file l_delay_slots.c.
References LHPPAop_ADDIB_LT_BWD, LHPPAop_ADDIB_LT_FWD, and NULL.
Referenced by Lsched_fill_from_target().
void Lsched_check_for_fill_candidates (Squeue * queue)
Definition at line 705 of file l_delay_slots.c.
References L_get_queue_next_entry(), L_reset_queue_current(), Lsched_update_ctl_delay_sinfo(), and NULL.
Referenced by Lsched_schedule_block().
void Lsched_fill_from_target (L_Func * fn)
Definition at line 194 of file l_delay_slots.c.
References FILLED_ABOVE, FILLED_BELOW, FILLER, L_alter_branch_destination(), L_valid_branch_filler(), NULL, and SCHED_INFO.
Referenced by Lsched_fill_nonsquashing_branches().
void Lsched_fill_nonsquashing_branches (L_Func * fn)
Definition at line 375 of file l_delay_slots.c.
References Lsched_fill_from_target(), and Lsched_fill_nonsquashing_slots().
Referenced by Lsched_postpass_code_scheduling().
void Lsched_fill_nonsquashing_slots (L_Func * fn)
Definition at line 348 of file l_delay_slots.c.
References FILLED_ABOVE, and NULL.
Referenced by Lsched_fill_nonsquashing_branches().
void Lsched_fill_squashing_branches (L_Func * fn)
Definition at line 385 of file l_delay_slots.c.
References FILLED_ABOVE, FILLED_BELOW, FILLER, L_alter_branch_destination(), NULL, Sched_Info::ru_info, RU_SELECTED_ALT_ID, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
void Lsched_fill_unfilled_branches (L_Func * fn)
Definition at line 495 of file l_delay_slots.c.
References FILLED_ABOVE, FILLED_BELOW, Lsched_debug_unfilled_branches, NULL, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
int Lsched_handle_spilled_branch (L_Cb * cb, Sched_Info * sinfo)
Definition at line 560 of file l_delay_slots.c.
References Sched_Info::delay_sinfo, FILLED_BELOW, FILLER, HAS_DELAY_SLOT, IS_CTL, IS_MEMORY_STORE, NULL, Sched_Info::oper, and SCHED_INFO.
Referenced by Lsched_schedule_block().
void Lsched_schedule_with_delay_op (L_Cb * cb, Sched_Info * sinfo, int current_time, int current_block, int issue_slot, int spec)
Definition at line 715 of file l_delay_slots.c.
References CAN_SCHEDULE, Sched_Info::current_block, Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, FILLED_ABOVE, FILLED_BELOW, FILLER, HAS_DELAY_SLOT, Sched_Info::id, Dep_Info::input_dep, IS_CTL, Sched_Info::issue_slot, L_DEP_CNT, L_dequeue_from_all(), L_enqueue(), L_enqueue_min_to_max_1(), L_get_queue_next_entry(), L_remove_dep(), Lsched_can_schedule_op(), Lsched_debug_nonsquashing_branches, Lsched_schedule_op(), Lsched_total_issue_slots, Sched_Info::mdes_info, Dep_Info::n_input_dep, Dep_Info::n_output_dep, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, Dep_Info::output_dep, pending_ready_queue, priority_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_schedule_op_at(), RU_unschedule_op(), and Sched_Info::scheduled.
Referenced by Lsched_schedule_block().
int Lsched_update_ctl_delay_sinfo (Squeue * queue, Sched_Info * sinfo)
Definition at line 594 of file l_delay_slots.c.
References Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, FILLED_BELOW, HAS_DELAY_SLOT, Sched_Info::id, IS_CTL, L_DEP_CNT, L_dequeue(), L_enqueue_min_to_max_1(), Lsched_debug_nonsquashing_branches, Dep_Info::n_output_dep, not_ready_queue, Sched_Info::num_depend, Sched_Info::oper, Dep_Info::output_dep, pending_ready_queue, Sched_Info::priority, Sched_Info::proc_opc, Sched_Info::ready_time, SCHED_INFO, L_Dep::to_oper, and L_Dep::type.
Referenced by Lsched_check_for_fill_candidates(), and Lsched_make_ready().