l_mcb.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `l_schedule.h`
#include <machine/m_hppa.h>
Functions
void L_change_beq_mcb (L_Cb *cb)
L_Cb * L_copy_all_oper_in_cb (L_Func *fn, L_Cb *cb)
void L_mcb_insert_check_and_rem_dependences (L_Cb *cb)
int L_dependent_memory_ops (L_Cb *cb, L_Oper *op1, L_Oper *op2)
void L_remove_sched_cb (L_Func *fn, L_Cb *cb)
void L_mcb_init ()
void L_free_oper_list (L_Oper *oper)
void L_mcb_remove_check (L_Cb *cb, L_Oper *oper, int ready_time)
L_Oper_List * L_new_oper_list ()
Function Documentation
void L_change_beq_mcb (L_Cb * cb)
Definition at line 131 of file l_mcb.c.
References NULL, and Dep_Info::oper.
L_Cb* L_copy_all_oper_in_cb (L_Func * fn, L_Cb * cb)
Definition at line 364 of file l_mcb.c.
int L_dependent_memory_ops (L_Cb * cb, L_Oper * op1, L_Oper * op2)
Definition at line 235 of file l_mcb.c.
References L_check_equivalent_regs(), and M_is_stack_operand().
Referenced by L_mcb_insert_check_and_rem_dependences().
void L_free_oper_list (L_Oper * oper)
void L_mcb_init ()
Definition at line 414 of file l_mcb.c.
References L_create_alloc_pool(), and Lmcb_list_pool.
Referenced by Lsched_init().
void L_mcb_insert_check_and_rem_dependences (L_Cb * cb)
Definition at line 629 of file l_mcb.c.
References DEP_INFO, Dep_Info::input_dep, L_add_check_ptr_to_oper(), L_add_check_to_check_dep(), L_DEP_MEM_FLOW, L_dependent_memory_ops(), L_mcb_add_store_to_load_list(), L_mcb_insert_check(), L_remove_dep(), MAX_STORES_BYPASSED, Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, Dep_Info::output_dep, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
void L_mcb_remove_check (L_Cb * cb, L_Oper * oper, int ready_time)
Definition at line 1573 of file l_mcb.c.
L_Oper_List* L_new_oper_list ()
Referenced by L_mcb_add_store_to_load_list().
void L_remove_sched_cb (L_Func * fn, L_Cb * cb)
Definition at line 385 of file l_mcb.c.
References L_delete_ru_info_oper(), L_free(), Lmcb_list_pool, NULL, Dep_Info::oper, Operand_ready_pool, SCHED_INFO, and Sched_Info_pool.