l_mcb.c File Reference
#include <config.h>
#include `l_mcb.h`
Defines
#define L_MAX_COPY_OPER 1000
#define L_MAX_CB_LOADS 1000
#define L_MAX_CB_STORES 1000
#define MIN_MCB_SPEEDUP 0.00
#define MAX_STORES_BYPASSED 9
#define MCB_MIN_CB_WEIGHT 1000.0
Functions
L_Oper * L_find_next_branch (L_Cb *cb, L_Oper *oper)
static L_Oper * L_get_regs_load_def (L_Oper *oper, L_Operand *reg)
static int L_are_same_pointer_regs (L_Oper *op1, L_Operand *reg1, L_Oper *op2, L_Operand *reg2)
static int L_check_equivalent_regs (L_Oper *op1, L_Operand *reg1, L_Oper *op2, L_Operand *reg2)
static void L_check_flow_op (int dest_reg, L_Oper *begin_op, L_Oper *end_op)
static int L_get_reg_num (L_Operand *operand)
static void L_rename_src_reg (L_Cb *cb, int operand_num, L_Oper *oper, L_Oper *end_op)
static void L_change_ext_operand (L_Oper *oper, int operand_num, L_Operand *new_operand)
static void L_mcb_add_store_to_load_list (L_Oper *store, L_Oper *load)
static void L_add_check_ptr_to_oper (L_Oper *check, L_Oper *load)
static int L_is_mem_or_flow_dep (L_Dep *depend)
static L_Oper * L_mcb_insert_check (L_Oper *oper)
static void L_add_check_to_check_dep (L_Oper *prev_check, L_Oper *check)
static int L_is_corr_cb (L_Cb *cb)
static void L_insert_correction_code (L_Cb *cb)
static void L_insert_fall_thru_code (L_Cb *cb)
static void L_free_sched_info (L_Cb *cb)
static void L_mcb_delete_check (L_Cb *cb, L_Oper *check, int current_time)
void L_change_beq_mcb (L_Cb *cb)
int L_dependent_memory_ops (L_Cb *cb, L_Oper *op1, L_Oper *op2)
L_Cb * L_copy_all_oper_in_cb (L_Func *fn, L_Cb *cb)
void L_remove_sched_cb (L_Func *fn, L_Cb *cb)
void L_mcb_init ()
static void L_free_oper_list_cb (L_Cb *cb)
void L_mcb_insert_check_and_rem_dependences (L_Cb *cb)
static void L_mcb_convert_sched_info (L_Oper *new_oper, L_Oper *old_oper)
static void L_mcb_convert_to_parent (L_Cb *cb)
void Lsched_mcb_schedule_block (L_Func *fn, L_Cb *cb, L_Cb *nomcb_cb)
void L_mcb_remove_check (L_Cb *cb, L_Oper *oper, int ready_time)
Variables
L_Alloc_Pool * Lmcb_list_pool = NULL
int Lsched_num_opers
int Lmcb_keep_checks
Define Documentation
#define L_MAX_CB_LOADS 1000
Definition at line 72 of file l_mcb.c.
#define L_MAX_CB_STORES 1000
Definition at line 73 of file l_mcb.c.
#define L_MAX_COPY_OPER 1000
Definition at line 71 of file l_mcb.c.
#define MAX_STORES_BYPASSED 9
Definition at line 75 of file l_mcb.c.
Referenced by L_mcb_insert_check_and_rem_dependences().
#define MCB_MIN_CB_WEIGHT 1000.0
Definition at line 1337 of file l_mcb.c.
Referenced by Lsched_mcb_schedule_block().
#define MIN_MCB_SPEEDUP 0.00
Definition at line 74 of file l_mcb.c.
Referenced by Lsched_mcb_schedule_block().
Function Documentation
static void L_add_check_ptr_to_oper (L_Oper * check, L_Oper * load) [static]
Definition at line 488 of file l_mcb.c.
References SCHED_INFO.
Referenced by L_mcb_insert_check_and_rem_dependences().
static void L_add_check_to_check_dep (L_Oper * prev_check, L_Oper * check) [static]
Definition at line 609 of file l_mcb.c.
References DEP_CNT_OPERAND, L_add_dep(), L_DEP_CNT, NULL, and SCHED_INFO.
Referenced by L_mcb_insert_check_and_rem_dependences().
static int L_are_same_pointer_regs (L_Oper * op1, L_Operand * reg1, L_Oper * op2, L_Operand * reg2) [static]
Definition at line 192 of file l_mcb.c.
References L_get_regs_load_def(), and NULL.
Referenced by L_check_equivalent_regs().
void L_change_beq_mcb (L_Cb * cb)
Definition at line 131 of file l_mcb.c.
References NULL, and Dep_Info::oper.
static void L_change_ext_operand (L_Oper * oper, int operand_num, L_Operand * new_operand) [static]
Definition at line 1257 of file l_mcb.c.
References NULL.
Referenced by L_rename_src_reg().
static int L_check_equivalent_regs (L_Oper * op1, L_Operand * reg1, L_Oper * op2, L_Operand * reg2) [static]
Definition at line 225 of file l_mcb.c.
References L_are_same_pointer_regs().
Referenced by L_dependent_memory_ops().
static void L_check_flow_op (int dest_reg, L_Oper * begin_op, L_Oper * end_op) [static]
Definition at line 1103 of file l_mcb.c.
References L_get_reg_num(), and NULL.
Referenced by L_insert_correction_code().
L_Cb* L_copy_all_oper_in_cb (L_Func * fn, L_Cb * cb)
Definition at line 364 of file l_mcb.c.
References NULL, and Dep_Info::oper.
int L_dependent_memory_ops (L_Cb * cb, L_Oper * op1, L_Oper * op2)
Definition at line 235 of file l_mcb.c.
References L_check_equivalent_regs(), and M_is_stack_operand().
Referenced by L_mcb_insert_check_and_rem_dependences().
L_Oper* L_find_next_branch (L_Cb * cb, L_Oper * oper)
Definition at line 1374 of file l_schedule.c.
References Lsched_is_branch(), and NULL.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
static void L_free_oper_list_cb (L_Cb * cb) [static]
Definition at line 455 of file l_mcb.c.
References NULL, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
static void L_free_sched_info (L_Cb * cb) [static]
Definition at line 1278 of file l_mcb.c.
References Sched_Info::branch_kill_set, Sched_Info::check_op, Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::entry_list, Sched_Info::extend_lr_down, L_delete_ru_info_oper(), L_free(), Sched_Info::mdes_info, NULL, Sched_Info::oper, Operand_ready_pool, Sched_Info::post_br, Sched_Info::prev_br, Sched_Info::ru_info, SCHED_INFO, Sched_Info_pool, and Sched_Info::store_list.
Referenced by Lsched_mcb_schedule_block().
static int L_get_reg_num (L_Operand * operand) [static]
Definition at line 1158 of file l_mcb.c.
Referenced by L_check_flow_op(), L_insert_correction_code(), and L_rename_src_reg().
static L_Oper * L_get_regs_load_def (L_Oper * oper, L_Operand * reg) [static]
Definition at line 173 of file l_mcb.c.
References NULL.
Referenced by L_are_same_pointer_regs().
static void L_insert_correction_code (L_Cb * cb) [static]
Definition at line 808 of file l_mcb.c.
References L_check_flow_op(), L_get_reg_num(), L_is_corr_cb(), L_mcb_convert_sched_info(), L_rename_src_reg(), NULL, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
static void L_insert_fall_thru_code (L_Cb * cb) [static]
Definition at line 994 of file l_mcb.c.
References NULL.
Referenced by Lsched_mcb_schedule_block().
static int L_is_corr_cb (L_Cb * cb) [static]
Definition at line 798 of file l_mcb.c.
References NULL.
Referenced by L_insert_correction_code().
static int L_is_mem_or_flow_dep (L_Dep * depend) [static]
Definition at line 495 of file l_mcb.c.
References L_DEP_CNT, L_DEP_MEM_ANTI, L_DEP_MEM_FLOW, L_DEP_MEM_OUTPUT, and L_Dep::type.
Referenced by L_mcb_insert_check().
static void L_mcb_add_store_to_load_list (L_Oper * store, L_Oper * load) [static]
Definition at line 474 of file l_mcb.c.
References L_new_oper_list(), and SCHED_INFO.
Referenced by L_mcb_insert_check_and_rem_dependences().
static void L_mcb_convert_sched_info (L_Oper * new_oper, L_Oper * old_oper) [static]
Definition at line 782 of file l_mcb.c.
References Sched_Info::dep_info, Sched_Info::id, Sched_Info::mdes_info, Sched_Info::oper, and Sched_Info::proc_opc.
Referenced by L_insert_correction_code().
static void L_mcb_convert_to_parent (L_Cb * cb) [static]
Definition at line 1319 of file l_mcb.c.
References NULL.
Referenced by Lsched_mcb_schedule_block().
static void L_mcb_delete_check (L_Cb * cb, L_Oper * check, int current_time) [static]
Definition at line 1482 of file l_mcb.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, Dep_Info::input_dep, Sched_Info::issue_slot, L_delete_dependence_info(), L_delete_sched_info(), L_dequeue_from_all(), L_in_queue(), L_remove_dep(), Lsched_debug_messages, Lsched_make_ready(), Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, Sched_Info::num_depend, Dep_Info::output_dep, SCHED_INFO, scheduled_queue, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by L_mcb_remove_check().
void L_mcb_init ()
Definition at line 414 of file l_mcb.c.
References L_create_alloc_pool(), and Lmcb_list_pool.
Referenced by Lsched_init().
static L_Oper * L_mcb_insert_check (L_Oper * oper) [static]
Definition at line 512 of file l_mcb.c.
References DEP_CNT_OPERAND, DEP_INFO, input, Dep_Info::input_dep, L_add_dep(), L_create_sched_info(), L_DEP_CNT, L_DEP_REG_FLOW, L_is_mem_or_flow_dep(), L_new_dep_info(), Dep_Info::n_input_dep, NULL, output, Dep_Info::output_dep, and SCHED_INFO.
Referenced by L_mcb_insert_check_and_rem_dependences().
void L_mcb_insert_check_and_rem_dependences (L_Cb * cb)
Definition at line 629 of file l_mcb.c.
References DEP_INFO, Dep_Info::input_dep, L_add_check_ptr_to_oper(), L_add_check_to_check_dep(), L_DEP_MEM_FLOW, L_dependent_memory_ops(), L_mcb_add_store_to_load_list(), L_mcb_insert_check(), L_remove_dep(), MAX_STORES_BYPASSED, Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, Dep_Info::output_dep, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
void L_mcb_remove_check (L_Cb * cb, L_Oper * oper, int ready_time)
Definition at line 1573 of file l_mcb.c.
References L_in_queue(), L_mcb_delete_check(), Lmcb_keep_checks, NULL, SCHED_INFO, and scheduled_queue.
void L_remove_sched_cb (L_Func * fn, L_Cb * cb)
Definition at line 385 of file l_mcb.c.
References L_delete_ru_info_oper(), L_free(), Lmcb_list_pool, NULL, Dep_Info::oper, Operand_ready_pool, SCHED_INFO, and Sched_Info_pool.
static void L_rename_src_reg (L_Cb * cb, int operand_num, L_Oper * oper, L_Oper * end_op) [static]
Definition at line 1177 of file l_mcb.c.
References L_change_ext_operand(), L_get_reg_num(), and NULL.
Referenced by L_insert_correction_code().
void Lsched_mcb_schedule_block (L_Func * fn, L_Cb * cb, L_Cb * nomcb_cb)
Definition at line 1340 of file l_mcb.c.
References IS_IGNORE, IS_UCOND_BRANCH, L_approx_cb_time(), L_build_dependence_graph(), L_create_sched_info(), L_delete_dependence_graph(), L_find_next_branch(), L_free(), L_free_oper_list_cb(), L_free_sched_info(), L_insert_correction_code(), L_insert_fall_thru_code(), L_mcb_convert_to_parent(), L_mcb_insert_check_and_rem_dependences(), LDEP_MODE_ACYCLIC, LDEP_PREPASS, Lsched_debug_messages, Lsched_is_branch(), Lsched_latest_br, Lsched_num_opers, Lsched_schedule_block(), MCB_MIN_CB_WEIGHT, MIN_MCB_SPEEDUP, NULL, and SCHED_INFO.
Variable Documentation
int Lmcb_keep_checks
Definition at line 124 of file l_schedule.c.
Referenced by L_mcb_remove_check().
L_Alloc_Pool* Lmcb_list_pool = NULL
Definition at line 81 of file l_mcb.c.
Referenced by L_mcb_init(), and L_remove_sched_cb().
int Lsched_num_opers
Definition at line 101 of file l_schedule.c.
Referenced by Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), and Lsched_schedule_block().