l_queue.c File Reference
#include <config.h>
#include `l_schedule.h`
Functions
Squeue * L_create_queue (char *name, int id)
void L_delete_queue (Squeue *queue)
void L_reset_queue_current (Squeue *queue)
Sched_Info * L_get_queue_next_entry (Squeue *queue)
Sched_Info * L_get_queue_head (Squeue *queue)
int L_get_queue_size (Squeue *queue)
void L_enqueue (Squeue *queue, Sched_Info *sinfo)
void L_dequeue (Squeue *queue, Sched_Info *sinfo)
void L_dequeue_entry (Sq_entry *entry)
void L_dequeue_from_all (Sched_Info *sinfo)
void L_enqueue_before (Squeue *queue, Sched_Info *sinfo, Sq_entry *before)
void L_move_entry_before (Squeue *new_queue, Sq_entry *entry, Sq_entry *before)
void L_enqueue_min_to_max_1 (Squeue *queue, Sched_Info *sinfo, float key)
void L_enqueue_max_to_min_1 (Squeue *queue, Sched_Info *sinfo, float key)
void L_enqueue_min_to_max_2 (Squeue *queue, Sched_Info *sinfo, float key1, float key2)
void L_enqueue_max_to_min_2 (Squeue *queue, Sched_Info *sinfo, float key1, float key2)
void L_enqueue_regpres (Squeue *queue, Sched_Info *sinfo, float key1, float key2)
int L_in_queue (Squeue *queue, Sched_Info *sinfo)
Function Documentation
Squeue* L_create_queue (char * name, int id)
Definition at line 68 of file l_queue.c.
References Squeue::current, Squeue::head, L_alloc(), Squeue::name, NULL, Squeue::size, Squeue_pool, and Squeue::tail.
Referenced by Lregpres_init_func(), and Lsched_init().
void L_delete_queue (Squeue * queue)
Definition at line 84 of file l_queue.c.
References L_free(), Squeue::name, Squeue::size, and Squeue_pool.
Referenced by Lregpres_deinit_func().
void L_dequeue (Squeue * queue, Sched_Info * sinfo)
Definition at line 161 of file l_queue.c.
References Squeue::current, entry, Squeue::head, L_free(), L_reset_queue_current(), NULL, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_update_virt_reg(), Lsched_make_ready(), Lsched_schedule_block(), and Lsched_update_ctl_delay_sinfo().
void L_dequeue_entry (Sq_entry * entry)
Definition at line 211 of file l_queue.c.
References Squeue::current, entry, Squeue::head, L_free(), L_reset_queue_current(), NULL, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_dequeue_from_all().
void L_dequeue_from_all (Sched_Info * sinfo)
Definition at line 256 of file l_queue.c.
References entry, Sched_Info::entry_list, L_dequeue_entry(), and NULL.
Referenced by L_mcb_delete_check(), Lsched_schedule_with_delay_op(), and wbs_delete_check().
void L_enqueue (Squeue * queue, Sched_Info * sinfo)
Definition at line 130 of file l_queue.c.
References entry, Sched_Info::entry_list, Squeue::head, L_alloc(), Sq_entry::next_entry, NULL, Sq_entry::prev_queue, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_enqueue_max_to_min_1(), L_enqueue_max_to_min_2(), L_enqueue_min_to_max_1(), L_enqueue_min_to_max_2(), L_enqueue_regpres(), Lregpres_add_virt_reg_use(), Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
void L_enqueue_before (Squeue * queue, Sched_Info * sinfo, Sq_entry * before)
Definition at line 272 of file l_queue.c.
References entry, Sched_Info::entry_list, Squeue::head, L_alloc(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::prev_queue, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_enqueue_max_to_min_1(), L_enqueue_max_to_min_2(), L_enqueue_min_to_max_1(), L_enqueue_min_to_max_2(), and L_enqueue_regpres().
void L_enqueue_max_to_min_1 (Squeue * queue, Sched_Info * sinfo, float key)
Definition at line 421 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, and Squeue::tail.
void L_enqueue_max_to_min_2 (Squeue * queue, Sched_Info * sinfo, float key1, float key2)
Definition at line 514 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, Sched_Info::sort_key2, and Squeue::tail.
Referenced by L_insert_entry().
void L_enqueue_min_to_max_1 (Squeue * queue, Sched_Info * sinfo, float key)
Definition at line 376 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, and Squeue::tail.
Referenced by Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
void L_enqueue_min_to_max_2 (Squeue * queue, Sched_Info * sinfo, float key1, float key2)
Definition at line 466 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, Sched_Info::sort_key2, and Squeue::tail.
void L_enqueue_regpres (Squeue * queue, Sched_Info * sinfo, float key1, float key2)
Definition at line 562 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sched_Info::rsort_key1, Sched_Info::rsort_key2, Sq_entry::sinfo, and Squeue::tail.
Referenced by L_insert_entry(), and L_update_virt_reg().
Sched_Info* L_get_queue_head (Squeue * queue)
Definition at line 113 of file l_queue.c.
References Squeue::head, NULL, Sq_entry::sinfo, and Squeue::size.
Referenced by L_update_virt_reg(), and Lsched_schedule_block().
Sched_Info* L_get_queue_next_entry (Squeue * queue)
Definition at line 97 of file l_queue.c.
References Squeue::current, Squeue::head, Sq_entry::next_entry, NULL, and Sq_entry::sinfo.
Referenced by L_get_next_entry(), Lsched_check_for_fill_candidates(), and Lsched_schedule_with_delay_op().
int L_get_queue_size (Squeue * queue)
Definition at line 121 of file l_queue.c.
References Squeue::size.
Referenced by L_get_next_entry(), L_update_virt_reg(), and Lsched_schedule_block().
int L_in_queue (Squeue * queue, Sched_Info * sinfo)
Definition at line 610 of file l_queue.c.
References Sched_Info::entry_list, Sq_entry::next_entry, NULL, and Sq_entry::queue.
Referenced by L_mcb_delete_check(), L_mcb_remove_check(), L_update_virt_reg(), and wbs_delete_check().
void L_move_entry_before (Squeue * new_queue, Sq_entry * entry, Sq_entry * before)
Definition at line 325 of file l_queue.c.
References entry, Squeue::head, Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Squeue::size, and Squeue::tail.
void L_reset_queue_current (Squeue * queue)
Definition at line 92 of file l_queue.c.
References Squeue::current.
Referenced by L_dequeue(), L_dequeue_entry(), L_init_ready_queue(), and Lsched_check_for_fill_candidates().