l_ru_interface.c File Reference
#include <config.h>
#include `l_schedule.h`
#include `RU_manager.h`
#include `l_ru_interface.h`
Functions
RU_Info * L_create_ru_info_oper (L_Oper *oper)
void L_delete_ru_info_oper (RU_Info *ru_info)
Function Documentation
RU_Info* L_create_ru_info_oper (L_Oper * oper)
Definition at line 77 of file l_ru_interface.c.
References NULL, RU_info_create(), and RU_pred_alloc().
Referenced by L_create_sched_info().
void L_delete_ru_info_oper (RU_Info * ru_info)
Definition at line 129 of file l_ru_interface.c.
References NULL, and RU_info_delete().
Referenced by L_delete_sched_info(), L_free_sched_info(), and L_remove_sched_cb().