l_ru_interface.h File Reference
#include <config.h>
Functions
RU_Info * L_create_ru_info_oper (L_Oper *oper)
void L_create_ru_info_cb (L_Cb *cb)
void L_create_ru_info_fn (L_Func *fn)
void L_delete_ru_info_oper (RU_Info *ru_info)
void L_delete_ru_info_cb (L_Cb *cb)
void L_delete_ru_info_fn (L_Func *fn)
Function Documentation
void L_create_ru_info_cb (L_Cb * cb)
void L_create_ru_info_fn (L_Func * fn)
RU_Info* L_create_ru_info_oper (L_Oper * oper)
Definition at line 77 of file l_ru_interface.c.
References NULL, RU_info_create(), and RU_pred_alloc().
Referenced by L_create_sched_info().
void L_delete_ru_info_cb (L_Cb * cb)
void L_delete_ru_info_fn (L_Func * fn)
void L_delete_ru_info_oper (RU_Info * ru_info)
Definition at line 129 of file l_ru_interface.c.
References NULL, and RU_info_delete().
Referenced by L_delete_sched_info(), L_free_sched_info(), and L_remove_sched_cb().