l_regpres.c File Reference
#include <config.h>
#include <Lcode/r_regproto.h>
#include `l_schedule.h`
Defines
#define CALLEE 0
#define CALLER 1
Functions
void Lregpres_compute_benefit (Sched_Info *sinfo)
int Lregpres_inc_current (int ctype, int count)
int Lregpres_dec_current (int ctype, int count)
void Lregpres_inc_set (Regtypes *set, int ctype)
void Lregpres_add_virt_reg_use (Sched_Info *sinfo, int reg_num)
void Lregpres_init_func (L_Func *fn)
void Lregpres_deinit_func (L_Func *fn)
void Lregpres_init_cb (L_Cb *cb)
void L_init_ready_queue ()
Sched_Info * L_get_next_entry ()
void L_insert_entry (Sched_Info *sinfo)
void L_update_virt_reg (Sched_Info *sinfo)
Variables
int Lsched_use_register_pressure_heuristic = 0
int Lsched_register_pressure_threshhold = 75
int Lsched_regpres_heuristic = 0
int Lregpres_problem = 0
int num_virt_reg
Vreg * virt_reg = NULL
CB_REG_INFO preg_info
CB_REG_INFO ireg_info
CB_REG_INFO freg_info
CB_REG_INFO dreg_info
Define Documentation
#define CALLEE 0
Definition at line 83 of file l_regpres.c.
Referenced by Lregpres_init_func().
#define CALLER 1
Definition at line 84 of file l_regpres.c.
Referenced by Lregpres_init_func().
Function Documentation
Sched_Info* L_get_next_entry ()
Definition at line 606 of file l_regpres.c.
References L_get_queue_next_entry(), L_get_queue_size(), Lregpres_problem, Lsched_regpres_heuristic, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
void L_init_ready_queue ()
Definition at line 598 of file l_regpres.c.
References L_reset_queue_current(), Lsched_regpres_heuristic, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
void L_insert_entry (Sched_Info * sinfo)
Definition at line 616 of file l_regpres.c.
References Sched_Info::benefit, Sched_Info::dep_info, L_enqueue_max_to_min_2(), L_enqueue_regpres(), Lsched_regpres_heuristic, Lsched_use_fan_out, Dep_Info::n_output_dep, Sched_Info::priority, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
void L_update_virt_reg (Sched_Info * sinfo)
Definition at line 630 of file l_regpres.c.
References Sched_Info::benefit, Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, Vreg::ctype, Regtypes::d, Sched_Info::def_set, Regtypes::f, Regtypes::i, IS_BRANCH, Sched_Info::kill_set, L_dequeue(), L_enqueue_regpres(), L_get_queue_head(), L_get_queue_size(), L_in_queue(), Lregpres_compute_benefit(), Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lsched_regpres_heuristic, Sched_Info::oper, Regtypes::p, Sched_Info::priority, Sched_Info::proc_opc, regpres_ready_queue, Vreg::use_queue, and virt_reg.
Referenced by Lsched_schedule_op().
void Lregpres_add_virt_reg_use (Sched_Info * sinfo, int reg_num)
Definition at line 225 of file l_regpres.c.
References L_enqueue(), and virt_reg.
Referenced by Lregpres_init_cb().
void Lregpres_compute_benefit (Sched_Info * sinfo)
Definition at line 91 of file l_regpres.c.
References Sched_Info::benefit, Regtypes::d, Sched_Info::def_set, Regtypes::f, Regtypes::i, Sched_Info::kill_set, and Regtypes::p.
Referenced by L_update_virt_reg().
int Lregpres_dec_current (int ctype, int count)
Definition at line 144 of file l_regpres.c.
References CB_REG_INFO::change, CB_REG_INFO::current_reg, Regtypes::d, dreg_info, Regtypes::f, freg_info, Regtypes::i, ireg_info, Lregpres_problem, Regtypes::p, preg_info, and CB_REG_INFO::threshhold.
Referenced by L_update_virt_reg().
void Lregpres_deinit_func (L_Func * fn)
Definition at line 412 of file l_regpres.c.
References L_delete_queue(), Lsched_regpres_heuristic, NULL, num_virt_reg, and virt_reg.
int Lregpres_inc_current (int ctype, int count)
Definition at line 100 of file l_regpres.c.
References CB_REG_INFO::change, CB_REG_INFO::current_reg, Regtypes::d, dreg_info, Regtypes::f, freg_info, Regtypes::i, ireg_info, Lregpres_problem, Regtypes::p, preg_info, and CB_REG_INFO::threshhold.
Referenced by L_update_virt_reg(), and Lregpres_init_cb().
void Lregpres_inc_set (Regtypes * set, int ctype)
Definition at line 188 of file l_regpres.c.
References CB_REG_INFO::change, Regtypes::d, dreg_info, Regtypes::f, freg_info, Regtypes::i, ireg_info, Regtypes::p, and preg_info.
Referenced by L_update_virt_reg(), and Lregpres_init_cb().
void Lregpres_init_cb (L_Cb * cb)
Definition at line 429 of file l_regpres.c.
References Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, CB_REG_INFO::current_reg, Sched_Info::def_set, dreg_info, freg_info, ireg_info, IS_BRANCH, IS_JSR, IS_UCOND_BRANCH, Lregpres_add_virt_reg_use(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_problem, Lsched_regpres_heuristic, NULL, num_virt_reg, Dep_Info::oper, preg_info, Sched_Info::proc_opc, SCHED_INFO, Set_2array(), Set_size(), Set_subtract(), and virt_reg.
Referenced by Lsched_schedule_block().
void Lregpres_init_func (L_Func * fn)
Definition at line 236 of file l_regpres.c.
References CALLEE, CB_REG_INFO::callee_reg, CB_REG_INFO::callee_thresh, CALLER, CB_REG_INFO::caller_reg, CB_REG_INFO::caller_thresh, CB_REG_INFO::change, Vreg::ctype, Regtypes::d, dreg_info, Regtypes::f, FALSE, freg_info, Regtypes::i, ireg_info, L_create_queue(), Lsched_register_pressure_threshhold, Lsched_regpres_heuristic, Lsched_use_register_pressure_heuristic, NULL, num_virt_reg, Dep_Info::oper, Regtypes::p, preg_info, CB_REG_INFO::size, TRUE, and virt_reg.
Referenced by Lsched_prepass_code_scheduling().
Variable Documentation
CB_REG_INFO dreg_info
Definition at line 81 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
CB_REG_INFO freg_info
Definition at line 80 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
CB_REG_INFO ireg_info
Definition at line 79 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
int Lregpres_problem = 0
Definition at line 74 of file l_regpres.c.
Referenced by L_get_next_entry(), Lregpres_dec_current(), Lregpres_inc_current(), and Lregpres_init_cb().
int Lsched_register_pressure_threshhold = 75
Definition at line 72 of file l_regpres.c.
Referenced by L_read_parm_lsched(), and Lregpres_init_func().
int Lsched_regpres_heuristic = 0
Definition at line 73 of file l_regpres.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), L_update_virt_reg(), Lregpres_deinit_func(), Lregpres_init_cb(), Lregpres_init_func(), and Lsched_schedule_block().
int Lsched_use_register_pressure_heuristic = 0
Definition at line 71 of file l_regpres.c.
Referenced by L_read_parm_lsched(), and Lregpres_init_func().
int num_virt_reg
Definition at line 76 of file l_regpres.c.
Referenced by Lregpres_deinit_func(), Lregpres_init_cb(), and Lregpres_init_func().
CB_REG_INFO preg_info
Definition at line 78 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
Vreg* virt_reg = NULL
Definition at line 77 of file l_regpres.c.
Referenced by L_update_virt_reg(), Lregpres_add_virt_reg_use(), Lregpres_deinit_func(), Lregpres_init_cb(), and Lregpres_init_func().