l_schedule.c File Reference
#include <config.h>
#include `l_schedule.h`
#include `l_mcb.h`
Data Structures
struct LEAF
Defines
#define FALL_THRU 0
#define UBR_TAKEN 1
#define CBR_TAKEN 2
#define NO_CB_PAD 0x7FFFFFFF
Functions
int Lsched_loads_per_cycle ()
int Lsched_stores_per_cycle ()
int Lsched_branches_per_cycle ()
int Lsched_issue_time (L_Oper *oper)
int Lsched_completion_time (L_Oper *oper)
int Lsched_latency (L_Oper *oper)
void L_read_parm_lsched (Parm_Parse_Info *ppi)
void Lsched_init (Parm_Macro_List *command_line_macro_list, char *lmdes_file_name)
void Lsched_renumber_issue_slots (L_Func *fn)
void Lsched_func_complete (L_Func *fn)
Sched_Info * L_create_sched_info (L_Oper *oper, int home_block, L_Oper *prev_br, L_Oper *post_br)
void L_update_sched_info (Sched_Info *sinfo, L_Oper *oper, int home_block)
void L_delete_sched_info (Sched_Info *sinfo)
void L_print_sched_info (FILE *F, Sched_Info *s_info)
void Lsched_init_etimes_and_ltimes (L_Cb *cb)
int Lsched_determine_etimes (L_Cb *cb, L_Oper ***exit_ops)
void Lsched_determine_ltimes (L_Cb *cb, int num_exits, L_Oper **exit_ops)
void Lsched_calculate_priority_normal (L_Cb *cb, int num_exits, L_Oper **exit_ops)
int Lsched_is_branch (int proc_opc)
L_Oper * L_find_next_branch (L_Cb *cb, L_Oper *oper)
void L_annotate_instr (L_Cb *cb)
void Lsched_make_ready (L_Cb *cb, int oper_issue_time, Sched_Info *sinfo, Sched_Info *dep_sinfo, int to_index, int from_index, int distance)
void Lsched_schedule_op (L_Cb *cb, Sched_Info *sinfo, int spec, int ready_time)
int Lsched_can_schedule_op (L_Cb *cb, Sched_Info *sinfo, int current_time, int current_block, int *issue_slot, int *spec, int *silent)
static L_Oper * Lsched_create_nop (int issue_time, int issue_slot)
static L_Oper * Lsched_create_jump (int issue_time, int issue_slot, L_Operand *target)
static void Lsched_pad_slots_with_nops (L_Cb *cb)
int Lsched_get_cb_start_pad_value (L_Cb *cb)
void Lsched_create_cb_start_pad (L_Cb *cb, int pad_value)
int Lsched_get_cb_end_pad_value (L_Cb *cb)
void Lsched_create_cb_end_pad (L_Cb *cb, int pad_value)
int Lsched_get_br_pad_value (L_Oper *oper)
void Lsched_create_br_pad (L_Oper *oper, int pad_value)
int Lsched_cb_completion_time (L_Cb *cb)
int Lsched_need_pad (L_Cb *target, L_Oper *oper, int overextend)
static void Lsched_determine_pad_for_vliw (L_Cb *cb)
static void Lsched_pad_cycles_start_of_cb_for_vliw (L_Cb *cb)
static void Lsched_pad_cycles_end_of_cb_for_vliw (L_Cb *cb)
static void Lsched_pad_cycles_for_vliw (L_Func *fn, L_Cb *cb)
static void Lsched_correct_schedule_for_vliw (L_Func *fn)
void Lsched_add_isl_attr (L_Func *fn)
void Lsched_delete_isl_attr (L_Func *fn)
void Lsched_fix_flows (L_Cb *cb)
void Lsched_schedule_block (L_Cb *cb)
void Lsched_prepass_code_scheduling (L_Func *fn)
void Lsched_postpass_code_scheduling (L_Func *fn)
Variables
int Lsched_debug_operation_priority = 0
int Lsched_debug_prepass_scheduling = 0
int Lsched_debug_postpass_scheduling = 0
int Lsched_debug_squashing_branches = 0
int Lsched_debug_nonsquashing_branches = 0
int Lsched_debug_unfilled_branches = 0
int Lsched_debug_use_sched_cb_bounds = 0
int Lsched_debug_lower_sched_cb_bound = 0
int Lsched_debug_upper_sched_cb_bound = 100000000
int Lsched_num_branches_per_cycle = 0
int Lsched_static_fall_thru_weight = 1
int Lsched_pad_height = 1
int Lsched_use_fan_out = 1
int Lsched_infinite_issue = 0
int Lsched_do_postpass_scheduling = 0
int Lsched_demote_all_the_way = 0
int Lsched_do_fill_squashing_branches = 0
int Lsched_do_fill_nonsquashing_branches = 0
int Lsched_do_fill_unfilled_branches = 0
int Lsched_include_only_oper_lt_hb = 0
int Lsched_print_statistics = 0
int Lsched_print_prepass_statistics = 0
int Lsched_print_spec_condition = 0
int Lsched_do_sentinel_recovery = 0
int Lsched_prepass = 0
int Lsched_print_hb_and_spec = 0
int Lsched_print_cycle_delimiter = 0
int Lsched_num_opers = 0
int Lsched_loads_each_cycle = 0
int Lsched_stores_each_cycle = 0
int current_time = 0
int Lsched_infinite_issue_slot = 0
int Lsched_pad_vliw_slots_with_nops = 0
int Lsched_vliw_has_interlocking = 0
int Lsched_do_renumber_issue_slots = 0
char * Lsched_profile_info_to_use = NULL
L_Oper * Lsched_latest_br = NULL
Squeue * scheduled_queue
Squeue * priority_ready_queue
Squeue * regpres_ready_queue
Squeue * pending_ready_queue
Squeue * not_ready_queue
int Lsched_processor_model = MDES_SUPERSCALAR
int Lsched_total_issue_slots = 0
float Lsched_branch_increase = 0.0
int Lsched_fill_delay_slots = 0
int Lsched_debug_messages = 0
int Lmcb_keep_checks = 0
L_Alloc_Pool * Squeue_pool = NULL
L_Alloc_Pool * Sq_entry_pool = NULL
L_Alloc_Pool * Sched_Info_pool = NULL
L_Alloc_Pool * Operand_ready_pool = NULL
Define Documentation
#define CBR_TAKEN 2
Definition at line 1074 of file l_schedule.c.
#define FALL_THRU 0
Definition at line 1072 of file l_schedule.c.
#define NO_CB_PAD 0x7FFFFFFF
Definition at line 1950 of file l_schedule.c.
Referenced by Lsched_get_cb_start_pad_value(), and Lsched_pad_cycles_start_of_cb_for_vliw().
#define UBR_TAKEN 1
Definition at line 1073 of file l_schedule.c.
Function Documentation
void L_annotate_instr (L_Cb * cb)
Definition at line 1389 of file l_schedule.c.
References Sched_Info::current_block, Sched_Info::home_block, Lsched_print_hb_and_spec, NULL, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
Sched_Info* L_create_sched_info (L_Oper * oper, int home_block, L_Oper * prev_br, L_Oper * post_br)
Definition at line 585 of file l_schedule.c.
References Sched_Info::benefit, Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, Sched_Info::check_op, Sched_Info::current_block, Regtypes::d, Sched_Info::def_set, Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, Sched_Info::entry_list, Sched_Info::etime, Sched_Info::extend_lr_down, Regtypes::f, Sched_Info::home_block, Regtypes::i, Sched_Info::id, Sched_Info::index, Sched_Info::instr_prob, Sched_Info::issue_slot, Sched_Info::issue_time, Sched_Info::kill_set, L_alloc(), L_create_ru_info_oper(), Sched_Info::ltimes, Sched_Info::mdes_info, Dep_Info::n_input_dep, Sched_Info::not_taken_instr_prob, NULL, Sched_Info::num_depend, Sched_Info::on_stack, Sched_Info::oper, Operand_ready_pool, Sched_Info::operand_ready_times, Sched_Info::orig_block, Regtypes::p, Sched_Info::post_br, Sched_Info::prev_br, Sched_Info::priority, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::relative_latency, Sched_Info::rsort_key1, Sched_Info::rsort_key2, Sched_Info::ru_info, Sched_Info_pool, Sched_Info::scheduled, Sched_Info::sort_key1, Sched_Info::spec_cond, Dep_Info::spec_cond, Sched_Info::store_list, Sched_Info::taken_instr_prob, and Sched_Info::weight.
Referenced by L_mcb_insert_check(), Lsched_create_jump(), Lsched_create_nop(), Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), and wbs_insert_check().
void L_delete_sched_info (Sched_Info * sinfo)
Definition at line 698 of file l_schedule.c.
References Sched_Info::branch_kill_set, L_delete_ru_info_oper(), L_free(), Sched_Info::ltimes, NULL, Dep_Info::oper, Sched_Info::oper, Operand_ready_pool, Sched_Info::operand_ready_times, Sched_Info::relative_latency, Sched_Info::ru_info, and Sched_Info_pool.
Referenced by L_mcb_delete_check(), Lsched_func_complete(), and wbs_delete_check().
L_Oper* L_find_next_branch (L_Cb * cb, L_Oper * oper)
Definition at line 1374 of file l_schedule.c.
References Lsched_is_branch(), and NULL.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
void L_print_sched_info (FILE * F, Sched_Info * s_info)
Definition at line 713 of file l_schedule.c.
References Sched_Info::current_block, Sched_Info::home_block, Sched_Info::id, Sched_Info::post_br, and Sched_Info::prev_br.
void L_read_parm_lsched (Parm_Parse_Info * ppi)
Definition at line 213 of file l_schedule.c.
References L_read_parm_b(), L_read_parm_i(), L_read_parm_s(), Lsched_debug_lower_sched_cb_bound, Lsched_debug_nonsquashing_branches, Lsched_debug_operation_priority, Lsched_debug_postpass_scheduling, Lsched_debug_prepass_scheduling, Lsched_debug_squashing_branches, Lsched_debug_unfilled_branches, Lsched_debug_upper_sched_cb_bound, Lsched_debug_use_sched_cb_bounds, Lsched_do_fill_nonsquashing_branches, Lsched_do_fill_squashing_branches, Lsched_do_fill_unfilled_branches, Lsched_do_postpass_scheduling, Lsched_do_renumber_issue_slots, Lsched_do_sentinel_recovery, Lsched_infinite_issue, Lsched_loads_each_cycle, Lsched_num_branches_per_cycle, Lsched_pad_height, Lsched_pad_vliw_slots_with_nops, Lsched_print_cycle_delimiter, Lsched_print_hb_and_spec, Lsched_print_prepass_statistics, Lsched_print_spec_condition, Lsched_print_statistics, Lsched_profile_info_to_use, Lsched_register_pressure_threshhold, Lsched_static_fall_thru_weight, Lsched_stores_each_cycle, Lsched_use_fan_out, Lsched_use_register_pressure_heuristic, and Lsched_vliw_has_interlocking.
Referenced by Lsched_init().
void L_update_sched_info (Sched_Info * sinfo, L_Oper * oper, int home_block)
Definition at line 664 of file l_schedule.c.
References Sched_Info::check_op, Sched_Info::current_block, Sched_Info::delay_sinfo, Sched_Info::dep_info, DEP_NON_EXCEPTING, Sched_Info::earliest_slot, Sched_Info::entry_list, Sched_Info::extend_lr_down, Sched_Info::issue_slot, Sched_Info::issue_time, Sched_Info::mdes_info, Dep_Info::n_input_dep, NULL, Sched_Info::num_depend, Sched_Info::on_stack, Sched_Info::operand_ready_times, Sched_Info::orig_block, Sched_Info::ready_time, Sched_Info::relative_latency, Sched_Info::scheduled, Sched_Info::spec_cond, and Dep_Info::spec_cond.
Referenced by Lsched_postpass_code_scheduling().
void Lsched_add_isl_attr (L_Func * fn)
Definition at line 2370 of file l_schedule.c.
References Sched_Info::issue_slot, Sched_Info::issue_time, NULL, Sched_Info::relative_latency, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
int Lsched_branches_per_cycle (void)
Definition at line 160 of file l_schedule.c.
References Lsched_num_branches_per_cycle.
Referenced by Lsched_init().
void Lsched_calculate_priority_normal (L_Cb * cb, int num_exits, L_Oper ** exit_ops)
Definition at line 974 of file l_schedule.c.
References Sched_Info::etime, Sched_Info::ltimes, Dep_Info::oper, Sched_Info::priority, and SCHED_INFO.
Referenced by Lsched_schedule_block().
int Lsched_can_schedule_op (L_Cb * cb, Sched_Info * sinfo, int current_time, int current_block, int * issue_slot, int * spec, int * silent)
Definition at line 1652 of file l_schedule.c.
References CAN_SCHEDULE, CANT_SCHEDULE, DEP_DELAYS_EXCEPTION, Sched_Info::dep_info, DEP_SILENT, Sched_Info::earliest_slot, Sched_Info::home_block, Sched_Info::issue_slot, Sched_Info::issue_time, Lsched_infinite_issue, Lsched_infinite_issue_slot, Lsched_processor_model, Lsched_total_issue_slots, Sched_Info::mdes_info, NULL, Sched_Info::operand_ready_times, Sched_Info::prev_br, Sched_Info::ready_time, RU_can_schedule_op(), Sched_Info::ru_info, SCHED_INFO, Sched_Info::scheduled, and Dep_Info::spec_cond.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
int Lsched_cb_completion_time (L_Cb * cb)
Definition at line 2024 of file l_schedule.c.
References IS_IGNORE, and SCHED_INFO.
Referenced by Lsched_determine_pad_for_vliw().
int Lsched_completion_time (L_Oper * oper)
Definition at line 176 of file l_schedule.c.
References Lsched_latency(), NULL, and SCHED_INFO.
Referenced by L_approx_cb_time(), L_print_schedule(), and Lsched_determine_pad_for_vliw().
static void Lsched_correct_schedule_for_vliw (L_Func * fn) [static]
Definition at line 2311 of file l_schedule.c.
References Lsched_determine_pad_for_vliw(), Lsched_pad_cycles_end_of_cb_for_vliw(), Lsched_pad_cycles_for_vliw(), Lsched_pad_cycles_start_of_cb_for_vliw(), Lsched_pad_slots_with_nops(), Lsched_print_statistics, M_arch, M_HPPA, M_IMPACT, M_PLAYDOH, and NULL.
Referenced by Lsched_postpass_code_scheduling().
void Lsched_create_br_pad (L_Oper * oper, int pad_value)
Definition at line 2009 of file l_schedule.c.
Referenced by Lsched_determine_pad_for_vliw().
void Lsched_create_cb_end_pad (L_Cb * cb, int pad_value)
Definition at line 1985 of file l_schedule.c.
Referenced by Lsched_determine_pad_for_vliw().
void Lsched_create_cb_start_pad (L_Cb * cb, int pad_value)
Definition at line 1961 of file l_schedule.c.
Referenced by Lsched_determine_pad_for_vliw().
static L_Oper* Lsched_create_jump (int issue_time, int issue_slot, L_Operand * target) [static]
Definition at line 1864 of file l_schedule.c.
References Sched_Info::issue_slot, Sched_Info::issue_time, L_create_sched_info(), and NULL.
Referenced by Lsched_pad_cycles_for_vliw().
static L_Oper* Lsched_create_nop (int issue_time, int issue_slot) [static]
Definition at line 1841 of file l_schedule.c.
References Sched_Info::issue_slot, Sched_Info::issue_time, L_create_sched_info(), and NULL.
Referenced by Lsched_pad_cycles_end_of_cb_for_vliw(), Lsched_pad_cycles_for_vliw(), Lsched_pad_cycles_start_of_cb_for_vliw(), and Lsched_pad_slots_with_nops().
void Lsched_delete_isl_attr (L_Func * fn)
Definition at line 2409 of file l_schedule.c.
int Lsched_determine_etimes (L_Cb * cb, L_Oper *** exit_ops)
Definition at line 763 of file l_schedule.c.
References DEP_INFO, L_Dep::distance, Sched_Info::etime, L_Dep::from_oper, Dep_Info::input_dep, IS_COND_BRANCH, IS_UCOND_BRANCH, L_DEP_CNT, Lsched_branch_increase, L_Dep::next_dep, L_Dep::omega, Dep_Info::oper, SCHED_INFO, and L_Dep::type.
Referenced by Lsched_schedule_block().
void Lsched_determine_ltimes (L_Cb * cb, int num_exits, L_Oper ** exit_ops)
Definition at line 853 of file l_schedule.c.
References DEP_INFO, L_Dep::distance, IS_UCOND_BRANCH, L_DEP_CNT, Lsched_branch_increase, Lsched_profile_info_to_use, L_Dep::next_dep, L_Dep::omega, Dep_Info::oper, Dep_Info::output_dep, SCHED_INFO, L_Dep::to_oper, and L_Dep::type.
Referenced by Lsched_schedule_block().
static void Lsched_determine_pad_for_vliw (L_Cb * cb) [static]
Definition at line 2061 of file l_schedule.c.
References DEP_INFO, L_Dep::from_oper, IS_IGNORE, Lsched_cb_completion_time(), Lsched_completion_time(), Lsched_create_br_pad(), Lsched_create_cb_end_pad(), Lsched_create_cb_start_pad(), Lsched_get_br_pad_value(), Lsched_get_cb_end_pad_value(), Lsched_get_cb_start_pad_value(), Lsched_need_pad(), L_Dep::next_dep, and NULL.
Referenced by Lsched_correct_schedule_for_vliw().
void Lsched_fix_flows (L_Cb * cb)
Definition at line 2425 of file l_schedule.c.
References NULL, Sched_Info::orig_block, and SCHED_INFO.
Referenced by Lsched_schedule_block().
void Lsched_func_complete (L_Func * fn)
Definition at line 427 of file l_schedule.c.
References DEP_ALWAYS_SAFE, DEP_COMPLEX_SAFE, DEP_CTL_DEP_SAFE, DEP_DELAYS_EXCEPTION, DEP_NON_EXCEPTING, DEP_SAFE_STORE, DEP_SILENT, Sched_Info::issue_time, L_delete_sched_info(), Lsched_do_postpass_scheduling, Lsched_do_renumber_issue_slots, Lsched_print_cycle_delimiter, Lsched_print_spec_condition, Lsched_renumber_issue_slots(), Sched_Info::mdes_info, NULL, Dep_Info::oper, SCHED_INFO, and Sched_Info::spec_cond.
Referenced by Lsched_postpass_code_scheduling().
int Lsched_get_br_pad_value (L_Oper * oper)
Definition at line 1999 of file l_schedule.c.
Referenced by Lsched_determine_pad_for_vliw(), and Lsched_pad_cycles_for_vliw().
int Lsched_get_cb_end_pad_value (L_Cb * cb)
Definition at line 1975 of file l_schedule.c.
Referenced by Lsched_determine_pad_for_vliw(), and Lsched_pad_cycles_end_of_cb_for_vliw().
int Lsched_get_cb_start_pad_value (L_Cb * cb)
Definition at line 1951 of file l_schedule.c.
References NO_CB_PAD.
Referenced by Lsched_determine_pad_for_vliw(), Lsched_pad_cycles_end_of_cb_for_vliw(), Lsched_pad_cycles_for_vliw(), and Lsched_pad_cycles_start_of_cb_for_vliw().
void Lsched_init (Parm_Macro_List * command_line_macro_list, char * lmdes_file_name)
Definition at line 293 of file l_schedule.c.
References BASIC_BLOCK, GENERAL, L_create_alloc_pool(), L_create_queue(), L_load_parameters_aliased(), L_mcb_init(), L_read_parm_lsched(), Ldep_allow_downward_code_perc, Ldep_allow_upward_code_perc, Ldep_init(), Lsched_branch_increase, Lsched_branches_per_cycle(), Lsched_demote_all_the_way, Lsched_do_sentinel_recovery, Lsched_include_only_oper_lt_hb, Lsched_processor_model, Lsched_total_issue_slots, MCB, not_ready_queue, Operand_ready_pool, pending_ready_queue, priority_ready_queue, regpres_ready_queue, RESTRICTED, RU_map_create(), RU_set_max_pred(), Sched_Info_pool, scheduled_queue, SENTINEL, Sq_entry_pool, Squeue_pool, and WRITEBACK_SUPPRESSION.
void Lsched_init_etimes_and_ltimes (L_Cb * cb)
Definition at line 744 of file l_schedule.c.
References Sched_Info::etime, Sched_Info::ltimes, NULL, Dep_Info::oper, and SCHED_INFO.
Referenced by Lsched_schedule_block().
int Lsched_is_branch (int proc_opc)
Definition at line 1366 of file l_schedule.c.
References IS_BRANCH, IS_CTL, and SENTINEL.
Referenced by L_find_next_branch(), Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), Lsched_schedule_block(), wbs_insert_check(), and wbs_remove_check().
int Lsched_issue_time (L_Oper * oper)
Definition at line 168 of file l_schedule.c.
References NULL, and SCHED_INFO.
int Lsched_latency (L_Oper * oper)
Definition at line 185 of file l_schedule.c.
References NULL, Sched_Info::relative_latency, and SCHED_INFO.
Referenced by Lsched_completion_time().
int Lsched_loads_per_cycle (void)
Definition at line 144 of file l_schedule.c.
References Lsched_loads_each_cycle.
void Lsched_make_ready (L_Cb * cb, int oper_issue_time, Sched_Info * sinfo, Sched_Info * dep_sinfo, int to_index, int from_index, int distance)
Definition at line 1421 of file l_schedule.c.
References Sched_Info::earliest_slot, FILLER, Sched_Info::issue_slot, L_dequeue(), L_enqueue_min_to_max_1(), Lsched_fill_delay_slots, Lsched_infinite_issue, Lsched_processor_model, Lsched_update_ctl_delay_sinfo(), Sched_Info::mdes_info, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, pending_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_SELECTED_ALT, and RU_SELECTED_ALT_ID.
Referenced by L_mcb_delete_check(), and wbs_delete_check().
int Lsched_need_pad (L_Cb * target, L_Oper * oper, int overextend)
Definition at line 2033 of file l_schedule.c.
References IS_IGNORE, NULL, and SCHED_INFO.
Referenced by Lsched_determine_pad_for_vliw().
static void Lsched_pad_cycles_end_of_cb_for_vliw (L_Cb * cb) [static]
Definition at line 2187 of file l_schedule.c.
References IS_IGNORE, Lsched_create_nop(), Lsched_get_cb_end_pad_value(), Lsched_get_cb_start_pad_value(), and SCHED_INFO.
Referenced by Lsched_correct_schedule_for_vliw().
static void Lsched_pad_cycles_for_vliw (L_Func * fn, L_Cb * cb) [static]
Definition at line 2217 of file l_schedule.c.
References Lsched_create_jump(), Lsched_create_nop(), Lsched_get_br_pad_value(), Lsched_get_cb_start_pad_value(), NULL, and SCHED_INFO.
Referenced by Lsched_correct_schedule_for_vliw().
static void Lsched_pad_cycles_start_of_cb_for_vliw (L_Cb * cb) [static]
Definition at line 2157 of file l_schedule.c.
References IS_IGNORE, Lsched_create_nop(), Lsched_get_cb_start_pad_value(), NO_CB_PAD, NULL, and SCHED_INFO.
Referenced by Lsched_correct_schedule_for_vliw().
static void Lsched_pad_slots_with_nops (L_Cb * cb) [static]
Definition at line 1885 of file l_schedule.c.
References IS_IGNORE, Sched_Info::issue_slot, Sched_Info::issue_time, Lsched_create_nop(), Lsched_pad_vliw_slots_with_nops, Lsched_total_issue_slots, NULL, and SCHED_INFO.
Referenced by Lsched_correct_schedule_for_vliw().
void Lsched_postpass_code_scheduling (L_Func * fn)
Definition at line 2888 of file l_schedule.c.
References EXTERN_LOG_FILE, IS_IGNORE, IS_UCOND_BRANCH, L_annotate_instr(), L_build_dependence_graph(), L_create_sched_info(), L_delete_dependence_graph(), L_find_next_branch(), L_print_schedule(), L_update_sched_info(), Ldep_allow_downward_code_perc, Ldep_allow_upward_code_perc, Ldep_mark_safe(), LDEP_MODE_ACYCLIC, LDEP_POSTPASS, Lsched_add_isl_attr(), Lsched_correct_schedule_for_vliw(), Lsched_debug_lower_sched_cb_bound, Lsched_debug_postpass_scheduling, Lsched_debug_upper_sched_cb_bound, Lsched_debug_use_sched_cb_bounds, Lsched_do_fill_nonsquashing_branches, Lsched_do_fill_squashing_branches, Lsched_do_fill_unfilled_branches, Lsched_do_postpass_scheduling, Lsched_fill_delay_slots, Lsched_fill_nonsquashing_branches(), Lsched_fill_squashing_branches(), Lsched_fill_unfilled_branches(), Lsched_func_complete(), Lsched_is_branch(), Lsched_latest_br, Lsched_num_opers, Lsched_prepass, Lsched_processor_model, Lsched_schedule_block(), Lsched_static_fall_thru_weight, Lsched_vliw_has_interlocking, MCB, NULL, SCHED_INFO, SENTINEL, wbs_insert_check(), and WRITEBACK_SUPPRESSION.
void Lsched_prepass_code_scheduling (L_Func * fn)
Definition at line 2692 of file l_schedule.c.
References Ldep_mark_safe(), Lregpres_init_func(), Lsched_debug_lower_sched_cb_bound, Lsched_debug_messages, Lsched_debug_prepass_scheduling, Lsched_debug_upper_sched_cb_bound, Lsched_debug_use_sched_cb_bounds, Lsched_fill_delay_slots, Lsched_prepass, Lsched_static_fall_thru_weight, MCB, NULL, and SENTINEL.
void Lsched_renumber_issue_slots (L_Func * fn)
Definition at line 379 of file l_schedule.c.
References NULL.
Referenced by Lsched_func_complete().
void Lsched_schedule_block (L_Cb * cb)
Definition at line 2485 of file l_schedule.c.
References CAN_SCHEDULE, Sched_Info::current_block, current_time, Sched_Info::dep_info, FALSE, Sched_Info::home_block, Sched_Info::issue_slot, L_dequeue(), L_enqueue(), L_enqueue_min_to_max_1(), L_get_next_entry(), L_get_queue_head(), L_get_queue_size(), L_init_ready_queue(), L_insert_entry(), Dep_Info::level, Lregpres_init_cb(), Lsched_calculate_priority_normal(), Lsched_can_schedule_op(), Lsched_check_for_fill_candidates(), Lsched_determine_etimes(), Lsched_determine_ltimes(), Lsched_fill_delay_slots, Lsched_fix_flows(), Lsched_handle_spilled_branch(), Lsched_infinite_issue, Lsched_infinite_issue_slot, Lsched_init_etimes_and_ltimes(), Lsched_is_branch(), Lsched_num_opers, Lsched_regpres_heuristic, Lsched_schedule_op(), Lsched_schedule_with_delay_op(), Sched_Info::mdes_info, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, pending_ready_queue, priority_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_map_init(), RU_MODE_ACYCLIC, RU_schedule_op_at(), SCHED_INFO, scheduled_queue, and TRUE.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
void Lsched_schedule_op (L_Cb * cb, Sched_Info * sinfo, int spec, int ready_time)
Definition at line 1551 of file l_schedule.c.
References Sched_Info::dep_info, Sched_Info::issue_time, L_update_virt_reg(), Lsched_infinite_issue, Sched_Info::mdes_info, NULL, Sched_Info::oper, Sched_Info::proc_opc, Sched_Info::relative_latency, Sched_Info::ru_info, and RU_SELECTED_ALT_ID.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
int Lsched_stores_per_cycle (void)
Definition at line 152 of file l_schedule.c.
References Lsched_stores_each_cycle.
Variable Documentation
int current_time = 0
Definition at line 104 of file l_schedule.c.
Referenced by Lsched_schedule_block().
int Lmcb_keep_checks = 0
Definition at line 124 of file l_schedule.c.
Referenced by L_mcb_remove_check().
float Lsched_branch_increase = 0.0
Definition at line 120 of file l_schedule.c.
Referenced by Lsched_determine_etimes(), Lsched_determine_ltimes(), and Lsched_init().
int Lsched_debug_lower_sched_cb_bound = 0
Definition at line 78 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
int Lsched_debug_messages = 0
Definition at line 122 of file l_schedule.c.
Referenced by L_mcb_delete_check(), Lsched_mcb_schedule_block(), Lsched_prepass_code_scheduling(), and wbs_delete_check().
int Lsched_debug_nonsquashing_branches = 0
Definition at line 73 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
int Lsched_debug_operation_priority = 0
Definition at line 69 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_debug_postpass_scheduling = 0
Definition at line 71 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_debug_prepass_scheduling = 0
Definition at line 70 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_prepass_code_scheduling().
int Lsched_debug_squashing_branches = 0
Definition at line 72 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_debug_unfilled_branches = 0
Definition at line 74 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_fill_unfilled_branches().
int Lsched_debug_upper_sched_cb_bound = 100000000
Definition at line 79 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
int Lsched_debug_use_sched_cb_bounds = 0
Definition at line 77 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
int Lsched_demote_all_the_way = 0
Definition at line 89 of file l_schedule.c.
Referenced by Lsched_init().
int Lsched_do_fill_nonsquashing_branches = 0
Definition at line 91 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_fill_squashing_branches = 0
Definition at line 90 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_fill_unfilled_branches = 0
Definition at line 92 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_postpass_scheduling = 0
Definition at line 88 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_func_complete(), and Lsched_postpass_code_scheduling().
int Lsched_do_renumber_issue_slots = 0
Definition at line 108 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_func_complete().
int Lsched_do_sentinel_recovery = 0
Definition at line 97 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_init().
int Lsched_fill_delay_slots = 0
Definition at line 121 of file l_schedule.c.
Referenced by Lsched_make_ready(), Lsched_postpass_code_scheduling(), Lsched_prepass_code_scheduling(), and Lsched_schedule_block().
int Lsched_include_only_oper_lt_hb = 0
Definition at line 93 of file l_schedule.c.
Referenced by Lsched_init().
int Lsched_infinite_issue = 0
Definition at line 87 of file l_schedule.c.
Referenced by L_print_schedule(), L_read_parm_lsched(), Lsched_can_schedule_op(), Lsched_make_ready(), Lsched_schedule_block(), and Lsched_schedule_op().
int Lsched_infinite_issue_slot = 0
Definition at line 105 of file l_schedule.c.
Referenced by Lsched_can_schedule_op(), and Lsched_schedule_block().
L_Oper* Lsched_latest_br = NULL
Definition at line 110 of file l_schedule.c.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
int Lsched_loads_each_cycle = 0
Definition at line 102 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_loads_per_cycle().
int Lsched_num_branches_per_cycle = 0
Definition at line 83 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_branches_per_cycle().
int Lsched_num_opers = 0
Definition at line 101 of file l_schedule.c.
Referenced by Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), and Lsched_schedule_block().
int Lsched_pad_height = 1
Definition at line 85 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_pad_vliw_slots_with_nops = 0
Definition at line 106 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_pad_slots_with_nops().
int Lsched_prepass = 0
Definition at line 98 of file l_schedule.c.
Referenced by Lsched_postpass_code_scheduling(), Lsched_prepass_code_scheduling(), RU_can_schedule_op(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().
int Lsched_print_cycle_delimiter = 0
Definition at line 100 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_func_complete().
int Lsched_print_hb_and_spec = 0
Definition at line 99 of file l_schedule.c.
Referenced by L_annotate_instr(), and L_read_parm_lsched().
int Lsched_print_prepass_statistics = 0
Definition at line 95 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_print_spec_condition = 0
Definition at line 96 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_func_complete().
int Lsched_print_statistics = 0
Definition at line 94 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_correct_schedule_for_vliw().
int Lsched_processor_model = MDES_SUPERSCALAR
Definition at line 118 of file l_schedule.c.
Referenced by L_compute_control_dependence(), Lsched_can_schedule_op(), Lsched_init(), Lsched_make_ready(), and Lsched_postpass_code_scheduling().
char* Lsched_profile_info_to_use = NULL
Definition at line 109 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_determine_ltimes().
int Lsched_static_fall_thru_weight = 1
Definition at line 84 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
int Lsched_stores_each_cycle = 0
Definition at line 103 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_stores_per_cycle().
int Lsched_total_issue_slots = 0
Definition at line 119 of file l_schedule.c.
Referenced by Lsched_can_schedule_op(), Lsched_init(), Lsched_pad_slots_with_nops(), and Lsched_schedule_with_delay_op().
int Lsched_use_fan_out = 1
Definition at line 86 of file l_schedule.c.
Referenced by L_insert_entry(), and L_read_parm_lsched().
int Lsched_vliw_has_interlocking = 0
Definition at line 107 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
Squeue * not_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by Lsched_init(), Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
L_Alloc_Pool* Operand_ready_pool = NULL
Definition at line 131 of file l_schedule.c.
Referenced by L_create_sched_info(), L_delete_sched_info(), L_free_sched_info(), L_remove_sched_cb(), and Lsched_init().
Squeue * pending_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by Lsched_init(), Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
Squeue * priority_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), Lsched_init(), Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
Squeue * regpres_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), L_update_virt_reg(), and Lsched_init().
L_Alloc_Pool* Sched_Info_pool = NULL
Definition at line 130 of file l_schedule.c.
Referenced by L_create_sched_info(), L_delete_sched_info(), L_free_sched_info(), L_remove_sched_cb(), and Lsched_init().
Squeue* scheduled_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_mcb_delete_check(), L_mcb_remove_check(), Lsched_init(), Lsched_schedule_block(), and wbs_delete_check().
L_Alloc_Pool* Sq_entry_pool = NULL
Definition at line 129 of file l_schedule.c.
Referenced by L_dequeue(), L_dequeue_entry(), L_enqueue(), L_enqueue_before(), and Lsched_init().
L_Alloc_Pool* Squeue_pool = NULL
Definition at line 128 of file l_schedule.c.
Referenced by L_create_queue(), L_delete_queue(), and Lsched_init().