l_schedule.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include `l_dependence.h`
#include `RU_manager.h`
#include `l_ru_interface.h`
#include <machine/lmdes.h>
#include <machine/lmdes_interface.h>
Data Structures
struct Squeue
struct Sq_entry
struct Regtypes
struct CB_REG_INFO
struct Vreg
struct Sched_Info
Defines
#define TRUE 1
#define FALSE 0
#define FILLER L_OPER_RESERVED_TEMP1
#define FILLED_ABOVE L_OPER_RESERVED_TEMP2
#define FILLED_BELOW L_OPER_RESERVED_TEMP3
#define CAN_SCHEDULE 1
#define CANT_SCHEDULE 2
#define SCHED_INFO(oper) ((Sched_Info *)((oper) $\rightarrow$ ext))
#define IS_UCOND_BRANCH(opc) op_flag_set(opc, OP_FLAG_JMP)
#define IS_COND_BRANCH(opc) op_flag_set(opc, OP_FLAG_CBR)
#define IS_BRANCH(opc) op_flag_set(opc, OP_FLAG_CBR|OP_FLAG_JMP)
#define IS_CTL(opc) op_flag_set(opc, OP_FLAG_CBR|OP_FLAG_JMP|OP_FLAG_RTS|OP_FLAG_JSR)
#define IS_JSR(opc) op_flag_set(opc, OP_FLAG_JSR)
#define IS_MEMORY_LOAD(opc) op_flag_set(opc, OP_FLAG_LOAD)
#define IS_MEMORY_STORE(opc) op_flag_set(opc, OP_FLAG_STORE)
#define IS_MEMORY_OP(opc) op_flag_set(opc, OP_FLAG_STORE|OP_FLAG_LOAD)
#define HAS_DELAY_SLOT(opc) op_flag_set(opc, OP_FLAG_NI)
#define IS_IGNORE(opc) op_flag_set(opc, OP_FLAG_IGNORE)
#define IS_EXCEPTING(opc) op_flag_set(opc, OP_FLAG_EXCEPT)
#define BASIC_BLOCK 0
#define RESTRICTED 1
#define GENERAL 2
#define WBS 3
#define WRITEBACK_SUPPRESSION 3
#define SENTINEL 4
#define BOOSTING 5
#define MCB 6
#define EXTERN_LOG_FILE `IMPACT_001`
#define EXTERN_LOG_FILE_PREPASS `IMPACT_001_PREPASS`
Functions
int Lsched_is_branch (int)
int Lsched_loads_per_cycle (void)
int Lsched_stores_per_cycle (void)
int Lsched_branches_per_cycle (void)
int Lsched_issue_time (L_Oper *)
int Lsched_completion_time (L_Oper *)
int Lsched_latency (L_Oper *)
void Lsched_prepass_code_scheduling (L_Func *)
void Lsched_postpass_code_scheduling (L_Func *)
int Lsched_update_ctl_delay_sinfo (Squeue *, Sched_Info *)
void Lsched_check_for_fill_candidates (Squeue *)
void Lsched_schedule_with_delay_op (L_Cb *, Sched_Info *, int, int, int, int)
void Lsched_fill_nonsquashing_branches (L_Func *)
void Lsched_fill_squashing_branches (L_Func *)
void Lsched_fill_unfilled_branches (L_Func *)
void Lsched_init ()
int Lsched_can_schedule_op (L_Cb *, Sched_Info *, int, int, int *, int *, int *)
void Lsched_schedule_op (L_Cb *, Sched_Info *, int, int)
void Lsched_make_ready (L_Cb *, int, Sched_Info *, Sched_Info *, int, int, int)
void L_delete_sched_info (Sched_Info *)
void Lsched_add_isl_attr (L_Func *fn)
void Lsched_delete_isl_attr (L_Func *fn)
void wbs_remove_check ()
void wbs_insert_check ()
void wbs_extend_live_range ()
void Lsched_schedule_block (L_Cb *cb)
Sched_Info * L_create_sched_info (L_Oper *oper, int home_block, L_Oper *prev_br, L_Oper *post_br)
void L_mcb_remove_check (L_Cb *cb, L_Oper *oper, int ready_time)
Squeue * L_create_queue (char *, int)
void L_delete_queue (Squeue *queue)
void L_reset_queue_current (Squeue *)
Sched_Info * L_get_queue_next_entry (Squeue *)
Sched_Info * L_get_queue_head (Squeue *)
int L_get_queue_size (Squeue *)
void L_enqueue (Squeue *, Sched_Info *)
void L_dequeue (Squeue *, Sched_Info *)
void L_dequeue_from_all (Sched_Info *)
void L_enqueue_min_to_max_1 (Squeue *, Sched_Info *, float)
void L_enqueue_max_to_min_1 (Squeue *, Sched_Info *, float)
void L_enqueue_min_to_max_2 (Squeue *, Sched_Info *, float, float)
void L_enqueue_max_to_min_2 (Squeue *, Sched_Info *, float, float)
void L_enqueue_regpres (Squeue *queue, Sched_Info *sinfo, float key1, float key2)
int L_in_queue (Squeue *, Sched_Info *)
void Lregpres_init_func (L_Func *)
void Lregpres_deinit_func (L_Func *)
void Lregpres_init_cb (L_Cb *)
void L_init_ready_queue ()
Sched_Info * L_get_next_entry ()
void L_insert_entry (Sched_Info *)
void L_update_virt_reg (Sched_Info *)
double L_approx_cb_time (L_Cb *cb)
L_Cb * L_copy_all_oper_in_cb (L_Func *fn, L_Cb *cb)
void Lsched_mcb_prepass_schedule_block (L_Func *fn, L_Cb *cb, L_Cb *nomcb_cb)
void Lsched_mcb_schedule_block (L_Func *fn, L_Cb *cb, L_Cb *nomcb_cb)
int Lsched_handle_spilled_branch (L_Cb *cb, Sched_Info *sinfo)
void L_print_schedule (char *F, L_Func *fn)
Variables
L_Alloc_Pool * Squeue_pool
L_Alloc_Pool * Sq_entry_pool
Squeue * scheduled_queue
Squeue * priority_ready_queue
Squeue * regpres_ready_queue
Squeue * pending_ready_queue
Squeue * not_ready_queue
CB_REG_INFO preg_info
CB_REG_INFO ireg_info
CB_REG_INFO freg_info
CB_REG_INFO dreg_info
int Lsched_use_register_pressure_heuristic
int Lsched_register_pressure_threshhold
Vreg * virt_reg
char * Lsched_model_name
int Lsched_model
int Lsched_processor_model
int Lsched_total_issue_slots
int Lsched_debug_prepass_scheduling
int Lsched_debug_postpass_scheduling
int Lsched_debug_messages
int Lsched_do_postpass_scheduling
char * Lsched_profile_info_to_use
int Lsched_use_fan_out
int Lsched_infinite_issue
int Lsched_debug_squashing_branches
int Lsched_debug_nonsquashing_branches
int Lsched_debug_unfilled_branches
int Lsched_do_fill_squashing_branches
int Lsched_do_fill_nonsquashing_branches
int Lsched_do_fill_unfilled_branches
int Lsched_fill_delay_slots
int Lsched_include_only_oper_lt_hb
int Lsched_print_statistics
int Lsched_print_prepass_statistics
int Lsched_demote_all_the_way
int Lsched_do_sentinel_recovery
int Lsched_prepass
L_Oper * Lsched_latest_br
int Lsched_use_register_pressure_heuristic
int Lsched_register_pressure_threshhold
int Lsched_regpres_heuristic
int Lsched_num_branches_per_cycle
L_Alloc_Pool * Operand_ready_pool
L_Alloc_Pool * Sched_Info_pool
Define Documentation
#define BASIC_BLOCK 0
Definition at line 340 of file l_schedule.h.
Referenced by Lsched_init().
#define BOOSTING 5
Definition at line 346 of file l_schedule.h.
#define CAN_SCHEDULE 1
Definition at line 191 of file l_schedule.h.
Referenced by Lsched_can_schedule_op(), Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
#define CANT_SCHEDULE 2
Definition at line 192 of file l_schedule.h.
Referenced by Lsched_can_schedule_op().
#define EXTERN_LOG_FILE `IMPACT_001`
Definition at line 386 of file l_schedule.h.
Referenced by Lsched_postpass_code_scheduling().
#define EXTERN_LOG_FILE_PREPASS `IMPACT_001_PREPASS`
Definition at line 387 of file l_schedule.h.
#define FALSE 0
Definition at line 100 of file l_schedule.h.
Referenced by Lregpres_init_func(), and Lsched_schedule_block().
#define FILLED_ABOVE L_OPER_RESERVED_TEMP2
Definition at line 182 of file l_schedule.h.
Referenced by Lsched_fill_from_target(), Lsched_fill_nonsquashing_slots(), Lsched_fill_squashing_branches(), Lsched_fill_unfilled_branches(), and Lsched_schedule_with_delay_op().
#define FILLED_BELOW L_OPER_RESERVED_TEMP3
Definition at line 183 of file l_schedule.h.
Referenced by Lsched_fill_from_target(), Lsched_fill_squashing_branches(), Lsched_fill_unfilled_branches(), Lsched_handle_spilled_branch(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
#define FILLER L_OPER_RESERVED_TEMP1
Definition at line 181 of file l_schedule.h.
Referenced by Lsched_fill_from_target(), Lsched_fill_squashing_branches(), Lsched_handle_spilled_branch(), Lsched_make_ready(), and Lsched_schedule_with_delay_op().
#define GENERAL 2
Definition at line 342 of file l_schedule.h.
Referenced by Lsched_init().
#define HAS_DELAY_SLOT(opc) op_flag_set(opc, OP_FLAG_NI)
Definition at line 334 of file l_schedule.h.
Referenced by Lsched_handle_spilled_branch(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
#define IS_BRANCH(opc) op_flag_set(opc, OP_FLAG_CBR|OP_FLAG_JMP)
Definition at line 323 of file l_schedule.h.
Referenced by L_update_virt_reg(), Lregpres_init_cb(), and Lsched_is_branch().
#define IS_COND_BRANCH(opc) op_flag_set(opc, OP_FLAG_CBR)
Definition at line 322 of file l_schedule.h.
Referenced by Lsched_determine_etimes().
#define IS_CTL(opc) op_flag_set(opc, OP_FLAG_CBR|OP_FLAG_JMP|OP_FLAG_RTS|OP_FLAG_JSR)
Definition at line 324 of file l_schedule.h.
Referenced by Lsched_handle_spilled_branch(), Lsched_is_branch(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
#define IS_EXCEPTING(opc) op_flag_set(opc, OP_FLAG_EXCEPT)
Definition at line 336 of file l_schedule.h.
Referenced by wbs_extend_live_range(), and wbs_insert_check().
#define IS_IGNORE(opc) op_flag_set(opc, OP_FLAG_IGNORE)
Definition at line 335 of file l_schedule.h.
Referenced by Lsched_cb_completion_time(), Lsched_determine_pad_for_vliw(), Lsched_mcb_schedule_block(), Lsched_need_pad(), Lsched_pad_cycles_end_of_cb_for_vliw(), Lsched_pad_cycles_start_of_cb_for_vliw(), Lsched_pad_slots_with_nops(), and Lsched_postpass_code_scheduling().
#define IS_JSR(opc) op_flag_set(opc, OP_FLAG_JSR)
Definition at line 325 of file l_schedule.h.
Referenced by Lregpres_init_cb().
#define IS_MEMORY_LOAD(opc) op_flag_set(opc, OP_FLAG_LOAD)
Definition at line 328 of file l_schedule.h.
#define IS_MEMORY_OP(opc) op_flag_set(opc, OP_FLAG_STORE|OP_FLAG_LOAD)
Definition at line 330 of file l_schedule.h.
#define IS_MEMORY_STORE(opc) op_flag_set(opc, OP_FLAG_STORE)
Definition at line 329 of file l_schedule.h.
Referenced by Lsched_handle_spilled_branch().
#define IS_UCOND_BRANCH(opc) op_flag_set(opc, OP_FLAG_JMP)
Definition at line 321 of file l_schedule.h.
Referenced by Lregpres_init_cb(), Lsched_determine_etimes(), Lsched_determine_ltimes(), Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
#define MCB 6
Definition at line 347 of file l_schedule.h.
Referenced by Lsched_init(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
#define RESTRICTED 1
Definition at line 341 of file l_schedule.h.
Referenced by Lsched_init().
#define SCHED_INFO(oper) ((Sched_Info *)((oper) $\rightarrow$ ext))
Definition at line 317 of file l_schedule.h.
Referenced by L_add_check_ptr_to_oper(), L_add_check_to_check_dep(), L_annotate_instr(), L_approx_cb_time(), L_free_oper_list_cb(), L_free_sched_info(), L_insert_correction_code(), L_mcb_add_store_to_load_list(), L_mcb_delete_check(), L_mcb_insert_check(), L_mcb_insert_check_and_rem_dependences(), L_mcb_remove_check(), L_print_schedule(), L_remove_sched_cb(), Lregpres_init_cb(), Lsched_add_isl_attr(), Lsched_calculate_priority_normal(), Lsched_can_schedule_op(), Lsched_cb_completion_time(), Lsched_completion_time(), Lsched_determine_etimes(), Lsched_determine_ltimes(), Lsched_fill_from_target(), Lsched_fill_squashing_branches(), Lsched_fill_unfilled_branches(), Lsched_fix_flows(), Lsched_func_complete(), Lsched_handle_spilled_branch(), Lsched_init_etimes_and_ltimes(), Lsched_issue_time(), Lsched_latency(), Lsched_mcb_schedule_block(), Lsched_need_pad(), Lsched_pad_cycles_end_of_cb_for_vliw(), Lsched_pad_cycles_for_vliw(), Lsched_pad_cycles_start_of_cb_for_vliw(), Lsched_pad_slots_with_nops(), Lsched_postpass_code_scheduling(), Lsched_schedule_block(), Lsched_update_ctl_delay_sinfo(), wbs_delete_check(), wbs_extend_live_range(), wbs_insert_check(), and wbs_remove_check().
#define SENTINEL 4
Definition at line 345 of file l_schedule.h.
Referenced by Lsched_init(), Lsched_is_branch(), Lsched_postpass_code_scheduling(), and Lsched_prepass_code_scheduling().
#define TRUE 1
Definition at line 99 of file l_schedule.h.
Referenced by Lregpres_init_func(), and Lsched_schedule_block().
#define WBS 3
Definition at line 343 of file l_schedule.h.
#define WRITEBACK_SUPPRESSION 3
Definition at line 344 of file l_schedule.h.
Referenced by Lsched_init(), and Lsched_postpass_code_scheduling().
Function Documentation
double L_approx_cb_time (L_Cb * cb)
Definition at line 101 of file l_statistic.c.
References Lsched_completion_time(), NULL, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
L_Cb* L_copy_all_oper_in_cb (L_Func * fn, L_Cb * cb)
Definition at line 364 of file l_mcb.c.
References NULL, and Dep_Info::oper.
Squeue* L_create_queue (char *, int)
Definition at line 68 of file l_queue.c.
References Squeue::current, Squeue::head, L_alloc(), Squeue::name, NULL, Squeue::size, Squeue_pool, and Squeue::tail.
Referenced by Lregpres_init_func(), and Lsched_init().
Sched_Info* L_create_sched_info (L_Oper * oper, int home_block, L_Oper * prev_br, L_Oper * post_br)
Definition at line 585 of file l_schedule.c.
References Sched_Info::benefit, Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, Sched_Info::check_op, Sched_Info::current_block, Regtypes::d, Sched_Info::def_set, Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, Sched_Info::entry_list, Sched_Info::etime, Sched_Info::extend_lr_down, Regtypes::f, Sched_Info::home_block, Regtypes::i, Sched_Info::id, Sched_Info::index, Sched_Info::instr_prob, Sched_Info::issue_slot, Sched_Info::issue_time, Sched_Info::kill_set, L_alloc(), L_create_ru_info_oper(), Sched_Info::ltimes, Sched_Info::mdes_info, Dep_Info::n_input_dep, Sched_Info::not_taken_instr_prob, NULL, Sched_Info::num_depend, Sched_Info::on_stack, Sched_Info::oper, Operand_ready_pool, Sched_Info::operand_ready_times, Sched_Info::orig_block, Regtypes::p, Sched_Info::post_br, Sched_Info::prev_br, Sched_Info::priority, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::relative_latency, Sched_Info::rsort_key1, Sched_Info::rsort_key2, Sched_Info::ru_info, Sched_Info_pool, Sched_Info::scheduled, Sched_Info::sort_key1, Dep_Info::spec_cond, Sched_Info::spec_cond, Sched_Info::store_list, Sched_Info::taken_instr_prob, and Sched_Info::weight.
Referenced by L_mcb_insert_check(), Lsched_create_jump(), Lsched_create_nop(), Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), and wbs_insert_check().
void L_delete_queue (Squeue * queue)
Definition at line 84 of file l_queue.c.
References L_free(), Squeue::name, Squeue::size, and Squeue_pool.
Referenced by Lregpres_deinit_func().
void L_delete_sched_info (Sched_Info *)
Definition at line 698 of file l_schedule.c.
References Sched_Info::branch_kill_set, L_delete_ru_info_oper(), L_free(), Sched_Info::ltimes, NULL, Sched_Info::oper, Dep_Info::oper, Operand_ready_pool, Sched_Info::operand_ready_times, Sched_Info::relative_latency, Sched_Info::ru_info, and Sched_Info_pool.
Referenced by L_mcb_delete_check(), Lsched_func_complete(), and wbs_delete_check().
void L_dequeue (Squeue *, Sched_Info *)
Definition at line 161 of file l_queue.c.
References Squeue::current, entry, Squeue::head, L_free(), L_reset_queue_current(), NULL, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_update_virt_reg(), Lsched_make_ready(), Lsched_schedule_block(), and Lsched_update_ctl_delay_sinfo().
void L_dequeue_from_all (Sched_Info *)
Definition at line 256 of file l_queue.c.
References entry, Sched_Info::entry_list, L_dequeue_entry(), and NULL.
Referenced by L_mcb_delete_check(), Lsched_schedule_with_delay_op(), and wbs_delete_check().
void L_enqueue (Squeue *, Sched_Info *)
Definition at line 130 of file l_queue.c.
References entry, Sched_Info::entry_list, Squeue::head, L_alloc(), Sq_entry::next_entry, NULL, Sq_entry::prev_queue, Squeue::size, Sq_entry_pool, and Squeue::tail.
Referenced by L_enqueue_max_to_min_1(), L_enqueue_max_to_min_2(), L_enqueue_min_to_max_1(), L_enqueue_min_to_max_2(), L_enqueue_regpres(), Lregpres_add_virt_reg_use(), Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
void L_enqueue_max_to_min_1 (Squeue *, Sched_Info *, float)
Definition at line 421 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, and Squeue::tail.
void L_enqueue_max_to_min_2 (Squeue *, Sched_Info *, float, float)
Definition at line 514 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, Sched_Info::sort_key2, and Squeue::tail.
Referenced by L_insert_entry().
void L_enqueue_min_to_max_1 (Squeue *, Sched_Info *, float)
Definition at line 376 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, and Squeue::tail.
Referenced by Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
void L_enqueue_min_to_max_2 (Squeue *, Sched_Info *, float, float)
Definition at line 466 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sq_entry::sinfo, Sched_Info::sort_key1, Sched_Info::sort_key2, and Squeue::tail.
void L_enqueue_regpres (Squeue * queue, Sched_Info * sinfo, float key1, float key2)
Definition at line 562 of file l_queue.c.
References Squeue::current, Squeue::head, L_enqueue(), L_enqueue_before(), Sq_entry::next_entry, NULL, Sq_entry::prev_entry, Sched_Info::rsort_key1, Sched_Info::rsort_key2, Sq_entry::sinfo, and Squeue::tail.
Referenced by L_insert_entry(), and L_update_virt_reg().
Sched_Info* L_get_next_entry ()
Definition at line 606 of file l_regpres.c.
References L_get_queue_next_entry(), L_get_queue_size(), Lregpres_problem, Lsched_regpres_heuristic, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
Sched_Info* L_get_queue_head (Squeue *)
Definition at line 113 of file l_queue.c.
References Squeue::head, NULL, Sq_entry::sinfo, and Squeue::size.
Referenced by L_update_virt_reg(), and Lsched_schedule_block().
Sched_Info* L_get_queue_next_entry (Squeue *)
Definition at line 97 of file l_queue.c.
References Squeue::current, Squeue::head, Sq_entry::next_entry, NULL, and Sq_entry::sinfo.
Referenced by L_get_next_entry(), Lsched_check_for_fill_candidates(), and Lsched_schedule_with_delay_op().
int L_get_queue_size (Squeue *)
Definition at line 121 of file l_queue.c.
References Squeue::size.
Referenced by L_get_next_entry(), L_update_virt_reg(), and Lsched_schedule_block().
int L_in_queue (Squeue *, Sched_Info *)
Definition at line 610 of file l_queue.c.
References Sched_Info::entry_list, Sq_entry::next_entry, NULL, and Sq_entry::queue.
Referenced by L_mcb_delete_check(), L_mcb_remove_check(), L_update_virt_reg(), and wbs_delete_check().
void L_init_ready_queue ()
Definition at line 598 of file l_regpres.c.
References L_reset_queue_current(), Lsched_regpres_heuristic, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
void L_insert_entry (Sched_Info *)
Definition at line 616 of file l_regpres.c.
References Sched_Info::benefit, Sched_Info::dep_info, L_enqueue_max_to_min_2(), L_enqueue_regpres(), Lsched_regpres_heuristic, Lsched_use_fan_out, Dep_Info::n_output_dep, Sched_Info::priority, priority_ready_queue, and regpres_ready_queue.
Referenced by Lsched_schedule_block().
void L_mcb_remove_check (L_Cb * cb, L_Oper * oper, int ready_time)
Definition at line 1573 of file l_mcb.c.
References L_in_queue(), L_mcb_delete_check(), Lmcb_keep_checks, NULL, SCHED_INFO, and scheduled_queue.
void L_print_schedule (char * F, L_Func * fn)
Definition at line 223 of file l_statistic.c.
References Lsched_completion_time(), Lsched_infinite_issue, NULL, RU_SELECTED_ALT_ID, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
void L_reset_queue_current (Squeue *)
Definition at line 92 of file l_queue.c.
References Squeue::current.
Referenced by L_dequeue(), L_dequeue_entry(), L_init_ready_queue(), and Lsched_check_for_fill_candidates().
void L_update_virt_reg (Sched_Info *)
Definition at line 630 of file l_regpres.c.
References Sched_Info::benefit, Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, Vreg::ctype, Regtypes::d, Sched_Info::def_set, Regtypes::f, Regtypes::i, IS_BRANCH, Sched_Info::kill_set, L_dequeue(), L_enqueue_regpres(), L_get_queue_head(), L_get_queue_size(), L_in_queue(), Lregpres_compute_benefit(), Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lsched_regpres_heuristic, Sched_Info::oper, Regtypes::p, Sched_Info::priority, Sched_Info::proc_opc, regpres_ready_queue, Vreg::use_queue, and virt_reg.
Referenced by Lsched_schedule_op().
void Lregpres_deinit_func (L_Func *)
Definition at line 412 of file l_regpres.c.
References L_delete_queue(), Lsched_regpres_heuristic, NULL, num_virt_reg, and virt_reg.
void Lregpres_init_cb (L_Cb *)
Definition at line 429 of file l_regpres.c.
References Sched_Info::branch_kill_set, Sched_Info::branch_kill_set_size, CB_REG_INFO::current_reg, Sched_Info::def_set, dreg_info, freg_info, ireg_info, IS_BRANCH, IS_JSR, IS_UCOND_BRANCH, Lregpres_add_virt_reg_use(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_problem, Lsched_regpres_heuristic, NULL, num_virt_reg, Dep_Info::oper, preg_info, Sched_Info::proc_opc, SCHED_INFO, Set_2array(), Set_size(), Set_subtract(), and virt_reg.
Referenced by Lsched_schedule_block().
void Lregpres_init_func (L_Func *)
Definition at line 236 of file l_regpres.c.
References CALLEE, CB_REG_INFO::callee_reg, CB_REG_INFO::callee_thresh, CALLER, CB_REG_INFO::caller_reg, CB_REG_INFO::caller_thresh, CB_REG_INFO::change, Vreg::ctype, Regtypes::d, dreg_info, Regtypes::f, FALSE, freg_info, Regtypes::i, ireg_info, L_create_queue(), Lsched_register_pressure_threshhold, Lsched_regpres_heuristic, Lsched_use_register_pressure_heuristic, NULL, num_virt_reg, Dep_Info::oper, Regtypes::p, preg_info, CB_REG_INFO::size, TRUE, and virt_reg.
Referenced by Lsched_prepass_code_scheduling().
void Lsched_add_isl_attr (L_Func * fn)
Definition at line 2370 of file l_schedule.c.
References Sched_Info::issue_slot, Sched_Info::issue_time, NULL, Sched_Info::relative_latency, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
int Lsched_branches_per_cycle (void)
Definition at line 160 of file l_schedule.c.
References Lsched_num_branches_per_cycle.
Referenced by Lsched_init().
int Lsched_can_schedule_op (L_Cb *, Sched_Info *, int, int, int *, int *, int *)
Definition at line 1652 of file l_schedule.c.
References CAN_SCHEDULE, CANT_SCHEDULE, DEP_DELAYS_EXCEPTION, Sched_Info::dep_info, DEP_SILENT, Sched_Info::earliest_slot, Sched_Info::home_block, Sched_Info::issue_slot, Sched_Info::issue_time, Lsched_infinite_issue, Lsched_infinite_issue_slot, Lsched_processor_model, Lsched_total_issue_slots, Sched_Info::mdes_info, NULL, Sched_Info::operand_ready_times, Sched_Info::prev_br, Sched_Info::ready_time, RU_can_schedule_op(), Sched_Info::ru_info, SCHED_INFO, Sched_Info::scheduled, and Dep_Info::spec_cond.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
void Lsched_check_for_fill_candidates (Squeue *)
Definition at line 705 of file l_delay_slots.c.
References L_get_queue_next_entry(), L_reset_queue_current(), Lsched_update_ctl_delay_sinfo(), and NULL.
Referenced by Lsched_schedule_block().
int Lsched_completion_time (L_Oper *)
Definition at line 176 of file l_schedule.c.
References Lsched_latency(), NULL, and SCHED_INFO.
Referenced by L_approx_cb_time(), L_print_schedule(), and Lsched_determine_pad_for_vliw().
void Lsched_delete_isl_attr (L_Func * fn)
Definition at line 2409 of file l_schedule.c.
void Lsched_fill_nonsquashing_branches (L_Func *)
Definition at line 375 of file l_delay_slots.c.
References Lsched_fill_from_target(), and Lsched_fill_nonsquashing_slots().
Referenced by Lsched_postpass_code_scheduling().
void Lsched_fill_squashing_branches (L_Func *)
Definition at line 385 of file l_delay_slots.c.
References FILLED_ABOVE, FILLED_BELOW, FILLER, L_alter_branch_destination(), NULL, Sched_Info::ru_info, RU_SELECTED_ALT_ID, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
void Lsched_fill_unfilled_branches (L_Func *)
Definition at line 495 of file l_delay_slots.c.
References FILLED_ABOVE, FILLED_BELOW, Lsched_debug_unfilled_branches, NULL, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
int Lsched_handle_spilled_branch (L_Cb * cb, Sched_Info * sinfo)
Definition at line 560 of file l_delay_slots.c.
References Sched_Info::delay_sinfo, FILLED_BELOW, FILLER, HAS_DELAY_SLOT, IS_CTL, IS_MEMORY_STORE, NULL, Sched_Info::oper, and SCHED_INFO.
Referenced by Lsched_schedule_block().
void Lsched_init ()
int Lsched_is_branch (int)
Definition at line 1366 of file l_schedule.c.
References IS_BRANCH, IS_CTL, and SENTINEL.
Referenced by L_find_next_branch(), Lsched_mcb_schedule_block(), Lsched_postpass_code_scheduling(), Lsched_schedule_block(), wbs_insert_check(), and wbs_remove_check().
int Lsched_issue_time (L_Oper *)
Definition at line 168 of file l_schedule.c.
References NULL, and SCHED_INFO.
int Lsched_latency (L_Oper *)
Definition at line 185 of file l_schedule.c.
References NULL, Sched_Info::relative_latency, and SCHED_INFO.
Referenced by Lsched_completion_time().
int Lsched_loads_per_cycle (void)
Definition at line 144 of file l_schedule.c.
References Lsched_loads_each_cycle.
void Lsched_make_ready (L_Cb *, int, Sched_Info *, Sched_Info *, int, int, int)
Definition at line 1421 of file l_schedule.c.
References Sched_Info::earliest_slot, FILLER, Sched_Info::issue_slot, L_dequeue(), L_enqueue_min_to_max_1(), Lsched_fill_delay_slots, Lsched_infinite_issue, Lsched_processor_model, Lsched_update_ctl_delay_sinfo(), Sched_Info::mdes_info, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, pending_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_SELECTED_ALT, and RU_SELECTED_ALT_ID.
Referenced by L_mcb_delete_check(), and wbs_delete_check().
void Lsched_mcb_prepass_schedule_block (L_Func * fn, L_Cb * cb, L_Cb * nomcb_cb)
void Lsched_mcb_schedule_block (L_Func * fn, L_Cb * cb, L_Cb * nomcb_cb)
Definition at line 1340 of file l_mcb.c.
References IS_IGNORE, IS_UCOND_BRANCH, L_approx_cb_time(), L_build_dependence_graph(), L_create_sched_info(), L_delete_dependence_graph(), L_find_next_branch(), L_free(), L_free_oper_list_cb(), L_free_sched_info(), L_insert_correction_code(), L_insert_fall_thru_code(), L_mcb_convert_to_parent(), L_mcb_insert_check_and_rem_dependences(), LDEP_MODE_ACYCLIC, LDEP_PREPASS, Lsched_debug_messages, Lsched_is_branch(), Lsched_latest_br, Lsched_num_opers, Lsched_schedule_block(), MCB_MIN_CB_WEIGHT, MIN_MCB_SPEEDUP, NULL, and SCHED_INFO.
void Lsched_postpass_code_scheduling (L_Func *)
Definition at line 2888 of file l_schedule.c.
References EXTERN_LOG_FILE, IS_IGNORE, IS_UCOND_BRANCH, L_annotate_instr(), L_build_dependence_graph(), L_create_sched_info(), L_delete_dependence_graph(), L_find_next_branch(), L_print_schedule(), L_update_sched_info(), Ldep_allow_downward_code_perc, Ldep_allow_upward_code_perc, Ldep_mark_safe(), LDEP_MODE_ACYCLIC, LDEP_POSTPASS, Lsched_add_isl_attr(), Lsched_correct_schedule_for_vliw(), Lsched_debug_lower_sched_cb_bound, Lsched_debug_postpass_scheduling, Lsched_debug_upper_sched_cb_bound, Lsched_debug_use_sched_cb_bounds, Lsched_do_fill_nonsquashing_branches, Lsched_do_fill_squashing_branches, Lsched_do_fill_unfilled_branches, Lsched_do_postpass_scheduling, Lsched_fill_delay_slots, Lsched_fill_nonsquashing_branches(), Lsched_fill_squashing_branches(), Lsched_fill_unfilled_branches(), Lsched_func_complete(), Lsched_is_branch(), Lsched_latest_br, Lsched_num_opers, Lsched_prepass, Lsched_processor_model, Lsched_schedule_block(), Lsched_static_fall_thru_weight, Lsched_vliw_has_interlocking, MCB, NULL, SCHED_INFO, SENTINEL, wbs_insert_check(), and WRITEBACK_SUPPRESSION.
void Lsched_prepass_code_scheduling (L_Func *)
Definition at line 2692 of file l_schedule.c.
References Ldep_mark_safe(), Lregpres_init_func(), Lsched_debug_lower_sched_cb_bound, Lsched_debug_messages, Lsched_debug_prepass_scheduling, Lsched_debug_upper_sched_cb_bound, Lsched_debug_use_sched_cb_bounds, Lsched_fill_delay_slots, Lsched_prepass, Lsched_static_fall_thru_weight, MCB, NULL, and SENTINEL.
void Lsched_schedule_block (L_Cb * cb)
Definition at line 2485 of file l_schedule.c.
References CAN_SCHEDULE, Sched_Info::current_block, current_time, Sched_Info::dep_info, FALSE, Sched_Info::home_block, Sched_Info::issue_slot, L_dequeue(), L_enqueue(), L_enqueue_min_to_max_1(), L_get_next_entry(), L_get_queue_head(), L_get_queue_size(), L_init_ready_queue(), L_insert_entry(), Dep_Info::level, Lregpres_init_cb(), Lsched_calculate_priority_normal(), Lsched_can_schedule_op(), Lsched_check_for_fill_candidates(), Lsched_determine_etimes(), Lsched_determine_ltimes(), Lsched_fill_delay_slots, Lsched_fix_flows(), Lsched_handle_spilled_branch(), Lsched_infinite_issue, Lsched_infinite_issue_slot, Lsched_init_etimes_and_ltimes(), Lsched_is_branch(), Lsched_num_opers, Lsched_regpres_heuristic, Lsched_schedule_op(), Lsched_schedule_with_delay_op(), Sched_Info::mdes_info, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, pending_ready_queue, priority_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_map_init(), RU_MODE_ACYCLIC, RU_schedule_op_at(), SCHED_INFO, scheduled_queue, and TRUE.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
void Lsched_schedule_op (L_Cb *, Sched_Info *, int, int)
Definition at line 1551 of file l_schedule.c.
References Sched_Info::dep_info, Sched_Info::issue_time, L_update_virt_reg(), Lsched_infinite_issue, Sched_Info::mdes_info, NULL, Sched_Info::oper, Sched_Info::proc_opc, Sched_Info::relative_latency, Sched_Info::ru_info, and RU_SELECTED_ALT_ID.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
void Lsched_schedule_with_delay_op (L_Cb *, Sched_Info *, int, int, int, int)
Definition at line 715 of file l_delay_slots.c.
References CAN_SCHEDULE, Sched_Info::current_block, Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, FILLED_ABOVE, FILLED_BELOW, FILLER, HAS_DELAY_SLOT, Sched_Info::id, Dep_Info::input_dep, IS_CTL, Sched_Info::issue_slot, L_DEP_CNT, L_dequeue_from_all(), L_enqueue(), L_enqueue_min_to_max_1(), L_get_queue_next_entry(), L_remove_dep(), Lsched_can_schedule_op(), Lsched_debug_nonsquashing_branches, Lsched_schedule_op(), Lsched_total_issue_slots, Sched_Info::mdes_info, Dep_Info::n_input_dep, Dep_Info::n_output_dep, not_ready_queue, NULL, Sched_Info::num_depend, Sched_Info::oper, Sched_Info::operand_ready_times, Dep_Info::output_dep, pending_ready_queue, priority_ready_queue, Sched_Info::proc_opc, Sched_Info::ready_time, Sched_Info::ru_info, RU_schedule_op_at(), RU_unschedule_op(), and Sched_Info::scheduled.
Referenced by Lsched_schedule_block().
int Lsched_stores_per_cycle (void)
Definition at line 152 of file l_schedule.c.
References Lsched_stores_each_cycle.
int Lsched_update_ctl_delay_sinfo (Squeue *, Sched_Info *)
Definition at line 594 of file l_delay_slots.c.
References Sched_Info::delay_sinfo, Sched_Info::dep_info, Sched_Info::earliest_slot, FILLED_BELOW, HAS_DELAY_SLOT, Sched_Info::id, IS_CTL, L_DEP_CNT, L_dequeue(), L_enqueue_min_to_max_1(), Lsched_debug_nonsquashing_branches, Dep_Info::n_output_dep, not_ready_queue, Sched_Info::num_depend, Sched_Info::oper, Dep_Info::output_dep, pending_ready_queue, Sched_Info::priority, Sched_Info::proc_opc, Sched_Info::ready_time, SCHED_INFO, L_Dep::to_oper, and L_Dep::type.
Referenced by Lsched_check_for_fill_candidates(), and Lsched_make_ready().
void wbs_extend_live_range ()
void wbs_insert_check ()
Referenced by Lsched_postpass_code_scheduling().
void wbs_remove_check ()
Variable Documentation
CB_REG_INFO dreg_info
Definition at line 81 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
CB_REG_INFO freg_info
Definition at line 80 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
CB_REG_INFO ireg_info
Definition at line 79 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
int Lsched_debug_messages
Definition at line 122 of file l_schedule.c.
Referenced by L_mcb_delete_check(), Lsched_mcb_schedule_block(), Lsched_prepass_code_scheduling(), and wbs_delete_check().
int Lsched_debug_nonsquashing_branches
Definition at line 73 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
int Lsched_debug_postpass_scheduling
Definition at line 71 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_debug_prepass_scheduling
Definition at line 70 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_prepass_code_scheduling().
int Lsched_debug_squashing_branches
Definition at line 72 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_debug_unfilled_branches
Definition at line 74 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_fill_unfilled_branches().
int Lsched_demote_all_the_way
Definition at line 89 of file l_schedule.c.
Referenced by Lsched_init().
int Lsched_do_fill_nonsquashing_branches
Definition at line 91 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_fill_squashing_branches
Definition at line 90 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_fill_unfilled_branches
Definition at line 92 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_postpass_code_scheduling().
int Lsched_do_postpass_scheduling
Definition at line 88 of file l_schedule.c.
Referenced by L_read_parm_lsched(), Lsched_func_complete(), and Lsched_postpass_code_scheduling().
int Lsched_do_sentinel_recovery
Definition at line 97 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_init().
int Lsched_fill_delay_slots
Definition at line 121 of file l_schedule.c.
Referenced by Lsched_make_ready(), Lsched_postpass_code_scheduling(), Lsched_prepass_code_scheduling(), and Lsched_schedule_block().
int Lsched_include_only_oper_lt_hb
Definition at line 93 of file l_schedule.c.
Referenced by Lsched_init().
int Lsched_infinite_issue
Definition at line 87 of file l_schedule.c.
Referenced by L_print_schedule(), L_read_parm_lsched(), Lsched_can_schedule_op(), Lsched_make_ready(), Lsched_schedule_block(), and Lsched_schedule_op().
struct L_Oper* Lsched_latest_br
Definition at line 110 of file l_schedule.c.
Referenced by Lsched_mcb_schedule_block(), and Lsched_postpass_code_scheduling().
int Lsched_model
char* Lsched_model_name
int Lsched_num_branches_per_cycle
Definition at line 83 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_branches_per_cycle().
int Lsched_prepass
Definition at line 98 of file l_schedule.c.
Referenced by Lsched_postpass_code_scheduling(), Lsched_prepass_code_scheduling(), RU_can_schedule_op(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().
int Lsched_print_prepass_statistics
Definition at line 95 of file l_schedule.c.
Referenced by L_read_parm_lsched().
int Lsched_print_statistics
Definition at line 94 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_correct_schedule_for_vliw().
int Lsched_processor_model
Definition at line 118 of file l_schedule.c.
Referenced by L_compute_control_dependence(), Lsched_can_schedule_op(), Lsched_init(), Lsched_make_ready(), and Lsched_postpass_code_scheduling().
char* Lsched_profile_info_to_use
Definition at line 109 of file l_schedule.c.
Referenced by L_read_parm_lsched(), and Lsched_determine_ltimes().
int Lsched_register_pressure_threshhold
Definition at line 72 of file l_regpres.c.
Referenced by L_read_parm_lsched(), and Lregpres_init_func().
int Lsched_register_pressure_threshhold
Definition at line 72 of file l_regpres.c.
int Lsched_regpres_heuristic
Definition at line 73 of file l_regpres.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), L_update_virt_reg(), Lregpres_deinit_func(), Lregpres_init_cb(), Lregpres_init_func(), and Lsched_schedule_block().
int Lsched_total_issue_slots
Definition at line 119 of file l_schedule.c.
Referenced by Lsched_can_schedule_op(), Lsched_init(), Lsched_pad_slots_with_nops(), and Lsched_schedule_with_delay_op().
int Lsched_use_fan_out
Definition at line 86 of file l_schedule.c.
Referenced by L_insert_entry(), and L_read_parm_lsched().
int Lsched_use_register_pressure_heuristic
Definition at line 71 of file l_regpres.c.
Referenced by L_read_parm_lsched(), and Lregpres_init_func().
int Lsched_use_register_pressure_heuristic
Definition at line 71 of file l_regpres.c.
Squeue * not_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by Lsched_init(), Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
L_Alloc_Pool* Operand_ready_pool
Definition at line 131 of file l_schedule.c.
Referenced by L_create_sched_info(), L_delete_sched_info(), L_free_sched_info(), L_remove_sched_cb(), and Lsched_init().
Squeue * pending_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by Lsched_init(), Lsched_make_ready(), Lsched_schedule_block(), Lsched_schedule_with_delay_op(), and Lsched_update_ctl_delay_sinfo().
CB_REG_INFO preg_info
Definition at line 78 of file l_regpres.c.
Referenced by Lregpres_dec_current(), Lregpres_inc_current(), Lregpres_inc_set(), Lregpres_init_cb(), and Lregpres_init_func().
Squeue * priority_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), Lsched_init(), Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
Squeue * regpres_ready_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_get_next_entry(), L_init_ready_queue(), L_insert_entry(), L_update_virt_reg(), and Lsched_init().
L_Alloc_Pool* Sched_Info_pool
Definition at line 130 of file l_schedule.c.
Referenced by L_create_sched_info(), L_delete_sched_info(), L_free_sched_info(), L_remove_sched_cb(), and Lsched_init().
Squeue* scheduled_queue
Definition at line 112 of file l_schedule.c.
Referenced by L_mcb_delete_check(), L_mcb_remove_check(), Lsched_init(), Lsched_schedule_block(), and wbs_delete_check().
L_Alloc_Pool* Sq_entry_pool
Definition at line 129 of file l_schedule.c.
Referenced by L_dequeue(), L_dequeue_entry(), L_enqueue(), L_enqueue_before(), and Lsched_init().
L_Alloc_Pool* Squeue_pool
Definition at line 128 of file l_schedule.c.
Referenced by L_create_queue(), L_delete_queue(), and Lsched_init().
Vreg* virt_reg
Definition at line 77 of file l_regpres.c.
Referenced by L_update_virt_reg(), Lregpres_add_virt_reg_use(), Lregpres_deinit_func(), Lregpres_init_cb(), and Lregpres_init_func().