l_statistic.c File Reference
#include <config.h>
#include `l_schedule.h`
Functions
static double L_taken_weight (L_Cb *cb, L_Oper *oper)
static double L_fall_thru_weight (L_Cb *cb, L_Oper *oper)
double L_approx_cb_time (L_Cb *cb)
void L_print_schedule (char *F, L_Func *fn)
Function Documentation
double L_approx_cb_time (L_Cb * cb)
Definition at line 101 of file l_statistic.c.
References Lsched_completion_time(), NULL, and SCHED_INFO.
Referenced by Lsched_mcb_schedule_block().
static double L_fall_thru_weight (L_Cb * cb, L_Oper * oper) [static]
Definition at line 91 of file l_statistic.c.
References L_taken_weight().
void L_print_schedule (char * F, L_Func * fn)
Definition at line 223 of file l_statistic.c.
References Lsched_completion_time(), Lsched_infinite_issue, NULL, RU_SELECTED_ALT_ID, and SCHED_INFO.
Referenced by Lsched_postpass_code_scheduling().
static double L_taken_weight (L_Cb * cb, L_Oper * oper) [static]
Definition at line 73 of file l_statistic.c.
Referenced by L_fall_thru_weight().