l_wbs.c File Reference
#include <config.h>
#include `l_schedule.h`
Functions
static void wbs_delete_check (L_Cb *cb, L_Oper *check, int current_time)
void wbs_insert_check (L_Cb *cb)
void wbs_extend_live_range (L_Cb *cb)
void wbs_remove_check (L_Cb *cb, Sched_Info *branch_sinfo, int current_time)
Function Documentation
static void wbs_delete_check (L_Cb	* cb, L_Oper 	* check, int current_time) [static]
Definition at line 85 of file l_wbs.c.
References DEP_INFO, L_Dep::distance, L_Dep::from_index, L_Dep::from_oper, Dep_Info::input_dep, Sched_Info::issue_slot, L_delete_dependence_info(), L_delete_sched_info(), L_dequeue_from_all(), L_in_queue(), L_remove_dep(), Lsched_debug_messages, Lsched_make_ready(), Dep_Info::n_input_dep, Dep_Info::n_output_dep, NULL, Sched_Info::num_depend, Dep_Info::output_dep, SCHED_INFO, scheduled_queue, L_Dep::to_index, L_Dep::to_oper, and L_Dep::type.
Referenced by wbs_remove_check().
void wbs_extend_live_range (L_Cb * cb)
Definition at line 348 of file l_wbs.c.
References Sched_Info::current_block, Sched_Info::extend_lr_down, Sched_Info::home_block, IS_EXCEPTING, NULL, Sched_Info::prev_br, and SCHED_INFO.
void wbs_insert_check (L_Cb 		* cb)
Definition at line 165 of file l_wbs.c.
References Sched_Info::current_block, DEP_CNT_OPERAND, Sched_Info::dep_info, DEP_INFO, Dep_Info::input_dep, IS_EXCEPTING, L_add_dep(), L_create_sched_info(), L_DEP_CNT, L_find_dep(), L_new_dep_info(), Ldep_except_branch_perc_limit, Lsched_is_branch(), Sched_Info::mdes_info, NULL, Sched_Info::oper, Dep_Info::output_dep, Sched_Info::post_br, Sched_Info::prev_br, Sched_Info::proc_opc, SCHED_INFO, and Sched_Info::weight.
void wbs_remove_check (L_Cb 	* cb, Sched_Info	* branch_sinfo, int current_time)
Definition at line 403 of file l_wbs.c.
References DEP_INFO, Sched_Info::dep_info, Lsched_is_branch(), Dep_Info::n_input_dep, L_Dep::next_dep, NULL, Sched_Info::num_depend, Sched_Info::proc_opc, SCHED_INFO, L_Dep::to_oper, and wbs_delete_check().