old_sm_rmap.c File Reference
#include <config.h>
#include <stdio.h>
#include `old_sm.h`
#include <machine/mdes2.h>
#include <library/l_alloc_new.h>
Defines
#define DEBUG_RMAP_RESIZE 0
#define DEBUG_RMAP 0
#define TAKE_STATS 0
Functions
void OLD_SM_commit_choices (unsigned int *map, SM_Table *table, unsigned short *choices_made)
OLD_SM_Cb * OLD_SM_new_cb (Mdes2 *mdes2, OLD_SM_Func *sm_func, L_Cb *cb)
void OLD_SM_delete_cb (OLD_SM_Cb *sm_cb)
void OLD_SM_check_map (OLD_SM_Cb *sm_cb)
void OLD_SM_expand_map_end_offset (OLD_SM_Cb *sm_cb, int max_init_offset)
void OLD_SM_expand_map_start_offset (OLD_SM_Cb *sm_cb, int min_init_offset)
void OLD_SM_init_for_max_usage (OLD_SM_Cb *sm_cb, int max_usage_offset)
void OLD_SM_init_for_min_usage (OLD_SM_Cb *sm_cb, int min_usage_offset)
void OLD_SM_create_map (OLD_SM_Cb *sm_cb, int min_usage_offset, int max_usage_offset)
int OLD_SM_sched_table (OLD_SM_Cb *sm_cb, SM_Table *table, int time, unsigned short min_slot, unsigned short max_slot, int commit, Mdes_Stats *stats)
int OLD_SM_choose_first_avail_options (unsigned int *map, SM_Table *table, unsigned short *choices_made, unsigned int min_slot, unsigned int max_slot, Mdes_Stats *stats)
void OLD_SM_print_option (FILE *out, SM_Mdes *sm_mdes, SM_Option *option)
void OLD_SM_print_map (FILE *out, SM_Mdes *sm_mdes, OLD_SM_Cb *sm_cb)
void OLD_SM_print_stats (FILE *out, Mdes_Stats *stats)
Variables
static L_Alloc_Pool * OLD_SM_Cb_pool = NULL
Define Documentation
#define DEBUG_RMAP 0
Definition at line 68 of file old_sm_rmap.c.
#define DEBUG_RMAP_RESIZE 0
Definition at line 67 of file old_sm_rmap.c.
#define TAKE_STATS 0
Definition at line 69 of file old_sm_rmap.c.
Function Documentation
void OLD_SM_check_map (OLD_SM_Cb * sm_cb)
Definition at line 112 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, and OLD_SM_Cb::min_init_offset.
Referenced by OLD_SM_expand_map_end_offset(), OLD_SM_expand_map_start_offset(), OLD_SM_init_for_max_usage(), and OLD_SM_init_for_min_usage().
int OLD_SM_choose_first_avail_options (unsigned int * map, SM_Table * table, unsigned short * choices_made, unsigned int min_slot, unsigned int max_slot, Mdes_Stats * stats)
Definition at line 694 of file old_sm_rmap.c.
References NULL, and OLD_SM_print_option().
Referenced by OLD_SM_sched_table().
void OLD_SM_commit_choices (unsigned int * map, SM_Table * table, unsigned short * choices_made)
Definition at line 921 of file old_sm_rmap.c.
Referenced by OLD_SM_sched_table().
void OLD_SM_create_map (OLD_SM_Cb * sm_cb, int min_usage_offset, int max_usage_offset)
Definition at line 498 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_array_size, OLD_SM_Cb::map_end_offset, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, OLD_SM_Cb::min_init_offset, NULL, and OLD_SM_init_for_max_usage().
Referenced by OLD_SM_sched_table().
void OLD_SM_delete_cb (OLD_SM_Cb * sm_cb)
Definition at line 102 of file old_sm_rmap.c.
References L_free(), OLD_SM_Cb::map_array, NULL, and OLD_SM_Cb_pool.
Referenced by RU_map_init().
void OLD_SM_expand_map_end_offset (OLD_SM_Cb * sm_cb, int max_init_offset)
Definition at line 137 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_array_size, OLD_SM_Cb::map_end_offset, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, OLD_SM_Cb::min_init_offset, NULL, and OLD_SM_check_map().
Referenced by OLD_SM_init_for_max_usage().
void OLD_SM_expand_map_start_offset (OLD_SM_Cb * sm_cb, int min_init_offset)
Definition at line 217 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_array_size, OLD_SM_Cb::map_end_offset, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, OLD_SM_Cb::min_init_offset, NULL, and OLD_SM_check_map().
Referenced by OLD_SM_init_for_min_usage().
void OLD_SM_init_for_max_usage (OLD_SM_Cb * sm_cb, int max_usage_offset)
Definition at line 308 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_end_offset, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, OLD_SM_check_map(), and OLD_SM_expand_map_end_offset().
Referenced by OLD_SM_create_map(), and OLD_SM_sched_table().
void OLD_SM_init_for_min_usage (OLD_SM_Cb * sm_cb, int min_usage_offset)
Definition at line 402 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::min_init_offset, OLD_SM_check_map(), and OLD_SM_expand_map_start_offset().
Referenced by OLD_SM_sched_table().
OLD_SM_Cb* OLD_SM_new_cb (Mdes2 * mdes2, OLD_SM_Func * sm_func, L_Cb * cb)
Definition at line 77 of file old_sm_rmap.c.
References OLD_SM_Cb::cb, L_alloc(), L_create_alloc_pool(), OLD_SM_Cb::map_array, NULL, OLD_SM_Cb_pool, OLD_SM_Cb::sm_func, and OLD_SM_Cb::sm_mdes.
Referenced by RU_map_init().
void OLD_SM_print_map (FILE * out, SM_Mdes * sm_mdes, OLD_SM_Cb * sm_cb)
Definition at line 1049 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, and OLD_SM_Cb::min_init_offset.
Referenced by RU_map_init().
void OLD_SM_print_option (FILE * out, SM_Mdes * sm_mdes, SM_Option * option)
Definition at line 1016 of file old_sm_rmap.c.
References name.
Referenced by OLD_SM_choose_first_avail_options().
void OLD_SM_print_stats (FILE * out, Mdes_Stats * stats)
Definition at line 1146 of file old_sm_rmap.c.
int OLD_SM_sched_table (OLD_SM_Cb * sm_cb, SM_Table * table, int time, unsigned short min_slot, unsigned short max_slot, int commit, Mdes_Stats * stats)
Definition at line 558 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, NULL, OLD_SM_choose_first_avail_options(), OLD_SM_commit_choices(), OLD_SM_create_map(), OLD_SM_init_for_max_usage(), OLD_SM_init_for_min_usage(), and OLD_SM_Cb::sm_mdes.
Referenced by RU_can_schedule_op(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().
Variable Documentation
L_Alloc_Pool* OLD_SM_Cb_pool = NULL [static]
Definition at line 71 of file old_sm_rmap.c.
Referenced by OLD_SM_delete_cb(), and OLD_SM_new_cb().