old_sm.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <library/md.h>
#include <machine/mdes2.h>
#include <machine/sm_mdes.h>
Data Structures
struct OLD_SM_Dep
struct OLD_SM_Oper
struct OLD_SM_Cb
struct OLD_SM_Func
struct OLD_SM_Stats
Functions
OLD_SM_Cb * OLD_SM_new_cb (struct Mdes2 *mdes2, OLD_SM_Func *sm_func, L_Cb *cb)
void OLD_SM_delete_cb (OLD_SM_Cb *sm_cb)
int OLD_SM_sched_table (OLD_SM_Cb *sm_cb, SM_Table *table, int time, unsigned short min_slot, unsigned short max_slot, int commit, Mdes_Stats *stats)
void OLD_SM_print_option (FILE *out, SM_Mdes *sm_mdes, SM_Option *option)
void OLD_SM_print_map (FILE *out, SM_Mdes *sm_mdes, OLD_SM_Cb *sm_cb)
int OLD_SM_choose_first_avail_options (unsigned int *map, SM_Table *table, unsigned short *choices_made, unsigned int min_slot, unsigned int max_slot, Mdes_Stats *stats)
Function Documentation
int OLD_SM_choose_first_avail_options (unsigned int * map, SM_Table * table, unsigned short * choices_made, unsigned int min_slot, unsigned int max_slot, Mdes_Stats * stats)
Definition at line 694 of file old_sm_rmap.c.
References NULL, and OLD_SM_print_option().
Referenced by OLD_SM_sched_table().
void OLD_SM_delete_cb (OLD_SM_Cb * sm_cb)
Definition at line 102 of file old_sm_rmap.c.
References L_free(), OLD_SM_Cb::map_array, NULL, and OLD_SM_Cb_pool.
Referenced by RU_map_init().
OLD_SM_Cb* OLD_SM_new_cb (struct Mdes2 * mdes2, OLD_SM_Func * sm_func, L_Cb * cb)
Definition at line 77 of file old_sm_rmap.c.
References OLD_SM_Cb::cb, L_alloc(), L_create_alloc_pool(), OLD_SM_Cb::map_array, NULL, OLD_SM_Cb_pool, OLD_SM_Cb::sm_func, and OLD_SM_Cb::sm_mdes.
Referenced by RU_map_init().
void OLD_SM_print_map (FILE * out, SM_Mdes * sm_mdes, OLD_SM_Cb * sm_cb)
Definition at line 1049 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, OLD_SM_Cb::map_start_offset, OLD_SM_Cb::max_init_offset, and OLD_SM_Cb::min_init_offset.
Referenced by RU_map_init().
void OLD_SM_print_option (FILE * out, SM_Mdes * sm_mdes, SM_Option * option)
Definition at line 1016 of file old_sm_rmap.c.
References name.
Referenced by OLD_SM_choose_first_avail_options().
int OLD_SM_sched_table (OLD_SM_Cb * sm_cb, SM_Table * table, int time, unsigned short min_slot, unsigned short max_slot, int commit, Mdes_Stats * stats)
Definition at line 558 of file old_sm_rmap.c.
References OLD_SM_Cb::map_array, NULL, OLD_SM_choose_first_avail_options(), OLD_SM_commit_choices(), OLD_SM_create_map(), OLD_SM_init_for_max_usage(), OLD_SM_init_for_min_usage(), and OLD_SM_Cb::sm_mdes.
Referenced by RU_can_schedule_op(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().