RU_manager.h File Reference
#include <config.h>
#include <stdio.h>
#include <malloc.h>
#include <stdarg.h>
#include <Lcode/l_code.h>
#include <machine/lmdes.h>
Data Structures
struct _RU_Alloc_Header
struct _RU_Alloc_Data
struct _RU_Info
struct _RU_Node
struct _RU_Map
Defines
#define RU_MAP_DEFAULT_SIZE 128
#define RU_MODE_ACYCLIC 0
#define RU_MODE_CYCLIC 1
#define RU_SELECTED_ALT(info) ((Mdes_Alt *)(info $\rightarrow$ selected_alt))
#define RU_SELECTED_ALT_ID(info) ((int)(info $\rightarrow$ selected_alt $\rightarrow$ id))
Typedefs
typedef _RU_Alloc_Header RU_Alloc_Header
typedef _RU_Alloc_Data RU_Alloc_Data
typedef _RU_Info RU_Info
typedef _RU_Node RU_Node
typedef _RU_Map RU_Map
Functions
void RU_set_max_pred (int)
int * RU_pred_alloc ()
void RU_pred_free (int *)
void RU_pred_print_alloc_data (FILE *, int)
RU_Info * RU_info_alloc ()
void RU_info_free (RU_Info *)
void RU_info_print_alloc_data (FILE *, int)
RU_Info * RU_info_create (L_Oper *, int *)
void RU_info_delete (RU_Info *)
RU_Node * RU_node_alloc ()
void RU_node_free (RU_Node *)
void RU_node_print_alloc_data (FILE *, int)
RU_Node * RU_node_create (RU_Info *)
void RU_node_delete (RU_Map *, RU_Node *)
void RU_node_delete_all (RU_Node *)
void RU_node_insert_before (RU_Map *, RU_Node *, RU_Node *)
void RU_node_insert_after (RU_Map *, RU_Node *, RU_Node *)
RU_Node * RU_node_find (RU_Node *, RU_Info *, Mdes_Rused *)
void RU_map_create (int)
void RU_map_realloc ()
void RU_map_init (int, int)
void RU_map_delete ()
int RU_number_of_alts (RU_Info *, Mdes_Info *, int)
void RU_update_usage_count (RU_Info *, Mdes_Info *, int *, int)
int RU_alt_flags_compatible (RU_Info *, Mdes_Alt *, int)
int RU_can_place (int, Mdes_Rused *, int)
void RU_place (int, Mdes_Rused *, int, RU_Info *)
void RU_unplace (int, Mdes_Rused *, RU_Info *)
int RU_schedule_op (RU_Info *, Mdes_Info *, int *, int, int, int, int)
int RU_schedule_op_reverse (RU_Info *, Mdes_Info *, int *, int, int, int, int)
int RU_can_schedule_op (RU_Info *, Mdes_Info *, int *, int, int, int, int)
int RU_schedule_op_at (RU_Info *, Mdes_Info *, int *, int, int, int)
void RU_unschedule_op (RU_Info *)
Variables
RU_Map * RU_map
int RU_map_length
int RU_map_mode
int RU_map_cycles
int * RU_mask
int RU_mask_width
int RU_max_pred
Define Documentation
#define RU_MAP_DEFAULT_SIZE 128
Definition at line 80 of file RU_manager.h.
Referenced by RU_map_create().
#define RU_MODE_ACYCLIC 0
Definition at line 82 of file RU_manager.h.
Referenced by Lsched_schedule_block().
#define RU_MODE_CYCLIC 1
Definition at line 83 of file RU_manager.h.
Referenced by RU_can_place(), RU_map_init(), RU_place(), and RU_unplace().
#define RU_SELECTED_ALT(info) ((Mdes_Alt *)(info $\rightarrow$ selected_alt))
Definition at line 111 of file RU_manager.h.
Referenced by Lsched_make_ready().
#define RU_SELECTED_ALT_ID(info) ((int)(info $\rightarrow$ selected_alt $\rightarrow$ id))
Definition at line 112 of file RU_manager.h.
Referenced by L_print_schedule(), Lsched_fill_squashing_branches(), Lsched_make_ready(), and Lsched_schedule_op().
Typedef Documentation
typedef struct _RU_Alloc_Data RU_Alloc_Data
typedef struct _RU_Alloc_Header RU_Alloc_Header
typedef struct _RU_Info RU_Info
typedef struct _RU_Map RU_Map
typedef struct _RU_Node RU_Node
Function Documentation
int RU_alt_flags_compatible (RU_Info *, Mdes_Alt *, int)
Definition at line 963 of file RU_manager.c.
References _RU_Info::proc_opc.
Referenced by RU_can_schedule_op(), RU_number_of_alts(), RU_schedule_op(), RU_schedule_op_at(), RU_schedule_op_reverse(), and RU_update_usage_count().
int RU_can_place (int, Mdes_Rused *, int)
Definition at line 982 of file RU_manager.c.
References ERR, _RU_Map::mask, RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_map_realloc(), RU_mask_width, and RU_MODE_CYCLIC.
Referenced by RU_can_schedule_op(), RU_schedule_op(), and RU_schedule_op_at().
int RU_can_schedule_op (RU_Info *, Mdes_Info *, int *, int, int, int, int)
Definition at line 1667 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
Referenced by Lsched_can_schedule_op().
RU_Info* RU_info_alloc ()
Definition at line 203 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_info_alloc_data, and RU_info_alloc_target_size.
Referenced by RU_info_create().
RU_Info* RU_info_create (L_Oper *, int *)
Definition at line 302 of file RU_manager.c.
References _RU_Info::issue_time, NULL, _RU_Info::op, _RU_Info::pred, RU_info_alloc(), _RU_Info::selected_alt, and _RU_Info::slot_used.
Referenced by L_create_ru_info_oper().
void RU_info_delete (RU_Info *)
Definition at line 316 of file RU_manager.c.
References NULL, _RU_Info::op, _RU_Info::pred, RU_info_free(), RU_pred_free(), and _RU_Info::selected_alt.
Referenced by L_delete_ru_info_oper().
void RU_info_free (RU_Info *)
Definition at line 266 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_info_alloc_data.
Referenced by RU_info_delete().
void RU_info_print_alloc_data (FILE *, int)
Definition at line 292 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_info_alloc_data.
void RU_map_create (int)
Definition at line 563 of file RU_manager.c.
References ERR, _RU_Map::first_node, _RU_Map::last_node, _RU_Map::mask, NULL, RU_map, RU_MAP_DEFAULT_SIZE, RU_map_length, RU_mask, and RU_mask_width.
Referenced by Lsched_init().
void RU_map_delete ()
Definition at line 723 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, NULL, RU_map, RU_map_length, RU_mask, and RU_node_delete_all().
void RU_map_init (int, int)
Definition at line 663 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, NULL, OLD_SM_delete_cb(), OLD_SM_new_cb(), OLD_SM_print_map(), RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_mask_width, RU_MODE_CYCLIC, RU_node_delete_all(), and RU_sm_cb.
Referenced by Lsched_schedule_block().
void RU_map_realloc ()
Definition at line 603 of file RU_manager.c.
References ERR, _RU_Map::first_node, _RU_Map::last_node, _RU_Map::mask, NULL, RU_map, RU_map_length, RU_mask, RU_mask_width, and RU_sm_cb.
Referenced by RU_can_place(), and RU_place().
RU_Node* RU_node_alloc ()
Definition at line 338 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_node_alloc_data, and RU_node_alloc_target_size.
Referenced by RU_node_create().
RU_Node* RU_node_create (RU_Info *)
Definition at line 437 of file RU_manager.c.
References node, NULL, and RU_node_alloc().
Referenced by RU_place().
void RU_node_delete (RU_Map *, RU_Node *)
Definition at line 451 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, _RU_Node::next_node, node, NULL, _RU_Node::prev_node, and RU_node_free().
Referenced by RU_unplace().
void RU_node_delete_all (RU_Node *)
Definition at line 485 of file RU_manager.c.
References _RU_Node::next_node, NULL, _RU_Node::prev_node, and RU_node_free().
Referenced by RU_map_delete(), and RU_map_init().
RU_Node* RU_node_find (RU_Node *, RU_Info *, Mdes_Rused *)
Definition at line 533 of file RU_manager.c.
References _RU_Node::info, _RU_Node::next_node, NULL, and _RU_Node::rused.
Referenced by RU_unplace().
void RU_node_free (RU_Node *)
Definition at line 401 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_node_alloc_data.
Referenced by RU_node_delete(), and RU_node_delete_all().
void RU_node_insert_after (RU_Map *, RU_Node *, RU_Node *)
Definition at line 515 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, _RU_Node::next_node, node, and NULL.
void RU_node_insert_before (RU_Map *, RU_Node *, RU_Node *)
Definition at line 497 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, node, NULL, and _RU_Node::prev_node.
Referenced by RU_place().
void RU_node_print_alloc_data (FILE *, int)
Definition at line 427 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_node_alloc_data.
int RU_number_of_alts (RU_Info *, Mdes_Info *, int)
Definition at line 753 of file RU_manager.c.
References NULL, and RU_alt_flags_compatible().
void RU_place (int, Mdes_Rused *, int, RU_Info *)
Definition at line 1017 of file RU_manager.c.
References ERR, node, RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_map_realloc(), RU_mask_width, RU_MODE_CYCLIC, RU_node_create(), and RU_node_insert_before().
int* RU_pred_alloc ()
Definition at line 95 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_max_pred, RU_pred_alloc_data, and RU_pred_alloc_target_size.
Referenced by L_create_ru_info_oper().
void RU_pred_free (int *)
Definition at line 158 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_pred_alloc_data.
Referenced by RU_info_delete().
void RU_pred_print_alloc_data (FILE *, int)
Definition at line 184 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_pred_alloc_data.
int RU_schedule_op (RU_Info *, Mdes_Info *, int *, int, int, int, int)
Definition at line 1073 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
int RU_schedule_op_at (RU_Info *, Mdes_Info *, int *, int, int, int)
Definition at line 1959 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
int RU_schedule_op_reverse (RU_Info *, Mdes_Info *, int *, int, int, int, int)
Definition at line 1370 of file RU_manager.c.
References DEBUG, ERR, _RU_Info::issue_time, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_sm_cb, _RU_Info::selected_alt, and _RU_Info::slot_used.
void RU_set_max_pred (int)
Definition at line 90 of file RU_manager.c.
References RU_max_pred.
Referenced by Lsched_init().
void RU_unplace (int, Mdes_Rused *, RU_Info *)
Definition at line 1049 of file RU_manager.c.
References node, RU_map, RU_map_cycles, RU_map_mode, RU_mask_width, RU_MODE_CYCLIC, RU_node_delete(), and RU_node_find().
Referenced by RU_unschedule_op().
void RU_unschedule_op (RU_Info *)
Definition at line 2247 of file RU_manager.c.
References _RU_Info::issue_time, NULL, RU_unplace(), and _RU_Info::selected_alt.
Referenced by Lsched_schedule_with_delay_op().
void RU_update_usage_count (RU_Info *, Mdes_Info *, int *, int)
Definition at line 855 of file RU_manager.c.
References NULL, RU_alt_flags_compatible(), RU_find_max(), and RU_find_resource_index().
Variable Documentation
RU_Map* RU_map
Definition at line 549 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_create(), RU_map_delete(), RU_map_init(), RU_map_realloc(), RU_place(), and RU_unplace().
int RU_map_cycles
Definition at line 552 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_init(), RU_place(), and RU_unplace().
int RU_map_length
Definition at line 550 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_create(), RU_map_delete(), RU_map_init(), RU_map_realloc(), and RU_place().
int RU_map_mode
Definition at line 551 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_init(), RU_place(), and RU_unplace().
int* RU_mask
Definition at line 553 of file RU_manager.c.
Referenced by RU_map_create(), RU_map_delete(), and RU_map_realloc().
int RU_mask_width
Definition at line 554 of file RU_manager.c.
Referenced by RU_can_place(), RU_can_schedule_op(), RU_map_create(), RU_map_init(), RU_map_realloc(), RU_place(), RU_schedule_op(), RU_schedule_op_at(), and RU_unplace().
int RU_max_pred
Definition at line 86 of file RU_manager.c.
Referenced by RU_pred_alloc(), and RU_set_max_pred().