RU_manager.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdarg.h>
#include `l_schedule.h`
#include `old_sm.h`
Defines
#define ERR stdout
Functions
void RU_set_max_pred (int max)
int * RU_pred_alloc ()
void RU_pred_free (int *ptr)
void RU_pred_print_alloc_data (FILE *F, int verbose)
RU_Info * RU_info_alloc ()
void RU_info_free (RU_Info *ptr)
void RU_info_print_alloc_data (FILE *F, int verbose)
RU_Info * RU_info_create (L_Oper *op, int *pred)
void RU_info_delete (RU_Info *info)
RU_Node * RU_node_alloc ()
void RU_node_free (RU_Node *ptr)
void RU_node_print_alloc_data (FILE *F, int verbose)
RU_Node * RU_node_create (RU_Info *info)
void RU_node_delete (RU_Map *map, RU_Node *node)
void RU_node_delete_all (RU_Node *list)
void RU_node_insert_before (RU_Map *map, RU_Node *before_node, RU_Node *node)
void RU_node_insert_after (RU_Map *map, RU_Node *after_node, RU_Node *node)
RU_Node * RU_node_find (RU_Node *list, RU_Info *ru_info, Mdes_Rused *rused)
void RU_map_create (int length)
void RU_map_realloc ()
void RU_map_init (int mode, int cycles)
void RU_map_delete ()
int RU_number_of_alts (RU_Info *ru_info, Mdes_Info *mdes_info, int flags)
static int RU_find_resource_index (Mdes_Rmask *mask)
static int RU_find_max (int *ru_count)
void RU_update_usage_count (RU_Info *ru_info, Mdes_Info *mdes_info, int *ru_count, int flags)
int RU_alt_flags_compatible (RU_Info *ru_info, Mdes_Alt *alt, int flags)
int RU_can_place (int time, Mdes_Rused *rused, int option_num)
void RU_place (int time, Mdes_Rused *rused, int option_num, RU_Info *ru_info)
void RU_unplace (int time, Mdes_Rused *rused, RU_Info *ru_info)
int RU_schedule_op (RU_Info *ru_info, Mdes_Info *mdes_info, int *operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
int RU_schedule_op_reverse (RU_Info *ru_info, Mdes_Info *mdes_info, int *operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
int RU_can_schedule_op (RU_Info *ru_info, Mdes_Info *mdes_info, int *operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
int RU_schedule_op_at (RU_Info *ru_info, Mdes_Info *mdes_info, int *operand_ready_times, int issue_time, int slot, int flags)
void RU_unschedule_op (RU_Info *ru_info)
Variables
int RU_max_pred = 0
int RU_pred_alloc_target_size = 128
static RU_Alloc_Data RU_pred_alloc_data = {0, 0, 0}
int RU_info_alloc_target_size = 128
static RU_Alloc_Data RU_info_alloc_data = {0, 0, 0}
int RU_node_alloc_target_size = 128
static RU_Alloc_Data RU_node_alloc_data = {0, 0, 0}
RU_Map * RU_map = NULL
int RU_map_length = 0
int RU_map_mode = -1
int RU_map_cycles = -1
int * RU_mask = NULL
int RU_mask_width = -1
OLD_SM_Cb * RU_sm_cb = NULL
Define Documentation
#define ERR stdout
Definition at line 77 of file RU_manager.c.
Referenced by RU_can_place(), RU_can_schedule_op(), RU_map_create(), RU_map_realloc(), RU_place(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().
Function Documentation
int RU_alt_flags_compatible (RU_Info * ru_info, Mdes_Alt * alt, int flags)
Definition at line 963 of file RU_manager.c.
References _RU_Info::proc_opc.
Referenced by RU_can_schedule_op(), RU_number_of_alts(), RU_schedule_op(), RU_schedule_op_at(), RU_schedule_op_reverse(), and RU_update_usage_count().
int RU_can_place (int time, Mdes_Rused * rused, int option_num)
Definition at line 982 of file RU_manager.c.
References ERR, _RU_Map::mask, RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_map_realloc(), RU_mask_width, and RU_MODE_CYCLIC.
Referenced by RU_can_schedule_op(), RU_schedule_op(), and RU_schedule_op_at().
int RU_can_schedule_op (RU_Info * ru_info, Mdes_Info * mdes_info, int * operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
Definition at line 1667 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
Referenced by Lsched_can_schedule_op().
static int RU_find_max (int * ru_count) [static]
Definition at line 825 of file RU_manager.c.
References NULL.
Referenced by RU_update_usage_count().
static int RU_find_resource_index (Mdes_Rmask * mask) [static]
Definition at line 778 of file RU_manager.c.
References NULL.
Referenced by RU_update_usage_count().
RU_Info* RU_info_alloc ()
Definition at line 203 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_info_alloc_data, and RU_info_alloc_target_size.
Referenced by RU_info_create().
RU_Info* RU_info_create (L_Oper * op, int * pred)
Definition at line 302 of file RU_manager.c.
References _RU_Info::issue_time, NULL, _RU_Info::op, _RU_Info::pred, RU_info_alloc(), _RU_Info::selected_alt, and _RU_Info::slot_used.
Referenced by L_create_ru_info_oper().
void RU_info_delete (RU_Info * info)
Definition at line 316 of file RU_manager.c.
References NULL, _RU_Info::op, _RU_Info::pred, RU_info_free(), RU_pred_free(), and _RU_Info::selected_alt.
Referenced by L_delete_ru_info_oper().
void RU_info_free (RU_Info * ptr)
Definition at line 266 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_info_alloc_data.
Referenced by RU_info_delete().
void RU_info_print_alloc_data (FILE * F, int verbose)
Definition at line 292 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_info_alloc_data.
void RU_map_create (int length)
Definition at line 563 of file RU_manager.c.
References ERR, _RU_Map::first_node, _RU_Map::last_node, _RU_Map::mask, NULL, RU_map, RU_MAP_DEFAULT_SIZE, RU_map_length, RU_mask, and RU_mask_width.
Referenced by Lsched_init().
void RU_map_delete ()
Definition at line 723 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, NULL, RU_map, RU_map_length, RU_mask, and RU_node_delete_all().
void RU_map_init (int mode, int cycles)
Definition at line 663 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, NULL, OLD_SM_delete_cb(), OLD_SM_new_cb(), OLD_SM_print_map(), RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_mask_width, RU_MODE_CYCLIC, RU_node_delete_all(), and RU_sm_cb.
Referenced by Lsched_schedule_block().
void RU_map_realloc ()
Definition at line 603 of file RU_manager.c.
References ERR, _RU_Map::first_node, _RU_Map::last_node, _RU_Map::mask, NULL, RU_map, RU_map_length, RU_mask, RU_mask_width, and RU_sm_cb.
Referenced by RU_can_place(), and RU_place().
RU_Node* RU_node_alloc ()
Definition at line 338 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_node_alloc_data, and RU_node_alloc_target_size.
Referenced by RU_node_create().
RU_Node* RU_node_create (RU_Info * info)
Definition at line 437 of file RU_manager.c.
References node, NULL, and RU_node_alloc().
Referenced by RU_place().
void RU_node_delete (RU_Map * map, RU_Node * node)
Definition at line 451 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, _RU_Node::next_node, node, NULL, _RU_Node::prev_node, and RU_node_free().
Referenced by RU_unplace().
void RU_node_delete_all (RU_Node * list)
Definition at line 485 of file RU_manager.c.
References _RU_Node::next_node, NULL, _RU_Node::prev_node, and RU_node_free().
Referenced by RU_map_delete(), and RU_map_init().
RU_Node* RU_node_find (RU_Node * list, RU_Info * ru_info, Mdes_Rused * rused)
Definition at line 533 of file RU_manager.c.
References _RU_Node::info, _RU_Node::next_node, NULL, and _RU_Node::rused.
Referenced by RU_unplace().
void RU_node_free (RU_Node * ptr)
Definition at line 401 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_node_alloc_data.
Referenced by RU_node_delete(), and RU_node_delete_all().
void RU_node_insert_after (RU_Map * map, RU_Node * after_node, RU_Node * node)
Definition at line 515 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, _RU_Node::next_node, node, and NULL.
void RU_node_insert_before (RU_Map * map, RU_Node * before_node, RU_Node * node)
Definition at line 497 of file RU_manager.c.
References _RU_Map::first_node, _RU_Map::last_node, node, NULL, and _RU_Node::prev_node.
Referenced by RU_place().
void RU_node_print_alloc_data (FILE * F, int verbose)
Definition at line 427 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_node_alloc_data.
int RU_number_of_alts (RU_Info * ru_info, Mdes_Info * mdes_info, int flags)
Definition at line 753 of file RU_manager.c.
References NULL, and RU_alt_flags_compatible().
void RU_place (int time, Mdes_Rused * rused, int option_num, RU_Info * ru_info)
Definition at line 1017 of file RU_manager.c.
References ERR, node, RU_map, RU_map_cycles, RU_map_length, RU_map_mode, RU_map_realloc(), RU_mask_width, RU_MODE_CYCLIC, RU_node_create(), and RU_node_insert_before().
int* RU_pred_alloc ()
Definition at line 95 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, RU_max_pred, RU_pred_alloc_data, and RU_pred_alloc_target_size.
Referenced by L_create_ru_info_oper().
void RU_pred_free (int * ptr)
Definition at line 158 of file RU_manager.c.
References _RU_Alloc_Data::free, _RU_Alloc_Data::head, _RU_Alloc_Header::next, NULL, and RU_pred_alloc_data.
Referenced by RU_info_delete().
void RU_pred_print_alloc_data (FILE * F, int verbose)
Definition at line 184 of file RU_manager.c.
References _RU_Alloc_Data::allocated, _RU_Alloc_Data::free, and RU_pred_alloc_data.
int RU_schedule_op (RU_Info * ru_info, Mdes_Info * mdes_info, int * operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
Definition at line 1073 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
int RU_schedule_op_at (RU_Info * ru_info, Mdes_Info * mdes_info, int * operand_ready_times, int issue_time, int slot, int flags)
Definition at line 1959 of file RU_manager.c.
References DEBUG, ERR, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_can_place(), RU_mask_width, and RU_sm_cb.
Referenced by Lsched_schedule_block(), and Lsched_schedule_with_delay_op().
int RU_schedule_op_reverse (RU_Info * ru_info, Mdes_Info * mdes_info, int * operand_ready_times, int issue_time, int earliest_slot, int latest_slot, int flags)
Definition at line 1370 of file RU_manager.c.
References DEBUG, ERR, _RU_Info::issue_time, Lsched_prepass, NULL, OLD_SM_sched_table(), _RU_Info::op, RU_alt_flags_compatible(), RU_sm_cb, _RU_Info::selected_alt, and _RU_Info::slot_used.
void RU_set_max_pred (int max)
Definition at line 90 of file RU_manager.c.
References RU_max_pred.
Referenced by Lsched_init().
void RU_unplace (int time, Mdes_Rused * rused, RU_Info * ru_info)
Definition at line 1049 of file RU_manager.c.
References node, RU_map, RU_map_cycles, RU_map_mode, RU_mask_width, RU_MODE_CYCLIC, RU_node_delete(), and RU_node_find().
Referenced by RU_unschedule_op().
void RU_unschedule_op (RU_Info * ru_info)
Definition at line 2247 of file RU_manager.c.
References _RU_Info::issue_time, NULL, RU_unplace(), and _RU_Info::selected_alt.
Referenced by Lsched_schedule_with_delay_op().
void RU_update_usage_count (RU_Info * ru_info, Mdes_Info * mdes_info, int * ru_count, int flags)
Definition at line 855 of file RU_manager.c.
References NULL, RU_alt_flags_compatible(), RU_find_max(), and RU_find_resource_index().
Variable Documentation
RU_Alloc_Data RU_info_alloc_data = {0, 0, 0} [static]
Definition at line 201 of file RU_manager.c.
Referenced by RU_info_alloc(), RU_info_free(), and RU_info_print_alloc_data().
int RU_info_alloc_target_size = 128
Definition at line 200 of file RU_manager.c.
Referenced by RU_info_alloc().
RU_Map* RU_map = NULL
Definition at line 549 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_create(), RU_map_delete(), RU_map_init(), RU_map_realloc(), RU_place(), and RU_unplace().
int RU_map_cycles = -1
Definition at line 552 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_init(), RU_place(), and RU_unplace().
int RU_map_length = 0
Definition at line 550 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_create(), RU_map_delete(), RU_map_init(), RU_map_realloc(), and RU_place().
int RU_map_mode = -1
Definition at line 551 of file RU_manager.c.
Referenced by RU_can_place(), RU_map_init(), RU_place(), and RU_unplace().
int* RU_mask = NULL
Definition at line 553 of file RU_manager.c.
Referenced by RU_map_create(), RU_map_delete(), and RU_map_realloc().
int RU_mask_width = -1
Definition at line 554 of file RU_manager.c.
Referenced by RU_can_place(), RU_can_schedule_op(), RU_map_create(), RU_map_init(), RU_map_realloc(), RU_place(), RU_schedule_op(), RU_schedule_op_at(), and RU_unplace().
int RU_max_pred = 0
Definition at line 86 of file RU_manager.c.
Referenced by RU_pred_alloc(), and RU_set_max_pred().
RU_Alloc_Data RU_node_alloc_data = {0, 0, 0} [static]
Definition at line 336 of file RU_manager.c.
Referenced by RU_node_alloc(), RU_node_free(), and RU_node_print_alloc_data().
int RU_node_alloc_target_size = 128
Definition at line 335 of file RU_manager.c.
Referenced by RU_node_alloc().
RU_Alloc_Data RU_pred_alloc_data = {0, 0, 0} [static]
Definition at line 88 of file RU_manager.c.
Referenced by RU_pred_alloc(), RU_pred_free(), and RU_pred_print_alloc_data().
int RU_pred_alloc_target_size = 128
Definition at line 87 of file RU_manager.c.
Referenced by RU_pred_alloc().
OLD_SM_Cb* RU_sm_cb = NULL
Definition at line 557 of file RU_manager.c.
Referenced by RU_can_schedule_op(), RU_map_init(), RU_map_realloc(), RU_schedule_op(), RU_schedule_op_at(), and RU_schedule_op_reverse().