header_reader.c File Reference
#include <config.h>
#include <ctype.h>
#include `hmdes.h`
Data Structures
struct hparse_info_st
Typedefs
typedef hparse_info_st Hparse_Info
Functions
static void Hparse_line (char *ptr, char *name, char *arg)
static int Hget_next_line (Hparse_Info *hinfo, char *ret_buf)
static void Hskip_to_endif (Hparse_Info *hinfo, char *source, int line)
Msymbol_Table * Hread_header_file (char *file_name)
Typedef Documentation
typedef struct hparse_info_st
 Hparse_Info
Function Documentation
static int Hget_next_line (Hparse_Info * hinfo, char * ret_buf) [static]
Definition at line 251 of file header_reader.c.
References hparse_info_st::comment_level, H_punt(), hparse_info_st::in, hparse_info_st::line, Misspace(), MLINE_SIZE, hparse_info_st::name, and NULL.
Referenced by Hread_header_file(), and Hskip_to_endif().
static void Hparse_line (char * ptr, char * name, char * arg) [static]
Definition at line 224 of file header_reader.c.
Referenced by Hread_header_file().
Msymbol_Table* Hread_header_file (char * file_name)
Definition at line 83 of file header_reader.c.
References H_punt(), Hget_next_line(), Hparse_line(), Hskip_to_endif(), Malloc_name(), Malloc_struct(), Mcreate_symbol_table(), Mfind_symbol(), Minsert_symbol(), MLINE_SIZE, name, NULL, and verbose.
Referenced by hmdes_read_define().
static void Hskip_to_endif (Hparse_Info * hinfo, char * source, int line) [static]
Definition at line 197 of file header_reader.c.
References hparse_info_st::endif_level, H_punt(), Hget_next_line(), and MLINE_SIZE.
Referenced by Hread_header_file().