hmdes.h File Reference
#include <config.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <library/l_alloc_new.h>
#include <ctype.h>
#include <stdarg.h>
Data Structures
struct msymbol_st
struct msymbol_table_st
struct header_file_st
struct hmdes_reg_file_st
struct hmdes_io_node_st
struct hmdes_io_set_st
struct hmdes_io_item_st
struct hmdes_res_sub_st
struct hmdes_resource_st
struct hmdes_res_option_st
struct hmdes_res_node_st
struct hmdes_res_list_st
struct hmdes_latency_st
struct hmdes_class_node_st
struct hmdes_operation_class_st
struct hmdes_flag_st
struct hmdes_flag_list_st
struct hmdes_operation_node_st
struct hmdes_operation_st
struct hmdes_st
struct mparse_item_st
struct mparse_info_st
Defines
#define MITEM_SIZE 401
#define MLINE_SIZE 4001
#define MAX_HEADER_FILES 50
#define MSYMBOL_TABLE_SIZE 256
#define MAX_MASK_SIZE 50
#define MDES_SUPERSCALAR 0
#define MDES_VLIW 1
#define MDES_OVERLAPPING_REQUEST 0x00000001
Typedefs
typedef msymbol_st Msymbol
typedef msymbol_table_st Msymbol_Table
typedef header_file_st Header_File
typedef hmdes_reg_file_st Hmdes_Reg_File
typedef hmdes_io_node_st Hmdes_IO_Node
typedef hmdes_io_set_st Hmdes_IO_Set
typedef hmdes_io_item_st Hmdes_IO_Item
typedef hmdes_res_sub_st Hmdes_Res_Sub
typedef hmdes_resource_st Hmdes_Resource
typedef hmdes_res_option_st Hmdes_Res_Option
typedef hmdes_res_node_st Hmdes_Res_Node
typedef hmdes_res_list_st Hmdes_Res_List
typedef hmdes_latency_st Hmdes_Latency
typedef hmdes_class_node_st Hmdes_Class_Node
typedef hmdes_operation_class_st Hmdes_Operation_Class
typedef hmdes_flag_st Hmdes_Flag
typedef hmdes_flag_list_st Hmdes_Flag_List
typedef hmdes_operation_node_st Hmdes_Operation_Node
typedef hmdes_operation_st Hmdes_Operation
typedef hmdes_st Hmdes
typedef mparse_item_st Mparse_Item
typedef mparse_info_st Mparse_Info
Functions
Msymbol_Table * Hread_header_file (char *file_name)
void Mdie_on_fatal_errors (Mparse_Info *pinfo)
void Hbuild_environment_defines (Msymbol_Table *env_tab, char **envp)
void Hbuild_command_line_defines (Msymbol_Table *cl_tab, char **argv)
Hmdes * create_hmdes (char *hmdes_file_name, char **argv, char **envp)
void hmdes_read_section (Mparse_Info *pinfo, char *name, void(*func)())
void hmdes_read_define (Mparse_Info *pinfo, char *sname)
int Mis_name_next (Mparse_Info *pinfo)
int Mis_next (Mparse_Info *pinfo, char *str)
void Mread_name (Mparse_Info *pinfo, char *name, char *desc)
void Mread_symbol (Mparse_Info *pinfo, Msymbol_Table *table, void **ptr, char *desc)
void Mread_IO_item_symbol (Mparse_Info *pinfo, Msymbol_Table *table, void **ptr, char *terminator)
void Mread_match (Mparse_Info *pinfo, char *str)
int mscan_set (Mparse_Info *pinfo, char *name)
int mread_proc_model (Mparse_Info *pinfo, char *name, int *ptr)
int mread_define_var (Mparse_Info *pinfo, char *name, int *ptr)
void Malloc_struct (void **ptr, int size)
void Malloc_name (char **ptr, char *name)
int Mread_int (Mparse_Info *pinfo, int *ptr)
Msymbol_Table * Mcreate_symbol_table (char *name, int size)
void * Mfind_symbol (Msymbol_Table *table, char *name)
void Minsert_unique_symbol (Mparse_Info *pinfo, Msymbol_Table *table, char *name, void *ptr)
void Minsert_symbol (Msymbol_Table *table, char *name, void *ptr)
void Mprint_symbol_table (FILE *out, Msymbol_Table *table)
int Mhash_name (char *name, int mask)
int find_header_value (Mparse_Info *pinfo, char *name, int *ptr)
void hmdes_read_register_files (Mparse_Info *pinfo)
void Madd_IO_node (Hmdes_IO_Set *IO_set, Hmdes_Reg_File *reg_file)
void hmdes_read_IO_sets (Mparse_Info *pinfo)
void hmdes_read_IO_items (Mparse_Info *pinfo)
void hmdes_add_res_subscript (Mparse_Info *pinfo, Hmdes_Resource *resource, int subscript, int id)
void hmdes_read_resources (Mparse_Info *pinfo)
void Madd_res_option (Mparse_Info *pinfo, Hmdes_Res_Node *node, char *name, int subscript)
void hmdes_read_restables (Mparse_Info *pinfo)
void Mread_latency (Mparse_Info *pinfo, int *ptr)
void hmdes_read_latencies (Mparse_Info *pinfo)
Hmdes_Operation_Class * hmdes_read_class_def (Mparse_Info *pinfo, char *class_name)
void hmdes_read_operation_class (Mparse_Info *pinfo)
void Mfree_flag_list (Hmdes_Flag_List *flag_list)
int Mmatch_flag_lists (Hmdes_Flag_List *list1, Hmdes_Flag_List *list2)
int valid_flag_value (Mparse_Info *pinfo, Hmdes_Flag *flag)
void Mread_flag (Mparse_Info *pinfo, Hmdes_Flag_List *flag_list, char *flag_prefix, char *desc)
void hmdes_read_operations (Mparse_Info *pinfo)
void Mprint_op (FILE *out, Hmdes *hmdes, char *name)
int hmdes_section_end (Mparse_Info *pinfo)
int Mpeek_ahead (Mparse_Info *pinfo, int dist, char *buf)
int Mget_next (Mparse_Info *pinfo, char *buf)
void L_preprocess_line (Mparse_Info *pinfo, char *raw_line, char *buf, int max)
int Misspace (char ch)
char * Mstrip (char *buf)
Mparse_Info * create_mparse_info (char *name, Hmdes *hmdes)
void Mparse_warn (Mparse_Info *pinfo, char *fmt,...)
void Mparse_fatal (Mparse_Info *pinfo, char *fmt,...)
void Mparse_error (Mparse_Info *pinfo, char *fmt,...)
void H_punt (char *fmt,...)
int Mmatch (char *s1, char *s2)
void associate_reg_files (Hmdes *hmdes)
void associate_opcodes (Hmdes *hmdes)
void clear_mask (int *mask, int size)
void set_mask_bit (int *mask, unsigned int bit)
void print_mask (FILE *out, int *mask, int size)
void write_res_node (FILE *out, int mask_size, Hmdes_Res_Node *res_node)
void write_lmdes (Hmdes *hmdes, FILE *out)
Variables
int verbose
Define Documentation
#define MAX_HEADER_FILES 50
Definition at line 76 of file hmdes.h.
Referenced by hmdes_read_define().
#define MAX_MASK_SIZE 50
Definition at line 79 of file hmdes.h.
Referenced by set_mask_bit(), write_lmdes(), and write_res_node().
#define MDES_OVERLAPPING_REQUEST 0x00000001
Definition at line 86 of file hmdes.h.
Referenced by hmdes_read_restables().
#define MDES_SUPERSCALAR 0
Definition at line 82 of file hmdes.h.
Referenced by mread_proc_model().
#define MDES_VLIW 1
Definition at line 83 of file hmdes.h.
Referenced by mread_proc_model().
#define MITEM_SIZE 401
Definition at line 73 of file hmdes.h.
Referenced by associate_reg_files(), create_hmdes(), hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operation_class(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), hmdes_read_section(), hmdes_section_end(), Mis_name_next(), Mis_next(), Mparse_next_line(), Mread_flag(), Mread_int(), Mread_match(), mread_proc_model(), Mread_symbol(), mscan_set(), and write_lmdes().
#define MLINE_SIZE 4001
Definition at line 74 of file hmdes.h.
Referenced by Hget_next_line(), Hread_header_file(), Hskip_to_endif(), L_preprocess_line(), and Mparse_next_line().
#define MSYMBOL_TABLE_SIZE 256
Definition at line 78 of file hmdes.h.
Referenced by create_hmdes().
Typedef Documentation
typedef struct header_file_st
 Header_File
typedef struct hmdes_st
 Hmdes
typedef struct hmdes_class_node_st
 Hmdes_Class_Node
typedef struct hmdes_flag_st
 Hmdes_Flag
typedef struct hmdes_flag_list_st
 Hmdes_Flag_List
typedef struct hmdes_io_item_st
 Hmdes_IO_Item
typedef struct hmdes_io_node_st
 Hmdes_IO_Node
typedef struct hmdes_io_set_st
 Hmdes_IO_Set
typedef struct hmdes_latency_st
 Hmdes_Latency
typedef struct hmdes_operation_st
 Hmdes_Operation
typedef struct hmdes_operation_class_st
 Hmdes_Operation_Class
typedef struct hmdes_operation_node_st
 Hmdes_Operation_Node
typedef struct hmdes_reg_file_st
 Hmdes_Reg_File
typedef struct hmdes_res_list_st
 Hmdes_Res_List
typedef struct hmdes_res_node_st
 Hmdes_Res_Node
typedef struct hmdes_res_option_st
 Hmdes_Res_Option
typedef struct hmdes_res_sub_st
 Hmdes_Res_Sub
typedef struct hmdes_resource_st
 Hmdes_Resource
typedef struct mparse_info_st
 Mparse_Info
typedef struct mparse_item_st
 Mparse_Item
typedef struct msymbol_st
 Msymbol
typedef struct msymbol_table_st
 Msymbol_Table
Function Documentation
void associate_opcodes (Hmdes * hmdes)
Definition at line 3236 of file hmdes.c.
References msymbol_table_st::head, header_table, hmdes_operation_st::id, Mfind_symbol(), header_file_st::name, msymbol_table_st::name, hmdes_operation_st::name, msymbol_st::next_linear, NULL, num_header_files, hmdes_st::operations, msymbol_st::ptr, and header_file_st::table.
void associate_reg_files (Hmdes * hmdes)
Definition at line 3123 of file hmdes.c.
References hmdes_io_set_st::external_id, msymbol_table_st::head, header_table, hmdes_st::IO_sets, Mfind_symbol(), MITEM_SIZE, header_file_st::name, msymbol_table_st::name, hmdes_io_set_st::name, msymbol_st::next_linear, NULL, num_header_files, msymbol_st::ptr, and header_file_st::table.
void clear_mask (int * mask, int size)
Definition at line 3337 of file hmdes.c.
Referenced by write_lmdes(), and write_res_node().
Hmdes* create_hmdes (char * hmdes_file_name, char ** argv, char ** envp)
Definition at line 202 of file hmdes.c.
References create_mparse_info(), hmdes_st::defines_command, hmdes_st::defines_environ, hmdes_st::defines_internal, fatal_parse_errors, hmdes_st::file_name, H_punt(), Hbuild_command_line_defines(), Hbuild_environment_defines(), hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operation_class(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), hmdes_read_section(), hmdes_st::IO_items, hmdes_st::IO_sets, L_create_alloc_pool(), L_free_alloc_pool(), hmdes_st::latencies, Malloc_name(), hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, Mcreate_symbol_table(), Mdie_on_fatal_errors(), Mget_next(), MITEM_SIZE, Mmatch(), Mparse_error(), Mparse_Item_pool, MSYMBOL_TABLE_SIZE, NULL, hmdes_st::op_class, hmdes_st::operations, hmdes_st::processor_model, hmdes_st::reg_file, hmdes_st::res_lists, and hmdes_st::resources.
Mparse_Info* create_mparse_info (char * name, Hmdes * hmdes)
Definition at line 3026 of file hmdes.c.
References mparse_info_st::file_name, H_punt(), mparse_info_st::head, mparse_info_st::hmdes, mparse_info_st::in, mparse_info_st::line, NULL, mparse_info_st::queue_size, mparse_info_st::section_name, and mparse_info_st::tail.
Referenced by create_hmdes().
int find_header_value (Mparse_Info * pinfo, char * name, int * ptr)
Definition at line 842 of file hmdes.c.
References header_table, Mfind_symbol(), Mparse_fatal(), msymbol_table_st::name, header_file_st::name, NULL, num_header_files, and header_file_st::table.
Referenced by hmdes_read_IO_sets(), hmdes_read_operations(), hmdes_read_register_files(), and Mread_flag().
void H_punt (char * fmt, ...)
Definition at line 3828 of file hmdes.c.
Referenced by create_hmdes(), create_mparse_info(), Hget_next_line(), hmdes_read_define(), hmdes_read_IO_sets(), hmdes_read_restables(), Hread_header_file(), Hskip_to_endif(), L_preprocess_line(), Malloc_name(), Malloc_struct(), Mcreate_symbol_table(), Minsert_symbol(), Mpeek_ahead(), Mprint_op(), set_mask_bit(), valid_flag_value(), write_lmdes(), and write_res_node().
void Hbuild_command_line_defines (Msymbol_Table * cl_tab, char ** argv)
Definition at line 155 of file hmdes.c.
References Minsert_symbol(), NULL, and verbose.
Referenced by create_hmdes().
void Hbuild_environment_defines (Msymbol_Table * env_tab, char ** envp)
Definition at line 108 of file hmdes.c.
References Minsert_symbol(), and NULL.
Referenced by create_hmdes().
void hmdes_add_res_subscript (Mparse_Info * pinfo, Hmdes_Resource * resource, int subscript, int id)
Definition at line 1242 of file hmdes.c.
References hmdes_resource_st::head, Malloc_struct(), Mparse_error(), hmdes_resource_st::name, hmdes_res_sub_st::next, NULL, hmdes_resource_st::num_subscripts, hmdes_res_sub_st::subscript, and hmdes_resource_st::tail.
Referenced by hmdes_read_resources().
Hmdes_Operation_Class* hmdes_read_class_def (Mparse_Info * pinfo, char * class_name)
Definition at line 1910 of file hmdes.c.
References mparse_info_st::hmdes, hmdes_st::IO_items, hmdes_st::latencies, Malloc_name(), Malloc_struct(), Minsert_unique_symbol(), Mis_next(), Mread_match(), Mread_symbol(), msymbol_table_st::name, node, NULL, hmdes_st::op_class, and hmdes_st::res_lists.
Referenced by hmdes_read_operation_class(), and hmdes_read_operations().
void hmdes_read_define (Mparse_Info * pinfo, char * sname)
Definition at line 332 of file hmdes.c.
References H_punt(), header_table, mparse_info_st::hmdes, hmdes_section_end(), Hread_header_file(), Malloc_name(), hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, MAX_HEADER_FILES, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, Mdie_on_fatal_errors(), Mget_next(), Mis_next(), MITEM_SIZE, Mparse_error(), Mparse_fatal(), Mparse_warn(), Mpeek_ahead(), mread_define_var(), Mread_match(), mread_proc_model(), num_header_files, hmdes_st::processor_model, header_file_st::table, and verbose.
Referenced by create_hmdes().
void hmdes_read_IO_items (Mparse_Info * pinfo)
Definition at line 1157 of file hmdes.c.
References mparse_info_st::hmdes, hmdes_section_end(), hmdes_st::IO_items, hmdes_st::IO_sets, Malloc_name(), Malloc_struct(), hmdes_st::max_dest_operands, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, Minsert_unique_symbol(), Mis_next(), MITEM_SIZE, Mread_IO_item_symbol(), Mread_match(), Mread_name(), msymbol_table_st::name, and hmdes_st::null_set.
Referenced by create_hmdes().
void hmdes_read_IO_sets (Mparse_Info * pinfo)
Definition at line 1024 of file hmdes.c.
References hmdes_reg_file_st::external_id, find_header_value(), H_punt(), msymbol_table_st::head, mparse_info_st::hmdes, hmdes_section_end(), hmdes_reg_file_st::id, hmdes_st::IO_sets, Madd_IO_node(), Malloc_name(), Malloc_struct(), Mfind_symbol(), Minsert_unique_symbol(), Mis_name_next(), MITEM_SIZE, Mparse_error(), Mread_match(), Mread_name(), Mread_symbol(), msymbol_table_st::name, hmdes_reg_file_st::name, hmdes_io_node_st::next, msymbol_st::next_linear, NULL, hmdes_st::null_set, msymbol_st::ptr, hmdes_io_node_st::reg_file, hmdes_st::reg_file, and verbose.
Referenced by create_hmdes().
void hmdes_read_latencies (Mparse_Info * pinfo)
Definition at line 1825 of file hmdes.c.
References mparse_info_st::hmdes, hmdes_section_end(), hmdes_st::latencies, Malloc_name(), Malloc_struct(), hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, Minsert_unique_symbol(), MITEM_SIZE, Mread_int(), Mread_latency(), Mread_match(), Mread_name(), and msymbol_table_st::name.
Referenced by create_hmdes().
void hmdes_read_operation_class (Mparse_Info * pinfo)
Definition at line 1966 of file hmdes.c.
References mparse_info_st::hmdes, hmdes_read_class_def(), hmdes_section_end(), MITEM_SIZE, and Mread_name().
Referenced by create_hmdes().
void hmdes_read_operations (Mparse_Info * pinfo)
Definition at line 2174 of file hmdes.c.
References hmdes_flag_list_st::bit_version, find_header_value(), hmdes_operation_st::head, hmdes_flag_list_st::head, mparse_info_st::hmdes, hmdes_read_class_def(), hmdes_section_end(), Malloc_name(), Malloc_struct(), Mfind_symbol(), Mfree_flag_list(), Minsert_unique_symbol(), Mis_next(), MITEM_SIZE, Mmatch_flag_lists(), Mparse_fatal(), Mread_flag(), Mread_match(), Mread_name(), Mread_symbol(), hmdes_operation_st::name, hmdes_operation_node_st::next, node, NULL, hmdes_flag_list_st::num_flags, hmdes_st::op_class, hmdes_operation_st::op_flags, hmdes_st::operations, hmdes_operation_st::size, and hmdes_operation_st::tail.
Referenced by create_hmdes().
void hmdes_read_register_files (Mparse_Info * pinfo)
Definition at line 904 of file hmdes.c.
References find_header_value(), mparse_info_st::hmdes, hmdes_section_end(), Malloc_name(), Malloc_struct(), Mfind_symbol(), Minsert_unique_symbol(), MITEM_SIZE, Mmatch(), Mparse_error(), Mread_int(), Mread_match(), Mread_name(), msymbol_table_st::name, NULL, hmdes_st::reg_file, and verbose.
Referenced by create_hmdes().
void hmdes_read_resources (Mparse_Info * pinfo)
Definition at line 1270 of file hmdes.c.
References mparse_info_st::hmdes, hmdes_add_res_subscript(), hmdes_section_end(), Malloc_name(), Malloc_struct(), hmdes_st::max_slot, Minsert_unique_symbol(), Mis_next(), MITEM_SIZE, Mparse_error(), Mparse_fatal(), Mread_int(), Mread_match(), Mread_name(), msymbol_table_st::name, hmdes_res_sub_st::next, NULL, hmdes_st::resources, and hmdes_res_sub_st::subscript.
Referenced by create_hmdes().
void hmdes_read_restables (Mparse_Info * pinfo)
Definition at line 1485 of file hmdes.c.
References hmdes_res_node_st::end_usage, hmdes_res_node_st::flags, H_punt(), hmdes_res_node_st::head, hmdes_resource_st::head, mparse_info_st::hmdes, hmdes_section_end(), hmdes_res_sub_st::id, Madd_res_option(), Malloc_name(), Malloc_struct(), MDES_OVERLAPPING_REQUEST, Mfind_symbol(), minimize_res_lists, Minsert_unique_symbol(), Mis_name_next(), Mis_next(), MITEM_SIZE, Mparse_error(), Mread_int(), Mread_match(), Mread_name(), msymbol_table_st::name, hmdes_res_option_st::next, hmdes_res_node_st::next, hmdes_res_sub_st::next, node, NULL, hmdes_st::res_lists, hmdes_st::resources, hmdes_res_node_st::start_usage, hmdes_res_option_st::subscript, and hmdes_res_sub_st::subscript.
Referenced by create_hmdes().
void hmdes_read_section (Mparse_Info * pinfo, char * name, void(*)() func)
Definition at line 299 of file hmdes.c.
References Mget_next(), MITEM_SIZE, Mmatch(), Mparse_error(), and mparse_info_st::section_name.
Referenced by create_hmdes().
int hmdes_section_end (Mparse_Info * pinfo)
Definition at line 2534 of file hmdes.c.
References Mget_next(), MITEM_SIZE, Mmatch(), Mparse_error(), and Mpeek_ahead().
Referenced by hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operation_class(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), and hmdes_read_restables().
Msymbol_Table* Hread_header_file (char * file_name)
Definition at line 83 of file header_reader.c.
References H_punt(), Hget_next_line(), Hparse_line(), Hskip_to_endif(), Malloc_name(), Malloc_struct(), Mcreate_symbol_table(), Mfind_symbol(), Minsert_symbol(), MLINE_SIZE, name, NULL, and verbose.
Referenced by hmdes_read_define().
void L_preprocess_line (Mparse_Info * pinfo, char * raw_line, char * buf, int max)
Definition at line 2642 of file hmdes.c.
References hmdes_st::defines_command, hmdes_st::defines_environ, hmdes_st::defines_internal, H_punt(), mparse_info_st::hmdes, Mfind_symbol(), Minsert_symbol(), MLINE_SIZE, Mparse_error(), Mstrip(), and NULL.
Referenced by Mparse_next_line().
void Madd_IO_node (Hmdes_IO_Set * IO_set, Hmdes_Reg_File * reg_file)
Definition at line 1005 of file hmdes.c.
References hmdes_io_set_st::head, Malloc_struct(), hmdes_io_node_st::next, NULL, hmdes_io_set_st::size, and hmdes_io_set_st::tail.
Referenced by hmdes_read_IO_sets().
void Madd_res_option (Mparse_Info * pinfo, Hmdes_Res_Node * node, char * name, int subscript)
Definition at line 1436 of file hmdes.c.
References hmdes_resource_st::head, mparse_info_st::hmdes, Malloc_struct(), Mfind_symbol(), Mmatch(), Mparse_error(), hmdes_res_sub_st::next, node, NULL, hmdes_res_sub_st::resource, hmdes_st::resources, and hmdes_res_sub_st::subscript.
Referenced by hmdes_read_restables().
void Malloc_name (char ** ptr, char * name)
Definition at line 622 of file hmdes.c.
References H_punt(), and NULL.
Referenced by create_hmdes(), hmdes_read_class_def(), hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), Hread_header_file(), and Mread_flag().
void Malloc_struct (void ** ptr, int size)
Definition at line 615 of file hmdes.c.
References H_punt(), and NULL.
Referenced by hmdes_add_res_subscript(), hmdes_read_class_def(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), Hread_header_file(), Madd_IO_node(), Madd_res_option(), Mread_flag(), and write_lmdes().
Msymbol_Table* Mcreate_symbol_table (char * name, int size)
Definition at line 662 of file hmdes.c.
References msymbol_table_st::entry_count, H_punt(), msymbol_table_st::hash_mask, msymbol_table_st::hash_table, msymbol_table_st::head, msymbol_table_st::name, NULL, and msymbol_table_st::tail.
Referenced by create_hmdes(), and Hread_header_file().
void Mdie_on_fatal_errors (Mparse_Info * pinfo)
Definition at line 89 of file hmdes.c.
References fatal_parse_errors, and Mparse_error().
Referenced by create_hmdes(), and hmdes_read_define().
void* Mfind_symbol (Msymbol_Table * table, char * name)
Definition at line 712 of file hmdes.c.
References msymbol_table_st::hash_mask, msymbol_table_st::hash_table, Mhash_name(), msymbol_st::name, msymbol_st::next_hash, NULL, and msymbol_st::ptr.
Referenced by associate_opcodes(), associate_reg_files(), find_header_value(), hmdes_read_IO_sets(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_restables(), Hread_header_file(), L_preprocess_line(), Madd_res_option(), Minsert_unique_symbol(), Mprint_op(), Mread_symbol(), and write_lmdes().
void Mfree_flag_list (Hmdes_Flag_List * flag_list)
Definition at line 1984 of file hmdes.c.
References hmdes_flag_list_st::bit_version, hmdes_flag_list_st::head, hmdes_flag_st::name, hmdes_flag_st::next, NULL, and hmdes_flag_list_st::num_flags.
Referenced by hmdes_read_operations().
int Mget_next (Mparse_Info * pinfo, char * buf)
Definition at line 2606 of file hmdes.c.
References mparse_item_st::buf, mparse_info_st::head, L_free(), Mparse_Item_pool, Mparse_next_line(), mparse_item_st::next, NULL, mparse_info_st::queue_size, and mparse_info_st::tail.
Referenced by create_hmdes(), hmdes_read_define(), hmdes_read_section(), hmdes_section_end(), Mread_int(), Mread_match(), Mread_name(), mread_proc_model(), and mscan_set().
int Mhash_name (char * name, int mask)
Definition at line 813 of file hmdes.c.
Referenced by Mfind_symbol(), and Minsert_symbol().
void Minsert_symbol (Msymbol_Table * table, char * name, void * ptr)
Definition at line 752 of file hmdes.c.
References msymbol_table_st::entry_count, H_punt(), msymbol_table_st::hash_mask, msymbol_table_st::hash_table, msymbol_table_st::head, Mhash_name(), msymbol_st::name, msymbol_st::next_hash, msymbol_st::next_linear, NULL, msymbol_st::prev_linear, msymbol_st::ptr, and msymbol_table_st::tail.
Referenced by Hbuild_command_line_defines(), Hbuild_environment_defines(), Hread_header_file(), L_preprocess_line(), and Minsert_unique_symbol().
void Minsert_unique_symbol (Mparse_Info * pinfo, Msymbol_Table * table, char * name, void * ptr)
Definition at line 736 of file hmdes.c.
References Mfind_symbol(), Minsert_symbol(), Mmatch(), Mparse_error(), NULL, and mparse_info_st::section_name.
Referenced by hmdes_read_class_def(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), and hmdes_read_restables().
int Mis_name_next (Mparse_Info * pinfo)
Definition at line 421 of file hmdes.c.
References MITEM_SIZE, Mparse_error(), and Mpeek_ahead().
Referenced by hmdes_read_IO_sets(), and hmdes_read_restables().
int Mis_next (Mparse_Info * pinfo, char * str)
Definition at line 435 of file hmdes.c.
References MITEM_SIZE, Mmatch(), Mparse_error(), and Mpeek_ahead().
Referenced by hmdes_read_class_def(), hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_operations(), hmdes_read_resources(), hmdes_read_restables(), mread_define_var(), Mread_IO_item_symbol(), Mread_latency(), and mread_proc_model().
int Misspace (char ch)
Definition at line 2994 of file hmdes.c.
Referenced by Hget_next_line(), Mparse_next_line(), and Mstrip().
int Mmatch (char * s1, char * s2)
Definition at line 3108 of file hmdes.c.
Referenced by create_hmdes(), hmdes_read_register_files(), hmdes_read_section(), hmdes_section_end(), Madd_res_option(), Minsert_unique_symbol(), Mis_next(), Mread_match(), Mread_name(), mread_proc_model(), Mread_symbol(), and mscan_set().
int Mmatch_flag_lists (Hmdes_Flag_List * list1, Hmdes_Flag_List * list2)
Definition at line 2005 of file hmdes.c.
References hmdes_flag_list_st::head, hmdes_flag_st::name, hmdes_flag_st::next, NULL, and hmdes_flag_list_st::num_flags.
Referenced by hmdes_read_operations().
void Mparse_error (Mparse_Info * pinfo, char * fmt, ...)
Definition at line 3093 of file hmdes.c.
References mparse_info_st::file_name, mparse_info_st::line, and mparse_info_st::section_name.
Referenced by create_hmdes(), hmdes_add_res_subscript(), hmdes_read_define(), hmdes_read_IO_sets(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), hmdes_read_section(), hmdes_section_end(), L_preprocess_line(), Madd_res_option(), Mdie_on_fatal_errors(), Minsert_unique_symbol(), Mis_name_next(), Mis_next(), Mparse_next_line(), mread_define_var(), Mread_flag(), Mread_int(), Mread_latency(), Mread_match(), Mread_name(), mread_proc_model(), Mread_symbol(), and mscan_set().
void Mparse_fatal (Mparse_Info * pinfo, char * fmt, ...)
Definition at line 3077 of file hmdes.c.
References fatal_parse_errors, mparse_info_st::file_name, mparse_info_st::line, and mparse_info_st::section_name.
Referenced by find_header_value(), hmdes_read_define(), hmdes_read_operations(), hmdes_read_resources(), Mread_flag(), and valid_flag_value().
void Mparse_warn (Mparse_Info * pinfo, char * fmt, ...)
Definition at line 3059 of file hmdes.c.
References mparse_info_st::file_name, mparse_info_st::line, and mparse_info_st::section_name.
Referenced by hmdes_read_define().
int Mpeek_ahead (Mparse_Info * pinfo, int dist, char * buf)
Definition at line 2567 of file hmdes.c.
References mparse_item_st::buf, H_punt(), mparse_info_st::head, Mparse_next_line(), mparse_item_st::next, and mparse_info_st::queue_size.
Referenced by hmdes_read_define(), hmdes_section_end(), Mis_name_next(), and Mis_next().
void Mprint_op (FILE * out, Hmdes * hmdes, char * name)
Definition at line 2334 of file hmdes.c.
References hmdes_operation_node_st::asm_name, hmdes_operation_node_st::class, hmdes_latency_st::dest, hmdes_io_item_st::dest, hmdes_res_node_st::end_usage, hmdes_latency_st::exception, hmdes_st::file_name, H_punt(), hmdes_res_list_st::head, hmdes_res_node_st::head, hmdes_operation_class_st::head, hmdes_operation_st::head, hmdes_flag_list_st::head, hmdes_operation_st::id, hmdes_class_node_st::io_item, hmdes_class_node_st::latency, hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, hmdes_st::max_pred_operands, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, hmdes_operation_node_st::mdes_flags, Mfind_symbol(), hmdes_latency_st::name, hmdes_resource_st::name, hmdes_res_list_st::name, hmdes_io_set_st::name, hmdes_io_item_st::name, hmdes_operation_class_st::name, hmdes_flag_st::name, hmdes_operation_st::name, hmdes_res_node_st::next, hmdes_res_option_st::next, hmdes_class_node_st::next, hmdes_operation_node_st::next, hmdes_flag_st::next, NULL, hmdes_flag_list_st::num_flags, hmdes_operation_st::op_flags, hmdes_st::operations, hmdes_latency_st::pred, hmdes_io_item_st::pred, hmdes_class_node_st::res_list, hmdes_res_option_st::resource, hmdes_operation_st::size, hmdes_res_list_st::slot_options, hmdes_latency_st::src, hmdes_io_item_st::src, hmdes_res_node_st::start_usage, hmdes_res_sub_st::subscript, hmdes_res_option_st::subscript, hmdes_latency_st::sync_dest, and hmdes_latency_st::sync_src.
void Mprint_symbol_table (FILE * out, Msymbol_Table * table)
Definition at line 794 of file hmdes.c.
References msymbol_table_st::entry_count, msymbol_table_st::head, msymbol_st::name, msymbol_table_st::name, msymbol_st::next_linear, and NULL.
int mread_define_var (Mparse_Info * pinfo, char * name, int * ptr)
void Mread_flag (Mparse_Info * pinfo, Hmdes_Flag_List * flag_list, char * flag_prefix, char * desc)
Definition at line 2083 of file hmdes.c.
References hmdes_flag_list_st::bit_version, find_header_value(), hmdes_flag_list_st::head, Malloc_name(), Malloc_struct(), MITEM_SIZE, Mparse_error(), Mparse_fatal(), Mread_name(), hmdes_flag_st::name, hmdes_flag_st::next, NULL, hmdes_flag_list_st::num_flags, valid_flag_value(), and hmdes_flag_st::value.
Referenced by hmdes_read_operations().
int Mread_int (Mparse_Info * pinfo, int * ptr)
void Mread_IO_item_symbol (Mparse_Info * pinfo, Msymbol_Table * table, void ** ptr, char * terminator)
Definition at line 491 of file hmdes.c.
References Mis_next(), Mread_match(), and Mread_symbol().
Referenced by hmdes_read_IO_items().
void Mread_latency (Mparse_Info * pinfo, int * ptr)
Definition at line 1803 of file hmdes.c.
References Mis_next(), Mparse_error(), Mread_int(), and Mread_match().
Referenced by hmdes_read_latencies().
void Mread_match (Mparse_Info * pinfo, char * str)
Definition at line 508 of file hmdes.c.
References Mget_next(), MITEM_SIZE, Mmatch(), and Mparse_error().
Referenced by hmdes_read_class_def(), hmdes_read_define(), hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), mread_define_var(), Mread_IO_item_symbol(), Mread_latency(), and mread_proc_model().
void Mread_name (Mparse_Info * pinfo, char * name, char * desc)
Definition at line 449 of file hmdes.c.
References Mget_next(), Mmatch(), and Mparse_error().
Referenced by hmdes_read_IO_items(), hmdes_read_IO_sets(), hmdes_read_latencies(), hmdes_read_operation_class(), hmdes_read_operations(), hmdes_read_register_files(), hmdes_read_resources(), hmdes_read_restables(), Mread_flag(), and Mread_symbol().
int mread_proc_model (Mparse_Info * pinfo, char * name, int * ptr)
void Mread_symbol (Mparse_Info * pinfo, Msymbol_Table * table, void ** ptr, char * desc)
Definition at line 464 of file hmdes.c.
References Mfind_symbol(), MITEM_SIZE, Mmatch(), Mparse_error(), Mread_name(), and NULL.
Referenced by hmdes_read_class_def(), hmdes_read_IO_sets(), hmdes_read_operations(), and Mread_IO_item_symbol().
int mscan_set (Mparse_Info * pinfo, char * name)
Definition at line 521 of file hmdes.c.
References Mget_next(), MITEM_SIZE, Mmatch(), and Mparse_error().
char* Mstrip (char * buf)
Definition at line 3007 of file hmdes.c.
References Misspace().
Referenced by L_preprocess_line().
void print_mask (FILE * out, int * mask, int size)
Definition at line 3367 of file hmdes.c.
Referenced by write_lmdes(), and write_res_node().
void set_mask_bit (int * mask, unsigned int bit)
Definition at line 3349 of file hmdes.c.
References H_punt(), and MAX_MASK_SIZE.
Referenced by write_lmdes(), and write_res_node().
int valid_flag_value (Mparse_Info * pinfo, Hmdes_Flag * flag)
Definition at line 2034 of file hmdes.c.
References H_punt(), Mparse_fatal(), hmdes_flag_st::name, and hmdes_flag_st::value.
Referenced by Mread_flag().
void write_lmdes (Hmdes * hmdes, FILE * out)
Definition at line 3413 of file hmdes.c.
References hmdes_operation_node_st::asm_name, hmdes_operation_node_st::class, clear_mask(), hmdes_latency_st::dest, hmdes_io_item_st::dest, hmdes_res_node_st::end_usage, msymbol_table_st::entry_count, hmdes_latency_st::exception, hmdes_io_set_st::external_id, H_punt(), hmdes_operation_class_st::head, hmdes_operation_st::head, hmdes_res_node_st::head, hmdes_res_list_st::head, hmdes_resource_st::head, hmdes_io_set_st::head, msymbol_table_st::head, hmdes_operation_st::id, hmdes_latency_st::id, hmdes_res_list_st::id, hmdes_res_sub_st::id, hmdes_io_item_st::id, hmdes_io_set_st::id, hmdes_reg_file_st::id, hmdes_st::IO_items, hmdes_st::IO_sets, hmdes_st::latencies, Malloc_struct(), hmdes_st::max_dest_operands, hmdes_st::max_dest_syncs, MAX_MASK_SIZE, hmdes_st::max_pred_operands, hmdes_st::max_slot, hmdes_st::max_src_operands, hmdes_st::max_src_syncs, Mfind_symbol(), MITEM_SIZE, hmdes_operation_st::name, hmdes_latency_st::name, hmdes_res_list_st::name, hmdes_resource_st::name, hmdes_io_item_st::name, hmdes_io_set_st::name, hmdes_class_node_st::next, hmdes_operation_node_st::next, hmdes_res_option_st::next, hmdes_res_node_st::next, hmdes_res_sub_st::next, hmdes_io_node_st::next, msymbol_st::next_linear, NULL, hmdes_st::null_set, hmdes_res_node_st::num_options, hmdes_st::num_resources, hmdes_resource_st::num_subscripts, hmdes_st::operations, hmdes_latency_st::pred, hmdes_io_item_st::pred, print_mask(), hmdes_st::processor_model, msymbol_st::ptr, hmdes_io_node_st::reg_file, hmdes_st::reg_file, hmdes_st::res_lists, hmdes_st::resources, set_mask_bit(), hmdes_res_list_st::size, hmdes_res_list_st::slot_options, hmdes_latency_st::src, hmdes_io_item_st::src, hmdes_res_node_st::start_usage, hmdes_res_option_st::subscript, hmdes_res_sub_st::subscript, hmdes_latency_st::sync_dest, hmdes_latency_st::sync_src, and write_res_node().
void write_res_node (FILE * out, int mask_size, Hmdes_Res_Node * res_node)
Definition at line 3382 of file hmdes.c.
References clear_mask(), hmdes_res_node_st::end_usage, hmdes_res_node_st::flags, H_punt(), hmdes_res_node_st::head, hmdes_res_sub_st::id, MAX_MASK_SIZE, hmdes_res_option_st::next, NULL, hmdes_res_node_st::num_options, print_mask(), set_mask_bit(), hmdes_res_node_st::start_usage, and hmdes_res_option_st::subscript.
Referenced by write_lmdes().
Variable Documentation
int verbose
Definition at line 67 of file hmdes.c.