l_gen_pipe.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include `l_mve.h`
#include `l_pipe_sync.h`
#include <Lcode/r_regalloc.h>
Defines
#define UNKNOWN_WEIGHT 0
#define FALL_THRU_EPI 0
#define TARGET_EPI 1
Functions
void Lpipe_rem_loop_gen (L_Func *fn, L_Oper *loop_incr, int ii, int unroll, int stage_count)
static void Lpipe_gen_epi (L_Func *fn, L_Cb *header_cb, L_Oper *exit_branch, L_Cb *fall_thru_cb, int epi_type, int ii, int unroll, int stage_count)
L_Oper * Lpipe_find_exit_branch_copy (L_Oper *exit_branch, L_Oper *first_oper, L_Oper *last_oper)
static void Lpipe_gen_partial_epi (L_Func *fn, L_Cb *header_cb, L_Oper *exit_branch, L_Cb *fall_thru_cb, int ii, int unroll, int stage_count)
void M_starcore_negate_compare (L_Oper *)
void Lpipe_multi_epi_gen (L_Func *fn, int stage_count, L_Oper *loop_back_br, int ii, int unroll)
static void Lpipe_remove_comp_code_block (L_Cb *ssa_cb)
static void Lpipe_remove_epilogue (L_Func *fn, L_Oper *exit, L_Cb *pipe_cb, L_Cb *epilogue_cb, L_Cb *fall_thru_cb, int epi_type)
void Lpipe_remove_empty_epilogues (L_Func *fn, L_Cb *header_cb)
L_Oper * Lpipe_gen_epilogue_counter (L_Func *fn, L_Cb *cb, int i, int top)
L_Oper * Lpipe_gen_loop_counter (L_Func *fn, L_Cb *cb, int i, int top)
static void Lpipe_change_branch_dir (L_Oper *branch, L_Cb *target)
static void Lpipe_gen_partial_epi_rot (L_Func *fn, L_Cb *header_cb, L_Oper *exit_branch, L_Cb *fall_thru_cb, int ii, int stage_count)
static void Lpipe_gen_epi_rot (SM_Cb *sm_cb, L_Oper *exit_branch, L_Cb *fall_thru_cb, int epi_type)
void Lpipe_multi_epi_gen_rot (SM_Cb *sm_cb, L_Oper *loop_back_br)
void Lpipe_kernel_gen_rot (SM_Cb *sm_cb, L_Oper *loop_back_br)
Define Documentation
#define FALL_THRU_EPI 0
Definition at line 67 of file l_gen_pipe.c.
Referenced by Lpipe_gen_epi(), Lpipe_gen_epi_rot(), Lpipe_kernel_gen_rot(), Lpipe_multi_epi_gen(), and Lpipe_remove_empty_epilogues().
#define TARGET_EPI 1
Definition at line 68 of file l_gen_pipe.c.
Referenced by Lpipe_gen_epi(), Lpipe_gen_epi_rot(), Lpipe_kernel_gen_rot(), Lpipe_multi_epi_gen(), Lpipe_remove_empty_epilogues(), and Lpipe_remove_epilogue().
#define UNKNOWN_WEIGHT 0
Definition at line 65 of file l_gen_pipe.c.
Referenced by Lpipe_gen_epi(), Lpipe_gen_partial_epi(), Lpipe_gen_partial_epi_rot(), Lpipe_multi_epi_gen(), and Lpipe_rem_loop().
Function Documentation
static void Lpipe_change_branch_dir (L_Oper * branch, L_Cb * target) [static]
Definition at line 1384 of file l_gen_pipe.c.
Referenced by Lpipe_gen_epi_rot(), and Lpipe_gen_partial_epi_rot().
L_Oper* Lpipe_find_exit_branch_copy (L_Oper * exit_branch, L_Oper * first_oper, L_Oper * last_oper)
Definition at line 544 of file l_gen_pipe.c.
References _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, Lpipe_ignore_kernel_inst, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_gen_partial_epi(), and Lpipe_gen_partial_epi_rot().
static void Lpipe_gen_epi (L_Func * fn, L_Cb * header_cb, L_Oper * exit_branch, L_Cb * fall_thru_cb, int epi_type, int ii, int unroll, int stage_count) [static]
Definition at line 347 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, exit_cb, _Softpipe_Op_Info::exit_weight, FALL_THRU_EPI, _Softpipe_Op_Info::home_block, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, Lpipe_copy_op_info(), Lpipe_ignore_kernel_inst, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, TARGET_EPI, UNKNOWN_WEIGHT, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_multi_epi_gen().
static void Lpipe_gen_epi_rot (SM_Cb * sm_cb, L_Oper * exit_branch, L_Cb * fall_thru_cb, int epi_type) [static]
Definition at line 1598 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, exit_cb, _Softpipe_Op_Info::exit_weight, FALL_THRU_EPI, header_cb, SM_Cb::II, _Softpipe_Op_Info::issue_time, L_annotate_oper(), SM_Cb::lcode_cb, SM_Cb::lcode_fn, _Softpipe_Op_Info::loop_back_br, Lpipe_change_branch_dir(), Lpipe_copy_op_info(), Lpipe_ignore_kernel_inst, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, SM_Cb::stages, and TARGET_EPI.
Referenced by Lpipe_kernel_gen_rot().
L_Oper* Lpipe_gen_epilogue_counter (L_Func * fn, L_Cb * cb, int i, int top)
Definition at line 1323 of file l_gen_pipe.c.
References L_annotate_oper(), Lpipe_gen_mov_consuming_operands(), M_native_int_register_ctype(), and M_return_epilogue_cntr_register().
Referenced by Lpipe_kernel_gen_rot().
L_Oper* Lpipe_gen_loop_counter (L_Func * fn, L_Cb * cb, int i, int top)
Definition at line 1353 of file l_gen_pipe.c.
References L_annotate_oper(), Lpipe_gen_mov_consuming_operands(), M_native_int_register_ctype(), and M_return_loop_cntr_register().
static void Lpipe_gen_partial_epi (L_Func * fn, L_Cb * header_cb, L_Oper * exit_branch, L_Cb * fall_thru_cb, int ii, int unroll, int stage_count) [static]
Definition at line 581 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, exit_cb, _Softpipe_Op_Info::home_block, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, Lpipe_copy_op_info(), Lpipe_find_exit_branch_copy(), Lpipe_ignore_kernel_inst, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, UNKNOWN_WEIGHT, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_multi_epi_gen().
static void Lpipe_gen_partial_epi_rot (L_Func * fn, L_Cb * header_cb, L_Oper * exit_branch, L_Cb * fall_thru_cb, int ii, int stage_count) [static]
Definition at line 1396 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, exit_cb, _Softpipe_Op_Info::home_block, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::loop_back_br, Lpipe_change_branch_dir(), Lpipe_copy_op_info(), Lpipe_find_exit_branch_copy(), Lpipe_ignore_kernel_inst, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and UNKNOWN_WEIGHT.
void Lpipe_kernel_gen_rot (SM_Cb * sm_cb, L_Oper * loop_back_br)
Definition at line 2061 of file l_gen_pipe.c.
References FALL_THRU_EPI, header_cb, L_annotate_oper(), SM_Cb::lcode_fn, Lpipe_gen_epi_rot(), Lpipe_gen_epilogue_counter(), Lpipe_gen_uncond_pred_define(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, R_get_rot_regs(), SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, SM_Cb::stages, and TARGET_EPI.
Referenced by Lpipe_pipeline_loop().
void Lpipe_multi_epi_gen (L_Func * fn, int stage_count, L_Oper * loop_back_br, int ii, int unroll)
Definition at line 759 of file l_gen_pipe.c.
References FALL_THRU_EPI, header_cb, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, _Softpipe_Op_Info::loop_back_br, Lpipe_adjust_syncs_for_prologue(), Lpipe_copy_op_info(), Lpipe_gen_epi(), Lpipe_gen_partial_epi(), Lpipe_ignore_kernel_inst, M_arch, M_STARCORE, M_starcore_negate_compare(), preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, TARGET_EPI, UNKNOWN_WEIGHT, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_pipeline_loop().
void Lpipe_multi_epi_gen_rot (SM_Cb * sm_cb, L_Oper * loop_back_br)
Definition at line 1774 of file l_gen_pipe.c.
References SM_Cb::II, _Softpipe_Op_Info::issue_time, SM_Cb::lcode_cb, SM_Cb::lcode_fn, Lpipe_copy_op_info(), Lpipe_get_pro_reg(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_rem_loop_gen (L_Func * fn, L_Oper * loop_incr, int ii, int unroll, int stage_count)
Definition at line 108 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, header_cb, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, Lpipe_adjust_syncs_for_epilogue(), Lpipe_adjust_syncs_for_prologue(), Lpipe_copy_op_info(), Lpipe_find_loop_back_br(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, remainder_cb, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_remove_comp_code_block (L_Cb * ssa_cb) [static]
Definition at line 1147 of file l_gen_pipe.c.
References exit_cb.
Referenced by Lpipe_remove_empty_epilogues().
void Lpipe_remove_empty_epilogues (L_Func * fn, L_Cb * header_cb)
Definition at line 1206 of file l_gen_pipe.c.
References FALL_THRU_EPI, Lpipe_remove_comp_code_block(), Lpipe_remove_epilogue(), prologue_cb, and TARGET_EPI.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_remove_epilogue (L_Func * fn, L_Oper * exit, L_Cb * pipe_cb, L_Cb * epilogue_cb, L_Cb * fall_thru_cb, int epi_type) [static]
Definition at line 1180 of file l_gen_pipe.c.
References TARGET_EPI.
Referenced by Lpipe_remove_empty_epilogues().
void M_starcore_negate_compare (L_Oper *)