l_gen_pipe.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
Functions
void Lpipe_rem_loop_gen (L_Func *, L_Oper *, int, int, int)
void Lpipe_multi_epi_gen (L_Func *, int, L_Oper *, int, int)
void Lpipe_multi_epi_gen_rot (SM_Cb *, L_Oper *)
void Lpipe_kernel_gen_rot (SM_Cb *, L_Oper *)
void Lpipe_remove_empty_epilogues (L_Func *, L_Cb *)
Function Documentation
void Lpipe_kernel_gen_rot (SM_Cb *, L_Oper *)
Definition at line 2061 of file l_gen_pipe.c.
References FALL_THRU_EPI, header_cb, L_annotate_oper(), SM_Cb::lcode_fn, Lpipe_gen_epi_rot(), Lpipe_gen_epilogue_counter(), Lpipe_gen_uncond_pred_define(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, R_get_rot_regs(), SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, SM_Cb::stages, and TARGET_EPI.
Referenced by Lpipe_pipeline_loop().
void Lpipe_multi_epi_gen (L_Func *, int, L_Oper *, int, int)
Definition at line 759 of file l_gen_pipe.c.
References FALL_THRU_EPI, header_cb, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, _Softpipe_Op_Info::loop_back_br, Lpipe_adjust_syncs_for_prologue(), Lpipe_copy_op_info(), Lpipe_gen_epi(), Lpipe_gen_partial_epi(), Lpipe_ignore_kernel_inst, M_arch, M_STARCORE, M_starcore_negate_compare(), preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, TARGET_EPI, UNKNOWN_WEIGHT, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_pipeline_loop().
void Lpipe_multi_epi_gen_rot (SM_Cb *, L_Oper *)
Definition at line 1774 of file l_gen_pipe.c.
References SM_Cb::II, _Softpipe_Op_Info::issue_time, SM_Cb::lcode_cb, SM_Cb::lcode_fn, Lpipe_copy_op_info(), Lpipe_get_pro_reg(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_rem_loop_gen (L_Func *, L_Oper *, int, int, int)
Definition at line 108 of file l_gen_pipe.c.
References _Softpipe_Op_Info::epilogue_stage, header_cb, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, Lpipe_adjust_syncs_for_epilogue(), Lpipe_adjust_syncs_for_prologue(), Lpipe_copy_op_info(), Lpipe_find_loop_back_br(), Lpipe_ignore_kernel_inst, preheader_cb, prologue_cb, _Softpipe_Op_Info::prologue_stage, remainder_cb, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_remove_empty_epilogues (L_Func *, L_Cb *)
Definition at line 1206 of file l_gen_pipe.c.
References FALL_THRU_EPI, Lpipe_remove_comp_code_block(), Lpipe_remove_epilogue(), prologue_cb, and TARGET_EPI.
Referenced by Lpipe_pipeline_loop().