l_loop_prep.h File Reference
#include <config.h>
Functions
void Lpipe_loop_prep_init (Parm_Macro_List *)
void Lpipe_loop_prep_end ()
void Lpipe_softpipe_loop_prep (L_Func *)
Function Documentation
void Lpipe_loop_prep_end ()
Definition at line 115 of file l_loop_prep.c.
References Lpipe_check_loops_in_phase1, Lpipe_print_statistics, and prep_statfile.
void Lpipe_loop_prep_init (Parm_Macro_List *)
Definition at line 92 of file l_loop_prep.c.
References L_read_parm_lpipe(), Lpipe_check_loops_in_phase1, Lpipe_print_statistics, and prep_statfile.
void Lpipe_softpipe_loop_prep (L_Func *)
Definition at line 131 of file l_loop_prep.c.
References header_cb, Lpipe_can_create_fallthru_cb(), Lpipe_check_loops_in_phase1, Lpipe_debug, Lpipe_do_induction_reversal, Lpipe_loop_induction_reversal(), Lpipe_print_statistics, Lpipe_rem_loop(), Lpipe_schema, prep_statfile, and REM_LOOP.