l_loop_prep.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include `l_loop_prep.h`
Defines
#define UNKNOWN_WEIGHT 0
#define DUMMY_VAL 95
Functions
static int Lpipe_is_post_increment (L_Oper *ind_op, L_Oper *loop_back_br)
static void Lpipe_fix_max (L_Func *fn, L_Operand *ind_incr, L_Operand *ind_var, L_Oper *loop_back_br, L_Cb *preheader)
static L_Oper * Lpipe_loop_induction_reversal (L_Func *fn, L_Cb *header_cb, L_Cb *preheader_cb, L_Oper *loop_back_br)
static void Lpipe_rem_loop (L_Func *fn, L_Cb *header_cb, L_Cb *preheader_cb, L_Oper *loop_back_br, L_Oper *loop_incr_op)
void Lpipe_loop_prep_init (Parm_Macro_List *command_line_macro_list)
void Lpipe_loop_prep_end ()
void Lpipe_softpipe_loop_prep (L_Func *fn)
Variables
static FILE * prep_statfile
Define Documentation
#define DUMMY_VAL 95
Definition at line 298 of file l_loop_prep.c.
Referenced by Lpipe_rem_loop().
#define UNKNOWN_WEIGHT 0
Definition at line 297 of file l_loop_prep.c.
Function Documentation
static void Lpipe_fix_max (L_Func * fn, L_Operand * ind_incr, L_Operand * ind_var, L_Oper * loop_back_br, L_Cb * preheader) [static]
Definition at line 343 of file l_loop_prep.c.
Referenced by Lpipe_loop_induction_reversal().
static int Lpipe_is_post_increment (L_Oper * ind_op, L_Oper * loop_back_br) [static]
Definition at line 310 of file l_loop_prep.c.
Referenced by Lpipe_loop_induction_reversal().
static L_Oper * Lpipe_loop_induction_reversal (L_Func * fn, L_Cb * header_cb, L_Cb * preheader_cb, L_Oper * loop_back_br) [static]
Definition at line 405 of file l_loop_prep.c.
References Lpipe_fix_max(), and Lpipe_is_post_increment().
Referenced by Lpipe_softpipe_loop_prep().
void Lpipe_loop_prep_end ()
Definition at line 115 of file l_loop_prep.c.
References Lpipe_check_loops_in_phase1, Lpipe_print_statistics, and prep_statfile.
void Lpipe_loop_prep_init (Parm_Macro_List * command_line_macro_list)
Definition at line 92 of file l_loop_prep.c.
References L_read_parm_lpipe(), Lpipe_check_loops_in_phase1, Lpipe_print_statistics, and prep_statfile.
static void Lpipe_rem_loop (L_Func * fn, L_Cb * header_cb, L_Cb * preheader_cb, L_Oper * loop_back_br, L_Oper * loop_incr_op) [static]
Definition at line 500 of file l_loop_prep.c.
References DUMMY_VAL, prologue_cb, remainder_cb, and UNKNOWN_WEIGHT.
Referenced by Lpipe_softpipe_loop_prep().
void Lpipe_softpipe_loop_prep (L_Func * fn)
Definition at line 131 of file l_loop_prep.c.
References header_cb, Lpipe_can_create_fallthru_cb(), Lpipe_check_loops_in_phase1, Lpipe_debug, Lpipe_do_induction_reversal, Lpipe_loop_induction_reversal(), Lpipe_print_statistics, Lpipe_rem_loop(), Lpipe_schema, prep_statfile, and REM_LOOP.
Variable Documentation
FILE* prep_statfile [static]
Definition at line 82 of file l_loop_prep.c.
Referenced by Lpipe_loop_prep_end(), Lpipe_loop_prep_init(), and Lpipe_softpipe_loop_prep().