l_mve.h File Reference
#include <config.h>
#include <Lcode/sm.h>
Functions
void Lpipe_free_mve_info ()
int Lpipe_analyze_lr (SM_Cb *, int)
int Lpipe_rreg_transform (SM_Cb *)
void Lpipe_fix_live_in_rot (SM_Cb *)
void Lpipe_fix_live_out_rot (SM_Cb *, SM_Oper *)
void Lpipe_mve_transform (SM_Cb *, int)
void Lpipe_fix_live_in (SM_Cb *)
void Lpipe_fix_live_out (SM_Cb *, int)
int Lpipe_find_name (SM_Cb *, Lpipe_LRInfo *, Lpipe_MVEInfo *)
int Lpipe_get_pro_reg (SM_Cb *sm_cb, Lpipe_LRInfo *lr_info, Lpipe_MVEInfo *mve_info, int stg_ofst)
Variables
L_Alloc_Pool * Lpipe_src_mve_pool
L_Alloc_Pool * Lpipe_pred_mve_pool
L_Alloc_Pool * Lpipe_dest_mve_pool
L_Alloc_Pool * Lpipe_dest_lr_pool
L_Alloc_Pool * Lpipe_MVEInfo_pool
Function Documentation
int Lpipe_analyze_lr (SM_Cb *, int)
Definition at line 1436 of file l_mve.c.
References SM_Cb::II, SM_Cb::lcode_cb, Lpipe_associate_mve_regs(), Lpipe_associate_rot_regs(), Lpipe_construct_lr(), Lpipe_debug, Lpipe_delete_all_live_range_info(), Lpipe_delete_all_mve_info(), Lpipe_ignore_kernel_inst, Lpipe_mve_lr_list, Lpipe_print_live_ranges(), Lpipe_print_mve_info(), Lpipe_schema, MULTI_EPI, and REM_LOOP.
Referenced by Lpipe_pipeline_loop().
int Lpipe_find_name (SM_Cb *, Lpipe_LRInfo *, Lpipe_MVEInfo *)
Definition at line 1495 of file l_mve.c.
References _Lpipe_LRInfo::first_def_time, SM_Cb::II, _Lpipe_MVEInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, and _Lpipe_LRInfo::num_names.
Referenced by Lpipe_fix_live_out_rot(), Lpipe_get_pro_reg(), and Lpipe_rreg_transform().
void Lpipe_fix_live_in (SM_Cb *)
Definition at line 2214 of file l_mve.c.
References SM_Cb::lcode_cb, SM_Cb::lcode_fn, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, prologue_cb, _Lpipe_LRInfo::prologue_mov_inserted, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::src_mve_info, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_fix_live_in_rot (SM_Cb *)
Definition at line 1726 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, SM_Cb::first_serial_op, KERNEL_ONLY, SM_Cb::lcode_cb, SM_Cb::lcode_fn, SM_Oper::lcode_op, _Lpipe_LRInfo::live_in, _Lpipe_MVEInfo::live_range, Lpipe_gen_rot_pro_fixup(), Lpipe_get_pro_reg(), Lpipe_schema, MULTI_EPI_ROT_REG, SM_Oper::next_serial_op, _Lpipe_LRInfo::num_names, prologue_cb, _Lpipe_LRInfo::prologue_mov_inserted, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_fix_live_out (SM_Cb *, int)
Definition at line 2765 of file l_mve.c.
References _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, SM_Cb::lcode_cb, _Softpipe_Op_Info::loop_back_br, Lpipe_fix_live_out_epi(), Lpipe_fix_live_out_stage(), Lpipe_fix_set_out_epi(), Lpipe_fix_set_out_stage(), Lpipe_ignore_kernel_inst, Lpipe_merge_compensation_code(), Lpipe_modulo_decrement(), Lpipe_schema, REM_LOOP, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_pipeline_loop().
void Lpipe_fix_live_out_rot (SM_Cb *, SM_Oper *)
Definition at line 1884 of file l_mve.c.
References _Softpipe_Op_Info::exit_cb, SM_Cb::first_serial_op, _Softpipe_Op_Info::isrc_mve_info, SM_Cb::lcode_cb, SM_Cb::lcode_fn, SM_Oper::lcode_op, _Lpipe_MVEInfo::live_range, Lpipe_find_name(), Lpipe_gen_rot_epi_fixup(), SM_Oper::next_serial_op, _Lpipe_LRInfo::num_names, SM_Reg_Info::operand, _Lpipe_LRInfo::rinfo, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_free_mve_info ()
Definition at line 414 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, header_cb, kernel_copy_first_op, kernel_copy_last_op, Lpipe_delete_all_live_range_info(), Lpipe_delete_all_mve_info(), Lpipe_dest_mve_pool, Lpipe_ignore_kernel_inst, Lpipe_mve_lr_list, Lpipe_pred_mve_pool, Lpipe_schema, Lpipe_src_mve_pool, MULTI_EPI, _Softpipe_Op_Info::pred_mve_info, REM_LOOP, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_pipeline_loop().
int Lpipe_get_pro_reg (SM_Cb * sm_cb, Lpipe_LRInfo * lr_info, Lpipe_MVEInfo * mve_info, int stg_ofst)
Definition at line 2882 of file l_mve.c.
References SM_Cb::lcode_cb, SM_Cb::lcode_fn, Lpipe_find_name(), _Lpipe_LRInfo::names, and _Lpipe_LRInfo::num_names_w_pro.
Referenced by Lpipe_fix_live_in_rot(), and Lpipe_multi_epi_gen_rot().
void Lpipe_mve_transform (SM_Cb *, int)
Definition at line 1963 of file l_mve.c.
References _Lpipe_LRInfo::def_sm_oper, _Softpipe_Op_Info::dest_mve_info, _Lpipe_LRInfo::first_def_time, SM_Cb::II, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, SM_Cb::lcode_cb, SM_Oper::lcode_op, _Lpipe_MVEInfo::lifetime, _Lpipe_MVEInfo::live_range, Lpipe_copy_op_info(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, SOFTPIPE_OP_INFO, _Lpipe_MVEInfo::stage_lifetime_incr, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
int Lpipe_rreg_transform (SM_Cb *)
Definition at line 1540 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, SM_Cb::lcode_cb, _Lpipe_MVEInfo::lifetime, _Lpipe_MVEInfo::live_range, Lpipe_find_name(), _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, _Softpipe_Op_Info::pred_mve_info, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_pipeline_loop().
Variable Documentation
L_Alloc_Pool* Lpipe_dest_lr_pool
L_Alloc_Pool* Lpipe_dest_mve_pool
Definition at line 81 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().
L_Alloc_Pool* Lpipe_MVEInfo_pool
Definition at line 87 of file l_mve.c.
Referenced by Lpipe_delete_all_mve_info(), Lpipe_init(), and Lpipe_new_opd_mve_info().
L_Alloc_Pool* Lpipe_pred_mve_pool
Definition at line 79 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().
L_Alloc_Pool* Lpipe_src_mve_pool
Definition at line 77 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().