l_mve.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include `l_mve.h`
#include <assert.h>
Defines
#define LPIPE_LR_TYPE (SM_REGISTER_TYPE|SM_MACRO_TYPE)
Functions
static Lpipe_LRInfo * Lpipe_create_live_range_info (SM_Reg_Info *rinfo)
static List Lpipe_delete_all_live_range_info (List lr_list)
static Lpipe_LRInfo * Lpipe_find_live_range (List lr_list, SM_Reg_Info *rinfo)
static void Lpipe_update_lr_last_acc (Lpipe_LRInfo *lr_info, int issue_time, int issue_slot, int ii)
static Lpipe_MVEInfo * Lpipe_new_opd_mve_info (Lpipe_LRInfo *lr)
static void Lpipe_print_live_ranges (List lr_list, int ii)
static int Lpipe_modulo_decrement (int count, int unrolled)
static void Lpipe_print_mve_info (SM_Cb *sm_cb)
static void Lpipe_delete_all_mve_info (L_Oper *oper)
void Lpipe_free_mve_info ()
static int Lpipe_get_best_lr (List *op_array, Lpipe_LRInfo *prev_lr_info, Lpipe_LRInfo **lr_info, int ii)
static int Lpipe_associate_rot_regs (List lr_list, SM_Cb *sm_cb, int count_only)
static int Lpipe_associate_mve_regs (List lr_list, SM_Cb *sm_cb)
static List Lpipe_construct_lr (SM_Cb *kernel_cb)
int Lpipe_analyze_lr (SM_Cb *kernel_cb, int count_only)
int Lpipe_find_name (SM_Cb *sm_cb, Lpipe_LRInfo *lr_info, Lpipe_MVEInfo *mve_info)
static int Lpipe_mov_opc (L_Operand *opd)
int Lpipe_rreg_transform (SM_Cb *sm_cb)
static void Lpipe_gen_rot_pro_fixup (L_Func *fn, L_Cb *cb, Lpipe_LRInfo *lr_info, int reg)
void Lpipe_fix_live_in_rot (SM_Cb *sm_cb)
static void Lpipe_gen_rot_epi_fixup (L_Func *fn, L_Cb *cb, Lpipe_LRInfo *lr_info, int name_index)
void Lpipe_fix_live_out_rot (SM_Cb *sm_cb, SM_Oper *sm_loop_back_br)
void Lpipe_mve_transform (SM_Cb *sm_cb, int unroll)
void Lpipe_fix_live_in (SM_Cb *sm_cb)
static void Lpipe_merge_compensation_code (L_Cb *epilogue_cb)
static void Lpipe_fix_live_out_epi (L_Cb *kernel_cb, L_Oper *exit_branch)
static Set Lpipe_fix_set_out_epi (Set to_fix, L_Cb *kernel_cb, L_Oper *exit_branch)
static void Lpipe_fix_live_out_stage (L_Cb *kernel_cb, L_Oper *exit_branch, L_Oper *first_op, L_Oper *last_op, int stage)
static Set Lpipe_fix_set_out_stage (Set to_fix, L_Cb *kernel_cb, L_Oper *exit_branch, L_Oper *first_op, L_Oper *last_op, int stage)
void Lpipe_fix_live_out (SM_Cb *sm_cb, int unroll)
int Lpipe_get_pro_reg (SM_Cb *sm_cb, Lpipe_LRInfo *lr_info, Lpipe_MVEInfo *mve_info, int stg_ofst)
Variables
L_Alloc_Pool * Lpipe_src_mve_pool = NULL
L_Alloc_Pool * Lpipe_pred_mve_pool = NULL
L_Alloc_Pool * Lpipe_dest_mve_pool = NULL
static L_Alloc_Pool * Lpipe_LRInfo_pool = NULL
L_Alloc_Pool * Lpipe_MVEInfo_pool = NULL
static List Lpipe_mve_lr_list = NULL
Define Documentation
#define LPIPE_LR_TYPE (SM_REGISTER_TYPE|SM_MACRO_TYPE)
Definition at line 97 of file l_mve.c.
Referenced by Lpipe_construct_lr().
Function Documentation
int Lpipe_analyze_lr (SM_Cb * kernel_cb, int count_only)
Definition at line 1436 of file l_mve.c.
References SM_Cb::II, SM_Cb::lcode_cb, Lpipe_associate_mve_regs(), Lpipe_associate_rot_regs(), Lpipe_construct_lr(), Lpipe_debug, Lpipe_delete_all_live_range_info(), Lpipe_delete_all_mve_info(), Lpipe_ignore_kernel_inst, Lpipe_mve_lr_list, Lpipe_print_live_ranges(), Lpipe_print_mve_info(), Lpipe_schema, MULTI_EPI, and REM_LOOP.
Referenced by Lpipe_pipeline_loop().
static int Lpipe_associate_mve_regs (List lr_list, SM_Cb * sm_cb) [static]
Definition at line 858 of file l_mve.c.
References SM_Reg_Info::id, SM_Cb::II, SM_Cb::lcode_fn, _Lpipe_LRInfo::lifetime, Lpipe_print_mve_summary, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, SM_Reg_Info::operand, _Lpipe_LRInfo::rinfo, SM_REGISTER_TYPE, SM_Reg_Info::type, and _Lpipe_LRInfo::use_after_def_slot.
Referenced by Lpipe_analyze_lr().
static int Lpipe_associate_rot_regs (List lr_list, SM_Cb * sm_cb, int count_only) [static]
Definition at line 527 of file l_mve.c.
References _Lpipe_LRInfo::first_def_slot, _Lpipe_LRInfo::first_def_time, SM_Reg_Info::id, SM_Cb::II, KERNEL_ONLY, _Lpipe_LRInfo::last_access_time, SM_Cb::lcode_cb, SM_Cb::lcode_fn, _Lpipe_LRInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, Lpipe_get_best_lr(), Lpipe_print_mve_summary, Lpipe_schema, M_arch, M_native_int_register_ctype(), M_TAHOE, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, _Lpipe_LRInfo::num_names_w_pro, SM_Reg_Info::operand, R_get_rot_reg_max_alloc(), R_get_rot_regs(), _Lpipe_LRInfo::rinfo, SM_MACRO_TYPE, SM_Cb::stages, SM_Reg_Info::type, and _Lpipe_LRInfo::use_after_def_slot.
Referenced by Lpipe_analyze_lr().
static List Lpipe_construct_lr (SM_Cb * kernel_cb) [static]
Definition at line 960 of file l_mve.c.
References SM_Oper::dest, _Softpipe_Op_Info::dest_mve_info, SM_Reg_Info::first_def, _Lpipe_LRInfo::first_def_time, SM_Reg_Action::first_dep_in, SM_Reg_Action::first_dep_out, SM_Cb::first_rinfo, SM_Cb::first_serial_op, SM_Reg_Action::flags, SM_Dep::flags, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::II, _Softpipe_Op_Info::isrc_mve_info, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, KERNEL_ONLY, SM_Cb::lcode_cb, SM_Cb::lcode_fn, SM_Oper::lcode_op, _Lpipe_MVEInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, _Lpipe_LRInfo::live_out, _Lpipe_MVEInfo::live_range, _Softpipe_Op_Info::loop_back_br, Lpipe_create_live_range_info(), Lpipe_debug, Lpipe_find_live_range(), LPIPE_LR_TYPE, Lpipe_new_opd_mve_info(), Lpipe_schema, Lpipe_update_lr_last_acc(), MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MULTI_EPI_ROT_REG, SM_Dep::next_dep_in, SM_Dep::next_dep_out, SM_Reg_Info::next_rinfo, SM_Oper::next_serial_op, SM_Dep::omega, SM_Reg_Info::operand, SM_Reg_Action::operand_number, SM_Reg_Action::operand_type, _Softpipe_Op_Info::pred_mve_info, SM_Reg_Action::rinfo, SM_FLOW_DEP, SM_Reg_Action::sm_op, SM_OUTPUT_DEP, SM_PRED_COND_USE, SM_PRED_UNCOND_USE, SM_REG_DEP, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::src_mve_info, _Lpipe_MVEInfo::stage_lifetime_incr, SM_Dep::to_action, and SM_Reg_Info::type.
Referenced by Lpipe_analyze_lr().
static Lpipe_LRInfo* Lpipe_create_live_range_info (SM_Reg_Info * rinfo) [static]
Definition at line 104 of file l_mve.c.
References _Lpipe_LRInfo::def_sm_oper, SM_Reg_Info::ext, SM_Reg_Info::first_def, _Lpipe_LRInfo::first_def_slot, _Lpipe_LRInfo::first_def_time, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, _Lpipe_LRInfo::last_access_slot, _Lpipe_LRInfo::last_access_time, SM_Oper::lcode_op, _Lpipe_LRInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, _Lpipe_LRInfo::live_out, Lpipe_LRInfo_pool, _Lpipe_LRInfo::names, SM_Reg_Action::next_def, _Lpipe_LRInfo::num_names, _Lpipe_LRInfo::num_names_w_pro, _Lpipe_LRInfo::prologue_mov_inserted, _Lpipe_LRInfo::rinfo, SM_Oper::sched_cycle, SM_Cb::sched_cycle_offset, SM_Oper::sched_slot, SM_Oper::sm_cb, SM_Reg_Action::sm_op, SOFTPIPE_OP_INFO, and _Lpipe_LRInfo::use_after_def_slot.
Referenced by Lpipe_construct_lr().
static List Lpipe_delete_all_live_range_info (List lr_list) [static]
Definition at line 185 of file l_mve.c.
References Lpipe_LRInfo_pool, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, and _Lpipe_LRInfo::num_names_w_pro.
Referenced by Lpipe_analyze_lr(), and Lpipe_free_mve_info().
static void Lpipe_delete_all_mve_info (L_Oper * oper) [static]
Definition at line 379 of file l_mve.c.
References Lpipe_MVEInfo_pool, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_analyze_lr(), and Lpipe_free_mve_info().
static Lpipe_LRInfo* Lpipe_find_live_range (List lr_list, SM_Reg_Info * rinfo) [static]
Definition at line 216 of file l_mve.c.
References _Lpipe_LRInfo::rinfo.
Referenced by Lpipe_construct_lr().
int Lpipe_find_name (SM_Cb * sm_cb, Lpipe_LRInfo * lr_info, Lpipe_MVEInfo * mve_info)
Definition at line 1495 of file l_mve.c.
References _Lpipe_LRInfo::first_def_time, SM_Cb::II, _Lpipe_MVEInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, and _Lpipe_LRInfo::num_names.
Referenced by Lpipe_fix_live_out_rot(), Lpipe_get_pro_reg(), and Lpipe_rreg_transform().
void Lpipe_fix_live_in (SM_Cb * sm_cb)
Definition at line 2214 of file l_mve.c.
References SM_Cb::lcode_cb, SM_Cb::lcode_fn, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, prologue_cb, _Lpipe_LRInfo::prologue_mov_inserted, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::src_mve_info, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_fix_live_in_rot (SM_Cb * sm_cb)
Definition at line 1726 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, SM_Cb::first_serial_op, KERNEL_ONLY, SM_Cb::lcode_cb, SM_Cb::lcode_fn, SM_Oper::lcode_op, _Lpipe_LRInfo::live_in, _Lpipe_MVEInfo::live_range, Lpipe_gen_rot_pro_fixup(), Lpipe_get_pro_reg(), Lpipe_schema, MULTI_EPI_ROT_REG, SM_Oper::next_serial_op, _Lpipe_LRInfo::num_names, prologue_cb, _Lpipe_LRInfo::prologue_mov_inserted, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
void Lpipe_fix_live_out (SM_Cb * sm_cb, int unroll)
Definition at line 2765 of file l_mve.c.
References _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, SM_Cb::lcode_cb, _Softpipe_Op_Info::loop_back_br, Lpipe_fix_live_out_epi(), Lpipe_fix_live_out_stage(), Lpipe_fix_set_out_epi(), Lpipe_fix_set_out_stage(), Lpipe_ignore_kernel_inst, Lpipe_merge_compensation_code(), Lpipe_modulo_decrement(), Lpipe_schema, REM_LOOP, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_fix_live_out_epi (L_Cb * kernel_cb, L_Oper * exit_branch) [static]
Definition at line 2367 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::epilogue_stage, _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::home_block, _Lpipe_LRInfo::live_out, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_fix_live_out().
void Lpipe_fix_live_out_rot (SM_Cb * sm_cb, SM_Oper * sm_loop_back_br)
Definition at line 1884 of file l_mve.c.
References _Softpipe_Op_Info::exit_cb, SM_Cb::first_serial_op, _Softpipe_Op_Info::isrc_mve_info, SM_Cb::lcode_cb, SM_Cb::lcode_fn, SM_Oper::lcode_op, _Lpipe_MVEInfo::live_range, Lpipe_find_name(), Lpipe_gen_rot_epi_fixup(), SM_Oper::next_serial_op, _Lpipe_LRInfo::num_names, SM_Reg_Info::operand, _Lpipe_LRInfo::rinfo, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_fix_live_out_stage (L_Cb * kernel_cb, L_Oper * exit_branch, L_Oper * first_op, L_Oper * last_op, int stage) [static]
Definition at line 2562 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::home_block, _Lpipe_LRInfo::live_out, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_fix_live_out().
static Set Lpipe_fix_set_out_epi (Set to_fix, L_Cb * kernel_cb, L_Oper * exit_branch) [static]
Definition at line 2459 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::epilogue_stage, _Softpipe_Op_Info::home_block, _Lpipe_LRInfo::live_out, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_fix_live_out().
static Set Lpipe_fix_set_out_stage (Set to_fix, L_Cb * kernel_cb, L_Oper * exit_branch, L_Oper * first_op, L_Oper * last_op, int stage) [static]
Definition at line 2661 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::home_block, L_annotate_oper(), _Lpipe_LRInfo::live_out, _Lpipe_MVEInfo::live_range, Lpipe_gen_mov_consuming_operands(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_fix_live_out().
void Lpipe_free_mve_info ()
Definition at line 414 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, header_cb, kernel_copy_first_op, kernel_copy_last_op, Lpipe_delete_all_live_range_info(), Lpipe_delete_all_mve_info(), Lpipe_dest_mve_pool, Lpipe_ignore_kernel_inst, Lpipe_mve_lr_list, Lpipe_pred_mve_pool, Lpipe_schema, Lpipe_src_mve_pool, MULTI_EPI, _Softpipe_Op_Info::pred_mve_info, REM_LOOP, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_gen_rot_epi_fixup (L_Func * fn, L_Cb * cb, Lpipe_LRInfo * lr_info, int name_index) [static]
Definition at line 1811 of file l_mve.c.
References L_annotate_oper(), Lpipe_mov_opc(), M_arch, M_TAHOE, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, SM_Reg_Info::operand, and _Lpipe_LRInfo::rinfo.
Referenced by Lpipe_fix_live_out_rot().
static void Lpipe_gen_rot_pro_fixup (L_Func * fn, L_Cb * cb, Lpipe_LRInfo * lr_info, int reg) [static]
Definition at line 1674 of file l_mve.c.
References L_annotate_oper(), Lpipe_mov_opc(), M_arch, M_TAHOE, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, SM_Reg_Info::operand, and _Lpipe_LRInfo::rinfo.
Referenced by Lpipe_fix_live_in_rot().
static int Lpipe_get_best_lr (List * op_array, Lpipe_LRInfo * prev_lr_info, Lpipe_LRInfo ** lr_info, int ii) [static]
Definition at line 474 of file l_mve.c.
References _Lpipe_LRInfo::last_access_slot, _Lpipe_LRInfo::last_access_time, SM_Reg_Info::operand, and _Lpipe_LRInfo::rinfo.
Referenced by Lpipe_associate_rot_regs().
int Lpipe_get_pro_reg (SM_Cb * sm_cb, Lpipe_LRInfo * lr_info, Lpipe_MVEInfo * mve_info, int stg_ofst)
Definition at line 2882 of file l_mve.c.
References SM_Cb::lcode_cb, SM_Cb::lcode_fn, Lpipe_find_name(), _Lpipe_LRInfo::names, and _Lpipe_LRInfo::num_names_w_pro.
Referenced by Lpipe_fix_live_in_rot(), and Lpipe_multi_epi_gen_rot().
static void Lpipe_merge_compensation_code (L_Cb * epilogue_cb) [static]
Definition at line 2341 of file l_mve.c.
Referenced by Lpipe_fix_live_out().
static int Lpipe_modulo_decrement (int count, int unrolled) [static]
Definition at line 314 of file l_mve.c.
Referenced by Lpipe_fix_live_out().
static int Lpipe_mov_opc (L_Operand * opd) [static]
Definition at line 1519 of file l_mve.c.
Referenced by Lpipe_gen_rot_epi_fixup(), and Lpipe_gen_rot_pro_fixup().
void Lpipe_mve_transform (SM_Cb * sm_cb, int unroll)
Definition at line 1963 of file l_mve.c.
References _Lpipe_LRInfo::def_sm_oper, _Softpipe_Op_Info::dest_mve_info, _Lpipe_LRInfo::first_def_time, SM_Cb::II, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, kernel_copy_first_op, kernel_copy_last_op, SM_Cb::lcode_cb, SM_Oper::lcode_op, _Lpipe_MVEInfo::lifetime, _Lpipe_MVEInfo::live_range, Lpipe_copy_op_info(), Lpipe_ignore_kernel_inst, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, SOFTPIPE_OP_INFO, _Lpipe_MVEInfo::stage_lifetime_incr, and SM_Cb::stages.
Referenced by Lpipe_pipeline_loop().
static Lpipe_MVEInfo* Lpipe_new_opd_mve_info (Lpipe_LRInfo * lr) [static]
Definition at line 257 of file l_mve.c.
References _Lpipe_MVEInfo::lifetime, _Lpipe_MVEInfo::live_range, Lpipe_MVEInfo_pool, and _Lpipe_MVEInfo::stage_lifetime_incr.
Referenced by Lpipe_construct_lr().
static void Lpipe_print_live_ranges (List lr_list, int ii) [static]
Definition at line 271 of file l_mve.c.
References _Lpipe_LRInfo::def_sm_oper, _Lpipe_LRInfo::first_def_slot, _Lpipe_LRInfo::first_def_time, SM_Reg_Info::id, _Lpipe_LRInfo::last_access_slot, _Lpipe_LRInfo::last_access_time, SM_Oper::lcode_op, _Lpipe_LRInfo::lifetime, _Lpipe_LRInfo::live_in, _Lpipe_LRInfo::live_in_def_time, _Lpipe_LRInfo::live_out, _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, _Lpipe_LRInfo::rinfo, and _Lpipe_LRInfo::use_after_def_slot.
Referenced by Lpipe_analyze_lr().
static void Lpipe_print_mve_info (SM_Cb * sm_cb) [static]
Definition at line 324 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, SM_Cb::first_serial_op, SM_Oper::lcode_op, _Lpipe_MVEInfo::lifetime, SM_Oper::next_serial_op, _Softpipe_Op_Info::pred_mve_info, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::src_mve_info, and _Lpipe_MVEInfo::stage_lifetime_incr.
Referenced by Lpipe_analyze_lr().
int Lpipe_rreg_transform (SM_Cb * sm_cb)
Definition at line 1540 of file l_mve.c.
References _Softpipe_Op_Info::dest_mve_info, SM_Cb::lcode_cb, _Lpipe_MVEInfo::lifetime, _Lpipe_MVEInfo::live_range, Lpipe_find_name(), _Lpipe_LRInfo::names, _Lpipe_LRInfo::num_names, _Softpipe_Op_Info::pred_mve_info, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_update_lr_last_acc (Lpipe_LRInfo * lr_info, int issue_time, int issue_slot, int ii) [static]
Definition at line 232 of file l_mve.c.
References _Lpipe_LRInfo::first_def_slot, _Lpipe_LRInfo::first_def_time, _Lpipe_LRInfo::last_access_slot, _Lpipe_LRInfo::last_access_time, _Lpipe_LRInfo::lifetime, and _Lpipe_LRInfo::use_after_def_slot.
Referenced by Lpipe_construct_lr().
Variable Documentation
L_Alloc_Pool* Lpipe_dest_mve_pool = NULL
Definition at line 81 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().
L_Alloc_Pool* Lpipe_LRInfo_pool = NULL [static]
Definition at line 86 of file l_mve.c.
Referenced by Lpipe_create_live_range_info(), and Lpipe_delete_all_live_range_info().
List Lpipe_mve_lr_list = NULL [static]
Definition at line 89 of file l_mve.c.
Referenced by Lpipe_analyze_lr(), and Lpipe_free_mve_info().
L_Alloc_Pool* Lpipe_MVEInfo_pool = NULL
Definition at line 87 of file l_mve.c.
Referenced by Lpipe_delete_all_mve_info(), Lpipe_init(), and Lpipe_new_opd_mve_info().
L_Alloc_Pool* Lpipe_pred_mve_pool = NULL
Definition at line 79 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().
L_Alloc_Pool* Lpipe_src_mve_pool = NULL
Definition at line 77 of file l_mve.c.
Referenced by Lpipe_create_op_info(), Lpipe_free_mve_info(), Lpipe_free_oper_op_info(), and Lpipe_init().