l_pipe_util.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include <Lcode/r_regalloc.h>
Functions
void L_read_parm_lpipe (Parm_Parse_Info *ppi)
Queue * Q_create_queue ()
void Q_reinit_queue (Queue *queue)
void Q_delete_queue (Queue *queue)
void Q_priority_enqueue_increasing (Queue *queue, SM_Oper *oper, int priority)
void Q_priority_enqueue_decreasing (Queue *queue, SM_Oper *oper, int priority)
SM_Oper * Q_dequeue (Queue *queue)
SM_Oper * Q_peek_tail (Queue *queue)
SM_Oper * Q_peek_head (Queue *queue)
int Lpipe_reordered_anti_dependent_ops (SM_Oper *oper, SM_Oper *next_oper)
void Lpipe_ignore_self_dependences (SM_Cb *sm_cb)
L_Oper * Lpipe_find_loop_back_br (L_Func *fn, L_Cb *header_cb)
void Lpipe_remove_branches (L_Func *fn, int unroll)
void Lpipe_cb_set_iter (SM_Cb *sm_cb)
void Lpipe_cb_set_issue_time (SM_Cb *sm_cb)
L_Oper * Lpipe_gen_uncond_pred_define (L_Operand *pred0, L_Operand *pred1, L_Operand *dest, int opc)
void Lpipe_create_uncond_pred_defines (L_Func *fn)
void Lpipe_create_start_stop_nodes (SM_Cb *sm_cb)
void Lpipe_delete_start_stop_nodes (SM_Cb *sm_cb)
void Lpipe_print_cb_schedule (FILE *file, L_Func *fn, SM_Cb *sm_cb)
void Lpipe_create_defines (L_Func *fn)
void Lpipe_delete_defines (L_Func *fn)
void Lpipe_print_cyclic_stats (FILE *gen_statfile, L_Cb *header_cb, Softpipe_MinII *MinII, int ii, int tries, int schedule_length, int loop_dep_height, int stage_count, int unroll, int theta, int num_oper, int branch_count, L_Inner_Loop *loop)
L_Oper * Lpipe_gen_mov_consuming_operands (L_Operand *dest, L_Operand *src)
void Lpipe_move_int_parm_regs (L_Func *fn)
int Lpipe_can_create_fallthru_cb (L_Cb *cb)
void Lpipe_reduce_defines (L_Func *fn)
void Lpipe_insert_non_rr_defines (L_Func *fn)
Variables
L_Alloc_Pool * Queue_pool = NULL
L_Alloc_Pool * Qnode_pool = NULL
int Lpipe_do_induction_reversal = 0
int Lpipe_check_loops_in_phase1 = 1
char * Lpipe_schema_name = NULL
int Lpipe_schema = MULTI_EPI
int Lpipe_backward_sched = 1
float Lpipe_budget_ratio = 5.0
int Lpipe_min_ii = 0
int Lpipe_max_ii = 1000
int Lpipe_max_stages = 1000
int Lpipe_max_tries = 50
int Lpipe_fixed_slots_for_branches = 0
int Lpipe_do_only_postpass_steps = 0
int Lpipe_compact_branch_path_opers = 0
int Lpipe_sort_mrt_rows = 1
int Lpipe_combine_cbs = 1
int Lpipe_debug = 0
int Lpipe_debug_use_cb_bounds = 0
int Lpipe_debug_lower_cb_bound = 0
int Lpipe_debug_upper_cb_bound = 100000000
int Lpipe_print_statistics = 0
int Lpipe_print_iteration_schedule = 0
int Lpipe_print_schedules_for_debug = 0
int Lpipe_print_mve_summary = 0
int Lpipe_compute_loop_reg_pressure = 0
int Lpipe_add_spill_attributes = 0
int Lpipe_dump_dot = 0
Function Documentation
void L_read_parm_lpipe (Parm_Parse_Info * ppi)
Definition at line 123 of file l_pipe_util.c.
References KERNEL_ONLY, Lpipe_add_spill_attributes, Lpipe_backward_sched, Lpipe_budget_ratio, Lpipe_check_loops_in_phase1, Lpipe_combine_cbs, Lpipe_compact_branch_path_opers, Lpipe_compute_loop_reg_pressure, Lpipe_debug, Lpipe_debug_lower_cb_bound, Lpipe_debug_upper_cb_bound, Lpipe_debug_use_cb_bounds, Lpipe_do_induction_reversal, Lpipe_do_only_postpass_steps, Lpipe_dump_dot, Lpipe_fixed_slots_for_branches, Lpipe_max_ii, Lpipe_max_stages, Lpipe_max_tries, Lpipe_min_ii, Lpipe_print_iteration_schedule, Lpipe_print_mve_summary, Lpipe_print_schedules_for_debug, Lpipe_print_statistics, Lpipe_schema, Lpipe_schema_name, Lpipe_sort_mrt_rows, MULTI_EPI, MULTI_EPI_ROT_REG, and REM_LOOP.
Referenced by Lpipe_init(), and Lpipe_loop_prep_init().
int Lpipe_can_create_fallthru_cb (L_Cb * cb)
Definition at line 1536 of file l_pipe_util.c.
Referenced by Lpipe_softpipe_loop_prep().
void Lpipe_cb_set_issue_time (SM_Cb * sm_cb)
Definition at line 651 of file l_pipe_util.c.
References SM_Cb::first_serial_op, _Softpipe_Op_Info::issue_time, SM_Oper::lcode_op, SM_Oper::next_serial_op, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_sm_commit().
void Lpipe_cb_set_iter (SM_Cb * sm_cb)
Definition at line 626 of file l_pipe_util.c.
References SM_Cb::first_serial_op, SM_Oper::lcode_op, and SM_Oper::next_serial_op.
Referenced by Lpipe_sm_commit().
void Lpipe_create_defines (L_Func * fn)
Definition at line 1002 of file l_pipe_util.c.
References M_arch, M_native_int_register_ctype(), M_return_epilogue_cntr_register(), M_TAHOE, and R_get_rot_reg_alloc_multiple().
Referenced by Lpipe_software_pipeline().
void Lpipe_create_start_stop_nodes (SM_Cb * sm_cb)
Definition at line 788 of file l_pipe_util.c.
References SM_Oper::ext_dest, SM_Oper::ext_src, SM_Reg_Action::first_dep_in, SM_Oper::first_op_action, SM_Cb::first_serial_op, SM_Dep::from_action, SM_Cb::last_serial_op, Lpipe_create_op_info(), Lpipe_init_op_info(), MDES_SYNC_OUT, SM_Dep::next_dep_in, SM_Reg_Action::next_op_action, SM_Oper::next_serial_op, SM_add_dep(), SM_add_reg_action(), SM_FIXED_DELAY, SM_FLOW_DEP, SM_HARD_DEP, SM_ignore_dep(), SM_insert_oper_after(), SM_MVE_IGNORE, SM_Reg_Action::sm_op, SM_SOFT_DEP, SM_SYNC_ACTION_INDEX, SM_SYNC_ACTION_OPERAND, and SM_SYNC_DEP.
Referenced by Lpipe_pipeline_loop().
void Lpipe_create_uncond_pred_defines (L_Func * fn)
Definition at line 713 of file l_pipe_util.c.
References Lpipe_debug, and Lpipe_gen_uncond_pred_define().
Referenced by Lpipe_software_pipeline().
void Lpipe_delete_defines (L_Func * fn)
Definition at line 1261 of file l_pipe_util.c.
References M_is_template_op.
Referenced by Lpipe_software_pipeline().
void Lpipe_delete_start_stop_nodes (SM_Cb * sm_cb)
Definition at line 875 of file l_pipe_util.c.
References SM_Cb::first_serial_op, SM_Cb::lcode_cb, SM_Oper::lcode_op, Lpipe_free_oper_op_info(), SM_Oper::next_serial_op, SM_Oper::sm_cb, and SM_delete_oper().
Referenced by Lpipe_failure(), and Lpipe_pipeline_loop().
L_Oper* Lpipe_find_loop_back_br (L_Func * fn, L_Cb * header_cb)
Definition at line 554 of file l_pipe_util.c.
Referenced by Lpipe_rem_loop_gen().
L_Oper* Lpipe_gen_mov_consuming_operands (L_Operand * dest, L_Operand * src)
Definition at line 1375 of file l_pipe_util.c.
Referenced by L_fix_exposed_pred_wrt(), Lpipe_fix_live_in(), Lpipe_fix_live_out_epi(), Lpipe_fix_live_out_stage(), Lpipe_fix_set_out_epi(), Lpipe_fix_set_out_stage(), Lpipe_gen_epilogue_counter(), Lpipe_gen_loop_counter(), Lpipe_move_int_parm_regs(), and Lpipe_rename_mac().
L_Oper* Lpipe_gen_uncond_pred_define (L_Operand * pred0, L_Operand * pred1, L_Operand * dest, int opc)
Definition at line 676 of file l_pipe_util.c.
References M_native_int_register_ctype().
Referenced by Lpipe_create_uncond_pred_defines(), and Lpipe_kernel_gen_rot().
void Lpipe_ignore_self_dependences (SM_Cb * sm_cb)
Definition at line 506 of file l_pipe_util.c.
References SM_Reg_Action::first_dep_in, SM_Oper::first_op_action, SM_Cb::first_serial_op, SM_Dep::from_action, SM_Dep::ignore, SM_Oper::lcode_op, SM_Dep::next_dep_in, SM_Reg_Action::next_op_action, SM_Oper::next_serial_op, SM_ignore_dep(), SM_MVE_IGNORE, SM_Reg_Action::sm_op, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_insert_non_rr_defines (L_Func * fn)
Definition at line 1606 of file l_pipe_util.c.
References R_build_rotating_reg_set().
void Lpipe_move_int_parm_regs (L_Func * fn)
Definition at line 1414 of file l_pipe_util.c.
References L_annotate_oper(), Lpipe_gen_mov_consuming_operands(), and M_native_int_register_ctype().
void Lpipe_print_cb_schedule (FILE * file, L_Func * fn, SM_Cb * sm_cb)
Definition at line 928 of file l_pipe_util.c.
References SM_Oper_Queue::first_qentry, header_cb, SM_Cb::kernel_queue, SM_Cb::lcode_cb, SM_Oper::lcode_op, SM_Oper_Qentry::next_qentry, sched_file, SM_attach_isl(), and SM_Oper_Qentry::sm_op.
Referenced by Lpipe_pipeline_loop().
void Lpipe_print_cyclic_stats (FILE * gen_statfile, L_Cb * header_cb, Softpipe_MinII * MinII, int ii, int tries, int schedule_length, int loop_dep_height, int stage_count, int unroll, int theta, int num_oper, int branch_count, L_Inner_Loop * loop)
Definition at line 1296 of file l_pipe_util.c.
References Lpipe_budget_ratio.
Referenced by Lpipe_pipeline_loop().
void Lpipe_reduce_defines (L_Func * fn)
Definition at line 1560 of file l_pipe_util.c.
Referenced by Lpipe_software_pipeline().
void Lpipe_remove_branches (L_Func * fn, int unroll)
Definition at line 605 of file l_pipe_util.c.
References header_cb, _Softpipe_Op_Info::kernel_copy, SOFTPIPE_OP_INFO, and Softpipe_Op_Info_pool.
Referenced by Lpipe_pipeline_loop().
int Lpipe_reordered_anti_dependent_ops (SM_Oper * oper, SM_Oper * next_oper)
Definition at line 432 of file l_pipe_util.c.
References SM_Oper::dest, SM_Reg_Action::first_dep_out, SM_Dep::ignore, SM_Dep::min_delay, SM_Dep::next_dep_out, SM_Dep::omega, SM_Reg_Action::sm_op, and SM_Dep::to_action.
Referenced by Lpipe_sort_MRT_rows().
Queue* Q_create_queue ()
Definition at line 217 of file l_pipe_util.c.
References Queue::head, Queue_pool, and Queue::tail.
Referenced by Lpipe_sm_schedule().
void Q_delete_queue (Queue * queue)
Definition at line 245 of file l_pipe_util.c.
References Queue::head, Qnode::next_qnode, Qnode_pool, and Queue_pool.
SM_Oper* Q_dequeue (Queue * queue)
Definition at line 374 of file l_pipe_util.c.
References Queue::head, SM_Oper::lcode_op, Lpipe_debug, Qnode::next_qnode, Qnode::oper, Qnode::prev_qnode, Qnode::priority, Qnode_pool, and Queue::tail.
Referenced by Lpipe_sm_schedule().
SM_Oper* Q_peek_head (Queue * queue)
Definition at line 418 of file l_pipe_util.c.
References Queue::head, and Qnode::oper.
SM_Oper* Q_peek_tail (Queue * queue)
Definition at line 408 of file l_pipe_util.c.
References Qnode::oper, and Queue::tail.
void Q_priority_enqueue_decreasing (Queue * queue, SM_Oper * oper, int priority)
Definition at line 318 of file l_pipe_util.c.
References Queue::head, SM_Oper::lcode_op, Lpipe_debug, Qnode::next_qnode, Qnode::oper, Qnode::prev_qnode, Qnode::priority, Qnode_pool, and Queue::tail.
Referenced by Lpipe_eject_oper_for_resource_conflict(), Lpipe_eject_opers_if_dependence_conflict(), and Lpipe_sm_schedule().
void Q_priority_enqueue_increasing (Queue * queue, SM_Oper * oper, int priority)
Definition at line 261 of file l_pipe_util.c.
References Queue::head, SM_Oper::lcode_op, Lpipe_debug, Qnode::next_qnode, Qnode::oper, Qnode::prev_qnode, Qnode::priority, Qnode_pool, and Queue::tail.
Referenced by Lpipe_eject_oper_for_resource_conflict(), Lpipe_eject_opers_if_dependence_conflict(), and Lpipe_sm_schedule().
void Q_reinit_queue (Queue * queue)
Definition at line 229 of file l_pipe_util.c.
References Queue::head, Qnode::next_qnode, Qnode_pool, and Queue::tail.
Variable Documentation
int Lpipe_add_spill_attributes = 0
Definition at line 111 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_mark_loops_with_spills(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
int Lpipe_backward_sched = 1
Definition at line 85 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_compute_ready_time(), Lpipe_compute_static_priorities(), Lpipe_eject_oper_for_resource_conflict(), Lpipe_eject_opers_if_dependence_conflict(), Lpipe_optimize_lifetimes(), and Lpipe_sm_schedule().
float Lpipe_budget_ratio = 5.0
Definition at line 87 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_pipeline_loop(), and Lpipe_print_cyclic_stats().
int Lpipe_check_loops_in_phase1 = 1
Definition at line 80 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_loop_prep_end(), Lpipe_loop_prep_init(), and Lpipe_softpipe_loop_prep().
int Lpipe_combine_cbs = 1
Definition at line 99 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_software_pipeline().
int Lpipe_compact_branch_path_opers = 0
Definition at line 96 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe().
int Lpipe_compute_loop_reg_pressure = 0
Definition at line 110 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_compute_reg_pressure(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
int Lpipe_debug = 0
Definition at line 101 of file l_pipe_util.c.
Referenced by L_fix_exposed_pred_wrt(), L_read_parm_lpipe(), Lpipe_analyze_lr(), Lpipe_construct_lr(), Lpipe_create_uncond_pred_defines(), Lpipe_do_compact_branch_path_opers(), Lpipe_eject_oper_for_resource_conflict(), Lpipe_eject_opers_if_dependence_conflict(), Lpipe_optimize_lifetimes(), Lpipe_pipeline_loop(), Lpipe_sm_schedule(), Lpipe_softpipe_loop_prep(), Lpipe_sort_MRT_rows(), Q_dequeue(), Q_priority_enqueue_decreasing(), and Q_priority_enqueue_increasing().
int Lpipe_debug_lower_cb_bound = 0
Definition at line 103 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_software_pipeline().
int Lpipe_debug_upper_cb_bound = 100000000
Definition at line 104 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_software_pipeline().
int Lpipe_debug_use_cb_bounds = 0
Definition at line 102 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_software_pipeline().
int Lpipe_do_induction_reversal = 0
Definition at line 79 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_softpipe_loop_prep().
int Lpipe_do_only_postpass_steps = 0
Definition at line 94 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_software_pipeline().
int Lpipe_dump_dot = 0
Definition at line 113 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_sm_commit().
int Lpipe_fixed_slots_for_branches = 0
Definition at line 93 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_sort_MRT_rows().
int Lpipe_max_ii = 1000
Definition at line 89 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_pipeline_loop().
int Lpipe_max_stages = 1000
Definition at line 90 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe().
int Lpipe_max_tries = 50
Definition at line 91 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe().
int Lpipe_min_ii = 0
Definition at line 88 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_pipeline_loop().
int Lpipe_print_iteration_schedule = 0
Definition at line 106 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_cleanup(), and Lpipe_init().
int Lpipe_print_mve_summary = 0
Definition at line 108 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_associate_mve_regs(), and Lpipe_associate_rot_regs().
int Lpipe_print_schedules_for_debug = 0
Definition at line 107 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_cleanup(), and Lpipe_init().
int Lpipe_print_statistics = 0
Definition at line 105 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_cleanup(), Lpipe_init(), Lpipe_loop_prep_end(), Lpipe_loop_prep_init(), Lpipe_pipeline_loop(), Lpipe_softpipe_loop_prep(), and Lpipe_software_pipeline().
int Lpipe_schema = MULTI_EPI
Definition at line 83 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), Lpipe_analyze_lr(), Lpipe_associate_rot_regs(), Lpipe_construct_lr(), Lpipe_fix_live_in_rot(), Lpipe_fix_live_out(), Lpipe_free_mve_info(), Lpipe_mark_loops_with_spills(), Lpipe_pipeline_loop(), Lpipe_softpipe_loop_prep(), and Lpipe_software_pipeline().
char* Lpipe_schema_name = NULL
Definition at line 82 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe(), and Lpipe_init().
int Lpipe_sort_mrt_rows = 1
Definition at line 97 of file l_pipe_util.c.
Referenced by L_read_parm_lpipe().
L_Alloc_Pool* Qnode_pool = NULL
Definition at line 71 of file l_pipe_util.c.
Referenced by Lpipe_init(), Q_delete_queue(), Q_dequeue(), Q_priority_enqueue_decreasing(), Q_priority_enqueue_increasing(), and Q_reinit_queue().
L_Alloc_Pool* Queue_pool = NULL
Definition at line 70 of file l_pipe_util.c.
Referenced by Lpipe_init(), Q_create_queue(), and Q_delete_queue().