l_pipe_sched.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <alloca.h>
#include `l_softpipe_int.h`
#include `l_pipe_sched.h`
#include `l_mve.h`
Defines
#define LARGE_NUMBER 1000
Functions
static void Lpipe_sort_MRT_rows (SM_Cb *sm_cb)
void Lpipe_mark_branch_path_opers (SM_Cb *sm_cb, SM_Oper *sm_loop_back_br)
static void Lpipe_do_compact_branch_path_opers (SM_Cb *sm_cb, SM_Oper *sm_loop_back_br)
static void Lpipe_optimize_lifetimes (SM_Cb *sm_cb)
static void Lpipe_compute_slack_time_using_MinDist (SM_Cb *sm_cb)
static void Lpipe_compute_static_priorities (SM_Cb *sm_cb)
static void Lpipe_compute_ready_time (SM_Cb *sm_cb, SM_Oper *sm_op, int init_ready_time)
static void Lpipe_eject_opers_if_dependence_conflict (SM_Oper *sm_op, int II, int desired_cycle)
static void Lpipe_eject_oper_for_resource_conflict (SM_Oper *sm_op)
static void Lpipe_eject_earlier_branches_and_last_slot (SM_Cb *sm_cb, int row, int last_slot)
static void Lpipe_eject_opers_if_resource_conflict (SM_Cb *sm_cb, int cycle)
void Lpipe_sm_terminate (SM_Cb *sm_cb)
int Lpipe_sm_schedule (SM_Cb *sm_cb, int II, SM_Oper *loop_back_br, int budget)
void Lpipe_sm_commit (SM_Cb *sm_cb)
Variables
static Queue * Lpipe_ready_queue = NULL
Define Documentation
#define LARGE_NUMBER 1000
Definition at line 76 of file l_pipe_sched.c.
Referenced by Lpipe_sm_schedule().
Function Documentation
static void Lpipe_compute_ready_time (SM_Cb * sm_cb, SM_Oper * sm_op, int init_ready_time) [static]
Definition at line 794 of file l_pipe_sched.c.
References SM_Reg_Action::first_dep_in, SM_Reg_Action::first_dep_out, SM_Oper::first_op_action, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::II, SM_Oper::lcode_op, Lpipe_backward_sched, SM_Dep::min_delay, SM_Dep::next_dep_in, SM_Dep::next_dep_out, SM_Reg_Action::next_op_action, SM_Dep::omega, _Softpipe_Op_Info::ready_time, SM_Oper::sched_cycle, _Softpipe_Op_Info::scheduled, SM_Reg_Action::sm_op, SOFTPIPE_OP_INFO, and SM_Dep::to_action.
Referenced by Lpipe_sm_schedule().
static void Lpipe_compute_slack_time_using_MinDist (SM_Cb * sm_cb) [static]
Definition at line 643 of file l_pipe_sched.c.
References _Softpipe_Op_Info::estart, SM_Cb::first_serial_op, SM_Cb::last_serial_op, SM_Cb::lcode_cb, SM_Oper::lcode_op, loop_dep_height, _Softpipe_Op_Info::lstart, SM_Oper::next_serial_op, SM_Cb::op_count, SM_Oper::prev_serial_op, _Softpipe_Op_Info::slack, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_sm_schedule().
static void Lpipe_compute_static_priorities (SM_Cb * sm_cb) [static]
Definition at line 713 of file l_pipe_sched.c.
References _Softpipe_Op_Info::estart, SM_Cb::first_serial_op, SM_Oper::lcode_op, _Softpipe_Op_Info::loop_back_br, Lpipe_backward_sched, _Softpipe_Op_Info::lstart, SM_Oper::next_serial_op, _Softpipe_Op_Info::priority, _Softpipe_Op_Info::slack, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_sm_schedule().
static void Lpipe_do_compact_branch_path_opers (SM_Cb * sm_cb, SM_Oper * sm_loop_back_br) [static]
Definition at line 281 of file l_pipe_sched.c.
References _Softpipe_Op_Info::branch_path_node, SM_Reg_Action::first_dep_in, SM_Oper::first_op_action, SM_Cb::first_serial_op, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::II, IMPOSSIBLE_SLACK, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, SM_Oper::lcode_op, Lpipe_debug, SM_Dep::min_delay, SM_Dep::next_dep_in, SM_Reg_Action::next_op_action, SM_Oper::next_serial_op, SM_Dep::omega, SM_Oper::sched_cycle, SM_Oper::sched_slot, SM_MAX_CYCLE, SM_Reg_Action::sm_op, SM_schedule_oper(), SM_unschedule_oper(), and SOFTPIPE_OP_INFO.
static void Lpipe_eject_earlier_branches_and_last_slot (SM_Cb * sm_cb, int row, int last_slot) [static]
Definition at line 1144 of file l_pipe_sched.c.
References SM_Cb::first_serial_op, SM_Cb::II, IS_MDES_FLAG_BR, SM_Oper::lcode_op, Lpipe_eject_oper_for_resource_conflict(), Lpipe_total_issue_slots, SM_Oper::next_serial_op, _Softpipe_Op_Info::priority, SM_Oper::sched_cycle, SM_Oper::sched_slot, _Softpipe_Op_Info::scheduled, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_sm_schedule().
static void Lpipe_eject_oper_for_resource_conflict (SM_Oper * sm_op) [static]
Definition at line 1112 of file l_pipe_sched.c.
References _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, SM_Oper::lcode_op, _Softpipe_Op_Info::loop_back_br, Lpipe_backward_sched, Lpipe_debug, Lpipe_ready_queue, _Softpipe_Op_Info::priority, Q_priority_enqueue_decreasing(), Q_priority_enqueue_increasing(), SM_Oper::sched_cycle, SM_Oper::sched_slot, _Softpipe_Op_Info::scheduled, SM_unschedule_oper(), and SOFTPIPE_OP_INFO.
Referenced by Lpipe_eject_earlier_branches_and_last_slot(), and Lpipe_eject_opers_if_resource_conflict().
static void Lpipe_eject_opers_if_dependence_conflict (SM_Oper * sm_op, int II, int desired_cycle) [static]
Definition at line 898 of file l_pipe_sched.c.
References SM_Reg_Action::first_dep_in, SM_Reg_Action::first_dep_out, SM_Oper::first_op_action, SM_Dep::from_action, SM_Dep::ignore, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_time, SM_Oper::lcode_op, Lpipe_backward_sched, Lpipe_debug, Lpipe_ready_queue, SM_Dep::min_delay, SM_Dep::next_dep_in, SM_Dep::next_dep_out, SM_Reg_Action::next_op_action, SM_Dep::omega, _Softpipe_Op_Info::priority, Q_priority_enqueue_decreasing(), Q_priority_enqueue_increasing(), SM_Oper::sched_cycle, SM_Oper::sched_slot, _Softpipe_Op_Info::scheduled, SM_Reg_Action::sm_op, SM_unschedule_oper(), SOFTPIPE_OP_INFO, and SM_Dep::to_action.
Referenced by Lpipe_sm_schedule().
static void Lpipe_eject_opers_if_resource_conflict (SM_Cb * sm_cb, int cycle) [static]
Definition at line 1193 of file l_pipe_sched.c.
References SM_Cb::first_serial_op, SM_Cb::II, SM_Oper::lcode_op, Lpipe_eject_oper_for_resource_conflict(), SM_Oper::next_serial_op, SM_Oper::sched_cycle, _Softpipe_Op_Info::scheduled, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_sm_schedule().
void Lpipe_mark_branch_path_opers (SM_Cb * sm_cb, SM_Oper * sm_loop_back_br)
Definition at line 228 of file l_pipe_sched.c.
References _Softpipe_Op_Info::branch_path_node, SM_Reg_Action::first_dep_in, SM_Oper::first_op_action, SM_Dep::flags, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::last_serial_op, SM_Oper::lcode_op, SM_Dep::next_dep_in, SM_Reg_Action::next_op_action, SM_Dep::omega, SM_Oper::prev_serial_op, SM_FLOW_DEP, SM_Reg_Action::sm_op, SM_REG_DEP, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_optimize_lifetimes (SM_Cb * sm_cb) [static]
Definition at line 420 of file l_pipe_sched.c.
References SM_Reg_Action::first_dep_in, SM_Reg_Action::first_dep_out, SM_Oper::first_op_action, SM_Cb::first_serial_op, SM_Dep::flags, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::II, IMPOSSIBLE_SLACK, _Softpipe_Op_Info::intra_iter_issue_time, SM_Cb::last_serial_op, SM_Oper::lcode_op, _Softpipe_Op_Info::loop_back_br, Lpipe_backward_sched, Lpipe_debug, SM_Dep::min_delay, SM_Dep::next_dep_in, SM_Dep::next_dep_out, SM_Reg_Action::next_op_action, SM_Oper::next_serial_op, SM_Dep::omega, SM_Oper::prev_serial_op, SM_Oper::sched_cycle, SM_Oper::sched_slot, SM_FLOW_DEP, SM_Reg_Action::sm_op, SM_REG_DEP, SM_schedule_oper(), SM_unschedule_oper(), SOFTPIPE_OP_INFO, and SM_Dep::to_action.
void Lpipe_sm_commit (SM_Cb * sm_cb)
Definition at line 1877 of file l_pipe_sched.c.
References SM_Cb::lcode_cb, Lpipe_cb_set_issue_time(), Lpipe_cb_set_iter(), Lpipe_copy_sched_info(), Lpipe_dump_dot, SM_commit_cb(), and SM_print_cb_dot_graph().
Referenced by Lpipe_pipeline_loop().
int Lpipe_sm_schedule (SM_Cb * sm_cb, int II, SM_Oper * loop_back_br, int budget)
Definition at line 1227 of file l_pipe_sched.c.
References SM_Cb::first_serial_op, header_cb, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, LARGE_NUMBER, SM_Cb::last_serial_op, SM_Oper::lcode_op, Lpipe_backward_sched, Lpipe_compute_ready_time(), Lpipe_compute_slack_time_using_MinDist(), Lpipe_compute_static_priorities(), Lpipe_debug, Lpipe_eject_earlier_branches_and_last_slot(), Lpipe_eject_opers_if_dependence_conflict(), Lpipe_eject_opers_if_resource_conflict(), Lpipe_init_op_info(), Lpipe_ready_queue, Lpipe_total_issue_slots, SM_Oper::next_serial_op, SM_Oper::prev_serial_op, _Softpipe_Op_Info::priority, Q_create_queue(), Q_dequeue(), Q_priority_enqueue_decreasing(), Q_priority_enqueue_increasing(), _Softpipe_Op_Info::ready_time, SM_Oper::sched_slot, _Softpipe_Op_Info::scheduled, SM_Oper::slot_upper_bound, SM_do_template_bundling, SM_MAX_SLOT, SM_print_map(), SM_schedule_oper(), SM_set_cb_II(), SM_unschedule_cb(), and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_sm_terminate (SM_Cb * sm_cb)
Definition at line 1216 of file l_pipe_sched.c.
References SM_unschedule_cb().
Referenced by Lpipe_pipeline_loop().
static void Lpipe_sort_MRT_rows (SM_Cb * sm_cb) [static]
Definition at line 85 of file l_pipe_sched.c.
References SM_Oper_Queue::first_qentry, _Softpipe_Op_Info::home_block, SM_Cb::II, IS_MDES_FLAG_BR, SM_Cb::kernel_queue, SM_Oper::lcode_op, _Softpipe_Op_Info::loop_back_br, Lpipe_debug, Lpipe_fixed_slots_for_branches, Lpipe_reordered_anti_dependent_ops(), SM_Oper_Qentry::next_qentry, SM_Oper::sched_cycle, SM_Oper::sched_slot, SM_dequeue_oper(), SM_enqueue_oper_after(), SM_Oper_Qentry::sm_op, SM_schedule_oper(), SM_unschedule_oper(), and SOFTPIPE_OP_INFO.
Variable Documentation
Queue* Lpipe_ready_queue = NULL [static]
Definition at line 74 of file l_pipe_sched.c.
Referenced by Lpipe_eject_oper_for_resource_conflict(), Lpipe_eject_opers_if_dependence_conflict(), and Lpipe_sm_schedule().