l_pipe_sched.h File Reference
#include <config.h>
Defines
#define IMPOSSIBLE_SLACK 1000000
Functions
int Lpipe_sm_schedule (SM_Cb *, int, SM_Oper *, int)
void Lpipe_sm_terminate (SM_Cb *)
void Lpipe_sm_commit (SM_Cb *)
void Lpipe_mark_branch_path_opers (SM_Cb *, SM_Oper *)
Define Documentation
#define IMPOSSIBLE_SLACK 1000000
Definition at line 67 of file l_pipe_sched.h.
Referenced by Lpipe_do_compact_branch_path_opers(), and Lpipe_optimize_lifetimes().
Function Documentation
void Lpipe_mark_branch_path_opers (SM_Cb *, SM_Oper *)
Definition at line 228 of file l_pipe_sched.c.
References _Softpipe_Op_Info::branch_path_node, SM_Reg_Action::first_dep_in, SM_Oper::first_op_action, SM_Dep::flags, SM_Dep::from_action, SM_Dep::ignore, SM_Cb::last_serial_op, SM_Oper::lcode_op, SM_Dep::next_dep_in, SM_Reg_Action::next_op_action, SM_Dep::omega, SM_Oper::prev_serial_op, SM_FLOW_DEP, SM_Reg_Action::sm_op, SM_REG_DEP, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_sm_commit (SM_Cb *)
Definition at line 1877 of file l_pipe_sched.c.
References SM_Cb::lcode_cb, Lpipe_cb_set_issue_time(), Lpipe_cb_set_iter(), Lpipe_copy_sched_info(), Lpipe_dump_dot, SM_commit_cb(), and SM_print_cb_dot_graph().
Referenced by Lpipe_pipeline_loop().
int Lpipe_sm_schedule (SM_Cb *, int, SM_Oper *, int)
Definition at line 1227 of file l_pipe_sched.c.
References SM_Cb::first_serial_op, header_cb, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, LARGE_NUMBER, SM_Cb::last_serial_op, SM_Oper::lcode_op, Lpipe_backward_sched, Lpipe_compute_ready_time(), Lpipe_compute_slack_time_using_MinDist(), Lpipe_compute_static_priorities(), Lpipe_debug, Lpipe_eject_earlier_branches_and_last_slot(), Lpipe_eject_opers_if_dependence_conflict(), Lpipe_eject_opers_if_resource_conflict(), Lpipe_init_op_info(), Lpipe_ready_queue, Lpipe_total_issue_slots, SM_Oper::next_serial_op, SM_Oper::prev_serial_op, _Softpipe_Op_Info::priority, Q_create_queue(), Q_dequeue(), Q_priority_enqueue_decreasing(), Q_priority_enqueue_increasing(), _Softpipe_Op_Info::ready_time, SM_Oper::sched_slot, _Softpipe_Op_Info::scheduled, SM_Oper::slot_upper_bound, SM_do_template_bundling, SM_MAX_SLOT, SM_print_map(), SM_schedule_oper(), SM_set_cb_II(), SM_unschedule_cb(), and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
void Lpipe_sm_terminate (SM_Cb *)
Definition at line 1216 of file l_pipe_sched.c.
References SM_unschedule_cb().
Referenced by Lpipe_pipeline_loop().