l_pipe_sync.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include `l_pipe_sync.h`
Functions
void Lpipe_adjust_syncs_for_modulo_sched (SM_Cb *sm_cb)
void Lpipe_adjust_syncs_for_prologue (void)
void Lpipe_adjust_syncs_for_epilogue (L_Cb *epilogue_cb)
Function Documentation
void Lpipe_adjust_syncs_for_epilogue (L_Cb * epilogue_cb)
Definition at line 568 of file l_pipe_sync.c.
References header_cb, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_rem_loop_gen().
void Lpipe_adjust_syncs_for_modulo_sched (SM_Cb * sm_cb)
Definition at line 76 of file l_pipe_sync.c.
References header_cb, SM_Cb::lcode_cb, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_pipeline_loop().
void Lpipe_adjust_syncs_for_prologue (void)
Definition at line 291 of file l_pipe_sync.c.
References header_cb, prologue_cb, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_multi_epi_gen(), and Lpipe_rem_loop_gen().