l_pipe_rename.c File Reference
#include <config.h>
#include <alloca.h>
#include `l_softpipe_int.h`
#include `l_pipe_rename.h`
#include `l_pipe_util.h`
#include <Lcode/r_regalloc.h>
#include <Lcode/l_opti.h>
Data Structures
struct _LpipeLiveRange
Typedefs
typedef _LpipeLiveRange LpipeLiveRange
Functions
static int L_fix_exposed_pred_wrt (L_Func *fn, L_Cb *pipe_cb, int vreg)
void R_print_LpipeLiveRange (LpipeLiveRange *lr)
static void Lpipe_create_rename_comp_code_block (L_Func *fn, L_Cb *pipe_cb, L_Oper *exit_branch)
void Lpipe_create_comp_code_blocks (L_Func *fn, L_Inner_Loop *loop)
static void Lpipe_rename_mac (L_Func *fn, L_Operand *mopd, L_Inner_Loop *inl)
int Lpipe_rename_defined_macros (L_Func *fn, L_Inner_Loop *inl)
int Lpipe_fix_infinite_lifetimes (L_Func *fn, L_Cb *cb)
void Lpipe_rename_disj_vregs_in_loop (L_Func *fn, L_Inner_Loop *loop)
Variables
static LpipeLiveRange ** LpipeLiveRanges
static int numLpipeLiveRange
Typedef Documentation
typedef struct _LpipeLiveRange LpipeLiveRange
Function Documentation
static int L_fix_exposed_pred_wrt (L_Func * fn, L_Cb * pipe_cb, int vreg) [static]
Definition at line 292 of file l_pipe_rename.c.
References L_annotate_oper(), Lpipe_debug, and Lpipe_gen_mov_consuming_operands().
Referenced by Lpipe_fix_infinite_lifetimes().
void Lpipe_create_comp_code_blocks (L_Func * fn, L_Inner_Loop * loop)
Definition at line 152 of file l_pipe_rename.c.
References L_split_arc(), and Lpipe_create_rename_comp_code_block().
Referenced by Lpipe_software_pipeline().
static void Lpipe_create_rename_comp_code_block (L_Func * fn, L_Cb * pipe_cb, L_Oper * exit_branch) [static]
Definition at line 117 of file l_pipe_rename.c.
References exit_cb, L_annotate_oper(), and L_split_arc().
Referenced by Lpipe_create_comp_code_blocks().
int Lpipe_fix_infinite_lifetimes (L_Func * fn, L_Cb * cb)
Definition at line 335 of file l_pipe_rename.c.
References L_fix_exposed_pred_wrt().
Referenced by Lpipe_software_pipeline().
int Lpipe_rename_defined_macros (L_Func * fn, L_Inner_Loop * inl)
Definition at line 242 of file l_pipe_rename.c.
References Lpipe_rename_mac().
Referenced by Lpipe_software_pipeline().
void Lpipe_rename_disj_vregs_in_loop (L_Func * fn, L_Inner_Loop * loop)
Definition at line 353 of file l_pipe_rename.c.
References LpipeLiveRanges, M_arch, M_TI, M_X86, and numLpipeLiveRange.
Referenced by Lpipe_software_pipeline().
static void Lpipe_rename_mac (L_Func * fn, L_Operand * mopd, L_Inner_Loop * inl) [static]
Definition at line 180 of file l_pipe_rename.c.
References L_annotate_oper(), and Lpipe_gen_mov_consuming_operands().
Referenced by Lpipe_rename_defined_macros().
void R_print_LpipeLiveRange (LpipeLiveRange * lr)
Definition at line 102 of file l_pipe_rename.c.
References _LpipeLiveRange::def_op, _LpipeLiveRange::def_oper, _LpipeLiveRange::live_out_op, _LpipeLiveRange::op, _LpipeLiveRange::ref_op, and _LpipeLiveRange::vreg.
Variable Documentation
LpipeLiveRange** LpipeLiveRanges [static]
Definition at line 88 of file l_pipe_rename.c.
Referenced by Lpipe_rename_disj_vregs_in_loop().
int numLpipeLiveRange [static]
Definition at line 89 of file l_pipe_rename.c.
Referenced by Lpipe_rename_disj_vregs_in_loop().