l_pipe_rename.h File Reference
#include <config.h>
Functions
void Lpipe_create_comp_code_blocks (L_Func *fn, L_Inner_Loop *loop)
void Lpipe_rename_disj_vregs_in_loop (L_Func *, L_Inner_Loop *)
int Lpipe_fix_infinite_lifetimes (L_Func *fn, L_Cb *cb)
int Lpipe_rename_defined_macros (L_Func *fn, L_Inner_Loop *inl)
Function Documentation
void Lpipe_create_comp_code_blocks (L_Func * fn, L_Inner_Loop * loop)
Definition at line 152 of file l_pipe_rename.c.
References L_split_arc(), and Lpipe_create_rename_comp_code_block().
Referenced by Lpipe_software_pipeline().
int Lpipe_fix_infinite_lifetimes (L_Func * fn, L_Cb * cb)
Definition at line 335 of file l_pipe_rename.c.
References L_fix_exposed_pred_wrt().
Referenced by Lpipe_software_pipeline().
int Lpipe_rename_defined_macros (L_Func * fn, L_Inner_Loop * inl)
Definition at line 242 of file l_pipe_rename.c.
References Lpipe_rename_mac().
Referenced by Lpipe_software_pipeline().
void Lpipe_rename_disj_vregs_in_loop (L_Func *, L_Inner_Loop *)
Definition at line 353 of file l_pipe_rename.c.
References LpipeLiveRanges, M_arch, M_TI, M_X86, and numLpipeLiveRange.
Referenced by Lpipe_software_pipeline().