l_softpipe_info.h File Reference
#include <config.h>
#include <Lcode/l_code.h>
Data Structures
struct _Lpipe_LRInfo
struct _Lpipe_MVEInfo
struct _Softpipe_Op_Info
Typedefs
typedef _Lpipe_LRInfo Lpipe_LRInfo
typedef _Lpipe_MVEInfo Lpipe_MVEInfo
typedef _Softpipe_Op_Info Softpipe_Op_Info
Functions
Softpipe_Op_Info * Lpipe_create_op_info ()
void Lpipe_init_op_info (SM_Oper *, int, int)
void Lpipe_construct_op_info (SM_Cb *, SM_Oper *, int *, int *)
Softpipe_Op_Info * Lpipe_copy_op_info (Softpipe_Op_Info *)
void Lpipe_free_op_info (L_Cb *)
void Lpipe_free_oper_op_info (L_Oper *)
void Lpipe_print_op_info (SM_Oper *)
void Lpipe_print_cb_info (SM_Cb *)
void Lpipe_copy_sched_info (SM_Cb *)
Variables
L_Alloc_Pool * Softpipe_Op_Info_pool
Typedef Documentation
typedef struct _Lpipe_LRInfo Lpipe_LRInfo
typedef struct _Lpipe_MVEInfo Lpipe_MVEInfo
typedef struct _Softpipe_Op_Info Softpipe_Op_Info
Function Documentation
void Lpipe_construct_op_info (SM_Cb *, SM_Oper *, int *, int *)
Definition at line 141 of file l_softpipe_info.c.
References _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::exit_weight, SM_Cb::first_serial_op, _Softpipe_Op_Info::home_block, SM_Cb::lcode_cb, SM_Oper::lcode_op, _Softpipe_Op_Info::loop_back_br, Lpipe_create_op_info(), Lpipe_init_op_info(), and SM_Oper::next_serial_op.
Referenced by Lpipe_pipeline_loop().
Softpipe_Op_Info* Lpipe_copy_op_info (Softpipe_Op_Info *)
Definition at line 226 of file l_softpipe_info.c.
References _Softpipe_Op_Info::branch_path_node, _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::epilogue_stage, _Softpipe_Op_Info::estart, _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::exit_weight, _Softpipe_Op_Info::home_block, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, _Softpipe_Op_Info::loop_back_br, _Softpipe_Op_Info::lstart, _Softpipe_Op_Info::pred_mve_info, _Softpipe_Op_Info::priority, _Softpipe_Op_Info::prologue_stage, _Softpipe_Op_Info::ready_time, _Softpipe_Op_Info::scheduled, _Softpipe_Op_Info::slack, Softpipe_Op_Info_pool, _Softpipe_Op_Info::src_mve_info, _Softpipe_Op_Info::stage, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_gen_epi(), Lpipe_gen_epi_rot(), Lpipe_gen_partial_epi(), Lpipe_gen_partial_epi_rot(), Lpipe_multi_epi_gen(), Lpipe_multi_epi_gen_rot(), Lpipe_mve_transform(), and Lpipe_rem_loop_gen().
void Lpipe_copy_sched_info (SM_Cb *)
Definition at line 258 of file l_softpipe_info.c.
References SM_Cb::first_serial_op, SM_Cb::II, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, SM_Oper::lcode_op, SM_Oper::next_serial_op, SM_Oper::sched_slot, SOFTPIPE_OP_INFO, and _Softpipe_Op_Info::stage.
Referenced by Lpipe_sm_commit().
Softpipe_Op_Info* Lpipe_create_op_info ()
Definition at line 108 of file l_softpipe_info.c.
References _Softpipe_Op_Info::branch_path_node, _Softpipe_Op_Info::dest_mve_info, _Softpipe_Op_Info::exit_cb, _Softpipe_Op_Info::exit_weight, _Softpipe_Op_Info::home_block, _Softpipe_Op_Info::isrc_mve_info, _Softpipe_Op_Info::loop_back_br, Lpipe_dest_mve_pool, Lpipe_pred_mve_pool, Lpipe_src_mve_pool, _Softpipe_Op_Info::pred_mve_info, Softpipe_Op_Info_pool, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_construct_op_info(), and Lpipe_create_start_stop_nodes().
void Lpipe_free_op_info (L_Cb *)
Definition at line 301 of file l_softpipe_info.c.
References SOFTPIPE_OP_INFO, and Softpipe_Op_Info_pool.
Referenced by Lpipe_failure(), and Lpipe_pipeline_loop().
void Lpipe_free_oper_op_info (L_Oper *)
Definition at line 320 of file l_softpipe_info.c.
References _Softpipe_Op_Info::dest_mve_info, Lpipe_dest_mve_pool, Lpipe_pred_mve_pool, Lpipe_src_mve_pool, _Softpipe_Op_Info::pred_mve_info, SOFTPIPE_OP_INFO, Softpipe_Op_Info_pool, and _Softpipe_Op_Info::src_mve_info.
Referenced by Lpipe_delete_start_stop_nodes().
void Lpipe_init_op_info (SM_Oper *, int, int)
Definition at line 81 of file l_softpipe_info.c.
References _Softpipe_Op_Info::epilogue_stage, _Softpipe_Op_Info::estart, IMPOSSIBLE_PRIORITY, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, SM_Oper::lcode_op, _Softpipe_Op_Info::lstart, _Softpipe_Op_Info::priority, _Softpipe_Op_Info::prologue_stage, _Softpipe_Op_Info::ready_time, _Softpipe_Op_Info::scheduled, _Softpipe_Op_Info::slack, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_construct_op_info(), Lpipe_create_start_stop_nodes(), and Lpipe_sm_schedule().
void Lpipe_print_cb_info (SM_Cb *)
Definition at line 340 of file l_softpipe_info.c.
References SM_Cb::first_serial_op, SM_Cb::lcode_cb, Lpipe_print_op_info(), and SM_Oper::next_serial_op.
Referenced by Lpipe_pipeline_loop().
void Lpipe_print_op_info (SM_Oper *)
Definition at line 356 of file l_softpipe_info.c.
References _Softpipe_Op_Info::epilogue_stage, _Softpipe_Op_Info::estart, _Softpipe_Op_Info::intra_iter_issue_time, _Softpipe_Op_Info::issue_slot, _Softpipe_Op_Info::issue_time, _Softpipe_Op_Info::kernel_copy, SM_Oper::lcode_op, _Softpipe_Op_Info::lstart, _Softpipe_Op_Info::priority, _Softpipe_Op_Info::prologue_stage, _Softpipe_Op_Info::ready_time, _Softpipe_Op_Info::scheduled, _Softpipe_Op_Info::slack, SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and _Softpipe_Op_Info::unrolled_iter_num.
Referenced by Lpipe_print_cb_info().
Variable Documentation
L_Alloc_Pool* Softpipe_Op_Info_pool
Definition at line 66 of file l_softpipe_info.c.
Referenced by Lpipe_copy_op_info(), Lpipe_create_op_info(), Lpipe_free_op_info(), Lpipe_free_oper_op_info(), Lpipe_init(), and Lpipe_remove_branches().