l_softpipe.c File Reference
#include <config.h>
#include `l_softpipe_int.h`
#include `l_softpipe.h`
#include `l_pipe_sched.h`
#include `l_pipe_sync.h`
#include `l_pipe_rename.h`
#include `l_mve.h`
#include <Lcode/r_regalloc.h>
#include <Lcode/l_opti.h>
#include <Lcode/l_disjvreg.h>
Defines
#define MAX_TRIES 100
Functions
void Lpipe_init (Parm_Macro_List *command_line_macro_list)
void Lpipe_measurement_init (Parm_Macro_List *command_line_macro_list)
void Lpipe_cleanup (void)
void Lpipe_measurement_cleanup (void)
static void Lpipe_failure (SM_Cb *sm_cb, Softpipe_MinII *MinII)
static void Lpipe_compute_start_stop_issue_time (SM_Cb *sm_cb)
static int Lpipe_pipeline_loop (L_Func *fn, L_Inner_Loop *loop)
void Lpipe_software_pipeline (L_Func *fn)
void Lpipe_mark_loops_with_spills (L_Func *fn)
void Lpipe_compute_reg_pressure (L_Func *fn)
Variables
L_Cb * header_cb
L_Cb * preheader_cb
L_Cb * prologue_cb
L_Cb * remainder_cb
int Lpipe_stage_count
int Lpipe_counted_loop = 0
L_Oper ** kernel_copy_last_op = 0
L_Oper ** kernel_copy_first_op = 0
int loop_dep_height = -1
int Lpipe_total_issue_slots = -1
FILE * sched_file = NULL
FILE * pipe_statfile = NULL
FILE * gen_statfile = NULL
FILE * iters_statfile = NULL
FILE * reg_statfile = NULL
FILE * func_reg_statfile = NULL
FILE * spill_statfile = NULL
FILE * code_statfile = NULL
FILE * swp_code_statfile = NULL
FILE * acyclic_statfile = NULL
Define Documentation
#define MAX_TRIES 100
Definition at line 74 of file l_softpipe.c.
Referenced by Lpipe_pipeline_loop().
Function Documentation
void Lpipe_cleanup (void)
Definition at line 259 of file l_softpipe.c.
References gen_statfile, iters_statfile, Lpipe_measurement_cleanup(), Lpipe_print_iteration_schedule, Lpipe_print_schedules_for_debug, Lpipe_print_statistics, pipe_statfile, and sched_file.
void Lpipe_compute_reg_pressure (L_Func * fn)
Definition at line 1322 of file l_softpipe.c.
References func_reg_statfile, header_cb, Lpipe_compute_loop_reg_pressure, and reg_statfile.
static void Lpipe_compute_start_stop_issue_time (SM_Cb * sm_cb) [static]
Definition at line 327 of file l_softpipe.c.
References SM_Cb::first_serial_op, _Softpipe_Op_Info::intra_iter_issue_time, SM_Cb::last_serial_op, SM_Oper::lcode_op, SM_Oper::next_serial_op, SM_Oper::sched_cycle, SM_MAX_CYCLE, SM_MIN_CYCLE, and SOFTPIPE_OP_INFO.
Referenced by Lpipe_pipeline_loop().
static void Lpipe_failure (SM_Cb * sm_cb, Softpipe_MinII * MinII) [static]
Definition at line 295 of file l_softpipe.c.
References header_cb, SM_Cb::lcode_cb, Lpipe_delete_start_stop_nodes(), Lpipe_free_op_info(), and SM_delete_cb().
Referenced by Lpipe_pipeline_loop().
void Lpipe_init (Parm_Macro_List * command_line_macro_list)
Definition at line 139 of file l_softpipe.c.
References acyclic_statfile, code_statfile, func_reg_statfile, gen_statfile, iters_statfile, L_read_parm_lpipe(), Lpipe_dest_mve_pool, Lpipe_measurement_init(), Lpipe_MVEInfo_pool, Lpipe_pred_mve_pool, Lpipe_print_iteration_schedule, Lpipe_print_schedules_for_debug, Lpipe_print_statistics, Lpipe_schema_name, Lpipe_src_mve_pool, pipe_statfile, Qnode_pool, Queue_pool, reg_statfile, sched_file, Softpipe_Op_Info_pool, spill_statfile, and swp_code_statfile.
void Lpipe_mark_loops_with_spills (L_Func * fn)
Definition at line 978 of file l_softpipe.c.
References code_statfile, KERNEL_ONLY, Lpipe_add_spill_attributes, Lpipe_schema, num_cb, prologue_cb, spill_statfile, and swp_code_statfile.
void Lpipe_measurement_cleanup (void)
Definition at line 278 of file l_softpipe.c.
References code_statfile, func_reg_statfile, Lpipe_add_spill_attributes, Lpipe_compute_loop_reg_pressure, reg_statfile, spill_statfile, and swp_code_statfile.
Referenced by Lpipe_cleanup().
void Lpipe_measurement_init (Parm_Macro_List * command_line_macro_list)
Definition at line 226 of file l_softpipe.c.
References code_statfile, func_reg_statfile, Lpipe_add_spill_attributes, Lpipe_compute_loop_reg_pressure, reg_statfile, spill_statfile, and swp_code_statfile.
Referenced by Lpipe_init().
static int Lpipe_pipeline_loop (L_Func * fn, L_Inner_Loop * loop) [static]
Definition at line 367 of file l_softpipe.c.
References SM_Oper::flags, gen_statfile, header_cb, iters_statfile, kernel_copy_first_op, kernel_copy_last_op, KERNEL_ONLY, SM_Cb::lcode_cb, SM_Cb::lcode_fn, lmdes, loop_dep_height, Lpipe_adjust_syncs_for_modulo_sched(), Lpipe_analyze_lr(), Lpipe_budget_ratio, Lpipe_compute_start_stop_issue_time(), Lpipe_construct_op_info(), Lpipe_create_start_stop_nodes(), Lpipe_debug, Lpipe_delete_start_stop_nodes(), Lpipe_failure(), Lpipe_fix_live_in(), Lpipe_fix_live_in_rot(), Lpipe_fix_live_out(), Lpipe_fix_live_out_rot(), Lpipe_free_mve_info(), Lpipe_free_op_info(), Lpipe_ignore_self_dependences(), Lpipe_kernel_gen_rot(), Lpipe_mark_branch_path_opers(), Lpipe_max_ii, Lpipe_min_ii, Lpipe_multi_epi_gen(), Lpipe_multi_epi_gen_rot(), Lpipe_mve_transform(), Lpipe_print_cb_info(), Lpipe_print_cb_schedule(), Lpipe_print_cyclic_stats(), Lpipe_print_statistics, Lpipe_rem_loop_gen(), Lpipe_remove_branches(), Lpipe_remove_empty_epilogues(), Lpipe_rreg_transform(), Lpipe_schema, Lpipe_sm_commit(), Lpipe_sm_schedule(), Lpipe_sm_terminate(), Lpipe_stage_count, Lpipe_total_issue_slots, mdes_st::max_slot, MAX_TRIES, MULTI_EPI, MULTI_EPI_ROT_REG, SM_Cb::op_count, pipe_statfile, preheader_cb, prologue_cb, REM_LOOP, remainder_cb, SM_delete_cb(), SM_find_sm_op(), SM_LOOP_BACK_BR, SM_MODULO, SM_new_cb(), SM_NORMALIZE_ISSUE, SM_PREPASS, SM_print_cb_dependences(), SOFTPIPE_OP_INFO, _Softpipe_Op_Info::stage, and SM_Cb::version1_mdes.
Referenced by Lpipe_software_pipeline().
void Lpipe_software_pipeline (L_Func * fn)
Definition at line 753 of file l_softpipe.c.
References header_cb, KERNEL_ONLY, L_jump_branch_target_expansion(), L_jump_combine_branch_to_uncond_branch(), L_jump_combine_labels(), L_jump_elim_branch_to_next_block(), L_jump_merge_always_successive_blocks(), L_rename_disjoint_virtual_registers(), L_split_cb_after(), Lpipe_combine_cbs, Lpipe_counted_loop, Lpipe_create_comp_code_blocks(), Lpipe_create_defines(), Lpipe_create_uncond_pred_defines(), Lpipe_debug_lower_cb_bound, Lpipe_debug_upper_cb_bound, Lpipe_debug_use_cb_bounds, Lpipe_delete_defines(), Lpipe_do_only_postpass_steps, Lpipe_fix_infinite_lifetimes(), Lpipe_pipeline_loop(), Lpipe_print_statistics, Lpipe_reduce_defines(), Lpipe_rename_defined_macros(), Lpipe_rename_disj_vregs_in_loop(), Lpipe_schema, MULTI_EPI_ROT_REG, pipe_statfile, R_build_rotating_reg_set(), and REM_LOOP.
Variable Documentation
FILE* acyclic_statfile = NULL
Definition at line 120 of file l_softpipe.c.
Referenced by Lpipe_init().
FILE* code_statfile = NULL
Definition at line 116 of file l_softpipe.c.
Referenced by Lpipe_init(), Lpipe_mark_loops_with_spills(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
FILE* func_reg_statfile = NULL
Definition at line 112 of file l_softpipe.c.
Referenced by Lpipe_compute_reg_pressure(), Lpipe_init(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
FILE* gen_statfile = NULL
Definition at line 106 of file l_softpipe.c.
Referenced by Lpipe_cleanup(), Lpipe_init(), and Lpipe_pipeline_loop().
L_Cb* header_cb
Definition at line 83 of file l_softpipe.c.
Referenced by Lpipe_adjust_syncs_for_epilogue(), Lpipe_adjust_syncs_for_modulo_sched(), Lpipe_adjust_syncs_for_prologue(), Lpipe_compute_reg_pressure(), Lpipe_failure(), Lpipe_free_mve_info(), Lpipe_gen_epi_rot(), Lpipe_kernel_gen_rot(), Lpipe_multi_epi_gen(), Lpipe_pipeline_loop(), Lpipe_print_cb_schedule(), Lpipe_rem_loop_gen(), Lpipe_remove_branches(), Lpipe_sm_schedule(), Lpipe_softpipe_loop_prep(), and Lpipe_software_pipeline().
FILE* iters_statfile = NULL
Definition at line 108 of file l_softpipe.c.
Referenced by Lpipe_cleanup(), Lpipe_init(), and Lpipe_pipeline_loop().
L_Oper** kernel_copy_first_op = 0
Definition at line 91 of file l_softpipe.c.
Referenced by Lpipe_fix_live_out(), Lpipe_free_mve_info(), Lpipe_gen_epi(), Lpipe_gen_partial_epi(), Lpipe_multi_epi_gen(), Lpipe_mve_transform(), Lpipe_pipeline_loop(), and Lpipe_rem_loop_gen().
L_Oper** kernel_copy_last_op = 0
Definition at line 90 of file l_softpipe.c.
Referenced by Lpipe_fix_live_out(), Lpipe_free_mve_info(), Lpipe_gen_epi(), Lpipe_gen_partial_epi(), Lpipe_multi_epi_gen(), Lpipe_mve_transform(), Lpipe_pipeline_loop(), and Lpipe_rem_loop_gen().
int loop_dep_height = -1
Definition at line 93 of file l_softpipe.c.
Referenced by Lpipe_compute_slack_time_using_MinDist(), and Lpipe_pipeline_loop().
int Lpipe_counted_loop = 0
Definition at line 88 of file l_softpipe.c.
Referenced by Lpipe_software_pipeline().
int Lpipe_stage_count
Definition at line 87 of file l_softpipe.c.
Referenced by Lpipe_pipeline_loop().
int Lpipe_total_issue_slots = -1
Definition at line 94 of file l_softpipe.c.
Referenced by Lpipe_eject_earlier_branches_and_last_slot(), Lpipe_pipeline_loop(), and Lpipe_sm_schedule().
FILE* pipe_statfile = NULL
Definition at line 104 of file l_softpipe.c.
Referenced by Lpipe_cleanup(), Lpipe_init(), Lpipe_pipeline_loop(), and Lpipe_software_pipeline().
L_Cb* preheader_cb
Definition at line 84 of file l_softpipe.c.
Referenced by Lpipe_kernel_gen_rot(), Lpipe_multi_epi_gen(), Lpipe_multi_epi_gen_rot(), Lpipe_pipeline_loop(), and Lpipe_rem_loop_gen().
L_Cb* prologue_cb
Definition at line 85 of file l_softpipe.c.
Referenced by Lpipe_adjust_syncs_for_prologue(), Lpipe_fix_live_in(), Lpipe_fix_live_in_rot(), Lpipe_gen_partial_epi(), Lpipe_gen_partial_epi_rot(), Lpipe_kernel_gen_rot(), Lpipe_mark_loops_with_spills(), Lpipe_multi_epi_gen(), Lpipe_multi_epi_gen_rot(), Lpipe_pipeline_loop(), Lpipe_rem_loop(), Lpipe_rem_loop_gen(), and Lpipe_remove_empty_epilogues().
FILE* reg_statfile = NULL
Definition at line 110 of file l_softpipe.c.
Referenced by Lpipe_compute_reg_pressure(), Lpipe_init(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
L_Cb* remainder_cb
Definition at line 86 of file l_softpipe.c.
Referenced by Lpipe_pipeline_loop(), Lpipe_rem_loop(), and Lpipe_rem_loop_gen().
FILE* sched_file = NULL
Definition at line 101 of file l_softpipe.c.
Referenced by Lpipe_cleanup(), Lpipe_init(), and Lpipe_print_cb_schedule().
FILE* spill_statfile = NULL
Definition at line 114 of file l_softpipe.c.
Referenced by Lpipe_init(), Lpipe_mark_loops_with_spills(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().
FILE* swp_code_statfile = NULL
Definition at line 118 of file l_softpipe.c.
Referenced by Lpipe_init(), Lpipe_mark_loops_with_spills(), Lpipe_measurement_cleanup(), and Lpipe_measurement_init().