l_softpipe.h File Reference
#include <config.h>
#include <Lcode/l_main.h>
Functions
void Lpipe_init (Parm_Macro_List *)
void Lpipe_cleanup (void)
void Lpipe_measurement_init (Parm_Macro_List *)
void Lpipe_measurement_cleanup (void)
void Lpipe_software_pipeline (L_Func *)
void Lpipe_fill_delay_slots (L_Func *)
void Lpipe_mark_loops_with_spills (L_Func *)
void Lpipe_compute_reg_pressure (L_Func *)
void Lpipe_move_int_parm_regs (L_Func *)
void L_annotate_oper (L_Func *, L_Cb *, L_Oper *)
Function Documentation
void L_annotate_oper (L_Func *, L_Cb *, L_Oper *)
Referenced by L_fix_exposed_pred_wrt(), Lpipe_create_rename_comp_code_block(), Lpipe_fix_set_out_stage(), Lpipe_gen_epi_rot(), Lpipe_gen_epilogue_counter(), Lpipe_gen_loop_counter(), Lpipe_gen_rot_epi_fixup(), Lpipe_gen_rot_pro_fixup(), Lpipe_kernel_gen_rot(), Lpipe_move_int_parm_regs(), and Lpipe_rename_mac().
void Lpipe_cleanup (void)
Definition at line 259 of file l_softpipe.c.
References gen_statfile, iters_statfile, Lpipe_measurement_cleanup(), Lpipe_print_iteration_schedule, Lpipe_print_schedules_for_debug, Lpipe_print_statistics, pipe_statfile, and sched_file.
void Lpipe_compute_reg_pressure (L_Func *)
Definition at line 1322 of file l_softpipe.c.
References func_reg_statfile, header_cb, Lpipe_compute_loop_reg_pressure, and reg_statfile.
void Lpipe_fill_delay_slots (L_Func *)
void Lpipe_init (Parm_Macro_List *)
Definition at line 139 of file l_softpipe.c.
References acyclic_statfile, code_statfile, func_reg_statfile, gen_statfile, iters_statfile, L_read_parm_lpipe(), Lpipe_dest_mve_pool, Lpipe_measurement_init(), Lpipe_MVEInfo_pool, Lpipe_pred_mve_pool, Lpipe_print_iteration_schedule, Lpipe_print_schedules_for_debug, Lpipe_print_statistics, Lpipe_schema_name, Lpipe_src_mve_pool, pipe_statfile, Qnode_pool, Queue_pool, reg_statfile, sched_file, Softpipe_Op_Info_pool, spill_statfile, and swp_code_statfile.
void Lpipe_mark_loops_with_spills (L_Func *)
Definition at line 978 of file l_softpipe.c.
References code_statfile, KERNEL_ONLY, Lpipe_add_spill_attributes, Lpipe_schema, num_cb, prologue_cb, spill_statfile, and swp_code_statfile.
void Lpipe_measurement_cleanup (void)
Definition at line 278 of file l_softpipe.c.
References code_statfile, func_reg_statfile, Lpipe_add_spill_attributes, Lpipe_compute_loop_reg_pressure, reg_statfile, spill_statfile, and swp_code_statfile.
Referenced by Lpipe_cleanup().
void Lpipe_measurement_init (Parm_Macro_List *)
Definition at line 226 of file l_softpipe.c.
References code_statfile, func_reg_statfile, Lpipe_add_spill_attributes, Lpipe_compute_loop_reg_pressure, reg_statfile, spill_statfile, and swp_code_statfile.
Referenced by Lpipe_init().
void Lpipe_move_int_parm_regs (L_Func *)
Definition at line 1414 of file l_pipe_util.c.
References L_annotate_oper(), Lpipe_gen_mov_consuming_operands(), and M_native_int_register_ctype().
void Lpipe_software_pipeline (L_Func *)
Definition at line 753 of file l_softpipe.c.
References header_cb, KERNEL_ONLY, L_jump_branch_target_expansion(), L_jump_combine_branch_to_uncond_branch(), L_jump_combine_labels(), L_jump_elim_branch_to_next_block(), L_jump_merge_always_successive_blocks(), L_rename_disjoint_virtual_registers(), L_split_cb_after(), Lpipe_combine_cbs, Lpipe_counted_loop, Lpipe_create_comp_code_blocks(), Lpipe_create_defines(), Lpipe_create_uncond_pred_defines(), Lpipe_debug_lower_cb_bound, Lpipe_debug_upper_cb_bound, Lpipe_debug_use_cb_bounds, Lpipe_delete_defines(), Lpipe_do_only_postpass_steps, Lpipe_fix_infinite_lifetimes(), Lpipe_pipeline_loop(), Lpipe_print_statistics, Lpipe_reduce_defines(), Lpipe_rename_defined_macros(), Lpipe_rename_disj_vregs_in_loop(), Lpipe_schema, MULTI_EPI_ROT_REG, pipe_statfile, R_build_rotating_reg_set(), and REM_LOOP.