cpu_time.c File Reference
#include <config.h>
#include <stdio.h>
#include <bdd/util.h>
Functions
long util_cpu_time ()
Function Documentation
long util_cpu_time ()
Definition at line 41 of file cpu_time.c.
Referenced by Cudd_CofMinterm(), Cudd_ReduceHeap(), Cudd_StdPostReordHook(), Cudd_zddReduceHeap(), cuddGarbageCollect(), cuddGarbageCollectZdd(), ddShuffle(), ptime(), and zddShuffle().