cuddZddIsop.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_zddIsop (DdManager *dd, DdNode *L, DdNode *U, DdNode **zdd_I)
DdNode * Cudd_bddIsop (DdManager *dd, DdNode *L, DdNode *U)
DdNode * cuddZddIsop (DdManager *dd, DdNode *L, DdNode *U, DdNode **zdd_I)
DdNode * cuddBddIsop (DdManager *dd, DdNode *L, DdNode *U)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddIsop.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_bddIsop (DdManager * dd, DdNode * L, DdNode * U)
Function********************************************************************
Synopsis [Computes a BDD in the interval between L and U with a simple sum-of-produuct cover.]
Description [Computes a BDD in the interval between L and U with a simple sum-of-produuct cover. This procedure is similar to Cudd_zddIsop, but it does not return the ZDD for the cover. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddIsop]
Definition at line 143 of file cuddZddIsop.c.
References cuddBddIsop(), and DdManager::reordered.
DdNode* Cudd_zddIsop (DdManager * dd, DdNode * L, DdNode * U, DdNode ** zdd_I)
Function********************************************************************
Synopsis [Computes an ISOP in ZDD form from BDDs.]
Description [Computes an irredundant sum of products (ISOP) in ZDD form from BDDs. The two BDDs L and U represent the lower bound and the upper bound, respectively, of the function. The ISOP uses two ZDD variables for each BDD variable: One for the positive literal, and one for the negative literal. These two variables should be adjacent in the ZDD order. The two ZDD variables corresponding to BDD variable i should have indices 2i and 2i+1. The result of this procedure depends on the variable order. If successful, Cudd_zddIsop returns the BDD for the function chosen from the interval. The ZDD representing the irredundant cover is returned as a side effect in zdd_I. In case of failure, NULL is returned.]
SideEffects [zdd_I holds the pointer to the ZDD for the ISOP on successful return.]
SeeAlso [Cudd_bddIsop Cudd_zddVarsFromBddVars]
Definition at line 105 of file cuddZddIsop.c.
References DdManager::autoDynZ, cuddZddIsop(), and DdManager::reordered.
DdNode* cuddBddIsop (DdManager * dd, DdNode * L, DdNode * U)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddIsop.]
Description []
SideEffects [None]
SeeAlso [Cudd_bddIsop]
Definition at line 512 of file cuddZddIsop.c.
References Cudd_Deref(), Cudd_E, Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Ref(), Cudd_Regular, Cudd_T, cuddBddAndRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddUniqueInter(), DD_ONE, ddMin, one, DdManager::perm, and zero.
Referenced by Cudd_bddIsop(), and cuddZddIsop().
DdNode* cuddZddIsop (DdManager * dd, DdNode * L, DdNode * U, DdNode ** zdd_I)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddIsop.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddIsop]
Definition at line 176 of file cuddZddIsop.c.
References Cudd_Deref(), Cudd_E, Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, Cudd_T, cuddBddAndRecur(), cuddBddIsop(), cuddCacheInsert2(), cuddCacheLookup2(), cuddCacheLookup2Zdd(), cuddRef, cuddUniqueInter(), cuddZddGetNodeIVO(), DD_ONE, DD_ZERO, ddMin, exit(), one, DdManager::perm, and zero.
Referenced by Cudd_zddIsop().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddIsop.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddIsop.c]
PackageName [cudd]
Synopsis [Functions to find irredundant SOP covers as ZDDs from BDDs.]
Description [External procedures included in this module:
Cudd_bddIsop();
Cudd_zddIsop();
Internal procedures included in this module:
cuddBddIsop();
cuddZddIsop();
Static procedures included in this module:
]
SeeAlso []
Author [In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 60 of file cuddZddIsop.c.