cuddZddSymm.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define ZDD_MV_OOM (Move *)1L
Functions
static int cuddZddSymmSiftingAux ARGS ((DdManager *table, int x, int x_low, int x_high))
static Move *cuddZddSymmSifting_up ARGS ((DdManager *table, int x, int x_low, int initial_size))
static Move *cuddZddSymmSifting_down ARGS ((DdManager *table, int x, int x_high, int initial_size))
static int cuddZddSymmSiftingBackward ARGS ((DdManager *table, Move *moves, int size))
static int zdd_group_move ARGS ((DdManager *table, int x, int y, Move **moves))
static int zdd_group_move_backward ARGS ((DdManager *table, int x, int y))
static void cuddZddSymmSummary ARGS ((DdManager *table, int lower, int upper, int *symvars, int *symgroups))
void Cudd_zddSymmProfile (DdManager *table, int lower, int upper)
int cuddZddSymmCheck (DdManager *table, int x, int y)
int cuddZddSymmSifting (DdManager *table, int lower, int upper)
int cuddZddSymmSiftingConv (DdManager *table, int lower, int upper)
static int cuddZddSymmSiftingAux (DdManager *table, int x, int x_low, int x_high)
static int cuddZddSymmSiftingConvAux (DdManager *table, int x, int x_low, int x_high)
static Move * cuddZddSymmSifting_up (DdManager *table, int x, int x_low, int initial_size)
static Move * cuddZddSymmSifting_down (DdManager *table, int x, int x_high, int initial_size)
static int cuddZddSymmSiftingBackward (DdManager *table, Move *moves, int size)
static int zdd_group_move (DdManager *table, int x, int y, Move **moves)
static int zdd_group_move_backward (DdManager *table, int x, int y)
static void cuddZddSymmSummary (DdManager *table, int lower, int upper, int *symvars, int *symgroups)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddSymm.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
int * zdd_entry
int zddTotalNumberSwapping
static DdNode * empty
Define Documentation
#define ZDD_MV_OOM (Move *)1L
CFile***********************************************************************
FileName [cuddZddSymm.c]
PackageName [cudd]
Synopsis [Functions for symmetry-based ZDD variable reordering.]
Description [External procedures included in this module:
Cudd_zddSymmProfile()
Internal procedures included in this module:
cuddZddSymmCheck()
cuddZddSymmSifting()
cuddZddSymmSiftingConv()
Static procedures included in this module:
cuddZddUniqueCompare()
cuddZddSymmSiftingAux()
cuddZddSymmSiftingConvAux()
cuddZddSymmSifting_up()
cuddZddSymmSifting_down()
zdd_group_move()
cuddZddSymmSiftingBackward()
zdd_group_move_backward()
]
SeeAlso [cuddSymmetry.c]
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 52 of file cuddZddSymm.c.
Referenced by cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), cuddZddSymmSiftingAux(), and cuddZddSymmSiftingConvAux().
Function Documentation
static void cuddZddSymmSummary ARGS ((DdManager *table, int lower, int upper, int *symvars, int *symgroups)) [static]
static int zdd_group_move_backward ARGS ((DdManager *table, int x, int y)) [static]
static int zdd_group_move ARGS ((DdManager *table, int x, int y, Move **moves)) [static]
static int cuddZddSymmSiftingBackward ARGS ((DdManager *table, Move *moves, int size)) [static]
static Move* cuddZddSymmSifting_down ARGS ((DdManager *table, int x, int x_high, int initial_size)) [static]
static Move* cuddZddSymmSifting_up ARGS ((DdManager *table, int x, int x_low, int initial_size)) [static]
static int cuddZddSymmSiftingConvAux ARGS ((DdManager *table, int x, int x_low, int x_high)) [static]
AutomaticStart
void Cudd_zddSymmProfile (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Prints statistics on symmetric ZDD variables.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 116 of file cuddZddSymm.c.
References assert, DdManager::invpermZ, DdSubtable::next, DdManager::sizeZ, and DdManager::subtableZ.
int cuddZddSymmCheck (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Checks for symmetry of x and y.]
Description [Checks for symmetry of x and y. Ignores projection functions, unless they are isolated. Returns 1 in case of symmetry; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 171 of file cuddZddSymm.c.
References cuddE, cuddT, empty, DdNode::index, DdManager::invpermZ, DdNode::next, NIL, DdSubtable::nodelist, DdNode::ref, DdSubtable::slots, DdManager::subtableZ, and DdManager::zero.
Referenced by cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), and cuddZddSymmSiftingAux().
int cuddZddSymmSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Symmetric sifting algorithm for ZDDs.]
Description [Symmetric sifting algorithm. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique subtable.
Sift the variable up and down, remembering each time the total size of the ZDD heap and grouping variables that are symmetric.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 plus the number of symmetric variables if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddZddSymmSiftingConv]
Definition at line 275 of file cuddZddSymm.c.
References ALLOC, CUDD_MEMORY_OUT, cuddZddSymmSiftingAux(), cuddZddUniqueCompare(), ddMin, DdManager::errorCode, DdSubtable::keys, DdManager::keysZ, DdSubtable::next, DdManager::permZ, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::sizeZ, DdManager::subtableZ, zdd_entry, and zddTotalNumberSwapping.
Referenced by zddReorderChildren().
static Move* cuddZddSymmSifting_down (DdManager * table, int x, int x_high, int initial_size) [static]
Function********************************************************************
Synopsis [Moves x down until either it reaches the bound (x_high) or the size of the ZDD heap increases too much.]
Description [Moves x down until either it reaches the bound (x_high) or the size of the ZDD heap increases too much. Assumes that x is the bottom of a symmetry group. Checks x for symmetry to the adjacent variables. If symmetry is found, the symmetry group of x is merged with the symmetry group of the other variable. Returns the set of moves in case of success; ZDD_MV_OOM if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 1301 of file cuddZddSymm.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextHigh(), cuddZddSwapInPlace(), cuddZddSymmCheck(), DdManager::maxGrowth, Move::next, DdSubtable::next, Move::size, size, DdManager::subtableZ, Move::x, Move::y, zdd_group_move(), and ZDD_MV_OOM.
Referenced by cuddZddSymmSiftingAux(), and cuddZddSymmSiftingConvAux().
static Move* cuddZddSymmSifting_up (DdManager * table, int x, int x_low, int initial_size) [static]
Function********************************************************************
Synopsis [Moves x up until either it reaches the bound (x_low) or the size of the ZDD heap increases too much.]
Description [Moves x up until either it reaches the bound (x_low) or the size of the ZDD heap increases too much. Assumes that x is the top of a symmetry group. Checks x for symmetry to the adjacent variables. If symmetry is found, the symmetry group of x is merged with the symmetry group of the other variable. Returns the set of moves in case of success; ZDD_MV_OOM if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 1213 of file cuddZddSymm.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextLow(), cuddZddSwapInPlace(), cuddZddSymmCheck(), DdManager::maxGrowth, Move::next, DdSubtable::next, Move::size, size, DdManager::subtableZ, Move::x, Move::y, zdd_group_move(), and ZDD_MV_OOM.
Referenced by cuddZddSymmSiftingAux(), and cuddZddSymmSiftingConvAux().
static int cuddZddSymmSiftingAux (DdManager * table, int x, int x_low, int x_high) [static]
Function********************************************************************
Synopsis [Given x_low <= x <= x_high moves x up and down between the boundaries.]
Description [Given x_low <= x <= x_high moves x up and down between the boundaries. Finds the best position and does the required changes. Assumes that x is not part of a symmetry group. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 572 of file cuddZddSymm.c.
References cuddZddSymmCheck(), cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), cuddZddSymmSiftingBackward(), DdManager::keysZ, DdSubtable::next, result, DdManager::subtableZ, Move::y, and ZDD_MV_OOM.
Referenced by cuddZddSymmSifting(), and cuddZddSymmSiftingConv().
static int cuddZddSymmSiftingBackward (DdManager * table, Move * moves, int size) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the ZDD heap to the position giving the minimum size.]
Description [Given a set of moves, returns the ZDD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1392 of file cuddZddSymm.c.
References Move::next, and Move::size.
Referenced by cuddZddSymmSiftingAux(), and cuddZddSymmSiftingConvAux().
int cuddZddSymmSiftingConv (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Symmetric sifting to convergence algorithm for ZDDs.]
Description [Symmetric sifting to convergence algorithm for ZDDs. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique subtable.
Sift the variable up and down, remembering each time the total size of the ZDD heap and grouping variables that are symmetric.
Select the best permutation.
Repeat 3 and 4 for all variables.
Repeat 1-4 until no further improvement.
Returns 1 plus the number of symmetric variables if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddZddSymmSifting]
Definition at line 396 of file cuddZddSymm.c.
References ALLOC, CUDD_MEMORY_OUT, cuddZddSymmSiftingAux(), cuddZddUniqueCompare(), ddMin, DdManager::errorCode, DdSubtable::keys, DdManager::keysZ, DdSubtable::next, DdManager::permZ, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::sizeZ, DdManager::subtableZ, zdd_entry, and zddTotalNumberSwapping.
Referenced by zddReorderChildren().
static int cuddZddSymmSiftingConvAux (DdManager * table, int x, int x_low, int x_high) [static]
Function********************************************************************
Synopsis [Given x_low <= x <= x_high moves x up and down between the boundaries.]
Description [Given x_low <= x <= x_high moves x up and down between the boundaries. Finds the best position and does the required changes. Assumes that x is either an isolated variable, or it is the bottom of a symmetry group. All symmetries may not have been found, because of exceeded growth limit. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 908 of file cuddZddSymm.c.
References cuddDeallocNode, cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), cuddZddSymmSiftingBackward(), DdManager::keysZ, Move::next, DdSubtable::next, result, DdManager::subtableZ, Move::x, Move::y, and ZDD_MV_OOM.
static void cuddZddSymmSummary (DdManager * table, int lower, int upper, int * symvars, int * symgroups) [static]
Function********************************************************************
Synopsis [Counts numbers of symmetric variables and symmetry groups.]
Description []
SideEffects [None]
Definition at line 1636 of file cuddZddSymm.c.
References assert, DdSubtable::next, and DdManager::subtableZ.
static int zdd_group_move (DdManager * table, int x, int y, Move ** moves) [static]
Function********************************************************************
Synopsis [Swaps two groups.]
Description [Swaps two groups. x is assumed to be the bottom variable of the first group. y is assumed to be the top variable of the second group. Updates the list of moves. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1444 of file cuddZddSymm.c.
References assert, cuddZddSwapInPlace(), DdSubtable::next, size, and DdManager::subtableZ.
Referenced by cuddZddSymmSifting_down(), and cuddZddSymmSifting_up().
static int zdd_group_move_backward (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Undoes the swap of two groups.]
Description [Undoes the swap of two groups. x is assumed to be the bottom variable of the first group. y is assumed to be the top variable of the second group. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1552 of file cuddZddSymm.c.
References assert, cuddZddSwapInPlace(), DdSubtable::next, size, and DdManager::subtableZ.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddSymm.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 67 of file cuddZddSymm.c.
DdNode* empty [static]
Definition at line 74 of file cuddZddSymm.c.
int* zdd_entry
Definition at line 79 of file cuddZddReord.c.
int zddTotalNumberSwapping
Definition at line 81 of file cuddZddReord.c.