cuddSplit.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *selectMintermsFromUniverse ARGS ((DdManager *manager, int *varSeen, double n))
static DdNode *mintermsFromUniverse ARGS ((DdManager *manager, DdNode **vars, int numVars, double n, int index))
static double bddAnnotateMintermCount ARGS ((DdManager *manager, DdNode *node, double max, st_table *table))
DdNode * Cudd_SplitSet (DdManager *manager, DdNode *S, DdNode **xVars, int n, double m)
DdNode * cuddSplitSetRecur (DdManager *manager, st_table *mtable, int *varSeen, DdNode *p, double n, double max, int index)
static DdNode * selectMintermsFromUniverse (DdManager *manager, int *varSeen, double n)
static DdNode * mintermsFromUniverse (DdManager *manager, DdNode **vars, int numVars, double n, int index)
static double bddAnnotateMintermCount (DdManager *manager, DdNode *node, double max, st_table *table)
Function Documentation
static double bddAnnotateMintermCount ARGS ((DdManager *manager, DdNode *node, double max, st_table *table)) [static]
static DdNode* mintermsFromUniverse ARGS ((DdManager *manager, DdNode **vars, int numVars, double n, int index)) [static]
static DdNode* selectMintermsFromUniverse ARGS ((DdManager *manager, int *varSeen, double n)) [static]
AutomaticStart
static double bddAnnotateMintermCount (DdManager * manager, DdNode * node, double max, st_table * table) [static]
Function********************************************************************
Synopsis [Annotates every node in the BDD node with its minterm count.]
Description [Annotates every node in the BDD node with its minterm count. In this function, every node and the minterm count represented by it are stored in a hash table.]
SideEffects [Fills up 'table' with the pair <node,minterm_count>.]
Definition at line 599 of file cuddSplit.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DD_ONE, DdManager::errorCode, FREE, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_SplitSet().
DdNode* Cudd_SplitSet (DdManager * manager, DdNode * S, DdNode ** xVars, int n, double m)
Function********************************************************************
Synopsis [Returns m minterms from a BDD.]
Description [Returns m minterms from a BDD whose support has n variables at most. The procedure tries to create as few extra nodes as possible. The function represented by S depends on at most n of the variables in xVars. Returns a BDD with m minterms of the on-set of S if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 100 of file cuddSplit.c.
References ALLOC, bddAnnotateMintermCount(), CUDD_MEMORY_OUT, Cudd_Not, cuddDeref, cuddRef, cuddSplitSetRecur(), cuddStCountfree(), DD_ONE, DdManager::errorCode, FREE, DdManager::invperm, max, NIL, one, DdManager::reordered, result, selectMintermsFromUniverse(), DdManager::size, size, st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and zero.
DdNode* cuddSplitSetRecur (DdManager * manager, st_table * mtable, int * varSeen, DdNode * p, double n, double max, int index)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_SplitSet.]
Description [Implements the recursive step of Cudd_SplitSet. The procedure recursively traverses the BDD and checks to see if any node satisfies the minterm requirements as specified by 'n'. At any node X, n is compared to the number of minterms in the onset of X's children. If either of the child nodes have exactly n minterms, then that node is returned; else, if n is greater than the onset of one of the child nodes, that node is retained and the difference in the number of minterms is extracted from the other child. In case n minterms can be extracted from constant 1, the algorithm returns the result with at most log(n) nodes.]
SideEffects [The array 'varSeen' is updated at every recursive call to set the variables traversed by the procedure.]
SeeAlso []
Definition at line 215 of file cuddSplit.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddBddIteRecur(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, DdManager::invperm, one, result, selectMintermsFromUniverse(), st_lookup(), and zero.
Referenced by Cudd_SplitSet().
static DdNode* mintermsFromUniverse (DdManager * manager, DdNode ** vars, int numVars, double n, int index) [static]
Function********************************************************************
Synopsis [Recursive procedure to extract n mintems from constant 1.]
Description [Recursive procedure to extract n mintems from constant 1.]
SideEffects [None]
Definition at line 529 of file cuddSplit.c.
References Cudd_Not, Cudd_RecursiveDeref(), cuddBddAndRecur(), cuddBddIteRecur(), cuddDeref, cuddRef, DD_ONE, max, one, result, and zero.
Referenced by selectMintermsFromUniverse().
static DdNode* selectMintermsFromUniverse (DdManager * manager, int * varSeen, double n) [static]
Function********************************************************************
Synopsis [This function prepares an array of variables which have not been encountered so far when traversing the procedure cuddSplitSetRecur.]
Description [This function prepares an array of variables which have not been encountered so far when traversing the procedure cuddSplitSetRecur. This array is then used to extract the required number of minterms from a constant 1. The algorithm guarantees that the size of BDD will be utmost (n).]
SideEffects [None]
Definition at line 466 of file cuddSplit.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), cuddRef, cuddUniqueInter(), DD_ONE, DdManager::errorCode, FREE, mintermsFromUniverse(), one, DdManager::perm, result, DdManager::size, size, and zero.
Referenced by Cudd_SplitSet(), and cuddSplitSetRecur().