cuddAddIte.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static void addVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *one, DdNode *zero))
DdNode * Cudd_addIte (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * Cudd_addIteConstant (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * Cudd_addEvalConst (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_addCmpl (DdManager *dd, DdNode *f)
int Cudd_addLeq (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddAddIteRecur (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * cuddAddCmplRecur (DdManager *dd, DdNode *f)
static void addVarToConst (DdNode *f, DdNode **gp, DdNode **hp, DdNode *one, DdNode *zero)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddIte.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static void addVarToConst (DdNode * f, DdNode ** gp, DdNode ** hp, DdNode * one, DdNode * zero) [static]
Function********************************************************************
Synopsis [Replaces variables with constants if possible (part of canonical form).]
Description []
SideEffects [None]
Definition at line 594 of file cuddAddIte.c.
References one, and zero.
Referenced by Cudd_addIteConstant(), and cuddAddIteRecur().
static void addVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *one, DdNode *zero)) [static]
AutomaticStart
DdNode* Cudd_addCmpl (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Computes the complement of an ADD a la C language.]
Description [Computes the complement of an ADD a la C language: The complement of 0 is 1 and the complement of everything else is 0. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addNegate]
Definition at line 319 of file cuddAddIte.c.
References cuddAddCmplRecur(), and DdManager::reordered.
Referenced by cuddAddCmplRecur().
DdNode* Cudd_addEvalConst (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Checks whether ADD g is constant whenever ADD f is 1.]
Description [Checks whether ADD g is constant whenever ADD f is 1. f must be a 0-1 ADD. Returns a pointer to the resulting ADD (which may or may not be constant) or DD_NON_CONSTANT. If f is identically 0, the check is assumed to be successful, and the background value is returned. No new nodes are created.]
SideEffects [None]
SeeAlso [Cudd_addIteConstant Cudd_addLeq]
Definition at line 230 of file cuddAddIte.c.
References assert, DdManager::background, Cudd_IsComplement, cuddCacheInsert2(), cuddConstantLookup(), cuddE, cuddI, cuddIsConstant, cuddT, DD_NON_CONSTANT, DD_ONE, DD_ZERO, DdNode::index, and zero.
DdNode* Cudd_addIte (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements ITE(f,g,h).]
Description [Implements ITE(f,g,h). This procedure assumes that f is a 0-1 ADD. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addIteConstant Cudd_addApply]
Definition at line 100 of file cuddAddIte.c.
References cuddAddIteRecur(), and DdManager::reordered.
Referenced by addWalshInt(), Cudd_addComputeCube(), Cudd_addRead(), Cudd_addResidue(), Cudd_addTimesPlus(), Cudd_addXeqy(), and cuddAddIteRecur().
DdNode* Cudd_addIteConstant (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements ITEconstant for ADDs.]
Description [Implements ITEconstant for ADDs. f must be a 0-1 ADD. Returns a pointer to the resulting ADD (which may or may not be constant) or DD_NON_CONSTANT. No new nodes are created. This function can be used, for instance, to check that g has a constant value (specified by h) whenever f is 1. If the constant value is unknown, then one should use Cudd_addEvalConst.]
SideEffects [None]
SeeAlso [Cudd_addIte Cudd_addEvalConst Cudd_bddIteConstant]
Definition at line 134 of file cuddAddIte.c.
References addVarToConst(), cuddCacheInsert(), cuddConstantLookup(), cuddE, cuddI, cuddIsConstant, cuddT, DD_NON_CONSTANT, DD_ONE, DD_ZERO, ddMin, DdNode::index, one, and zero.
int Cudd_addLeq (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Determines whether f is less than or equal to g.]
Description [Returns 1 if f is less than or equal to g; 0 otherwise. No new nodes are created. This procedure works for arbitrary ADDs. For 0-1 ADDs Cudd_addEvalConst is more efficient.]
SideEffects [None]
SeeAlso [Cudd_addIteConstant Cudd_addEvalConst Cudd_bddLeq]
Definition at line 347 of file cuddAddIte.c.
References Cudd_IsConstant, Cudd_NotCond, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddI, cuddT, cuddV, DD_MINUS_INFINITY, DD_ONE, DD_PLUS_INFINITY, and DdNode::index.
DdNode* cuddAddCmplRecur (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addCmpl.]
Description [Performs the recursive step of Cudd_addCmpl. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addCmpl]
Definition at line 532 of file cuddAddIte.c.
References Cudd_addCmpl(), Cudd_RecursiveDeref(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, one, and zero.
Referenced by Cudd_addCmpl(), and ddBddToAddRecur().
DdNode* cuddAddIteRecur (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_addIte(f,g,h).]
Description [Implements the recursive step of Cudd_addIte(f,g,h). Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addIte]
Definition at line 416 of file cuddAddIte.c.
References addVarToConst(), Cudd_addIte(), Cudd_RecursiveDeref(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, ddMin, DdNode::index, one, and zero.
Referenced by Cudd_addIte(), cuddAddComposeRecur(), cuddAddPermuteRecur(), and cuddAddVectorComposeRecur().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddIte.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddIte.c]
PackageName [cudd]
Synopsis [ADD ITE function and satellites.]
Description [External procedures included in this module:
Cudd_addIte()
Cudd_addIteConstant()
Cudd_addEvalConst()
Cudd_addCmpl()
Cudd_addLeq()
Internal procedures included in this module:
cuddAddIteRecur()
cuddAddCmplRecur()
Static procedures included in this module:
addVarToConst()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 61 of file cuddAddIte.c.