cuddLCache.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define DD_MAX_HASHTABLE_DENSITY 2
#define ddLCHash2(f, g, shift) ((((unsigned)(f) * DD_P1 + (unsigned)(g)) * DD_P2) >> (shift))
#define ddLCHash3(f, g, h, shift) ddCHash2(f,g,h,shift)
Functions
static void cuddLocalCacheResize ARGS ((DdLocalCache *cache))
static DD_INLINE unsigned int ddLCHash ARGS ((DdNodePtr *key, unsigned int keysize, int shift))
static int cuddHashTableResize ARGS ((DdHashTable *hash))
DdLocalCache * cuddLocalCacheInit (DdManager *manager, unsigned int keySize, unsigned int cacheSize, unsigned int maxCacheSize)
void cuddLocalCacheQuit (DdLocalCache *cache)
void cuddLocalCacheInsert (DdLocalCache *cache, DdNodePtr *key, DdNode *value)
DdNode * cuddLocalCacheLookup (DdLocalCache *cache, DdNodePtr *key)
void cuddLocalCacheClearDead (DdManager *manager)
void cuddLocalCacheClearAll (DdManager *manager)
DdHashTable * cuddHashTableInit (DdManager *manager, unsigned int keySize, unsigned int initSize)
void cuddHashTableQuit (DdHashTable *hash)
int cuddHashTableInsert (DdHashTable *hash, DdNodePtr *key, DdNode *value, ptrint count)
DdNode * cuddHashTableLookup (DdHashTable *hash, DdNodePtr *key)
int cuddHashTableInsert1 (DdHashTable *hash, DdNode *f, DdNode *value, ptrint count)
DdNode * cuddHashTableLookup1 (DdHashTable *hash, DdNode *f)
int cuddHashTableInsert2 (DdHashTable *hash, DdNode *f, DdNode *g, DdNode *value, ptrint count)
DdNode * cuddHashTableLookup2 (DdHashTable *hash, DdNode *f, DdNode *g)
int cuddHashTableInsert3 (DdHashTable *hash, DdNode *f, DdNode *g, DdNode *h, DdNode *value, ptrint count)
DdNode * cuddHashTableLookup3 (DdHashTable *hash, DdNode *f, DdNode *g, DdNode *h)
static void cuddLocalCacheResize (DdLocalCache *cache)
static DD_INLINE unsigned int ddLCHash (DdNodePtr *key, unsigned int keysize, int shift)
static void cuddLocalCacheAddToList (DdLocalCache *cache)
static void cuddLocalCacheRemoveFromList (DdLocalCache *cache)
static int cuddHashTableResize (DdHashTable *hash)
static DD_INLINE DdHashItem * cuddHashTableAlloc (DdHashTable *hash)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddLCache.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define DD_MAX_HASHTABLE_DENSITY 2
CFile***********************************************************************
FileName [cuddLCache.c]
PackageName [cudd]
Synopsis [Functions for local caches.]
Description [Internal procedures included in this module:
cuddLocalCacheInit()
cuddLocalCacheQuit()
cuddLocalCacheInsert()
cuddLocalCacheLookup()
cuddLocalCacheClearDead()
cuddLocalCacheClearAll()
cuddLocalCacheProfile()
cuddHashTableInit()
cuddHashTableQuit()
cuddHashTableInsert()
cuddHashTableLookup()
cuddHashTableInsert2()
cuddHashTableLookup2()
cuddHashTableInsert3()
cuddHashTableLookup3()
Static procedures included in this module:
cuddLocalCacheResize()
ddLCHash()
cuddLocalCacheAddToList()
cuddLocalCacheRemoveFromList()
cuddHashTableResize()
cuddHashTableAlloc()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 57 of file cuddLCache.c.
Referenced by cuddHashTableInit().
#define ddLCHash2(f, g, shift) ((((unsigned)(f) * DD_P1 + (unsigned)(g)) * DD_P2) >> (shift))
Macro***********************************************************************
Synopsis [Computes hash function for keys of two operands.]
Description []
SideEffects [None]
SeeAlso [ddLCHash3 ddLCHash]
Definition at line 97 of file cuddLCache.c.
Referenced by cuddHashTableInsert1(), cuddHashTableInsert2(), cuddHashTableLookup1(), cuddHashTableLookup2(), and cuddHashTableResize().
#define ddLCHash3(f, g, h, shift) ddCHash2(f,g,h,shift)
Macro***********************************************************************
Synopsis [Computes hash function for keys of three operands.]
Description []
SideEffects [None]
SeeAlso [ddLCHash2 ddLCHash]
Definition at line 113 of file cuddLCache.c.
Referenced by cuddHashTableInsert3(), and cuddHashTableLookup3().
Function Documentation
static int cuddHashTableResize ARGS ((DdHashTable *hash)) [static]
static DD_INLINE unsigned int ddLCHash ARGS ((DdNodePtr *key, unsigned int keysize, int shift)) [static]
static void cuddLocalCacheResize ARGS ((DdLocalCache *cache)) [static]
AutomaticStart
static DD_INLINE DdHashItem* cuddHashTableAlloc (DdHashTable * hash) [static]
Function********************************************************************
Synopsis [Fast storage allocation for DdNodes in the table.]
Description [Fast storage allocation for DdNodes in the table. The first 4 bytes of a chunk contain a pointer to the next block; the rest contains DD_MEM_CHUNK spaces for DdNodes. Returns a pointer to a new node if successful; NULL is memory is full.]
SideEffects [None]
SeeAlso [cuddDynamicAllocNode]
Definition at line 1366 of file cuddLCache.c.
References ALLOC, CUDD_MEMORY_OUT, DD_MEM_CHUNK, DdManager::errorCode, DdHashTable::itemsize, DdHashTable::manager, DdHashTable::memoryList, DdHashItem::next, and DdHashTable::nextFree.
Referenced by cuddHashTableInsert(), cuddHashTableInsert1(), cuddHashTableInsert2(), and cuddHashTableInsert3().
DdHashTable* cuddHashTableInit (DdManager * manager, unsigned int keySize, unsigned int initSize)
Function********************************************************************
Synopsis [Initializes a hash table.]
Description [Initializes a hash table. Returns a pointer to the new table if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddHashTableQuit]
Definition at line 513 of file cuddLCache.c.
References ALLOC, DdHashTable::bucket, CUDD_MEMORY_OUT, cuddComputeFloorLog2(), DD_MAX_HASHTABLE_DENSITY, DdManager::errorCode, FREE, DdHashTable::itemsize, DdHashTable::keysize, DdHashTable::manager, DdHashTable::maxsize, DdHashTable::memoryList, memset(), DdHashTable::nextFree, DdHashTable::numBuckets, DdHashTable::shift, and DdHashTable::size.
Referenced by Cudd_addPermute(), Cudd_addVectorCompose(), Cudd_bddPermute(), and Cudd_bddVectorCompose().
int cuddHashTableInsert (DdHashTable * hash, DdNodePtr * key, DdNode * value, ptrint count)
Function********************************************************************
Synopsis [Inserts an item in a hash table.]
Description [Inserts an item in a hash table when the key has more than three pointers. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [[cuddHashTableInsert1 cuddHashTableInsert2 cuddHashTableInsert3 cuddHashTableLookup]
Definition at line 623 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddHashTableAlloc(), cuddHashTableResize(), cuddRef, ddLCHash(), DdHashItem::key, DdHashTable::keysize, DdHashTable::maxsize, DdHashItem::next, result, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
int cuddHashTableInsert1 (DdHashTable * hash, DdNode * f, DdNode * value, ptrint count)
Function********************************************************************
Synopsis [Inserts an item in a hash table.]
Description [Inserts an item in a hash table when the key is one pointer. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddHashTableInsert cuddHashTableInsert2 cuddHashTableInsert3 cuddHashTableLookup1]
Definition at line 742 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddHashTableAlloc(), cuddHashTableResize(), cuddRef, ddLCHash2, DdHashItem::key, DdHashTable::keysize, DdHashTable::maxsize, DdHashItem::next, result, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
Referenced by cuddAddPermuteRecur(), cuddAddVectorComposeRecur(), cuddBddPermuteRecur(), and cuddBddVectorComposeRecur().
int cuddHashTableInsert2 (DdHashTable * hash, DdNode * f, DdNode * g, DdNode * value, ptrint count)
Function********************************************************************
Synopsis [Inserts an item in a hash table.]
Description [Inserts an item in a hash table when the key is composed of two pointers. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddHashTableInsert cuddHashTableInsert1 cuddHashTableInsert3 cuddHashTableLookup2]
Definition at line 849 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddHashTableAlloc(), cuddHashTableResize(), cuddRef, ddLCHash2, DdHashItem::key, DdHashTable::keysize, DdHashTable::maxsize, DdHashItem::next, result, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
int cuddHashTableInsert3 (DdHashTable * hash, DdNode * f, DdNode * g, DdNode * h, DdNode * value, ptrint count)
Function********************************************************************
Synopsis [Inserts an item in a hash table.]
Description [Inserts an item in a hash table when the key is composed of three pointers. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddHashTableInsert cuddHashTableInsert1 cuddHashTableInsert2 cuddHashTableLookup3]
Definition at line 959 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddHashTableAlloc(), cuddHashTableResize(), cuddRef, ddLCHash3, DdHashItem::key, DdHashTable::keysize, DdHashTable::maxsize, DdHashItem::next, result, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
DdNode* cuddHashTableLookup (DdHashTable * hash, DdNodePtr * key)
Function********************************************************************
Synopsis [Looks up a key in a hash table.]
Description [Looks up a key consisting of more than three pointers in a hash table. Returns the value associated to the key if there is an entry for the given key in the table; NULL otherwise. If the entry is present, its reference counter is decremented if not saturated. If the counter reaches 0, the value of the entry is dereferenced, and the entry is returned to the free list.]
SideEffects [None]
SeeAlso [cuddHashTableLookup1 cuddHashTableLookup2 cuddHashTableLookup3 cuddHashTableInsert]
Definition at line 678 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddDeref, cuddSatDec, ddLCHash(), DdHashItem::key, DdHashTable::keysize, DdHashItem::next, DdHashTable::nextFree, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
DdNode* cuddHashTableLookup1 (DdHashTable * hash, DdNode * f)
Function********************************************************************
Synopsis [Looks up a key consisting of one pointer in a hash table.]
Description [Looks up a key consisting of one pointer in a hash table. Returns the value associated to the key if there is an entry for the given key in the table; NULL otherwise. If the entry is present, its reference counter is decremented if not saturated. If the counter reaches 0, the value of the entry is dereferenced, and the entry is returned to the free list.]
SideEffects [None]
SeeAlso [cuddHashTableLookup cuddHashTableLookup2 cuddHashTableLookup3 cuddHashTableInsert1]
Definition at line 794 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddDeref, cuddSatDec, ddLCHash2, DdHashItem::key, DdHashTable::keysize, DdHashItem::next, DdHashTable::nextFree, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
Referenced by cuddAddPermuteRecur(), cuddAddVectorComposeRecur(), cuddBddPermuteRecur(), and cuddBddVectorComposeRecur().
DdNode* cuddHashTableLookup2 (DdHashTable * hash, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Looks up a key consisting of two pointers in a hash table.]
Description [Looks up a key consisting of two pointer in a hash table. Returns the value associated to the key if there is an entry for the given key in the table; NULL otherwise. If the entry is present, its reference counter is decremented if not saturated. If the counter reaches 0, the value of the entry is dereferenced, and the entry is returned to the free list.]
SideEffects [None]
SeeAlso [cuddHashTableLookup cuddHashTableLookup1 cuddHashTableLookup3 cuddHashTableInsert2]
Definition at line 903 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddDeref, cuddSatDec, ddLCHash2, DdHashItem::key, DdHashTable::keysize, DdHashItem::next, DdHashTable::nextFree, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
DdNode* cuddHashTableLookup3 (DdHashTable * hash, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Looks up a key consisting of three pointers in a hash table.]
Description [Looks up a key consisting of three pointers in a hash table. Returns the value associated to the key if there is an entry for the given key in the table; NULL otherwise. If the entry is present, its reference counter is decremented if not saturated. If the counter reaches 0, the value of the entry is dereferenced, and the entry is returned to the free list.]
SideEffects [None]
SeeAlso [cuddHashTableLookup cuddHashTableLookup1 cuddHashTableLookup2 cuddHashTableInsert3]
Definition at line 1015 of file cuddLCache.c.
References assert, DdHashTable::bucket, DdHashItem::count, cuddDeref, cuddSatDec, ddLCHash3, DdHashItem::key, DdHashTable::keysize, DdHashItem::next, DdHashTable::nextFree, DdHashTable::shift, DdHashTable::size, and DdHashItem::value.
void cuddHashTableQuit (DdHashTable * hash)
Function********************************************************************
Synopsis [Shuts down a hash table.]
Description [Shuts down a hash table, dereferencing all the values.]
SideEffects [None]
SeeAlso [cuddHashTableInit]
Definition at line 570 of file cuddLCache.c.
References DdHashTable::bucket, Cudd_RecursiveDeref(), FREE, DdHashTable::manager, DdHashTable::memoryList, DdHashItem::next, DdHashTable::numBuckets, and DdHashItem::value.
Referenced by Cudd_addPermute(), Cudd_addVectorCompose(), Cudd_bddPermute(), and Cudd_bddVectorCompose().
static int cuddHashTableResize (DdHashTable * hash) [static]
Function********************************************************************
Synopsis [Resizes a hash table.]
Description [Resizes a hash table. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddHashTableInsert]
Definition at line 1251 of file cuddLCache.c.
References ALLOC, DdHashTable::bucket, Cudd_OutOfMem(), ddLCHash2, DdHashItem::key, DdHashTable::keysize, DdHashTable::maxsize, memset(), MMoutOfMemory, DdHashItem::next, DdHashTable::numBuckets, and DdHashTable::shift.
Referenced by cuddHashTableInsert(), cuddHashTableInsert1(), cuddHashTableInsert2(), and cuddHashTableInsert3().
static void cuddLocalCacheAddToList (DdLocalCache * cache) [static]
Function********************************************************************
Synopsis [Inserts a local cache in the manager list.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1185 of file cuddLCache.c.
References DdManager::localCaches, DdLocalCache::manager, and DdLocalCache::next.
Referenced by cuddLocalCacheInit().
void cuddLocalCacheClearAll (DdManager * manager)
Function********************************************************************
Synopsis [Clears the local caches of a manager.]
Description [Clears the local caches of a manager. Used before reordering.]
SideEffects [None]
SeeAlso []
Definition at line 380 of file cuddLCache.c.
References DdLocalCache::item, DdLocalCache::itemsize, DdManager::localCaches, memset(), DdLocalCache::next, and DdLocalCache::slots.
Referenced by ddReorderPreprocess().
void cuddLocalCacheClearDead (DdManager * manager)
Function********************************************************************
Synopsis [Clears the dead entries of the local caches of a manager.]
Description [Clears the dead entries of the local caches of a manager. Used during garbage collection.]
SideEffects [None]
SeeAlso []
Definition at line 323 of file cuddLCache.c.
References Cudd_Regular, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCacheItem::key, DdLocalCache::keysize, DdManager::localCaches, DdLocalCache::next, DdLocalCache::slots, and DdLocalCacheItem::value.
DdLocalCache* cuddLocalCacheInit (DdManager * manager, unsigned int keySize, unsigned int cacheSize, unsigned int maxCacheSize)
Function********************************************************************
Synopsis [Initializes a local computed table.]
Description [Initializes a computed table. Returns a pointer the the new local cache in case of success; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddInitCache]
Definition at line 154 of file cuddLCache.c.
References ALLOC, CUDD_MEMORY_OUT, cuddComputeFloorLog2(), cuddLocalCacheAddToList(), ddMax, ddMin, DdManager::errorCode, FREE, DdLocalCache::hits, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCache::keysize, DdLocalCache::lookUps, DdLocalCache::manager, DdLocalCache::maxslots, memset(), DdManager::memused, DdManager::minHit, DdLocalCache::minHit, DdLocalCache::shift, DdLocalCache::slots, and DdManager::slots.
void cuddLocalCacheInsert (DdLocalCache * cache, DdNodePtr * key, DdNode * value)
Function********************************************************************
Synopsis [Inserts a result in a local cache.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 243 of file cuddLCache.c.
References ddLCHash(), entry, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCache::keysize, memcpy(), and DdLocalCache::shift.
DdNode* cuddLocalCacheLookup (DdLocalCache * cache, DdNodePtr * key)
Function********************************************************************
Synopsis [Looks up in a local cache.]
Description [Looks up in a local cache. Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso []
Definition at line 276 of file cuddLCache.c.
References Cudd_Regular, cuddLocalCacheResize(), cuddReclaim(), ddLCHash(), entry, DdLocalCache::hits, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCache::keysize, DdLocalCache::lookUps, DdLocalCache::manager, DdLocalCache::maxslots, memcmp(), DdLocalCache::minHit, DdNode::ref, DdLocalCache::shift, and DdLocalCache::slots.
void cuddLocalCacheQuit (DdLocalCache * cache)
Function********************************************************************
Synopsis [Shuts down a local computed table.]
Description [Initializes the computed table. It is called by Cudd_Init. Returns a pointer the the new local cache in case of success; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddLocalCacheInit]
Definition at line 217 of file cuddLCache.c.
References cuddLocalCacheRemoveFromList(), FREE, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCache::manager, DdManager::memused, and DdLocalCache::slots.
static void cuddLocalCacheRemoveFromList (DdLocalCache * cache) [static]
Function********************************************************************
Synopsis [Removes a local cache from the manager list.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1209 of file cuddLCache.c.
References DdManager::localCaches, DdLocalCache::manager, and DdLocalCache::next.
Referenced by cuddLocalCacheQuit().
static void cuddLocalCacheResize (DdLocalCache * cache) [static]
Function********************************************************************
Synopsis [Resizes a local cache.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1075 of file cuddLCache.c.
References ALLOC, Cudd_OutOfMem(), ddLCHash(), entry, DdLocalCache::hits, DdLocalCache::item, DdLocalCache::itemsize, DdLocalCacheItem::key, DdLocalCache::keysize, DdLocalCache::lookUps, DdLocalCache::manager, DdLocalCache::maxslots, memcpy(), memset(), DdManager::memused, MMoutOfMemory, DdLocalCache::shift, DdLocalCache::slots, and DdLocalCacheItem::value.
Referenced by cuddLocalCacheLookup().
static DD_INLINE unsigned int ddLCHash (DdNodePtr * key, unsigned int keysize, int shift) [static]
Function********************************************************************
Synopsis [Computes the hash value for a local cache.]
Description [Computes the hash value for a local cache. Returns the bucket index.]
SideEffects [None]
SeeAlso []
Definition at line 1156 of file cuddLCache.c.
References DD_P1.
Referenced by cuddHashTableInsert(), cuddHashTableLookup(), cuddLocalCacheInsert(), cuddLocalCacheLookup(), and cuddLocalCacheResize().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddLCache.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 74 of file cuddLCache.c.