cuddZddMisc.c File Reference
#include <config.h>
#include <math.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static int cuddZddDagInt ARGS ((DdNode *n, st_table *tab))
int Cudd_zddDagSize (DdNode *p_node)
double Cudd_zddCountMinterm (DdManager *zdd, DdNode *node, int path)
void Cudd_zddPrintSubtable (DdManager *table)
static int cuddZddDagInt (DdNode *n, st_table *tab)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddMisc.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int cuddZddDagInt ARGS ((DdNode *n, st_table *tab)) [static]
AutomaticStart
double Cudd_zddCountMinterm (DdManager * zdd, DdNode * node, int path)
Function********************************************************************
Synopsis [Counts the number of minterms of a ZDD.]
Description [Counts the number of minterms of the ZDD rooted at node. This procedure takes a parameter path that specifies how many variables are in the support of the function.]
SideEffects [None]
SeeAlso [Cudd_zddCountDouble]
Definition at line 129 of file cuddZddMisc.c.
References Cudd_zddCountDouble(), and DdManager::sizeZ.
Referenced by Cudd_zddPrintDebug().
int Cudd_zddDagSize (DdNode * p_node)
Function********************************************************************
Synopsis [Counts the number of nodes in a ZDD.]
Description [Counts the number of nodes in a ZDD. This function duplicates Cudd_DagSize and is only retained for compatibility.]
SideEffects [None]
SeeAlso [Cudd_DagSize]
Definition at line 99 of file cuddZddMisc.c.
References cuddZddDagInt(), st_free_table(), st_init_table(), st_ptrcmp(), and st_ptrhash().
Referenced by Cudd_zddPrintDebug().
void Cudd_zddPrintSubtable (DdManager * table)
Function********************************************************************
Synopsis [Prints the ZDD table.]
Description [Prints the ZDD table for debugging purposes.]
SideEffects [None]
SeeAlso []
Definition at line 155 of file cuddZddMisc.c.
References Cudd_E, Cudd_IsConstant, Cudd_T, DdNode::index, DdNode::next, NIL, DdSubtable::nodelist, DdManager::one, DdNode::ref, DdManager::sizeZ, DdSubtable::slots, and DdManager::subtableZ.
static int cuddZddDagInt (DdNode * n, st_table * tab) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddDagSize.]
Description [Performs the recursive step of Cudd_zddDagSize. Does not check for out-of-memory conditions.]
SideEffects [None]
SeeAlso []
Definition at line 236 of file cuddZddMisc.c.
References Cudd_E, Cudd_IsConstant, Cudd_T, NIL, st_insert(), and st_is_member.
Referenced by Cudd_zddDagSize().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddMisc.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddMisc.c]
PackageName [cudd]
Synopsis [.]
Description [External procedures included in this module:
Cudd_zddDagSize()
Cudd_zddCountMinterm()
Cudd_zddPrintSubtable()
Internal procedures included in this module:
Static procedures included in this module:
cuddZddDagInt()
]
SeeAlso []
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 62 of file cuddZddMisc.c.