cuddAddFind.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *addDoIthBit ARGS ((DdManager *dd, DdNode *f, DdNode *index))
DdNode * Cudd_addFindMax (DdManager *dd, DdNode *f)
DdNode * Cudd_addFindMin (DdManager *dd, DdNode *f)
DdNode * Cudd_addIthBit (DdManager *dd, DdNode *f, int bit)
static DdNode * addDoIthBit (DdManager *dd, DdNode *f, DdNode *index)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddFind.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* addDoIthBit (DdManager * dd, DdNode * f, DdNode * index) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addIthBit.]
Description [Performs the recursive step for Cudd_addIthBit. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 231 of file cuddAddFind.c.
References Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), cuddV, DD_ONE, DD_ZERO, DdNode::index, and DdGen::value.
Referenced by Cudd_addIthBit().
static DdNode* addDoIthBit ARGS ((DdManager *dd, DdNode *f, DdNode *index)) [static]
AutomaticStart
DdNode* Cudd_addFindMax (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Finds the maximum discriminant of f.]
Description [Returns a pointer to a constant ADD.]
SideEffects [None]
Definition at line 89 of file cuddAddFind.c.
References cuddCacheInsert1(), cuddCacheLookup1(), cuddE, cuddIsConstant, cuddT, cuddV, and DD_PLUS_INFINITY.
DdNode* Cudd_addFindMin (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Finds the minimum discriminant of f.]
Description [Returns a pointer to a constant ADD.]
SideEffects [None]
Definition at line 128 of file cuddAddFind.c.
References cuddCacheInsert1(), cuddCacheLookup1(), cuddE, cuddIsConstant, cuddT, cuddV, and DD_MINUS_INFINITY.
DdNode* Cudd_addIthBit (DdManager * dd, DdNode * f, int bit)
Function********************************************************************
Synopsis [Extracts the i-th bit from an ADD.]
Description [Produces an ADD from another ADD by replacing all discriminants whose i-th bit is equal to 1 with 1, and all other discriminants with 0. The i-th bit refers to the integer representation of the leaf value. If the value is has a fractional part, it is ignored. Repeated calls to this procedure allow one to transform an integer-valued ADD into an array of ADDs, one for each bit of the leaf values. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddIthBit]
Definition at line 176 of file cuddAddFind.c.
References addDoIthBit(), Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddDeref, cuddRef, cuddUniqueConst(), and DdManager::reordered.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddFind.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddFind.c]
PackageName [cudd]
Synopsis [Functions to find maximum and minimum in an ADD and to extract the i-th bit.]
Description [External procedures included in this module:
Cudd_addFindMax()
Cudd_addFindMin()
Cudd_addIthBit()
Static functions included in this module:
addDoIthBit()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 55 of file cuddAddFind.c.