cuddZddSetop.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *zdd_subset1_aux ARGS ((DdManager *zdd, DdNode *P, DdNode *zvar))
static void zddVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *base, DdNode *empty))
DdNode * Cudd_zddIte (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * Cudd_zddUnion (DdManager *dd, DdNode *P, DdNode *Q)
DdNode * Cudd_zddIntersect (DdManager *dd, DdNode *P, DdNode *Q)
DdNode * Cudd_zddDiff (DdManager *dd, DdNode *P, DdNode *Q)
DdNode * Cudd_zddDiffConst (DdManager *zdd, DdNode *P, DdNode *Q)
DdNode * Cudd_zddSubset1 (DdManager *dd, DdNode *P, int var)
DdNode * Cudd_zddSubset0 (DdManager *dd, DdNode *P, int var)
DdNode * Cudd_zddChange (DdManager *dd, DdNode *P, int var)
DdNode * cuddZddIte (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * cuddZddUnion (DdManager *zdd, DdNode *P, DdNode *Q)
DdNode * cuddZddIntersect (DdManager *zdd, DdNode *P, DdNode *Q)
DdNode * cuddZddDiff (DdManager *zdd, DdNode *P, DdNode *Q)
DdNode * cuddZddChangeAux (DdManager *zdd, DdNode *P, DdNode *zvar)
DdNode * cuddZddSubset1 (DdManager *dd, DdNode *P, int var)
DdNode * cuddZddSubset0 (DdManager *dd, DdNode *P, int var)
DdNode * cuddZddChange (DdManager *dd, DdNode *P, int var)
static DdNode * zdd_subset1_aux (DdManager *zdd, DdNode *P, DdNode *zvar)
static DdNode * zdd_subset0_aux (DdManager *zdd, DdNode *P, DdNode *zvar)
static void zddVarToConst (DdNode *f, DdNode **gp, DdNode **hp, DdNode *base, DdNode *empty)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddSetop.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static void zddVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *base, DdNode *empty)) [static]
static DdNode* zdd_subset1_aux ARGS ((DdManager *zdd, DdNode *P, DdNode *zvar)) [static]
AutomaticStart
DdNode* Cudd_zddChange (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Substitutes a variable with its complement in a ZDD.]
Description [Substitutes a variable with its complement in a ZDD. returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 356 of file cuddZddSetop.c.
References CUDD_MAXINDEX, cuddZddChange(), and DdManager::reordered.
DdNode* Cudd_zddDiff (DdManager * dd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Computes the difference of two ZDDs.]
Description [Computes the difference of two ZDDs. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddDiffConst]
Definition at line 201 of file cuddZddSetop.c.
References cuddZddDiff(), and DdManager::reordered.
DdNode* Cudd_zddDiffConst (DdManager * zdd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Performs the inclusion test for ZDDs (P implies Q).]
Description [Inclusion test for ZDDs (P implies Q). No new nodes are generated by this procedure. Returns empty if true; a valid pointer different from empty or DD_NON_CONSTANT otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddDiff]
Definition at line 231 of file cuddZddSetop.c.
References cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddE, cuddIsConstant, cuddT, cuddZddDiff(), DD_NON_CONSTANT, DD_ZERO, empty, DdNode::index, and DdManager::permZ.
DdNode* Cudd_zddIntersect (DdManager * dd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Computes the intersection of two ZDDs.]
Description [Computes the intersection of two ZDDs. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 172 of file cuddZddSetop.c.
References cuddZddIntersect(), and DdManager::reordered.
DdNode* Cudd_zddIte (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Computes the ITE of three ZDDs.]
Description [Computes the ITE of three ZDDs. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 113 of file cuddZddSetop.c.
References cuddZddIte(), and DdManager::reordered.
Referenced by cuddZddIte().
DdNode* Cudd_zddSubset0 (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Computes the negative cofactor of a ZDD w.r.t. a variable.]
Description [Computes the negative cofactor of a ZDD w.r.t. a variable. In terms of combinations, the result is the set of all combinations in which the variable is negated. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddSubset1]
Definition at line 326 of file cuddZddSetop.c.
References cuddZddSubset0(), and DdManager::reordered.
DdNode* Cudd_zddSubset1 (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Computes the positive cofactor of a ZDD w.r.t. a variable.]
Description [Computes the positive cofactor of a ZDD w.r.t. a variable. In terms of combinations, the result is the set of all combinations in which the variable is asserted. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddSubset0]
Definition at line 294 of file cuddZddSetop.c.
References cuddZddSubset1(), and DdManager::reordered.
DdNode* Cudd_zddUnion (DdManager * dd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Computes the union of two ZDDs.]
Description [Computes the union of two ZDDs. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 143 of file cuddZddSetop.c.
References cuddZddUnion(), and DdManager::reordered.
DdNode* cuddZddChange (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Substitutes a variable with its complement in a ZDD.]
Description [Substitutes a variable with its complement in a ZDD. returns a pointer to the result if successful; NULL otherwise. cuddZddChange performs the same function as Cudd_zddChange, but does not restart if reordering has taken place. Therefore it can be called from within a recursive procedure.]
SideEffects [None]
SeeAlso [Cudd_zddChange]
Definition at line 930 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), cuddZddChangeAux(), DD_ONE, and DD_ZERO.
Referenced by Cudd_zddChange().
DdNode* cuddZddChangeAux (DdManager * zdd, DdNode * P, DdNode * zvar)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddChange.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 759 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddRef, cuddT, cuddZddGetNode(), DD_ONE, DD_ZERO, empty, DdNode::index, and DdManager::permZ.
Referenced by cuddZddChange().
DdNode* cuddZddDiff (DdManager * zdd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddDiff.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 678 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddZddGetNode(), DD_NON_CONSTANT, DD_ZERO, empty, DdNode::index, and DdManager::permZ.
Referenced by Cudd_zddDiff(), and Cudd_zddDiffConst().
DdNode* cuddZddIntersect (DdManager * zdd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddIntersect.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 604 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddZddGetNode(), DD_ZERO, empty, DdNode::index, and DdManager::permZ.
Referenced by Cudd_zddIntersect(), cuddZddDivide(), cuddZddDivideF(), cuddZddWeakDiv(), and cuddZddWeakDivF().
DdNode* cuddZddIte (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddIte.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 391 of file cuddZddSetop.c.
References CUDD_MAXINDEX, Cudd_RecursiveDerefZdd(), Cudd_zddIte(), cuddCacheInsert(), cuddCacheLookupZdd(), cuddDeref, cuddE, cuddIZ, cuddRef, cuddT, cuddZddGetNode(), DD_ONE, DD_ZERO, ddMin, empty, DdNode::index, DdManager::univ, and zddVarToConst().
Referenced by Cudd_zddIte().
DdNode* cuddZddSubset0 (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Computes the negative cofactor of a ZDD w.r.t. a variable.]
Description [Computes the negative cofactor of a ZDD w.r.t. a variable. In terms of combinations, the result is the set of all combinations in which the variable is negated. Returns a pointer to the result if successful; NULL otherwise. cuddZddSubset0 performs the same function as Cudd_zddSubset0, but does not restart if reordering has taken place. Therefore it can be called from within a recursive procedure.]
SideEffects [None]
SeeAlso [cuddZddSubset1 Cudd_zddSubset0]
Definition at line 882 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), DD_ONE, DD_ZERO, empty, and zdd_subset0_aux().
Referenced by Cudd_zddSubset0(), cuddZddGetCofactors2(), and cuddZddGetCofactors3().
DdNode* cuddZddSubset1 (DdManager * dd, DdNode * P, int var)
Function********************************************************************
Synopsis [Computes the positive cofactor of a ZDD w.r.t. a variable.]
Description [Computes the positive cofactor of a ZDD w.r.t. a variable. In terms of combinations, the result is the set of all combinations in which the variable is asserted. Returns a pointer to the result if successful; NULL otherwise. cuddZddSubset1 performs the same function as Cudd_zddSubset1, but does not restart if reordering has taken place. Therefore it can be called from within a recursive procedure.]
SideEffects [None]
SeeAlso [cuddZddSubset0 Cudd_zddSubset1]
Definition at line 833 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), DD_ONE, DD_ZERO, empty, and zdd_subset1_aux().
Referenced by Cudd_zddSubset1(), cuddZddGetCofactors2(), and cuddZddGetCofactors3().
DdNode* cuddZddUnion (DdManager * zdd, DdNode * P, DdNode * Q)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddUnion.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 516 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddZddGetNode(), DD_ZERO, empty, and DdManager::permZ.
Referenced by Cudd_zddUnion(), cuddZddGetNodeIVO(), cuddZddProduct(), and cuddZddUnateProduct().
static DdNode* zdd_subset0_aux (DdManager * zdd, DdNode * P, DdNode * zvar) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddSubset0.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1040 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddZddGetNode(), DD_ONE, DD_ZERO, empty, DdNode::index, and DdManager::permZ.
Referenced by cuddZddSubset0().
static DdNode* zdd_subset1_aux (DdManager * zdd, DdNode * P, DdNode * zvar) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddSubset1.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 971 of file cuddZddSetop.c.
References Cudd_RecursiveDerefZdd(), cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddZddGetNode(), DD_ONE, DD_ZERO, empty, DdNode::index, and DdManager::permZ.
Referenced by cuddZddSubset1().
static void zddVarToConst (DdNode * f, DdNode ** gp, DdNode ** hp, DdNode * base, DdNode * empty) [static]
Function********************************************************************
Synopsis [Replaces variables with constants if possible (part of canonical form).]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1112 of file cuddZddSetop.c.
References empty.
Referenced by cuddZddIte().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddSetop.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddSetop.c]
PackageName [cudd]
Synopsis [Set operations on ZDDs.]
Description [External procedures included in this module:
Cudd_zddIte()
Cudd_zddUnion()
Cudd_zddIntersect()
Cudd_zddDiff()
Cudd_zddDiffConst()
Cudd_zddSubset1()
Cudd_zddSubset0()
Cudd_zddChange()
Internal procedures included in this module:
cuddZddIte()
cuddZddUnion()
cuddZddIntersect()
cuddZddDiff()
cuddZddChangeAux()
cuddZddSubset1()
cuddZddSubset0()
Static procedures included in this module:
zdd_subset1_aux()
zdd_subset0_aux()
zddVarToConst()
]
SeeAlso []
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 74 of file cuddZddSetop.c.