cuddUtil.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct DdGen
Defines
#define CUDD_GEN_CUBES 0
#define CUDD_GEN_NODES 1
#define CUDD_GEN_EMPTY 0
#define CUDD_GEN_NONEMPTY 1
#define MODULUS1 2147483563
#define LEQA1 40014
#define LEQQ1 53668
#define LEQR1 12211
#define MODULUS2 2147483399
#define LEQA2 40692
#define LEQQ2 52774
#define LEQR2 3791
#define STAB_SIZE 64
#define STAB_DIV (1 + (MODULUS1 - 1) / STAB_SIZE)
#define bang(f) ((Cudd_IsComplement(f)) ? '!' : ' ')
Functions
static int dp2 ARGS ((DdNode *f, st_table *t))
static void ddPrintMintermAux ARGS ((DdManager *dd, DdNode *node, int *list))
static int ddDagInt ARGS ((DdNode *n))
static int cuddEstimateCofactor ARGS ((DdManager *dd, st_table *table, DdNode *node, int i, int phase, DdNode **ptr))
static DdNode *cuddUniqueLookup ARGS ((DdManager *unique, intindex, DdNode *T, DdNode *E))
static int cuddEstimateCofactorSimple ARGS ((DdNode *node, int i))
static double ddCountMintermAux ARGS ((DdNode *node, double max, st_table *table))
static double ddCountPathAux ARGS ((DdNode *node, st_table *table))
static void ddSupportStep ARGS ((DdNode *f, int *support))
static void ddClearFlag ARGS ((DdNode *f))
static int ddPickArbitraryMinterms ARGS ((DdManager *dd, DdNode *node, int nvars, int nminterms, char **string))
int Cudd_PrintMinterm (DdManager *manager, DdNode *node)
int Cudd_PrintDebug (DdManager *dd, DdNode *f, int n, int pr)
int Cudd_DagSize (DdNode *node)
int Cudd_EstimateCofactor (DdManager *dd, DdNode *f, int i, int phase)
int Cudd_EstimateCofactorSimple (DdNode *node, int i)
int Cudd_SharingSize (DdNode **nodeArray, int n)
double Cudd_CountMinterm (DdManager *manager, DdNode *node, int nvars)
double Cudd_CountPath (DdNode *node)
DdNode * Cudd_Support (DdManager *dd, DdNode *f)
int Cudd_SupportSize (DdManager *dd, DdNode *f)
DdNode * Cudd_VectorSupport (DdManager *dd, DdNode **F, int n)
int Cudd_VectorSupportSize (DdManager *dd, DdNode **F, int n)
int Cudd_ClassifySupport (DdManager *dd, DdNode *f, DdNode *g, DdNode **common, DdNode **onlyF, DdNode **onlyG)
int Cudd_CountLeaves (DdNode *node)
int Cudd_bddPickOneCube (DdManager *ddm, DdNode *node, char *string)
DdNode * Cudd_bddPickOneMinterm (DdManager *dd, DdNode *f, DdNode **vars, int n)
DdNode ** Cudd_bddPickArbitraryMinterms (DdManager *dd, DdNode *f, DdNode **vars, int n, int k)
DdGen * Cudd_FirstCube (DdManager *dd, DdNode *f, int **cube, CUDD_VALUE_TYPE *value)
int Cudd_NextCube (DdGen *gen, int **cube, CUDD_VALUE_TYPE *value)
DdNode * Cudd_bddComputeCube (DdManager *dd, DdNode **vars, int *phase, int n)
DdNode * Cudd_addComputeCube (DdManager *dd, DdNode **vars, int *phase, int n)
DdGen * Cudd_FirstNode (DdManager *dd, DdNode *f, DdNode **node)
int Cudd_NextNode (DdGen *gen, DdNode **node)
int Cudd_GenFree (DdGen *gen)
int Cudd_IsGenEmpty (DdGen *gen)
DdNode * Cudd_IndicesToCube (DdManager *dd, int *array, int n)
void Cudd_PrintVersion (FILE *fp)
double Cudd_AverageDistance (DdManager *dd)
long Cudd_Random ()
void Cudd_Srandom (long seed)
double Cudd_Density (DdManager *dd, DdNode *f, int nvars)
void Cudd_OutOfMem (long size)
int cuddP (DdManager *dd, DdNode *f)
enum st_retval cuddStCountfree (char *key, char *value, char *arg)
int cuddCollectNodes (DdNode *f, st_table *visited)
static int dp2 (DdNode *f, st_table *t)
static void ddPrintMintermAux (DdManager *dd, DdNode *node, int *list)
static int ddDagInt (DdNode *n)
static int cuddEstimateCofactor (DdManager *dd, st_table *table, DdNode *node, int i, int phase, DdNode **ptr)
static DdNode * cuddUniqueLookup (DdManager *unique, int index, DdNode *T, DdNode *E)
static int cuddEstimateCofactorSimple (DdNode *node, int i)
static double ddCountMintermAux (DdNode *node, double max, st_table *table)
static double ddCountPathAux (DdNode *node, st_table *table)
static void ddSupportStep (DdNode *f, int *support)
static void ddClearFlag (DdNode *f)
static int ddLeavesInt (DdNode *n)
static int ddPickArbitraryMinterms (DdManager *dd, DdNode *node, int nvars, int nminterms, char **string)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddUtil.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static DdNode * background
static DdNode * zero
static long cuddRand = 0
static long cuddRand2
static long shuffleSelect
static long shuffleTable [STAB_SIZE]
Define Documentation
#define bang(f) ((Cudd_IsComplement(f)) ? '!' : ' ')
Definition at line 149 of file cuddUtil.c.
Referenced by dp2().
#define CUDD_GEN_CUBES 0
CFile***********************************************************************
FileName [cuddUtil.c]
PackageName [cudd]
Synopsis [Utility functions.]
Description [External procedures included in this module:
Cudd_PrintMinterm()
Cudd_PrintDebug()
Cudd_DagSize()
Cudd_EstimateCofactor()
Cudd_EstimateCofactorSimple()
Cudd_SharingSize()
Cudd_CountMinterm()
Cudd_CountPath()
Cudd_Support()
Cudd_SupportSize()
Cudd_VectorSupport()
Cudd_VectorSupportSize()
Cudd_ClassifySupport()
Cudd_CountLeaves()
Cudd_bddPickOneCube()
Cudd_bddPickOneMinterm()
Cudd_bddPickArbitraryMinterms()
Cudd_FirstCube()
Cudd_NextCube()
Cudd_bddComputeCube()
Cudd_addComputeCube()
Cudd_FirstNode()
Cudd_NextNode()
Cudd_GenFree()
Cudd_IsGenEmpty()
Cudd_IndicesToCube()
Cudd_PrintVersion()
Cudd_AverageDistance()
Cudd_Random()
Cudd_Srandom()
Cudd_Density()
Internal procedures included in this module:
cuddP()
cuddStCountfree()
cuddCollectNodes()
Static procedures included in this module:
dp2()
ddPrintMintermAux()
ddDagInt()
ddCountMintermAux()
ddCountPathAux()
ddSupportStep()
ddClearFlag()
ddLeavesInt()
ddPickArbitraryMinterms()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 82 of file cuddUtil.c.
Referenced by Cudd_FirstCube(), and Cudd_GenFree().
#define CUDD_GEN_EMPTY 0
Definition at line 84 of file cuddUtil.c.
Referenced by Cudd_FirstCube(), Cudd_FirstNode(), Cudd_IsGenEmpty(), Cudd_NextCube(), and Cudd_NextNode().
#define CUDD_GEN_NODES 1
Definition at line 83 of file cuddUtil.c.
Referenced by Cudd_FirstNode(), and Cudd_GenFree().
#define CUDD_GEN_NONEMPTY 1
Definition at line 85 of file cuddUtil.c.
Referenced by Cudd_FirstNode(), and Cudd_NextCube().
#define LEQA1 40014
Definition at line 89 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
#define LEQA2 40692
Definition at line 93 of file cuddUtil.c.
Referenced by Cudd_Random().
#define LEQQ1 53668
Definition at line 90 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
#define LEQQ2 52774
Definition at line 94 of file cuddUtil.c.
Referenced by Cudd_Random().
#define LEQR1 12211
Definition at line 91 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
#define LEQR2 3791
Definition at line 95 of file cuddUtil.c.
Referenced by Cudd_Random().
#define MODULUS1 2147483563
Definition at line 88 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
#define MODULUS2 2147483399
Definition at line 92 of file cuddUtil.c.
Referenced by Cudd_Random().
#define STAB_DIV (1 + (MODULUS1 - 1) / STAB_SIZE)
Definition at line 97 of file cuddUtil.c.
Referenced by Cudd_Random().
#define STAB_SIZE 64
Definition at line 96 of file cuddUtil.c.
Referenced by Cudd_Srandom().
Function Documentation
static int ddPickArbitraryMinterms ARGS ((DdManager *dd, DdNode *node, int nvars, int nminterms, char **string)) [static]
static void ddClearFlag ARGS ((DdNode *f)) [static]
static void ddSupportStep ARGS ((DdNode *f, int *support)) [static]
static double ddCountPathAux ARGS ((DdNode *node, st_table *table)) [static]
static double ddCountMintermAux ARGS ((DdNode *node, double max, st_table *table)) [static]
static int cuddEstimateCofactorSimple ARGS ((DdNode *node, int i)) [static]
static DdNode* cuddUniqueLookup ARGS ((DdManager *unique, intindex, DdNode *T, DdNode *E)) [static]
static int cuddEstimateCofactor ARGS ((DdManager *dd, st_table *table, DdNode *node, int i, int phase, DdNode **ptr)) [static]
static int ddDagInt ARGS ((DdNode *n)) [static]
static void ddPrintMintermAux ARGS ((DdManager *dd, DdNode *node, int *list)) [static]
static int dp2 ARGS ((DdNode *f, st_table *t)) [static]
AutomaticStart
DdNode* Cudd_addComputeCube (DdManager * dd, DdNode ** vars, int * phase, int n)
Function********************************************************************
Synopsis [Computes the cube of an array of ADD variables.]
Description [Computes the cube of an array of ADD variables. If non-null, the phase argument indicates which literal of each variable should appear in the cube. If phase\[i\] is nonzero, then the positive literal is used. If phase is NULL, the cube is positive unate. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [none]
SeeAlso [Cudd_bddComputeCube]
Definition at line 1534 of file cuddUtil.c.
References Cudd_addIte(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, DD_ONE, DD_ZERO, and zero.
double Cudd_AverageDistance (DdManager * dd)
Function********************************************************************
Synopsis [Computes the average distance between adjacent nodes.]
Description [Computes the average distance between adjacent nodes in the manager. Adjacent nodes are node pairs such that the second node is the then child, else child, or next node in the collision list.]
SideEffects [None]
SeeAlso []
Definition at line 1813 of file cuddUtil.c.
References Cudd_Regular, cuddE, cuddT, ddAbs, DdSubtable::nodelist, scan, DdManager::size, DdSubtable::slots, and DdManager::subtables.
DdNode* Cudd_bddComputeCube (DdManager * dd, DdNode ** vars, int * phase, int n)
Function********************************************************************
Synopsis [Computes the cube of an array of BDD variables.]
Description [Computes the cube of an array of BDD variables. If non-null, the phase argument indicates which literal of each variable should appear in the cube. If phase\[i\] is nonzero, then the positive literal is used. If phase is NULL, the cube is positive unate. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addComputeCube Cudd_IndicesToCube]
Definition at line 1484 of file cuddUtil.c.
References Cudd_bddAnd(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, cuddRef, and DD_ONE.
DdNode** Cudd_bddPickArbitraryMinterms (DdManager * dd, DdNode * f, DdNode ** vars, int n, int k)
Function********************************************************************
Synopsis [Picks k on-set minterms evenly distributed from given DD.]
Description [Picks k on-set minterms evenly distributed from given DD. The minterms are in terms of vars. The array vars should contain at least all variables in the support of f; if this condition is not met the minterms built by this procedure may not be contained in f. Builds a BDD for the minterms and returns a pointer to it if successful; NULL otherwise. There are three reasons why the procedure may fail:
It may run out of memory;
the function f may be the constant 0;
the minterms may not be contained in f.
]
SideEffects [None]
SeeAlso [Cudd_bddPickOneMinterm Cudd_bddPickOneCube]
Definition at line 1081 of file cuddUtil.c.
References ALLOC, Cudd_bddIte(), Cudd_bddLeq(), Cudd_CountMinterm(), CUDD_MEMORY_OUT, Cudd_Not, Cudd_Random(), Cudd_ReadOne(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, ddPickArbitraryMinterms(), DdManager::errorCode, FREE, result, DdManager::size, size, strcmp(), strcpy(), and zero.
int Cudd_bddPickOneCube (DdManager * ddm, DdNode * node, char * string)
Function********************************************************************
Synopsis [Picks one on-set cube randomly from the given DD.]
Description [Picks one on-set cube randomly from the given DD. The cube is written into an array of characters. The array must have at least as many entries as there are variables. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddPickOneMinterm]
Definition at line 902 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Random(), Cudd_Regular, cuddE, cuddT, DD_ONE, DdNode::index, one, and DdManager::size.
Referenced by Cudd_bddPickOneMinterm().
DdNode* Cudd_bddPickOneMinterm (DdManager * dd, DdNode * f, DdNode ** vars, int n)
Function********************************************************************
Synopsis [Picks one on-set minterm randomly from the given DD.]
Description [Picks one on-set minterm randomly from the given DD. The minterm is in terms of vars. The array vars should contain at least all variables in the support of f; if this condition is not met the minterm built by this procedure may not be contained in f. Builds a BDD for the minterm and returns a pointer to it if successful; NULL otherwise. There are three reasons why the procedure may fail:
It may run out of memory;
the function f may be the constant 0;
the minterm may not be contained in f.
]
SideEffects [None]
SeeAlso [Cudd_bddPickOneCube]
Definition at line 978 of file cuddUtil.c.
References ALLOC, Cudd_bddIte(), Cudd_bddLeq(), Cudd_bddPickOneCube(), CUDD_MEMORY_OUT, Cudd_Not, Cudd_Random(), Cudd_ReadOne(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, DdManager::errorCode, FREE, result, DdManager::size, size, and zero.
int Cudd_ClassifySupport (DdManager * dd, DdNode * f, DdNode * g, DdNode ** common, DdNode ** onlyF, DdNode ** onlyG)
Function********************************************************************
Synopsis [Classifies the variables in the support of two DDs.]
Description [Classifies the variables in the support of two DDs f and g, depending on whther they appear in both DDs, only in f, or only in g. Returns 1 successful; 0 otherwise.]
SideEffects [The cubes of the three classes of variables are returned as side effects.]
SeeAlso [Cudd_Support Cudd_VectorSupport]
Definition at line 766 of file cuddUtil.c.
References ALLOC, Cudd_bddAnd(), CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddDeref, cuddRef, cuddUniqueInter(), DD_ONE, ddClearFlag(), ddMax, ddSupportStep(), DdManager::errorCode, FREE, DdManager::invperm, DdManager::one, DdManager::size, size, and DdManager::sizeZ.
Referenced by Cudd_bddRestrict().
int Cudd_CountLeaves (DdNode * node)
Function********************************************************************
Synopsis [Counts the number of leaves in a DD.]
Description [Counts the number of leaves in a DD. Returns the number of leaves in the DD rooted at node if successful; CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_PrintDebug]
Definition at line 875 of file cuddUtil.c.
References Cudd_Regular, ddClearFlag(), and ddLeavesInt().
Referenced by Cudd_PrintDebug().
double Cudd_CountMinterm (DdManager * manager, DdNode * node, int nvars)
Function********************************************************************
Synopsis [Counts the number of minterms of a DD.]
Description [Counts the number of minterms of a DD. The function is assumed to depend on nvars variables. The minterm count is represented as a double, to allow for a larger number of variables. Returns the number of minterms of the function rooted at node if successful; (double) CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_PrintDebug Cudd_CountPath]
Definition at line 436 of file cuddUtil.c.
References DdManager::background, background, CUDD_MEMORY_OUT, Cudd_Not, CUDD_OUT_OF_MEM, cuddStCountfree(), ddCountMintermAux(), DdManager::errorCode, max, DdManager::one, st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and zero.
Referenced by Cudd_bddPickArbitraryMinterms(), Cudd_Density(), Cudd_PrintDebug(), and ddPickArbitraryMinterms().
double Cudd_CountPath (DdNode * node)
Function********************************************************************
Synopsis [Counts the number of paths of a DD.]
Description [Counts the number of paths of a DD. Paths to all terminal nodes are counted. The path count is represented as a double, to allow for a larger number of variables. Returns the number of paths of the function rooted at node.]
SideEffects [None]
SeeAlso [Cudd_CountMinterm]
Definition at line 481 of file cuddUtil.c.
References CUDD_OUT_OF_MEM, Cudd_Regular, cuddStCountfree(), ddCountPathAux(), st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_DagSize (DdNode * node)
Function********************************************************************
Synopsis [Counts the number of nodes in a DD.]
Description [Counts the number of nodes in a DD. Returns the number of nodes in the graph rooted at node.]
SideEffects [None]
SeeAlso [Cudd_SharingSize Cudd_PrintDebug]
Definition at line 301 of file cuddUtil.c.
References Cudd_Regular, ddClearFlag(), and ddDagInt().
Referenced by Cudd_addRestrict(), Cudd_ApaPrintDensity(), Cudd_bddRestrict(), Cudd_bddSqueeze(), Cudd_Density(), Cudd_PrintDebug(), cuddBddSqueeze(), cuddRemapUnderApprox(), cuddUnderApprox(), and gatherInfo().
double Cudd_Density (DdManager * dd, DdNode * f, int nvars)
Function********************************************************************
Synopsis [Computes the density of a BDD or ADD.]
Description [Computes the density of a BDD or ADD. The density is the ratio of the number of minterms to the number of nodes. If 0 is passed as number of variables, the number of variables existing in the manager is used. Returns the density if successful; (double) CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_CountMinterm Cudd_DagSize]
Definition at line 2008 of file cuddUtil.c.
References Cudd_CountMinterm(), Cudd_DagSize(), CUDD_OUT_OF_MEM, and DdManager::size.
int Cudd_EstimateCofactor (DdManager * dd, DdNode * f, int i, int phase)
Function********************************************************************
Synopsis [Estimates the number of nodes in a cofactor of a DD.]
Description [Estimates the number of nodes in a cofactor of a DD. Returns an estimate of the number of nodes in a cofactor of the graph rooted at node with respect to the variable whose index is i. In case of failure, returns CUDD_OUT_OF_MEM. This function uses a refinement of the algorithm of Cabodi et al. (ICCAD96). The refinement allows the procedure to account for part of the recombination that may occur in the part of the cofactor above the cofactoring variable. This procedure does no create any new node. It does keep a small table of results; therefore itmay run out of memory. If this is a concern, one should use Cudd_EstimateCofactorSimple, which is faster, does not allocate any memory, but is less accurate.]
SideEffects [None]
SeeAlso [Cudd_DagSize Cudd_EstimateCofactorSimple]
Definition at line 336 of file cuddUtil.c.
References CUDD_OUT_OF_MEM, Cudd_Regular, cuddEstimateCofactor(), ddClearFlag(), st_free_table(), st_init_table(), st_ptrcmp(), and st_ptrhash().
Referenced by Cudd_bddVarConjDecomp().
int Cudd_EstimateCofactorSimple (DdNode * node, int i)
Function********************************************************************
Synopsis [Estimates the number of nodes in a cofactor of a DD.]
Description [Estimates the number of nodes in a cofactor of a DD. Returns an estimate of the number of nodes in the positive cofactor of the graph rooted at node with respect to the variable whose index is i. This procedure implements with minor changes the algorithm of Cabodi et al. (ICCAD96). It does not allocate any memory, it does not change the state of the manager, and it is fast. However, it has been observed to overestimate the size of the cofactor by as much as a factor of 2.]
SideEffects [None]
SeeAlso [Cudd_DagSize]
Definition at line 375 of file cuddUtil.c.
References Cudd_Regular, cuddEstimateCofactorSimple(), and ddClearFlag().
DdGen* Cudd_FirstCube (DdManager * dd, DdNode * f, int ** cube, CUDD_VALUE_TYPE * value)
Function********************************************************************
Synopsis [Finds the first cube of a decision diagram.]
Description [Defines an iterator on the onset of a decision diagram and finds its first cube. Returns a generator that contains the information necessary to continue the enumeration if successful; NULL otherwise.
A cube is represented as an array of literals, which are integers in {0, 1, 2}; 0 represents a complemented literal, 1 represents an uncomplemented literal, and 2 stands for don't care. The enumeration produces a disjoint cover of the function associated with the diagram. The size of the array equals the number of variables in the manager at the time Cudd_FirstCube is called.
For each cube, a value is also returned. This value is always 1 for a BDD, while it may be different from 1 for an ADD. For BDDs, the offset is the set of cubes whose value is the logical zero. For ADDs, the offset is the set of cubes whose value is the background value. The cubes of the offset are not enumerated.]
SideEffects [The first cube and its value are returned as side effects.]
SeeAlso [Cudd_ForeachCube Cudd_NextCube Cudd_GenFree Cudd_IsGenEmpty Cudd_FirstNode]
Definition at line 1268 of file cuddUtil.c.
References ALLOC, DdGen::cubes, CUDD_GEN_CUBES, CUDD_GEN_EMPTY, CUDD_MEMORY_OUT, DD_ZERO_VAL, DdManager::errorCode, FREE, DdGen::gen, DdGen::manager, DdGen::node, DdManager::size, DdGen::stack, DdGen::status, and DdGen::type.
DdGen* Cudd_FirstNode (DdManager * dd, DdNode * f, DdNode ** node)
Function********************************************************************
Synopsis [Finds the first node of a decision diagram.]
Description [Defines an iterator on the nodes of a decision diagram and finds its first node. Returns a generator that contains the information necessary to continue the enumeration if successful; NULL otherwise.]
SideEffects [The first node is returned as a side effect.]
SeeAlso [Cudd_ForeachNode Cudd_NextNode Cudd_GenFree Cudd_IsGenEmpty Cudd_FirstCube]
Definition at line 1585 of file cuddUtil.c.
References ALLOC, CUDD_GEN_EMPTY, CUDD_GEN_NODES, CUDD_GEN_NONEMPTY, CUDD_MEMORY_OUT, Cudd_Regular, cuddCollectNodes(), DdManager::errorCode, FREE, DdGen::gen, DdGen::manager, DdGen::node, DdGen::nodes, st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), st_ptrhash(), DdGen::stack, DdGen::status, and DdGen::type.
int Cudd_GenFree (DdGen * gen)
Function********************************************************************
Synopsis [Frees a CUDD generator.]
Description [Frees a CUDD generator. Always returns 0, so that it can be used in mis-like foreach constructs.]
SideEffects [None]
SeeAlso [Cudd_ForeachCube Cudd_ForeachNode Cudd_FirstCube Cudd_NextCube Cudd_FirstNode Cudd_NextNode Cudd_IsGenEmpty]
Definition at line 1693 of file cuddUtil.c.
References DdGen::cubes, CUDD_GEN_CUBES, CUDD_GEN_NODES, FREE, DdGen::gen, DdGen::nodes, st_free_gen(), st_free_table(), DdGen::stack, and DdGen::type.
DdNode* Cudd_IndicesToCube (DdManager * dd, int * array, int n)
Function********************************************************************
Synopsis [Builds a cube of BDD variables from an array of indices.]
Description [Builds a cube of BDD variables from an array of indices. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddComputeCube]
Definition at line 1752 of file cuddUtil.c.
References Cudd_bddAnd(), Cudd_bddIthVar(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, and DD_ONE.
int Cudd_IsGenEmpty (DdGen * gen)
Function********************************************************************
Synopsis [Queries the status of a generator.]
Description [Queries the status of a generator. Returns 1 if the generator is empty or NULL; 0 otherswise.]
SideEffects [None]
SeeAlso [Cudd_ForeachCube Cudd_ForeachNode Cudd_FirstCube Cudd_NextCube Cudd_FirstNode Cudd_NextNode Cudd_GenFree]
Definition at line 1730 of file cuddUtil.c.
References CUDD_GEN_EMPTY, and DdGen::status.
int Cudd_NextCube (DdGen * gen, int ** cube, CUDD_VALUE_TYPE * value)
Function********************************************************************
Synopsis [Generates the next cube of a decision diagram onset.]
Description [Generates the next cube of a decision diagram onset, using generator gen. Returns 0 if the enumeration is completed; 1 otherwise.]
SideEffects [The cube and its value are returned as side effects. The generator is modified.]
SeeAlso [Cudd_ForeachCube Cudd_FirstCube Cudd_GenFree Cudd_IsGenEmpty Cudd_NextNode]
Definition at line 1387 of file cuddUtil.c.
References DdManager::background, DdGen::cubes, CUDD_GEN_EMPTY, CUDD_GEN_NONEMPTY, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, cuddV, DD_ONE, DdGen::gen, DdNode::index, DdGen::manager, DdGen::stack, and DdGen::status.
int Cudd_NextNode (DdGen * gen, DdNode ** node)
Function********************************************************************
Synopsis [Finds the next node of a decision diagram.]
Description [Finds the node of a decision diagram, using generator gen. Returns 0 if the enumeration is completed; 1 otherwise.]
SideEffects [The next node is returned as a side effect.]
SeeAlso [Cudd_ForeachNode Cudd_FirstNode Cudd_GenFree Cudd_IsGenEmpty Cudd_NextCube]
Definition at line 1660 of file cuddUtil.c.
References CUDD_GEN_EMPTY, DdGen::gen, DdGen::node, DdGen::nodes, st_gen(), and DdGen::status.
void Cudd_OutOfMem (long size)
Function********************************************************************
Synopsis [Warns that a memory allocation failed.]
Description [Warns that a memory allocation failed. This function can be used as replacement of MMout_of_memory to prevent the safe_mem functions of the util package from exiting when malloc returns NULL. One possible use is in case of discretionary allocations; for instance, the allocation of memory to enlarge the computed table.]
SideEffects [None]
SeeAlso []
Definition at line 2043 of file cuddUtil.c.
Referenced by cuddCacheResize(), cuddHashTableResize(), cuddLocalCacheResize(), ddRehash(), ddRehashZdd(), ddReorderPostprocess(), hashResize(), and zddReorderPostprocess().
int Cudd_PrintDebug (DdManager * dd, DdNode * f, int n, int pr)
Function********************************************************************
Synopsis [Prints to the standard output a DD and its statistics.]
Description [Prints to the standard output a DD and its statistics. The statistics include the number of nodes, the number of leaves, and the number of minterms. (The number of minterms is the number of assignments to the variables that cause the function to be different from the logical zero (for BDDs) and from the background value (for ADDs.) The statistics are printed if pr > 0. Specifically:
pr = 0 : prints nothing
pr = 1 : prints counts of nodes and minterms
pr = 2 : prints counts + disjoint sum of product
pr = 3 : prints counts + list of nodes
pr > 3 : prints counts + disjoint sum of product + list of nodes
Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_DagSize Cudd_CountLeaves Cudd_CountMinterm Cudd_PrintMinterm]
Definition at line 241 of file cuddUtil.c.
References Cudd_CountLeaves(), Cudd_CountMinterm(), Cudd_DagSize(), Cudd_Not, CUDD_OUT_OF_MEM, Cudd_PrintMinterm(), cuddP(), DD_ONE, and DD_ZERO.
int Cudd_PrintMinterm (DdManager * manager, DdNode * node)
Function********************************************************************
Synopsis [Prints a disjoint sum of products.]
Description [Prints a disjoint sum of product cover for the function rooted at node. Each product corresponds to a path from node a leaf node different from the logical zero, and different from the background value. Uses the standard output. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_PrintDebug]
Definition at line 194 of file cuddUtil.c.
References ALLOC, DdManager::background, background, CUDD_MEMORY_OUT, Cudd_Not, ddPrintMintermAux(), DdManager::errorCode, FREE, DdManager::one, DdManager::size, and zero.
Referenced by Cudd_PrintDebug().
void Cudd_PrintVersion (FILE * fp)
Function********************************************************************
Synopsis [Prints the package version number.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1791 of file cuddUtil.c.
References CUDD_VERSION.
long Cudd_Random ()
Function********************************************************************
Synopsis [Portable random number generator.]
Description [Portable number generator based on ran2 from `Numerical Recipes in C.` It is a long period (> 2 * 10^18) random number generator of L'Ecuyer with Bays-Durham shuffle. Returns a long integer uniformly distributed between 0 and 2147483561 (inclusive of the endpoint values). The ranom generator can be explicitly initialized by calling Cudd_Srandom. If no explicit initialization is performed, then the seed 1 is assumed.]
SideEffects [None]
SeeAlso [Cudd_Srandom]
Definition at line 1907 of file cuddUtil.c.
References Cudd_Srandom(), cuddRand, cuddRand2, LEQA1, LEQA2, LEQQ1, LEQQ2, LEQR1, LEQR2, MODULUS1, MODULUS2, shuffleSelect, shuffleTable, and STAB_DIV.
Referenced by Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneCube(), Cudd_bddPickOneMinterm(), cuddAnnealing(), cuddConjunctsAux(), cuddSwapping(), cuddZddSwapping(), rand_int(), random_generator(), and roulette().
int Cudd_SharingSize (DdNode ** nodeArray, int n)
Function********************************************************************
Synopsis [Counts the number of nodes in an array of DDs.]
Description [Counts the number of nodes in an array of DDs. Shared nodes are counted only once. Returns the total number of nodes.]
SideEffects [None]
SeeAlso [Cudd_DagSize]
Definition at line 402 of file cuddUtil.c.
References Cudd_Regular, ddClearFlag(), and ddDagInt().
Referenced by Cudd_bddIterConjDecomp().
void Cudd_Srandom (long seed)
Function********************************************************************
Synopsis [Initializer for the portable random number generator.]
Description [Initializer for the portable number generator based on ran2 in `Numerical Recipes in C.` The input is the seed for the generator. If it is negative, its absolute value is taken as seed. If it is 0, then 1 is taken as seed. The initialized sets up the two recurrences used to generate a long-period stream, and sets up the shuffle table.]
SideEffects [None]
SeeAlso [Cudd_Random]
Definition at line 1970 of file cuddUtil.c.
References cuddRand, cuddRand2, LEQA1, LEQQ1, LEQR1, MODULUS1, shuffleSelect, shuffleTable, and STAB_SIZE.
Referenced by Cudd_Random().
DdNode* Cudd_Support (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Finds the variables on which a DD depends.]
Description [Finds the variables on which a DD depends. Returns a BDD consisting of the product of the variables if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_VectorSupport Cudd_ClassifySupport]
Definition at line 518 of file cuddUtil.c.
References ALLOC, Cudd_bddAnd(), CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddDeref, cuddRef, cuddUniqueInter(), DD_ONE, ddClearFlag(), ddMax, ddSupportStep(), DdManager::errorCode, FREE, DdManager::invperm, DdManager::one, DdManager::size, size, and DdManager::sizeZ.
Referenced by Cudd_addRestrict(), Cudd_bddVarConjDecomp(), Cudd_CProjection(), and Cudd_zddDumpDot().
int Cudd_SupportSize (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Counts the variables on which a DD depends.]
Description [Counts the variables on which a DD depends. Returns the number of the variables if successful; CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_Support]
Definition at line 585 of file cuddUtil.c.
References ALLOC, CUDD_MEMORY_OUT, CUDD_OUT_OF_MEM, Cudd_Regular, ddClearFlag(), ddMax, ddSupportStep(), DdManager::errorCode, FREE, DdManager::size, size, and DdManager::sizeZ.
Referenced by Cudd_bddApproxConjDecomp(), Cudd_bddIterConjDecomp(), and cuddConjunctsAux().
DdNode* Cudd_VectorSupport (DdManager * dd, DdNode ** F, int n)
Function********************************************************************
Synopsis [Finds the variables on which a set of DDs depends.]
Description [Finds the variables on which a set of DDs depends. The set must contain either BDDs and ADDs, or ZDDs. Returns a BDD consisting of the product of the variables if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_Support Cudd_ClassifySupport]
Definition at line 636 of file cuddUtil.c.
References ALLOC, Cudd_bddAnd(), CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddDeref, cuddRef, cuddUniqueInter(), DD_ONE, ddClearFlag(), ddMax, ddSupportStep(), DdManager::errorCode, FREE, DdManager::invperm, DdManager::one, DdManager::size, size, and DdManager::sizeZ.
Referenced by Cudd_DumpBlif(), Cudd_DumpDDcal(), and Cudd_DumpDot().
int Cudd_VectorSupportSize (DdManager * dd, DdNode ** F, int n)
Function********************************************************************
Synopsis [Counts the variables on which a set of DDs depends.]
Description [Counts the variables on which a set of DDs depends. The set must contain either BDDs and ADDs, or ZDDs. Returns the number of the variables if successful; CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_VectorSupport Cudd_SupportSize]
Definition at line 709 of file cuddUtil.c.
References ALLOC, CUDD_MEMORY_OUT, CUDD_OUT_OF_MEM, Cudd_Regular, ddClearFlag(), ddMax, ddSupportStep(), DdManager::errorCode, FREE, DdManager::size, size, and DdManager::sizeZ.
int cuddCollectNodes (DdNode * f, st_table * visited)
Function********************************************************************
Synopsis [Recursively collects all the nodes of a DD in a symbol table.]
Description [Traverses the BDD f and collects all its nodes in a symbol table. f is assumed to be a regular pointer and cuddCollectNodes guarantees this assumption in the recursive calls. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 2131 of file cuddUtil.c.
References assert, Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, st_add_direct(), st_is_member, and ST_OUT_OF_MEM.
Referenced by Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_FirstNode(), and Cudd_zddDumpDot().
static int cuddEstimateCofactor (DdManager * dd, st_table * table, DdNode * node, int i, int phase, DdNode ** ptr) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CofactorEstimate.]
Description [Performs the recursive step of Cudd_CofactorEstimate. Returns an estimate of the number of nodes in the DD of a cofactor of node. Uses the least significant bit of the next field as visited flag. node is supposed to be regular; the invariant is maintained by this procedure.]
SideEffects [None]
SeeAlso []
Definition at line 2366 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_NotCond, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddIsConstant, cuddT, cuddUniqueLookup(), ddDagInt(), DdNode::index, DdNode::next, DdManager::perm, DdNode::ref, st_add_direct(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_EstimateCofactor().
static int cuddEstimateCofactorSimple (DdNode * node, int i) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CofactorEstimateSimple.]
Description [Performs the recursive step of Cudd_CofactorEstimateSimple. Returns an estimate of the number of nodes in the DD of the positive cofactor of node. Uses the least significant bit of the next field as visited flag. node is supposed to be regular; the invariant is maintained by this procedure.]
SideEffects [None]
SeeAlso []
Definition at line 2527 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DdNode::index, and DdNode::next.
Referenced by Cudd_EstimateCofactorSimple().
int cuddP (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Prints a DD to the standard output. One line per node is printed.]
Description [Prints a DD to the standard output. One line per node is printed. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_PrintDebug]
Definition at line 2072 of file cuddUtil.c.
References dp2(), st_free_table(), st_init_table(), st_ptrcmp(), and st_ptrhash().
Referenced by Cudd_PrintDebug().
enum st_retval cuddStCountfree (char * key, char * value, char * arg)
Function********************************************************************
Synopsis [Frees the memory used to store the minterm counts recorded in the visited table.]
Description [Frees the memory used to store the minterm counts recorded in the visited table. Returns ST_CONTINUE.]
SideEffects [None]
Definition at line 2101 of file cuddUtil.c.
References FREE, and ST_CONTINUE.
Referenced by Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), and Cudd_SplitSet().
static DdNode* cuddUniqueLookup (DdManager * unique, int index, DdNode * T, DdNode * E) [static]
Function********************************************************************
Synopsis [Checks the unique table for the existence of an internal node.]
Description [Checks the unique table for the existence of an internal node. Returns a pointer to the node if it is in the table; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddUniqueInter]
Definition at line 2464 of file cuddUtil.c.
References assert, Cudd_Regular, cuddE, cuddI, cuddT, ddHash, DdNode::index, DdSubtable::nodelist, DdManager::perm, DdSubtable::shift, DdManager::size, and DdManager::subtables.
Referenced by cuddEstimateCofactor().
static void ddClearFlag (DdNode * f) [static]
Function********************************************************************
Synopsis [Performs a DFS from f, clearing the LSB of the next pointers.]
Description []
SideEffects [None]
SeeAlso [ddSupportStep ddDagInt]
Definition at line 2722 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, and DdNode::next.
Referenced by Cudd_ClassifySupport(), Cudd_CountLeaves(), Cudd_DagSize(), Cudd_EstimateCofactor(), Cudd_EstimateCofactorSimple(), Cudd_SharingSize(), Cudd_Support(), Cudd_SupportSize(), Cudd_VectorSupport(), and Cudd_VectorSupportSize().
static double ddCountMintermAux (DdNode * node, double max, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CountMinterm.]
Description [Performs the recursive step of Cudd_CountMinterm. It is based on the following identity. Let |f| be the number of minterms of f. Then: <xmp> |f| = (|f0|+|f1|)/2 </xmp> where f0 and f1 are the two cofactors of f. Does not use the identity |f'| = max - |f|, to minimize loss of accuracy due to roundoff. Returns the number of minterms of the function rooted at node.]
SideEffects [None]
Definition at line 2567 of file cuddUtil.c.
References ALLOC, background, Cudd_IsComplement, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddIsConstant, cuddT, FREE, st_add_direct(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by Cudd_CountMinterm().
static double ddCountPathAux (DdNode * node, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CountPath.]
Description [Performs the recursive step of Cudd_CountPath. It is based on the following identity. Let |f| be the number of paths of f. Then: <xmp> |f| = |f0|+|f1| </xmp> where f0 and f1 are the two cofactors of f. Uses the identity |f'| = |f|, to improve the utilization of the (local) cache. Returns the number of paths of the function rooted at node.]
SideEffects [None]
Definition at line 2635 of file cuddUtil.c.
References ALLOC, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddIsConstant, cuddT, FREE, st_add_direct(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_CountPath().
static int ddDagInt (DdNode * n) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_DagSize.]
Description [Performs the recursive step of Cudd_DagSize. Returns the number of nodes in the graph rooted at n.]
SideEffects [None]
Definition at line 2331 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, and DdNode::next.
Referenced by Cudd_DagSize(), Cudd_SharingSize(), and cuddEstimateCofactor().
static int ddLeavesInt (DdNode * n) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CountLeaves.]
Description [Performs the recursive step of Cudd_CountLeaves. Returns the number of leaves in the DD rooted at n.]
SideEffects [None]
Definition at line 2751 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, and DdNode::next.
Referenced by Cudd_CountLeaves().
static int ddPickArbitraryMinterms (DdManager * dd, DdNode * node, int nvars, int nminterms, char ** string) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddPickArbitraryMinterms.]
Description [Performs the recursive step of Cudd_bddPickArbitraryMinterms.]
SideEffects [Cudd_bddPickArbitraryMinterms]
Definition at line 2780 of file cuddUtil.c.
References Cudd_CountMinterm(), Cudd_IsComplement, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddT, DD_ONE, DdNode::index, one, and result.
Referenced by Cudd_bddPickArbitraryMinterms().
static void ddPrintMintermAux (DdManager * dd, DdNode * node, int * list) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_PrintMinterm.]
Description []
SideEffects [None]
Definition at line 2277 of file cuddUtil.c.
References background, Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, cuddV, DdNode::index, DdManager::size, and zero.
Referenced by Cudd_PrintMinterm().
static void ddSupportStep (DdNode * f, int * support) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_Support.]
Description [Performs the recursive step of Cudd_Support. Performs a DFS from f. The support is accumulated in supp as a side effect. Uses the LSB of the then pointer as visited flag.]
SideEffects [None]
SeeAlso [ddClearFlag]
Definition at line 2691 of file cuddUtil.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DdNode::index, and DdNode::next.
Referenced by Cudd_ClassifySupport(), Cudd_Support(), Cudd_SupportSize(), Cudd_VectorSupport(), and Cudd_VectorSupportSize().
static int dp2 (DdNode * f, st_table * t) [static]
Function********************************************************************
Synopsis [Performs the recursive step of cuddP.]
Description [Performs the recursive step of cuddP. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 2185 of file cuddUtil.c.
References bang, Cudd_Regular, cuddE, cuddIsConstant, cuddT, cuddV, st_add_direct(), st_is_member, and ST_OUT_OF_MEM.
Referenced by cuddP().
Variable Documentation
DdNode* background [static]
Definition at line 138 of file cuddUtil.c.
long cuddRand = 0 [static]
Definition at line 140 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
long cuddRand2 [static]
Definition at line 141 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
char rcsid [] DD_UNUSED = `$Id: cuddUtil.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 135 of file cuddUtil.c.
long shuffleSelect [static]
Definition at line 142 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
long shuffleTable[STAB_SIZE] [static]
Definition at line 143 of file cuddUtil.c.
Referenced by Cudd_Random(), and Cudd_Srandom().
DdNode * zero [static]
Definition at line 138 of file cuddUtil.c.