cuddExport.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static int ddDoDumpBlif ARGS ((DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names))
static int ddDoDumpDaVinci ARGS ((DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names, long mask))
static int ddDoDumpFactoredForm ARGS ((DdManager *dd, DdNode *f, FILE *fp, char **names))
int Cudd_DumpBlif (DdManager *dd, int n, DdNode **f, char **inames, char **onames, char *mname, FILE *fp)
int Cudd_DumpDot (DdManager *dd, int n, DdNode **f, char **inames, char **onames, FILE *fp)
int Cudd_DumpDaVinci (DdManager *dd, int n, DdNode **f, char **inames, char **onames, FILE *fp)
int Cudd_DumpDDcal (DdManager *dd, int n, DdNode **f, char **inames, char **onames, FILE *fp)
int Cudd_DumpFactoredForm (DdManager *dd, int n, DdNode **f, char **inames, char **onames, FILE *fp)
static int ddDoDumpBlif (DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names)
static int ddDoDumpDaVinci (DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names, long mask)
static int ddDoDumpDDcal (DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names, long mask)
static int ddDoDumpFactoredForm (DdManager *dd, DdNode *f, FILE *fp, char **names)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddExport.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int ddDoDumpFactoredForm ARGS ((DdManager *dd, DdNode *f, FILE *fp, char **names)) [static]
static int ddDoDumpDDcal ARGS ((DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names, long mask)) [static]
static int ddDoDumpBlif ARGS ((DdManager *dd, DdNode *f, FILE *fp, st_table *visited, char **names)) [static]
AutomaticStart
int Cudd_DumpBlif (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, char * mname, FILE * fp)
Function********************************************************************
Synopsis [Writes a blif file representing the argument BDDs.]
Description [Writes a blif file representing the argument BDDs as a network of multiplexers. One multiplexer is written for each BDD node. It returns 1 in case of success; 0 otherwise (e.g., out-of-memory, file system full, or an ADD with constants different from 0 and 1). Cudd_DumpBlif does not close the file: This is the caller responsibility. Cudd_DumpBlif uses a minimal unique subset of the hexadecimal address of a node as name for it. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames.]
SideEffects [None]
SeeAlso [Cudd_DumpDot Cudd_PrintDebug]
Definition at line 106 of file cuddExport.c.
References ALLOC, Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_Regular, Cudd_VectorSupport(), cuddIsConstant, cuddRef, cuddT, ddDoDumpBlif(), DdManager::errorCode, FREE, scan, DdManager::size, st_free_table(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_DumpDaVinci (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, FILE * fp)
Function********************************************************************
Synopsis [Writes a daVinci file representing the argument BDDs.]
Description [Writes a daVinci file representing the argument BDDs. It returns 1 in case of success; 0 otherwise (e.g., out-of-memory or file system full). Cudd_DumpDaVinci does not close the file: This is the caller responsibility. Cudd_DumpDaVinci uses a minimal unique subset of the hexadecimal address of a node as name for it. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames.]
SideEffects [None]
SeeAlso [Cudd_DumpDot Cudd_PrintDebug Cudd_DumpBlif]
Definition at line 545 of file cuddExport.c.
References Cudd_IsComplement, Cudd_RecursiveDeref(), Cudd_Regular, cuddCollectNodes(), ddDoDumpDaVinci(), scan, st_free_gen(), st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_DumpDDcal (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, FILE * fp)
Function********************************************************************
Synopsis [Writes a DDcal file representing the argument BDDs.]
Description [Writes a DDcal file representing the argument BDDs. It returns 1 in case of success; 0 otherwise (e.g., out-of-memory or file system full). Cudd_DumpDDcal does not close the file: This is the caller responsibility. Cudd_DumpDDcal uses a minimal unique subset of the hexadecimal address of a node as name for it. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames.]
SideEffects [None]
SeeAlso [Cudd_DumpDot Cudd_PrintDebug Cudd_DumpBlif Cudd_DumpDaVinci]
Definition at line 658 of file cuddExport.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_Regular, Cudd_VectorSupport(), cuddCollectNodes(), cuddIsConstant, cuddRef, cuddT, DdManager::errorCode, DdManager::invperm, scan, DdManager::size, st_free_gen(), st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_DumpDot (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, FILE * fp)
Function********************************************************************
Synopsis [Writes a dot file representing the argument DDs.]
Description [Writes a file representing the argument DDs in a format suitable for the graph drawing program dot. It returns 1 in case of success; 0 otherwise (e.g., out-of-memory, file system full). Cudd_DumpDot does not close the file: This is the caller responsibility. Cudd_DumpDot uses a minimal unique subset of the hexadecimal address of a node as name for it. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames. Cudd_DumpDot uses the following convention to draw arcs:
solid line: THEN arcs;
dotted line: complement arcs;
dashed line: regular ELSE arcs.
The dot options are chosen so that the drawing fits on a letter-size sheet. ]
SideEffects [None]
SeeAlso [Cudd_DumpBlif Cudd_PrintDebug]
Definition at line 263 of file cuddExport.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_Regular, Cudd_VectorSupport(), cuddCollectNodes(), cuddIsConstant, cuddRef, cuddT, DdManager::errorCode, DdManager::invperm, scan, DdManager::size, st_free_gen(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_DumpFactoredForm (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, FILE * fp)
Function********************************************************************
Synopsis [Writes factored forms representing the argument BDDs.]
Description [Writes factored forms representing the argument BDDs. The format of the factored form is the one used in the genlib files for technology mapping in sis. It returns 1 in case of success; 0 otherwise (e.g., file system full). Cudd_DumpFactoredForm does not close the file: This is the caller responsibility. Caution must be exercised because a factored form may be exponentially larger than the argument BDD. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames.]
SideEffects [None]
SeeAlso [Cudd_DumpDot Cudd_PrintDebug Cudd_DumpBlif Cudd_DumpDaVinci Cudd_DumpDDcal]
Definition at line 815 of file cuddExport.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, DD_ONE, DD_ZERO, and ddDoDumpFactoredForm().
static int ddDoDumpBlif (DdManager * dd, DdNode * f, FILE * fp, st_table * visited, char ** names) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_DumpBlif.]
Description [Performs the recursive step of Cudd_DumpBlif. Traverses the BDD f and writes a multiplexer-network description to the file pointed by fp in blif format. f is assumed to be a regular pointer and ddDoDumpBlif guarantees this assumption in the recursive calls.]
SideEffects [None]
SeeAlso []
Definition at line 882 of file cuddExport.c.
References assert, Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DD_ONE, DD_ZERO, st_insert(), st_is_member, and ST_OUT_OF_MEM.
Referenced by Cudd_DumpBlif().
static int ddDoDumpDaVinci (DdManager * dd, DdNode * f, FILE * fp, st_table * visited, char ** names, long mask) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_DumpDaVinci.]
Description [Performs the recursive step of Cudd_DumpDaVinci. Traverses the BDD f and writes a term expression to the file pointed by fp in daVinci format. f is assumed to be a regular pointer and ddDoDumpDaVinci guarantees this assumption in the recursive calls.]
SideEffects [None]
SeeAlso []
Definition at line 1006 of file cuddExport.c.
References assert, Cudd_IsComplement, Cudd_IsConstant, Cudd_Regular, cuddE, cuddT, cuddV, st_insert(), st_is_member, and ST_OUT_OF_MEM.
Referenced by Cudd_DumpDaVinci().
static int ddDoDumpDDcal (DdManager * dd, DdNode * f, FILE * fp, st_table * visited, char ** names, long mask) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_DumpDDcal.]
Description [Performs the recursive step of Cudd_DumpDDcal. Traverses the BDD f and writes a line for each node to the file pointed by fp in DDcal format. f is assumed to be a regular pointer and ddDoDumpDDcal guarantees this assumption in the recursive calls.]
SideEffects [None]
SeeAlso []
Definition at line 1099 of file cuddExport.c.
References assert, Cudd_IsComplement, Cudd_IsConstant, Cudd_Regular, cuddE, cuddT, cuddV, DD_ONE, DD_ZERO, st_insert(), st_is_member, and ST_OUT_OF_MEM.
static int ddDoDumpFactoredForm (DdManager * dd, DdNode * f, FILE * fp, char ** names) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_DumpFactoredForm.]
Description [Performs the recursive step of Cudd_DumpFactoredForm. Traverses the BDD f and writes a factored form for each node to the file pointed by fp in terms of the factored forms of the children. Constants are propagated, and absorption is applied. f is assumed to be a regular pointer and ddDoDumpFActoredForm guarantees this assumption in the recursive calls.]
SideEffects [None]
SeeAlso [Cudd_DumpFactoredForm]
Definition at line 1187 of file cuddExport.c.
References assert, Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_Regular, cuddE, cuddT, DD_ONE, DD_ZERO, and DdNode::index.
Referenced by Cudd_DumpFactoredForm().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddExport.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddExport.c]
PackageName [cudd]
Synopsis [Export functions.]
Description [External procedures included in this module:
Cudd_DumpBlif()
Cudd_DumpDot()
Cudd_DumpDaVinci()
Cudd_DumpDDcal()
Cudd_DumpFactoredForm()
Internal procedures included in this module:
Static procedures included in this module:
ddDoDumpBlif()
ddDoDumpDaVinci()
ddDoDumpDDcal()
ddDoDumpFactoredForm()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 60 of file cuddExport.c.