cuddSubsetSP.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct NodeDist
struct AssortedInfo
Defines
#define DEFAULT_PAGE_SIZE 2048
#define DEFAULT_NODE_DIST_PAGE_SIZE 2048
#define MAXSHORTINT ((DdHalfWord) ~0)
#define INITIAL_PAGES 128
Typedefs
typedef NodeDist NodeDist_t
Functions
static void ResizeNodeDistPages ARGS (())
static void CreateTopDist ARGS ((st_table *pathTable, int parentPage, int parentQueueIndex, int topLen, DdNode **childPage, int childQueueIndex, int numParents))
static void CreateBotDist ARGS ((DdNode *node, st_table *pathTable, unsigned int *pathLengthArray))
static st_table *CreatePathTable ARGS ((DdNode *node, unsigned int *pathLengthArray))
static unsigned int AssessPathLength ARGS ((unsigned int *pathLengthArray, int threshold, int numVars, unsigned int *excess))
static DdNode *BuildSubsetBdd ARGS ((DdManager *dd, st_table *pathTable, DdNode *node, struct AssortedInfo *info, st_table *subsetNodeTable))
static enum st_retval stPathTableDdFree ARGS ((char *key, char *value, char *arg))
DdNode * Cudd_SubsetShortPaths (DdManager *dd, DdNode *f, int numVars, int threshold, int hardlimit)
DdNode * Cudd_SupersetShortPaths (DdManager *dd, DdNode *f, int numVars, int threshold, int hardlimit)
DdNode * cuddSubsetShortPaths (DdManager *dd, DdNode *f, int numVars, int threshold, int hardlimit)
static void ResizeNodeDistPages ()
static void ResizeQueuePages ()
static void CreateTopDist (st_table *pathTable, int parentPage, int parentQueueIndex, int topLen, DdNode **childPage, int childQueueIndex, int numParents)
static void CreateBotDist (DdNode *node, st_table *pathTable, unsigned int *pathLengthArray)
static st_table * CreatePathTable (DdNode *node, unsigned int *pathLengthArray)
static unsigned int AssessPathLength (unsigned int *pathLengthArray, int threshold, int numVars, unsigned int *excess)
static DdNode * BuildSubsetBdd (DdManager *dd, st_table *pathTable, DdNode *node, struct AssortedInfo *info, st_table *subsetNodeTable)
static enum st_retval stPathTableDdFree (char *key, char *value, char *arg)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddSubsetSP.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int memOut
static DdNode * zero
static DdNode * one
static NodeDist_t ** nodeDistPages
static int nodeDistPageIndex
static int nodeDistPage
static int nodeDistPageSize = DEFAULT_NODE_DIST_PAGE_SIZE
static int maxNodeDistPages
static NodeDist_t * currentNodeDistPage
static DdNode *** queuePages
static int queuePageIndex
static int queuePage
static int queuePageSize = DEFAULT_PAGE_SIZE
static int maxQueuePages
static DdNode ** currentQueuePage
Define Documentation
#define DEFAULT_NODE_DIST_PAGE_SIZE 2048
Definition at line 55 of file cuddSubsetSP.c.
#define DEFAULT_PAGE_SIZE 2048
CFile***********************************************************************
FileName [cuddSubsetSP.c]
PackageName [cudd]
Synopsis [Procedure to subset the given BDD choosing the shortest paths (largest cubes) in the BDD.]
Description [External procedures included in this module:
Cudd_SubsetShortPaths()
Cudd_SupersetShortPaths()
Internal procedures included in this module:
cuddSubsetShortPaths()
Static procedures included in this module:
BuildSubsetBdd()
CreatePathTable()
AssessPathLength()
CreateTopDist()
CreateBotDist()
ResizeNodeDistPages()
ResizeQueuePages()
stPathTableDdFree()
]
SeeAlso [cuddSubsetHB.c]
Author [Kavita Ravi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 54 of file cuddSubsetSP.c.
#define INITIAL_PAGES 128
Definition at line 61 of file cuddSubsetSP.c.
#define MAXSHORTINT ((DdHalfWord) ~0)
Definition at line 56 of file cuddSubsetSP.c.
Referenced by BuildSubsetBdd(), CreateBotDist(), CreatePathTable(), CreateTopDist(), and cuddSubsetShortPaths().
Typedef Documentation
typedef struct NodeDist NodeDist_t
Definition at line 94 of file cuddSubsetSP.c.
Function Documentation
static enum st_retval stPathTableDdFree ARGS ((char *key, char *value, char *arg)) [static]
static DdNode* BuildSubsetBdd ARGS ((DdManager *dd, st_table *pathTable, DdNode *node, struct AssortedInfo *info, st_table *subsetNodeTable)) [static]
static unsigned int AssessPathLength ARGS ((unsigned int *pathLengthArray, int threshold, int numVars, unsigned int *excess)) [static]
static st_table* CreatePathTable ARGS ((DdNode *node, unsigned int *pathLengthArray)) [static]
static void CreateBotDist ARGS ((DdNode *node, st_table *pathTable, unsigned int *pathLengthArray)) [static]
static void CreateTopDist ARGS ((st_table *pathTable, int parentPage, int parentQueueIndex, int topLen, DdNode **childPage, int childQueueIndex, int numParents)) [static]
static void ResizeNodeDistPages ARGS (()) [static]
AutomaticStart
static unsigned int AssessPathLength (unsigned int * pathLengthArray, int threshold, int numVars, unsigned int * excess) [static]
Function********************************************************************
Synopsis [Chooses the maximum allowable path length os nodes under the threshold]
Description [Chooses the maximum allowable path length under each node. The corner cases are when the threshold is larger than the number of nodes in the bdd iself, in which case 'numVars + 1' is returned. If all nodes of a particular path length are needed, then the maxpath returned is the next one with excess nodes = 0;]
SideEffects [None]
SeeAlso []
Definition at line 1129 of file cuddSubsetSP.c.
References AssortedInfo::maxpath.
Referenced by cuddSubsetShortPaths().
static DdNode* BuildSubsetBdd (DdManager * dd, st_table * pathTable, DdNode * node, struct AssortedInfo * info, st_table * subsetNodeTable) [static]
Function********************************************************************
Synopsis [Builds the BDD with nodes labeled with path length less than or equal to maxpath]
Description [Builds the BDD with nodes labeled with path length under maxpath and as many nodes labeled maxpath as determined by the threshold. The procedure uses the path table to determine which nodes in the original bdd need to be retained. This procedure picks a shortest path (tie break decided by taking the child with the shortest distance to the constant) and recurs down the path till it reaches the constant. the procedure then starts building the subset upward from the constant. All nodes labeled by path lengths less than the given maxpath are used to build the subset. However, in the case of nodes that have label equal to maxpath, as many are chosen as required by the threshold. This number is stored in the info structure in the field thresholdReached. This field is decremented whenever a node labeled maxpath is encountered and the nodes labeled maxpath are aggregated in a maxpath table. As soon as the thresholdReached count goes to 0, the shortest path from this node to the constant is found. The extraction of nodes with the above labeling is based on the fact that each node, labeled with a path length, P, has at least one child labeled P or less. So extracting all nodes labeled a given path length P ensures complete paths between the root and the constant. Extraction of a partial number of nodes with a given path length may result in incomplete paths and hence the additional number of nodes are grabbed to complete the path. Since the Bdd is built bottom-up, other nodes labeled maxpath do lie on complete paths. The procedure may cause the subset to have a larger or smaller number of nodes than the specified threshold. The increase in the number of nodes is caused by the building of a subset and the reduction by recombination. However in most cases, the recombination overshadows the increase and the procedure returns a result with lower number of nodes than specified. The subsetNodeTable is NIL when there is no hard limit on the number of nodes. Further efforts towards keeping the subset closer to the threshold number were abandoned in favour of keeping the procedure simple and fast.]
SideEffects [SubsetNodeTable is changed if it is not NIL.]
SeeAlso []
Definition at line 1211 of file cuddSubsetSP.c.
References BuildSubsetBdd(), Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_NodeReadIndex(), Cudd_Not, Cudd_NotCond, Cudd_ReadVars(), Cudd_RecursiveDeref(), Cudd_Regular, Cudd_T, cuddBddIteRecur(), cuddDeref, cuddRef, DD_ONE, entry, exit(), AssortedInfo::findShortestPath, AssortedInfo::maxpath, AssortedInfo::maxpathTable, MAXSHORTINT, memOut, NIL, st_count, st_insert(), st_lookup(), ST_OUT_OF_MEM, AssortedInfo::threshold, AssortedInfo::thresholdReached, and zero.
static void CreateBotDist (DdNode * node, st_table * pathTable, unsigned int * pathLengthArray) [static]
Function********************************************************************
Synopsis [ Labels each node with the shortest distance from the constant.]
Description [Labels each node with the shortest distance from the constant. This is done in a DFS search of the BDD. Each node has an odd and even parity distance from the sink (since there exists paths to both zero and one) which is less than MAXSHORTINT. At each node these distances are updated using the minimum distance of its children from the constant. SInce now both the length from the root and child is known, the minimum path length(length of the shortest path between the root and the constant that this node lies on) of this node can be calculated and used to update the pathLengthArray]
SideEffects [Updates Path Table and path length array]
SeeAlso [CreatePathTable CreateTopDist AssessPathLength]
Definition at line 796 of file cuddSubsetSP.c.
References CreateBotDist(), Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_NotCond, Cudd_Regular, Cudd_T, exit(), MAXSHORTINT, and st_lookup().
static st_table* CreatePathTable (DdNode * node, unsigned int * pathLengthArray) [static]
Function********************************************************************
Synopsis [ The outer procedure to label each node with its shortest distance from the root and constant]
Description [ The outer procedure to label each node with its shortest distance from the root and constant. Calls CreateTopDist and CreateBotDist. The basis for computing the distance between root and constant is that the distance may be the sum of even distances from the node to the root and constant or the sum of odd distances from the node to the root and constant. Both CreateTopDist and CreateBotDist create the odd and even parity distances from the root and constant respectively.]
SideEffects [None]
SeeAlso [CreateTopDist CreateBotDist]
Definition at line 979 of file cuddSubsetSP.c.
References ALLOC, NodeDist::compResult, CreateBotDist(), CreateTopDist(), Cudd_IsComplement, Cudd_Regular, currentNodeDistPage, currentQueuePage, NodeDist::evenBotDist, NodeDist::evenTopDist, exit(), FREE, INITIAL_PAGES, maxNodeDistPages, maxQueuePages, MAXSHORTINT, memOut, nodeDistPage, nodeDistPageIndex, nodeDistPages, nodeDistPageSize, NodeDist::oddBotDist, NodeDist::oddTopDist, queuePage, queuePageIndex, queuePages, queuePageSize, NodeDist::regResult, ResizeNodeDistPages(), st_free_table(), st_init_table(), st_insert(), ST_OUT_OF_MEM, st_ptrcmp(), and st_ptrhash().
Referenced by cuddSubsetShortPaths().
static void CreateTopDist (st_table * pathTable, int parentPage, int parentQueueIndex, int topLen, DdNode ** childPage, int childQueueIndex, int numParents) [static]
Function********************************************************************
Synopsis [ Labels each node with its shortest distance from the root]
Description [ Labels each node with its shortest distance from the root. This is done in a BFS search of the BDD. The nodes are processed in a queue implemented as pages(array) to reduce memory fragmentation. An entry is created for each node visited. The distance from the root to the node with the corresponding parity is updated. The procedure is called recursively each recusion level handling nodes at a given level from the root.]
SideEffects [Creates entries in the pathTable]
SeeAlso [CreatePathTable CreateBotDist]
Definition at line 596 of file cuddSubsetSP.c.
References assert, Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_NotCond, Cudd_Regular, Cudd_T, currentNodeDistPage, currentQueuePage, FREE, MAXSHORTINT, memOut, nodeDistPage, nodeDistPageIndex, nodeDistPages, nodeDistPageSize, queuePage, queuePageIndex, queuePages, queuePageSize, ResizeNodeDistPages(), ResizeQueuePages(), st_free_table(), st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by CreatePathTable().
DdNode* Cudd_SubsetShortPaths (DdManager * dd, DdNode * f, int numVars, int threshold, int hardlimit)
Function********************************************************************
Synopsis [Extracts a dense subset from a BDD with the shortest paths heuristic.]
Description [Extracts a dense subset from a BDD. This procedure tries to preserve the shortest paths of the input BDD, because they give many minterms and contribute few nodes. This procedure may increase the number of nodes in trying to create the subset or reduce the number of nodes due to recombination as compared to the original BDD. Hence the threshold may not be strictly adhered to. In practice, recombination overshadows the increase in the number of nodes and results in small BDDs as compared to the threshold. The hardlimit specifies whether threshold needs to be strictly adhered to. If it is set to 1, the procedure ensures that result is never larger than the specified limit but may be considerably less than the threshold. Returns a pointer to the BDD for the subset if successful; NULL otherwise. The value for numVars should be as close as possible to the size of the support of f for better efficiency. However, it is safe to pass the value returned by Cudd_ReadSize for numVars. If 0 is passed, then the value returned by Cudd_ReadSize is used.]
SideEffects [None]
SeeAlso [Cudd_SupersetShortPaths Cudd_SubsetHeavyBranch Cudd_ReadSize]
Definition at line 185 of file cuddSubsetSP.c.
References cuddSubsetShortPaths(), memOut, and DdManager::reordered.
Referenced by Cudd_SubsetCompress().
DdNode* Cudd_SupersetShortPaths (DdManager * dd, DdNode * f, int numVars, int threshold, int hardlimit)
Function********************************************************************
Synopsis [Extracts a dense superset from a BDD with the shortest paths heuristic.]
Description [Extracts a dense superset from a BDD. The procedure is identical to the subset procedure except for the fact that it receives the complement of the given function. Extracting the subset of the complement function is equivalent to extracting the superset of the function. This procedure tries to preserve the shortest paths of the complement BDD, because they give many minterms and contribute few nodes. This procedure may increase the number of nodes in trying to create the superset or reduce the number of nodes due to recombination as compared to the original BDD. Hence the threshold may not be strictly adhered to. In practice, recombination overshadows the increase in the number of nodes and results in small BDDs as compared to the threshold. The hardlimit specifies whether threshold needs to be strictly adhered to. If it is set to 1, the procedure ensures that result is never larger than the specified limit but may be considerably less than the threshold. Returns a pointer to the BDD for the superset if successful; NULL otherwise. The value for numVars should be as close as possible to the size of the support of f for better efficiency. However, it is safe to pass the value returned by Cudd_ReadSize for numVar. If 0 is passed, then the value returned by Cudd_ReadSize is used.]
SideEffects [None]
SeeAlso [Cudd_SubsetShortPaths Cudd_SupersetHeavyBranch Cudd_ReadSize]
Definition at line 237 of file cuddSubsetSP.c.
References Cudd_Not, Cudd_NotCond, cuddSubsetShortPaths(), memOut, and DdManager::reordered.
DdNode* cuddSubsetShortPaths (DdManager * dd, DdNode * f, int numVars, int threshold, int hardlimit)
Function********************************************************************
Synopsis [The outermost procedure to return a subset of the given BDD with the shortest path lengths.]
Description [The outermost procedure to return a subset of the given BDD with the largest cubes. The path lengths are calculated, the maximum allowable path length is determined and the number of nodes of this path length that can be used to build a subset. If the threshold is larger than the size of the original BDD, the original BDD is returned. ]
SideEffects [None]
SeeAlso [Cudd_SubsetShortPaths]
Definition at line 281 of file cuddSubsetSP.c.
References ALLOC, AssessPathLength(), BuildSubsetBdd(), CreatePathTable(), Cudd_bddIteConstant(), Cudd_IsConstant, Cudd_Not, Cudd_ReadSize(), Cudd_Regular, cuddDeref, cuddRef, DD_ONE, exit(), AssortedInfo::findShortestPath, FREE, AssortedInfo::maxpath, AssortedInfo::maxpathTable, MAXSHORTINT, memOut, NIL, nodeDistPage, nodeDistPages, one, st_foreach(), st_free_table(), st_init_table(), st_lookup(), st_ptrcmp(), st_ptrhash(), stPathTableDdFree(), AssortedInfo::threshold, AssortedInfo::thresholdReached, and zero.
Referenced by Cudd_SubsetShortPaths(), and Cudd_SupersetShortPaths().
static void ResizeNodeDistPages () [static]
Function********************************************************************
Synopsis [Resize the number of pages allocated to store the distances related to each node.]
Description [Resize the number of pages allocated to store the distances related to each node. The procedure moves the counter to the next page when the end of the page is reached and allocates new pages when necessary. ]
SideEffects [Changes the size of pages, page, page index, maximum number of pages freeing stuff in case of memory out. ]
SeeAlso []
Definition at line 471 of file cuddSubsetSP.c.
References ALLOC, currentNodeDistPage, FREE, INITIAL_PAGES, maxNodeDistPages, memOut, nodeDistPage, nodeDistPageIndex, nodeDistPages, and nodeDistPageSize.
Referenced by CreatePathTable(), and CreateTopDist().
static void ResizeQueuePages () [static]
Function********************************************************************
Synopsis [Resize the number of pages allocated to store nodes in the BFS traversal of the Bdd .]
Description [Resize the number of pages allocated to store nodes in the BFS traversal of the Bdd. The procedure moves the counter to the next page when the end of the page is reached and allocates new pages when necessary.]
SideEffects [Changes the size of pages, page, page index, maximum number of pages freeing stuff in case of memory out. ]
SeeAlso []
Definition at line 534 of file cuddSubsetSP.c.
References ALLOC, currentQueuePage, FREE, INITIAL_PAGES, maxQueuePages, memOut, queuePage, queuePageIndex, queuePages, and queuePageSize.
Referenced by CreateTopDist().
static enum st_retval stPathTableDdFree (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Procedure to free te result dds stored in the NodeDist pages.]
Description [None]
SideEffects [None]
SeeAlso []
Definition at line 1603 of file cuddSubsetSP.c.
References NodeDist::compResult, Cudd_RecursiveDeref(), NodeDist::regResult, and ST_CONTINUE.
Referenced by cuddSubsetShortPaths().
Variable Documentation
NodeDist_t* currentNodeDistPage [static]
Definition at line 119 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeNodeDistPages().
DdNode** currentQueuePage [static]
Definition at line 126 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeQueuePages().
char rcsid [] DD_UNUSED = `$Id: cuddSubsetSP.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 101 of file cuddSubsetSP.c.
int maxNodeDistPages [static]
Definition at line 118 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), and ResizeNodeDistPages().
int maxQueuePages [static]
Definition at line 125 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), and ResizeQueuePages().
int memOut [static]
Definition at line 111 of file cuddSubsetSP.c.
int nodeDistPage [static]
Definition at line 116 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), cuddSubsetShortPaths(), and ResizeNodeDistPages().
int nodeDistPageIndex [static]
Definition at line 115 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeNodeDistPages().
NodeDist_t** nodeDistPages [static]
Definition at line 114 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), cuddSubsetShortPaths(), and ResizeNodeDistPages().
int nodeDistPageSize = DEFAULT_NODE_DIST_PAGE_SIZE [static]
Definition at line 117 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeNodeDistPages().
DdNode * one [static]
Definition at line 112 of file cuddSubsetSP.c.
int queuePage [static]
Definition at line 123 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeQueuePages().
int queuePageIndex [static]
Definition at line 122 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeQueuePages().
DdNode*** queuePages [static]
Definition at line 121 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeQueuePages().
int queuePageSize = DEFAULT_PAGE_SIZE [static]
Definition at line 124 of file cuddSubsetSP.c.
Referenced by CreatePathTable(), CreateTopDist(), and ResizeQueuePages().
DdNode* zero [static]
Definition at line 112 of file cuddSubsetSP.c.