cuddBddCorr.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct hashEntry
Typedefs
typedef hashEntry HashEntry
Functions
static double bddCorrelationAux ARGS ((DdManager *dd, DdNode *f, DdNode *g, st_table *table))
static double bddCorrelationWeightsAux ARGS ((DdManager *dd, DdNode *f, DdNode *g, double *prob, st_table *table))
static int CorrelCompare ARGS ((const char *key1, const char *key2))
static int CorrelHash ARGS ((char *key, int modulus))
static enum st_retval CorrelCleanUp ARGS ((char *key, char *value, char *arg))
double Cudd_bddCorrelation (DdManager *manager, DdNode *f, DdNode *g)
double Cudd_bddCorrelationWeights (DdManager *manager, DdNode *f, DdNode *g, double *prob)
static double bddCorrelationAux (DdManager *dd, DdNode *f, DdNode *g, st_table *table)
static double bddCorrelationWeightsAux (DdManager *dd, DdNode *f, DdNode *g, double *prob, st_table *table)
static int CorrelCompare (const char *key1, const char *key2)
static int CorrelHash (char *key, int modulus)
static enum st_retval CorrelCleanUp (char *key, char *value, char *arg)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddBddCorr.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Typedef Documentation
typedef struct hashEntry HashEntry
CFile***********************************************************************
FileName [cuddBddCorr.c]
PackageName [cudd]
Synopsis [Correlation between BDDs.]
Description [External procedures included in this module:
Cudd_bddCorrelation()
Cudd_bddCorrelationWeights()
Static procedures included in this module:
bddCorrelationAux()
bddCorrelationWeightsAux()
CorrelCompare()
CorrelHash()
CorrelCleanUp()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Function Documentation
static enum st_retval CorrelCleanUp ARGS ((char *key, char *value, char *arg)) [static]
static int CorrelHash ARGS ((char *key, int modulus)) [static]
static int CorrelCompare ARGS ((const char *key1, const char *key2)) [static]
static double bddCorrelationWeightsAux ARGS ((DdManager *dd, DdNode *f, DdNode *g, double *prob, st_table *table)) [static]
static double bddCorrelationAux ARGS ((DdManager *dd, DdNode *f, DdNode *g, st_table *table)) [static]
AutomaticStart
static double bddCorrelationAux (DdManager * dd, DdNode * f, DdNode * g, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddCorrelation.]
Description [Performs the recursive step of Cudd_bddCorrelation. Returns the fraction of minterms in the ON-set of the EXNOR of f and g.]
SideEffects [None]
SeeAlso [bddCorrelationWeightsAux]
Definition at line 202 of file cuddBddCorr.c.
References ALLOC, Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddI, cuddT, entry, DdManager::errorCode, FREE, DdNode::index, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_bddCorrelation().
static double bddCorrelationWeightsAux (DdManager * dd, DdNode * f, DdNode * g, double * prob, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddCorrelationWeigths.]
Description []
SideEffects [None]
SeeAlso [bddCorrelationAux]
Definition at line 303 of file cuddBddCorr.c.
References ALLOC, Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddI, cuddT, entry, DdManager::errorCode, FREE, DdNode::index, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_bddCorrelationWeights().
static enum st_retval CorrelCleanUp (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees memory associated with hash table.]
Description [Frees memory associated with hash table. Returns ST_CONTINUE.]
SideEffects [None]
Definition at line 467 of file cuddBddCorr.c.
References entry, FREE, and ST_CONTINUE.
Referenced by Cudd_bddCorrelation(), and Cudd_bddCorrelationWeights().
static int CorrelCompare (const char * key1, const char * key2) [static]
Function********************************************************************
Synopsis [Compares two hash table entries.]
Description [Compares two hash table entries. Returns 0 if they are identical; 1 otherwise.]
SideEffects [None]
Definition at line 410 of file cuddBddCorr.c.
References hashEntry::f, and hashEntry::g.
Referenced by Cudd_bddCorrelation(), and Cudd_bddCorrelationWeights().
static int CorrelHash (char * key, int modulus) [static]
Function********************************************************************
Synopsis [Hashes a hash table entry.]
Description [Hashes a hash table entry. It is patterned after st_strhash. Returns a value between 0 and modulus.]
SideEffects [None]
Definition at line 437 of file cuddBddCorr.c.
References entry.
Referenced by Cudd_bddCorrelation(), and Cudd_bddCorrelationWeights().
double Cudd_bddCorrelation (DdManager * manager, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the correlation of f and g.]
Description [Computes the correlation of f and g. If f == g, their correlation is 1. If f == g', their correlation is 0. Returns the fraction of minterms in the ON-set of the EXNOR of f and g. If it runs out of memory, returns (double)CUDD_OUT_OF_MEM.]
SideEffects [None]
SeeAlso [Cudd_bddCorrelationWeights]
Definition at line 112 of file cuddBddCorr.c.
References bddCorrelationAux(), CorrelCleanUp(), CorrelCompare(), CorrelHash(), CUDD_OUT_OF_MEM, NIL, st_foreach(), st_free_table(), and st_init_table().
double Cudd_bddCorrelationWeights (DdManager * manager, DdNode * f, DdNode * g, double * prob)
Function********************************************************************
Synopsis [Computes the correlation of f and g for given input probabilities.]
Description [Computes the correlation of f and g for given input probabilities. On input, prob\[i\] is supposed to contain the probability of the i-th input variable to be 1. If f == g, their correlation is 1. If f == g', their correlation is 0. Returns the probability that f and g have the same value. If it runs out of memory, returns (double)CUDD_OUT_OF_MEM. The correlation of f and the constant one gives the probability of f.]
SideEffects [None]
SeeAlso [Cudd_bddCorrelation]
Definition at line 154 of file cuddBddCorr.c.
References bddCorrelationWeightsAux(), CorrelCleanUp(), CorrelCompare(), CorrelHash(), CUDD_OUT_OF_MEM, NIL, st_foreach(), st_free_table(), and st_init_table().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddBddCorr.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 65 of file cuddBddCorr.c.