cuddReorder.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define DD_MAX_SUBTABLE_SPARSITY 8
#define DD_SHRINK_FACTOR 2
Functions
static int ddUniqueCompare ARGS ((int *ptrX, int *ptrY))
static Move *ddSwapAny ARGS ((DdManager *table, int x, int y))
static int ddSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh))
static Move *ddSiftingUp ARGS ((DdManager *table, int y, int xLow))
static Move *ddSiftingDown ARGS ((DdManager *table, int x, int xHigh))
static int ddSiftingBackward ARGS ((DdManager *table, int size, Move *moves))
static int ddReorderPreprocess ARGS ((DdManager *table))
static int ddShuffle ARGS ((DdManager *table, int *permutation))
static int ddSiftUp ARGS ((DdManager *table, int x, int xLow))
static void bddFixTree ARGS ((DdManager *table, MtrNode *treenode))
int Cudd_ReduceHeap (DdManager *table, Cudd_ReorderingType heuristic, int minsize)
int Cudd_ShuffleHeap (DdManager *table, int *permutation)
DdNode * cuddDynamicAllocNode (DdManager *table)
int cuddSifting (DdManager *table, int lower, int upper)
int cuddSwapping (DdManager *table, int lower, int upper, Cudd_ReorderingType heuristic)
int cuddNextHigh (DdManager *table, int x)
int cuddNextLow (DdManager *table, int x)
int cuddSwapInPlace (DdManager *table, int x, int y)
int cuddBddAlignToZdd (DdManager *table)
static int ddUniqueCompare (int *ptrX, int *ptrY)
static Move * ddSwapAny (DdManager *table, int x, int y)
static int ddSiftingAux (DdManager *table, int x, int xLow, int xHigh)
static Move * ddSiftingUp (DdManager *table, int y, int xLow)
static Move * ddSiftingDown (DdManager *table, int x, int xHigh)
static int ddSiftingBackward (DdManager *table, int size, Move *moves)
static int ddReorderPreprocess (DdManager *table)
static int ddReorderPostprocess (DdManager *table)
static int ddShuffle (DdManager *table, int *permutation)
static int ddSiftUp (DdManager *table, int x, int xLow)
static void bddFixTree (DdManager *table, MtrNode *treenode)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddReorder.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int * entry
int ddTotalNumberSwapping
Define Documentation
#define DD_MAX_SUBTABLE_SPARSITY 8
CFile***********************************************************************
FileName [cuddReorder.c]
PackageName [cudd]
Synopsis [Functions for dynamic variable reordering.]
Description [External procedures included in this file:
Cudd_ReduceHeap()
Cudd_ShuffleHeap()
Internal procedures included in this module:
cuddDynamicAllocNode()
cuddSifting()
cuddSwapping()
cuddNextHigh()
cuddNextLow()
cuddSwapInPlace()
cuddBddAlignToZdd()
Static procedures included in this module:
ddUniqueCompare()
ddSwapAny()
ddSiftingAux()
ddSiftingUp()
ddSiftingDown()
ddSiftingBackward()
ddReorderPreprocess()
ddReorderPostprocess()
ddShuffle()
ddSiftUp()
bddFixTree()
]
Author [Shipra Panda, Bernard Plessier, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 57 of file cuddReorder.c.
Referenced by ddReorderPostprocess(), and zddReorderPostprocess().
#define DD_SHRINK_FACTOR 2
Definition at line 58 of file cuddReorder.c.
Function Documentation
static void bddFixTree ARGS ((DdManager *table, MtrNode *treenode)) [static]
static int ddSiftUp ARGS ((DdManager *table, int x, int xLow)) [static]
static int ddShuffle ARGS ((DdManager *table, int *permutation)) [static]
static int ddReorderPreprocess ARGS ((DdManager *table)) [static]
static int ddSiftingBackward ARGS ((DdManager *table, int size, Move *moves)) [static]
static Move* ddSiftingDown ARGS ((DdManager *table, int x, int xHigh)) [static]
static Move* ddSiftingUp ARGS ((DdManager *table, int y, int xLow)) [static]
static int ddSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh)) [static]
static Move* ddSwapAny ARGS ((DdManager *table, int x, int y)) [static]
static int ddUniqueCompare ARGS ((int *ptrX, int *ptrY)) [static]
AutomaticStart
static void bddFixTree (DdManager * table, MtrNode * treenode) [static]
Function********************************************************************
Synopsis [Fixes the BDD variable group tree after a shuffle.]
Description [Fixes the BDD variable group tree after a shuffle. Assumes that the order of the variables in a terminal node has not been changed.]
SideEffects [Changes the BDD variable group tree.]
SeeAlso []
Definition at line 1853 of file cuddReorder.c.
References MtrNode::child, MtrNode::index, MtrNode::low, MtrNode::parent, DdManager::perm, DdManager::size, and MtrNode::younger.
Referenced by cuddBddAlignToZdd().
int Cudd_ReduceHeap (DdManager * table, Cudd_ReorderingType heuristic, int minsize)
Function********************************************************************
Synopsis [Main dynamic reordering routine.]
Description [Main dynamic reordering routine. Calls one of the possible reordering procedures:
Swapping
Sifting
Symmetric Sifting
Group Sifting
Window Permutation
Simulated Annealing
Genetic Algorithm
Dynamic Programming (exact)
For sifting, symmetric sifting, group sifting, and window permutation it is possible to request reordering to convergence.
The core of all methods is the reordering procedure cuddSwapInPlace() which swaps two adjacent variables and is based on Rudell's paper. Returns 1 in case of success; 0 otherwise. In the case of symmetric sifting (with and without convergence) returns 1 plus the number of symmetric variables, in case of success.]
SideEffects [Changes the variable order for all diagrams and clears the cache.]
Definition at line 145 of file cuddReorder.c.
References DdManager::autoMethod, DdManager::constants, CUDD_REORDER_ANNEALING, CUDD_REORDER_EXACT, CUDD_REORDER_GENETIC, CUDD_REORDER_GROUP_SIFT, CUDD_REORDER_GROUP_SIFT_CONV, CUDD_REORDER_LINEAR, CUDD_REORDER_LINEAR_CONVERGE, CUDD_REORDER_NONE, CUDD_REORDER_RANDOM, CUDD_REORDER_RANDOM_PIVOT, CUDD_REORDER_SAME, CUDD_REORDER_SIFT, CUDD_REORDER_SIFT_CONVERGE, CUDD_REORDER_SYMM_SIFT, CUDD_REORDER_SYMM_SIFT_CONV, CUDD_REORDER_WINDOW2, CUDD_REORDER_WINDOW2_CONV, CUDD_REORDER_WINDOW3, CUDD_REORDER_WINDOW3_CONV, CUDD_REORDER_WINDOW4, CUDD_REORDER_WINDOW4_CONV, cuddTreeSifting(), cuddZddAlignToBdd(), DD_DYN_RATIO, ddReorderPostprocess(), ddReorderPreprocess(), ddTotalNumberSwapping, DdManager::dead, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdHook::next, DdManager::nextDyn, DdManager::postReorderingHook, DdManager::preReorderingHook, DdManager::realign, DdManager::reordered, DdManager::reorderings, DdManager::reordTime, result, and util_cpu_time().
Referenced by cuddUniqueInter().
int Cudd_ShuffleHeap (DdManager * table, int * permutation)
Function********************************************************************
Synopsis [Reorders variables according to given permutation.]
Description [Reorders variables according to given permutation. The i-th entry of the permutation array contains the index of the variable that should be brought to the i-th level. The size of the array should be equal or greater to the number of variables currently in use. Returns 1 in case of success; 0 otherwise.]
SideEffects [Changes the variable order for all diagrams and clears the cache.]
SeeAlso [Cudd_ReduceHeap]
Definition at line 296 of file cuddReorder.c.
References ddReorderPostprocess(), ddReorderPreprocess(), ddShuffle(), and result.
int cuddBddAlignToZdd (DdManager * table)
Function********************************************************************
Synopsis [Reorders ZDD variables according to the order of the BDD variables.]
Description [Reorders BDD variables according to the order of the ZDD variables. This function can be called at the end of ZDD reordering to insure that the order of the BDD variables is consistent with the order of the ZDD variables. The number of ZDD variables must be a multiple of the number of BDD variables. Let M be the ratio of the two numbers. cuddBddAlignToZdd then considers the ZDD variables from M*i to (M+1)*i-1 as corresponding to BDD variable i. This function should be normally called from Cudd_zddReduceHeap, which clears the cache. Returns 1 in case of success; 0 otherwise.]
SideEffects [Changes the BDD variable order for all diagrams and performs garbage collection of the BDD unique table.]
SeeAlso [Cudd_ShuffleHeap Cudd_zddReduceHeap]
Definition at line 1018 of file cuddReorder.c.
References ALLOC, bddFixTree(), CUDD_MEMORY_OUT, cuddGarbageCollect(), cuddInitInteract(), ddShuffle(), DdManager::errorCode, FREE, DdManager::invpermZ, result, DdManager::size, and DdManager::sizeZ.
Referenced by Cudd_zddReduceHeap().
DdNode* cuddDynamicAllocNode (DdManager * table)
Function********************************************************************
Synopsis [Dynamically allocates a Node.]
Description [Dynamically allocates a Node. This procedure is similar to cuddAllocNode in Cudd_Table.c, but it does not attempt garbage collection, because during reordering there are no dead nodes. Returns a pointer to a new node if successful; NULL is memory is full.]
SideEffects [None]
SeeAlso [cuddAllocNode]
Definition at line 335 of file cuddReorder.c.
References ALLOC, CUDD_MEMORY_OUT, DD_MEM_CHUNK, DdManager::errorCode, DdManager::memoryList, DdManager::memused, DdNode::next, and DdManager::nextFree.
Referenced by cuddLinearInPlace(), cuddSwapInPlace(), cuddZddLinearDown(), cuddZddLinearUp(), cuddZddSiftingDown(), cuddZddSiftingUp(), cuddZddSwapInPlace(), cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), cuddZddUndoMoves(), ddExchange(), ddGroupMove(), ddGroupSiftingDown(), ddGroupSiftingUp(), ddJumpingDown(), ddJumpingUp(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), ddSiftingDown(), ddSiftingUp(), ddSwapAny(), ddSymmGroupMove(), ddSymmSiftingDown(), ddSymmSiftingUp(), ddUndoMoves(), zddGroupMove(), zddGroupSiftingDown(), zddGroupSiftingUp(), and zddSwapAny().
int cuddNextHigh (DdManager * table, int x)
Function********************************************************************
Synopsis [Finds the next subtable with a larger index.]
Description [Finds the next subtable with a larger index. Returns the index.]
SideEffects [None]
SeeAlso [cuddNextLow]
Definition at line 607 of file cuddReorder.c.
Referenced by cuddLinearInPlace(), cuddSwapInPlace(), ddExchange(), ddGroupMove(), ddGroupMoveBackward(), ddGroupSiftingAux(), ddGroupSiftingDown(), ddJumpingAux(), ddJumpingDown(), ddLinearAndSiftingDown(), ddSiftingDown(), ddSwapAny(), ddSymmSiftingAux(), ddSymmSiftingConvAux(), and ddSymmSiftingDown().
int cuddNextLow (DdManager * table, int x)
Function********************************************************************
Synopsis [Finds the next subtable with a smaller index.]
Description [Finds the next subtable with a smaller index. Returns the index.]
SideEffects [None]
SeeAlso [cuddNextHigh]
Definition at line 629 of file cuddReorder.c.
Referenced by ddExchange(), ddGroupMove(), ddGroupMoveBackward(), ddGroupSiftingUp(), ddJumpingAux(), ddJumpingUp(), ddLinearAndSiftingUp(), ddSiftingUp(), ddSiftUp(), ddSwapAny(), ddSymmGroupMoveBackward(), ddSymmSiftingUp(), restoreOrder(), and sift_up().
int cuddSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Implementation of Rudell's sifting algorithm.]
Description [Implementation of Rudell's sifting algorithm. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique table.
Sift the variable up and down, remembering each time the total size of the DD heap.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 401 of file cuddReorder.c.
References ALLOC, CUDD_MEMORY_OUT, ddMin, ddSiftingAux(), ddTotalNumberSwapping, ddUniqueCompare(), entry, DdManager::errorCode, FREE, DdManager::isolated, DdManager::keys, DdSubtable::keys, DdManager::perm, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::size, size, and DdManager::subtables.
Referenced by build_dd(), cuddAnnealing(), cuddGa(), and ddReorderChildren().
int cuddSwapInPlace (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Swaps two adjacent variables.]
Description [Swaps two adjacent variables. It assumes that no dead nodes are present on entry to this procedure. The procedure then guarantees that no dead nodes will be present when it terminates. cuddSwapInPlace assumes that x < y. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
Definition at line 652 of file cuddReorder.c.
References assert, Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddDeallocNode, cuddDynamicAllocNode(), cuddE, cuddNextHigh(), cuddSatDec, cuddSatInc, cuddT, cuddTestInteract(), ddHash, ddTotalNumberSwapping, DdSubtable::dead, DdNode::index, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdSubtable::slots, DdManager::subtables, and DdManager::vars.
Referenced by ddExchange(), ddGroupMove(), ddGroupMoveBackward(), ddGroupSiftingDown(), ddGroupSiftingUp(), ddJumpingDown(), ddJumpingUp(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), ddPermuteWindow3(), ddPermuteWindow4(), ddSiftingDown(), ddSiftingUp(), ddSiftUp(), ddSwapAny(), ddSymmGroupMove(), ddSymmGroupMoveBackward(), ddSymmSiftingDown(), ddSymmSiftingUp(), ddUndoMoves(), ddWindow2(), ddWindowConv2(), restoreOrder(), and sift_up().
int cuddSwapping (DdManager * table, int lower, int upper, Cudd_ReorderingType heuristic)
Function********************************************************************
Synopsis [Reorders variables by a sequence of (non-adjacent) swaps.]
Description [Implementation of Plessier's algorithm that reorders variables by a sequence of (non-adjacent) swaps.
Select two variables (RANDOM or HEURISTIC).
Permute these variables.
If the nodes have decreased accept the permutation.
Otherwise reconstruct the original heap.
Loop.
Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 496 of file cuddReorder.c.
References assert, Cudd_Random(), CUDD_REORDER_RANDOM_PIVOT, cuddDeallocNode, ddSiftingBackward(), ddSwapAny(), ddTotalNumberSwapping, DdManager::isolated, DdManager::keys, DdSubtable::keys, max, Move::next, result, DdManager::siftMaxSwap, size, and DdManager::subtables.
Referenced by ddReorderChildren().
static int ddReorderPostprocess (DdManager * table) [static]
Function********************************************************************
Synopsis [Shrinks almost empty subtables at the end of reordering to guarantee that they have a reasonable load factor.]
Description [Frees the interaction matrix and shrinks almost empty subtables at the end of reordering to guarantee that they have a reasonable load factor. However, if there many nodes are being reclaimed, then no resizing occurs. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1632 of file cuddReorder.c.
References ALLOC, DdManager::allocated, Cudd_OutOfMem(), CUDD_UNIQUE_SLOTS, cuddE, cuddT, DD_MAX_SUBTABLE_SPARSITY, ddHash, ddMin, FREE, DdManager::gcPercent, DdManager::interact, DdSubtable::keys, DdManager::maxCache, DdManager::maxCacheHard, DdSubtable::maxKeys, DdManager::memused, DdManager::minDead, MMoutOfMemory, DdNode::next, DdSubtable::nodelist, DdManager::reclaimed, DdSubtable::shift, DdManager::size, DdManager::slots, DdSubtable::slots, and DdManager::subtables.
Referenced by Cudd_ReduceHeap(), and Cudd_ShuffleHeap().
static int ddReorderPreprocess (DdManager * table) [static]
Function********************************************************************
Synopsis [Prepares the DD heap for dynamic reordering.]
Description [Prepares the DD heap for dynamic reordering. Does garbage collection, to guarantee that there are no dead nodes; clears the cache, which is invalidated by dynamic reordering; initializes the number of isolated projection functions; and initializes the interaction matrix. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1589 of file cuddReorder.c.
References cuddCacheFlush(), cuddGarbageCollect(), cuddInitInteract(), cuddLocalCacheClearAll(), DdManager::isolated, DdNode::ref, DdManager::size, and DdManager::vars.
Referenced by Cudd_ReduceHeap(), and Cudd_ShuffleHeap().
static int ddShuffle (DdManager * table, int * permutation) [static]
Function********************************************************************
Synopsis [Reorders variables according to a given permutation.]
Description [Reorders variables according to a given permutation. The i-th permutation array contains the index of the variable that should be brought to the i-th level. ddShuffle assumes that no dead nodes are present and that the interaction matrix is properly initialized. The reordering is achieved by a series of upward sifts. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1742 of file cuddReorder.c.
References ddSiftUp(), ddTotalNumberSwapping, DdManager::isolated, DdManager::keys, numvars, DdManager::perm, result, DdManager::size, and util_cpu_time().
static int ddSiftingAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. Finds the best position and does the required changes. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 1255 of file cuddReorder.c.
References CUDD_OUT_OF_MEM, cuddDeallocNode, ddSiftingBackward(), ddSiftingDown(), ddSiftingUp(), DdManager::isolated, DdManager::keys, Move::next, result, Move::x, and Move::y.
Referenced by cuddSifting().
static int ddSiftingBackward (DdManager * table, int size, Move * moves) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the DD heap to the position giving the minimum size.]
Description [Given a set of moves, returns the DD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1550 of file cuddReorder.c.
References Move::next, and Move::size.
Referenced by cuddSwapping(), and ddSiftingAux().
static Move* ddSiftingDown (DdManager * table, int x, int xHigh) [static]
Function********************************************************************
Synopsis [Sifts a variable down.]
Description [Sifts a variable down. Moves x down until either it reaches the bound (xHigh) or the size of the DD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
Definition at line 1458 of file cuddReorder.c.
References assert, CUDD_OUT_OF_MEM, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddSwapInPlace(), cuddTestInteract(), DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, Move::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddSiftingAux().
static Move* ddSiftingUp (DdManager * table, int y, int xLow) [static]
Function********************************************************************
Synopsis [Sifts a variable up.]
Description [Sifts a variable up. Moves y up until either it reaches the bound (xLow) or the size of the DD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
Definition at line 1358 of file cuddReorder.c.
References assert, CUDD_OUT_OF_MEM, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextLow(), cuddSwapInPlace(), cuddTestInteract(), DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, Move::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddSiftingAux().
static int ddSiftUp (DdManager * table, int x, int xLow) [static]
Function********************************************************************
Synopsis [Moves one variable up.]
Description [Takes a variable from position x and sifts it up to position xLow; xLow should be less than or equal to x. Returns 1 if successful; 0 otherwise]
SideEffects [None]
SeeAlso []
Definition at line 1817 of file cuddReorder.c.
References cuddNextLow(), cuddSwapInPlace(), and size.
static Move* ddSwapAny (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Swaps any two variables.]
Description [Swaps any two variables. Returns the set of moves.]
SideEffects [None]
Definition at line 1114 of file cuddReorder.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddNextLow(), cuddSwapInPlace(), DdManager::isolated, DdManager::keys, DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddSwapping().
static int ddUniqueCompare (int * ptrX, int * ptrY) [static]
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
Definition at line 1090 of file cuddReorder.c.
References entry.
Referenced by cuddSifting().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddReorder.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 73 of file cuddReorder.c.
int ddTotalNumberSwapping
Definition at line 78 of file cuddReorder.c.
int* entry [static]
Definition at line 76 of file cuddReorder.c.