cuddAddAbs.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static int addCheckPositiveCube ARGS ((DdManager *manager, DdNode *cube))
DdNode * Cudd_addExistAbstract (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * Cudd_addUnivAbstract (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * Cudd_addOrAbstract (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * cuddAddExistAbstractRecur (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * cuddAddUnivAbstractRecur (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * cuddAddOrAbstractRecur (DdManager *manager, DdNode *f, DdNode *cube)
static int addCheckPositiveCube (DdManager *manager, DdNode *cube)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static DdNode * two
Function Documentation
static int addCheckPositiveCube (DdManager * manager, DdNode * cube) [static]
Function********************************************************************
Synopsis [Checks whether cube is an ADD representing the product of positive literals.]
Description [Checks whether cube is an ADD representing the product of positive literals. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 549 of file cuddAddAbs.c.
References DdGen::cube, Cudd_IsComplement, cuddE, cuddIsConstant, cuddT, DD_ONE, DD_ZERO, and DdGen::manager.
Referenced by Cudd_addExistAbstract(), Cudd_addOrAbstract(), and Cudd_addUnivAbstract().
static int addCheckPositiveCube ARGS ((DdManager *manager, DdNode *cube)) [static]
AutomaticStart
DdNode* Cudd_addExistAbstract (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Existentially Abstracts all the variables in cube from f.]
Description [Abstracts all the variables in cube from f by summing over all possible values taken by the variables. Returns the abstracted ADD.]
SideEffects [None]
SeeAlso [Cudd_addUnivAbstract Cudd_bddExistAbstract Cudd_addOrAbstract]
Definition at line 100 of file cuddAddAbs.c.
References addCheckPositiveCube(), DdGen::cube, Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddAddExistAbstractRecur(), cuddDeref, cuddRef, cuddUniqueConst(), DdGen::manager, DdManager::reordered, and two.
Referenced by Cudd_addTimesPlus(), and cuddAddExistAbstractRecur().
DdNode* Cudd_addOrAbstract (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Disjunctively abstracts all the variables in cube from the 0-1 ADD f.]
Description [Abstracts all the variables in cube from the 0-1 ADD f by taking the disjunction over all possible values taken by the variables. Returns the abstracted ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addUnivAbstract Cudd_addExistAbstract]
Definition at line 187 of file cuddAddAbs.c.
References addCheckPositiveCube(), DdGen::cube, cuddAddOrAbstractRecur(), DdGen::manager, and DdManager::reordered.
Referenced by cuddAddOrAbstractRecur().
DdNode* Cudd_addUnivAbstract (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Universally Abstracts all the variables in cube from f.]
Description [Abstracts all the variables in cube from f by taking the product over all possible values taken by the variable. Returns the abstracted ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addExistAbstract Cudd_bddUnivAbstract Cudd_addOrAbstract]
Definition at line 149 of file cuddAddAbs.c.
References addCheckPositiveCube(), DdGen::cube, cuddAddUnivAbstractRecur(), DdGen::manager, and DdManager::reordered.
Referenced by cuddAddUnivAbstractRecur().
DdNode* cuddAddExistAbstractRecur (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addExistAbstract.]
Description [Performs the recursive step of Cudd_addExistAbstract. Returns the ADD obtained by abstracting the variables of cube from f, if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 227 of file cuddAddAbs.c.
References DdGen::cube, Cudd_addExistAbstract(), Cudd_addPlus(), Cudd_addTimes(), Cudd_RecursiveDeref(), cuddAddApplyRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ZERO, DdNode::index, DdGen::manager, two, and zero.
Referenced by Cudd_addExistAbstract(), and cuddAddNonSimComposeRecur().
DdNode* cuddAddOrAbstractRecur (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addOrAbstract.]
Description [Performs the recursive step of Cudd_addOrAbstract. Returns the ADD obtained by abstracting the variables of cube from f, if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 436 of file cuddAddAbs.c.
References DdGen::cube, Cudd_addOr(), Cudd_addOrAbstract(), Cudd_RecursiveDeref(), cuddAddApplyRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, DdGen::manager, and one.
Referenced by Cudd_addOrAbstract().
DdNode* cuddAddUnivAbstractRecur (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addUnivAbstract.]
Description [Performs the recursive step of Cudd_addUnivAbstract. Returns the ADD obtained by abstracting the variables of cube from f, if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 330 of file cuddAddAbs.c.
References DdGen::cube, Cudd_addTimes(), Cudd_addUnivAbstract(), Cudd_RecursiveDeref(), cuddAddApplyRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, DdGen::manager, one, and zero.
Referenced by Cudd_addUnivAbstract().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddAbs.c]
PackageName [cudd]
Synopsis [Quantification functions for ADDs.]
Description [External procedures included in this module:
Cudd_addExistAbstract()
Cudd_addUnivAbstract()
Cudd_addOrAbstract()
Internal procedures included in this module:
cuddAddExistAbstractRecur()
cuddAddUnivAbstractRecur()
cuddAddOrAbstractRecur()
Static procedures included in this module:
addCheckPositiveCube()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 60 of file cuddAddAbs.c.
DdNode* two [static]
Definition at line 63 of file cuddAddAbs.c.
Referenced by Cudd_addExistAbstract(), and cuddAddExistAbstractRecur().