cuddCache.c File Reference
#include <config.h>
#include <string.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
int cuddInitCache (DdManager *unique, unsigned int cacheSize, unsigned int maxCacheSize)
void cuddCacheInsert (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *, DdNode *), DdNode *f, DdNode *g, DdNode *h, DdNode *data)
void cuddCacheInsert2 (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *), DdNode *f, DdNode *g, DdNode *data)
void cuddCacheInsert1 (DdManager *table, DdNode *(*op)(DdManager *, DdNode *), DdNode *f, DdNode *data)
DdNode * cuddCacheLookup (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *, DdNode *), DdNode *f, DdNode *g, DdNode *h)
DdNode * cuddCacheLookupZdd (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *, DdNode *), DdNode *f, DdNode *g, DdNode *h)
DdNode * cuddCacheLookup2 (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *), DdNode *f, DdNode *g)
DdNode * cuddCacheLookup1 (DdManager *table, DdNode *(*op)(DdManager *, DdNode *), DdNode *f)
DdNode * cuddCacheLookup2Zdd (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *), DdNode *f, DdNode *g)
DdNode * cuddCacheLookup1Zdd (DdManager *table, DdNode *(*op)(DdManager *, DdNode *), DdNode *f)
DdNode * cuddConstantLookup (DdManager *table, DdNode *(*op)(DdManager *, DdNode *, DdNode *, DdNode *), DdNode *f, DdNode *g, DdNode *h)
int cuddCacheProfile (DdManager *table, FILE *fp)
void cuddCacheResize (DdManager *table)
void cuddCacheFlush (DdManager *table)
int cuddComputeFloorLog2 (unsigned int value)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddCache.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
void cuddCacheFlush (DdManager * table)
Function********************************************************************
Synopsis [Flushes the cache.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 916 of file cuddCache.c.
References DdManager::cache, DdManager::cachedeletions, DdManager::cacheSlots, and DdCache::data.
Referenced by ddReorderPreprocess(), and zddReorderPreprocess().
void cuddCacheInsert (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *, DdNode *) op, DdNode * f, DdNode * g, DdNode * h, DdNode * data)
Function********************************************************************
Synopsis [Inserts a result in the cache.]
Description []
SideEffects [None]
SeeAlso [cuddCacheInsert2 cuddCacheInsert1]
Definition at line 181 of file cuddCache.c.
References DdManager::cache, DdManager::cachecollisions, DdManager::cacheinserts, DdManager::cacheShift, ddCHash, and entry.
Referenced by addBddDoInterval(), Cudd_addIteConstant(), Cudd_bddIteConstant(), Cudd_EquivDC(), cuddAddComposeRecur(), cuddAddIteRecur(), cuddBddAndAbstractRecur(), cuddBddClipAndAbsRecur(), cuddBddComposeRecur(), cuddBddIteRecur(), cuddBddXorExistAbstractRecur(), and cuddZddIte().
void cuddCacheInsert1 (DdManager * table, DdNode *(*)(DdManager *, DdNode *) op, DdNode * f, DdNode * data)
Function********************************************************************
Synopsis [Inserts a result in the cache for a function with two operands.]
Description []
SideEffects [None]
SeeAlso [cuddCacheInsert cuddCacheInsert2]
Definition at line 268 of file cuddCache.c.
References DdManager::cache, DdManager::cachecollisions, DdManager::cacheinserts, DdManager::cacheShift, ddCHash2, and entry.
Referenced by addBddDoPattern(), Cudd_addFindMax(), Cudd_addFindMin(), cuddAddCmplRecur(), cuddAddNegateRecur(), cuddAddRoundOffRecur(), ddBddToAddRecur(), ddFindEssentialRecur(), zddPortFromBddStep(), and zddPortToBddStep().
void cuddCacheInsert2 (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *) op, DdNode * f, DdNode * g, DdNode * data)
Function********************************************************************
Synopsis [Inserts a result in the cache for a function with two operands.]
Description []
SideEffects [None]
SeeAlso [cuddCacheInsert cuddCacheInsert1]
Definition at line 225 of file cuddCache.c.
References DdManager::cache, DdManager::cachecollisions, DdManager::cacheinserts, DdManager::cacheShift, ddCHash2, and entry.
Referenced by addBddDoIthBit(), addBddDoStrictThreshold(), addBddDoThreshold(), addDoIthBit(), addTriangleRecur(), Cudd_addEvalConst(), Cudd_addLeq(), Cudd_bddLeq(), Cudd_bddVarIsDependent(), Cudd_Decreasing(), Cudd_EqualSupNorm(), Cudd_zddDiffConst(), cuddAddApplyRecur(), cuddAddConstrainRecur(), cuddAddExistAbstractRecur(), cuddAddOrAbstractRecur(), cuddAddRestrictRecur(), cuddAddScalarInverseRecur(), cuddAddUnivAbstractRecur(), cuddBddAndRecur(), cuddBddBooleanDiffRecur(), cuddBddCharToVect(), cuddBddClippingAndRecur(), cuddBddConstrainRecur(), cuddBddExistAbstractRecur(), cuddBddIntersectRecur(), cuddBddIsop(), cuddBddLiteralSetIntersectionRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddXorRecur(), cuddCofactorRecur(), cuddCProjectionRecur(), cuddZddChangeAux(), cuddZddDiff(), cuddZddDivide(), cuddZddDivideF(), cuddZddIntersect(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddUnion(), cuddZddWeakDiv(), cuddZddWeakDivF(), zdd_subset0_aux(), and zdd_subset1_aux().
DdNode* cuddCacheLookup (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *, DdNode *) op, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f, g, and h.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookup2 cuddCacheLookup1]
Definition at line 311 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaim(), DdCache::data, ddCHash, DdCache::f, DdCache::g, DdCache::h, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by addBddDoInterval(), Cudd_EquivDC(), cuddAddComposeRecur(), cuddAddIteRecur(), cuddAddNonSimComposeRecur(), cuddBddAndAbstractRecur(), cuddBddClipAndAbsRecur(), cuddBddComposeRecur(), cuddBddIteRecur(), and cuddBddXorExistAbstractRecur().
DdNode* cuddCacheLookup1 (DdManager * table, DdNode *(*)(DdManager *, DdNode *) op, DdNode * f)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookup cuddCacheLookup2]
Definition at line 477 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaim(), DdCache::data, ddCHash2, DdCache::f, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by addBddDoPattern(), Cudd_addFindMax(), Cudd_addFindMin(), cuddAddCmplRecur(), cuddAddNegateRecur(), cuddAddRoundOffRecur(), ddBddToAddRecur(), ddFindEssentialRecur(), and zddPortToBddStep().
DdNode* cuddCacheLookup1Zdd (DdManager * table, DdNode *(*)(DdManager *, DdNode *) op, DdNode * f)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookupZdd cuddCacheLookup2Zdd]
Definition at line 585 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaimZdd(), DdCache::data, ddCHash2, DdCache::f, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by zddPortFromBddStep().
DdNode* cuddCacheLookup2 (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *) op, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f and g.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookup cuddCacheLookup1]
Definition at line 423 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaim(), DdCache::data, ddCHash2, DdCache::f, DdCache::g, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by addBddDoIthBit(), addBddDoStrictThreshold(), addBddDoThreshold(), addDoIthBit(), addTriangleRecur(), Cudd_addLeq(), Cudd_bddLeq(), Cudd_bddVarIsDependent(), Cudd_Decreasing(), Cudd_EqualSupNorm(), cuddAddApplyRecur(), cuddAddConstrainRecur(), cuddAddExistAbstractRecur(), cuddAddOrAbstractRecur(), cuddAddRestrictRecur(), cuddAddScalarInverseRecur(), cuddAddUnivAbstractRecur(), cuddBddAndRecur(), cuddBddBooleanDiffRecur(), cuddBddCharToVect(), cuddBddClippingAndRecur(), cuddBddConstrainRecur(), cuddBddExistAbstractRecur(), cuddBddIntersectRecur(), cuddBddIsop(), cuddBddLiteralSetIntersectionRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddXorRecur(), cuddCofactorRecur(), cuddCProjectionRecur(), and cuddZddIsop().
DdNode* cuddCacheLookup2Zdd (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *) op, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f and g.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookupZdd cuddCacheLookup1Zdd]
Definition at line 531 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaimZdd(), DdCache::data, ddCHash2, DdCache::f, DdCache::g, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by Cudd_zddDiffConst(), cuddZddChangeAux(), cuddZddDiff(), cuddZddDivide(), cuddZddDivideF(), cuddZddIntersect(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddUnion(), cuddZddWeakDiv(), cuddZddWeakDivF(), zdd_subset0_aux(), and zdd_subset1_aux().
DdNode* cuddCacheLookupZdd (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *, DdNode *) op, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f, g, and h.]
Description [Returns the result if found; it returns NULL if no result is found.]
SideEffects [None]
SeeAlso [cuddCacheLookup2Zdd cuddCacheLookup1Zdd]
Definition at line 367 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_Regular, cuddCacheResize(), cuddReclaimZdd(), DdCache::data, ddCHash, DdCache::f, DdCache::g, DdCache::h, DdManager::maxCache, DdManager::minHit, DdCache::op, and DdNode::ref.
Referenced by cuddZddIte().
int cuddCacheProfile (DdManager * table, FILE * fp)
Function********************************************************************
Synopsis [Computes and prints a profile of the cache usage.]
Description [Computes and prints a profile of the cache usage. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 696 of file cuddCache.c.
References ALLOC, DdManager::cache, DdManager::cacheSlots, CUDD_MEMORY_OUT, DdManager::errorCode, FREE, and max.
Referenced by Cudd_PrintInfo().
void cuddCacheResize (DdManager * table)
Function********************************************************************
Synopsis [Resizes the cache.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 823 of file cuddCache.c.
References ALLOC, DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, Cudd_OutOfMem(), DdCache::data, ddCHash, ddCHash2, entry, DdCache::f, DdCache::g, DdCache::h, DdManager::maxCache, DdManager::maxCacheHard, DdManager::memused, MMoutOfMemory, and DdCache::op.
Referenced by cuddCacheLookup(), cuddCacheLookup1(), cuddCacheLookup1Zdd(), cuddCacheLookup2(), cuddCacheLookup2Zdd(), cuddCacheLookupZdd(), cuddConstantLookup(), and ddFixLimits().
int cuddComputeFloorLog2 (unsigned int value)
Function********************************************************************
Synopsis [Returns the floor of the logarithm to the base 2.]
Description [Returns the floor of the logarithm to the base 2. The input value is assumed to be greater than 0.]
SideEffects [None]
SeeAlso []
Definition at line 947 of file cuddCache.c.
References assert.
Referenced by cuddHashTableInit(), cuddInitCache(), cuddInitTable(), cuddInsertSubtables(), cuddLevelQueueInit(), cuddLocalCacheInit(), cuddResizeTableZdd(), and ddResizeTable().
DdNode* cuddConstantLookup (DdManager * table, DdNode *(*)(DdManager *, DdNode *, DdNode *, DdNode *) op, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Looks up in the cache for the result of op applied to f, g, and h.]
Description [Looks up in the cache for the result of op applied to f, g, and h. Assumes that the calling procedure (e.g., Cudd_bddIteConstant) is only interested in whether the result is constant or not. Returns the result if found (possibly DD_NON_CONSTANT); otherwise it returns NULL.]
SideEffects [None]
SeeAlso [cuddCacheLookup]
Definition at line 642 of file cuddCache.c.
References DdManager::cache, DdManager::cacheHits, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, cuddCacheResize(), DdCache::data, ddCHash, DdCache::f, DdCache::g, DdCache::h, DdManager::maxCache, DdManager::minHit, and DdCache::op.
Referenced by Cudd_addEvalConst(), Cudd_addIteConstant(), and Cudd_bddIteConstant().
int cuddInitCache (DdManager * unique, unsigned int cacheSize, unsigned int maxCacheSize)
Function********************************************************************
Synopsis [Initializes the computed table.]
Description [Initializes the computed table. It is called by Cudd_Init. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_Init]
Definition at line 111 of file cuddCache.c.
References ALLOC, DdManager::cache, DdManager::cachecollisions, DdManager::cachedeletions, DdManager::cacheHits, DdManager::cacheinserts, DdManager::cacheMisses, DdManager::cacheShift, DdManager::cacheSlots, CUDD_MEMORY_OUT, Cudd_SetMinHit(), cuddComputeFloorLog2(), DdCache::data, DD_MIN_HIT, ddMax, ddMin, DdManager::errorCode, DdManager::maxCache, DdManager::maxCacheHard, memset(), DdManager::memused, DdManager::minCache, DdManager::minHit, DdManager::slots, DdManager::totCachehits, and DdManager::totCacheMisses.
Referenced by Cudd_Init().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddCache.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddCache.c]
PackageName [cudd]
Synopsis [Functions for cache insertion and lookup.]
Description [Internal procedures included in this module:
cuddInitCache()
cuddCacheInsert()
cuddCacheInsert2()
cuddCacheLookup()
cuddCacheLookupZdd()
cuddCacheLookup2()
cuddCacheLookup2Zdd()
cuddConstantLookup()
cuddCacheProfile()
cuddCacheResize()
cuddCacheFlush()
cuddComputeFloorLog2()
Static procedures included in this module:
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 69 of file cuddCache.c.