cuddAddWalsh.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *addWalshInt ARGS ((DdManager *dd, DdNode **x, DdNode **y, int n))
DdNode * Cudd_addWalsh (DdManager *dd, DdNode **x, DdNode **y, int n)
DdNode * Cudd_addResidue (DdManager *dd, int n, int m, int options, int top)
static DdNode * addWalshInt (DdManager *dd, DdNode **x, DdNode **y, int n)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddWalsh.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* addWalshInt (DdManager * dd, DdNode ** x, DdNode ** y, int n) [static]
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_addWalsh.]
Description [Generates a Walsh matrix in ADD form. Returns a pointer to the matrixi if successful; NULL otherwise.]
SideEffects [None]
Definition at line 269 of file cuddAddWalsh.c.
References Cudd_addIte(), Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddDeref, cuddRef, cuddUniqueConst(), DD_ONE, and one.
Referenced by Cudd_addWalsh().
static DdNode* addWalshInt ARGS ((DdManager *dd, DdNode **x, DdNode **y, int n)) [static]
AutomaticStart
DdNode* Cudd_addResidue (DdManager * dd, int n, int m, int options, int top)
Function********************************************************************
Synopsis [Builds an ADD for the residue modulo m of an n-bit number.]
Description [Builds an ADD for the residue modulo m of an n-bit number. The modulus must be at least 2, and the number of bits at least 1. Parameter options specifies whether the MSB should be on top or the LSB; and whther the number whose residue is computed is in two's complement notation or not. The macro CUDD_RESIDUE_DEFAULT specifies LSB on top and unsigned number. The macro CUDD_RESIDUE_MSB specifies MSB on top, and the macro CUDD_RESIDUE_TC specifies two's complement residue. To request MSB on top and two's complement residue simultaneously, one can OR the two macros: CUDD_RESIDUE_MSB | CUDD_RESIDUE_TC. Cudd_addResidue returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 132 of file cuddAddWalsh.c.
References ALLOC, Cudd_addIte(), CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), CUDD_RESIDUE_MSB, CUDD_RESIDUE_TC, CUDD_VALUE_TYPE, cuddDeref, cuddRef, cuddUniqueConst(), cuddUniqueInter(), DD_ONE, DD_ZERO, DdManager::errorCode, and FREE.
DdNode* Cudd_addWalsh (DdManager * dd, DdNode ** x, DdNode ** y, int n)
Function********************************************************************
Synopsis [Generates a Walsh matrix in ADD form.]
Description [Generates a Walsh matrix in ADD form. Returns a pointer to the matrixi if successful; NULL otherwise.]
SideEffects [None]
Definition at line 91 of file cuddAddWalsh.c.
References addWalshInt(), and DdManager::reordered.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddWalsh.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddWalsh.c]
PackageName [cudd]
Synopsis [Functions that generate Walsh matrices and residue functions in ADD form.]
Description [External procedures included in this module:
Cudd_addWalsh()
Cudd_addResidue()
Static procedures included in this module:
addWalshInt()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 55 of file cuddAddWalsh.c.