cuddLinear.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define CUDD_SWAP_MOVE 0
#define CUDD_LINEAR_TRANSFORM_MOVE 1
#define CUDD_INVERSE_TRANSFORM_MOVE 2
#define BPL 32
#define LOGBPL 5
Functions
static int ddLinearUniqueCompare ARGS ((int *ptrX, int *ptrY))
static int ddLinearAndSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh))
static Move *ddLinearAndSiftingUp ARGS ((DdManager *table, int y, int xLow, Move *prevMoves))
static Move *ddLinearAndSiftingDown ARGS ((DdManager *table, int x, int xHigh, Move *prevMoves))
static int ddLinearAndSiftingBackward ARGS ((DdManager *table, int size, Move *moves))
static Move *ddUndoMoves ARGS ((DdManager *table, Move *moves))
static int cuddLinearInPlace ARGS ((DdManager *table, int x, int y))
static void ddUpdateInteractionMatrix ARGS ((DdManager *table, int xindex, int yindex))
static int cuddInitLinear ARGS ((DdManager *table))
int Cudd_PrintLinear (DdManager *table)
int Cudd_ReadLinear (DdManager *table, int x, int y)
int cuddLinearAndSifting (DdManager *table, int lower, int upper)
static int ddLinearUniqueCompare (int *ptrX, int *ptrY)
static int ddLinearAndSiftingAux (DdManager *table, int x, int xLow, int xHigh)
static Move * ddLinearAndSiftingUp (DdManager *table, int y, int xLow, Move *prevMoves)
static Move * ddLinearAndSiftingDown (DdManager *table, int x, int xHigh, Move *prevMoves)
static int ddLinearAndSiftingBackward (DdManager *table, int size, Move *moves)
static Move * ddUndoMoves (DdManager *table, Move *moves)
static int cuddLinearInPlace (DdManager *table, int x, int y)
static void ddUpdateInteractionMatrix (DdManager *table, int xindex, int yindex)
static int cuddInitLinear (DdManager *table)
static int cuddResizeLinear (DdManager *table)
static void cuddXorLinear (DdManager *table, int x, int y)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddLinear.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int * entry
Define Documentation
#define BPL 32
Definition at line 53 of file cuddLinear.c.
#define CUDD_INVERSE_TRANSFORM_MOVE 2
Definition at line 48 of file cuddLinear.c.
Referenced by cuddZddUndoMoves(), and ddUndoMoves().
#define CUDD_LINEAR_TRANSFORM_MOVE 1
Definition at line 47 of file cuddLinear.c.
Referenced by cuddZddLinearDown(), cuddZddLinearUp(), cuddZddUndoMoves(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), and ddUndoMoves().
#define CUDD_SWAP_MOVE 0
CFile***********************************************************************
FileName [cuddLinear.c]
PackageName [cudd]
Synopsis [Functions for DD reduction by linear transformations.]
Description [ Internal procedures included in this module:
cuddLinearAndSifting()
Static procedures included in this module:
ddLinearUniqueCompare()
ddLinearAndSiftingAux()
ddLinearAndSiftingUp()
ddLinearAndSiftingDown()
ddLinearAndSiftingBackward()
ddUndoMoves()
ddUpdateInteractionMatrix()
cuddLinearInPlace()
cuddInitLinear()
cuddResizeLinear()
cuddXorLinear()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 46 of file cuddLinear.c.
Referenced by cuddZddLinearDown(), cuddZddLinearUp(), cuddZddUndoMoves(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), and ddUndoMoves().
#define LOGBPL 5
Definition at line 54 of file cuddLinear.c.
Function Documentation
static int cuddInitLinear ARGS ((DdManager *table)) [static]
static void ddUpdateInteractionMatrix ARGS ((DdManager *table, int xindex, int yindex)) [static]
static int cuddLinearInPlace ARGS ((DdManager *table, int x, int y)) [static]
static Move* ddUndoMoves ARGS ((DdManager *table, Move *moves)) [static]
static int ddLinearAndSiftingBackward ARGS ((DdManager *table, int size, Move *moves)) [static]
static Move* ddLinearAndSiftingDown ARGS ((DdManager *table, int x, int xHigh, Move *prevMoves)) [static]
static Move* ddLinearAndSiftingUp ARGS ((DdManager *table, int y, int xLow, Move *prevMoves)) [static]
static int ddLinearAndSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh)) [static]
static int ddLinearUniqueCompare ARGS ((int *ptrX, int *ptrY)) [static]
AutomaticStart
int Cudd_PrintLinear (DdManager * table)
Function********************************************************************
Synopsis [Prints the linear transform matrix.]
Description [Prints the linear transform matrix. Returns 1 in case of success; 0 otherwise.]
SideEffects [none]
SeeAlso []
Definition at line 128 of file cuddLinear.c.
References BPL, DdManager::linear, DdManager::linearSize, and LOGBPL.
Referenced by cuddLinearAndSifting().
int Cudd_ReadLinear (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Reads an entry of the linear transform matrix.]
Description [Reads an entry of the linear transform matrix.]
SideEffects [none]
SeeAlso []
Definition at line 166 of file cuddLinear.c.
References assert, BPL, DdManager::linear, DdManager::linearSize, LOGBPL, result, and DdManager::size.
static int cuddInitLinear (DdManager * table) [static]
Function********************************************************************
Synopsis [Initializes the linear transform matrix.]
Description []
SideEffects [none]
SeeAlso []
Definition at line 1198 of file cuddLinear.c.
References ALLOC, BPL, CUDD_MEMORY_OUT, DdManager::errorCode, DdManager::linear, DdManager::linearSize, LOGBPL, DdManager::memused, and DdManager::size.
Referenced by cuddLinearAndSifting().
int cuddLinearAndSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [BDD reduction based on combination of sifting and linear transformations.]
Description [BDD reduction based on combination of sifting and linear transformations. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique table.
Sift the variable up and down, remembering each time the total size of the DD heap. At each position, linear transformation of the two adjacent variables is tried and is accepted if it reduces the size of the DD.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 215 of file cuddLinear.c.
References ALLOC, Cudd_DebugCheck(), CUDD_MEMORY_OUT, Cudd_PrintLinear(), cuddInitLinear(), cuddResizeLinear(), ddLinearAndSiftingAux(), ddLinearUniqueCompare(), ddMin, entry, DdManager::errorCode, FREE, DdManager::isolated, DdManager::keys, DdSubtable::keys, DdManager::linear, DdManager::linearSize, DdManager::perm, qsort(), result, DdManager::siftMaxVar, DdManager::size, size, and DdManager::subtables.
Referenced by ddReorderChildren().
static int cuddLinearInPlace (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Linearly combines two adjacent variables.]
Description [Linearly combines two adjacent variables. Specifically, replaces the top variable with the exclusive nor of the two variables. It assumes that no dead nodes are present on entry to this procedure. The procedure then guarantees that no dead nodes will be present when it terminates. cuddLinearInPlace assumes that x < y. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [The two subtables corrresponding to variables x and y are modified. The global counters of the unique table are also affected.]
SeeAlso [cuddSwapInPlace]
Definition at line 824 of file cuddLinear.c.
References assert, Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddDeallocNode, cuddDynamicAllocNode(), cuddE, cuddNextHigh(), cuddSatDec, cuddSatInc, cuddT, cuddTestInteract(), ddHash, DdSubtable::dead, DdNode::index, DdManager::invperm, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdSubtable::slots, DdManager::subtables, and DdManager::vars.
Referenced by ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), and ddUndoMoves().
static int cuddResizeLinear (DdManager * table) [static]
Function********************************************************************
Synopsis [Resizes the linear transform matrix.]
Description []
SideEffects [none]
SeeAlso []
Definition at line 1242 of file cuddLinear.c.
References ALLOC, BPL, CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdManager::linear, DdManager::linearSize, LOGBPL, DdManager::memused, and DdManager::size.
Referenced by cuddLinearAndSifting().
static void cuddXorLinear (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [XORs two rows of the linear transform matrix.]
Description [XORs two rows of the linear transform matrix and replaces the first row with the result.]
SideEffects [none]
SeeAlso []
Definition at line 1305 of file cuddLinear.c.
References DdManager::linear, LOGBPL, and DdManager::size.
static int ddLinearAndSiftingAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. At each step a linear transformation is tried, and, if it decreases the size of the DD, it is accepted. Finds the best position and does the required changes. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 365 of file cuddLinear.c.
References assert, CUDD_OUT_OF_MEM, cuddDeallocNode, ddLinearAndSiftingBackward(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), ddUndoMoves(), DdManager::isolated, DdManager::keys, Move::next, result, Move::x, and Move::y.
Referenced by cuddLinearAndSifting().
static int ddLinearAndSiftingBackward (DdManager * table, int size, Move * moves) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the DD heap to the order giving the minimum size.]
Description [Given a set of moves, returns the DD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 707 of file cuddLinear.c.
References Move::next, and Move::size.
Referenced by ddLinearAndSiftingAux().
static Move* ddLinearAndSiftingDown (DdManager * table, int x, int xHigh, Move * prevMoves) [static]
Function********************************************************************
Synopsis [Sifts a variable down and applies linear transformations.]
Description [Sifts a variable down and applies linear transformations. Moves x down until either it reaches the bound (xHigh) or the size of the DD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
Definition at line 594 of file cuddLinear.c.
References CUDD_LINEAR_TRANSFORM_MOVE, CUDD_OUT_OF_MEM, CUDD_SWAP_MOVE, cuddDeallocNode, cuddDynamicAllocNode(), cuddLinearInPlace(), cuddNextHigh(), cuddSwapInPlace(), cuddTestInteract(), ddUpdateInteractionMatrix(), Move::flags, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, Move::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddLinearAndSiftingAux().
static Move* ddLinearAndSiftingUp (DdManager * table, int y, int xLow, Move * prevMoves) [static]
Function********************************************************************
Synopsis [Sifts a variable up and applies linear transformations.]
Description [Sifts a variable up and applies linear transformations. Moves y up until either it reaches the bound (xLow) or the size of the DD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
Definition at line 471 of file cuddLinear.c.
References CUDD_LINEAR_TRANSFORM_MOVE, CUDD_OUT_OF_MEM, CUDD_SWAP_MOVE, cuddDeallocNode, cuddDynamicAllocNode(), cuddLinearInPlace(), cuddNextLow(), cuddSwapInPlace(), cuddTestInteract(), ddUpdateInteractionMatrix(), Move::flags, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, Move::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddLinearAndSiftingAux().
static int ddLinearUniqueCompare (int * ptrX, int * ptrY) [static]
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
Definition at line 337 of file cuddLinear.c.
References entry.
Referenced by cuddLinearAndSifting().
static Move* ddUndoMoves (DdManager * table, Move * moves) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the DD heap to the order in effect before the moves.]
Description [Given a set of moves, returns the DD heap to the order in effect before the moves. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 753 of file cuddLinear.c.
References CUDD_INVERSE_TRANSFORM_MOVE, CUDD_LINEAR_TRANSFORM_MOVE, CUDD_SWAP_MOVE, cuddDynamicAllocNode(), cuddLinearInPlace(), cuddSwapInPlace(), Move::flags, Move::next, size, Move::x, and Move::y.
Referenced by ddLinearAndSiftingAux().
static void ddUpdateInteractionMatrix (DdManager * table, int xindex, int yindex) [static]
Function********************************************************************
Synopsis [Updates the interaction matrix.]
Description []
SideEffects [none]
SeeAlso []
Definition at line 1158 of file cuddLinear.c.
References cuddSetInteract(), cuddTestInteract(), and DdManager::size.
Referenced by ddLinearAndSiftingDown(), and ddLinearAndSiftingUp().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddLinear.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 70 of file cuddLinear.c.
int* entry [static]
Definition at line 73 of file cuddLinear.c.