cuddExact.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static int getMaxBinomial ARGS ((int n))
static int gcd ARGS ((int x, int y))
static DdHalfWord **getMatrix ARGS ((int rows, int cols))
static void freeMatrix ARGS ((DdHalfWord **matrix))
static int getLevelKeys ARGS ((DdManager *table, int l))
static int ddShuffle ARGS ((DdManager *table, DdHalfWord *permutation, int lower, int upper))
static int ddSiftUp ARGS ((DdManager *table, int x, int xLow))
static int updateUB ARGS ((DdManager *table, int oldBound, DdHalfWord *bestOrder, int lower, int upper))
static int ddCountRoots ARGS ((DdManager *table, int lower, int upper))
static void ddClearGlobal ARGS ((DdManager *table, int lower, int maxlevel))
static int computeLB ARGS ((DdManager *table, DdHalfWord *order, int roots, int cost, int lower, int upper, int level))
static int updateEntry ARGS ((DdManager *table, DdHalfWord *order, int level, int cost, DdHalfWord **orders, int *costs, int subsets, char *mask, int lower, int upper))
static void pushDown ARGS ((DdHalfWord *order, int j, int level))
static int checkSymmInfo ARGS ((DdManager *table, DdHalfWord *symmInfo, int index, int level))
int cuddExact (DdManager *table, int lower, int upper)
static int getMaxBinomial (int n)
static int gcd (int x, int y)
static DdHalfWord ** getMatrix (int rows, int cols)
static void freeMatrix (DdHalfWord **matrix)
static int getLevelKeys (DdManager *table, int l)
static int ddShuffle (DdManager *table, DdHalfWord *permutation, int lower, int upper)
static int ddSiftUp (DdManager *table, int x, int xLow)
static int updateUB (DdManager *table, int oldBound, DdHalfWord *bestOrder, int lower, int upper)
static int ddCountRoots (DdManager *table, int lower, int upper)
static void ddClearGlobal (DdManager *table, int lower, int maxlevel)
static int computeLB (DdManager *table, DdHalfWord *order, int roots, int cost, int lower, int upper, int level)
static int updateEntry (DdManager *table, DdHalfWord *order, int level, int cost, DdHalfWord **orders, int *costs, int subsets, char *mask, int lower, int upper)
static void pushDown (DdHalfWord *order, int j, int level)
static DdHalfWord * initSymmInfo (DdManager *table, int lower, int upper)
static int checkSymmInfo (DdManager *table, DdHalfWord *symmInfo, int index, int level)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddExact.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int checkSymmInfo ARGS ((DdManager *table, DdHalfWord *symmInfo, int index, int level)) [static]
static void pushDown ARGS ((DdHalfWord *order, int j, int level)) [static]
static int updateEntry ARGS ((DdManager *table, DdHalfWord *order, int level, int cost, DdHalfWord **orders, int *costs, int subsets, char *mask, int lower, int upper)) [static]
static int computeLB ARGS ((DdManager *table, DdHalfWord *order, int roots, int cost, int lower, int upper, int level)) [static]
static void ddClearGlobal ARGS ((DdManager *table, int lower, int maxlevel)) [static]
static int ddCountRoots ARGS ((DdManager *table, int lower, int upper)) [static]
static int updateUB ARGS ((DdManager *table, int oldBound, DdHalfWord *bestOrder, int lower, int upper)) [static]
static int ddSiftUp ARGS ((DdManager *table, int x, int xLow)) [static]
static int ddShuffle ARGS ((DdManager *table, DdHalfWord *permutation, int lower, int upper)) [static]
static int getLevelKeys ARGS ((DdManager *table, int l)) [static]
static void freeMatrix ARGS ((DdHalfWord **matrix)) [static]
static DdHalfWord** getMatrix ARGS ((int rows, int cols)) [static]
static int gcd ARGS ((int x, int y)) [static]
static int getMaxBinomial ARGS ((int n)) [static]
AutomaticStart
static int checkSymmInfo (DdManager * table, DdHalfWord * symmInfo, int index, int level) [static]
Function********************************************************************
Synopsis [Check symmetry condition.]
Description [Check whether a variable is the one with the highest index among those belonging to a symmetry group that are in the top part of the BDD.]
SideEffects [None]
SeeAlso [initSymmInfo]
Definition at line 989 of file cuddExact.c.
Referenced by cuddExact().
static int computeLB (DdManager * table, DdHalfWord * order, int roots, int cost, int lower, int upper, int level) [static]
Function********************************************************************
Synopsis [Computes a lower bound on the size of a BDD.]
Description [Computes a lower bound on the size of a BDD from the following factors:
size of the lower part of it;
size of the part of the upper part not subjected to reordering;
number of roots in the part of the BDD subjected to reordering;
variable in the support of the roots in the upper part of the BDD subjected to reordering.
SideEffects [None]
SeeAlso []
Definition at line 798 of file cuddExact.c.
References getLevelKeys(), DdManager::invperm, DdSubtable::keys, DdNode::ref, DdManager::size, DdManager::subtables, and DdManager::vars.
Referenced by cuddExact().
int cuddExact (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Exact variable ordering algorithm.]
Description [Exact variable ordering algorithm. Finds an optimum order for the variables between lower and upper. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 125 of file cuddExact.c.
References ALLOC, checkSymmInfo(), computeLB(), DdManager::constants, CUDD_MEMORY_OUT, cuddSymmSiftingConv(), ddCountRoots(), ddShuffle(), DdManager::errorCode, FREE, freeMatrix(), getLevelKeys(), getMatrix(), getMaxBinomial(), initSymmInfo(), DdManager::invperm, DdManager::isolated, DdManager::keys, DdSubtable::keys, pushDown(), result, DdManager::size, size, DdManager::subtables, updateEntry(), updateUB(), and DdManager::vars.
Referenced by ddReorderChildren().
static void ddClearGlobal (DdManager * table, int lower, int maxlevel) [static]
Function********************************************************************
Synopsis [Scans the DD and clears the LSB of the next pointers.]
Description [Scans the DD and clears the LSB of the next pointers. The LSB of the next pointers are used as markers to tell whether a node was reached. Once the roots are counted, these flags are reset.]
SideEffects [None]
SeeAlso [ddCountRoots]
Definition at line 746 of file cuddExact.c.
References Cudd_Regular, DdNode::next, DdSubtable::nodelist, DdSubtable::slots, and DdManager::subtables.
static int ddCountRoots (DdManager * table, int lower, int upper) [static]
Function********************************************************************
Synopsis [Counts the number of roots.]
Description [Counts the number of roots at the levels between lower and upper. The computation is based on breadth-first search. A node is a root if it is not reachable from any previously visited node. (All the nodes at level lower are therefore considered roots.) The visited flag uses the LSB of the next pointer. Returns the root count. The roots that are constant nodes are always ignored.]
SideEffects [None]
SeeAlso [ddClearGlobal]
Definition at line 673 of file cuddExact.c.
References Cudd_Complement, Cudd_IsComplement, Cudd_IsConstant, Cudd_Regular, cuddE, cuddT, DdNode::index, DdNode::next, DdSubtable::nodelist, DdManager::perm, DdSubtable::slots, DdManager::subtables, and DdManager::vars.
Referenced by cuddExact().
static int ddShuffle (DdManager * table, DdHalfWord * permutation, int lower, int upper) [static]
Function********************************************************************
Synopsis [Reorders variables according to a given permutation.]
Description [Reorders variables according to a given permutation. The i-th permutation array contains the index of the variable that should be brought to the i-th level. ddShuffle assumes that no dead nodes are present and that the interaction matrix is properly initialized. The reordering is achieved by a series of upward sifts. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 516 of file cuddExact.c.
References ddSiftUp(), DdManager::invperm, DdManager::isolated, DdManager::keys, numvars, DdManager::perm, result, DdManager::size, and util_cpu_time().
Referenced by Cudd_ShuffleHeap(), cuddBddAlignToZdd(), and cuddExact().
static int ddSiftUp (DdManager * table, int x, int xLow) [static]
Function********************************************************************
Synopsis [Moves one variable up.]
Description [Takes a variable from position x and sifts it up to position xLow; xLow should be less than or equal to x. Returns 1 if successful; 0 otherwise]
SideEffects [None]
SeeAlso []
Definition at line 596 of file cuddExact.c.
References cuddNextLow(), cuddSwapInPlace(), and size.
Referenced by ddShuffle().
static void freeMatrix (DdHalfWord ** matrix) [static]
Function********************************************************************
Synopsis [Frees a two-dimensional matrix allocated by getMatrix.]
Description []
SideEffects [None]
SeeAlso [getMatrix]
Definition at line 461 of file cuddExact.c.
References FREE.
Referenced by cuddExact().
static int gcd (int x, int y) [static]
Function********************************************************************
Synopsis [Returns the gcd of two integers.]
Description [Returns the gcd of two integers. Uses the binary GCD algorithm described in Cormen, Leiserson, and Rivest.]
SideEffects [None]
SeeAlso []
Definition at line 374 of file cuddExact.c.
Referenced by getMaxBinomial().
static int getLevelKeys (DdManager * table, int l) [static]
Function********************************************************************
Synopsis [Returns the number of nodes at one level of a unique table.]
Description [Returns the number of nodes at one level of a unique table. The projection function, if isolated, is not counted.]
SideEffects [None]
SeeAlso []
Definition at line 484 of file cuddExact.c.
References DdManager::invperm, DdSubtable::keys, DdNode::ref, DdManager::subtables, and DdManager::vars.
Referenced by computeLB(), and cuddExact().
static DdHalfWord** getMatrix (int rows, int cols) [static]
Function********************************************************************
Synopsis [Allocates a two-dimensional matrix of ints.]
Description [Allocates a two-dimensional matrix of ints. Returns the pointer to the matrix if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [freeMatrix]
Definition at line 429 of file cuddExact.c.
References ALLOC.
Referenced by cuddExact().
static int getMaxBinomial (int n) [static]
Function********************************************************************
Synopsis [Returns the maximum value of (n choose k) for a given n.]
Description [Computes the maximum value of (n choose k) for a given n. The maximum value occurs for k = n/2 when n is even, or k = (n-1)/2 when n is odd. The algorithm used in this procedure is quite inefficient, but it avoids intermediate overflow problems. Returns the computed value if successful; -1 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 324 of file cuddExact.c.
References ALLOC, FREE, gcd(), and result.
Referenced by cuddExact().
static DdHalfWord* initSymmInfo (DdManager * table, int lower, int upper) [static]
Function********************************************************************
Synopsis [Gathers symmetry information.]
Description [Translates the symmetry information stored in the next field of each subtable from level to indices. This procedure is called immediately after symmetric sifting, so that the next fields are correct. By translating this informaton in terms of indices, we make it independent of subsequent reorderings. THe format used is the same of the next fields: a circular list where each variable points to the next variable in the same symmetry group. Only the entries between lower and upper are considered. The procedure returns a pointer to an array holding the symmetry information if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [checkSymmInfo]
Definition at line 953 of file cuddExact.c.
References ALLOC, DdManager::invperm, DdSubtable::next, DdManager::size, and DdManager::subtables.
Referenced by cuddExact().
static void pushDown (DdHalfWord * order, int j, int level) [static]
Function********************************************************************
Synopsis [Pushes a variable in the order down to position `level.`]
Description []
SideEffects [None]
SeeAlso []
Definition at line 915 of file cuddExact.c.
Referenced by cuddExact().
static int updateEntry (DdManager * table, DdHalfWord * order, int level, int cost, DdHalfWord ** orders, int * costs, int subsets, char * mask, int lower, int upper) [static]
Function********************************************************************
Synopsis [Updates entry for a subset.]
Description [Updates entry for a subset. Finds the subset, if it exists. If the new order for the subset has lower cost, or if the subset did not exist, it stores the new order and cost. Returns the number of subsets currently in the table.]
SideEffects [None]
SeeAlso []
Definition at line 862 of file cuddExact.c.
References DdManager::invperm, and size.
Referenced by cuddExact().
static int updateUB (DdManager * table, int oldBound, DdHalfWord * bestOrder, int lower, int upper) [static]
Function********************************************************************
Synopsis [Updates the upper bound and saves the best order seen so far.]
Description [Updates the upper bound and saves the best order seen so far. Returns the current value of the upper bound.]
SideEffects [None]
SeeAlso []
Definition at line 631 of file cuddExact.c.
References DdManager::invperm, DdManager::isolated, and DdManager::keys.
Referenced by cuddExact().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddExact.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddExact.c]
PackageName [cudd]
Synopsis [Functions for exact variable reordering.]
Description [External procedures included in this file:
Internal procedures included in this module:
cuddExact()
Static procedures included in this module:
getMaxBinomial()
gcd()
getMatrix()
freeMatrix()
getLevelKeys()
ddShuffle()
ddSiftUp()
updateUB()
ddCountRoots()
ddClearGlobal()
computeLB()
updateEntry()
pushDown()
initSymmInfo()
]
Author [Cheng Hua, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 66 of file cuddExact.c.