cuddPriority.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_PrioritySelect (DdManager *dd, DdNode *R, DdNode **x, DdNode **y, DdNode **z, DdNode *Pi, int n, DdNode *(*Pifunc)(DdManager *, int, DdNode **, DdNode **, DdNode **))
DdNode * Cudd_Xgty (DdManager *dd, int N, DdNode **z, DdNode **x, DdNode **y)
DdNode * Cudd_Xeqy (DdManager *dd, int N, DdNode **x, DdNode **y)
DdNode * Cudd_addXeqy (DdManager *dd, int N, DdNode **x, DdNode **y)
DdNode * Cudd_Dxygtdxz (DdManager *dd, int N, DdNode **x, DdNode **y, DdNode **z)
DdNode * Cudd_Dxygtdyz (DdManager *dd, int N, DdNode **x, DdNode **y, DdNode **z)
DdNode * Cudd_CProjection (DdManager *dd, DdNode *R, DdNode *Y)
DdNode * Cudd_addHamming (DdManager *dd, DdNode **xVars, DdNode **yVars, int nVars)
DdNode * cuddCProjectionRecur (DdManager *dd, DdNode *R, DdNode *Y, DdNode *Ysupp)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddPriority.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_addHamming (DdManager * dd, DdNode ** xVars, DdNode ** yVars, int nVars)
Function********************************************************************
Synopsis [Computes the Hamming distance ADD.]
Description [Computes the Hamming distance ADD. Returns an ADD that gives the Hamming distance between its two arguments if successful; NULL otherwise. The two vectors xVars and yVars identify the variables that form the two arguments.]
SideEffects [None]
SeeAlso []
Definition at line 752 of file cuddPriority.c.
References Cudd_addApply(), Cudd_addPlus(), Cudd_bddIte(), Cudd_BddToAdd(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, cuddRef, DD_ZERO, and result.
DdNode* Cudd_addXeqy (DdManager * dd, int N, DdNode ** x, DdNode ** y)
Function********************************************************************
Synopsis [Generates an ADD for the function x==y.]
Description [This function generates an ADD for the function x==y. Both x and y are N-bit numbers, x\[0\] x\[1\] ... x\[N-1\] and y\[0\] y\[1\] ... y\[N-1\], with 0 the most significant bit. The ADD is built bottom-up. It has 3*N-1 internal nodes, if the variables are ordered as follows: x\[0\] y\[0\] x\[1\] y\[1\] ... x\[N-1\] y\[N-1\]. ]
SideEffects [None]
SeeAlso [Cudd_Xeqy]
Definition at line 364 of file cuddPriority.c.
References Cudd_addIte(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, DD_ONE, DD_ZERO, one, and zero.
DdNode* Cudd_CProjection (DdManager * dd, DdNode * R, DdNode * Y)
Function********************************************************************
Synopsis [Computes the compatible projection of R w.r.t. cube Y.]
Description [Computes the compatible projection of relation R with respect to cube Y. Returns a pointer to the c-projection if successful; NULL otherwise. For a comparison between Cudd_CProjection and Cudd_PrioritySelect, see the documentation of the latter.]
SideEffects [None]
SeeAlso [Cudd_PrioritySelect]
Definition at line 698 of file cuddPriority.c.
References Cudd_RecursiveDeref(), Cudd_Support(), cuddCheckCube(), cuddCProjectionRecur(), cuddDeref, cuddRef, and DdManager::reordered.
Referenced by cuddCProjectionRecur().
DdNode* Cudd_Dxygtdxz (DdManager * dd, int N, DdNode ** x, DdNode ** y, DdNode ** z)
Function********************************************************************
Synopsis [Generates a BDD for the function d(x,y) > d(x,z).]
Description [This function generates a BDD for the function d(x,y) > d(x,z); x, y, and z are N-bit numbers, x\[0\] x\[1\] ... x\[N-1\], y\[0\] y\[1\] ... y\[N-1\], and z\[0\] z\[1\] ... z\[N-1\], with 0 the most significant bit. The distance d(x,y) is defined as: {i=0}^{N-1}(|x_i - y_i| 2^{N-i-1}). The BDD is built bottom-up. It has 7*N-3 internal nodes, if the variables are ordered as follows: x\[0\] y\[0\] z\[0\] x\[1\] y\[1\] z\[1\] ... x\[N-1\] y\[N-1\] z\[N-1\]. ]
SideEffects [None]
SeeAlso [Cudd_PrioritySelect Cudd_Dxygtdyz Cudd_Xgty Cudd_bddAdjPermuteX]
Definition at line 450 of file cuddPriority.c.
References Cudd_bddIte(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, cuddRef, DD_ONE, one, and zero.
DdNode* Cudd_Dxygtdyz (DdManager * dd, int N, DdNode ** x, DdNode ** y, DdNode ** z)
Function********************************************************************
Synopsis [Generates a BDD for the function d(x,y) > d(y,z).]
Description [This function generates a BDD for the function d(x,y) > d(y,z); x, y, and z are N-bit numbers, x\[0\] x\[1\] ... x\[N-1\], y\[0\] y\[1\] ... y\[N-1\], and z\[0\] z\[1\] ... z\[N-1\], with 0 the most significant bit. The distance d(x,y) is defined as: {i=0}^{N-1}(|x_i - y_i| 2^{N-i-1}). The BDD is built bottom-up. It has 7*N-3 internal nodes, if the variables are ordered as follows: x\[0\] y\[0\] z\[0\] x\[1\] y\[1\] z\[1\] ... x\[N-1\] y\[N-1\] z\[N-1\]. ]
SideEffects [None]
SeeAlso [Cudd_PrioritySelect Cudd_Dxygtdxz Cudd_Xgty Cudd_bddAdjPermuteX]
Definition at line 577 of file cuddPriority.c.
References Cudd_bddIte(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, cuddRef, DD_ONE, one, and zero.
DdNode* Cudd_PrioritySelect (DdManager * dd, DdNode * R, DdNode ** x, DdNode ** y, DdNode ** z, DdNode * Pi, int n, DdNode *(*)(DdManager *, int, DdNode **, DdNode **, DdNode **) Pifunc)
Function********************************************************************
Synopsis [Selects pairs from R using a priority function.]
Description [Selects pairs from a relation R(x,y) (given as a BDD) in such a way that a given x appears in one pair only. Uses a priority function to determine which y should be paired to a given x. Cudd_PrioritySelect returns a pointer to the selected function if successful; NULL otherwise. Three of the arguments--x, y, and z--are vectors of BDD variables. The first two are the variables on which R depends. The third vectore is a vector of auxiliary variables, used during the computation. This vector is optional. If a NULL value is passed instead, Cudd_PrioritySelect will create the working variables on the fly. The sizes of x and y (and z if it is not NULL) should equal n. The priority function Pi can be passed as a BDD, or can be built by Cudd_PrioritySelect. If NULL is passed instead of a DdNode *, parameter Pifunc is used by Cudd_PrioritySelect to build a BDD for the priority function. (Pifunc is a pointer to a C function.) If Pi is not NULL, then Pifunc is ignored. Pifunc should have the same interface as the standard priority functions (e.g., Cudd_Dxygtdxz). Cudd_PrioritySelect and Cudd_CProjection can sometimes be used interchangeably. Specifically, calling Cudd_PrioritySelect with Cudd_Xgty as Pifunc produces the same result as calling Cudd_CProjection with the all-zero minterm as reference minterm. However, depending on the application, one or the other may be preferable:
When extracting representatives from an equivalence relation, Cudd_CProjection has the advantage of nor requiring the auxiliary variables.
When computing matchings in general bipartite graphs, Cudd_PrioritySelect normally obtains better results because it can use more powerful matching schemes (e.g., Cudd_Dxygtdxz).
]
SideEffects [If called with z == NULL, will create new variables in the manager.]
SeeAlso [Cudd_Dxygtdxz Cudd_Dxygtdyz Cudd_Xgty Cudd_bddAdjPermuteX Cudd_CProjection]
Definition at line 131 of file cuddPriority.c.
References ALLOC, Cudd_bddAnd(), Cudd_bddAndAbstract(), Cudd_bddSwapVariables(), CUDD_MAXINDEX, CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, cuddRef, cuddUniqueInter(), DD_ONE, DdManager::errorCode, FREE, DdManager::one, and DdManager::size.
DdNode* Cudd_Xeqy (DdManager * dd, int N, DdNode ** x, DdNode ** y)
Function********************************************************************
Synopsis [Generates a BDD for the function x==y.]
Description [This function generates a BDD for the function x==y. Both x and y are N-bit numbers, x\[0\] x\[1\] ... x\[N-1\] and y\[0\] y\[1\] ... y\[N-1\], with 0 the most significant bit. The BDD is built bottom-up. It has 3*N-1 internal nodes, if the variables are ordered as follows: x\[0\] y\[0\] x\[1\] y\[1\] ... x\[N-1\] y\[N-1\]. ]
SideEffects [None]
SeeAlso [Cudd_addXeqy]
Definition at line 301 of file cuddPriority.c.
References Cudd_bddAnd(), Cudd_bddIte(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, and cuddRef.
DdNode* Cudd_Xgty (DdManager * dd, int N, DdNode ** z, DdNode ** x, DdNode ** y)
Function********************************************************************
Synopsis [Generates a BDD for the function x > y.]
Description [This function generates a BDD for the function x > y. Both x and y are N-bit numbers, x\[0\] x\[1\] ... x\[N-1\] and y\[0\] y\[1\] ... y\[N-1\], with 0 the most significant bit. The BDD is built bottom-up. It has 3*N-1 internal nodes, if the variables are ordered as follows: x\[0\] y\[0\] x\[1\] y\[1\] ... x\[N-1\] y\[N-1\]. Argument z is not used by Cudd_Xgty: it is included to make it call-compatible to Cudd_Dxygtdxz and Cudd_Dxygtdyz.]
SideEffects [None]
SeeAlso [Cudd_PrioritySelect Cudd_Dxygtdxz Cudd_Dxygtdyz]
Definition at line 236 of file cuddPriority.c.
References Cudd_bddAnd(), Cudd_bddIte(), Cudd_Not, Cudd_RecursiveDeref(), cuddDeref, and cuddRef.
DdNode* cuddCProjectionRecur (DdManager * dd, DdNode * R, DdNode * Y, DdNode * Ysupp)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_CProjection.]
Description [Performs the recursive step of Cudd_CProjection. Returns the projection if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_CProjection]
Definition at line 816 of file cuddPriority.c.
References assert, Cudd_CProjection(), Cudd_IsConstant, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddBddExistAbstractRecur(), cuddBddIteRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, DD_ONE, ddMin, DdNode::index, one, and DdManager::vars.
Referenced by Cudd_CProjection().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddPriority.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddPriority.c]
PackageName [cudd]
Synopsis [Priority functions.]
Description [External procedures included in this file:
Cudd_PrioritySelect()
Cudd_Xgty()
Cudd_Xeqy()
Cudd_addXeqy()
Cudd_Dxygtdxz()
Cudd_Dxygtdyz()
Cudd_CProjection()
Cudd_addHamming()
Internal procedures included in this module:
cuddCProjectionRecur()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 63 of file cuddPriority.c.