cuddBddAbs.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static int bddCheckPositiveCube ARGS ((DdManager *manager, DdNode *cube))
DdNode * Cudd_bddExistAbstract (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * Cudd_bddXorExistAbstract (DdManager *manager, DdNode *f, DdNode *g, DdNode *cube)
DdNode * Cudd_bddUnivAbstract (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * Cudd_bddBooleanDiff (DdManager *manager, DdNode *f, int x)
int Cudd_bddVarIsDependent (DdManager *dd, DdNode *f, DdNode *var)
DdNode * cuddBddExistAbstractRecur (DdManager *manager, DdNode *f, DdNode *cube)
DdNode * cuddBddXorExistAbstractRecur (DdManager *manager, DdNode *f, DdNode *g, DdNode *cube)
DdNode * cuddBddBooleanDiffRecur (DdManager *manager, DdNode *f, DdNode *var)
static int bddCheckPositiveCube (DdManager *manager, DdNode *cube)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddBddAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int bddCheckPositiveCube ARGS ((DdManager *manager, DdNode *cube)) [static]
AutomaticStart
static int bddCheckPositiveCube (DdManager * manager, DdNode * cube) [static]
Function********************************************************************
Synopsis [Checks whether cube is an BDD representing the product of positive literals.]
Description [Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 667 of file cuddBddAbs.c.
References Cudd_IsComplement, Cudd_Not, cuddE, cuddIsConstant, cuddT, and DD_ONE.
Referenced by Cudd_bddExistAbstract(), Cudd_bddUnivAbstract(), and Cudd_bddXorExistAbstract().
DdNode* Cudd_bddBooleanDiff (DdManager * manager, DdNode * f, int x)
Function********************************************************************
Synopsis [Computes the boolean difference of f with respect to x.]
Description [Computes the boolean difference of f with respect to the variable with index x. Returns the BDD of the boolean difference if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 211 of file cuddBddAbs.c.
References Cudd_Not, Cudd_Regular, cuddBddBooleanDiffRecur(), DD_ONE, DdManager::reordered, DdManager::size, and DdManager::vars.
DdNode* Cudd_bddExistAbstract (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Existentially abstracts all the variables in cube from f.]
Description [Existentially abstracts all the variables in cube from f. Returns the abstracted BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddUnivAbstract Cudd_addExistAbstract]
Definition at line 101 of file cuddBddAbs.c.
References bddCheckPositiveCube(), cuddBddExistAbstractRecur(), and DdManager::reordered.
Referenced by Cudd_bddRestrict(), and cuddBddExistAbstractRecur().
DdNode* Cudd_bddUnivAbstract (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Universally abstracts all the variables in cube from f.]
Description [Universally abstracts all the variables in cube from f. Returns the abstracted BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddExistAbstract Cudd_addUnivAbstract]
Definition at line 174 of file cuddBddAbs.c.
References bddCheckPositiveCube(), Cudd_Not, cuddBddExistAbstractRecur(), and DdManager::reordered.
int Cudd_bddVarIsDependent (DdManager * dd, DdNode * f, DdNode * var)
Function********************************************************************
Synopsis [Checks whether a variable is dependent on others in a function.]
Description [Checks whether a variable is dependent on others in a function. Returns 1 if the variable is dependent; 0 otherwise. No new nodes are created.]
SideEffects [None]
SeeAlso []
Definition at line 249 of file cuddBddAbs.c.
References Cudd_bddLeq(), Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddT, DD_ONE, DdNode::index, DdManager::perm, and zero.
DdNode* Cudd_bddXorExistAbstract (DdManager * manager, DdNode * f, DdNode * g, DdNode * cube)
Function********************************************************************
Synopsis [Takes the exclusive OR of two BDDs and simultaneously abstracts the variables in cube.]
Description [Takes the exclusive OR of two BDDs and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddUnivAbstract Cudd_bddExistAbstract Cudd_bddAndAbstract]
Definition at line 138 of file cuddBddAbs.c.
References bddCheckPositiveCube(), cuddBddXorExistAbstractRecur(), and DdManager::reordered.
Referenced by cuddBddXorExistAbstractRecur().
DdNode* cuddBddBooleanDiffRecur (DdManager * manager, DdNode * f, DdNode * var)
Function********************************************************************
Synopsis [Performs the recursive steps of Cudd_bddBoleanDiff.]
Description [Performs the recursive steps of Cudd_bddBoleanDiff. Returns the BDD obtained by XORing the cofactors of f with respect to var if successful; NULL otherwise. Exploits the fact that dF/dx = dF'/dx.]
SideEffects [None]
SeeAlso []
Definition at line 597 of file cuddBddAbs.c.
References Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddBddIteRecur(), cuddBddXorRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, DD_ONE, DdNode::index, DdManager::perm, and DdManager::vars.
Referenced by Cudd_bddBooleanDiff().
DdNode* cuddBddExistAbstractRecur (DdManager * manager, DdNode * f, DdNode * cube)
Function********************************************************************
Synopsis [Performs the recursive steps of Cudd_bddExistAbstract.]
Description [Performs the recursive steps of Cudd_bddExistAbstract. Returns the BDD obtained by abstracting the variables of cube from f if successful; NULL otherwise. It is also used by Cudd_bddUnivAbstract.]
SideEffects [None]
SeeAlso [Cudd_bddExistAbstract Cudd_bddUnivAbstract]
Definition at line 318 of file cuddBddAbs.c.
References Cudd_bddExistAbstract(), Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddBddAndRecur(), cuddBddIteRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, DD_ONE, DdNode::index, one, DdManager::perm, DdNode::ref, and DdManager::vars.
Referenced by Cudd_bddExistAbstract(), Cudd_bddUnivAbstract(), cuddBddAndAbstractRecur(), cuddBddClipAndAbsRecur(), cuddBddXorExistAbstractRecur(), cuddCProjectionRecur(), and cuddSolveEqnRecur().
DdNode* cuddBddXorExistAbstractRecur (DdManager * manager, DdNode * f, DdNode * g, DdNode * cube)
Function********************************************************************
Synopsis [Takes the exclusive OR of two BDDs and simultaneously abstracts the variables in cube.]
Description [Takes the exclusive OR of two BDDs and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddAndAbstract]
Definition at line 426 of file cuddBddAbs.c.
References Cudd_bddXorExistAbstract(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddBddAndRecur(), cuddBddExistAbstractRecur(), cuddBddXorRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, ddMin, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_bddXorExistAbstract().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddBddAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddBddAbs.c]
PackageName [cudd]
Synopsis [Quantification functions for BDDs.]
Description [External procedures included in this module:
Cudd_bddExistAbstract()
Cudd_bddXorExistAbstract()
Cudd_bddUnivAbstract()
Cudd_bddBooleanDiff()
Cudd_bddVarIsDependent()
Internal procedures included in this module:
cuddBddExistAbstractRecur()
cuddBddXorExistAbstractRecur()
cuddBddBooleanDiffRecur()
Static procedures included in this module:
bddCheckPositiveCube()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 64 of file cuddBddAbs.c.