cuddBridge.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *addBddDoThreshold ARGS ((DdManager *dd, DdNode *f, DdNode *val))
static DdNode *addBddDoInterval ARGS ((DdManager *dd, DdNode *f, DdNode *l, DdNode *u))
static DdNode *addBddDoIthBit ARGS ((DdManager *dd, DdNode *f, DdNode *index))
static DdNode *ddBddToAddRecur ARGS ((DdManager *dd, DdNode *B))
static DdNode *addBddDoPattern ARGS ((DdManager *dd, DdNode *f))
static DdNode *cuddBddTransferRecur ARGS ((DdManager *ddS, DdManager *ddD, DdNode *f, st_table *table))
DdNode * Cudd_addBddThreshold (DdManager *dd, DdNode *f, CUDD_VALUE_TYPE value)
DdNode * Cudd_addBddStrictThreshold (DdManager *dd, DdNode *f, CUDD_VALUE_TYPE value)
DdNode * Cudd_addBddInterval (DdManager *dd, DdNode *f, CUDD_VALUE_TYPE lower, CUDD_VALUE_TYPE upper)
DdNode * Cudd_addBddIthBit (DdManager *dd, DdNode *f, int bit)
DdNode * Cudd_BddToAdd (DdManager *dd, DdNode *B)
DdNode * Cudd_addBddPattern (DdManager *dd, DdNode *f)
DdNode * Cudd_bddTransfer (DdManager *ddSource, DdManager *ddDestination, DdNode *f)
DdNode * cuddBddTransfer (DdManager *ddS, DdManager *ddD, DdNode *f)
static DdNode * addBddDoThreshold (DdManager *dd, DdNode *f, DdNode *val)
static DdNode * addBddDoStrictThreshold (DdManager *dd, DdNode *f, DdNode *val)
static DdNode * addBddDoInterval (DdManager *dd, DdNode *f, DdNode *l, DdNode *u)
static DdNode * addBddDoIthBit (DdManager *dd, DdNode *f, DdNode *index)
static DdNode * ddBddToAddRecur (DdManager *dd, DdNode *B)
static DdNode * addBddDoPattern (DdManager *dd, DdNode *f)
static DdNode * cuddBddTransferRecur (DdManager *ddS, DdManager *ddD, DdNode *f, st_table *table)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddBridge.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* addBddDoInterval (DdManager * dd, DdNode * f, DdNode * l, DdNode * u) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addBddInterval.]
Description [Performs the recursive step for Cudd_addBddInterval. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [addBddDoThreshold addBddDoStrictThreshold]
Definition at line 606 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), cuddV, DD_ONE, and DdNode::index.
Referenced by Cudd_addBddInterval().
static DdNode* addBddDoIthBit (DdManager * dd, DdNode * f, DdNode * index) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addBddIthBit.]
Description [Performs the recursive step for Cudd_addBddIthBit. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 679 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), cuddV, DD_ONE, and DdNode::index.
Referenced by Cudd_addBddIthBit().
static DdNode* addBddDoPattern (DdManager * dd, DdNode * f) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addBddPattern.]
Description [Performs the recursive step for Cudd_addBddPattern. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 840 of file cuddBridge.c.
References Cudd_addBddPattern(), Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, and DdNode::index.
Referenced by Cudd_addBddPattern().
static DdNode* addBddDoStrictThreshold (DdManager * dd, DdNode * f, DdNode * val) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addBddStrictThreshold.]
Description [Performs the recursive step for Cudd_addBddStrictThreshold. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [addBddDoThreshold]
Definition at line 534 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), cuddV, DD_ONE, and DdNode::index.
Referenced by Cudd_addBddStrictThreshold().
static DdNode* addBddDoThreshold (DdManager * dd, DdNode * f, DdNode * val) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_addBddThreshold.]
Description [Performs the recursive step for Cudd_addBddThreshold. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [addBddDoStrictThreshold]
Definition at line 462 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), cuddV, DD_ONE, and DdNode::index.
Referenced by Cudd_addBddThreshold().
static DdNode* cuddBddTransferRecur ARGS ((DdManager *ddS, DdManager *ddD, DdNode *f, st_table *table)) [static]
static DdNode* addBddDoPattern ARGS ((DdManager *dd, DdNode *f)) [static]
static DdNode* ddBddToAddRecur ARGS ((DdManager *dd, DdNode *B)) [static]
static DdNode* addBddDoIthBit ARGS ((DdManager *dd, DdNode *f, DdNode *index)) [static]
static DdNode* addBddDoInterval ARGS ((DdManager *dd, DdNode *f, DdNode *l, DdNode *u)) [static]
static DdNode *addBddDoStrictThreshold ARGS ((DdManager *dd, DdNode *f, DdNode *val)) [static]
AutomaticStart
DdNode* Cudd_addBddInterval (DdManager * dd, DdNode * f, CUDD_VALUE_TYPE lower, CUDD_VALUE_TYPE upper)
Function********************************************************************
Synopsis [Converts an ADD to a BDD.]
Description [Converts an ADD to a BDD by replacing all discriminants greater than or equal to lower and less than or equal to upper with 1, and all other discriminants with 0. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddThreshold Cudd_addBddStrictThreshold Cudd_addBddPattern Cudd_BddToAdd]
Definition at line 209 of file cuddBridge.c.
References addBddDoInterval(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, cuddUniqueConst(), and DdManager::reordered.
DdNode* Cudd_addBddIthBit (DdManager * dd, DdNode * f, int bit)
Function********************************************************************
Synopsis [Converts an ADD to a BDD by extracting the i-th bit from the leaves.]
Description [Converts an ADD to a BDD by replacing all discriminants whose i-th bit is equal to 1 with 1, and all other discriminants with 0. The i-th bit refers to the integer representation of the leaf value. If the value is has a fractional part, it is ignored. Repeated calls to this procedure allow one to transform an integer-valued ADD into an array of BDDs, one for each bit of the leaf values. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddInterval Cudd_addBddPattern Cudd_BddToAdd]
Definition at line 271 of file cuddBridge.c.
References addBddDoIthBit(), Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddDeref, cuddRef, cuddUniqueConst(), and DdManager::reordered.
DdNode* Cudd_addBddPattern (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Converts an ADD to a BDD.]
Description [Converts an ADD to a BDD by replacing all discriminants different from 0 with 1. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_BddToAdd Cudd_addBddThreshold Cudd_addBddInterval Cudd_addBddStrictThreshold]
Definition at line 344 of file cuddBridge.c.
References addBddDoPattern(), and DdManager::reordered.
Referenced by addBddDoPattern().
DdNode* Cudd_addBddStrictThreshold (DdManager * dd, DdNode * f, CUDD_VALUE_TYPE value)
Function********************************************************************
Synopsis [Converts an ADD to a BDD.]
Description [Converts an ADD to a BDD by replacing all discriminants STRICTLY greater than value with 1, and all other discriminants with 0. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddInterval Cudd_addBddPattern Cudd_BddToAdd Cudd_addBddThreshold]
Definition at line 164 of file cuddBridge.c.
References addBddDoStrictThreshold(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, cuddUniqueConst(), and DdManager::reordered.
DdNode* Cudd_addBddThreshold (DdManager * dd, DdNode * f, CUDD_VALUE_TYPE value)
Function********************************************************************
Synopsis [Converts an ADD to a BDD.]
Description [Converts an ADD to a BDD by replacing all discriminants greater than or equal to value with 1, and all other discriminants with 0. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddInterval Cudd_addBddPattern Cudd_BddToAdd Cudd_addBddStrictThreshold]
Definition at line 119 of file cuddBridge.c.
References addBddDoThreshold(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, cuddUniqueConst(), and DdManager::reordered.
DdNode* Cudd_BddToAdd (DdManager * dd, DdNode * B)
Function********************************************************************
Synopsis [Converts a BDD to a 0-1 ADD.]
Description [Converts a BDD to a 0-1 ADD. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addBddPattern Cudd_addBddThreshold Cudd_addBddInterval Cudd_addBddStrictThreshold]
Definition at line 314 of file cuddBridge.c.
References ddBddToAddRecur(), and DdManager::reordered.
Referenced by Cudd_addHamming().
DdNode* Cudd_bddTransfer (DdManager * ddSource, DdManager * ddDestination, DdNode * f)
Function********************************************************************
Synopsis [Convert a BDD from a manager to another one.]
Description [Convert a BDD from a manager to another one. Returns a pointer to the BDD in the destination manager if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 373 of file cuddBridge.c.
References cuddBddTransfer(), and DdManager::reordered.
DdNode* cuddBddTransfer (DdManager * ddS, DdManager * ddD, DdNode * f)
Function********************************************************************
Synopsis [Convert a BDD from a manager to another one.]
Description [Convert a BDD from a manager to another one. Returns a pointer to the BDD in the destination manager if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddTransfer]
Definition at line 407 of file cuddBridge.c.
References Cudd_RecursiveDeref(), cuddBddTransferRecur(), cuddDeref, cuddRef, st_free_gen(), st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), and st_ptrhash().
Referenced by Cudd_bddTransfer().
static DdNode* cuddBddTransferRecur (DdManager * ddS, DdManager * ddD, DdNode * f, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddTransfer.]
Description [Performs the recursive step of Cudd_bddTransfer. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddBddTransfer]
Definition at line 911 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), cuddBddIteRecur(), cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, one, st_add_direct(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by cuddBddTransfer().
static DdNode* ddBddToAddRecur (DdManager * dd, DdNode * B) [static]
Function********************************************************************
Synopsis [Performs the recursive step for Cudd_BddToAdd.]
Description [Performs the recursive step for Cudd_BddToAdd. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 754 of file cuddBridge.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_RecursiveDeref(), Cudd_Regular, cuddAddCmplRecur(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, and one.
Referenced by Cudd_BddToAdd().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddBridge.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddBridge.c]
PackageName [cudd]
Synopsis [Translation from BDD to ADD and vice versa and transfer between different managers.]
Description [External procedures included in this file:
Cudd_addBddThreshold()
Cudd_addBddStrictThreshold()
Cudd_addBddInterval()
Cudd_addBddIthBit()
Cudd_BddToAdd()
Cudd_addBddPattern()
Cudd_bddTRnasfer()
Internal procedures included in this file:
cuddBddTransfer()
Static procedures included in this file:
addBddDoThreshold()
addBddDoStrictThreshold()
addBddDoInterval()
addBddDoIthBit()
ddBddToAddRecur()
addBddDoPattern()
cuddBddTransferRecur()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 73 of file cuddBridge.c.