cuddAddNeg.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_addNegate (DdManager *dd, DdNode *f)
DdNode * Cudd_addRoundOff (DdManager *dd, DdNode *f, int N)
DdNode * cuddAddNegateRecur (DdManager *dd, DdNode *f)
DdNode * cuddAddRoundOffRecur (DdManager *dd, DdNode *f, double trunc)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddNeg.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_addNegate (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Computes the additive inverse of an ADD.]
Description [Computes the additive inverse of an ADD. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addCmpl]
Definition at line 91 of file cuddAddNeg.c.
References cuddAddNegateRecur(), and DdManager::reordered.
Referenced by cuddAddNegateRecur().
DdNode* Cudd_addRoundOff (DdManager * dd, DdNode * f, int N)
Function********************************************************************
Synopsis [Rounds off the discriminants of an ADD.]
Description [Rounds off the discriminants of an ADD. The discriminants are rounded off to N digits after the decimal. Returns a pointer to the result ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 119 of file cuddAddNeg.c.
References cuddAddRoundOffRecur(), and DdManager::reordered.
Referenced by cuddAddRoundOffRecur().
DdNode* cuddAddNegateRecur (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_addNegate.]
Description [Implements the recursive step of Cudd_addNegate. Returns a pointer to the result.]
SideEffects [None]
Definition at line 151 of file cuddAddNeg.c.
References Cudd_addNegate(), Cudd_RecursiveDeref(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueConst(), cuddUniqueInter(), cuddV, and DdNode::index.
Referenced by Cudd_addMinus(), and Cudd_addNegate().
DdNode* cuddAddRoundOffRecur (DdManager * dd, DdNode * f, double trunc)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_addRoundOff.]
Description [Implements the recursive step of Cudd_addRoundOff. Returns a pointer to the result.]
SideEffects [None]
Definition at line 210 of file cuddAddNeg.c.
References Cudd_addRoundOff(), Cudd_RecursiveDeref(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueConst(), cuddUniqueInter(), cuddV, and DdNode::index.
Referenced by Cudd_addRoundOff().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddNeg.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddNeg.c]
PackageName [cudd]
Synopsis [function to compute the negation of an ADD.]
Description [External procedures included in this module:
Cudd_addNegate()
Cudd_addRoundOff()
Internal procedures included in this module:
cuddAddNegateRecur()
cuddAddRoundOffRecur()
]
Author [Fabio Somenzi, Balakrishna Kumthekar]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 55 of file cuddAddNeg.c.