cuddSat.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct cuddPathPair
Defines
#define DD_BIGGY 1000000
#define WEIGHT(weight, col) ((weight) == NULL ? 1 : weight[col])
Functions
static enum st_retval free_path_pair ARGS ((char *key, char *value, char *arg))
static cuddPathPair get_shortest ARGS ((DdNode *root, int *cost, int *support, st_table *visited))
static DdNode *get_path ARGS ((DdManager *manager, st_table *visited, DdNode *f, int *weight, int cost))
static cuddPathPair get_largest ARGS ((DdNode *root, st_table *visited))
static DdNode *get_cube ARGS ((DdManager *manager, st_table *visited, DdNode *f, int cost))
DdNode * Cudd_Eval (DdManager *dd, DdNode *f, int *inputs)
DdNode * Cudd_ShortestPath (DdManager *manager, DdNode *f, int *weight, int *support, int *length)
DdNode * Cudd_LargestCube (DdManager *manager, DdNode *f, int *length)
int Cudd_ShortestLength (DdManager *manager, DdNode *f, int *weight)
DdNode * Cudd_Decreasing (DdManager *dd, DdNode *f, int i)
DdNode * Cudd_Increasing (DdManager *dd, DdNode *f, int i)
int Cudd_EquivDC (DdManager *dd, DdNode *F, DdNode *G, DdNode *D)
int Cudd_EqualSupNorm (DdManager *dd, DdNode *f, DdNode *g, CUDD_VALUE_TYPE tolerance, int pr)
static enum st_retval free_path_pair (char *key, char *value, char *arg)
static cuddPathPair get_shortest (DdNode *root, int *cost, int *support, st_table *visited)
static DdNode * get_path (DdManager *manager, st_table *visited, DdNode *f, int *weight, int cost)
static cuddPathPair get_largest (DdNode *root, st_table *visited)
static DdNode * get_cube (DdManager *manager, st_table *visited, DdNode *f, int cost)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddSat.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static DdNode * one
static DdNode * zero
Define Documentation
#define DD_BIGGY 1000000
CFile***********************************************************************
FileName [cuddSat.c]
PackageName [cudd]
Synopsis [Functions for the solution of satisfiability related problems.]
Description [External procedures included in this file:
Cudd_Eval()
Cudd_ShortestPath()
Cudd_LargestCube()
Cudd_ShortestLength()
Cudd_Decreasing()
Cudd_Increasing()
Cudd_EquivDC()
Cudd_EqualSupNorm()
Static procedures included in this module:
free_path_pair()
get_shortest()
get_path()
get_largest()
get_cube()
]
Author [Seh-Woong Jeong, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 49 of file cuddSat.c.
Referenced by Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), get_largest(), and get_shortest().
#define WEIGHT(weight, col) ((weight) == NULL ? 1 : weight[col])
Definition at line 78 of file cuddSat.c.
Referenced by get_path(), and get_shortest().
Function Documentation
static DdNode* get_cube ARGS ((DdManager *manager, st_table *visited, DdNode *f, int cost)) [static]
static cuddPathPair get_largest ARGS ((DdNode *root, st_table *visited)) [static]
static DdNode* get_path ARGS ((DdManager *manager, st_table *visited, DdNode *f, int *weight, int cost)) [static]
static cuddPathPair get_shortest ARGS ((DdNode *root, int *cost, int *support, st_table *visited)) [static]
static enum st_retval free_path_pair ARGS ((char *key, char *value, char *arg)) [static]
AutomaticStart
DdNode* Cudd_Decreasing (DdManager * dd, DdNode * f, int i)
Function********************************************************************
Synopsis [Determines whether a BDD is negative unate in a variable.]
Description [Determines whether the function represented by BDD f is negative unate (monotonic decreasing) in variable i. Returns the constant one is f is unate and the (logical) constant zero if it is not. This function does not generate any new nodes.]
SideEffects [None]
SeeAlso [Cudd_Increasing]
Definition at line 369 of file cuddSat.c.
References assert, Cudd_bddLeq(), Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddI, cuddT, DD_ONE, DdNode::index, DdManager::perm, size, and DdManager::vars.
Referenced by Cudd_Increasing().
int Cudd_EqualSupNorm (DdManager * dd, DdNode * f, DdNode * g, CUDD_VALUE_TYPE tolerance, int pr)
Function********************************************************************
Synopsis [Compares two ADDs for equality within tolerance.]
Description [Compares two ADDs for equality within tolerance. Two ADDs are reported to be equal if the maximum difference between them (the sup norm of their difference) is less than or equal to the tolerance parameter. Returns 1 if the two ADDs are equal (within tolerance); 0 otherwise. If parameter pr is positive the first failure is reported to the standard output.]
SideEffects [None]
SeeAlso []
Definition at line 580 of file cuddSat.c.
References Cudd_IsConstant, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddI, cuddT, cuddV, DD_ONE, ddEqualVal, and DdNode::index.
int Cudd_EquivDC (DdManager * dd, DdNode * F, DdNode * G, DdNode * D)
Function********************************************************************
Synopsis [Tells whether F and G are identical wherever D is 0.]
Description [Tells whether F and G are identical wherever D is 0. F and G are either two ADDs or two BDDs. D is either a 0-1 ADD or a BDD. The function returns 1 if F and G are equivalent, and 0 otherwise. No new nodes are created.]
SideEffects [None]
SeeAlso []
Definition at line 473 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddCacheInsert(), cuddCacheLookup(), cuddE, cuddI, cuddT, DD_ONE, DD_ZERO, ddMin, DdNode::index, one, and DdManager::perm.
DdNode* Cudd_Eval (DdManager * dd, DdNode * f, int * inputs)
Function********************************************************************
Synopsis [Returns the value of a DD for a given variable assignment.]
Description [Finds the value of a DD for a given variable assignment. The variable assignment is passed in an array of int's, that should specify a zero or a one for each variable in the support of the function. Returns a pointer to a constant node. No new nodes are produced.]
SideEffects [None]
SeeAlso [Cudd_bddLeq Cudd_addEvalConst]
Definition at line 116 of file cuddSat.c.
References Cudd_IsComplement, Cudd_NotCond, Cudd_Regular, cuddE, cuddIsConstant, cuddT, and DdNode::index.
DdNode* Cudd_Increasing (DdManager * dd, DdNode * f, int i)
Function********************************************************************
Synopsis [Determines whether a BDD is positive unate in a variable.]
Description [Determines whether the function represented by BDD f is positive unate (monotonic decreasing) in variable i. It is based on Cudd_Decreasing and the fact that f is monotonic increasing in i if and only if its complement is monotonic decreasing in i.]
SideEffects [None]
SeeAlso [Cudd_Decreasing]
Definition at line 448 of file cuddSat.c.
References Cudd_Decreasing(), and Cudd_Not.
DdNode* Cudd_LargestCube (DdManager * manager, DdNode * f, int * length)
Function********************************************************************
Synopsis [Finds a largest cube in a DD.]
Description [Finds a largest cube in a DD. f is the DD we want to get the largest cube for. The problem is translated into the one of finding a shortest path in f, when both THEN and ELSE arcs are assumed to have unit length. This yields a largest cube in the disjoint cover corresponding to the DD. Therefore, it is not necessarily the largest implicant of f. Returns the largest cube as a BDD.]
SideEffects [The number of literals of the cube is returned in length.]
SeeAlso [Cudd_ShortestPath]
Definition at line 240 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, DD_BIGGY, DD_ONE, DD_ZERO, free_path_pair(), get_cube(), get_largest(), one, DdManager::reordered, st_foreach(), st_free_table(), st_init_table(), st_lookup(), st_ptrcmp(), st_ptrhash(), and zero.
int Cudd_ShortestLength (DdManager * manager, DdNode * f, int * weight)
Function********************************************************************
Synopsis [Find the length of the shortest path(s) in a DD.]
Description [Find the length of the shortest path(s) in a DD. f is the DD we want to get the shortest path for; weight\[i\] is the weight of the THEN edge coming from the node whose index is i. All ELSE edges have 0 weight. Returns the length of the shortest path(s) if successful; CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso [Cudd_ShortestPath]
Definition at line 309 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, DD_BIGGY, DD_ONE, DD_ZERO, free_path_pair(), get_shortest(), one, st_foreach(), st_free_table(), st_init_table(), st_lookup(), st_ptrcmp(), st_ptrhash(), and zero.
DdNode* Cudd_ShortestPath (DdManager * manager, DdNode * f, int * weight, int * support, int * length)
Function********************************************************************
Synopsis [Finds a shortest path in a DD.]
Description [Finds a shortest path in a DD. f is the DD we want to get the shortest path for; weight\[i\] is the weight of the THEN arc coming from the node whose index is i. If weight is NULL, then unit weights are assumed for all THEN arcs. All ELSE arcs have 0 weight. If non-NULL, both weight and support should point to arrays with at least as many entries as there are variables in the manager. Returns the shortest path as the BDD of a cube.]
SideEffects [support contains on return the true support of f. If support is NULL on entry, then Cudd_ShortestPath does not compute the true support info. length contains the length of the path.]
SeeAlso [Cudd_ShortestLength Cudd_LargestCube]
Definition at line 160 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, DD_BIGGY, DD_ONE, DD_ZERO, free_path_pair(), get_path(), get_shortest(), one, DdManager::reordered, DdManager::size, st_foreach(), st_free_table(), st_init_table(), st_lookup(), st_ptrcmp(), st_ptrhash(), and zero.
static enum st_retval free_path_pair (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees the entries of the visited symbol table.]
Description [Frees the entries of the visited symbol table. Returns ST_CONTINUE.]
SideEffects [None]
Definition at line 658 of file cuddSat.c.
References FREE, and ST_CONTINUE.
Referenced by Cudd_LargestCube(), Cudd_ShortestLength(), and Cudd_ShortestPath().
static DdNode* get_cube (DdManager * manager, st_table * visited, DdNode * f, int cost) [static]
Function********************************************************************
Synopsis [Build a BDD for a largest cube of f.]
Description [Build a BDD for a largest cube of f. Given the minimum length from the root, and the minimum lengths for each node (in visited), apply triangulation at each node. Of the two children of each node on a shortest path, at least one is on a shortest path. In case of ties the procedure chooses the THEN children. Returns a pointer to the cube BDD representing the path if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 956 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, DdNode::index, one, st_lookup(), and DdManager::vars.
Referenced by Cudd_LargestCube().
static cuddPathPair get_largest (DdNode * root, st_table * visited) [static]
Function********************************************************************
Synopsis [Finds the size of the largest cube(s) in a DD.]
Description [Finds the size of the largest cube(s) in a DD. This problem is translated into finding the shortest paths from a node when both THEN and ELSE arcs have unit lengths. Uses a local symbol table to store the lengths for each node. Only the lengths for the regular nodes are entered in the table, because those for the complement nodes are simply obtained by swapping the two lenghts. Returns a pair of lengths: the length of the shortest path to 1; and the length of the shortest path to 0. This is done so as to take complement arcs into account.]
SideEffects [none]
SeeAlso []
Definition at line 874 of file cuddSat.c.
References ALLOC, Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DD_BIGGY, ddMin, cuddPathPair::neg, cuddPathPair::pos, st_insert(), st_lookup(), and zero.
Referenced by Cudd_LargestCube().
static DdNode* get_path (DdManager * manager, st_table * visited, DdNode * f, int * weight, int cost) [static]
Function********************************************************************
Synopsis [Build a BDD for a shortest path of f.]
Description [Build a BDD for a shortest path of f. Given the minimum length from the root, and the minimum lengths for each node (in visited), apply triangulation at each node. Of the two children of each node on a shortest path, at least one is on a shortest path. In case of ties the procedure chooses the THEN children. Returns a pointer to the cube BDD representing the path if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 782 of file cuddSat.c.
References Cudd_IsComplement, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, DdNode::index, one, st_lookup(), DdManager::vars, and WEIGHT.
Referenced by Cudd_ShortestPath().
static cuddPathPair get_shortest (DdNode * root, int * cost, int * support, st_table * visited) [static]
Function********************************************************************
Synopsis [Finds the length of the shortest path(s) in a DD.]
Description [Finds the length of the shortest path(s) in a DD. Uses a local symbol table to store the lengths for each node. Only the lengths for the regular nodes are entered in the table, because those for the complement nodes are simply obtained by swapping the two lenghts. Returns a pair of lengths: the length of the shortest path to 1; and the length of the shortest path to 0. This is done so as to take complement arcs into account.]
SideEffects [Accumulates the support of the DD in support.]
SeeAlso []
Definition at line 691 of file cuddSat.c.
References ALLOC, Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DD_BIGGY, ddMin, cuddPathPair::neg, cuddPathPair::pos, st_insert(), st_lookup(), WEIGHT, and zero.
Referenced by Cudd_ShortestLength(), and Cudd_ShortestPath().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddSat.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 69 of file cuddSat.c.
DdNode* one [static]
Definition at line 72 of file cuddSat.c.
DdNode * zero [static]
Definition at line 72 of file cuddSat.c.