cuddZddFuncs.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_zddProduct (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_zddUnateProduct (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_zddWeakDiv (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_zddDivide (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_zddWeakDivF (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_zddDivideF (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddProduct (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddUnateProduct (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddWeakDiv (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddWeakDivF (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddDivide (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddZddDivideF (DdManager *dd, DdNode *f, DdNode *g)
int cuddZddGetCofactors3 (DdManager *dd, DdNode *f, int v, DdNode **f1, DdNode **f0, DdNode **fd)
int cuddZddGetCofactors2 (DdManager *dd, DdNode *f, int v, DdNode **f1, DdNode **f0)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddFuncs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_zddDivide (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the quotient of two unate covers.]
Description [Computes the quotient of two unate covers represented by ZDDs. Unate covers use one ZDD variable for each BDD variable. Returns a pointer to the resulting ZDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddWeakDiv]
Definition at line 206 of file cuddZddFuncs.c.
References cuddZddDivide(), and DdManager::reordered.
DdNode* Cudd_zddDivideF (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Modified version of Cudd_zddDivide.]
Description [Modified version of Cudd_zddDivide. This function may disappear in future releases.]
SideEffects [None]
SeeAlso []
Definition at line 264 of file cuddZddFuncs.c.
References cuddZddDivideF(), and DdManager::reordered.
DdNode* Cudd_zddProduct (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the product of two covers represented by ZDDs.]
Description [Computes the product of two covers represented by ZDDs. The result is also a ZDD. Returns a pointer to the result if successful; NULL otherwise. The covers on which Cudd_zddProduct operates use two ZDD variables for each function variable (one ZDD variable for each literal of the variable). Those two ZDD variables should be adjacent in the order.]
SideEffects [None]
SeeAlso [Cudd_zddUnateProduct]
Definition at line 110 of file cuddZddFuncs.c.
References cuddZddProduct(), and DdManager::reordered.
DdNode* Cudd_zddUnateProduct (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the product of two unate covers.]
Description [Computes the product of two unate covers represented as ZDDs. Unate covers use one ZDD variable for each BDD variable. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddProduct]
Definition at line 141 of file cuddZddFuncs.c.
References cuddZddUnateProduct(), and DdManager::reordered.
DdNode* Cudd_zddWeakDiv (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Applies weak division to two covers.]
Description [Applies weak division to two ZDDs representing two covers. Returns a pointer to the ZDD representing the result if successful; NULL otherwise. The result of weak division depends on the variable order. The covers on which Cudd_zddWeakDiv operates use two ZDD variables for each function variable (one ZDD variable for each literal of the variable). Those two ZDD variables should be adjacent in the order.]
SideEffects [None]
SeeAlso [Cudd_zddDivide]
Definition at line 175 of file cuddZddFuncs.c.
References cuddZddWeakDiv(), and DdManager::reordered.
DdNode* Cudd_zddWeakDivF (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Modified version of Cudd_zddWeakDiv.]
Description [Modified version of Cudd_zddWeakDiv. This function may disappear in future releases.]
SideEffects [None]
SeeAlso [Cudd_zddWeakDiv]
Definition at line 235 of file cuddZddFuncs.c.
References cuddZddWeakDivF(), and DdManager::reordered.
DdNode* cuddZddDivide (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddDivide.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddDivide]
Definition at line 1066 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors2(), cuddZddIntersect(), DD_ONE, DD_ZERO, one, and zero.
Referenced by Cudd_zddDivide().
DdNode* cuddZddDivideF (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddDivideF.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddDivideF]
Definition at line 1165 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors2(), cuddZddIntersect(), DD_ONE, DD_ZERO, one, and zero.
Referenced by Cudd_zddDivideF().
int cuddZddGetCofactors2 (DdManager * dd, DdNode * f, int v, DdNode ** f1, DdNode ** f0)
Function********************************************************************
Synopsis [Computes the two-way decomposition of f w.r.t. v.]
Description []
SideEffects [The results are returned in f1 and f0.]
SeeAlso [cuddZddGetCofactors3]
Definition at line 1347 of file cuddZddFuncs.c.
References Cudd_RecursiveDerefZdd(), cuddZddSubset0(), and cuddZddSubset1().
Referenced by cuddZddDivide(), cuddZddDivideF(), and cuddZddUnateProduct().
int cuddZddGetCofactors3 (DdManager * dd, DdNode * f, int v, DdNode ** f1, DdNode ** f0, DdNode ** fd)
Function********************************************************************
Synopsis [Computes the three-way decomposition of f w.r.t. v.]
Description [Computes the three-way decomposition of function f (represented by a ZDD) wit respect to variable v.]
SideEffects [The results are returned in f1, f0, and fd.]
SeeAlso [cuddZddGetCofactors2]
Definition at line 1265 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddZddSubset0(), cuddZddSubset1(), DD_ZERO, DdManager::permZ, and zero.
Referenced by cuddZddProduct(), cuddZddWeakDiv(), and cuddZddWeakDivF().
DdNode* cuddZddProduct (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddProduct.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddProduct]
Definition at line 297 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors3(), cuddZddGetNode(), cuddZddUnion(), DD_ONE, DD_ZERO, one, DdManager::permZ, and zero.
Referenced by Cudd_zddProduct(), and cuddZddGetNodeIVO().
DdNode* cuddZddUnateProduct (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddUnateProduct.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddUnateProduct]
Definition at line 531 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors2(), cuddZddGetNode(), cuddZddUnion(), DD_ONE, DD_ZERO, one, DdManager::permZ, and zero.
Referenced by Cudd_zddUnateProduct().
DdNode* cuddZddWeakDiv (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddWeakDiv.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddWeakDiv]
Definition at line 674 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors3(), cuddZddIntersect(), DD_ONE, DD_ZERO, one, and zero.
Referenced by Cudd_zddWeakDiv().
DdNode* cuddZddWeakDivF (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddWeakDivF.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddWeakDivF]
Definition at line 834 of file cuddZddFuncs.c.
References Cudd_Deref(), Cudd_RecursiveDerefZdd(), Cudd_Ref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2Zdd(), cuddZddGetCofactors3(), cuddZddGetNode(), cuddZddIntersect(), DD_ONE, DD_ZERO, ddMin, one, DdManager::permZ, and zero.
Referenced by Cudd_zddWeakDivF().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddFuncs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddFuncs.c]
PackageName [cudd]
Synopsis [Functions to manipulate covers represented as ZDDs.]
Description [External procedures included in this module:
Cudd_zddProduct();
Cudd_zddUnateProduct();
Cudd_zddWeakDiv();
Cudd_zddWeakDivF();
Cudd_zddDivide();
Cudd_zddDivideF();
Internal procedures included in this module:
cuddZddProduct();
cuddZddUnateProduct();
cuddZddWeakDiv();
cuddZddWeakDivF();
cuddZddDivide();
cuddZddDivideF();
cuddZddGetCofactors3()
cuddZddGetCofactors2()
Static procedures included in this module:
]
SeeAlso []
Author [In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 70 of file cuddZddFuncs.c.