cuddZddReord.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define DD_MAX_SUBTABLE_SPARSITY 8
#define DD_SHRINK_FACTOR 2
Functions
static Move *zddSwapAny ARGS ((DdManager *table, int x, int y))
static int cuddZddSiftingAux ARGS ((DdManager *table, int x, int x_low, int x_high))
static Move *cuddZddSiftingUp ARGS ((DdManager *table, int x, int x_low, int initial_size))
static Move *cuddZddSiftingDown ARGS ((DdManager *table, int x, int x_high, int initial_size))
static int cuddZddSiftingBackward ARGS ((DdManager *table, Move *moves, int size))
static void zddReorderPreprocess ARGS ((DdManager *table))
static int zddShuffle ARGS ((DdManager *table, int *permutation))
static int zddSiftUp ARGS ((DdManager *table, int x, int xLow))
static void zddFixTree ARGS ((DdManager *table, MtrNode *treenode))
int Cudd_zddReduceHeap (DdManager *table, Cudd_ReorderingType heuristic, int minsize)
int Cudd_zddShuffleHeap (DdManager *table, int *permutation)
int cuddZddAlignToBdd (DdManager *table)
int cuddZddNextHigh (DdManager *table, int x)
int cuddZddNextLow (DdManager *table, int x)
int cuddZddUniqueCompare (int *ptr_x, int *ptr_y)
int cuddZddSwapInPlace (DdManager *table, int x, int y)
int cuddZddSwapping (DdManager *table, int lower, int upper, Cudd_ReorderingType heuristic)
int cuddZddSifting (DdManager *table, int lower, int upper)
static Move * zddSwapAny (DdManager *table, int x, int y)
static int cuddZddSiftingAux (DdManager *table, int x, int x_low, int x_high)
static Move * cuddZddSiftingUp (DdManager *table, int x, int x_low, int initial_size)
static Move * cuddZddSiftingDown (DdManager *table, int x, int x_high, int initial_size)
static int cuddZddSiftingBackward (DdManager *table, Move *moves, int size)
static void zddReorderPreprocess (DdManager *table)
static int zddReorderPostprocess (DdManager *table)
static int zddShuffle (DdManager *table, int *permutation)
static int zddSiftUp (DdManager *table, int x, int xLow)
static void zddFixTree (DdManager *table, MtrNode *treenode)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddReord.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
int * zdd_entry
int zddTotalNumberSwapping
static DdNode * empty
Define Documentation
#define DD_MAX_SUBTABLE_SPARSITY 8
CFile***********************************************************************
FileName [cuddZddReord.c]
PackageName [cudd]
Synopsis [Procedures for dynamic variable ordering of ZDDs.]
Description [External procedures included in this module:
Cudd_zddReduceHeap()
Cudd_zddShuffleHeap()
Internal procedures included in this module:
cuddZddAlignToBdd()
cuddZddNextHigh()
cuddZddNextLow()
cuddZddUniqueCompare()
cuddZddSwapInPlace()
cuddZddSwapping()
cuddZddSifting()
Static procedures included in this module:
zddSwapAny()
cuddZddSiftingAux()
cuddZddSiftingUp()
cuddZddSiftingDown()
cuddZddSiftingBackward()
zddReorderPreprocess()
zddReorderPostprocess()
zddShuffle()
zddSiftUp()
]
SeeAlso []
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 58 of file cuddZddReord.c.
#define DD_SHRINK_FACTOR 2
Definition at line 59 of file cuddZddReord.c.
Function Documentation
static void zddFixTree ARGS ((DdManager *table, MtrNode *treenode)) [static]
static int zddSiftUp ARGS ((DdManager *table, int x, int xLow)) [static]
static int zddShuffle ARGS ((DdManager *table, int *permutation)) [static]
static void zddReorderPreprocess ARGS ((DdManager *table)) [static]
static int cuddZddSiftingBackward ARGS ((DdManager *table, Move *moves, int size)) [static]
static Move* cuddZddSiftingDown ARGS ((DdManager *table, int x, int x_high, int initial_size)) [static]
static Move* cuddZddSiftingUp ARGS ((DdManager *table, int x, int x_low, int initial_size)) [static]
static int cuddZddSiftingAux ARGS ((DdManager *table, int x, int x_low, int x_high)) [static]
static Move* zddSwapAny ARGS ((DdManager *table, int x, int y)) [static]
AutomaticStart
int Cudd_zddReduceHeap (DdManager * table, Cudd_ReorderingType heuristic, int minsize)
Function********************************************************************
Synopsis [Main dynamic reordering routine for ZDDs.]
Description [Main dynamic reordering routine for ZDDs. Calls one of the possible reordering procedures:
Swapping
Sifting
Symmetric Sifting
For sifting and symmetric sifting it is possible to request reordering to convergence.
The core of all methods is the reordering procedure cuddZddSwapInPlace() which swaps two adjacent variables. Returns 1 in case of success; 0 otherwise. In the case of symmetric sifting (with and without convergence) returns 1 plus the number of symmetric variables, in case of success.]
SideEffects [Changes the variable order for all ZDDs and clears the cache.]
Definition at line 142 of file cuddZddReord.c.
References DdManager::autoMethodZ, CUDD_REORDER_LINEAR, CUDD_REORDER_LINEAR_CONVERGE, CUDD_REORDER_NONE, CUDD_REORDER_RANDOM, CUDD_REORDER_RANDOM_PIVOT, CUDD_REORDER_SAME, CUDD_REORDER_SIFT, CUDD_REORDER_SIFT_CONVERGE, CUDD_REORDER_SYMM_SIFT, CUDD_REORDER_SYMM_SIFT_CONV, cuddBddAlignToZdd(), cuddZddTreeSifting(), DD_DYN_RATIO, DdManager::deadZ, empty, DdManager::keysZ, DdHook::next, DdManager::nextDyn, DdManager::postReorderingHook, DdManager::preReorderingHook, DdManager::realignZ, DdManager::reordered, DdManager::reorderings, DdManager::reordTime, result, util_cpu_time(), zddReorderPostprocess(), zddReorderPreprocess(), zddTotalNumberSwapping, and DdManager::zero.
Referenced by cuddUniqueInterZdd().
int Cudd_zddShuffleHeap (DdManager * table, int * permutation)
Function********************************************************************
Synopsis [Reorders ZDD variables according to given permutation.]
Description [Reorders ZDD variables according to given permutation. The i-th entry of the permutation array contains the index of the variable that should be brought to the i-th level. The size of the array should be equal or greater to the number of variables currently in use. Returns 1 in case of success; 0 otherwise.]
SideEffects [Changes the ZDD variable order for all diagrams and clears the cache.]
SeeAlso [Cudd_zddReduceHeap]
Definition at line 275 of file cuddZddReord.c.
References empty, result, zddReorderPostprocess(), zddReorderPreprocess(), zddShuffle(), and DdManager::zero.
Referenced by Cudd_zddVarsFromBddVars().
int cuddZddAlignToBdd (DdManager * table)
Function********************************************************************
Synopsis [Reorders ZDD variables according to the order of the BDD variables.]
Description [Reorders ZDD variables according to the order of the BDD variables. This function can be called at the end of BDD reordering to insure that the order of the ZDD variables is consistent with the order of the BDD variables. The number of ZDD variables must be a multiple of the number of BDD variables. Let M be the ratio of the two numbers. cuddZddAlignToBdd then considers the ZDD variables from M*i to (M+1)*i-1 as corresponding to BDD variable i. This function should be normally called from Cudd_ReduceHeap, which clears the cache. Returns 1 in case of success; 0 otherwise.]
SideEffects [Changes the ZDD variable order for all diagrams and performs garbage collection of the ZDD unique table.]
SeeAlso [Cudd_zddShuffleHeap Cudd_ReduceHeap]
Definition at line 323 of file cuddZddReord.c.
References ALLOC, CUDD_MEMORY_OUT, cuddGarbageCollectZdd(), empty, DdManager::errorCode, FREE, DdManager::invperm, DdManager::invpermZ, DdManager::permZ, result, DdManager::size, DdManager::sizeZ, zddFixTree(), zddShuffle(), and DdManager::zero.
Referenced by Cudd_ReduceHeap().
int cuddZddNextHigh (DdManager * table, int x)
Function********************************************************************
Synopsis [Finds the next subtable with a larger index.]
Description [Finds the next subtable with a larger index. Returns the index.]
SideEffects [None]
SeeAlso []
Definition at line 384 of file cuddZddReord.c.
Referenced by cuddZddLinearDown(), cuddZddLinearInPlace(), cuddZddSiftingDown(), cuddZddSwapInPlace(), cuddZddSymmSifting_down(), zddGroupMove(), zddGroupMoveBackward(), zddGroupSiftingAux(), zddGroupSiftingDown(), and zddSwapAny().
int cuddZddNextLow (DdManager * table, int x)
Function********************************************************************
Synopsis [Finds the next subtable with a smaller index.]
Description [Finds the next subtable with a smaller index. Returns the index.]
SideEffects [None]
SeeAlso []
Definition at line 406 of file cuddZddReord.c.
Referenced by cuddZddLinearUp(), cuddZddSiftingUp(), cuddZddSymmSifting_up(), zddGroupMove(), zddGroupMoveBackward(), zddGroupSiftingUp(), zddSiftUp(), and zddSwapAny().
int cuddZddSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Implementation of Rudell's sifting algorithm.]
Description [Implementation of Rudell's sifting algorithm. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique table.
Sift the variable up and down, remembering each time the total size of the DD heap.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 850 of file cuddZddReord.c.
References ALLOC, CUDD_MEMORY_OUT, cuddZddSiftingAux(), cuddZddUniqueCompare(), ddMin, DdManager::errorCode, FREE, DdSubtable::keys, DdManager::keysZ, DdManager::permZ, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, size, DdManager::sizeZ, DdManager::subtableZ, zdd_entry, and zddTotalNumberSwapping.
Referenced by zddReorderChildren().
static int cuddZddSiftingAux (DdManager * table, int x, int x_low, int x_high) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. Finds the best position and does the required changes. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1100 of file cuddZddReord.c.
References assert, cuddDeallocNode, cuddZddSiftingBackward(), cuddZddSiftingDown(), cuddZddSiftingUp(), DdSubtable::keys, DdManager::keysZ, Move::next, result, DdManager::subtableZ, Move::x, and Move::y.
Referenced by cuddZddSifting().
static int cuddZddSiftingBackward (DdManager * table, Move * moves, int size) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the ZDD heap to the position giving the minimum size.]
Description [Given a set of moves, returns the ZDD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1347 of file cuddZddReord.c.
References Move::next, and Move::size.
Referenced by cuddZddSiftingAux(), and cuddZddSwapping().
static Move* cuddZddSiftingDown (DdManager * table, int x, int x_high, int initial_size) [static]
Function********************************************************************
Synopsis [Sifts a variable down.]
Description [Sifts a variable down. Moves x down until either it reaches the bound (x_high) or the size of the ZDD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 1283 of file cuddZddReord.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextHigh(), cuddZddSwapInPlace(), DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddZddSiftingAux().
static Move* cuddZddSiftingUp (DdManager * table, int x, int x_low, int initial_size) [static]
Function********************************************************************
Synopsis [Sifts a variable up.]
Description [Sifts a variable up. Moves y up until either it reaches the bound (x_low) or the size of the ZDD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 1220 of file cuddZddReord.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextLow(), cuddZddSwapInPlace(), DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddZddSiftingAux().
int cuddZddSwapInPlace (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Swaps two adjacent variables.]
Description [Swaps two adjacent variables. It assumes that no dead nodes are present on entry to this procedure. The procedure then guarantees that no dead nodes will be present when it terminates. cuddZddSwapInPlace assumes that x < y. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 455 of file cuddZddReord.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddE, cuddSatDec, cuddSatInc, cuddT, cuddZddNextHigh(), ddHash, DdSubtable::dead, empty, DdNode::index, DdManager::invpermZ, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdSubtable::slots, DdManager::subtableZ, and zddTotalNumberSwapping.
Referenced by cuddZddLinearDown(), cuddZddLinearUp(), cuddZddSiftingDown(), cuddZddSiftingUp(), cuddZddSymmSifting_down(), cuddZddSymmSifting_up(), cuddZddUndoMoves(), zdd_group_move(), zdd_group_move_backward(), zddGroupMove(), zddGroupMoveBackward(), zddGroupSiftingDown(), zddGroupSiftingUp(), zddSiftUp(), and zddSwapAny().
int cuddZddSwapping (DdManager * table, int lower, int upper, Cudd_ReorderingType heuristic)
Function********************************************************************
Synopsis [Reorders variables by a sequence of (non-adjacent) swaps.]
Description [Implementation of Plessier's algorithm that reorders variables by a sequence of (non-adjacent) swaps.
Select two variables (RANDOM or HEURISTIC).
Permute these variables.
If the nodes have decreased accept the permutation.
Otherwise reconstruct the original heap.
Loop.
Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 729 of file cuddZddReord.c.
References assert, Cudd_Random(), CUDD_REORDER_RANDOM_PIVOT, cuddDeallocNode, cuddZddSiftingBackward(), DdSubtable::keys, DdManager::keysZ, max, Move::next, result, DdManager::subtableZ, and zddSwapAny().
Referenced by zddReorderChildren().
int cuddZddUniqueCompare (int * ptr_x, int * ptr_y)
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
SeeAlso []
Definition at line 430 of file cuddZddReord.c.
References zdd_entry.
Referenced by cuddZddLinearSifting(), cuddZddSifting(), cuddZddSymmSifting(), and cuddZddSymmSiftingConv().
static void zddFixTree (DdManager * table, MtrNode * treenode) [static]
Function********************************************************************
Synopsis [Fixes the ZDD variable group tree after a shuffle.]
Description [Fixes the ZDD variable group tree after a shuffle. Assumes that the order of the variables in a terminal node has not been changed.]
SideEffects [Changes the ZDD variable group tree.]
SeeAlso []
Definition at line 1637 of file cuddZddReord.c.
References MtrNode::child, MtrNode::index, MtrNode::low, MtrNode::parent, DdManager::permZ, DdManager::sizeZ, and MtrNode::younger.
Referenced by cuddZddAlignToBdd().
static int zddReorderPostprocess (DdManager * table) [static]
Function********************************************************************
Synopsis [Shrinks almost empty ZDD subtables at the end of reordering to guarantee that they have a reasonable load factor.]
Description [Shrinks almost empty subtables at the end of reordering to guarantee that they have a reasonable load factor. However, if there many nodes are being reclaimed, then no resizing occurs. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1422 of file cuddZddReord.c.
References ALLOC, DdManager::allocated, Cudd_OutOfMem(), CUDD_UNIQUE_SLOTS, cuddE, cuddT, DD_MAX_SUBTABLE_SPARSITY, ddHash, ddMin, FREE, DdManager::gcPercent, DdSubtable::keys, DdManager::maxCache, DdManager::maxCacheHard, DdSubtable::maxKeys, DdManager::memused, DdManager::minDead, MMoutOfMemory, DdNode::next, DdSubtable::nodelist, DdManager::reclaimed, DdSubtable::shift, DdManager::sizeZ, DdManager::slots, DdSubtable::slots, and DdManager::subtableZ.
Referenced by Cudd_zddReduceHeap(), and Cudd_zddShuffleHeap().
static void zddReorderPreprocess (DdManager * table) [static]
Function********************************************************************
Synopsis [Prepares the ZDD heap for dynamic reordering.]
Description [Prepares the ZDD heap for dynamic reordering. Does garbage collection, to guarantee that there are no dead nodes; and clears the cache, which is invalidated by dynamic reordering.]
SideEffects [None]
Definition at line 1393 of file cuddZddReord.c.
References cuddCacheFlush(), and cuddGarbageCollectZdd().
Referenced by Cudd_zddReduceHeap(), and Cudd_zddShuffleHeap().
static int zddShuffle (DdManager * table, int * permutation) [static]
Function********************************************************************
Synopsis [Reorders ZDD variables according to a given permutation.]
Description [Reorders ZDD variables according to a given permutation. The i-th permutation array contains the index of the variable that should be brought to the i-th level. zddShuffle assumes that no dead nodes are present. The reordering is achieved by a series of upward sifts. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1528 of file cuddZddReord.c.
References DdManager::keysZ, numvars, DdManager::permZ, result, DdManager::sizeZ, util_cpu_time(), zddSiftUp(), and zddTotalNumberSwapping.
Referenced by Cudd_zddShuffleHeap(), and cuddZddAlignToBdd().
static int zddSiftUp (DdManager * table, int x, int xLow) [static]
Function********************************************************************
Synopsis [Moves one ZDD variable up.]
Description [Takes a ZDD variable from position x and sifts it up to position xLow; xLow should be less than or equal to x. Returns 1 if successful; 0 otherwise]
SideEffects [None]
SeeAlso []
Definition at line 1601 of file cuddZddReord.c.
References cuddZddNextLow(), cuddZddSwapInPlace(), and size.
Referenced by zddShuffle().
static Move* zddSwapAny (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Swaps any two variables.]
Description [Swaps any two variables. Returns the set of moves.]
SideEffects [None]
SeeAlso []
Definition at line 944 of file cuddZddReord.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextHigh(), cuddZddNextLow(), cuddZddSwapInPlace(), DdManager::keysZ, DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddZddSwapping().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddReord.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 76 of file cuddZddReord.c.
DdNode* empty [static]
Definition at line 83 of file cuddZddReord.c.
int* zdd_entry
Definition at line 79 of file cuddZddReord.c.
int zddTotalNumberSwapping
Definition at line 81 of file cuddZddReord.c.