cuddCof.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_Cofactor (DdManager *dd, DdNode *f, DdNode *g)
void cuddGetBranches (DdNode *g, DdNode **g1, DdNode **g0)
int cuddCheckCube (DdManager *dd, DdNode *g)
DdNode * cuddCofactorRecur (DdManager *dd, DdNode *f, DdNode *g)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddCof.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_Cofactor (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the cofactor of f with respect to g.]
Description [Computes the cofactor of f with respect to g; g must be the BDD or the ADD of a cube. Returns a pointer to the cofactor if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain Cudd_bddRestrict]
Definition at line 94 of file cuddCof.c.
References Cudd_Not, cuddCofactorRecur(), DD_ONE, DD_ZERO, DdManager::reordered, and zero.
Referenced by cuddCofactorRecur().
int cuddCheckCube (DdManager * dd, DdNode * g)
Function********************************************************************
Synopsis [Checks whether g is the BDD of a cube.]
Description [Checks whether g is the BDD of a cube. Returns 1 in case of success; 0 otherwise. The constant 1 is a valid cube, but all other constant functions cause cuddCheckCube to return 0.]
SideEffects [None]
SeeAlso []
Definition at line 163 of file cuddCof.c.
References Cudd_IsConstant, Cudd_Not, cuddGetBranches(), DD_ONE, one, and zero.
Referenced by Cudd_CProjection().
DdNode* cuddCofactorRecur (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_Cofactor.]
Description [Performs the recursive step of Cudd_Cofactor. Returns a pointer to the cofactor if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_Cofactor]
Definition at line 200 of file cuddCof.c.
References Cudd_Cofactor(), Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_Cofactor(), and cuddSolveEqnRecur().
void cuddGetBranches (DdNode * g, DdNode ** g1, DdNode ** g0)
Function********************************************************************
Synopsis [Computes the children of g.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 132 of file cuddCof.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, and cuddT.
Referenced by cuddCheckCube().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddCof.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddCof.c]
PackageName [cudd]
Synopsis [Cofactoring functions.]
Description [External procedures included in this module:
Cudd_Cofactor()
Internal procedures included in this module:
cuddGetBranches()
cuddCheckCube()
cuddCofactorRecur()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 57 of file cuddCof.c.