cuddRef.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
void Cudd_Ref (DdNode *n)
void Cudd_RecursiveDeref (DdManager *table, DdNode *n)
void Cudd_IterDerefBdd (DdManager *table, DdNode *n)
void Cudd_RecursiveDerefZdd (DdManager *table, DdNode *n)
void Cudd_Deref (DdNode *node)
int Cudd_CheckZeroRef (DdManager *manager)
void cuddReclaim (DdManager *table, DdNode *n)
void cuddReclaimZdd (DdManager *table, DdNode *n)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddRef.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
int Cudd_CheckZeroRef (DdManager * manager)
Function********************************************************************
Synopsis [Checks the unique table for nodes with non-zero reference counts.]
Description [Checks the unique table for nodes with non-zero reference counts. It is normally called before Cudd_Quit to make sure that there are no memory leaks due to missing Cudd_RecursiveDeref's. Takes into account that reference counts may saturate and that the basic constants and the projection functions are referenced by the manager. Returns the number of nodes with non-zero reference count. (Except for the cases mentioned above.)]
SideEffects [None]
SeeAlso []
Definition at line 332 of file cuddRef.c.
References DD_MAXREF, DdNode::index, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdManager::size, size, DdManager::subtables, and DdManager::vars.
void Cudd_Deref (DdNode * node)
Function********************************************************************
Synopsis [Decreases the reference count of node.]
Description [Decreases the reference count of node. It is primarily used in recursive procedures to decrease the ref count of a result node before returning it. This accomplishes the goal of removing the protection applied by a previous Cudd_Ref.]
SideEffects [None]
SeeAlso [Cudd_RecursiveDeref Cudd_RecursiveDerefZdd Cudd_Ref]
Definition at line 304 of file cuddRef.c.
References Cudd_Regular, cuddSatDec, and DdNode::ref.
Referenced by Cudd_addTimesPlus(), cuddBddIsop(), cuddSolveEqnRecur(), cuddZddDivide(), cuddZddDivideF(), cuddZddGetCofactors3(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddWeakDiv(), and cuddZddWeakDivF().
void Cudd_IterDerefBdd (DdManager * table, DdNode * n)
Function********************************************************************
Synopsis [Decreases the reference count of BDD node n.]
Description [Decreases the reference count of node n. If n dies, recursively decreases the reference counts of its children. It is used to dispose of a BDD that is no longer needed. It is more efficient than Cudd_RecursiveDeref, but it cannot be used on ADDs. The greater efficiency comes from being able to assume that no constant node will ever die as a result of a call to this procedure.]
SideEffects [None]
SeeAlso [Cudd_RecursiveDeref]
Definition at line 185 of file cuddRef.c.
References assert, Cudd_Regular, cuddE, cuddIsConstant, cuddSatDec, cuddT, DdSubtable::dead, DdManager::dead, DdNode::index, DdManager::perm, DdNode::ref, DdManager::stack, and DdManager::subtables.
Referenced by Cudd_bddCharToVect(), Cudd_bddConstrainDecomp(), Cudd_bddMinimize(), Cudd_bddRestrict(), Cudd_bddSqueeze(), Cudd_SubsetCompress(), cuddBddAndAbstractRecur(), cuddBddAndRecur(), cuddBddBooleanDiffRecur(), cuddBddCharToVect(), cuddBddComposeRecur(), cuddBddConstrainDecomp(), cuddBddConstrainRecur(), cuddBddExistAbstractRecur(), cuddBddIntersectRecur(), cuddBddIteRecur(), cuddBddLICBuildResult(), cuddBddPermuteRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddVectorComposeRecur(), cuddBddXorExistAbstractRecur(), and cuddBddXorRecur().
void Cudd_RecursiveDeref (DdManager * table, DdNode * n)
Function********************************************************************
Synopsis [Decreases the reference count of node n.]
Description [Decreases the reference count of node n. If n dies, recursively decreases the reference counts of its children. It is used to dispose of a DD that is no longer needed.]
SideEffects [None]
SeeAlso [Cudd_Deref Cudd_Ref Cudd_RecursiveDerefZdd]
Definition at line 120 of file cuddRef.c.
References assert, DdManager::constants, Cudd_Regular, cuddE, cuddIsConstant, cuddSatDec, cuddT, DdSubtable::dead, DdManager::dead, DdNode::index, DdManager::perm, DdNode::ref, DdManager::stack, and DdManager::subtables.
Referenced by addBddDoInterval(), addBddDoIthBit(), addBddDoPattern(), addBddDoStrictThreshold(), addBddDoThreshold(), addDoIthBit(), addTriangleRecur(), addWalshInt(), BuildConjuncts(), BuildSubsetBdd(), ConjunctsFree(), Cudd_addBddInterval(), Cudd_addBddIthBit(), Cudd_addBddStrictThreshold(), Cudd_addBddThreshold(), Cudd_addComputeCube(), Cudd_addExistAbstract(), Cudd_addHamming(), Cudd_addHarwell(), Cudd_addIthBit(), Cudd_addNonSimCompose(), Cudd_addRead(), Cudd_addResidue(), Cudd_addRestrict(), Cudd_addTimesPlus(), Cudd_addXeqy(), Cudd_bddApproxConjDecomp(), Cudd_bddComputeCube(), Cudd_bddGenConjDecomp(), Cudd_bddIterConjDecomp(), Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneMinterm(), Cudd_bddRead(), Cudd_bddVarConjDecomp(), Cudd_ClassifySupport(), Cudd_CProjection(), Cudd_DumpBlif(), Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_Dxygtdxz(), Cudd_Dxygtdyz(), Cudd_IndicesToCube(), Cudd_PrioritySelect(), Cudd_Support(), Cudd_VectorSupport(), Cudd_Xeqy(), Cudd_Xgty(), Cudd_zddDumpDot(), cuddAddApplyRecur(), cuddAddCmplRecur(), cuddAddComposeRecur(), cuddAddConstrainRecur(), cuddAddExistAbstractRecur(), cuddAddIteRecur(), cuddAddNegateRecur(), cuddAddNonSimComposeRecur(), cuddAddOrAbstractRecur(), cuddAddPermuteRecur(), cuddAddRestrictRecur(), cuddAddRoundOffRecur(), cuddAddScalarInverseRecur(), cuddAddUnivAbstractRecur(), cuddAddVectorComposeRecur(), cuddBddClipAndAbsRecur(), cuddBddClippingAndRecur(), cuddBddIsop(), cuddBddLiteralSetIntersectionRecur(), cuddBddTransfer(), cuddBddTransferRecur(), cuddCofactorRecur(), cuddCProjectionRecur(), cuddDestroySubtables(), cuddHashTableQuit(), cuddSolveEqnRecur(), cuddSplitSetRecur(), cuddSubsetHeavyBranch(), cuddVerifySol(), cuddZddIsop(), ddBddToAddRecur(), ddFindEssentialRecur(), get_cube(), get_path(), mintermsFromUniverse(), RAbuildSubset(), selectMintermsFromUniverse(), stPathTableDdFree(), UAbuildSubset(), zddPortToBddStep(), and ZeroCase().
void Cudd_RecursiveDerefZdd (DdManager * table, DdNode * n)
Function********************************************************************
Synopsis [Decreases the reference count of ZDD node n.]
Description [Decreases the reference count of ZDD node n. If n dies, recursively decreases the reference counts of its children. It is used to dispose of a ZDD that is no longer needed.]
SideEffects [None]
SeeAlso [Cudd_Deref Cudd_Ref Cudd_RecursiveDeref]
Definition at line 244 of file cuddRef.c.
References assert, cuddE, cuddIsConstant, cuddSatDec, cuddT, DdSubtable::dead, DdManager::deadZ, DdNode::index, DdManager::permZ, DdNode::ref, DdManager::stack, and DdManager::subtableZ.
Referenced by Cudd_zddIthVar(), cuddZddChange(), cuddZddChangeAux(), cuddZddDiff(), cuddZddDivide(), cuddZddDivideF(), cuddZddFreeUniv(), cuddZddGetCofactors2(), cuddZddGetCofactors3(), cuddZddGetNodeIVO(), cuddZddInitUniv(), cuddZddIntersect(), cuddZddIsop(), cuddZddIte(), cuddZddProduct(), cuddZddSubset0(), cuddZddSubset1(), cuddZddUnateProduct(), cuddZddUnion(), cuddZddWeakDiv(), cuddZddWeakDivF(), zdd_subset0_aux(), zdd_subset1_aux(), and zddPortFromBddStep().
void Cudd_Ref (DdNode * n)
Function********************************************************************
Synopsis [Increases the reference count of a node, if it is not saturated.]
Description []
SideEffects [None]
SeeAlso [Cudd_RecursiveDeref Cudd_Deref]
Definition at line 95 of file cuddRef.c.
References Cudd_Regular, cuddSatInc, and DdNode::ref.
Referenced by Cudd_addTimesPlus(), cuddBddIsop(), cuddZddDivide(), cuddZddDivideF(), cuddZddGetCofactors3(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddWeakDiv(), and cuddZddWeakDivF().
void cuddReclaim (DdManager * table, DdNode * n)
Function********************************************************************
Synopsis [Brings children of a dead node back.]
Description []
SideEffects [None]
SeeAlso [cuddReclaimZdd]
Definition at line 452 of file cuddRef.c.
References assert, DdManager::constants, Cudd_Regular, cuddE, cuddIsConstant, cuddSatDec, cuddSatInc, cuddT, DdSubtable::dead, DdManager::dead, DdNode::index, DdManager::perm, DdManager::reclaimed, DdNode::ref, DdManager::stack, and DdManager::subtables.
Referenced by cuddCacheLookup(), cuddCacheLookup1(), cuddCacheLookup2(), cuddLocalCacheLookup(), cuddUniqueConst(), and cuddUniqueInter().
void cuddReclaimZdd (DdManager * table, DdNode * n)
Function********************************************************************
Synopsis [Brings children of a dead ZDD node back.]
Description []
SideEffects [None]
SeeAlso [cuddReclaim]
Definition at line 513 of file cuddRef.c.
References assert, cuddE, cuddIsConstant, cuddSatDec, cuddSatInc, cuddT, DdSubtable::dead, DdManager::deadZ, DdNode::index, DdManager::permZ, DdManager::reclaimed, DdNode::ref, DdManager::stack, and DdManager::subtableZ.
Referenced by cuddCacheLookup1Zdd(), cuddCacheLookup2Zdd(), cuddCacheLookupZdd(), and cuddUniqueInterZdd().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddRef.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddRef.c]
PackageName [cudd]
Synopsis [Functions that manipulate the reference counts.]
Description [External procedures included in this module:
Cudd_Ref()
Cudd_RecursiveDeref()
Cudd_IterDerefBdd()
Cudd_RecursiveDerefZdd()
Cudd_Deref()
Cudd_CheckZeroRef()
Internal procedures included in this module:
cuddReclaim()
cuddReclaimZdd()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 61 of file cuddRef.c.