cuddSymmetry.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define MV_OOM (Move *)1L
Functions
static int ddSymmUniqueCompare ARGS ((int *ptrX, int *ptrY))
static int ddSymmSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh))
static Move *ddSymmSiftingUp ARGS ((DdManager *table, int y, int xLow))
static Move *ddSymmSiftingDown ARGS ((DdManager *table, int x, int xHigh))
static int ddSymmGroupMove ARGS ((DdManager *table, int x, int y, Move **moves))
static int ddSymmGroupMoveBackward ARGS ((DdManager *table, int x, int y))
static int ddSymmSiftingBackward ARGS ((DdManager *table, Move *moves, int size))
static void ddSymmSummary ARGS ((DdManager *table, int lower, int upper, int *symvars, int *symgroups))
void Cudd_SymmProfile (DdManager *table, int lower, int upper)
int cuddSymmCheck (DdManager *table, int x, int y)
int cuddSymmSifting (DdManager *table, int lower, int upper)
int cuddSymmSiftingConv (DdManager *table, int lower, int upper)
static int ddSymmUniqueCompare (int *ptrX, int *ptrY)
static int ddSymmSiftingAux (DdManager *table, int x, int xLow, int xHigh)
static int ddSymmSiftingConvAux (DdManager *table, int x, int xLow, int xHigh)
static Move * ddSymmSiftingUp (DdManager *table, int y, int xLow)
static Move * ddSymmSiftingDown (DdManager *table, int x, int xHigh)
static int ddSymmGroupMove (DdManager *table, int x, int y, Move **moves)
static int ddSymmGroupMoveBackward (DdManager *table, int x, int y)
static int ddSymmSiftingBackward (DdManager *table, Move *moves, int size)
static void ddSymmSummary (DdManager *table, int lower, int upper, int *symvars, int *symgroups)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddSymmetry.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int * entry
int ddTotalNumberSwapping
Define Documentation
#define MV_OOM (Move *)1L
CFile***********************************************************************
FileName [cuddSymmetry.c]
PackageName [cudd]
Synopsis [Functions for symmetry-based variable reordering.]
Description [External procedures included in this file:
Cudd_SymmProfile()
Internal procedures included in this module:
cuddSymmCheck()
cuddSymmSifting()
cuddSymmSiftingConv()
Static procedures included in this module:
ddSymmUniqueCompare()
ddSymmSiftingAux()
ddSymmSiftingConvAux()
ddSymmSiftingUp()
ddSymmSiftingDown()
ddSymmGroupMove()
ddSymmGroupMoveBackward()
ddSymmSiftingBackward()
ddSymmSummary()
]
Author [Shipra Panda, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 50 of file cuddSymmetry.c.
Referenced by ddSymmSiftingAux(), ddSymmSiftingConvAux(), ddSymmSiftingDown(), and ddSymmSiftingUp().
Function Documentation
static void ddSymmSummary ARGS ((DdManager *table, int lower, int upper, int *symvars, int *symgroups)) [static]
static int ddSymmSiftingBackward ARGS ((DdManager *table, Move *moves, int size)) [static]
static int ddSymmGroupMoveBackward ARGS ((DdManager *table, int x, int y)) [static]
static int ddSymmGroupMove ARGS ((DdManager *table, int x, int y, Move **moves)) [static]
static Move* ddSymmSiftingDown ARGS ((DdManager *table, int x, int xHigh)) [static]
static Move* ddSymmSiftingUp ARGS ((DdManager *table, int y, int xLow)) [static]
static int ddSymmSiftingConvAux ARGS ((DdManager *table, int x, int xLow, int xHigh)) [static]
static int ddSymmUniqueCompare ARGS ((int *ptrX, int *ptrY)) [static]
AutomaticStart
void Cudd_SymmProfile (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Prints statistics on symmetric variables.]
Description []
SideEffects [None]
Definition at line 113 of file cuddSymmetry.c.
References assert, DdManager::invperm, DdSubtable::next, and DdManager::subtables.
int cuddSymmCheck (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Checks for symmetry of x and y.]
Description [Checks for symmetry of x and y. Ignores projection functions, unless they are isolated. Returns 1 in case of symmetry; 0 otherwise.]
SideEffects [None]
Definition at line 163 of file cuddSymmetry.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddT, DD_ONE, DdNode::index, DdManager::invperm, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::slots, DdManager::subtables, and DdManager::vars.
Referenced by ddSymmSiftingAux(), ddSymmSiftingDown(), and ddSymmSiftingUp().
int cuddSymmSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Symmetric sifting algorithm.]
Description [Symmetric sifting algorithm. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique subtable.
Sift the variable up and down, remembering each time the total size of the DD heap and grouping variables that are symmetric.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 plus the number of symmetric variables if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddSymmSiftingConv]
Definition at line 299 of file cuddSymmetry.c.
References ALLOC, CUDD_MEMORY_OUT, ddMin, ddSymmSiftingAux(), ddSymmSummary(), ddSymmUniqueCompare(), ddTotalNumberSwapping, entry, DdManager::errorCode, FREE, DdManager::isolated, DdManager::keys, DdSubtable::keys, DdSubtable::next, DdManager::perm, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::size, size, and DdManager::subtables.
Referenced by ddReorderChildren().
int cuddSymmSiftingConv (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Symmetric sifting to convergence algorithm.]
Description [Symmetric sifting to convergence algorithm. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique subtable.
Sift the variable up and down, remembering each time the total size of the DD heap and grouping variables that are symmetric.
Select the best permutation.
Repeat 3 and 4 for all variables.
Repeat 1-4 until no further improvement.
Returns 1 plus the number of symmetric variables if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddSymmSifting]
Definition at line 414 of file cuddSymmetry.c.
References ALLOC, CUDD_MEMORY_OUT, ddMin, ddSymmSiftingAux(), ddSymmSiftingConvAux(), ddSymmSummary(), ddSymmUniqueCompare(), ddTotalNumberSwapping, entry, DdManager::errorCode, FREE, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdSubtable::next, DdManager::perm, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::size, size, and DdManager::subtables.
Referenced by cuddExact(), and ddReorderChildren().
static int ddSymmGroupMove (DdManager * table, int x, int y, Move ** moves) [static]
Function********************************************************************
Synopsis [Swaps two groups.]
Description [Swaps two groups. x is assumed to be the bottom variable of the first group. y is assumed to be the top variable of the second group. Updates the list of moves. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
Definition at line 1437 of file cuddSymmetry.c.
References assert, cuddDynamicAllocNode(), cuddSwapInPlace(), Move::next, DdSubtable::next, Move::size, size, DdManager::subtables, Move::x, and Move::y.
Referenced by ddSymmSiftingDown(), and ddSymmSiftingUp().
static int ddSymmGroupMoveBackward (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Undoes the swap of two groups.]
Description [Undoes the swap of two groups. x is assumed to be the bottom variable of the first group. y is assumed to be the top variable of the second group. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
Definition at line 1518 of file cuddSymmetry.c.
References assert, cuddNextLow(), cuddSwapInPlace(), DdSubtable::next, size, and DdManager::subtables.
static int ddSymmSiftingAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. Finds the best position and does the required changes. Assumes that x is not part of a symmetry group. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 606 of file cuddSymmetry.c.
References assert, cuddDeallocNode, cuddNextHigh(), cuddSymmCheck(), ddSymmSiftingBackward(), ddSymmSiftingDown(), ddSymmSiftingUp(), DdManager::isolated, DdManager::keys, MV_OOM, Move::next, DdSubtable::next, result, DdManager::subtables, Move::x, and Move::y.
Referenced by cuddSymmSifting(), and cuddSymmSiftingConv().
static int ddSymmSiftingBackward (DdManager * table, Move * moves, int size) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the DD heap to the position giving the minimum size.]
Description [Given a set of moves, returns the DD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1589 of file cuddSymmetry.c.
References Move::next, and Move::size.
Referenced by ddSymmSiftingAux(), and ddSymmSiftingConvAux().
static int ddSymmSiftingConvAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. Finds the best position and does the required changes. Assumes that x is either an isolated variable, or it is the bottom of a symmetry group. All symmetries may not have been found, because of exceeded growth limit. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 904 of file cuddSymmetry.c.
References assert, cuddDeallocNode, cuddNextHigh(), ddSymmSiftingBackward(), ddSymmSiftingDown(), ddSymmSiftingUp(), DdManager::isolated, DdManager::keys, MV_OOM, Move::next, DdSubtable::next, result, DdManager::subtables, Move::x, and Move::y.
Referenced by cuddSymmSiftingConv().
static Move* ddSymmSiftingDown (DdManager * table, int x, int xHigh) [static]
Function********************************************************************
Synopsis [Moves x down until either it reaches the bound (xHigh) or the size of the DD heap increases too much.]
Description [Moves x down until either it reaches the bound (xHigh) or the size of the DD heap increases too much. Assumes that x is the bottom of a symmetry group. Checks x for symmetry to the adjacent variables. If symmetry is found, the symmetry group of x is merged with the symmetry group of the other variable. Returns the set of moves in case of success; MV_OOM if memory is full.]
SideEffects [None]
Definition at line 1299 of file cuddSymmetry.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddSwapInPlace(), cuddSymmCheck(), cuddTestInteract(), ddSymmGroupMove(), DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, MV_OOM, Move::next, DdSubtable::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddSymmSiftingAux(), and ddSymmSiftingConvAux().
static Move* ddSymmSiftingUp (DdManager * table, int y, int xLow) [static]
Function********************************************************************
Synopsis [Moves x up until either it reaches the bound (xLow) or the size of the DD heap increases too much.]
Description [Moves x up until either it reaches the bound (xLow) or the size of the DD heap increases too much. Assumes that x is the top of a symmetry group. Checks x for symmetry to the adjacent variables. If symmetry is found, the symmetry group of x is merged with the symmetry group of the other variable. Returns the set of moves in case of success; MV_OOM if memory is full.]
SideEffects [None]
Definition at line 1157 of file cuddSymmetry.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextLow(), cuddSwapInPlace(), cuddSymmCheck(), cuddTestInteract(), ddSymmGroupMove(), DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, MV_OOM, Move::next, DdSubtable::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddSymmSiftingAux(), and ddSymmSiftingConvAux().
static void ddSymmSummary (DdManager * table, int lower, int upper, int * symvars, int * symgroups) [static]
Function********************************************************************
Synopsis [Counts numbers of symmetric variables and symmetry groups.]
Description []
SideEffects [None]
Definition at line 1633 of file cuddSymmetry.c.
References assert, DdSubtable::next, and DdManager::subtables.
Referenced by cuddSymmSifting(), and cuddSymmSiftingConv().
static int ddSymmUniqueCompare (int * ptrX, int * ptrY) [static]
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
Definition at line 578 of file cuddSymmetry.c.
References entry.
Referenced by cuddSymmSifting(), and cuddSymmSiftingConv().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddSymmetry.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 65 of file cuddSymmetry.c.
int ddTotalNumberSwapping
Definition at line 78 of file cuddReorder.c.
int* entry [static]
Definition at line 68 of file cuddSymmetry.c.