cuddClip.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *cuddBddClippingAndRecur ARGS ((DdManager *manager, DdNode *f, DdNode *g, int distance, int direction))
static DdNode *cuddBddClipAndAbsRecur ARGS ((DdManager *manager, DdNode *f, DdNode *g, DdNode *cube, int distance, int direction))
DdNode * Cudd_bddClippingAnd (DdManager *dd, DdNode *f, DdNode *g, int maxDepth, int direction)
DdNode * Cudd_bddClippingAndAbstract (DdManager *dd, DdNode *f, DdNode *g, DdNode *cube, int maxDepth, int direction)
DdNode * cuddBddClippingAnd (DdManager *dd, DdNode *f, DdNode *g, int maxDepth, int direction)
DdNode * cuddBddClippingAndAbstract (DdManager *dd, DdNode *f, DdNode *g, DdNode *cube, int maxDepth, int direction)
static DdNode * cuddBddClippingAndRecur (DdManager *manager, DdNode *f, DdNode *g, int distance, int direction)
static DdNode * cuddBddClipAndAbsRecur (DdManager *manager, DdNode *f, DdNode *g, DdNode *cube, int distance, int direction)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddClip.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* cuddBddClipAndAbsRecur ARGS ((DdManager *manager, DdNode *f, DdNode *g, DdNode *cube, int distance, int direction)) [static]
static DdNode* cuddBddClippingAndRecur ARGS ((DdManager *manager, DdNode *f, DdNode *g, int distance, int direction)) [static]
AutomaticStart
DdNode* Cudd_bddClippingAnd (DdManager * dd, DdNode * f, DdNode * g, int maxDepth, int direction)
Function********************************************************************
Synopsis [Approximates the conjunction of two BDDs f and g.]
Description [Approximates the conjunction of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddAnd]
Definition at line 100 of file cuddClip.c.
References cuddBddClippingAnd(), and DdManager::reordered.
Referenced by cuddBddClippingAndRecur().
DdNode* Cudd_bddClippingAndAbstract (DdManager * dd, DdNode * f, DdNode * g, DdNode * cube, int maxDepth, int direction)
Function********************************************************************
Synopsis [Approximates the conjunction of two BDDs f and g and simultaneously abstracts the variables in cube.]
Description [Approximates the conjunction of two BDDs f and g and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddAndAbstract Cudd_bddClippingAnd]
Definition at line 134 of file cuddClip.c.
References cuddBddClippingAndAbstract(), and DdManager::reordered.
Referenced by cuddBddClipAndAbsRecur().
static DdNode* cuddBddClipAndAbsRecur (DdManager * manager, DdNode * f, DdNode * g, DdNode * cube, int distance, int direction) [static]
Function********************************************************************
Synopsis [Approximates the AND of two BDDs and simultaneously abstracts the variables in cube.]
Description [Approximates the AND of two BDDs and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddClippingAndAbstract]
Definition at line 375 of file cuddClip.c.
References Cudd_bddClippingAndAbstract(), Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddClippingAndAbstract(), cuddBddClippingAndRecur(), cuddBddExistAbstractRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, ddMin, DdNode::index, one, DdManager::perm, DdNode::ref, and zero.
Referenced by cuddBddClippingAndAbstract().
DdNode* cuddBddClippingAnd (DdManager * dd, DdNode * f, DdNode * g, int maxDepth, int direction)
Function********************************************************************
Synopsis [Approximates the conjunction of two BDDs f and g.]
Description [Approximates the conjunction of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddClippingAnd]
Definition at line 172 of file cuddClip.c.
References cuddBddClippingAndRecur().
Referenced by Cudd_bddClippingAnd(), and cuddBddClippingAndRecur().
DdNode* cuddBddClippingAndAbstract (DdManager * dd, DdNode * f, DdNode * g, DdNode * cube, int maxDepth, int direction)
Function********************************************************************
Synopsis [Approximates the conjunction of two BDDs f and g and simultaneously abstracts the variables in cube.]
Description [Approximates the conjunction of two BDDs f and g and simultaneously abstracts the variables in cube. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddClippingAndAbstract]
Definition at line 204 of file cuddClip.c.
References cuddBddClipAndAbsRecur().
Referenced by Cudd_bddClippingAndAbstract(), and cuddBddClipAndAbsRecur().
static DdNode* cuddBddClippingAndRecur (DdManager * manager, DdNode * f, DdNode * g, int distance, int direction) [static]
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_bddClippingAnd.]
Description [Implements the recursive step of Cudd_bddClippingAnd by taking the conjunction of two BDDs. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddBddClippingAnd]
Definition at line 240 of file cuddClip.c.
References Cudd_bddClippingAnd(), Cudd_bddLeq(), Cudd_IsComplement, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddClippingAnd(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, one, DdManager::perm, DdNode::ref, and zero.
Referenced by cuddBddClipAndAbsRecur(), and cuddBddClippingAnd().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddClip.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddClip.c]
PackageName [cudd]
Synopsis [Clipping functions.]
Description [External procedures included in this module:
Cudd_bddClippingAnd()
Cudd_bddClippingAndAbstract()
Internal procedures included in this module:
cuddBddClippingAnd()
cuddBddClippingAndAbstract()
Static procedures included in this module:
cuddBddClippingAndRecur()
cuddBddClipAndAbsRecur()
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 61 of file cuddClip.c.