cuddLiteral.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_bddLiteralSetIntersection (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddBddLiteralSetIntersectionRecur (DdManager *dd, DdNode *f, DdNode *g)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddLiteral.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_bddLiteralSetIntersection (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the intesection of two sets of literals represented as BDDs.]
Description [Computes the intesection of two sets of literals represented as BDDs. Each set is represented as a cube of the literals in the set. The empty set is represented by the constant 1. No variable can be simultaneously present in both phases in a set. Returns a pointer to the BDD representing the intersected sets, if successful; NULL otherwise.]
SideEffects [None]
Definition at line 89 of file cuddLiteral.c.
References cuddBddLiteralSetIntersectionRecur(), and DdManager::reordered.
Referenced by Cudd_addRestrict(), and cuddBddLiteralSetIntersectionRecur().
DdNode* cuddBddLiteralSetIntersectionRecur (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddLiteralSetIntersection.]
Description [Performs the recursive step of Cudd_bddLiteralSetIntersection. Scans the cubes for common variables, and checks whether they agree in phase. Returns a pointer to the resulting cube if successful; NULL otherwise.]
SideEffects [None]
Definition at line 124 of file cuddLiteral.c.
References Cudd_bddLiteralSetIntersection(), Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, DD_ONE, DdNode::index, one, DdManager::vars, and zero.
Referenced by Cudd_bddLiteralSetIntersection(), and ddFindEssentialRecur().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddLiteral.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddLiteral.c]
PackageName [cudd]
Synopsis [Functions for manipulation of literal sets represented by BDDs.]
Description [External procedures included in this file:
Cudd_bddLiteralSetIntersection()
Internal procedures included in this file:
cuddBddLiteralSetIntersectionRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 51 of file cuddLiteral.c.