cuddSubsetHB.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct NodeData
Defines
#define DBL_MAX_EXP 1024
#define DEFAULT_PAGE_SIZE 2048
#define DEFAULT_NODE_DATA_PAGE_SIZE 1024
#define INITIAL_PAGES 128
Typedefs
typedef NodeData NodeData_t
Functions
static void ResizeNodeDataPages ARGS (())
static double SubsetCountMintermAux ARGS ((DdNode *node, double max, st_table *table))
static st_table *SubsetCountMinterm ARGS ((DdNode *node, int nvars))
static int SubsetCountNodesAux ARGS ((DdNode *node, st_table *table, double max))
static int SubsetCountNodes ARGS ((DdNode *node, st_table *table, int nvars))
static void StoreNodes ARGS ((st_table *storeTable, DdManager *dd, DdNode *node))
static DdNode *BuildSubsetBdd ARGS ((DdManager *dd, DdNode *node, int *size, st_table *visitedTable, int threshold, st_table *storeTable, st_table *approxTable))
DdNode * Cudd_SubsetHeavyBranch (DdManager *dd, DdNode *f, int numVars, int threshold)
DdNode * Cudd_SupersetHeavyBranch (DdManager *dd, DdNode *f, int numVars, int threshold)
DdNode * cuddSubsetHeavyBranch (DdManager *dd, DdNode *f, int numVars, int threshold)
static void ResizeNodeDataPages ()
static void ResizeCountMintermPages ()
static void ResizeCountNodePages ()
static double SubsetCountMintermAux (DdNode *node, double max, st_table *table)
static st_table * SubsetCountMinterm (DdNode *node, int nvars)
static int SubsetCountNodesAux (DdNode *node, st_table *table, double max)
static int SubsetCountNodes (DdNode *node, st_table *table, int nvars)
static void StoreNodes (st_table *storeTable, DdManager *dd, DdNode *node)
static DdNode * BuildSubsetBdd (DdManager *dd, DdNode *node, int *size, st_table *visitedTable, int threshold, st_table *storeTable, st_table *approxTable)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddSubsetHB.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int memOut
static DdNode * zero
static DdNode * one
static double ** mintermPages
static int ** nodePages
static int ** lightNodePages
static double * currentMintermPage
static double max
static int * currentNodePage
static int * currentLightNodePage
static int pageIndex
static int page
static int pageSize = DEFAULT_PAGE_SIZE
static int maxPages
static NodeData_t * currentNodeDataPage
static int nodeDataPage
static int nodeDataPageIndex
static NodeData_t ** nodeDataPages
static int nodeDataPageSize = DEFAULT_NODE_DATA_PAGE_SIZE
static int maxNodeDataPages
Define Documentation
#define DBL_MAX_EXP 1024
CFile***********************************************************************
FileName [cuddSubsetHB.c]
PackageName [cudd]
Synopsis [Procedure to subset the given BDD by choosing the heavier branches]
Description [External procedures provided by this module:
Cudd_SubsetHeavyBranch()
Cudd_SupersetHeavyBranch()
Internal procedures included in this module:
cuddSubsetHeavyBranch()
Static procedures included in this module:
ResizeCountMintermPages();
ResizeNodeDataPages()
ResizeCountNodePages()
SubsetCountMintermAux()
SubsetCountMinterm()
SubsetCountNodesAux()
SubsetCountNodes()
BuildSubsetBdd()
]
SeeAlso [cuddSubsetSP.c]
Author [Kavita Ravi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 50 of file cuddSubsetHB.c.
#define DEFAULT_NODE_DATA_PAGE_SIZE 1024
Definition at line 61 of file cuddSubsetHB.c.
#define DEFAULT_PAGE_SIZE 2048
Definition at line 60 of file cuddSubsetHB.c.
#define INITIAL_PAGES 128
Definition at line 62 of file cuddSubsetHB.c.
Referenced by CreatePathTable(), ResizeCountMintermPages(), ResizeCountNodePages(), ResizeNodeDataPages(), ResizeNodeDistPages(), ResizeQueuePages(), SubsetCountMinterm(), and SubsetCountNodes().
Typedef Documentation
typedef struct NodeData NodeData_t
Definition at line 86 of file cuddSubsetHB.c.
Function Documentation
static DdNode* BuildSubsetBdd ARGS ((DdManager *dd, DdNode *node, int *size, st_table *visitedTable, int threshold, st_table *storeTable, st_table *approxTable)) [static]
static void StoreNodes ARGS ((st_table *storeTable, DdManager *dd, DdNode *node)) [static]
static int SubsetCountNodes ARGS ((DdNode *node, st_table *table, int nvars)) [static]
static int SubsetCountNodesAux ARGS ((DdNode *node, st_table *table, double max)) [static]
static st_table* SubsetCountMinterm ARGS ((DdNode *node, int nvars)) [static]
static double SubsetCountMintermAux ARGS ((DdNode *node, double max, st_table *table)) [static]
static void ResizeNodeDataPages ARGS (()) [static]
AutomaticStart
static DdNode* BuildSubsetBdd (DdManager * dd, DdNode * node, int * size, st_table * visitedTable, int threshold, st_table * storeTable, st_table * approxTable) [static]
Function********************************************************************
Synopsis [Builds the subset BDD using the heavy branch method.]
Description [The procedure carries out the building of the subset BDD starting at the root. Using the three different counts labelling each node, the procedure chooses the heavier branch starting from the root and keeps track of the number of nodes it discards at each step, thus keeping count of the size of the subset BDD dynamically. Once the threshold is satisfied, the procedure then calls ITE to build the BDD.]
SideEffects [None]
SeeAlso []
Definition at line 1138 of file cuddSubsetHB.c.
References Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_NodeReadIndex(), Cudd_NotCond, Cudd_ReadVars(), Cudd_RecursiveDeref(), Cudd_Regular, Cudd_T, cuddBddIteRecur(), cuddDeref, cuddRef, max, NIL, st_insert(), st_lookup(), StoreNodes(), and zero.
Referenced by BuildSubsetBdd(), cuddSubsetHeavyBranch(), and cuddSubsetShortPaths().
DdNode* Cudd_SubsetHeavyBranch (DdManager * dd, DdNode * f, int numVars, int threshold)
Function********************************************************************
Synopsis [Extracts a dense subset from a BDD with the heavy branch heuristic.]
Description [Extracts a dense subset from a BDD. This procedure builds a subset by throwing away one of the children of each node, starting from the root, until the result is small enough. The child that is eliminated from the result is the one that contributes the fewer minterms. Returns a pointer to the BDD of the subset if successful. NULL if the procedure runs out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation and node count calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SubsetShortPaths Cudd_SupersetHeavyBranch Cudd_ReadSize]
Definition at line 182 of file cuddSubsetHB.c.
References cuddSubsetHeavyBranch(), memOut, and DdManager::reordered.
DdNode* Cudd_SupersetHeavyBranch (DdManager * dd, DdNode * f, int numVars, int threshold)
Function********************************************************************
Synopsis [Extracts a dense superset from a BDD with the heavy branch heuristic.]
Description [Extracts a dense superset from a BDD. The procedure is identical to the subset procedure except for the fact that it receives the complement of the given function. Extracting the subset of the complement function is equivalent to extracting the superset of the function. This procedure builds a superset by throwing away one of the children of each node starting from the root of the complement function, until the result is small enough. The child that is eliminated from the result is the one that contributes the fewer minterms. Returns a pointer to the BDD of the superset if successful. NULL if intermediate result causes the procedure to run out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation and node count calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SubsetHeavyBranch Cudd_SupersetShortPaths Cudd_ReadSize]
Definition at line 232 of file cuddSubsetHB.c.
References Cudd_Not, Cudd_NotCond, cuddSubsetHeavyBranch(), memOut, and DdManager::reordered.
DdNode* cuddSubsetHeavyBranch (DdManager * dd, DdNode * f, int numVars, int threshold)
Function********************************************************************
Synopsis [The main procedure that returns a subset by choosing the heavier branch in the BDD.]
Description [Here a subset BDD is built by throwing away one of the children. Starting at root, annotate each node with the number of minterms (in terms of the total number of variables specified - numVars), number of nodes taken by the DAG rooted at this node and number of additional nodes taken by the child that has the lesser minterms. The child with the lower number of minterms is thrown away and a dyanmic count of the nodes of the subset is kept. Once the threshold is reached the subset is returned to the calling procedure.]
SideEffects [None]
SeeAlso [Cudd_SubsetHeavyBranch]
Definition at line 277 of file cuddSubsetHB.c.
References ALLOC, BuildSubsetBdd(), Cudd_bddLeq(), Cudd_CheckKeys(), Cudd_DebugCheck(), Cudd_IsConstant, CUDD_MEMORY_OUT, Cudd_Not, Cudd_ReadOne(), Cudd_RecursiveDeref(), cuddDeref, cuddRef, DBL_MAX_EXP, DdManager::errorCode, exit(), FREE, lightNodePages, max, memOut, mintermPages, NIL, nodeDataPage, nodeDataPages, nodePages, one, page, size, st_free_gen(), st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_insert(), st_lookup(), ST_OUT_OF_MEM, st_ptrcmp(), st_ptrhash(), SubsetCountMinterm(), SubsetCountNodes(), and zero.
Referenced by Cudd_SubsetHeavyBranch(), and Cudd_SupersetHeavyBranch().
static void ResizeCountMintermPages () [static]
Function********************************************************************
Synopsis [Resize the number of pages allocated to store the minterm counts. ]
Description [Resize the number of pages allocated to store the minterm counts. The procedure moves the counter to the next page when the end of the page is reached and allocates new pages when necessary.]
SideEffects [Changes the size of minterm pages, page, page index, maximum number of pages freeing stuff in case of memory out. ]
SeeAlso []
Definition at line 502 of file cuddSubsetHB.c.
References ALLOC, currentMintermPage, FREE, INITIAL_PAGES, maxPages, memOut, mintermPages, page, pageIndex, and pageSize.
Referenced by SubsetCountMintermAux().
static void ResizeCountNodePages () [static]
Function********************************************************************
Synopsis [Resize the number of pages allocated to store the node counts.]
Description [Resize the number of pages allocated to store the node counts. The procedure moves the counter to the next page when the end of the page is reached and allocates new pages when necessary.]
SideEffects [Changes the size of pages, page, page index, maximum number of pages freeing stuff in case of memory out.]
SeeAlso []
Definition at line 560 of file cuddSubsetHB.c.
References ALLOC, currentLightNodePage, currentNodePage, FREE, INITIAL_PAGES, lightNodePages, maxPages, memOut, nodePages, page, pageIndex, and pageSize.
Referenced by SubsetCountNodesAux().
static void ResizeNodeDataPages () [static]
Function********************************************************************
Synopsis [Resize the number of pages allocated to store the node data.]
Description [Resize the number of pages allocated to store the node data The procedure moves the counter to the next page when the end of the page is reached and allocates new pages when necessary.]
SideEffects [Changes the size of pages, page, page index, maximum number of pages freeing stuff in case of memory out. ]
SeeAlso []
Definition at line 442 of file cuddSubsetHB.c.
References ALLOC, currentNodeDataPage, FREE, INITIAL_PAGES, maxNodeDataPages, memOut, nodeDataPage, nodeDataPageIndex, nodeDataPages, and nodeDataPageSize.
Referenced by SubsetCountMintermAux().
static void StoreNodes (st_table * storeTable, DdManager * dd, DdNode * node) [static]
Function********************************************************************
Synopsis [Procedure to recursively store nodes that are retained in the subset.]
Description [rocedure to recursively store nodes that are retained in the subset.]
SideEffects [None]
SeeAlso [StoreNodes]
Definition at line 1091 of file cuddSubsetHB.c.
References Cudd_E, Cudd_IsConstant, Cudd_Regular, Cudd_T, cuddRef, NIL, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by BuildSubsetBdd().
static st_table* SubsetCountMinterm (DdNode * node, int nvars) [static]
Function********************************************************************
Synopsis [Counts minterms of each node in the DAG]
Description [Counts minterms of each node in the DAG. Similar to the Cudd_CountMinterm procedure except this returns the minterm count for all the nodes in the bdd in an st_table.]
SideEffects [none]
SeeAlso [SubsetCountMintermAux]
Definition at line 762 of file cuddSubsetHB.c.
References ALLOC, currentMintermPage, currentNodeDataPage, FREE, INITIAL_PAGES, max, maxNodeDataPages, maxPages, memOut, mintermPages, nodeDataPage, nodeDataPageIndex, nodeDataPages, nodeDataPageSize, page, pageIndex, pageSize, st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and SubsetCountMintermAux().
Referenced by cuddSubsetHeavyBranch().
static double SubsetCountMintermAux (DdNode * node, double max, st_table * table) [static]
Function********************************************************************
Synopsis [Recursively counts minterms of each node in the DAG.]
Description [Recursively counts minterms of each node in the DAG. Similar to the cuddCountMintermAux which recursively counts the number of minterms for the dag rooted at each node in terms of the total number of variables (max). This procedure creates the node data structure and stores the minterm count as part of the node data structure. ]
SideEffects [Creates structures of type node quality and fills the st_table]
SeeAlso [SubsetCountMinterm]
Definition at line 651 of file cuddSubsetHB.c.
References Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_NotCond, Cudd_Regular, Cudd_T, currentMintermPage, currentNodeDataPage, FREE, memOut, mintermPages, NodeData::mintermPointer, nodeDataPage, nodeDataPageIndex, nodeDataPages, nodeDataPageSize, NodeData::nodesPointer, page, pageIndex, pageSize, ResizeCountMintermPages(), ResizeNodeDataPages(), st_free_table(), st_insert(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by SubsetCountMinterm().
static int SubsetCountNodes (DdNode * node, st_table * table, int nvars) [static]
Function********************************************************************
Synopsis [Counts the nodes under the current node and its lighter child]
Description [Counts the nodes under the current node and its lighter child. Calls a recursive procedure to count the number of nodes of a DAG rooted at a particular node and the number of nodes taken by its lighter child.]
SideEffects [None]
SeeAlso [SubsetCountNodesAux]
Definition at line 1013 of file cuddSubsetHB.c.
References ALLOC, currentLightNodePage, currentNodePage, FREE, INITIAL_PAGES, lightNodePages, max, maxPages, memOut, mintermPages, nodeDataPage, nodeDataPages, nodePages, page, pageIndex, pageSize, and SubsetCountNodesAux().
Referenced by cuddSubsetHeavyBranch().
static int SubsetCountNodesAux (DdNode * node, st_table * table, double max) [static]
Function********************************************************************
Synopsis [Recursively counts the number of nodes under the dag. Also counts the number of nodes under the lighter child of this node.]
Description [Recursively counts the number of nodes under the dag. Also counts the number of nodes under the lighter child of this node. . Note that the same dag may be the lighter child of two different nodes and have different counts. As with the minterm counts, the node counts are stored in pages to be space efficient and the address for these node counts are stored in an st_table associated to each node. ]
SideEffects [Updates the node data table with node counts]
SeeAlso [SubsetCountNodes]
Definition at line 845 of file cuddSubsetHB.c.
References Cudd_E, Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_Regular, Cudd_T, currentLightNodePage, currentNodePage, FREE, memOut, mintermPages, nodeDataPage, nodeDataPages, NodeData::nodesPointer, page, pageIndex, pageSize, ResizeCountNodePages(), st_free_table(), st_lookup(), and zero.
Referenced by SubsetCountNodes().
Variable Documentation
int* currentLightNodePage [static]
Definition at line 112 of file cuddSubsetHB.c.
Referenced by ResizeCountNodePages(), SubsetCountNodes(), and SubsetCountNodesAux().
double* currentMintermPage [static]
Definition at line 105 of file cuddSubsetHB.c.
Referenced by ResizeCountMintermPages(), SubsetCountMinterm(), and SubsetCountMintermAux().
NodeData_t* currentNodeDataPage [static]
Definition at line 119 of file cuddSubsetHB.c.
Referenced by ResizeNodeDataPages(), SubsetCountMinterm(), and SubsetCountMintermAux().
int* currentNodePage [static]
Definition at line 110 of file cuddSubsetHB.c.
Referenced by ResizeCountNodePages(), SubsetCountNodes(), and SubsetCountNodesAux().
char rcsid [] DD_UNUSED = `$Id: cuddSubsetHB.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 93 of file cuddSubsetHB.c.
int** lightNodePages [static]
Definition at line 104 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeCountNodePages(), and SubsetCountNodes().
double max [static]
Definition at line 107 of file cuddSubsetHB.c.
Referenced by BuildSubsetBdd(), Cudd_ApaCountMinterm(), Cudd_CountMinterm(), Cudd_SplitSet(), cuddCacheProfile(), cuddConjunctsAux(), cuddSubsetHeavyBranch(), cuddSwapping(), cuddZddSwapping(), mintermsFromUniverse(), SubsetCountMinterm(), and SubsetCountNodes().
int maxNodeDataPages [static]
Definition at line 126 of file cuddSubsetHB.c.
Referenced by ResizeNodeDataPages(), and SubsetCountMinterm().
int maxPages [static]
Definition at line 117 of file cuddSubsetHB.c.
Referenced by ResizeCountMintermPages(), ResizeCountNodePages(), SubsetCountMinterm(), and SubsetCountNodes().
int memOut [static]
Definition at line 96 of file cuddSubsetHB.c.
Referenced by BuildSubsetBdd(), CreatePathTable(), CreateTopDist(), Cudd_SubsetHeavyBranch(), Cudd_SubsetShortPaths(), Cudd_SupersetHeavyBranch(), Cudd_SupersetShortPaths(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), ResizeCountMintermPages(), ResizeCountNodePages(), ResizeNodeDataPages(), ResizeNodeDistPages(), ResizeQueuePages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
double** mintermPages [static]
Definition at line 102 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeCountMintermPages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
int nodeDataPage [static]
Definition at line 121 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeNodeDataPages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
int nodeDataPageIndex [static]
Definition at line 122 of file cuddSubsetHB.c.
Referenced by ResizeNodeDataPages(), SubsetCountMinterm(), and SubsetCountMintermAux().
NodeData_t** nodeDataPages [static]
Definition at line 123 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeNodeDataPages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
int nodeDataPageSize = DEFAULT_NODE_DATA_PAGE_SIZE [static]
Definition at line 124 of file cuddSubsetHB.c.
Referenced by ResizeNodeDataPages(), SubsetCountMinterm(), and SubsetCountMintermAux().
int** nodePages [static]
Definition at line 103 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeCountNodePages(), and SubsetCountNodes().
DdNode * one [static]
Definition at line 101 of file cuddSubsetHB.c.
int page [static]
Definition at line 115 of file cuddSubsetHB.c.
Referenced by cuddSubsetHeavyBranch(), ResizeCountMintermPages(), ResizeCountNodePages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
int pageIndex [static]
Definition at line 114 of file cuddSubsetHB.c.
Referenced by ResizeCountMintermPages(), ResizeCountNodePages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
int pageSize = DEFAULT_PAGE_SIZE [static]
Definition at line 116 of file cuddSubsetHB.c.
Referenced by ResizeCountMintermPages(), ResizeCountNodePages(), SubsetCountMinterm(), SubsetCountMintermAux(), SubsetCountNodes(), and SubsetCountNodesAux().
DdNode* zero [static]
Definition at line 101 of file cuddSubsetHB.c.