cuddAddApply.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_addApply (DdManager *dd, DdNode *(*op)(DdManager *, DdNode **, DdNode **), DdNode *f, DdNode *g)
DdNode * Cudd_addPlus (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addTimes (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addThreshold (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addSetNZ (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addDivide (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addMinus (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addMinimum (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addMaximum (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addOneZeroMaximum (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addDiff (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addAgreement (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addOr (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addNand (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addNor (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addXor (DdManager *dd, DdNode **f, DdNode **g)
DdNode * Cudd_addXnor (DdManager *dd, DdNode **f, DdNode **g)
DdNode * cuddAddApplyRecur (DdManager *dd, DdNode *(*op)(DdManager *, DdNode **, DdNode **), DdNode *f, DdNode *g)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddApply.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_addAgreement (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [f if f==g; background if f!=g.]
Description [Returns NULL if not a terminal case; f op g otherwise, where f op g is f if f==g; background if f!=g.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 510 of file cuddAddApply.c.
References DdManager::background, and cuddIsConstant.
DdNode* Cudd_addApply (DdManager * dd, DdNode *(*)(DdManager *, DdNode **, DdNode **) op, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Applies op to the corresponding discriminants of f and g.]
Description [Applies op to the corresponding discriminants of f and g. Returns a pointer to the result if succssful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addPlus Cudd_addTimes Cudd_addThreshold Cudd_addSetNZ Cudd_addDivide Cudd_addMinus Cudd_addMinimum Cudd_addMaximum Cudd_addOneZeroMaximum Cudd_addDiff Cudd_addAgreement Cudd_addOr Cudd_addNand Cudd_addNor Cudd_addXor Cudd_addXnor]
Definition at line 107 of file cuddAddApply.c.
References cuddAddApplyRecur(), and DdManager::reordered.
Referenced by Cudd_addHamming(), Cudd_addHarwell(), Cudd_addNonSimCompose(), Cudd_addRead(), and Cudd_addTimesPlus().
DdNode* Cudd_addDiff (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Returns plusinfinity if f=g; returns min(f,g) if f!=g.]
Description [Returns NULL if not a terminal case; f op g otherwise, where f op g is plusinfinity if f=g; min(f,g) if f!=g.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 471 of file cuddAddApply.c.
References cuddIsConstant, cuddV, DD_PLUS_INFINITY, and DdManager::plusinfinity.
DdNode* Cudd_addDivide (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point division.]
Description [Integer and floating point division. Returns NULL if not a terminal case; f / g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 278 of file cuddAddApply.c.
References CUDD_VALUE_TYPE, cuddIsConstant, cuddUniqueConst(), cuddV, DD_ONE, DD_ZERO, and DdGen::value.
DdNode* Cudd_addMaximum (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point max.]
Description [Integer and floating point max for Cudd_addApply. Returns NULL if not a terminal case; max(f,g) otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 392 of file cuddAddApply.c.
References cuddIsConstant, cuddV, DD_MINUS_INFINITY, and DD_PLUS_INFINITY.
DdNode* Cudd_addMinimum (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point min.]
Description [Integer and floating point min for Cudd_addApply. Returns NULL if not a terminal case; min(f,g) otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 348 of file cuddAddApply.c.
References cuddIsConstant, cuddV, DD_MINUS_INFINITY, and DD_PLUS_INFINITY.
Referenced by addTriangleRecur().
DdNode* Cudd_addMinus (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point subtraction.]
Description [Integer and floating point subtraction. Returns NULL if not a terminal case; f - g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 313 of file cuddAddApply.c.
References CUDD_VALUE_TYPE, cuddAddNegateRecur(), cuddIsConstant, cuddUniqueConst(), cuddV, DD_ZERO, and DdGen::value.
DdNode* Cudd_addNand (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [NAND of two 0-1 ADDs.]
Description [NAND of two 0-1 ADDs. Returns NULL if not a terminal case; f NAND g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 573 of file cuddAddApply.c.
References cuddIsConstant, DD_ONE, and DD_ZERO.
DdNode* Cudd_addNor (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [NOR of two 0-1 ADDs.]
Description [NOR of two 0-1 ADDs. Returns NULL if not a terminal case; f NOR g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 605 of file cuddAddApply.c.
References cuddIsConstant, DD_ONE, and DD_ZERO.
DdNode* Cudd_addOneZeroMaximum (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Returns 1 if f &gt g and 0 otherwise.]
Description [Returns 1 if f &gt g (both should be terminal cases) and 0 otherwise. Used in conjunction with Cudd_addApply. Returns NULL if not a terminal case.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 437 of file cuddAddApply.c.
References cuddIsConstant, cuddV, DD_ONE, DD_PLUS_INFINITY, and DD_ZERO.
DdNode* Cudd_addOr (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Disjunction of two 0-1 ADDs.]
Description [Disjunction of two 0-1 ADDs. Returns NULL if not a terminal case; f OR g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 540 of file cuddAddApply.c.
References cuddIsConstant, and DD_ONE.
Referenced by cuddAddOrAbstractRecur(), and cuddAddRestrictRecur().
DdNode* Cudd_addPlus (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point addition.]
Description [Integer and floating point addition. Returns NULL if not a terminal case; f+g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 137 of file cuddAddApply.c.
References CUDD_VALUE_TYPE, cuddIsConstant, cuddUniqueConst(), cuddV, DD_ZERO, and DdGen::value.
Referenced by Cudd_addHamming(), Cudd_addHarwell(), and cuddAddExistAbstractRecur().
DdNode* Cudd_addSetNZ (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [This operator sets f to the value of g wherever g != 0.]
Description [This operator sets f to the value of g wherever g != 0. Returns NULL if not a terminal case; f op g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 249 of file cuddAddApply.c.
References cuddIsConstant, and DD_ZERO.
DdNode* Cudd_addThreshold (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [f if f>=g; 0 if f<g.]
Description [Threshold operator for Apply (f if f >=g; 0 if f<g). Returns NULL if not a terminal case; f op g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 216 of file cuddAddApply.c.
References cuddIsConstant, cuddV, and DD_ZERO.
DdNode* Cudd_addTimes (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [Integer and floating point multiplication.]
Description [Integer and floating point multiplication. Returns NULL if not a terminal case; f * g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 176 of file cuddAddApply.c.
References CUDD_VALUE_TYPE, cuddIsConstant, cuddUniqueConst(), cuddV, DD_ONE, DD_ZERO, and DdGen::value.
Referenced by Cudd_addHarwell(), Cudd_addNonSimCompose(), Cudd_addRead(), Cudd_addTimesPlus(), cuddAddExistAbstractRecur(), and cuddAddUnivAbstractRecur().
DdNode* Cudd_addXnor (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [XNOR of two 0-1 ADDs.]
Description [XNOR of two 0-1 ADDs. Returns NULL if not a terminal case; f XNOR g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 670 of file cuddAddApply.c.
References cuddIsConstant, DD_ONE, and DD_ZERO.
Referenced by Cudd_addNonSimCompose().
DdNode* Cudd_addXor (DdManager * dd, DdNode ** f, DdNode ** g)
Function********************************************************************
Synopsis [XOR of two 0-1 ADDs.]
Description [XOR of two 0-1 ADDs. Returns NULL if not a terminal case; f XOR g otherwise.]
SideEffects [None]
SeeAlso [Cudd_addApply]
Definition at line 637 of file cuddAddApply.c.
References cuddIsConstant, DD_ONE, and DD_ZERO.
DdNode* cuddAddApplyRecur (DdManager * dd, DdNode *(*)(DdManager *, DdNode **, DdNode **) op, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addApply.]
Description [Performs the recursive step of Cudd_addApply. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 708 of file cuddAddApply.c.
References Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, cuddUniqueInter(), and DdNode::index.
Referenced by addTriangleRecur(), Cudd_addApply(), cuddAddExistAbstractRecur(), cuddAddOrAbstractRecur(), cuddAddRestrictRecur(), and cuddAddUnivAbstractRecur().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddApply.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddApply.c]
PackageName [cudd]
Synopsis [Apply function for ADDs and its operators.]
Description [External procedures included in this module:
Cudd_addApply()
Cudd_addPlus()
Cudd_addTimes()
Cudd_addThreshold()
Cudd_addSetNZ()
Cudd_addDivide()
Cudd_addMinus()
Cudd_addMinimum()
Cudd_addMaximum()
Cudd_addOneZeroMaximum()
Cudd_addDiff()
Cudd_addAgreement()
Cudd_addOr()
Cudd_addNand()
Cudd_addNor()
Cudd_addXor()
Cudd_addXnor()
Internal procedures included in this module:
cuddAddApplyRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 68 of file cuddAddApply.c.