cuddZddCount.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static int cuddZddCountStep ARGS ((DdNode *P, st_table *table, DdNode *base, DdNode *empty))
static enum st_retval st_zdd_countfree ARGS ((char *key, char *value, char *arg))
int Cudd_zddCount (DdManager *zdd, DdNode *P)
double Cudd_zddCountDouble (DdManager *zdd, DdNode *P)
static int cuddZddCountStep (DdNode *P, st_table *table, DdNode *base, DdNode *empty)
static double cuddZddCountDoubleStep (DdNode *P, st_table *table, DdNode *base, DdNode *empty)
static enum st_retval st_zdd_countfree (char *key, char *value, char *arg)
static enum st_retval st_zdd_count_dbl_free (char *key, char *value, char *arg)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddCount.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static enum st_retval st_zdd_count_dbl_free ARGS ((char *key, char *value, char *arg)) [static]
static double cuddZddCountDoubleStep ARGS ((DdNode *P, st_table *table, DdNode *base, DdNode *empty)) [static]
AutomaticStart
int Cudd_zddCount (DdManager * zdd, DdNode * P)
Function********************************************************************
Synopsis [Counts the number of minterms in a ZDD.]
Description [Returns an integer representing the number of minterms in a ZDD.]
SideEffects [None]
SeeAlso [Cudd_zddCountDouble]
Definition at line 103 of file cuddZddCount.c.
References CUDD_MEMORY_OUT, CUDD_OUT_OF_MEM, cuddZddCountStep(), DD_ONE, DD_ZERO, empty, DdManager::errorCode, NIL, st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and st_zdd_countfree().
double Cudd_zddCountDouble (DdManager * zdd, DdNode * P)
Function********************************************************************
Synopsis [Counts the number of minterms of a ZDD.]
Description [Counts the number of minterms of a ZDD. The result is returned as a double. If the procedure runs out of memory, it returns CUDD_OUT_OF_MEM. This procedure is used in Cudd_zddCountMinterm.]
SideEffects [None]
SeeAlso [Cudd_zddCountMinterm Cudd_zddCount]
Definition at line 141 of file cuddZddCount.c.
References CUDD_MEMORY_OUT, CUDD_OUT_OF_MEM, cuddZddCountDoubleStep(), DD_ONE, DD_ZERO, empty, DdManager::errorCode, NIL, st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and st_zdd_count_dbl_free().
Referenced by Cudd_zddCountMinterm().
static double cuddZddCountDoubleStep (DdNode * P, st_table * table, DdNode * base, DdNode * empty) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddCountDouble.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 237 of file cuddZddCount.c.
References ALLOC, Cudd_E, CUDD_OUT_OF_MEM, Cudd_T, empty, FREE, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_zddCountDouble().
static int cuddZddCountStep (DdNode * P, st_table * table, DdNode * base, DdNode * empty) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddCount.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 187 of file cuddZddCount.c.
References ALLOC, Cudd_E, CUDD_OUT_OF_MEM, Cudd_T, empty, FREE, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by Cudd_zddCount().
static enum st_retval st_zdd_count_dbl_free (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees the memory associated with the computed table of Cudd_zddCountDouble.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 315 of file cuddZddCount.c.
References FREE, and ST_CONTINUE.
Referenced by Cudd_zddCountDouble().
static enum st_retval st_zdd_countfree (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees the memory associated with the computed table of Cudd_zddCount.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 288 of file cuddZddCount.c.
References FREE, and ST_CONTINUE.
Referenced by Cudd_zddCount().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddCount.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddCount.c]
PackageName [cudd]
Synopsis [Procedures to count the number of minterms of a ZDD.]
Description [External procedures included in this module:
Cudd_zddCount();
Cudd_zddCountDouble();
Internal procedures included in this module:
Static procedures included in this module:
cuddZddCountStep();
cuddZddCountDoubleStep();
st_zdd_count_dbl_free()
st_zdd_countfree()
]
SeeAlso []
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 63 of file cuddZddCount.c.