cuddHarwell.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
int Cudd_addHarwell (FILE *fp, DdManager *dd, DdNode **E, DdNode ***x, DdNode ***y, DdNode ***xn, DdNode ***yn_, int *nx, int *ny, int *m, int *n, int bx, int sx, int by, int sy, int pr)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddHarwell.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
int Cudd_addHarwell (FILE * fp, DdManager * dd, DdNode ** E, DdNode *** x, DdNode *** y, DdNode *** xn, DdNode *** yn_, int * nx, int * ny, int * m, int * n, int bx, int sx, int by, int sy, int pr)
Function********************************************************************
Synopsis [Reads in a matrix in the format of the Harwell-Boeing benchmark suite.]
Description [Reads in a matrix in the format of the Harwell-Boeing benchmark suite. The variables are ordered as follows: <blockquote> x\[0\] y\[0\] x\[1\] y\[1\] ... </blockquote> 0 is the most significant bit. On input, nx and ny hold the numbers of row and column variables already in existence. On output, they hold the numbers of row and column variables actually used by the matrix. m and n are set to the numbers of rows and columns of the matrix. Their values on input are immaterial. Returns 1 on success; 0 otherwise. The ADD for the sparse matrix is returned in E, and its reference count is > 0.]
SideEffects [None]
SeeAlso [Cudd_addRead Cudd_bddRead]
Definition at line 95 of file cuddHarwell.c.
References ALLOC, Cudd_addApply(), Cudd_addPlus(), Cudd_addTimes(), CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddRef, cuddUniqueConst(), cuddUniqueInter(), DD_ONE, DD_ZERO, ddMax, DdManager::errorCode, FREE, one, REALLOC, DdManager::reordered, and zero.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddHarwell.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddHarwell.c]
PackageName [cudd]
Synopsis [Function to read a matrix in Harwell format.]
Description [External procedures included in this module:
Cudd_addHarwell()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 49 of file cuddHarwell.c.