cuddZddPort.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *zddPortFromBddStep ARGS ((DdManager *dd, DdNode *B, int expected))
static DdNode *zddPortToBddStep ARGS ((DdManager *dd, DdNode *f, int depth))
DdNode * Cudd_zddPortFromBdd (DdManager *dd, DdNode *B)
DdNode * Cudd_zddPortToBdd (DdManager *dd, DdNode *f)
static DdNode * zddPortFromBddStep (DdManager *dd, DdNode *B, int expected)
static DdNode * zddPortToBddStep (DdManager *dd, DdNode *f, int depth)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddPort.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* zddPortToBddStep ARGS ((DdManager *dd, DdNode *f, int depth)) [static]
static DdNode* zddPortFromBddStep ARGS ((DdManager *dd, DdNode *B, int expected)) [static]
AutomaticStart
DdNode* Cudd_zddPortFromBdd (DdManager * dd, DdNode * B)
Function********************************************************************
Synopsis [Converts a BDD into a ZDD.]
Description [Converts a BDD into a ZDD. This function assumes that there is a one-to-one correspondence between the BDD variables and the ZDD variables, and that the variable order is the same for both types of variables. These conditions are established if the ZDD variables are created by one call to Cudd_zddVarsFromBddVars with multiplicity = 1. Returns a pointer to the resulting ZDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddVarsFromBddVars]
Definition at line 103 of file cuddZddPort.c.
References DdManager::reordered, and zddPortFromBddStep().
Referenced by zddPortFromBddStep().
DdNode* Cudd_zddPortToBdd (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Converts a ZDD into a BDD.]
Description [Converts a ZDD into a BDD. Returns a pointer to the resulting ZDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddPortFromBdd]
Definition at line 132 of file cuddZddPort.c.
References DdManager::reordered, and zddPortToBddStep().
Referenced by zddPortToBddStep().
static DdNode* zddPortFromBddStep (DdManager * dd, DdNode * B, int expected) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddPortFromBdd.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 169 of file cuddZddPort.c.
References Cudd_IsComplement, Cudd_Not, Cudd_RecursiveDerefZdd(), Cudd_Regular, Cudd_zddPortFromBdd(), cuddCacheInsert1(), cuddCacheLookup1Zdd(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, cuddZddGetNode(), DD_ONE, DD_ZERO, and DdNode::index.
Referenced by Cudd_zddPortFromBdd().
static DdNode* zddPortToBddStep (DdManager * dd, DdNode * f, int depth) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddPortToBdd.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 276 of file cuddZddPort.c.
References Cudd_Not, Cudd_RecursiveDeref(), Cudd_zddPortToBdd(), cuddBddIteRecur(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIZ, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, DdManager::invpermZ, one, DdManager::sizeZ, and zero.
Referenced by Cudd_zddPortToBdd().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddPort.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddPort.c]
PackageName [cudd]
Synopsis [Functions that translate BDDs to ZDDs.]
Description [External procedures included in this module:
Cudd_zddPortFromBdd()
Cudd_zddPortToBdd()
Internal procedures included in this module:
Static procedures included in this module:
zddPortFromBddStep()
zddPortToBddStep()
]
SeeAlso []
Author [Hyong-kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 61 of file cuddZddPort.c.