cuddZddUtil.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static int zp2 ARGS ((DdManager *zdd, DdNode *f, st_table *t))
static void zdd_print_minterm_aux ARGS ((DdManager *zdd, DdNode *node, int level, int *list))
int Cudd_zddPrintMinterm (DdManager *zdd, DdNode *node)
int Cudd_zddPrintDebug (DdManager *zdd, DdNode *f, int n, int pr)
int Cudd_zddDumpDot (DdManager *dd, int n, DdNode **f, char **inames, char **onames, FILE *fp)
int cuddZddP (DdManager *zdd, DdNode *f)
static int zp2 (DdManager *zdd, DdNode *f, st_table *t)
static void zdd_print_minterm_aux (DdManager *zdd, DdNode *node, int level, int *list)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddUtil.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static void zdd_print_minterm_aux ARGS ((DdManager *zdd, DdNode *node, int level, int *list)) [static]
static int zp2 ARGS ((DdManager *zdd, DdNode *f, st_table *t)) [static]
AutomaticStart
int Cudd_zddDumpDot (DdManager * dd, int n, DdNode ** f, char ** inames, char ** onames, FILE * fp)
Function********************************************************************
Synopsis [Writes a dot file representing the argument ZDDs.]
Description [Writes a file representing the argument ZDDs in a format suitable for the graph drawing program dot. It returns 1 in case of success; 0 otherwise (e.g., out-of-memory, file system full). Cudd_zddDumpDot does not close the file: This is the caller responsibility. Cudd_zddDumpDot uses a minimal unique subset of the hexadecimal address of a node as name for it. If the argument inames is non-null, it is assumed to hold the pointers to the names of the inputs. Similarly for onames. Cudd_zddDumpDot uses the following convention to draw arcs:
solid line: THEN arcs;
dashed line: ELSE arcs.
The dot options are chosen so that the drawing fits on a letter-size sheet. ]
SideEffects [None]
SeeAlso [Cudd_DumpDot Cudd_zddPrintDebug]
Definition at line 209 of file cuddZddUtil.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_Support(), cuddCollectNodes(), cuddIsConstant, cuddRef, cuddT, DdManager::errorCode, DdManager::invpermZ, scan, DdManager::sizeZ, st_free_gen(), st_gen(), st_init_gen(), st_init_table(), st_ptrcmp(), and st_ptrhash().
int Cudd_zddPrintDebug (DdManager * zdd, DdNode * f, int n, int pr)
Function********************************************************************
Synopsis [Prints to the standard output a ZDD and its statistics.]
Description [Prints to the standard output a DD and its statistics. The statistics include the number of nodes and the number of minterms. (The number of minterms is also the number of combinations in the set.) The statistics are printed if pr > 0. Specifically:
pr = 0 : prints nothing
pr = 1 : prints counts of nodes and minterms
pr = 2 : prints counts + disjoint sum of product
pr = 3 : prints counts + list of nodes
pr > 3 : prints counts + disjoint sum of product + list of nodes
Returns 1 if successful; 0 otherwise. ]
SideEffects [None]
SeeAlso []
Definition at line 145 of file cuddZddUtil.c.
References CUDD_OUT_OF_MEM, Cudd_zddCountMinterm(), Cudd_zddDagSize(), Cudd_zddPrintMinterm(), cuddZddP(), DD_ZERO, and empty.
int Cudd_zddPrintMinterm (DdManager * zdd, DdNode * node)
Function********************************************************************
Synopsis []
Description []
SideEffects [None]
SeeAlso [Cudd_zddPrintDebug]
Definition at line 100 of file cuddZddUtil.c.
References ALLOC, CUDD_MEMORY_OUT, DdManager::errorCode, FREE, size, DdManager::sizeZ, and zdd_print_minterm_aux().
Referenced by Cudd_zddPrintDebug().
int cuddZddP (DdManager * zdd, DdNode * f)
Function********************************************************************
Synopsis [Prints a ZDD to the standard output. One line per node is printed.]
Description [Prints a ZDD to the standard output. One line per node is printed. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddPrintDebug]
Definition at line 480 of file cuddZddUtil.c.
References st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and zp2().
Referenced by Cudd_zddPrintDebug(), and cuddZddInitUniv().
static void zdd_print_minterm_aux (DdManager * zdd, DdNode * node, int level, int * list) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_zddPrintMinterm.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 594 of file cuddZddUtil.c.
References Cudd_IsConstant, cuddE, cuddIZ, cuddT, DD_ONE, DdNode::index, DdManager::invpermZ, and DdManager::sizeZ.
Referenced by Cudd_zddPrintMinterm().
static int zp2 (DdManager * zdd, DdNode * f, st_table * t) [static]
Function********************************************************************
Synopsis [Performs the recursive step of cuddZddP.]
Description [Performs the recursive step of cuddZddP. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 515 of file cuddZddUtil.c.
References Cudd_IsConstant, cuddE, cuddT, DD_ONE, st_insert(), st_is_member, and ST_OUT_OF_MEM.
Referenced by cuddZddP().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddUtil.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddUtil.c]
PackageName [cudd]
Synopsis [Utility functions for ZDDs.]
Description [External procedures included in this module:
Cudd_zddPrintMinterm()
Cudd_zddPrintDebug()
Cudd_zddDumpDot()
Internal procedures included in this module:
cuddZddP()
Static procedures included in this module:
zp2()
zdd_print_minterm_aux()
]
SeeAlso []
Author [Hyong-Kyoon Shin, In-Ho Moon]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 63 of file cuddZddUtil.c.