cuddAndAbs.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_bddAndAbstract (DdManager *manager, DdNode *f, DdNode *g, DdNode *cube)
DdNode * cuddBddAndAbstractRecur (DdManager *manager, DdNode *f, DdNode *g, DdNode *cube)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAndAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_bddAndAbstract (DdManager * manager, DdNode * f, DdNode * g, DdNode * cube)
Function********************************************************************
Synopsis [Takes the AND of two BDDs and simultaneously abstracts the variables in cube.]
Description [Takes the AND of two BDDs and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the result is successful; NULL otherwise. Cudd_bddAndAbstract implements the semiring matrix multiplication algorithm for the boolean semiring.]
SideEffects [None]
SeeAlso [Cudd_addMatrixMultiply Cudd_addTriangle Cudd_bddAnd]
Definition at line 94 of file cuddAndAbs.c.
References DdGen::cube, cuddBddAndAbstractRecur(), DdGen::manager, and DdManager::reordered.
Referenced by Cudd_PrioritySelect(), and cuddBddAndAbstractRecur().
DdNode* cuddBddAndAbstractRecur (DdManager * manager, DdNode * f, DdNode * g, DdNode * cube)
Function********************************************************************
Synopsis [Takes the AND of two BDDs and simultaneously abstracts the variables in cube.]
Description [Takes the AND of two BDDs and simultaneously abstracts the variables in cube. The variables are existentially abstracted. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddAndAbstract]
Definition at line 131 of file cuddAndAbs.c.
References DdGen::cube, Cudd_bddAndAbstract(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddBddAndRecur(), cuddBddExistAbstractRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, ddMin, DdNode::index, DdGen::manager, one, DdManager::perm, DdNode::ref, and zero.
Referenced by Cudd_bddAndAbstract().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAndAbs.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAndAbs.c]
PackageName [cudd]
Synopsis [Combined AND and existential abstraction for BDDs]
Description [External procedures included in this module:
Cudd_bddAndAbstract()
Internal procedures included in this module:
cuddBddAndAbstractRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 53 of file cuddAndAbs.c.