cuddCompose.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *cuddAddPermuteRecur ARGS ((DdManager *manager, DdHashTable *table, DdNode *node, int *permut))
static DdNode *cuddAddVectorComposeRecur ARGS ((DdManager *dd, DdHashTable *table, DdNode *f, DdNode **vector, int deepest))
static DdNode *cuddAddNonSimComposeRecur ARGS ((DdManager *dd, DdNode *f, DdNode **vector, DdNode *key, DdNode *cube, int lastsub))
static DD_INLINE int ddIsIthAddVar ARGS ((DdManager *dd, DdNode *f, unsigned int i))
DdNode * Cudd_bddCompose (DdManager *dd, DdNode *f, DdNode *g, int v)
DdNode * Cudd_addCompose (DdManager *dd, DdNode *f, DdNode *g, int v)
DdNode * Cudd_addPermute (DdManager *manager, DdNode *node, int *permut)
DdNode * Cudd_addSwapVariables (DdManager *dd, DdNode *f, DdNode **x, DdNode **y, int n)
DdNode * Cudd_bddPermute (DdManager *manager, DdNode *node, int *permut)
DdNode * Cudd_bddSwapVariables (DdManager *dd, DdNode *f, DdNode **x, DdNode **y, int n)
DdNode * Cudd_bddAdjPermuteX (DdManager *dd, DdNode *B, DdNode **x, int n)
DdNode * Cudd_addVectorCompose (DdManager *dd, DdNode *f, DdNode **vector)
DdNode * Cudd_addNonSimCompose (DdManager *dd, DdNode *f, DdNode **vector)
DdNode * Cudd_bddVectorCompose (DdManager *dd, DdNode *f, DdNode **vector)
DdNode * cuddBddComposeRecur (DdManager *dd, DdNode *f, DdNode *g, DdNode *proj)
DdNode * cuddAddComposeRecur (DdManager *dd, DdNode *f, DdNode *g, DdNode *proj)
static DdNode * cuddAddPermuteRecur (DdManager *manager, DdHashTable *table, DdNode *node, int *permut)
static DdNode * cuddBddPermuteRecur (DdManager *manager, DdHashTable *table, DdNode *node, int *permut)
static DdNode * cuddAddVectorComposeRecur (DdManager *dd, DdHashTable *table, DdNode *f, DdNode **vector, int deepest)
static DdNode * cuddAddNonSimComposeRecur (DdManager *dd, DdNode *f, DdNode **vector, DdNode *key, DdNode *cube, int lastsub)
static DdNode * cuddBddVectorComposeRecur (DdManager *dd, DdHashTable *table, DdNode *f, DdNode **vector, int deepest)
static DD_INLINE int ddIsIthAddVar (DdManager *dd, DdNode *f, unsigned int i)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddCompose.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DD_INLINE int ddIsIthAddVar ARGS ((DdManager *dd, DdNode *f, unsigned int i)) [static]
static DdNode* cuddAddNonSimComposeRecur ARGS ((DdManager *dd, DdNode *f, DdNode **vector, DdNode *key, DdNode *cube, int lastsub)) [static]
static DdNode *cuddBddVectorComposeRecur ARGS ((DdManager *dd, DdHashTable *table, DdNode *f, DdNode **vector, int deepest)) [static]
static DdNode *cuddBddPermuteRecur ARGS ((DdManager *manager, DdHashTable *table, DdNode *node, int *permut)) [static]
AutomaticStart
DdNode* Cudd_addCompose (DdManager * dd, DdNode * f, DdNode * g, int v)
Function********************************************************************
Synopsis [Substitutes g for x_v in the ADD for f.]
Description [Substitutes g for x_v in the ADD for f. v is the index of the variable to be substituted. g must be a 0-1 ADD. Cudd_bddCompose passes the corresponding projection function to the recursive procedure, so that the cache may be used. Returns the composed ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddCompose]
Definition at line 163 of file cuddCompose.c.
References cuddAddComposeRecur(), DdManager::reordered, DdManager::size, and DdManager::vars.
DdNode* Cudd_addNonSimCompose (DdManager * dd, DdNode * f, DdNode ** vector)
Function********************************************************************
Synopsis [Composes an ADD with a vector of 0-1 ADDs.]
Description [Given a vector of 0-1 ADDs, creates a new ADD by substituting the 0-1 ADDs for the variables of the ADD f. There should be an entry in vector for each variable in the manager. This function implements non-simultaneous composition. If any of the functions being composed depends on any of the variables being substituted, then the result depends on the order of composition, which in turn depends on the variable order: The variables farther from the roots in the order are substituted first. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addVectorCompose Cudd_addPermute Cudd_addCompose]
Definition at line 490 of file cuddCompose.c.
References Cudd_addApply(), Cudd_addIthVar(), Cudd_addTimes(), Cudd_addXnor(), Cudd_RecursiveDeref(), cuddAddNonSimComposeRecur(), cuddDeref, cuddRef, DD_ONE, ddIsIthAddVar(), DdManager::reordered, and DdManager::size.
Referenced by cuddAddNonSimComposeRecur().
DdNode* Cudd_addPermute (DdManager * manager, DdNode * node, int * permut)
Function********************************************************************
Synopsis [Permutes the variables of an ADD.]
Description [Given a permutation in array permut, creates a new ADD with permuted variables. There should be an entry in array permut for each variable in the manager. The i-th entry of permut holds the index of the variable that is to substitute the i-th variable. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddPermute Cudd_addSwapVariables]
Definition at line 201 of file cuddCompose.c.
References cuddAddPermuteRecur(), cuddDeref, cuddHashTableInit(), cuddHashTableQuit(), cuddRef, and DdManager::reordered.
Referenced by Cudd_addSwapVariables().
DdNode* Cudd_addSwapVariables (DdManager * dd, DdNode * f, DdNode ** x, DdNode ** y, int n)
Function********************************************************************
Synopsis [Swaps two sets of variables of the same size (x and y) in the ADD f.]
Description [Swaps two sets of variables of the same size (x and y) in the ADD f. The size is given by n. The two sets of variables are assumed to be disjoint. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addPermute Cudd_bddSwapVariables]
Definition at line 242 of file cuddCompose.c.
References ALLOC, Cudd_addPermute(), CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdNode::index, and DdManager::size.
DdNode* Cudd_addVectorCompose (DdManager * dd, DdNode * f, DdNode ** vector)
Function********************************************************************
Synopsis [Composes an ADD with a vector of 0-1 ADDs.]
Description [Given a vector of 0-1 ADDs, creates a new ADD by substituting the 0-1 ADDs for the variables of the ADD f. There should be an entry in vector for each variable in the manager. If no substitution is sought for a given variable, the corresponding projection function should be specified in the vector. This function implements simultaneous composition. Returns a pointer to the resulting ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addNonSimCompose Cudd_addPermute Cudd_addCompose Cudd_bddVectorCompose]
Definition at line 431 of file cuddCompose.c.
References cuddAddVectorComposeRecur(), cuddDeref, cuddHashTableInit(), cuddHashTableQuit(), cuddRef, ddIsIthAddVar(), DdManager::invperm, DdManager::reordered, and DdManager::size.
DdNode* Cudd_bddAdjPermuteX (DdManager * dd, DdNode * B, DdNode ** x, int n)
Function********************************************************************
Synopsis [Rearranges a set of variables in the BDD B.]
Description [Rearranges a set of variables in the BDD B. The size of the set is given by n. This procedure is intended for the `randomization' of the priority functions. Returns a pointer to the BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddPermute Cudd_bddSwapVariables Cudd_Dxygtdxz Cudd_Dxygtdyz Cudd_PrioritySelect]
Definition at line 380 of file cuddCompose.c.
References ALLOC, Cudd_bddPermute(), CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdNode::index, and DdManager::size.
DdNode* Cudd_bddCompose (DdManager * dd, DdNode * f, DdNode * g, int v)
Function********************************************************************
Synopsis [Substitutes g for x_v in the BDD for f.]
Description [Substitutes g for x_v in the BDD for f. v is the index of the variable to be substituted. Cudd_bddCompose passes the corresponding projection function to the recursive procedure, so that the cache may be used. Returns the composed BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addCompose]
Definition at line 126 of file cuddCompose.c.
References cuddBddComposeRecur(), DdManager::reordered, DdManager::size, and DdManager::vars.
Referenced by cuddVerifySol().
DdNode* Cudd_bddPermute (DdManager * manager, DdNode * node, int * permut)
Function********************************************************************
Synopsis [Permutes the variables of a BDD.]
Description [Given a permutation in array permut, creates a new BDD with permuted variables. There should be an entry in array permut for each variable in the manager. The i-th entry of permut holds the index of the variable that is to substitute the i-th variable. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addPermute Cudd_bddSwapVariables]
Definition at line 291 of file cuddCompose.c.
References cuddBddPermuteRecur(), cuddDeref, cuddHashTableInit(), cuddHashTableQuit(), cuddRef, and DdManager::reordered.
Referenced by Cudd_bddAdjPermuteX(), and Cudd_bddSwapVariables().
DdNode* Cudd_bddSwapVariables (DdManager * dd, DdNode * f, DdNode ** x, DdNode ** y, int n)
Function********************************************************************
Synopsis [Swaps two sets of variables of the same size (x and y) in the BDD f.]
Description [Swaps two sets of variables of the same size (x and y) in the BDD f. The size is given by n. The two sets of variables are assumed to be disjoint. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddPermute Cudd_addSwapVariables]
Definition at line 332 of file cuddCompose.c.
References ALLOC, Cudd_bddPermute(), CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdNode::index, and DdManager::size.
Referenced by Cudd_PrioritySelect().
DdNode* Cudd_bddVectorCompose (DdManager * dd, DdNode * f, DdNode ** vector)
Function********************************************************************
Synopsis [Composes a BDD with a vector of BDDs.]
Description [Given a vector of BDDs, creates a new BDD by substituting the BDDs for the variables of the BDD f. There should be an entry in vector for each variable in the manager. If no substitution is sought for a given variable, the corresponding projection function should be specified in the vector. This function implements simultaneous composition. Returns a pointer to the resulting BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddPermute Cudd_bddCompose Cudd_addVectorCompose]
Definition at line 599 of file cuddCompose.c.
References cuddBddVectorComposeRecur(), cuddDeref, cuddHashTableInit(), cuddHashTableQuit(), cuddRef, DdManager::invperm, DdManager::reordered, DdManager::size, and DdManager::vars.
DdNode* cuddAddComposeRecur (DdManager * dd, DdNode * f, DdNode * g, DdNode * proj)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addCompose.]
Description [Performs the recursive step of Cudd_addCompose. Returns the composed BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addCompose]
Definition at line 759 of file cuddCompose.c.
References Cudd_RecursiveDeref(), cuddAddIteRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, cuddUniqueInter(), DdNode::index, and DdManager::perm.
Referenced by Cudd_addCompose().
static DdNode* cuddAddNonSimComposeRecur (DdManager * dd, DdNode * f, DdNode ** vector, DdNode * key, DdNode * cube, int lastsub) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addNonSimCompose.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1113 of file cuddCompose.c.
References ALLOC, Cudd_addIthVar(), Cudd_addNonSimCompose(), Cudd_IsConstant, CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), cuddAddExistAbstractRecur(), cuddCacheLookup(), cuddE, cuddI, cuddRef, cuddT, DD_ONE, ddMin, DdManager::errorCode, FREE, DdNode::index, and DdManager::invperm.
Referenced by Cudd_addNonSimCompose().
static DdNode* cuddAddPermuteRecur (DdManager * manager, DdHashTable * table, DdNode * node, int * permut) [static]
Function********************************************************************
Synopsis [Implements the recursive step of addPermute.]
Description [ Recursively puts the ADD in the order given in the array permut. Checks for trivial cases to terminate recursion, then splits on the children of this node. Once the solutions for the children are obtained, it puts into the current position the node from the rest of the ADD that should be here. Then returns this ADD. The key here is that the node being visited is NOT put in its proper place by this instance, but rather is switched when its proper position is reached in the recursion tree.
The DdNode * that is returned is the same ADD as passed in as node, but in the new order.]
SideEffects [None]
SeeAlso [cuddBddPermuteRecur]
Definition at line 863 of file cuddCompose.c.
References Cudd_RecursiveDeref(), cuddAddIteRecur(), cuddDeref, cuddE, cuddHashTableInsert1(), cuddHashTableLookup1(), cuddIsConstant, cuddRef, cuddSatDec, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, and DdNode::ref.
Referenced by Cudd_addPermute().
static DdNode* cuddAddVectorComposeRecur (DdManager * dd, DdHashTable * table, DdNode * f, DdNode ** vector, int deepest) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addVectorCompose.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1038 of file cuddCompose.c.
References Cudd_RecursiveDeref(), cuddAddIteRecur(), cuddDeref, cuddE, cuddHashTableInsert1(), cuddHashTableLookup1(), cuddI, cuddRef, cuddSatDec, cuddT, DdNode::index, and DdNode::ref.
Referenced by Cudd_addVectorCompose().
DdNode* cuddBddComposeRecur (DdManager * dd, DdNode * f, DdNode * g, DdNode * proj)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddCompose.]
Description [Performs the recursive step of Cudd_bddCompose. Exploits the fact that the composition of f' with g produces the complement of the composition of f with g to better utilize the cache. Returns the composed BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddCompose]
Definition at line 658 of file cuddCompose.c.
References Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddBddIteRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, DdNode::index, DdManager::perm, and DdManager::vars.
Referenced by Cudd_bddCompose(), and cuddSolveEqnRecur().
static DdNode* cuddBddPermuteRecur (DdManager * manager, DdHashTable * table, DdNode * node, int * permut) [static]
Function********************************************************************
Synopsis [Implements the recursive step of bddPermute.]
Description [ Recursively puts the BDD in the order given in the array permut. Checks for trivial cases to terminate recursion, then splits on the children of this node. Once the solutions for the children are obtained, it puts into the current position the node from the rest of the BDD that should be here. Then returns this BDD. The key here is that the node being visited is NOT put in its proper place by this instance, but rather is switched when its proper position is reached in the recursion tree.
The DdNode * that is returned is the same BDD as passed in as node, but in the new order.]
SideEffects [None]
SeeAlso [cuddAddPermuteRecur]
Definition at line 955 of file cuddCompose.c.
References Cudd_IterDerefBdd(), Cudd_NotCond, Cudd_Regular, cuddBddIteRecur(), cuddDeref, cuddE, cuddHashTableInsert1(), cuddHashTableLookup1(), cuddIsConstant, cuddRef, cuddSatDec, cuddT, DdNode::index, DdNode::ref, and DdManager::vars.
Referenced by Cudd_bddPermute().
static DdNode* cuddBddVectorComposeRecur (DdManager * dd, DdHashTable * table, DdNode * f, DdNode ** vector, int deepest) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddVectorCompose.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 1275 of file cuddCompose.c.
References Cudd_IterDerefBdd(), Cudd_NotCond, Cudd_Regular, cuddBddIteRecur(), cuddDeref, cuddE, cuddHashTableInsert1(), cuddHashTableLookup1(), cuddI, cuddRef, cuddSatDec, cuddT, DdNode::index, and DdNode::ref.
Referenced by Cudd_bddVectorCompose().
static DD_INLINE int ddIsIthAddVar (DdManager * dd, DdNode * f, unsigned int i) [static]
Function********************************************************************
Synopsis [Comparison of a function to the i-th ADD variable.]
Description [Comparison of a function to the i-th ADD variable. Returns 1 if the function is the i-th ADD variable; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 1358 of file cuddCompose.c.
References cuddE, cuddT, DD_ONE, DD_ZERO, and DdNode::index.
Referenced by Cudd_addNonSimCompose(), and Cudd_addVectorCompose().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddCompose.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddCompose.c]
PackageName [cudd]
Synopsis [Functional composition and variable permutation of DDs.]
Description [External procedures included in this module:
Cudd_bddCompose()
Cudd_addCompose()
Cudd_addPermute()
Cudd_addSwapVariables()
Cudd_bddPermute()
Cudd_bddSwapVariables()
Cudd_bddAdjPermuteX()
Cudd_addVectorCompose()
Cudd_addNonSimCompose()
Cudd_bddVectorCompose()
Internal procedures included in this module:
cuddBddComposeRecur()
cuddAddComposeRecur()
Static procedures included in this module:
cuddAddPermuteRecur()
cuddBddPermuteRecur()
cuddAddVectorComposeRecur()
cuddAddNonSimComposeRecur()
cuddBddVectorComposeRecur()
ddIsIthAddVar()
The permutation functions use a local cache because the results to be remembered depend on the permutation being applied. Since the permutation is just an array, it cannot be stored in the global cache. There are different procedured for BDDs and ADDs. This is because bddPermuteRecur uses cuddBddIteRecur. If this were changed, the procedures could be merged.]
Author [Fabio Somenzi and Kavita Ravi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 75 of file cuddCompose.c.