cuddGroup.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static int ddTreeSiftingAux ARGS ((DdManager *table, MtrNode *treenode, Cudd_ReorderingType method))
static void ddFindNodeHiLo ARGS ((DdManager *table, MtrNode *treenode, int *lower, int *upper))
static int ddUniqueCompareGroup ARGS ((int *ptrX, int *ptrY))
static int ddGroupSifting ARGS ((DdManager *table, int lower, int upper, int(*checkFunction)(DdManager *, int, int)))
static void ddCreateGroup ARGS ((DdManager *table, int x, int y))
static int ddGroupSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh, int(*checkFunction)(DdManager *, int, int)))
static int ddGroupSiftingUp ARGS ((DdManager *table, int y, int xLow, int(*checkFunction)(DdManager *, int, int), Move **moves))
static int ddGroupSiftingDown ARGS ((DdManager *table, int x, int xHigh, int(*checkFunction)(DdManager *, int, int), Move **moves))
static int ddGroupMove ARGS ((DdManager *table, int x, int y, Move **moves))
static int ddGroupSiftingBackward ARGS ((DdManager *table, Move *moves, int size))
static void ddMergeGroups ARGS ((DdManager *table, MtrNode *treenode, int low, int high))
MtrNode * Cudd_MakeTreeNode (DdManager *dd, unsigned int low, unsigned int size, unsigned int type)
int cuddTreeSifting (DdManager *table, Cudd_ReorderingType method)
static int ddTreeSiftingAux (DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)
static int ddReorderChildren (DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)
static void ddFindNodeHiLo (DdManager *table, MtrNode *treenode, int *lower, int *upper)
static int ddUniqueCompareGroup (int *ptrX, int *ptrY)
static int ddGroupSifting (DdManager *table, int lower, int upper, int(*checkFunction)(DdManager *, int, int))
static void ddCreateGroup (DdManager *table, int x, int y)
static int ddGroupSiftingAux (DdManager *table, int x, int xLow, int xHigh, int(*checkFunction)(DdManager *, int, int))
static int ddGroupSiftingUp (DdManager *table, int y, int xLow, int(*checkFunction)(DdManager *, int, int), Move **moves)
static int ddGroupSiftingDown (DdManager *table, int x, int xHigh, int(*checkFunction)(DdManager *, int, int), Move **moves)
static int ddGroupMove (DdManager *table, int x, int y, Move **moves)
static int ddGroupMoveBackward (DdManager *table, int x, int y)
static int ddGroupSiftingBackward (DdManager *table, Move *moves, int size)
static void ddMergeGroups (DdManager *table, MtrNode *treenode, int low, int high)
static void ddDissolveGroup (DdManager *table, int x, int y)
static int ddNoCheck (DdManager *table, int x, int y)
static int ddSecDiffCheck (DdManager *table, int x, int y)
static int ddExtSymmCheck (DdManager *table, int x, int y)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int * entry
int ddTotalNumberSwapping
Function Documentation
static void ddMergeGroups ARGS ((DdManager *table, MtrNode *treenode, int low, int high)) [static]
static int ddGroupSiftingBackward ARGS ((DdManager *table, Move *moves, int size)) [static]
static int ddGroupMove ARGS ((DdManager *table, int x, int y, Move **moves)) [static]
static int ddGroupSiftingDown ARGS ((DdManager *table, int x, int xHigh, int(*checkFunction)(DdManager *, int, int), Move **moves)) [static]
static int ddGroupSiftingUp ARGS ((DdManager *table, int y, int xLow, int(*checkFunction)(DdManager *, int, int), Move **moves)) [static]
static int ddGroupSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh, int(*checkFunction)(DdManager *, int, int))) [static]
static void ddCreateGroup ARGS ((DdManager *table, int x, int y)) [static]
static int ddGroupSifting ARGS ((DdManager *table, int lower, int upper, int(*checkFunction)(DdManager *, int, int))) [static]
static int ddUniqueCompareGroup ARGS ((int *ptrX, int *ptrY)) [static]
static void ddFindNodeHiLo ARGS ((DdManager *table, MtrNode *treenode, int *lower, int *upper)) [static]
static int ddReorderChildren ARGS ((DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)) [static]
AutomaticStart
MtrNode* Cudd_MakeTreeNode (DdManager * dd, unsigned int low, unsigned int size, unsigned int type)
Function********************************************************************
Synopsis [Creates a new variable group.]
Description [Creates a new variable group. The group starts at variable and contains size variables. The parameter low is the index of the first variable. If the variable already exists, its current position in the order is known to the manager. If the variable does not exist yet, the position is assumed to be the same as the index. The group tree is created if it does not exist yet. Returns a pointer to the group if successful; NULL otherwise.]
SideEffects [The variable tree is changed.]
SeeAlso [Cudd_MakeZddTreeNode]
Definition at line 145 of file cuddGroup.c.
References ddMax, MtrNode::index, DdManager::invperm, Mtr_InitGroupTree(), Mtr_MakeGroup(), MTR_MAXHIGH, DdManager::perm, MtrNode::size, DdManager::size, and DdManager::tree.
int cuddTreeSifting (DdManager * table, Cudd_ReorderingType method)
Function********************************************************************
Synopsis [Tree sifting algorithm.]
Description [Tree sifting algorithm. Assumes that a tree representing a group hierarchy is passed as a parameter. It then reorders each group in postorder fashion by calling ddTreeSiftingAux. Assumes that no dead nodes are present. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 213 of file cuddGroup.c.
References CUDD_GROUP_CHECK5, CUDD_GROUP_CHECK7, CUDD_REORDER_GROUP_SIFT, ddTreeSiftingAux(), DdManager::groupcheck, MtrNode::index, DdManager::invperm, Mtr_InitGroupTree(), Mtr_PrintGroups(), DdSubtable::next, result, DdManager::size, DdManager::subtables, and DdManager::tree.
Referenced by Cudd_ReduceHeap().
static void ddCreateGroup (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Creates a group encompassing variables from x to y in the DD table.]
Description [Creates a group encompassing variables from x to y in the DD table. In the current implementation it must be y == x+1. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 825 of file cuddGroup.c.
References assert, DdSubtable::next, and DdManager::subtables.
static void ddDissolveGroup (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Dissolves a group in the DD table.]
Description [x and y are variables in a group to be cut in two. The cut is to pass between x and y.]
SideEffects [None]
Definition at line 1646 of file cuddGroup.c.
References DdSubtable::next, and DdManager::subtables.
static int ddExtSymmCheck (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Checks for extended symmetry of x and y.]
Description [Checks for extended symmetry of x and y. Returns 1 in case of extended symmetry; 0 otherwise.]
SideEffects [None]
Definition at line 1760 of file cuddGroup.c.
References DdManager::arcviolation, assert, Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddE, cuddT, cuddTestInteract(), DD_ONE, DdNode::index, DdManager::invperm, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, one, DdNode::ref, DdSubtable::slots, DdManager::subtables, DdManager::symmviolation, and DdManager::vars.
Referenced by ddReorderChildren().
static void ddFindNodeHiLo (DdManager * table, MtrNode * treenode, int * lower, int * upper) [static]
Function********************************************************************
Synopsis [Finds the lower and upper bounds of the group represented by treenode.]
Description [Finds the lower and upper bounds of the group represented by treenode. The high and low fields of treenode are indices. From those we need to derive the current positions, and find maximum and minimum.]
SideEffects [The bounds are returned as side effects.]
SeeAlso []
Definition at line 539 of file cuddGroup.c.
References assert, MtrNode::child, MtrNode::index, MtrNode::low, DdManager::perm, size, MtrNode::size, DdManager::size, and MtrNode::younger.
Referenced by ddReorderChildren().
static int ddGroupMove (DdManager * table, int x, int y, Move ** moves) [static]
Function********************************************************************
Synopsis [Swaps two groups and records the move.]
Description [Swaps two groups and records the move. Returns the number of keys in the DD table in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1370 of file cuddGroup.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddNextLow(), cuddSwapInPlace(), Move::flags, DdManager::isolated, DdManager::keys, MTR_DEFAULT, Move::next, DdSubtable::next, Move::size, size, DdManager::subtables, Move::x, and Move::y.
Referenced by ddGroupSiftingDown(), and ddGroupSiftingUp().
static int ddGroupMoveBackward (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Undoes the swap two groups.]
Description [Undoes the swap two groups. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1476 of file cuddGroup.c.
References assert, cuddNextHigh(), cuddNextLow(), cuddSwapInPlace(), DdSubtable::next, size, and DdManager::subtables.
static int ddGroupSifting (DdManager * table, int lower, int upper, int(*)(DdManager *, int, int) checkFunction) [static]
Function********************************************************************
Synopsis [Sifts from treenode->low to treenode->high.]
Description [Sifts from treenode->low to treenode->high. If croupcheck == CUDD_GROUP_CHECK7, it checks for group creation at the end of the initial sifting. If a group is created, it is then sifted again. After sifting one variable, the group that contains it is dissolved. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 642 of file cuddGroup.c.
References ALLOC, CUDD_MEMORY_OUT, entry, DdManager::errorCode, DdSubtable::keys, DdSubtable::next, DdManager::perm, result, DdManager::size, and DdManager::subtables.
Referenced by ddReorderChildren().
static int ddGroupSiftingAux (DdManager * table, int x, int xLow, int xHigh, int(*)(DdManager *, int, int) checkFunction) [static]
Function********************************************************************
Synopsis [Sifts one variable up and down until it has taken all positions. Checks for aggregation.]
Description [Sifts one variable up and down until it has taken all positions. Checks for aggregation. There may be at most two sweeps, even if the group grows. Assumes that x is either an isolated variable, or it is the bottom of a group. All groups may not have been found. The variable being moved is returned to the best position seen during sifting. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 866 of file cuddGroup.c.
References assert, cuddDeallocNode, cuddNextHigh(), ddGroupSiftingBackward(), ddGroupSiftingDown(), ddGroupSiftingUp(), DdManager::isolated, DdManager::keys, Move::next, DdSubtable::next, result, DdManager::subtables, Move::x, and Move::y.
static int ddGroupSiftingBackward (DdManager * table, Move * moves, int size) [static]
Function********************************************************************
Synopsis [Determines the best position for a variables and returns it there.]
Description [Determines the best position for a variables and returns it there. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1550 of file cuddGroup.c.
References Move::next, and Move::size.
Referenced by ddGroupSiftingAux().
static int ddGroupSiftingDown (DdManager * table, int x, int xHigh, int(*)(DdManager *, int, int) checkFunction, Move ** moves) [static]
Function********************************************************************
Synopsis [Sifts down a variable until it reaches position xHigh.]
Description [Sifts down a variable until it reaches position xHigh. Assumes that x is the bottom of a group (or a singleton). Records all the moves. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1214 of file cuddGroup.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddSwapInPlace(), cuddTestInteract(), ddGroupMove(), Move::flags, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, MTR_DEFAULT, MTR_NEWNODE, Move::next, DdSubtable::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddGroupSiftingAux().
static int ddGroupSiftingUp (DdManager * table, int y, int xLow, int(*)(DdManager *, int, int) checkFunction, Move ** moves) [static]
Function********************************************************************
Synopsis [Sifts up a variable until either it reaches position xLow or the size of the DD heap increases too much.]
Description [Sifts up a variable until either it reaches position xLow or the size of the DD heap increases too much. Assumes that y is the top of a group (or a singleton). Checks y for aggregation to the adjacent variables. Records all the moves that are appended to the list of moves received as input and returned as a side effect. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1057 of file cuddGroup.c.
References assert, cuddDynamicAllocNode(), cuddNextLow(), cuddSwapInPlace(), cuddTestInteract(), ddGroupMove(), Move::flags, DdManager::invperm, DdManager::isolated, DdSubtable::keys, DdManager::keys, DdManager::maxGrowth, MTR_DEFAULT, MTR_NEWNODE, Move::next, DdSubtable::next, DdNode::ref, Move::size, size, DdManager::subtables, DdManager::vars, Move::x, and Move::y.
Referenced by ddGroupSiftingAux().
static void ddMergeGroups (DdManager * table, MtrNode * treenode, int low, int high) [static]
Function********************************************************************
Synopsis [Merges groups in the DD table.]
Description [Creates a single group from low to high and adjusts the idex field of the tree node.]
SideEffects [None]
Definition at line 1603 of file cuddGroup.c.
References MtrNode::index, DdManager::invperm, DdSubtable::next, MtrNode::parent, DdManager::subtables, and DdManager::tree.
Referenced by ddReorderChildren().
static int ddNoCheck (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Pretends to check two variables for aggregation.]
Description [Pretends to check two variables for aggregation. Always returns 0.]
SideEffects [None]
Definition at line 1680 of file cuddGroup.c.
Referenced by ddReorderChildren().
static int ddReorderChildren (DdManager * table, MtrNode * treenode, Cudd_ReorderingType method) [static]
Function********************************************************************
Synopsis [Reorders the children of a group tree node according to the options.]
Description [Reorders the children of a group tree node according to the options. After reordering puts all the variables in the group and/or its descendents in a single group. This allows hierarchical reordering. If the variables in the group do not exist yet, simply does nothing. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 387 of file cuddGroup.c.
References CUDD_GROUP_CHECK5, CUDD_GROUP_CHECK7, CUDD_NO_CHECK, CUDD_REORDER_ANNEALING, CUDD_REORDER_EXACT, CUDD_REORDER_GENETIC, CUDD_REORDER_GROUP_SIFT, CUDD_REORDER_GROUP_SIFT_CONV, CUDD_REORDER_LINEAR, CUDD_REORDER_LINEAR_CONVERGE, CUDD_REORDER_RANDOM, CUDD_REORDER_RANDOM_PIVOT, CUDD_REORDER_SIFT, CUDD_REORDER_SIFT_CONVERGE, CUDD_REORDER_SYMM_SIFT, CUDD_REORDER_SYMM_SIFT_CONV, CUDD_REORDER_WINDOW2, CUDD_REORDER_WINDOW2_CONV, CUDD_REORDER_WINDOW3, CUDD_REORDER_WINDOW3_CONV, CUDD_REORDER_WINDOW4, CUDD_REORDER_WINDOW4_CONV, cuddAnnealing(), cuddExact(), cuddGa(), cuddLinearAndSifting(), cuddSifting(), cuddSwapping(), cuddSymmSifting(), cuddSymmSiftingConv(), cuddWindowReorder(), ddExtSymmCheck(), ddFindNodeHiLo(), ddGroupSifting(), ddMergeGroups(), ddNoCheck(), MtrNode::flags, DdManager::groupcheck, DdManager::isolated, DdManager::keys, MTR_FIXED, and result.
Referenced by ddTreeSiftingAux().
static int ddSecDiffCheck (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Checks two variables for aggregation.]
Description [Checks two variables for aggregation. The check is based on the second difference of the number of nodes as a function of the layer. If the second difference is lower than a given threshold (typically negative) then the two variables should be aggregated. Returns 1 if the two variables pass the test; 0 otherwise.]
SideEffects [None]
Definition at line 1704 of file cuddGroup.c.
References cuddTestInteract(), DdManager::invperm, DdSubtable::keys, DdManager::recomb, and DdManager::subtables.
static int ddTreeSiftingAux (DdManager * table, MtrNode * treenode, Cudd_ReorderingType method) [static]
Function********************************************************************
Synopsis [Visits the group tree and reorders each group.]
Description [Recursively visits the group tree and reorders each group in postorder fashion. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 299 of file cuddGroup.c.
References MtrNode::child, CUDD_NO_CHECK, CUDD_REORDER_GROUP_SIFT, ddReorderChildren(), DdManager::groupcheck, Mtr_PrintGroups(), MtrNode::size, and MtrNode::younger.
Referenced by cuddTreeSifting().
static int ddUniqueCompareGroup (int * ptrX, int * ptrY) [static]
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
Definition at line 614 of file cuddGroup.c.
References entry.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddGroup.c]
PackageName [cudd]
Synopsis [Functions for group sifting.]
Description [External procedures included in this file:
Cudd_MakeTreeNode()
Internal procedures included in this file:
cuddTreeSifting()
Static procedures included in this module:
ddTreeSiftingAux()
ddCountInternalMtrNodes()
ddReorderChildren()
ddFindNodeHiLo()
ddUniqueCompareGroup()
ddGroupSifting()
ddCreateGroup()
ddGroupSiftingAux()
ddGroupSiftingUp()
ddGroupSiftingDown()
ddGroupMove()
ddGroupMoveBackward()
ddGroupSiftingBackward()
ddMergeGroups()
ddDissolveGroup()
ddNoCheck()
ddSecDiffCheck()
ddExtSymmCheck()
]
Author [Shipra Panda, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 70 of file cuddGroup.c.
int ddTotalNumberSwapping
Definition at line 78 of file cuddReorder.c.
Referenced by Cudd_ReduceHeap(), cuddSifting(), cuddSwapInPlace(), cuddSwapping(), cuddSymmSifting(), cuddSymmSiftingConv(), and ddShuffle().
int* entry [static]
Definition at line 73 of file cuddGroup.c.
Referenced by bddCorrelationAux(), bddCorrelationWeightsAux(), BuildSubsetBdd(), CorrelCleanUp(), CorrelHash(), cuddCacheInsert(), cuddCacheInsert1(), cuddCacheInsert2(), cuddCacheResize(), cuddLinearAndSifting(), cuddLocalCacheInsert(), cuddLocalCacheLookup(), cuddLocalCacheResize(), cuddSifting(), cuddSymmSifting(), cuddSymmSiftingConv(), ddGroupSifting(), ddLinearUniqueCompare(), ddSymmUniqueCompare(), ddUniqueCompare(), ddUniqueCompareGroup(), MarkCacheCleanUp(), MarkCacheHash(), zddGroupSifting(), and zddUniqueCompareGroup().