cuddMatMult.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *addMMRecur ARGS ((DdManager *dd, DdNode *A, DdNode *B, int topP, int *vars))
static DdNode *addTriangleRecur ARGS ((DdManager *dd, DdNode *f, DdNode *g, int *vars))
DdNode * Cudd_addMatrixMultiply (DdManager *dd, DdNode *A, DdNode *B, DdNode **z, int nz)
DdNode * Cudd_addTimesPlus (DdManager *dd, DdNode *A, DdNode *B, DdNode **z, int nz)
DdNode * Cudd_addTriangle (DdManager *dd, DdNode *f, DdNode *g, DdNode **z, int nz)
static DdNode * addMMRecur (DdManager *dd, DdNode *A, DdNode *B, int topP, int *vars)
static DdNode * addTriangleRecur (DdManager *dd, DdNode *f, DdNode *g, int *vars)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddMatMult.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* addMMRecur (DdManager * dd, DdNode * A, DdNode * B, int topP, int * vars) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addMatrixMultiply.]
Description [Performs the recursive step of Cudd_addMatrixMultiply. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
Definition at line 260 of file cuddMatMult.c.
References CUDD_VALUE_TYPE, cuddIsConstant, cuddUniqueConst(), cuddV, DD_ZERO, DdManager::perm, DdManager::size, and zero.
Referenced by Cudd_addMatrixMultiply().
static DdNode* addTriangleRecur (DdManager * dd, DdNode * f, DdNode * g, int * vars) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addTriangle.]
Description [Performs the recursive step of Cudd_addTriangle. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
Definition at line 471 of file cuddMatMult.c.
References Cudd_addMinimum(), Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddAddApplyRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddIsConstant, cuddRef, cuddT, cuddUniqueConst(), cuddUniqueInter(), cuddV, DD_PLUS_INFINITY, ddMin, DdNode::index, and DdManager::invperm.
Referenced by Cudd_addTriangle().
static DdNode* addTriangleRecur ARGS ((DdManager *dd, DdNode *f, DdNode *g, int *vars)) [static]
static DdNode* addMMRecur ARGS ((DdManager *dd, DdNode *A, DdNode *B, int topP, int *vars)) [static]
AutomaticStart
DdNode* Cudd_addMatrixMultiply (DdManager * dd, DdNode * A, DdNode * B, DdNode ** z, int nz)
Function********************************************************************
Synopsis [Calculates the product of two matrices represented as ADDs.]
Description [Calculates the product of two matrices, A and B, represented as ADDs. This procedure implements the quasiring multiplication algorithm. A is assumed to depend on varibles x (rows) and z (columns). B is assumed to depend on varibles z (rows) and y (columns). The product of A and B then depends on x (rows) and y (columns). Only the z variables have to be explicitly identified; they are the `summation` variables. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addTimesPlus Cudd_addTriangle Cudd_bddAndAbstract]
Definition at line 100 of file cuddMatMult.c.
References addMMRecur(), ALLOC, CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdManager::reordered, and DdManager::size.
DdNode* Cudd_addTimesPlus (DdManager * dd, DdNode * A, DdNode * B, DdNode ** z, int nz)
Function********************************************************************
Synopsis [Calculates the product of two matrices represented as ADDs.]
Description [Calculates the product of two matrices, A and B, represented as ADDs, using the CMU matrix by matrix multiplication procedure by Clarke et al.. Matrix A has x's as row variables and z's as column variables, while matrix B has z's as row variables and y's as column variables. Returns the pointer to the result if successful; NULL otherwise. The resulting matrix has x's as row variables and y's as column variables.]
SideEffects [None]
SeeAlso [Cudd_addMatrixMultiply]
Definition at line 153 of file cuddMatMult.c.
References Cudd_addApply(), Cudd_addExistAbstract(), Cudd_addIte(), Cudd_addTimes(), Cudd_Deref(), Cudd_RecursiveDeref(), Cudd_Ref(), DD_ONE, and DD_ZERO.
DdNode* Cudd_addTriangle (DdManager * dd, DdNode * f, DdNode * g, DdNode ** z, int nz)
Function********************************************************************
Synopsis [Performs the triangulation step for the shortest path computation.]
Description [Implements the semiring multiplication algorithm used in the triangulation step for the shortest path computation. f is assumed to depend on varibles x (rows) and z (columns). g is assumed to depend on varibles z (rows) and y (columns). The product of f and g then depends on x (rows) and y (columns). Only the z variables have to be explicitly identified; they are the `abstraction` variables. Returns a pointer to the result if successful; NULL otherwise. ]
SideEffects [None]
SeeAlso [Cudd_addMatrixMultiply Cudd_bddAndAbstract]
Definition at line 211 of file cuddMatMult.c.
References addTriangleRecur(), ALLOC, CUDD_MEMORY_OUT, DdManager::errorCode, FREE, DdManager::reordered, and DdManager::size.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddMatMult.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddMatMult.c]
PackageName [cudd]
Synopsis [Matrix multiplication functions.]
Description [External procedures included in this module:
Cudd_addMatrixMultiply()
Cudd_addTimesPlus()
Cudd_addTriangle()
Static procedures included in this module:
addMMRecur()
addTriangleRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 56 of file cuddMatMult.c.