cuddWindow.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define ABC 1
#define BAC 2
#define BCA 3
#define CBA 4
#define CAB 5
#define ACB 6
#define ABCD 1
#define BACD 7
#define BADC 13
#define ABDC 8
#define ADBC 14
#define ADCB 9
#define DACB 15
#define DABC 20
#define DBAC 23
#define BDAC 19
#define BDCA 21
#define DBCA 24
#define DCBA 22
#define DCAB 18
#define CDAB 12
#define CDBA 17
#define CBDA 11
#define BCDA 16
#define BCAD 10
#define CBAD 5
#define CABD 3
#define CADB 6
#define ACDB 4
#define ACBD 2
Functions
static int ddWindow2 ARGS ((DdManager *table, int low, int high))
static int ddPermuteWindow3 ARGS ((DdManager *table, int x))
static int ddPermuteWindow4 ARGS ((DdManager *table, int w))
int cuddWindowReorder (DdManager *table, int low, int high, Cudd_ReorderingType submethod)
static int ddWindow2 (DdManager *table, int low, int high)
static int ddWindowConv2 (DdManager *table, int low, int high)
static int ddPermuteWindow3 (DdManager *table, int x)
static int ddWindow3 (DdManager *table, int low, int high)
static int ddWindowConv3 (DdManager *table, int low, int high)
static int ddPermuteWindow4 (DdManager *table, int w)
static int ddWindow4 (DdManager *table, int low, int high)
static int ddWindowConv4 (DdManager *table, int low, int high)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddWindow.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define ABC 1
Referenced by ddPermuteWindow3(), ddWindow3(), and ddWindowConv3().
#define ABCD 1
Referenced by ddPermuteWindow4(), ddWindow4(), and ddWindowConv4().
#define ABDC 8
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define ACB 6
Referenced by ddPermuteWindow3(), and ddWindowConv3().
#define ACBD 2
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define ACDB 4
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define ADBC 14
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define ADCB 9
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BAC 2
Referenced by ddPermuteWindow3(), and ddWindowConv3().
#define BACD 7
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BADC 13
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BCA 3
Referenced by ddPermuteWindow3(), and ddWindowConv3().
#define BCAD 10
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BCDA 16
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BDAC 19
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define BDCA 21
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CAB 5
Referenced by ddPermuteWindow3(), and ddWindowConv3().
#define CABD 3
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CADB 6
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CBA 4
Referenced by ddPermuteWindow3(), and ddWindowConv3().
#define CBAD 5
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CBDA 11
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CDAB 12
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define CDBA 17
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DABC 20
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DACB 15
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DBAC 23
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DBCA 24
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DCAB 18
Referenced by ddPermuteWindow4(), and ddWindowConv4().
#define DCBA 22
Referenced by ddPermuteWindow4(), and ddWindowConv4().
Function Documentation
static int ddPermuteWindow4 ARGS ((DdManager *table, int w)) [static]
static int ddPermuteWindow3 ARGS ((DdManager *table, int x)) [static]
static int ddWindowConv4 ARGS ((DdManager *table, int low, int high)) [static]
AutomaticStart
int cuddWindowReorder (DdManager * table, int low, int high, Cudd_ReorderingType submethod)
Function********************************************************************
Synopsis [Reorders by applying the method of the sliding window.]
Description [Reorders by applying the method of the sliding window. Tries all possible permutations to the variables in a window that slides from low to high. The size of the window is determined by submethod. Assumes that no dead nodes are present. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 113 of file cuddWindow.c.
References CUDD_REORDER_WINDOW2, CUDD_REORDER_WINDOW2_CONV, CUDD_REORDER_WINDOW3, CUDD_REORDER_WINDOW3_CONV, CUDD_REORDER_WINDOW4, CUDD_REORDER_WINDOW4_CONV, ddWindow2(), ddWindow3(), ddWindow4(), ddWindowConv2(), ddWindowConv3(), ddWindowConv4(), DdManager::isolated, and DdManager::keys.
Referenced by ddReorderChildren().
static int ddPermuteWindow3 (DdManager * table, int x) [static]
Function********************************************************************
Synopsis [Tries all the permutations of the three variables between x and x+2 and retains the best.]
Description [Tries all the permutations of the three variables between x and x+2 and retains the best. Assumes that no dead nodes are present. Returns the index of the best permutation (1-6) in case of success; 0 otherwise.Assumes that no dead nodes are present. Returns the index of the best permutation (1-6) in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 329 of file cuddWindow.c.
References ABC, ACB, assert, BAC, BCA, CAB, CBA, cuddSwapInPlace(), DdManager::dead, DdManager::isolated, DdManager::keys, DdManager::size, and size.
Referenced by ddWindow3(), and ddWindowConv3().
static int ddPermuteWindow4 (DdManager * table, int w) [static]
Function********************************************************************
Synopsis [Tries all the permutations of the four variables between w and w+3 and retains the best.]
Description [Tries all the permutations of the four variables between w and w+3 and retains the best. Assumes that no dead nodes are present. Returns the index of the best permutation (1-24) in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 566 of file cuddWindow.c.
References ABCD, ABDC, ACBD, ACDB, ADBC, ADCB, assert, BACD, BADC, BCAD, BCDA, BDAC, BDCA, CABD, CADB, CBAD, CBDA, CDAB, CDBA, cuddSwapInPlace(), DABC, DACB, DBAC, DBCA, DCAB, DCBA, DdManager::dead, DdManager::isolated, DdManager::keys, DdManager::size, and size.
Referenced by ddWindow4(), and ddWindowConv4().
static int ddWindow2 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by applying a sliding window of width 2.]
Description [Reorders by applying a sliding window of width 2. Tries both permutations of the variables in a window that slides from low to high. Assumes that no dead nodes are present. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 185 of file cuddWindow.c.
References assert, cuddSwapInPlace(), DdManager::isolated, DdManager::keys, and size.
Referenced by cuddWindowReorder(), and ddWindow3().
static int ddWindow3 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by applying a sliding window of width 3.]
Description [Reorders by applying a sliding window of width 3. Tries all possible permutations to the variables in a window that slides from low to high. Assumes that no dead nodes are present. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 424 of file cuddWindow.c.
References ABC, assert, ddPermuteWindow3(), ddWindow2(), and size.
Referenced by cuddWindowReorder(), and ddWindow4().
static int ddWindow4 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by applying a sliding window of width 4.]
Description [Reorders by applying a sliding window of width 4. Tries all possible permutations to the variables in a window that slides from low to high. Assumes that no dead nodes are present. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 822 of file cuddWindow.c.
References ABCD, assert, ddPermuteWindow4(), ddWindow3(), and size.
Referenced by cuddWindowReorder().
static int ddWindowConv2 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by repeatedly applying a sliding window of width 2.]
Description [Reorders by repeatedly applying a sliding window of width 2. Tries both permutations of the variables in a window that slides from low to high. Assumes that no dead nodes are present. Uses an event-driven approach to determine convergence. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 239 of file cuddWindow.c.
References ALLOC, assert, CUDD_MEMORY_OUT, cuddSwapInPlace(), DdManager::errorCode, FREE, DdManager::isolated, DdManager::keys, and size.
Referenced by cuddWindowReorder(), and ddWindowConv3().
static int ddWindowConv3 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by repeatedly applying a sliding window of width 3.]
Description [Reorders by repeatedly applying a sliding window of width 3. Tries all possible permutations to the variables in a window that slides from low to high. Assumes that no dead nodes are present. Uses an event-driven approach to determine convergence. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 471 of file cuddWindow.c.
References ABC, ACB, ALLOC, assert, BAC, BCA, CAB, CBA, CUDD_MEMORY_OUT, ddPermuteWindow3(), ddWindowConv2(), DdManager::errorCode, FREE, and size.
Referenced by cuddWindowReorder(), and ddWindowConv4().
static int ddWindowConv4 (DdManager * table, int low, int high) [static]
Function********************************************************************
Synopsis [Reorders by repeatedly applying a sliding window of width 4.]
Description [Reorders by repeatedly applying a sliding window of width 4. Tries all possible permutations to the variables in a window that slides from low to high. Assumes that no dead nodes are present. Uses an event-driven approach to determine convergence. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 869 of file cuddWindow.c.
References ABCD, ABDC, ACBD, ACDB, ADBC, ADCB, ALLOC, assert, BACD, BADC, BCAD, BCDA, BDAC, BDCA, CABD, CADB, CBAD, CBDA, CDAB, CDBA, CUDD_MEMORY_OUT, DABC, DACB, DBAC, DBCA, DCAB, DCBA, ddPermuteWindow4(), ddWindowConv3(), DdManager::errorCode, FREE, and size.
Referenced by cuddWindowReorder().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddWindow.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddWindow.c]
PackageName [cudd]
Synopsis [Functions for window permutation]
Description [Internal procedures included in this module:
cuddWindowReorder()
Static procedures included in this module:
ddWindow2()
ddWindowConv2()
ddPermuteWindow3()
ddWindow3()
ddWindowConv3()
ddPermuteWindow4()
ddWindow4()
ddWindowConv4()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 59 of file cuddWindow.c.