cuddSolve.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_SolveEqn (DdManager *bdd, DdNode *F, DdNode *Y, DdNode **G, int **yIndex, int n)
DdNode * Cudd_VerifySol (DdManager *bdd, DdNode *F, DdNode **G, int *yIndex, int n)
DdNode * cuddSolveEqnRecur (DdManager *bdd, DdNode *F, DdNode *Y, DdNode **G, int n, int *yIndex, int i)
DdNode * cuddVerifySol (DdManager *bdd, DdNode *F, DdNode **G, int *yIndex, int n)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddSolve.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_SolveEqn (DdManager * bdd, DdNode * F, DdNode * Y, DdNode ** G, int ** yIndex, int n)
Function********************************************************************
Synopsis [Implements the solution of F(x,y) = 0.]
Description [Implements the solution for F(x,y) = 0. The return value is the consistency condition. The y variables are the unknowns and the remaining variables are the parameters. Returns the consistency condition if successful; NULL otherwise. Cudd_SolveEqn allocates an array and fills it with the indices of the unknowns. This array is used by Cudd_VerifySol.]
SideEffects [The solution is returned in G; the indices of the y variables are returned in yIndex.]
SeeAlso [Cudd_VerifySol]
Definition at line 97 of file cuddSolve.c.
References ALLOC, CUDD_MEMORY_OUT, cuddSolveEqnRecur(), DdManager::errorCode, and DdManager::reordered.
DdNode* Cudd_VerifySol (DdManager * bdd, DdNode * F, DdNode ** G, int * yIndex, int n)
Function********************************************************************
Synopsis [Checks the solution of F(x,y) = 0.]
Description [Checks the solution of F(x,y) = 0. This procedure substitutes the solution components for the unknowns of F and returns the resulting BDD for F.]
SideEffects [Frees the memory pointed by yIndex.]
SeeAlso [Cudd_SolveEqn]
Definition at line 139 of file cuddSolve.c.
References cuddVerifySol(), FREE, and DdManager::reordered.
DdNode* cuddSolveEqnRecur (DdManager * bdd, DdNode * F, DdNode * Y, DdNode ** G, int n, int * yIndex, int i)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_SolveEqn.]
Description [Implements the recursive step of Cudd_SolveEqn. Returns NULL if the intermediate solution blows up or reordering occurs. The parametric solutions are stored in the array G.]
SideEffects [none]
SeeAlso [Cudd_SolveEqn, Cudd_VerifySol]
Definition at line 180 of file cuddSolve.c.
References Cudd_Deref(), Cudd_Not, Cudd_RecursiveDeref(), Cudd_T, cuddBddComposeRecur(), cuddBddExistAbstractRecur(), cuddBddIteRecur(), cuddBddRestrictRecur(), cuddCofactorRecur(), cuddRef, DD_ONE, DdNode::index, one, and DdManager::vars.
Referenced by Cudd_SolveEqn().
DdNode* cuddVerifySol (DdManager * bdd, DdNode * F, DdNode ** G, int * yIndex, int n)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_VerifySol. ]
Description []
SideEffects [none]
SeeAlso [Cudd_VerifySol]
Definition at line 312 of file cuddSolve.c.
References Cudd_bddCompose(), Cudd_RecursiveDeref(), cuddDeref, and cuddRef.
Referenced by Cudd_VerifySol().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddSolve.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddSolve.c]
PackageName [cudd]
Synopsis [Boolean equation solver and related functions.]
Description [External functions included in this modoule:
Cudd_SolveEqn()
Cudd_VerifySol()
Internal functions included in this module:
cuddSolveEqnRecur()
cuddVerifySol()
]
SeeAlso []
Author [Balakrishna Kumthekar]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 56 of file cuddSolve.c.