cuddAPI.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static void fixVarTree ARGS ((MtrNode *treenode, int *perm, int size))
DdNode * Cudd_addNewVar (DdManager *dd)
DdNode * Cudd_addNewVarAtLevel (DdManager *dd, int level)
DdNode * Cudd_bddNewVar (DdManager *dd)
DdNode * Cudd_bddNewVarAtLevel (DdManager *dd, int level)
DdNode * Cudd_addIthVar (DdManager *dd, int i)
DdNode * Cudd_bddIthVar (DdManager *dd, int i)
DdNode * Cudd_zddIthVar (DdManager *dd, int i)
int Cudd_zddVarsFromBddVars (DdManager *dd, int multiplicity)
DdNode * Cudd_addConst (DdManager *dd, CUDD_VALUE_TYPE c)
void Cudd_AutodynEnable (DdManager *unique, Cudd_ReorderingType method)
void Cudd_AutodynDisable (DdManager *unique)
int Cudd_ReorderingStatus (DdManager *unique, Cudd_ReorderingType *method)
void Cudd_AutodynEnableZdd (DdManager *unique, Cudd_ReorderingType method)
void Cudd_AutodynDisableZdd (DdManager *unique)
int Cudd_ReorderingStatusZdd (DdManager *unique, Cudd_ReorderingType *method)
int Cudd_zddRealignmentEnabled (DdManager *unique)
void Cudd_zddRealignEnable (DdManager *unique)
void Cudd_zddRealignDisable (DdManager *unique)
int Cudd_bddRealignmentEnabled (DdManager *unique)
void Cudd_bddRealignEnable (DdManager *unique)
void Cudd_bddRealignDisable (DdManager *unique)
DdNode * Cudd_ReadOne (DdManager *dd)
DdNode * Cudd_ReadZddOne (DdManager *dd, int i)
DdNode * Cudd_ReadZero (DdManager *dd)
DdNode * Cudd_ReadLogicZero (DdManager *dd)
DdNode * Cudd_ReadPlusInfinity (DdManager *dd)
DdNode * Cudd_ReadMinusInfinity (DdManager *dd)
DdNode * Cudd_ReadBackground (DdManager *dd)
void Cudd_SetBackground (DdManager *dd, DdNode *bck)
unsigned int Cudd_ReadCacheSlots (DdManager *dd)
double Cudd_ReadCacheUsedSlots (DdManager *dd)
double Cudd_ReadCacheLookUps (DdManager *dd)
double Cudd_ReadCacheHits (DdManager *dd)
unsigned int Cudd_ReadMinHit (DdManager *dd)
void Cudd_SetMinHit (DdManager *dd, unsigned int hr)
unsigned int Cudd_ReadLooseUpTo (DdManager *dd)
void Cudd_SetLooseUpTo (DdManager *dd, unsigned int lut)
unsigned int Cudd_ReadMaxCache (DdManager *dd)
void Cudd_SetMaxCache (DdManager *dd, unsigned int mc)
unsigned int Cudd_ReadMaxCacheHard (DdManager *dd)
void Cudd_SetMaxCacheHard (DdManager *dd, unsigned int mc)
int Cudd_ReadSize (DdManager *dd)
int Cudd_ReadZddSize (DdManager *dd)
unsigned int Cudd_ReadSlots (DdManager *dd)
double Cudd_ReadUsedSlots (DdManager *dd)
unsigned int Cudd_ReadKeys (DdManager *dd)
unsigned int Cudd_ReadDead (DdManager *dd)
unsigned int Cudd_ReadMinDead (DdManager *dd)
int Cudd_ReadReorderings (DdManager *dd)
long Cudd_ReadReorderingTime (DdManager *dd)
int Cudd_ReadGarbageCollections (DdManager *dd)
long Cudd_ReadGarbageCollectionTime (DdManager *dd)
double Cudd_ReadNodesFreed (DdManager *dd)
double Cudd_ReadNodesDropped (DdManager *dd)
double Cudd_ReadUniqueLookUps (DdManager *dd)
double Cudd_ReadUniqueLinks (DdManager *dd)
int Cudd_ReadSiftMaxVar (DdManager *dd)
void Cudd_SetSiftMaxVar (DdManager *dd, int smv)
int Cudd_ReadSiftMaxSwap (DdManager *dd)
void Cudd_SetSiftMaxSwap (DdManager *dd, int sms)
double Cudd_ReadMaxGrowth (DdManager *dd)
void Cudd_SetMaxGrowth (DdManager *dd, double mg)
MtrNode * Cudd_ReadTree (DdManager *dd)
void Cudd_SetTree (DdManager *dd, MtrNode *tree)
void Cudd_FreeTree (DdManager *dd)
MtrNode * Cudd_ReadZddTree (DdManager *dd)
void Cudd_SetZddTree (DdManager *dd, MtrNode *tree)
void Cudd_FreeZddTree (DdManager *dd)
unsigned int Cudd_NodeReadIndex (DdNode *node)
int Cudd_ReadPerm (DdManager *dd, int i)
int Cudd_ReadPermZdd (DdManager *dd, int i)
int Cudd_ReadInvPerm (DdManager *dd, int i)
int Cudd_ReadInvPermZdd (DdManager *dd, int i)
DdNode * Cudd_ReadVars (DdManager *dd, int i)
CUDD_VALUE_TYPE Cudd_ReadEpsilon (DdManager *dd)
void Cudd_SetEpsilon (DdManager *dd, CUDD_VALUE_TYPE ep)
Cudd_AggregationType Cudd_ReadGroupcheck (DdManager *dd)
void Cudd_SetGroupcheck (DdManager *dd, Cudd_AggregationType gc)
int Cudd_GarbageCollectionEnabled (DdManager *dd)
void Cudd_EnableGarbageCollection (DdManager *dd)
void Cudd_DisableGarbageCollection (DdManager *dd)
int Cudd_DeadAreCounted (DdManager *dd)
void Cudd_TurnOnCountDead (DdManager *dd)
void Cudd_TurnOffCountDead (DdManager *dd)
int Cudd_ReadRecomb (DdManager *dd)
void Cudd_SetRecomb (DdManager *dd, int recomb)
int Cudd_ReadSymmviolation (DdManager *dd)
void Cudd_SetSymmviolation (DdManager *dd, int symmviolation)
int Cudd_ReadArcviolation (DdManager *dd)
void Cudd_SetArcviolation (DdManager *dd, int arcviolation)
int Cudd_ReadPopulationSize (DdManager *dd)
void Cudd_SetPopulationSize (DdManager *dd, int populationSize)
int Cudd_ReadNumberXovers (DdManager *dd)
void Cudd_SetNumberXovers (DdManager *dd, int numberXovers)
long Cudd_ReadMemoryInUse (DdManager *dd)
int Cudd_PrintInfo (DdManager *dd, FILE *fp)
long Cudd_ReadPeakNodeCount (DdManager *dd)
long Cudd_ReadNodeCount (DdManager *dd)
long Cudd_zddReadNodeCount (DdManager *dd)
int Cudd_AddHook (DdManager *dd, int(*f)(DdManager *, void *), Cudd_HookType where)
int Cudd_RemoveHook (DdManager *dd, int(*f)(DdManager *, void *), Cudd_HookType where)
int Cudd_IsInHook (DdManager *dd, int(*f)(DdManager *, void *), Cudd_HookType where)
int Cudd_StdPreReordHook (DdManager *dd, void *data)
int Cudd_StdPostReordHook (DdManager *dd, void *data)
int Cudd_EnableReorderingReporting (DdManager *dd)
int Cudd_DisableReorderingReporting (DdManager *dd)
int Cudd_ReorderingReporting (DdManager *dd)
Cudd_ErrorType Cudd_ReadErrorCode (DdManager *dd)
void Cudd_ClearErrorCode (DdManager *dd)
static void fixVarTree (MtrNode *treenode, int *perm, int size)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAPI.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static void fixVarTree ARGS ((MtrNode *treenode, int *perm, int size)) [static]
AutomaticStart
DdNode* Cudd_addConst (DdManager * dd, CUDD_VALUE_TYPE c)
Function********************************************************************
Synopsis [Returns the ADD for constant c.]
Description [Retrieves the ADD for constant c if it already exists, or creates a new ADD. Returns a pointer to the ADD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addNewVar Cudd_addIthVar]
Definition at line 532 of file cuddAPI.c.
References cuddUniqueConst().
int Cudd_AddHook (DdManager * dd, int(*)(DdManager *, void *) f, Cudd_HookType where)
Function********************************************************************
Synopsis [Adds a function to a hook.]
Description [Adds a function to a hook. A hook is a list of application-provided functions called on certain occasions by the package. Returns 1 if the function is successfully added; 2 if the function was already in the list; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_RemoveHook]
Definition at line 2904 of file cuddAPI.c.
References ALLOC, CUDD_MEMORY_OUT, CUDD_POST_GC_HOOK, CUDD_POST_REORDERING_HOOK, CUDD_PRE_GC_HOOK, CUDD_PRE_REORDERING_HOOK, DdManager::errorCode, DdHook::next, DdManager::postGCHook, DdManager::postReorderingHook, DdManager::preGCHook, and DdManager::preReorderingHook.
Referenced by Cudd_EnableReorderingReporting().
DdNode* Cudd_addIthVar (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the ADD variable with index i.]
Description [Retrieves the ADD variable with index i if it already exists, or creates a new ADD variable. Returns a pointer to the variable if successful; NULL otherwise. An ADD variable differs from a BDD variable because it points to the arithmetic zero, instead of having a complement pointer to 1. ]
SideEffects [None]
SeeAlso [Cudd_addNewVar Cudd_bddIthVar Cudd_addConst Cudd_addNewVarAtLevel]
Definition at line 314 of file cuddAPI.c.
References CUDD_MAXINDEX, cuddUniqueInter(), DD_ONE, DD_ZERO, and DdManager::reordered.
Referenced by Cudd_addNewVarAtLevel(), Cudd_addNonSimCompose(), and cuddAddNonSimComposeRecur().
DdNode* Cudd_addNewVar (DdManager * dd)
Function********************************************************************
Synopsis [Returns a new ADD variable.]
Description [Creates a new ADD variable. The new variable has an index equal to the largest previous index plus 1. Returns a pointer to the new variable if successful; NULL otherwise. An ADD variable differs from a BDD variable because it points to the arithmetic zero, instead of having a complement pointer to 1. ]
SideEffects [None]
SeeAlso [Cudd_bddNewVar Cudd_addIthVar Cudd_addConst Cudd_addNewVarAtLevel]
Definition at line 189 of file cuddAPI.c.
References CUDD_MAXINDEX, cuddUniqueInter(), DD_ONE, DD_ZERO, DdManager::reordered, and DdManager::size.
DdNode* Cudd_addNewVarAtLevel (DdManager * dd, int level)
Function********************************************************************
Synopsis [Returns a new ADD variable at a specified level.]
Description [Creates a new ADD variable. The new variable has an index equal to the largest previous index plus 1 and is positioned at the specified level in the order. Returns a pointer to the new variable if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addNewVar Cudd_addIthVar Cudd_bddNewVarAtLevel]
Definition at line 220 of file cuddAPI.c.
References Cudd_addIthVar(), CUDD_MAXINDEX, cuddInsertSubtables(), cuddUniqueInter(), DD_ONE, DD_ZERO, DdManager::reordered, and DdManager::size.
void Cudd_AutodynDisable (DdManager * unique)
Function********************************************************************
Synopsis [Disables automatic dynamic reordering.]
Description []
SideEffects [None]
SeeAlso [Cudd_AutodynEnable Cudd_ReorderingStatus Cudd_AutodynDisableZdd]
Definition at line 583 of file cuddAPI.c.
References DdManager::autoDyn.
void Cudd_AutodynDisableZdd (DdManager * unique)
Function********************************************************************
Synopsis [Disables automatic dynamic reordering of ZDDs.]
Description []
SideEffects [None]
SeeAlso [Cudd_AutodynEnableZdd Cudd_ReorderingStatusZdd Cudd_AutodynDisable]
Definition at line 661 of file cuddAPI.c.
References DdManager::autoDynZ.
void Cudd_AutodynEnable (DdManager * unique, Cudd_ReorderingType method)
Function********************************************************************
Synopsis [Enables automatic dynamic reordering of BDDs and ADDs.]
Description [Enables automatic dynamic reordering of BDDs and ADDs. Parameter method is used to determine the method used for reordering. If CUDD_REORDER_SAME is passed, the method is unchanged.]
SideEffects [None]
SeeAlso [Cudd_AutodynDisable Cudd_ReorderingStatus Cudd_AutodynEnableZdd]
Definition at line 557 of file cuddAPI.c.
References DdManager::autoDyn, DdManager::autoMethod, and CUDD_REORDER_SAME.
void Cudd_AutodynEnableZdd (DdManager * unique, Cudd_ReorderingType method)
Function********************************************************************
Synopsis [Enables automatic dynamic reordering of ZDDs.]
Description [Enables automatic dynamic reordering of ZDDs. Parameter method is used to determine the method used for reordering ZDDs. If CUDD_REORDER_SAME is passed, the method is unchanged.]
SideEffects [None]
SeeAlso [Cudd_AutodynDisableZdd Cudd_ReorderingStatusZdd Cudd_AutodynEnable]
Definition at line 635 of file cuddAPI.c.
References DdManager::autoDynZ, DdManager::autoMethodZ, and CUDD_REORDER_SAME.
DdNode* Cudd_bddIthVar (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the BDD variable with index i.]
Description [Retrieves the BDD variable with index i if it already exists, or creates a new BDD variable. Returns a pointer to the variable if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddNewVar Cudd_addIthVar Cudd_bddNewVarAtLevel]
Definition at line 345 of file cuddAPI.c.
References CUDD_MAXINDEX, Cudd_Not, cuddUniqueInter(), DdManager::one, size, and DdManager::vars.
Referenced by Cudd_bddNewVarAtLevel(), Cudd_bddVarConjDecomp(), and Cudd_IndicesToCube().
DdNode* Cudd_bddNewVar (DdManager * dd)
Function********************************************************************
Synopsis [Returns a new BDD variable.]
Description [Creates a new BDD variable. The new variable has an index equal to the largest previous index plus 1. Returns a pointer to the new variable if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addNewVar Cudd_bddIthVar Cudd_bddNewVarAtLevel]
Definition at line 253 of file cuddAPI.c.
References CUDD_MAXINDEX, Cudd_Not, cuddUniqueInter(), DdManager::one, and DdManager::size.
DdNode* Cudd_bddNewVarAtLevel (DdManager * dd, int level)
Function********************************************************************
Synopsis [Returns a new BDD variable at a specified level.]
Description [Creates a new BDD variable. The new variable has an index equal to the largest previous index plus 1 and is positioned at the specified level in the order. Returns a pointer to the new variable if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddNewVar Cudd_bddIthVar Cudd_addNewVarAtLevel]
Definition at line 281 of file cuddAPI.c.
References Cudd_bddIthVar(), CUDD_MAXINDEX, cuddInsertSubtables(), DdManager::size, and DdManager::vars.
void Cudd_bddRealignDisable (DdManager * unique)
Function********************************************************************
Synopsis [Disables realignment of ZDD order to BDD order.]
Description []
SideEffects [None]
SeeAlso [Cudd_bddRealignEnable Cudd_bddRealignmentEnabled Cudd_zddRealignEnable Cudd_zddRealignmentEnabled]
Definition at line 840 of file cuddAPI.c.
References DdManager::realignZ.
void Cudd_bddRealignEnable (DdManager * unique)
Function********************************************************************
Synopsis [Enables realignment of BDD order to ZDD order.]
Description [Enables realignment of the BDD variable order to the ZDD variable order after the ZDDs have been reordered. The number of ZDD variables must be a multiple of the number of BDD variables for realignment to make sense. If this condition is not met, Cudd_zddReduceHeap will return 0. Let M be the ratio of the two numbers. For the purpose of realignment, the ZDD variables from M*i to (M+1)*i-1 are reagarded as corresponding to BDD variable i. Realignment is initially disabled.]
SideEffects [None]
SeeAlso [Cudd_zddReduceHeap Cudd_bddRealignDisable Cudd_bddRealignmentEnabled Cudd_zddRealignDisable Cudd_zddRealignmentEnabled]
Definition at line 818 of file cuddAPI.c.
References DdManager::realignZ.
int Cudd_bddRealignmentEnabled (DdManager * unique)
Function********************************************************************
Synopsis [Tells whether the realignment of BDD order to ZDD order is enabled.]
Description [Returns 1 if the realignment of BDD order to ZDD order is enabled; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddRealignEnable Cudd_bddRealignDisable Cudd_zddRealignEnable Cudd_zddRealignDisable]
Definition at line 788 of file cuddAPI.c.
References DdManager::realignZ.
Referenced by Cudd_PrintInfo().
void Cudd_ClearErrorCode (DdManager * dd)
Function********************************************************************
Synopsis [Clear the error code of a manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadErrorCode]
Definition at line 3283 of file cuddAPI.c.
References CUDD_NO_ERROR, and DdManager::errorCode.
int Cudd_DeadAreCounted (DdManager * dd)
Function********************************************************************
Synopsis [Tells whether dead nodes are counted towards triggering reordering.]
Description [Tells whether dead nodes are counted towards triggering reordering. Returns 1 if dead nodes are counted; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_TurnOnCountDead Cudd_TurnOffCountDead]
Definition at line 2288 of file cuddAPI.c.
References DdManager::countDead.
Referenced by Cudd_PrintInfo().
void Cudd_DisableGarbageCollection (DdManager * dd)
Function********************************************************************
Synopsis [Disables garbage collection.]
Description [Disables garbage collection. Garbage collection is initially enabled. This function may be called to disable it. However, garbage collection will still occur when a new node must be created and no memory is left, or when garbage collection is required for correctness. (E.g., before reordering.)]
SideEffects [None]
SeeAlso [Cudd_EnableGarbageCollection Cudd_GarbageCollectionEnabled]
Definition at line 2266 of file cuddAPI.c.
References DdManager::gcEnabled.
int Cudd_DisableReorderingReporting (DdManager * dd)
Function********************************************************************
Synopsis [Disables reporting of reordering stats.]
Description [Disables reporting of reordering stats. Returns 1 if successful; 0 otherwise.]
SideEffects [Removes functions from the pre-reordering and post-reordering hooks.]
SeeAlso [Cudd_EnableReorderingReporting Cudd_ReorderingReporting]
Definition at line 3215 of file cuddAPI.c.
References CUDD_POST_REORDERING_HOOK, CUDD_PRE_REORDERING_HOOK, Cudd_RemoveHook(), Cudd_StdPostReordHook(), and Cudd_StdPreReordHook().
void Cudd_EnableGarbageCollection (DdManager * dd)
Function********************************************************************
Synopsis [Enables garbage collection.]
Description [Enables garbage collection. Garbage collection is initially enabled. Therefore it is necessary to call this function only if garbage collection has been explicitly disabled.]
SideEffects [None]
SeeAlso [Cudd_DisableGarbageCollection Cudd_GarbageCollectionEnabled]
Definition at line 2242 of file cuddAPI.c.
References DdManager::gcEnabled.
int Cudd_EnableReorderingReporting (DdManager * dd)
Function********************************************************************
Synopsis [Enables reporting of reordering stats.]
Description [Enables reporting of reordering stats. Returns 1 if successful; 0 otherwise.]
SideEffects [Installs functions in the pre-reordering and post-reordering hooks.]
SeeAlso [Cudd_DisableReorderingReporting Cudd_ReorderingReporting]
Definition at line 3187 of file cuddAPI.c.
References Cudd_AddHook(), CUDD_POST_REORDERING_HOOK, CUDD_PRE_REORDERING_HOOK, Cudd_StdPostReordHook(), and Cudd_StdPreReordHook().
void Cudd_FreeTree (DdManager * dd)
Function********************************************************************
Synopsis [Frees the variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetTree Cudd_ReadTree Cudd_FreeZddTree]
Definition at line 1885 of file cuddAPI.c.
References Mtr_FreeTree(), and DdManager::tree.
void Cudd_FreeZddTree (DdManager * dd)
Function********************************************************************
Synopsis [Frees the variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetZddTree Cudd_ReadZddTree Cudd_FreeTree]
Definition at line 1957 of file cuddAPI.c.
References Mtr_FreeTree(), and DdManager::treeZ.
Referenced by Cudd_zddVarsFromBddVars().
int Cudd_GarbageCollectionEnabled (DdManager * dd)
Function********************************************************************
Synopsis [Tells whether garbage collection is enabled.]
Description [Returns 1 if garbage collection is enabled; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_EnableGarbageCollection Cudd_DisableGarbageCollection]
Definition at line 2220 of file cuddAPI.c.
References DdManager::gcEnabled.
Referenced by Cudd_PrintInfo().
int Cudd_IsInHook (DdManager * dd, int(*)(DdManager *, void *) f, Cudd_HookType where)
Function********************************************************************
Synopsis [Checks whether a function is in a hook.]
Description [Checks whether a function is in a hook. A hook is a list of application-provided functions called on certain occasions by the package. Returns 1 if the function is found; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_AddHook Cudd_RemoveHook]
Definition at line 3019 of file cuddAPI.c.
References CUDD_POST_GC_HOOK, CUDD_POST_REORDERING_HOOK, CUDD_PRE_GC_HOOK, CUDD_PRE_REORDERING_HOOK, DdHook::next, DdManager::postGCHook, DdManager::postReorderingHook, DdManager::preGCHook, and DdManager::preReorderingHook.
Referenced by Cudd_ReorderingReporting().
unsigned int Cudd_NodeReadIndex (DdNode * node)
Function********************************************************************
Synopsis [Returns the index of the node.]
Description [Returns the index of the node. The node pointer can be either regular or complemented.]
SideEffects [None]
SeeAlso [Cudd_ReadIndex]
Definition at line 1982 of file cuddAPI.c.
References Cudd_Regular, and DdGen::node.
Referenced by BuildSubsetBdd().
int Cudd_PrintInfo (DdManager * dd, FILE * fp)
Function********************************************************************
Synopsis [Prints out statistics and settings for a CUDD manager.]
Description [Prints out statistics and settings for a CUDD manager. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 2640 of file cuddAPI.c.
References DdManager::allocated, DdManager::cachecollisions, DdManager::cachedeletions, DdManager::cacheinserts, DdManager::cacheSlots, Cudd_bddRealignmentEnabled(), Cudd_DeadAreCounted(), Cudd_GarbageCollectionEnabled(), Cudd_ReadArcviolation(), Cudd_ReadCacheHits(), Cudd_ReadCacheLookUps(), Cudd_ReadGarbageCollections(), Cudd_ReadGarbageCollectionTime(), Cudd_ReadGroupcheck(), Cudd_ReadLooseUpTo(), Cudd_ReadMaxCacheHard(), Cudd_ReadMaxGrowth(), Cudd_ReadMemoryInUse(), Cudd_ReadMinHit(), Cudd_ReadNumberXovers(), Cudd_ReadPeakNodeCount(), Cudd_ReadPopulationSize(), Cudd_ReadRecomb(), Cudd_ReadReorderingTime(), Cudd_ReadSiftMaxSwap(), Cudd_ReadSiftMaxVar(), Cudd_ReadSymmviolation(), Cudd_ReadUsedSlots(), Cudd_ReorderingStatus(), Cudd_ReorderingStatusZdd(), Cudd_zddRealignmentEnabled(), cuddCacheProfile(), DdManager::dead, DdManager::deadZ, DdManager::keys, DdManager::keysZ, DdManager::maxCache, DdManager::reclaimed, DdManager::size, DdManager::sizeZ, and DdManager::slots.
int Cudd_ReadArcviolation (DdManager * dd)
Function********************************************************************
Synopsis [Returns the current value of the arcviolation parameter used in group sifting.]
Description [Returns the current value of the arcviolation parameter. This parameter is used in group sifting to decide how many arcs into y not coming from x are tolerable when checking for aggregation due to extended symmetry. The value should be between 0 and 100. A small value causes fewer variables to be aggregated. The default value is 0.]
SideEffects [None]
SeeAlso [Cudd_SetArcviolation]
Definition at line 2467 of file cuddAPI.c.
References DdManager::arcviolation.
Referenced by Cudd_PrintInfo().
DdNode* Cudd_ReadBackground (DdManager * dd)
Function********************************************************************
Synopsis [Reads the background constant of the manager.]
Description []
SideEffects [None]
Definition at line 987 of file cuddAPI.c.
References DdManager::background.
double Cudd_ReadCacheHits (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of cache hits.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadCacheLookUps]
Definition at line 1100 of file cuddAPI.c.
References DdManager::cacheHits, and DdManager::totCachehits.
Referenced by Cudd_PrintInfo().
double Cudd_ReadCacheLookUps (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of cache look-ups.]
Description [Returns the number of cache look-ups.]
SideEffects [None]
SeeAlso [Cudd_ReadCacheHits]
Definition at line 1079 of file cuddAPI.c.
References DdManager::cacheHits, DdManager::cacheMisses, DdManager::totCachehits, and DdManager::totCacheMisses.
Referenced by Cudd_PrintInfo().
unsigned int Cudd_ReadCacheSlots (DdManager * dd)
Function********************************************************************
Synopsis [Reads the number of slots in the cache.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadCacheUsedSlots]
Definition at line 1027 of file cuddAPI.c.
References DdManager::cacheSlots.
double Cudd_ReadCacheUsedSlots (DdManager * dd)
Function********************************************************************
Synopsis [Reads the fraction of used slots in the cache.]
Description [Reads the fraction of used slots in the cache. The unused slots are those in which no valid data is stored. Garbage collection, variable reordering, and cache resizing may cause used slots to become unused.]
SideEffects [None]
SeeAlso [Cudd_ReadCacheSlots]
Definition at line 1050 of file cuddAPI.c.
References DdManager::cache, and DdManager::cacheSlots.
unsigned int Cudd_ReadDead (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of dead nodes in the unique table.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadKeys]
Definition at line 1451 of file cuddAPI.c.
References DdManager::dead.
CUDD_VALUE_TYPE Cudd_ReadEpsilon (DdManager * dd)
Function********************************************************************
Synopsis [Reads the epsilon parameter of the manager.]
Description [Reads the epsilon parameter of the manager. The epsilon parameter control the comparison between floating point numbers.]
SideEffects [None]
SeeAlso [Cudd_SetEpsilon]
Definition at line 2133 of file cuddAPI.c.
References DdManager::epsilon.
Cudd_ErrorType Cudd_ReadErrorCode (DdManager * dd)
Function********************************************************************
Synopsis [Returns the code of the last error.]
Description [Returns the code of the last error. The error codes are defined in cudd.h.]
SideEffects [None]
SeeAlso [Cudd_ClearErrorCode]
Definition at line 3263 of file cuddAPI.c.
References DdManager::errorCode.
int Cudd_ReadGarbageCollections (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of times garbage collection has occurred.]
Description [Returns the number of times garbage collection has occurred in the manager. The number includes both the calls from reordering procedures and those caused by requests to create new nodes.]
SideEffects [None]
SeeAlso [Cudd_ReadGarbageCollectionTime]
Definition at line 1546 of file cuddAPI.c.
References DdManager::garbageCollections.
Referenced by Cudd_PrintInfo().
long Cudd_ReadGarbageCollectionTime (DdManager * dd)
Function********************************************************************
Synopsis [Returns the time spent in garbage collection.]
Description [Returns the number of milliseconds spent doing garbage collection since the manager was initialized.]
SideEffects [None]
SeeAlso [Cudd_ReadGarbageCollections]
Definition at line 1567 of file cuddAPI.c.
References DdManager::GCTime.
Referenced by Cudd_PrintInfo().
Cudd_AggregationType Cudd_ReadGroupcheck (DdManager * dd)
Function********************************************************************
Synopsis [Reads the groupcheck parameter of the manager.]
Description [Reads the groupcheck parameter of the manager. The groupcheck parameter determines the aggregation criterion in group sifting.]
SideEffects [None]
SeeAlso [Cudd_SetGroupcheck]
Definition at line 2177 of file cuddAPI.c.
References DdManager::groupcheck.
Referenced by Cudd_PrintInfo().
int Cudd_ReadInvPerm (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the index of the variable currently in the i-th position of the order.]
Description [Returns the index of the variable currently in the i-th position of the order. If the index is CUDD_MAXINDEX, returns CUDD_MAXINDEX; otherwise, if the index is out of bounds returns -1.]
SideEffects [None]
SeeAlso [Cudd_ReadPerm Cudd_ReadInvPermZdd]
Definition at line 2057 of file cuddAPI.c.
References CUDD_MAXINDEX, DdManager::invperm, and DdManager::size.
int Cudd_ReadInvPermZdd (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the index of the ZDD variable currently in the i-th position of the order.]
Description [Returns the index of the ZDD variable currently in the i-th position of the order. If the index is CUDD_MAXINDEX, returns CUDD_MAXINDEX; otherwise, if the index is out of bounds returns -1.]
SideEffects [None]
SeeAlso [Cudd_ReadPerm Cudd_ReadInvPermZdd]
Definition at line 2083 of file cuddAPI.c.
References CUDD_MAXINDEX, DdManager::invpermZ, and DdManager::sizeZ.
unsigned int Cudd_ReadKeys (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of nodes in the unique table.]
Description [Returns the total number of nodes currently in the unique table, including the dead nodes.]
SideEffects [None]
SeeAlso [Cudd_ReadDead]
Definition at line 1431 of file cuddAPI.c.
References DdManager::keys.
DdNode* Cudd_ReadLogicZero (DdManager * dd)
Function********************************************************************
Synopsis [Returns the logic zero constant of the manager.]
Description [Returns the zero constant of the manager. The logic zero constant is the complement of the one constant, and is distinct from the arithmetic zero.]
SideEffects [None]
SeeAlso [Cudd_ReadOne Cudd_ReadZero]
Definition at line 933 of file cuddAPI.c.
References Cudd_Not, and DD_ONE.
unsigned int Cudd_ReadLooseUpTo (DdManager * dd)
Function********************************************************************
Synopsis [Reads the looseUpTo parameter of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetLooseUpTo Cudd_ReadMinHit Cudd_ReadMinDead]
Definition at line 1170 of file cuddAPI.c.
References DdManager::looseUpTo.
Referenced by Cudd_PrintInfo().
unsigned int Cudd_ReadMaxCache (DdManager * dd)
Function********************************************************************
Synopsis [Reads the maxCache parameter of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetMaxCache Cudd_ReadMaxCache]
Definition at line 1220 of file cuddAPI.c.
References DdManager::maxCache.
unsigned int Cudd_ReadMaxCacheHard (DdManager * dd)
Function********************************************************************
Synopsis [Reads the maxCacheHard parameter of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetMaxCacheHard Cudd_ReadMaxCache]
Definition at line 1265 of file cuddAPI.c.
References DdManager::maxCacheHard.
Referenced by Cudd_PrintInfo().
double Cudd_ReadMaxGrowth (DdManager * dd)
Function********************************************************************
Synopsis [Reads the maxGrowth parameter of the manager.]
Description [Reads the maxGrowth parameter of the manager. This parameter determines how much the number of nodes can grow during sifting of a variable. Overall, sifting never increases the size of the decision diagrams. This parameter only refers to intermediate results. A lower value will speed up sifting, possibly at the expense of quality.]
SideEffects [None]
SeeAlso [Cudd_SetMaxGrowth]
Definition at line 1792 of file cuddAPI.c.
References DdManager::maxGrowth.
Referenced by Cudd_PrintInfo().
long Cudd_ReadMemoryInUse (DdManager * dd)
Function********************************************************************
Synopsis [Returns the memory in use by the manager measured in bytes.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 2619 of file cuddAPI.c.
References DdManager::memused.
Referenced by Cudd_PrintInfo().
unsigned int Cudd_ReadMinDead (DdManager * dd)
Function********************************************************************
Synopsis [Reads the minDead parameter of the manager.]
Description [Reads the minDead parameter of the manager. The minDead parameter is used by the package to decide whether to collect garbage or resize a subtable of the unique table when the subtable becomes too full. The application can indirectly control the value of minDead by setting the looseUpTo parameter.]
SideEffects [None]
SeeAlso [Cudd_ReadDead Cudd_ReadLooseUpTo Cudd_SetLooseUpTo]
Definition at line 1475 of file cuddAPI.c.
References DdManager::minDead.
unsigned int Cudd_ReadMinHit (DdManager * dd)
Function********************************************************************
Synopsis [Reads the hit ratio that causes resizinig of the computed table.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetMinHit]
Definition at line 1121 of file cuddAPI.c.
References DdManager::minHit.
Referenced by Cudd_PrintInfo().
DdNode* Cudd_ReadMinusInfinity (DdManager * dd)
Function********************************************************************
Synopsis [Reads the minus-infinity constant from the manager.]
Description []
SideEffects [None]
Definition at line 969 of file cuddAPI.c.
References DdManager::minusinfinity.
long Cudd_ReadNodeCount (DdManager * dd)
Function********************************************************************
Synopsis [Reports the number of nodes in BDDs and ADDs.]
Description [Reports the number of nodes in BDDs and ADDs. This number does not include the isolated projection functions and the unused constants. These nodes that are not counted are not part of the DDs manipulated by the application.]
SideEffects [None]
SeeAlso [Cudd_ReadPeakNodeCount Cudd_zddReadNodeCount]
Definition at line 2845 of file cuddAPI.c.
References DD_MINUS_INFINITY, DD_PLUS_INFINITY, DD_ZERO, DdManager::dead, DdManager::keys, DdNode::ref, DdManager::size, and DdManager::vars.
Referenced by Cudd_StdPostReordHook(), and Cudd_StdPreReordHook().
double Cudd_ReadNodesDropped (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of nodes dropped.]
Description [Returns the number of nodes killed by dereferencing if the keeping of this statistic is enabled; -1 otherwise. This statistic is enabled only if the package is compiled with DD_STATS defined.]
SideEffects [None]
SeeAlso [Cudd_ReadNodesFreed]
Definition at line 1615 of file cuddAPI.c.
double Cudd_ReadNodesFreed (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of nodes freed.]
Description [Returns the number of nodes returned to the free list if the keeping of this statistic is enabled; -1 otherwise. This statistic is enabled only if the package is compiled with DD_STATS defined.]
SideEffects [None]
SeeAlso [Cudd_ReadNodesDropped]
Definition at line 1589 of file cuddAPI.c.
int Cudd_ReadNumberXovers (DdManager * dd)
Function********************************************************************
Synopsis [Reads the current number of crossovers used by the genetic algorithm for reordering.]
Description [Reads the current number of crossovers used by the genetic algorithm for variable reordering. A larger number of crossovers will cause the genetic algorithm to take more time, but will generally produce better results. The default value is 0, in which case the package uses three times the number of variables as number of crossovers, with a maximum of 60.]
SideEffects [None]
SeeAlso [Cudd_SetNumberXovers]
Definition at line 2573 of file cuddAPI.c.
References DdManager::numberXovers.
Referenced by Cudd_PrintInfo().
DdNode* Cudd_ReadOne (DdManager * dd)
Function********************************************************************
Synopsis [Returns the one constant of the manager.]
Description [Returns the one constant of the manager. The one constant is common to ADDs and BDDs.]
SideEffects [None]
SeeAlso [Cudd_ReadZero Cudd_ReadLogicZero Cudd_ReadZddOne]
Definition at line 862 of file cuddAPI.c.
References DdManager::one.
Referenced by Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneMinterm(), and cuddSubsetHeavyBranch().
long Cudd_ReadPeakNodeCount (DdManager * dd)
Function********************************************************************
Synopsis [Reports the peak number of nodes.]
Description [Reports the peak number of nodes. This number includes node on the free list. At the peak, the number of nodes on the free list is guaranteed to be less than DD_MEM_CHUNK.]
SideEffects [None]
SeeAlso [Cudd_ReadNodeCount Cudd_PrintInfo]
Definition at line 2808 of file cuddAPI.c.
References DD_MEM_CHUNK, DdManager::memoryList, and scan.
Referenced by Cudd_PrintInfo().
int Cudd_ReadPerm (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the current position of the i-th variable in the order.]
Description [Returns the current position of the i-th variable in the order. If the index is CUDD_MAXINDEX, returns CUDD_MAXINDEX; otherwise, if the index is out of bounds returns -1.]
SideEffects [None]
SeeAlso [Cudd_ReadInvPerm Cudd_ReadPermZdd]
Definition at line 2005 of file cuddAPI.c.
References CUDD_MAXINDEX, DdManager::perm, and DdManager::size.
int Cudd_ReadPermZdd (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the current position of the i-th ZDD variable in the order.]
Description [Returns the current position of the i-th ZDD variable in the order. If the index is CUDD_MAXINDEX, returns CUDD_MAXINDEX; otherwise, if the index is out of bounds returns -1.]
SideEffects [None]
SeeAlso [Cudd_ReadInvPermZdd Cudd_ReadPerm]
Definition at line 2031 of file cuddAPI.c.
References CUDD_MAXINDEX, DdManager::permZ, and DdManager::sizeZ.
DdNode* Cudd_ReadPlusInfinity (DdManager * dd)
Function********************************************************************
Synopsis [Reads the plus-infinity constant from the manager.]
Description []
SideEffects [None]
Definition at line 951 of file cuddAPI.c.
References DdManager::plusinfinity.
int Cudd_ReadPopulationSize (DdManager * dd)
Function********************************************************************
Synopsis [Reads the current size of the population used by the genetic algorithm for reordering.]
Description [Reads the current size of the population used by the genetic algorithm for variable reordering. A larger population size will cause the genetic algorithm to take more time, but will generally produce better results. The default value is 0, in which case the package uses three times the number of variables as population size, with a maximum of 120.]
SideEffects [None]
SeeAlso [Cudd_SetPopulationSize]
Definition at line 2520 of file cuddAPI.c.
References DdManager::populationSize.
Referenced by Cudd_PrintInfo().
int Cudd_ReadRecomb (DdManager * dd)
Function********************************************************************
Synopsis [Returns the current value of the recombination parameter used in group sifting.]
Description [Returns the current value of the recombination parameter used in group sifting. A larger (positive) value makes the aggregation of variables due to the second difference criterion more likely. A smaller (negative) value makes aggregation less likely.]
SideEffects [None]
SeeAlso [Cudd_SetRecomb]
Definition at line 2360 of file cuddAPI.c.
References DdManager::recomb.
Referenced by Cudd_PrintInfo().
int Cudd_ReadReorderings (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of times reordering has occurred.]
Description [Returns the number of times reordering has occurred in the manager. The number includes both the calls to Cudd_ReduceHeap from the application program and those automatically performed by the package. However, calls that do not even initiate reordering are not counted. A call may not initiate reordering if there are fewer than minsize live nodes in the manager, or if CUDD_REORDER_NONE is specified as reordering method. The calls to Cudd_ShuffleHeap are not counted.]
SideEffects [None]
SeeAlso [Cudd_ReduceHeap Cudd_ReadReorderingTime]
Definition at line 1501 of file cuddAPI.c.
References DdManager::reorderings.
long Cudd_ReadReorderingTime (DdManager * dd)
Function********************************************************************
Synopsis [Returns the time spent in reordering.]
Description [Returns the number of milliseconds spent reordering variables since the manager was initialized. The time spent in collecting garbage before reordering is included.]
SideEffects [None]
SeeAlso [Cudd_ReadReorderings]
Definition at line 1523 of file cuddAPI.c.
References DdManager::reordTime.
Referenced by Cudd_PrintInfo().
int Cudd_ReadSiftMaxSwap (DdManager * dd)
Function********************************************************************
Synopsis [Reads the siftMaxSwap parameter of the manager.]
Description [Reads the siftMaxSwap parameter of the manager. This parameter gives the maximum number of swaps that will be attempted for each invocation of sifting. The real number of swaps may exceed the set limit because the package will always complete the sifting of the variable that causes the limit to be reached.]
SideEffects [None]
SeeAlso [Cudd_ReadSiftMaxVar Cudd_SetSiftMaxSwap]
Definition at line 1743 of file cuddAPI.c.
References DdManager::siftMaxSwap.
Referenced by Cudd_PrintInfo().
int Cudd_ReadSiftMaxVar (DdManager * dd)
Function********************************************************************
Synopsis [Reads the siftMaxVar parameter of the manager.]
Description [Reads the siftMaxVar parameter of the manager. This parameter gives the maximum number of variables that will be sifted for each invocation of sifting.]
SideEffects [None]
SeeAlso [Cudd_ReadSiftMaxSwap Cudd_SetSiftMaxVar]
Definition at line 1696 of file cuddAPI.c.
References DdManager::siftMaxVar.
Referenced by Cudd_PrintInfo().
int Cudd_ReadSize (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of BDD variables in existance.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadZddSize]
Definition at line 1315 of file cuddAPI.c.
References DdManager::size.
Referenced by cuddSubsetShortPaths().
unsigned int Cudd_ReadSlots (DdManager * dd)
Function********************************************************************
Synopsis [Returns the total number of slots of the unique table.]
Description [Returns the total number of slots of the unique table. This number ismainly for diagnostic purposes.]
SideEffects [None]
Definition at line 1354 of file cuddAPI.c.
References DdManager::slots.
int Cudd_ReadSymmviolation (DdManager * dd)
Function********************************************************************
Synopsis [Returns the current value of the symmviolation parameter used in group sifting.]
Description [Returns the current value of the symmviolation parameter. This parameter is used in group sifting to decide how many violations to the symmetry conditions f10 = f01 or f11 = f00 are tolerable when checking for aggregation due to extended symmetry. The value should be between 0 and 100. A small value causes fewer variables to be aggregated. The default value is 0.]
SideEffects [None]
SeeAlso [Cudd_SetSymmviolation]
Definition at line 2413 of file cuddAPI.c.
References DdManager::symmviolation.
Referenced by Cudd_PrintInfo().
MtrNode* Cudd_ReadTree (DdManager * dd)
Function********************************************************************
Synopsis [Returns the variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetTree Cudd_FreeTree Cudd_ReadZddTree]
Definition at line 1837 of file cuddAPI.c.
References DdManager::tree.
double Cudd_ReadUniqueLinks (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of links followed in the unique table.]
Description [Returns the number of links followed during look-ups in the unique table if the keeping of this statistic is enabled; -1 otherwise. If an item is found in the first position of its collision list, the number of links followed is taken to be 0. If it is in second position, the number of links is 1, and so on. This statistic is enabled only if the package is compiled with DD_UNIQUE_PROFILE defined.]
SideEffects [None]
SeeAlso [Cudd_ReadUniqueLookUps]
Definition at line 1670 of file cuddAPI.c.
double Cudd_ReadUniqueLookUps (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of look-ups in the unique table.]
Description [Returns the number of look-ups in the unique table if the keeping of this statistic is enabled; -1 otherwise. This statistic is enabled only if the package is compiled with DD_UNIQUE_PROFILE defined.]
SideEffects [None]
SeeAlso [Cudd_ReadUniqueLinks]
Definition at line 1641 of file cuddAPI.c.
double Cudd_ReadUsedSlots (DdManager * dd)
Function********************************************************************
Synopsis [Reads the fraction of used slots in the unique table.]
Description [Reads the fraction of used slots in the unique table. The unused slots are those in which no valid data is stored. Garbage collection, variable reordering, and subtable resizing may cause used slots to become unused.]
SideEffects [None]
SeeAlso [Cudd_ReadSlots]
Definition at line 1377 of file cuddAPI.c.
References DdGen::node, DdSubtable::nodelist, DdManager::size, size, DdManager::sizeZ, DdManager::slots, DdManager::subtables, and DdManager::subtableZ.
Referenced by Cudd_PrintInfo().
DdNode* Cudd_ReadVars (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the i-th element of the vars array.]
Description [Returns the i-th element of the vars array if it falls within the array bounds; NULL otherwise. If i is the index of an existing variable, this function produces the same result as Cudd_bddIthVar. However, if the i-th var does not exist yet, Cudd_bddIthVar will create it, whereas Cudd_ReadVars will not.]
SideEffects [None]
SeeAlso [Cudd_bddIthVar]
Definition at line 2110 of file cuddAPI.c.
References DdManager::size, and DdManager::vars.
Referenced by BuildSubsetBdd().
DdNode* Cudd_ReadZddOne (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the ZDD for the constant 1 function.]
Description [Returns the ZDD for the constant 1 function. The representation of the constant 1 function as a ZDD depends on how many variables it (nominally) depends on. The index of the topmost variable in the support is given as argument i.]
SideEffects [None]
SeeAlso [Cudd_ReadOne]
Definition at line 885 of file cuddAPI.c.
References DD_ONE, and DdManager::univ.
int Cudd_ReadZddSize (DdManager * dd)
Function********************************************************************
Synopsis [Returns the number of ZDD variables in existance.]
Description []
SideEffects [None]
SeeAlso [Cudd_ReadSize]
Definition at line 1335 of file cuddAPI.c.
References DdManager::sizeZ.
MtrNode* Cudd_ReadZddTree (DdManager * dd)
Function********************************************************************
Synopsis [Returns the variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_SetZddTree Cudd_FreeZddTree Cudd_ReadTree]
Definition at line 1909 of file cuddAPI.c.
References DdManager::treeZ.
DdNode* Cudd_ReadZero (DdManager * dd)
Function********************************************************************
Synopsis [Returns the zero constant of the manager.]
Description [Returns the zero constant of the manager. The zero constant is the arithmetic zero, rather than the logic zero. The latter is the complement of the one constant.]
SideEffects [None]
SeeAlso [Cudd_ReadOne Cudd_ReadLogicZero]
Definition at line 911 of file cuddAPI.c.
References DD_ZERO.
int Cudd_RemoveHook (DdManager * dd, int(*)(DdManager *, void *) f, Cudd_HookType where)
Function********************************************************************
Synopsis [Removes a function from a hook.]
Description [Removes a function from a hook. A hook is a list of application-provided functions called on certain occasions by the package. Returns 1 if successful; 0 the function was not in the list.]
SideEffects [None]
SeeAlso [Cudd_AddHook]
Definition at line 2966 of file cuddAPI.c.
References CUDD_POST_GC_HOOK, CUDD_POST_REORDERING_HOOK, CUDD_PRE_GC_HOOK, CUDD_PRE_REORDERING_HOOK, FREE, DdHook::next, DdManager::postGCHook, DdManager::postReorderingHook, DdManager::preGCHook, and DdManager::preReorderingHook.
Referenced by Cudd_DisableReorderingReporting(), and cuddFreeTable().
int Cudd_ReorderingReporting (DdManager * dd)
Function********************************************************************
Synopsis [Returns 1 if reporting of reordering stats is enabled.]
Description [Returns 1 if reporting of reordering stats is enabled; 0 otherwise.]
SideEffects [none]
SeeAlso [Cudd_EnableReorderingReporting Cudd_DisableReorderingReporting]
Definition at line 3242 of file cuddAPI.c.
References Cudd_IsInHook(), CUDD_PRE_REORDERING_HOOK, and Cudd_StdPreReordHook().
int Cudd_ReorderingStatus (DdManager * unique, Cudd_ReorderingType * method)
Function********************************************************************
Synopsis [Reports the status of automatic dynamic reordering of BDDs and ADDs.]
Description [Reports the status of automatic dynamic reordering of BDDs and ADDs. Parameter method is set to the reordering method currently selected. Returns 1 if automatic reordering is enabled; 0 otherwise.]
SideEffects [Parameter method is set to the reordering method currently selected.]
SeeAlso [Cudd_AutodynEnable Cudd_AutodynDisable Cudd_ReorderingStatusZdd]
Definition at line 610 of file cuddAPI.c.
References DdManager::autoDyn, and DdManager::autoMethod.
Referenced by Cudd_PrintInfo().
int Cudd_ReorderingStatusZdd (DdManager * unique, Cudd_ReorderingType * method)
Function********************************************************************
Synopsis [Reports the status of automatic dynamic reordering of ZDDs.]
Description [Reports the status of automatic dynamic reordering of ZDDs. Parameter method is set to the ZDD reordering method currently selected. Returns 1 if automatic reordering is enabled; 0 otherwise.]
SideEffects [Parameter method is set to the ZDD reordering method currently selected.]
SeeAlso [Cudd_AutodynEnableZdd Cudd_AutodynDisableZdd Cudd_ReorderingStatus]
Definition at line 687 of file cuddAPI.c.
References DdManager::autoDynZ, and DdManager::autoMethodZ.
Referenced by Cudd_PrintInfo().
void Cudd_SetArcviolation (DdManager * dd, int arcviolation)
Function********************************************************************
Synopsis [Sets the value of the arcviolation parameter used in group sifting.]
Description [Sets the value of the arcviolation parameter. This parameter is used in group sifting to decide how many arcs into y not coming from x are tolerable when checking for aggregation due to extended symmetry. The value should be between 0 and 100. A small value causes fewer variables to be aggregated. The default value is 0.]
SideEffects [None]
SeeAlso [Cudd_ReadArcviolation]
Definition at line 2493 of file cuddAPI.c.
References DdManager::arcviolation.
void Cudd_SetBackground (DdManager * dd, DdNode * bck)
Function********************************************************************
Synopsis [Sets the background constant of the manager.]
Description [Sets the background constant of the manager. It assumes that the DdNode pointer bck is already referenced.]
SideEffects [None]
Definition at line 1006 of file cuddAPI.c.
References DdManager::background.
void Cudd_SetEpsilon (DdManager * dd, CUDD_VALUE_TYPE ep)
Function********************************************************************
Synopsis [Sets the epsilon parameter of the manager to ep.]
Description [Sets the epsilon parameter of the manager to ep. The epsilon parameter control the comparison between floating point numbers.]
SideEffects [None]
SeeAlso [Cudd_ReadEpsilon]
Definition at line 2154 of file cuddAPI.c.
References DdManager::epsilon.
void Cudd_SetGroupcheck (DdManager * dd, Cudd_AggregationType gc)
Function********************************************************************
Synopsis [Sets the parameter groupcheck of the manager to gc.]
Description [Sets the parameter groupcheck of the manager to gc. The groupcheck parameter determines the aggregation criterion in group sifting.]
SideEffects [None]
SeeAlso [Cudd_ReadGroupCheck]
Definition at line 2199 of file cuddAPI.c.
References DdManager::groupcheck.
void Cudd_SetLooseUpTo (DdManager * dd, unsigned int lut)
Function********************************************************************
Synopsis [Sets the looseUpTo parameter of the manager.]
Description [Sets the looseUpTo parameter of the manager. This parameter of the manager controls the threshold beyond which no fast growth of the unique table is allowed. The threshold is given as a number of slots. If the value passed to this function is 0, the function determines a suitable value based on the available memory.]
SideEffects [None]
SeeAlso [Cudd_ReadLooseUpTo Cudd_SetMinHit]
Definition at line 1194 of file cuddAPI.c.
References DD_MAX_LOOSE_FRACTION, getSoftDataLimit(), and DdManager::looseUpTo.
Referenced by Cudd_Init(), and cuddInitTable().
void Cudd_SetMaxCache (DdManager * dd, unsigned int mc)
Function********************************************************************
Synopsis [Sets the maxCache parameter of the manager.]
Description [Sets the maxCache parameter of the manager. This parameter is normally automatically determined by the package based on the total number of nodes and the parameter maxCacheHard. Applications should normally change maxCacheHard rather than maxCache if they want to explicitly control the trade-off of memory versus speed.]
SideEffects [None]
SeeAlso [Cudd_ReadMaxCache Cudd_SetMaxCacheHard]
Definition at line 1244 of file cuddAPI.c.
References DdManager::maxCache.
void Cudd_SetMaxCacheHard (DdManager * dd, unsigned int mc)
Function********************************************************************
Synopsis [Sets the maxCacheHard parameter of the manager.]
Description [Sets the maxCacheHard parameter of the manager. The cache cannot grow larger than maxCacheHard entries. This parameter allows an application to control the trade-off of memory versus speed. If the value passed to this function is 0, the function determines a suitable maximum cache size based on the available memory.]
SideEffects [None]
SeeAlso [Cudd_ReadMaxCacheHard Cudd_SetMaxCache]
Definition at line 1289 of file cuddAPI.c.
References DD_MAX_CACHE_FRACTION, getSoftDataLimit(), and DdManager::maxCacheHard.
void Cudd_SetMaxGrowth (DdManager * dd, double mg)
Function********************************************************************
Synopsis [Sets the maxGrowth parameter of the manager.]
Description [Sets the maxGrowth parameter of the manager. This parameter determines how much the number of nodes can grow during sifting of a variable. Overall, sifting never increases the size of the decision diagrams. This parameter only refers to intermediate results. A lower value will speed up sifting, possibly at the expense of quality.]
SideEffects [None]
SeeAlso [Cudd_ReadMaxGrowth]
Definition at line 1816 of file cuddAPI.c.
References DdManager::maxGrowth.
void Cudd_SetMinHit (DdManager * dd, unsigned int hr)
Function********************************************************************
Synopsis [Sets the hit ratio that causes resizinig of the computed table.]
Description [Sets the minHit parameter of the manager. This parameter controls the resizing of the computed table. If the hit ratio is larger than the specified value, and the cache is not already too large, then its size is doubled.]
SideEffects [None]
SeeAlso [Cudd_ReadMinHit]
Definition at line 1147 of file cuddAPI.c.
References DdManager::minHit.
Referenced by cuddInitCache().
void Cudd_SetNumberXovers (DdManager * dd, int numberXovers)
Function********************************************************************
Synopsis [Sets the number of crossovers used by the genetic algorithm for reordering.]
Description [Sets the number of crossovers used by the genetic algorithm for variable reordering. A larger number of crossovers will cause the genetic algorithm to take more time, but will generally produce better results. The default value is 0, in which case the package uses three times the number of variables as number of crossovers, with a maximum of 60.]
SideEffects [None]
SeeAlso [Cudd_ReadNumberXovers]
Definition at line 2599 of file cuddAPI.c.
References DdManager::numberXovers.
void Cudd_SetPopulationSize (DdManager * dd, int populationSize)
Function********************************************************************
Synopsis [Sets the size of the population used by the genetic algorithm for reordering.]
Description [Sets the size of the population used by the genetic algorithm for variable reordering. A larger population size will cause the genetic algorithm to take more time, but will generally produce better results. The default value is 0, in which case the package uses three times the number of variables as population size, with a maximum of 120.]
SideEffects [Changes the manager.]
SeeAlso [Cudd_ReadPopulationSize]
Definition at line 2546 of file cuddAPI.c.
References DdManager::populationSize.
void Cudd_SetRecomb (DdManager * dd, int recomb)
Function********************************************************************
Synopsis [Sets the value of the recombination parameter used in group sifting.]
Description [Sets the value of the recombination parameter used in group sifting. A larger (positive) value makes the aggregation of variables due to the second difference criterion more likely. A smaller (negative) value makes aggregation less likely. The default value is 0.]
SideEffects [Changes the manager.]
SeeAlso [Cudd_ReadRecomb]
Definition at line 2385 of file cuddAPI.c.
References DdManager::recomb.
void Cudd_SetSiftMaxSwap (DdManager * dd, int sms)
Function********************************************************************
Synopsis [Sets the siftMaxSwap parameter of the manager.]
Description [Sets the siftMaxSwap parameter of the manager. This parameter gives the maximum number of swaps that will be attempted for each invocation of sifting. The real number of swaps may exceed the set limit because the package will always complete the sifting of the variable that causes the limit to be reached.]
SideEffects [None]
SeeAlso [Cudd_SetSiftMaxVar Cudd_ReadSiftMaxSwap]
Definition at line 1767 of file cuddAPI.c.
References DdManager::siftMaxSwap.
void Cudd_SetSiftMaxVar (DdManager * dd, int smv)
Function********************************************************************
Synopsis [Sets the siftMaxVar parameter of the manager.]
Description [Sets the siftMaxVar parameter of the manager. This parameter gives the maximum number of variables that will be sifted for each invocation of sifting.]
SideEffects [None]
SeeAlso [Cudd_SetSiftMaxSwap Cudd_ReadSiftMaxVar]
Definition at line 1718 of file cuddAPI.c.
References DdManager::siftMaxVar.
void Cudd_SetSymmviolation (DdManager * dd, int symmviolation)
Function********************************************************************
Synopsis [Sets the value of the symmviolation parameter used in group sifting.]
Description [Sets the value of the symmviolation parameter. This parameter is used in group sifting to decide how many violations to the symmetry conditions f10 = f01 or f11 = f00 are tolerable when checking for aggregation due to extended symmetry. The value should be between 0 and 100. A small value causes fewer variables to be aggregated. The default value is 0.]
SideEffects [Changes the manager.]
SeeAlso [Cudd_ReadSymmviolation]
Definition at line 2440 of file cuddAPI.c.
References DdManager::symmviolation.
void Cudd_SetTree (DdManager * dd, MtrNode * tree)
Function********************************************************************
Synopsis [Sets the variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_FreeTree Cudd_ReadTree Cudd_SetZddTree]
Definition at line 1857 of file cuddAPI.c.
References fixVarTree(), Mtr_FreeTree(), DdManager::perm, DdManager::size, and DdManager::tree.
void Cudd_SetZddTree (DdManager * dd, MtrNode * tree)
Function********************************************************************
Synopsis [Sets the ZDD variable group tree of the manager.]
Description []
SideEffects [None]
SeeAlso [Cudd_FreeZddTree Cudd_ReadZddTree Cudd_SetTree]
Definition at line 1929 of file cuddAPI.c.
References fixVarTree(), Mtr_FreeTree(), DdManager::permZ, DdManager::sizeZ, and DdManager::treeZ.
int Cudd_StdPostReordHook (DdManager * dd, void * data)
Function********************************************************************
Synopsis [Sample hook function to call after reordering.]
Description [Sample hook function to call after reordering. Prints on stdout final size and reordering time. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_StdPreReordHook]
Definition at line 3156 of file cuddAPI.c.
References Cudd_ReadNodeCount(), and util_cpu_time().
Referenced by Cudd_DisableReorderingReporting(), and Cudd_EnableReorderingReporting().
int Cudd_StdPreReordHook (DdManager * dd, void * data)
Function********************************************************************
Synopsis [Sample hook function to call before reordering.]
Description [Sample hook function to call before reordering. Prints on stdout reordering method and initial size. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_StdPostReordHook]
Definition at line 3068 of file cuddAPI.c.
References Cudd_ReadNodeCount(), CUDD_REORDER_ANNEALING, CUDD_REORDER_EXACT, CUDD_REORDER_GENETIC, CUDD_REORDER_GROUP_SIFT, CUDD_REORDER_GROUP_SIFT_CONV, CUDD_REORDER_LINEAR, CUDD_REORDER_LINEAR_CONVERGE, CUDD_REORDER_RANDOM, CUDD_REORDER_RANDOM_PIVOT, CUDD_REORDER_SIFT, CUDD_REORDER_SIFT_CONVERGE, CUDD_REORDER_SYMM_SIFT, CUDD_REORDER_SYMM_SIFT_CONV, CUDD_REORDER_WINDOW2, CUDD_REORDER_WINDOW2_CONV, CUDD_REORDER_WINDOW3, CUDD_REORDER_WINDOW3_CONV, CUDD_REORDER_WINDOW4, and CUDD_REORDER_WINDOW4_CONV.
Referenced by Cudd_DisableReorderingReporting(), Cudd_EnableReorderingReporting(), and Cudd_ReorderingReporting().
void Cudd_TurnOffCountDead (DdManager * dd)
Function********************************************************************
Synopsis [Causes the dead nodes not to be counted towards triggering reordering.]
Description [Causes the dead nodes not to be counted towards triggering reordering. This causes less frequent reorderings. By default dead nodes are not counted. Therefore there is no need to call this function unless Cudd_TurnOnCountDead has been previously called.]
SideEffects [Changes the manager.]
SeeAlso [Cudd_TurnOnCountDead Cudd_DeadAreCounted]
Definition at line 2336 of file cuddAPI.c.
References DdManager::countDead.
void Cudd_TurnOnCountDead (DdManager * dd)
Function********************************************************************
Synopsis [Causes the dead nodes to be counted towards triggering reordering.]
Description [Causes the dead nodes to be counted towards triggering reordering. This causes more frequent reorderings. By default dead nodes are not counted.]
SideEffects [Changes the manager.]
SeeAlso [Cudd_TurnOffCountDead Cudd_DeadAreCounted]
Definition at line 2311 of file cuddAPI.c.
References DdManager::countDead.
DdNode* Cudd_zddIthVar (DdManager * dd, int i)
Function********************************************************************
Synopsis [Returns the ZDD variable with index i.]
Description [Retrieves the ZDD variable with index i if it already exists, or creates a new ZDD variable. Returns a pointer to the variable if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddIthVar Cudd_addIthVar]
Definition at line 377 of file cuddAPI.c.
References CUDD_MAXINDEX, Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), DD_ONE, DD_ZERO, DdManager::invpermZ, DdManager::permZ, DdManager::reordered, DdManager::sizeZ, and DdManager::univ.
long Cudd_zddReadNodeCount (DdManager * dd)
Function********************************************************************
Synopsis [Reports the number of nodes in ZDDs.]
Description [Reports the number of nodes in ZDDs. This number always includes the two constants 1 and 0.]
SideEffects [None]
SeeAlso [Cudd_ReadPeakNodeCount Cudd_ReadNodeCount]
Definition at line 2881 of file cuddAPI.c.
References DdManager::deadZ, and DdManager::keysZ.
void Cudd_zddRealignDisable (DdManager * unique)
Function********************************************************************
Synopsis [Disables realignment of ZDD order to BDD order.]
Description []
SideEffects [None]
SeeAlso [Cudd_zddRealignEnable Cudd_zddRealignmentEnabled Cudd_bddRealignEnable Cudd_bddRealignmentEnabled]
Definition at line 764 of file cuddAPI.c.
References DdManager::realign.
void Cudd_zddRealignEnable (DdManager * unique)
Function********************************************************************
Synopsis [Enables realignment of ZDD order to BDD order.]
Description [Enables realignment of the ZDD variable order to the BDD variable order after the BDDs and ADDs have been reordered. The number of ZDD variables must be a multiple of the number of BDD variables for realignment to make sense. If this condition is not met, Cudd_ReduceHeap will return 0. Let M be the ratio of the two numbers. For the purpose of realignment, the ZDD variables from M*i to (M+1)*i-1 are reagarded as corresponding to BDD variable i. Realignment is initially disabled.]
SideEffects [None]
SeeAlso [Cudd_ReduceHeap Cudd_zddRealignDisable Cudd_zddRealignmentEnabled Cudd_bddRealignDisable Cudd_bddRealignmentEnabled]
Definition at line 742 of file cuddAPI.c.
References DdManager::realign.
int Cudd_zddRealignmentEnabled (DdManager * unique)
Function********************************************************************
Synopsis [Tells whether the realignment of ZDD order to BDD order is enabled.]
Description [Returns 1 if the realignment of ZDD order to BDD order is enabled; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_zddRealignEnable Cudd_zddRealignDisable Cudd_bddRealignEnable Cudd_bddRealignDisable]
Definition at line 712 of file cuddAPI.c.
References DdManager::realign.
Referenced by Cudd_PrintInfo().
int Cudd_zddVarsFromBddVars (DdManager * dd, int multiplicity)
Function********************************************************************
Synopsis [Creates one or more ZDD variables for each BDD variable.]
Description [Creates one or more ZDD variables for each BDD variable. If some ZDD variables already exist, only the missing variables are created. Parameter multiplicity allows the caller to control how many variables are created for each BDD variable in existence. For instance, if ZDDs are used to represent covers, two ZDD variables are required for each BDD variable. The order of the BDD variables is transferred to the ZDD variables. If a variable group tree exists for the BDD variables, a corresponding ZDD variable group tree is created by expanding the BDD variable tree. In any case, the ZDD variables derived from the same BDD variable are merged in a ZDD variable group. If a ZDD variable group tree exists, it is freed. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddNewVar Cudd_bddIthVar Cudd_bddNewVarAtLevel]
Definition at line 448 of file cuddAPI.c.
References ALLOC, Cudd_FreeZddTree(), Cudd_MakeZddTreeNode(), CUDD_MEMORY_OUT, Cudd_zddShuffleHeap(), cuddResizeTableZdd(), DdManager::errorCode, FREE, MtrNode::index, DdNode::index, DdManager::invperm, DdManager::invpermZ, Mtr_CopyTree(), MTR_DEFAULT, Mtr_InitGroupTree(), DdGen::node, DdManager::perm, DdManager::permZ, DdManager::size, DdManager::sizeZ, DdManager::tree, DdManager::treeZ, and DdManager::univ.
static void fixVarTree (MtrNode * treenode, int * perm, int size) [static]
Function********************************************************************
Synopsis [Fixes a variable group tree.]
Description []
SideEffects [Changes the variable group tree.]
SeeAlso []
Definition at line 3312 of file cuddAPI.c.
References MtrNode::child, MtrNode::index, MtrNode::low, and MtrNode::younger.
Referenced by Cudd_SetTree(), and Cudd_SetZddTree().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAPI.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAPI.c]
PackageName [cudd]
Synopsis [Application interface functions.]
Description [External procedures included in this module:
Cudd_addNewVar()
Cudd_addNewVarAtLevel()
Cudd_bddNewVar()
Cudd_bddNewVarAtLevel()
Cudd_addIthVar()
Cudd_bddIthVar()
Cudd_zddIthVar()
Cudd_zddVarsFromBddVars()
Cudd_addConst()
Cudd_AutodynEnable()
Cudd_AutodynDisable()
Cudd_ReorderingStatus()
Cudd_AutodynEnableZdd()
Cudd_AutodynDisableZdd()
Cudd_ReorderingStatusZdd()
Cudd_zddRealignmentEnabled()
Cudd_zddRealignEnable()
Cudd_zddRealignDisable()
Cudd_bddRealignmentEnabled()
Cudd_bddRealignEnable()
Cudd_bddRealignDisable()
Cudd_ReadOne()
Cudd_ReadZddOne()
Cudd_ReadZero()
Cudd_ReadLogicZero()
Cudd_ReadPlusInfinity()
Cudd_ReadMinusInfinity()
Cudd_ReadBackground()
Cudd_SetBackground()
Cudd_ReadCacheSlots()
Cudd_ReadCacheUsedSlots()
Cudd_ReadCacheLookUps()
Cudd_ReadCacheHits()
Cudd_ReadMinHit()
Cudd_SetMinHit()
Cudd_ReadLooseUpTo()
Cudd_SetLooseUpTo()
Cudd_ReadMaxCache()
Cudd_SetMaxCache()
Cudd_ReadMaxCacheHard()
Cudd_SetMaxCacheHard()
Cudd_ReadSize()
Cudd_ReadSlots()
Cudd_ReadKeys()
Cudd_ReadDead()
Cudd_ReadMinDead()
Cudd_ReadReorderings()
Cudd_ReadReorderingTime()
Cudd_ReadGarbageCollections()
Cudd_ReadGarbageCollectionTime()
Cudd_ReadNodesFreed()
Cudd_ReadNodesDropped()
Cudd_ReadUniqueLookUps()
Cudd_ReadUniqueLinks()
Cudd_ReadSiftMaxVar()
Cudd_SetSiftMaxVar()
Cudd_ReadMaxGrowth()
Cudd_SetMaxGrowth()
Cudd_ReadTree()
Cudd_SetTree()
Cudd_FreeTree()
Cudd_ReadZddTree()
Cudd_SetZddTree()
Cudd_FreeZddTree()
Cudd_NodeReadIndex()
Cudd_ReadPerm()
Cudd_ReadInvPerm()
Cudd_ReadVars()
Cudd_ReadEpsilon()
Cudd_SetEpsilon()
Cudd_ReadGroupCheck()
Cudd_SetGroupcheck()
Cudd_GarbageCollectionEnabled()
Cudd_EnableGarbageCollection()
Cudd_DisableGarbageCollection()
Cudd_DeadAreCounted()
Cudd_TurnOnCountDead()
Cudd_TurnOffCountDead()
Cudd_ReadRecomb()
Cudd_SetRecomb()
Cudd_ReadSymmviolation()
Cudd_SetSymmviolation()
Cudd_ReadArcviolation()
Cudd_SetArcviolation()
Cudd_ReadPopulationSize()
Cudd_SetPopulationSize()
Cudd_ReadNumberXovers()
Cudd_SetNumberXovers()
Cudd_ReadMemoryInUse()
Cudd_PrintInfo()
Cudd_ReadPeakNodeCount()
Cudd_ReadNodeCount()
Cudd_zddReadNodeCount()
Cudd_AddHook()
Cudd_RemoveHook()
Cudd_IsInHook()
Cudd_StdPreReordHook()
Cudd_StdPostReordHook()
Cudd_EnableReorderingReporting()
Cudd_DisableReorderingReporting()
Cudd_ReorderingReporting()
Cudd_ReadErrorCode()
Cudd_ClearErrorCode()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 149 of file cuddAPI.c.