cuddAnneal.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define BETA 0.6
#define ALPHA 0.90
#define EXC_PROB 0.4
#define JUMP_UP_PROB 0.36
#define MAXGEN_RATIO 15.0
#define STOP_TEMP 1.0
Functions
static int stopping_criterion ARGS ((int c1, int c2, int c3, int c4, double temp))
static double random_generator ARGS (())
static int ddExchange ARGS ((DdManager *table, int x, int y, double temp))
static int ddJumpingAux ARGS ((DdManager *table, int x, int x_low, int x_high, double temp))
static Move *ddJumpingUp ARGS ((DdManager *table, int x, int x_low, int initial_size))
static Move *ddJumpingDown ARGS ((DdManager *table, int x, int x_high, int initial_size))
static int siftBackwardProb ARGS ((DdManager *table, Move *moves, int size, double temp))
static void copyOrder ARGS ((DdManager *table, int *array, int lower, int upper))
int cuddAnnealing (DdManager *table, int lower, int upper)
static int stopping_criterion (int c1, int c2, int c3, int c4, double temp)
static double random_generator ()
static int ddExchange (DdManager *table, int x, int y, double temp)
static int ddJumpingAux (DdManager *table, int x, int x_low, int x_high, double temp)
static Move * ddJumpingUp (DdManager *table, int x, int x_low, int initial_size)
static Move * ddJumpingDown (DdManager *table, int x, int x_high, int initial_size)
static int siftBackwardProb (DdManager *table, Move *moves, int size, double temp)
static void copyOrder (DdManager *table, int *array, int lower, int upper)
static int restoreOrder (DdManager *table, int *array, int lower, int upper)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAnneal.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define ALPHA 0.90
Definition at line 49 of file cuddAnneal.c.
Referenced by cuddAnnealing().
#define BETA 0.6
CFile***********************************************************************
FileName [cuddAnneal.c]
PackageName [cudd]
Synopsis [Reordering of DDs based on simulated annealing]
Description [Internal procedures included in this file:
cuddAnnealing()
Static procedures included in this file:
stopping_criterion()
random_generator()
ddExchange()
ddJumpingAux()
ddJumpingUp()
ddJumpingDown()
siftBackwardProb()
copyOrder()
restoreOrder()
]
SeeAlso []
Author [Jae-Young Jang, Jorgen Sivesind]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 48 of file cuddAnneal.c.
Referenced by cuddAnnealing().
#define EXC_PROB 0.4
Definition at line 50 of file cuddAnneal.c.
Referenced by cuddAnnealing().
#define JUMP_UP_PROB 0.36
Definition at line 51 of file cuddAnneal.c.
Referenced by cuddAnnealing().
#define MAXGEN_RATIO 15.0
Definition at line 52 of file cuddAnneal.c.
Referenced by cuddAnnealing().
#define STOP_TEMP 1.0
Definition at line 53 of file cuddAnneal.c.
Referenced by stopping_criterion().
Function Documentation
static int restoreOrder ARGS ((DdManager *table, int *array, int lower, int upper)) [static]
static int siftBackwardProb ARGS ((DdManager *table, Move *moves, int size, double temp)) [static]
static Move* ddJumpingDown ARGS ((DdManager *table, int x, int x_high, int initial_size)) [static]
static Move* ddJumpingUp ARGS ((DdManager *table, int x, int x_low, int initial_size)) [static]
static int ddJumpingAux ARGS ((DdManager *table, int x, int x_low, int x_high, double temp)) [static]
static int ddExchange ARGS ((DdManager *table, int x, int y, double temp)) [static]
static double random_generator ARGS (()) [static]
static int stopping_criterion ARGS ((int c1, int c2, int c3, int c4, double temp)) [static]
AutomaticStart
static void copyOrder (DdManager * table, int * array, int lower, int upper) [static]
Function********************************************************************
Synopsis [Copies the current variable order to array.]
Description [Copies the current variable order to array. At the same time inverts the permutation.]
SideEffects [None]
SeeAlso []
Definition at line 730 of file cuddAnneal.c.
References DdManager::invperm.
Referenced by cuddAnnealing().
int cuddAnnealing (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Get new variable-order by simulated annealing algorithm.]
Description [Get x, y by random selection. Choose either exchange or jump randomly. In case of jump, choose between jump_up and jump_down randomly. Do exchange or jump and get optimal case. Loop until there is no improvement or temperature reaches minimum. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 129 of file cuddAnneal.c.
References ALLOC, ALPHA, BETA, copyOrder(), CUDD_MEMORY_OUT, Cudd_Random(), cuddSifting(), ddExchange(), ddJumpingAux(), DdManager::errorCode, EXC_PROB, FREE, DdManager::isolated, JUMP_UP_PROB, DdManager::keys, MAXGEN_RATIO, random_generator(), restoreOrder(), result, size, and stopping_criterion().
Referenced by ddReorderChildren().
static int ddExchange (DdManager * table, int x, int y, double temp) [static]
Function********************************************************************
Synopsis [This function is for exchanging two variables, x and y.]
Description [This is the same funcion as ddSwapping except for comparison expression. Use probability function, exp(-size_change/temp).]
SideEffects [None]
SeeAlso []
Definition at line 327 of file cuddAnneal.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddNextLow(), cuddSwapInPlace(), DD_MAX_REORDER_GROWTH, DdManager::isolated, DdManager::keys, Move::next, result, siftBackwardProb(), Move::size, size, Move::x, and Move::y.
Referenced by cuddAnnealing().
static int ddJumpingAux (DdManager * table, int x, int x_low, int x_high, double temp) [static]
Function********************************************************************
Synopsis [Moves a variable to a specified position.]
Description [If x==x_low, it executes jumping_down. If x==x_high, it executes jumping_up. This funcion is similar to ddSiftingAux. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 476 of file cuddAnneal.c.
References assert, cuddDeallocNode, cuddNextHigh(), cuddNextLow(), ddJumpingDown(), ddJumpingUp(), DdManager::isolated, DdSubtable::keys, DdManager::keys, Move::next, result, siftBackwardProb(), and DdManager::subtables.
Referenced by cuddAnnealing().
static Move* ddJumpingDown (DdManager * table, int x, int x_high, int initial_size) [static]
Function********************************************************************
Synopsis [This function is for jumping down.]
Description [This is a simplified version of ddSiftingDown. It does not use lower bounding. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 606 of file cuddAnneal.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddNextHigh(), cuddSwapInPlace(), DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by ddJumpingAux().
static Move* ddJumpingUp (DdManager * table, int x, int x_low, int initial_size) [static]
Function********************************************************************
Synopsis [This function is for jumping up.]
Description [This is a simplified version of ddSiftingUp. It does not use lower bounding. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 547 of file cuddAnneal.c.
References cuddDeallocNode, cuddDynamicAllocNode(), cuddNextLow(), cuddSwapInPlace(), DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by ddJumpingAux().
static double random_generator () [static]
Function********************************************************************
Synopsis [Random number generator.]
Description [Returns a double precision value between 0.0 and 1.0.]
SideEffects [None]
SeeAlso []
Definition at line 306 of file cuddAnneal.c.
References Cudd_Random().
Referenced by cuddAnnealing().
static int restoreOrder (DdManager * table, int * array, int lower, int upper) [static]
Function********************************************************************
Synopsis [Restores the variable order in array by a series of sifts up.]
Description [Restores the variable order in array by a series of sifts up. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 760 of file cuddAnneal.c.
References assert, cuddNextLow(), cuddSwapInPlace(), DdManager::perm, and size.
Referenced by cuddAnnealing().
static int siftBackwardProb (DdManager * table, Move * moves, int size, double temp) [static]
Function********************************************************************
Synopsis [Returns the DD to the best position encountered during sifting if there was improvement.]
Description [Otherwise, `tosses a coin` to decide whether to keep the current configuration or return the DD to the original one. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 666 of file cuddAnneal.c.
References Move::next, and Move::size.
Referenced by ddExchange(), and ddJumpingAux().
static int stopping_criterion (int c1, int c2, int c3, int c4, double temp) [static]
Function********************************************************************
Synopsis [Checks termination condition.]
Description [If temperature is STOP_TEMP or there is no improvement then terminates. Returns 1 if the termination criterion is met; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 276 of file cuddAnneal.c.
References STOP_TEMP.
Referenced by cuddAnnealing().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAnneal.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 70 of file cuddAnneal.c.