cuddZddGroup.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static int zddTreeSiftingAux ARGS ((DdManager *table, MtrNode *treenode, Cudd_ReorderingType method))
static void zddFindNodeHiLo ARGS ((DdManager *table, MtrNode *treenode, int *lower, int *upper))
static int zddUniqueCompareGroup ARGS ((int *ptrX, int *ptrY))
static int zddGroupSifting ARGS ((DdManager *table, int lower, int upper))
static int zddGroupSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh))
static int zddGroupSiftingUp ARGS ((DdManager *table, int y, int xLow, Move **moves))
static int zddGroupSiftingDown ARGS ((DdManager *table, int x, int xHigh, Move **moves))
static int zddGroupMove ARGS ((DdManager *table, int x, int y, Move **moves))
static int zddGroupMoveBackward ARGS ((DdManager *table, int x, int y))
static int zddGroupSiftingBackward ARGS ((DdManager *table, Move *moves, int size))
static void zddMergeGroups ARGS ((DdManager *table, MtrNode *treenode, int low, int high))
MtrNode * Cudd_MakeZddTreeNode (DdManager *dd, unsigned int low, unsigned int size, unsigned int type)
int cuddZddTreeSifting (DdManager *table, Cudd_ReorderingType method)
static int zddTreeSiftingAux (DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)
static int zddReorderChildren (DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)
static void zddFindNodeHiLo (DdManager *table, MtrNode *treenode, int *lower, int *upper)
static int zddUniqueCompareGroup (int *ptrX, int *ptrY)
static int zddGroupSifting (DdManager *table, int lower, int upper)
static int zddGroupSiftingAux (DdManager *table, int x, int xLow, int xHigh)
static int zddGroupSiftingUp (DdManager *table, int y, int xLow, Move **moves)
static int zddGroupSiftingDown (DdManager *table, int x, int xHigh, Move **moves)
static int zddGroupMove (DdManager *table, int x, int y, Move **moves)
static int zddGroupMoveBackward (DdManager *table, int x, int y)
static int zddGroupSiftingBackward (DdManager *table, Move *moves, int size)
static void zddMergeGroups (DdManager *table, MtrNode *treenode, int low, int high)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static int * entry
int zddTotalNumberSwapping
Function Documentation
static void zddMergeGroups ARGS ((DdManager *table, MtrNode *treenode, int low, int high)) [static]
static int zddGroupSiftingBackward ARGS ((DdManager *table, Move *moves, int size)) [static]
static int zddGroupMoveBackward ARGS ((DdManager *table, int x, int y)) [static]
static int zddGroupMove ARGS ((DdManager *table, int x, int y, Move **moves)) [static]
static int zddGroupSiftingDown ARGS ((DdManager *table, int x, int xHigh, Move **moves)) [static]
static int zddGroupSiftingUp ARGS ((DdManager *table, int y, int xLow, Move **moves)) [static]
static int zddGroupSiftingAux ARGS ((DdManager *table, int x, int xLow, int xHigh)) [static]
static int zddGroupSifting ARGS ((DdManager *table, int lower, int upper)) [static]
static int zddUniqueCompareGroup ARGS ((int *ptrX, int *ptrY)) [static]
static void zddFindNodeHiLo ARGS ((DdManager *table, MtrNode *treenode, int *lower, int *upper)) [static]
static int zddReorderChildren ARGS ((DdManager *table, MtrNode *treenode, Cudd_ReorderingType method)) [static]
AutomaticStart
MtrNode* Cudd_MakeZddTreeNode (DdManager * dd, unsigned int low, unsigned int size, unsigned int type)
Function********************************************************************
Synopsis [Creates a new ZDD variable group.]
Description [Creates a new ZDD variable group. The group starts at variable and contains size variables. The parameter low is the index of the first variable. If the variable already exists, its current position in the order is known to the manager. If the variable does not exist yet, the position is assumed to be the same as the index. The group tree is created if it does not exist yet. Returns a pointer to the group if successful; NULL otherwise.]
SideEffects [The ZDD variable tree is changed.]
SeeAlso [Cudd_MakeTreeNode]
Definition at line 134 of file cuddZddGroup.c.
References ddMax, MtrNode::index, DdManager::invpermZ, Mtr_InitGroupTree(), Mtr_MakeGroup(), MTR_MAXHIGH, DdManager::permZ, MtrNode::size, DdManager::sizeZ, and DdManager::treeZ.
Referenced by Cudd_zddVarsFromBddVars().
int cuddZddTreeSifting (DdManager * table, Cudd_ReorderingType method)
Function********************************************************************
Synopsis [Tree sifting algorithm for ZDDs.]
Description [Tree sifting algorithm for ZDDs. Assumes that a tree representing a group hierarchy is passed as a parameter. It then reorders each group in postorder fashion by calling zddTreeSiftingAux. Assumes that no dead nodes are present. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 203 of file cuddZddGroup.c.
References CUDD_GROUP_CHECK5, CUDD_GROUP_CHECK7, CUDD_REORDER_GROUP_SIFT, DdManager::groupcheck, MtrNode::index, DdManager::invpermZ, Mtr_InitGroupTree(), Mtr_PrintGroups(), DdSubtable::next, result, DdManager::sizeZ, DdManager::subtableZ, DdManager::treeZ, and zddTreeSiftingAux().
Referenced by Cudd_zddReduceHeap().
static void zddFindNodeHiLo (DdManager * table, MtrNode * treenode, int * lower, int * upper) [static]
Function********************************************************************
Synopsis [Finds the lower and upper bounds of the group represented by treenode.]
Description [Finds the lower and upper bounds of the group represented by treenode. The high and low fields of treenode are indices. From those we need to derive the current positions, and find maximum and minimum.]
SideEffects [The bounds are returned as side effects.]
SeeAlso []
Definition at line 474 of file cuddZddGroup.c.
References assert, MtrNode::child, MtrNode::index, MtrNode::low, DdManager::permZ, MtrNode::size, DdManager::sizeZ, and MtrNode::younger.
Referenced by zddReorderChildren().
static int zddGroupMove (DdManager * table, int x, int y, Move ** moves) [static]
Function********************************************************************
Synopsis [Swaps two groups and records the move.]
Description [Swaps two groups and records the move. Returns the number of keys in the DD table in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1025 of file cuddZddGroup.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextHigh(), cuddZddNextLow(), cuddZddSwapInPlace(), Move::flags, DdManager::keysZ, MTR_DEFAULT, Move::next, DdSubtable::next, Move::size, size, DdManager::subtableZ, Move::x, and Move::y.
Referenced by zddGroupSiftingDown(), and zddGroupSiftingUp().
static int zddGroupMoveBackward (DdManager * table, int x, int y) [static]
Function********************************************************************
Synopsis [Undoes the swap two groups.]
Description [Undoes the swap two groups. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1131 of file cuddZddGroup.c.
References assert, cuddZddNextHigh(), cuddZddNextLow(), cuddZddSwapInPlace(), DdSubtable::next, size, and DdManager::subtableZ.
static int zddGroupSifting (DdManager * table, int lower, int upper) [static]
Function********************************************************************
Synopsis [Sifts from treenode->low to treenode->high.]
Description [Sifts from treenode->low to treenode->high. If croupcheck == CUDD_GROUP_CHECK7, it checks for group creation at the end of the initial sifting. If a group is created, it is then sifted again. After sifting one variable, the group that contains it is dissolved. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 577 of file cuddZddGroup.c.
References ALLOC, CUDD_MEMORY_OUT, entry, DdManager::errorCode, DdSubtable::keys, DdSubtable::next, DdManager::permZ, result, DdManager::sizeZ, and DdManager::subtableZ.
Referenced by zddReorderChildren().
static int zddGroupSiftingAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Sifts one variable up and down until it has taken all positions. Checks for aggregation.]
Description [Sifts one variable up and down until it has taken all positions. Checks for aggregation. There may be at most two sweeps, even if the group grows. Assumes that x is either an isolated variable, or it is the bottom of a group. All groups may not have been found. The variable being moved is returned to the best position seen during sifting. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 706 of file cuddZddGroup.c.
References assert, cuddDeallocNode, cuddZddNextHigh(), DdManager::keysZ, Move::next, DdSubtable::next, result, DdManager::subtableZ, Move::x, Move::y, zddGroupSiftingBackward(), zddGroupSiftingDown(), and zddGroupSiftingUp().
static int zddGroupSiftingBackward (DdManager * table, Move * moves, int size) [static]
Function********************************************************************
Synopsis [Determines the best position for a variables and returns it there.]
Description [Determines the best position for a variables and returns it there. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 1205 of file cuddZddGroup.c.
References Move::next, and Move::size.
Referenced by zddGroupSiftingAux().
static int zddGroupSiftingDown (DdManager * table, int x, int xHigh, Move ** moves) [static]
Function********************************************************************
Synopsis [Sifts down a variable until it reaches position xHigh.]
Description [Sifts down a variable until it reaches position xHigh. Assumes that x is the bottom of a group (or a singleton). Records all the moves. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 936 of file cuddZddGroup.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextHigh(), cuddZddSwapInPlace(), Move::flags, DdManager::invpermZ, DdManager::keysZ, DdManager::maxGrowth, MTR_DEFAULT, Move::next, DdSubtable::next, Move::size, size, DdManager::subtableZ, Move::x, Move::y, and zddGroupMove().
Referenced by zddGroupSiftingAux().
static int zddGroupSiftingUp (DdManager * table, int y, int xLow, Move ** moves) [static]
Function********************************************************************
Synopsis [Sifts up a variable until either it reaches position xLow or the size of the DD heap increases too much.]
Description [Sifts up a variable until either it reaches position xLow or the size of the DD heap increases too much. Assumes that y is the top of a group (or a singleton). Checks y for aggregation to the adjacent variables. Records all the moves that are appended to the list of moves received as input and returned as a side effect. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 855 of file cuddZddGroup.c.
References assert, cuddDeallocNode, cuddDynamicAllocNode(), cuddZddNextLow(), cuddZddSwapInPlace(), Move::flags, DdManager::invpermZ, DdManager::keysZ, DdManager::maxGrowth, MTR_DEFAULT, Move::next, DdSubtable::next, Move::size, size, DdManager::subtableZ, Move::x, Move::y, and zddGroupMove().
Referenced by zddGroupSiftingAux().
static void zddMergeGroups (DdManager * table, MtrNode * treenode, int low, int high) [static]
Function********************************************************************
Synopsis [Merges groups in the DD table.]
Description [Creates a single group from low to high and adjusts the idex field of the tree node.]
SideEffects [None]
Definition at line 1253 of file cuddZddGroup.c.
References MtrNode::index, DdManager::invpermZ, DdSubtable::next, MtrNode::parent, DdManager::subtableZ, and DdManager::treeZ.
Referenced by zddReorderChildren().
static int zddReorderChildren (DdManager * table, MtrNode * treenode, Cudd_ReorderingType method) [static]
Function********************************************************************
Synopsis [Reorders the children of a group tree node according to the options.]
Description [Reorders the children of a group tree node according to the options. After reordering puts all the variables in the group and/or its descendents in a single group. This allows hierarchical reordering. If the variables in the group do not exist yet, simply does nothing. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 373 of file cuddZddGroup.c.
References CUDD_REORDER_GROUP_SIFT, CUDD_REORDER_LINEAR, CUDD_REORDER_LINEAR_CONVERGE, CUDD_REORDER_RANDOM, CUDD_REORDER_RANDOM_PIVOT, CUDD_REORDER_SIFT, CUDD_REORDER_SIFT_CONVERGE, CUDD_REORDER_SYMM_SIFT, CUDD_REORDER_SYMM_SIFT_CONV, cuddZddLinearSifting(), cuddZddSifting(), cuddZddSwapping(), cuddZddSymmSifting(), cuddZddSymmSiftingConv(), MtrNode::flags, DdManager::keysZ, MTR_FIXED, result, zddFindNodeHiLo(), zddGroupSifting(), and zddMergeGroups().
Referenced by zddTreeSiftingAux().
static int zddTreeSiftingAux (DdManager * table, MtrNode * treenode, Cudd_ReorderingType method) [static]
Function********************************************************************
Synopsis [Visits the group tree and reorders each group.]
Description [Recursively visits the group tree and reorders each group in postorder fashion. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
Definition at line 289 of file cuddZddGroup.c.
References MtrNode::child, CUDD_REORDER_GROUP_SIFT, Mtr_PrintGroups(), MtrNode::size, MtrNode::younger, and zddReorderChildren().
Referenced by cuddZddTreeSifting().
static int zddUniqueCompareGroup (int * ptrX, int * ptrY) [static]
Function********************************************************************
Synopsis [Comparison function used by qsort.]
Description [Comparison function used by qsort to order the variables according to the number of keys in the subtables. Returns the difference in number of keys between the two variables being compared.]
SideEffects [None]
Definition at line 549 of file cuddZddGroup.c.
References entry.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddZddGroup.c]
PackageName [cudd]
Synopsis [Functions for ZDD group sifting.]
Description [External procedures included in this file:
Cudd_MakeZddTreeNode()
Internal procedures included in this file:
cuddZddTreeSifting()
Static procedures included in this module:
zddTreeSiftingAux()
zddCountInternalMtrNodes()
zddReorderChildren()
zddFindNodeHiLo()
zddUniqueCompareGroup()
zddGroupSifting()
zddGroupSiftingAux()
zddGroupSiftingUp()
zddGroupSiftingDown()
zddGroupMove()
zddGroupMoveBackward()
zddGroupSiftingBackward()
zddMergeGroups()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 65 of file cuddZddGroup.c.
int* entry [static]
Definition at line 68 of file cuddZddGroup.c.
int zddTotalNumberSwapping
Definition at line 81 of file cuddZddReord.c.
Referenced by Cudd_zddReduceHeap(), cuddZddLinearSifting(), cuddZddSifting(), cuddZddSwapInPlace(), cuddZddSymmSifting(), cuddZddSymmSiftingConv(), and zddShuffle().