cuddAddInv.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
DdNode * Cudd_addScalarInverse (DdManager *dd, DdNode *f, DdNode *epsilon)
DdNode * cuddAddScalarInverseRecur (DdManager *dd, DdNode *f, DdNode *epsilon)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddAddInv.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
DdNode* Cudd_addScalarInverse (DdManager * dd, DdNode * f, DdNode * epsilon)
Function********************************************************************
Synopsis [Computes the scalar inverse of an ADD.]
Description [Computes an n ADD where the discriminants are the multiplicative inverses of the corresponding discriminants of the argument ADD. Returns a pointer to the resulting ADD in case of success. Returns NULL if any discriminants smaller than epsilon is encountered.]
SideEffects [None]
Definition at line 91 of file cuddAddInv.c.
References cuddAddScalarInverseRecur(), cuddIsConstant, and DdManager::reordered.
Referenced by cuddAddScalarInverseRecur().
DdNode* cuddAddScalarInverseRecur (DdManager * dd, DdNode * f, DdNode * epsilon)
Function********************************************************************
Synopsis [Performs the recursive step of addScalarInverse.]
Description [Returns a pointer to the resulting ADD in case of success. Returns NULL if any discriminants smaller than epsilon is encountered.]
SideEffects [None]
Definition at line 127 of file cuddAddInv.c.
References Cudd_addScalarInverse(), Cudd_RecursiveDeref(), CUDD_VALUE_TYPE, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueConst(), cuddUniqueInter(), cuddV, ddAbs, DdNode::index, and DdGen::value.
Referenced by Cudd_addScalarInverse().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddAddInv.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddAddInv.c]
PackageName [cudd]
Synopsis [Function to compute the scalar inverse of an ADD.]
Description [External procedures included in this module:
Cudd_addScalarInverse()
Internal procedures included in this module:
cuddAddScalarInverseRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 53 of file cuddAddInv.c.