cuddTable.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Data Structures
union hack
Defines
#define DD_STACK_SIZE 128
#define DD_RED 0
#define DD_BLACK 1
#define DD_PAGE_SIZE 8192
#define DD_PAGE_MASK ~(DD_PAGE_SIZE - 1)
#define DD_INSERT_COMPARE(x, y)
#define DD_COLOR(p) ((p) $\rightarrow$ index)
#define DD_IS_BLACK(p) ((p) $\rightarrow$ index == DD_BLACK)
#define DD_IS_RED(p) ((p) $\rightarrow$ index == DD_RED)
#define DD_LEFT(p) cuddT(p)
#define DD_RIGHT(p) cuddE(p)
#define DD_NEXT(p) ((p) $\rightarrow$ next)
Functions
static void ddRehash ARGS ((DdManager *unique, int i))
static int ddResizeTable ARGS ((DdManager *unique, int index))
static int cuddFindParent ARGS ((DdManager *table, DdNode *node))
static DD_INLINE void ddFixLimits ARGS ((DdManager *unique))
static void cuddOrderedInsert ARGS ((DdNode **root, DdNode *node))
static DdNode *cuddOrderedThread ARGS ((DdNode *root, DdNode *list))
static void cuddRotateLeft ARGS ((DdNode **nodeP))
static void cuddDoRebalance ARGS ((DdNode ***stack, int stackN))
static void ddPatchTree ARGS ((DdManager *dd, MtrNode *treenode))
unsigned int Cudd_Prime (unsigned int p)
DdNode * cuddAllocNode (DdManager *unique)
DdManager * cuddInitTable (unsigned int numVars, unsigned int numVarsZ, unsigned int numSlots)
void cuddFreeTable (DdManager *unique)
int cuddGarbageCollect (DdManager *unique, int clearCache)
int cuddGarbageCollectZdd (DdManager *unique, int clearCache)
DdNode * cuddZddGetNode (DdManager *zdd, int id, DdNode *T, DdNode *E)
DdNode * cuddZddGetNodeIVO (DdManager *dd, int index, DdNode *g, DdNode *h)
DdNode * cuddUniqueInter (DdManager *unique, int index, DdNode *T, DdNode *E)
DdNode * cuddUniqueInterZdd (DdManager *unique, int index, DdNode *T, DdNode *E)
DdNode * cuddUniqueConst (DdManager *unique, CUDD_VALUE_TYPE value)
int cuddInsertSubtables (DdManager *unique, int n, int level)
int cuddDestroySubtables (DdManager *unique, int n)
int cuddResizeTableZdd (DdManager *unique, int index)
static void ddRehash (DdManager *unique, int i)
static void ddRehashZdd (DdManager *unique, int i)
static int ddResizeTable (DdManager *unique, int index)
static int cuddFindParent (DdManager *table, DdNode *node)
static DD_INLINE void ddFixLimits (DdManager *unique)
static void cuddOrderedInsert (DdNode **root, DdNode *node)
static DdNode * cuddOrderedThread (DdNode *root, DdNode *list)
static DD_INLINE void cuddRotateLeft (DdNode **nodeP)
static DD_INLINE void cuddRotateRight (DdNode **nodeP)
static void cuddDoRebalance (DdNode ***stack, int stackN)
static void ddPatchTree (DdManager *dd, MtrNode *treenode)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddTable.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define DD_BLACK 1
Definition at line 66 of file cuddTable.c.
Referenced by cuddDoRebalance().
#define DD_COLOR(p) ((p) $\rightarrow$ index)
Definition at line 103 of file cuddTable.c.
Referenced by cuddDoRebalance(), and cuddOrderedInsert().
#define DD_INSERT_COMPARE(x, y)
Value:
(((unsigned long) (x) & DD_PAGE_MASK) - \
         ((unsigned long) (y) & DD_PAGE_MASK))
Definition at line 69 of file cuddTable.c.
Referenced by cuddOrderedInsert().
#define DD_IS_BLACK(p) ((p) $\rightarrow$ index == DD_BLACK)
Definition at line 104 of file cuddTable.c.
Referenced by cuddDoRebalance().
#define DD_IS_RED(p) ((p) $\rightarrow$ index == DD_RED)
Definition at line 105 of file cuddTable.c.
Referenced by cuddDoRebalance().
#define DD_LEFT(p) cuddT(p)
Definition at line 106 of file cuddTable.c.
Referenced by cuddDoRebalance(), cuddOrderedInsert(), cuddOrderedThread(), cuddRotateLeft(), and cuddRotateRight().
#define DD_NEXT(p) ((p) $\rightarrow$ next)
Definition at line 108 of file cuddTable.c.
Referenced by cuddOrderedInsert(), and cuddOrderedThread().
#define DD_PAGE_MASK ~(DD_PAGE_SIZE - 1)
Definition at line 68 of file cuddTable.c.
#define DD_PAGE_SIZE 8192
Definition at line 67 of file cuddTable.c.
#define DD_RED 0
Definition at line 65 of file cuddTable.c.
Referenced by cuddDoRebalance(), and cuddOrderedInsert().
#define DD_RIGHT(p) cuddE(p)
Definition at line 107 of file cuddTable.c.
Referenced by cuddDoRebalance(), cuddOrderedInsert(), cuddOrderedThread(), cuddRotateLeft(), and cuddRotateRight().
#define DD_STACK_SIZE 128
CFile***********************************************************************
FileName [cuddTable.c]
PackageName [cudd]
Synopsis [Unique table management functions.]
Description [External procedures included in this module:
Cudd_Prime()
Internal procedures included in this module:
cuddAllocNode()
cuddInitTable()
cuddFreeTable()
cuddGarbageCollect()
cuddGarbageCollectZdd()
cuddZddGetNode()
cuddZddGetNodeIVO()
cuddUniqueInter()
cuddUniqueInterZdd()
cuddUniqueConst()
cuddInsertSubtables()
cuddDestroySubtables()
cuddResizeTableZdd()
Static procedures included in this module:
ddRehash()
ddRehashZdd()
ddResizeTable()
cuddFindParent()
cuddOrderedInsert()
cuddOrderedThread()
cuddRotateLeft()
cuddRotateRight()
cuddDoRebalance()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 64 of file cuddTable.c.
Referenced by cuddOrderedInsert().
Function Documentation
static void ddPatchTree ARGS ((DdManager *dd, MtrNode *treenode)) [static]
static void cuddDoRebalance ARGS ((DdNode ***stack, int stackN)) [static]
static void cuddRotateRight ARGS ((DdNode **nodeP)) [static]
static DdNode* cuddOrderedThread ARGS ((DdNode *root, DdNode *list)) [static]
static void cuddOrderedInsert ARGS ((DdNode **root, DdNode *node)) [static]
static DD_INLINE void ddFixLimits ARGS ((DdManager *unique)) [static]
static int cuddFindParent ARGS ((DdManager *table, DdNode *node)) [static]
static int ddResizeTable ARGS ((DdManager *unique, int index)) [static]
static void ddRehashZdd ARGS ((DdManager *unique, int i)) [static]
AutomaticStart
unsigned int Cudd_Prime (unsigned int p)
Function********************************************************************
Synopsis [Returns the next prime >= p.]
Description []
SideEffects [None]
Definition at line 155 of file cuddTable.c.
DdNode* cuddAllocNode (DdManager * unique)
Function********************************************************************
Synopsis [Fast storage allocation for DdNodes in the table.]
Description [Fast storage allocation for DdNodes in the table. The first 4 bytes of a chunk contain a pointer to the next block; the rest contains DD_MEM_CHUNK spaces for DdNodes. Returns a pointer to a new node if successful; NULL is memory is full.]
SideEffects [None]
SeeAlso [cuddDynamicAllocNode]
Definition at line 202 of file cuddTable.c.
References ALLOC, DdManager::allocated, assert, CUDD_MEMORY_OUT, cuddGarbageCollect(), DD_MEM_CHUNK, DdManager::memoryList, DdManager::memused, DdNode::next, and DdManager::nextFree.
Referenced by cuddUniqueConst(), cuddUniqueInter(), and cuddUniqueInterZdd().
int cuddDestroySubtables (DdManager * unique, int n)
Function********************************************************************
Synopsis [Destroys the n most recently created subtables in a unique table.]
Description [Destroys the n most recently created subtables in a unique table. n should be positive. The subtables should not contain any live nodes, except the (isolated) projection function. The projection functions are freed. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddInsertSubtables]
Definition at line 1623 of file cuddTable.c.
References assert, Cudd_RecursiveDeref(), cuddFindParent(), cuddGarbageCollect(), DD_MAXREF, DdSubtable::dead, DdManager::dead, FREE, DdManager::invperm, DdSubtable::keys, DdManager::keys, DdSubtable::maxKeys, DdManager::memused, DdSubtable::nodelist, DdManager::perm, DdNode::ref, DdSubtable::shift, DdManager::size, DdManager::slots, DdSubtable::slots, DdManager::subtables, and DdManager::vars.
static void cuddDoRebalance (DdNode *** stack, int stackN) [static]
Function********************************************************************
Synopsis [Rebalances a red/black tree.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 2658 of file cuddTable.c.
References cuddRotateLeft(), cuddRotateRight(), DD_BLACK, DD_COLOR, DD_IS_BLACK, DD_IS_RED, DD_LEFT, DD_RED, and DD_RIGHT.
Referenced by cuddOrderedInsert().
static int cuddFindParent (DdManager * table, DdNode * node) [static]
Function********************************************************************
Synopsis [Searches the subtables above node for a parent.]
Description [Searches the subtables above node for a parent. Returns 1 as soon as one parent is found. Returns 0 is the search is fruitless.]
SideEffects [None]
SeeAlso []
Definition at line 2408 of file cuddTable.c.
References Cudd_Regular, cuddE, cuddI, cuddT, DdNode::index, DdNode::next, DdSubtable::nodelist, DdSubtable::slots, and DdManager::subtables.
Referenced by cuddDestroySubtables().
void cuddFreeTable (DdManager * unique)
Function********************************************************************
Synopsis [Frees the resources associated to a unique table.]
Description []
SideEffects [None]
SeeAlso [cuddInitTable]
Definition at line 505 of file cuddTable.c.
References CUDD_POST_GC_HOOK, CUDD_POST_REORDERING_HOOK, CUDD_PRE_GC_HOOK, CUDD_PRE_REORDERING_HOOK, Cudd_RemoveHook(), cuddZddFreeUniv(), FREE, DdManager::memoryList, Mtr_FreeTree(), and DdManager::univ.
Referenced by Cudd_Quit().
int cuddGarbageCollect (DdManager * unique, int clearCache)
Function********************************************************************
Synopsis [Performs garbage collection on a unique table.]
Description [Performs garbage collection on a unique table. If clearCache is 0, the cache is not cleared. This should only be specified if the cache has been cleared right before calling cuddGarbageCollect. (As in the case of dynamic reordering.) Returns the total number of deleted nodes.]
SideEffects [None]
SeeAlso [cuddGarbageCollectZdd]
Definition at line 578 of file cuddTable.c.
References DdManager::allocated, DdManager::cache, DdManager::cachedeletions, DdManager::cacheSlots, Cudd_Regular, DdCache::data, DD_GC_PERCENT_HI, DD_GC_PERCENT_LO, DD_NON_CONSTANT, DdManager::dead, DdCache::f, DdCache::g, DdManager::garbageCollections, DdManager::gcPercent, DdCache::h, DdManager::keys, DdManager::looseUpTo, DdManager::minDead, DdHook::next, DdManager::preGCHook, DdManager::reclaimed, DdManager::slots, and util_cpu_time().
Referenced by cuddAllocNode(), cuddBddAlignToZdd(), cuddDestroySubtables(), cuddUniqueConst(), cuddUniqueInter(), ddRehash(), and ddReorderPreprocess().
int cuddGarbageCollectZdd (DdManager * unique, int clearCache)
Function********************************************************************
Synopsis [Performs garbage collection on a ZDD unique table.]
Description [Performs garbage collection on a ZDD unique table. If clearCache is 0, the cache is not cleared. This should only be specified if the cache has been cleared right before calling cuddGarbageCollectZdd. (As in the case of dynamic reordering.) Returns the total number of deleted nodes.]
SideEffects [None]
SeeAlso [cuddGarbageCollect]
Definition at line 803 of file cuddTable.c.
References DdManager::allocated, DdManager::cache, DdManager::cachedeletions, DdManager::cacheSlots, Cudd_Regular, DdCache::data, DD_GC_PERCENT_HI, DD_GC_PERCENT_LO, DD_NON_CONSTANT, DdManager::deadZ, DdCache::f, DdCache::g, DdManager::garbageCollections, DdManager::gcPercent, DdCache::h, DdManager::keysZ, DdManager::looseUpTo, DdManager::minDead, DdManager::reclaimed, DdManager::slots, and util_cpu_time().
Referenced by cuddUniqueInterZdd(), cuddZddAlignToBdd(), ddRehashZdd(), and zddReorderPreprocess().
DdManager* cuddInitTable (unsigned int numVars, unsigned int numVarsZ, unsigned int numSlots)
Function********************************************************************
Synopsis [Creates and initializes the unique table.]
Description [Creates and initializes the unique table. Returns a pointer to the table if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_Init cuddFreeTable]
Definition at line 274 of file cuddTable.c.
References ALLOC, DdManager::allocated, DdManager::arcviolation, DdManager::autoDyn, DdManager::autoDynZ, DdManager::autoMethod, DdManager::autoMethodZ, DdManager::constants, DdManager::countDead, CUDD_GROUP_CHECK7, CUDD_MEMORY_OUT, CUDD_NO_ERROR, CUDD_REORDER_SIFT, Cudd_SetLooseUpTo(), CUDD_UNIQUE_SLOTS, cuddComputeFloorLog2(), DD_DEFAULT_RECOMB, DD_DEFAULT_RESIZE, DD_EPSILON, DD_FIRST_REORDER, DD_GC_PERCENT_HI, DD_MAX_REORDER_GROWTH, DD_MAX_SUBTABLE_DENSITY, DD_SIFT_MAX_SWAPS, DD_SIFT_MAX_VAR, ddMax, DdSubtable::dead, DdManager::dead, DdManager::deadZ, DdManager::epsilon, DdManager::errorCode, DdManager::garbageCollections, DdManager::gcEnabled, DdManager::gcPercent, DdManager::GCTime, DdManager::groupcheck, DdManager::invperm, DdManager::invpermZ, DdSubtable::keys, DdManager::keys, DdManager::keysZ, DdManager::linear, DdManager::linearSize, DdManager::localCaches, DdManager::maxGrowth, DdSubtable::maxKeys, DdManager::maxSize, DdManager::maxSizeZ, DdManager::memoryList, DdManager::memused, DdManager::minDead, DdManager::nextDyn, DdManager::nextFree, DdSubtable::nodelist, DdManager::numberXovers, DdManager::perm, DdManager::permZ, DdManager::populationSize, DdManager::postGCHook, DdManager::postReorderingHook, DdManager::preGCHook, DdManager::preReorderingHook, DdManager::realign, DdManager::realignZ, DdManager::reclaimed, DdManager::recomb, DdManager::reordered, DdManager::reorderings, DdManager::reordTime, DdSubtable::shift, DdManager::siftMaxSwap, DdManager::siftMaxVar, DdManager::size, DdManager::sizeZ, DdSubtable::slots, DdManager::slots, DdManager::stack, DdManager::subtables, DdManager::subtableZ, DdManager::symmviolation, DdManager::tree, DdManager::treeZ, and DdManager::univ.
Referenced by Cudd_Init().
int cuddInsertSubtables (DdManager * unique, int n, int level)
Function********************************************************************
Synopsis [Inserts n new subtables in a unique table at level.]
Description [Inserts n new subtables in a unique table at level. The number n should be positive, and level should be an existing level. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddDestroySubtables]
Definition at line 1389 of file cuddTable.c.
References ALLOC, assert, DdManager::autoDyn, CUDD_MEMORY_OUT, Cudd_Not, CUDD_UNIQUE_SLOTS, cuddComputeFloorLog2(), cuddRef, cuddUniqueInter(), DD_DEFAULT_RESIZE, DD_MAX_SUBTABLE_DENSITY, ddFixLimits(), ddMax, DdSubtable::dead, DdManager::errorCode, FREE, DdManager::invperm, DdSubtable::keys, DdSubtable::maxKeys, DdManager::maxSize, DdManager::maxSizeZ, DdManager::memused, DdSubtable::nodelist, DdManager::one, one, DdManager::perm, DdSubtable::shift, DdManager::size, size, DdManager::slots, DdSubtable::slots, DdManager::stack, DdManager::subtables, DdManager::vars, and zero.
Referenced by Cudd_addNewVarAtLevel(), and Cudd_bddNewVarAtLevel().
static void cuddOrderedInsert (DdNode ** root, DdNode * node) [static]
Function********************************************************************
Synopsis [Inserts a DdNode in a red/black search tree.]
Description [Inserts a DdNode in a red/black search tree. Nodes from the same `page` (defined by DD_PAGE_MASK) are linked in a LIFO list.]
SideEffects [None]
SeeAlso [cuddOrderedThread]
Definition at line 2489 of file cuddTable.c.
References cuddDoRebalance(), DD_COLOR, DD_INSERT_COMPARE, DD_LEFT, DD_NEXT, DD_RED, DD_RIGHT, DD_STACK_SIZE, and scan.
static DdNode* cuddOrderedThread (DdNode * root, DdNode * list) [static]
Function********************************************************************
Synopsis [Threads all the nodes of a search tree into a linear list.]
Description [Threads all the nodes of a search tree into a linear list. For each node of the search tree, the `left` child, if non-null, has a lower address than its parent, and the `right` child, if non-null, has a higher address than its parent. The list is sorted in order of increasing addresses. The search tree is destroyed as a result of this operation. The last element of the linear list is made to point to the address passed in list. Each node if the search tree is a linearly-linked list of nodes from the same memory page (as defined in DD_PAGE_MASK). When a node is added to the linear list, all the elements of the linked list are added.]
SideEffects [The search tree is destroyed as a result of this operation.]
SeeAlso [cuddOrderedInsert]
Definition at line 2538 of file cuddTable.c.
References DD_LEFT, DD_NEXT, and DD_RIGHT.
int cuddResizeTableZdd (DdManager * unique, int index)
Function********************************************************************
Synopsis [Increases the number of ZDD subtables in a unique table so that it meets or exceeds index.]
Description [Increases the number of ZDD subtables in a unique table so that it meets or exceeds index. When new ZDD variables are created, it is possible to preserve the functions unchanged, or it is possible to preserve the covers unchanged, but not both. cuddResizeTableZdd preserves the covers. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [ddResizeTable]
Definition at line 1747 of file cuddTable.c.
References ALLOC, CUDD_MEMORY_OUT, CUDD_UNIQUE_SLOTS, cuddComputeFloorLog2(), cuddZddFreeUniv(), cuddZddInitUniv(), DD_DEFAULT_RESIZE, DD_MAX_SUBTABLE_DENSITY, ddFixLimits(), ddMax, DdSubtable::dead, DdManager::errorCode, FREE, DdManager::invpermZ, DdSubtable::keys, DdSubtable::maxKeys, DdManager::maxSize, DdManager::maxSizeZ, DdManager::memused, DdSubtable::nodelist, one, DdManager::permZ, DdSubtable::shift, DdManager::sizeZ, DdManager::slots, DdSubtable::slots, DdManager::stack, DdManager::subtableZ, and zero.
Referenced by Cudd_zddVarsFromBddVars(), and cuddUniqueInterZdd().
static DD_INLINE void cuddRotateLeft (DdNode ** nodeP) [static]
Function********************************************************************
Synopsis [Performs the left rotation for red/black trees.]
Description []
SideEffects [None]
SeeAlso [cuddRotateRight]
Definition at line 2607 of file cuddTable.c.
References DD_LEFT, and DD_RIGHT.
Referenced by cuddDoRebalance().
static DD_INLINE void cuddRotateRight (DdNode ** nodeP) [static]
Function********************************************************************
Synopsis [Performs the right rotation for red/black trees.]
Description []
SideEffects [None]
SeeAlso [cuddRotateLeft]
Definition at line 2633 of file cuddTable.c.
References DD_LEFT, and DD_RIGHT.
Referenced by cuddDoRebalance().
DdNode* cuddUniqueConst (DdManager * unique, CUDD_VALUE_TYPE value)
Function********************************************************************
Synopsis [Checks the unique table for the existence of a constant node.]
Description [Checks the unique table for the existence of a constant node. If it does not exist, it creates a new one. Does not modify the reference count of whatever is returned. A newly created internal node comes back with a reference count 0. Returns a pointer to the new node.]
SideEffects [None]
Definition at line 1301 of file cuddTable.c.
References hack::bits, DdManager::constants, CUDD_MAXINDEX, cuddAdjust, cuddAllocNode(), cuddGarbageCollect(), cuddReclaim(), ddAbs, ddEqualVal, ddHash, ddRehash(), DdSubtable::dead, DdManager::dead, DdManager::epsilon, DdManager::gcEnabled, DdNode::index, DdManager::keys, DdSubtable::keys, DdSubtable::maxKeys, DdManager::minDead, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdNode::type, DdNode::value, and hack::value.
Referenced by addMMRecur(), addTriangleRecur(), addWalshInt(), Cudd_addBddInterval(), Cudd_addBddIthBit(), Cudd_addBddStrictThreshold(), Cudd_addBddThreshold(), Cudd_addConst(), Cudd_addDivide(), Cudd_addExistAbstract(), Cudd_addHarwell(), Cudd_addIthBit(), Cudd_addMinus(), Cudd_addPlus(), Cudd_addRead(), Cudd_addResidue(), Cudd_addTimes(), Cudd_Init(), cuddAddNegateRecur(), cuddAddRoundOffRecur(), and cuddAddScalarInverseRecur().
DdNode* cuddUniqueInter (DdManager * unique, int index, DdNode * T, DdNode * E)
Function********************************************************************
Synopsis [Checks the unique table for the existence of an internal node.]
Description [Checks the unique table for the existence of an internal node. If it does not exist, it creates a new one. Does not modify the reference count of whatever is returned. A newly created internal node comes back with a reference count 0. For a newly created node, increments the reference counts of what T and E point to. Returns a pointer to the new node if successful; NULL if memory is exhausted or if reordering took place.]
SideEffects [None]
SeeAlso [cuddUniqueInterZdd]
Definition at line 1056 of file cuddTable.c.
References assert, Cudd_CheckKeys(), Cudd_DebugCheck(), Cudd_ReduceHeap(), Cudd_Regular, cuddAllocNode(), cuddE, cuddGarbageCollect(), cuddI, cuddReclaim(), cuddRef, cuddT, ddHash, ddRehash(), ddResizeTable(), DdSubtable::dead, DdNode::index, DdSubtable::keys, DdSubtable::maxKeys, DdNode::next, DdSubtable::nodelist, DdManager::perm, DdNode::ref, DdSubtable::shift, DdManager::size, and DdManager::subtables.
Referenced by addBddDoInterval(), addBddDoIthBit(), addBddDoPattern(), addBddDoStrictThreshold(), addBddDoThreshold(), addDoIthBit(), addTriangleRecur(), Cudd_addHarwell(), Cudd_addIthVar(), Cudd_addNewVar(), Cudd_addNewVarAtLevel(), Cudd_addRead(), Cudd_addResidue(), Cudd_bddIsVarEssential(), Cudd_bddIthVar(), Cudd_bddNewVar(), Cudd_bddRead(), Cudd_ClassifySupport(), Cudd_Init(), Cudd_PrioritySelect(), Cudd_Support(), Cudd_VectorSupport(), cuddAddApplyRecur(), cuddAddCmplRecur(), cuddAddComposeRecur(), cuddAddConstrainRecur(), cuddAddExistAbstractRecur(), cuddAddIteRecur(), cuddAddNegateRecur(), cuddAddOrAbstractRecur(), cuddAddPermuteRecur(), cuddAddRestrictRecur(), cuddAddRoundOffRecur(), cuddAddScalarInverseRecur(), cuddAddUnivAbstractRecur(), cuddBddAndAbstractRecur(), cuddBddAndRecur(), cuddBddClipAndAbsRecur(), cuddBddClippingAndRecur(), cuddBddConstrainRecur(), cuddBddIntersectRecur(), cuddBddIsop(), cuddBddIteRecur(), cuddBddLICBuildResult(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddTransferRecur(), cuddBddXorExistAbstractRecur(), cuddBddXorRecur(), cuddCofactorRecur(), cuddInsertSubtables(), cuddSplitSetRecur(), cuddZddIsop(), ddBddToAddRecur(), ddFindEssentialRecur(), ddResizeTable(), RAbuildSubset(), selectMintermsFromUniverse(), UAbuildSubset(), and zddPortToBddStep().
DdNode* cuddUniqueInterZdd (DdManager * unique, int index, DdNode * T, DdNode * E)
Function********************************************************************
Synopsis [Checks the unique table for the existence of an internal ZDD node.]
Description [Checks the unique table for the existence of an internal ZDD node. If it does not exist, it creates a new one. Does not modify the reference count of whatever is returned. A newly created internal node comes back with a reference count 0. For a newly created node, increments the reference counts of what T and E point to. Returns a pointer to the new node if successful; NULL if memory is exhausted or if reordering took place.]
SideEffects [None]
SeeAlso [cuddUniqueInter]
Definition at line 1183 of file cuddTable.c.
References assert, Cudd_CheckKeys(), Cudd_DebugCheck(), Cudd_Regular, Cudd_zddReduceHeap(), cuddAllocNode(), cuddE, cuddGarbageCollectZdd(), cuddIZ, cuddReclaimZdd(), cuddRef, cuddResizeTableZdd(), cuddT, ddHash, ddRehashZdd(), DdSubtable::dead, DdNode::index, DdSubtable::keys, DdSubtable::maxKeys, DdNode::next, DdSubtable::nodelist, DdManager::permZ, DdNode::ref, DdSubtable::shift, DdManager::sizeZ, and DdManager::subtableZ.
Referenced by Cudd_zddIthVar(), cuddZddChange(), cuddZddGetNode(), cuddZddGetNodeIVO(), cuddZddInitUniv(), cuddZddSubset0(), and cuddZddSubset1().
DdNode* cuddZddGetNode (DdManager * zdd, int id, DdNode * T, DdNode * E)
Function********************************************************************
Synopsis [Wrapper for cuddUniqueInterZdd.]
Description [Wrapper for cuddUniqueInterZdd, which applies the ZDD reduction rule. Returns a pointer to the result node under normal conditions; NULL if reordering occurred or memory was exhausted.]
SideEffects [None]
SeeAlso [cuddUniqueInterZdd]
Definition at line 969 of file cuddTable.c.
References cuddUniqueInterZdd(), and DD_ZERO.
Referenced by cuddZddChangeAux(), cuddZddDiff(), cuddZddIntersect(), cuddZddIte(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddUnion(), cuddZddWeakDivF(), zdd_subset0_aux(), zdd_subset1_aux(), and zddPortFromBddStep().
DdNode* cuddZddGetNodeIVO (DdManager * dd, int index, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Wrapper for cuddUniqueInterZdd that is independent of variable ordering.]
Description [Wrapper for cuddUniqueInterZdd that is independent of variable ordering (IVO). This function does not require parameter index to precede the indices of the top nodes of g and h in the variable order. Returns a pointer to the result node under normal conditions; NULL if reordering occurred or memory was exhausted.]
SideEffects [None]
SeeAlso [cuddZddGetNode cuddZddIsop]
Definition at line 1002 of file cuddTable.c.
References Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), cuddZddProduct(), cuddZddUnion(), DD_ONE, and DD_ZERO.
Referenced by cuddZddIsop().
static DD_INLINE void ddFixLimits (DdManager * unique) [static]
Function********************************************************************
Synopsis [Adjusts the values of table limits.]
Description [Adjusts the values of table fields controlling the. sizes of subtables and computed table. If the computed table is too small according to the new values, it is resized.]
SideEffects [Modifies manager fields. May resize computed table.]
SeeAlso []
Definition at line 2458 of file cuddTable.c.
References DdManager::cacheSlots, cuddCacheResize(), ddMax, ddMin, DdManager::gcPercent, DdManager::maxCache, DdManager::maxCacheHard, DdManager::minCache, DdManager::minDead, and DdManager::slots.
Referenced by cuddInsertSubtables(), cuddResizeTableZdd(), ddRehash(), ddRehashZdd(), and ddResizeTable().
static void ddPatchTree (DdManager * dd, MtrNode * treenode) [static]
Function********************************************************************
Synopsis [Fixes a variable tree after the insertion of new subtables.]
Description [Fixes a variable tree after the insertion of new subtables. After such an insertion, the low fields of the tree below the insertion point are inconsistent.]
SideEffects [None]
SeeAlso []
Definition at line 2736 of file cuddTable.c.
References MtrNode::child, MtrNode::index, MtrNode::low, DdManager::perm, and MtrNode::younger.
static void ddRehash (DdManager * unique, int i) [static]
Function********************************************************************
Synopsis [Rehashes a unique subtable.]
Description []
SideEffects [None]
SeeAlso [ddRehashZdd]
Definition at line 1924 of file cuddTable.c.
References ALLOC, DdManager::allocated, hack::bits, DdManager::constants, CUDD_MAXINDEX, Cudd_OutOfMem(), cuddE, cuddGarbageCollect(), cuddT, cuddV, DD_GC_PERCENT_HI, DD_GC_PERCENT_LO, DD_MAX_SUBTABLE_DENSITY, ddFixLimits(), ddHash, DdSubtable::dead, FREE, DdManager::gcPercent, DdSubtable::keys, DdManager::looseUpTo, DdSubtable::maxKeys, DdManager::memused, DdManager::minDead, MMoutOfMemory, DdNode::next, DdSubtable::nodelist, DdManager::reclaimed, DdSubtable::shift, DdManager::size, DdSubtable::slots, DdManager::slots, DdManager::subtables, and hack::value.
Referenced by cuddUniqueConst(), and cuddUniqueInter().
static void ddRehashZdd (DdManager * unique, int i) [static]
Function********************************************************************
Synopsis [Rehashes a ZDD unique subtable.]
Description []
SideEffects [None]
SeeAlso [ddRehash]
Definition at line 2101 of file cuddTable.c.
References ALLOC, DdManager::allocated, assert, CUDD_MAXINDEX, Cudd_OutOfMem(), cuddE, cuddGarbageCollectZdd(), cuddT, DD_GC_PERCENT_HI, DD_GC_PERCENT_LO, DD_MAX_SUBTABLE_DENSITY, ddFixLimits(), ddHash, DdSubtable::dead, FREE, DdManager::gcPercent, DdSubtable::keys, DdManager::looseUpTo, DdSubtable::maxKeys, DdManager::memused, DdManager::minDead, MMoutOfMemory, DdNode::next, DdSubtable::nodelist, DdManager::reclaimed, DdSubtable::shift, DdManager::sizeZ, DdSubtable::slots, DdManager::slots, and DdManager::subtableZ.
Referenced by cuddUniqueInterZdd().
static int ddResizeTable (DdManager * unique, int index) [static]
Function********************************************************************
Synopsis [Increases the number of subtables in a unique table so that it meets or exceeds index.]
Description [Increases the number of subtables in a unique table so that it meets or exceeds index. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddResizeTableZdd]
Definition at line 2215 of file cuddTable.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_Not, CUDD_UNIQUE_SLOTS, cuddComputeFloorLog2(), cuddRef, cuddUniqueInter(), DD_DEFAULT_RESIZE, DD_MAX_SUBTABLE_DENSITY, ddFixLimits(), ddMax, DdSubtable::dead, DdManager::errorCode, FREE, DdManager::invperm, DdSubtable::keys, DdSubtable::maxKeys, DdManager::maxSize, DdManager::maxSizeZ, DdManager::memused, DdSubtable::nodelist, one, DdManager::perm, DdSubtable::shift, DdManager::size, DdManager::slots, DdSubtable::slots, DdManager::stack, DdManager::subtables, DdManager::vars, and zero.
Referenced by cuddUniqueInter().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddTable.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 93 of file cuddTable.c.