cuddApprox.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct NodeData
struct ApproxInfo
struct GlobalQueueItem
struct LocalQueueItem
Defines
#define DBL_MAX_EXP 1024
#define NOTHING 0
#define REPLACE_T 1
#define REPLACE_E 2
#define REPLACE_N 3
#define REPLACE_TT 4
#define REPLACE_TE 5
Functions
static void updateParity ARGS ((DdNode *node, ApproxInfo *info, int newparity))
static NodeData *gatherInfoAux ARGS ((DdNode *node, ApproxInfo *info, int parity))
static ApproxInfo *gatherInfo ARGS ((DdManager *dd, DdNode *node, int numVars, int parity))
static int computeSavings ARGS ((DdManager *dd, DdNode *f, DdNode *skip, ApproxInfo *info, DdLevelQueue *queue))
static int UAmarkNodes ARGS ((DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, int safe, double quality))
static DdNode *UAbuildSubset ARGS ((DdManager *dd, DdNode *node, ApproxInfo *info))
static int RAmarkNodes ARGS ((DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, double quality))
DdNode * Cudd_UnderApprox (DdManager *dd, DdNode *f, int numVars, int threshold, int safe, double quality)
DdNode * Cudd_OverApprox (DdManager *dd, DdNode *f, int numVars, int threshold, int safe, double quality)
DdNode * Cudd_RemapUnderApprox (DdManager *dd, DdNode *f, int numVars, int threshold, double quality)
DdNode * Cudd_RemapOverApprox (DdManager *dd, DdNode *f, int numVars, int threshold, double quality)
DdNode * cuddUnderApprox (DdManager *dd, DdNode *f, int numVars, int threshold, int safe, double quality)
DdNode * cuddRemapUnderApprox (DdManager *dd, DdNode *f, int numVars, int threshold, double quality)
static void updateParity (DdNode *node, ApproxInfo *info, int newparity)
static NodeData * gatherInfoAux (DdNode *node, ApproxInfo *info, int parity)
static ApproxInfo * gatherInfo (DdManager *dd, DdNode *node, int numVars, int parity)
static int computeSavings (DdManager *dd, DdNode *f, DdNode *skip, ApproxInfo *info, DdLevelQueue *queue)
static int updateRefs (DdManager *dd, DdNode *f, DdNode *skip, ApproxInfo *info, DdLevelQueue *queue)
static int UAmarkNodes (DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, int safe, double quality)
static DdNode * UAbuildSubset (DdManager *dd, DdNode *node, ApproxInfo *info)
static int RAmarkNodes (DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, double quality)
static DdNode * RAbuildSubset (DdManager *dd, DdNode *node, ApproxInfo *info)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddApprox.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define DBL_MAX_EXP 1024
CFile***********************************************************************
FileName [cuddApprox.c]
PackageName [cudd]
Synopsis [Procedures to approximate a given BDD.]
Description [External procedures provided by this module:
Cudd_UnderApprox()
Cudd_OverApprox()
Cudd_RemapUnderApprox()
Cudd_RemapOverApprox()
Internal procedures included in this module:
cuddUnderApprox()
cuddRemapUnderApprox()
Static procedures included in this module:
gatherInfoAux()
gatherInfo()
computeSavings()
UAmarkNodes()
UAbuildSubset()
updateRefs()
RAmarkNodes()
RAbuildSubset()
]
SeeAlso [cuddSubsetHB.c cuddSubsetSP.c cuddGenCof.c]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 51 of file cuddApprox.c.
Referenced by cuddSubsetHeavyBranch(), and gatherInfo().
#define NOTHING 0
Definition at line 61 of file cuddApprox.c.
Referenced by RAmarkNodes().
#define REPLACE_E 2
Definition at line 63 of file cuddApprox.c.
Referenced by RAbuildSubset(), and RAmarkNodes().
#define REPLACE_N 3
Definition at line 64 of file cuddApprox.c.
Referenced by RAbuildSubset(), and RAmarkNodes().
#define REPLACE_T 1
Definition at line 62 of file cuddApprox.c.
Referenced by RAbuildSubset(), and RAmarkNodes().
#define REPLACE_TE 5
Definition at line 66 of file cuddApprox.c.
Referenced by RAbuildSubset(), and RAmarkNodes().
#define REPLACE_TT 4
Definition at line 65 of file cuddApprox.c.
Referenced by RAbuildSubset(), and RAmarkNodes().
Function Documentation
static int RAmarkNodes ARGS ((DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, double quality)) [static]
static DdNode *RAbuildSubset ARGS ((DdManager *dd, DdNode *node, ApproxInfo *info)) [static]
static int UAmarkNodes ARGS ((DdManager *dd, DdNode *f, ApproxInfo *info, int threshold, int safe, double quality)) [static]
static int updateRefs ARGS ((DdManager *dd, DdNode *f, DdNode *skip, ApproxInfo *info, DdLevelQueue *queue)) [static]
static ApproxInfo* gatherInfo ARGS ((DdManager *dd, DdNode *node, int numVars, int parity)) [static]
static NodeData* gatherInfoAux ARGS ((DdNode *node, ApproxInfo *info, int parity)) [static]
static void updateParity ARGS ((DdNode *node, ApproxInfo *info, int newparity)) [static]
AutomaticStart
static int computeSavings (DdManager * dd, DdNode * f, DdNode * skip, ApproxInfo * info, DdLevelQueue * queue) [static]
Function********************************************************************
Synopsis [Counts the nodes that would be eliminated if a given node were replaced by zero.]
Description [Counts the nodes that would be eliminated if a given node were replaced by zero. This procedure uses a queue passed by the caller for efficiency: since the queue is left empty at the endof the search, it can be reused as is by the next search. Returns the count (always striclty positive) if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddUnderApprox]
Definition at line 748 of file cuddApprox.c.
References assert, Cudd_IsConstant, Cudd_Regular, cuddE, cuddI, cuddLevelQueueDequeue(), cuddLevelQueueEnqueue(), cuddT, DdLevelQueue::first, DdNode::index, LocalQueueItem::localRef, LocalQueueItem::node, DdLevelQueue::size, st_lookup(), and ApproxInfo::table.
Referenced by RAmarkNodes(), and UAmarkNodes().
DdNode* Cudd_OverApprox (DdManager * dd, DdNode * f, int numVars, int threshold, int safe, double quality)
Function********************************************************************
Synopsis [Extracts a dense superset from a BDD with Shiple's underapproximation method.]
Description [Extracts a dense superset from a BDD. The procedure is identical to the underapproximation procedure except for the fact that it works on the complement of the given function. Extracting the subset of the complement function is equivalent to extracting the superset of the function. Returns a pointer to the BDD of the superset if successful. NULL if intermediate result causes the procedure to run out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SupersetHeavyBranch Cudd_SupersetShortPaths Cudd_ReadSize]
Definition at line 236 of file cuddApprox.c.
References Cudd_Not, Cudd_NotCond, cuddUnderApprox(), and DdManager::reordered.
DdNode* Cudd_RemapOverApprox (DdManager * dd, DdNode * f, int numVars, int threshold, double quality)
Function********************************************************************
Synopsis [Extracts a dense superset from a BDD with Shiple's underapproximation method.]
Description [Extracts a dense superset from a BDD. The procedure is identical to the underapproximation procedure except for the fact that it works on the complement of the given function. Extracting the subset of the complement function is equivalent to extracting the superset of the function. Returns a pointer to the BDD of the superset if successful. NULL if intermediate result causes the procedure to run out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SupersetHeavyBranch Cudd_SupersetShortPaths Cudd_ReadSize]
Definition at line 326 of file cuddApprox.c.
References Cudd_Not, Cudd_NotCond, cuddRemapUnderApprox(), and DdManager::reordered.
Referenced by Cudd_bddApproxConjDecomp(), Cudd_bddIterConjDecomp(), and Cudd_bddMinimize().
DdNode* Cudd_RemapUnderApprox (DdManager * dd, DdNode * f, int numVars, int threshold, double quality)
Function********************************************************************
Synopsis [Extracts a dense subset from a BDD with remapping underapproximation method.]
Description [Extracts a dense subset from a BDD. This procedure uses a remapping technique and density as the cost function. Returns a pointer to the BDD of the subset if successful. NULL if the procedure runs out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will cause overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SubsetShortPaths Cudd_SubsetHeavyBranch Cudd_UnderApprox Cudd_ReadSize]
Definition at line 281 of file cuddApprox.c.
References cuddRemapUnderApprox(), and DdManager::reordered.
Referenced by Cudd_SubsetCompress().
DdNode* Cudd_UnderApprox (DdManager * dd, DdNode * f, int numVars, int threshold, int safe, double quality)
Function********************************************************************
Synopsis [Extracts a dense subset from a BDD with Shiple's underapproximation method.]
Description [Extracts a dense subset from a BDD. This procedure uses a variant of Tom Shiple's underapproximation method. The main difference from the original method is that density is used as cost function. Returns a pointer to the BDD of the subset if successful. NULL if the procedure runs out of memory. The parameter numVars is the maximum number of variables to be used in minterm calculation. The optimal number should be as close as possible to the size of the support of f. However, it is safe to pass the value returned by Cudd_ReadSize for numVars when the number of variables is under 1023. If numVars is larger than 1023, it will cause overflow. If a 0 parameter is passed then the procedure will compute a value which will avoid overflow but will cause underflow with 2046 variables or more.]
SideEffects [None]
SeeAlso [Cudd_SubsetShortPaths Cudd_SubsetHeavyBranch Cudd_ReadSize]
Definition at line 189 of file cuddApprox.c.
References cuddUnderApprox(), and DdManager::reordered.
DdNode* cuddRemapUnderApprox (DdManager * dd, DdNode * f, int numVars, int threshold, double quality)
Function********************************************************************
Synopsis [Applies the remapping underappoximation algorithm.]
Description [Applies the remapping underappoximation algorithm. Proceeds in three phases:
collect information on each node in the BDD; this is done via DFS.
traverse the BDD in top-down fashion and compute for each node whether remapping increases density.
traverse the BDD via DFS and actually perform the elimination.
Returns the approximated BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_RemapUnderApprox]
Definition at line 458 of file cuddApprox.c.
References Cudd_bddLeq(), Cudd_CheckKeys(), Cudd_DagSize(), Cudd_DebugCheck(), Cudd_IsConstant, cuddDeref, cuddRef, FREE, gatherInfo(), ApproxInfo::page, RAbuildSubset(), RAmarkNodes(), result, ApproxInfo::size, st_free_table(), ApproxInfo::table, and TRUE.
Referenced by Cudd_RemapOverApprox(), and Cudd_RemapUnderApprox().
DdNode* cuddUnderApprox (DdManager * dd, DdNode * f, int numVars, int threshold, int safe, double quality)
Function********************************************************************
Synopsis [Applies Tom Shiple's underappoximation algorithm.]
Description [Applies Tom Shiple's underappoximation algorithm. Proceeds in three phases:
collect information on each node in the BDD; this is done via DFS.
traverse the BDD in top-down fashion and compute for each node whether its elimination increases density.
traverse the BDD via DFS and actually perform the elimination.
Returns the approximated BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_UnderApprox]
Definition at line 371 of file cuddApprox.c.
References Cudd_bddLeq(), Cudd_CheckKeys(), Cudd_DagSize(), Cudd_DebugCheck(), Cudd_IsConstant, cuddDeref, cuddRef, FREE, gatherInfo(), ApproxInfo::page, result, ApproxInfo::size, st_free_table(), ApproxInfo::table, UAbuildSubset(), and UAmarkNodes().
Referenced by Cudd_OverApprox(), and Cudd_UnderApprox().
static ApproxInfo* gatherInfo (DdManager * dd, DdNode * node, int numVars, int parity) [static]
Function********************************************************************
Synopsis [Gathers information about each node.]
Description [Counts minterms and computes reference counts of each node in the BDD . The minterm count is separately computed for the node and its complement. This is to avoid cancellation errors. Returns a pointer to the data structure holding the information gathered if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddUnderApprox gatherInfoAux]
Definition at line 654 of file cuddApprox.c.
References ALLOC, Cudd_DagSize(), Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Not, DBL_MAX_EXP, DD_ONE, DdManager::errorCode, FREE, NodeData::functionRef, gatherInfoAux(), ApproxInfo::index, ApproxInfo::max, memset(), ApproxInfo::minterms, NodeData::mintermsN, NodeData::mintermsP, LocalQueueItem::node, ApproxInfo::one, ApproxInfo::page, ApproxInfo::size, st_free_table(), st_init_table(), st_insert(), ST_OUT_OF_MEM, st_ptrcmp(), st_ptrhash(), ApproxInfo::table, and ApproxInfo::zero.
Referenced by cuddRemapUnderApprox(), and cuddUnderApprox().
static NodeData* gatherInfoAux (DdNode * node, ApproxInfo * info, int parity) [static]
Function********************************************************************
Synopsis [Recursively counts minterms and computes reference counts of each node in the BDD.]
Description [Recursively counts minterms and computes reference counts of each node in the BDD. Similar to the cuddCountMintermAux which recursively counts the number of minterms for the dag rooted at each node in terms of the total number of variables (max). It assumes that the node pointer passed to it is regular and it maintains the invariant.]
SideEffects [None]
SeeAlso [gatherInfo]
Definition at line 584 of file cuddApprox.c.
References Cudd_IsComplement, Cudd_NotCond, Cudd_Regular, cuddE, cuddT, NodeData::functionRef, ApproxInfo::index, NodeData::mintermsN, NodeData::mintermsP, LocalQueueItem::node, ApproxInfo::page, st_insert(), st_lookup(), ST_OUT_OF_MEM, ApproxInfo::table, and updateParity().
Referenced by gatherInfo().
static DdNode* RAbuildSubset (DdManager * dd, DdNode * node, ApproxInfo * info) [static]
Function********************************************************************
Synopsis [Builds the subset BDD for cuddRemapUnderApprox.]
Description [Builds the subset BDDfor cuddRemapUnderApprox. Based on the info table, performs remapping or replacement at selected nodes. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddRemapUnderApprox]
Definition at line 1432 of file cuddApprox.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), LocalQueueItem::node, ApproxInfo::one, REPLACE_E, REPLACE_N, REPLACE_T, REPLACE_TE, REPLACE_TT, st_lookup(), ApproxInfo::table, and ApproxInfo::zero.
Referenced by cuddRemapUnderApprox().
static int RAmarkNodes (DdManager * dd, DdNode * f, ApproxInfo * info, int threshold, double quality) [static]
Function********************************************************************
Synopsis [Marks nodes for remapping.]
Description [Marks nodes for remapping. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddRemapUnderApprox]
Definition at line 1118 of file cuddApprox.c.
References assert, computeSavings(), Cudd_bddLeq(), Cudd_IsComplement, Cudd_IsConstant, Cudd_NotCond, Cudd_Regular, CUDD_UNIQUE_SLOTS, cuddE, cuddI, cuddLevelQueueDequeue(), cuddLevelQueueEnqueue(), cuddLevelQueueInit(), cuddLevelQueueQuit(), cuddT, DdLevelQueue::first, GlobalQueueItem::impactN, GlobalQueueItem::impactP, DdNode::index, ApproxInfo::minterms, GlobalQueueItem::node, LocalQueueItem::node, NOTHING, REPLACE_E, REPLACE_N, REPLACE_T, REPLACE_TE, REPLACE_TT, DdManager::size, ApproxInfo::size, st_lookup(), ApproxInfo::table, and updateRefs().
Referenced by cuddRemapUnderApprox().
static DdNode* UAbuildSubset (DdManager * dd, DdNode * node, ApproxInfo * info) [static]
Function********************************************************************
Synopsis [Builds the subset BDD.]
Description [Builds the subset BDD. Based on the info table, replaces selected nodes by zero. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddUnderApprox]
Definition at line 1025 of file cuddApprox.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), LocalQueueItem::node, st_lookup(), ApproxInfo::table, TRUE, and ApproxInfo::zero.
Referenced by cuddUnderApprox().
static int UAmarkNodes (DdManager * dd, DdNode * f, ApproxInfo * info, int threshold, int safe, double quality) [static]
Function********************************************************************
Synopsis [Marks nodes for replacement by zero.]
Description [Marks nodes for replacement by zero. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddUnderApprox]
Definition at line 901 of file cuddApprox.c.
References assert, computeSavings(), Cudd_IsComplement, Cudd_IsConstant, Cudd_Regular, CUDD_UNIQUE_SLOTS, cuddE, cuddI, cuddLevelQueueDequeue(), cuddLevelQueueEnqueue(), cuddLevelQueueInit(), cuddLevelQueueQuit(), cuddT, DdLevelQueue::first, GlobalQueueItem::impactN, GlobalQueueItem::impactP, DdNode::index, ApproxInfo::minterms, GlobalQueueItem::node, LocalQueueItem::node, DdManager::size, ApproxInfo::size, st_lookup(), ApproxInfo::table, TRUE, and updateRefs().
Referenced by cuddUnderApprox().
static void updateParity (DdNode * node, ApproxInfo * info, int newparity) [static]
Function********************************************************************
Synopsis [Recursively update the parity of the paths reaching a node.]
Description [Recursively update the parity of the paths reaching a node. Assumes that node is regular and propagates the invariant.]
SideEffects [None]
SeeAlso [gatherInfoAux]
Definition at line 542 of file cuddApprox.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, cuddE, cuddT, LocalQueueItem::node, st_lookup(), and ApproxInfo::table.
Referenced by gatherInfoAux().
static int updateRefs (DdManager * dd, DdNode * f, DdNode * skip, ApproxInfo * info, DdLevelQueue * queue) [static]
Function********************************************************************
Synopsis [Update function reference counts.]
Description [Update function reference counts to account for replacement. Returns the number of nodes saved if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [UAmarkNodes RAmarkNodes]
Definition at line 820 of file cuddApprox.c.
References assert, Cudd_IsConstant, Cudd_Regular, cuddE, cuddI, cuddLevelQueueDequeue(), cuddLevelQueueEnqueue(), cuddT, DdLevelQueue::first, DdNode::index, LocalQueueItem::node, DdLevelQueue::size, st_lookup(), and ApproxInfo::table.
Referenced by RAmarkNodes(), and UAmarkNodes().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddApprox.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 134 of file cuddApprox.c.