cuddInit.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define CUDD_MAIN
Functions
DdManager * Cudd_Init (unsigned int numVars, unsigned int numVarsZ, unsigned int numSlots, unsigned int cacheSize, unsigned long maxMemory)
void Cudd_Quit (DdManager *unique)
int cuddZddInitUniv (DdManager *zdd)
void cuddZddFreeUniv (DdManager *zdd)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddInit.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define CUDD_MAIN
CFile***********************************************************************
FileName [cuddInit.c]
PackageName [cudd]
Synopsis [Functions to initialize and shut down the DD manager.]
Description [External procedures included in this module:
Cudd_Init()
Cudd_Quit()
Internal procedures included in this module:
cuddZddInitUniv()
cuddZddFreeUniv()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 35 of file cuddInit.c.
Function Documentation
DdManager* Cudd_Init (unsigned int numVars, unsigned int numVarsZ, unsigned int numSlots, unsigned int cacheSize, unsigned long maxMemory)
Function********************************************************************
Synopsis [Creates a new DD manager.]
Description [Creates a new DD manager, initializes the table, the basic constants and the projection functions. If maxMemory is 0, Cudd_Init decides suitable values for the maximum size of the cache and for the limit for fast unique table growth based on the available memory. Returns a pointer to the manager if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_Quit]
Definition at line 98 of file cuddInit.c.
References ALLOC, DdManager::background, CUDD_MEMORY_OUT, Cudd_Not, Cudd_SetLooseUpTo(), cuddInitCache(), cuddInitTable(), cuddRef, cuddUniqueConst(), cuddUniqueInter(), cuddZddInitUniv(), DD_MAX_CACHE_FRACTION, DD_MAX_LOOSE_FRACTION, DD_MINUS_INF_VAL, DD_PLUS_INF_VAL, DdManager::errorCode, getSoftDataLimit(), DdManager::maxSize, DdManager::minusinfinity, DdManager::one, one, DdManager::plusinfinity, result, DdManager::size, DdManager::sizeZ, DdManager::vars, DdManager::zero, and zero.
void Cudd_Quit (DdManager * unique)
Function********************************************************************
Synopsis [Deletes resources associated with a DD manager.]
Description [Deletes resources associated with a DD manager and resets the global statistical counters. (Otherwise, another manaqger subsequently created would inherit the stats of this one.)]
SideEffects [None]
SeeAlso [Cudd_Init]
Definition at line 193 of file cuddInit.c.
References cuddFreeTable().
void cuddZddFreeUniv (DdManager * zdd)
Function********************************************************************
Synopsis [Frees the ZDD universe.]
Description [Frees the ZDD universe.]
SideEffects [None]
SeeAlso [cuddZddInitUniv]
Definition at line 275 of file cuddInit.c.
References Cudd_RecursiveDerefZdd(), FREE, and DdManager::univ.
Referenced by cuddFreeTable(), and cuddResizeTableZdd().
int cuddZddInitUniv (DdManager * zdd)
Function********************************************************************
Synopsis [Initializes the ZDD universe.]
Description [Initializes the ZDD universe. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddZddFreeUniv]
Definition at line 219 of file cuddInit.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_RecursiveDerefZdd(), cuddDeref, cuddRef, cuddUniqueInterZdd(), cuddZddP(), DD_ONE, DdManager::errorCode, FREE, DdManager::invpermZ, DdManager::sizeZ, and DdManager::univ.
Referenced by Cudd_Init(), and cuddResizeTableZdd().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddInit.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 59 of file cuddInit.c.