cuddBddIte.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static void bddVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *one))
static int bddVarToCanonical ARGS ((DdManager *dd, DdNode **fp, DdNode **gp, DdNode **hp, unsigned int *topfp, unsigned int *topgp, unsigned int *tophp))
DdNode * Cudd_bddIte (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * Cudd_bddIteConstant (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * Cudd_bddIntersect (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddAnd (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddOr (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddNand (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddNor (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddXor (DdManager *dd, DdNode *f, DdNode *g)
DdNode * Cudd_bddXnor (DdManager *dd, DdNode *f, DdNode *g)
int Cudd_bddLeq (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddBddIteRecur (DdManager *dd, DdNode *f, DdNode *g, DdNode *h)
DdNode * cuddBddIntersectRecur (DdManager *dd, DdNode *f, DdNode *g)
DdNode * cuddBddAndRecur (DdManager *manager, DdNode *f, DdNode *g)
DdNode * cuddBddXorRecur (DdManager *manager, DdNode *f, DdNode *g)
static void bddVarToConst (DdNode *f, DdNode **gp, DdNode **hp, DdNode *one)
static int bddVarToCanonical (DdManager *dd, DdNode **fp, DdNode **gp, DdNode **hp, unsigned int *topfp, unsigned int *topgp, unsigned int *tophp)
static int bddVarToCanonicalSimple (DdManager *dd, DdNode **fp, DdNode **gp, DdNode **hp, unsigned int *topfp, unsigned int *topgp, unsigned int *tophp)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddBddIte.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int bddVarToCanonicalSimple ARGS ((DdManager *dd, DdNode **fp, DdNode **gp, DdNode **hp, unsigned int *topfp, unsigned int *topgp, unsigned int *tophp)) [static]
static void bddVarToConst ARGS ((DdNode *f, DdNode **gp, DdNode **hp, DdNode *one)) [static]
AutomaticStart
static int bddVarToCanonical (DdManager * dd, DdNode ** fp, DdNode ** gp, DdNode ** hp, unsigned int * topfp, unsigned int * topgp, unsigned int * tophp) [static]
Function********************************************************************
Synopsis [Picks unique member from equiv expressions.]
Description [Reduces 2 variable expressions to canonical form.]
SideEffects [None]
SeeAlso [bddVarToConst bddVarToCanonicalSimple]
Definition at line 1086 of file cuddBddIte.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddI, DdNode::index, DdManager::one, and one.
Referenced by Cudd_bddIteConstant().
static int bddVarToCanonicalSimple (DdManager * dd, DdNode ** fp, DdNode ** gp, DdNode ** hp, unsigned int * topfp, unsigned int * topgp, unsigned int * tophp) [static]
Function********************************************************************
Synopsis [Picks unique member from equiv expressions.]
Description [Reduces 2 variable expressions to canonical form.]
SideEffects [None]
SeeAlso [bddVarToConst bddVarToCanonical]
Definition at line 1184 of file cuddBddIte.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddI, DdNode::index, and DdManager::perm.
Referenced by cuddBddIteRecur().
static void bddVarToConst (DdNode * f, DdNode ** gp, DdNode ** hp, DdNode * one) [static]
Function********************************************************************
Synopsis [Replaces variables with constants if possible.]
Description [This function performs part of the transformation to standard form by replacing variables with constants if possible.]
SideEffects [None]
SeeAlso [bddVarToCanonical bddVarToCanonicalSimple]
Definition at line 1051 of file cuddBddIte.c.
References Cudd_Not, and one.
Referenced by Cudd_bddIteConstant().
DdNode* Cudd_bddAnd (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the conjunction of two BDDs f and g.]
Description [Computes the conjunction of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAndAbstract Cudd_bddIntersect Cudd_bddOr Cudd_bddNand Cudd_bddNor Cudd_bddXor Cudd_bddXnor]
Definition at line 283 of file cuddBddIte.c.
References cuddBddAndRecur(), and DdManager::reordered.
Referenced by Cudd_bddComputeCube(), Cudd_bddIterConjDecomp(), Cudd_bddRead(), Cudd_ClassifySupport(), Cudd_IndicesToCube(), Cudd_PrioritySelect(), Cudd_Support(), Cudd_VectorSupport(), Cudd_Xeqy(), Cudd_Xgty(), and cuddBddAndRecur().
DdNode* Cudd_bddIntersect (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Returns a function included in the intersection of f and g.]
Description [Computes a function included in the intersection of f and g. (That is, a witness that the intersection is not empty.) Cudd_bddIntersect tries to build as few new nodes as possible. If the only result of interest is whether f and g intersect, Cudd_bddLeq should be used instead.]
SideEffects [None]
SeeAlso [Cudd_bddLeq Cudd_bddIteConstant]
Definition at line 251 of file cuddBddIte.c.
References cuddBddIntersectRecur(), and DdManager::reordered.
Referenced by cuddBddIntersectRecur().
DdNode* Cudd_bddIte (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements ITE(f,g,h).]
Description [Implements ITE(f,g,h). Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_addIte Cudd_bddIteConstant Cudd_bddIntersect]
Definition at line 113 of file cuddBddIte.c.
References cuddBddIteRecur(), and DdManager::reordered.
Referenced by Cudd_addHamming(), Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneMinterm(), Cudd_Dxygtdxz(), Cudd_Dxygtdyz(), Cudd_Xeqy(), Cudd_Xgty(), and cuddBddIteRecur().
DdNode* Cudd_bddIteConstant (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements ITEconstant(f,g,h).]
Description [Implements ITEconstant(f,g,h). Returns a pointer to the resulting BDD (which may or may not be constant) or DD_NON_CONSTANT. No new nodes are created.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_bddIntersect Cudd_bddLeq Cudd_addIteConstant]
Definition at line 144 of file cuddBddIte.c.
References bddVarToCanonical(), bddVarToConst(), Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddCacheInsert(), cuddConstantLookup(), cuddE, cuddT, DD_NON_CONSTANT, DD_ONE, ddMin, one, and zero.
Referenced by Cudd_bddIsVarEssential(), and cuddSubsetShortPaths().
int Cudd_bddLeq (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Determines whether f is less than or equal to g.]
Description [Returns 1 if f is less than or equal to g; 0 otherwise. No new nodes are created.]
SideEffects [None]
SeeAlso [Cudd_bddIteConstant Cudd_addEvalConst]
Definition at line 469 of file cuddBddIte.c.
References Cudd_IsComplement, Cudd_Not, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddE, cuddT, DD_ONE, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneMinterm(), Cudd_bddVarIsDependent(), Cudd_Decreasing(), cuddBddClippingAndRecur(), cuddBddSqueeze(), cuddConjunctsAux(), cuddRemapUnderApprox(), cuddSubsetHeavyBranch(), cuddUnderApprox(), and RAmarkNodes().
DdNode* Cudd_bddNand (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the NAND of two BDDs f and g.]
Description [Computes the NAND of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAnd Cudd_bddOr Cudd_bddNor Cudd_bddXor Cudd_bddXnor]
Definition at line 346 of file cuddBddIte.c.
References Cudd_NotCond, cuddBddAndRecur(), and DdManager::reordered.
DdNode* Cudd_bddNor (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the NOR of two BDDs f and g.]
Description [Computes the NOR of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAnd Cudd_bddOr Cudd_bddNand Cudd_bddXor Cudd_bddXnor]
Definition at line 378 of file cuddBddIte.c.
References Cudd_Not, cuddBddAndRecur(), and DdManager::reordered.
DdNode* Cudd_bddOr (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the disjunction of two BDDs f and g.]
Description [Computes the disjunction of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAnd Cudd_bddNand Cudd_bddNor Cudd_bddXor Cudd_bddXnor]
Definition at line 314 of file cuddBddIte.c.
References Cudd_Not, Cudd_NotCond, cuddBddAndRecur(), and DdManager::reordered.
Referenced by Cudd_bddVarConjDecomp().
DdNode* Cudd_bddXnor (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the exclusive NOR of two BDDs f and g.]
Description [Computes the exclusive NOR of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAnd Cudd_bddOr Cudd_bddNand Cudd_bddNor Cudd_bddXor]
Definition at line 440 of file cuddBddIte.c.
References Cudd_Not, cuddBddXorRecur(), and DdManager::reordered.
DdNode* Cudd_bddXor (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Computes the exclusive OR of two BDDs f and g.]
Description [Computes the exclusive OR of two BDDs f and g. Returns a pointer to the resulting BDD if successful; NULL if the intermediate result blows up.]
SideEffects [None]
SeeAlso [Cudd_bddIte Cudd_addApply Cudd_bddAnd Cudd_bddOr Cudd_bddNand Cudd_bddNor Cudd_bddXnor]
Definition at line 409 of file cuddBddIte.c.
References cuddBddXorRecur(), and DdManager::reordered.
Referenced by cuddBddXorRecur().
DdNode* cuddBddAndRecur (DdManager * manager, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_bddAnd.]
Description [Implements the recursive step of Cudd_bddAnd by taking the conjunction of two BDDs. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddAnd]
Definition at line 814 of file cuddBddIte.c.
References Cudd_bddAnd(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, one, DdManager::perm, DdNode::ref, and zero.
Referenced by Cudd_bddAnd(), Cudd_bddNand(), Cudd_bddNor(), Cudd_bddOr(), cuddBddAndAbstractRecur(), cuddBddConstrainDecomp(), cuddBddExistAbstractRecur(), cuddBddIsop(), cuddBddIteRecur(), cuddBddLiteralSetIntersectionRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddXorExistAbstractRecur(), cuddCProjectionRecur(), cuddSplitSetRecur(), cuddZddIsop(), ddFindEssentialRecur(), get_cube(), get_path(), mintermsFromUniverse(), and ZeroCase().
DdNode* cuddBddIntersectRecur (DdManager * dd, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_bddIntersect.]
Description []
SideEffects [None]
SeeAlso [Cudd_bddIntersect]
Definition at line 700 of file cuddBddIte.c.
References Cudd_bddIntersect(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_bddIntersect().
DdNode* cuddBddIteRecur (DdManager * dd, DdNode * f, DdNode * g, DdNode * h)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_bddIte.]
Description [Implements the recursive step of Cudd_bddIte. Returns a pointer to the resulting BDD. NULL if the intermediate result blows up or if reordering occurs.]
SideEffects [None]
SeeAlso []
Definition at line 566 of file cuddBddIte.c.
References bddVarToCanonicalSimple(), Cudd_bddIte(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddBddAndRecur(), cuddCacheInsert(), cuddCacheLookup(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, ddMin, DdNode::index, one, and zero.
Referenced by BuildConjuncts(), BuildSubsetBdd(), Cudd_bddIte(), cuddBddBooleanDiffRecur(), cuddBddCharToVect(), cuddBddComposeRecur(), cuddBddExistAbstractRecur(), cuddBddPermuteRecur(), cuddBddTransferRecur(), cuddBddVectorComposeRecur(), cuddCProjectionRecur(), cuddSolveEqnRecur(), cuddSplitSetRecur(), mintermsFromUniverse(), and zddPortToBddStep().
DdNode* cuddBddXorRecur (DdManager * manager, DdNode * f, DdNode * g)
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_bddXor.]
Description [Implements the recursive step of Cudd_bddXor by taking the exclusive OR of two BDDs. Returns a pointer to the result is successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddXor]
Definition at line 931 of file cuddBddIte.c.
References Cudd_bddXor(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_bddXnor(), Cudd_bddXor(), cuddBddBooleanDiffRecur(), and cuddBddXorExistAbstractRecur().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddBddIte.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddBddIte.c]
PackageName [cudd]
Synopsis [BDD ITE function and satellites.]
Description [External procedures included in this module:
Cudd_bddIte()
Cudd_bddIteConstant()
Cudd_bddIntersect()
Cudd_bddAnd()
Cudd_bddOr()
Cudd_bddNand()
Cudd_bddNor()
Cudd_bddXor()
Cudd_bddXnor()
Cudd_bddLeq()
Internal procedures included in this module:
cuddBddIteRecur()
cuddBddIntersectRecur()
cuddBddAndRecur()
cuddBddXorRecur()
Static procedures included in this module:
bddVarToConst()
bddVarToCanonical()
bddVarToCanonicalSimple()
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 73 of file cuddBddIte.c.