cuddApa.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static DdApaNumber cuddApaCountMintermAux ARGS ((DdNode *node, int digits, DdApaNumber max, DdApaNumber min, st_table *table))
static enum st_retval cuddApaStCountfree ARGS ((char *key, char *value, char *arg))
int Cudd_ApaNumberOfDigits (int binaryDigits)
DdApaNumber Cudd_NewApaNumber (int digits)
void Cudd_ApaCopy (int digits, DdApaNumber source, DdApaNumber dest)
DdApaDigit Cudd_ApaAdd (int digits, DdApaNumber a, DdApaNumber b, DdApaNumber sum)
DdApaDigit Cudd_ApaSubtract (int digits, DdApaNumber a, DdApaNumber b, DdApaNumber diff)
DdApaDigit Cudd_ApaShortDivision (int digits, DdApaNumber dividend, DdApaDigit divisor, DdApaNumber quotient)
unsigned int Cudd_ApaIntDivision (int digits, DdApaNumber dividend, unsigned int divisor, DdApaNumber quotient)
void Cudd_ApaShiftRight (int digits, DdApaDigit in, DdApaNumber a, DdApaNumber b)
void Cudd_ApaSetToLiteral (int digits, DdApaNumber number, DdApaDigit literal)
void Cudd_ApaPowerOfTwo (int digits, DdApaNumber number, int power)
int Cudd_ApaCompare (int digitsFirst, DdApaNumber first, int digitsSecond, DdApaNumber second)
int Cudd_ApaCompareRatios (int digitsFirst, DdApaNumber firstNum, unsigned int firstDen, int digitsSecond, DdApaNumber secondNum, unsigned int secondDen)
int Cudd_ApaPrintHex (FILE *fp, int digits, DdApaNumber number)
int Cudd_ApaPrintDecimal (FILE *fp, int digits, DdApaNumber number)
int Cudd_ApaPrintExponential (FILE *fp, int digits, DdApaNumber number, int precision)
DdApaNumber Cudd_ApaCountMinterm (DdManager *manager, DdNode *node, int nvars, int *digits)
int Cudd_ApaPrintMinterm (FILE *fp, DdManager *dd, DdNode *node, int nvars)
int Cudd_ApaPrintMintermExp (FILE *fp, DdManager *dd, DdNode *node, int nvars, int precision)
int Cudd_ApaPrintDensity (FILE *fp, DdManager *dd, DdNode *node, int nvars)
static DdApaNumber cuddApaCountMintermAux (DdNode *node, int digits, DdApaNumber max, DdApaNumber min, st_table *table)
static enum st_retval cuddApaStCountfree (char *key, char *value, char *arg)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddApa.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static DdNode * background
static DdNode * zero
Function Documentation
static enum st_retval cuddApaStCountfree ARGS ((char *key, char *value, char *arg)) [static]
static DdApaNumber cuddApaCountMintermAux ARGS ((DdNode *node, int digits, DdApaNumber max, DdApaNumber min, st_table *table)) [static]
AutomaticStart
DdApaDigit Cudd_ApaAdd (int digits, DdApaNumber a, DdApaNumber b, DdApaNumber sum)
Function********************************************************************
Synopsis [Adds two arbitrary precision integers.]
Description [Adds two arbitrary precision integers. Returns the carry out of the most significant digit.]
SideEffects [The result of the sum is stored in parameter sum.]
SeeAlso []
Definition at line 171 of file cuddApa.c.
References DD_LSDIGIT, and DD_MSDIGIT.
Referenced by cuddApaCountMintermAux().
int Cudd_ApaCompare (int digitsFirst, DdApaNumber first, int digitsSecond, DdApaNumber second)
Function********************************************************************
Synopsis [Compares two arbitrary precision integers.]
Description [Compares two arbitrary precision integers. Returns 1 if the first number is larger; 0 if they are equal; -1 if the second number is larger.]
SideEffects [None]
SeeAlso []
Definition at line 399 of file cuddApa.c.
Referenced by Cudd_ApaCompareRatios().
int Cudd_ApaCompareRatios (int digitsFirst, DdApaNumber firstNum, unsigned int firstDen, int digitsSecond, DdApaNumber secondNum, unsigned int secondDen)
Function********************************************************************
Synopsis [Compares the ratios of two arbitrary precision integers to two unsigned ints.]
Description [Compares the ratios of two arbitrary precision integers to two unsigned ints. Returns 1 if the first number is larger; 0 if they are equal; -1 if the second number is larger.]
SideEffects [None]
SeeAlso []
Definition at line 439 of file cuddApa.c.
References Cudd_ApaCompare(), Cudd_ApaIntDivision(), Cudd_NewApaNumber(), and result.
void Cudd_ApaCopy (int digits, DdApaNumber source, DdApaNumber dest)
Function********************************************************************
Synopsis [Makes a copy of an arbitrary precision integer.]
Description [Makes a copy of an arbitrary precision integer.]
SideEffects [Changes parameter dest.]
SeeAlso []
Definition at line 144 of file cuddApa.c.
Referenced by Cudd_ApaCountMinterm(), Cudd_ApaPrintDecimal(), and Cudd_ApaPrintExponential().
DdApaNumber Cudd_ApaCountMinterm (DdManager * manager, DdNode * node, int nvars, int * digits)
Function********************************************************************
Synopsis [Counts the number of minterms of a DD.]
Description [Counts the number of minterms of a DD. The function is assumed to depend on nvars variables. The minterm count is represented as an arbitrary precision unsigned integer, to allow for any number of variables CUDD supports. Returns a pointer to the array representing the number of minterms of the function rooted at node if successful; NULL otherwise.]
SideEffects [The number of digits of the result is returned in parameter digits.]
SeeAlso [Cudd_CountMinterm]
Definition at line 632 of file cuddApa.c.
References DdManager::background, background, Cudd_ApaCopy(), Cudd_ApaNumberOfDigits(), Cudd_ApaPowerOfTwo(), Cudd_ApaSetToLiteral(), Cudd_ApaSubtract(), Cudd_IsComplement, Cudd_NewApaNumber(), Cudd_Not, Cudd_Regular, cuddApaCountMintermAux(), cuddApaStCountfree(), FREE, DdGen::manager, max, DdGen::node, DdManager::one, st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and zero.
Referenced by Cudd_ApaPrintDensity(), Cudd_ApaPrintMinterm(), and Cudd_ApaPrintMintermExp().
unsigned int Cudd_ApaIntDivision (int digits, DdApaNumber dividend, unsigned int divisor, DdApaNumber quotient)
Function********************************************************************
Synopsis [Divides an arbitrary precision integer by an integer.]
Description [Divides an arbitrary precision integer by a 32-bit unsigned integer. Returns the remainder of the division. This procedure relies on the assumption that the number of bits of a DdApaDigit plus the number of bits of an unsigned int is less the number of bits of the mantissa of a double. This guarantees that the product of a DdApaDigit and an unsigned int can be represented without loss of precision by a double. On machines where this assumption is not satisfied, this procedure will malfunction.]
SideEffects [The quotient is returned in parameter quotient.]
SeeAlso [Cudd_ApaShortDivision]
Definition at line 274 of file cuddApa.c.
References DD_APA_BASE.
Referenced by Cudd_ApaCompareRatios(), and Cudd_ApaPrintDensity().
int Cudd_ApaNumberOfDigits (int binaryDigits)
Function********************************************************************
Synopsis [Finds the number of digits for an arbitrary precision integer.]
Description [Finds the number of digits for an arbitrary precision integer given the maximum number of binary digits. The number of binary digits should be positive. Returns the number of digits if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 97 of file cuddApa.c.
References DD_APA_BITS.
Referenced by Cudd_ApaCountMinterm().
void Cudd_ApaPowerOfTwo (int digits, DdApaNumber number, int power)
Function********************************************************************
Synopsis [Sets an arbitrary precision integer to a power of two.]
Description [Sets an arbitrary precision integer to a power of two. If the power of two is too large to be represented, the number is set to 0.]
SideEffects [The result is returned in parameter number.]
SeeAlso []
Definition at line 367 of file cuddApa.c.
References DD_APA_BITS.
Referenced by Cudd_ApaCountMinterm().
int Cudd_ApaPrintDecimal (FILE * fp, int digits, DdApaNumber number)
Function********************************************************************
Synopsis [Prints an arbitrary precision integer in decimal format.]
Description [Prints an arbitrary precision integer in decimal format. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_ApaPrintHex Cudd_ApaPrintExponential]
Definition at line 510 of file cuddApa.c.
References ALLOC, Cudd_ApaCopy(), Cudd_ApaShortDivision(), Cudd_NewApaNumber(), DD_APA_BASE, FREE, and result.
Referenced by Cudd_ApaPrintDensity(), and Cudd_ApaPrintMinterm().
int Cudd_ApaPrintDensity (FILE * fp, DdManager * dd, DdNode * node, int nvars)
Function********************************************************************
Synopsis [Prints the density of a BDD or ADD using arbitrary precision arithmetic.]
Description [Prints the density of a BDD or ADD using arbitrary precision arithmetic. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 786 of file cuddApa.c.
References Cudd_ApaCountMinterm(), Cudd_ApaIntDivision(), Cudd_ApaPrintDecimal(), Cudd_DagSize(), Cudd_NewApaNumber(), FREE, DdGen::node, result, and size.
int Cudd_ApaPrintExponential (FILE * fp, int digits, DdApaNumber number, int precision)
Function********************************************************************
Synopsis [Prints an arbitrary precision integer in exponential format.]
Description [Prints an arbitrary precision integer in exponential format. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_ApaPrintHex Cudd_ApaPrintDecimal]
Definition at line 567 of file cuddApa.c.
References ALLOC, Cudd_ApaCopy(), Cudd_ApaShortDivision(), Cudd_NewApaNumber(), DD_APA_BASE, ddMin, FREE, and result.
Referenced by Cudd_ApaPrintMintermExp().
int Cudd_ApaPrintHex (FILE * fp, int digits, DdApaNumber number)
Function********************************************************************
Synopsis [Prints an arbitrary precision integer in hexadecimal format.]
Description [Prints an arbitrary precision integer in hexadecimal format. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_ApaPrintDecimal Cudd_ApaPrintExponential]
Definition at line 480 of file cuddApa.c.
References DD_APA_HEXPRINT, and result.
int Cudd_ApaPrintMinterm (FILE * fp, DdManager * dd, DdNode * node, int nvars)
Function********************************************************************
Synopsis [Prints the number of minterms of a BDD or ADD using arbitrary precision arithmetic.]
Description [Prints the number of minterms of a BDD or ADD using arbitrary precision arithmetic. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_ApaPrintMintermExp]
Definition at line 709 of file cuddApa.c.
References Cudd_ApaCountMinterm(), Cudd_ApaPrintDecimal(), FREE, DdGen::node, and result.
int Cudd_ApaPrintMintermExp (FILE * fp, DdManager * dd, DdNode * node, int nvars, int precision)
Function********************************************************************
Synopsis [Prints the number of minterms of a BDD or ADD in exponential format using arbitrary precision arithmetic.]
Description [Prints the number of minterms of a BDD or ADD in exponential format using arbitrary precision arithmetic. Parameter precision controls the number of signficant digits printed. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [Cudd_ApaPrintMinterm]
Definition at line 748 of file cuddApa.c.
References Cudd_ApaCountMinterm(), Cudd_ApaPrintExponential(), FREE, DdGen::node, and result.
void Cudd_ApaSetToLiteral (int digits, DdApaNumber number, DdApaDigit literal)
Function********************************************************************
Synopsis [Sets an arbitrary precision integer to a one-digit literal.]
Description [Sets an arbitrary precision integer to a one-digit literal.]
SideEffects [The result is returned in parameter number.]
SeeAlso []
Definition at line 339 of file cuddApa.c.
Referenced by Cudd_ApaCountMinterm().
void Cudd_ApaShiftRight (int digits, DdApaDigit in, DdApaNumber a, DdApaNumber b)
Function********************************************************************
Synopsis [Shifts right an arbitrary precision integer by one binary place.]
Description [Shifts right an arbitrary precision integer by one binary place. The most significant binary digit of the result is taken from parameter in.]
SideEffects [The result is returned in parameter b.]
SeeAlso []
Definition at line 311 of file cuddApa.c.
References DD_APA_BITS.
Referenced by cuddApaCountMintermAux().
DdApaDigit Cudd_ApaShortDivision (int digits, DdApaNumber dividend, DdApaDigit divisor, DdApaNumber quotient)
Function********************************************************************
Synopsis [Divides an arbitrary precision integer by a digit.]
Description [Divides an arbitrary precision integer by a digit.]
SideEffects [The quotient is returned in parameter quotient.]
SeeAlso []
Definition at line 233 of file cuddApa.c.
References DD_APA_BASE.
Referenced by Cudd_ApaPrintDecimal(), and Cudd_ApaPrintExponential().
DdApaDigit Cudd_ApaSubtract (int digits, DdApaNumber a, DdApaNumber b, DdApaNumber diff)
Function********************************************************************
Synopsis [Subtracts two arbitrary precision integers.]
Description [Subtracts two arbitrary precision integers. Returns the borrow out of the most significant digit.]
SideEffects [The result of the subtraction is stored in parameter diff.]
SeeAlso []
Definition at line 203 of file cuddApa.c.
References DD_APA_BASE, DD_APA_MASK, DD_LSDIGIT, and DD_MSDIGIT.
Referenced by Cudd_ApaCountMinterm(), and cuddApaCountMintermAux().
DdApaNumber Cudd_NewApaNumber (int digits)
Function********************************************************************
Synopsis [Allocates memory for an arbitrary precision integer.]
Description [Allocates memory for an arbitrary precision integer. Returns a pointer to the allocated memory if successful; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 124 of file cuddApa.c.
References ALLOC.
Referenced by Cudd_ApaCompareRatios(), Cudd_ApaCountMinterm(), Cudd_ApaPrintDecimal(), Cudd_ApaPrintDensity(), Cudd_ApaPrintExponential(), and cuddApaCountMintermAux().
static DdApaNumber cuddApaCountMintermAux (DdNode * node, int digits, DdApaNumber max, DdApaNumber min, st_table * table) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_ApaCountMinterm.]
Description [Performs the recursive step of Cudd_ApaCountMinterm. It is based on the following identity. Let |f| be the number of minterms of f. Then: <xmp> |f| = (|f0|+|f1|)/2 </xmp> where f0 and f1 are the two cofactors of f. Uses the identity |f'| = max - |f|. Returns the number of minterms of the function rooted at node.]
SideEffects [None]
Definition at line 843 of file cuddApa.c.
References background, Cudd_ApaAdd(), Cudd_ApaShiftRight(), Cudd_ApaSubtract(), Cudd_IsComplement, Cudd_NewApaNumber(), Cudd_Regular, cuddE, cuddIsConstant, cuddT, FREE, DdGen::node, DdNode::ref, st_insert(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by Cudd_ApaCountMinterm().
static enum st_retval cuddApaStCountfree (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees the memory used to store the minterm counts recorded in the visited table.]
Description [Frees the memory used to store the minterm counts recorded in the visited table. Returns ST_CONTINUE.]
SideEffects [None]
Definition at line 908 of file cuddApa.c.
References FREE, and ST_CONTINUE.
Referenced by Cudd_ApaCountMinterm().
Variable Documentation
DdNode* background [static]
Definition at line 57 of file cuddApa.c.
Referenced by Cudd_ApaCountMinterm(), Cudd_CountMinterm(), Cudd_PrintMinterm(), cuddApaCountMintermAux(), ddCountMintermAux(), and ddPrintMintermAux().
char rcsid [] DD_UNUSED = `$Id: cuddApa.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddApa.c]
PackageName [cudd]
Synopsis [Arbitrary precision arithmetic functions.]
Description [External procedures included in this module:
Internal procedures included in this module:
()
Static procedures included in this module:
()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 54 of file cuddApa.c.
DdNode * zero [static]
Definition at line 57 of file cuddApa.c.
Referenced by addMMRecur(), addVarToConst(), BuildConjuncts(), BuildSubsetBdd(), CountMinterms(), Cudd_addComputeCube(), Cudd_addEvalConst(), Cudd_addHarwell(), Cudd_addIteConstant(), Cudd_addRead(), Cudd_addXeqy(), Cudd_ApaCountMinterm(), Cudd_bddGenConjDecomp(), Cudd_bddIsVarEssential(), Cudd_bddIteConstant(), Cudd_bddLeq(), Cudd_bddPickArbitraryMinterms(), Cudd_bddPickOneMinterm(), Cudd_bddRead(), Cudd_bddVarIsDependent(), Cudd_Cofactor(), Cudd_CountMinterm(), Cudd_Dxygtdxz(), Cudd_Dxygtdyz(), Cudd_Init(), Cudd_LargestCube(), Cudd_PrintMinterm(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), cuddAddCmplRecur(), cuddAddConstrainRecur(), cuddAddExistAbstractRecur(), cuddAddIteRecur(), cuddAddRestrictRecur(), cuddAddUnivAbstractRecur(), cuddApaCountMintermAux(), cuddBddAndAbstractRecur(), cuddBddAndRecur(), cuddBddCharToVect(), cuddBddClipAndAbsRecur(), cuddBddClippingAndRecur(), cuddBddConstrainRecur(), cuddBddIntersectRecur(), cuddBddIsop(), cuddBddIteRecur(), cuddBddLICBuildResult(), cuddBddLICMarkEdges(), cuddBddLICompaction(), cuddBddLiteralSetIntersectionRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddTransferRecur(), cuddBddXorExistAbstractRecur(), cuddBddXorRecur(), cuddCheckCube(), cuddCofactorRecur(), cuddInsertSubtables(), cuddResizeTableZdd(), cuddSplitSetRecur(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddDivide(), cuddZddDivideF(), cuddZddGetCofactors3(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddWeakDiv(), cuddZddWeakDivF(), ddCountMintermAux(), ddPrintMintermAux(), ddResizeTable(), get_largest(), get_shortest(), mintermsFromUniverse(), selectMintermsFromUniverse(), SubsetCountMintermAux(), SubsetCountNodesAux(), zddPortToBddStep(), and ZeroCase().