cuddEssent.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Functions
static DdNode *ddFindEssentialRecur ARGS ((DdManager *dd, DdNode *f))
DdNode * Cudd_FindEssential (DdManager *dd, DdNode *f)
int Cudd_bddIsVarEssential (DdManager *manager, DdNode *f, int id, int phase)
static DdNode * ddFindEssentialRecur (DdManager *dd, DdNode *f)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddEssent.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static DdNode* ddFindEssentialRecur ARGS ((DdManager *dd, DdNode *f)) [static]
AutomaticStart
int Cudd_bddIsVarEssential (DdManager * manager, DdNode * f, int id, int phase)
Function********************************************************************
Synopsis [Determines whether a given variable is essential with a given phase in a BDD.]
Description [Determines whether a given variable is essential with a given phase in a BDD. Uses Cudd_bddIteConstant. Returns 1 if phase == 1 and f-->x_id, or if phase == 0 and f-->x_id'.]
SideEffects [None]
SeeAlso [Cudd_FindEssential]
Definition at line 119 of file cuddEssent.c.
References Cudd_bddIteConstant(), Cudd_Not, Cudd_NotCond, cuddUniqueInter(), DD_ONE, one, and zero.
DdNode* Cudd_FindEssential (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Finds the essential variables of a DD.]
Description [Returns the cube of the essential variables. A positive literal means that the variable must be set to 1 for the function to be 1. A negative literal means that the variable must be set to 0 for the function to be 1. Returns a pointer to the cube BDD if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddIsVarEssential]
Definition at line 89 of file cuddEssent.c.
References ddFindEssentialRecur(), and DdManager::reordered.
Referenced by ddFindEssentialRecur().
static DdNode* ddFindEssentialRecur (DdManager * dd, DdNode * f) [static]
Function********************************************************************
Synopsis [Implements the recursive step of Cudd_FindEssential.]
Description [Implements the recursive step of Cudd_FindEssential. Returns a pointer to the cube BDD if successful; NULL otherwise.]
SideEffects [None]
Definition at line 164 of file cuddEssent.c.
References Cudd_FindEssential(), Cudd_IsComplement, Cudd_IsConstant, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddBddLiteralSetIntersectionRecur(), cuddCacheInsert1(), cuddCacheLookup1(), cuddDeref, cuddE, cuddIsConstant, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, one, and DdManager::vars.
Referenced by Cudd_FindEssential().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddEssent.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddEssent.c]
PackageName [cudd]
Synopsis [Functions for the detection of essential variables.]
Description [External procedures included in this file:
Cudd_FindEssential()
Cudd_bddIsVarEssential()
Static procedures included in this module:
ddFindEssentialRecur()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 50 of file cuddEssent.c.