cuddLevelQ.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define lqHash(key, shift) (((unsigned)(key) * DD_P1) >> (shift))
Functions
static DdQueueItem *hashLookup ARGS ((DdLevelQueue *queue, void *key))
static int hashInsert ARGS ((DdLevelQueue *queue, DdQueueItem *item))
static int hashResize ARGS ((DdLevelQueue *queue))
DdLevelQueue * cuddLevelQueueInit (int levels, int itemSize, int numBuckets)
void cuddLevelQueueQuit (DdLevelQueue *queue)
void * cuddLevelQueueEnqueue (DdLevelQueue *queue, void *key, int level)
void cuddLevelQueueDequeue (DdLevelQueue *queue, int level)
static DdQueueItem * hashLookup (DdLevelQueue *queue, void *key)
static int hashInsert (DdLevelQueue *queue, DdQueueItem *item)
static void hashDelete (DdLevelQueue *queue, DdQueueItem *item)
static int hashResize (DdLevelQueue *queue)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddLevelQ.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define lqHash(key, shift) (((unsigned)(key) * DD_P1) >> (shift))
Macro***********************************************************************
Synopsis [Hash function for the table of a level queue.]
Description [Hash function for the table of a level queue.]
SideEffects [None]
SeeAlso [hashInsert hashLookup hashDelete]
Definition at line 99 of file cuddLevelQ.c.
Referenced by hashDelete(), hashInsert(), hashLookup(), and hashResize().
Function Documentation
static int hashResize ARGS ((DdLevelQueue *queue)) [static]
static void hashDelete ARGS ((DdLevelQueue *queue, DdQueueItem *item)) [static]
static DdQueueItem* hashLookup ARGS ((DdLevelQueue *queue, void *key)) [static]
AutomaticStart
void cuddLevelQueueDequeue (DdLevelQueue * queue, int level)
Function********************************************************************
Synopsis [Remove an item from the front of a level queue.]
Description [Remove an item from the front of a level queue.]
SideEffects [None]
SeeAlso [cuddLevelQueueEnqueue]
Definition at line 325 of file cuddLevelQ.c.
References DdLevelQueue::first, DdLevelQueue::freelist, hashDelete(), DdLevelQueue::last, DdQueueItem::next, and DdLevelQueue::size.
Referenced by computeSavings(), RAmarkNodes(), UAmarkNodes(), and updateRefs().
void* cuddLevelQueueEnqueue (DdLevelQueue * queue, void * key, int level)
Function********************************************************************
Synopsis [Inserts a new key in a level queue.]
Description [Inserts a new key in a level queue. A new entry is created in the queue only if the node is not already enqueued. Returns a pointer to the queue item if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddLevelQueueInit cuddLevelQueueDequeue]
Definition at line 253 of file cuddLevelQ.c.
References ALLOC, assert, DdLevelQueue::first, DdLevelQueue::freelist, hashInsert(), hashLookup(), DdLevelQueue::itemsize, DdLevelQueue::last, memset(), DdQueueItem::next, and DdLevelQueue::size.
Referenced by computeSavings(), RAmarkNodes(), UAmarkNodes(), and updateRefs().
DdLevelQueue* cuddLevelQueueInit (int levels, int itemSize, int numBuckets)
Function********************************************************************
Synopsis [Initializes a level queue.]
Description [Initializes a level queue. A level queue is a queue where inserts are based on the levels of the nodes. Within each level the policy is FIFO. Level queues are useful in traversing a BDD top-down. Queue items are kept in a free list when dequeued for efficiency. Returns a pointer to the new queue if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddLevelQueueQuit cuddLevelQueueEnqueue cuddLevelQueueDequeue]
Definition at line 140 of file cuddLevelQ.c.
References ALLOC, DdLevelQueue::buckets, cuddComputeFloorLog2(), DD_MAX_SUBTABLE_DENSITY, DdLevelQueue::first, FREE, DdLevelQueue::freelist, DdLevelQueue::itemsize, DdLevelQueue::last, DdLevelQueue::levels, DdLevelQueue::maxsize, memset(), DdLevelQueue::numBuckets, DdLevelQueue::shift, and DdLevelQueue::size.
Referenced by RAmarkNodes(), and UAmarkNodes().
void cuddLevelQueueQuit (DdLevelQueue * queue)
Function********************************************************************
Synopsis [Shuts down a level queue.]
Description [Shuts down a level queue and releases all the associated memory.]
SideEffects [None]
SeeAlso [cuddLevelQueueInit]
Definition at line 215 of file cuddLevelQ.c.
References DdLevelQueue::buckets, DdLevelQueue::first, FREE, DdLevelQueue::freelist, DdLevelQueue::last, and DdQueueItem::next.
Referenced by RAmarkNodes(), and UAmarkNodes().
static void hashDelete (DdLevelQueue * queue, DdQueueItem * item) [static]
Function********************************************************************
Synopsis [Removes an item from the hash table of a level queue.]
Description [Removes an item from the hash table of a level queue. Nothing is done if the item is not in the table.]
SideEffects [None]
SeeAlso [cuddLevelQueueDequeue hashInsert]
Definition at line 438 of file cuddLevelQ.c.
References DdLevelQueue::buckets, DdQueueItem::cnext, DdQueueItem::key, lqHash, and DdLevelQueue::shift.
Referenced by cuddLevelQueueDequeue().
static int hashInsert (DdLevelQueue * queue, DdQueueItem * item) [static]
Function********************************************************************
Synopsis [Inserts an item in the hash table of a level queue.]
Description [Inserts an item in the hash table of a level queue. Returns 1 if successful; 0 otherwise. No check is performed to see if an item with the same key is already in the hash table.]
SideEffects [None]
SeeAlso [cuddLevelQueueEnqueue]
Definition at line 404 of file cuddLevelQ.c.
References DdLevelQueue::buckets, DdQueueItem::cnext, hashResize(), DdQueueItem::key, lqHash, DdLevelQueue::maxsize, result, DdLevelQueue::shift, and DdLevelQueue::size.
Referenced by cuddLevelQueueEnqueue().
static DdQueueItem* hashLookup (DdLevelQueue * queue, void * key) [static]
Function********************************************************************
Synopsis [Looks up a key in the hash table of a level queue.]
Description [Looks up a key in the hash table of a level queue. Returns a pointer to the item with the given key if the key is found; NULL otherwise.]
SideEffects [None]
SeeAlso [cuddLevelQueueEnqueue hashInsert]
Definition at line 369 of file cuddLevelQ.c.
References DdLevelQueue::buckets, DdQueueItem::cnext, DdQueueItem::key, lqHash, and DdLevelQueue::shift.
Referenced by cuddLevelQueueEnqueue().
static int hashResize (DdLevelQueue * queue) [static]
Function********************************************************************
Synopsis [Resizes the hash table of a level queue.]
Description [Resizes the hash table of a level queue. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [hashInsert]
Definition at line 479 of file cuddLevelQ.c.
References ALLOC, DdLevelQueue::buckets, DdQueueItem::cnext, Cudd_OutOfMem(), FREE, DdQueueItem::key, lqHash, DdLevelQueue::maxsize, memset(), MMoutOfMemory, DdLevelQueue::numBuckets, and DdLevelQueue::shift.
Referenced by hashInsert().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddLevelQ.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddLevelQ.c]
PackageName [cudd]
Synopsis [Procedure to manage level queues.]
Description [The functions in this file allow an application to easily manipulate a queue where nodes are prioritized by level. The emphasis is on efficiency. Therefore, the queue items can have variable size. If the application does not need to attach information to the nodes, it can declare the queue items to be of type DdQueueItem. Otherwise, it can declare them to be of a structure type such that the first three fields are data pointers. The third pointer points to the node. The first two pointers are used by the level queue functions. The remaining fields are initialized to 0 when a new item is created, and are then left to the exclusive use of the application. On the DEC Alphas the three pointers must be 32-bit pointers when CUDD is compiled with 32-bit pointers. The level queue functions make sure that each node appears at most once in the queue. They do so by keeping a hash table where the node is used as key. Queue items are recycled via a free list for efficiency.
Internal procedures provided by this module:
cuddLevelQueueInit()
cuddLevelQueueQuit()
cuddLevelQueueEnqueue()
cuddLevelQueueDequeue()
Static procedures included in this module:
hashLookup()
hashInsert()
hashDelete()
hashResize()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 76 of file cuddLevelQ.c.