cuddDecomp.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct Conjuncts
struct NodeStat
Defines
#define DEPTH 5
#define THRESHOLD 10
#define NONE 0
#define PAIR_ST 1
#define PAIR_CR 2
#define G_ST 3
#define G_CR 4
#define H_ST 5
#define H_CR 6
#define BOTH_G 7
#define BOTH_H 8
#define FactorsNotStored(factors) ((int)((long)(factors) & 01))
#define FactorsComplement(factors) ((Conjuncts *)((long)(factors) | 01))
#define FactorsUncomplement(factors) ((Conjuncts *)((long)(factors) ^ 01))
Functions
static NodeStat *CreateBotDist ARGS ((DdNode *node, st_table *distanceTable))
static double CountMinterms ARGS ((DdNode *node, double max, st_table *mintermTable))
static void ConjunctsFree ARGS ((DdManager *dd, Conjuncts *factors))
static int PairInTables ARGS ((DdNode *g, DdNode *h, st_table *ghTable))
static Conjuncts *CheckTablesCacheAndReturn ARGS ((DdNode *node, DdNode *g, DdNode *h, st_table *ghTable, st_table *cacheTable))
static Conjuncts *PickOnePair ARGS ((DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable))
static Conjuncts *CheckInTables ARGS ((DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable, int *outOfMem))
static Conjuncts *ZeroCase ARGS ((DdManager *dd, DdNode *node, Conjuncts *factorsNv, st_table *ghTable, st_table *cacheTable, int switched))
static Conjuncts *BuildConjuncts ARGS ((DdManager *dd, DdNode *node, st_table *distanceTable, st_table *cacheTable, int approxDistance, int maxLocalRef, st_table *ghTable, st_table *mintermTable))
static int cuddConjunctsAux ARGS ((DdManager *dd, DdNode *f, DdNode **c1, DdNode **c2))
int Cudd_bddApproxConjDecomp (DdManager *dd, DdNode *f, DdNode ***conjuncts)
int Cudd_bddApproxDisjDecomp (DdManager *dd, DdNode *f, DdNode ***disjuncts)
int Cudd_bddIterConjDecomp (DdManager *dd, DdNode *f, DdNode ***conjuncts)
int Cudd_bddIterDisjDecomp (DdManager *dd, DdNode *f, DdNode ***disjuncts)
int Cudd_bddGenConjDecomp (DdManager *dd, DdNode *f, DdNode ***conjuncts)
int Cudd_bddGenDisjDecomp (DdManager *dd, DdNode *f, DdNode ***disjuncts)
int Cudd_bddVarConjDecomp (DdManager *dd, DdNode *f, DdNode ***conjuncts)
int Cudd_bddVarDisjDecomp (DdManager *dd, DdNode *f, DdNode ***disjuncts)
static NodeStat * CreateBotDist (DdNode *node, st_table *distanceTable)
static double CountMinterms (DdNode *node, double max, st_table *mintermTable)
static void ConjunctsFree (DdManager *dd, Conjuncts *factors)
static int PairInTables (DdNode *g, DdNode *h, st_table *ghTable)
static Conjuncts * CheckTablesCacheAndReturn (DdNode *node, DdNode *g, DdNode *h, st_table *ghTable, st_table *cacheTable)
static Conjuncts * PickOnePair (DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable)
static Conjuncts * CheckInTables (DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable, int *outOfMem)
static Conjuncts * ZeroCase (DdManager *dd, DdNode *node, Conjuncts *factorsNv, st_table *ghTable, st_table *cacheTable, int switched)
static Conjuncts * BuildConjuncts (DdManager *dd, DdNode *node, st_table *distanceTable, st_table *cacheTable, int approxDistance, int maxLocalRef, st_table *ghTable, st_table *mintermTable)
static int cuddConjunctsAux (DdManager *dd, DdNode *f, DdNode **c1, DdNode **c2)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddDecomp.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
static DdNode * one
static DdNode * zero
long lastTimeG
Define Documentation
#define BOTH_G 7
Definition at line 55 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define BOTH_H 8
Definition at line 56 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define DEPTH 5
CFile***********************************************************************
FileName [cuddDecomp.c]
PackageName [cudd]
Synopsis [Functions for BDD decomposition.]
Description [External procedures included in this file:
Cudd_bddApproxConjDecomp()
Cudd_bddApproxDisjDecomp()
Cudd_bddIterConjDecomp()
Cudd_bddIterDisjDecomp()
Cudd_bddGenConjDecomp()
Cudd_bddGenDisjDecomp()
Cudd_bddVarConjDecomp()
Cudd_bddVarDisjDecomp()
Static procedures included in this module:
cuddConjunctsAux()
CreateBotDist()
BuildConjuncts()
ConjunctsFree()
]
Author [Kavita Ravi, Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 46 of file cuddDecomp.c.
Referenced by cuddConjunctsAux().
#define FactorsComplement(factors) ((Conjuncts *)((long)(factors) | 01))
Definition at line 94 of file cuddDecomp.c.
Referenced by BuildConjuncts().
#define FactorsNotStored(factors) ((int)((long)(factors) & 01))
Definition at line 92 of file cuddDecomp.c.
Referenced by BuildConjuncts(), and cuddConjunctsAux().
#define FactorsUncomplement(factors) ((Conjuncts *)((long)(factors) ^ 01))
Definition at line 96 of file cuddDecomp.c.
Referenced by BuildConjuncts(), and cuddConjunctsAux().
#define G_CR 4
Definition at line 52 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define G_ST 3
Definition at line 51 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define H_CR 6
Definition at line 54 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define H_ST 5
Definition at line 53 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define NONE 0
Definition at line 48 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define PAIR_CR 2
Definition at line 50 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define PAIR_ST 1
Definition at line 49 of file cuddDecomp.c.
Referenced by CheckInTables(), CheckTablesCacheAndReturn(), and PairInTables().
#define THRESHOLD 10
Definition at line 47 of file cuddDecomp.c.
Function Documentation
static int cuddConjunctsAux ARGS ((DdManager *dd, DdNode *f, DdNode **c1, DdNode **c2)) [static]
static Conjuncts* BuildConjuncts ARGS ((DdManager *dd, DdNode *node, st_table *distanceTable, st_table *cacheTable, int approxDistance, int maxLocalRef, st_table *ghTable, st_table *mintermTable)) [static]
static Conjuncts* ZeroCase ARGS ((DdManager *dd, DdNode *node, Conjuncts *factorsNv, st_table *ghTable, st_table *cacheTable, int switched)) [static]
static Conjuncts* CheckInTables ARGS ((DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable, int *outOfMem)) [static]
static Conjuncts* PickOnePair ARGS ((DdNode *node, DdNode *g1, DdNode *h1, DdNode *g2, DdNode *h2, st_table *ghTable, st_table *cacheTable)) [static]
static Conjuncts* CheckTablesCacheAndReturn ARGS ((DdNode *node, DdNode *g, DdNode *h, st_table *ghTable, st_table *cacheTable)) [static]
static int PairInTables ARGS ((DdNode *g, DdNode *h, st_table *ghTable)) [static]
static void ConjunctsFree ARGS ((DdManager *dd, Conjuncts *factors)) [static]
static double CountMinterms ARGS ((DdNode *node, double max, st_table *mintermTable)) [static]
static NodeStat* CreateBotDist ARGS ((DdNode *node, st_table *distanceTable)) [static]
AutomaticStart
static Conjuncts* BuildConjuncts (DdManager * dd, DdNode * node, st_table * distanceTable, st_table * cacheTable, int approxDistance, int maxLocalRef, st_table * ghTable, st_table * mintermTable) [static]
Function********************************************************************
Synopsis [Builds the conjuncts recursively, bottom up.]
Description [Builds the conjuncts recursively, bottom up. Constants are returned as (f, f). The cache is checked for previously computed result. The decomposition points are determined by the local reference count of this node and the longest distance from the constant. At the decomposition point, the factors returned are (f, 1). Recur on the two children. The order is determined by the heavier branch. Combine the factors of the two children and pick the one that already occurs in the gh table. Occurence in g is indicated by value 1, occurence in h by 2, occurence in both 3.]
SideEffects []
SeeAlso [cuddConjunctsAux]
Definition at line 1683 of file cuddDecomp.c.
References ALLOC, CheckInTables(), Cudd_IsComplement, Cudd_IsConstant, CUDD_MEMORY_OUT, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddIteRecur(), cuddE, cuddRef, cuddT, DdManager::errorCode, FactorsComplement, FactorsNotStored, FactorsUncomplement, FREE, Conjuncts::g, Conjuncts::h, lastTimeG, one, PickOnePair(), st_insert(), st_lookup(), st_lookup_int(), ST_OUT_OF_MEM, DdManager::vars, zero, and ZeroCase().
Referenced by cuddConjunctsAux().
static Conjuncts* CheckInTables (DdNode * node, DdNode * g1, DdNode * h1, DdNode * g2, DdNode * h2, st_table * ghTable, st_table * cacheTable, int * outOfMem) [static]
Function********************************************************************
Synopsis [Check if the two pairs exist in the table, If any of the conjuncts do exist, store in the cache and return the corresponding pair.]
Description [Check if the two pairs exist in the table. If any of the conjuncts do exist, store in the cache and return the corresponding pair.]
SideEffects []
SeeAlso [ZeroCase BuildConjuncts]
Definition at line 1198 of file cuddDecomp.c.
References ALLOC, BOTH_G, BOTH_H, Cudd_Regular, FREE, Conjuncts::g, G_CR, G_ST, Conjuncts::h, H_CR, H_ST, NONE, one, PAIR_CR, PAIR_ST, PairInTables(), st_insert(), and ST_OUT_OF_MEM.
Referenced by BuildConjuncts(), and ZeroCase().
static Conjuncts* CheckTablesCacheAndReturn (DdNode * node, DdNode * g, DdNode * h, st_table * ghTable, st_table * cacheTable) [static]
Function********************************************************************
Synopsis [Check the tables for the existence of pair and return one combination, cache the result.]
Description [Check the tables for the existence of pair and return one combination, cache the result. The assumption is that one of the conjuncts is already in the tables.]
SideEffects [g and h referenced for the cache]
SeeAlso [ZeroCase]
Definition at line 966 of file cuddDecomp.c.
References ALLOC, assert, BOTH_G, BOTH_H, Cudd_Regular, FREE, Conjuncts::g, G_CR, G_ST, Conjuncts::h, H_CR, H_ST, NONE, one, PAIR_CR, PAIR_ST, PairInTables(), st_insert(), st_lookup_int(), and ST_OUT_OF_MEM.
Referenced by ZeroCase().
static void ConjunctsFree (DdManager * dd, Conjuncts * factors) [static]
Function********************************************************************
Synopsis [Free factors structure]
Description []
SideEffects [None]
SeeAlso []
Definition at line 876 of file cuddDecomp.c.
References Cudd_RecursiveDeref(), FREE, Conjuncts::g, and Conjuncts::h.
Referenced by cuddConjunctsAux().
static double CountMinterms (DdNode * node, double max, st_table * mintermTable) [static]
Function********************************************************************
Synopsis [Count the number of minterms of each node ina a BDD and store it in a hash table.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 814 of file cuddDecomp.c.
References ALLOC, Cudd_IsComplement, Cudd_NotCond, Cudd_Regular, cuddE, cuddIsConstant, cuddT, st_insert(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by cuddConjunctsAux().
static NodeStat* CreateBotDist (DdNode * node, st_table * distanceTable) [static]
Function********************************************************************
Synopsis [Get longest distance of node from constant.]
Description [Get longest distance of node from constant. Returns the distance of the root from the constant if successful; CUDD_OUT_OF_MEM otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 744 of file cuddDecomp.c.
References ALLOC, Cudd_IsComplement, Cudd_IsConstant, Cudd_NotCond, Cudd_Regular, cuddE, cuddT, NodeStat::distance, st_insert(), st_lookup(), and ST_OUT_OF_MEM.
Referenced by CreateBotDist(), CreatePathTable(), and cuddConjunctsAux().
int Cudd_bddApproxConjDecomp (DdManager * dd, DdNode * f, DdNode *** conjuncts)
Function********************************************************************
Synopsis [Performs two-way conjunctive decomposition of a BDD.]
Description [Performs two-way conjunctive decomposition of a BDD. This procedure owes its name to the use of supersetting to obtain an initial factor of the given function. Returns the number of conjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The conjuncts produced by this procedure tend to be imbalanced.]
SideEffects [The factors are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the conjuncts are already referenced. If the function returns 0, the array for the conjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddApproxDisjDecomp Cudd_bddIterConjDecomp Cudd_bddGenConjDecomp Cudd_bddVarConjDecomp Cudd_RemapOverApprox Cudd_bddSqueeze Cudd_bddLICompaction]
Definition at line 147 of file cuddDecomp.c.
References ALLOC, Cudd_bddLICompaction(), Cudd_bddSqueeze(), CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_RemapOverApprox(), Cudd_SupportSize(), cuddRef, and DD_ONE.
Referenced by Cudd_bddApproxDisjDecomp().
int Cudd_bddApproxDisjDecomp (DdManager * dd, DdNode * f, DdNode *** disjuncts)
Function********************************************************************
Synopsis [Performs two-way disjunctive decomposition of a BDD.]
Description [Performs two-way disjunctive decomposition of a BDD. Returns the number of disjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The disjuncts produced by this procedure tend to be imbalanced.]
SideEffects [The two disjuncts are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the disjuncts are already referenced. If the function returns 0, the array for the disjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddApproxConjDecomp Cudd_bddIterDisjDecomp Cudd_bddGenDisjDecomp Cudd_bddVarDisjDecomp]
Definition at line 245 of file cuddDecomp.c.
References Cudd_bddApproxConjDecomp(), Cudd_Not, and result.
int Cudd_bddGenConjDecomp (DdManager * dd, DdNode * f, DdNode *** conjuncts)
Function********************************************************************
Synopsis [Performs two-way conjunctive decomposition of a BDD.]
Description [Performs two-way conjunctive decomposition of a BDD. This procedure owes its name to the fact tht it generalizes the decomposition based on the cofactors with respect to one variable. Returns the number of conjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The conjuncts produced by this procedure tend to be balanced.]
SideEffects [The two factors are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the conjuncts are already referenced. If the function returns 0, the array for the conjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddGenDisjDecomp Cudd_bddApproxConjDecomp Cudd_bddIterConjDecomp Cudd_bddVarConjDecomp]
Definition at line 468 of file cuddDecomp.c.
References ALLOC, CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), cuddConjunctsAux(), DD_ONE, one, DdManager::reordered, result, and zero.
Referenced by Cudd_bddGenDisjDecomp().
int Cudd_bddGenDisjDecomp (DdManager * dd, DdNode * f, DdNode *** disjuncts)
Function********************************************************************
Synopsis [Performs two-way disjunctive decomposition of a BDD.]
Description [Performs two-way disjunctive decomposition of a BDD. Returns the number of disjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The disjuncts produced by this procedure tend to be balanced.]
SideEffects [The two disjuncts are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the disjuncts are already referenced. If the function returns 0, the array for the disjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddGenConjDecomp Cudd_bddApproxDisjDecomp Cudd_bddIterDisjDecomp Cudd_bddVarDisjDecomp]
Definition at line 547 of file cuddDecomp.c.
References Cudd_bddGenConjDecomp(), Cudd_Not, and result.
int Cudd_bddIterConjDecomp (DdManager * dd, DdNode * f, DdNode *** conjuncts)
Function********************************************************************
Synopsis [Performs two-way conjunctive decomposition of a BDD.]
Description [Performs two-way conjunctive decomposition of a BDD. This procedure owes its name to the iterated use of supersetting to obtain a factor of the given function. Returns the number of conjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The conjuncts produced by this procedure tend to be imbalanced.]
SideEffects [The factors are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the conjuncts are already referenced. If the function returns 0, the array for the conjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddIterDisjDecomp Cudd_bddApproxConjDecomp Cudd_bddGenConjDecomp Cudd_bddVarConjDecomp Cudd_RemapOverApprox Cudd_bddSqueeze Cudd_bddLICompaction]
Definition at line 285 of file cuddDecomp.c.
References ALLOC, Cudd_bddAnd(), Cudd_bddLICompaction(), Cudd_bddSqueeze(), CUDD_MEMORY_OUT, Cudd_RecursiveDeref(), Cudd_RemapOverApprox(), Cudd_SharingSize(), Cudd_SupportSize(), cuddRef, and DD_ONE.
Referenced by Cudd_bddIterDisjDecomp().
int Cudd_bddIterDisjDecomp (DdManager * dd, DdNode * f, DdNode *** disjuncts)
Function********************************************************************
Synopsis [Performs two-way disjunctive decomposition of a BDD.]
Description [Performs two-way disjunctive decomposition of a BDD. Returns the number of disjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise. The disjuncts produced by this procedure tend to be imbalanced.]
SideEffects [The two disjuncts are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the disjuncts are already referenced. If the function returns 0, the array for the disjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddIterConjDecomp Cudd_bddApproxDisjDecomp Cudd_bddGenDisjDecomp Cudd_bddVarDisjDecomp]
Definition at line 428 of file cuddDecomp.c.
References Cudd_bddIterConjDecomp(), Cudd_Not, and result.
int Cudd_bddVarConjDecomp (DdManager * dd, DdNode * f, DdNode *** conjuncts)
Function********************************************************************
Synopsis [Performs two-way conjunctive decomposition of a BDD.]
Description [Conjunctively decomposes one BDD according to a variable. If f is the function of the BDD and x is the variable, the decomposition is (f+x)(f+x'). The variable is chosen so as to balance the sizes of the two conjuncts and to keep them small. Returns the number of conjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise.]
SideEffects [The two factors are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the conjuncts are already referenced. If the function returns 0, the array for the conjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddVarDisjDecomp Cudd_bddGenConjDecomp Cudd_bddApproxConjDecomp Cudd_bddIterConjDecomp]
Definition at line 587 of file cuddDecomp.c.
References ALLOC, assert, Cudd_bddIthVar(), Cudd_bddOr(), Cudd_EstimateCofactor(), Cudd_IsConstant, CUDD_MEMORY_OUT, Cudd_Not, Cudd_RecursiveDeref(), Cudd_Support(), cuddRef, cuddT, DD_ONE, DdManager::errorCode, scan, and size.
Referenced by Cudd_bddVarDisjDecomp().
int Cudd_bddVarDisjDecomp (DdManager * dd, DdNode * f, DdNode *** disjuncts)
Function********************************************************************
Synopsis [Performs two-way disjunctive decomposition of a BDD.]
Description [Performs two-way disjunctive decomposition of a BDD according to a variable. If f is the function of the BDD and x is the variable, the decomposition is f*x + f*x'. The variable is chosen so as to balance the sizes of the two disjuncts and to keep them small. Returns the number of disjuncts produced, that is, 2 if successful; 1 if no meaningful decomposition was found; 0 otherwise.]
SideEffects [The two disjuncts are returned in an array as side effects. The array is allocated by this function. It is the caller's responsibility to free it. On successful completion, the disjuncts are already referenced. If the function returns 0, the array for the disjuncts is not allocated. If the function returns 1, the only factor equals the function to be decomposed.]
SeeAlso [Cudd_bddVarConjDecomp Cudd_bddApproxDisjDecomp Cudd_bddIterDisjDecomp Cudd_bddGenDisjDecomp]
Definition at line 705 of file cuddDecomp.c.
References Cudd_bddVarConjDecomp(), Cudd_Not, and result.
static int cuddConjunctsAux (DdManager * dd, DdNode * f, DdNode ** c1, DdNode ** c2) [static]
Function********************************************************************
Synopsis [Procedure to compute two conjunctive factors of f and place in *c1 and *c2.]
Description [Procedure to compute two conjunctive factors of f and place in *c1 and *c2. Sets up the required data - table of distances from the constant and local reference count. Also minterm table. ]
SideEffects []
SeeAlso []
Definition at line 2002 of file cuddDecomp.c.
References ALLOC, assert, BuildConjuncts(), ConjunctsFree(), CountMinterms(), CreateBotDist(), Cudd_bddLeq(), Cudd_IsConstant, CUDD_MEMORY_OUT, Cudd_Random(), Cudd_SupportSize(), cuddRef, DD_ONE, DEPTH, NodeStat::distance, FactorsNotStored, FactorsUncomplement, FREE, Conjuncts::g, Conjuncts::h, lastTimeG, NodeStat::localRef, max, one, st_free_gen(), st_free_table(), st_gen(), st_init_gen(), st_init_table(), st_insert(), ST_OUT_OF_MEM, st_ptrcmp(), and st_ptrhash().
Referenced by Cudd_bddGenConjDecomp().
static int PairInTables (DdNode * g, DdNode * h, st_table * ghTable) [static]
Function********************************************************************
Synopsis [Check whether the given pair is in the tables.]
Description [.Check whether the given pair is in the tables. gTable and hTable are combined. absence in both is indicated by 0, presence in gTable is indicated by 1, presence in hTable by 2 and presence in both by 3. The values returned by this function are PAIR_ST, PAIR_CR, G_ST, G_CR, H_ST, H_CR, BOTH_G, BOTH_H, NONE. PAIR_ST implies g in gTable and h in hTable PAIR_CR implies g in hTable and h in gTable G_ST implies g in gTable and h not in any table G_CR implies g in hTable and h not in any table H_ST implies h in hTable and g not in any table H_CR implies h in gTable and g not in any table BOTH_G implies both in gTable BOTH_H implies both in hTable NONE implies none in table; ]
SideEffects []
SeeAlso [CheckTablesCacheAndReturn CheckInTables]
Definition at line 916 of file cuddDecomp.c.
References BOTH_G, BOTH_H, Cudd_Regular, G_CR, G_ST, H_CR, H_ST, NONE, PAIR_CR, PAIR_ST, and st_lookup_int().
Referenced by CheckInTables(), and CheckTablesCacheAndReturn().
static Conjuncts* PickOnePair (DdNode * node, DdNode * g1, DdNode * h1, DdNode * g2, DdNode * h2, st_table * ghTable, st_table * cacheTable) [static]
Function********************************************************************
Synopsis [Check the tables for the existence of pair and return one combination, store in cache.]
Description [Check the tables for the existence of pair and return one combination, store in cache. The pair that has more pointers to it is picked. An approximation of the number of local pointers is made by taking the reference count of the pairs sent. ]
SideEffects []
SeeAlso [ZeroCase BuildConjuncts]
Definition at line 1075 of file cuddDecomp.c.
References ALLOC, Cudd_Regular, FREE, Conjuncts::g, Conjuncts::h, one, st_insert(), st_lookup_int(), and ST_OUT_OF_MEM.
Referenced by BuildConjuncts(), and ZeroCase().
static Conjuncts* ZeroCase (DdManager * dd, DdNode * node, Conjuncts * factorsNv, st_table * ghTable, st_table * cacheTable, int switched) [static]
Function********************************************************************
Synopsis [If one child is zero, do explicitly what Restrict does or better]
Description [If one child is zero, do explicitly what Restrict does or better. First separate a variable and its child in the base case. In case of a cube times a function, separate the cube and function. As a last resort, look in tables.]
SideEffects [Frees the BDDs in factorsNv. factorsNv itself is not freed because it is freed above.]
SeeAlso [BuildConjuncts]
Definition at line 1441 of file cuddDecomp.c.
References ALLOC, CheckInTables(), CheckTablesCacheAndReturn(), Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Not, Cudd_NotCond, Cudd_RecursiveDeref(), Cudd_Regular, cuddBddAndRecur(), cuddE, cuddRef, cuddT, DdManager::errorCode, FREE, Conjuncts::g, Conjuncts::h, DdNode::index, one, PickOnePair(), st_insert(), st_lookup_int(), ST_OUT_OF_MEM, DdManager::vars, and zero.
Referenced by BuildConjuncts().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddDecomp.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 81 of file cuddDecomp.c.
long lastTimeG
Definition at line 85 of file cuddDecomp.c.
Referenced by BuildConjuncts(), and cuddConjunctsAux().
DdNode* one [static]
Definition at line 84 of file cuddDecomp.c.
Referenced by addVarToConst(), addWalshInt(), bddVarToCanonical(), bddVarToConst(), BuildConjuncts(), CheckInTables(), CheckTablesCacheAndReturn(), Cudd_addHarwell(), Cudd_addIteConstant(), Cudd_addRead(), Cudd_addXeqy(), Cudd_bddGenConjDecomp(), Cudd_bddIsVarEssential(), Cudd_bddIteConstant(), Cudd_bddLeq(), Cudd_bddPickOneCube(), Cudd_bddRead(), Cudd_Dxygtdxz(), Cudd_Dxygtdyz(), Cudd_EquivDC(), Cudd_Init(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), cuddAddCmplRecur(), cuddAddConstrainRecur(), cuddAddIteRecur(), cuddAddOrAbstractRecur(), cuddAddRestrictRecur(), cuddAddUnivAbstractRecur(), cuddBddAndAbstractRecur(), cuddBddAndRecur(), cuddBddCharToVect(), cuddBddClipAndAbsRecur(), cuddBddClippingAndRecur(), cuddBddConstrainRecur(), cuddBddExistAbstractRecur(), cuddBddIntersectRecur(), cuddBddIsop(), cuddBddIteRecur(), cuddBddLICBuildResult(), cuddBddLICMarkEdges(), cuddBddLiteralSetIntersectionRecur(), cuddBddRestrictRecur(), cuddBddSqueeze(), cuddBddTransferRecur(), cuddBddXorExistAbstractRecur(), cuddBddXorRecur(), cuddCheckCube(), cuddCofactorRecur(), cuddConjunctsAux(), cuddCProjectionRecur(), cuddInsertSubtables(), cuddResizeTableZdd(), cuddSolveEqnRecur(), cuddSplitSetRecur(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddDivide(), cuddZddDivideF(), cuddZddIsop(), cuddZddProduct(), cuddZddUnateProduct(), cuddZddWeakDiv(), cuddZddWeakDivF(), ddBddToAddRecur(), ddExtSymmCheck(), ddFindEssentialRecur(), ddPickArbitraryMinterms(), ddResizeTable(), get_cube(), get_path(), mintermsFromUniverse(), PickOnePair(), selectMintermsFromUniverse(), zddPortToBddStep(), and ZeroCase().
DdNode * zero [static]
Definition at line 84 of file cuddDecomp.c.