cuddZddLin.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define CUDD_SWAP_MOVE 0
#define CUDD_LINEAR_TRANSFORM_MOVE 1
#define CUDD_INVERSE_TRANSFORM_MOVE 2
Functions
static int cuddZddLinearAux ARGS ((DdManager *table, int x, int xLow, int xHigh))
static Move *cuddZddLinearUp ARGS ((DdManager *table, int y, int xLow, Move *prevMoves))
static Move *cuddZddLinearDown ARGS ((DdManager *table, int x, int xHigh, Move *prevMoves))
static int cuddZddLinearBackward ARGS ((DdManager *table, int size, Move *moves))
static Move *cuddZddUndoMoves ARGS ((DdManager *table, Move *moves))
int cuddZddLinearSifting (DdManager *table, int lower, int upper)
int cuddZddLinearInPlace (DdManager *table, int x, int y)
static int cuddZddLinearAux (DdManager *table, int x, int xLow, int xHigh)
static Move * cuddZddLinearUp (DdManager *table, int y, int xLow, Move *prevMoves)
static Move * cuddZddLinearDown (DdManager *table, int x, int xHigh, Move *prevMoves)
static int cuddZddLinearBackward (DdManager *table, int size, Move *moves)
static Move * cuddZddUndoMoves (DdManager *table, Move *moves)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddZddLin.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
int * zdd_entry
int zddTotalNumberSwapping
static int zddTotalNumberLinearTr
static DdNode * empty
Define Documentation
#define CUDD_INVERSE_TRANSFORM_MOVE 2
Definition at line 46 of file cuddZddLin.c.
#define CUDD_LINEAR_TRANSFORM_MOVE 1
Definition at line 45 of file cuddZddLin.c.
#define CUDD_SWAP_MOVE 0
CFile***********************************************************************
FileName [cuddZddLin.c]
PackageName [cudd]
Synopsis [Procedures for dynamic variable ordering of ZDDs.]
Description [Internal procedures included in this module:
cuddZddLinearSifting()
Static procedures included in this module:
cuddZddLinearInPlace()
cuddZddLinerAux()
cuddZddLinearUp()
cuddZddLinearDown()
cuddZddLinearBackward()
cuddZddUndoMoves()
]
SeeAlso [cuddLinear.c cuddZddReord.c]
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 44 of file cuddZddLin.c.
Function Documentation
static Move* cuddZddUndoMoves ARGS ((DdManager *table, Move *moves)) [static]
static int cuddZddLinearBackward ARGS ((DdManager *table, int size, Move *moves)) [static]
static Move* cuddZddLinearDown ARGS ((DdManager *table, int x, int xHigh, Move *prevMoves)) [static]
static Move* cuddZddLinearUp ARGS ((DdManager *table, int y, int xLow, Move *prevMoves)) [static]
static int cuddZddLinearAux ARGS ((DdManager *table, int x, int xLow, int xHigh)) [static]
AutomaticStart
static int cuddZddLinearAux (DdManager * table, int x, int xLow, int xHigh) [static]
Function********************************************************************
Synopsis [Given xLow <= x <= xHigh moves x up and down between the boundaries.]
Description [Given xLow <= x <= xHigh moves x up and down between the boundaries. Finds the best position and does the required changes. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 551 of file cuddZddLin.c.
References assert, CUDD_OUT_OF_MEM, cuddDeallocNode, cuddZddLinearBackward(), cuddZddLinearDown(), cuddZddLinearUp(), cuddZddUndoMoves(), DdSubtable::keys, DdManager::keysZ, Move::next, result, DdManager::subtableZ, Move::x, and Move::y.
Referenced by cuddZddLinearSifting().
static int cuddZddLinearBackward (DdManager * table, int size, Move * moves) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the ZDD heap to the position giving the minimum size.]
Description [Given a set of moves, returns the ZDD heap to the position giving the minimum size. In case of ties, returns to the closest position giving the minimum size. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 847 of file cuddZddLin.c.
References Move::next, and Move::size.
Referenced by cuddZddLinearAux().
static Move* cuddZddLinearDown (DdManager * table, int x, int xHigh, Move * prevMoves) [static]
Function********************************************************************
Synopsis [Sifts a variable down and applies the XOR transformation.]
Description [Sifts a variable down. Moves x down until either it reaches the bound (xHigh) or the size of the ZDD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 763 of file cuddZddLin.c.
References CUDD_LINEAR_TRANSFORM_MOVE, CUDD_OUT_OF_MEM, CUDD_SWAP_MOVE, cuddDeallocNode, cuddDynamicAllocNode(), cuddZddLinearInPlace(), cuddZddNextHigh(), cuddZddSwapInPlace(), Move::flags, DdManager::keysZ, DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddZddLinearAux().
int cuddZddLinearInPlace (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Linearly combines two adjacent variables.]
Description [Linearly combines two adjacent variables. It assumes that no dead nodes are present on entry to this procedure. The procedure then guarantees that no dead nodes will be present when it terminates. cuddZddLinearInPlace assumes that x < y. Returns the number of keys in the table if successful; 0 otherwise.]
SideEffects [None]
SeeAlso [cuddZddSwapInPlace cuddLinearInPlace]
Definition at line 225 of file cuddZddLin.c.
References assert, cuddE, cuddSatDec, cuddT, cuddZddNextHigh(), DdSubtable::dead, empty, DdNode::index, DdManager::invpermZ, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdSubtable::slots, DdManager::subtableZ, and zddTotalNumberLinearTr.
Referenced by cuddZddLinearDown(), cuddZddLinearUp(), and cuddZddUndoMoves().
int cuddZddLinearSifting (DdManager * table, int lower, int upper)
Function********************************************************************
Synopsis [Implementation of the linear sifting algorithm for ZDDs.]
Description [Implementation of the linear sifting algorithm for ZDDs. Assumes that no dead nodes are present.
Order all the variables according to the number of entries in each unique table.
Sift the variable up and down and applies the XOR transformation, remembering each time the total size of the DD heap.
Select the best permutation.
Repeat 3 and 4 for all variables.
Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 126 of file cuddZddLin.c.
References ALLOC, CUDD_MEMORY_OUT, cuddZddLinearAux(), cuddZddUniqueCompare(), ddMin, empty, DdManager::errorCode, FREE, DdSubtable::keys, DdManager::keysZ, DdManager::permZ, qsort(), result, DdManager::siftMaxSwap, DdManager::siftMaxVar, size, DdManager::sizeZ, DdManager::subtableZ, zdd_entry, zddTotalNumberSwapping, and DdManager::zero.
Referenced by zddReorderChildren().
static Move* cuddZddLinearUp (DdManager * table, int y, int xLow, Move * prevMoves) [static]
Function********************************************************************
Synopsis [Sifts a variable up applying the XOR transformation.]
Description [Sifts a variable up applying the XOR transformation. Moves y up until either it reaches the bound (xLow) or the size of the ZDD heap increases too much. Returns the set of moves in case of success; NULL if memory is full.]
SideEffects [None]
SeeAlso []
Definition at line 678 of file cuddZddLin.c.
References CUDD_LINEAR_TRANSFORM_MOVE, CUDD_OUT_OF_MEM, CUDD_SWAP_MOVE, cuddDeallocNode, cuddDynamicAllocNode(), cuddZddLinearInPlace(), cuddZddNextLow(), cuddZddSwapInPlace(), Move::flags, DdManager::keysZ, DdManager::maxGrowth, Move::next, Move::size, size, Move::x, and Move::y.
Referenced by cuddZddLinearAux().
static Move* cuddZddUndoMoves (DdManager * table, Move * moves) [static]
Function********************************************************************
Synopsis [Given a set of moves, returns the ZDD heap to the order in effect before the moves.]
Description [Given a set of moves, returns the ZDD heap to the order in effect before the moves. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
Definition at line 895 of file cuddZddLin.c.
References CUDD_INVERSE_TRANSFORM_MOVE, CUDD_LINEAR_TRANSFORM_MOVE, CUDD_SWAP_MOVE, cuddDynamicAllocNode(), cuddZddLinearInPlace(), cuddZddSwapInPlace(), Move::flags, Move::next, size, Move::x, and Move::y.
Referenced by cuddZddLinearAux().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddZddLin.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 63 of file cuddZddLin.c.
DdNode* empty [static]
Definition at line 69 of file cuddZddLin.c.
Referenced by Cudd_zddCount(), Cudd_zddCountDouble(), Cudd_zddDiffConst(), Cudd_zddPrintDebug(), Cudd_zddReduceHeap(), Cudd_zddShuffleHeap(), cuddZddAlignToBdd(), cuddZddChangeAux(), cuddZddCountDoubleStep(), cuddZddCountStep(), cuddZddDiff(), cuddZddIntersect(), cuddZddIte(), cuddZddLinearInPlace(), cuddZddLinearSifting(), cuddZddSubset0(), cuddZddSubset1(), cuddZddSwapInPlace(), cuddZddSymmCheck(), cuddZddUnion(), zdd_subset0_aux(), zdd_subset1_aux(), and zddVarToConst().
int* zdd_entry
Definition at line 79 of file cuddZddReord.c.
Referenced by cuddZddLinearSifting(), cuddZddSifting(), cuddZddSymmSifting(), cuddZddSymmSiftingConv(), and cuddZddUniqueCompare().
int zddTotalNumberLinearTr [static]
Definition at line 68 of file cuddZddLin.c.
Referenced by cuddZddLinearInPlace().
int zddTotalNumberSwapping
Definition at line 81 of file cuddZddReord.c.