cuddCheck.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Functions
static void debugFindParent ARGS ((DdManager *table, DdNode *node))
int Cudd_DebugCheck (DdManager *table)
int Cudd_CheckKeys (DdManager *table)
int cuddHeapProfile (DdManager *dd)
void cuddPrintNode (DdNode *f)
static void debugFindParent (DdManager *table, DdNode *node)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddCheck.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static void debugFindParent ARGS ((DdManager *table, DdNode *node)) [static]
AutomaticStart
int Cudd_CheckKeys (DdManager * table)
Function********************************************************************
Synopsis [Checks for several conditions that should not occur.]
Description [Checks for the following conditions:
Wrong sizes of subtables.
Wrong number of keys found in unique subtable.
Wrong number of dead found in unique subtable.
Wrong number of keys found in the constant table
Wrong number of dead found in the constant table
Wrong number of total slots found
Wrong number of maximum keys found
Wrong number of total dead found
Reports the average length of non-empty lists. Returns the number of subtables for which the number of keys is wrong.]
SideEffects [None]
SeeAlso [Cudd_DebugCheck]
Definition at line 408 of file cuddCheck.c.
References DdSubtable::dead, DdSubtable::keys, DdNode::next, DdSubtable::nodelist, DdNode::ref, DdSubtable::shift, DdManager::size, size, DdSubtable::slots, and DdManager::subtables.
Referenced by cuddRemapUnderApprox(), cuddSubsetHeavyBranch(), cuddUnderApprox(), cuddUniqueInter(), and cuddUniqueInterZdd().
int Cudd_DebugCheck (DdManager * table)
Function********************************************************************
Synopsis [Checks for inconsistencies in the DD heap.]
Description [Checks for inconsistencies in the DD heap:
node has illegal index
live node has dead children
node has illegal Then or Else pointers
BDD/ADD node has identical children
ZDD node has zero then child
wrong number of total nodes
wrong number of dead nodes
ref count error at node
Returns 0 if no inconsistencies are found; DD_OUT_OF_MEM if there is not enough memory; 1 otherwise.]
SideEffects [None]
SeeAlso [Cudd_CheckKeys]
Definition at line 113 of file cuddCheck.c.
References CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddI, cuddPrintNode(), cuddT, DdNode::index, DdManager::invperm, DdNode::next, DdSubtable::nodelist, DdManager::perm, DdNode::ref, DdManager::size, DdSubtable::slots, st_free_table(), st_init_table(), st_insert(), st_lookup(), ST_OUT_OF_MEM, st_ptrcmp(), st_ptrhash(), and DdManager::subtables.
Referenced by cuddLinearAndSifting(), cuddRemapUnderApprox(), cuddSubsetHeavyBranch(), cuddUnderApprox(), cuddUniqueInter(), and cuddUniqueInterZdd().
int cuddHeapProfile (DdManager * dd)
Function********************************************************************
Synopsis [Prints information about the heap.]
Description [Prints to stdout the number of live nodes for each level of the DD heap that contains at least one live node. It also prints a summary containing:
total number of tables;
number of tables with live nodes;
table with the largest number of live nodes;
number of nodes in that table.
If more than one table contains the maximum number of live nodes, only the one of lowest index is reported. Returns 1 in case of success and 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 594 of file cuddCheck.c.
References CUDD_MAXINDEX, largest(), DdManager::size, and DdManager::subtables.
void cuddPrintNode (DdNode * f)
Function********************************************************************
Synopsis [Prints out information on a node.]
Description [Prints out information on a node.]
SideEffects [None]
SeeAlso []
Definition at line 663 of file cuddCheck.c.
References Cudd_Regular, cuddE, cuddT, and DdNode::index.
Referenced by Cudd_DebugCheck().
static void debugFindParent (DdManager * table, DdNode * node) [static]
Function********************************************************************
Synopsis [Searches the subtables above node for its parents.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 693 of file cuddCheck.c.
References Cudd_Regular, cuddE, cuddI, cuddT, DdNode::index, DdNode::next, DdSubtable::nodelist, DdSubtable::slots, and DdManager::subtables.
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddCheck.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [cuddCheck.c]
PackageName [cudd]
Synopsis [Functions to check consistency of data structures.]
Description [External procedures included in this module:
Cudd_DebugCheck()
Cudd_CheckKeys()
Internal procedures included in this module:
cuddHeapProfile()
cuddPrintNode()
Static procedures included in this module:
debugFindParent()
]
SeeAlso []
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 62 of file cuddCheck.c.