cuddInteract.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/cuddInt.h>
Defines
#define BPL 32
#define LOGBPL 5
Functions
static void ddSuppInteract ARGS ((DdNode *f, int *support))
static void ddClearLocal ARGS ((DdNode *f))
static void ddUpdateInteract ARGS ((DdManager *table, int *support))
static void ddClearGlobal ARGS ((DdManager *table))
void cuddSetInteract (DdManager *table, int x, int y)
int cuddTestInteract (DdManager *table, int x, int y)
int cuddInitInteract (DdManager *table)
static void ddSuppInteract (DdNode *f, int *support)
static void ddClearLocal (DdNode *f)
static void ddUpdateInteract (DdManager *table, int *support)
static void ddClearGlobal (DdManager *table)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddInteract.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define BPL 32
CFile***********************************************************************
FileName [cuddInteract.c]
PackageName [cudd]
Synopsis [Functions to manipulate the variable interaction matrix.]
Description [Internal procedures included in this file:
cuddSetInteract()
cuddTestInteract()
cuddInitInteract()
Static procedures included in this file:
ddSuppInteract()
ddClearLocal()
ddUpdateInteract()
ddClearGlobal()
The interaction matrix tells whether two variables are both in the support of some function of the DD. The main use of the interaction matrix is in the in-place swapping. Indeed, if two variables do not interact, there is no arc connecting the two layers; therefore, the swap can be performed in constant time, without scanning the subtables. Another use of the interaction matrix is in the computation of the lower bounds for sifting. Finally, the interaction matrix can be used to speed up aggregation checks in symmetric and group sifting.
The computation of the interaction matrix is done with a series of depth-first searches. The searches start from those nodes that have only external references. The matrix is stored as a packed array of bits; since it is symmetric, only the upper triangle is kept in memory. As a final remark, we note that there may be variables that do intercat, but that for a given variable order have no arc connecting their layers when they are adjacent.]
SeeAlso []
Author [Fabio Somenzi]
Copyright [ This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 63 of file cuddInteract.c.
Referenced by Cudd_PrintLinear(), Cudd_ReadLinear(), cuddInitLinear(), cuddResizeLinear(), cuddSetInteract(), and cuddTestInteract().
#define LOGBPL 5
Definition at line 64 of file cuddInteract.c.
Referenced by Cudd_PrintLinear(), Cudd_ReadLinear(), cuddInitInteract(), cuddInitLinear(), cuddResizeLinear(), cuddSetInteract(), cuddTestInteract(), and cuddXorLinear().
Function Documentation
static void ddClearGlobal ARGS ((DdManager *table)) [static]
static void ddUpdateInteract ARGS ((DdManager *table, int *support)) [static]
static void ddClearLocal ARGS ((DdNode *f)) [static]
static void ddSuppInteract ARGS ((DdNode *f, int *support)) [static]
AutomaticStart
int cuddInitInteract (DdManager * table)
Function********************************************************************
Synopsis [Initializes the interaction matrix.]
Description [Initializes the interaction matrix. The interaction matrix is implemented as a bit vector storing the upper triangle of the symmetric interaction matrix. The bit vector is kept in an array of long integers. The computation is based on a series of depth-first searches, one for each root of the DAG. Two flags are needed: The local visited flag uses the LSB of the then pointer. The global visited flag uses the LSB of the next pointer. Returns 1 if successful; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 208 of file cuddInteract.c.
References ALLOC, Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Regular, ddClearLocal(), ddSuppInteract(), ddUpdateInteract(), DdManager::errorCode, FREE, DdManager::interact, LOGBPL, DdNode::next, DdSubtable::nodelist, DdManager::size, DdSubtable::slots, and DdManager::subtables.
Referenced by cuddBddAlignToZdd(), and ddReorderPreprocess().
void cuddSetInteract (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Set interaction matrix entries.]
Description [Given a pair of variables 0 <= x < y < table->size, sets the corresponding bit of the interaction matrix to 1.]
SideEffects [None]
SeeAlso []
Definition at line 127 of file cuddInteract.c.
References assert, BPL, DdManager::interact, LOGBPL, DdManager::size, and size.
Referenced by ddUpdateInteract(), and ddUpdateInteractionMatrix().
int cuddTestInteract (DdManager * table, int x, int y)
Function********************************************************************
Synopsis [Test interaction matrix entries.]
Description [Given a pair of variables 0 <= x < y < table->size, tests whether the corresponding bit of the interaction matrix is 1. Returns the value of the bit.]
SideEffects [None]
SeeAlso []
Definition at line 162 of file cuddInteract.c.
References assert, BPL, DdManager::interact, LOGBPL, result, DdManager::size, and size.
Referenced by cuddLinearInPlace(), cuddSwapInPlace(), ddExtSymmCheck(), ddGroupSiftingDown(), ddGroupSiftingUp(), ddLinearAndSiftingDown(), ddLinearAndSiftingUp(), ddSecDiffCheck(), ddSiftingDown(), ddSiftingUp(), ddSymmSiftingDown(), ddSymmSiftingUp(), and ddUpdateInteractionMatrix().
static void ddClearGlobal (DdManager * table) [static]
Function********************************************************************
Synopsis [Scans the DD and clears the LSB of the next pointers.]
Description [The LSB of the next pointers are used as markers to tell whether a node was reached by at least one DFS. Once the interaction matrix is built, these flags are reset.]
SideEffects [None]
SeeAlso []
Definition at line 388 of file cuddInteract.c.
References Cudd_Regular, DdNode::next, DdSubtable::nodelist, DdManager::size, DdSubtable::slots, and DdManager::subtables.
static void ddClearLocal (DdNode * f) [static]
Function********************************************************************
Synopsis [Performs a DFS from f, clearing the LSB of the then pointers.]
Description []
SideEffects [None]
SeeAlso []
Definition at line 325 of file cuddInteract.c.
References Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, and cuddT.
Referenced by cuddInitInteract().
static void ddSuppInteract (DdNode * f, int * support) [static]
Function********************************************************************
Synopsis [Find the support of f.]
Description [Performs a DFS from f. Uses the LSB of the then pointer as visited flag.]
SideEffects [Accumulates in support the variables on which f depends.]
SeeAlso []
Definition at line 294 of file cuddInteract.c.
References Cudd_Complement, Cudd_IsComplement, Cudd_Regular, cuddE, cuddIsConstant, cuddT, DdNode::index, and DdNode::next.
Referenced by cuddInitInteract().
static void ddUpdateInteract (DdManager * table, int * support) [static]
Function********************************************************************
Synopsis [Marks as interacting all pairs of variables that appear in support.]
Description [If support[i] == support[j] == 1, sets the (i,j) entry of the interaction matrix to 1.]
SideEffects [None]
SeeAlso []
Definition at line 354 of file cuddInteract.c.
References cuddSetInteract(), and DdManager::size.
Referenced by cuddInitInteract().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddInteract.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 82 of file cuddInteract.c.