cuddGenCof.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/st.h>
#include <bdd/cuddInt.h>
Data Structures
struct MarkCacheKey
Defines
#define DD_LIC_DC 0
#define DD_LIC_1 1
#define DD_LIC_0 2
#define DD_LIC_NL 3
Functions
static int cuddBddConstrainDecomp ARGS ((DdManager *dd, DdNode *f, DdNode **decomp))
static DdNode *cuddBddCharToVect ARGS ((DdManager *dd, DdNode *f, DdNode *x))
static int cuddBddLICMarkEdges ARGS ((DdManager *dd, DdNode *f, DdNode *c, st_table *table, st_table *cache))
static DdNode *cuddBddLICBuildResult ARGS ((DdManager *dd, DdNode *f, st_table *cache, st_table *table))
static int MarkCacheHash ARGS ((char *ptr, int modulus))
static int MarkCacheCompare ARGS ((const char *ptr1, const char *ptr2))
static enum st_retval MarkCacheCleanUp ARGS ((char *key, char *value, char *arg))
static DdNode *cuddBddSqueeze ARGS ((DdManager *dd, DdNode *l, DdNode *u))
DdNode * Cudd_bddConstrain (DdManager *dd, DdNode *f, DdNode *c)
DdNode * Cudd_bddRestrict (DdManager *dd, DdNode *f, DdNode *c)
DdNode * Cudd_addConstrain (DdManager *dd, DdNode *f, DdNode *c)
DdNode ** Cudd_bddConstrainDecomp (DdManager *dd, DdNode *f)
DdNode * Cudd_addRestrict (DdManager *dd, DdNode *f, DdNode *c)
DdNode ** Cudd_bddCharToVect (DdManager *dd, DdNode *f)
DdNode * Cudd_bddLICompaction (DdManager *dd, DdNode *f, DdNode *c)
DdNode * Cudd_bddSqueeze (DdManager *dd, DdNode *l, DdNode *u)
DdNode * Cudd_bddMinimize (DdManager *dd, DdNode *f, DdNode *c)
DdNode * Cudd_SubsetCompress (DdManager *dd, DdNode *f, int nvars, int threshold)
DdNode * Cudd_SupersetCompress (DdManager *dd, DdNode *f, int nvars, int threshold)
DdNode * cuddBddConstrainRecur (DdManager *dd, DdNode *f, DdNode *c)
DdNode * cuddBddRestrictRecur (DdManager *dd, DdNode *f, DdNode *c)
DdNode * cuddAddConstrainRecur (DdManager *dd, DdNode *f, DdNode *c)
DdNode * cuddAddRestrictRecur (DdManager *dd, DdNode *f, DdNode *c)
DdNode * cuddBddLICompaction (DdManager *dd, DdNode *f, DdNode *c)
static int cuddBddConstrainDecomp (DdManager *dd, DdNode *f, DdNode **decomp)
static DdNode * cuddBddCharToVect (DdManager *dd, DdNode *f, DdNode *x)
static int cuddBddLICMarkEdges (DdManager *dd, DdNode *f, DdNode *c, st_table *table, st_table *cache)
static DdNode * cuddBddLICBuildResult (DdManager *dd, DdNode *f, st_table *cache, st_table *table)
static int MarkCacheHash (char *ptr, int modulus)
static int MarkCacheCompare (const char *ptr1, const char *ptr2)
static enum st_retval MarkCacheCleanUp (char *key, char *value, char *arg)
static DdNode * cuddBddSqueeze (DdManager *dd, DdNode *l, DdNode *u)
Variables
static char rcsid[] DD_UNUSED = `$Id: cuddGenCof.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Define Documentation
#define DD_LIC_0 2
Definition at line 65 of file cuddGenCof.c.
Referenced by cuddBddLICMarkEdges().
#define DD_LIC_1 1
Definition at line 64 of file cuddGenCof.c.
Referenced by cuddBddLICBuildResult(), and cuddBddLICMarkEdges().
#define DD_LIC_DC 0
CFile***********************************************************************
FileName [cuddGenCof.c]
PackageName [cudd]
Synopsis [Generalized cofactors for BDDs and ADDs.]
Description [External procedures included in this module:
Cudd_bddConstrain()
Cudd_bddRestrict()
Cudd_addConstrain()
Cudd_bddConstrainDecomp()
Cudd_addRestrict()
Cudd_bddCharToVect()
Cudd_bddLICompaction()
Cudd_bddSqueeze()
Cudd_SubsetCompress()
Cudd_SupersetCompress()
Internal procedures included in this module:
cuddBddConstrainRecur()
cuddBddRestrictRecur()
cuddAddConstrainRecur()
cuddAddRestrictRecur()
cuddBddLICompaction()
Static procedures included in this module:
cuddBddConstrainDecomp()
cuddBddCharToVect()
cuddBddLICMarkEdges()
cuddBddLICBuildResult()
cuddBddSqueeze()
]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 63 of file cuddGenCof.c.
Referenced by cuddBddLICBuildResult(), and cuddBddLICMarkEdges().
#define DD_LIC_NL 3
Definition at line 66 of file cuddGenCof.c.
Referenced by cuddBddLICBuildResult().
Function Documentation
static DdNode* cuddBddSqueeze ARGS ((DdManager *dd, DdNode *l, DdNode *u)) [static]
static enum st_retval MarkCacheCleanUp ARGS ((char *key, char *value, char *arg)) [static]
static int MarkCacheCompare ARGS ((const char *ptr1, const char *ptr2)) [static]
static int MarkCacheHash ARGS ((char *ptr, int modulus)) [static]
static DdNode* cuddBddLICBuildResult ARGS ((DdManager *dd, DdNode *f, st_table *cache, st_table *table)) [static]
static int cuddBddLICMarkEdges ARGS ((DdManager *dd, DdNode *f, DdNode *c, st_table *table, st_table *cache)) [static]
static DdNode* cuddBddCharToVect ARGS ((DdManager *dd, DdNode *f, DdNode *x)) [static]
static int cuddBddConstrainDecomp ARGS ((DdManager *dd, DdNode *f, DdNode **decomp)) [static]
AutomaticStart
DdNode* Cudd_addConstrain (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Computes f constrain c for ADDs.]
Description [Computes f constrain c (f @ c), for f an ADD and c a 0-1 ADD. List of special cases:
F @ 0 = 0
F @ 1 = F
0 @ c = 0
1 @ c = 1
F @ F = 1
Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain]
Definition at line 262 of file cuddGenCof.c.
References cuddAddConstrainRecur(), and DdManager::reordered.
Referenced by cuddAddConstrainRecur().
DdNode* Cudd_addRestrict (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [ADD restrict according to Coudert and Madre's algorithm (ICCAD90).]
Description [ADD restrict according to Coudert and Madre's algorithm (ICCAD90). Returns the restricted ADD if successful; otherwise NULL. If application of restrict results in an ADD larger than the input ADD, the input ADD is returned.]
SideEffects [None]
SeeAlso [Cudd_addConstrain Cudd_bddRestrict]
Definition at line 357 of file cuddGenCof.c.
References Cudd_bddLiteralSetIntersection(), Cudd_DagSize(), Cudd_RecursiveDeref(), Cudd_Support(), cuddAddRestrictRecur(), cuddRef, DD_ONE, and DdManager::reordered.
Referenced by cuddAddRestrictRecur().
DdNode** Cudd_bddCharToVect (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [Computes a vector whose image equals a non-zero function.]
Description [Computes a vector of BDDs whose image equals a non-zero function. The result depends on the variable order. The i-th component of the vector depends only on the first i variables in the order. Each BDD in the vector is not larger than the BDD of the given characteristic function. This function is based on the description of char-to-vect in `Verification of Sequential Machines Using Boolean Functional Vectors` by O. Coudert, C. Berthet and J. C. Madre. Returns a pointer to an array containing the result if successful; NULL otherwise. The size of the array equals the number of variables in the manager. The components of the solution have their reference counts already incremented (unlike the results of most other functions in the package.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain]
Definition at line 436 of file cuddGenCof.c.
References ALLOC, Cudd_IterDerefBdd(), CUDD_MEMORY_OUT, Cudd_Not, cuddBddCharToVect(), cuddRef, DD_ONE, DdManager::errorCode, FREE, DdManager::invperm, DdManager::reordered, DdManager::size, and DdManager::vars.
DdNode* Cudd_bddConstrain (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Computes f constrain c.]
Description [Computes f constrain c (f @ c). Uses a canonical form: (f' @ c) = (f @ c)'. (Note: this is not true for c.) List of special cases:
F @ 0 = 0
F @ 1 = F
0 @ c = 0
1 @ c = 1
F @ F = 1
F @ F'= 0
Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddRestrict Cudd_addConstrain]
Definition at line 142 of file cuddGenCof.c.
References cuddBddConstrainRecur(), and DdManager::reordered.
Referenced by cuddBddConstrainRecur().
DdNode** Cudd_bddConstrainDecomp (DdManager * dd, DdNode * f)
Function********************************************************************
Synopsis [BDD conjunctive decomposition as in McMillan's CAV96 paper.]
Description [BDD conjunctive decomposition as in McMillan's CAV96 paper. The decomposition is canonical only for a given variable order. If canonicity is required, variable ordering must be disabled after the decomposition has been computed. Returns an array with one entry for each BDD variable in the manager if successful; otherwise NULL. The components of the solution have their reference counts already incremented (unlike the results of most other functions in the package.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain Cudd_bddExistAbstract]
Definition at line 297 of file cuddGenCof.c.
References ALLOC, Cudd_IterDerefBdd(), CUDD_MEMORY_OUT, cuddBddConstrainDecomp(), cuddRef, DD_ONE, DdManager::errorCode, FREE, DdManager::reordered, and DdManager::size.
DdNode* Cudd_bddLICompaction (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs safe minimization of a BDD.]
Description [Performs safe minimization of a BDD. Given the BDD f of a function to be minimized and a BDD c representing the care set, Cudd_bddLICompaction produces the BDD of a function that agrees with f wherever c is 1. Safe minimization means that the size of the result is guaranteed not to exceed the size of f. This function is based on the DAC97 paper by Hong et al.. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddRestrict]
Definition at line 496 of file cuddGenCof.c.
References cuddBddLICompaction(), and DdManager::reordered.
Referenced by Cudd_bddApproxConjDecomp(), Cudd_bddIterConjDecomp(), and Cudd_bddMinimize().
DdNode* Cudd_bddMinimize (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Finds a small BDD that agrees with f over c.]
Description [Finds a small BDD that agrees with f over c. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddRestrict Cudd_bddLICompaction Cudd_bddSqueeze]
Definition at line 579 of file cuddGenCof.c.
References Cudd_bddLICompaction(), Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, Cudd_RemapOverApprox(), cuddDeref, cuddRef, and DD_ONE.
DdNode* Cudd_bddRestrict (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [BDD restrict according to Coudert and Madre's algorithm (ICCAD90).]
Description [BDD restrict according to Coudert and Madre's algorithm (ICCAD90). Returns the restricted BDD if successful; otherwise NULL. If application of restrict results in a BDD larger than the input BDD, the input BDD is returned.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain Cudd_addRestrict]
Definition at line 174 of file cuddGenCof.c.
References Cudd_bddExistAbstract(), Cudd_ClassifySupport(), Cudd_DagSize(), Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, cuddBddRestrictRecur(), cuddDeref, cuddRef, and DD_ONE.
Referenced by cuddBddRestrictRecur().
DdNode* Cudd_bddSqueeze (DdManager * dd, DdNode * l, DdNode * u)
Function********************************************************************
Synopsis [Finds a small BDD in a function interval.]
Description [Finds a small BDD in a function interval. Given BDDs l and u, representing the lower bound and upper bound of a function interval, Cudd_bddSqueeze produces the BDD of a function within the interval with a small BDD. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddRestrict Cudd_bddLICompaction]
Definition at line 528 of file cuddGenCof.c.
References Cudd_DagSize(), Cudd_IterDerefBdd(), cuddBddSqueeze(), cuddRef, and DdManager::reordered.
Referenced by Cudd_bddApproxConjDecomp(), Cudd_bddIterConjDecomp(), Cudd_SubsetCompress(), and cuddBddSqueeze().
DdNode* Cudd_SubsetCompress (DdManager * dd, DdNode * f, int nvars, int threshold)
Function********************************************************************
Synopsis [Find a dense subset of BDD f.]
Description [Finds a dense subset of BDD f. Density is the ratio of number of minterms to number of nodes. Uses several techniques in series. It is more expensive than other subsetting procedures, but often produces better results. See Cudd_SubsetShortPaths for a description of the threshold and nvars parameters. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_SubsetRemap Cudd_SubsetShortPaths Cudd_SubsetHeavyBranch Cudd_bddSqueeze]
Definition at line 626 of file cuddGenCof.c.
References Cudd_bddSqueeze(), Cudd_IterDerefBdd(), Cudd_RemapUnderApprox(), Cudd_SubsetShortPaths(), cuddDeref, and cuddRef.
Referenced by Cudd_SupersetCompress().
DdNode* Cudd_SupersetCompress (DdManager * dd, DdNode * f, int nvars, int threshold)
Function********************************************************************
Synopsis [Find a dense superset of BDD f.]
Description [Finds a dense superset of BDD f. Density is the ratio of number of minterms to number of nodes. Uses several techniques in series. It is more expensive than other supersetting procedures, but often produces better results. See Cudd_SupersetShortPaths for a description of the threshold and nvars parameters. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_SubsetCompress Cudd_SupersetRemap Cudd_SupersetShortPaths Cudd_SupersetHeavyBranch Cudd_bddSqueeze]
Definition at line 676 of file cuddGenCof.c.
References Cudd_Not, Cudd_NotCond, and Cudd_SubsetCompress().
DdNode* cuddAddConstrainRecur (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addConstrain.]
Description [Performs the recursive step of Cudd_addConstrain. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_addConstrain]
Definition at line 986 of file cuddGenCof.c.
References Cudd_addConstrain(), Cudd_IsConstant, Cudd_RecursiveDeref(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_addConstrain().
DdNode* cuddAddRestrictRecur (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_addRestrict.]
Description [Performs the recursive step of Cudd_addRestrict. Returns the restricted ADD if successful; otherwise NULL.]
SideEffects [None]
SeeAlso [Cudd_addRestrict]
Definition at line 1089 of file cuddGenCof.c.
References Cudd_addOr(), Cudd_addRestrict(), Cudd_IsConstant, Cudd_RecursiveDeref(), cuddAddApplyRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, DD_ZERO, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_addRestrict().
static DdNode* cuddBddCharToVect (DdManager * dd, DdNode * f, DdNode * x) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddCharToVect.]
Description [Performs the recursive step of Cudd_bddCharToVect. This function maintains the invariant that f is non-zero. Returns the i-th component of the vector if successful; otherwise NULL.]
SideEffects [None]
SeeAlso [Cudd_bddCharToVect]
Definition at line 1347 of file cuddGenCof.c.
References Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddBddIteRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddI, cuddRef, cuddT, DD_ONE, DdNode::index, one, DdManager::perm, and zero.
Referenced by Cudd_bddCharToVect().
static int cuddBddConstrainDecomp (DdManager * dd, DdNode * f, DdNode ** decomp) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddConstrainDecomp.]
Description [Performs the recursive step of Cudd_bddConstrainDecomp. Returns f super (i) if successful; otherwise NULL.]
SideEffects [None]
SeeAlso [Cudd_bddConstrainDecomp]
Definition at line 1285 of file cuddGenCof.c.
References Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, Cudd_Regular, cuddBddAndRecur(), cuddBddConstrainRecur(), cuddE, cuddRef, cuddT, DdNode::index, and result.
Referenced by Cudd_bddConstrainDecomp().
DdNode* cuddBddConstrainRecur (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddConstrain.]
Description [Performs the recursive step of Cudd_bddConstrain. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddConstrain]
Definition at line 709 of file cuddGenCof.c.
References Cudd_bddConstrain(), Cudd_IsComplement, Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, one, DdManager::perm, and zero.
Referenced by Cudd_bddConstrain(), and cuddBddConstrainDecomp().
static DdNode* cuddBddLICBuildResult (DdManager * dd, DdNode * f, st_table * cache, st_table * table) [static]
Function********************************************************************
Synopsis [Builds the result of Cudd_bddLICompaction.]
Description [Builds the results of Cudd_bddLICompaction. Returns a pointer to the minimized BDD if successful; otherwise NULL.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction cuddBddLICMarkEdges]
Definition at line 1549 of file cuddGenCof.c.
References Cudd_IsComplement, Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_LIC_1, DD_LIC_DC, DD_LIC_NL, DD_ONE, one, DdManager::perm, st_insert(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by cuddBddLICompaction().
static int cuddBddLICMarkEdges (DdManager * dd, DdNode * f, DdNode * c, st_table * table, st_table * cache) [static]
Function********************************************************************
Synopsis [Performs the edge marking step of Cudd_bddLICompaction.]
Description [Performs the edge marking step of Cudd_bddLICompaction. Returns the LUB of the markings of the two outgoing edges of f if successful; otherwise CUDD_OUT_OF_MEM.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction cuddBddLICBuildResult]
Definition at line 1427 of file cuddGenCof.c.
References ALLOC, MarkCacheKey::c, Cudd_IsComplement, CUDD_MEMORY_OUT, Cudd_Not, CUDD_OUT_OF_MEM, Cudd_Regular, cuddE, cuddI, cuddT, DD_LIC_0, DD_LIC_1, DD_LIC_DC, DD_ONE, DdManager::errorCode, MarkCacheKey::f, FREE, DdNode::index, one, DdManager::perm, st_find_or_add(), st_insert(), st_lookup(), ST_OUT_OF_MEM, and zero.
Referenced by cuddBddLICompaction().
DdNode* cuddBddLICompaction (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs safe minimization of a BDD.]
Description [Performs safe minimization of a BDD. Given the BDD f of a function to be minimized and a BDD c representing the care set, Cudd_bddLICompaction produces the BDD of a function that agrees with f wherever c is 1. Safe minimization means that the size of the result is guaranteed not to exceed the size of f. This function is based on the DAC97 paper by Hong et al.. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction]
Definition at line 1215 of file cuddGenCof.c.
References Cudd_Not, CUDD_OUT_OF_MEM, cuddBddLICBuildResult(), cuddBddLICMarkEdges(), DD_ONE, MarkCacheCleanUp(), MarkCacheCompare(), MarkCacheHash(), st_foreach(), st_free_table(), st_init_table(), st_ptrcmp(), st_ptrhash(), and zero.
Referenced by Cudd_bddLICompaction().
DdNode* cuddBddRestrictRecur (DdManager * dd, DdNode * f, DdNode * c)
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddRestrict.]
Description [Performs the recursive step of Cudd_bddRestrict. Returns the restricted BDD if successful; otherwise NULL.]
SideEffects [None]
SeeAlso [Cudd_bddRestrict]
Definition at line 837 of file cuddGenCof.c.
References Cudd_bddRestrict(), Cudd_IsComplement, Cudd_IsConstant, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddBddAndRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, one, DdManager::perm, and zero.
Referenced by Cudd_bddRestrict(), and cuddSolveEqnRecur().
static DdNode* cuddBddSqueeze (DdManager * dd, DdNode * l, DdNode * u) [static]
Function********************************************************************
Synopsis [Performs the recursive step of Cudd_bddSqueeze.]
Description [Performs the recursive step of Cudd_bddSqueeze. This procedure exploits the fact that if we complement and swap the bounds of the interval we obtain a valid solution by taking the complement of the solution to the original problem. Therefore, we can enforce the condition that the upper bound is always regular. Returns a pointer to the result if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddSqueeze]
Definition at line 1752 of file cuddGenCof.c.
References Cudd_bddLeq(), Cudd_bddSqueeze(), Cudd_DagSize(), Cudd_IsComplement, Cudd_IterDerefBdd(), Cudd_Not, Cudd_NotCond, Cudd_Regular, cuddBddAndRecur(), cuddCacheInsert2(), cuddCacheLookup2(), cuddDeref, cuddE, cuddRef, cuddT, cuddUniqueInter(), DD_ONE, one, DdManager::perm, and zero.
Referenced by Cudd_bddSqueeze().
static enum st_retval MarkCacheCleanUp (char * key, char * value, char * arg) [static]
Function********************************************************************
Synopsis [Frees memory associated with computed table of cuddBddLICMarkEdges.]
Description [Frees memory associated with computed table of cuddBddLICMarkEdges. Returns ST_CONTINUE.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction]
Definition at line 1721 of file cuddGenCof.c.
References entry, FREE, and ST_CONTINUE.
Referenced by cuddBddLICompaction().
static int MarkCacheCompare (const char * ptr1, const char * ptr2) [static]
Function********************************************************************
Synopsis [Comparison function for the computed table of cuddBddLICMarkEdges.]
Description [Comparison function for the computed table of cuddBddLICMarkEdges. Returns 0 if the two nodes of the key are equal; 1 otherwise.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction]
Definition at line 1692 of file cuddGenCof.c.
References MarkCacheKey::c, and MarkCacheKey::f.
Referenced by cuddBddLICompaction().
static int MarkCacheHash (char * ptr, int modulus) [static]
Function********************************************************************
Synopsis [Hash function for the computed table of cuddBddLICMarkEdges.]
Description [Hash function for the computed table of cuddBddLICMarkEdges. Returns the bucket number.]
SideEffects [None]
SeeAlso [Cudd_bddLICompaction]
Definition at line 1660 of file cuddGenCof.c.
References entry.
Referenced by cuddBddLICompaction().
Variable Documentation
char rcsid [] DD_UNUSED = `$Id: cuddGenCof.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
Definition at line 88 of file cuddGenCof.c.