datalimit.c File Reference
#include <config.h>
#include <sys/time.h>
#include <sys/resource.h>
Defines
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_GETRLIMIT 1
#define RLIMIT_DATA_DEFAULT 16777216
#define EXTERN extern
Functions
EXTERN long getSoftDataLimit ()
Define Documentation
#define EXTERN extern
Definition at line 31 of file datalimit.c.
#define HAVE_GETRLIMIT 1
Definition at line 13 of file datalimit.c.
#define HAVE_SYS_RESOURCE_H 1
Definition at line 7 of file datalimit.c.
#define HAVE_SYS_TIME_H 1
Definition at line 10 of file datalimit.c.
#define RLIMIT_DATA_DEFAULT 16777216
Definition at line 24 of file datalimit.c.
Referenced by getSoftDataLimit().
Function Documentation
long getSoftDataLimit ()
Definition at line 38 of file datalimit.c.
References result, and RLIMIT_DATA_DEFAULT.
Referenced by Cudd_Init(), Cudd_SetLooseUpTo(), and Cudd_SetMaxCacheHard().