mtrBasic.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/mtrInt.h>
Functions
MtrNode * Mtr_AllocNode ()
void Mtr_DeallocNode (MtrNode *node)
MtrNode * Mtr_InitTree ()
void Mtr_FreeTree (MtrNode *node)
MtrNode * Mtr_CopyTree (MtrNode *node, int expansion)
void Mtr_MakeFirstChild (MtrNode *parent, MtrNode *child)
void Mtr_MakeLastChild (MtrNode *parent, MtrNode *child)
MtrNode * Mtr_CreateFirstChild (MtrNode *parent)
MtrNode * Mtr_CreateLastChild (MtrNode *parent)
void Mtr_MakeNextSibling (MtrNode *first, MtrNode *second)
void Mtr_PrintTree (MtrNode *node)
Variables
static char rcsid[] MTR_UNUSED = `$Id: mtrBasic.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
MtrNode* Mtr_AllocNode ()
Function********************************************************************
Synopsis [Allocates new tree node.]
Description [Allocates new tree node. Returns pointer to node.]
SideEffects [None]
SeeAlso [Mtr_DeallocNode]
Definition at line 91 of file mtrBasic.c.
References ALLOC.
Referenced by Mtr_CopyTree(), Mtr_CreateFirstChild(), Mtr_CreateLastChild(), Mtr_InitTree(), and Mtr_MakeGroup().
MtrNode* Mtr_CopyTree (MtrNode * node, int expansion)
Function********************************************************************
Synopsis [Makes a copy of tree.]
Description [Makes a copy of tree. If parameter expansion is greater than 1, it will expand the tree by that factor. It is an error for expansion to be less than 1. Returns a pointer to the copy if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Mtr_InitTree]
Definition at line 190 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, MtrNode::index, MtrNode::low, Mtr_AllocNode(), Mtr_DeallocNode(), Mtr_FreeTree(), MtrNode::parent, MtrNode::size, and MtrNode::younger.
Referenced by Cudd_zddVarsFromBddVars().
MtrNode* Mtr_CreateFirstChild (MtrNode * parent)
Function********************************************************************
Synopsis [Creates a new node and makes it the first child of parent.]
Description [Creates a new node and makes it the first child of parent. Returns pointer to new child.]
SideEffects [None]
SeeAlso [Mtr_MakeFirstChild Mtr_CreateLastChild]
Definition at line 312 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, Mtr_AllocNode(), Mtr_MakeFirstChild(), MtrNode::parent, and MtrNode::younger.
MtrNode* Mtr_CreateLastChild (MtrNode * parent)
Function********************************************************************
Synopsis [Creates a new node and makes it the last child of parent.]
Description [Creates a new node and makes it the last child of parent. Returns pointer to new child.]
SideEffects [None]
SeeAlso [Mtr_MakeLastChild Mtr_CreateFirstChild]
Definition at line 341 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, Mtr_AllocNode(), Mtr_MakeLastChild(), MtrNode::parent, and MtrNode::younger.
void Mtr_DeallocNode (MtrNode * node)
Function********************************************************************
Synopsis [Deallocates tree node.]
Description []
SideEffects [None]
SeeAlso [Mtr_AllocNode]
Definition at line 114 of file mtrBasic.c.
References FREE.
Referenced by Mtr_CopyTree(), Mtr_DissolveGroup(), and Mtr_FreeTree().
void Mtr_FreeTree (MtrNode * node)
Function********************************************************************
Synopsis [Disposes of tree rooted at node.]
Description []
SideEffects [None]
SeeAlso [Mtr_InitTree]
Definition at line 163 of file mtrBasic.c.
References MtrNode::child, Mtr_DeallocNode(), MTR_TERMINAL, MTR_TEST, and MtrNode::younger.
Referenced by Cudd_FreeTree(), Cudd_FreeZddTree(), Cudd_SetTree(), Cudd_SetZddTree(), cuddFreeTable(), and Mtr_CopyTree().
MtrNode* Mtr_InitTree ()
Function********************************************************************
Synopsis [Initializes tree with one node.]
Description [Initializes tree with one node. Returns pointer to node.]
SideEffects [None]
SeeAlso [Mtr_FreeTree Mtr_InitGroupTree]
Definition at line 135 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, Mtr_AllocNode(), MtrNode::parent, and MtrNode::younger.
Referenced by Mtr_InitGroupTree().
void Mtr_MakeFirstChild (MtrNode * parent, MtrNode * child)
Function********************************************************************
Synopsis [Makes child the first child of parent.]
Description []
SideEffects [None]
SeeAlso [Mtr_MakeLastChild Mtr_CreateFirstChild]
Definition at line 244 of file mtrBasic.c.
References assert, MtrNode::child, MtrNode::elder, MtrNode::parent, and MtrNode::younger.
Referenced by Mtr_CreateFirstChild().
void Mtr_MakeLastChild (MtrNode * parent, MtrNode * child)
Function********************************************************************
Synopsis [Makes child the last child of parent.]
Description []
SideEffects [None]
SeeAlso [Mtr_MakeFirstChild Mtr_CreateLastChild]
Definition at line 275 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::parent, and MtrNode::younger.
Referenced by Mtr_CreateLastChild().
void Mtr_MakeNextSibling (MtrNode * first, MtrNode * second)
Function********************************************************************
Synopsis [Makes second the next sibling of first.]
Description [Makes second the next sibling of first. Second becomes a child of the parent of first.]
SideEffects [None]
SeeAlso []
Definition at line 370 of file mtrBasic.c.
References MtrNode::elder, MtrNode::parent, and MtrNode::younger.
void Mtr_PrintTree (MtrNode * node)
Function********************************************************************
Synopsis [Prints a tree, one node per line.]
Description []
SideEffects [None]
SeeAlso [Mtr_PrintGroups]
Definition at line 398 of file mtrBasic.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, MTR_TERMINAL, MTR_TEST, MtrNode::parent, and MtrNode::younger.
Variable Documentation
char rcsid [] MTR_UNUSED = `$Id: mtrBasic.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [mtrBasic.c]
PackageName [mtr]
Synopsis [Basic manipulation of multiway branching trees.]
Description [External procedures included in this module:
Mtr_AllocNode()
Mtr_DeallocNode()
Mtr_InitTree()
Mtr_FreeTree()
Mtr_MakeFirstChild()
Mtr_MakeLastChild()
Mtr_CreateFirstChild()
Mtr_CreateLastChild()
Mtr_MakeNextSibling()
Mtr_PrintTree()
]
SeeAlso [cudd package]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 58 of file mtrBasic.c.