mtrGroup.c File Reference
#include <config.h>
#include <bdd/util.h>
#include <bdd/mtrInt.h>
Functions
static int mtrShiftHL ARGS ((MtrNode *node, int shift))
MtrNode * Mtr_InitGroupTree (int lower, int size)
MtrNode * Mtr_MakeGroup (MtrNode *root, unsigned int low, unsigned int size, unsigned int flags)
MtrNode * Mtr_DissolveGroup (MtrNode *group)
MtrNode * Mtr_FindGroup (MtrNode *root, unsigned int low, unsigned int size)
int Mtr_SwapGroups (MtrNode *first, MtrNode *second)
void Mtr_PrintGroups (MtrNode *root, int silent)
MtrNode * Mtr_ReadGroups (FILE *fp, int nleaves)
static int mtrShiftHL (MtrNode *node, int shift)
Variables
static char rcsid[] MTR_UNUSED = `$Id: mtrGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $`
Function Documentation
static int mtrShiftHL ARGS ((MtrNode *node, int shift)) [static]
AutomaticStart
MtrNode* Mtr_DissolveGroup (MtrNode * group)
Function********************************************************************
Synopsis [Merges the children of `group' with the children of its parent.]
Description [Merges the children of `group' with the children of its parent. Disposes of the node pointed by group. If group is the root of the group tree, this procedure leaves the tree unchanged. Returns the pointer to the parent of `group' upon successful termination; NULL otherwise.]
SideEffects [None]
SeeAlso [Mtr_MakeGroup]
Definition at line 328 of file mtrGroup.c.
References MtrNode::child, MtrNode::elder, Mtr_DeallocNode(), MTR_TERMINAL, MTR_TEST, MtrNode::parent, and MtrNode::younger.
MtrNode* Mtr_FindGroup (MtrNode * root, unsigned int low, unsigned int size)
Function********************************************************************
Synopsis [Finds a group with size leaves starting at low, if it exists.]
Description [Finds a group with size leaves starting at low, if it exists. This procedure relies on the low and size fields of each node. It also assumes that the children of each node are sorted in order of increasing low. Returns the pointer to the root of the group upon successful termination; NULL otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 380 of file mtrGroup.c.
References assert, MtrNode::child, MtrNode::low, MTR_TERMINAL, MTR_TEST, MtrNode::size, and MtrNode::younger.
MtrNode* Mtr_InitGroupTree (int lower, int size)
Function********************************************************************
Synopsis [Allocate new tree.]
Description [Allocate new tree with one node, whose low and size fields are specified by the lower and size parameters. Returns pointer to tree root.]
SideEffects [None]
SeeAlso [Mtr_InitTree Mtr_FreeTree]
Definition at line 94 of file mtrGroup.c.
References MtrNode::flags, MtrNode::low, MTR_DEFAULT, Mtr_InitTree(), and MtrNode::size.
Referenced by Cudd_MakeTreeNode(), Cudd_MakeZddTreeNode(), Cudd_zddVarsFromBddVars(), cuddTreeSifting(), cuddZddTreeSifting(), and Mtr_ReadGroups().
MtrNode* Mtr_MakeGroup (MtrNode * root, unsigned int low, unsigned int size, unsigned int flags)
Function********************************************************************
Synopsis [Makes a new group with size leaves starting at low.]
Description [Makes a new group with size leaves starting at low. If the new group intersects an existing group, it must either contain it or be contained by it. This procedure relies on the low and size fields of each node. It also assumes that the children of each node are sorted in order of increasing low. In case of a valid request, the flags of the new group are set to the value passed in `flags.' This can also be used to change the flags of an existing group. Returns the pointer to the root of the new group upon successful termination; NULL otherwise. If the group already exists, the pointer to its root is returned.]
SideEffects [None]
SeeAlso [Mtr_DissolveGroup Mtr_ReadGroups Mtr_FindGroup]
Definition at line 131 of file mtrGroup.c.
References MtrNode::child, MtrNode::elder, MtrNode::flags, MtrNode::low, Mtr_AllocNode(), MtrNode::parent, MtrNode::size, and MtrNode::younger.
Referenced by Cudd_MakeTreeNode(), Cudd_MakeZddTreeNode(), and Mtr_ReadGroups().
void Mtr_PrintGroups (MtrNode * root, int silent)
Function********************************************************************
Synopsis [Prints the groups as a parenthesized list.]
Description [Prints the groups as a parenthesized list. After each group, the group's flag are printed, preceded by a `|'. For each flag (except MTR_TERMINAL) a character is printed.
F: MTR_FIXED
N: MTR_NEWNODE
S: MTR_SOFT
The second argument, silent, if different from 0, causes Mtr_PrintGroups to only check the syntax of the group tree. ]
SideEffects [None]
SeeAlso [Mtr_PrintTree]
Definition at line 508 of file mtrGroup.c.
References assert, MtrNode::child, MtrNode::elder, MtrNode::flags, MtrNode::low, MTR_DEFAULT, MTR_FIXED, MTR_NEWNODE, MTR_SOFT, MTR_TERMINAL, MTR_TEST, MtrNode::parent, MtrNode::size, and MtrNode::younger.
Referenced by cuddTreeSifting(), cuddZddTreeSifting(), ddTreeSiftingAux(), and zddTreeSiftingAux().
MtrNode* Mtr_ReadGroups (FILE * fp, int nleaves)
Function********************************************************************
Synopsis [Reads groups from a file and creates a group tree.]
Description [Reads groups from a file and creates a group tree. Each group is specified by three fields: <xmp> low size flags. </xmp> Low and size are (short) integers. Flags is a string composed of the following characters (with associated translation):
D: MTR_DEFAULT
F: MTR_FIXED
N: MTR_NEWNODE
S: MTR_SOFT
T: MTR_TERMINAL
Normally, the only flags that are needed are D and F. Groups and fields are separated by white space (spaces, tabs, and newlines). Returns a pointer to the group tree if successful; NULL otherwise.]
SideEffects [None]
SeeAlso [Mtr_InitGroupTree Mtr_MakeGroup]
Definition at line 574 of file mtrGroup.c.
References MtrNode::flags, MtrNode::low, MTR_DEFAULT, MTR_FIXED, Mtr_InitGroupTree(), Mtr_MakeGroup(), MTR_NEWNODE, MTR_SOFT, MTR_TERMINAL, size, and strlen().
int Mtr_SwapGroups (MtrNode * first, MtrNode * second)
Function********************************************************************
Synopsis [Swaps two children of a tree node.]
Description [Swaps two children of a tree node. Adjusts the high and low fields of the two nodes and their descendants. The two children must be adjacent. However, first may be the younger sibling of second. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 441 of file mtrGroup.c.
References MtrNode::child, MtrNode::elder, mtrShiftHL(), MtrNode::parent, MtrNode::size, and MtrNode::younger.
static int mtrShiftHL (MtrNode * node, int shift) [static]
Function********************************************************************
Synopsis [Adjusts the low fields of a node and its descendants.]
Description [Adjusts the low fields of a node and its descendants. Adds shift to low of each node. Checks that no out-of-bounds values result. Returns 1 in case of success; 0 otherwise.]
SideEffects [None]
SeeAlso []
Definition at line 663 of file mtrGroup.c.
References MtrNode::child, MtrNode::low, MTR_MAXHIGH, MTR_TERMINAL, MTR_TEST, MtrNode::size, and MtrNode::younger.
Referenced by Mtr_SwapGroups().
Variable Documentation
char rcsid [] MTR_UNUSED = `$Id: mtrGroup.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $` [static]
CFile***********************************************************************
FileName [mtrGroup.c]
PackageName [mtr]
Synopsis [Functions to support group specification for reordering.]
Description [External procedures included in this module:
Mtr_InitGroupTree()
Mtr_MakeGroup()
Mtr_DissolveGroup()
Mtr_FindGroup()
Mtr_SwapGroups()
Mtr_PrintGroups()
Mtr_ReadGroups()
Static procedures included in this module:
mtrShiftHL
]
SeeAlso [cudd package]
Author [Fabio Somenzi]
Copyright [This file was created at the University of Colorado at Boulder. The University of Colorado at Boulder makes no warranty about the suitability of this software for any purpose. It is presented on an AS IS basis.]
Definition at line 58 of file mtrGroup.c.