pathsearch.c File Reference
#include <config.h>
#include <stdio.h>
#include <bdd/util.h>
Functions
static int check_file ARGS ((char *, char *))
char * util_path_search (char *prog)
char * util_file_search (char *file, char *path, char *mode)
static int check_file (char *filename, char *mode)
Function Documentation
static int check_file ARGS ((char *, char *)) [static]
static int check_file (char * filename, char * mode) [static]
Definition at line 69 of file pathsearch.c.
References strcmp().
Referenced by util_file_search().
char* util_file_search (char * file, char * path, char * mode)
Definition at line 22 of file pathsearch.c.
References ALLOC, check_file(), FREE, sprintf(), strchr(), strcmp(), strlen(), strsav, and util_tilde_expand().
Referenced by util_path_search().
char* util_path_search (char * prog)
Definition at line 11 of file pathsearch.c.
References getenv(), NIL, and util_file_search().