safe_mem.c File Reference
#include <config.h>
#include <stdio.h>
#include <bdd/util.h>
Functions
char * MMalloc ()
void MMout_of_memory ()
char * MMrealloc ()
void MMout_of_memory (long size)
char * MMalloc (long size)
char * MMrealloc (char *obj, long size)
void MMfree (char *obj)
Variables
void(*) MMoutOfMemory (long) = MMout_of_memory
Function Documentation
char* MMalloc (long size)
Definition at line 45 of file safe_mem.c.
References malloc(), MMoutOfMemory, and NIL.
char* MMalloc ()
Referenced by MMrealloc().
void MMfree (char * obj)
Definition at line 86 of file safe_mem.c.
References free().
void MMout_of_memory (long size)
Definition at line 36 of file safe_mem.c.
References exit().
void MMout_of_memory ()
char* MMrealloc (char * obj, long size)
Definition at line 65 of file safe_mem.c.
References MMalloc(), MMoutOfMemory, NIL, and realloc().
char* MMrealloc ()
Variable Documentation
void(*) MMoutOfMemory(long) = MMout_of_memory
Definition at line 31 of file safe_mem.c.
Referenced by cuddCacheResize(), cuddHashTableResize(), cuddLocalCacheResize(), ddRehash(), ddRehashZdd(), ddReorderPostprocess(), hashResize(), MMalloc(), MMrealloc(), and zddReorderPostprocess().