st.c File Reference
#include <config.h>
#include <stdio.h>
#include <bdd/util.h>
#include <bdd/st.h>
Defines
#define ST_NUMCMP(x, y) ((x) != (y))
#define ST_NUMHASH(x, size) (ABS((long)x)%(size))
#define ST_PTRHASH(x, size) ((int)((unsigned long)(x)>>2)%size)
#define EQUAL(func, x, y)
#define do_hash(key, table)
#define PTR_NOT_EQUAL(table, ptr, user_key) (ptr != NULL && !EQUAL(table $\rightarrow$ compare, user_key, (ptr) $\rightarrow$ key))
#define FIND_ENTRY(table, hash_val, key, ptr, last)
#define ADD_DIRECT(table, key, value, hash_val, newt)
Functions
static int rehash ARGS ((st_table *))
st_table * st_init_table_with_params (ST_PFICPCP compare, ST_PFICPI hash, int size, int density, double grow_factor, int reorder_flag)
st_table * st_init_table (ST_PFICPCP compare, ST_PFICPI hash)
void st_free_table (st_table *table)
int st_lookup (st_table *table, char *key, char **value)
int st_lookup_int (st_table *table, char *key, int *value)
int st_insert (st_table *table, char *key, char *value)
int st_add_direct (st_table *table, char *key, char *value)
int st_find_or_add (st_table *table, char *key, char ***slot)
int st_find (st_table *table, char *key, char ***slot)
static int rehash (st_table *table)
st_table * st_copy (st_table *old_table)
int st_delete (st_table *table, char **keyp, char **value)
int st_delete_int (st_table *table, int *keyp, char **value)
int st_foreach (st_table *table, ST_PFSR func, char *arg)
int st_strhash (char *string, int modulus)
int st_numhash (char *x, int size)
int st_ptrhash (char *x, int size)
int st_numcmp (const char *x, const char *y)
int st_ptrcmp (const char *x, const char *y)
st_generator * st_init_gen (st_table *table)
int st_gen (st_generator *gen, char **key_p, char **value_p)
int st_gen_int (st_generator *gen, char **key_p, long *value_p)
void st_free_gen (st_generator *gen)
Define Documentation
#define ADD_DIRECT(table, key, value, hash_val, newt)
Value:
{\
    if (table->num_entries/table->num_bins >= table->max_density) {\
        rehash(table);\
        hash_val = do_hash(key,table);\
    }\
    \
    newt = ALLOC(st_table_entry, 1);\
    \
    newt->key = key;\
    newt->record = value;\
    newt->next = table->bins[hash_val];\
    table->bins[hash_val] = newt;\
    table->num_entries++;\
}
Definition at line 151 of file st.c.
#define do_hash(key, table)
Value:
((int)((table->hash == st_ptrhash) ? ST_PTRHASH((key),(table)->num_bins) :\
     (table->hash == st_numhash) ? ST_NUMHASH((key), (table)->num_bins) :\
     (*table->hash)((key), (table)->num_bins)))
Definition at line 24 of file st.c.
Referenced by rehash(), st_add_direct(), st_delete(), st_delete_int(), st_find(), st_find_or_add(), st_insert(), st_lookup(), and st_lookup_int().
#define EQUAL(func, x, y)
Value:
((((func) == st_numcmp) || ((func) == st_ptrcmp)) ?\
      (ST_NUMCMP((x),(y)) == 0) : ((*func)((x), (y)) == 0))
Definition at line 19 of file st.c.
#define FIND_ENTRY(table, hash_val, key, ptr, last)
Value:
(last) = &(table)->bins[hash_val];\
    (ptr) = *(last);\
    while (PTR_NOT_EQUAL((table), (ptr), (key))) {\
        (last) = &(ptr)->next; (ptr) = *(last);\
    }\
    if ((ptr) != NULL && (table)->reorder_flag) {\
        *(last) = (ptr)->next;\
        (ptr)->next = (table)->bins[hash_val];\
        (table)->bins[hash_val] = (ptr);\
    }
Definition at line 98 of file st.c.
Referenced by st_delete(), st_delete_int(), st_find(), st_find_or_add(), st_insert(), st_lookup(), and st_lookup_int().
#define PTR_NOT_EQUAL(table, ptr, user_key) (ptr != NULL && !EQUAL(table $\rightarrow$ compare, user_key, (ptr) $\rightarrow$ key))
Definition at line 95 of file st.c.
#define ST_NUMCMP(x, y) ((x) != (y))
Definition at line 16 of file st.c.
Referenced by st_numcmp(), and st_ptrcmp().
#define ST_NUMHASH(x, size) (ABS((long)x)%(size))
Definition at line 17 of file st.c.
Referenced by st_numhash().
#define ST_PTRHASH(x, size) ((int)((unsigned long)(x)>>2)%size)
Definition at line 18 of file st.c.
Referenced by st_ptrhash().
Function Documentation
static int rehash ARGS ((st_table *)) [static]
static int rehash (st_table * table) [static]
Definition at line 281 of file st.c.
References ALLOC, st_table::bins, do_hash, FREE, st_table::grow_factor, st_table_entry::key, st_table_entry::next, NIL, st_table::num_bins, st_table::num_entries, and ST_OUT_OF_MEM.
Referenced by st_add_direct(), st_find_or_add(), and st_insert().
int st_add_direct (st_table * table, char * key, char * value)
Definition at line 202 of file st.c.
References ALLOC, st_table::bins, do_hash, st_table_entry::key, st_table::max_density, st_table_entry::next, NIL, st_table::num_bins, st_table::num_entries, st_table_entry::record, rehash(), and ST_OUT_OF_MEM.
Referenced by cuddBddTransferRecur(), cuddCollectNodes(), cuddEstimateCofactor(), ddCountMintermAux(), ddCountPathAux(), and dp2().
st_table* st_copy (st_table * old_table)
Definition at line 327 of file st.c.
References ALLOC, st_table::bins, FREE, st_table_entry::next, NIL, and st_table::num_bins.
int st_delete (st_table * table, char ** keyp, char ** value)
Definition at line 372 of file st.c.
References do_hash, FIND_ENTRY, FREE, st_table_entry::key, st_table_entry::next, NIL, st_table::num_entries, and st_table_entry::record.
Referenced by cuddGa().
int st_delete_int (st_table * table, int * keyp, char ** value)
Definition at line 395 of file st.c.
References do_hash, FIND_ENTRY, FREE, st_table_entry::key, st_table_entry::next, NIL, st_table::num_entries, and st_table_entry::record.
int st_find (st_table * table, char * key, char *** slot)
Definition at line 261 of file st.c.
References do_hash, FIND_ENTRY, NIL, and st_table_entry::record.
int st_find_or_add (st_table * table, char * key, char *** slot)
Definition at line 227 of file st.c.
References ALLOC, st_table::bins, do_hash, FIND_ENTRY, st_table_entry::key, st_table::max_density, st_table_entry::next, NIL, st_table::num_bins, st_table::num_entries, st_table_entry::record, rehash(), and ST_OUT_OF_MEM.
Referenced by cuddBddLICMarkEdges().
int st_foreach (st_table * table, ST_PFSR func, char * arg)
Definition at line 418 of file st.c.
References st_table::bins, FREE, st_table_entry::key, st_table_entry::next, NIL, st_table::num_bins, st_table::num_entries, st_table_entry::record, ST_CONTINUE, ST_DELETE, and ST_STOP.
Referenced by Cudd_ApaCountMinterm(), Cudd_bddCorrelation(), Cudd_bddCorrelationWeights(), Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), Cudd_zddCount(), Cudd_zddCountDouble(), cuddBddLICompaction(), and cuddSubsetShortPaths().
void st_free_gen (st_generator * gen)
Definition at line 553 of file st.c.
References FREE.
Referenced by Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_GenFree(), Cudd_zddDumpDot(), cuddBddTransfer(), cuddConjunctsAux(), and cuddSubsetHeavyBranch().
void st_free_table (st_table * table)
Definition at line 78 of file st.c.
References st_table::bins, FREE, st_table_entry::next, NIL, and st_table::num_bins.
Referenced by CreatePathTable(), CreateTopDist(), Cudd_ApaCountMinterm(), Cudd_bddCorrelation(), Cudd_bddCorrelationWeights(), Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), Cudd_DebugCheck(), Cudd_DumpBlif(), Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_EstimateCofactor(), Cudd_FirstNode(), Cudd_GenFree(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), Cudd_zddCount(), Cudd_zddCountDouble(), Cudd_zddDagSize(), cuddBddLICompaction(), cuddBddTransfer(), cuddConjunctsAux(), cuddGa(), cuddP(), cuddRemapUnderApprox(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddUnderApprox(), cuddZddP(), gatherInfo(), SubsetCountMinterm(), SubsetCountMintermAux(), and SubsetCountNodesAux().
int st_gen (st_generator * gen, char ** key_p, char ** value_p)
Definition at line 499 of file st.c.
References st_table::bins, st_generator::entry, st_generator::index, st_table_entry::key, st_table_entry::next, NIL, st_table_entry::record, and st_generator::table.
Referenced by Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_FirstNode(), Cudd_NextNode(), Cudd_zddDumpDot(), cuddBddTransfer(), cuddConjunctsAux(), and cuddSubsetHeavyBranch().
int st_gen_int (st_generator * gen, char ** key_p, long * value_p)
Definition at line 526 of file st.c.
References st_table::bins, st_generator::entry, st_generator::index, st_table_entry::key, st_table_entry::next, NIL, st_table_entry::record, and st_generator::table.
st_generator* st_init_gen (st_table * table)
Definition at line 483 of file st.c.
References ALLOC, st_generator::entry, st_generator::index, NIL, and st_generator::table.
Referenced by Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_FirstNode(), Cudd_zddDumpDot(), cuddBddTransfer(), cuddConjunctsAux(), and cuddSubsetHeavyBranch().
st_table* st_init_table (ST_PFICPCP compare, ST_PFICPI hash)
Definition at line 69 of file st.c.
References ST_DEFAULT_GROW_FACTOR, ST_DEFAULT_INIT_TABLE_SIZE, ST_DEFAULT_MAX_DENSITY, ST_DEFAULT_REORDER_FLAG, and st_init_table_with_params().
Referenced by CreatePathTable(), Cudd_ApaCountMinterm(), Cudd_bddCorrelation(), Cudd_bddCorrelationWeights(), Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), Cudd_DebugCheck(), Cudd_DumpBlif(), Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_EstimateCofactor(), Cudd_FirstNode(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), Cudd_zddCount(), Cudd_zddCountDouble(), Cudd_zddDagSize(), Cudd_zddDumpDot(), cuddBddLICompaction(), cuddBddTransfer(), cuddConjunctsAux(), cuddGa(), cuddP(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddP(), gatherInfo(), and SubsetCountMinterm().
st_table* st_init_table_with_params (ST_PFICPCP compare, ST_PFICPI hash, int size, int density, double grow_factor, int reorder_flag)
Definition at line 32 of file st.c.
References ALLOC, st_table::bins, st_table::compare, FREE, st_table::grow_factor, st_table::hash, st_table::max_density, NIL, st_table::num_bins, st_table::num_entries, and st_table::reorder_flag.
Referenced by st_init_table().
int st_insert (st_table * table, char * key, char * value)
Definition at line 168 of file st.c.
References ALLOC, st_table::bins, do_hash, FIND_ENTRY, st_table_entry::key, st_table::max_density, st_table_entry::next, NIL, st_table::num_bins, st_table::num_entries, st_table_entry::record, rehash(), and ST_OUT_OF_MEM.
Referenced by bddAnnotateMintermCount(), bddCorrelationAux(), bddCorrelationWeightsAux(), BuildConjuncts(), BuildSubsetBdd(), CheckInTables(), CheckTablesCacheAndReturn(), CountMinterms(), CreateBotDist(), CreatePathTable(), CreateTopDist(), Cudd_DebugCheck(), cuddApaCountMintermAux(), cuddBddLICBuildResult(), cuddBddLICMarkEdges(), cuddConjunctsAux(), cuddGa(), cuddSubsetHeavyBranch(), cuddZddCountDoubleStep(), cuddZddCountStep(), cuddZddDagInt(), ddDoDumpBlif(), ddDoDumpDaVinci(), ddDoDumpDDcal(), gatherInfo(), gatherInfoAux(), get_largest(), get_shortest(), PickOnePair(), StoreNodes(), SubsetCountMintermAux(), ZeroCase(), and zp2().
int st_lookup (st_table * table, char * key, char ** value)
Definition at line 111 of file st.c.
References do_hash, FIND_ENTRY, NIL, and st_table_entry::record.
Referenced by bddAnnotateMintermCount(), bddCorrelationAux(), bddCorrelationWeightsAux(), build_dd(), BuildConjuncts(), BuildSubsetBdd(), computeSavings(), CountMinterms(), CreateBotDist(), CreateTopDist(), Cudd_DebugCheck(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), cuddApaCountMintermAux(), cuddBddLICBuildResult(), cuddBddLICMarkEdges(), cuddBddTransferRecur(), cuddEstimateCofactor(), cuddGa(), cuddSplitSetRecur(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddCountDoubleStep(), cuddZddCountStep(), ddCofMintermAux(), ddCountMintermAux(), ddCountPathAux(), gatherInfoAux(), get_cube(), get_largest(), get_path(), get_shortest(), RAbuildSubset(), RAmarkNodes(), StoreNodes(), SubsetCountMintermAux(), SubsetCountNodesAux(), UAbuildSubset(), UAmarkNodes(), updateParity(), and updateRefs().
int st_lookup_int (st_table * table, char * key, int * value)
Definition at line 131 of file st.c.
References do_hash, FIND_ENTRY, NIL, and st_table_entry::record.
Referenced by BuildConjuncts(), CheckTablesCacheAndReturn(), PairInTables(), PickOnePair(), and ZeroCase().
int st_numcmp (const char * x, const char * y)
Definition at line 471 of file st.c.
References ST_NUMCMP.
int st_numhash (char * x, int size)
Definition at line 459 of file st.c.
References ST_NUMHASH.
int st_ptrcmp (const char * x, const char * y)
Definition at line 477 of file st.c.
References ST_NUMCMP.
Referenced by CreatePathTable(), Cudd_ApaCountMinterm(), Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), Cudd_DebugCheck(), Cudd_DumpBlif(), Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_EstimateCofactor(), Cudd_FirstNode(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), Cudd_zddCount(), Cudd_zddCountDouble(), Cudd_zddDagSize(), Cudd_zddDumpDot(), cuddBddLICompaction(), cuddBddTransfer(), cuddConjunctsAux(), cuddP(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddP(), gatherInfo(), and SubsetCountMinterm().
int st_ptrhash (char * x, int size)
Definition at line 465 of file st.c.
References ST_PTRHASH.
Referenced by CreatePathTable(), Cudd_ApaCountMinterm(), Cudd_CofMinterm(), Cudd_CountMinterm(), Cudd_CountPath(), Cudd_DebugCheck(), Cudd_DumpBlif(), Cudd_DumpDaVinci(), Cudd_DumpDDcal(), Cudd_DumpDot(), Cudd_EstimateCofactor(), Cudd_FirstNode(), Cudd_LargestCube(), Cudd_ShortestLength(), Cudd_ShortestPath(), Cudd_SplitSet(), Cudd_zddCount(), Cudd_zddCountDouble(), Cudd_zddDagSize(), Cudd_zddDumpDot(), cuddBddLICompaction(), cuddBddTransfer(), cuddConjunctsAux(), cuddP(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddP(), gatherInfo(), and SubsetCountMinterm().
int st_strhash (char * string, int modulus)
Definition at line 446 of file st.c.