texpand.c File Reference
#include <config.h>
#include <stdio.h>
#include <bdd/util.h>
Functions
char * util_tilde_expand (char *fname)
Function Documentation
char* util_tilde_expand (char * fname)
Definition at line 14 of file texpand.c.
References ALLOC, ARGS, strcat(), strlen(), and strsav.
Referenced by util_file_search().