util-std.h File Reference
#include <config.h>
Functions
double atof ()
double strtod ()
long strtol ()
long strtoul ()
long labs ()
int atoi ()
int rand ()
int atexit ()
int system ()
int abs ()
void srand ()
void free ()
void abort ()
void exit ()
void qsort ()
char * calloc ()
char ** realloc ()
char *** malloc ()
char **** bsearch ()
char ***** getenv ()
Function Documentation
void abort ()
int abs ()
int atexit ()
double atof ()
int atoi ()
char* * * * bsearch ()
char* calloc ()
void exit ()
Referenced by BuildSubsetBdd(), CreateBotDist(), CreatePathTable(), cuddSubsetHeavyBranch(), cuddSubsetShortPaths(), cuddZddIsop(), and MMout_of_memory().
void free ()
Referenced by MMfree().
char* * * * * getenv ()
Referenced by util_path_search().
long labs ()
char* * * malloc ()
Referenced by MMalloc().
void qsort ()
Referenced by cuddLinearAndSifting(), cuddSifting(), cuddSymmSifting(), cuddSymmSiftingConv(), cuddZddLinearSifting(), cuddZddSifting(), cuddZddSymmSifting(), and cuddZddSymmSiftingConv().
int rand ()
char* * realloc ()
Referenced by MMrealloc().
void srand ()
double strtod ()
long strtol ()
long strtoul ()
int system ()
Referenced by util_print_cpu_stats().