m_opti.c File Reference
#include <config.h>
#include <Lcode/l_main.h>
#include <Lcode/l_opti.h>
#include <Lcode/m_opti.h>
Functions
void L_read_parm_mopti (Parm_Parse_Info *ppi)
void Mopti_init (Parm_Macro_List *command_line_macro_list)
void Mopti_perform_optimizations (L_Func *fn, Parm_Macro_List *command_line_macro_list)
Variables
int Mopti_imax_num_iterations = 10
int Mopti_omax_num_iterations = 10
int Mopti_init_performed = 0
int Mopti_print_stats = 0
int Mopti_debug_copy_prop = 0
int Mopti_debug_common_subs = 0
int Mopti_debug_dead_code = 0
int Mopti_do_common_subs = 1
int Mopti_do_copy_prop = 1
int Mopti_do_dead_code = 1
Function Documentation
void L_read_parm_mopti (Parm_Parse_Info * ppi)
Definition at line 100 of file m_opti.c.
References Mopti_debug_common_subs, Mopti_debug_copy_prop, Mopti_debug_dead_code, Mopti_do_common_subs, Mopti_do_copy_prop, Mopti_do_dead_code, Mopti_init_performed, and Mopti_print_stats.
Referenced by Mopti_init().
void Mopti_init (Parm_Macro_List * command_line_macro_list)
Definition at line 115 of file m_opti.c.
References L_read_parm_mopti().
Referenced by Mopti_perform_optimizations().
void Mopti_perform_optimizations (L_Func * fn, Parm_Macro_List * command_line_macro_list)
Definition at line 124 of file m_opti.c.
References L_COMMON_SUB_MOVES_WITH_FLT_CONSTANT, L_COMMON_SUB_MOVES_WITH_INT_CONSTANT, L_COMMON_SUB_MOVES_WITH_LABEL_CONSTANT, L_COMMON_SUB_MOVES_WITH_STRING_CONSTANT, L_global_dead_code_removal(), L_local_common_subexpression(), L_local_copy_propagation(), L_local_dead_code_removal(), Mopti_do_common_subs, Mopti_do_copy_prop, Mopti_do_dead_code, Mopti_imax_num_iterations, Mopti_init(), Mopti_init_performed, Mopti_omax_num_iterations, and Mopti_print_stats.
Variable Documentation
int Mopti_debug_common_subs = 0
Definition at line 92 of file m_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_debug_copy_prop = 0
Definition at line 91 of file m_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_debug_dead_code = 0
Definition at line 93 of file m_opti.c.
Referenced by L_read_parm_mopti().
int Mopti_do_common_subs = 1
Definition at line 94 of file m_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations().
int Mopti_do_copy_prop = 1
Definition at line 95 of file m_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations().
int Mopti_do_dead_code = 1
Definition at line 96 of file m_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations().
int Mopti_imax_num_iterations = 10
Definition at line 83 of file m_opti.c.
Referenced by Mopti_perform_optimizations().
int Mopti_init_performed = 0
Definition at line 85 of file m_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations().
int Mopti_omax_num_iterations = 10
Definition at line 84 of file m_opti.c.
Referenced by Mopti_perform_optimizations().
int Mopti_print_stats = 0
Definition at line 90 of file m_opti.c.
Referenced by L_read_parm_mopti(), and Mopti_perform_optimizations().