#!/usr/local/bin/perl

###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
# Annotates source code with the attributes from the sorted
# .pc.pos file (should be in .sort file). Sends annotated
# source code to stdout.
#
# Usage:
#    annot_source filename > filename.c.annot
#
#    Expects filename.c and filename.sort to exist.
#

$ARGV = shift;
$source_file = $ARGV.".c";
$pcpos_file = $ARGV.".sort";
open(SOURCE_FILE,$source_file);
open(PCPOS_FILE,$pcpos_file);

$current_line = 0;

while (<PCPOS_FILE>) {
    @line = split(" ");

      while ($current_line != $line[0]) {
	if ($current_line != 0) {
	    print"\n";
	}
	$current_line++;
	$line2 = <SOURCE_FILE>;
	@source_line = split("\n",$line2);
	print "$source_line[0]";
      }

    print " /*## $line[1] $line[2]=";
    for ($i=0;$i<$line[3];$i++) {
	$_ = $line[$i+4];
	if ($line[$i+4] eq "NULL") {
	    print "()";
	}
	elsif (/\d*\.\d*/) {
	    print sprintf("(%.3f)",$line[$i+4]);
	}
	else {
	    print sprintf("(%d)",$line[$i+4]);
	}
    }
    if (defined($line[$i+4])) {
    	print sprintf(" \$%d\$",$line[$i+4]);
    }
    print " ##*/";
}
print "\n";
while (<SOURCE_FILE>) {
    print "$_";
}
