#!/usr/local/bin/perl

###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
# Sorts the miss counts (dmc attributes) in the given annotation file 
# and outputs to stdout an new annotation file with rankings attached
# to the dmc attributes.
#
# Usage:
#    annot_sort filename >! filename.annot
#
#    Expects filename.annot to exist.
#

$line_num = 0;

$ARGV = shift;
$source_file = $ARGV.".annot";
open(SOURCE_FILE,$source_file);
 
while (<SOURCE_FILE>) {
    $line_num++;
    @line1 = split("\n");
    @line = split(" ");
    if ($line[1] eq "dmc") {
	$dmc_vals{$line_num} = $line[4];
    }
}

$rank = 1;
foreach $line_num ( sort { $dmc_vals{$b} <=> $dmc_vals{$a} } keys %dmc_vals ) {
    $dmc_ranks{$line_num} = $rank++;
} 

close(SOURCE_FILE);
open(SOURCE_FILE,$source_file);

$line_num = 0;
while (<SOURCE_FILE>) {
    $line_num++;
    @line1 = split("\n");
    print "$line1[0]";
    @line = split(" ");
    if ($line[1] eq "dmc") {
	print " Rank $dmc_ranks{$line_num}";
    }
    print "\n";
}
