#!/bin/sh
###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#
#	Converts ascii lcode to binary lcode in place.
#
#	Run this script with no arguments for usage informantion
#
#	Script written by John Gyllenhaal, Wen-mei Hwu 4/96
#

VALID_ARCH=0;

if [ $# -gt 0 ]; then
  # Set architecture specific settings 
  ARCH="$1";
  shift;

  case $ARCH in 
    hppa)
      ARCH_PARMS="${IMPACT_REL_PATH}/parms/PROBE_HPPA";
      VALID_ARCH=1;;

    sparc)
      ARCH_PARMS="${IMPACT_REL_PATH}/parms/PROBE_SPARC";
      VALID_ARCH=1;;

    x86)
      ARCH_PARMS="${IMPACT_REL_PATH}/parms/PROBE_X86";
      VALID_ARCH=1;;

    *)
      echo " ";
      echo "ascii2binary error:"
      echo "   Invalid architecture '$ARCH'!"
      echo "   Expect either hppa, sparc, or x86!";
      echo " ";
      VALID_ARCH=0;;
  esac
fi

if [ $# -lt 1 -o $VALID_ARCH -eq 0 ]; then
	echo "Usage: ascii2binary arch file1 [file2 ...]";
	echo " "
	echo "       Converts the arch's ascii lcode to binary lcode in place,";
	echo "       where arch may be hppa, sparc, or x86.";
	echo " "
	exit 1;
fi 


# Convert each file specified
while [ $# -gt 0 ]
do
    # get the next file to be processed 
    FILE="$1";
    shift;

    # Do not process empty files
    if [ ! -s $FILE ]; then
        echo "> Skipping ${FILE}, empty file.";
        continue;
    fi

    # Only convert non-binary files 
    Lis_binary ${FILE}
    IS_BINARY="$?";
    if test $IS_BINARY = 0; then	
	echo "> Converting ${FILE} to binary lcode format"
    elif test $IS_BINARY = 1; then
	echo "> Skipping ${FILE}, already binary lcode.";
	continue;
    else
	echo "> Error processing ${FILE} error code '$IS_BINARY'.  Terminating!";

	# Remove the temp file
	/bin/rm -f ascii2binary.temp

	exit 1;
    fi

    # Convert to binary and write to temp file
    Lcode -p ${ARCH_PARMS} \
	  -Foutput_binary_format=yes -Fecho=yes \
	  -i ${FILE} -o ascii2binary.temp

    # Stop on errors before overwritting source!
    if test "$?" != 0; then 
	echo "Exiting: Error reading lcode file '${FILE}'"; 

	# Remove the temp file
	/bin/rm -f ascii2binary.temp

	exit 1;
    fi

    # Copy the temp file to the original file's name (to preserve permissions)
    cp ascii2binary.temp ${FILE}
    if test "$?" != 0; then 
	echo "Error:  Unable to copy ascii2binary.temp to '${FILE}'.  Terminating!"; 
	# Remove the temp file
	/bin/rm -f ascii2binary.temp

	exit 1;
    fi
	
done;

# Remove the temp file
/bin/rm -f ascii2binary.temp

echo "> Done"

