#!/bin/tcsh

foreach file (`find $IMPACT_REL_PATH -name doxygen_config.tag`)
  set dir = `dirname $file`
  echo "Building tag file in $dir"
  cd $dir && doxygen doxygen_config.tag
end

foreach file (`find $IMPACT_REL_PATH -name doxygen_config.doc`)
  set dir = `dirname $file`
  echo "Building documentation in $dir"
  cd $dir && doxygen doxygen_config.doc
end