#!/bin/sh

###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#	Copy files from one extension to another
#       Also create a new list containing the copy file names
#
#	Usage: copy_files "dir" "new_ext" "new_list" < "list"
#
#	Brian Deitrich

if [ $# -eq 3 ]; then
	PREFIX="$1";
	NEW_EXT="$2";
	NEW_LIST="$3";

else
	echo '> Usage copy_files "dir" "new_ext" "new_list" < "list"'
	echo '> "dir" is location of input files';
	echo '> "new_ext" is the new extension for the copied files';
	echo '> "new_list" is the name of the file used to contain the new list of files';
	echo '> "list" is list of Lcode file to process';
	exit 0200;
fi;

echo "> COPY FILES TO A NEW EXTENSION";
echo "> Prefixing files with ${PREFIX}/";
echo "> New extension is ${NEW_EXT}";
echo "> New list for the new extension files is ${NEW_LIST}";

rm -f ${NEW_LIST}

while read FILE;
do
	FILEOUT=`echo $FILE | \
	awk -F. '{if ($(NF) == "p") NF=NF-1; ORS="."; for (i=1; i<NF-1; i++) print $i; ORS=""; print $(NF-1)}'`

	echo "> Copying ${PREFIX}/${FILE} to ${PREFIX}/${FILEOUT}.${NEW_EXT}"
	cp ${PREFIX}/${FILE} ${PREFIX}/${FILEOUT}.${NEW_EXT}

	echo "${PREFIX}/${FILEOUT}.${NEW_EXT}" >> ${NEW_LIST}
done;

echo "> done";
