#!/bin/sh

###############################################################################
##
##                    Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:
##
##              IMPACT Research Group
##
##              University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################

#	Generate machine code for sparc 
#
#	Usage: gen_Lsparc "dir" "model" "phase" ["extra args"] < "list"
#	
#	Sabrina Y. Hwu
#	Probing extensions to script added by John C. Gyllenhaal 10/3/94

if [ $# -eq 3 ]; then
	PREFIX="$1";
	MODEL="$2";
	PHASE="$3";
	EXTRA_ARGS="";
elif [ $# -eq 4 ]; then
        PREFIX="$1";
        MODEL="$2";
        PHASE="$3";
        EXTRA_ARGS="$4";
else
        echo '> Usage gen_Lsparc "directory" "model" "phase" ["extra_args"] < "list"';
        echo '>';
        echo '> "directory" is location of input files';
        echo '> "model" is target sparc model (ie elc)';
	echo '> "phase" is the code generation phase (ie. 1,2,3,4,6,or 7(0) )';
	echo '>         May be prefixed with S, P, or A to insert probes for';
	echo '>         simulation, profiling, or address_trace (ie. S6)';
        echo '> "extra_args" are optional additional -P and -F arguments to pass';
        echo ">              Lsparc (Put quote around args, ie '-Fparm1=2 -Fparm2=3')";
        echo '> "list" is list of Lcode files to process';
        exit 0200;
fi;


# Detect prefix of S (simulation), P (profiling), C (cache simulation)
# to PHASE
PROBE_PREFIX=`echo $PHASE | awk '{print substr($1,1,1)}'`
PHASE_SUBSTR=`echo $PHASE | awk '{print substr($1,2)}'`

PROBE_PARM_FILE="-p ${IMPACT_REL_PATH}/parms/PROBE_SPARC"
PROBE_PARMS=""
PROBE_TYPE="none";

case "$PROBE_PREFIX" in
	S|s) 
	    PROBE_TYPE="simulation";;
	P|p) 
	    PROBE_TYPE="profiling";;
	A|a) 
	    PROBE_TYPE="address_trace";;
	*);;
esac

if [ "${PROBE_TYPE}" != "none" ]; then
	PHASE="$PHASE_SUBSTR";
	PROBE_PARMS="$PROBE_PARM_FILE -Pprobe_type=$PROBE_TYPE";
fi

if [ $PHASE -eq 0 ]; then
    echo "> Performing Lcode to Assembly Code Conversion";
    SUFFIX="s";
    PHASE="7";
elif [ $PHASE -eq 1 ]; then
    echo "> Performing Lcode to Mcode Conversion";
    SUFFIX="mc";
elif [ $PHASE -eq 2 ]; then
    echo "> Performing Mcode to Optimized Mcode Conversion";
    SUFFIX="mco";
elif [ $PHASE -eq 3 ]; then
    echo "> Performing Lcode to Optimized Mcode Conversion";
    SUFFIX="mco";
elif [ $PHASE -eq 4 ]; then
    echo "> Performing Optimized Mcode to Assembly Code Conversion";
    SUFFIX="s";
elif [ $PHASE -eq 6 ]; then
    echo "> Performing Mcode to Assembly Code Conversion";
    SUFFIX="s";
elif [ $PHASE -eq 7 ]; then
    echo "> Performing Lcode to Assembly Code Conversion";
    SUFFIX="s";
else
    echo "> Invalid Code Generation Phase: ( Try 1,2,3,4,6,or 7(0) )";
    exit 0200;
fi;

if [ "${PROBE_TYPE}" != "none" ]; then
echo "> Inserting probes for $PROBE_TYPE"
fi

echo "> Prefixing files with ${PREFIX}/";
echo "> Compiling for : arch = sparc / model = ${MODEL}";
echo "> Extra Lsparc arguments : ${EXTRA_ARGS}";

while read FILE;
do
	echo "> processing $PREFIX/$FILE"
#	FILEOUT=`echo $FILE | awk -F. '{print $1}'`
	FILEOUT=`echo $FILE | \
	awk -F. '{if ($(NF) == "p") NF=NF-1; ORS="."; for (i=1; i<NF-1; i++) print $i; ORS=""; print $(NF-1)}'`
	Lsparc \
		${PROBE_PARMS} \
		-Parch=sparc \
		-Pmodel=${MODEL} \
		-Pphase=${PHASE} \
		${EXTRA_ARGS} \
		-i ${PREFIX}/${FILE} \
		-o ${PREFIX}/${FILEOUT}.${SUFFIX}

	ERROR=$?;
	if [ $ERROR -ne 0 ]; then
	    echo "> Lsparc failed on input file: ${FILE}";
	    echo "> error_code= ${ERROR}";
	    exit 0200;
	fi;
done;

echo "> done";
