#!/bin/sh
###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#
#	Flatten Pcode files. To fix the inconsistency of function return types,
#	may need to run `gen_Psplit input_file "-Fsp_format=None"` in advance
#
#	Usage: gen_PtoP-flatten "dir" < "list"
#
#	Ben-Chung Cheng
#	Modified from Dan Lavery, Wen-mei Hwu

if [ $# -eq 1 ]; then
        PREFIX="$1";

else
	echo '> Usage: gen_PtoP-flatten "dir" < "list"';
        exit 0200;
fi;


echo "> Prefixing files with ${PREFIX}/";

while read FILE;
do
#	FILENAME=`echo $FILE | awk -F. '{print $1}'`
	FILENAME=`echo $FILE | \
	awk -F. '{if ($(NF) == "p") NF=NF-1; ORS="."; for (i=1; i<NF-1; i++) print $i; ORS=""; print $(NF-1)}'`

	echo "> processing $PREFIX/$FILE"
        Pflatten   -i ${PREFIX}/${FILE} \
                   -o ${PREFIX}/${FILENAME}.pcf

	ERROR=$?;

	if [ $ERROR -ne 0 ]; then
	    echo "> Pcode failed on input file: ${PREFIX}/${FILE}";
	    echo "> error_code= ${ERROR}";
	    exit 0200;
	fi;

done;

echo "> done";


