#!/bin/sh

###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#	Lcode inliner
#
#	Usage: gen_Linline "dir" "arch" "model" "list" ["extra_args"]
#
#	Brian Deitrich

if [ $# -eq 4 ]; then
	PREFIX="$1";
	ARCH="$2";
	MODEL="$3";
	LIST="$4";
	EXTRA_ARGS="";

elif [ $# -eq 5 ]; then
	PREFIX="$1";
	ARCH="$2";
	MODEL="$3";
	LIST="$4";
	EXTRA_ARGS="$5";

else
	echo '> Usage gen_Linline "dir" "arch" "model" "list" ["extra_args"]';
	echo '> "dir" is location of input files';
	echo '> "arch" is target processor architecture (ie HPPA)';
	echo '> "model" is target processor model (ie PA-7100)';
	echo '> "list" is list of Lcode file to process';
	echo '> "extra_args" are optional additional -P and -F arguments to pass';
	echo ">           Linline (Put quote around args, ie '-Fp1=2 -Fp2=3')";
	exit 0200;
fi;

echo "> Prefixing files with ${PREFIX}/";
echo "> Compiling for : arch = ${ARCH} / model = ${MODEL}";
echo "> Extra Linline arguments : ${EXTRA_ARGS}";
echo "> List of files : ${LIST}";
echo ">"

copy_files ${PREFIX} lci LINLINE-FILES~$$ < ${LIST}

echo "> Perform actual inlining"
Linline -Ffile_processing_model=filelist \
        -Ffilelist_file_name=LINLINE-FILES~$$ \
	-Parch=${ARCH} \
	-Pmodel=${MODEL} \
	${EXTRA_ARGS}
ERROR=$?;
if [ $ERROR -ne 0 ]; then
	echo "> Linline failed";
	echo "> error_code= ${ERROR}";
	exit $ERROR;
fi;

rm -f LINLINE-FILES~$$;

echo "> done";

