#!/bin/sh
###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#
# Run PtoC to generate a probed C program corresponding to the
# specified Pcode.
#
# Usage: gen_PtoC_probed "target directory"  [extra_args] < "list"
#
#       The IMPACT research group and Wen-mei Hwu

EXTRA_ARGS="";

if [ $# -gt 0 ]; then
   FILE="$1";
   if [ $# -gt 1 ]; then
       EXTRA_ARGS="$2";
   fi;
else
   echo '> Usage gen_PtoC_probed <a.out file> [extra_args]';
   echo '>';
   echo '> [extra_args] includes extra arguments if there is any';
   exit 0200;
fi;

echo "> gen_PtoC_probed runs:"
echo ">     PtoC - produces rev.c files with profiling probes" 
echo "> Prefixing output files with ${PREFIX}/";

echo "> removing impact_probe.status, impact_probe.tmp and *_rev.c"
rm -rf impact_probe.status impact_probe.tmp *_rev.c 

PtoC -i ${FILE} \
   -Finsert_probe=yes -Finsert_loop_probe=yes -Finsert_ipc_probe=yes \
   -Flog_file=stderr ${EXTRA_ARGS}

ERROR=$?;
if [ $ERROR -ne 0 ]; then
   echo "> Pcode failed on input file: ${FILENAME}.pc";
   echo "> error_code= ${ERROR}";
   exit 0200;
fi;

echo "> done";
