#!/bin/sh

###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
#    Convert Dosuper loops with software pipelining flag to Dosuper loops
#    without the flag and add a DOALL attribute.  These loops will later be
#    unrolled and scheduled with the knowledge that the array memory
#    accesses for each iteration are independent.
#
#	Usage: gen_Lmarkdoall directory < list
#
#    Generates .doall temporary files.  If there are no errors, the
#    input file is overwritten with the .doall file.
#
#    Daniel M. Lavery

if [ $# -eq 1 ]; then
	PREFIX="$1";
else
        echo '> Usage: gen_Lmarkdoall directory < list';
        echo '>';
        echo '>        "directory" is the location of the input Lcode files';
        echo '>        "list" is a list of Lcode files to process';
        exit 0200;
fi;

while read FILE;
do
#       FILEOUT=`echo $FILE | awk -F. '{print $1}'`
	FILEOUT=`echo $FILE | \
	awk -F. '{if ($(NF) == "p") NF=NF-1; ORS="."; for (i=1; i<NF-1; i++) print $i; ORS=""; print $(NF-1)}'`
	echo "> processing $PREFIX/$FILE; temp output to ${PREFIX}/${FILEOUT}.doall";
	Lmarkdoall \
		-i ${PREFIX}/${FILE} \
                -o ${PREFIX}/${FILEOUT}.doall;

	ERROR=$?;
	if [ $ERROR -ne 0 ]; then
	    echo "> Lmarkdoall failed on input file: ${FILE}";
	    echo "> error_code= ${ERROR}";
	    exit $ERROR;
	fi;

        mv ${PREFIX}/${FILEOUT}.doall ${PREFIX}/${FILE};
done;

echo "> done";
