#!/bin/sh
###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
##############################################################################
 #
 # Generates a .txt from a md binary file (.lmdes2, .layout_info, etc.)
 #
 # type script name without arguments to see usage.
 #
 # Written by John C. Gyllenhaal, Wen-mei Hwu 2/10/95
 #
##############################################################################

# Assume arguments valid
VALID_ARGS=1;

# get fixed arguments 
if [ $# -eq 1 ]; then
    MD_NAME="$1"

    # skip the 1 set arguments
    shift 1;
else
    VALID_ARGS=0;
fi

if [ $VALID_ARGS -eq 0 ]; then

    echo ' ';
    echo '> Usage: md2txt md_file';
    echo '> ';
    echo '> Generates a md_file.txt file, which is a user readable version';
    echo '> of the binary md file passed (.lmdes2, .layout_info, etc)';
    exit 0200;
fi

echo "> Translating $MD_NAME -> ${MD_NAME}.txt";
md_compiler $MD_NAME -o ${MD_NAME}.txt -read_lmdes -hmdes
if test "$?" != 0; then echo "Exiting: non-zero exit code"; exit 1;fi
echo "> Done"
