#!/bin/sh
###############################################################################
##
##		      Illinois Open Source License
##                     University of Illinois/NCSA
##                         Open Source License
##
## Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
## All rights reserved.
##
## Developed by:             
##
##		IMPACT Research Group
##
##		University of Illinois at Urbana-Champaign
##
##              http://www.crhc.uiuc.edu/IMPACT
##              http://www.gelato.org
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal with the Software without
## restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies
## of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## Redistributions of source code must retain the above copyright
## notice, this list of conditions and the following disclaimers.
##
## Redistributions in binary form must reproduce the above copyright
## notice, this list of conditions and the following disclaimers in
## the documentation and/or other materials provided with the
## distribution.
##
## Neither the names of the IMPACT Research Group, the University of
## Illinois, nor the names of its contributors may be used to endorse
## or promote products derived from this Software without specific
## prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
## WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
## LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
## PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
## OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
## OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
##
###############################################################################
###############################################################################
#
#       Test the bench_info for list of benchmarks with test_bench_info,
#       each benchmark in its own directory.
#
#       Run this script with no arguments for usage information.
#
#       Script created by John C. Gyllenhaal, Wen-mei Hwu 2/15/99
#

BENCH_SCRIPT="test_bench_info"

if [ $# -lt 1 ]; then
   echo "> Usage: test_list list [options]"
   echo ">"
   echo ">   For every 'BENCHMARK' in the 'list' file, makes a directory"
   echo ">   'BENCHMARK', and runs 'test_bench_info BENCHMARK options -copy_src'"
   echo ">   in it."
   exit 1;
fi

FILE_NAME="$1";
shift;
FILE_LIST=`cat $FILE_NAME`

echo " "
echo "> For every benchmark in '$FILE_NAME', will run:"
echo ">   ${BENCH_SCRIPT} (bench_name) $@ -copy_src"

for PROGRAM in $FILE_LIST
do

  echo " "
  DIR_TO="./${PROGRAM}";

  if [ -d $DIR_TO ]; then
    echo "> Removing exising '${DIR_TO}'"
    rm -rf ${DIR_TO};
  fi

  echo "> Creating '${DIR_TO}' and changing directories into it"
  mkdir ${DIR_TO};
  cd ${DIR_TO};

  echo " "
  echo "> Starting test of ${PROGRAM} with following command:"
  echo ">   ${BENCH_SCRIPT} ${PROGRAM} $@ -copy_src"

  $BENCH_SCRIPT $PROGRAM $@ -copy_src

  echo " "
  echo "> Finished with ${PROGRAM}, changing directories to '..'"
  cd ..;

done;

echo " "
echo "> Done, test_list has reached the end of '${FILE_NAME}'"
