md_compiler.c File Reference
#include <config.h>
#include `md_compiler.h`
Functions
void print_usage (char *fmt,...)
void read_command_line_parameters (int argc, char **arg_ptr)
int main (int argc, char **argv)
Fptr * create_Fptr (Mfile *mfile)
void free_Fptr (Fptr *fptr)
void Ferror (Fptr *fptr, char *fmt,...)
void vFerror (Fptr *fptr, char *fmt, va_list args)
int Fpeekc (Fptr *fptr)
int Fgetc (Fptr *fptr)
void Fget_line_directive (Fptr *fptr)
void Fadvance_to_next_token (Fptr *fptr)
int Fis_token_char (int ch)
int Fget_token (Fptr *fptr, Mbuf *mbuf)
int is_md_ident (char *ident)
MD * build_md (FILE *in, char *md_name)
void build_field_decl (MD *md, MD_Section *section, Fptr *fptr, Mbuf *mbuf)
int build_int (char *string, int *value)
int build_double (char *string, double *value)
void strip_first_and_last_char (char *string)
void strip_backslashes (char *string)
void build_element (MD_Field *field, MD_Element_Req *element_req, int element_index, Fptr *fptr, Mbuf *mbuf)
void build_entry (MD_Section *section, Fptr *fptr, Mbuf *mbuf)
int check_md_for_ambiguous_links (FILE *out, MD *md)
void L_punt (char *fmt,...)
Variables
Mbuf * input_buf = NULL
char * program_name = NULL
char * input_file_name = NULL
char * output_file_name = NULL
int using_stdin = 0
char * output_mode = NULL
char * input_mode = NULL
int output_page_width = 80
Function Documentation
int build_double (char * string, double * value)
Definition at line 1198 of file md_compiler.c.
Referenced by build_element().
void build_element (MD_Field * field, MD_Element_Req * element_req, int element_index, Fptr * fptr, Mbuf * mbuf)
Definition at line 1281 of file md_compiler.c.
References build_double(), build_int(), copy_Mbuf_buf(), MD_Field::decl, MD_Element_Req::desc, entry, MD_Field::entry, Ferror(), Fis_token_char(), L_punt(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_BLOCK, MD_DOUBLE, MD_find_entry, MD_INT, MD_LINK, MD_set_block, MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_STRING, MD_Section::name, MD_Entry::name, MD_Field_Decl::name, NULL, MD_Entry::section, strip_backslashes(), strip_first_and_last_char(), and MD_Element_Req::type.
Referenced by build_entry().
void build_entry (MD_Section * section, Fptr * fptr, Mbuf * mbuf)
Definition at line 1472 of file md_compiler.c.
References build_element(), CONCAT_FIELD, copy_Mbuf_buf(), MD_Field::decl, MD_Element_Req::desc, entry, ENTRY_END, ENTRY_START, Ferror(), Fget_token(), FIELD_END, FIELD_START, is_md_ident(), KLEENE_STAR, MD_Element_Req::kleene_starred, MD_Field_Decl::kleene_starred_req, match_Mbuf(), MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_field(), MD_find_entry, MD_find_field, MD_find_field_decl, MD_new_entry(), MD_new_field(), MD_Section::name, MD_Field_Decl::name, NULL, REPLACE_FIELD, MD_Field_Decl::require, SECTION_END, strip_backslashes(), strip_first_and_last_char(), and TERMINATOR.
Referenced by build_md().
void build_field_decl (MD * md, MD_Section * section, Fptr * fptr, Mbuf * mbuf)
Definition at line 940 of file md_compiler.c.
References copy_Mbuf_buf(), Ferror(), Fget_token(), FIELD_END, FIELD_START, is_md_ident(), KLEENE_STAR, LINK_END, LINK_START, match_Mbuf(), MD_Field_Decl::max_require_index, MD_find_field_decl, MD_find_section, MD_kleene_star_requirement(), MD_new_field_decl(), MD_OPTIONAL_FIELD, MD_require_block(), MD_require_double(), MD_require_int(), MD_require_multi_target_link(), MD_require_string(), MD_REQUIRED_FIELD, NULL, OR_MARKER, SECTION_START, and TERMINATOR.
Referenced by build_md().
int build_int (char * string, int * value)
Definition at line 1175 of file md_compiler.c.
Referenced by build_element().
MD* build_md (FILE * in, char * md_name)
Definition at line 789 of file md_compiler.c.
References build_entry(), build_field_decl(), check_md_for_ambiguous_links(), copy_Mbuf_buf(), create_Fptr(), create_Mbuf(), create_Mfile(), Ferror(), Fget_token(), free_Fptr(), free_Mbuf(), free_Mfile(), is_md_ident(), L_punt(), match_Mbuf(), MD_check_md(), MD_find_section, MD_new_md(), MD_new_section(), MD::name, NULL, SECTION_END, and SECTION_START.
Referenced by main().
int check_md_for_ambiguous_links (FILE * out, MD * md)
Definition at line 1735 of file md_compiler.c.
References MD_Field::element, entry, MD_Section::field_decl, MD_Field_Decl::kleene_starred_req, MD_Element::l, L_punt(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_find_entry, MD_first_entry(), MD_first_section(), MD_LINK, MD_next_entry(), MD_next_section(), MD_Entry::name, MD_Field_Decl::name, MD_Section::name, NULL, MD_Field_Decl::require, MD_Entry::section, MD_Element_Req::type, and MD_Element::value.
Referenced by build_md().
Fptr* create_Fptr (Mfile * mfile)
Definition at line 359 of file md_compiler.c.
References Fptr::checkpoint, copy_Mptr(), create_Mbuf(), create_Mptr(), L_punt(), Fptr::mptr, NULL, Fptr::source_line, and Fptr::source_name.
Referenced by build_md().
void Fadvance_to_next_token (Fptr * fptr)
Definition at line 598 of file md_compiler.c.
References Fptr::checkpoint, Fget_line_directive(), Fgetc(), Fpeekc(), move_Mptr(), Fptr::mptr, Mptr_pos(), and Fptr::source_line.
Referenced by Fget_token().
void Ferror (Fptr * fptr, char * fmt, ...)
Definition at line 391 of file md_compiler.c.
References vFerror().
Referenced by build_element(), build_entry(), build_field_decl(), build_md(), Fget_line_directive(), and Fget_token().
void Fget_line_directive (Fptr * fptr)
Definition at line 487 of file md_compiler.c.
References addc_to_Mbuf(), Fptr::checkpoint, clear_Mbuf(), Ferror(), Fgetc(), Fpeekc(), move_Mptr(), and Fptr::mptr.
Referenced by Fadvance_to_next_token().
int Fget_token (Fptr * fptr, Mbuf * mbuf)
Definition at line 656 of file md_compiler.c.
References addc_to_Mbuf(), clear_Mbuf(), Fadvance_to_next_token(), Ferror(), Fgetc(), Fis_token_char(), and Fpeekc().
Referenced by build_entry(), build_field_decl(), and build_md().
int Fgetc (Fptr * fptr)
Definition at line 478 of file md_compiler.c.
References Mgetc(), and Fptr::mptr.
Referenced by Fadvance_to_next_token(), Fget_line_directive(), and Fget_token().
int Fis_token_char (int ch)
Definition at line 629 of file md_compiler.c.
Referenced by build_element(), and Fget_token().
int Fpeekc (Fptr * fptr)
Definition at line 469 of file md_compiler.c.
References Mpeekc(), and Fptr::mptr.
Referenced by Fadvance_to_next_token(), Fget_line_directive(), and Fget_token().
void free_Fptr (Fptr * fptr)
Definition at line 373 of file md_compiler.c.
References Fptr::checkpoint, free_Mbuf(), free_Mptr(), Fptr::mptr, and Fptr::source_name.
Referenced by build_md().
int is_md_ident (char * ident)
Definition at line 771 of file md_compiler.c.
Referenced by build_entry(), build_field_decl(), and build_md().
void L_punt (char * fmt, ...)
Definition at line 1839 of file md_compiler.c.
Referenced by build_element(), build_md(), check_md_for_ambiguous_links(), create_Fptr(), and main().
int main (int argc, char ** argv)
Definition at line 260 of file md_compiler.c.
References build_md(), create_Mbuf(), free_Mbuf(), input_buf, input_file_name, input_mode, L_free_alloc_pool(), L_punt(), Mbuf_pool, MD_delete_md(), MD_print_md(), MD_print_md_declarations(), MD_print_md_template(), MD_read_md(), MD_write_md(), Mfile_pool, Mline_pool, Mptr_pool, NULL, output_file_name, output_mode, read_command_line_parameters(), and using_stdin.
void print_usage (char * fmt, ...)
Definition at line 89 of file md_compiler.c.
References NULL, and program_name.
Referenced by read_command_line_parameters().
void read_command_line_parameters (int argc, char ** arg_ptr)
Definition at line 129 of file md_compiler.c.
References bypass_alloc_routines, input_file_name, input_mode, NULL, output_file_name, output_mode, output_page_width, print_usage(), program_name, and using_stdin.
Referenced by main().
void strip_backslashes (char * string)
Definition at line 1247 of file md_compiler.c.
Referenced by build_element(), and build_entry().
void strip_first_and_last_char (char * string)
Definition at line 1221 of file md_compiler.c.
Referenced by build_element(), and build_entry().
void vFerror (Fptr * fptr, char * fmt, va_list args)
Definition at line 400 of file md_compiler.c.
References Mline::buf, Fptr::checkpoint, get_Mbuf_buf(), len_of_Mbuf(), Mline::line_no, Mptr::mfile, Mptr::mline, Mfile::name, NULL, Mptr::pos, print_buf_with_arrow(), Fptr::source_line, and Fptr::source_name.
Referenced by Ferror().
Variable Documentation
Mbuf* input_buf = NULL
Definition at line 75 of file md_compiler.c.
Referenced by main().
char* input_file_name = NULL
Definition at line 80 of file md_compiler.c.
Referenced by main(), and read_command_line_parameters().
char* input_mode = NULL
Definition at line 84 of file md_compiler.c.
Referenced by main(), and read_command_line_parameters().
char* output_file_name = NULL
Definition at line 81 of file md_compiler.c.
Referenced by main(), and read_command_line_parameters().
char* output_mode = NULL
Definition at line 83 of file md_compiler.c.
Referenced by main(), and read_command_line_parameters().
int output_page_width = 80
Definition at line 85 of file md_compiler.c.
Referenced by read_command_line_parameters().
char* program_name = NULL
Definition at line 77 of file md_compiler.c.
Referenced by print_usage(), and read_command_line_parameters().
int using_stdin = 0
Definition at line 82 of file md_compiler.c.
Referenced by main(), and read_command_line_parameters().