md_compiler.h File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <library/mbuf.h>
#include <library/mfile.h>
#include <library/md.h>
Data Structures
struct Fptr
Defines
#define MAXARGS 100
#define SECTION_START `{`
#define SECTION_END `}`
#define FIELD_START `(`
#define FIELD_END `)`
#define ENTRY_START `(`
#define ENTRY_END `)`
#define LINK_START `(`
#define LINK_END `)`
#define CREATE_SECTION `CREATE`
#define TERMINATOR `;`
#define KLEENE_STAR `*`
#define OR_MARKER `|`
#define REPLACE_FIELD `!`
#define CONCAT_FIELD `||`
Functions
int Fpeekc (Fptr *fptr)
int Fgetc (Fptr *fptr)
void Fadvance_to_next_token (Fptr *fptr)
int is_md_ident (char *ident)
void Ferror (Fptr *fptr, char *fmt,...)
void vFerror (Fptr *fptr, char *fmt, va_list args)
void L_punt (char *fmt,...)
MD * build_md (FILE *in, char *input_file_name)
int check_md_for_ambiguous_links (FILE *out, MD *md)
void build_field_decl (MD *md, MD_Section *section, Fptr *fptr, Mbuf *mbuf)
void build_entry (MD_Section *section, Fptr *fptr, Mbuf *mbuf)
void build_element (MD_Field *field, MD_Element_Req *element_req, int element_index, Fptr *fptr, Mbuf *mbuf)
Define Documentation
#define CONCAT_FIELD `||`
Definition at line 101 of file md_compiler.h.
Referenced by build_entry().
#define CREATE_SECTION `CREATE`
Definition at line 94 of file md_compiler.h.
#define ENTRY_END `)`
Definition at line 89 of file md_compiler.h.
Referenced by build_entry().
#define ENTRY_START `(`
Definition at line 88 of file md_compiler.h.
Referenced by build_entry().
#define FIELD_END `)`
Definition at line 86 of file md_compiler.h.
Referenced by build_entry(), and build_field_decl().
#define FIELD_START `(`
Definition at line 85 of file md_compiler.h.
Referenced by build_entry(), and build_field_decl().
#define KLEENE_STAR `*`
Definition at line 97 of file md_compiler.h.
Referenced by build_entry(), and build_field_decl().
#define LINK_END `)`
Definition at line 92 of file md_compiler.h.
Referenced by build_field_decl().
#define LINK_START `(`
Definition at line 91 of file md_compiler.h.
Referenced by build_field_decl().
#define MAXARGS 100
Definition at line 66 of file md_compiler.h.
#define OR_MARKER `|`
Definition at line 98 of file md_compiler.h.
Referenced by build_field_decl().
#define REPLACE_FIELD `!`
Definition at line 100 of file md_compiler.h.
Referenced by build_entry().
#define SECTION_END `}`
Definition at line 83 of file md_compiler.h.
Referenced by build_entry(), and build_md().
#define SECTION_START `{`
Definition at line 82 of file md_compiler.h.
Referenced by build_field_decl(), and build_md().
#define TERMINATOR `;`
Definition at line 96 of file md_compiler.h.
Referenced by build_entry(), and build_field_decl().
Function Documentation
void build_element (MD_Field * field, MD_Element_Req * element_req, int element_index, Fptr * fptr, Mbuf * mbuf)
Definition at line 1281 of file md_compiler.c.
References build_double(), build_int(), copy_Mbuf_buf(), MD_Field::decl, MD_Element_Req::desc, MD_Field::entry, entry, Ferror(), Fis_token_char(), L_punt(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_BLOCK, MD_DOUBLE, MD_find_entry, MD_INT, MD_LINK, MD_set_block, MD_set_double, MD_set_int, MD_set_link, MD_set_string, MD_STRING, MD_Field_Decl::name, MD_Entry::name, MD_Section::name, NULL, MD_Entry::section, strip_backslashes(), strip_first_and_last_char(), and MD_Element_Req::type.
Referenced by build_entry().
void build_entry (MD_Section * section, Fptr * fptr, Mbuf * mbuf)
Definition at line 1472 of file md_compiler.c.
References build_element(), CONCAT_FIELD, copy_Mbuf_buf(), MD_Field::decl, MD_Element_Req::desc, entry, ENTRY_END, ENTRY_START, Ferror(), Fget_token(), FIELD_END, FIELD_START, is_md_ident(), KLEENE_STAR, MD_Element_Req::kleene_starred, MD_Field_Decl::kleene_starred_req, match_Mbuf(), MD_Field::max_element_index, MD_Field_Decl::max_require_index, MD_delete_field(), MD_find_entry, MD_find_field, MD_find_field_decl, MD_new_entry(), MD_new_field(), MD_Field_Decl::name, MD_Section::name, NULL, REPLACE_FIELD, MD_Field_Decl::require, SECTION_END, strip_backslashes(), strip_first_and_last_char(), and TERMINATOR.
Referenced by build_md().
void build_field_decl (MD * md, MD_Section * section, Fptr * fptr, Mbuf * mbuf)
Definition at line 940 of file md_compiler.c.
References copy_Mbuf_buf(), Ferror(), Fget_token(), FIELD_END, FIELD_START, is_md_ident(), KLEENE_STAR, LINK_END, LINK_START, match_Mbuf(), MD_Field_Decl::max_require_index, MD_find_field_decl, MD_find_section, MD_kleene_star_requirement(), MD_new_field_decl(), MD_OPTIONAL_FIELD, MD_require_block(), MD_require_double(), MD_require_int(), MD_require_multi_target_link(), MD_require_string(), MD_REQUIRED_FIELD, NULL, OR_MARKER, SECTION_START, and TERMINATOR.
Referenced by build_md().
MD* build_md (FILE * in, char * input_file_name)
Definition at line 789 of file md_compiler.c.
References build_entry(), build_field_decl(), check_md_for_ambiguous_links(), copy_Mbuf_buf(), create_Fptr(), create_Mbuf(), create_Mfile(), Ferror(), Fget_token(), free_Fptr(), free_Mbuf(), free_Mfile(), is_md_ident(), L_punt(), match_Mbuf(), MD_check_md(), MD_find_section, MD_new_md(), MD_new_section(), MD::name, NULL, SECTION_END, and SECTION_START.
Referenced by main().
int check_md_for_ambiguous_links (FILE * out, MD * md)
Definition at line 1735 of file md_compiler.c.
References MD_Field::element, entry, MD_Section::field_decl, MD_Field_Decl::kleene_starred_req, MD_Element::l, L_punt(), MD_Element_Req::link, MD_Element_Req::link_array_size, MD_Field::max_element_index, MD_Section::max_field_index, MD_Field_Decl::max_require_index, MD_find_entry, MD_first_entry(), MD_first_section(), MD_LINK, MD_next_entry(), MD_next_section(), MD_Section::name, MD_Field_Decl::name, MD_Entry::name, NULL, MD_Field_Decl::require, MD_Entry::section, MD_Element_Req::type, and MD_Element::value.
Referenced by build_md().
void Fadvance_to_next_token (Fptr * fptr)
Definition at line 598 of file md_compiler.c.
References Fptr::checkpoint, Fget_line_directive(), Fgetc(), Fpeekc(), move_Mptr(), Fptr::mptr, Mptr_pos(), and Fptr::source_line.
Referenced by Fget_token().
void Ferror (Fptr * fptr, char * fmt, ...)
Definition at line 391 of file md_compiler.c.
References vFerror().
Referenced by build_element(), build_entry(), build_field_decl(), build_md(), Fget_line_directive(), and Fget_token().
int Fgetc (Fptr * fptr)
Definition at line 478 of file md_compiler.c.
References Mgetc(), and Fptr::mptr.
Referenced by Fadvance_to_next_token(), Fget_line_directive(), and Fget_token().
int Fpeekc (Fptr * fptr)
Definition at line 469 of file md_compiler.c.
References Mpeekc(), and Fptr::mptr.
Referenced by Fadvance_to_next_token(), Fget_line_directive(), and Fget_token().
int is_md_ident (char * ident)
Definition at line 771 of file md_compiler.c.
Referenced by build_entry(), build_field_decl(), and build_md().
void L_punt (char * fmt, ...)
Definition at line 1839 of file md_compiler.c.
Referenced by build_element(), build_md(), check_md_for_ambiguous_links(), create_Fptr(), and main().
void vFerror (Fptr * fptr, char * fmt, va_list args)
Definition at line 400 of file md_compiler.c.
References Mline::buf, Fptr::checkpoint, get_Mbuf_buf(), len_of_Mbuf(), Mline::line_no, Mptr::mfile, Mptr::mline, Mfile::name, NULL, Mptr::pos, print_buf_with_arrow(), Fptr::source_line, and Fptr::source_name.
Referenced by Ferror().