/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /n/lloth/y/repository/openimpact/src/Pcode/Pcode/lex.c,v 1.1.1.1 2005/04/18 17:40:17 mchu Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
static yyconst short int yy_accept[195] =
    {   0,
        0,    0,    0,    0,    0,    0,   45,   43,   12,   13,
       11,   23,   43,   25,   16,   26,   28,   43,   30,   31,
       29,   43,   16,   16,   15,   37,   42,   38,   40,   39,
       36,   24,   32,   43,   33,   27,   16,   34,   35,   41,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   43,    8,   11,    0,   21,    0,    0,
       16,    0,    0,    0,   15,    0,   16,   10,   17,    0,
       14,   16,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    7,    5,    6,    4,    1,    1,    1,    1,    1,
        1,    1,    8,    0,    0,    0,    0,   22,    0,   22,
        0,    0,    0,   19,    0,   16,   17,    0,    0,   18,
       16,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   20,
        0,   16,   16,    0,   17,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    0,    0,    0,    9,    0,   19,    1,    1,    1,
        1,    1,    1,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,    1,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   30,   29,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,   34,   35,   36,   31,    1,   37,   38,   39,   39,

       40,   41,   31,   31,   42,   31,   31,   43,   31,   44,
       31,   31,   31,   45,   31,   46,   31,   47,   31,   32,
       31,   31,   48,    1,   49,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    4,    1,    1,
        5,    1,    1,    6,    1,    4,    4,    4,    7,    7,
        7,    4,    1,    1,    1,    1,    1,    1,    7,    7,
        4,    4,    1,    1,    1,    1,    7,    7,    7,    7,
        7,    4,    4,    4,    4,    4,    4,    1,    1,    1
    } ;

static yyconst short int yy_base[207] =
    {   0,
        0,    0,   50,    0,   86,   93,  400,  709,  709,  709,
      395,  709,   97,  338,    0,  709,  709,  336,  709,  709,
      709,   98,  101,  349,  106,  709,  709,  709,  709,  709,
      709,  709,  709,  359,  709,  709,  316,  709,  709,  709,
        0,  709,  709,  355,    0,  127,  312,  154,    0,    0,
      114,    0,    0,  132,  135,  118,  336,  148,    0,    0,
        0,    0,    0,    0,    0,    0,  344,    0,    0,  302,
        0,    0,    0,  185,  190,  319,   98,  709,  228,  277,
        0,  302,  197,  123,  202,  267,  224,  709,  231,  261,
      709,  267,    0,  301,  145,    0,  280,  256,    0,  279,

      290,  709,  709,  709,  709,  161,  276,  240,  238,  309,
      316,  238,  321,  206,  314,    0,  226,  709,  256,  252,
      283,  138,  242,  324,  208,  337,  346,  353,  194,  358,
        0,  369,  378,  394,  202,    0,  230,  213,  374,  371,
      425,  388,  162,  401,  418,  452,  406,  421,    0,  441,
      470,  450,  493,  149,  376,  176,  391,  155,  462,  709,
      430,   95,  148,  466,  473,  522,  555,  533,  578,  120,
      477,  142,  506,  601,  500,    0,  482,  524,  529,  539,
      543,    0,  184,  222,  709,  134,  551,    0,  576,  577,
        0,  119,  567,  709,  642,  646,  653,  660,  667,  674,

      681,  688,  695,  117,  698,  701
    } ;

static yyconst short int yy_def[207] =
    {   0,
      194,    1,  194,    3,    1,    1,  194,  194,  194,  194,
      194,  194,  195,  194,  196,  194,  194,  197,  194,  194,
      194,  194,  196,  196,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  196,  194,  194,  194,
      198,  194,  194,  198,  198,  199,  198,  198,  198,  198,
      200,  198,  198,  201,  198,   48,   48,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,   48,
      198,  198,  198,  194,  194,  194,  195,  194,  194,  194,
      196,  194,  202,  194,  194,  194,  196,  194,  194,  194,
      194,  196,  198,  198,  199,  198,  198,  198,   48,  198,

      203,  194,  194,  194,  194,  198,  198,  198,   48,  198,
      198,   48,  194,  195,  195,  204,  194,  194,  194,  194,
      194,  194,  205,  194,  194,  196,  194,  194,  194,  194,
      196,  199,  199,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,   48,  198,  198,  198,  198,   48,  195,
      195,  195,  151,  194,  194,  205,  194,  206,  194,  194,
      194,  126,  126,  194,  194,  199,  199,  199,  167,  198,
      198,  141,  198,  141,  198,  198,  198,   48,   48,  198,
      198,  153,  195,  195,  194,  194,  194,  169,  199,  199,
      198,  198,  198,    0,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194
    } ;

static yyconst short int yy_nxt[760] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   22,   23,   24,   25,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   15,   15,
       15,   15,   33,   34,   35,   36,   15,   15,   15,   15,
       15,   37,   15,   15,   15,   15,   15,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   55,   56,   57,   58,   58,
       58,   59,   60,   61,   62,   63,   64,   65,   48,   48,
       48,   48,   66,   67,   68,   69,   48,   48,   48,   48,
       48,   70,   48,   48,   48,   48,   48,   71,   72,   73,

       74,   74,   78,   78,   75,   75,   75,   74,   74,  194,
       81,   75,   75,   75,   84,   82,   85,   85,   85,   87,
       87,   87,   89,  153,   85,   85,   85,   82,   77,  136,
       79,   79,   96,  103,  104,   90,  109,  109,  109,   86,
       77,  124,  124,  124,  118,   90,   77,  101,  118,  105,
       96,  106,   93,  107,  107,  107,  157,  157,   77,  191,
       97,   99,  194,   81,  110,  118,  107,  107,  107,   99,
       99,   99,   99,   99,   99,   99,  108,  111,   97,  142,
      142,  142,   99,   99,   99,   99,  194,  111,  185,   78,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   84,  176,  113,  113,  113,   89,  120,  113,  113,
      113,   78,  130,  130,  130,  121,  122,   79,   89,   90,
       85,   85,   85,  136,  150,  150,   86,   78,  123,   90,
       77,   90,   77,   77,   77,   77,   77,  151,   77,   79,
      136,   90,   87,   87,   87,  170,  114,  115,  160,  127,
      127,  127,  118,  126,   77,   79,  109,  109,  109,  116,
      128,   77,  118,  126,   77,   77,  118,  144,   77,  154,
      128,   77,   77,   77,   77,  129,  129,  144,  149,  130,
      130,  130,   77,  143,   95,   95,   95,   95,   95,  136,
       95,  119,  110,  118,  107,  107,  107,  135,  132,  133,

      138,  155,  155,  119,   94,  111,   95,  131,  139,  140,
      125,  134,  118,   95,  156,  111,   95,   95,  117,   78,
       95,  141,   76,   95,   95,   95,   95,  145,  145,  145,
      147,  147,  152,  152,  148,  148,  148,   89,  146,  113,
      113,  113,  124,  124,  124,  112,   91,   79,  146,   88,
       90,  161,  162,  159,   98,  163,  163,  163,   94,   92,
       90,   91,   88,  159,  127,  127,  127,  164,  164,   83,
       77,  165,  165,  165,   96,  128,  130,  130,  130,   77,
       80,  136,   77,   96,  136,  128,  118,  166,  166,  173,
      173,   77,  171,  171,  157,  157,  168,  168,   76,  194,

      167,  118,   97,  194,  194,  172,  142,  142,  142,  119,
      119,   97,  169,  169,  169,  177,  178,  175,  194,  179,
      179,  179,  169,  169,  148,  148,  148,  175,  194,  194,
      169,  169,  169,  169,  169,  136,  145,  145,  145,  148,
      148,  148,  194,  174,  174,  174,   78,  146,  187,  187,
      187,  194,  194,  174,  174,   78,  194,  146,  194,  152,
      152,  174,  174,  174,  174,  174,  180,  180,  183,  183,
      181,  181,  181,  194,   79,   78,  161,  161,  194,  194,
      187,  187,  187,   79,  165,  165,  165,  136,  182,  182,
      182,  165,  165,  165,  194,  173,  173,  194,  182,  182,

      193,  193,  193,   79,  194,  194,  182,  182,  182,  182,
      182,  184,  184,  184,  177,  177,  136,  194,  193,  193,
      193,  184,  184,   77,  137,  137,  194,   96,  194,  184,
      184,  184,  184,  184,   77,   77,  194,  194,   96,  194,
      168,  168,  179,  179,  179,  194,   77,  179,  179,  179,
      194,  189,  189,  194,  194,   97,   77,  181,  181,  181,
       96,  181,  181,  181,  194,  194,   97,  194,   77,  187,
      187,  187,  194,  188,  188,  188,  194,   77,   77,  194,
      194,   96,   96,  188,  188,  193,  193,  193,   97,   77,
       77,  188,  188,  188,  188,  188,  190,  190,  190,  194,

      194,  194,  194,  194,  194,  194,  190,  190,  194,   97,
       97,  194,  194,  194,  190,  190,  190,  190,  190,  192,
      192,  192,  194,  194,  194,  194,  194,  194,  194,  192,
      192,  194,  194,  194,  194,  194,  194,  192,  192,  192,
      192,  192,   77,   77,  194,   77,   77,   77,   77,   81,
      194,  194,   81,   82,   82,  194,   82,   82,   82,   82,
       93,  194,  194,   93,   93,  194,   93,   95,   95,  194,
       95,   95,   95,   95,  100,  100,  194,  100,  100,  100,
      100,  102,  102,  102,  102,  102,  194,  102,  119,  119,
      194,  119,  119,  119,  119,  137,  137,  194,  137,  137,

      137,  137,  158,  194,  158,  186,  194,  186,    7,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194
    } ;

static yyconst short int yy_chk[760] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        5,    5,   13,   77,    5,    5,    5,    6,    6,  162,
      162,    6,    6,    6,   22,   51,   22,   22,   22,   23,
       23,   23,   25,  204,   25,   25,   25,   51,   46,  192,
       13,   77,   46,   54,   54,   25,   56,   56,   56,   22,
       46,   84,   84,   84,  186,   25,   95,   51,  122,   54,
       95,   55,  172,   55,   55,   55,  122,  122,   95,  170,
       46,   48,  163,  163,   58,  158,   58,   58,   58,   48,
       48,   48,   48,   48,   48,   48,   55,   58,   95,  106,
      106,  106,   48,   48,   48,   48,  156,   58,  154,  183,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   74,  143,   74,   74,   74,   75,   83,   75,   75,
       75,  114,  129,  129,  129,   83,   83,  183,   85,   75,
       85,   85,   85,  138,  114,  114,   74,  184,   83,   75,
       79,   85,   79,   79,   79,   79,   79,  114,   79,  114,
      137,   85,   87,   87,   87,  135,   79,   79,  125,   89,
       89,   89,  123,   87,   79,  184,  109,  109,  109,   79,
       89,   79,  120,   87,   79,   79,  119,  109,   79,  117,
       89,   79,   79,   79,   79,   90,   90,  109,  112,   90,
       90,   90,   97,  108,   97,   97,   97,   97,   97,  100,
       97,  101,  107,  121,  107,  107,  107,   98,   97,   97,

      101,  121,  121,  101,   94,  107,   97,   92,  101,  101,
       86,   97,   82,   97,  121,  107,   97,   97,   80,  115,
       97,  101,   76,   97,   97,   97,   97,  110,  110,  110,
      111,  111,  115,  115,  111,  111,  111,  113,  110,  113,
      113,  113,  124,  124,  124,   70,   67,  115,  110,   57,
      113,  126,  126,  124,   47,  126,  126,  126,   44,   37,
      113,   34,   24,  124,  127,  127,  127,  128,  128,   18,
      132,  128,  128,  128,  132,  127,  130,  130,  130,  133,
       14,  140,  132,  133,  139,  127,  155,  132,  132,  140,
      140,  133,  139,  139,  155,  155,  133,  133,   11,    7,

      132,  157,  132,    0,    0,  139,  142,  142,  142,  157,
      157,  133,  134,  134,  134,  144,  144,  142,    0,  144,
      144,  144,  134,  134,  147,  147,  147,  142,    0,    0,
      134,  134,  134,  134,  134,  141,  145,  145,  145,  148,
      148,  148,    0,  141,  141,  141,  150,  145,  161,  161,
      161,    0,    0,  141,  141,  152,    0,  145,    0,  150,
      150,  141,  141,  141,  141,  141,  146,  146,  152,  152,
      146,  146,  146,    0,  150,  151,  159,  159,    0,    0,
      159,  159,  159,  152,  164,  164,  164,  171,  151,  151,
      151,  165,  165,  165,    0,  171,  171,    0,  151,  151,

      177,  177,  177,  151,    0,    0,  151,  151,  151,  151,
      151,  153,  153,  153,  175,  175,  173,    0,  175,  175,
      175,  153,  153,  166,  173,  173,    0,  166,    0,  153,
      153,  153,  153,  153,  168,  166,    0,    0,  168,    0,
      166,  166,  178,  178,  178,    0,  168,  179,  179,  179,
        0,  168,  168,    0,    0,  166,  167,  180,  180,  180,
      167,  181,  181,  181,    0,    0,  168,    0,  167,  187,
      187,  187,    0,  167,  167,  167,    0,  189,  190,    0,
        0,  189,  190,  167,  167,  193,  193,  193,  167,  189,
      190,  167,  167,  167,  167,  167,  169,  169,  169,    0,

        0,    0,    0,    0,    0,    0,  169,  169,    0,  189,
      190,    0,    0,    0,  169,  169,  169,  169,  169,  174,
      174,  174,    0,    0,    0,    0,    0,    0,    0,  174,
      174,    0,    0,    0,    0,    0,    0,  174,  174,  174,
      174,  174,  195,  195,    0,  195,  195,  195,  195,  196,
        0,    0,  196,  197,  197,    0,  197,  197,  197,  197,
      198,    0,    0,  198,  198,    0,  198,  199,  199,    0,
      199,  199,  199,  199,  200,  200,    0,  200,  200,  200,
      200,  201,  201,  201,  201,  201,    0,  201,  202,  202,
        0,  202,  202,  202,  202,  203,  203,    0,  203,  203,

      203,  203,  205,    0,  205,  206,    0,  206,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../impact/src/Pcode/Pcode/lex.l"
#define INITIAL 0
#line 2 "../impact/src/Pcode/Pcode/lex.l"

/*****************************************************************************\
 *
 *		      Illinois Open Source License
 *                     University of Illinois/NCSA
 *                         Open Source License
 *
 * Copyright (c) 2004, The University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Developed by:             
 *
 *		IMPACT Research Group
 *
 *		University of Illinois at Urbana-Champaign
 *
 *              http://www.crhc.uiuc.edu/IMPACT
 *              http://www.gelato.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal with the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimers.
 *
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimers in
 * the documentation and/or other materials provided with the
 * distribution.
 *
 * Neither the names of the IMPACT Research Group, the University of
 * Illinois, nor the names of its contributors may be used to endorse
 * or promote products derived from this Software without specific
 * prior written permission.  THE SOFTWARE IS PROVIDED "AS IS",
 * WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
 * OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 *
\*****************************************************************************/
/*****************************************************************************\
 *	File:	lex.l
 *	Author:	Pohua Chang
 * 	Copyright (c) 1991 Pohua Chang. All rights reserved.  
 * 	All rights granted to the University of Illinois.
 *	The University of Illinois software License Agreement
 * 	specifies the terms and conditions for redistribution.
\*****************************************************************************/

#ifndef lint
#define lint
static char copyright[] =
"@(#) Copyright (c) 1991 Pohua Chang.\n All rights reserved.\n";
#endif

/*---------------------------------------------------------------------------
 *--------------------------------------------------------------------------*/
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <malloc.h>
#include <string.h>
#include <Pcode/pcode.h>
#include <Pcode/lex.h>
#include <Pcode/parse_prefix.h>
#include "parse.h"

#undef YYLMAX
/* BCC - extended YYLMAX from 2048 to 2500 for EDG/132.ijpeg - 6/27/96*/
#define YYLMAX 2500 

int last_line = 1;
int last_column = 0;

int lexIntLit (void);
int lexLongLit (void);
int lexRealLit (void);
int lexStringLit (void);
int lexCharLit (void);
int lexIdentifier (void);
void lexError (char *);
int yywrap (void);


int	TokenType;		/* token type */
char	*TokenName;		/* token string */
int	TokenInteger;		/* scalar value */
double	TokenReal;		/* floating point value */
int 	lex_error = 0;		/* number of lexical errors encountered */

#define ToState(n) BEGIN(n)	/* change lex state */
#define DefaultState 0		/* default lex state */

/* BCC - make '-' as a legal char for id names - 2/3/96 */
#define COMMENT 1
#define LINENO 2

#line 703 "src/Pcode/Pcode/lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 116 "../impact/src/Pcode/Pcode/lex.l"


#line 857 "src/Pcode/Pcode/lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 195 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 709 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 120 "../impact/src/Pcode/Pcode/lex.l"
{ last_line++; last_column = 0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 121 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; ToState (DefaultState); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 122 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "../impact/src/Pcode/Pcode/lex.l"
{ last_line++; last_column = 0; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 124 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 125 "../impact/src/Pcode/Pcode/lex.l"
{ last_line = atoi (yytext); last_column = 0;
                          ToState (DefaultState); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "../impact/src/Pcode/Pcode/lex.l"
{ ToState (LINENO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; ToState (COMMENT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 131 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 132 "../impact/src/Pcode/Pcode/lex.l"
{ last_line++; last_column = 0; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "../impact/src/Pcode/Pcode/lex.l"
{ last_line++; last_column = 0; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 135 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexLongLit ()); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; 
                          /* Special case: "inf" is a floating point
			   * literal, not an identifier. */
                          if (strcmp (yytext, "inf") == 0)
			    return (lexRealLit ());
			  else
			    return (lexIdentifier ());
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexRealLit ()); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexRealLit ()); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexRealLit ()); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 147 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexRealLit ()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexStringLit ()); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 149 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (lexCharLit ()); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 151 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 153 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 155 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 156 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 157 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 158 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 159 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 160 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 161 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 162 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 163 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 166 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 168 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 169 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 170 "../impact/src/Pcode/Pcode/lex.l"
{ last_column += yyleng; return (yytext[0]); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "../impact/src/Pcode/Pcode/lex.l"
{ lexError (yytext); 
			  return (ERROR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "../impact/src/Pcode/Pcode/lex.l"
ECHO;
	YY_BREAK
#line 1169 "src/Pcode/Pcode/lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(LINENO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 195 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 195 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 194);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 175 "../impact/src/Pcode/Pcode/lex.l"


/*----------------------------------------------------------------*/
#define MAX_LEVEL	20
#if 0
static int stack_top = 0;
static FILE *stack[MAX_LEVEL];
static char *fname[MAX_LEVEL];
#endif
static char *current_file = "??";

/* Lexical Error */
void
lexError (char *message)
{
  lex_error++;
  fprintf (stderr, "lexical error : %s (in %s)\n", message, current_file);
  exit (-1);
}

#if 0
static void
Push (FILE *fpt, char *name)
{
  stack[stack_top] = fpt;
  fname[stack_top] = name;
  stack_top += 1;
  if (stack_top >= MAX_LEVEL) 
    lexError ("too many levels of file inclusion");
}

static FILE *
Pop (void)
{
  if (stack_top <= 0)
    return (stdin);	/* default */
  stack_top -= 1;
  return (stack[stack_top]);
}

static char *
LastFile (void)
{
  if (stack_top <= 0)
    return ("??");	/* default */
  return (fname[stack_top-1]);
}
#endif

/* 1 for no wrap.  We won't set up a second source file to lex after the
 * current one. */
int
yywrap (void)
{
  return (1);
}	

#if 0
/* BCC - Test if the file exists - 7/14/97 */
int
lexExist (char *file_name, int inclusion)
{
  FILE *fpt;
  char *last_file;

  last_file = current_file;
  /*
   *      If the current_file is specified from the
   *      root directory, do nothing.
   *      Otherwise, add the prefix of the last file
   *      to the front of the file_name.
   */
  if (inclusion && (file_name[0] != '/'))
    {
      int len, j, i;
      char temp1[1024];
      len = strlen (last_file);
      /* find the prefix: /x/y/z -> /x/y */
      for (i = len-1; i >= 0; i--)
	if (last_file[i] == '/')
	  break;
      for (j = 0; j <= i; j++)
	temp1[j] = last_file[j];
      for (i = 0; i <= strlen (file_name); i++)
	temp1[i+j] = file_name[i];
      file_name = FindString (temp1);
    }

  if (!strcmp (file_name, "stdin"))
    {
      return (1);
    }
  else
    {                        /* open new file */
      fpt = fopen (file_name, "r");
      if (fpt==NULL)
	{
	  return (0);
	}
      return (1);
    }
}
#endif

int
lexSetInput (FILE *in)
{
  if (in != yyin)
    yyrestart (in);

  return (1);
}

/* Assumes the given file handle has just been adjusted with seek.  Calls
 * yyrestart if the file is the same as yyin. */
int
lexNotifySeek (FILE *in)
{
  if (in == yyin)
    yyrestart (in);

  return (1);
}

int
lexFinish (void)
{
  YY_FLUSH_BUFFER;

#if 0
  yy_delete_buffer (YY_CURRENT_BUFFER);
#endif

  return (1);
}

/* Set Up The Input File */
int
lexOpen (char *file_name)
{
  FILE *fpt;

#if 0
  Push (yyin, current_file);	/** save the previous fpt **/
  last_file = current_file;

  /*
   *	If the current_file is specified from the
   *	root directory, do nothing.
   *	Otherwise, add the prefix of the last file
   *	to the front of the file_name.
   */
  if (inclusion && (file_name[0] != '/'))
    {
      int len, j, i;
      char temp1[1024];

      len = strlen (last_file);
      /* find the prefix: /x/y/z -> /x/y */
      for (i = len-1; i >= 0; i--)
	if (last_file[i] == '/')
	  break;
      for (j = 0; j <= i; j++)
	temp1[j] = last_file[j];
      for (i = 0; i <= strlen (file_name); i++)
	temp1[i+j] = file_name[i];
      file_name = FindString (temp1);
    }
  current_file = file_name;	/** we have a new file **/
#endif

  if (!strcmp (file_name, "stdin"))
    {
      yyin = stdin;			
      return (1);
    }
  else
    {			/* open new file */
      fpt = fopen (file_name, "r");
      if (fpt == NULL)
	{
	  fprintf (stderr, "> %s\n", file_name);
	  lexError ("can not open file");
	  return (0);
	}
      yyin = fpt;
      return (1);
    }
}

/* Close an Input File */
int
lexClose (char *file_name)
{
  if (strcmp (file_name, "stdin"))
    fclose (yyin);

#if 0
  current_file = LastFile ();
  yyin = Pop ();
#endif
  return (1);
}

FILE *
SwitchFile (FILE *fpt)
{
  FILE *old_yyin;
  old_yyin = yyin;
  if (fpt != NULL)
    {
      yyin = fpt;
      return (old_yyin);
    }
  lexError ("cannot switch yyin to NULL");
  return (0);
}

/*----------------------------------------------------------------*/
/* Process an integer Literal */
#ifdef __linux__
/* ADA: 7/9/96: Linux libc atoi() will return MAX_LONG if input string is too
        large.  This is disastrous when reading a huge number still in unsigned
        long range.  Use the following routine instead.  Different name is used
        to avoid conflict with linux header files */
int
atoi_linux (char *s)
{
  /* 
   * atoi() exsits to allow overflow int in s
   */
  char *p = s;
  int neg, ret;
  
  if ((p = s) == NULL)
    return 0;
  
  while (isspace (*p))
    p++;
  
  if (*p == '-')
    {
      p++;
      neg = 1;
    }
  else if (*p == '+')
    {
      p++;
      neg = 0;
    }
  else
    neg = 0;

  for (ret = 0; *p; p++) 
    if (isdigit (*p))
      {
	ret *= 10;
	ret += *p - '0';
      }
    else
      break;
  
  return ((neg) ? -ret : ret);  
}
#endif

int
lexIntLit ()
{
#ifdef __linux__
  yylval.i_val = atoi_linux (yytext);  /* See above note */
#else
  yylval.i_val = atoi (yytext);
#endif
  return(I_LIT);
}

int
lexLongLit ()
{
  yylval.i_val = atol (yytext);
  return (I_LIT);
}

/* Process a Real Literal */
int
lexRealLit (void)
{
  yylval.f_val = atof (yytext);
  return (F_LIT);
}

/* Process a String Literal */
int
lexStringLit ()
{
  yylval.st_val = strdup (yytext);
  return (ST_LIT);
}

/* Process a Character Literal */
int
lexCharLit ()
{
  yylval.c_val = yytext[0];
  return (C_LIT);
}

/* Process an Identifier/Typeid/Keyword */
int
lexIdentifier ()
{
  /* Rather than a huge list of strcmps, use switch statements to narrow
   * identifier down to a couple choices.  This block switches on each
   * character of a keyword until we have three or fewer choices. */
#if 0
  yylval.st_val = strdup (yytext);
#endif

  switch (yytext[0])
    {
    case 'A':
      switch (yytext[1])
	{
	case 'D':
	  if (strcmp (yytext, "ADD") == 0)
	    return (ADD);
	  else if (strcmp (yytext, "ADDR") == 0)
	    return (ADDR);
	  else if (strcmp (yytext, "ADVANCE") == 0)
	    return (ADVANCE);
	  break;
	case 'L':
	  if (strcmp (yytext, "ALIGNMENT") == 0)
	    return (ALIGNMENT);
	  break;
	case 'N':
	  if (strcmp (yytext, "AND") == 0)
	    return (AND);
	  break;
	case 'R':
	  if (strcmp (yytext, "ARRAY") == 0)
	    return (ARRAY);
	  else if (strcmp (yytext, "ARROW") == 0)
	    return (ARROW);
	  break;
	case 'S':
	  if (strcmp (yytext, "ASM") == 0)
	    return (ASM);
	  else if (strcmp (yytext, "ASMOPRD") == 0)
	    return (ASMOPRD);
	  else if (strcmp (yytext, "ASSIGN") == 0)
	    return (ASSIGN);
	  break;
	case 'U':
	  if (strcmp (yytext, "AUTO") == 0)
	    return (AUTO);
	  break;
	case 'W':
	  if (strcmp (yytext, "AWAIT") == 0)
	    return (AWAIT);
	  break;
	case '_':
	  switch (yytext[2])
	    {
	    case 'A':
	      if (strcmp (yytext, "A_ADD") == 0)
		return (A_ADD);
	      else if (strcmp (yytext, "A_AND") == 0)
		return (A_AND);
	      break;
	    case 'D':
	      if (strcmp (yytext, "A_DIV") == 0)
		return (A_DIV);
	      break;
	    case 'L':
	      if (strcmp (yytext, "A_LSHFT") == 0)
		return (A_LSHFT);
	      break;
	    case 'M':
	      if (strcmp (yytext, "A_MOD") == 0)
		return (A_MOD);
	      else if (strcmp (yytext, "A_MUL") == 0)
		return (A_MUL);
	      break;
	    case 'O':
	      if (strcmp (yytext, "A_OR") == 0)
		return (A_OR);
	      break;
	    case 'R':
	      if (strcmp (yytext, "A_RSHFT") == 0)
		return (A_RSHFT);
	      break;
	    case 'S':
	      if (strcmp (yytext, "A_SUB") == 0)
		return (A_SUB);
	      break;
	    case 'X':
	      if (strcmp (yytext, "A_XOR") == 0)
		return (A_XOR);
	      break;
	    }
	  break;
	}
      break;
    case 'B':
      switch (yytext[1])
	{
	case 'I':
	  if (strcmp (yytext, "BITFIELD") == 0)
	    return (BITFIELD);
	  break;
	case 'L':
	  if (strcmp (yytext, "BLOCK") == 0)
	    return (BLOCK);
	  break;
	case 'R':
	  if (strcmp (yytext, "BREAK") == 0)
	    return (BREAK);
	  break;
	}
      break;
    case 'C':
      switch (yytext[1])
	{
	case 'A':
	  if (strcmp (yytext, "CALL") == 0)
	    return (CALL);
	  else if (strcmp (yytext, "CASE") == 0)
	    return (CASE);
	  else if (strcmp (yytext, "CAST") == 0)
	    return (CAST);
	  break;
	case 'D':
	  if (strcmp (yytext, "CDECL") == 0)
	    return (CDECL);
	  break;
	case 'H':
	  if (strcmp (yytext, "CHAR") == 0)
	    return (CHAR);
	  break;
	case 'L':
	  if (strcmp (yytext, "CLOBBERS") == 0)
	    return (CLOBBERS);
	  break;
	case 'O':
	  switch (yytext[2])
	    {
	    case 'B':
	      if (strcmp (yytext, "COBEGIN") == 0)
		return (COBEGIN);
	      break;
	    case 'M':
	      switch (yytext[3])
		{
		case 'D':
		  if (strcmp (yytext, "COMDAT") == 0)
		    return (COMDAT);
		  break;
		case 'M':
		  if (strcmp (yytext, "COMMON") == 0)
		    return (COMMON);
		  break;
		case 'P':
		  if (strcmp (yytext, "COMPEXPR") == 0)
		    return (COMPEXPR);
		  else if (strcmp (yytext, "COMPSTMT") == 0)
		    return (COMPSTMT);
		  break;
		}
	      break;
	    case 'N':
	      switch (yytext[3])
		{
		case 'J':
		  if (strcmp (yytext, "CONJ") == 0)
		    return (CONJ);
		  break;
		case 'S':
		  if (strcmp (yytext, "CONST") == 0)
		    return (CONST);
		  else if (strcmp (yytext, "CONSTRUCTOR") == 0)
		    return (CONSTRUCTOR);
		  break;
		case 'T':
		  if (strcmp (yytext, "CONTINUE") == 0)
		    return (CONTINUE);
		  break;
		}
	      break;
	    }
	  break;
	}
      break;
    case 'D':
      switch (yytext[1])
	{
	case 'E':
	  switch (yytext[2])
	    {
	    case 'F':
	      if (strcmp (yytext, "DEF") == 0)
		return (DEF);
	      else if (strcmp (yytext, "DEFAULT") == 0)
		return (DEFAULT);
	      else if (strcmp (yytext, "DEFINED") == 0)
		return (DEFINED);
	      break;
	    case 'S':
	      if (strcmp (yytext, "DESTRUCTOR") == 0)
		return (DESTRUCTOR);
	      break;
	    }
	  break;
	case 'I':
	  if (strcmp (yytext, "DIM") == 0)
	    return (DIM);
	  else if (strcmp (yytext, "DISJ") == 0)
	    return (DISJ);
	  else if (strcmp (yytext, "DIV") == 0)
	    return (DIV);
	  break;
	case 'O':
	  if (strcmp (yytext, "DO") == 0)
	    return (DO);
	  else
	    switch (yytext[2])
	      {
	      case 'A':
		if (strcmp (yytext, "DOACROSS") == 0)
		  return (DOACROSS);
		else if (strcmp (yytext, "DOALL") == 0)
		  return (DOALL);
		break;
	      case 'S':
		if (strcmp (yytext, "DOSERIAL") == 0)
		  return (DOSERIAL);
		else if (strcmp (yytext, "DOSUPER") == 0)
		  return (DOSUPER);
		break;
	      case 'T':
		if (strcmp (yytext, "DOT") == 0)
		  return (DOT);
		break;
	      case 'U':
		if (strcmp (yytext, "DOUBLE") == 0)
		  return (DOUBLE);
		break;
	      }
	  break;
	}
      break;
    case 'E':
      switch (yytext[1])
	{
	case 'L':
	  if (strcmp (yytext, "ELSE") == 0)
	    return (ELSE);
	  else if (strcmp (yytext, "ELLIPSIS") == 0)
	    return (ELLIPSIS);
	  break;
	case 'M':
	  if (strcmp (yytext, "EMPTY") == 0)
	    return (EMPTY);
	  break;
	case 'N':
	  if (strcmp (yytext, "END") == 0)
	    return (END);
	  if (strcmp (yytext, "ENUM") == 0)
	    return (ENUM);
	  else if (strcmp (yytext, "ENUMFIELD") == 0)
	    return (ENUMFIELD);
	  break;
	case 'Q':
	  if (strcmp (yytext, "EQ") == 0)
	    return (EQ);
	  break;
	case 'R':
	  if (strcmp (yytext, "ERROR") == 0)
	    return (ERROR);
	  break;
	case 'X':
	  switch (yytext[2])
	    {
	    case 'P':
	      if (strcmp (yytext, "EXPLICIT_ALIGNMENT") == 0)
		return (EXPLICIT_ALIGNMENT);
	      else if (strcmp (yytext, "EXPR") == 0)
		return (EXPR);
	      else if (strcmp (yytext, "EXPRSIZE") == 0)
		return (EXPRSIZE);
	      break;
	    case 'T':
	      if (strcmp (yytext, "EXTERN") == 0)
		return (EXTERN);
	      break;
	    }
	  break;
	}
      break;
    case 'F':
      switch (yytext[1])
	{
	case 'A':
	  if (strcmp (yytext, "FASTCALL") == 0)
	    return (FASTCALL);
	  break;
	case 'I':
	  if (strcmp (yytext, "FIELD") == 0)
	    return (FIELD);
	  else if (strcmp (yytext, "FINAL") == 0)
	    return (FINAL);
	  break;
	case 'L':
	  if (strcmp (yytext, "FLOAT") == 0)
	    return (FLOAT);
	  break;
	case 'O':
	  if (strcmp (yytext, "FOR") == 0)
	    return (FOR);
	  break;
	case 'U':
	  if (strcmp (yytext, "FUNC") == 0)
	    return (FUNC);
	  else if (strcmp (yytext, "FUNCTION") == 0)
	    return (FUNCTION);
	  break;
	}
      break;
    case 'G':
      switch (yytext[1])
	{
	case 'E':
	  if (strcmp (yytext, "GE") == 0)
	    return (GE);
	  break;
	case 'L':
	  if (strcmp (yytext, "GLOBAL") == 0)
	    return (GLOBAL);
	  break;
	case 'O':
	  if (strcmp (yytext, "GOTO") == 0)
	    return (GOTO);
	  break;
	case 'T':
	  if (strcmp (yytext, "GT") == 0)
	    return (GT);
	  break;
	case 'V':
	  if (strcmp (yytext, "GVAR") == 0)
	    return (GVAR);
	  break;
	}
      break;
    case 'H':
      if (strcmp (yytext, "HEADER") == 0)
	return (HEADER);
      break;
    case 'I':
      switch (yytext[1])
	{
	case 'D':
	  if (strcmp (yytext, "ID") == 0)
	    return (ID);
	  break;
	case 'F':
	  if (strcmp (yytext, "IF") == 0)
	    return (IF);
	  break;
	case 'M':
	  if (strcmp (yytext, "IMPLICIT") == 0)
	    return (IMPLICIT);
	  break;
	case 'N':
	  if (strcmp (yytext, "IN") == 0)
	    return (IN);
	  else
	    {
	      switch (yytext[2])
		{
		case 'C':
		  if (strcmp (yytext, "INC") == 0)
		    return (INC);
		  else if (strcmp (yytext, "INCLUDE") == 0)
		    return (INCLUDE);
		  else if (strcmp (yytext, "INCOMPLETE") == 0)
		    return (INCOMPLETE);
		  break;
		case 'D':
		  if (strcmp (yytext, "INDEX") == 0)
		    return (INDEX);
		  else if (strcmp (yytext, "INDR") == 0)
		    return (INDR);
		  break;
		case 'I':
		  if (strcmp (yytext, "INIT") == 0)
		    return (INIT);
		  break;
		case 'T':
		  if (strcmp (yytext, "INT") == 0)
		    return (INT);
		  break;
		case 'V':
		  if (strcmp (yytext, "INV") == 0)
		    return (INV);
		  break;
		}
	    }
	  break;
	case 'P':
	  if (strcmp (yytext, "IP_TABLE") == 0)
	    return (IP_TABLE);
	  break;
	}
      break;
    case 'K':
      if (strcmp (yytext, "KEY") == 0)
	return (KEY);
      break;
    case 'L':
      switch (yytext[1])
	{
	case 'A':
	  if (strcmp (yytext, "LABEL") == 0)
	    return (LABEL);
	  break;
	case 'E':
	  if (strcmp (yytext, "LE") == 0)
	    return (LE);
	  break;
	case 'I':
	  if (strcmp (yytext, "LINKED") == 0)
	    return (LINKED);
	  else if (strcmp (yytext, "LINKMULTI") == 0)
	    return (LINKMULTI);
	  break;
	case 'O':
	  if (strcmp (yytext, "LONG") == 0)
	    return (LONG);
	  else if (strcmp (yytext, "LONGLONG") == 0)
	    return (LONGLONG);
	  else if (strcmp (yytext, "LONGDOUBLE") == 0)
	    return (LONGDOUBLE);
	  break;
	case 'S':
	  if (strcmp (yytext, "LSHFT") == 0)
	    return (LSHFT);
	  break;
	case 'T':
	  if (strcmp (yytext, "LT") == 0)
	    return (LT);
	  else if (strcmp (yytext, "LTYPE") == 0)
	    return (LTYPE);
	  break;
	}
      break;
    case 'M':
      switch (yytext[1])
	{
	case 'O':
	  if (strcmp (yytext, "MOD") == 0)
	    return (MOD);
	  break;
	case 'U':
	  if (strcmp (yytext, "MUL") == 0)
	    return (MUL);
	  else if (strcmp (yytext, "MUTEX") == 0)
	    return (MUTEX);
	  break;
	}
      break;
    case 'N':
      switch (yytext[1])
	{
	case 'E':
	  if (strcmp (yytext, "NE") == 0)
	    return (NE);
	  else if (strcmp (yytext, "NEG") == 0)
	    return (NEG);
	  break;
	case 'O':
	  if (strcmp (yytext, "NOT") == 0)
	    return (NOT);
	  else if (strcmp (yytext, "NOT_AVAIL") == 0)
	    return (NOT_AVAIL);
	  break;
	case 'U':
	  if (strcmp (yytext, "NULL") == 0)
	    return (KW_NULL);
	  else if (strcmp (yytext, "NUM_ENTRIES") == 0)
	    return (NUM_ENTRIES);
	  break;
	}
      break;
    case 'O':
      switch (yytext[1])
	{
	case 'F':
	  if (strcmp (yytext, "OFFSET") == 0)
	    return (OFFSET);
	  break;
	case 'L':
	  if (strcmp (yytext, "OLD_PARAM") == 0)
	    return (OLD_PARAM);
	  break;
	case 'P':
	  if (strcmp (yytext, "OPERANDS") == 0)
	    return (OPERANDS);
	  break;
	case 'R':
	  if (strcmp (yytext, "OR") == 0)
	    return (OR);
	  break;
	case 'U':
	  if (strcmp (yytext, "OUT") == 0)
	    return (OUT);
	  break;
	}
      break;
    case 'P':
      switch (yytext[1])
	{
	case 'A':
	  if (strcmp (yytext, "PARAM") == 0)
	    return (PARAM);
	  else if (strcmp (yytext, "PARAMETER") == 0)
	    return (PARAMETER);
	  else if (strcmp (yytext, "PARENT") == 0)
	    return (PARENT);
	  break;
	case 'H':
	  if (strcmp (yytext, "PHI") == 0)
            return (PHI);
          break;
	case 'O':
	  switch (yytext[2])
	    {
	    case 'I':
	      if (strcmp (yytext, "POINTER") == 0)
		return (POINTER);
	      break;
	    case 'S':
	      if (strcmp (yytext, "POS") == 0)
		return (POS);
	      else if (strcmp (yytext, "POSTDEC") == 0)
		return (POSTDEC);
	      else if (strcmp (yytext, "POSTINC") == 0)
		return (POSTINC);
	      break;
	    }
	  break;
	case 'R':
	  switch (yytext[2])
	    {
	    case 'A':
	      if (strcmp (yytext, "PRAGMA") == 0)
		return (PRAGMA);
	      break;
	    case 'E':
	      if (strcmp (yytext, "PREDEC") == 0)
		return (PREDEC);
	      else if (strcmp (yytext, "PREINC") == 0)
		return (PREINC);
	      break;
	    case 'O':
	      if (strcmp (yytext, "PROFILE") == 0)
		return (PROFILE);
	      break;
	    }
	  break;
	case 'S':
	  if (strcmp (yytext, "PSTMT") == 0)
	    return (PSTMT);
	  break;
	}
      break;
    case 'Q':
      if (strcmp (yytext, "QUEST") == 0)
	return (QUEST);
      break;
    case 'R':
      switch (yytext[1])
	{
	case 'E':
	  if (strcmp (yytext, "REFS") == 0)
	    return (REFS);
	  else if (strcmp (yytext, "REGISTER") == 0)
	    return (REGISTER);
	  else if (strcmp (yytext, "RETURN") == 0)
	    return (RETURN);
	  break;
	case 'S':
	  if (strcmp (yytext, "RSHFT") == 0)
	    return (RSHFT);
	  break;
	}
      break;
    case 'S':
      switch (yytext[1])
	{
	case 'C':
	  if (strcmp (yytext, "SCOPE") == 0)
	    return (SCOPE);
	  break;
	case 'I':
	  if (strcmp (yytext, "SIGNED") == 0)
	    return (SIGNED);
	  else if (strcmp (yytext, "SIZE") == 0)
	    return (SIZE);
	  break;
	case 'H':
	  if (strcmp (yytext, "SHADOW") == 0)
	    return (SHADOW);
	  else if (strcmp (yytext, "SHORT") == 0)
	    return (SHORT);
	  break;
	case 'O':
	  if (strcmp (yytext, "SOURCE") == 0)
	    return (SOURCE);
	  break;
	case 'T':
	  switch (yytext[2])
	    {
	    case 'A':
	      if (strcmp (yytext, "STATIC") == 0)
		return (STATIC);
	      break;
	    case 'D':
	      if (strcmp (yytext, "STDCALL") == 0)
		return (STDCALL);
	      break;
	    case 'M':
	      if (strcmp (yytext, "STMT") == 0)
		return (STMT);
	      else if (strcmp (yytext, "STMTEXPR") == 0)
		return (STMTEXPR);
	      break;
	    case 'R':
	      if (strcmp (yytext, "STRUCT") == 0)
		return (STRUCT);
	      else if (strcmp (yytext, "STRING") == 0)
		return (STRING);
	      break;
	    }
	  break;
	case 'U':
	  if (strcmp (yytext, "SUB") == 0)
	    return (SUB);
	  break;
	case 'W':
	  if (strcmp (yytext, "SWITCH") == 0)
	    return (SWITCH);
	  break;
	case 'Y':
	  if (strcmp (yytext, "SYM") == 0)
	    return (SYM);
	  else if (strcmp (yytext, "SYMBOL_TABLE") == 0)
	    return (SYMBOL_TABLE);
	  else if (strcmp (yytext, "SYNC") == 0)
	    return (SYNC);
	  break;
	}
      break;
    case 'T':
      switch (yytext[1])
	{
	case 'H':
	  if (strcmp (yytext, "THEN") == 0)
	    return (THEN);
	  break;
	case 'Y':
	  if (strcmp (yytext, "TYPE") == 0)
	    return (TYPE);
	  else if (strcmp (yytext, "TYPEDEF") == 0)
	    return (TYPEDEF);
	  else if (strcmp (yytext, "TYPESIZE") == 0)
	    return (TYPESIZE);
	  break;
	}
      break;
    case 'U':
      if (strcmp (yytext, "UNION") == 0)
	return (UNION);
      else if (strcmp (yytext, "UNSIGNED") == 0)
	return (UNSIGNED);
      else if (strcmp (yytext, "UNNAMED") == 0)
	return (UNNAMED);
      break;
    case 'V':
      switch (yytext[1])
	{
	case 'A':
	  if (strcmp (yytext, "VAR") == 0)
	    return (VAR);
	  else if (strcmp (yytext, "VARARG") == 0)
	    return (VARARG);
	  break;
	case 'O':
	  if (strcmp (yytext, "VOID") == 0)
	    return (VOID);
	  else if (strcmp (yytext, "VOLATILE") == 0)
	    return (VOLATILE);
	  break;
	}
      break;
    case 'W':
      if (strcmp (yytext, "WEAK") == 0)
	return (WEAK);
      else if (strcmp (yytext, "WHILE") == 0)
	return (WHILE);
      break;
    case 'X':
      if (strcmp (yytext, "XOR") == 0)
	return (XOR);
      break;
    }
  /* If we didn't match a keyword, complain. */
  P_warn ("lex.l:lexIdentifier:%d Unknown identifier %s", __LINE__, yytext);

  return (0);
}


/*--------------------------------------------------------------------------*/
/*      We will implement a binary tree string management.
 */
typedef struct String
{
  char            *name;          /* string */
  struct String   *left;
  struct String   *right;
} String;
 
static String *stringTree = 0;
 
static char *
lmalloc (int size)
{
  char *new_str = (char *)malloc (size);
  if (new_str==0)
    {
      fprintf (stderr, "LIST : malloc returns nil\n");
      exit (1);
    }
  return (new_str);
}

/* String Save Function. */
static char *
strsave (char *str)
{
  char *new_str = (char *)lmalloc (strlen (str) + 1);
  strcpy (new_str, str);
  return (new_str);
}
 
/*      Find a string.  */
static String *
FindS (String *T, char *str)
{
  int diff;
  
  if (T == 0)                         /* not found */
    return (0);
  diff = strcmp (str, T->name);
  if (diff == 0)
    return (T);                 /* find a match */
  if (diff > 0)
    return (FindS (T->left, str));    /* search left */
  else
    return (FindS (T->right, str));   /* search right */
}

/*      Add a string.   */
static String *
AddS (String *T, char *str)
{
  int diff;
  String *new_str;
  
  if (T == 0)
    {                       /* add new string */
      new_str = (String *)lmalloc (sizeof (String));
      new_str->name = strsave (str);
      new_str->left = new_str->right = 0;
      return (new_str);
    }
  diff = strcmp (str, T->name);
  if (diff == 0) return (T);                 /* already exist */
  if (diff > 0)
    {
      T->left = AddS (T->left, str);   /* add to left */
      return (T);
    }
  else
    {
      T->right = AddS (T->right, str); /* add to right */
      return (T);
    }
}
 
/*      This function maintains all define-once-only names.
 *      It maintains a table of a list of unique names used
 *      by the entire program. This will save some space.
 */
char *
FindString (char *str)
{
  String *ptr;
  ptr = FindS (stringTree, str);
  if (ptr == 0)
    {
      /*      This is extremely inefficient.
       *      We should change the two routines
       *      to combine find and insert.
       */
      stringTree = AddS (stringTree, str);
      ptr = FindS (stringTree, str);
    }
  return (ptr->name);
}

/*--------------------------------------------------------------------------*/
#if 0
static LIST dead_list = 0;
static int dead_list_length = 0;

/*	allocate space for a new node.	*/
static LIST
NewNode (void)
{
  LIST new_node;
  if (dead_list != 0)
    {
      new_node = dead_list;
      dead_list = SiblingOf (dead_list);
      NodeType (new_node) = T_NULL;
      SiblingOf (new_node) = 0;
      ChildOf (new_node) = 0;
      /* BCC - 8/8/97 */
      LastChildOf (new_node) = 0;
    }
  else
    {
      new_node = (LIST)lmalloc (sizeof (NODE));
      NodeType (new_node) = T_NULL;
      SiblingOf (new_node) = 0;
      ChildOf (new_node) = 0;
      /* BCC - 8/8/97 */
      LastChildOf (new_node) = 0;
    }
  return (new_node);
}

/*	dispose space of a node and its siblings and descendants.	*/
LIST
DisposeNode (LIST node) 
{
  if (node == 0)
    return 0;
  if (dead_list_length > 50000)
    FreeDeadList ();
  if (NodeType (node) == T_LIST)
    {
      DisposeNode (ChildOf (node));
      ChildOf (node) = 0;
    }
  DisposeNode (SiblingOf (node));
  
  SiblingOf (node) = dead_list;	/* add node to the dead list */
  dead_list = node;		/* for recycling */
  dead_list_length++;

  return (0);
}

void
FreeDeadList ()
{
  LIST node1, node2;
  
  node1 = dead_list;
  while (node1)
    {
      node2 = node1;
      node1 = SiblingOf (node1);
      free (node2);
    }
  dead_list = 0;
  dead_list_length = 0;
}

/*	add a child.	*/
static void
AddChildNode (LIST parent, LIST child)
{
  LIST ptr;
  if (ChildOf (parent) == 0)
    {
      /* the first child */
      ChildOf (parent) = child;
      /* BCC - 8/8/97 */
      for (LastChildOf (parent) = child;
	   SiblingOf (LastChildOf (parent));
	   LastChildOf (parent) = SiblingOf (LastChildOf (parent)));
    }
  else
    {
      if (SiblingOf (LastChildOf (parent)))
	{
	  fprintf (stderr, "AddChildNode: Node found after LastChild");
	  exit (1);
	}
      SiblingOf (LastChildOf (parent)) = child;
      LastChildOf (parent) = child;
      for (LastChildOf (parent) = child;
	   SiblingOf (LastChildOf (parent));
	   LastChildOf (parent) = SiblingOf (LastChildOf (parent)));
      /* BCC - this old implementation takes forever to build a
	 6000-node long list */
#if 0
      /* find last child */
      for (ptr = ChildOf (parent); SiblingOf (ptr) != 0; )
	ptr = SiblingOf (ptr);
      /* append the new child to it */
      SiblingOf (ptr) = child;
#endif
    }
}

/*
 *	Get a node or a complete list from input.
 *	It is assumed that the lexer has been properly set up.
 */
LIST
GetNode (void)
{
  int node_type;
  LIST new_node, ptr;

  node_type = yylex ();		/* get token */

  if (node_type == 0)
    {		/* end of file */
      new_node = NewNode ();
      NodeType (new_node) = T_EOF;
      return (new_node);
    }

  switch (node_type)
    {
    case L_ID:		/* identifier */
      new_node = NewNode ();
      NodeType (new_node) = T_ID;
      StringOf (new_node) = FindString (TokenName);
      break;
    case L_INT:		/* integer */
      new_node = NewNode ();
      NodeType (new_node) = T_INT;
      IntegerOf (new_node) = TokenInteger;
      break;
    case L_REAL:		/* real constant literal */
      new_node = NewNode ();
      NodeType (new_node) = T_REAL;
      RealOf (new_node) = TokenReal;
      break;
    case L_STRING:		/* string literal */
      new_node = NewNode ();
      NodeType (new_node) = T_STRING;
      StringOf (new_node) = FindString (TokenName);
      break;
    case L_CHAR:		/* character literal */
      new_node = NewNode ();
      NodeType (new_node) = T_CHAR;
      StringOf (new_node) = FindString (TokenName);
      break;
    case L_ERROR:		/* erroneous input */
      new_node = NewNode ();
      NodeType (new_node) = T_NULL;
      break;
    default:		/* single character operator */
      if (node_type == '(')
	{
	  new_node = NewNode ();
	  NodeType (new_node) = T_LIST;
	  ChildOf (new_node) = 0;
	  while ((ptr = GetNode ()) != 0) 
	    AddChildNode (new_node, ptr);
	}
      else
	if (node_type == ')')
	  {
	    new_node = 0;
	  }
	else
	  {
	    char line[10];
	    sprintf (line, "'%c'", node_type);
	    new_node = NewNode ();
	    NodeType (new_node) = T_CHAR;
	    StringOf (new_node) = FindString (line);
	  }
      break;
    }
  return (new_node);
}

/*	print a node.
 *	this is useful for program debugging.
 */
static FILE *FF = stdout;
void
print_node (LIST node, int indent)
{
  int i;
  LIST ptr;
  if (node == 0)
    return;
  for (i = 0; i < indent; i++)
    fprintf (FF, " ");
  switch (NodeType (node))
    {
    case T_EOF:
      fprintf (FF, "<EOF>");
      break;
    case T_NULL:
      fprintf (FF, "<NULL>");
      break;
    case T_LIST:
      fprintf (FF, "(\n");
      for (ptr = ChildOf (node); ptr != 0; ptr = SiblingOf (ptr))
	{
	  print_node (ptr, indent+2);
	  fprintf (FF, "\n");
	}
      for (i = 0; i < indent; i++)
	fprintf (FF, " ");
      fprintf (FF, ")");
      break;
    case T_ID:
      fprintf (FF, "(id %s)", StringOf (node));
      break;
    case T_INT:
      fprintf (FF, "(int %d)", IntegerOf (node));
      break;
    case T_REAL:
      fprintf (FF, "(real %e)", RealOf (node));
      break;
    case T_STRING:
      fprintf (FF, "(string %s)", StringOf (node));
      break;
    case T_CHAR:
      fprintf (FF, "(char %s)", StringOf (node));
      break;
    case T_OPER:
      fprintf (FF, "(oper %c)", IntegerOf (node));
      break;
    default:
      fprintf (FF, "<ERROR>");
      break;
    }
}

/*
 *	print a node in a specified file.
 */
void
PrintNode (FILE *F, LIST node)
{
  FILE *save = FF;
  FF = F;
  print_node (node, 0);
  fprintf (F, "\n");
  FF = save;
}

LIST
GetInteger (LIST list, int *val)
{
  if (list == 0)
    return (0);
  if (NodeType (list) != T_INT)
    return (list);
  *val = IntegerOf (list);
  return (SiblingOf (list));
}

LIST
GetReal (LIST list, double *val)
{
  if (list == 0)
    return (0);
  if (NodeType (list) != T_REAL)
    return (list);
  *val = RealOf (list);
  return (SiblingOf (list));
}

LIST
GetString (LIST list, char **val)
{
  if (list == 0)
    return (0);
  if (NodeType (list) != T_STRING)
    return (list);
  *val = StringOf (list);
  return (SiblingOf (list));
}

LIST
GetId (LIST list, char **val)
{
  if (list == 0)
    return (0);
  if (NodeType (list) != T_ID)
    return (list);
  *val = StringOf (list);
  return (SiblingOf (list));
}

/* BCC - added for garbage collection - 8/22/96 */
static void
RemoveS (String *ptr)
{
  if (ptr == 0)
    return;
  RemoveS (ptr->left);
  ptr->left = 0;
  RemoveS (ptr->right);
  ptr->right = 0;
  free (ptr->name);
  free (ptr);
}

/* BCC - added for garbage collection - 8/22/96 */
void
RemoveAllString ()
{
  RemoveS (stringTree);
  stringTree = 0;
}

#endif



