lmdes.h File Reference
#include <config.h>
#include <stdio.h>
#include <library/dynamic_symbol.h>
#include <library/set.h>
Data Structures
struct mdes_IO_set_st
struct mdes_IO_item_st
struct mdes_resource_st
struct mdes_rmask_st
struct mdes_Rused
struct mdes_reslist_st
struct mdes_latency_st
struct mdes_alt_st
struct Mdes_Stats
struct mdes_operation_st
struct mdes_st
struct mdes_compatable_alt_st
struct Mdes_Info
Defines
#define MDES_INFO(oper) ((Mdes_Info *)(oper $\rightarrow$ mdes_info))
#define MDES_PRED 0
#define MDES_DEST 1
#define MDES_SRC 2
#define MDES_SYNC_IN 3
#define MDES_SYNC_OUT 4
#define MDES_SUPERSCALAR 0
#define MDES_VLIW 1
#define MDES_OVERLAPPING_REQUEST 0x00000001
#define mdes_processor_model() lmdes $\rightarrow$ processor_model
#define mdes_total_slots() lmdes $\rightarrow$ num_slots
Typedefs
typedef mdes_IO_set_st Mdes_IO_Set
typedef mdes_IO_item_st Mdes_IO_Item
typedef mdes_resource_st Mdes_Resource
typedef mdes_rmask_st Mdes_Rmask
typedef mdes_Rused Mdes_Rused
typedef mdes_reslist_st Mdes_ResList
typedef mdes_latency_st Mdes_Latency
typedef mdes_alt_st Mdes_Alt
typedef mdes_operation_st Mdes_Operation
typedef mdes_st Mdes
typedef mdes_compatable_alt_st Mdes_Compatable_Alt
Functions
void L_init_lmdes (char *mdes_file_name)
void L_init_lmdes2 (char *mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
void print_mdes (FILE *out, Mdes *mdes)
int lmdes_initialized (void)
Mdes_Info * build_mdes_info (unsigned int opcode, int *io_list)
void free_mdes_info (Mdes_Info *info)
void print_mdes_operand_name (FILE *out, Mdes *mdes, unsigned int index)
void mdes_print_IO_set (FILE *out, unsigned int id)
int mdes_defined_opcode (unsigned int opcode)
int op_flag_set (unsigned int opcode, int mask)
int alt_flag_set (unsigned int opcode, unsigned int alt_no, int mask)
int any_alt_flag_set (Mdes_Info *mdes_info, int mask)
int mdes_max_opcode (void)
int mdes_operand_count (void)
int mdes_latency_count (void)
int mdes_num_operands (unsigned int operand_type)
int mdes_null_operand (void)
int operand_index (unsigned int operand_type, unsigned int operand_number)
int operand_type (unsigned int operand_index)
int operand_number (unsigned int operand_index)
int max_operand_time (Mdes_Info *mdes_info, int operand_index)
int min_operand_time (Mdes_Info *mdes_info, int operand_index)
int mdes_calc_min_ready_time (Mdes_Info *mdes_info, int *ready_time)
int mdes_operand_latency (unsigned int opcode, unsigned int alt_no, unsigned int operand_index)
int mdes_max_completion_time (int opcode, int alt_no)
int mdes_heuristic_alt_id (int opcode)
Mdes * load_lmdes_from_version2 (char *mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
void Malloc_struct (void **ptr, int size)
void Malloc_name (char **ptr, char *name)
void print_mdes_stats (FILE *out, int prepass)
void increment_check_history (INT_Symbol_Table *table, int num_checks, int inc)
Variables
Mdes * lmdes
Define Documentation
#define MDES_DEST 1
Definition at line 74 of file lmdes.h.
Referenced by L_initialize_build_mdes_info(), load_lmdes(), load_lmdes_from_version2(), mdes_build_iolist(), mdes_max_completion_time(), print_mdes(), print_mdes_info_debug_info(), and print_mdes_operand_name().
#define MDES_INFO(oper) ((Mdes_Info *)(oper $\rightarrow$ mdes_info))
Definition at line 70 of file lmdes.h.
#define MDES_OVERLAPPING_REQUEST 0x00000001
Definition at line 84 of file lmdes.h.
#define MDES_PRED 0
Definition at line 73 of file lmdes.h.
Referenced by L_initialize_build_mdes_info(), load_lmdes(), load_lmdes_from_version2(), mdes_build_iolist(), print_mdes(), print_mdes_info_debug_info(), and print_mdes_operand_name().
#define mdes_processor_model() lmdes $\rightarrow$ processor_model
Definition at line 283 of file lmdes.h.
#define MDES_SRC 2
Definition at line 75 of file lmdes.h.
Referenced by L_initialize_build_mdes_info(), load_lmdes(), load_lmdes_from_version2(), mdes_build_iolist(), print_mdes(), print_mdes_info_debug_info(), and print_mdes_operand_name().
#define MDES_SUPERSCALAR 0
Definition at line 80 of file lmdes.h.
Referenced by load_lmdes_from_version2().
#define MDES_SYNC_IN 3
Definition at line 76 of file lmdes.h.
Referenced by load_lmdes(), load_lmdes_from_version2(), print_mdes(), and print_mdes_operand_name().
#define MDES_SYNC_OUT 4
Definition at line 77 of file lmdes.h.
Referenced by load_lmdes(), load_lmdes_from_version2(), print_mdes(), and print_mdes_operand_name().
#define mdes_total_slots() lmdes $\rightarrow$ num_slots
Definition at line 284 of file lmdes.h.
#define MDES_VLIW 1
Definition at line 81 of file lmdes.h.
Referenced by load_lmdes_from_version2().
Typedef Documentation
typedef struct mdes_st
 Mdes
typedef struct mdes_alt_st
 Mdes_Alt
typedef struct mdes_compatable_alt_st
 Mdes_Compatable_Alt
typedef struct mdes_IO_item_st
 Mdes_IO_Item
typedef struct mdes_IO_set_st
 Mdes_IO_Set
typedef struct mdes_latency_st
 Mdes_Latency
typedef struct mdes_operation_st
 Mdes_Operation
typedef struct mdes_reslist_st
 Mdes_ResList
typedef struct mdes_resource_st
 Mdes_Resource
typedef struct mdes_rmask_st
 Mdes_Rmask
typedef struct mdes_Rused
 Mdes_Rused
Function Documentation
int alt_flag_set (unsigned int opcode, unsigned int alt_no, int mask)
Definition at line 156 of file lmdes.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_st::file_name, I_punt(), lmdes, mdes_st::max_opcode, NULL, mdes_operation_st::num_alts, and mdes_st::op_table.
int any_alt_flag_set (Mdes_Info * mdes_info, int mask)
Definition at line 189 of file lmdes.c.
References mdes_compatable_alt_st::alt, mdes_alt_st::alt_flags, Mdes_Info::compatable_alts, mdes_compatable_alt_st::next, and NULL.
Mdes_Info* build_mdes_info (unsigned int opcode, int * io_list)
Definition at line 356 of file lmdes.c.
References mdes_st::file_name, mdes_st::IO_set_table, lmdes, mdes_st::max_IO_set_id, mdes_st::max_opcode, NULL, mdes_st::op_table, mdes_st::operand_count, operand_type(), mdes_st::operand_type_buf, and print_mdes_operand_name().
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
void free_mdes_info (Mdes_Info * info)
Definition at line 452 of file lmdes.c.
References Mdes_Info::compatable_alts, L_free(), Mdes_Compatable_Alt_pool, mdes_compatable_alt_st::next, and NULL.
Referenced by L_free_cb_mdes_info(), and L_free_oper_mdes_info().
void increment_check_history (INT_Symbol_Table * table, int num_checks, int inc)
Definition at line 1398 of file lmdes2.c.
References INT_Symbol::data, INT_add_symbol(), INT_find_symbol(), and NULL.
Referenced by add_check_history().
void L_init_lmdes (char * mdes_file_name)
Definition at line 781 of file lmdes.c.
References I_punt(), L_create_alloc_pool(), load_lmdes(), Mdes_Compatable_Alt_pool, and NULL.
void L_init_lmdes2 (char * mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
Definition at line 827 of file lmdes.c.
References L_create_alloc_pool(), load_lmdes(), load_lmdes_from_version2(), Mdes_Compatable_Alt_pool, and NULL.
int lmdes_initialized (void)
Definition at line 93 of file lmdes.c.
References lmdes, and NULL.
Mdes* load_lmdes_from_version2 (char * mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
Definition at line 450 of file lmdes2.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_alt_st::asm_name, calc_num_alts(), calc_num_op_alts(), calc_op_total_string_len(), calc_total_entry_name_len(), mdes_operation_st::can_sched_postpass, mdes_operation_st::can_sched_prepass, DEBUG_LMDES2, entry, mdes_latency_st::exception, mdes_IO_set_st::external_id, mdes_operation_st::external_name, find_field_by_name(), get_binary_parm(), get_int_parm(), get_int_value(), get_num_entries(), get_string_parm(), mdes_operation_st::heuristic_alt, I_punt(), mdes_IO_set_st::id, mdes_IO_item_st::id, mdes_resource_st::id, mdes_latency_st::id, mdes_operation_st::id, mdes_alt_st::id, init_stats(), mdes_alt_st::IO_item, mdes_operation_st::lat_class, mdes_alt_st::latency, load_mdes2(), Malloc_name(), Malloc_struct(), mdes_IO_set_st::mask, SM_Port::mask, SM_Syllable::mask, MD_Field::max_element_index, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_next_entry(), MDES_DEST, MDES_PRED, MDES_SRC, MDES_SUPERSCALAR, MDES_SYNC_IN, MDES_SYNC_OUT, MDES_VLIW, mdes_IO_set_st::name, mdes_IO_item_st::name, mdes_resource_st::name, mdes_latency_st::name, MD_Entry::name, SM_Nop::next_nop, mdes_operation_st::nop, NULL, mdes_operation_st::num_alts, SM_Table::num_choices, mdes_operation_st::num_slots, SM_Syllable::num_slots, mdes_operation_st::op_flags, mdes_operation_st::opcode, mdes_latency_st::operand_latency, mdes_IO_item_st::operand_type, mdes_alt_st::operation, mdes_operation_st::port_mask, SM_Nop::prev_nop, mdes_alt_st::reslist, mdes_operation_st::sched_postpass, mdes_operation_st::sched_prepass, MD_Entry::section, Set_add(), Set_copy(), Set_dispose(), set_latencies(), Set_new(), SM_add_ids_to_entries(), mdes_operation_st::syll_mask, SM_Port::syllable, and mdes_alt_st::table.
Referenced by L_init_lmdes2().
void Malloc_name (char ** ptr, char * name)
void Malloc_struct (void ** ptr, int size)
int max_operand_time (Mdes_Info * mdes_info, int operand_index)
Definition at line 536 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int mdes_calc_min_ready_time (Mdes_Info * mdes_info, int * ready_time)
Definition at line 612 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int mdes_defined_opcode (unsigned int opcode)
Definition at line 106 of file lmdes.c.
References lmdes, mdes_st::max_opcode, NULL, and mdes_st::op_table.
int mdes_heuristic_alt_id (int opcode)
Definition at line 699 of file lmdes.c.
References mdes_operation_st::heuristic_alt, I_punt(), mdes_max_completion_time(), NULL, and mdes_operation_st::num_alts.
int mdes_latency_count (void)
Definition at line 217 of file lmdes.c.
References mdes_st::latency_count, and lmdes.
int mdes_max_completion_time (int opcode, int alt_no)
Definition at line 738 of file lmdes.c.
References mdes_operation_st::alt, I_punt(), mdes_alt_st::latency, MDES_DEST, NULL, mdes_operation_st::num_alts, operand_index(), and mdes_latency_st::operand_latency.
Referenced by mdes_heuristic_alt_id().
int mdes_max_opcode (void)
Definition at line 122 of file lmdes.c.
References lmdes, and mdes_st::max_opcode.
int mdes_null_operand (void)
Definition at line 241 of file lmdes.c.
References lmdes, and mdes_st::null_external_id.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
int mdes_num_operands (unsigned int operand_type)
Definition at line 226 of file lmdes.c.
References I_punt(), lmdes, NULL, and mdes_st::number.
Referenced by L_initialize_build_mdes_info(), mdes_build_iolist(), and print_mdes_info_debug_info().
int mdes_operand_count (void)
Definition at line 207 of file lmdes.c.
References lmdes, and mdes_st::operand_count.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
int mdes_operand_latency (unsigned int opcode, unsigned int alt_no, unsigned int operand_index)
Definition at line 656 of file lmdes.c.
References mdes_operation_st::alt, I_punt(), mdes_alt_st::latency, NULL, mdes_operation_st::num_alts, and mdes_latency_st::operand_latency.
void mdes_print_IO_set (FILE * out, unsigned int id)
Definition at line 337 of file lmdes.c.
References mdes_st::IO_set_table, lmdes, mdes_st::max_IO_set_id, mdes_IO_set_st::name, and NULL.
Referenced by print_mdes_info_debug_info().
int min_operand_time (Mdes_Info * mdes_info, int operand_index)
Definition at line 574 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int op_flag_set (unsigned int opcode, int mask)
Definition at line 134 of file lmdes.c.
References mdes_st::file_name, I_punt(), lmdes, mdes_st::max_opcode, NULL, mdes_operation_st::op_flags, and mdes_st::op_table.
int operand_index (unsigned int operand_type, unsigned int operand_number)
Definition at line 469 of file lmdes.c.
References I_punt(), and NULL.
Referenced by L_initialize_build_mdes_info(), and mdes_max_completion_time().
int operand_number (unsigned int operand_index)
Definition at line 515 of file lmdes.c.
References I_punt().
Referenced by print_mdes_operand_name().
int operand_type (unsigned int operand_index)
Definition at line 495 of file lmdes.c.
References I_punt().
Referenced by build_mdes_info().
void print_mdes (FILE * out, Mdes * mdes)
Definition at line 1385 of file lmdes.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_alt_st::asm_name, mdes_Rused::end_usage, mdes_latency_st::exception, mdes_IO_set_st::external_id, mdes_operation_st::external_name, mdes_latency_st::id, mdes_reslist_st::id, mdes_resource_st::id, mdes_IO_item_st::id, mdes_IO_set_st::id, mdes_alt_st::IO_item, mdes_st::IO_item, mdes_st::IO_set, mdes_st::IOmask_width, mdes_alt_st::latency, mdes_st::latency, mdes_st::latency_count, mdes_IO_set_st::mask, mdes_st::max_opcode, MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MDES_SYNC_OUT, mdes_latency_st::name, mdes_reslist_st::name, mdes_resource_st::name, mdes_IO_item_st::name, mdes_IO_set_st::name, NULL, mdes_operation_st::num_alts, mdes_st::num_IO_items, mdes_st::num_IO_sets, mdes_st::num_latencies, mdes_st::num_operations, mdes_Rused::num_options, mdes_st::num_reslists, mdes_st::num_resources, mdes_reslist_st::num_RU_entries_required, mdes_reslist_st::num_slot_options, mdes_reslist_st::num_used, mdes_st::number, mdes_st::offset, mdes_operation_st::op_flags, mdes_st::op_table, mdes_operation_st::opcode, mdes_st::operand_count, mdes_latency_st::operand_latency, mdes_IO_item_st::operand_type, mdes_st::operation, mdes_Rused::option, mdes_rmask_st::pred, mdes_alt_st::reslist, mdes_st::reslist, mdes_st::resource, mdes_st::Rmask_width, mdes_reslist_st::slot_options, mdes_Rused::start_usage, mdes_rmask_st::uncond, and mdes_reslist_st::used.
void print_mdes_operand_name (FILE * out, Mdes * mdes, unsigned int index)
Definition at line 251 of file lmdes.c.
References I_punt(), mdes_st::latency_count, MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MDES_SYNC_OUT, mdes_st::offset, and operand_number().
Referenced by build_mdes_info().
void print_mdes_stats (FILE * out, int prepass)
Definition at line 1566 of file lmdes2.c.
References add_stats(), mdes_operation_st::can_sched_postpass, mdes_operation_st::can_sched_prepass, mdes_operation_st::external_name, Mdes_Stats::fail_option_check_dist, Mdes_Stats::fail_usage_check_dist, Mdes_Stats::first_choice_dist, Heap_Create(), Heap_ExtractTop(), Heap_Insert(), HEAP_MAX, init_stats(), lmdes, mdes_st::max_opcode, mdes_st::mdes2, NULL, Mdes_Stats::num_choice_dist, Mdes_Stats::num_oper_checks, Mdes_Stats::num_slot_checks, Mdes_Stats::num_usage_checks, mdes_st::op_table, print_check_history(), print_op_stats(), mdes_operation_st::sched_postpass, mdes_operation_st::sched_prepass, Mdes_Stats::succeed_option_check_dist, and Mdes_Stats::succeed_usage_check_dist.
Variable Documentation
Mdes* lmdes
Definition at line 73 of file lmdes.c.
Referenced by alt_flag_set(), build_mdes_info(), lmdes_initialized(), mdes_defined_opcode(), mdes_latency_count(), mdes_max_opcode(), mdes_null_operand(), mdes_num_operands(), mdes_operand_count(), mdes_print_IO_set(), op_flag_set(), print_mdes_info_debug_info(), and print_mdes_stats().