lmdes2.h File Reference
#include <config.h>
Functions
int get_int_parm (MD *md, char *parm_name)
Function Documentation
int get_int_parm (MD * md, char * parm_name)
Definition at line 127 of file lmdes2.c.
References find_parm_value(), I_punt(), and MD_get_string.
Referenced by load_lmdes_from_version2(), and SM_build_prod_cons_latency().