lmdes_interface.h File Reference
#include <config.h>
#include `lmdes.h`
Functions
void L_build_oper_mdes_info (L_Oper *op)
void L_build_cb_mdes_info (L_Cb *cb)
void L_free_oper_mdes_info (L_Oper *op)
void L_free_cb_mdes_info (L_Cb *cb)
Function Documentation
void L_build_cb_mdes_info (L_Cb * cb)
Definition at line 254 of file lmdes_interface.c.
References _build_mdes_info_initialized, _io_list, _io_list_dest, _io_list_pred, _io_list_src, build_mdes_info(), L_initialize_build_mdes_info(), mdes_build_iolist(), mdes_null_operand(), mdes_operand_count(), NULL, and print_mdes_info_debug_info().
void L_build_oper_mdes_info (L_Oper * op)
Definition at line 307 of file lmdes_interface.c.
References _build_mdes_info_initialized, _io_list, _io_list_dest, _io_list_pred, _io_list_src, build_mdes_info(), I_punt(), L_initialize_build_mdes_info(), mdes_build_iolist(), mdes_null_operand(), mdes_operand_count(), NULL, and print_mdes_info_debug_info().
void L_free_cb_mdes_info (L_Cb * cb)
Definition at line 356 of file lmdes_interface.c.
References free_mdes_info(), and NULL.
void L_free_oper_mdes_info (L_Oper * op)
Definition at line 375 of file lmdes_interface.c.
References free_mdes_info(), I_punt(), and NULL.