lmdes.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <malloc.h>
#include `lmdes.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Defines
#define MDES_VERSION 3
Functions
static Mdes * load_lmdes (char *file_name)
void Malloc_struct (void **ptr, int size)
void Malloc_name (char **ptr, char *name)
int lmdes_initialized (void)
int mdes_defined_opcode (unsigned int opcode)
int mdes_max_opcode (void)
int op_flag_set (unsigned int opcode, int mask)
int alt_flag_set (unsigned int opcode, unsigned int alt_no, int mask)
int any_alt_flag_set (Mdes_Info *mdes_info, int mask)
int mdes_operand_count (void)
int mdes_latency_count (void)
int mdes_num_operands (unsigned int operand_type)
int mdes_null_operand (void)
void print_mdes_operand_name (FILE *out, Mdes *mdes, unsigned int index)
static int IO_sets_intersect (Mdes *mdes, Mdes_IO_Set *set1, Mdes_IO_Set *set2)
static int IO_items_compatable (Mdes *mdes, Mdes_IO_Set **operand_type1, Mdes_IO_Set **operand_type2)
void mdes_print_IO_set (FILE *out, unsigned int id)
Mdes_Info * build_mdes_info (unsigned int opcode, int *io_list)
void free_mdes_info (Mdes_Info *info)
int operand_index (unsigned int operand_type, unsigned int operand_number)
int operand_type (unsigned int operand_index)
int operand_number (unsigned int operand_index)
int max_operand_time (Mdes_Info *mdes_info, int operand_index)
int min_operand_time (Mdes_Info *mdes_info, int operand_index)
int mdes_calc_min_ready_time (Mdes_Info *mdes_info, int *ready_time)
int mdes_operand_latency (unsigned int opcode, unsigned int alt_no, unsigned int operand_index)
int mdes_heuristic_alt_id (int opcode)
int mdes_max_completion_time (int opcode, int alt_no)
void L_init_lmdes (char *mdes_file_name)
void L_init_lmdes2 (char *mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
static void LM_read_mask (FILE *in, int *mask, int width)
void print_mdes (FILE *out, Mdes *mdes)
Variables
Mdes * lmdes
static L_Alloc_Pool * Mdes_Info_pool = NULL
static L_Alloc_Pool * Mdes_Compatable_Alt_pool = NULL
Define Documentation
#define MDES_VERSION 3
Definition at line 76 of file lmdes.c.
Referenced by load_lmdes().
Function Documentation
int alt_flag_set (unsigned int opcode, unsigned int alt_no, int mask)
Definition at line 156 of file lmdes.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_st::file_name, I_punt(), lmdes, mdes_st::max_opcode, NULL, mdes_operation_st::num_alts, and mdes_st::op_table.
int any_alt_flag_set (Mdes_Info * mdes_info, int mask)
Definition at line 189 of file lmdes.c.
References mdes_compatable_alt_st::alt, mdes_alt_st::alt_flags, Mdes_Info::compatable_alts, mdes_compatable_alt_st::next, and NULL.
Mdes_Info* build_mdes_info (unsigned int opcode, int * io_list)
Definition at line 356 of file lmdes.c.
References mdes_st::file_name, mdes_st::IO_set_table, lmdes, mdes_st::max_IO_set_id, mdes_st::max_opcode, NULL, mdes_st::op_table, mdes_st::operand_count, operand_type(), mdes_st::operand_type_buf, and print_mdes_operand_name().
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
void free_mdes_info (Mdes_Info * info)
Definition at line 452 of file lmdes.c.
References Mdes_Info::compatable_alts, L_free(), Mdes_Compatable_Alt_pool, mdes_compatable_alt_st::next, and NULL.
Referenced by L_free_cb_mdes_info(), and L_free_oper_mdes_info().
static int IO_items_compatable (Mdes * mdes, Mdes_IO_Set ** operand_type1, Mdes_IO_Set ** operand_type2) [static]
Definition at line 315 of file lmdes.c.
References IO_sets_intersect(), and mdes_st::operand_count.
static int IO_sets_intersect (Mdes * mdes, Mdes_IO_Set * set1, Mdes_IO_Set * set2) [static]
Definition at line 299 of file lmdes.c.
References mdes_st::IOmask_width, and mdes_IO_set_st::mask.
Referenced by IO_items_compatable().
void L_init_lmdes (char * mdes_file_name)
Definition at line 781 of file lmdes.c.
References I_punt(), L_create_alloc_pool(), load_lmdes(), Mdes_Compatable_Alt_pool, and NULL.
void L_init_lmdes2 (char * mdes_file_name, int num_pred, int num_dest, int num_src, int num_sync)
Definition at line 827 of file lmdes.c.
References L_create_alloc_pool(), load_lmdes(), load_lmdes_from_version2(), Mdes_Compatable_Alt_pool, and NULL.
static void LM_read_mask (FILE * in, int * mask, int width) [static]
Definition at line 883 of file lmdes.c.
References I_punt().
Referenced by load_lmdes().
int lmdes_initialized (void)
Definition at line 93 of file lmdes.c.
References lmdes, and NULL.
static Mdes * load_lmdes (char * file_name) [static]
Definition at line 897 of file lmdes.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_alt_st::asm_name, mdes_Rused::end_usage, mdes_latency_st::exception, mdes_IO_set_st::external_id, mdes_operation_st::external_name, mdes_Rused::flags, mdes_operation_st::heuristic_alt, I_punt(), mdes_alt_st::id, mdes_operation_st::id, mdes_latency_st::id, mdes_reslist_st::id, mdes_resource_st::id, mdes_IO_item_st::id, mdes_IO_set_st::id, mdes_alt_st::IO_item, mdes_alt_st::latency, LM_read_mask(), Malloc_name(), Malloc_struct(), mdes_IO_set_st::mask, MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MDES_SYNC_OUT, MDES_VERSION, mdes_latency_st::name, mdes_reslist_st::name, mdes_resource_st::name, mdes_IO_item_st::name, mdes_IO_set_st::name, NULL, mdes_operation_st::num_alts, mdes_Rused::num_options, mdes_reslist_st::num_RU_entries_required, mdes_reslist_st::num_slot_options, mdes_reslist_st::num_used, mdes_operation_st::op_flags, mdes_operation_st::opcode, mdes_latency_st::operand_latency, mdes_IO_item_st::operand_type, mdes_alt_st::operation, mdes_Rused::option, mdes_rmask_st::pred, mdes_alt_st::reslist, mdes_reslist_st::slot_options, mdes_Rused::start_usage, mdes_alt_st::table, mdes_rmask_st::uncond, and mdes_reslist_st::used.
Referenced by L_init_lmdes(), and L_init_lmdes2().
void Malloc_name (char ** ptr, char * name)
Definition at line 872 of file lmdes.c.
References I_punt(), and NULL.
Referenced by load_lmdes(), and load_lmdes_from_version2().
void Malloc_struct (void ** ptr, int size)
Definition at line 865 of file lmdes.c.
References I_punt(), and NULL.
Referenced by load_lmdes(), and load_lmdes_from_version2().
int max_operand_time (Mdes_Info * mdes_info, int operand_index)
Definition at line 536 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int mdes_calc_min_ready_time (Mdes_Info * mdes_info, int * ready_time)
Definition at line 612 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int mdes_defined_opcode (unsigned int opcode)
Definition at line 106 of file lmdes.c.
References lmdes, mdes_st::max_opcode, NULL, and mdes_st::op_table.
int mdes_heuristic_alt_id (int opcode)
Definition at line 699 of file lmdes.c.
References mdes_operation_st::heuristic_alt, I_punt(), mdes_max_completion_time(), NULL, and mdes_operation_st::num_alts.
int mdes_latency_count (void)
Definition at line 217 of file lmdes.c.
References mdes_st::latency_count, and lmdes.
int mdes_max_completion_time (int opcode, int alt_no)
Definition at line 738 of file lmdes.c.
References mdes_operation_st::alt, I_punt(), mdes_alt_st::latency, MDES_DEST, NULL, mdes_operation_st::num_alts, operand_index(), and mdes_latency_st::operand_latency.
Referenced by mdes_heuristic_alt_id().
int mdes_max_opcode (void)
Definition at line 122 of file lmdes.c.
References lmdes, and mdes_st::max_opcode.
int mdes_null_operand (void)
Definition at line 241 of file lmdes.c.
References lmdes, and mdes_st::null_external_id.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
int mdes_num_operands (unsigned int operand_type)
Definition at line 226 of file lmdes.c.
References I_punt(), lmdes, NULL, and mdes_st::number.
Referenced by L_initialize_build_mdes_info(), mdes_build_iolist(), and print_mdes_info_debug_info().
int mdes_operand_count (void)
Definition at line 207 of file lmdes.c.
References lmdes, and mdes_st::operand_count.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
int mdes_operand_latency (unsigned int opcode, unsigned int alt_no, unsigned int operand_index)
Definition at line 656 of file lmdes.c.
References mdes_operation_st::alt, I_punt(), mdes_alt_st::latency, NULL, mdes_operation_st::num_alts, and mdes_latency_st::operand_latency.
void mdes_print_IO_set (FILE * out, unsigned int id)
Definition at line 337 of file lmdes.c.
References mdes_st::IO_set_table, lmdes, mdes_st::max_IO_set_id, mdes_IO_set_st::name, and NULL.
Referenced by print_mdes_info_debug_info().
int min_operand_time (Mdes_Info * mdes_info, int operand_index)
Definition at line 574 of file lmdes.c.
References mdes_compatable_alt_st::alt, Mdes_Info::compatable_alts, I_punt(), mdes_alt_st::latency, mdes_compatable_alt_st::next, NULL, and mdes_latency_st::operand_latency.
int op_flag_set (unsigned int opcode, int mask)
Definition at line 134 of file lmdes.c.
References mdes_st::file_name, I_punt(), lmdes, mdes_st::max_opcode, NULL, mdes_operation_st::op_flags, and mdes_st::op_table.
int operand_index (unsigned int operand_type, unsigned int operand_number)
Definition at line 469 of file lmdes.c.
References I_punt(), and NULL.
Referenced by L_initialize_build_mdes_info(), and mdes_max_completion_time().
int operand_number (unsigned int operand_index)
Definition at line 515 of file lmdes.c.
References I_punt().
Referenced by print_mdes_operand_name().
int operand_type (unsigned int operand_index)
Definition at line 495 of file lmdes.c.
References I_punt().
Referenced by build_mdes_info().
void print_mdes (FILE * out, Mdes * mdes)
Definition at line 1385 of file lmdes.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_alt_st::asm_name, mdes_Rused::end_usage, mdes_latency_st::exception, mdes_IO_set_st::external_id, mdes_operation_st::external_name, mdes_IO_set_st::id, mdes_IO_item_st::id, mdes_resource_st::id, mdes_reslist_st::id, mdes_latency_st::id, mdes_st::IO_item, mdes_alt_st::IO_item, mdes_st::IO_set, mdes_st::IOmask_width, mdes_st::latency, mdes_alt_st::latency, mdes_st::latency_count, mdes_IO_set_st::mask, mdes_st::max_opcode, MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MDES_SYNC_OUT, mdes_IO_set_st::name, mdes_IO_item_st::name, mdes_resource_st::name, mdes_reslist_st::name, mdes_latency_st::name, NULL, mdes_operation_st::num_alts, mdes_st::num_IO_items, mdes_st::num_IO_sets, mdes_st::num_latencies, mdes_st::num_operations, mdes_Rused::num_options, mdes_st::num_reslists, mdes_st::num_resources, mdes_reslist_st::num_RU_entries_required, mdes_reslist_st::num_slot_options, mdes_reslist_st::num_used, mdes_st::number, mdes_st::offset, mdes_operation_st::op_flags, mdes_st::op_table, mdes_operation_st::opcode, mdes_st::operand_count, mdes_latency_st::operand_latency, mdes_IO_item_st::operand_type, mdes_st::operation, mdes_Rused::option, mdes_rmask_st::pred, mdes_st::reslist, mdes_alt_st::reslist, mdes_st::resource, mdes_st::Rmask_width, mdes_reslist_st::slot_options, mdes_Rused::start_usage, mdes_rmask_st::uncond, and mdes_reslist_st::used.
void print_mdes_operand_name (FILE * out, Mdes * mdes, unsigned int index)
Definition at line 251 of file lmdes.c.
References I_punt(), mdes_st::latency_count, MDES_DEST, MDES_PRED, MDES_SRC, MDES_SYNC_IN, MDES_SYNC_OUT, mdes_st::offset, and operand_number().
Referenced by build_mdes_info().
Variable Documentation
Mdes* lmdes
Definition at line 73 of file lmdes.c.
Referenced by alt_flag_set(), build_mdes_info(), lmdes_initialized(), mdes_defined_opcode(), mdes_latency_count(), mdes_max_opcode(), mdes_null_operand(), mdes_num_operands(), mdes_operand_count(), mdes_print_IO_set(), op_flag_set(), print_mdes_info_debug_info(), and print_mdes_stats().
L_Alloc_Pool* Mdes_Compatable_Alt_pool = NULL [static]
Definition at line 85 of file lmdes.c.
Referenced by free_mdes_info(), L_init_lmdes(), and L_init_lmdes2().
L_Alloc_Pool* Mdes_Info_pool = NULL [static]
Definition at line 84 of file lmdes.c.