lmdes2.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <malloc.h>
#include <library/md.h>
#include <library/i_error.h>
#include `lmdes.h`
#include `lmdes2.h`
#include `mdes2.h`
#include <library/heap.h>
#include <Lcode/l_flags.h>
Defines
#define DEBUG_LMDES2 0
Functions
int SM_add_ids_to_entries (MD_Section *section)
static void init_stats (Mdes_Stats *stats)
MD_Field * find_parm_value (MD *md, char *parm_name)
MD_Field * find_field_by_name (MD_Entry *entry, char *field_name)
char * get_string_parm (MD *md, char *parm_name)
int get_int_parm (MD *md, char *parm_name)
static int value_match (char *s1, char *s2)
int get_binary_parm (MD *md, char *parm_name)
int get_num_entries (MD *md, char *section_name)
int get_int_value (MD *md, char *section_name, char *entry_name, char *field_name, int index)
int calc_total_entry_name_len (MD *md, char *section_name)
void set_latencies (MD_Entry *entry, char *field_name, int *lat_array)
int calc_num_op_alts (MD_Entry *impact_op_entry)
int calc_num_alts (MD *md)
int calc_op_total_string_len (MD *md)
Mdes * load_lmdes_from_version2 (char *file_name, int num_pred, int num_dest, int num_src, int num_sync)
void increment_check_history (INT_Symbol_Table *table, int num_checks, int inc)
static void add_check_history (INT_Symbol_Table *dest, INT_Symbol_Table *src)
static void add_stats (Mdes_Stats *total, Mdes_Stats *add)
void print_check_history (FILE *out, char *name, char *type, INT_Symbol_Table *table)
void print_op_stats (FILE *out, char *name, Mdes_Stats *can_stats, Mdes_Stats *do_stats)
void print_mdes_stats (FILE *out, int prepass)
Define Documentation
#define DEBUG_LMDES2 0
Definition at line 69 of file lmdes2.c.
Referenced by load_lmdes_from_version2().
Function Documentation
static void add_check_history (INT_Symbol_Table * dest, INT_Symbol_Table * src) [static]
Definition at line 1417 of file lmdes2.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, increment_check_history(), INT_Symbol::next_symbol, NULL, and INT_Symbol::value.
Referenced by add_stats().
static void add_stats (Mdes_Stats * total, Mdes_Stats * add) [static]
Definition at line 1433 of file lmdes2.c.
References add_check_history(), Mdes_Stats::fail_option_check_dist, Mdes_Stats::fail_usage_check_dist, Mdes_Stats::first_choice_dist, Mdes_Stats::num_choice_dist, Mdes_Stats::num_oper_checks, Mdes_Stats::num_oper_checks_failed, Mdes_Stats::num_option_checks, Mdes_Stats::num_option_checks_failed, Mdes_Stats::num_slot_checks, Mdes_Stats::num_slot_checks_failed, Mdes_Stats::num_table_checks, Mdes_Stats::num_table_checks_failed, Mdes_Stats::num_usage_checks, Mdes_Stats::num_usage_checks_failed, Mdes_Stats::succeed_option_check_dist, Mdes_Stats::succeed_usage_check_dist, and total.
Referenced by print_mdes_stats().
int calc_num_alts (MD * md)
Definition at line 337 of file lmdes2.c.
References MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_link, MD_next_entry(), and NULL.
Referenced by load_lmdes_from_version2().
int calc_num_op_alts (MD_Entry * impact_op_entry)
Definition at line 299 of file lmdes2.c.
References find_field_by_name(), MD_Field::max_element_index, and MD_get_link.
Referenced by load_lmdes_from_version2().
int calc_op_total_string_len (MD * md)
Definition at line 391 of file lmdes2.c.
References MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_link, MD_next_entry(), MD_Entry::name, and NULL.
Referenced by load_lmdes_from_version2().
int calc_total_entry_name_len (MD * md, char * section_name)
Definition at line 246 of file lmdes2.c.
References entry, I_punt(), MD_find_section, MD_first_entry(), MD_next_entry(), and NULL.
Referenced by load_lmdes_from_version2().
MD_Field* find_field_by_name (MD_Entry * entry, char * field_name)
Definition at line 102 of file lmdes2.c.
References entry, I_punt(), MD_find_field, MD_find_field_decl, and NULL.
Referenced by calc_num_op_alts(), load_lmdes_from_version2(), and set_latencies().
MD_Field* find_parm_value (MD * md, char * parm_name)
Definition at line 76 of file lmdes2.c.
References I_punt(), MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_Field_Decl::name, and NULL.
Referenced by get_binary_parm(), get_int_parm(), and get_string_parm().
int get_binary_parm (MD * md, char * parm_name)
Definition at line 177 of file lmdes2.c.
References find_parm_value(), I_punt(), MD_get_string, and value_match().
Referenced by load_lmdes_from_version2().
int get_int_parm (MD * md, char * parm_name)
Definition at line 127 of file lmdes2.c.
References find_parm_value(), I_punt(), and MD_get_string.
Referenced by load_lmdes_from_version2(), and SM_build_prod_cons_latency().
int get_int_value (MD * md, char * section_name, char * entry_name, char * field_name, int index)
Definition at line 216 of file lmdes2.c.
References entry, I_punt(), MD_find_entry, MD_find_field, MD_find_field_decl, MD_find_section, MD_get_int, MD_Field_Decl::name, and NULL.
Referenced by load_lmdes_from_version2().
int get_num_entries (MD * md, char * section_name)
Definition at line 202 of file lmdes2.c.
References MD_Section::entry_table, MD_find_section, and MD_Symbol_Table::symbol_count.
Referenced by load_lmdes_from_version2().
char* get_string_parm (MD * md, char * parm_name)
Definition at line 116 of file lmdes2.c.
References find_parm_value(), and MD_get_string.
Referenced by load_lmdes_from_version2().
void increment_check_history (INT_Symbol_Table * table, int num_checks, int inc)
Definition at line 1398 of file lmdes2.c.
References INT_Symbol::data, INT_add_symbol(), INT_find_symbol(), and NULL.
Referenced by add_check_history().
static void init_stats (Mdes_Stats * stats) [static]
Definition at line 1372 of file lmdes2.c.
References Mdes_Stats::fail_option_check_dist, Mdes_Stats::fail_usage_check_dist, Mdes_Stats::first_choice_dist, INT_new_symbol_table(), Mdes_Stats::num_choice_dist, Mdes_Stats::num_oper_checks, Mdes_Stats::num_oper_checks_failed, Mdes_Stats::num_option_checks, Mdes_Stats::num_option_checks_failed, Mdes_Stats::num_slot_checks, Mdes_Stats::num_slot_checks_failed, Mdes_Stats::num_table_checks, Mdes_Stats::num_table_checks_failed, Mdes_Stats::num_usage_checks, Mdes_Stats::num_usage_checks_failed, Mdes_Stats::succeed_option_check_dist, and Mdes_Stats::succeed_usage_check_dist.
Referenced by load_lmdes_from_version2(), and print_mdes_stats().
Mdes* load_lmdes_from_version2 (char * file_name, int num_pred, int num_dest, int num_src, int num_sync)
Definition at line 450 of file lmdes2.c.
References mdes_operation_st::alt, mdes_alt_st::alt_flags, mdes_alt_st::asm_name, calc_num_alts(), calc_num_op_alts(), calc_op_total_string_len(), calc_total_entry_name_len(), mdes_operation_st::can_sched_postpass, mdes_operation_st::can_sched_prepass, DEBUG_LMDES2, entry, mdes_latency_st::exception, mdes_IO_set_st::external_id, mdes_operation_st::external_name, find_field_by_name(), get_binary_parm(), get_int_parm(), get_int_value(), get_num_entries(), get_string_parm(), mdes_operation_st::heuristic_alt, I_punt(), mdes_alt_st::id, mdes_operation_st::id, mdes_latency_st::id, mdes_resource_st::id, mdes_IO_item_st::id, mdes_IO_set_st::id, init_stats(), mdes_alt_st::IO_item, mdes_operation_st::lat_class, mdes_alt_st::latency, load_mdes2(), Malloc_name(), Malloc_struct(), SM_Syllable::mask, SM_Port::mask, mdes_IO_set_st::mask, MD_Field::max_element_index, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, MD_next_entry(), MDES_DEST, MDES_PRED, MDES_SRC, MDES_SUPERSCALAR, MDES_SYNC_IN, MDES_SYNC_OUT, MDES_VLIW, MD_Entry::name, mdes_latency_st::name, mdes_resource_st::name, mdes_IO_item_st::name, mdes_IO_set_st::name, SM_Nop::next_nop, mdes_operation_st::nop, NULL, mdes_operation_st::num_alts, SM_Table::num_choices, SM_Syllable::num_slots, mdes_operation_st::num_slots, mdes_operation_st::op_flags, mdes_operation_st::opcode, mdes_latency_st::operand_latency, mdes_IO_item_st::operand_type, mdes_alt_st::operation, mdes_operation_st::port_mask, SM_Nop::prev_nop, mdes_alt_st::reslist, mdes_operation_st::sched_postpass, mdes_operation_st::sched_prepass, MD_Entry::section, Set_add(), Set_copy(), Set_dispose(), set_latencies(), Set_new(), SM_add_ids_to_entries(), mdes_operation_st::syll_mask, SM_Port::syllable, and mdes_alt_st::table.
Referenced by L_init_lmdes2().
void print_check_history (FILE * out, char * name, char * type, INT_Symbol_Table * table)
Definition at line 1468 of file lmdes2.c.
References INT_Symbol::data, INT_Symbol_Table::head_symbol, Heap_Create(), Heap_ExtractTop(), Heap_Insert(), HEAP_MIN, INT_Symbol::next_symbol, NULL, and INT_Symbol::value.
Referenced by print_mdes_stats().
void print_mdes_stats (FILE * out, int prepass)
Definition at line 1566 of file lmdes2.c.
References add_stats(), mdes_operation_st::can_sched_postpass, mdes_operation_st::can_sched_prepass, mdes_operation_st::external_name, Mdes_Stats::fail_option_check_dist, Mdes_Stats::fail_usage_check_dist, Mdes_Stats::first_choice_dist, Heap_Create(), Heap_ExtractTop(), Heap_Insert(), HEAP_MAX, init_stats(), lmdes, mdes_st::max_opcode, mdes_st::mdes2, NULL, Mdes_Stats::num_choice_dist, Mdes_Stats::num_oper_checks, Mdes_Stats::num_slot_checks, Mdes_Stats::num_usage_checks, mdes_st::op_table, print_check_history(), print_op_stats(), mdes_operation_st::sched_postpass, mdes_operation_st::sched_prepass, Mdes_Stats::succeed_option_check_dist, and Mdes_Stats::succeed_usage_check_dist.
void print_op_stats (FILE * out, char * name, Mdes_Stats * can_stats, Mdes_Stats * do_stats)
Definition at line 1519 of file lmdes2.c.
References Mdes_Stats::num_oper_checks, Mdes_Stats::num_option_checks, Mdes_Stats::num_slot_checks_failed, Mdes_Stats::num_usage_checks, and Mdes_Stats::num_usage_checks_failed.
Referenced by print_mdes_stats().
void set_latencies (MD_Entry * entry, char * field_name, int * lat_array)
Definition at line 270 of file lmdes2.c.
References MD_Field::entry, entry, find_field_by_name(), I_punt(), MD_Field::max_element_index, MD_get_int, MD_get_link, MD_Entry::name, MD_Section::name, NULL, and MD_Entry::section.
Referenced by load_lmdes_from_version2().
int SM_add_ids_to_entries (MD_Section * section)
Definition at line 71 of file sm_mdes.c.
References entry, I_punt(), MD_find_field_decl, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, and NULL.
Referenced by load_lmdes_from_version2(), SM_build_choices(), SM_build_drules(), SM_build_issues(), SM_build_ports(), SM_build_prod_cons_latency(), SM_build_resources(), SM_build_restrictions(), SM_build_syllables(), SM_build_tables(), SM_build_templates(), SM_build_tgroups(), and SM_build_units().
static int value_match (char * s1, char * s2) [static]
Definition at line 159 of file lmdes2.c.
Referenced by get_binary_parm().