lmdes_interface.c File Reference
#include <config.h>
#include <library/i_error.h>
#include <Lcode/l_main.h>
#include `lmdes.h`
#include `lmdes_interface.h`
Functions
static void L_initialize_build_mdes_info (void)
static void print_mdes_info_debug_info (L_Oper *op, int opcode, char *func_name)
static int mdes_build_iolist (L_Oper *op, int **dest, int **src, int **pred)
void L_build_cb_mdes_info (L_Cb *cb)
void L_build_oper_mdes_info (L_Oper *op)
void L_free_cb_mdes_info (L_Cb *cb)
void L_free_oper_mdes_info (L_Oper *op)
Variables
static int _build_mdes_info_initialized = 0
static int ** _io_list_dest = NULL
static int ** _io_list_src = NULL
static int ** _io_list_pred = NULL
static int * _io_list = NULL
static int(*) mdes_get_operand_type_fptr (L_Operand *operand)
Function Documentation
void L_build_cb_mdes_info (L_Cb * cb)
Definition at line 254 of file lmdes_interface.c.
References _build_mdes_info_initialized, _io_list, _io_list_dest, _io_list_pred, _io_list_src, build_mdes_info(), L_initialize_build_mdes_info(), mdes_build_iolist(), mdes_null_operand(), mdes_operand_count(), NULL, and print_mdes_info_debug_info().
void L_build_oper_mdes_info (L_Oper * op)
Definition at line 307 of file lmdes_interface.c.
References _build_mdes_info_initialized, _io_list, _io_list_dest, _io_list_pred, _io_list_src, build_mdes_info(), I_punt(), L_initialize_build_mdes_info(), mdes_build_iolist(), mdes_null_operand(), mdes_operand_count(), NULL, and print_mdes_info_debug_info().
void L_free_cb_mdes_info (L_Cb * cb)
Definition at line 356 of file lmdes_interface.c.
References free_mdes_info(), and NULL.
void L_free_oper_mdes_info (L_Oper * op)
Definition at line 375 of file lmdes_interface.c.
References free_mdes_info(), I_punt(), and NULL.
static void L_initialize_build_mdes_info (void) [static]
Definition at line 78 of file lmdes_interface.c.
References _build_mdes_info_initialized, _io_list, _io_list_dest, _io_list_pred, _io_list_src, I_punt(), MDES_DEST, mdes_get_operand_type_fptr, mdes_num_operands(), MDES_PRED, MDES_SRC, NULL, and operand_index().
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
static int mdes_build_iolist (L_Oper * op, int ** dest, int ** src, int ** pred) [static]
Definition at line 191 of file lmdes_interface.c.
References I_punt(), MDES_DEST, mdes_get_operand_type_fptr, mdes_num_operands(), MDES_PRED, MDES_SRC, and NULL.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
static void print_mdes_info_debug_info (L_Oper * op, int opcode, char * func_name) [static]
Definition at line 147 of file lmdes_interface.c.
References _io_list_dest, _io_list_pred, _io_list_src, mdes_operation_st::external_name, I_punt(), lmdes, mdes_st::max_opcode, MDES_DEST, mdes_num_operands(), MDES_PRED, mdes_print_IO_set(), MDES_SRC, NULL, and mdes_st::op_table.
Referenced by L_build_cb_mdes_info(), and L_build_oper_mdes_info().
Variable Documentation
int _build_mdes_info_initialized = 0 [static]
Definition at line 68 of file lmdes_interface.c.
Referenced by L_build_cb_mdes_info(), L_build_oper_mdes_info(), and L_initialize_build_mdes_info().
int* _io_list = NULL [static]
Definition at line 72 of file lmdes_interface.c.
Referenced by L_build_cb_mdes_info(), L_build_oper_mdes_info(), and L_initialize_build_mdes_info().
int** _io_list_dest = NULL [static]
Definition at line 69 of file lmdes_interface.c.
Referenced by L_build_cb_mdes_info(), L_build_oper_mdes_info(), L_initialize_build_mdes_info(), and print_mdes_info_debug_info().
int** _io_list_pred = NULL [static]
Definition at line 71 of file lmdes_interface.c.
Referenced by L_build_cb_mdes_info(), L_build_oper_mdes_info(), L_initialize_build_mdes_info(), and print_mdes_info_debug_info().
int** _io_list_src = NULL [static]
Definition at line 70 of file lmdes_interface.c.
Referenced by L_build_cb_mdes_info(), L_build_oper_mdes_info(), L_initialize_build_mdes_info(), and print_mdes_info_debug_info().
int(*) mdes_get_operand_type_fptr(L_Operand *operand) [static]
Definition at line 75 of file lmdes_interface.c.
Referenced by L_initialize_build_mdes_info(), and mdes_build_iolist().