mdes2.h File Reference
#include <config.h>
#include <stdio.h>
#include <library/md.h>
#include `lmdes.h`
#include `sm_mdes.h`
Data Structures
struct Mdes2
Functions
Mdes2 * load_mdes2 (char *file_name)
Function Documentation
Mdes2* load_mdes2 (char * file_name)
Definition at line 70 of file mdes2.c.
References Mdes2::file_name, I_punt(), L_alloc(), L_create_alloc_pool(), Mdes2::md_mdes, MD_read_md(), Mdes2_pool, NULL, SM_build_mdes(), Mdes2::sm_mdes, and Mdes2::version1_mdes.
Referenced by load_lmdes_from_version2().