mdes2.c File Reference
#include <config.h>
#include <stdio.h>
#include <strings.h>
#include <Lcode/l_main.h>
#include <library/l_alloc_new.h>
#include <library/i_error.h>
#include `lmdes.h`
#include `mdes2.h`
Functions
Mdes2 * load_mdes2 (char *file_name)
Variables
static L_Alloc_Pool * Mdes2_pool = NULL
Function Documentation
Mdes2* load_mdes2 (char * file_name)
Definition at line 70 of file mdes2.c.
References Mdes2::file_name, I_punt(), L_alloc(), L_create_alloc_pool(), Mdes2::md_mdes, MD_read_md(), Mdes2_pool, NULL, SM_build_mdes(), Mdes2::sm_mdes, and Mdes2::version1_mdes.
Referenced by load_lmdes_from_version2().
Variable Documentation
L_Alloc_Pool* Mdes2_pool = NULL [static]
Definition at line 65 of file mdes2.c.
Referenced by load_mdes2().