sm_mdes.h File Reference
#include <config.h>
#include <library/md.h>
#include <library/set.h>
Data Structures
struct SM_Resource
struct SM_Usage
struct SM_Option
struct SM_Choice
struct SM_Table
struct SM_Syllable
struct SM_Port
struct SM_Restriction
struct SM_Template
struct SM_TGroup
struct SM_Issue
struct SM_DRule
struct SM_Nop
struct SM_PCLat
struct SM_Mdes
Functions
SM_Mdes * SM_build_mdes (struct Mdes2 *mdes2)
Function Documentation
SM_Mdes* SM_build_mdes (struct Mdes2 * mdes2)
Definition at line 1622 of file sm_mdes.c.
References SM_Mdes::drule_array, SM_Mdes::issue_array, L_alloc(), L_create_alloc_pool(), SM_Mdes::max_template_per_issue, MD_find_section, Mdes2::md_mdes, SM_Mdes::md_mdes, SM_Mdes::mdes2, NULL, SM_Mdes::num_drules, SM_Mdes::num_issues, SM_Mdes::num_ports, SM_Mdes::num_restricts, SM_Mdes::num_syllables, SM_Mdes::num_templates, SM_Mdes::num_tgroups, SM_Mdes::pclat_array, SM_Mdes::pclat_array_size, SM_Mdes::port_array, Print_prod_cons_latency(), SM_Mdes::restrict_array, SM_Mdes::slots_per_template, SM_build_choices(), SM_build_drules(), SM_build_issues(), SM_build_ports(), SM_build_prod_cons_latency(), SM_build_resources(), SM_build_restrictions(), SM_build_syllables(), SM_build_tables(), SM_build_templates(), SM_build_tgroups(), SM_build_units(), SM_Mdes_pool, SM_Mdes::syllable_array, SM_Mdes::template_array, SM_Mdes::template_shift_var, SM_Mdes::tgroup_array, and SM_Mdes::top_syllable.
Referenced by load_mdes2().