sm_mdes.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include `sm_mdes.h`
#include `mdes2.h`
#include `lmdes2.h`
#include <library/l_alloc_new.h>
#include <library/i_error.h>
Defines
#define DEBUG_MDES 0
Functions
int SM_add_ids_to_entries (MD_Section *section)
void SM_build_resources (SM_Mdes *sm_mdes)
void SM_build_units (SM_Mdes *sm_mdes)
void SM_build_choices (SM_Mdes *sm_mdes)
void SM_build_tables (SM_Mdes *sm_mdes)
void SM_build_syllables (SM_Mdes *sm_mdes)
void SM_build_ports (SM_Mdes *sm_mdes)
void SM_build_restrictions (SM_Mdes *sm_mdes)
void SM_build_templates (SM_Mdes *sm_mdes)
void SM_build_tgroups (SM_Mdes *sm_mdes)
void SM_build_issues (SM_Mdes *sm_mdes)
void SM_build_drules (SM_Mdes *sm_mdes)
void SM_build_prod_cons_latency (SM_Mdes *sm_mdes)
void Print_prod_cons_latency (SM_Mdes *sm_mdes)
SM_Mdes * SM_build_mdes (Mdes2 *mdes2)
Variables
static L_Alloc_Pool * SM_Mdes_pool = NULL
Define Documentation
#define DEBUG_MDES 0
Definition at line 66 of file sm_mdes.c.
Function Documentation
void Print_prod_cons_latency (SM_Mdes * sm_mdes)
Definition at line 1581 of file sm_mdes.c.
References SM_PCLat::clat, SM_PCLat::csrc_latency_penalty, SM_PCLat::name, SM_Mdes::pclat_array, SM_Mdes::pclat_array_size, SM_PCLat::pdest_latency_penalty, SM_PCLat::plat, and Set_print().
Referenced by SM_build_mdes().
int SM_add_ids_to_entries (MD_Section * section)
Definition at line 71 of file sm_mdes.c.
References entry, I_punt(), MD_find_field_decl, MD_first_entry(), MD_new_field(), MD_new_field_decl(), MD_next_entry(), MD_require_int(), MD_REQUIRED_FIELD, MD_set_int, and NULL.
Referenced by load_lmdes_from_version2(), SM_build_choices(), SM_build_drules(), SM_build_issues(), SM_build_ports(), SM_build_prod_cons_latency(), SM_build_resources(), SM_build_restrictions(), SM_build_syllables(), SM_build_tables(), SM_build_templates(), SM_build_tgroups(), and SM_build_units().
void SM_build_choices (SM_Mdes * sm_mdes)
Definition at line 346 of file sm_mdes.c.
References SM_Mdes::choice_array, SM_Mdes::choice_array_size, SM_Choice::first_option, SM_Option::first_usage, I_punt(), SM_Choice::last_option, SM_Option::last_usage, SM_Usage::map_offset, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, NULL, SM_add_ids_to_entries(), and SM_Mdes::unit_array.
Referenced by SM_build_mdes().
void SM_build_drules (SM_Mdes * sm_mdes)
Definition at line 1208 of file sm_mdes.c.
References SM_Mdes::drule_array, I_punt(), SM_Resource::mask, SM_TGroup::mask, SM_Syllable::mask, SM_Port::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_DRule::name, NULL, SM_Mdes::num_drules, SM_DRule::num_rsrcs, SM_DRule::num_slots, SM_Mdes::port_array, SM_DRule::port_mask, SM_Mdes::resource, SM_DRule::rsrc, SM_DRule::slot, SM_add_ids_to_entries(), SM_DRule::syll_mask, SM_Mdes::syllable_array, SM_Mdes::template_array, SM_DRule::templates, and SM_Mdes::tgroup_array.
Referenced by SM_build_mdes().
void SM_build_issues (SM_Mdes * sm_mdes)
Definition at line 1102 of file sm_mdes.c.
References I_punt(), SM_Mdes::issue_array, SM_TGroup::mask, MD_Field::max_element_index, SM_Mdes::max_template_per_issue, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_Issue::name, NULL, SM_Mdes::num_issues, SM_Issue::num_templates, SM_add_ids_to_entries(), SM_Mdes::template_array, SM_Issue::templates, and SM_Mdes::tgroup_array.
Referenced by SM_build_mdes().
SM_Mdes* SM_build_mdes (Mdes2 * mdes2)
Definition at line 1622 of file sm_mdes.c.
References SM_Mdes::drule_array, SM_Mdes::issue_array, L_alloc(), L_create_alloc_pool(), SM_Mdes::max_template_per_issue, MD_find_section, SM_Mdes::md_mdes, Mdes2::md_mdes, SM_Mdes::mdes2, NULL, SM_Mdes::num_drules, SM_Mdes::num_issues, SM_Mdes::num_ports, SM_Mdes::num_restricts, SM_Mdes::num_syllables, SM_Mdes::num_templates, SM_Mdes::num_tgroups, SM_Mdes::pclat_array, SM_Mdes::pclat_array_size, SM_Mdes::port_array, Print_prod_cons_latency(), SM_Mdes::restrict_array, SM_Mdes::slots_per_template, SM_build_choices(), SM_build_drules(), SM_build_issues(), SM_build_ports(), SM_build_prod_cons_latency(), SM_build_resources(), SM_build_restrictions(), SM_build_syllables(), SM_build_tables(), SM_build_templates(), SM_build_tgroups(), SM_build_units(), SM_Mdes_pool, SM_Mdes::syllable_array, SM_Mdes::template_array, SM_Mdes::template_shift_var, SM_Mdes::tgroup_array, and SM_Mdes::top_syllable.
Referenced by load_mdes2().
void SM_build_ports (SM_Mdes * sm_mdes)
Definition at line 743 of file sm_mdes.c.
References I_punt(), SM_Syllable::mask, SM_Port::mask, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), SM_Syllable::name, MD_Entry::name, SM_Port::name, NULL, SM_Mdes::num_ports, SM_Mdes::port_array, SM_add_ids_to_entries(), SM_Port::syllable, and SM_Mdes::syllable_array.
Referenced by SM_build_mdes().
void SM_build_prod_cons_latency (SM_Mdes * sm_mdes)
Definition at line 1416 of file sm_mdes.c.
References SM_PCLat::clat, SM_PCLat::csrc_latency_penalty, get_int_parm(), I_punt(), MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_PCLat::name, NULL, SM_Mdes::pclat_array, SM_Mdes::pclat_array_size, SM_PCLat::pdest_latency_penalty, SM_PCLat::plat, Set_add(), Set_copy(), Set_dispose(), Set_new(), and SM_add_ids_to_entries().
Referenced by SM_build_mdes().
void SM_build_resources (SM_Mdes * sm_mdes)
Definition at line 104 of file sm_mdes.c.
References I_punt(), SM_Mdes::map_width, SM_Resource::mask, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_Resource::name, NULL, SM_Mdes::num_resources, SM_Resource::offset, SM_Mdes::resource, SM_add_ids_to_entries(), and SM_Mdes::time_shift.
Referenced by SM_build_mdes().
void SM_build_restrictions (SM_Mdes * sm_mdes)
Definition at line 809 of file sm_mdes.c.
References I_punt(), SM_Port::mask, SM_Restriction::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_Restriction::name, NULL, SM_Restriction::num, SM_Mdes::num_restricts, SM_Mdes::port_array, SM_Mdes::restrict_array, and SM_add_ids_to_entries().
Referenced by SM_build_mdes().
void SM_build_syllables (SM_Mdes * sm_mdes)
Definition at line 646 of file sm_mdes.c.
References I_punt(), SM_Syllable::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_Syllable::name, NULL, SM_Syllable::num_slots, SM_Mdes::num_syllables, SM_add_ids_to_entries(), SM_Mdes::syllable_array, and SM_Mdes::top_syllable.
Referenced by SM_build_mdes().
void SM_build_tables (SM_Mdes * sm_mdes)
Definition at line 442 of file sm_mdes.c.
References SM_Mdes::choice_array, SM_Table::first_choice, SM_Choice::first_option, I_punt(), SM_Table::last_choice, SM_Choice::last_option, MD_Field::max_element_index, SM_Mdes::max_num_choices, SM_Table::max_usage_offset, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, NULL, SM_Table::num_choices, SM_Table::slot_choice, SM_Table::slot_options, SM_add_ids_to_entries(), SM_Mdes::table_array, SM_Mdes::table_array_size, and SM_Mdes::time_shift.
Referenced by SM_build_mdes().
void SM_build_templates (SM_Mdes * sm_mdes)
Definition at line 885 of file sm_mdes.c.
References I_punt(), SM_Syllable::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_Template::name, NULL, SM_Syllable::num_slots, SM_Mdes::num_templates, SM_Mdes::slots_per_template, SM_add_ids_to_entries(), SM_Mdes::syllable_array, SM_Mdes::template_array, SM_Mdes::template_shift_var, and SM_Mdes::top_syllable.
Referenced by SM_build_mdes().
void SM_build_tgroups (SM_Mdes * sm_mdes)
Definition at line 1034 of file sm_mdes.c.
References I_punt(), SM_TGroup::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, SM_TGroup::name, NULL, SM_Mdes::num_tgroups, SM_add_ids_to_entries(), SM_Mdes::template_array, and SM_Mdes::tgroup_array.
Referenced by SM_build_mdes().
void SM_build_units (SM_Mdes * sm_mdes)
Definition at line 197 of file sm_mdes.c.
References SM_Option::first_usage, I_punt(), SM_Option::last_usage, SM_Usage::map_offset, SM_Resource::mask, MD_Field::max_element_index, MD_find_field, MD_find_field_decl, MD_find_section, MD_first_entry(), MD_get_int, MD_get_link, SM_Mdes::md_mdes, MD_next_entry(), MD_Entry::name, NULL, SM_Resource::offset, SM_Mdes::resource, SM_Usage::resources_used, SM_add_ids_to_entries(), SM_Mdes::time_shift, SM_Mdes::unit_array, and SM_Mdes::unit_array_size.
Referenced by SM_build_mdes().
Variable Documentation
L_Alloc_Pool* SM_Mdes_pool = NULL [static]
Definition at line 68 of file sm_mdes.c.
Referenced by SM_build_mdes().